### PR TITLE
Add donkey project

### PR DESCRIPTION
**Pull request by donkeyfund-jijay**
##### List of audit links if any: 
Suho(https://docs.donkey.fund/about/audit)

[[ENG]donkey-fund_Security_Assessment_4th.pdf](https://github.com/DefiLlama/DefiLlama-Adapters/files/7553350/ENG.donkey-fund_Security_Assessment_4th.pdf)

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

donkey-logo

##### Token address and ticker if any: 

Ethereum
- address : 0x4576E6825B462b6916D2a41E187626E9090A92c6
- ticker : DON

Klaytn
- 0x5388ce775de8f7a69d17fd5caa9f7dbfee65dfce
- ticker : kDON

### CODE REVIEW

**Comment by waynebruce0x** [comment]
110,700,172,825,165 USD TVL sounds like a lot - is this right? Can you talk me through your method? Are borrowed funds included?

**Comment by donkeyfund-jijay** [comment]
> 110,700,172,825,165 USD TVL sounds like a lot - is this right? Can you talk me through your method? Are borrowed funds included?

Hi, there was a mistake calculating tvl in $ using current currency. I fixed it to 81814857 $. sorry for confusion 

And about the method, you're right. Borrowed funds are included in tvl.

**Comment by waynebruce0x** [comment]
For money market projects we don't count borrowed funds, just the liquidity actually held in the contracts. Is there any way you can subtract the borrowed amount?

**Comment by donkeyfund-jijay** [comment]
> For money market projects we don't count borrowed funds, just the liquidity actually held in the contracts. Is there any way you can subtract the borrowed amount?

@waynebruce0x 
yeah, of course. I'll update to the way you mentioned.

**Comment by donkeyfund-jijay** [comment]
@waynebruce0x 
I updated the code so that tvl is calculated using real balance of smart contract

**Pull request merged**
