### PR TITLE
Add Mozaic Adapter

### PR DESCRIPTION
**Pull request by Smile1017**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/mozaic exports TVL: 
        
 
 
    bsc                       616.3149320177544
    avax                      39.080768
    arbitrum                  1.63 k
    kava                      4.00 k
    fantom                    721.203743606216
    polygon                   64.71159997699999
    
    total                    7.07 k

**Comment by Define101** [comment]
Please provide website and twitter link @Smile1017

**Comment by llamatester** [comment]
The adapter at projects/mozaic exports TVL: 
        
 
 
    bsc                       616.2287119183119
    avax                      39.071261131674
    polygon                   112.691272046905
    arbitrum                  1.04 k
    fantom                    709.6829646784159
    kava                      4.00 k
    
    total                    6.51 k

**Review by g1nt0ki — APPROVED** [review]
thanks for the PR

**Pull request merged**
