### PR TITLE
feat: yield bearing assets for rings

### PR DESCRIPTION
**Pull request by 0xtekgrinder**
add yield bearing assets to rings adapter

### CODE REVIEW

**Comment by llamabutler** [comment]
The adapter at projects/rings exports TVL: 
        
 
 
    ethereum                  2.32 M
    sonic                     158.02 k
    
    total                    2.48 M

**Comment by llamabutler** [comment]
The adapter at projects/rings exports TVL: 
        
 
 
    ethereum                  2.32 M
    sonic                     159.73 k
    
    total                    2.48 M

**Comment by 0xtekgrinder** [comment]
It looks like weth on sonic price is missing

**Comment by waynebruce0x** [comment]
> It looks like weth on sonic price is missing

what is the address for this token?

**Comment by 0xtekgrinder** [comment]
> > It looks like weth on sonic price is missing
> 
> what is the address for this token?

The address is: 0x50c42dEAcD8Fc9773493ED674b675bE577f2634b

**Comment by llamabutler** [comment]
The adapter at projects/rings exports TVL: 
        
 
 
    ethereum                  2.56 M
    sonic                     760.50 k
    
    total                    3.32 M

**Comment by waynebruce0x** [comment]
WETH should now be added

**Pull request merged**
