### PR TITLE
add allchainbridge

### PR DESCRIPTION
**Pull request by Borishbc**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
SWFT

##### Twitter Link:
https://twitter.com/SWFTBridge

##### Website Link:
https://www.swft.pro/
https://defi.swft.pro/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://defi.swft.pro/img/swft.e7b0bd8e.png

##### Current TVL:
0

##### Chain:
kava

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
https://www.coingecko.com/en/coins/swftcoin

##### Short Description (to be shown on DefiLlama):
SWFT is a cross-chain swap   aggregator for DEX/CEX/NFT.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Bridge

##### methodology (what is being counted as tvl, how is tvl being calculated):
Assets staked in the pool and trading contracts

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@Borishbc thanks for the PR, but this feels a bit incomplete. I am seeing a lot of chains listed in your site, but the PR only has kava, and has 0 tvl. Can you please list the other chains as well, also sorry, but if there is no tvl, we cant list it.

**Comment by Borishbc** [comment]
Thank you, I have added other chains, and we have added the TVL of Kava chain.

**Comment by llamatester** [comment]
The adapter at projects/allchainbridge exports TVL: 
        
 
 
    polygon                   31.71 k
    bsc                       306.49 k
    fantom                    2.39 k
    ethereum                  91.55 k
    okexchain                 92.90 k
    heco                      138.01 k
    kava                      0
    
    total                    663.04 k

**Comment by Borishbc** [comment]
pls check again, kava we added the value

**Comment by Borishbc** [comment]
Is there anything else we need to add?

**Comment by llamatester** [comment]
The adapter at projects/allchainbridge exports TVL: 
        
 
 
    kava                      7.65
    ethereum                  108.62 k
    polygon                   44.95 k
    bsc                       275.43 k
    okexchain                 92.15 k
    fantom                    2.78 k
    heco                      168.13 k
    
    total                    692.06 k

**Pull request merged**
