### PR TITLE
Add Drops hallmarks

### PR DESCRIPTION
**Pull request by 0xmichalis**
Announcements:
* DAO launch: https://twitter.com/dropsnft/status/1521975077050400768
* DOP staking: https://twitter.com/dropsnft/status/1527782522804895745

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/drops: 
        
 
  
    
    
    Error: 
        Unknown chain(s): hallmarks
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file

**Comment by llamatester** [comment]
The adapter at projects/drops exports TVL: 
        
 
 
    ethereum-staking          67.02 k
    ethereum-pool2            110.71 k
    ethereum-borrowed         503.54 k
    ethereum                  1.61 M
    staking                   67.02 k
    pool2                     110.71 k
    borrowed                  503.54 k
    
    total                    1.61 M

**Comment by llamatester** [comment]
The adapter at projects/drops exports TVL: 
        
 
 
    ethereum-staking          67.02 k
    ethereum-pool2            110.71 k
    ethereum-borrowed         503.54 k
    ethereum                  1.61 M
    staking                   67.02 k
    pool2                     110.71 k
    borrowed                  503.54 k
    
    total                    1.61 M

**Comment by 0xmichalis** [comment]
@g1nt0ki is there any issue with merging exports? I still don't see the hallmarks in the Drops page.

https://defillama.com/protocol/drops

**Comment by g1nt0ki** [comment]
@0xmichalis yeah, it should be one level above, fixed it here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/60dc7999ca7b942aff9cfb0c98d5f58ca2e14a19

**Pull request merged**
