### PR TITLE
Add Proton-Loan TVL

### PR DESCRIPTION
**Pull request by jackymetal**
##### methodology (what is being counted as tvl, how is tvl being calculated): sum of all lending deposits in Proton Loan smart contract.

First project for Proton Chain (https://protonchain.com/): logo (https://assets.coingecko.com/coins/images/10941/small/Proton-Icon.png?1588283737)
Proton-Icon (2)

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Can you subtract borrowed funds from getLendingTvl(false) ? Also for the exports to be formatted correctly could you change them to:

module.exports = {
  methodology: `ProtonLoan TVL is sum of all lending deposits in Proton Loan smart contract.`,
  proton: {
    fetch: getLendingTvl(false),
  },
    borrowed: {
    fetch: getLendingTvl(true)
  },
  fetch: getLendingTvl(false)
}

**Comment by jafri** [comment]
@waynebruce0x 

1. `getLendingTvl` already excludes borrowed funds, `tvl` and `borrowed` are exclusive
2. Should root level `fetch` be TVL + staking?

**Comment by jackymetal** [comment]
> Can you subtract borrowed funds from getLendingTvl(false) ? Also for the exports to be formatted correctly could you change them to:
> 
> module.exports = { methodology: `ProtonLoan TVL is sum of all lending deposits in Proton Loan smart contract.`, proton: { fetch: getLendingTvl(false), }, borrowed: { fetch: getLendingTvl(true) }, fetch: getLendingTvl(false) }

@waynebruce0x I made the updates. please review.

1. subtract borrowed
2. updated exports

**Comment by realdealshaman** [comment]
@jackymetal Hello, I would like to ask you, what programming language do you use for Proton Blockchain? It's for a new section in Defillama where we are tracking the programming languages used in the crypto space :)

**Comment by jafri** [comment]
@realdealshaman Primarily C++

**Comment by realdealshaman** [comment]
Awesome! Many thanks

**Pull request merged**
