### PR TITLE
Update KlimaDAO TVL adapter

### PR DESCRIPTION
**Pull request by ChazSchmidt**
This PR transfers the TVL of BCT from Toucan Protocol to KlimaDAO - adding a check for the block height of transfer.

Additionally, some missing treasury assets were added to KlimaDAO's treasury asset count.

Context:
KlimaDAO votes to acquire BCT from Toucan Protocol https://snapshot.org/#/klimadao.eth/proposal/0xcef69824ff641a9a0951e6de77e2eda724efb335372e98f72e2f7d40fc3fb01b
Toucan Protocol transferred ownership of the BCT carbon pool contract to KlimaDAO https://polygonscan.com/tx/0x15904a9be05d8a22f393838ed28abd3706bbfc86a4166297a4dd7d93521bdacf

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/klima-dao exports TVL: 
        
 
 
    polygon                   26.89 M
    polygon-staking           26.86 M
    polygon-treasury          37.03 M
    staking                   26.86 M
    treasury                  37.03 M
    
    total                    26.89 M

**Comment by llamatester** [comment]
The adapter at projects/toucan-protocol exports TVL: 
        
 
 
    regen                     172.79 k
    celo                      303.51 k
    polygon                   1.51 M
    
    total                    1.99 M

**Comment by g1nt0ki** [comment]
@ChazSchmidt thanks for the PR

**Comment by llamatester** [comment]
The adapter at projects/klima-dao exports TVL: 
        
 
 
    polygon-staking           20.25 M
    polygon                   19.73 M
    staking                   20.25 M
    
    total                    19.73 M

**Comment by llamatester** [comment]
The adapter at projects/toucan-protocol exports TVL: 
        
 
 
    celo                      297.06 k
    polygon                   1.53 M
    regen                     172.16 k
    
    total                    1.99 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/klima-dao.js exports TVL: 
        
 
 
    polygon-ownTokens         2.65 M
    polygon                   25.81 M
    ownTokens                 2.65 M
    
    total                    25.81 M

**Pull request merged**
