### PR TITLE
secretswap

### PR DESCRIPTION
**Pull request by scrtisland**

### CODE REVIEW

**Comment by 0xngmi** [comment]
Listed: https://defillama.com/protocol/secretswap

**Comment by scrtisland** [comment]
Thanks @0xngmi . Can we add the token please? (below)

"id":"sefi","symbol":"sefi","name":"SEFI"

Coingecko ID (so your TVL can appear on Coingecko): sefi


Coinmarketcap ID (so your TVL can appear on Coinmarketcap): 9123


Description/bio (to be shown on DefiLlama): SecretSwap is the first front-running resistant, cross-chain and privacy-first AMM - secured by Secret Network.

Token address and ticker if any: 0x773258b03c730f84af10dfcb1bfaa7487558b8ac

**Comment by 0xngmi** [comment]
Done, I didn't see the token on the PR so I assumed it had no token, my bad.

**Comment by 0xngmi** [comment]
A day ago the tvl dropped heavily. Is this a real drop or is the api wrong?

**Comment by 0xngmi** [comment]
the api has stopped working, could you check on it and change the code to use the new api? I've looked at the requests made from the site and it seems to get the data from http://secretanalytics.xyz/_dash-update-component

I haven't updated the adapter because that api doesn't seem to be stable

**Comment by pmuecke** [comment]
> the api has stopped working, could you check on it and change the code to use the new api? I've looked at the requests made from the site and it seems to get the data from http://secretanalytics.xyz/_dash-update-component
> 
> I haven't updated the adapter because that api doesn't seem to be stable

Hi, thank you for your message. We are upgrading the chain tomorrow so there is some work ongoing on the api in anticipation of that. Should be back up again soon though. It might be stale temporarily tomorrow while upgrading.

**Pull request merged**
