### PR TITLE
Updated ascent-v3 to include vault tvl data

### PR DESCRIPTION
**Pull request by surfacing8671**
I updated the tvl calculation for Ascent-v3 to include the ichi vaults.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/ascentexchange-v3 exports TVL: 
        
 
 
    eon                       1.31 M
    
    total                    1.31 M

**Comment by g1nt0ki** [comment]
hi @surfacing8671 we are already counting ichi vaults as ichi tvl, on top of that, this would be doublecounting as value in pools is already counted as part of dex tvl?

**Comment by surfacing8671** [comment]
hey yes i was worried about that. so it is interesting because the way the vaults work is that they deploy to ascent lp only when market is moving. so actually you are already double counting that tvl. What is deployed on the ichi vaults are not necessarily deployed to ascent... yet. so this then brings up an interesting scenarios. Maybe we look at the vaults and get tvl from what the vault reports back as being deployed assets and then figure out the difference or something. but in the end maybe we should look at how the vaults are accessed by the user. and that in the end is through the ascent domain only. and not on the ichi site. So users are depositing through Ascent. but isnt directly put into our liquidity till the vault says so. Idk its an interesting situation that maybe needs a new category all together because i do see this kind of solution becoming more popular.

**Comment by g1nt0ki** [comment]
dont think we need a new category:

Ichi tvl: tokens in vault + tokens deployed to dex (marked as doublecounted)
ascent tvl: tokens in all the LPs

**Pull request closed without merging**
