### PR TITLE
Add BNB to Kava Boost

### PR DESCRIPTION
**Pull request by adamrturman**
**NOTE**

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by adamrturman** [comment]
Confirming that this is the correct listing for BNB (Binance Coin). I was unable to confirm by running `node test projects/kava-boost/index.js` which gave an output of 

```
  blocks: { getCurrentBlocks },
            
TypeError: Cannot read properties of undefined (reading 'getCurrentBlocks')
```

**Comment by g1nt0ki** [comment]
@adamrturman hi, I recently updated the sdk version, running `npm i` should fix the issue

**Comment by llamatester** [comment]
The adapter at projects/kava-boost exports TVL: 
        
 
 
    kava                      2.27 M
    
    total                    2.27 M

**Comment by adamrturman** [comment]
> @adamrturman hi, I recently updated the sdk version, running `npm i` should fix the issue

Thank you very much @g1nt0ki ✅

**Pull request merged**
