### PR TITLE
cryptoblades adapter

### PR DESCRIPTION
**Pull request by kcper**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

##### Twitter Link:
https://twitter.com/CryptoBlades

##### List of audit links if any:
None

##### Website Link:
https://www.cryptoblades.io/

##### Current TVL:
$295k
##### Chain:
BSC, HECO, OEC, POLYGON, AVAX, AURORA, SKALE, KAVA

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
cryptoblades

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
9654

##### Short Description (to be shown on DefiLlama):
CryptoBlades is a play-to-earn NFT RPG developed by Riveted Games. The game revolves around the acquisition of legendary Blades and the powerful Heroes who wield them. Players may participate in combat using their assets to earn SKILL tokens.  Assets are player-owned NFTs minted to the ERC-721 standard, and may be traded on the proprietary marketplace. CryptoBlades utilizes a play-to-earn model by distributing SKILL through gameplay, and giving value to player NFTs by increasing their use through future features.

##### Token address and ticker if any:
BSC: 0x154a9f9cbd3449ad22fdae23044319d6ef2a1fab
HECO: 0x27d4DfDB3fDf58e198bA4dbc23B2F82c0b8e3405
OEC: 0xcC137b0713E0DC63b1fA136272014F2A54Dd7aCB
POLYGON: 0x863D6074aFaF02D9D41A5f8Ea83278DF7089aA86
AVAX: 0x483416eB3aFA601B9C6385f63CeC0C82B6aBf1fb
AURORA: 0xE723111a6Ac865EB6E2d62e87432bdC6e2c4a86E
SKALE: 0x5F6E97612482095C0c2C02BC495C0171e61017d7
KAVA: 0xC28a73FCb6248Cb1718A50a9EC9cBC361dee3ea1

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Gaming

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
None, we're using our own oracle

##### forkedFrom (Does your project originate from another project):
None

##### methodology (what is being counted as tvl, how is tvl being calculated):
Counts the number of tokens locked in staking contracts, treasury contract that rewards are being claimed from constantly and game contract (ownTokens) which accumulates funds spent by players in game.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/cryptoblades exports TVL: 
        
 
 
    bsc                       0
    heco                      0
    okexchain                 0
    polygon                   0
    avax                      0
    aurora                    0
    kava                      0
    kava-staking              0
    aurora-staking            0
    avax-staking              12.686708882666546
    bsc-staking               239.88 k
    okexchain-staking         26.261343298522597
    heco-staking              197.20139187424405
    polygon-staking           30.219437611051948
    staking                   240.15 k
    
    total                    0

**Comment by g1nt0ki** [comment]
@kcper thanks for the PR, sorry, i have refactored yur code a bit. We can count only non native tokens in treasury, not sure game coffers can be counted since it is one directional right ? Users can never get back those tokens?
Staking is not counted as part of tvl but seperately: https://docs.llama.fi/list-your-project/what-to-include-as-tvl 

If you are fine with the changes, I can merge and list it.

**Comment by kcper** [comment]
> @kcper thanks for the PR, sorry, i have refactored yur code a bit. We can count only non native tokens in treasury, not sure game coffers can be counted since it is one directional right ? Users can never get back those tokens? Staking is not counted as part of tvl but seperately: https://docs.llama.fi/list-your-project/what-to-include-as-tvl
> 
> If you are fine with the changes, I can merge and list it.

Ok got it. Tokens in game coffer are used to refill reward pools, we manage it, not the users, but for the time being in the coffer they are 'locked'. I'm not sure if we should count it or not, you probably know better where to draw the line here. Other than that I'm fine with the changes, thanks.

**Comment by g1nt0ki** [comment]
sorry, if it is one way, then we dont count.

**Pull request merged**
