### PR TITLE
fix: adding v3 tvl

### PR DESCRIPTION
**Pull request by jeffywu**
Adding Notional V3 TVL metrics on Arbitrum. V2 TVL is unchanged on mainnet.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/notional exports TVL: 
        
 
 
    ethereum                  25.48 M
    arbitrum                  1.43 M
    
    total                    26.90 M

**Comment by g1nt0ki** [comment]
thanks @jeffywu 
would you prefer a new listing for v3?

**Comment by jeffywu** [comment]
Sure, will it look something like this:
image

**Comment by g1nt0ki** [comment]
yup, exactly like that. can I split it?

**Comment by g1nt0ki** [comment]
merged it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/8069

again, thanks for the PR

**Pull request closed without merging**
