### PR TITLE
Adapter for ABcDeFX

### PR DESCRIPTION
**Pull request by ftm1337**
**NOTE**

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
ABcDeFX

##### Twitter Link:
https://twitter.com/ftm1337

##### List of audit links if any:
None

##### Website Link:
https://abcdefx.eliteness.network

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://ftm.guru/icons/abcdefx_sq.png
https://ftm.guru/icons/abcdefx_sq.svg

##### Current TVL:
10-20k

##### Chain:
Fantom, KCC, Echelon, MultiVAC

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
None

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
None

##### Short Description (to be shown on DefiLlama):
ABcDeFx is **A** **B**lock**C**hain-**D**ecentralized **E**xchange & **F**ore**x**. ABcDeFX is a Multi-Chain StableSwap DEX & Forex Market.

##### Token address and ticker if any:
No Tokens

##### Category (full list at https://defillama.com/categories) *Please choose only one:
DEX

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Flash-proof TWAP

##### forkedFrom (Does your project originate from another project):
Solidly > Uniswap

##### methodology (what is being counted as tvl, how is tvl being calculated):
Using DefiLlama's SDK for making on-chain calls to ABcDeFX Factory Contract to iterate over Liquidity Pools & count token balances therein.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/ABCDEFX exports TVL: 
        
 
 
    fantom                    6.81 k
    multivac                  0
    echelon                   0
    kcc                       704.346
    
    total                    7.51 k

**Comment by ftm1337** [comment]
:thinking: Something looks off.. 
MultiVAC TVL should be $813 (469.5 USDC + 343.5 USDT)
> https://mtvscout.com/address/0x0A560176d62D69670060d7cBe43C371eDbD4F9A2/tokens#address-tabs
Echelon TVL should be $10750 (1.625M of WECH + 1.645M of SWECH)
> https://dexscreener.com/echelon/0x42fba9c02d5f3dc5596fd77f54c91812403a9d62
KCC & Fantom numbers are correct.

**Comment by llamatester** [comment]
The adapter at projects/ABCDEFX exports TVL: 
        
 
 
    fantom                    6.81 k
    kcc                       704.9490000000001
    multivac                  813.4689999999999
    echelon                   0
    
    total                    8.33 k

**Comment by g1nt0ki** [comment]
> 

sorry, we use coingecko for pricing tokens and it has rugged echelon: https://www.coingecko.com/en/coins/echelon

**Pull request merged**
