### PR TITLE
feat: separate the lending part to new adapter

### PR DESCRIPTION
**Pull request by singlefinance**
We are moving the lending vault TVL calculation to a new adapter

**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/single exports TVL: 
        
 
 
    arbitrum-staking          0
    fantom-staking            0
    fantom-pool2              0
    fantom                    12.31 k
    arbitrum-pool2            0
    arbitrum                  82.73 k
    cronos                    3.59 M
    staking                   0
    pool2                     0
    
    total                    3.69 M

**Comment by llamatester** [comment]
The adapter at projects/singlefinance-lend exports TVL: 
        
 
 
    arbitrum                  98.04 k
    fantom                    69.10 k
    arbitrum-borrowed         49.51 k
    fantom-borrowed           8.29 k
    cronos                    1.43 M
    cronos-borrowed           1.84 M
    borrowed                  1.89 M
    
    total                    1.60 M

**Comment by g1nt0ki** [comment]
@singlefinance Sorry, dont think I can merge this. The borrowing is within the protocol to yield farm right? similar to Gearbox in ethereum and Kleva in Klaytn? we dont split the listing there

**Comment by singlefinance** [comment]
@g1nt0ki 
Yes, the borrowing is within the protocol to yield farm. We have taken reference to Alpaca Finance and Kleva who are using separated adapters.
The whole protocol structure and function of Single FInance are similar to that of Alpaca Finance and Kleva. Our code is similar to these two protocols, may you please advice if there is anything needs to be changed

**Comment by g1nt0ki** [comment]
hi @singlefinance you are right, I will fix kleva and Alpaca soon, for leveraged farming, it should be merged together

**Comment by g1nt0ki** [comment]
hi @singlefinance I am closing this PR, I have fixed Alpaca & Kleva as well, let me know if you find this issue somewhere else as well

**Pull request closed without merging**
