### PR TITLE
Add Hashstack on Starknet

### PR DESCRIPTION
**Pull request by Sahitya777**
Name (to be shown on DefiLlama): 
Hashstack
Twitter Link: 
https://twitter.com/0xhashstack
List of audit links if any: 
N/A
Website Link: 
https://hashstack.finance/
Logo (High resolution, will be shown with rounded borders): 
https://svgshare.com/i/10f7.svg
Current TVL: 
$255 K
Treasury Addresses (if the protocol has treasury): 
N/A
Chain: 
Starknet
Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): 
N/A
Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): 
N/A
Short Description (to be shown on DefiLlama): 
Yield farm on Starknet through Hashstack's permissionless under-collateralised loans.
Token address and ticker if any: 
N/A
Category (full list at https://defillama.com/categories) *Please choose only one: 
Lending
Oracle used (Chainlink/Band/API3/TWAP or any other that you are using): 
Pragma Oracle
forkedFrom (Does your project originate from another project): 
N/A
methodology (what is being counted as tvl, how is tvl being calculated): 
User deposits are calculated as TVL.
Github org/user (Optional, if your code is open source, we can track activity): 
https://github.com/0xHashstack

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/hashstack exports TVL: 
        
 
 
    starknet                  252.66 k
    starknet-borrowed         169.88 k
    borrowed                  169.88 k
    
    total                    252.66 k

**Comment by web3Gurung** [comment]
Hey team, can we please list Hashstack on the airdrop page at defillama.com/airdrops?

We're currently running an airdrop campaign for Hashstack which can be seen here: x.com/0xHashstack/status/1734066325692243975

If this isn't the appropriate channel, please let me know whom to approach. Thank you :)

**Comment by g1nt0ki** [comment]
hi @Sahitya777 thanks for the PR, merged your code here with a minor fix, we dont included borrowed tokens as part of tvl: https://github.com/DefiLlama/DefiLlama-Adapters/pull/8362

regarding airdrop page, all protocols without tokens automatically show up there.

**Comment by web3Gurung** [comment]
Got it! thank you so much for the info @g1nt0ki, appreciate for the swift response :D

**Comment by web3Gurung** [comment]
Hey @g1nt0ki, can we have the borrowed amount be a part of the TVL?

In our project, the borrowed asset does not leave the protocol and cannot enter the user's wallet. As a result, the liquidity remains within Hashstack, and we include it when calculating the TVL.

**Comment by g1nt0ki** [comment]
> Hey @g1nt0ki, can we have the borrowed amount be a part of the TVL?
> 
> In our project, the borrowed asset does not leave the protocol and cannot enter the user's wallet. As a result, the liquidity remains within Hashstack, and we include it when calculating the TVL.

if the borrowed tokens dont go to users wallets, where do they go? can you share the contract details, we can include token value in those contracts

**Pull request closed without merging**
