### PR TITLE
Update Juice Finance

### PR DESCRIPTION
**Pull request by hoomp3**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/juice-finance exports TVL: 
        
 
 
    blast                     36.13 M
    
    total                    36.13 M

**Comment by hoomp3** [comment]
One of our vaults holds Thruster LP. Not sure how to price it.

**Comment by llamatester** [comment]
The adapter at projects/juice-finance exports TVL: 
        
 
 
    blast                     42.70 M
    
    total                    42.70 M

**Comment by g1nt0ki** [comment]
> One of our vaults holds Thruster LP. Not sure how to price it.

@hoomp3 thanks for the PR, the v2 LPs are unwound now.

**Pull request merged**
