### PR TITLE
PERI Finance - update contract addresses of existing chains and add 3 additional chains to TVL

### PR DESCRIPTION
**Pull request by richard-nend**
Changes

1. Updated contract addresses of existing networks such as Ethereum, BSC, and Polygon.
2. Added 3 additional networks to TVL including Base, Moonbeam, and Moonriver.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/perifinance exports TVL: 
        
 
 
    polygon                   2.93 M
    bsc                       846.26 k
    base                      566.20 k
    moonbeam                  157.19 k
    ethereum                  75.93 k
    moonriver                 4.68 k
    
    total                    4.58 M

**Comment by g1nt0ki** [comment]
@richard-nend thanks for the PR, I have refactored it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/11607

but it is not very clear to me, how is pUSD minted and why are we taking 4 * supply as tvl

**Comment by richard-nend** [comment]
That's because pUSD is minted as 25% of the staked PERI value, meaning the value of minted pUSD is one-fourth of the value of staked PERI.

**Comment by g1nt0ki** [comment]
but I dont see PERI tokens locked (by users) on ethereum in any contract, also, if the minted value is 1/4th of PERI why are we not pricing it in PERI but instead in USD?

**Comment by richard-nend** [comment]
PERI tokens are locked in the user's wallet, not in the contract. Since 1/4 of USD value in PERI is minted as pUSD, we should price it in USD.

**Comment by g1nt0ki** [comment]
the project has mcap of 3.8m on polygon, and you are claiming users have locked 2.93M of that? for example, this address has 1.6m worth tokens but has never interacted with any smart contract ever https://polygonscan.com/token/0xdc0e17eae3b9651875030244b971fa0223a1764f?a=0xc882b111a75c0c657fc507c04fbfcd2cc984f071

**Comment by richard-nend** [comment]
The total supply on each connected network works differently in PERI tokens.  The total supply means the issued supply on each chain. Since we have a proprietary Bridge in place, the tokens are moved around the chains. By looking at the top 5 holders on Polygon, you can easily see the sum of tokens held by the top 5 holders surpasses the total supply. So, more than half of the tokens issued on Ethereum are now on Polygon.  What's the issue here? We haven't updated DefiLlama's TVL script for quite a long time while updating the smart contracts on Ethereum, BSC, and Polygon. which may raise some questions. I understand. But, the logic is as it has been. All I updated were the contract addresses and added 3 more chains.

**Comment by g1nt0ki** [comment]
hi @richard-nend the issue is, it is not very clear to me where the locking is happening/what is counted as tvl. 

how does the protocol work? if users are locking in their own wallet, can they get slashed if pUSD depegs? I keep seeing this inflationMint but dont understand what it does. 

Yes, you are already listed, but if methodology is wrong, we need to correct it regardless.

**Review by Reallyfe — APPROVED** [review]

**Comment by g1nt0ki** [comment]
sorry, we are delisting Peri finance till we clear up the methodolody of computing tvl.

**Pull request closed without merging**
