### PR TITLE
Adapter for CoinCollect

### PR DESCRIPTION
**Pull request by r0b0roach**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
CoinCollect

##### Twitter Link:
https://twitter.com/CoinCollectOrg

##### Website Link:
https://coincollect.org/

##### Logo (High resolution, will be shown with rounded borders):
https://pbs.twimg.com/profile_images/1640425534579458072/DzXEp-zv_400x400.jpg

##### Current TVL:
$70K

##### Chain:
Polygon

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
ID: 25956

##### Short Description (to be shown on DefiLlama):
Earn Passive Income through NFTs

##### Token address and ticker if any:
0x56633733fc8BAf9f730AD2b6b9956Ae22c6d4148
COLLECT

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Launchpad

##### forkedFrom (Does your project originate from another project):
PancakeSwap

##### methodology (what is being counted as tvl, how is tvl being calculated):
We count liquidity on the pairs and Collect staking pools.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/Coin-Collect/coincollect-frontend

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/coincollect exports TVL: 
        
 
 
    polygon-staking           0
    polygon                   30.15 k
    staking                   0
    
    total                    30.15 k

**Comment by llamatester** [comment]
The adapter at projects/coincollect exports TVL: 
        
 
 
    polygon-staking           0
    polygon                   30.09 k
    staking                   0
    
    total                    30.09 k

**Comment by r0b0roach** [comment]
> The adapter at projects/coincollect exports TVL:
> 
> ```
> polygon-staking           0
> polygon                   30.09 k
> staking                   0
> 
> total                    30.09 k 
> ```

It seems like a problem that the staking amount is coming as 0.

**Comment by g1nt0ki** [comment]
> > The adapter at projects/coincollect exports TVL:
> > ```
> > polygon-staking           0
> > polygon                   30.09 k
> > staking                   0
> > 
> > total                    30.09 k 
> > ```
> 
> It seems like a problem that the staking amount is coming as 0.

can you share an LP with enough tvl, I can use it to price the staking token

**Comment by r0b0roach** [comment]
> > > The adapter at projects/coincollect exports TVL:
> > > ```
> > > polygon-staking           0
> > > polygon                   30.09 k
> > > staking                   0
> > > 
> > > total                    30.09 k 
> > > ```
> > 
> > 
> > It seems like a problem that the staking amount is coming as 0.
> 
> can you share an LP with enough tvl, I can use it to price the staking token

COLLECT / USDT LP: 0x0cCc84b6506003487AEC687085e82C2f912E607B

**Comment by r0b0roach** [comment]
@g1nt0ki 
It seems like there is a problem with the stake calculation. In the Stake Pool (0x46A928F2386b8c38cdde028a32c5b7aa19F40445), there is about $70K worth of collect. However, the adapter is calculating a total of $30K.

**Pull request merged**
