### PR TITLE
add autobark

### PR DESCRIPTION
**Pull request by g1nt0ki**
##### Twitter Link:
https://twitter.com/AutoBarkYield

##### List of audit links if any:
Coming soon

##### Website Link:
http://www.autobark.lol

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://pbs.twimg.com/profile_images/1560448776556273666/48GIp-xk_400x400.jpg

##### Current TVL:
$109,750

##### Chain:
DogeChain

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

##### Short Description (to be shown on DefiLlama):
AutoBark is a Decentralized, Yield Optimizer on DogeChain that allows its users to earn compound interest on their crypto holdings. AutoBark earns you the highest APYs with safety and efficiency in mind.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
N/A

##### forkedFrom (Does your project originate from another project):
Beefy

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/autobark exports TVL: 
        
 
 
    dogechain                 100.84 k
    
    total                    100.84 k

**Comment by autobark** [comment]
This looks great, thank you!

We have updated the public repo, please let me know if there's anything else you need.

**Comment by autobark** [comment]
Ah, we see that this actually references an outdated url for the vault list. We made the proper changes here:

https://github.com/DefiLlama/DefiLlama-Adapters/pull/3689

Thanks again!

**Comment by autobark** [comment]
Thanks for the merge team!

I see we ended up listed under the Yield category, can we have that changed to Yield Aggregator?

**Comment by g1nt0ki** [comment]
we have fixed it

**Pull request merged**
