### PR TITLE
Add ABC Pool adapter

### PR DESCRIPTION
**Pull request by 0xCaso**
**NOTE**

> 2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.

I discussed it in the discord, and this seems the best way to do it (it's not the Conflux EVM chain)

> 4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR

---
##### Name (to be shown on DefiLlama):
ABC PoS Pool

##### Twitter Link: 
https://twitter.com/ABCpospool

##### Website Link: 
https://confluxpos.cn/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

abc

##### Current TVL: 
16.84M USD (39.86M CFX)

##### Chain: 
Conflux Core Space

##### Short Description (to be shown on DefiLlama):
ABC PoS Pool is a staking solution that allows users to participate in PoS safely and pledge CFX without loss to obtain CFX+ABC reward.

##### Token address and ticker if any: 
Conflux Core Space: cfx:acb78besxg2tnxs1ccca45g2fm412mdpr6b0ve6wtc
Conflux eSpace: 0x905f2202003453006eaf975699545f2e909079b8
Ticker: $ABC

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Staking

##### methodology (what is being counted as tvl, how is tvl being calculated):
Calls poolSummary() in the proxy contract. The result is multiplied by 1000, as you can stake minimum 1000 CFX.

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@0xCaso sorry, dont thnk we can list this project. Main criteria for liquid staking is a liquid staked token like stETH by Lido for ETH

**Comment by 0xCaso** [comment]
@g1nt0ki ok, actually it's a competitor of Nucleon: https://defillama.com/protocol/nucleon (which is already listed)

**Comment by g1nt0ki** [comment]
hi @0xCaso , in nucleon's case, there is xCFX which is their liquidt token, do you have something similar

**Comment by 0xCaso** [comment]
> hi @0xCaso , in nucleon's case, there is xCFX which is their liquidt token, do you have something similar?

After talking with the dev, actually the protocol is just categorized as Staking and not Liquid Staking. I edited the description, sorry and thanks for noticing!

**Comment by g1nt0ki** [comment]
@0xCaso I am delaying a bit with the PR as we currently do not track chain staking, only liquid staking as it can be used as building block of other defi protocols, but I understand that it is good to track all projects in the chain, right now, fixing something in our server to not include these in chain tvl and have a separate dashboard for this like CEX page, will keep this PR open till that is fixed.

**Comment by Lin598** [comment]
@g1nt0ki Thanks for the effort to list the project! It seems the contract addresses are not being  correctly displayed. If only one contract address could be displayed, can conflux espace address start with 0x be used instead? Now it shows conflux core address missing "cfx:" at the front though. Thanks!

**Comment by Define101** [comment]
Hello Lin598, yes only 1 address.
We will use the 0x, we have made the changes and should reflect within 2 hours

**Pull request merged**
