### PR TITLE
Creation of Firoza Finance Adapter

### PR DESCRIPTION
**Pull request by xenothanhojem**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Short Description (to be shown on DefiLlama): 

Liberty finance and HAQQ network have jointly created Firoza Finance, to enable investment in pools to generate a range of returns with varying risk.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/stride exports TVL: 
        
 
 
    cosmos                    24.03 M
    dydx                      23.29 M
    celestia                  8.69 M
    osmosis                   8.26 M
    islm                      5.69 M
    evmos                     778.88 k
    dymension                 719.88 k
    juno                      456.67 k
    injective                 395.76 k
    stargaze                  307.89 k
    terra2                    62.57 k
    sommelier                 46.44 k
    umee                      44.12 k
    comdex                    12.03 k
    stride                    0
    
    total                    72.79 M

**Comment by llamatester** [comment]
The adapter at projects/firoza-finance exports TVL: 
        
 
 
    islm                      0
    
    total                    0

**Comment by xenothanhojem** [comment]
> @xenothanhojem thanks for the PR, is the project live? and what is this address '0x0ce35b0d42608ca54eb7bcc8044f7087c18e7717' mock USDC?

I missed this.

Project is live, this address is native USDC on the HAQQ Network. https://explorer.haqq.network/token/0x0CE35b0D42608Ca54Eb7bcc8044f7087C18E7717

Confirmed Sushiswap pool here: https://www.sushi.com/swap?chainId=11235&token0=0x0CE35b0D42608Ca54Eb7bcc8044f7087C18E7717&token1=NATIVE

**Comment by xenothanhojem** [comment]
Please see above comments to reopen this PR

**Pull request closed without merging**
