### PR TITLE
Upgraded to automated TVL, added arbitrum GLP

### PR DESCRIPTION
**Pull request by babayega**
Hey, we have rebranded our protocol, the details are as follows. Please let me know if any other details are required.

---
##### Short Description (to be shown on DefiLlama):
Olive is a multi-chain protocol that combines composability with structured products to amplify yields without exposing users' funds to principal or credit risks.

$1.5 Million Seed Round: https://twitter.com/0xOlive/status/1460279998367952897

$3 Million Strategic Round: https://twitter.com/0xOlive/status/1547252819157458944

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/polysynth exports TVL: 
        
 
 
    polygon                   596.71 k
    ethereum                  2.67 M
    arbitrum                  118.47 k
    
    total                    3.38 M

**Comment by babayega** [comment]
Hey @g1nt0ki  we have also rebranded our protocol. Have already shared the details in the PR. Can you please update that as well. 

Our marketing campaign is going to go live tonight. Would be a great help if it is done before that.

**Comment by g1nt0ki** [comment]
@babayega it is updated now

**Comment by babayega** [comment]
Thank you @g1nt0ki

**Pull request merged**
