### PR TITLE
Add optimism to beethoven-x

### PR DESCRIPTION
**Pull request by franzns**
This is addition to the already present beethoven-x project. Do you need below info nevertheless?

Also switching to thegraph subgraphs since we plan to shut down our local one.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/beethovenx: 
        
 
  
    
    
    Failed to decode `block.number` value: `subgraph Qmdky7YefnbBCWXq4SimxiiZJThGBitbA4FRBn3exrdhtd has only indexed up to block number 39697207 and data for block number 39697414 is therefore not yet available`
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/graphql-request/dist/index.js:340:31

**Comment by llamatester** [comment]
The adapter at projects/beethovenx exports TVL: 
        
 
 
    fantom                    83.93 M
    optimism                  4.03 M
    
    total                    87.96 M

**Comment by waynebruce0x** [comment]
Is there any way we can collect this data using onchain calls instead? We get a lot of trouble from thegraph

**Comment by franzns** [comment]
Unfortunately we can't, since we can't source token prices from coingecko for the interest bearing tokens in our boosted pools.
We could use our backend but there would not be a way to get historical TVL. And that will take some time to implement as well.

**Comment by waynebruce0x** [comment]
Can we map the ib token addresses to their underlying tokens and use that? Can the conversion rate be foun with a function call?

**Comment by franzns** [comment]
What I could do is what we had before, that if we want TVL for the a current timestamp we can use our backend and if we need historical data, we use the subgraph. Could we merge this now and come up with another solution after? Any other solution will need quite some effort to implement.

**Pull request merged**
