### PR TITLE
feat: split steadefi lending tvl to its own adapter

### PR DESCRIPTION
**Pull request by 0x67**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Steadefi Lending

##### Twitter Link:
https://twitter.com/steadefi

##### List of audit links if any:
https://omniscia.io/reports/steadefi-staking-vaults-64031f72d11ef00014ba49e5/

##### Website Link:
https://steadefi.com

##### Logo (High resolution, will be shown with rounded borders):
https://icons.llama.fi/steadefi.jpg

##### Current TVL:
avax: $114,700
arbitrum: $36,360

##### Treasury Addresses (if the protocol has treasury)
https://snowtrace.io/address/0x7e7584f60561C39e4530c92cF75F484aDA493520
https://arbiscan.io/address/0x7e7584f60561C39e4530c92cF75F484aDA493520

##### Chain:
Arbitrum, Avalanche

##### Short Description (to be shown on DefiLlama):
For both DeFi novices and professional institutions alike, Steadefi Lending Vaults offer easy-to-use mechanics and highly-competitive utilization and yield rates.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is a sum of liquidity in lending pools deposited by users

##### reason for PR
We're currently listed on https://defillama.com/protocol/steadefi, however the current TVL is including lending and lyf. We want to split it so it shows up similar to alpaca https://defillama.com/protocol/alpaca-finance that have dedicated tabs for lending and lyf

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/steadefi exports TVL: 
        
 
 
    avax                      120.94 k
    arbitrum                  109.42 k
    
    total                    230.36 k

**Comment by llamatester** [comment]
The adapter at projects/steadefi-lending exports TVL: 
        
 
 
    avax                      114.80 k
    arbitrum                  36.40 k
    arbitrum-borrowed         71.97 k
    avax-borrowed             80.91 k
    borrowed                  152.88 k
    
    total                    151.21 k

**Comment by 0x67** [comment]
Is this the correct way to split the adapter so it shows up as dedicated tab in defillama? @llamatester

**Comment by g1nt0ki** [comment]
hi @0x67 I would say gearbox/vector are similar protocols and we dont split them as two like your PR. The reasoning behind this is, we view it as different parts of single protocol

**Comment by g1nt0ki** [comment]
sorry for not being clear, I meant you qualify for lending in the yield page, didnt mean you need to split protocol into two

**Pull request closed without merging**
