### PR TITLE
feat: add hashmix adapter

### PR DESCRIPTION
**Pull request by kylidboy**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)  
"id":"filecoin","symbol":"fil","name":"Filecoin"

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
"id":2280,"name":"Filecoin","symbol":"FIL",

##### Short Description (to be shown on DefiLlama):
HashMix FIL Liquid Staking Protocol is a decentralized staking protocol on Filecoin, connecting FIL holders and miners in the ecosystem. 

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Liquid staking

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/hashmix: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'usd')
    Truncated error stack:
    
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/hashmix/index.js:9:35)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)
        at async Promise.all (index 3)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by llamatester** [comment]
The adapter at projects/hashmix exports TVL: 
        
 
 
    filecoin                  0
    
    total                    0

**Comment by llamatester** [comment]
Error while running adapter at projects/hashmix: 
        
 
  
    
    
    Error: invalid BigNumber string (argument="value", value="2.0109551233525462957064e+22", code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    Truncated error stack:
        at BigNumber.from (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/bignumber/lib/bignumber.js:199:27)
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/hashmix/index.js:27:12)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
The adapter at projects/hashmix exports TVL: 
        
 
 
    filecoin                  0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/hashmix exports TVL: 
        
 
 
    filecoin                  97.73 k
    
    total                    97.73 k

**Comment by g1nt0ki** [comment]
@kylidboy thanks for the PR, I have merged it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/6423

**Pull request closed without merging**
