### PR TITLE
add wombat-exchange dexs

### PR DESCRIPTION
**Pull request by dtmkeng**
add yoshi-exchange dexs
```

Running WOMBAT-EXCHANGE adapter
----------
BSC
Start time: Invalid Date
Daily: 5434722.343530977927983389415437502
Total: 413650354.16359144
----------
```

### CODE REVIEW

**Comment by 0xngmi** [comment]
can you fix start time?

**Comment by 0xngmi** [comment]
just hardcode a value for when volume starts

async()=>2131232

like this

**Comment by 0xngmi** [comment]
will implement directly

**Comment by dtmkeng** [comment]
Can I help you fix it?

**Comment by dtmkeng** [comment]
ohh, you solved thank you

**Comment by 0xngmi** [comment]
yeah, was faster to fix it directly

**Pull request merged**
