### PR TITLE
added LiALEX TVL

### PR DESCRIPTION
**Pull request by fiftyeightandeight**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/lisa exports TVL: 
        
 
 
    stacks                    7.92 M
    
    total                    7.92 M

**Comment by g1nt0ki** [comment]
sorry, rejecting this as your project is linked to alex, we are already counting staked tokens there right? Can you help me refactoring alex dex code the compute tvl on chain? it seems to be way off.

**Comment by g1nt0ki** [comment]
@fiftyeightandeight I would still like to compute alex tvl on chain, can you help me with that. 

The reason we dont want to count liquid staked alex as part of lisa's tvl is, it is projects gov token and already counted as part of alex.

**Comment by fiftyeightandeight** [comment]
> @fiftyeightandeight I would still like to compute alex tvl on chain, can you help me with that.
> 
> The reason we dont want to count liquid staked alex as part of lisa's tvl is, it is projects gov token and already counted as part of alex.

Yes, we are planning to move the TVL computation to on-chain data, which we hope to complete in the next few weeks. In the meantime, we are fixing the current API to provide the correct feed, until the move is complete.

On your comment on liquid staked alex,  so no liquid staked governance token is currently counted as TVL, correct?

**Comment by g1nt0ki** [comment]
"so no liquid staked governance token is currently counted as TVL" yup

**Pull request closed without merging**
