### PR TITLE
wheat protocol

### PR DESCRIPTION
**Pull request by whale-guru-dev**
##### Twitter Link:
https://twitter.com/GrowthDefi

##### List of audit links if any:
https://api.growthdefi.com/tvl/wheat-tvl

##### Website Link:
https://wheat.growthdefi.com/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://wheat.growthdefi.com/images/wheat-logo-desktop-dark.png

##### Current TVL:
$8447633.16 USD

##### Chain:
Binance smart chain

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
wheat-token

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
wheat

##### Description/bio (to be shown on DefiLlama):
Growth DeFi is a decentralized ecosystem that focuses on capital efficiency and maximizing returns through a variety of products. The goal is to maximize token holder value and maintain the best yields & products in the market. The ecosystem is composed of three tokens: WHEAT: Inflationary to begin, becomes deflationary over time - makes high yield farming on BSC sustainable. gROOT: Deflationary, limited supply - managed, diversified treasury investing with revenue share. GRO: Deflationary, governance with staking rewards earns revenue from everything built

##### Token address and ticker if any:
0x3ab63309F85df5D4c3351ff8EACb87980E05Da4E
WHEAT

##### Category (Yield/Dexes/Lending/Minting):
Yield

##### [Optional] ETH addresss (to receive a LlamaPunk):
0x350571b512c9d5290364fbf2748d5f4fb399b459

### CODE REVIEW

**Comment by 0xngmi** [comment]
We already have growth DeFi listed, how does this compare to what we currently have?

**Comment by whale-guru-dev** [comment]
> We already have growth DeFi listed, how does this compare to what we currently have?

Growth Ecosystem has several projects inside. Gro is one of those. And this wheat is another project.
https://wheat.growthdefi.com/

**Comment by 0xngmi** [comment]
Got it, thanks for submitting

**Comment by 0xngmi** [comment]
I'm currently getting it up

**Comment by 0xngmi** [comment]
Sure

**Pull request merged**
