### PR TITLE
Adapter for Beeton token project had been added

### PR DESCRIPTION
**Pull request by BEETON-token**
Adapter for Beeton token project had been created and it had been added to the "beeton" folder project's list of the main repoitory of DefiLlama

**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Beeton

##### Twitter Link:
https://twitter.com/bee_ton16322

##### Website Link:
https://bee-ton.ru/

##### Logo (High resolution, will be shown with rounded borders):
https://i.ibb.co/jJM88k7/photo-1.png

##### Current TVL:
70.03k $

##### Treasury Addresses (if the protocol has treasury)
EQDq-_byppqRdbCXE4mS2PyfB8xHTIFOsOtAC7eHXoZSD_yy   - Main token wallet address: token and nft
EQDzgrTfX9IfH6rAQhAtOsSj4v1J3aTWbXKUNJQ_vBuRTlMQ   - Team's wallet address
EQC6rf-8eJNz5h5ZBTdeUNvHf83uqwnTqLBso35rBISa89v6   - Marketing's wallet address
EQDDOPI6bdv9rYbTNYRNAVMiBNLTpSsQvxsr5Z1NKgtr_Q3q   - Listing's wallet address
EQDNydVAcvL1dbk_sE6KTx5QRvDBgjG3OZycFA1yWCcyk8LS   - NFT's wallet address

##### Chain:
TON

##### Short Description (to be shown on DefiLlama):
People's token BEETON

##### Token address and ticker if any:
EQCRU1SC3xNf_r33q8NZzLughmvdE21JRYIZj4oRKUdRKRDb
$BEE

##### Category (full list at https://defillama.com/categories) *Please choose only one:
SoFi

##### methodology (what is being counted as tvl, how is tvl being calculated):
The actual size of the TON pool for the BEETON token on the DEX DeDust

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/BEETON-token

### CODE REVIEW

**Comment by g1nt0ki** [comment]
sorry, the value of tokens in the LP pool belong to the dex, not your protocol

**Comment by BEETON-token** [comment]
> sorry, the value of tokens in the LP pool belong to the dex, not your protocol

To meet the requirements for submitting a pull request, what actions are necessary? Is it not possible to hold liquidity on a DEX exchange? I need to migrate the information about the liquidity of a token from the DEX's API to an API, for example, Gecko Terminal https://api.geckoterminal.com/api/v2/networks/ton/pools/EQAsxDhDoKNCOJdwPKTXuyOutl9bUFJhnEDBSbxAiSUrfUuG (the token on Coingecko is currently unavailable)? I'm not quite sure what I need to do

**Comment by g1nt0ki** [comment]
@BEETON-token we list defi projects, so show tvl of your project, are users depositing tokens into contracts deployed as part of your app?

**Comment by BEETON-token** [comment]
> @BEETON-token we list defi projects, so show tvl of your project, are users depositing tokens into contracts deployed as part of your app?

1. Users provide liquidity to our pool in the TON/BEE pair, receiving a portion of the exchange fees from the DEX and receiving a $BEE token boost from us.
2. Funds from the sale of our NFT collections on getgems.io, excluding the Honey Haven BEE NFT Collection, go 100% into token liquidity (for the Honey Haven BEE NFT Collection, 30% goes into liquidity, and 70% is distributed among buyers of NFTs from this collection).
3. 100% of payments made by users for creating and minting NFTs in our Telegram bot @art_incubator_bot goes to $BEE liquidity pool.

**Comment by BEETON-token** [comment]
@g1nt0ki the TVL calculation method has been updated in accordance with the rules

**Comment by g1nt0ki** [comment]
I think you are confusing treasury with tvl: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Pull request closed without merging**
