### PR TITLE
Add elocks adapter

### PR DESCRIPTION
**Pull request by ftm1337**
#### This TVL should be marked as "Double-Count TVL"

---

##### Name (to be shown on DefiLlama):
eLOCKS

##### Twitter Link:
ftm1337

##### List of audit links if any:
none

##### Website Link:
eliteness.network/elocks

##### Logo (High resolution, will be shown with rounded borders):
https://ftm.guru/icons/1f510.svg

##### Current TVL:
$500k~

##### Treasury Addresses (if the protocol has treasury)
eliteness.eth

##### Chain:
Fantom

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
ftm-guru

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
13436

##### Short Description (to be shown on DefiLlama):
eLOCKS are Yield-Bearing Financial NFTs that Tokenize Liquidity Positions Staked-Locked in Gauges, Farms, Masterchefs or other DeFi instruments, separating Yield (multiple yielded tokens) from Principal (LP Tokens) to enable trading of Rights to Future Yields as well as Rights to unlock & own the locked Collateral, independently, while guaranteeing Locked Liquidity for Trading underlying Tokens contained in the LP.

##### Token address and ticker if any:
eLOCKS (NFT) : "fantom:0x2f20A659601d1c161A108E0725FEF31256a907ad"

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Services

##### forkedFrom (Does your project originate from another project):
OG Tech™

##### methodology (what is being counted as tvl, how is tvl being calculated):
Only the Locked LP tokens are counted in TVL. Includes Locked-Staked LPs and Locked-Unstaked LPs.

##### Github org/user (Optional, if your code is open source, we can track activity):
ftm1337, eliteness/elocks

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/elocks exports TVL: 
        
 
 
    fantom                    406.19 k
    
    total                    406.19 k

**Comment by llamatester** [comment]
The adapter at projects/elocks exports TVL: 
        
 
 
    fantom                    417.61 k
    
    total                    417.61 k

**Comment by llamatester** [comment]
The adapter at projects/elocks exports TVL: 
        
 
 
    fantom                    417.61 k
    
    total                    417.61 k

**Comment by llamatester** [comment]
The adapter at projects/elocks exports TVL: 
        
 
 
    fantom                    417.04 k
    
    total                    417.04 k

**Comment by g1nt0ki** [comment]
@ftm1337 thanks for the PR

**Comment by ftm1337** [comment]
thanks g1nt0ki for cleaning up the adapter!
didnt know about the `fetchList`. will keep these helper functions in mind next time : )

**Pull request merged**
