### PR TITLE
Add Henjindex adapter on Taiko

### PR DESCRIPTION
**Pull request by nekojitaxyz**
##### Name (to be shown on DefiLlama):
Henjin DEX

##### Twitter Link:
https://x.com/henjinDEX

##### List of audit links if any:
https://github.com/bailsec/BailSec/blob/main/Bailsec%20-%20Algebra%20Integral%20-%20Update%20Audit%20(differential)%20Final%20Report%20Github%20(%2BResolution).pdf

##### Website Link:
https://henjin.xyz/

##### Logo (High resolution, will be shown with rounded borders):
https://henjin.xyz/resources/images/logo.svg
image

##### Current TVL:
Just launched on Taiko mainnet

##### Chain:
Taiko

##### Short Description (to be shown on DefiLlama):
An innovative and highly flexible v4 DEX built to support the Taiko ecosystem. Community driven plugins (hooks) and capital efficient automatic liquidity management (ALM).

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### forkedFrom (Does your project originate from another project):
Algebra Integral 1.1

##### Github org/user (Optional, if your code is open source, we can track activity):
HenjinDEX

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/henjin exports TVL: 
        
 
 
    taiko                     0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/henjin exports TVL: 
        
 
 
    taiko                     36
    
    total                    36.035999999999994

**Comment by llamatester** [comment]
The adapter at projects/henjin exports TVL: 
        
 
 
    taiko                     36
    
    total                    35.98974

**Comment by g1nt0ki** [comment]
thanks for the PR

**Pull request merged**
