### PR TITLE
updated Chronicle XNL

### PR DESCRIPTION
**Pull request by strange-dv**
updated Chronicle XNL information and corrected spelling errors

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/chronicle: 
        
 
  
    
    
    Error: 
        Please move the following keys into the chain: tvl
    
        We have a new adapter export specification now where tvl and other chain specific information are moved inside chain export.
        For example if your protocol is on ethereum and has tvl and pool2, the export file would look like:
        
            module.exports = {
              methodlogy: '...',
              ethereum: {
                tvl: 
                pool2:
              }
            }

**Comment by llamatester** [comment]
Error while running adapter at projects/chronicle: 
        
 
  
    
    
    Error: 
        Please move the following keys into the chain: tvl
    
        We have a new adapter export specification now where tvl and other chain specific information are moved inside chain export.
        For example if your protocol is on ethereum and has tvl and pool2, the export file would look like:
        
            module.exports = {
              methodlogy: '...',
              ethereum: {
                tvl: 
                pool2:
              }
            }

**Comment by llamatester** [comment]
The adapter at projects/chronicle exports TVL: 
        
 
 
    aurora                    0
    aurora-staking            0
    aurora-pool2              21.10 k
    staking                   0
    pool2                     21.10 k
    
    total                    0

**Comment by realdealshaman** [comment]
staking will show once XNL aurora address is available on coingecko

**Pull request merged**
