### PR TITLE
feat: add Ottopia adapter

### PR DESCRIPTION
**Pull request by 0xthk**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI

---

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): 
image

##### Short Description (to be shown on DefiLlama): 

OtterClam is a decentralized ecosystem that incorporates elements of finance, governance, and NFTs, in the Metaverse. These three components correspond to OtterClam’s Treasury, DAO, and Otter Kingdom, respectively.

We are a DAO-governed community of NFT, DeFi, and Metaverse enthusiasts who value transparency, innovation, education, and fun. 

##### methodology (what is being counted as tvl, how is tvl being calculated):

All the investment in treasury assets is counted as TVL.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/ottopia exports TVL: 
        
 
 
    polygon                   2.08 M
    polygon-staking           279.24 k
    staking                   279.24 k
    
    total                    2.08 M

**Comment by g1nt0ki** [comment]
@0xthk thanks for the PR, can you expand a bit on this part? "All the investment in treasury assets is counted as TVL."

if the treasury is tokens/fund owned by the team and unrelated to the users, I would say it needs to be included under "treasury" not "tvl", also we consider only non-native tokens for treasury: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by 0xthk** [comment]
> @0xthk thanks for the PR, can you expand a bit on this part? "All the investment in treasury assets is counted as TVL."
> 
> if the treasury is tokens/fund owned by the team and unrelated to the users, I would say it needs to be included under "treasury" not "tvl", also we consider only non-native tokens for treasury: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

Hi, @g1nt0ki , thanks for the comment. The treasury of Ottopia is bonded by the users. The yield of Ottopia staking reward is farmed by the treasury. The treasury owned by the investors, not the team.

**Comment by g1nt0ki** [comment]
@0xthk okay, in the UI, I see option only to stake CLAM for USD+ or autocompound CLAM, no option for purchasing bonds.

Also, what are the tokens that compromise the treasury

**Comment by 0xthk** [comment]
> 

Currently the bonds is not available because the market price of CLAM is below treasury backing. We'll enable bonding again once the market price above the backing price. 

The tokens of treasury is listed here https://app.otterclam.finance (our old dashboard, will be migrated to https://ottopia.app soon)
 
CleanShot 2022-07-19 at 17 45 24@2x

**Comment by g1nt0ki** [comment]
@0xthk thanks for the info

**Comment by g1nt0ki** [comment]
@0xthk we have a listing for otterclam here: https://defillama.com/protocol/otterclam

this project tvl/treasury is the same as otterclam, right?

**Comment by 0xthk** [comment]
> @0xthk we have a listing for otterclam here: https://defillama.com/protocol/otterclam
> 
> this project tvl/treasury is the same as otterclam, right?

The treasury is same, however, we did a major upgrade and rebranding to Ottopia. The tokenomics is totally different, so we would like to start from this one. Also, the TVL is no longer maintained.

**Comment by g1nt0ki** [comment]
so we replace the old listing?

**Comment by 0xthk** [comment]
> so we replace the old listing?

Yes, please do.

**Pull request merged**
