### PR TITLE
Update Davos TVL

### PR DESCRIPTION
**Pull request by Sk1mer12**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/davos-protocol: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:198:11
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by Sk1mer12** [comment]
@g1nt0ki Do you guys have any method that allows to fetch token price?

**Comment by llamatester** [comment]
Error while running adapter at projects/davos-protocol: 
        
 
  
    
    
    Error: Promise pool failed! 
     PromisePoolError: invalid address (argument="address", value="0x4e90156997bb469c6f5975e13ff1451c9500b711,0x87ad5ab05d7c1e1f904e029783810a2a95702563,0xb44a251d1c31dd32700e5f2584b4282716c43eb3", code=INVALID_ARGUMENT, version=6.9.2) (argument="account", value="0x4e90156997bb469c6f5975e13ff1451c9500b711,0x87ad5ab05d7c1e1f904e029783810a2a95702563,0xb44a251d1c31dd32700e5f2584b4282716c43eb3", code=INVALID_ARGUMENT, version=6.9.2)
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
The adapter at projects/davos-protocol exports TVL: 
        
 
 
    arbitrum                  431.69 k
    ethereum                  226.40 k
    bsc                       223.06 k
    polygon                   19.25 k
    optimism                  5.25 k
    mode                      494
    polygon_zkevm             0
    
    total                    906.15 k

**Comment by Sk1mer12** [comment]
Please hold before merging! Some contracts are wrong!

**Comment by llamatester** [comment]
The adapter at projects/davos-protocol exports TVL: 
        
 
 
    arbitrum                  430.37 k
    ethereum                  225.57 k
    bsc                       222.87 k
    polygon                   19.23 k
    optimism                  5.24 k
    polygon_zkevm             1.41 k
    mode                      492
    linea                     0
    
    total                    905.18 k

**Comment by llamatester** [comment]
The adapter at projects/davos-protocol exports TVL: 
        
 
 
    arbitrum                  430.30 k
    ethereum                  225.71 k
    bsc                       222.89 k
    polygon                   19.24 k
    optimism                  5.24 k
    polygon_zkevm             1.41 k
    mode                      492
    linea                     0
    
    total                    905.27 k

**Comment by llamatester** [comment]
The adapter at projects/davos-protocol exports TVL: 
        
 
 
    arbitrum                  430.05 k
    ethereum                  225.66 k
    bsc                       222.89 k
    polygon                   19.23 k
    optimism                  5.24 k
    polygon_zkevm             1.41 k
    mode                      492
    linea                     0
    
    total                    904.96 k

**Comment by llamatester** [comment]
The adapter at projects/davos-protocol exports TVL: 
        
 
 
    arbitrum                  430.05 k
    ethereum                  225.66 k
    bsc                       222.89 k
    polygon                   19.24 k
    optimism                  5.24 k
    polygon_zkevm             1.41 k
    mode                      492
    linea                     0
    
    total                    904.98 k

**Comment by llamatester** [comment]
The adapter at projects/davos-protocol exports TVL: 
        
 
 
    arbitrum                  430.51 k
    ethereum                  225.84 k
    bsc                       222.84 k
    polygon                   19.21 k
    optimism                  5.24 k
    polygon_zkevm             1.41 k
    mode                      493
    linea                     0
    
    total                    905.54 k

**Comment by llamatester** [comment]
The adapter at projects/davos-protocol exports TVL: 
        
 
 
    arbitrum                  430.81 k
    ethereum                  226.13 k
    bsc                       222.91 k
    polygon                   19.27 k
    optimism                  5.25 k
    polygon_zkevm             1.41 k
    mode                      493
    linea                     0
    
    total                    906.28 k

**Comment by g1nt0ki** [comment]
thanks for the update

**Pull request merged**
