### PR TITLE
Lion Commerce

### PR DESCRIPTION
**Pull request by gaspare100**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Lion Commerce

##### Twitter Link:
https://twitter.com/ScrubFinance

##### Website Link:
https://commerce.scrub.money

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://commerce.scrub.money/_next/image?url=%2Flogo.png&w=128&q=100

##### Current TVL:
0

##### Chain:
Kava
Cronos

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
lion-scrub-money

##### Short Description (to be shown on DefiLlama):
Lion Commerce empowers users to effortlessly purchase real-life products and gift cards with their on-chain assets. Plus, the innovative staking system enables them to earn additional discounts on their purchases. Powered by Scrub Money and currently available on Kava and Cronos chains, with many more to come, Lion Commerce is the future of decentralized shopping. Join Lion Commerce today and experience a whole new way of shopping!

##### Token address and ticker if any:
0x990e157fC8a492c28F5B50022F000183131b9026 LION

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Services

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
On chain price feed

##### forkedFrom (Does your project originate from another project):
none

##### methodology (what is being counted as tvl, how is tvl being calculated):
Included in PR

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/lioncommerce: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:203:11

**Comment by llamatester** [comment]
Error while running adapter at projects/lioncommerce: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:203:11

**Comment by llamatester** [comment]
The adapter at projects/lioncommerce exports TVL: 
        
 
 
    kava                      0
    kava-staking              0
    staking                   0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/lioncommerce exports TVL: 
        
 
 
    kava                      0
    kava-staking              274.707314559008
    staking                   274.707314559008
    
    total                    0

**Comment by gaspare100** [comment]
Hello, i'm really not sure how but we now have this protocol under a "Scrub Finance" name which is absolutely not what we want as we moved away from that name long ago.

Please, separate de protocols just as they are with the Kava ones.

**Pull request merged**
