### PR TITLE
Native

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/native: 
        
 
  
    
    
    Error: failed to meet quorum (method="getLogs", params={"filter":{"fromBlock":"0x1a03bc0","toBlock":"0x1a03deb","address":"0x85b0F66E83515ff4e825DfCAa58E040E08278EF9","topics":["0x583aa3202641e70abf6c4e526dd0bf713aa272b67f557ed30f2e40a37d985a8e"]}}, results=[{"weight":1,"start":1681289086714,"error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":46,\"error\":{\"code\":-32005,\"message\":\"limit exceeded\"}}","error":{"code":-32005},"requestBody":"{\"method\":\"eth_getLogs\",\"params\":[{\"fromBlock\":\"0x1a03bc0\",\"toBlock\":\"0x1a03deb\",\"address\":\"0x85b0f66e83515ff4e825dfcaa58e040e08278ef9\",\"topics\":[\"0x583aa3202641e70abf6c4e526dd0bf713aa272b67f557ed30f2e40a37d985a8e\"]}],\"id\":46,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://bsc-dataseed.binance.org/"}},{"weight":1,"start":1681289087464,"error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":43,\"error\":{\"code\":-32005,\"message\":\"limit exceeded\"}}","error":{"code":-32005},"requestBody":"{\"method\":\"eth_getLogs\",\"params\":[{\"fromBlock\":\"0x1a03bc0\",\"toBlock\":\"0x1a03deb\",\"address\":\"0x85b0f66e83515ff4e825dfcaa58e040e08278ef9\",\"topics\":[\"0x583aa3202641e70abf6c4e526dd0bf713aa272b67f557ed30f2e40a37d985a8e\"]}],\"id\":43,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://bsc-dataseed1.defibit.io/"}},{"weight":1,"start":1681289088214,"error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":43,\"error\":{\"code\":-32005,\"message\":\"limit exceeded\"}}","error":{"code":-32005},"requestBody":"{\"method\":\"eth_getLogs\",\"params\":[{\"fromBlock\":\"0x1a03bc0\",\"toBlock\":\"0x1a03deb\",\"address\":\"0x85b0f66e83515ff4e825dfcaa58e040e08278ef9\",\"topics\":[\"0x583aa3202641e70abf6c4e526dd0bf713aa272b67f557ed30f2e40a37d985a8e\"]}],\"id\":43,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://bsc-dataseed1.ninicoin.io/"}},{"weight":1,"start":1681289088964,"error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":43,\"error\":{\"code\":-32005,\"message\":\"limit exceeded\"}}","error":{"code":-32005},"requestBody":"{\"method\":\"eth_getLogs\",\"params\":[{\"fromBlock\":\"0x1a03bc0\",\"toBlock\":\"0x1a03deb\",\"address\":\"0x85b0f66e83515ff4e825dfcaa58e040e08278ef9\",\"topics\":[\"0x583aa3202641e70abf6c4e526dd0bf713aa272b67f557ed30f2e40a37d985a8e\"]}],\"id\":43,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://bsc-dataseed2.defibit.io/"}},{"weight":1,"start":1681289089714,"error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":43,\"error\":{\"code\":-32005,\"message\":\"limit exceeded\"}}","error":{"code":-32005},"requestBody":"{\"method\":\"eth_getLogs\",\"params\":[{\"fromBlock\":\"0x1a03bc0\",\"toBlock\":\"0x1a03deb\",\"address\":\"0x85b0f66e83515ff4e825dfcaa58e040e08278ef9\",\"topics\":[\"0x583aa3202641e70abf6c4e526dd0bf713aa272b67f557ed30f2e40a37d985a8e\"]}],\"id\":43,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://bsc-dataseed2.ninicoin.io/"}}], provider="[object Object]", code=SERVER_ERROR, version=providers/5.7.2)
    Truncated error stack:
        at FallbackProvider.<anonymous> (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:684:54)

**Comment by llamatester** [comment]
Error while running adapter at projects/native: 
        
 
  
    
    
    Error: failed to meet quorum (method="getLogs", params={"filter":{"fromBlock":"0x1a03bc0","toBlock":"0x1a03e13","address":"0x85b0F66E83515ff4e825DfCAa58E040E08278EF9","topics":["0x583aa3202641e70abf6c4e526dd0bf713aa272b67f557ed30f2e40a37d985a8e"]}}, results=[{"weight":1,"start":1681289208557,"error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":46,\"error\":{\"code\":-32005,\"message\":\"limit exceeded\"}}","error":{"code":-32005},"requestBody":"{\"method\":\"eth_getLogs\",\"params\":[{\"fromBlock\":\"0x1a03bc0\",\"toBlock\":\"0x1a03e13\",\"address\":\"0x85b0f66e83515ff4e825dfcaa58e040e08278ef9\",\"topics\":[\"0x583aa3202641e70abf6c4e526dd0bf713aa272b67f557ed30f2e40a37d985a8e\"]}],\"id\":46,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://bsc-dataseed.binance.org/"}},{"weight":1,"start":1681289209307,"error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":43,\"error\":{\"code\":-32005,\"message\":\"limit exceeded\"}}","error":{"code":-32005},"requestBody":"{\"method\":\"eth_getLogs\",\"params\":[{\"fromBlock\":\"0x1a03bc0\",\"toBlock\":\"0x1a03e13\",\"address\":\"0x85b0f66e83515ff4e825dfcaa58e040e08278ef9\",\"topics\":[\"0x583aa3202641e70abf6c4e526dd0bf713aa272b67f557ed30f2e40a37d985a8e\"]}],\"id\":43,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://bsc-dataseed1.defibit.io/"}},{"weight":1,"start":1681289210057,"error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":43,\"error\":{\"code\":-32005,\"message\":\"limit exceeded\"}}","error":{"code":-32005},"requestBody":"{\"method\":\"eth_getLogs\",\"params\":[{\"fromBlock\":\"0x1a03bc0\",\"toBlock\":\"0x1a03e13\",\"address\":\"0x85b0f66e83515ff4e825dfcaa58e040e08278ef9\",\"topics\":[\"0x583aa3202641e70abf6c4e526dd0bf713aa272b67f557ed30f2e40a37d985a8e\"]}],\"id\":43,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://bsc-dataseed1.ninicoin.io/"}},{"weight":1,"start":1681289210807,"error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":43,\"error\":{\"code\":-32005,\"message\":\"limit exceeded\"}}","error":{"code":-32005},"requestBody":"{\"method\":\"eth_getLogs\",\"params\":[{\"fromBlock\":\"0x1a03bc0\",\"toBlock\":\"0x1a03e13\",\"address\":\"0x85b0f66e83515ff4e825dfcaa58e040e08278ef9\",\"topics\":[\"0x583aa3202641e70abf6c4e526dd0bf713aa272b67f557ed30f2e40a37d985a8e\"]}],\"id\":43,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://bsc-dataseed2.defibit.io/"}},{"weight":1,"start":1681289211557,"error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":43,\"error\":{\"code\":-32005,\"message\":\"limit exceeded\"}}","error":{"code":-32005},"requestBody":"{\"method\":\"eth_getLogs\",\"params\":[{\"fromBlock\":\"0x1a03bc0\",\"toBlock\":\"0x1a03e13\",\"address\":\"0x85b0f66e83515ff4e825dfcaa58e040e08278ef9\",\"topics\":[\"0x583aa3202641e70abf6c4e526dd0bf713aa272b67f557ed30f2e40a37d985a8e\"]}],\"id\":43,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://bsc-dataseed2.ninicoin.io/"}}], provider="[object Object]", code=SERVER_ERROR, version=providers/5.7.2)
    Truncated error stack:
        at FallbackProvider.<anonymous> (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:684:54)

**Comment by g1nt0ki** [comment]
> @g1nt0ki thanks for the refactoring! Is it expected that the test doesn't pass?

it is failiing on github as we have not configured archival node for github actions, will work on our server:

--- ethereum ---
USDC                      937.27 k
WBTC                      719.94 k
USDT                      618.15 k
WETH                      559.92 k
ETH                       924.6849175637184
Total: 2.84 M 

--- bsc ---
WBNB                      1.21 M
USDT                      537.87 k
BUSD                      512.28 k
USDC                      265.84 k
ETH                       166.93 k
BTCB                      141.94 k
BNB                       807.0346297917497
Total: 2.84 M 

--- tvl ---
WBNB                      1.21 M
USDC                      1.20 M
USDT                      1.16 M
WBTC                      719.94 k
WETH                      559.92 k
BUSD                      512.28 k
ETH                       167.86 k
BTCB                      141.94 k
BNB                       807
Total: 5.68 M 

------ TVL ------
ethereum                  2.84 M
bsc                       2.84 M

total                    5.68 M

**Comment by hung-native** [comment]
@g1nt0ki just to let me know that the numbers look correct to me and we can merge this. Thanks!

**Comment by realdealshaman** [comment]
@hung-native can you add this info: 
Name:


audit links if has been audited:


Twitter Link:


Website Link:


Logo:


Current TVL:


Chain:


Coingecko ID of Governance Token:


Coinmarketcap ID of Governance Token:


Short Description (to be shown on DefiLlama):


Governance Token address and ticker if any:


Category (full list at https://defillama.com/categories) *Please choose only one:


Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):


Is the project a fork of another protocol:

**Comment by realdealshaman** [comment]
UPDATE: We've added the listing

**Comment by hung-native** [comment]
Hi @realdealshaman 
I provided the info in the original PR I submitted: https://github.com/DefiLlama/DefiLlama-Adapters/pull/5894

thanks for listing our project! saw it on the site. Just that I can see the TVL number calculated and showed, but the chart is not showing data. Is it expected? Or it's because we're just there and it takes more data points to have a chart? Thanks!

**Pull request merged**
