### PR TITLE
Add Optimism CEX Addresses

### PR DESCRIPTION
**Pull request by MSilb7**
Adding an identified OKX address on Optimism (tagged on Nansen as OKX)
Adding known KuCoin addresses for Optimism (shared with OP Team)

As a note, we have Binance, Coinbase, Ramp, Juno addresses here - didn't seem like there were adapters set up to input addresses: https://github.com/duneanalytics/spellbook/blob/main/models/addresses/optimism/addresses_optimism_cex.sql

**NOTE**

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/okex exports TVL: 
        
 
 
    bitcoin                   1.51 B
    tron                      845.54 M
    polygon                   34.77 M
    avax                      118.87 M
    ethereum                  3.77 B
    arbitrum                  14.12 M
    optimism                  23.38 M
    
    total                    6.32 B

**Comment by llamatester** [comment]
The adapter at projects/kucoin exports TVL: 
        
 
 
    algorand                  139.97 M
    tron                      241.44 M
    kcc                       1.53 M
    eos                       44.26 M
    ethereum                  1.42 B
    arbitrum                  14.76 M
    bitcoin                   257.47 M
    optimism                  8.45 M
    
    total                    2.13 B

**Comment by llamatester** [comment]
The adapter at projects/okex exports TVL: 
        
 
 
    bitcoin                   1.51 B
    tron                      845.70 M
    polygon                   34.76 M
    avax                      118.81 M
    arbitrum                  14.12 M
    optimism                  23.36 M
    ethereum                  3.77 B
    
    total                    6.32 B

**Comment by g1nt0ki** [comment]
@MSilb7 thanks for the PR, we are fixing some things on our server before merging this so it doesnt show up as token inflows, would merge this after that fix

**Pull request merged**
