### PR TITLE
Feature/bevm

### PR DESCRIPTION
**Pull request by 0xdigiscore**
##### Name (to be shown on DefiLlama):
BEVM

##### Twitter Link:
https://twitter.com/BTClayer2

##### Website Link:
https://www.bevm.io/

##### Current TVL:

3.82M
##### Chain:
Bitcoin

##### Short Description (to be shown on DefiLlama):
BEVM is the first fully decentralized EVM-compatible Bitcoin L2 that uses BTC as Gas. It allows all DApps which can run in the Ethereum ecosystem to operate on Bitcoin L2.

##### Token address and ticker if any:
BTC

##### Category (full list at https://defillama.com/categories) *Please choose only one:
BTC layer2

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/btclayer2

My previous description is inaccurate. These assets are locked by users in the bevm network through cross-connect bridges: https://bevm.io/bridge.
In fact, the multi-signature is a distributed threshold signature contract used to host BTC. It should be calculated as the TVL of the chain, similar to eth in l2 such as arb.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bevm exports TVL: 
        
 
 
    bitcoin                   3.84 M
    
    total                    3.84 M

**Comment by g1nt0ki** [comment]
comment why on your other PR

**Comment by llamatester** [comment]
The adapter at projects/bevm exports TVL: 
        
 
 
    bitcoin                   3.81 M
    
    total                    3.81 M

**Comment by g1nt0ki** [comment]
sorry, we cant show it as chain tvl but can be tracked as bridge (bridge tvl belongs to neither bitcoin nor bevm chain)

**Comment by g1nt0ki** [comment]
hmm, that is not (technically) possible atm, like it is not happening for ethereum l2 either, but some the users have requested for it, will will work on it soon

**Pull request merged**
