### PR TITLE
add bonsai strike

### PR DESCRIPTION
**Pull request by tw7613781**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Bonsai Strike

##### Twitter Link:
https://twitter.com/BonsaiStrike

##### List of audit links if any:
https://3252533156-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F2sLHA6VC2Qvv8soKXZfl%2Fuploads%2FEoxxawgW1OoGPCvYyyGt%2FCODA%20Audit%20Report_V4_140223.pdf?alt=media&token=c97d558c-3342-4a30-93be-d735c76724e7

##### Website Link:
https://bonsai.money

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://www.bonsai.money/static/media/main-icon.ac8191dd.svg

##### Current TVL:
867 BNB (~300k USD)

##### Treasury Addresses (if the protocol has treasury)
nil

##### Chain:
BNB Chain

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
nil

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
nil

##### Short Description (to be shown on DefiLlama):
Bonsai Strike is the first in a planned series of Defi products on Binance Smart Chain that help users access sustainable and real yield.

##### Token address and ticker if any:
nil

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Options Vault

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### forkedFrom (Does your project originate from another project):
Ribbon Finance

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is taken from the mark to market value of the tokens deposited in the vaults

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bonsai-strike exports TVL: 
        
 
 
    bsc                       309.32 k
    
    total                    309.32 k

**Comment by g1nt0ki** [comment]
hi @tw7613781 why is the total balance call returning 310k when only 13k worth of bnb is found in the protocol: https://www.bscscan.com/address/0x01cEF5B79044E1CCd9b6Ad76c3d0985b5A33F769

**Comment by tw7613781** [comment]
Hi @g1nt0ki . glad to get your reply. The reason is that our vault will mint options by using the locked asset (wbnb) as collateral from 3rd party protocol on weekly basis. So the totalBalance = the amount locked in 3rd party protocols + wbnb balance of our vault address (the number you saw above).

**Comment by g1nt0ki** [comment]
ah I see that it is deposited here: https://www.bscscan.com/address/0x4b9d1cf13129a79d92bef13dac908e9ffc665ad8#readContract but what protocol is this?

**Comment by tw7613781** [comment]
yes. the contract you found is MarginPool, use to keep the collateral of opening position, one of contracts in Opyn gamma protocol. We deployed a full suite of Opyn gamma protocol contracts to issue options to our vaults.

**Comment by tw7613781** [comment]
currently we focus on the vaults product. so counting balance in both and keep a single listing is good for us now. if we have changes (like make a separate UI for opyn gamma), could make a PR in future, right? thx.

**Comment by g1nt0ki** [comment]
> currently we focus on the vaults product. so counting balance in both and keep a single listing is good for us now. if we have changes (like make a separate UI for opyn gamma), could make a PR in future, right? thx.

yup, it would be easy

**Comment by llamatester** [comment]
The adapter at projects/bonsai-strike exports TVL: 
        
 
 
    bsc                       308.28 k
    
    total                    308.28 k

**Comment by llamatester** [comment]
The adapter at projects/bonsai-strike exports TVL: 
        
 
 
    bsc                       309.48 k
    
    total                    309.48 k

**Pull request merged**
