### PR TITLE
Update Balanced TVL

### PR DESCRIPTION
**Pull request by hetfly**
Updated collateral TVL calculation based on smart contract changes.

TVL to possibly check against https://stats.balanced.network/

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/balanced exports TVL: 
        
 
 
    icon                      12.17 M
    
    total                    12.17 M

**Comment by g1nt0ki** [comment]
hi @hetfly I am thinking we probably should move out this and create a new sublisting for it.

**Comment by g1nt0ki** [comment]
hi @hetfly , sorry for the delay, I have refactored the code here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/771e998e042e05a618f4abc9638a63ca235e66e8

the idea here is have a main listing for balanced, and two sublistings, one for the dex and other for the stablecoin

**Comment by g1nt0ki** [comment]
something like https://defillama.com/protocol/sushi

**Comment by g1nt0ki** [comment]
@hetfly check this out: https://defillama.com/protocol/balanced-dollar

**Pull request closed without merging**
