### PR TITLE
Create Typus-Finance

### PR DESCRIPTION
**Pull request by WayneAl**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Typus Finance

##### Twitter Link:
https://twitter.com/TypusFinance

##### List of audit links if any:
https://docs.typus.finance/audit

##### Website Link:
https://typus.finance

##### Logo (High resolution, will be shown with rounded borders):
https://raw.githubusercontent.com/Typus-Lab/typus-asset/main/logo.png

##### Current TVL:
12.97 k 

##### Chain:
SUI

##### Short Description (to be shown on DefiLlama):
[Typus Finance](https://typus.finance/) is a real yield infrastructure on [Sui Blockchain](https://sui.io/) (Sui) that enables users to obtain superior risk-to-reward returns, all in one click. 
Typus combines swap, lending, and derivatives protocols to create an options marketplace for long-tail assets. This approach not only improves risk-adjusted returns for Liquidity Providers (LPs), but also deepens liquidity in Decentralized Finance (DeFi), making it a win-win situation for everyone involved.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
[Options Vault](https://defillama.com/protocols/Options%20Vault)

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Typus Oracle / SwitchBoard / Pyth

##### forkedFrom (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated):
Sum all balance in the deposit vaults and bid vaults

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/typus-finance exports TVL: 
        
 
 
    sui                       12.97 k
    
    total                    12.97 k

**Comment by g1nt0ki** [comment]
@WayneAl thanks for the PR, not sure why this is not auto merged, maybe because of the rebase:     var value = BigInt(0);

**Comment by WayneAl** [comment]
@g1nt0ki  what should I do ?

**Comment by g1nt0ki** [comment]
all good, I have merged it, we will list it soon. closed this PR because it is redundant, nothing else

**Comment by g1nt0ki** [comment]
*your code/commit is copied but with different hash

**Comment by WayneAl** [comment]
Got it, thanks!

**Pull request closed without merging**
