### PR TITLE
Added TVL for goblins cash

### PR DESCRIPTION
**Pull request by Gauravk0029**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamabutler** [comment]
The adapter at projects/goblins-cash exports TVL: 
        
 
 
    smartbch                  111.69 k
    staking                   102.44 k
    smartbch-staking          55.89 k
    binance-staking           46.56 k
    binance                   34.96 k
    base                      5.42 k
    base-staking              0
    
    total                    152.07 k

**Comment by llamabutler** [comment]
The adapter at projects/goblins-cash exports TVL: 
        
 
 
    smartbch                  111.69 k
    staking                   102.44 k
    smartbch-staking          55.89 k
    binance-staking           46.56 k
    binance                   34.96 k
    base                      5.42 k
    base-staking              0
    
    total                    152.07 k

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
thanks for the PR, we already have a listing for goblin cash, can you use that? https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/goblinscash/index.js#L13


Also, what are you tracking as tvl here? for ohm forks, we count POL as treasury not tvl.

**Comment by llamabutler** [comment]
The adapter at projects/goblins-cash exports TVL: 
        
 
 
    smartbch                  115.33 k
    staking                   103.14 k
    smartbch-staking          59.31 k
    binance-staking           43.82 k
    binance                   35.02 k
    base                      5.33 k
    base-staking              0
    
    total                    155.68 k

**Comment by Gauravk0029** [comment]
Hey @g1nt0ki, we are tracking total liquidty in pools for goblins cash as tvl.

Sure let me push in existing goblin cash.

**Comment by llamabutler** [comment]
The adapter at projects/goblinscash exports TVL: 
        
 
 
    smartbch                  115.25 k
    staking                   111.19 k
    smartbch-staking          59.51 k
    binance-staking           43.85 k
    binance                   34.80 k
    base-staking              7.83 k
    base                      5.52 k
    
    total                    155.57 k

**Comment by llamabutler** [comment]
The adapter at projects/goblins-cash exports TVL: 
        
 
 
    smartbch                  115.25 k
    staking                   103.36 k
    smartbch-staking          59.51 k
    binance-staking           43.85 k
    binance                   34.80 k
    base                      5.52 k
    base-staking              0
    
    total                    155.57 k

**Comment by g1nt0ki** [comment]
@Gauravk0029 ah, sorry, I got confused. I created a new listing for the dex part, we will soon adapter to track the volume & fee part, thanks for the PR & the subgraph links

**Pull request closed without merging**
