### PR TITLE
Add Gumball.fi adapter

### PR DESCRIPTION
**Pull request by Ehlm**
**NOTE**

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
GumBall Protocol

##### Twitter Link:
https://twitter.com/GumBallProtocol

##### List of audit links if any:
https://github.com/zokyo-security/audit-reports/blob/main/Gumball_Zokyo%20audit%20report.pdf
https://github.com/peckshield/publications/blob/master/audit_reports/PeckShield-Audit-Report-GumBallV2-v1.0.pdf

##### Website Link:
https://www.gumball.fi/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
image

##### Current TVL:
$878K

##### Chain:
Arbitrum

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

##### Short Description (to be shown on DefiLlama):
GumBall Protocol is a Liquid NFT creation and trading hub.

##### Token address and ticker if any:
N/A

##### Category (full list at https://defillama.com/categories) *Please choose only one:
25 NFT Marketplace

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
N/A

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
We pull all balances from our 3 contracts for each NFT collection and convert them to ETH using current coingecko api and return them as total TVL.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/Gumball exports TVL: 
        
 
 
    arbitrum                  884.07 k
    
    total                    884.07 k

**Comment by llamatester** [comment]
The adapter at projects/gumball exports TVL: 
        
 
 
    arbitrum                  181.62 k
    
    total                    181.62 k

**Comment by g1nt0ki** [comment]
@Ehlm thanks for the PR, how are you computing the price of NFTs/nft tokens? the `currentPrice` method. I am seeing a floor price, can the nfts ever be sold below the floor price?  

Valuing NFTs has been troublesome: https://github.com/DefiLlama/DefiLlama-Adapters/pull/5002#issuecomment-1377724981

But since you have liquidity built into your protocol, can I put tvl as base token value * 2? Looked at your code, not sure why you are  including both the erc721 and erc20 version of the NFT under tvl, is that duplication?

**Comment by GumBallProtocol** [comment]
Because the ERC20 version of our NFT is always the same price as the ERC721 they are one-to-one and not duplicated.

**Comment by Ehlm** [comment]
I believe the comment you provided isn't applicable to our platform as the ERC-721's are directly redeemable for 1 GBT (a ERC-20 tokenization of the collection) always. It's not a standard opensea value or nft marketplace value. The currentPrice value is determined by a bonding curve on the collection exchange page.

**Comment by g1nt0ki** [comment]
> I believe the comment you provided isn't applicable to our platform as the ERC-721's are directly redeemable for 1 GBT (a ERC-20 tokenization of the collection) always. It's not a standard opensea value or nft marketplace value. The currentPrice value is determined by a bonding curve on the collection exchange page.

how is it different from sudoswap pools? correct me if I am wrong but bonding curves are set by the user right? it does not reflect market price (at least in sudoswap)

**Comment by GumBallProtocol** [comment]
This is more similar to univ2 where you can always buy/sell at the price of the bonding curve. Users cannot select where to supply liquidity, it is determined by the xy=k formula of the bonding curve.

**Comment by g1nt0ki** [comment]
> This is more similar to univ2 where you can always buy/sell at the price of the bonding curve. Users cannot select where to supply liquidity, it is determined by the xy=k formula of the bonding curve.

Got it, that's why I suggested WETH (base token) liquidity * 2, this is how we price unknown tokens in dexes

**Comment by GumBallProtocol** [comment]
sounds good let's just do that please!

**Comment by llamatester** [comment]
The adapter at projects/gumball exports TVL: 
        
 
 
    arbitrum                  308.45 k
    
    total                    308.45 k

**Pull request merged**
