### PR TITLE
Fyde Adapter

### PR DESCRIPTION
**Pull request by Teamo0**
##### Name (to be shown on DefiLlama):
Fyde

##### Twitter Link:
https://twitter.com/FydeTreasury

##### List of audit links if any:
https://docsend.com/view/6jemcyp2xav55d3h

##### Website Link:
www.fyde.fi

##### Logo (High resolution, will be shown with rounded borders):
https://github.com/FydeTreasury/FydeMediaKit/tree/main/Logos

##### Current TVL:
1,365,678

##### Chain:
Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
fyde-treasury

##### Short Description (to be shown on DefiLlama):
Fyde Treasury Protocol enables the crypto ecosystem to diversify portfolios & treasuries, unlock token liquidity, and generate yield - all while retaining governance rights. The protocol introduces an innovation of the Liquid Vault that creates large multi-asset liquidity vaults directly accessible by the user's native governance token.

##### Token address and ticker if any:
$TRSY
https://etherscan.io/token/0x87Cc45fFF5c0933bb6aF6bAe7Fc013b7eC7df2Ee

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Services, Indexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink, Uniswap V3 TWAP

##### forkedFrom (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated):
Fyde provides exposure to a diversified basket of tokens. The TVL is calculated by summing the balances of all token currently
in this basket.

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/Fyde exports TVL: 
        
 
 
    ethereum                  1.33 M
    
    total                    1.33 M

**Comment by g1nt0ki** [comment]
@Teamo0 thanks for the PR, refactored it a bit.

**Comment by llamatester** [comment]
The adapter at projects/fyde exports TVL: 
        
 
 
    ethereum                  1.18 M
    
    total                    1.18 M

**Comment by Teamo0** [comment]
Hey @g1nt0ki,
thanks for taking care of this. Your refactor unfortunately doesn't take into account the full protocol TVL. While most of the asset are owned by the Fyde contract, there are additional tokens that are kept in governance proxies. This allows depositor to still use their governance rights while invested in the pool. Your PR only considers the balanceOf the Fyde contract, while for the correct balance including the governance proxies, one has to query Fyde.totalAssetAccounting(address token), like I did in my Adapter code. This is why the llamatester reports a TVL of 1.18M after your commit and 1.33M before.

Thanks and best regards
Team0

**Comment by g1nt0ki** [comment]
@Teamo0 any way to get list of governance proxies used? yeah, I did notice a diff in ALCX tvl

**Comment by Teamo0** [comment]
Yes it is a bit annoying though since we only store the owners of the proxies, which then have to be mapped.

const GOVERNANCE_MODULE = 0xA8380974885c756CA560EbAD3C04E1a16FE63DbE;

to get the array of proxy users call
"function getAllGovUsers() public view returns (address[] memory)"

map each user to proxy by calling 
"function userToProxy(address) public view returns (address)"

this gives you the list of all governance proxies.

**Comment by g1nt0ki** [comment]
hmm, okay, I have reverted my change.

**Pull request merged**
