### PR TITLE
add Bitdrome adapter

### PR DESCRIPTION
**Pull request by kizenY**
Name (to be shown on DefiLlama): Bitdrome Finance

Twitter Link: https://x.com/BitdromeFi

List of audit links if any:

Website Link: https://app.bitdrome.finance/

Logo (High resolution, will be shown with rounded borders):
https://drive.google.com/file/d/1Qx4PsERp01rLe1jxummBXoTnY12P5_HG/view?usp=drive_link

Current TVL: $ 1,918,536.54

Treasury Addresses (if the protocol has treasury):

Chain: BEVM

Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

Short Description (to be shown on DefiLlama): Bitdrome Finance combines new generation (NG) AMM from Curve Finance and the ve(3,3) flywheel mechanism.The best place to farm and trade with your ₿ assets.

Token address and ticker if any:

*Please choose only one: [Dexes]

Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):

Implementation Details: Briefly describe how the oracle is integrated into your project:

Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage: https://bitdrome.gitbook.io/resources

forkedFrom (Does your project originate from another project): Curve Finance

methodology (what is being counted as tvl, how is tvl being calculated): The USD value of tokens stored in the pools

Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bitdrome exports TVL: 
        
 
 
    bevm                      955.74 k
    
    total                    955.74 k

**Comment by kizenY** [comment]
> The adapter at projects/bitdrome exports TVL:
> 
> ```
> bevm                      955.74 k
> 
> total                    955.74 k 
> ```

USDT(0xa67ED736649F2958A35fd249a584151056b4b745) in BEVM is unrecognized noe

**Comment by llamatester** [comment]
The adapter at projects/bitdrome exports TVL: 
        
 
 
    bevm                      1.94 M
    
    total                    1.94 M

**Comment by g1nt0ki** [comment]
@kizenY thanks for the PR

**Pull request merged**
