### PR TITLE
Securo Finance Project added

### PR DESCRIPTION
**Pull request by AdityaPune**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

##### Twitter Link:
https://twitter.com/Securo_Finance

##### Website Link:
https://securo.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
Please use the same one as Twitter profile pic from the link above

##### Current TVL:
Project has just been launched onto mainnet hence negligible TVL, need to integrate with popular open source dashboards such as yours to gain some traction
##### Chain:
Aurora, Binance Smart Chain, Avalanche, Polygon

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
NA

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
NA

##### Short Description (to be shown on DefiLlama):
Simplify crypto investing with DeFi indices Using all-in-1 dashboard and API integration

##### Token address and ticker if any:
NA

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Indexes

##### forkedFrom (Does your project originate from another project):
NA

##### methodology (what is being counted as tvl, how is tvl being calculated):
The amount stored in different strategy vaults is used to calculate TVL

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/securofinance exports TVL: 
        
 
 
    polygon                   0
    avax                      0.0054267493623897526
    aurora                    0
    bsc                       0.0149507889905503
    
    total                    0.020377538352940053

**Comment by llamatester** [comment]
The adapter at projects/securofinance exports TVL: 
        
 
 
    avax                      0.0053871643728914086
    bsc                       0.014967053697197143
    polygon                   0
    aurora                    0
    
    total                    0.020354218070088553

**Comment by g1nt0ki** [comment]
thanks for the PR

**Comment by Define101** [comment]
Hi guys, i can see on your website that you guys were audited by a few audits firms
Could you provide us with some links to display on the website? Cant find it on your website 
image

**Comment by AdityaPune** [comment]
Our project, previously DAOVentures, had audits done from the following agencies. Currently, its been revamped to Securo and does not have Audits for one of the strategies (BNI), hence we don't possess a link yet. Will update you when its completed.

**Pull request merged**
