### PR TITLE
Fxdx

### PR DESCRIPTION
**Pull request by hoysal08**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
FXDX

##### Twitter Link:
https://twitter.com/fxdxdex

##### List of audit links if any:

https://github.com/TheArcadiaGroup/publications/blob/main/audits/FXDX%20Final.pdf

##### Website Link:
https://fxdx.exchange/

##### Logo (High resolution, will be shown with rounded borders):

https://drive.google.com/file/d/1sdUWN-yz72l8jiERiTHYheo5bsORuVRR/view

##### Current TVL:
$15,875
##### Treasury Addresses (if the protocol has treasury)
  NA

##### Chain:
Optimism

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
NA

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
20637

##### Short Description (to be shown on DefiLlama):
FXDX is 0 trading fee perpetual futures decentralized exchange

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Derivatives

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):  
NA

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is calculated on the basis of all the assests held in the protocol vault.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/fxdx exports TVL: 
        
 
 
    optimism                  15.97 k
    
    total                    15.97 k

**Comment by llamatester** [comment]
The adapter at projects/fxdx exports TVL: 
        
 
 
    optimism                  16.00 k
    
    total                    16.00 k

**Comment by g1nt0ki** [comment]
hi @hoysal08 thanks for the PR, why is the total supply of WETH higher than the amount of ETH in it? https://optimistic.etherscan.io/address/0xd158b0f013230659098e58b66b602dff8f7ff120

**Comment by hoysal08** [comment]
hi @g1nt0ki . the amount of eth in the contract is about 2.84 ETH right now, and the balance of vault(0x10235996C4DAbCE8430a71Cbc06571bd475A1d0C) is also 2.84 ETH.
Can you please explain a little more about the numbers you think are not matching?

**Comment by g1nt0ki** [comment]
@hoysal08 but the WETH total supply must match the amount of ether in the WETH contract right, else 1WETH !== 1 ETH

**Comment by hoysal08** [comment]
@g1nt0ki , This wrapped eth contract is for **internal purposes** only and the vault contract will be the only user of the contract. No external user can mint WETH from here(if you can see the code on the explorer, we don't have a mint function).
We have implemented this mechanism so we can use ETH also as an ERC20 standard which gives uniformity while dealing with all the other assets of the platform.

The only way we can update the balance is by using the below 2 functions 

``` 
function deposit() public payable {
        _balances[msg.sender] = _balances[msg.sender].add(msg.value);
    }

    function withdraw(uint256 amount) public {
        require(_balances[msg.sender] >= amount);
        _balances[msg.sender] = _balances[msg.sender].sub(amount);
        msg.sender.transfer(amount);
    }
```    
and since we're not keeping track of TotalSupply here, the total supply will always be zero irrespective of how much ETH the contract holds.

**Comment by llamatester** [comment]
The adapter at projects/fxdx exports TVL: 
        
 
 
    optimism                  16.89 k
    
    total                    16.89 k

**Pull request merged**
