### PR TITLE
fix PsyOptions TVL tracking (RPC rate limits were causing issues)

### PR DESCRIPTION
**Pull request by tomjohn1028**
RPC rate limits were causing TVL from the PsyAmerican protocol to not be tracked.

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@tomjohn1028 I am not really seeing an rate limit issue now, and the adapter has room for improvement but not sure if replacement with a dependency is the right way

**Comment by tomjohn1028** [comment]
@g1nt0ki It's definitely missing some TVL from the Americans protocol, my initial assumption was RPC rate limits since I hit those when testing. Either way we can knock out an API and transition to fetch adapter. Closing this for now, will re-open the PR once that is complete

**Comment by g1nt0ki** [comment]
@tomjohn1028 I will try to refactor the adapter a bit but we strongly prefer on chain adapters, right now we are even rejecting fetch adapter PRs for chains that we support on chain calls

regarding rate limit issue, are you using public RPC? maybe that is the cause, ideally it should fail if it runs into rpc error right? I will have a closer look at the adapter

**Comment by g1nt0ki** [comment]
@tomjohn1028 I have refactored code here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/3609 does it match expected tvl now?

**Comment by tomjohn1028** [comment]
@g1nt0ki having issues running the local interactive test, but the site looks good to me now!

**Comment by g1nt0ki** [comment]
> @g1nt0ki having issues running the local interactive test, but the site looks good to me now!

try reducing chunk size and increasing sleep time, also is there some way to batch query? like multicall in ethereum, when I tried sending an array with more than one item here, it kept failing

**Comment by g1nt0ki** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/helper/solana.js#L356

**Comment by tomjohn1028** [comment]
@g1nt0ki Just reviewed the code in a little more detail and looks like you're 

1. taking all token + owner addresses (https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/psyoptions/index.js#L66)
2. grouping them into batches of 99 (https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/helper/solana.js#L356)
3. making a single request to get the token balance **for each** of the 99 in the batch (seen [here](https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/helper/solana.js#L118-L120) and [here](https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/helper/solana.js#L52))

There is much more efficient ways to handle this. The couple options are:

1. Consolidate the SPL Token account addresses and request to [_getMultipleAccountsInfo_](https://solana-labs.github.io/solana-web3.js/classes/Connection.html#getMultipleAccountsInfo). 
    * Note: Done this way you will need to decode the token accounts. You can see a decent example of how I similarly batch get token account information for an array of Token Account addresses in that dependency I tried to add ([here](https://github.com/mithraiclabs/psyoptions-ts/blob/master/packages/psy-metrics/src/utils.ts#L35-L66)). It relies on Anchor.
    
    
2. Batch your requests by constructing a JSON RPC Request (see image below and docs [here](https://docs.solana.com/developing/clients/jsonrpc-api#request-formatting))
    * Note: Here's the JSON RPC implementation of [_getMultipleAccounts_](https://docs.solana.com/developing/clients/jsonrpc-api#getmultipleaccounts) that the web3.js implementation constructs for you. Could combine them both.
Screen Shot 2022-08-18 at 4 37 11 PM

**Comment by g1nt0ki** [comment]
@tomjohn1028 thanks for the detailed answer, truly appreciate it, I followed your advice and making batch calls now instead of parallel calls

**Pull request closed without merging**
