### PR TITLE
Feat: Add MantaDEX TVL

### PR DESCRIPTION
**Pull request by DanielZhangReal**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
MantaDEX

##### Twitter Link:
https://twitter.com/MantaDex

##### Website Link:
https://mantadex.com/

##### Logo (High resolution, will be shown with rounded borders):
https://raw.githubusercontent.com/Manta-Network/manta-chaindata/main/assets/tokens/MANDEX.svg

##### Current TVL:
$468k

##### Chain:
Manta Atlantic

##### Short Description (to be shown on DefiLlama):
MantaDEX is a groundbreaking exchange on the Manta Network. Dive into a realm of innovation driven by modular ZK systems, shaping the future of web3 ecosystems and decentralized applications. Join us in redefining secure and interoperable trading experiences, guided by the strength of Zero-Knowledge technology.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### forkedFrom (Does your project originate from another project):
https://defillama.com/protocol/zenlink

##### methodology (what is being counted as tvl, how is tvl being calculated):
tvl()

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at : 
        
 
  > Please revert changes to package.json / package-lock.json

**Comment by llamatester** [comment]
Error while running adapter at : 
        
 
  > Please revert changes to package.json / package-lock.json

**Comment by g1nt0ki** [comment]
hi @DanielZhangReal sorry for the delay, will review this soon, being on polkadot makes it bit more tricky and takes a bit of time

**Comment by llamatester** [comment]
Error while running adapter at projects/manta-atlantic-mantadex: 
        
 
  
    
    
    Error: Data for protocol manta-atlantic-mantadex on chain manta_atlantic is undefined on heroku
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/heroku-api.js:11:19
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:64:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:160:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:3

**Comment by g1nt0ki** [comment]
@DanielZhangReal thanks, the code looks good, changed the folder name here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/9079

**Pull request closed without merging**
