### PR TITLE
Update adapter for Anzen

### PR DESCRIPTION
**Pull request by bshyong**
This is an update request with the following new information:
 New adapter to show TVL from V2 product, USDz which is a multichain stablecoin. The previous pools have been sunset.

Listing info (have opened separate PR for this in the listing info repo).
- Audit links updated. Audited by Zellic, Halborn, and Peckshield. https://github.com/Anzen-Finance/audits
- Coingecko link updated. https://www.coingecko.com/en/coins/anzen-usdz

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
5. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
6. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
7. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
8. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
9. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Anzen

##### Twitter Link:
https://twitter.com/anzenfinance

##### List of audit links if any:
Audited by Zellic, Halborn, and Peckshield
https://github.com/Anzen-Finance/audits

##### Website Link:
https://anzen.finance/

##### Logo (High resolution, will be shown with rounded borders):
use existing

##### Current TVL:
$3,050,000

##### Chain:
Ethereum, Base

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
https://www.coingecko.com/en/coins/anzen-usdz

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/anzen exports TVL: 
        
 
 
    base                      2.98 M
    ethereum                  65.87 k
    
    total                    3.05 M

**Comment by g1nt0ki** [comment]
hi, can you instead create a new folder "anzem-v2" and pull the token value backing the stablecoin instead of token spuuly?

**Comment by bshyong** [comment]
@g1nt0ki should I make the V2 folder even if V1 is discontinued now?  The backing for the stablecoin is a permissioned token that represents $1 of tokenized RWA that is always minted at 1:1 ratio. https://etherscan.io/token/0xf30a29f1c540724fd8c5c4be1af604a6c6800d29

**Comment by bshyong** [comment]
@g1nt0ki Let me know what you're thinking here.  We were advised to report totalSupply like Ethena has done:

https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/ethena/index.js

**Comment by llamatester** [comment]
Error while running adapter at projects/anzen-v2: 
        
 
  
    
    
    Error: 
        Found export keys that were not part of specification: secured_collateral
    
        List of valid keys: 
    				
    				tvl
    				staking
    				methodology
    				pool2
    				misrepresentedTokens
    				fetch
    				timetravel
    				borrowed
    				start
    				doublecounted
    				treasury
    				hallmarks
    				incentivized
    				offers
    				deadFrom
    				broken
    				ownTokens
    				vesting
        
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
The adapter at projects/anzen-v2 exports TVL: 
        
 
 
    base                      4.30 M
    ethereum                  353.00 k
    
    total                    4.66 M

**Pull request merged**
