### PR TITLE
List fUSDT + UST pools

### PR DESCRIPTION
**Pull request by aureliusbtc**

### CODE REVIEW

**Comment by 0xngmi** [comment]
Could you rebase on top of master? Getting some merge conflicts due to the changes to your adapter since the last PR

**Comment by aureliusbtc** [comment]
Rebased, can merge now

**Comment by 0xngmi** [comment]
Saw it, I'll need to write some code to unwrap 3nrv so for now I haven't merged yet

**Comment by 0xngmi** [comment]
Planning to get around it when I have a bit of time :thinking:

**Pull request merged**
