### PR TITLE
Update to Yieldlys TVL calcs using the official endpoint

### PR DESCRIPTION
**Pull request by AronTurner**

### CODE REVIEW

**Comment by 0xngmi** [comment]
could you separate staking from other tvl then?

**Comment by AronTurner** [comment]
Can I get an update on this please @0xngmi?

**Comment by waynebruce0x** [comment]
Sorry for the delay - can native Yieldly token staking be separated into a 'staking' export, instead of being included as core TVL?

**Comment by AronTurner** [comment]
From what I can understand,  I will seperate the No-loss prize game TVL from the rest of the staking TVL's. So this will have 2 TVL's one for the game (which is the amount of Algo locked up) and one for all our staking pools staked amounts summed in USD value. Much like what Pancakeswap has, correct?

**Comment by waynebruce0x** [comment]
yes thats correct, one tvl export, and one staking export. Users then have the option whether or not they want to include native token staking in the tvl shown. This was a community feature request and we try to keep our method consistent across all protocols.

**Comment by AronTurner** [comment]
I performed an update that split it into the NLL TVL and the staking TVL, please let me know if anything else is missing

**Comment by AronTurner** [comment]
@waynebruce0x there seems to be an issue on the frontend, it does not appear to have been updated with the same schema as the newest iteration of the code we pushed as all values are now 0, can this be rectified soon please?

**Pull request merged**
