### PR TITLE
add oswap token

### PR DESCRIPTION
**Pull request by Taump**
##### Name (to be shown on DefiLlama): 
OSWAP token

##### Twitter Link: 
https://twitter.com/ObyteOrg

##### Website Link: 
https://token.oswap.io/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): 
https://icons.llamao.fi/icons/protocols/oswap

##### Current TVL: 
$93.18 k

##### Chain: 
Obyte

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
byteball

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
1492

##### Short Description (to be shown on DefiLlama): 
Governance and reward token of Oswap DEX

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
https://explorer.obyte.org/address/KMCA3VLWKLO3AWSSDA3LQIKI3OQEN7TV

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/oswap-token exports TVL: 
        
 
 
    obyte                     90.94 k
    
    total                    90.94 k

**Comment by g1nt0ki** [comment]
@Taump thanks for the PR, sorry dont think we can add this. We already have a listing for oswap.

Adding this would be like creating a separate listing for just the farming part of sushiswap, imo it is double counting.

**Comment by tonyofbyteball** [comment]
There is more than just farming. It's a new token issued on a bonding curve, and the current TVL is what is committed to issuing it. Should we exclude the farming part? Farming is not active yet.

**Comment by g1nt0ki** [comment]
The current tvl includes LPs and your gov tokens right? 

https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by tonyofbyteball** [comment]
Correct. Currently there are 3 parts in total:
- LPs - we can exclude them as discussed above
- GBYTEs locked to issue OSWAP tokens on the bonding curve
- OSWAP tokens locked in governance/staking

**Comment by g1nt0ki** [comment]
this sale will end soon right? If so, we can update existing oswap list and add staked OSWAP tokens under "staking" tvl

Yeah, LPs should be removed, staked OSWAP must be counted under "staking" key and only locked GBYTEs can be counted as tvl

**Comment by llamatester** [comment]
The adapter at projects/oswap-token exports TVL: 
        
 
 
    obyte-staking             0
    obyte                     93.60 k
    staking                   0
    
    total                    93.60 k

**Comment by tonyofbyteball** [comment]
Yes, the sale will end soon, on Apr 6.
LPs are now removed and staked OSWAP is under "staking" key.
I don't think merging this with oswap would make sense. They are distinct apps that don't know anything about each other, and the meaning of their TVLs is different (DEX pools vs bonding curve reserves).

**Comment by tonyofbyteball** [comment]
@g1nt0ki looks like you renamed oswap to oswap-amm and that unfortunately broke our yield adapter https://github.com/DefiLlama/yield-server/blob/master/src/adaptors/oswap/index.js. We tried renaming but then another test fails

Running oswap-amm Test › Check if pool id already used by other project › Expect duplicate ids array to be empty

What would be the best way to fix?

**Comment by tonyofbyteball** [comment]
No issues, it works now, thanks for the fast fix!

**Pull request merged**
