### PR TITLE
add bifrost_mainnet, update bifi project

### PR DESCRIPTION
**Pull request by tlatkdgus1**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### List of audit links if any: 
https://github.com/bifrost-platform/BIFI/blob/master/docs/ENG/(ENG)_BiFi_BIFROST_Extension_Theori.pdf
https://github.com/bifrost-platform/BIFI/blob/master/docs/ENG/(ENG)_BiFi_Lending_Sooho_EN_Public.pdf
https://github.com/bifrost-platform/BIFI/blob/master/docs/ENG/(ENG)_BiFi_Token_Hexlant_EN.pdf
https://github.com/bifrost-platform/BIFI/blob/master/docs/ENG/(ENG)_BiFrost_BTC_Extension_CertiK.pdf
https://github.com/bifrost-platform/BiFi-X/blob/main/docs/bifrost_bifix_audit.pdf

##### Logo (High resolution, will be shown with rounded borders): 
https://raw.githubusercontent.com/bifrost-platform/AssetInfo/master/Protocols/images/bifi.png

##### Token address and ticker if any:
https://raw.githubusercontent.com/bifrost-platform/AssetInfo/master/Assets/bifrost/tokens/images/128/0x047938C3aD13c1eB821C8e310B2B6F889b6d0003.png

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/bifrost-platform/BIFI

### CODE REVIEW

**Comment by tlatkdgus1** [comment]
> Error while running adapter at projects/bifi:
> 
> ```
> TypeError: Cannot read properties of null (reading 'getBalance')
> Truncated error stack:
>     at Object.<anonymous> (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/eth/index.js:104:98)
>     at new Promise (<anonymous>)
>     at Array.map (<anonymous>)
> ```

Maybe it's because I put an address that exists in the new chain, is there a docs for this part?

This is what I asked the discord about
https://discord.com/channels/823822164956151810/823822165538373696/1163700431092994048

**Comment by g1nt0ki** [comment]
hi @tlatkdgus1 closing this in favor of https://github.com/DefiLlama/DefiLlama-Adapters/pull/7740 where I did a minor refactor on top of your code

**Comment by tlatkdgus1** [comment]
> hi @tlatkdgus1 closing this in favor of #7740 where I did a minor refactor on top of your code

Thank you :)

**Comment by Define101** [comment]
@tlatkdgus1 what is the bifrost website link?

**Comment by tlatkdgus1** [comment]
> @tlatkdgus1 what is the bifrost website link?

here is bifrost website
https://thebifrost.io/

**Comment by tlatkdgus1** [comment]
can we change logo and name ?

https://defillama.com/chain/Bifrost%20EVM

**Pull request closed without merging**
