### PR TITLE
Add Chaotic Finance adapter

### PR DESCRIPTION
**Pull request by chaotisss**
##### Twitter Link: 

https://twitter.com/Chaotic_Finance

##### Website Link:

https://chaotic.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

https://logo.chaotic.finance/

##### Current TVL:

$58.43 k

##### Chain:

Moonriver

##### Short Description (to be shown on DefiLlama):

The first community-driven delta-one asset protocol on Moonriver

##### Token address and ticker if any:

Moonriver: 0xf4c6850B6e3288E81Be542909b76865a0BdF9585 (CHAOS)

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Derivatives

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

Chainlink

##### forkedFrom (Does your project originate from another project):

No

##### methodology (what is being counted as tvl, how is tvl being calculated):

1. Staked CHAOS tokens in Chaotic Buildr
2. Locked CHAOS rewards from staking

### CODE REVIEW

**Comment by waynebruce0x** [comment]
users stake CHAOS to earn cUSD? What is cUSD's pegging mechanism? How do users lock CHAOS and what does locked CHAOS do? thanks

**Comment by ssstacey** [comment]
Hi,
Users stake CHAOS to build cUSD. CHAOS are used as collateral here for the debt incurred when cUSD is built.
cUSD derives its intrinsic value when a liquidation event occurs, under which case cUSD can be used to redeem the underlying CHAOS collateral at a discounted price.
Locked CHAOS are tokens that users own but are not yet vested. These tokens count towards a user's collateral balance, and can be used to back cUSD building just like unlocked ones. All locked tokens are subject to some unlock time, upon which they will be released to users.

**Comment by waynebruce0x** [comment]
have locked CHAOS been previously unlocked, as in are they in circulation, or are they sort of like uncirculated/not-minted-yet coins?

**Comment by ssstacey** [comment]
There has been no unlock event so far, but all the locked tokens have been minted to the token locker contract at 0xe8091cA33a5658ba01eb59bD738D1cb590493aE9. That's why we're taking the ERC20 balance of the said address instead of calling some methods on it.
All tokens in the locker contract are subject to some unlock schedule.

**Comment by waynebruce0x** [comment]
we cant count tokens that havent already been in circulation. Can you remove this part from the calculation? It sounds like they havent been locked by users and are effectively queued up emissions?

**Comment by ssstacey** [comment]
Hi,

I updated the code. Locked chaos has been removed from calculation now.

**Pull request merged**
