### PR TITLE
Master

### PR DESCRIPTION
**Pull request by amirtotem**
##### Twitter Link:
https://twitter.com/TotemFi

##### Website Link:
https://totemfi.com

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
PNG Black Background: https://drive.google.com/file/d/1VaUm2964tRL-YgQg5dW6ehUxgQnVeOi5/view?usp=sharing
PNG Transparent Background : https://drive.google.com/file/d/1xIqhFFrI9TsXiK_ITgFPcLMhTYznLVkR/view?usp=sharing

SVG Black Background: https://drive.google.com/file/d/1KUWBAdQaBwzLN4L9rzLUNCFEet0acxcK/view?usp=sharing
SVG White Background: https://drive.google.com/file/d/1T29KBvixQBYHRRxtQtu6k9eESRvfQJJE/view?usp=sharing
##### Current TVL:
327000000000000000000000 TOTM 

##### Chain:
BSC

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
totemfi

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
8673

##### Short Description (to be shown on DefiLlama):
Risk free high earning prediction market, you'll grow like you do in games

##### Token address and ticker if any:
Address: 0x6ff1bfa14a57594a5874b37ff6ac5efbd9f9599a
Ticker : TOTM

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Staking

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### methodology (what is being counted as tvl, how is tvl being calculated):
Actual amount of TOTM staked at our pools at the moment

### CODE REVIEW

**Comment by 0xngmi** [comment]
pls undo/remove the changes to pull_request_template.md

**Comment by amirtotem** [comment]
> pls undo/remove the changes to pull_request_template.md

@0xngmi it is resolved.

**Comment by 0xngmi** [comment]
> Error: Failed to decode `block.number` value: `subgraph QmQSy6dbVjUtzYZTYZYaEdSvF3MhR5mjtkqaVe9DMJvBEy has only indexed up to block number 11456005 and data for block number 13347510 is therefore not yet available`

Your subgraph is stale

**Comment by amirtotem** [comment]
I've updated the subgraph .

**Pull request merged**
