### PR TITLE
add KubeCoin adapter

### PR DESCRIPTION
**Pull request by AlexFlykube**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
KubeCoin

##### Twitter Link:
https://twitter.com/Kubecoin_

##### List of audit links if any:
https://cdn.kubecoin.org/media/public/KubeCoin+MlabsAudit+Report.pdf

##### Website Link:
https://kubecoin.org

##### Logo (High resolution, will be shown with rounded borders):
https://kubecoin.org/logo-600.png

##### Current TVL:
687.51 k

##### Chain:
Cardano

##### Short Description (to be shown on DefiLlama):
The utility token bringing digital currencies to the real world. Use $KUBE to purchase your favorite products and services from our ecosystem and partners.

##### Token address and ticker if any:
Ticker:  KUBE

##### Category (full list at https://defillama.com/categories) *Please choose only one:
7. Services

##### methodology (what is being counted as tvl, how is tvl being calculated):
Sum of the total Kubecoin Staked by all the accounts which are currently staking.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/kubecoin exports TVL: 
        
 
 
    cardano                   0
    cardano-staking           686.83 k
    staking                   686.83 k
    
    total                    0

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
Please compute tvl/staking value on chain

**Comment by llamatester** [comment]
The adapter at projects/kubecoin exports TVL: 
        
 
 
    cardano                   0
    cardano-staking           687.51 k
    staking                   687.51 k
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/kubecoin exports TVL: 
        
 
 
    cardano                   0
    cardano-staking           687.51 k
    staking                   687.51 k
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/kubecoin exports TVL: 
        
 
 
    cardano-staking           688.20 k
    cardano                   688.20 k
    staking                   688.20 k
    
    total                    688.20 k

**Comment by g1nt0ki** [comment]
closed this as PR is not in good state, I had requested that tvl value be computed on chain, not value returned  under 'tvl' key

I can make the on chain adapter, please comment with staking contract and token contract/script details, also, we cant list if your token is not on coingecko

**Pull request closed without merging**
