### PR TITLE
dApp Staking on Astar Network

### PR DESCRIPTION
**Pull request by codespool**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Short Description (to be shown on DefiLlama):
dApp Staking on Astar Network introduces a novel approach, empowering individuals to nominate their ASTR or SDN tokens to support dApps building on the network.

For every block produced on the network, a segment of inflation is specifically allocated to dApp staking. These rewards are then divided between the dApp developers and stakers involved, offering benefits to both developers and stakers.

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is calculated based on the amount of ASTR staked

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/AstarNetwork

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/dapp-staking: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:198:11
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
Error while running adapter at : 
        
 
  > Please revert changes to package.json / package-lock.json

**Comment by g1nt0ki** [comment]
Hi, we already have an adapter for this, but decided to delist it about 2 years ago: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/astar-dapps-staking/index.js

**Comment by llamatester** [comment]
Error while running adapter at projects/dapp-staking: 
        
 
  
    
    
    Error: Data for protocol dapp-staking on chain astar is undefined on heroku
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/heroku-api.js:12:19
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:143:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:186:3

**Comment by codespool** [comment]
> Hi, we already have an adapter for this, but decided to delist it about 2 years ago: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/astar-dapps-staking/index.js

The dApp Staking protocol has been updated to v3 recently, and it's basically a new product.

The protocol was delisted for the reason of "not wanting to add validator or protocol staking", but now I see that category explicitly mentioned in the list.

Also we've noticed some similar protocols being merged recently. (eg #9080 )

For the reasons above, we ask for dApp Staking protocol to be reconsidered.

**Comment by g1nt0ki** [comment]
hmm, checking with the team, I think Manta pacific staking should also be delisted.

**Comment by fiexer** [comment]
Thanks @g1nt0ki 
I'm looking forward to the discussion of the team.

**Comment by g1nt0ki** [comment]
I have copied your changes here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/a4a49c0ebfb6f06d4a1c129effc34295a0bfbcb9 and re-enabled the listing here: https://github.com/DefiLlama/defillama-server/commit/20889a92a752dfc67312bf7ddd1a09695615744e

**Comment by fiexer** [comment]
@g1nt0ki thanks a lot!
Do you have any timeline for when this will be reflected again on the website?

**Pull request closed without merging**
