### PR TITLE
Add FxDAO Vaults' TVL adapter

### PR DESCRIPTION
**Pull request by earrietadev**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

FxDAO

##### Twitter Link: 

https://x.com/FxDAO_io

##### List of audit links if any:

https://github.com/runtimeverification/publications/blob/main/reports/smart-contracts/FxDAO.pdf

##### Website Link:

https://fxdao.io

##### Logo (High resolution, will be shown with rounded borders):

https://assets.fxdao.io/brand/FxDAO-logo.png

##### Current TVL:

936,382 USD

##### Chain:

Stellar

##### Short Description (to be shown on DefiLlama):

FxDAO is the first protocol that allows the issuance of synthetic assets (stablecoins) backed by Stellar Lumens

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Lending

##### forkedFrom (Does your project originate from another project):

No

##### methodology (what is being counted as tvl, how is tvl being calculated):

The TVL consists of the total amount of XLMs locked in the vault that are used to back up the assets issued by the protocol, currently this collateral is backing stablecoins. Once we fetch the XLM balance the contract has we calculate the USD value using the built in api method `addCGToken`

##### Github org/user (Optional, if your code is open source, we can track activity):

https://github.com/fxDAO/

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/FxDAO: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:226:11
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by earrietadev** [comment]
This merge requires importing the official Stellar SDK because otherwise a lot of code will be needed. I think it makes sense to have this library so all new Stellar smart contracts projects can use it with DefiLlama

**Comment by theboycoder** [comment]
@g1nt0ki bumping for visibility

**Comment by g1nt0ki** [comment]
@earrietadev thanks for the PR, I have added support here: https://github.com/DefiLlama/sushi-analytics/commit/4e5f23587d0b5801691575e82da2df4029a46482

**Comment by earrietadev** [comment]
Hi @g1nt0ki, thanks for updating and adding the adapter here https://github.com/DefiLlama/DefiLlama-Adapters/commit/890e594453a4e6d6ec27dc6d218e587d5447a0f2

Just wanted to ask if is normal that when going to https://defillama.com/protocol/fxdao it doesn't show any value. If there something else we should do?

Normally new adapters take a day to show something after being merged but because it's been 3 days I just want to confirm if we are missing something.

Thanks in advance!

**Comment by g1nt0ki** [comment]
no, this is not normal, will fix the issue

**Pull request closed without merging**
