### PR TITLE
Add Orcus-Finance (Astar EVM)

### PR DESCRIPTION
**Pull request by R312r0**
##### methodology (what is being counted as tvl, how is tvl being calculated): on-chain calculations, LP pairs balances

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/orcus exports TVL: 
        
 
 
    astar                     1.56 M
    
    total                    1.56 M

**Comment by R312r0** [comment]
> The adapter at projects/orcus exports TVL:
> 
> ```
> astar                     1.56 M
> 
> total                    1.56 M 
> ```

Hey, don't understand properly is everything ok?

**Comment by g1nt0ki** [comment]
> > The adapter at projects/orcus exports TVL:
> > ```
> > astar                     1.56 M
> > 
> > total                    1.56 M 
> > ```
> 
> Hey, don't understand properly is everything ok?

Thanks for the PR, but I am afraid that we need to do a bit of rework, the fault is on our side for not having supportive helper function, I am fixing that now

**Comment by R312r0** [comment]
> > > The adapter at projects/orcus exports TVL:
> > > ```
> > > astar                     1.56 M
> > > 
> > > total                    1.56 M 
> > > ```
> > 
> > 
> > Hey, don't understand properly is everything ok?
> 
> Thanks for the PR, but I am afraid that we need to do a bit of rework, the fault is on our side for not having supportive helper function, I am fixing that now

Ok sounds great. Thank you!

**Comment by g1nt0ki** [comment]
Hi @R312r0 the promised PR: https://github.com/DefiLlama/DefiLlama-Adapters/pull/2380

Hope you dont mind me closing this one in favor of that

**Comment by R312r0** [comment]
> Hi @R312r0 the promised PR: #2380
> 
> Hope you dont mind me closing this one in favor of that

Hey there sure! What ever you will be comfortable with!

**Pull request closed without merging**
