### PR TITLE
Add Mynt and Zero to Sovryn TVL

### PR DESCRIPTION
**Pull request by BetsyBraddock**
This PR updates the Sovryn TVL calculation to include Mynt and Zero protocols.

**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### methodology (what is being counted as tvl, how is tvl being calculated): TVL is calculated as the sum of all tokens (in USD) of all contracts in the following Sovryn protocol contracts:
- AMM liquidity pools
- Lending protocol contracts
- Sovryn Protocol contract that holds margin trading collateral
- Subprotocols - this currently only includes the Mynt Bonding Curve contract
- Zero Lending Protocol - stability pool funds and RBTC collateral
- Mynt Protocol - bitcoin-backed stablecoins that collateralize the DLLR token

TVL is pulled from our API which queries our subgraph and the RSK chain directly. The code for our API is open source and can be found here: https://github.com/DistributedCollective/Sovryn-graph-wrapper/blob/development/src/services/tvl.service.ts

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/sovryn.js exports TVL: 
        
 
 
    rsk                       50.49 M
    
    total                    50.49 M

**Comment by llamatester** [comment]
The adapter at projects/sovryn.js exports TVL: 
        
 
 
    rsk                       50.49 M
    
    total                    50.49 M

**Comment by g1nt0ki** [comment]
hi @BetsyBraddock , thanks for the PR, I have not merged it yet as I want to split and create listing for each subprotocol kinda like https://defillama.com/protocol/parallel-defi-super-app

**Comment by BetsyBraddock** [comment]
> hi @BetsyBraddock , thanks for the PR, I have not merged it yet as I want to split and create listing for each subprotocol kinda like https://defillama.com/protocol/parallel-defi-super-app

hi @g1nt0ki  - thanks, do you mean like this? 
image

That sounds great! Let me know if there's anything you need from our side

**Comment by g1nt0ki** [comment]
hi @BetsyBraddock  I meant more like having a listing per product and a overview which includes everything.

I have created a PR with breakdown here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/5892
can you help me with these

  - what in included in `tvlProtocol` and `tvlSubprotocols`, it is not very clear
  - how to get borrowed value for 'lending' product (so we can show this in UI)
  
  Changes made: 
  - We can count only the DOC part of mynt since, backing of zusd is already counted under "zero" product tvl, but right now, there is 0 DOC, we need some tvl before we can list this product
  - We are not counting zUSD in stablity pool under tvl, we apply same rule for other CDPs that we have listed

**Comment by g1nt0ki** [comment]
@BetsyBraddock thanks, I hae added borrowed here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/5892

**Comment by john-light** [comment]
@g1nt0ki 

re:
> We are not counting zUSD in stablity pool under tvl, we apply same rule for other CDPs that we have listed

Why is this the rule? The stability pool is providing liquidity for liquidations and can earn depositors profit. It provides a valuable economic service, and that liquidity could be put to use elsewhere but it is locked here instead, a real opportunity cost to depositors.

re:
> We can count only the DOC part of mynt since, backing of zusd is already counted under "zero" product tvl, but right now, there is 0 DOC, we need some tvl before we can list this product

Similar as above here: The ZUSD that is deposited in Mynt is providing liquidity for conversions between ZUSD and other bAssets (currently just DOC, if there is a DOC balance in the aggregator). That ZUSD could be used elsewhere, but depositors have chosen to park it here instead. As a thought experiment, let's imagine that Mynt (just Mynt, not Zero) was created by some other project instead of Sovryn. Maybe a fictional project called "Nyrvos". If Nyrvos submitted Mynt to DefiLlama would you still not count the ZUSD held in the Nyrvos Mynt aggregator towards the Nyrvos TVL? Why or why not?

Not trying to be combative here, just want to make sure I understand the rationale for these decisions :)

**Pull request merged**
