### PR TITLE
test commit

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/ocean-protocol exports TVL: 
        
 
 
    energyweb                 1.69 k
    bsc                       425.56563904944795
    polygon                   1.21 M
    ethereum                  144.55 k
    moonriver                 156.03095918421164
    
    total                    1.36 M

**Comment by llamatester** [comment]
The adapter at projects/ocean-protocol exports TVL: 
        
 
 
    moonriver                 155.0584793011053
    bsc                       422.91325502847764
    energyweb                 1.68 k
    polygon                   309.34 k
    ethereum                  137.49 k
    
    total                    449.09 k

**Comment by llamatester** [comment]
The adapter at projects/saddle exports TVL: 
        
 
 
    arbitrum                  2.82 M
    optimism                  2.57 k
    evmos                     162.37 k
    ethereum                  42.16 M
    fantom                    3.01 M
    
    total                    48.16 M

**Comment by westonnelson** [comment]
Hi @g1nt0ki thanks again! I am wondering tho - did this work? It seems to have worked here ^^^

(Still not including the gauges TVL or veSDL but that is fine for now) But I just did a manual calculation and what you see reflected here is accurate as of then....any thoughts?

"
arbitrum                  2.82 M
optimism                  2.57 k
evmos                     162.37 k
ethereum                  42.16 M
fantom                    3.01 M

total                    48.16 M "

**Pull request merged**
