### PR TITLE
teahouse & teahouse-v3: use json vault list instead

### PR DESCRIPTION
**Pull request by VensonLiou**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/teahouse-v3 exports TVL: 
        
 
 
    linea                     2.41 M
    boba                      892.76 k
    arbitrum                  601.40 k
    optimism                  123.57 k
    starknet                  112.20 k
    scroll                    59.20 k
    mantle                    51.61 k
    polygon                   5.70 k
    bsc                       3.47 k
    
    total                    4.26 M

**Comment by llamatester** [comment]
The adapter at projects/teahouse exports TVL: 
        
 
 
    ethereum                  3.07 M
    bsc                       578.23 k
    arbitrum                  212.12 k
    optimism                  15.09 k
    polygon                   0
    
    total                    3.88 M

**Comment by g1nt0ki** [comment]
instead of putting up a PR here everytime you update the vault list, what if you maintain this list in a repo controlled by you and instead of hitting the api, we will pull that file from github, we are doing this for a few projects already.

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
.

**Comment by VensonLiou** [comment]
So, what I need to do is open a new repo with a json file, update it in the future if needed, and give you the repo link?

**Comment by g1nt0ki** [comment]
yup, exactly. this way we skip the future PRs related to file update.

**Comment by VensonLiou** [comment]
Sound great!
I created a new repo here: https://github.com/TeahouseFinance/Vaults-for-DeFiLlama
Please check it out.
Thanks!

**Comment by g1nt0ki** [comment]
thanks @VensonLiou I have updated it here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/0e71b086873d48a0ee0bbe30739af4d9a0a753aa

**Pull request closed without merging**
