### PR TITLE
Add TONNEL Network

### PR DESCRIPTION
**Pull request by SaberDoTcodeR**
##### Name (to be shown on DefiLlama):

* Tonnel Network

##### Twitter Link:

* https://twitter.com/tonnel_network

##### Website Link:

* https://tonnel.network

##### Logo (High resolution, will be shown with rounded borders):

* https://www.tonnel.network/Logo3.png

##### Current TVL:

* 775.19 k

##### Chain:

* TON Blockchain

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

* 29091

##### Short Description (to be shown on DefiLlama):

* TONNEL uses ZK technology to bring privacy to the SocialFi ecosystem on TON Blockchain which is deeply integrated into Telegram.

##### Token address and ticker if any:

* ticker: TONNEL
* address EQDNDv54v_TEU5t26rFykylsdPQsv5nsSZaH_v7JSJPtMitv

##### Category (full list at https://defillama.com/categories) *Please choose only one:

* [Privacy](https://defillama.com/protocols/Privacy)

##### forkedFrom (Does your project originate from another project):

* Tornado Cash

##### methodology (what is being counted as tvl, how is tvl being calculated):

* Balances of mixer pools are calculated(similar to Tornado Adapter)

##### Github org/user (Optional, if your code is open source, we can track activity):

* https://github.com/Tonnel-Network/core

### CODE REVIEW

**Comment by SaberDoTcodeR** [comment]
Hi, I think this issue is related to `tonapi.io` rate limit👀 I guess you run it on whitelist IP so it won't have this issue on prod

**Comment by SaberDoTcodeR** [comment]
@g1nt0ki These TONNEL pools are not staking pools👀 These are mixer pools, our staking contract is separate, and I'll add it later.

**Comment by g1nt0ki** [comment]
> @g1nt0ki These TONNEL pools are not staking pools👀 These are mixer pools, our staking contract is separate, and I'll add it later.

hi @SaberDoTcodeR we can count it either under staking or not at all :( https://docs.llama.fi/list-your-project/what-to-include-as-tvl

the issue is we cant count your own tokens as tvl, aslo got some links as to what is GRAM & DFC ?

**Comment by SaberDoTcodeR** [comment]
Ok, then let's count it as staking:)


Gram:
https://app.ston.fi/pools/EQASBZLwa2vfdsgoDF2w96pdccBJJRxDNXXPUL7NMm0WdnMx

DFC:
https://dedust.io/pools/EQCEho8oSvzVneM-q3ALV9GMOoRzlGNwrGtq4p2x3SnInMVA
https://app.ston.fi/pools/EQCmapEiLQO0uYEOmvDeXNR9i5R4kYVPEmyNJEcwSCTSUTTa

**Comment by llamatester** [comment]
The adapter at projects/tonnel exports TVL: 
        
 
 
    ton                       558.45 k
    
    total                    558.45 k

**Comment by llamatester** [comment]
The adapter at projects/tonnel exports TVL: 
        
 
 
    ton                       569.41 k
    
    total                    569.41 k

**Comment by g1nt0ki** [comment]
@SaberDoTcodeR unsure why, part of the issue is, tonapi suddenly started this strict rate limiting,

other issue is, you cant do async loop as, staking wont be part of exported object if delayed and hence skipped.

**Comment by llamatester** [comment]
The adapter at projects/tonnel exports TVL: 
        
 
 
    ton-staking               318.14 k
    ton                       569.41 k
    staking                   318.14 k
    
    total                    569.41 k

**Comment by g1nt0ki** [comment]
@SaberDoTcodeR thanks for the PR

**Comment by SaberDoTcodeR** [comment]
@g1nt0ki, thank you for taking care of rate limit.

Should I now make a PR [here](https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data3.ts)?

**Comment by g1nt0ki** [comment]
no, we take care of it

**Comment by SaberDoTcodeR** [comment]
Hi, I think there is an issue with our tracker:(
https://defillama.com/protocol/tonnel-network

**Pull request merged**
