### PR TITLE
Update: Rain TVL including NFTs value

### PR DESCRIPTION
**Pull request by solwhitey**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

Hello! I added code to use our oracle to get the value of the collateralized nft

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/rain: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:196:11

**Comment by llamatester** [comment]
Error while running adapter at projects/rain: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'account')
    Truncated error stack:
    
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/rain/index.js:13:45)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:50:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:141:9
        at async Promise.all (index 0)
        at async Promise.all (index 0)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:184:3

**Comment by llamatester** [comment]
Error while running adapter at projects/rain: 
        
 
  
    
    
    Error: 429 Too Many Requests: {"jsonrpc":"2.0","error":{"code":-32429,"message":"exceeded limit for getProgramAccounts"}}
    Truncated error stack:
        at ClientBrowser.callServer (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@solana/web3.js/lib/index.cjs.js:4892:18)

**Comment by g1nt0ki** [comment]
@solwhitey hi, what oracle is used here for pricing NFTs?

**Comment by solwhitey** [comment]
> @solwhitey hi, what oracle is used here for pricing NFTs?

Hey, it's our own in house oracle, it's the one also used to issue loans, So the floor price reported have to be correct lol. it has a 24 TWAP.

**Comment by g1nt0ki** [comment]
hmm, the issue is, atm we are not including any nft outside of a few handful with chainlink support on ethereum as tvl

if it was some external oracle like pyth, I could add price support for those solana nfts, sorry, but dont like the idea of using your in house oracle. Other issue of using oracle only here is, now, nfts are included in your tvl, but not for any other sol project with nft (that we have listed)

**Comment by g1nt0ki** [comment]
do you know if pyth has nft pricing support for even some 3rd party service with open rest api?

**Comment by g1nt0ki** [comment]
hi @solwhitey I am not questioning the accuracy of your oracle data. But prefer relying on a credibly neutral price feed, ideally 2-3 so, we are fine if one of them rugs us

**Comment by g1nt0ki** [comment]
closing this for now, hopefully, will revisit this once we find a way to price nfts

**Pull request closed without merging**
