### PR TITLE
adaptor request for fenrirfinance

### PR DESCRIPTION
**Pull request by 0xLoki**
##### Twitter Link:
https://twitter.com/FenrirFi

##### Website Link:
https://fenrirfinance.com/
https://app.fenrirfinance.com/dashboard

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
fenrir-logo

##### Token address and ticker if any:
0xA919C7eDeAb294DD15939c443BCacA1FA1a1850f and FNR

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Yes

##### forkedFrom (Does your project originate from another project):
Compound

### CODE REVIEW

**Comment by g1nt0ki** [comment]
Hi, can you restore `package-lock.json` file, the adapter looks good

**Comment by g1nt0ki** [comment]
also, please move the file to `projects/fenrir/index.js`

**Comment by llamatester** [comment]
The adapter at projects/fenrir.js exports TVL: 
        
 
 
    bsc                       875.1474729475021
    bsc-borrowed              93.08955956594156
    borrowed                  93.08955956594156
    
    total                    875.1474729475021

**Comment by 0xLoki** [comment]
done chagnes

**Comment by llamatester** [comment]
The adapter at projects/fenrirfinance exports TVL: 
        
 
 
    bsc-borrowed              88.48610325129665
    bsc                       867.4722845751195
    borrowed                  88.48610325129665
    
    total                    867.4722845751195

**Comment by realdealshaman** [comment]
Hey @0xLoki , which oracle does the protocol use?

**Comment by 0xLoki** [comment]
> Hey @0xLoki , which oracle does the protocol use?

https://bscscan.com/address/0xe11f535b6f3f358122e73b9c4757bf192c8994c7#code

**Pull request merged**
