### PR TITLE
Grappa finance adapter

### PR DESCRIPTION
**Pull request by antoncoding**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Grappa Finance

##### Twitter Link:
https://twitter.com/grappafinance

##### List of audit links if any:
Audit report is not public yet, will provide later

##### Website Link:
[grappa.finance](https://www.grappa.finance/)

##### Current TVL:
99K

##### Treasury Addresses (if the protocol has treasury)
N/A

##### Chain:
Only Ethereum atm

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

##### Short Description (to be shown on DefiLlama):
Grappa is an open sourced, permissionless option margin layer focuses on composability and capital efficiency. Different margin engines can be plugged into Grappa to provide wide range of choice based on users' risk tolerance and capital efficiency.

##### Token address and ticker if any:
N/A

##### Category (full list at https://defillama.com/categories) *Please choose only one:
options

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
Fetch all margin engine addresses that registered with the grappa contracts with abi calls, combined with all registered assets to fetch the total TVL.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/grappa-finance: 
        
 
  
    
    
    TypeError: getLogs(...).map is not a function
    Truncated error stack:
    
        at ethereumTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/grappa-finance/grappa-ethereum.js:21:8)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:31)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:147:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:135:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:130:44

**Comment by llamatester** [comment]
The adapter at projects/grappa-finance exports TVL: 
        
 
 
    ethereum                  99.92 k
    
    total                    99.92 k

**Comment by llamatester** [comment]
The adapter at projects/grappa-finance exports TVL: 
        
 
 
    ethereum                  100.02 k
    
    total                    100.02 k

**Comment by llamatester** [comment]
The adapter at projects/grappa-finance exports TVL: 
        
 
 
    ethereum                  100.02 k
    
    total                    100.02 k

**Comment by llamatester** [comment]
The adapter at projects/grappa-finance exports TVL: 
        
 
 
    ethereum                  100.03 k
    
    total                    100.03 k

**Comment by llamatester** [comment]
The adapter at projects/grappa-finance exports TVL: 
        
 
 
    ethereum                  100.07 k
    
    total                    100.07 k

**Comment by g1nt0ki** [comment]
@antoncoding thanks for the PR, `getLogs` was also fine

**Pull request merged**
