### PR TITLE
Adding AADA finance

### PR DESCRIPTION
**Pull request by aada-finance**
##### Twitter Link: 
- https://twitter.com/AadaFinance

##### List of audit links if any:
-

##### Website Link:
- https://aada.finance

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
- https://raw.githubusercontent.com/aada-finance/staking-pools/main/aada_logo.jpg

##### Current TVL:
- 1.5M ADA ($1.77)

##### Chain:
- cardano

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
- 

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
- https://coinmarketcap.com/currencies/aada-finance/

##### Short Description (to be shown on DefiLlama):
This is Aada Finance - Decentralized Lending and Borrowing on Cardano. We like to call ourselves Aave fork, but built on eUTXO and therefore secure.

##### Token address and ticker if any:
- https://cardanoscan.io/token/b5ed5d2da985a62c96c7af72fce5f6518fbc3ae2

##### Category (full list at https://defillama.com/categories) *Please choose only one:
- Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
- None

##### forkedFrom (Does your project originate from another project):
- None

##### methodology (what is being counted as tvl, how is tvl being calculated):
- Staking. Amount of AADA locked in Smart Contract multiplied by top buy order in AADA_ADA pair on orderbook exchange.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/aada/index.js: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:206:11
        at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by aada-finance** [comment]
added tvl param. Tested with test.js - all works fine.

**Comment by llamatester** [comment]
The adapter at projects/aada/index.js exports TVL: 
        
 
 
    cardano                   0
    cardano-staking           1.84 M
    staking                   1.84 M
    
    total                    0

**Comment by waynebruce0x** [comment]
Does this count liquidity (supply - borrow) or supply?

**Comment by aada-finance** [comment]
Currently, it counts only stake locked for 6/12 months. In future PRs supply will be added using the best practices.

**Pull request merged**
