### PR TITLE
Add Bril Finance project adapter

### PR DESCRIPTION
**Pull request by tstemko**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Bril Finance

##### Twitter Link:
https://twitter.com/Bril_Finance

##### Website Link:
https://www.bril.finance/

##### Logo (High resolution, will be shown with rounded borders):
https://www.bril.finance/bril-logo.png

##### Current TVL:
$4,960,996 (November 8)

##### Chain:
Binance Smart Chain

##### Short Description (to be shown on DefiLlama):
Bril Finance is an intuitive DeFi platform that automates and optimizes portfolio strategies via professional grade liquidity provision algorithms. With single token deposit vaults and highly efficient yield optimization, Bril positions users for the optimal DeFi experience.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield Aggregator

##### methodology (what is being counted as tvl, how is tvl being calculated):
Counts tokens managed by Bril automated liquidity management strategies

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bril-finance exports TVL: 
        
 
 
    bsc                       4.93 M
    
    total                    4.93 M

**Comment by llamatester** [comment]
The adapter at projects/bril-finance exports TVL: 
        
 
 
    bsc                       4.97 M
    
    total                    4.97 M

**Comment by tstemko** [comment]
@g1nt0ki  There are two contract factories that constitute separate protocols.  Bril Finance manages the strategy factory (0xfaa2e7c69F7F34195D3Ef6CF98B6B009A6A07F30), and ICHI manages the vault factory (0x131c03ca881B7cC66d7a5120A9273ebf675C241D). This is similar to the relationship between other aggregator protocols and underlying protocols such as Beefy Finance and Gamma.

**Comment by g1nt0ki** [comment]
yeah but beefy has other protocols as well, other thing is, I dont see the strategies in the UI, I only see sei, how do users interact with bsc chain part of your app?

**Comment by tstemko** [comment]
@g1nt0ki Thank you for the feedback here. The Bril app will be launching in the coming days which will enable the direct deposit into the different strategies and vaults they integrate of which this is the first. We will follow up to complete this PR around the time of that launch to address the concern. Thanks again and let us know if you have any feedback!

**Comment by g1nt0ki** [comment]
hi @tstemko closing this for now, can re-open it later when other strategies are launched. Make a comment in this PR when you are ready

**Comment by tstemko** [comment]
Hi @g1nt0ki , the Bril Finance app is launched. Here's the direct link:
https://brilapp.io/
The link is also available on the Bril Finance site: https://www.bril.finance/. We are ready to move forward with this PR. Please let me know if you have any additional questions. Thanks

**Pull request closed without merging**
