### PR TITLE
feat(tvl): Update DefiLlama tracking for all WW deployments

### PR DESCRIPTION
**Pull request by 0xFable**
Starting only with TVL. 
Once this is confirmed working after merge we may do a few more like fees but will need examples to draw from. 

Contracts come from our docs e.g: https://docs.whitewhale.money/white-whale-docs/smart-contracts/liquidity-hub-deployments/migaloo

Happy to make further changes if needed 

**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

**NOTE**
For volume we have an endpoint available but ill be honest not certain how to integrate it into the above listed repo. 

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/whitewhale: 
        
 
  
    
    
    Error: Chain not found: stargaze
    Truncated error stack:
    
        at getEndpoint (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/cosmos.js:54:32)
        at queryContract (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/cosmos.js:174:10)
        at getAllPairs (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/terraswap/factoryTvl.js:24:27)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/terraswap/factoryTvl.js:48:26
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:29)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:136:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:131:44

**Comment by 0xFable** [comment]
Cool I'll remove stargaze its not launched yet anyways

**Comment by 0xFable** [comment]
Done, stargaze removed for now. I can add back once it launches proper and has some tvl

**Comment by llamatester** [comment]
The adapter at projects/whitewhale exports TVL: 
        
 
 
    injective                 20.09 k
    sei                       3.20 k
    migaloo                   0
    terra                     196.2577506552348
    chihuahua                 300.24 k
    juno                      31.97 k
    comdex                    2.80 k
    terra2                    2.05 M
    
    total                    2.41 M

**Comment by 0xFable** [comment]
This looks decent. Migaloo is currently reporting as 0 tho. Is this because this is a somewhat newer chain? Its a normal Cosmos-SDK based on like terra or chihuahua but noticing nothing there. 
With only 1 reporting a zero i'd be happy to go ahead can always debug that one after

**Comment by llamatester** [comment]
The adapter at projects/whitewhale exports TVL: 
        
 
 
    migaloo                   0
    injective                 20.09 k
    terra                     196.0750176167118
    sei                       3.20 k
    terra2                    2.05 M
    juno                      31.99 k
    chihuahua                 300.30 k
    comdex                    2.80 k
    
    total                    2.41 M

**Comment by llamatester** [comment]
The adapter at projects/pancakeswap-v3 exports TVL: 
        
 
 
    era                       1.92 M
    arbitrum                  447.24 k
    linea                     320.59152483287323
    ethereum                  47.48 M
    polygon_zkevm             404.93 k
    bsc                       227.69 M
    
    total                    277.94 M

**Comment by llamatester** [comment]
The adapter at projects/whitewhale exports TVL: 
        
 
 
    injective                 20.06 k
    terra                     195.96244789677777
    migaloo                   0
    sei                       3.19 k
    juno                      31.97 k
    comdex                    2.80 k
    terra2                    2.04 M
    chihuahua                 298.70 k
    
    total                    2.40 M

**Comment by g1nt0ki** [comment]
hi @0xFable, @llamatester is our CI bot

Sorry for late reply. I fixed it here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/3c6c74b9cb8a2af2344a1380ef3ba7054f8bc537

I added price support for uwhale in different repo,  it should be linked to this cg entry right? https://www.coingecko.com/en/coins/white-whale

You had edited the wrong adapter file, my fault for not naming it more clearly

let me know once you have some tvl in stargaze, we can add it

for adding fees/volume, can you join our discord and ask for support there? or can you share your tg handle here, I will ask the relevant llama to get in touch 

Thanks again for the PR

**Comment by 0xFable** [comment]
@g1nt0ki thank you for the help ! 
My bad I had a feeling I was quoting the ci guy lol 

Thank you for adding price support, yes that cg is good :D 

So I have a question but maybe ill take it to the discord, ill put it here for linkage 
Now after merge the tvls are underreported for a couple chains and I think its because of 'unknown' tokens. Any idea how I can fix that? I know what the tokens are really, so I can provide a mapping somewhere if needed 

I notice we have multiple adapters now, WW and WW-dex 
I want to in future add our bonding contracts to TVL bonders are the recipient of DEX fees in the form of WHALE so want to include this. 
Last thing is we have an API already which includes most datas and is indexed. Would it be easier to make the llama integration work off this API ? 


Thanks for your help with the PR ser <3

**Comment by g1nt0ki** [comment]
@0xFable 

 - for cosmos tokens, we taken cg mapping from https://github.com/cosmostation/chainlist , we manually maintain a list as well, soPR to either works
 - yeah, you can put up PR for volume here: https://github.com/DefiLlama/dimension-adapters
 - bonding contract, is this similar to chain staking for other cosmos chains, if so, we cant count it as tvl, otherwise, we can include it under 'staking' key: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Pull request closed without merging**
