### PR TITLE
Update MVL Staking core TVL

### PR DESCRIPTION
**Pull request by picardcapt1212**
Refactoring token address and adding core tvl calculations.

</br></br>

**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/mvl exports TVL: 
        
 
 
    ethereum                  718.94 k
    ethereum-staking          2.53 M
    ethereum-pool2            718.85 k
    bsc-staking               1.98 M
    bsc-pool2                 205.62 k
    bsc                       273.33 k
    staking                   4.51 M
    pool2                     924.47 k
    
    total                    992.27 k

**Comment by Define101** [comment]
We cant merge this
If its your own token = staking
If its LP and one of the tokens is your governance token = pool2

**Comment by picardcapt1212** [comment]
Thanks for reply!
I already calculated staking and pool2 as you said.
How can I make TVL the result of adding staking, pool2? I found other Yield projects staking, pool2 options checked as default but our project doesn't.

**Comment by picardcapt1212** [comment]
Thanks for reply! I asked on discord and problemed solved.

**Pull request closed without merging**
