### PR TITLE
Add SpringSui (Ecosystem)

### PR DESCRIPTION
**Pull request by DaSichuan**
Please group this under the Suilend Protocol umbrella
Can you also please change the name of SpringSui to "SpringSui (sSUI)"

Ideally the order would be
```
Suilend Protocol
    Suilend
    SpringSui (sSUI)
    SpringSui Ecosystem
```

**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
SpringSui Ecosystem

##### Twitter Link:
`https://x.com/springsui_`

##### List of audit links if any:
https://docs.suilend.fi/springsui/springsui-audit

##### Website Link:
https://springsui.com/

##### Logo (High resolution, will be shown with rounded borders):
-eOJJCAx_400x400 (1)

##### Current TVL:
$128,000

##### Chain:
Sui

##### Short Description (to be shown on DefiLlama):
SpringSui Ecosystem LSTs are those that have been deployed using the SpringSui Standard. 

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Liquid Staking

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/springsui-ecosystem exports TVL: 
        
 
 
    sui                       44.34 k
    
    total                    44.34 k

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
hi, can you give bit more info on what is it, who is using it, I dont see any info on your website

**Comment by nope-finance** [comment]
@g1nt0ki hey on our site it has this in the faq 
image
It's pretty early as the first one is launching today (with studio mirai) but are expecting more to come in over the next few weeks/months

**Comment by nope-finance** [comment]
hey @g1nt0ki wanted to follow up here. I think from chatting in tg seemed like it was ok to add, but revisit later if some of the TVL was contentious

**Pull request merged**
