### PR TITLE
add frax dexs

### PR DESCRIPTION
**Pull request by dtmkeng**

### CODE REVIEW

**Comment by llamatester** [comment]
The frax adapter exports: 
        
 
 _______________________________________
    Volume for 22/9/2022
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 23/5/2022
    24h volume: 84915.36999999732
    Total volume: 17708965.43999999
    AURORA 👇
    Backfill start time: 18/1/2022
    24h volume: 84915.36999999732
    Total volume: 17708965.43999999
    AVAX 👇
    Backfill start time: 23/5/2022
    24h volume: 84915.36999999732
    Total volume: 17708965.43999999
    BOBA 👇
    Backfill start time: 27/12/2021
    24h volume: 84915.36999999732
    Total volume: 17708965.43999999
    BSC 👇
    Backfill start time: 19/12/2021
    24h volume: 84915.36999999732
    Total volume: 17708965.43999999
    ETHEREUM 👇
    Backfill start time: 14/5/2022
    24h volume: 84915.36999999732
    Total volume: 17708965.43999999
    FANTOM 👇
    Backfill start time: 22/5/2022
    24h volume: 84915.36999999732
    Total volume: 17708965.43999999
    HARMONY 👇
    Backfill start time: 12/1/2022
    24h volume: 84915.36999999732
    Total volume: 17708965.43999999
    MOONBEAM 👇
    Backfill start time: 14/1/2022
    24h volume: 84915.36999999732
    Total volume: 17708965.43999999
    MOONRIVER 👇
    Backfill start time: 30/12/2021
    24h volume: 84915.36999999732
    Total volume: 17708965.43999999
    POLYGON 👇
    Backfill start time: 22/5/2022
    24h volume: 84915.36999999732
    Total volume: 17708965.43999999

**Comment by llamatester** [comment]
The frax adapter exports: 
        
 
 _______________________________________
    Volume for 22/9/2022
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 23/5/2022
    24h volume: 84915.36999999732
    Total volume: 17708965.43999999
    AURORA 👇
    Backfill start time: 18/1/2022
    24h volume: 0
    Total volume: 4171204.3299999996
    AVAX 👇
    Backfill start time: 23/5/2022
    24h volume: 23197.460000000894
    Total volume: 9443678.130000003
    BOBA 👇
    Backfill start time: 27/12/2021
    24h volume: 0
    Total volume: 4769689.110000001
    BSC 👇
    Backfill start time: 19/12/2021
    24h volume: 8208.660000003874
    Total volume: 55089087.87999997
    ETHEREUM 👇
    Backfill start time: 14/5/2022
    24h volume: 1091762.1399999857
    Total volume: 327041291.3699999
    FANTOM 👇
    Backfill start time: 22/5/2022
    24h volume: 26085.519999999553
    Total volume: 13018670.099999998
    HARMONY 👇
    Backfill start time: 12/1/2022
    24h volume: 3.530000001192093
    Total volume: 16359325.979999995
    MOONBEAM 👇
    Backfill start time: 14/1/2022
    24h volume: 192062.1400000006
    Total volume: 64934738.22000001
    MOONRIVER 👇
    Backfill start time: 30/12/2021
    24h volume: 19815.5
    Total volume: 79359347.79
    POLYGON 👇
    Backfill start time: 22/5/2022
    24h volume: 49092.0700000003
    Total volume: 22896164.23999999

**Comment by 0xngmi** [comment]
much better than my adapter, better to go with this one and remove mine

**Comment by dtmkeng** [comment]
ty

**Comment by llamatester** [comment]
The frax adapter exports: 
        
 
 _______________________________________
    Volume for 23/9/2022
    _______________________________________
    
    Error: Can't get block of chain ethereum
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:90:31
        at step (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:44:23)
        at Object.next (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:25:53)
        at fulfilled (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:16:58)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
    ------ ERROR ------
    Error: Couldn't find block height for chain ethereum, RPC node rugged
        at Object.<anonymous> (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:173:27)
        at step (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:44:23)
        at Object.throw (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:25:53)
        at rejected (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:17:65)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by llamatester** [comment]
The frax adapter exports: 
        
 
 _______________________________________
    Volume for 23/9/2022
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 23/5/2022
    24h volume: 121656.83999999985
    Total volume: 17830622.27999999
    AURORA 👇
    Backfill start time: 18/1/2022
    24h volume: 0
    Total volume: 4171204.3299999996
    AVAX 👇
    Backfill start time: 23/5/2022
    24h volume: 70147.74000000022
    Total volume: 9513825.870000003
    BOBA 👇
    Backfill start time: 27/12/2021
    24h volume: 0
    Total volume: 4769689.110000001
    BSC 👇
    Backfill start time: 19/12/2021
    24h volume: 8476.380000002682
    Total volume: 55097564.259999976
    ETHEREUM 👇
    Backfill start time: 14/5/2022
    24h volume: 1073701.1399999857
    Total volume: 328114992.5099999
    FANTOM 👇
    Backfill start time: 22/5/2022
    24h volume: 27938.929999999702
    Total volume: 13046609.029999997
    HARMONY 👇
    Backfill start time: 12/1/2022
    24h volume: 0
    Total volume: 16359325.979999995
    MOONBEAM 👇
    Backfill start time: 14/1/2022
    24h volume: 81846.9299999997
    Total volume: 65016585.15000001
    MOONRIVER 👇
    Backfill start time: 30/12/2021
    24h volume: 29773.440000012517
    Total volume: 79389121.23000002
    POLYGON 👇
    Backfill start time: 22/5/2022
    24h volume: 68914.83000000194
    Total volume: 22965079.069999993

**Pull request merged**
