### PR TITLE
Add Funbear

### PR DESCRIPTION
**Pull request by funbeario**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
FunBear

##### Twitter Link:
https://twitter.com/funbeario

##### Website Link:
https://funbear.net/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://stake.funbear.net/favicon.png

##### Current TVL:
0

##### Chain:
Ethereum, BSC, Kava

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
-

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
-

##### Short Description (to be shown on DefiLlama):
Funbear is a community oriented DeFi protocol that rewards its community while expanding the utility of Web3 tools. Funbear works to grow the intrinsic value of each FUNB through market participation to provide long term value accrual, but also provides a continuous stream of tokens to members who stake their FUNB into the Bear Cave.

##### Token address and ticker if any:
Token Symbol: FUNB
Ethereum = 0xD86c0B9b686f78a7A5C3780f03e700dbbAd40e01
BSC = 0xD86c0B9b686f78a7A5C3780f03e700dbbAd40e01
Kava = 0xD86c0B9b686f78a7A5C3780f03e700dbbAd40e01

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Staking

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL counts staked FUNB coins on the platform itself.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/funbear exports TVL: 
        
 
 
    kava                      0
    kava-staking              0
    staking                   0
    
    total                    0

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
sorry, we cant list a project with 0 tvl

**Comment by funbeario** [comment]
I see some projects with 0 TVL. Is there a way for you to accept.

**Comment by g1nt0ki** [comment]
they probably had tvl at some point or have other metrics like volume/revenue.

One way for you is, to get listed on coingecko, this way staking tvl would show up

**Pull request closed without merging**
