### PR TITLE
add Polynetwork

### PR DESCRIPTION
**Pull request by sulingxiao**
##### Twitter Link:
https://twitter.com/PolyNetwork2

##### List of audit links if any:
https://github.com/polynetwork/audit-report

##### Website Link:
https://www.poly.network/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://bridge.poly.network/img/logo.2e569620.svg

##### Current TVL:
0.42B
##### Chain:
Ethereum, Polygon, Avalanche, Fantom, BNB Chain, Arbitrum, Optimism, HECO, OKC, Neo, Ontology, Zilliqa, Elrond, Gnosis Chain，Andromeda, Boba, zkSync,HSC,Carbon, Palette, KCC, Bytom, Cosmos-SDK, Oasis, Bitcoin

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
[https://api.coingecko.com/api/v3/coins/list](https://api.coingecko.com/api/v3/coins/list))

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
[https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000](https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000))

##### Short Description (to be shown on DefiLlama):
Poly Network is a global cross-chain protocol for implementing blockchain interoperability and building Web3.0 infrastructure. Poly Network has also integrated over 20 blockchains, including Ethereum, Polygon, Avalanche, Fantom, BNB Chain, Arbitrum, Optimism, HECO, OKC, Neo, Ontology, Zilliqa, Elrond, Gnosis Chain, etc. Since the launch, the protocol has enabled cross-chain asset transfer of more than $16 billion USD, and its TVL surpasses $0.6 billion USD.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Bridge

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
no

##### forkedFrom (Does your project originate from another project):
no

##### methodology (what is being counted as tvl, how is tvl being calculated):
The total amount of valuable tokens locked on each chain in Poly LockProxy.

### CODE REVIEW

**Comment by waynebruce0x** [comment]
The API endpoints used count locked tokens on the source chain, which as used as collateral/backing for tokens minted on the destination chain (which arent counted as TVL) - is this right? Is the API open source?

**Comment by rain-zxn** [comment]
> The API endpoints used count locked tokens on the source chain, which as used as collateral/backing for tokens minted on the destination chain (which arent counted as TVL) - is this right? Is the API open source?

yes, right.  but the destination chain unlock mapping token, not mint.
API is also open source.

**Comment by rain-zxn** [comment]
hello, When can it be deployed.

**Comment by rain-zxn** [comment]
@waynebruce0x I just asked with you Discord, but I was kicked out. hhhhhhhh
If you are sure to go online, please notify me, thank you

**Pull request merged**
