### PR TITLE
Add Mintlayer

### PR DESCRIPTION
**Pull request by anyxem**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Mintlayer

##### Twitter Link:
https://x.com/mintlayer

##### Website Link:
https://www.mintlayer.org/

##### Logo (High resolution, will be shown with rounded borders):
logo_transparent_borders

Preview:
Screenshot 2024-11-14 at 00 43 02

##### Current TVL:
```
--- mintlayer ---
Total: 0

--- mintlayer-staking ---
USDT                      9.02 M
Total: 9.02 M

--- tvl ---
Total: 0

--- staking ---
USDT                      9.02 M
Total: 9.02 M

------ TVL ------
mintlayer-staking         9.02 M
staking                   9.02 M
mintlayer                 0

total                    0
```

##### Chain:
Mintlayer

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
mintlayer

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
14977

##### Short Description (to be shown on DefiLlama):
A layer 2 sidechain for tokenization that opens Bitcoin to DeFi using Atomic Swaps. Truly trustless finance via direct token interoperability without polluting the Bitcoin network.

##### Token address and ticker if any:
ML

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Staking

##### methodology (what is being counted as tvl, how is tvl being calculated):
Sum of all staked ML * token price to get USDT value

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/mintlayer

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/mintlayer exports TVL: 
        
 
 
    mintlayer-staking         9.02 M
    staking                   9.02 M
    mintlayer                 0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/mintlayer exports TVL: 
        
 
 
    mintlayer                 9.00 M
    
    total                    9.00 M

**Comment by anyxem** [comment]
updated tvl. moved staking to total:
```
--- mintlayer ---
USDT                      9.02 M
Total: 9.02 M

--- tvl ---
USDT                      9.02 M
Total: 9.02 M

------ TVL ------
mintlayer                 9.02 M

total                    9.02 M
```

**Comment by llamatester** [comment]
The adapter at projects/mintlayer exports TVL: 
        
 
 
    mintlayer                 9.01 M
    
    total                    9.01 M

**Comment by anyxem** [comment]
Since this pull request was made from a company fork, the “Allow edits by maintainers” checkbox is not available. If there are any update requests, please leave a comment, and I will address them promptly. Thank you!

**Comment by llamatester** [comment]
The adapter at projects/mintlayer exports TVL: 
        
 
 
    mintlayer                 9.01 M
    
    total                    9.01 M

**Comment by llamatester** [comment]
The adapter at projects/mintlayer exports TVL: 
        
 
 
    mintlayer                 9.01 M
    
    total                    9.01 M

**Comment by g1nt0ki** [comment]
hi @anyxem 

Sorry, we dont track chain staking atm: https://github.com/DefiLlama/DefiLlama-Adapters/discussions/435 

But if you have any defi apps in production on your chain, we can list those

**Pull request closed without merging**
