### PR TITLE
Update factory address

### PR DESCRIPTION
**Pull request by Kalesberg**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/gammaswap exports TVL: 
        
 
 
    arbitrum                  0
    
    total                    0

**Comment by g1nt0ki** [comment]
hi @Kalesberg I am tracking deltaswap tvl here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/468bde20d8f156991ac85893ac335ae34cb0b003

we leave existing tvl of gammaswap as is? the new version of gammaswap is traded using deltaswap LPs right?

**Comment by Kalesberg** [comment]
> hi @Kalesberg I am tracking deltaswap tvl here: [468bde2](https://github.com/DefiLlama/DefiLlama-Adapters/commit/468bde20d8f156991ac85893ac335ae34cb0b003)
> 
> we leave existing tvl of gammaswap as is? the new version of gammaswap is traded using deltaswap LPs right?

hey @g1nt0ki 
can we reset current gammaswap tvl as the users will migrate their liquidity to the new pools
Also for your other question, currently gammapools are traded using deltaswap pools for now but we will include sushi/uni swap pools soon

**Comment by g1nt0ki** [comment]
hi @Kalesberg we dont like resetting tvl/removing existing data, maybe I can create a new listing called gammaswap v2, or some other sub listing, like what we have for uniswap or aave?

**Comment by llamatester** [comment]
The adapter at projects/gammaswap exports TVL: 
        
 
 
    arbitrum                  5.05 k
    
    total                    5.05 k

**Comment by Kalesberg** [comment]
hi @g1nt0ki 
Thanks for the suggestion

Discussed this in the team, and we would like to continue with the current tvl data in the chart

**Comment by g1nt0ki** [comment]
@Kalesberg I still dont like the idea of removing old pool/tvl, maybe I can update the adapter to count both in a single listing?

**Comment by Kalesberg** [comment]
yes thats fine

**Comment by 0xDanr** [comment]
I think there's a problem in your tvl calculation. Our TVL is actually 589k not 490k.

Our TVL is calculated as such, people deposited 589K into GammaSwap and that 589K was routed to DeltaSwap. So GammaSwap held 589K of liquidity in DeltaSwap. The TVL of GammaSwap and DeltaSwap is therefore both 589k

Then about 100k was borrowed out of GammaSwap, by removing that 100k of liquidity from DeltaSwap (reserve tokens: weth, usdc, arb, etc.) and held inside the GammaSwap smart contract as collateral with a very small additional amount of collateral to overcollateralize the loans. Therefore the TVL of DeltaSwap goes down by 100k, but the TVL of GammaSwap remains at 589k.

Therefore GammaSwap's TVL remains at 589k, since there's still 589k worth of tokens inside the GammaSwap smart contract, not the 490k you guys are showing in DefiLlama.

Please let me know if you still need further clarification.

**Comment by g1nt0ki** [comment]
hi @Kalesberg @0xDanr I have updated the code here so, we count gammaswap tvl in both factories: https://github.com/DefiLlama/DefiLlama-Adapters/commit/c0e1339c71799e160cbb9b94f74ab7802e87203c

But deltaswap tvl is excluded, since it has a separate listing, but in the end, both will be added and shown in the parent page: https://defillama.com/protocol/gammaswap-protocol

**Pull request closed without merging**
