### PR TITLE
dddx

### PR DESCRIPTION
**Pull request by DDDXio**
Twitter Link: https://twitter.com/DDDX_io

List of audit links if any: https://www.certik.com/projects/dddx-io

Website Link: https://dddx.io/

Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://dddx.io/tokens/govToken.png

Current TVL:
222,974,296 USD

Chain:
BNB Chain

Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

Short Description (to be shown on DefiLlama):
DDDX Protocol is a new decentralized exchange with dual AMM algorithm that supporting voting escrow tokenomics

Token address and ticker if any:
0x4B6ee8188d6Df169E1071a7c96929640D61f144f
https://github.com/DDDXio

Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
TWAP

forkedFrom (Does your project originate from another project):

methodology (what is being counted as tvl, how is tvl being calculated):
Liquidity Pool + DDDX Vaule Locked

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/dddxswap/index.js exports TVL: 
        
 
 
    bsc                       352.99 M
    
    total                    352.99 M

**Comment by DDDXio** [comment]
The data above is accurate.

When will DDDX.io be added to the BSC project list. Is there a specific
time? Also, is there anything else we need to provide?

llamatester ***@***.***> 于2022年4月8日周五 17:44写道：

**Comment by waynebruce0x** [comment]
Hey guys I was just looking at writing an onchain adapter and I had some feedback on the UI, hope you dont mind. When I click 'swap' on https://dddx.io/ before connecting to wallet, I get stuck on a loading wheel and I cant click anywhere to get off it

**Comment by DDDXio** [comment]
We are concerned about the feedback on related issues and will update to resolve this issue as soon as possible.

When can DDDX be added to the list? Is there any timetable for this? Are there any difficulties that affect the progress of this work? Do you need any support from us? If you have any needs, please feel free to contact us.

**Comment by waynebruce0x** [comment]
I can find 160M in the uni market, and 2M staking dddx, is there anything else?

**Comment by DDDXio** [comment]
These are enough. Just these two data, no others.
When will DDDX be added to the list?

waynebruce0x ***@***.***> 于2022年4月9日周六 23:52写道：

**Comment by waynebruce0x** [comment]
today

**Comment by waynebruce0x** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters/pull/2207

**Pull request closed without merging**
