### PR TITLE
Update Chintai/CHEX adapter

### PR DESCRIPTION
**Pull request by davidespataro**
##### Logo (High resolution, will be shown with rounded borders): 
image

##### Short Description (to be shown on DefiLlama):
Chintai is a licensed and regulated tokenization platform built for financial institutions. Powered by the $CHEX token, Chintai offers a fully integrated and compliant white-label solution for seamlessly tokenizing a wide range of real-world assets (RWAs).

##### Token address and ticker if any:
Ticker - $CHEX
Token Address (multichain token so multiple CA's)
Contract address (EOS): chexchexchex
Contract address (ETH): 0x9Ce84F6A69986a83d92C324df10bC8E64771030f
Contract address (BSC): 0x9Ce84F6A69986a83d92C324df10bC8E64771030f
Contract address (SOL): 6dKCoWjpj5MFU5gWDEFdpUUeBasBLK3wLEwhUzQPAa1e
Contract address (BASE): 0xc43f3ae305a92043bd9b62ebd2fe14f7547ee485

##### Category (full list at https://defillama.com/categories) *Please choose only one:
[RWA](https://defillama.com/protocols/RWA)

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/chintai: 
        
 
  
    
    
    Error: Failed to get https://sg.app.chintai.io/api/stats
    Truncated error stack:
    
        at get (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/http.js:33:11)
        at async chintaiTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/chintai/index.js:88:17)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:145:9
        at async Promise.all (index 0)
        at async Promise.all (index 6)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:188:3

**Comment by llamatester** [comment]
Error while running adapter at projects/chintai: 
        
 
  
    
    
    Error: Failed to get https://sg.app.chintai.io/api/stats
    Truncated error stack:
    
        at get (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/http.js:33:11)
        at async chintaiTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/chintai/index.js:117:17)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:145:9
        at async Promise.all (index 0)
        at async Promise.all (index 6)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:188:3

**Comment by llamatester** [comment]
Error while running adapter at projects/chintai: 
        
 
  
    
    
    Error: Failed to get https://sg.app.chintai.io/api/stats
    Truncated error stack:
    
        at get (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/http.js:33:11)
        at async chintaiTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/chintai/index.js:117:17)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:145:9
        at async Promise.all (index 0)
        at async Promise.all (index 6)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:188:3

**Comment by llamatester** [comment]
Error while running adapter at projects/chintai: 
        
 
  
    
    
    Error: Failed to get https://sg.app.chintai.io/api/stats
    Truncated error stack:
    
        at get (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/http.js:33:11)
        at async chintaiTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/chintai/index.js:112:17)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:145:9
        at async Promise.all (index 0)
        at async Promise.all (index 6)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:188:3

**Comment by llamatester** [comment]
Error while running adapter at projects/chintai: 
        
 
  
    
    
    Error: Failed to get https://sg.app.chintai.io/api/stats
    Truncated error stack:
    
        at get (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/http.js:33:11)
        at async chintaiTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/chintai/index.js:112:17)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:145:9
        at async Promise.all (index 0)
        at async Promise.all (index 6)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:188:3

**Comment by llamatester** [comment]
Error while running adapter at projects/chintai: 
        
 
  
    
    
    Error: Failed to get https://sg.app.chintai.io/api/stats
    Truncated error stack:
    
        at get (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/http.js:33:11)
        at async chintaiTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/chintai/index.js:112:17)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:145:9
        at async Promise.all (index 0)
        at async Promise.all (index 6)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:188:3

**Comment by llamatester** [comment]
Error while running adapter at projects/chintai: 
        
 
  
    
    
    Error: Failed to get https://sg.app.chintai.io/api/stats
    Truncated error stack:
    
        at get (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/http.js:33:11)
        at async chintaiTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/chintai/index.js:113:17)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:145:9
        at async Promise.all (index 0)
        at async Promise.all (index 6)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:188:3

**Comment by g1nt0ki** [comment]
closing this for now, will review once you put up a PR when it is ready for review

**Pull request closed without merging**
