### PR TITLE
Update GLIF Project adapter

### PR DESCRIPTION
**Pull request by Schwartz10**
- Offload more work to a server to allow DeFiLlama frontend to perform better (the Filecoin TVL is a heavy computation at this stage due to our scale)
- Fix bug in TVL calculation (we will report incorrect data through the website and can backfill historically to get fresh, accurate data since GLIF's launch)
- Add timetravel and start timestamp
- Add hallmarks 

*NOTE to the maintainers* - when I test this adapter and return a `0` for TVL, the test fails. Even attempting to hardcode any value in this call:

`api.add(nullAddress, tvl);` 

such as:

`api.add(nullAddress, "0");`<br />
`api.add(nullAddress, 0);`<br />
`api.add(nullAddress, new BN(0));`<br />

All fail - is this something we're doing wrong on our side?

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/glif exports TVL: 
        
 
 
    filecoin                  312.48 M
    
    total                    312.48 M

**Comment by llamatester** [comment]
The adapter at projects/glif exports TVL: 
        
 
 
    filecoin                  312.48 M
    
    total                    312.48 M

**Comment by llamatester** [comment]
Error while running adapter at projects/glif: 
        
 
  
    
    
    TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:138:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
Error while running adapter at projects/glif: 
        
 
  
    
    
    TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:138:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by waynebruce0x** [comment]
there seems to be an issue with the latest commit

**Comment by llamatester** [comment]
Error while running adapter at projects/glif: 
        
 
  
    
    
    Error: Failed to get https://events.glif.link/pool/0/tvl?height=undefined
    Truncated error stack:
    
        at get (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/http.js:33:11)
        at async tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/glif/index.js:14:23)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:49:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:139:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:182:3

**Comment by llamatester** [comment]
The adapter at projects/glif exports TVL: 
        
 
 
    filecoin                  318.16 M
    
    total                    318.16 M

**Comment by Schwartz10** [comment]
Hey @waynebruce0x all set now!

**Pull request merged**
