### PR TITLE
Add LanternSwap TVL

### PR DESCRIPTION
**Pull request by johnnythedev1231**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): 

llogo-modified

##### Short Description (to be shown on DefiLlama):
The stableswap for Kava

##### methodology (what is being counted as tvl, how is tvl being calculated):
Lanternswap is designed for extremely efficient stablecoin trading

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/lanternswap exports TVL: 
        
 
 
    kava                      0
    
    total                    0

**Comment by waynebruce0x** [comment]
TVL has to be non-zero to be listed

**Comment by johnnythedev1231** [comment]
The Tvl is now non-zero @llamatester @waynebruce0x can we merge it in now?

**Comment by llamatester** [comment]
The adapter at projects/lanternswap exports TVL: 
        
 
 
    kava                      1.499449859152
    
    total                    1.499449859152

**Pull request merged**
