### PR TITLE
[Bucket] Farming pool balance

### PR DESCRIPTION
**Pull request by Jarekkkkk**

### CODE REVIEW

**Comment by llamabutler** [comment]
The adapter at projects/bucket-protocol exports TVL: 
        
 
 
    sui                       44.84 M
    
    total                    44.84 M

**Comment by g1nt0ki** [comment]
thanks for the PR, we will create a new sublisting for the farm

**Comment by Jarekkkkk** [comment]
> thanks for the PR, we will create a new sublisting for the farm

thanks sir, btw what will be the name for the sublisting ?

**Comment by g1nt0ki** [comment]
maybe "Bucket Protocol - Farm"?

**Comment by Jarekkkkk** [comment]
> maybe "Bucket Protocol - Farm"?

we would like to go with **Bucket Protocol - Airdrop Farm**

**Pull request closed without merging**
