### PR TITLE
Add HebeSwap

### PR DESCRIPTION
**Pull request by HebeBlock**
##### Twitter Link:
https://twitter.com/BlockHebe

##### Website Link:
https://hebeswap.com

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://app.hebeswap.com/logo.png

##### Current TVL:
$499.60 k 

##### Chain:
EthereumClassic (ETC)

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

##### Short Description (to be shown on DefiLlama):
Hebeswap is a protocol for automated token exchange on Ethereum Classic. It was launched on December 29, 2021. Hebeswap a simple smart contract interface for swapping ERC20 tokens. It has a formalized model for pooling liquidity reserves. It serves as an open-source frontend interface for traders and liquidity providers and is committed to providing free and decentralized asset exchange.

##### Token address and ticker if any:
Token address 0x88d8C3Dc6B5324f34E8Cf229a93E197048671abD
Ticker HEBE

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
N/A

##### forkedFrom (Does your project originate from another project):
uniswap

##### methodology (what is being counted as tvl, how is tvl being calculated):
liquidity on the dexes

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/hebeswap/index.js: 
        
 
  
    
    
    Error: missing revert data in call exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (code=CALL_EXCEPTION, version=providers/5.6.1)
        at Logger.makeError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/logger/lib/index.js:233:21)
        at Logger.throwError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/logger/lib/index.js:242:20)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:652:52
        at Array.forEach (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:632:61
        at step (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:48:23)
        at Object.next (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:29:53)
        at step (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:33:139)
        at Object.next (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:29:53)
        at fulfilled (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:20:58) {
      reason: 'missing revert data in call exception',
      code: 'CALL_EXCEPTION'
    }

**Comment by HebeBlock** [comment]
HI, we run "node test.js projects/HebeSwap/index.js" locally, there is no problem, the TVL is successfully calculated

image

**Comment by Cocoahomology** [comment]
may be RPC problem

locally, using this provider works for me: https://www.ethercluster.com/etc

this one doesn't: https://blockscout.com/etc/mainnet/api/eth-rpc

**Comment by HebeBlock** [comment]
> https://blockscout.com/etc/mainnet/api/eth-rpc
Since the last blockscout update, only some simple rpc were provided.
https://blockscout.com/etc/mainnet/eth-rpc-api-docs

**Comment by realdealshaman** [comment]
I've made some updates to our sdk and got it to work locally, going to merge it and make some minor syntax changes that should get it work and allow it to get listed

**Pull request merged**
