### PR TITLE
Update file to calculate TVL on Arbitrum after launch

### PR DESCRIPTION
**Pull request by ayush-tm**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/astra-dao: 
        
 
  
    
    
    Error: 
        Unknown chain(s): atbitrum
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file

**Comment by llamatester** [comment]
Error while running adapter at projects/astra-dao: 
        
 
  
    
    
    Error: Failed to call baseStableCoin() target: 0x8e265fF847CC660Cd89786D4308076a9f921428f on chain: [ethereum] rpc: https://eth-mainnet.gateway.pokt.network/v1/5f3453978e354ab992c4da79  call reverted    
    Truncated error stack:

**Comment by llamatester** [comment]
The adapter at projects/astra-dao exports TVL: 
        
 
 
    arbitrum-staking          2.00 M
    arbitrum-pool2            261.77353117399514
    arbitrum                  85.95 k
    staking                   2.00 M
    pool2                     261.77353117399514
    
    total                    85.95 k

**Comment by llamatester** [comment]
The adapter at projects/astra-dao exports TVL: 
        
 
 
    arbitrum-staking          2.10 M
    ethereum                  1.02 k
    arbitrum-pool2            269.93549373828284
    arbitrum                  87.39 k
    staking                   2.10 M
    pool2                     269.93549373828284
    
    total                    88.41 k

**Comment by realdealshaman** [comment]
Hi @ayush-tm, thanks for the pull request! I updated it a bit so we can keep ethereum; Otherwise, the historical will be counted incorrectly in Arbitrum by only having arbitrum in the adapter.

**Pull request merged**
