### PR TITLE
Fix Yupana contract address

### PR DESCRIPTION
**Pull request by aguillon**
The Yupana lending protocol on Tezos has changed its contracts and asked users to migrate their assets: https://twitter.com/YupanaFinance/status/1739216683728797802

You can check the new contract address here: https://tzkt.io/KT1CojtgtVHVarS135fnV3y4z8TiKXrsRHJr/operations/ . Unfortunately, I haven't been able to find it in the documentation, but the test result should be pretty convincing.

Edit: actually check balances here https://tzkt.io/KT1CojtgtVHVarS135fnV3y4z8TiKXrsRHJr/balances/

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/yupana exports TVL: 
        
 
 
    tezos                     416.11 k
    tezos-borrowed            86.28 k
    borrowed                  86.28 k
    
    total                    416.11 k

**Comment by llamatester** [comment]
The adapter at projects/yupana exports TVL: 
        
 
 
    tezos                     442.17 k
    tezos-borrowed            94.73 k
    borrowed                  94.73 k
    
    total                    442.17 k

**Comment by g1nt0ki** [comment]
@aguillon thanks for the PR, I changed it a bit so we dont skip the tvl in old contract

**Comment by aguillon** [comment]
Even better. Thank you!

**Pull request merged**
