### PR TITLE
feat:Add vASTR in staking and update for stable swap

### PR DESCRIPTION
**Pull request by killbond007**
feat: Add vASTR in staking and update for stable swap

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bifrost-dex exports TVL: 
        
 
 
    bifrost                   862.89 k
    
    total                    862.89 k

**Comment by llamatester** [comment]
The adapter at projects/bifrost-liquid-crowdloan exports TVL: 
        
 
 
    bifrost                   19.62 M
    
    total                    19.62 M

**Comment by llamatester** [comment]
The adapter at projects/bifrost-staking exports TVL: 
        
 
 
    bifrost                   61.30 M
    filecoin                  686.44 k
    ethereum                  5.65 M
    
    total                    67.64 M

**Comment by killbond007** [comment]
Screenshot 2024-01-02 at 08 46 56
Hello DefiLlama, for bifrost-dex TVL we test for it , should 11.44 M

**Pull request merged**
