### PR TITLE
Alphadex DEX Listing

### PR DESCRIPTION
**Pull request by alphadex1**
Listing Commit

##### Twitter Link:
https://www.twitter.com/thealpdadex

##### Website Link:
https://app.alphadex.io/en/swap

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://ibb.co/ggC0Y5r

##### Current TVL:
$ 595,000 Moonriver

##### Chain:
Moonriver

##### Short Description (to be shown on DefiLlama):
Alphadex is an innovative decentralized AMM, Incubator,Yield Farming & NFT Launch solution powered by & Ethereum.

##### Token address and ticker if any:
0x8E7Cd893D8f371051a39aA65976Bca22d7b02A60 and ROAR

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
DEX

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
API3

##### forkedFrom (Does your project originate from another project):
NO

##### methodology (what is being counted as tvl, how is tvl being calculated):
Computed TVL using Alphadex Subgraphs

### CODE REVIEW

**Comment by waynebruce0x** [comment]
We prefer to avoid thegraph because everything breaks when thegraph falls behind current block. If you can send me your factory address I'll have a go at writing an on-chain adapter for you?

**Comment by alphadex1** [comment]
Thank you for your kind Suggestion. 
AlphadexV1Factory : 0xdD9EFCbDf9f422e2fc159eFe77aDD3730d48056d

**Comment by waynebruce0x** [comment]
btw your analytics page contract links all point to bscscan

**Comment by waynebruce0x** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters/pull/1408 This reports $863k. Please jump in the discord if you have any comments / questions. I'll close this PR

**Pull request closed without merging**
