### PR TITLE
Add unipilot polygon tvl

### PR DESCRIPTION
**Pull request by BilalMir135**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/unipilot exports TVL: 
        
 
 
    ethereum-staking          180.24 k
    ethereum                  378.28 k
    polygon                   8.17 k
    staking                   180.24 k
    
    total                    386.45 k

**Comment by g1nt0ki** [comment]
@BilalMir135 is there some other way to get vault list without relying on logs? fetching logs becomes expensive as # blocks increases and so we dont like to use it for chains other than ethereum

**Comment by BilalMir135** [comment]
@g1nt0ki we are using subgraph for indexing data. Can i use it for polygon vaults?

**Comment by g1nt0ki** [comment]
yes, that sounds like a good idea, thanks for understanding

**Comment by llamatester** [comment]
The adapter at projects/unipilot exports TVL: 
        
 
 
    ethereum-staking          199.81 k
    polygon                   10.07 k
    ethereum                  389.15 k
    staking                   199.81 k
    
    total                    399.21 k

**Comment by g1nt0ki** [comment]
> @g1nt0ki polygon vaults extraction has now shifted to subgraph by @HamzaBhatti125. You can review his commit ([faccebd](https://github.com/DefiLlama/DefiLlama-Adapters/pull/4337/files/e35846eaade152e4a2e39a9e3d42f1bffd3a7ec0..facc2bdb8f5fa0e1e45d12471a995dc2f29d0af7)). Thanks

looks good, thanks for the PR

**Pull request merged**
