### PR TITLE
Feat: add ashswap

### PR DESCRIPTION
**Pull request by dado0612**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Methodology (what is being counted as tvl, how is tvl being calculated):
- We use the total value of tokens locked in Ashswap pools for TVL of our protocol.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/ashswap: 
        
 
  
    
    
    Cannot query field "defillama" on type "Query".
    Truncated error stack:
    Error: Cannot query field "defillama" on type "Query".: {"response":{"errors":[{"message":"Cannot query field \"defillama\" on type \"Query\".","locations":[{"line":3,"column":3}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"defillama\" on type \"Query\".","    at Object.Field (/usr/src/app/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)","    at Object.enter (/usr/src/app/node_modules/graphql/language/visitor.js:301:32)","    at Object.enter (/usr/src/app/node_modules/graphql/utilities/TypeInfo.js:391:27)","    at visit (/usr/src/app/node_modules/graphql/language/visitor.js:197:21)","    at validate (/usr/src/app/node_modules/graphql/validation/validate.js:91:24)","    at validate (/usr/src/app/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)","    at processGraphQLRequest (/usr/src/app/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async processHTTPRequest (/usr/src/app/node_modules/apollo-server-core/dist/runHttpQuery.js:220:30)"]}}}],"status":400,"headers":{}},"request":{"query":"\n{\n  defillama {\n    totalValueStakedUSD\n  }\n}\n"}}

**Comment by realdealshaman** [comment]
@dado0612 Hi, thanks for the PR, Is your protocol live? The graph query seems to be returning 0 tvl

**Comment by dado0612** [comment]
Sorry sir, on 18 Feb 16, UTC users are allowed to farm, so staking value will increase from this time.

**Comment by dado0612** [comment]
@realdealshaman  hi sir, sorry about that but we have updated some information for our protocol. Please use the latest version from this comment https://github.com/DefiLlama/DefiLlama-Adapters/pull/5359#issue-1589120151 for your site

**Comment by realdealshaman** [comment]
@dado0612  updated the description, please let me know if anything else needs to be updated as well

**Comment by dado0612** [comment]
@realdealshaman ty for response.
On your page, I see our token address is wrong. It should be `ASH-a642d1`, but on your site is `a642d1`.
Please update our token address for more convenient.

**Pull request merged**
