### PR TITLE
NemoSwap (Renec Chain) adapter

### PR DESCRIPTION
**Pull request by kientt6034**
##### Name (to be shown on DefiLlama):
```NemoSwap```

##### Twitter Link:
```https://twitter.com/NemoSwapDEX```

##### List of audit links if any:
```https://github.com/verichains/public-audit-reports/blob/main/Verichains%20Public%20Audit%20Report%20-%20NemoSwap%20Smartcontracts%20-%20v1.0.pdf```

##### Website Link:
```[https://nemo.renec.org](https://nemo.renec.org/vi)```

##### Logo (High resolution, will be shown with rounded borders):
```https://drive.google.com/file/d/1fpV6eXP_pVJkLH-atf8RrhKFzafahrtc/view?usp=sharing```

##### Current TVL:
```$402.52k```

##### Treasury Addresses (if the protocol has treasury)
```Bxiea1rZyN7msNuWiMduF8Gi7NRhpFfcS9KfMAViqhFt```

##### Chain:
```RENEC Network```

##### Short Description (to be shown on DefiLlama):
```NemoSwap is the first DEX on the RENEC blockchain. Easily convert between Fiat and Cryptocurrencies with gasless transactions and low trading fee```

##### Category (full list at https://defillama.com/categories) *Please choose only one:
```https://defillama.com/protocols/Dexes```

##### forkedFrom (Does your project originate from another project):
```https://www.orca.so/```

##### methodology (what is being counted as tvl, how is tvl being calculated):
```TVL quantifies the total tokens deposited into a protocol as liquidity, a feature seen in platforms like Orca. Renec, our native coin, and ReUSD, our stablecoin, are not only listed and supported on various exchanges but are also prominently backed by Remitano.```

##### Github org/user (Optional, if your code is open source, we can track activity):
```https://github.com/renec-chain/nemo-swap```

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/nemoswap exports TVL: 
        
 
 
    renec                     402.37 k
    
    total                    402.37 k

**Comment by llamatester** [comment]
The adapter at projects/nemoswap exports TVL: 
        
 
 
    renec                     402.68 k
    
    total                    402.68 k

**Comment by llamatester** [comment]
The adapter at projects/nemoswap exports TVL: 
        
 
 
    renec                     402.65 k
    
    total                    402.65 k

**Comment by llamatester** [comment]
The adapter at projects/nemoswap exports TVL: 
        
 
 
    renec                     398.64 k
    
    total                    398.64 k

**Comment by llamatester** [comment]
The adapter at projects/nemoswap exports TVL: 
        
 
 
    renec                     398.72 k
    
    total                    398.72 k

**Comment by g1nt0ki** [comment]
@kientt6034 thanks for the PR, I added a small hack to avoid duplicate code

**Pull request merged**
