### PR TITLE
Frankencoin

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/frankencoin exports TVL: 
        
 
 
    ethereum                  339.99 k
    
    total                    339.99 k

**Comment by holy-pengy** [comment]
https://defillama.com/protocol/frankcoin
@g1nt0ki 
Project name and token ticker is wrong
Name should be `FrankenCoin` and ticker is `ZCHF`.

**Comment by holy-pengy** [comment]
https://defillama.com/protocol/frankencoin
@g1nt0ki 
Can you pls take care of the ticker again?
It is still wrong.
Our token tick is `ZCHF`, but on defillama it says `ZCHIF`.
There should be no `I` between H and F.
image

**Comment by g1nt0ki** [comment]
@holy-pengy it is fixed now https://github.com/DefiLlama/defillama-server/commit/5dd5af2dfd16fcb23c7210980f491167187f6f15

**Pull request merged**
