### PR TITLE
Tenx

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/tenx-exchange exports TVL: 
        
 
 
    tenet                     114.24 k
    
    total                    114.24 k

**Comment by bulbazavr1024** [comment]
@g1nt0ki thanks a lot!

**Comment by bulbazavr1024** [comment]
@g1nt0ki Oh. There are two different projects in one branch. I think that's my mistake. There were tenx(first Dex on tenet network) and tendieswap (second dex on tenet network). Can you add it too ? Or I can do it by myself

**Comment by g1nt0ki** [comment]
> @g1nt0ki Oh. There are two different projects in one branch. I think that's my mistake. There were tenx(first Dex on tenet network) and tendieswap (second dex on tenet network). Can you add it too ? Or I can do it by myself

okay, I thought second was a mistake since the factory contract was the same, added it now

**Comment by bulbazavr1024** [comment]
@g1nt0ki 
Tenx factory: 0xbaB158ED71F7FD4AD43b1db1aAc5d0EFA0a8469f
Tendieswap factory: 
0x2D2ee1a4aec9f3c8c14dFcE837e1C89b639dd1E4, right ?
Sorry for being so disturbing

**Comment by g1nt0ki** [comment]
> @g1nt0ki Tenx factory: 0xbaB158ED71F7FD4AD43b1db1aAc5d0EFA0a8469f Tendieswap factory: 0x2D2ee1a4aec9f3c8c14dFcE837e1C89b639dd1E4, right ? Sorry for being so disturbing

yeah, added the second one here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/d10f80ce30d88b83868a21c9751bbafca5eb123e

it was duplicate here
https://github.com/DefiLlama/DefiLlama-Adapters/pull/6767/files#diff-2aa4e3fca7e7a094709be05d46254e39687486d2ebb9f5c68f926194dfad15c5R3

**Comment by bulbazavr1024** [comment]
> > @g1nt0ki Tenx factory: 0xbaB158ED71F7FD4AD43b1db1aAc5d0EFA0a8469f Tendieswap factory: 0x2D2ee1a4aec9f3c8c14dFcE837e1C89b639dd1E4, right ? Sorry for being so disturbing
> 
> yeah, added the second one here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/d10f80ce30d88b83868a21c9751bbafca5eb123e
> 
> it was duplicate here
> https://github.com/DefiLlama/DefiLlama-Adapters/pull/6767/files#diff-2aa4e3fca7e7a094709be05d46254e39687486d2ebb9f5c68f926194dfad15c5R3

Thanks 🙏

**Pull request merged**
