### PR TITLE
USDY: adding aptos tvl + combining usdyc tvl with usdy

### PR DESCRIPTION
**Pull request by lililud**
## Note
USDY has a 40 day holding period before it is officially minted. Therefore, since it represents USDY, we wanted to combine the tvl in the Defillama UI so it only shows 1 token.

**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

### CODE REVIEW

**Comment by lililud** [comment]
### NOTE 
aptos TVL should be at 100 right now. it's showing as unrecognized when running the test.

```
Balance table for [aptos] Unrecognized tokens
┌─────────┬──────┬────────┬─────────┬────────────────────────────────────────────────────────────────────────────┬──────────┐
│ (index) │ name │ symbol │ balance │                                   label                                    │ decimals │
├─────────┼──────┼────────┼─────────┼────────────────────────────────────────────────────────────────────────────┼──────────┤
│    0    │ '-'  │  '-'   │   100   │ 'aptos:0xcfea864b32833f157f042618bd845145256b1bf4c0da34a7013b76e42daa53cc' │   null   │
```

**Comment by llamatester** [comment]
The adapter at projects/ondofinance exports TVL: 
        
 
 
    ethereum                  324.82 M
    solana                    54.34 M
    mantle                    41.87 M
    polygon                   11.29 M
    sui                       8.15 M
    aptos                     0
    
    total                    440.47 M

**Comment by llamatester** [comment]
The adapter at projects/ondofinance exports TVL: 
        
 
 
    ethereum                  324.67 M
    solana                    54.29 M
    mantle                    41.83 M
    polygon                   11.29 M
    sui                       8.14 M
    aptos                     105
    
    total                    440.23 M

**Comment by g1nt0ki** [comment]
@lililud thanks for the PR

**Pull request merged**
