### PR TITLE
Connext: update adapter

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/connext exports TVL: 
        
 
 
    moonriver                 1.20 M
    avalanche                 2.40 M
    moonbeam                  3.04 M
    arbitrum                  1.51 M
    ethereum                  3.15 M
    xdai                      2.49 M
    optimism                  1.31 M
    bsc                       3.31 M
    milkomeda                 169.05 k
    boba                      19.18 k
    evmos                     1.69 M
    harmony                   466.28 k
    fantom                    9.35 M
    fuse                      827.05 k
    polygon                   3.70 M
    cronos                    925.45 k
    
    total                    35.55 M

**Comment by llamatester** [comment]
The adapter at projects/mahadao exports TVL: 
        
 
 
    ethereum-pool2            207.19 k
    ethereum                  240.45708
    bsc                       727.32 k
    bsc-pool2                 773.48 k
    polygon-staking           2.03 M
    polygon-pool2             475.63 k
    polygon                   719.82 k
    pool2                     1.46 M
    staking                   2.03 M
    
    total                    1.45 M

**Comment by llamatester** [comment]
The adapter at projects/connext exports TVL: 
        
 
 
    xdai                      2.49 M
    avalanche                 2.40 M
    moonriver                 1.20 M
    moonbeam                  3.04 M
    boba                      19.18 k
    optimism                  1.31 M
    milkomeda                 169.05 k
    arbitrum                  1.51 M
    evmos                     1.70 M
    bsc                       3.31 M
    harmony                   466.28 k
    ethereum                  3.14 M
    fantom                    9.35 M
    fuse                      827.05 k
    polygon                   3.70 M
    cronos                    925.45 k
    
    total                    35.55 M

**Comment by llamatester** [comment]
The adapter at projects/mahadao exports TVL: 
        
 
 
    ethereum                  240.45708
    bsc                       727.32 k
    ethereum-pool2            207.19 k
    bsc-pool2                 773.48 k
    polygon-staking           2.03 M
    polygon                   719.82 k
    polygon-pool2             475.63 k
    pool2                     1.46 M
    staking                   2.03 M
    
    total                    1.45 M

**Comment by llamatester** [comment]
The adapter at projects/connext exports TVL: 
        
 
 
    moonbeam                  3.04 M
    moonriver                 1.20 M
    xdai                      2.49 M
    optimism                  1.30 M
    boba                      19.15 k
    milkomeda                 168.83 k
    bsc                       3.22 M
    avalanche                 2.39 M
    evmos                     1.74 M
    ethereum                  3.13 M
    harmony                   465.70 k
    arbitrum                  1.50 M
    fuse                      826.10 k
    fantom                    9.34 M
    polygon                   3.70 M
    cronos                    924.49 k
    
    total                    35.45 M

**Comment by llamatester** [comment]
The adapter at projects/mahadao exports TVL: 
        
 
 
    ethereum-pool2            206.66 k
    bsc                       782.58 k
    polygon-staking           2.02 M
    ethereum                  239.19923999999997
    bsc-pool2                 824.79 k
    polygon                   718.22 k
    polygon-pool2             473.79 k
    pool2                     1.51 M
    staking                   2.02 M
    
    total                    1.50 M

**Comment by llamatester** [comment]
The adapter at projects/soluna exports TVL: 
        
 
 
    terra                     14.44 M
    
    total                    14.44 M

**Comment by mahmoodonly** [comment]
- [ ] 

- [ ] [](url)

**Pull request merged**
