### PR TITLE
OMAX Staking | NEW WOMAX

### PR DESCRIPTION
**Pull request by pro100skm**
PLEASE UPDATE Wrapped OMAX address. Old WOMAX causes issue with staking tvl calculation. 

##### Logo (High resolution, will be shown with rounded borders):
https://ibb.co/dcb1r2h

##### Treasury Addresses (if the protocol has treasury)
0xF8872D3C24EBa5198F0AbFd88C2236062CEfe02d

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

omax-token

https://www.coingecko.com/en/coins/omax-token

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

coin id: 13916

https://coinmarketcap.com/currencies/omax-token/

##### Short Description (to be shown on DefiLlama):
Omax Staking Protocol is a DeFi platform that enables users to earn rewards by staking their cryptocurrency assets. Through a secure and transparent smart contract system, Omax facilitates the staking process, allowing participants to contribute to the network's security and governance while earning staking rewards in return.

##### Token address and ticker if any: 
WOMAX 
0x373e4b4E4D328927bc398A9B50e0082C6f91B7bb

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL: TVL in a staking pool is calculated by summing up the total amount of coins staked by participants within that specific pool. 

##### Github org/user (Optional, if your code is open source, we can track activity)
https://github.com/OMAXCHAIN

STAKING CA :

0x3A2DcDc705031eDBD94254ef7CEFB93D8066cC8D

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/omax-swap exports TVL: 
        
 
 
    omax-staking              0
    omax                      15.55 k
    staking                   0
    
    total                    15.55 k

**Comment by realdealshaman** [comment]
@pro100skm I see that WOMAX is still not listed on coingecko, this is why it is not getting priced

**Comment by OMAXCHAIN** [comment]
Hey , But for swap its fetching price isnt womax = omax ??

**Comment by llamatester** [comment]
The adapter at projects/omax-swap exports TVL: 
        
 
 
    omax-staking              2765.60 B
    omax                      211.39 k
    staking                   2765.60 B
    
    total                    211.39 k

**Comment by llamatester** [comment]
The adapter at projects/omax-swap exports TVL: 
        
 
 
    omax-staking              0
    omax                      210.86 k
    staking                   0
    
    total                    210.86 k

**Comment by llamatester** [comment]
The adapter at projects/omax-swap exports TVL: 
        
 
 
    omax-staking              4.48 M
    omax                      207.84 k
    staking                   4.48 M
    
    total                    207.84 k

**Comment by OMAXCHAIN** [comment]
> The adapter at projects/omax-swap exports TVL: 
>         
>  
>  
>     omax-staking              4.48 M
>     omax                      207.84 k
>     staking                   4.48 M
>     
>     total                    207.84 k 
>     
>     

Why the total is 207.84 instead of 4.68 M

**Comment by OMAXCHAIN** [comment]
> new WOMAX is already used, else your tvl wouold be much lower. I have refactored and added your changes here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/d0ece560766330cc8ba9a72288259d496c4bbc70
> 
> 
> 
> Deleting folders here might have side effects and break our server, skipped it. 
> 
> 
> 
> Staking is not automatically included in tvl, we let the users decide, more info: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

Does this mean you cant add coins locked in a contract or staked to be considered as TVL ? Is it atleast possible to show the protocol on tbe staking pool (defillama category) .
But and the end it says we let the users decide ..

**Comment by pro100skm** [comment]
@g1nt0ki  ??

> OMAXCHAIN

**Comment by g1nt0ki** [comment]
image

**Pull request closed without merging**
