### PR TITLE
Add y24 (Yield 24) staking TVL

### PR DESCRIPTION
**Pull request by Yield24**
---
##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/y24 exports TVL: 
        
 
 
    bsc                       0
    bsc-staking               0
    staking                   0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/y24 exports TVL: 
        
 
 
    bsc                       0
    bsc-staking               3.80 k
    staking                   3.80 k
    
    total                    0

**Comment by g1nt0ki** [comment]
@Yield24 thanks for the PR

**Comment by llamatester** [comment]
The adapter at projects/y24 exports TVL: 
        
 
 
    bsc                       0
    bsc-staking               3.80 k
    staking                   3.80 k
    
    total                    0

**Comment by Yield24** [comment]
Thanks for it,  when it will be live on defilama?

**Pull request merged**
