### PR TITLE
Octane

### PR DESCRIPTION
**Pull request by dtmkeng**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

##### Short Description (to be shown on DefiLlama): limit orders > redefined
The most powerful decentralized limit orders on Binance Smart Chain

##### methodology (what is being counted as tvl, how is tvl being calculated):  We count liquidity of all paris through Staking Contract by Masterchef Address

ref: https://github.com/DefiLlama/DefiLlama-Adapters/projects/2#card-71978675

### CODE REVIEW

**Comment by dtmkeng** [comment]
```
--- bsc ---
OCTANE                    3.07 k
BUSD                      2.00 k
Total: 5.07 k

--- tvl ---
OCTANE                    3.07 k
BUSD                      2.00 k
Total: 5.07 k

------ TVL ------
bsc                       5.07 k

total                    5.07 k
```

**Comment by llamatester** [comment]
The adapter at projects/octane exports TVL: 
        
 
 
    bsc                       5.08 k
    
    total                    5.08 k

**Comment by g1nt0ki** [comment]
@dtmkeng thanks for the PR, i have made some changes here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/3338
Moved pool2 and staking to their own export and export tokens in orderbook as tvl

**Comment by dtmkeng** [comment]
@g1nt0ki  ohhh. so thank

**Pull request merged**
