### PR TITLE
update tvl posi exchange ecosystem

### PR DESCRIPTION
**Pull request by MusketPosition**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/positionexchange exports TVL: 
        
 
 
    posichain-staking         373.23 k
    posichain                 373.23 k
    bsc                       0
    bsc-staking               3.01 M
    bsc-pool2                 7.63 M
    staking                   3.38 M
    pool2                     7.63 M
    
    total                    373.23 k

**Comment by realdealshaman** [comment]
Hey @MusketPosition thanks for the PR. Is the Posichain tvl counting the native chain staking of POSI tokens?

**Comment by MusketPosition** [comment]
@realdealshaman I didn't count. We use a bridge from BSC to PosiChain. We lock their Posi tokens in BSC and they will receive native coins (Posi) in Posichain. After that,  users can hold or delegate staking to validators

**Comment by realdealshaman** [comment]
Seems that the 373.23 k is the amount of POSI tokens that are staked with validators, is this correct? We have some info on why we don't count this for any chain here: https://github.com/DefiLlama/DefiLlama-Adapters/discussions/435

**Comment by MusketPosition** [comment]
@realdealshaman 
- `373.23k` is converted to USD. The current total Posi coin staked is `2,875,476 Posi`. 
- My team has one merge request for `defillama-server` at [763](https://github.com/DefiLlama/defillama-server/pull/763) and I read your comment about: `"we will need to include an adapter that returns the tvl of a defi protocol running on posichain"`, that why I counted stake in validators. Now I know you don't count native chain, so I must remove the code I have added or what should I do next? Thanks  😄

**Comment by realdealshaman** [comment]
Yes please, we'll have to close this PR. We need to wait to add a projects that runs on Posichain, were the users have deposited funds into that protocols smart contracts

**Comment by MusketPosition** [comment]
@realdealshaman don't close this PR. I also update the new contract address to update TVL in BSC. Thanks

**Comment by MusketPosition** [comment]
I already updated it, pls check it out and approve. Thanks 😄

**Comment by llamatester** [comment]
The adapter at projects/positionexchange exports TVL: 
        
 
 
    bsc                       0
    bsc-staking               2.98 M
    bsc-pool2                 7.59 M
    staking                   2.98 M
    pool2                     7.59 M
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/positionexchange exports TVL: 
        
 
 
    bsc-staking               2.97 M
    bsc                       0
    bsc-pool2                 7.58 M
    staking                   2.97 M
    pool2                     7.58 M
    
    total                    0

**Pull request merged**
