### PR TITLE
feat(protocols): add pumpx protocol

### PR DESCRIPTION
**Pull request by cxy77xbank**
##### Name (to be shown on DefiLlama):

PumpX


##### Twitter Link:

https://twitter.com/pumpx_io


##### List of audit links if any:


##### Website Link:

https://pumpx.io/


##### Logo (High resolution, will be shown with rounded borders):

![pumpx](https://github.com/DefiLlama/DefiLlama-Adapters/assets/142301877/4a0acf42-5503-453c-8333-389d28c09b00)


##### Current TVL:

```shell
$ node test.js projects/pumpx/index.js                                                                                                                                                                                                                          [13:38:08]
--- ethereum ---
usdt                      13.62 k
Total: 13.62 k 

--- blast ---
usdt                      57.93687899999999
Total: 57.93687899999999 

--- tvl ---
usdt                      13.68 k
Total: 13.68 k 

------ TVL ------
ethereum                  13.62 k
blast                     57.93687899999999

total                    13.68 k
```


##### Treasury Addresses (if the protocol has treasury)


##### Chain:

- Ethereum
- Blast


##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)


##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)


##### Short Description (to be shown on DefiLlama):

| A Peer-to-Peer protocol enables Lending & Earning on NFTs, based on pooling other L2's liquidity together on Blast. The rollout of PumpX is planned in 3 stages, with the Blast Native Yield integrated throughout each phase.


##### Token address and ticker if any:


##### Category (full list at https://defillama.com/categories) *Please choose only one:

NFT Lending


##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
##### Implementation Details: Briefly describe how the oracle is integrated into your project:
##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:

##### forkedFrom (Does your project originate from another project):


##### methodology (what is being counted as tvl, how is tvl being calculated):


##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by cxy77xbank** [comment]
Ref PR: https://github.com/DefiLlama/defillama-server/pull/6129

**Comment by llamatester** [comment]
The adapter at projects/pumpx exports TVL: 
        
 
 
    ethereum                  13.62 k
    blast                     57.93687899999999
    
    total                    13.68 k

**Comment by llamatester** [comment]
The adapter at projects/pumpx exports TVL: 
        
 
 
    blast                     57.93687899999999
    ethereum                  13.62 k
    
    total                    13.68 k

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
we cant count offers as tvl, we are not doing it for other protocols, if your protocol supports buy now and pay later option, the NFTs are locked till the loan is paid off right? if you share the smart contract where they are locked, we can count their value as tvl

**Comment by cxy77xbank** [comment]
> we cant count offers as tvl, we are not doing it for other protocols, if your protocol supports buy now and pay later option, the NFTs are locked till the loan is paid off right? if you share the smart contract where they are locked, we can count their value as tvl

Can I listen to the `Approval` event of WETH and use the `Allowance` approved to our contract as the TVL? @g1nt0ki

**Comment by g1nt0ki** [comment]
> > we cant count offers as tvl, we are not doing it for other protocols, if your protocol supports buy now and pay later option, the NFTs are locked till the loan is paid off right? if you share the smart contract where they are locked, we can count their value as tvl
> 
> Can I listen to the `Approval` event of WETH and use the `Allowance` approved to our contract as the TVL? @g1nt0ki

Sorry but no, only tokens on your smart contract count towards your tvl

**Comment by g1nt0ki** [comment]
closing this as there was no response

**Pull request closed without merging**
