### PR TITLE
Fetch adapter for StreamFlow

### PR DESCRIPTION
**Pull request by kredenac**
Hello DefiLlama Reviewers! Here's the info for StreamFlow:

##### Twitter Link:
https://twitter.com/streamflow_fi

##### List of audit links if any:
https://github.com/streamflow-finance/rust-sdk/blob/main/protocol_audit.pdf

##### Website Link:
https://streamflow.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
- https://static-content-23313.s3.amazonaws.com/logo.c4294b7c.png

##### Current TVL:
$112M

##### Chain:
Solana

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
- N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
- N/A

##### Short Description (to be shown on DefiLlama):
Streamflow brings streamed token vesting and batch payments to Solana. Making token streams the ultimate way to distribute value.

##### Token address and ticker if any:
- N/A

##### Category (full list at https://defillama.com/categories) *Please choose only one:
[Services](https://defillama.com/protocols/Services)

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
- N/A

##### forkedFrom (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated):
 Endpoint for fetching TVL is open sourced at: https://github.com/streamflow-finance/analytics/
 1. It uses CoinGecko to fetch token prices
 2. Fetches data from Solana for 2 streamflow programs
 3. The server multiplies the token price by the amount of tokens in the program and sums them up

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@kredenac thanks for the PR, can you change it to on chain adapter instead, we have some helper functions for solana and already some protocols using it. I could also help you out if you are struck/need help with the change.

Regarding tvl calculation, sorry, right now we doing include token vesting in tvl, only LP vesting. Reason for this is, some protocols abuse this

**Comment by nemanjab17** [comment]
hey @g1nt0ki lead dev from Streamflow here, can we go through the abusals and check if they apply within our case? I'll be happy to run you through the code base and assist in any way. 

We take a lot of care to display correct data and have reputation to maintain, giving us no reason to tinker with data.

Reasons for not going with on chain adapter are: 
- we have 2 forks of different versions of program
- we already have an internal system [here]( https://github.com/streamflow-finance/analytics/)
- our contracts evolve and so is the logic for calculating TVL, we want one single source of truth to maintain as we grow

It is instrumental to us to be added to defi lama dashboard to showcase hard work the team put into the product.

**Comment by 0xngmi** [comment]
We don't track any tokens that are not circulating, thus team and investors vesting tokens must be excluded from our tvl calculation, you can find that we apply this to similar products, like team finance and our own llamapay.

We don't accept fetch adapters because they are too obscure, sorry but you'll have to convert your adapter to be on-chain if you want to be listed on defillama

**Comment by nemanjab17** [comment]
I understand the first point, but can you confirm your consistency given there are multiple projects with api exposed to adapter like hubble? Is this applied to some projects and how do you choose this?

**Comment by nemanjab17** [comment]
What does too obscure means if you have full visibility of the methodology available? And our full comitment to help with any further questions? Im sorry too but your arguments are pretry vague and unsupported. Are decisions for being listed fully centralized within your team? Your approach sounds awfully like censorship and i got the idea that the product is fair and inclusive. Please  provide more details for both not includinfgocked tokens in Total value LOCKED (TVL) or link any explanations to others for the same question. I dont want to waste your time but please help me out here.

**Comment by g1nt0ki** [comment]
@nemanjab17 

Q1: I understand the first point, but can you confirm your consistency given there are multiple projects with api exposed to adapter like hubble? Is this applied to some projects and how do you choose this?

A: We have supported fetch adapters in the past, no longer. I am in the process changing them to on chain adapters, you can see that half my PRs last week are converting them on chain: https://github.com/DefiLlama/DefiLlama-Adapters/pulls?q=is%3Apr+author%3Ag1nt0ki 

The more fetch adapters we add, the more one of us have to re-write in the future. hence we are accepting only on chain adapters for new listings.

Q: What does too obscure means if you have full visibility of the methodology available?

A: with a fetch adapter, you can later change your mind what is considered a tvl and update the api, we would not even realise, with on chain, any change would go through the review process

Statment: Im sorry too but your arguments are pretry vague and unsupported. Are decisions for being listed fully centralized within your team?

A: See answer to Q1, also, again this is a standard we apply to all protocols, check the tvl stated on team finance/unicrypt and compare it to tvl on our site, we are not singling you out, we are asking you to follow the same rules we are setting for others.

**Comment by 0xngmi** [comment]
> Please provide more details for not including locked tokens in Total value LOCKED (TVL) or link any explanations to others for the same question.

You can find this here: https://docs.llama.fi/list-your-project/readme#our-methodology

**Comment by 0xngmi** [comment]
The reasoning is simple: tokens not yet circulating are tokens that dont exist yet and could be printed infinitely to inflate TVL.

I can issue a new token with 1bn supply, put 1 in an LP that prices it at 1$, and the rest into a protocol. Magically i've pumped a protocol's TVL to 1bn$.

Clearly you'll agree that this isn't right

**Comment by 0xngmi** [comment]
closing for inactivity

**Comment by g1nt0ki** [comment]
@nemanjab17 @kredenac we have added a new export key called 'vesting' for non-stablecoin tokens specifically for payments/streaming category

**Comment by nemanjab17** [comment]
@g1nt0ki  Thanks for getting back with this, so if we use on chain adapter it's good to go?

**Comment by g1nt0ki** [comment]
hi @nemanjab17 an on-chain adapter and stablecoin/solana token tvl go into 'tvl' section and other locked tokens go into 'vesting' section. You can check how we do it in llamapay/sushiswap furo adapter. Let me know if you need some help with the adapter

**Pull request closed without merging**
