### PR TITLE
ft: Unbound DefiLlama Adapter

### PR DESCRIPTION
**Pull request by Adeshh**
##### Twitter Link:  
https://twitter.com/unboundfinance

##### List of audit links if any:  
 https://github.com/unbound-finance/unbound-audits

##### Website Link:   
https://www.unbound.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
Unbound

##### Current TVL:   
6.53m

##### Chain:  
Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
unbound-finance

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
7846

##### Short Description (to be shown on DefiLlama):
Unbound Finance is a decentralized, cross-chain liquidity protocol that is building the next money lego by unlocking the liquidity from AMMs.

##### Token address and ticker if any:
UNB: 0x8db253a1943dddf1af9bcf8706ac9a0ce939d922

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
staking

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink And TWAP

##### forkedFrom (Does your project originate from another project):
Not applicable

##### methodology (what is being counted as tvl, how is tvl being calculated):
The locked liquidity pool tokens collateral value is considered as TVL. TVL is calculated by calculating value of locked TVL in terms of USD

### CODE REVIEW

**Comment by realdealshaman** [comment]
We'd prefer to have an adapters that uses on-chain calls. Would this be possible?

**Comment by Adeshh** [comment]
Since we use factory structure in the contracts it won't be possible to fetch the TVL directly using on chain contracts.

**Comment by waynebruce0x** [comment]
For some protocols with factory structures we query event logs for new pools. Would method 0x936f4330 work? We try to avoid thegraph because it causes issues when it falls behind current block height

**Comment by Adeshh** [comment]
Hey, @waynebruce0x at this moment, we won't be able to get make changes but soon we're launching version 2 of the product. We'll surely consider this when we're redesigning the contracts.

**Comment by waynebruce0x** [comment]
is there somewhere we can see how protocols.tvl is calculated?

**Comment by Adeshh** [comment]
At this moment we cannot open source our code but can add you guys to our repo so you can take a look

**Comment by waynebruce0x** [comment]
if you could that'd be good. We'd still prefer an on-chain adapter where possible because its more transparent for our users

**Comment by waynebruce0x** [comment]
@Adeshh any update?

**Comment by waynebruce0x** [comment]
Closing for inactivity, if you think this should be reopened let us know in discord

**Pull request closed without merging**
