### PR TITLE
change ribbon-lend tvl to use poolSize

### PR DESCRIPTION
**Pull request by timongll**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/ribbon-lend exports TVL: 
        
 
 
    ethereum-borrowed         5.26 M
    ethereum                  9.57 M
    borrowed                  5.26 M
    
    total                    9.57 M

**Comment by kenchangh** [comment]
Hi! We're looking to count the pool size as the TVL, rather than only counting the amount left after borrowing. Our justification is:

Ribbon Lend is an undercollateralized lending product, so unlike products like Aave, the collateral remaining in the vault would be <10% the total pool size. For Aave the TVL with borrows included is 1.5x the TVL without. This would be an inaccurate representation of the funds within the pool.

**Comment by g1nt0ki** [comment]
hi @kenchangh @timongll I understand but this is similar to Clearpool and TrueFi where we have applied similar logic.

**Comment by kenchangh** [comment]
> hi @kenchangh @timongll I understand but this is similar to Clearpool and TrueFi where we have applied similar logic.

Happy to make a PR to update their adapters too! For the sake of consistency. Let me know what you think

**Comment by g1nt0ki** [comment]
Sorry, I dont think we will change our policy regarding this just yet, until 3 months ago, we did not even show borrowed amount for undercollateralized lending: https://twitter.com/0xngmi/status/1534858338651066378?s=20&t=rPIbXtPFBH1K4Qdp0uwEog 

Reason for this is to tackle cycled lending: https://twitter.com/0xngmi/status/1434485818345799681?s=20&t=rPIbXtPFBH1K4Qdp0uwEog

**Pull request closed without merging**
