### PR TITLE
add CryptoSwap integration

### PR DESCRIPTION
**Pull request by CryptoLover705**
##### Twitter Link:
https://twitter.com/CryptoDevelopm3

##### Website Link:
https://cryptoswapdex.com/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://i.imgur.com/4PHbrxs.png

##### Current TVL:
$6.16k
##### Chain:
Binance Smart Chain

##### Short Description (to be shown on DefiLlama):
The hottest new AMM on BSC! Earn CST through yield farming, then stake it in Csyrup Pools to earn more tokens. Swap, stake, and earn — all on a platform you can trust.

##### Token address and ticker if any:
0xcC4b3EA1F25c8772D390dA1DB507832aBE4a9740 - CST

##### Category (full list at https://defillama.com/categories) *Please choose only one:
[Dexes](https://defillama.com/protocols/Dexes)

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### forkedFrom (Does your project originate from another project):
pancakeswap

##### methodology (what is being counted as tvl, how is tvl being calculated):
The CryptoSwap subgraph and the CryptoSwap factory contract address are used to obtain the balance held in every LP pair.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/cryptoswap exports TVL: 
        
 
 
    bsc                       6.22 k
    
    total                    6.22 k

**Comment by Define101** [comment]
Hi guys, the logo is looking a bit bad.
Do you guys have any logo without the text? A simple image would be better 
Can use the Twitter logo if you guys want

**Comment by Define101** [comment]
https://defillama.com/protocol/cryptoswap

**Comment by CryptoLover705** [comment]
self
Hey, here is logo without text for you

**Pull request merged**
