### PR TITLE
add ram protocol

### PR DESCRIPTION
**Pull request by flash-boys**
##### Twitter Link:

NA
##### List of audit links if any: 
Pending

##### Website Link:
[Ram Protocol](https://rammer.finance/#/)

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://ram-protocol.github.io/logo.svg

##### Current TVL:
1.3Mil

##### Chain:

ThuderCore
##### Description/bio (to be shown on DefiLlama):
Ram is a non-custodial liquidity protocol for earning interest on deposits and borrowing assets on the ThunderCore chain.

##### Token address and ticker if any:
Ram (RAM) token: 0xfe146d5710015d4075355fb7be8d133346ec63c2 

##### Category (Yield/Dexes/Lending/Minting):
Lending

##### [Optional] ETH addresss (to receive a LlamaPunk):
0xE257a9Ee73628A5d2A9d18e1dc4a7419e292a3C1

### CODE REVIEW

**Comment by 0xngmi** [comment]
Is there a reason why you chose to directly construct the requests instead of using Web3?

**Comment by flash-boys** [comment]
> Is there a reason why you chose to directly construct the requests instead of using Web3?

It was just for convenience since we've been using this method for our own tracking so we could just port it over.

**Comment by 0xngmi** [comment]
Delisted since the numbers reported seem to be wrong
image

Could you fix the script? I'll relist afterwards

**Comment by flash-boys** [comment]
Hi team,

Sorry for the inconvenience, I've switched over to using web3 and issued a
new PR here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/241
Let me know if there's any issues.

Thanks

**Pull request merged**
