### PR TITLE
Add USDC from Multichain.

### PR DESCRIPTION
**Pull request by yodedex**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/yodeswap exports TVL: 
        
 
 
    dogechain-staking         111.35 k
    dogechain                 1.36 M
    staking                   111.35 k
    
    total                    1.36 M

**Comment by yodedex** [comment]
TVL should be around 6 mil
https://info.yodeswap.dog/

**Comment by llamatester** [comment]
The adapter at projects/yodeswap exports TVL: 
        
 
 
    dogechain-staking         112.34 k
    dogechain                 1.36 M
    staking                   112.34 k
    
    total                    1.36 M

**Comment by g1nt0ki** [comment]
I have fixed it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/3680
the tokens need to be whitelisted to be priced.

**Comment by yodedex** [comment]
thank you!

**Pull request closed without merging**
