### PR TITLE
add laserswap

### PR DESCRIPTION
**Pull request by laserswapxyz**
##### Twitter Link:
https://twitter.com/Laser_Swap

##### List of audit links if any:
N/A

##### Website Link:
https://laserswap.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
Largest - https://laserswap.finance/images/laser-logo.png
Mid - https://laserswap.finance/images/laser-logo-bg.png
Favicon - https://laserswap.finance/favicon.ico

##### Current TVL:
416.74 k
##### Chain:
ThunderCore

##### Short Description (to be shown on DefiLlama):
LaserSwap, the first DEX V2 on ThunderCore (TT) delivering great trading experience and earning opportunities.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
TWAP

##### forkedFrom (Does your project originate from another project):
PancakeSwap

##### methodology (what is being counted as tvl, how is tvl being calculated):
Finds TotalLiquidityUSD using the LaserSwap subgraph "http://laserswap.finance:8000/subgraphs/name/laserswap/exchange

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/laserswap/index.js exports TVL: 
        
 
 
    
    total                    415.90 k

**Comment by g1nt0ki** [comment]
Can this be calculated using on-chain calls instead? We've got a guide on how to use our SDK here: https://docs.llama.fi/list-your-project/submit-a-project


You could also look into `calculateUsdUniTvl` used in other dex adapters, let me know if you have some doubts

**Comment by laserswapxyz** [comment]
Hey,

We've tried to implement it with on-chain calls, but realized that ThunderCore is not yet supported by the SDK.

**Comment by llamatester** [comment]
The adapter at projects/laserswap/index.js exports TVL: 
        
 
 
    thundercore               388.80 k
    
    total                    388.80 k

**Comment by llamatester** [comment]
The adapter at projects/laserswap/index.js exports TVL: 
        
 
 
    thundercore               389.29 k
    
    total                    389.29 k

**Pull request merged**
