### PR TITLE
add esALB TVL

### PR DESCRIPTION
**Pull request by darkalienlord**
Add TVL from escrowed ALB.
Update website link
Update Short Description
Update CMC ID
Update Logo
Update Token address and ticker
---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/alienbase-esALB exports TVL: 
        
 
 
    base                      6.78 M
    
    total                    6.78 M

**Comment by g1nt0ki** [comment]
@darkalienlord thanks for the PR, updated existing listing, we will update other details you mentioned in the PR: https://github.com/DefiLlama/DefiLlama-Adapters/commit/ccd54a9621ce0ae882c18c7c6f866dee030a4872

**Comment by Define101** [comment]
@darkalienlord what is the logo? It goes to a 404 page

**Comment by darkalienlord** [comment]
Sorry it didn’t build, try again.

I noticed also the TVL from esALB went to staking, this is not quite right
because those tokens are not staked but locked on the platform and
illiquid, so it should be included as a separate TVL or embedded into the
main TVL.

**Comment by g1nt0ki** [comment]
@darkalienlord we treat own tokens locked as staking

**Comment by darkalienlord** [comment]
@Define101 updates on the logo and social info?

**Comment by darkalienlord** [comment]
@g1nt0ki got it thank you!

**Comment by darkalienlord** [comment]
@Define101 sorry to bother, the logo update?

**Pull request closed without merging**
