### PR TITLE
add Ferro SDK adapter

### PR DESCRIPTION
**Pull request by CronosLabsDev**
##### Twitter Link:

https://twitter.com/FerroProtocol

##### List of audit links if any:

https://docs.ferroprotocol.com/extras/security

##### Website Link:

https://ferroprotocol.com/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

ferro

##### Current TVL:

52.6M

##### Chain:

Cronos

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

ferro

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

20716

##### Short Description (to be shown on DefiLlama):

a stableswap AMM protocol on Cronos

##### Token address and ticker if any:

0x39bC1e38c842C60775Ce37566D03B41A7A66C782

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Dexes

##### forkedFrom (Does your project originate from another project):

Saddle

##### methodology (what is being counted as tvl, how is tvl being calculated):

sum of ferro stablecoin pool contracts balance

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@CronosLabsDev please try using on chain calls instead of fetch adapter

**Comment by CronosLabsDev** [comment]
@g1nt0ki changed to use chain calls instead of fetch adapter, please take a look, thank you!

**Comment by llamatester** [comment]
The adapter at projects/ferro exports TVL: 
        
 
 
    cronos                    55.64 M
    
    total                    55.64 M

**Comment by g1nt0ki** [comment]
@CronosLabsDev thanks for the PR, it looks good

**Pull request merged**
