### PR TITLE
Adding Lombard (LBTC)

### PR DESCRIPTION
**Pull request by jameswstevens**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

Liquid Bitcoin

##### Twitter Link:

https://x.com/Lombard_Finance

##### List of audit links if any:

https://www.halborn.com/audits/lombard/lbtc
https://veridise.com/wp-content/uploads/2024/08/VAR_Lombard_240506.pdf
https://www.halborn.com/audits/lombard/consortium

##### Website Link:

https://www.lombard.finance/

##### Logo (High resolution, will be shown with rounded borders):

https://github.com/user-attachments/assets/39a99cf3-98cb-4cce-b6a1-913993d4bc41
https://github.com/user-attachments/assets/f3f67979-b949-4a91-a389-38f04bf045e7

##### Current TVL:

$163,173,356 USD

##### Chain:

Ethereum Mainnet

##### Short Description (to be shown on DefiLlama):

LBTC is liquid, yield-bearing, natively cross-chain, and 1:1 backed by bitcoin.

##### Token address and ticker if any:

0x8236a87084f8B84306f72007F36F2618A5634494
LBTC

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Liquid Staking

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):

Redstone

##### Implementation Details: Briefly describe how the oracle is integrated into your project:

Redstone ensures our 1:1 ratio. Redstone tracks our staked BTC deposited into Lombard Deposit Addresses and the corresponding LBTC minted on destination chains (only ETH for now)

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:

Redstone feed is compatible with the chainlink's AggregatorV3Interface:
https://github.com/redstone-finance/redstone-oracles-monorepo/blob/5ac1df8850fd9a0a4970953240229299f41d9bbd/packages/on-chain-relayer/contracts/price-feeds/interfaces/IPriceFeed.sol#L5C9-L5C30

Feed Contract: 0xb415eAA355D8440ac7eCB602D3fb67ccC1f0bc81

##### forkedFrom (Does your project originate from another project):

No

##### methodology (what is being counted as tvl, how is tvl being calculated):

TVL is the total BTC deposited into Lombard Deposit Addresses. This is equal to the amount of LBTC in circulation, it is calculated by retrieving all the LBTC supply.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/lombard exports TVL: 
        
 
 
    bitcoin                   163.69 M
    
    total                    163.69 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
thanks for the PR, but can you share the bitcoin addresses where equivalent amount is locked, we count the tvl at the source

**Comment by jameswstevens** [comment]
> thanks for the PR, but can you share the bitcoin addresses where equivalent amount is locked, we count the tvl at the source

Can I use our restone oracle endpoint? Or do I need to gather all the btc addresses directly?

**Comment by g1nt0ki** [comment]
>  "Can I use our restone oracle endpoint?"

does it return list of btc addresses? If so, yes

**Comment by jameswstevens** [comment]
> > "Can I use our restone oracle endpoint?"
> 
> does it return list of btc addresses? If so, yes

Do we need a sig to prove ownership or just listing the addresses okay? Will be a lot more work for us to have all the deposit addresses sign atm since we already set them up.

**Comment by jameswstevens** [comment]
> > > "Can I use our restone oracle endpoint?"
> > 
> > 
> > does it return list of btc addresses? If so, yes
> 
> Do we need a sig to prove ownership or just listing the addresses okay? Will be a lot more work for us to have all the deposit addresses sign atm since we already set them up. @g1nt0ki



> > > "Can I use our restone oracle endpoint?"
> > 
> > 
> > does it return list of btc addresses? If so, yes
> 
> Do we need a sig to prove ownership or just listing the addresses okay? Will be a lot more work for us to have all the deposit addresses sign atm since we already set them up. @g1nt0ki

hey @g1nt0ki, could yoy get back here?

**Comment by jameswstevens** [comment]
Yo @g1nt0ki, this is the list of our BTC addresses. The script totals the balances. Can also go and check the endpoint to get the addresses as well.

**Comment by g1nt0ki** [comment]
hi @jameswstevens thanks for the update, is there some way to filter the list for only addresses with balance? checked a few and they were zero

**Comment by llamatester** [comment]
The adapter at projects/lombard exports TVL: 
        
 
 
    bitcoin                   237.61 M
    
    total                    237.61 M

**Comment by jameswstevens** [comment]
@g1nt0ki, there is not way to know if it is 0 unless we go and check the balance. Would it be acceptable for us to update the balances on our backend and query from there so it is faster? Then anyone can still go check the address balances the long way if they need to check.

**Comment by jameswstevens** [comment]
> hi @jameswstevens thanks for the update, is there some way to filter the list for only addresses with balance? checked a few and they were zero

@g1nt0ki, want me to just query the balances we store in the backend? Anyone can also query our addresses and check the balances manually themselves.

**Comment by g1nt0ki** [comment]
if it is not too much work, can api be be updated to return address & respective balance? else it is fine.

I was trying to cut down on the # calls to bitcoin api

**Pull request merged**
