### PR TITLE
Add Incognito TVL

### PR DESCRIPTION
**Pull request by corollari**
#### Why are you creating this pull request?
Adding TVL of Incognito Chain

##### Twitter Link:
https://twitter.com/IncognitoChain

##### List of audit if any:
None

##### Website Link:
https://incognito.org/

##### Contact Email:
I'm not part of their team but you can contact me at defillama@albert.sh

##### Expected TVL:
30M USD

##### Chain:
Incognito Chain

##### Coingecko ID (so your TVL can appear on Coingecko):
`privacy`

##### Description/bio (to be shown on DefiLlama):
A privacy sidechain with a uniswap-like DEX.

##### Token address and ticker if any:
It's not on ethereum, it is the native token of the chain

Ticker is PRV

### CODE REVIEW

**Comment by DefiLlama** [comment]
Endpoint is down, please fix asap!

**Comment by corollari** [comment]
I did not build that service nor I have any association with it, sorry!

**Comment by DefiLlama** [comment]
You made the PR...

**Comment by corollari** [comment]
Yeah, I am not part of the team tho, I just worked with them previously and would like for them to succeed.

According to the creator of the API it will be down for over 1 day ([source](https://we.incognito.org/t/network-explorer/2086/365)) so I'd suggest delisting them.

**Comment by DefiLlama** [comment]
@corollari you want to chat on telegram? My handle is @defillama

**Pull request merged**
