### PR TITLE
Ubeswap add

### PR DESCRIPTION
**Pull request by ygboucherk**
##### Twitter Link:
https://twitter.com/ubeswap

##### Website Link:
https://ubeswap.org

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
image

##### Current TVL:
Roughly 27M

##### Chain:
Celo

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
ubeswap

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
ubeswap

##### Description/bio (to be shown on DefiLlama):
Ubeswap is the leading DEX on Celo network !

##### Token address and ticker if any:
Address 0x00Be915B9dCf56a3CBE739D9B9c202ca692409EC, ticker UBE

##### Category (Yield/Dexes/Lending/Minting):
DEX

##### [Optional] ETH addresss (to receive a LlamaPunk):
0x3f119cef08480751c47a6f59af1ad2f90b319d44

### CODE REVIEW

**Comment by 0xngmi** [comment]
we could sue the code we have for this type of uniswap-subgraph adapters to simplify your code

**Comment by 0xngmi** [comment]
I've pushed alternative versions of your code that are much shorter

**Comment by ygboucherk** [comment]
Okay thanks !

**Comment by ygboucherk** [comment]
Okay so shall I close PR ?

**Comment by ygboucherk** [comment]
Ah yes I see files - thanks very much !

**Comment by realdealshaman** [comment]
Hey @ygboucherk , thank you for contributing to Defillama. Your LlamaPunk has been sent: https://opensea.io/0x3f119cef08480751c47a6f59af1ad2f90b319d44

**Comment by ygboucherk** [comment]
> Hey @ygboucherk , thank you for contributing to Defillama. Your LlamaPunk has been sent: https://opensea.io/0x3f119cef08480751c47a6f59af1ad2f90b319d44

Thanks very much !

**Pull request closed without merging**
