### PR TITLE
Added Infy Protocol

### PR DESCRIPTION
**Pull request by dudhatparesh**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Infy Protocol

##### Twitter Link:
https://twitter.com/infy_protocol/

##### Website Link:
https://infy.network/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://pbs.twimg.com/profile_images/1535524784112553984/-zCQIope_400x400.jpg

##### Current TVL:
0

##### Chain:
polygon
kava

##### Short Description (to be shown on DefiLlama):
Infy is decentralized Lending and Renting Protocol for NFTs

##### Category (full list at https://defillama.com/categories) *Please choose only one:
NFT Lending

##### methodology (what is being counted as tvl, how is tvl being calculated):

TVL is counted as balances of ETH, USDC,DAI, USDT and TUSD in escrow contract

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/infy exports TVL: 
        
 
 
    polygon                   0
    kava                      0
    
    total                    0

**Comment by realdealshaman** [comment]
@dudhatparesh  I am not finding any of these balances: ETH, USDC,DAI, USDT and TUSD in escrow contracts. Is the project live already? wondering when will we be able to start seeing deposits and a tvl

**Comment by dudhatparesh** [comment]
Hi @realdealshaman its basically NFT rental marketplace so TVL would be more dynamic as whenever every items returned then the amount is distributed between lender, renter and treasury. I just rented one item and now the TVL is

--- polygon ---
USDC                      1.0427076659999999
WETH                      0
USDT                      0
DAI                       0
TUSD                      0
Total: 1.0427076659999999 

--- kava ---
ETH                       0
USDC                      0
USDT                      0
DAI                       0
Total: 0 

--- tvl ---
USDC                      1
WETH                      0
USDT                      0
DAI                       0
TUSD                      0
ETH                       0
Total: 1.0427076659999999 

------ TVL ------
polygon                   1.0427076659999999
kava                      0

total                    1.0427076659999999

**Comment by llamatester** [comment]
The adapter at projects/infy exports TVL: 
        
 
 
    kava                      0
    polygon                   1.043749332
    
    total                    1.043749332

**Pull request merged**
