### PR TITLE
feat: ethereum contracts

### PR DESCRIPTION
**Pull request by TbIKoBKa**
added ethereum contract to primex-finance

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/primex-finance exports TVL: 
        
 
 
    ethereum                  383.22302999408663
    arbitrum                  43.98 k
    polygon                   213.36 k
    
    total                    257.72 k

**Comment by llamatester** [comment]
The adapter at projects/treasury/primex-finance.js exports TVL: 
        
 
 
    ethereum-ownTokens        0
    polygon-ownTokens         0
    polygon                   2.31 k
    arbitrum-ownTokens        0
    arbitrum                  1.34 k
    ethereum                  0
    ownTokens                 0
    
    total                    3.65 k

**Comment by llamatester** [comment]
The adapter at projects/treasury/primex-finance.js exports TVL: 
        
 
 
    ethereum-ownTokens        0
    arbitrum-ownTokens        0
    arbitrum                  1.32 k
    polygon-ownTokens         0
    polygon                   2.28 k
    ethereum                  4.380560000000001
    ownTokens                 0
    
    total                    3.61 k

**Comment by g1nt0ki** [comment]
@TbIKoBKa thanks for the PR

**Pull request merged**
