### PR TITLE
arbitrum and eth tvl calcs

### PR DESCRIPTION
**Pull request by adamxyzxyz**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/fractal-protocol exports TVL: 
        
 
 
    ethereum                  3.46 M
    arbitrum                  99.97 k
    
    total                    3.56 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
@adamxyzxyz sorry, but I dont like this change because it is counting usdf supply as tvl instead of the back tokens that are locked in your protocol. 

According to this page: https://stats.fractalprotocol.org/d/-bD2j_g4z/stats about 2.25M is loaned out, we cant count it as tvl but as borrowed, any idea why borrowed is returning 5M instead of 2.25M?

**Comment by adamxyzxyz** [comment]
@g1nt0ki I hear you on the first point. I will redo the TVL Calculations and commit when ready.

With regards to the loans, assets loaned out were first deposited in the protocol as TVL. These are assets that Fractal is loaning out, not borrowing. This is exactly the same as Maple TVL being composed of USDC that was deposited in their credit pools to then be loaned out.

**Comment by g1nt0ki** [comment]
@adamxyzxyz we apply the same rule to maple if you check :) all loaned out tokens are marked as borrowed, only available liquidity is counted as tvl even for them

**Comment by llamatester** [comment]
The adapter at projects/fractal-protocol exports TVL: 
        
 
 
    ethereum-borrowed         49.97 k
    ethereum                  237.16 k
    polygon                   452.97 k
    avax-borrowed             2.20 M
    avax                      439.93 k
    arbitrum                  192.01 k
    borrowed                  2.25 M
    
    total                    1.32 M

**Comment by adamxyzxyz** [comment]
@g1nt0ki please check the updates I have added

**Comment by llamatester** [comment]
The adapter at projects/fractal-protocol exports TVL: 
        
 
 
    avax-borrowed             2.20 M
    ethereum-borrowed         50.05 k
    ethereum                  237.52 k
    polygon                   453.06 k
    avax                      440.02 k
    arbitrum                  117.40 k
    borrowed                  2.25 M
    
    total                    1.25 M

**Comment by g1nt0ki** [comment]
@adamxyzxyz It looks good, I made some sdk related changes, changed it to using newer version which is bit more concise 

other change I made was, remove USDF part from being counted towards tvl as tvl is amount of tokens backing USDF, we do the same thing for Frax/Maker tvl

**Comment by g1nt0ki** [comment]
*ignore the lint error, if you are fine with my changes, I can merge this PR :)

**Comment by adamxyzxyz** [comment]
Thanks @g1nt0ki I will review today and let you know!

**Comment by adamxyzxyz** [comment]
@g1nt0ki looks good, please merge!

**Pull request merged**
