### PR TITLE
adding swell earnETH

### PR DESCRIPTION
**Pull request by darvinrio**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama): 
Swell ETH Earn Vault

##### Twitter Link: 
https://x.com/swellnetworkio

##### List of audit links if any:
https://github.com/Ion-Protocol/nucleus-boring-vault/blob/master/audit/0xmacro-boring-vault-arctic-0.pdf 
https://github.com/Ion-Protocol/nucleus-boring-vault/blob/master/audit/pashov-boring-vault.pdf
https://github.com/Ion-Protocol/nucleus-boring-vault/blob/master/audit/spearbit-boring-vault-arctic-0.pdf

##### Website Link: 
https://app.swellnetwork.io/earn/vaults

##### Logo (High resolution, will be shown with rounded borders): 
https://cdn.prod.website-files.com/63dc9bdf46999ffb2c2f407a/6711e599662019e75b71d602_earnETH.svg

##### Short Description (to be shown on DefiLlama):
earnETH is an ETH denominated vault that allows users to deposit their ETH assets to get automated risk adjusted yields and points. [Learn More](https://docs.swellnetwork.io/swell-earn/earneth-vault)

##### Token address and ticker if any:
0x9Ed15383940CC380fAEF0a75edacE507cC775f22 
earnETH

##### Category (full list at https://defillama.com/categories) *Please choose only one: 
Yield

##### methodology (what is being counted as tvl, how is tvl being calculated):
earnETH supply * earnETH to ETH ratio from Accountant

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/swell-earn-eth exports TVL: 
        
 
 
    ethereum                  39
    
    total                    39.308699999999995

**Comment by llamatester** [comment]
The adapter at projects/swell-earn-eth exports TVL: 
        
 
 
    ethereum                  1.02 M
    
    total                    1.02 M

**Comment by 0xpeluche** [comment]
Thanks for the PR, I just made a refactor to use the balanceOf of the underlying tokens in the vault. If everything looks good on your side, I'll merge it, you can see it at #11987

**Comment by g1nt0ki** [comment]
@darvinrio thanks, I have merged the other PR

**Pull request closed without merging**
