### PR TITLE
added FuzioNetwork DEX

### PR DESCRIPTION
**Pull request by Dizz02**
Name (to be shown on DefiLlama): FuzioNetwork DEX
Twitter Link: https://twitter.com/FuzioNetwork
List of audit links if any:
Website Link: https://www.fuzio.network/
Logo (High resolution, will be shown with rounded borders): https://github.com/Fuzio-DeFi-Network/Fuzio-Network/blob/main/images/LogoFuzio-B.svg
Current TVL: 7.06 k
Treasury Addresses (if the protocol has treasury)
Chain: Sei Network
Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed):
Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed):
Short Description (to be shown on DefiLlama): Fuzio fuses strategic gaming with DeFi, crafting a cutting-edge platform for a captivating, skill-driven financial journey that's thrilling and rewarding on SEI Network. 

Token address and ticker if any:

Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using): Pyth
forkedFrom (Does your project originate from another project): No
methodology (what is being counted as tvl, how is tvl being calculated): Total SEI balances of all pools.
Github org/user (Optional, if your code is open source, we can track activity): Not open source

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/FuzioNetwork exports TVL: 
        
 
 
    sei                       7.83 k
    
    total                    7.83 k

**Comment by llamatester** [comment]
The adapter at projects/seaswap exports TVL: 
        
 
 
    sei                       20.77 k
    
    total                    20.77 k

**Comment by llamatester** [comment]
The adapter at projects/terraswap exports TVL: 
        
 
 
    terra2                    176.40 k
    terra                     916.13 k
    
    total                    1.09 M

**Comment by Dizz02** [comment]
Hi it's on Sei Network nothing to do with Terraswap. The code was working the way it initially was.

**Comment by Dizz02** [comment]
Hi team. Beautiful work by the way! Can i ask a little favor? To change Name (to be shown on DefiLlama): FuzioNetwork DEX and put Fuzio only instead of FuzioNetwork-DEX? Thank you!

**Pull request merged**
