### PR TITLE
Add Lavarage adapter

### PR DESCRIPTION
**Pull request by trishateh**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

**Note** : Is it possible to add a dependency: @solana/spl-token ? The checks are failing due to this. Thank you.

##### Name (to be shown on DefiLlama):
Lavarage

##### Twitter Link:
https://twitter.com/Lavaragexyz

##### List of audit links if any:
https://code4rena.com/reports/2024-04-lavarage
https://github.com/sec3-service/reports/blob/master/reports/sec3_lavarage_final_report.pdf

##### Website Link:
https://lavarage.xyz/

##### Logo (High resolution, will be shown with rounded borders):

lavarage

##### Current TVL:
109644.07 B
Screenshot 2024-11-15 at 8 59 44 PM

##### Short Description (to be shown on DefiLlama):
Lavarage is a decentralized spot margin trading platform that enables leveraged token trading on DEXs, backed by stakers and lenders. While it supports a wide range of assets, Lavarage specializes in providing access to long-tail assets, such as memecoins, offering unique opportunities for traders seeking high-potential markets.

##### Category (full list at https://defillama.com/categories) *Please choose only one: 
Derivatives

##### methodology (what is being counted as tvl, how is tvl being calculated):
Value of all long tail assets locked in users position accounts and staked assets in liquidity pools.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/lavarage: 
        
 
  
    
    
    Error: Cannot find module '@solana/spl-token'
    Require stack:
    - /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/lavarage/index.js
    - /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js
    Truncated error stack:
    
        at Object.<anonymous> (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/lavarage/index.js:5:18)
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'

**Comment by llamatester** [comment]
Error while running adapter at : 
        
 
  > Please revert changes to package.json / package-lock.json

**Comment by llamatester** [comment]
Error while running adapter at projects/lavarage: 
        
 
  
    
    
    Error: 429 Too Many Requests: {"jsonrpc":"2.0","error":{"code":-32429,"message":"max usage reached"}}
    Truncated error stack:
        at ClientBrowser.callServer (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@solana/web3.js/lib/index.cjs.js:4944:18)

**Comment by g1nt0ki** [comment]
@trishateh thanks for the PR, can you go over the code and check if I have introduced any bugs in my refactor?

**Comment by piske-alex** [comment]
Thanks for the refactor @g1nt0ki .
I appreciate how the way it's structured and its using defillama API.
However, will this lead to a lot of tokens that doesn't have a price in coingecko not being able to show up?
The TVL computed with your code is half of what we computed. This doesn't correctly reflect our TVL

**Comment by g1nt0ki** [comment]
Hi, what are the tokens missing price? We are pulling token prices from coingecko and think we are covering all major tokens on solana now

**Comment by piske-alex** [comment]
@g1nt0ki 

We mostly do tokens that are like few hours old and 1 day old. that's why we were using the Jupiter price api in our commit. I would say most tokens in our TVL are not on coingecko. mostly pump fun graduates.

If we can only use coingecko. every time someone borrows our tvl will drop, which will be very weird

**Comment by llamatester** [comment]
Error while running adapter at projects/lavarage: 
        
 
  
    
    
    Error: 429 Too Many Requests: {"jsonrpc":"2.0","error":{"code":-32429,"message":"max usage reached"}}
    Truncated error stack:
        at ClientBrowser.callServer (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@solana/web3.js/lib/index.cjs.js:4944:18)

**Comment by piske-alex** [comment]
@g1nt0ki thanks! I don't think so. everything else looks good to me

**Comment by trishateh** [comment]
Thanks @g1nt0ki and @piske-alex ! looks good to me too

**Pull request merged**
