### PR TITLE
adding darkness.finance

### PR DESCRIPTION
**Pull request by darkcrypto-warrior**
##### Twitter Link:
https://twitter.com/DarkCryptoFi

##### Website Link:
https://www.darkness.finance

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://www.darkness.finance/images/logo.svg

##### Current TVL:
$13,961,836

##### Chain:
Cronos

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
darkness-share

##### Short Description (to be shown on DefiLlama):
DarkNess Finance is the first multi-fractional-algorithmic stablecoin with stablecoins DEX on Cronos Chain

##### Token address and ticker if any:
NESS
0xE727240728C1a5f95437b8b50AFDd0EA4AE5F0c8

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### forkedFrom (Does your project originate from another project):
Balancer

##### methodology (what is being counted as tvl, how is tvl being calculated):
DarkNess TVL is pulled from the DarkNess subgraph and MEERKAT-LP (on mm.finance) locked in MasterChef (0x63Df75d039f7d7A8eE4A9276d6A9fE7990D7A6C5) , excluded D3USD that has been counted in liquidity

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Can NESS TVL be exported separately as 'staking'?

**Comment by v3s-finance** [comment]
Hi,
It's NESS/CRO-LP pool, not single asset. We will have NESS staking soon then we will export separately as staking
Please take a look,

Thank you

image

**Comment by darkcrypto-warrior** [comment]
Hi @waynebruce0x 

Just updated the code. Please look at this.
Thanks

**Comment by llamatester** [comment]
The adapter at projects/darkness/index.js exports TVL: 
                
 
 
cronos-pool2              2.82 M
cronos                    11.57 M
pool2                     2.82 M

total                    11.57 M

**Pull request merged**
