### PR TITLE
added Ostable Deposit adapter, a protocol that is part of the Obyte bonded stable coin protocol family

### PR DESCRIPTION
**Pull request by pmiklos**
##### Twitter Link:

https://twitter.com/ObyteOrg

##### Website Link:

https://ostable.org/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

https://ostable.org/static/media/logo.bd72e6a7.svg

##### Current TVL:

 92.54 k 

##### Chain:

Obyte

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

byteball

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

1492

##### Short Description (to be shown on DefiLlama):

Ostable Deposit is part of the Ostable advanced stable coin platform. It locks in so called interest tokens issued by the Ostable Curve protocol and issues stable tokens in exchange. An example interest token is IUSD and the resulting stable token is OUSD that is pegged to the US dollar.

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Algo-Stables

##### methodology (what is being counted as tvl, how is tvl being calculated):

The TVL is the USD value of the total Ostable Curve issued interest tokens locked into the autonomous agents that extend the Ostable Deposit protocol (v1 and v2).

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/ostable-deposit exports TVL: 
        
 
 
    obyte                     92.71 k
    
    total                    92.71 k

**Comment by pmiklos** [comment]
> Should this be combined with the ostable curve adapter?

We briefly discussed that in the Obyte community, both approaches could make sense. Ostable has multiple collaborating protocols, listing them individually makes it possible to track their tvl and let the user toggle the double count on the UI, while listing them as one gives less detail and control to the user but it would still be ok, perhaps even less confusing to the users since the project itself is called Ostable as a whole.

I don't know, what do you suggest? There are 4 main "smart contacts" in Ostable: curves, deposits, stability funds and governance.

**Comment by waynebruce0x** [comment]
Generally we combine products that share website/discord/twitter etc

**Comment by pmiklos** [comment]
I see, let me close this and the other pending one (#2850) then and merge them into Ostable Curve (which will need to be renamed to simply Ostable after that)

**Pull request closed without merging**
