### PR TITLE
Add prototype of scrt bridge adapter

### PR DESCRIPTION
**Pull request by 0xngmi**
Please fill in this info and verify that the adapter is correct, right now it's outputting 2.4M.

### CODE REVIEW

**Comment by nocanvas** [comment]
Why are you creating this pull request?
Add WSCRT as an asset

Twitter Link:
https://twitter.com/SecretNetwork

List of audit if any:
Website Link:
https://scrt.network/

Contact Email:
info@secret.foundation

Expected TVL:
~2.4m

Chain:
Ethereum

Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
secret-erc20

Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
secret-erc20

Description/bio (to be shown on DefiLlama):
Secret is the native coin of the Secret Network, a decentralized network for private / secure computation. Nodes on the network (known as secret nodes) can perform generalizable computations over encrypted data, which allows smart contracts (known as secret contracts) to use private and sensitive data as inputs. Our focus is on computational privacy, not just transactional privacy. Wrapped Secret (WSCRT) is the ERC-20 wrapped version of SCRT which can be swapped 1:1 for SCRT or secretSCRT.

Token address and ticker if any:
WSCRT
0x2b89bf8ba858cd2fcee1fada378d5cd6936968be

Category (Yield/Dexes/Lending/Minting): Asset

[Optional] ETH addresss (to receive a LlamaPunk): 0x7C6553933A471b43cE3a76A02245c5162C82522c

**Comment by nocanvas** [comment]
Hey @0xngmi checking in on this, I don't see WSCRT on https://defillama.com/protocols/assets 
Is there anything additional we need to do on our end?

**Comment by 0xngmi** [comment]
No, nothing is needed. Right now only one of the people working on defillama has access to the server so we are a bit bottlenecked on that side (right now there's 10 projects ready for listing but which are not listed yet).

**Comment by nocanvas** [comment]
Hi @0xngmi , sorry I just saw this live, and the name is "Secret Bridge", but I think that is a bit confusing, since this is specifically "WSCRT". Is that possible to change?

https://defillama.com/protocol/secret-bridge

**Comment by scrtisland** [comment]
hi @0xngmi , please see above comment, as well as wondering about this

Would it make sense to add TLV of secret network as the value of all assets on SN including:
- circulating SCRT
- other SNIP20s like SIENNA, FATS etc. (native tokens on secret network)
- ETH bridge  (bridged tokens onto secret network) <-- currently only tracking this

**Comment by 0xngmi** [comment]
For other chains we don't consider tokens issued on top of a protocol to be "locked" onto that platform so I don't see a compelling reason to do it for Secret:
- Is the market cap of ETH part of the TVL on Ethereum? Almost everyone will agree that it's not
- Is the market cap of all ERC20 part of Ethereum's TVL? Same.

**Pull request merged**
