### PR TITLE
BLUESHIFT DEX

### PR DESCRIPTION
**Pull request by KhrulSergey**
Added BOB chain contract addresses. Delete milkomeda_a1 chain support.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/blueshift exports TVL: 
        
 
 
    milkomeda                 740.05 k
    staking                   306.99 k
    milkomeda-staking         306.86 k
    bob                       64.81 k
    kava                      596
    kava-staking              128
    polygon                   72
    polygon-staking           0
    bob-staking               0
    
    total                    805.52 k

**Comment by g1nt0ki** [comment]
hi @KhrulSergey can you revert milkomeda_a1 change, we like to retain deprecated chains for historical tvl data.

**Comment by llamatester** [comment]
The adapter at projects/blueshift exports TVL: 
        
 
 
    milkomeda                 727.87 k
    staking                   297.94 k
    milkomeda-staking         294.59 k
    bob                       60.26 k
    milkomeda_a1              22.34 k
    bob-staking               3.03 k
    kava                      605
    milkomeda_a1-staking      201
    kava-staking              123
    polygon                   73
    polygon-staking           0
    
    total                    811.14 k

**Comment by KhrulSergey** [comment]
> hi @KhrulSergey can you revert milkomeda_a1 change, we like to retain deprecated chains for historical tvl data.

Hi! Ok, already did it.

**Comment by KhrulSergey** [comment]
@g1nt0ki Sorry, didn't mentioned you in previous comment. All modification was done.

**Pull request merged**
