### PR TITLE
Created index.js file with uniTvlExport 

### PR DESCRIPTION
**Pull request by Eminivince**
Wrote an SDK adapter in the index.js file to enable listing on DefiIllama.
Included Dex factory address.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/VoltageSwap exports TVL: 
        
 
 
    scroll                    8.00 k
    
    total                    8.00 k

**Comment by Eminivince** [comment]
What are those? Liquidity is currently 8.3k

**Comment by realdealshaman** [comment]
@Eminivince please fill out the listing info also:

Name (to be shown on DefiLlama):


Twitter Link:


List of audit links if any:

Website Link:

Logo (High resolution, will be shown with rounded borders):


Current TVL:


Treasury Addresses (if the protocol has treasury)


Chain:


Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)


Short Description (to be shown on DefiLlama):


Token address and ticker if any:
ticker: 
address:

Category (full list at https://defillama.com/categories) *Please choose only one:


Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):


forkedFrom (Does your project originate from another project):


methodology (what is being counted as tvl, how is tvl being calculated):


Github org/user (Optional, if your code is open source, we can track activity):

**Comment by Eminivince** [comment]
Name (to be shown on DefiLlama): VoltageSwap

Twitter Link: https://twitter.com/VoltageSwap?t=2cLm2ooVyEvH7lZbGl5K_Q&s=09

List of audit links if any:

Website Link: https://www.voltageswap.xyz/

Logo (High resolution, will be shown with rounded borders): 
Voltage

Current TVL: $8.3k

Treasury Addresses (if the protocol has treasury)

Chain: Scroll

Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

Short Description (to be shown on DefiLlama): Voltage Swap is a Native dex to Scroll, our core swap functionality ensures fast, cheap and efficient trades. Powered by an optimized architecture, our protocol guarantees exceptional capital efficiency, achieved through startegic liquidity incentives, seamless lending and borrowing integration and a remarkable feature: distributing over 80% of protocol generated revenue directly to users.

Token address and ticker if any:
ticker: VOLT
address: 0x515ba0F5B5Ed37b8E96289C9ef07F36b6DF490fA

Category (full list at https://defillama.com/categories) *Please choose only one: Dexes

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

forkedFrom (Does your project originate from another project): Uniswap V2

methodology (what is being counted as tvl, how is tvl being calculated): Calculated the value of tokens in the Dex in USD.

Github org/user (Optional, if your code is open source, we can track activity):

Merge

**Pull request merged**
