### PR TITLE
BlueMove team added a TVL Adapter

### PR DESCRIPTION
**Pull request by business-bluemove**
**NOTE**
Dear DefiLlama team

We would like to add the TVL Adapter for the BlueMove NFT marketplace
Please help me to review it

Thanks and Best Regards!
BlueMove Team
> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/blue-move-mart exports TVL: 
        
 
 
    aptos                     67.38 k
    
    total                    67.38 k

**Comment by llamatester** [comment]
The adapter at projects/blue-move-mart exports TVL: 
        
 
 
    aptos                     66.90 k
    
    total                    66.90 k

**Comment by business-bluemove** [comment]
> methodology
Hi,
I just updated the methodology used for calculating the TVL on us. Please help me to take a look into it
Thanks!

**Comment by g1nt0ki** [comment]
@business-bluemove can you count only the NFTs staked in your protocol? users are still in possession of an NFT after listing it for sale? Asking because this behavior is different between sudoswap and opensea

**Comment by business-bluemove** [comment]
> can you count only the NFTs staked in your protocol? users are still in possession of an NFT after listing it for sale? Asking because this behavior is different between sudoswap and opensea
Hi, Technically, in both listing and staking NFT, users don't possess NFTs. They have to send the NFTs to the smart contract belonging to BlueMove

**Pull request merged**
