### PR TITLE
Valoro

### PR DESCRIPTION
**Pull request by k05ta5**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protoc
valoro-logomark-on-black
ols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/valoro exports TVL: 
        
 
 
    elrond                    29
    
    total                    28.822075

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
hi @k05ta5 

thanks for the PR, is the project live? also, can you compute the tvl by checking token balances instead?

**Comment by k05ta5** [comment]
Hi @g1nt0ki ,

The project just made a soft launch. SCs are live in mainnet. The official launch will be in 1-2 days when the webpage will allow everyone to invest.

The TVL is actually computed by checking the token balances in the SCs. The $ value of all the tokens in a Fund's SC are summed and that number is the TVL of a Fund. Doing that for all Funds, we get the overall TVL.

**Comment by g1nt0ki** [comment]
yes, but we prefer computing tvl on our side and showing users token breakdown of the index, atm it is bit of a blackbox

**Comment by k05ta5** [comment]
Ok, so instead of returning the sum of TVL numbers of all Funds, should I return the TVL of each sum separately?
Or you even prefer to have the token balances themselves and you will calculate their $ value?

I can do both, just please let me know understand what you prefer. Tomorrow is our official launch and we'd be very glad to have our defillama exposure available.

**Comment by llamatester** [comment]
The adapter at projects/valoro exports TVL: 
        
 
 
    elrond                    182
    
    total                    181.553556

**Comment by llamatester** [comment]
The adapter at projects/valoro exports TVL: 
        
 
 
    elrond                    0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/valoro exports TVL: 
        
 
 
    elrond                    180
    
    total                    179.97321379519298

**Comment by k05ta5** [comment]
@g1nt0ki I updated as you described. Now I query all Funds SCs returning all Token balances.

**Comment by g1nt0ki** [comment]
Thanks for changing it

**Pull request merged**
