### PR TITLE
feat: update Pumpbtc adapter 

### PR DESCRIPTION
**Pull request by xianshui**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
Name (to be shown on DefiLlama):

PumpBTC

Twitter Link:

https://x.com/Pumpbtcxyz

List of audit links if any:

https://drive.google.com/file/d/1kUmOPM8J63JmzM20H1Cg38oAfPRBJwLy/view?pli=1

Website Link:

https://pumpbtc.xyz/

Logo (High resolution, will be shown with rounded borders):

https://drive.google.com/file/d/1jIj9IwhrEsnMI4BFBF8TYGxQO_uCZ3-s/view?usp=drive_link

Current TVL:

1.14 M

Treasury Addresses (if the protocol has treasury)

Chain:

ETH/BSC/Mantle

Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

pumpbtc

Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

Short Description (to be shown on DefiLlama):

PumpBTC serves as a Liquid Restaking Solution for Babylon. PumpBTC aims to help BTC holders maximize yields through Babylon's liquid staking - essentially rebuilding WBTC with native yield.

Token address and ticker if any:

ETH: 0xf469fbd2abcd6b9de8e169d128226c0fc90a012e
BSC: 0xf9C4FF105803A77eCB5DAE300871Ad76c2794fa4
Mantle: 0xC75D7767F2EdFbc6a5b18Fc1fA5d51ffB57c2B37

Category (full list at https://defillama.com/categories) *Please choose only one:

Liquid Staking

Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):

Implementation Details: Briefly describe how the oracle is integrated into your project:

Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:

forkedFrom (Does your project originate from another project):

methodology (what is being counted as tvl, how is tvl being calculated):

TVL for pumpBTC is calculated based on the total value of WBTC, FBTC, BTCB held in the contract that were utilized in the minting process of pumpBTC.

Github org/user (Optional, if your code is open source, we can track activity):

https://github.com/pumpbtc/pumpBTC-contract

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/pumpbtc exports TVL: 
        
 
 
    ethereum                  0
    mantle                    0
    bsc                       0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/pumpbtc exports TVL: 
        
 
 
    ethereum                  16.38 M
    bsc                       4.74 M
    mantle                    0
    
    total                    21.12 M

**Comment by llamatester** [comment]
The adapter at projects/pumpbtc exports TVL: 
        
 
 
    ethereum                  16.38 M
    bsc                       4.74 M
    mantle                    0
    
    total                    21.12 M

**Comment by g1nt0ki** [comment]
if we are missing some contracts where WBTC/FBTC is locked, can you share them and I can include them

**Comment by xianshui** [comment]
> sorry, we prefer counting the backing as tvl instead of token supply

hi, @g1nt0ki , for in the staking process, the  WBTC/FBTC is not always locked in the staking contract. It will be batched converted to another native BTC token by period, and cross bridged to contract in Babylon, so the locked WBTC/FBTC can not represent the actual staked pumpBTC. And in the system, new pumpBTC only minted according to  the new staking  WBTC/FBTC with the same amount, so we counting the total amount of pumpBTC to represent TVL. 

Could we just use this methodology ?

**Comment by g1nt0ki** [comment]
hi @xianshui there is some way to pull value staked in babylon on chain?

**Comment by g1nt0ki** [comment]
*wait, how is it cross-bridged?

**Comment by xianshui** [comment]
There is no related method to pull value staked in Babylon that can distinguish the staked WBTC, FBTC, BTCB from different chains (such as Etehreum, BSC, Mantle).

**Comment by xianshui** [comment]
> *wait, how is it cross-bridged?

Its bridging process is back by Cobo's Multi-Party Computation (MPC) custody solution, which is a leading digital asset custody solutions provider founded in 2017 and headquartered in Singapore.

**Comment by xianshui** [comment]
@g1nt0ki How do you think about this methodology? Can it be used?

**Comment by xianshui** [comment]
@g1nt0ki  For we submit a new PR for adjusting PumpBTC adapter, this PR closed.

**Pull request closed without merging**
