### PR TITLE
1、Themis Protocol project has been added to the Projects directory

### PR DESCRIPTION
**Pull request by ThemisCapital**
1、Name (to be shown on DefiLlama): Themis Protocol
2、Twitter Link: https://twitter.com/Themis_Pro
3、 List of audit links if any:  https://dehacker.io/audit_reports_store/Themis.pdf
4、 Website Link: https://themis.capital/
5、Logo (High resolution, will be shown with rounded borders): https://github.com/ThemisCapital/Brand-Asset/blob/main/themisProtocol.png
6、 Current TVL: 
7、Treasury Addresses (if the protocol has treasury)：0x0e511806C7AC38cF6d1EeAa9Ee51027e44Dcbf94
8、Chain: Filecoin-FEVM

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/themisPro exports TVL: 
        
 
 
    filecoin-staking          0
    filecoin                  0
    staking                   0
    
    total                    0

**Comment by g1nt0ki** [comment]
hi @ThemisCapital sorry for the late reply, how are these USDT bridged? any way to verify the token?
Noticed that there is a dex as well, run by the same group?

**Comment by pippolee123** [comment]
Yes, the link for DEX is: https://swap.themis.capital/#/swap
USDT is issued by Cbridge, and their link is: https://cbridge.celer.network/

**Comment by ThemisCapital** [comment]
@g1nt0ki  Yes, the link for our DEX is: https://swap.themis.capital/#/swap
USDT is issued by Cbridge, and their link is: https://cbridge.celer.network/

**Pull request closed without merging**
