### PR TITLE
Add Rootstock RNS

### PR DESCRIPTION
**Pull request by jonathansmirnoff**
##### Logo (High resolution, will be shown with rounded borders):
RIF symbol 400X400px-01 (1)

##### methodology (what is being counted as tvl, how is tvl being calculated):  TVL is counted as the amount of RIF tokens held by `0x39e00D2616E792f50ddD33bBE46e8Bf55EAdEBeE` address. When a user buys a domain, it has to pay an amount of RIF tokens for it. These tokens go to the treasury address.
For more information go to: https://dev.rootstock.io/rif/rns/ and https://rif.technology/content-hub/rif-naming-service/

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/rns exports TVL: 
        
 
 
    rsk                       21.99 k
    
    total                    21.99 k

**Comment by g1nt0ki** [comment]
hi @jonathansmirnoff we can count this towards RIF team treasury but not as tvl since the user never gets back the tokens paid as fees right?

**Comment by g1nt0ki** [comment]
@jonathansmirnoff can I update it to a treasury adapter?

**Comment by jonathansmirnoff** [comment]
@g1nt0ki where will be displayed the adapter? `https://defillama.com/protocol/rns`?

**Comment by g1nt0ki** [comment]
two options, either show it as treasury here: https://defillama.com/protocol/rif-on-chain, it is the same project right? else can you add a fee/revenue adapter here? https://github.com/DefiLlama/dimension-adapters

**Comment by jonathansmirnoff** [comment]
To be accurate, RNS is part of https://rif.technology/ . So it is better to for the second option, dimension-adapter. Do I have to create a new PR there?

**Comment by g1nt0ki** [comment]
yes, please

**Comment by jonathansmirnoff** [comment]
Another question, where will it be shown finally? here https://defillama.com/treasuries or in another place? Do you have another example?

**Comment by g1nt0ki** [comment]
yeah, both there and on the protocol: https://defillama.com/protocol/ens

**Comment by jonathansmirnoff** [comment]
Ok, I will close this PR and create a new one on https://github.com/DefiLlama/dimension-adapters

**Pull request closed without merging**
