### PR TITLE
More edits

### PR DESCRIPTION
**Pull request by waynebruce0x**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/larix.js exports TVL: 
        
 
 
    solana                    135.09 M
    solana-borrowed           41.99 M
    borrowed                  41.99 M
    
    total                    135.09 M

**Comment by llamatester** [comment]
The adapter at projects/robovault/index.js exports TVL: 
        
 
 
    polygon                   10.0096623254
    fantom                    17.18 M
    
    total                    17.18 M

**Comment by llamatester** [comment]
The adapter at projects/larix.js exports TVL: 
        
 
 
    solana                    135.64 M
    solana-borrowed           42.10 M
    borrowed                  42.10 M
    
    total                    135.64 M

**Comment by llamatester** [comment]
The adapter at projects/robovault/index.js exports TVL: 
        
 
 
    fantom                    17.21 M
    polygon                   10.01017924785
    
    total                    17.21 M

**Comment by llamatester** [comment]
The adapter at projects/larix.js exports TVL: 
        
 
 
    solana-borrowed           42.39 M
    solana                    137.40 M
    borrowed                  42.39 M
    
    total                    137.40 M

**Comment by llamatester** [comment]
The adapter at projects/robovault/index.js exports TVL: 
        
 
 
    fantom                    17.22 M
    polygon                   10.01017924785
    
    total                    17.22 M

**Comment by llamatester** [comment]
The adapter at projects/trustednode/index.js exports TVL: 
        
 
 
    fantom                    0
    bsc                       0
    bsc-staking               288.89 k
    bsc-pool2                 210.64 k
    fantom-pool2              267.30 k
    staking                   288.89 k
    pool2                     477.95 k
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/larix.js exports TVL: 
        
 
 
    solana-borrowed           42.61 M
    solana                    137.42 M
    borrowed                  42.61 M
    
    total                    137.42 M

**Comment by llamatester** [comment]
The adapter at projects/robovault/index.js exports TVL: 
        
 
 
    polygon                   10.009178079749999
    fantom                    17.89 M
    
    total                    17.89 M

**Comment by llamatester** [comment]
The adapter at projects/larix.js exports TVL: 
        
 
 
    solana                    137.39 M
    solana-borrowed           42.61 M
    borrowed                  42.61 M
    
    total                    137.39 M

**Comment by llamatester** [comment]
The adapter at projects/luchadores/index.js exports TVL: 
        
 
 
    polygon-staking           201.71 k
    polygon-pool2             162.51 k
    polygon                   25.16 k
    staking                   201.71 k
    pool2                     162.51 k
    
    total                    25.16 k

**Comment by llamatester** [comment]
The adapter at projects/robovault/index.js exports TVL: 
        
 
 
    polygon                   10.009178079749999
    fantom                    17.88 M
    
    total                    17.88 M

**Comment by llamatester** [comment]
The adapter at projects/trustednode/index.js exports TVL: 
        
 
 
    bsc                       0
    fantom                    0
    bsc-staking               287.76 k
    bsc-pool2                 210.21 k
    fantom-pool2              267.04 k
    staking                   287.76 k
    pool2                     477.25 k
    
    total                    0

**Review by g1nt0ki — APPROVED** [review]

**Comment by llamatester** [comment]
The adapter at projects/larix.js exports TVL: 
        
 
 
    solana-borrowed           42.33 M
    solana                    135.89 M
    borrowed                  42.33 M
    
    total                    135.89 M

**Comment by llamatester** [comment]
The adapter at projects/luchadores/index.js exports TVL: 
        
 
 
    polygon-staking           204.07 k
    polygon-pool2             159.20 k
    polygon                   25.00 k
    staking                   204.07 k
    pool2                     159.20 k
    
    total                    25.00 k

**Comment by llamatester** [comment]
The adapter at projects/robovault/index.js exports TVL: 
        
 
 
    polygon                   10.01017924785
    fantom                    17.83 M
    
    total                    17.83 M

**Comment by llamatester** [comment]
Error while running adapter at projects/single/index.js: 
        
 
  
    
    
    TypeError: unwrapLPsAuto is not a function
        at getUserMasterChefBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/masterchef.js:317:11)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/single/index.js:30:3)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:57:25)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:149:9
        at async Promise.all (index 0)
        at async Promise.all (index 3)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:194:3

**Comment by llamatester** [comment]
The adapter at projects/larix.js exports TVL: 
        
 
 
    solana                    136.06 M
    solana-borrowed           42.29 M
    borrowed                  42.29 M
    
    total                    136.06 M

**Comment by llamatester** [comment]
The adapter at projects/luchadores/index.js exports TVL: 
        
 
 
    polygon-pool2             159.20 k
    polygon-staking           204.07 k
    polygon                   25.00 k
    pool2                     159.20 k
    staking                   204.07 k
    
    total                    25.00 k

**Comment by llamatester** [comment]
The adapter at projects/risk-harbor/index.js exports TVL: 
        
 
 
    arbitrum                  439.83 k
    ethereum                  3.51 M
    terra                     210.53 M
    
    total                    214.49 M

**Comment by llamatester** [comment]
The adapter at projects/robovault/index.js exports TVL: 
        
 
 
    fantom                    17.83 M
    polygon                   10.01017924785
    
    total                    17.83 M

**Comment by llamatester** [comment]
Error while running adapter at projects/single/index.js: 
        
 
  
    
    
    TypeError: unwrapLPsAuto is not a function
        at getUserMasterChefBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/masterchef.js:317:11)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/single/index.js:30:3)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:57:25)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:149:9
        at async Promise.all (index 0)
        at async Promise.all (index 3)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:194:3

**Comment by llamatester** [comment]
The adapter at projects/larix.js exports TVL: 
        
 
 
    solana-borrowed           42.21 M
    solana                    135.48 M
    borrowed                  42.21 M
    
    total                    135.48 M

**Comment by llamatester** [comment]
The adapter at projects/luchadores/index.js exports TVL: 
        
 
 
    polygon-staking           201.36 k
    polygon-pool2             157.07 k
    polygon                   24.89 k
    staking                   201.36 k
    pool2                     157.07 k
    
    total                    24.89 k

**Comment by llamatester** [comment]
The adapter at projects/risk-harbor/index.js exports TVL: 
        
 
 
    arbitrum                  439.83 k
    ethereum                  3.51 M
    terra                     210.32 M
    
    total                    214.28 M

**Comment by llamatester** [comment]
The adapter at projects/robovault/index.js exports TVL: 
        
 
 
    fantom                    17.83 M
    polygon                   10.01017924785
    
    total                    17.83 M

**Comment by llamatester** [comment]
The adapter at projects/single/index.js exports TVL: 
        
 
 
    cronos-staking            556.22 k
    cronos                    14.69 M
    cronos-pool2              2.99 M
    staking                   556.22 k
    pool2                     2.99 M
    
    total                    14.69 M

**Comment by llamatester** [comment]
The adapter at projects/trustednode/index.js exports TVL: 
        
 
 
    bsc                       0
    fantom                    0
    bsc-staking               288.29 k
    bsc-pool2                 210.37 k
    fantom-pool2              267.15 k
    staking                   288.29 k
    pool2                     477.51 k
    
    total                    0

**Pull request merged**
