### PR TITLE
Added penguin finance

### PR DESCRIPTION
**Pull request by dylan5394**
##### Twitter Link:
https://twitter.com/png_fi

##### Website Link:
https://png.fi/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://pbs.twimg.com/profile_images/1459135275834163205/ROSwe0Ll_400x400.jpg

##### Current TVL:
1.51M

##### Chain:
Solana

##### Short Description (to be shown on DefiLlama):
A Liquidity-as-a-Service Platform, built on Solana.

##### Token address and ticker if any:
Token not launched yet.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
1 - Dexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Coingecko

##### forkedFrom (Does your project originate from another project):
Bonding functionality is forked from OlympusDAO

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL was calculated as the total token value inside all of the protocol's liquidity pools. Staking is handled by a partner protocol for now.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/penguin-finance/index.js exports TVL: 
                
 
 
solana-staking            568.81 k
solana-pool2              826.47 k
solana                    679.99 k
staking                   568.81 k
pool2                     826.47 k

total                    679.99 k

**Comment by llamatester** [comment]
The adapter at projects/penguin-finance/index.js exports TVL: 
                
 
 
solana                    1.51 M

total                    1.51 M

**Comment by waynebruce0x** [comment]
This just counts the dex is that correct?

**Comment by waynebruce0x** [comment]
This just counts the dex is that correct?

**Comment by dylan5394** [comment]
Yeah, I talked with a team member, they mentioned staking is handled by a partner protocol for now.

**Pull request merged**
