### PR TITLE
API3 staking

### PR DESCRIPTION
**Pull request by jo-chemla**
WIP: understand why API3 staked in Pool DAO is higher than API3 mcap

API3 staking

##### Twitter Link:
https://twitter.com/API3DAO

##### Website Link:
https://api3.eth.link/#/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
dark bg svg: https://api3.eth.link/api3-logo-white.svg

##### Current TVL:
260M (staking)

##### Chain:
Ethereum mainnet

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
api3

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
7737

##### Short Description (to be shown on DefiLlama):
The Web3 API Economy: Create trustless applications that interact with Web APIs
Connect Smart Contracts to Real-World Data. API3 is leading the movement from legacy third-party oracle networks to first-party oracle solutions that deliver more security, efficiency, regulatory compliance, and simplicity

##### Token address and ticker if any:
API3 0x0b38210ea11411557c13457d4da7dc6ea731b88a

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Insurance / Other

##### methodology (what is being counted as tvl, how is tvl being calculated):
API3 TVL is all API3 token staked in the API3 DAO Pool contract

### CODE REVIEW

**Comment by jo-chemla** [comment]
The reason is vested API3 tokens can also be part of the staking contract, and be slashed in case of a reimbursing event. Statement from their team: "Since they can be slashed, they are liquid, therefore should be part of the staking TVL"

**Comment by 0xngmi** [comment]
I think we shouldn't count vested tokens, my reasons are:
- it opens a whole can of worms (what if a new project pops up, counts a lot of the tokens that are not circulating and massively inflates their TVL that way).
- these vested tokens cannot be valued at market price, first because they are illiquid and second because there's enough of them for the market to crash if a part of them were to be sold
- it just makes no sense that staked TVL is higher than marketcap, it's not just a small amount of vested tokens but a huge one

Something similar already happened with sovryn and there we chose not to count staking for them.

I propose not counting their vested tokens here, if it's very hard to calculate this I'd just not list API3 for now.

**Comment by jo-chemla** [comment]
@0xngmi yes totally understood. From the back of my mind, it was not easy to split vested and unvested, their team did not come up with a way to do it, need to investigate or ask the team again. A rule of thumb would be to apply the vested over total ratio to the staked token volume, which might as well be really inaccurate. 

Most metrics regarding vesting are available here, seems like 35M out of 48M API3 tokens are vested. If they display it on this page, then it is possible to query it https://enormous.cloud/dao/api3/tracker/wallets

**Comment by jo-chemla** [comment]
Pushed a fix to remove vested tokens from staking TVL! This is retrieved from the contract `api3CirculatingSupply = "cD34bC5B03C954268d27c9Bc165a623c318bD0a8"`

**Pull request merged**
