### PR TITLE
add skydex tvl

### PR DESCRIPTION
**Pull request by skydest**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
SkyDex

##### Twitter Link:
https://twitter.com/SkyDex_zksync

##### Website Link:
https://skydex.pro/

##### Logo (High resolution, will be shown with rounded borders):
https://skydex.pro/favicon.ico

##### Current TVL:
42

##### Chain:
[zkSync Era](https://defillama.com/chain/zkSync%20Era)

##### Short Description (to be shown on DefiLlama):
First Stableswap on Zksync Era Swap stablecoins at minimal slippage and stake at maximum yield. Support Stablecoin and LSDfi!

##### Token address and ticker if any:
0xA5FcA69BDbd1D55Aa8698dca1486F5B5601D64a6

##### Category (full list at https://defillama.com/categories) *Please choose only one:
[Dexes](https://defillama.com/protocols/dexes)

##### methodology (what is being counted as tvl, how is tvl being calculated):
SkyDex counts the staking values as tvl

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by g1nt0ki** [comment]
hi @skydest , any idea why assetOf calls fail for '0xe59eA42466f3dD0ea620A622701085983A068863' ?

**Comment by llamatester** [comment]
Error while running adapter at projects/skydex: 
        
 
  
    
    
    Error: Multicall failed!
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/abi/index.js:286:35

**Comment by skydest** [comment]
We have fixed this issue, please try again

**Comment by skydest** [comment]
> hi @skydest , any idea why assetOf calls fail for '0xe59eA42466f3dD0ea620A622701085983A068863' ?

We have fixed this issue, please try again

**Pull request merged**
