### PR TITLE
add usdx.money USDX

### PR DESCRIPTION
**Pull request by brucelsoon**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
usdx.money USDX

##### Twitter Link:
https://x.com/usdx_money 

##### Website Link:
https://usdx.money/

##### Logo (High resolution, will be shown with rounded borders):
https://usdx.money/logo192.png

##### Current TVL:
bsc                       180.06 M
ethereum                  1.27 M
arbitrum                  40.83 k

total                    181.37 M

##### Chain:
BNB Smart Chain
Ethereum Mainnet
Arbitrum One

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
usdx-money-usdx

##### Short Description (to be shown on DefiLlama):
USDX (https://usdx.money/｜twitter: https://x.com/usdx_money) is a synthetic USD stablecoin built for the crypto ecosystem. It offers a crypto-native stablecoin solution that does not rely on traditional banking infrastructure which is censorship-resistant, scalable, and highly stable. Furthermore, it provides a multiple-layer savings tool including funding rate and crypto ecosystem yield accessible worldwide in USD denomination.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Basis Trading

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/usdx exports TVL: 
        
 
 
    bsc                       180.06 M
    ethereum                  1.27 M
    arbitrum                  40.83 k
    
    total                    181.37 M

**Comment by Define101** [comment]
@brucelsoon please provide the collateral addresses. Also the collateral page was updated 3 months ago

**Comment by Define101** [comment]
image

**Comment by brucelsoon** [comment]
@Define101 sure the addresses are

BNB Chain: 0x667cc3145f9f63bd796a1a62ef504aaa160550e5; 0x2587593e788Fde2Bdb63aF95Aab62f6b5bbd2cA9
Ethereum: 0x2587593e788Fde2Bdb63aF95Aab62f6b5bbd2cA9; 0x26670dc72a97c983d67877ec880293eb10672aa1
Arbitrum One:0x08e69d8665325fd2d7ccc8852205004548941699; 0x9f2ac08121b020f583f6ac3e17cdc0fe47d7a89f

These are Binance trading accounts / Ceffu deposit addresses. As USDX is backed by delta neutral positions similar to Ethena USDe. We share similar methodology to build the stablecoins and currently USDX only uses Binance / Ceffu as its trading platform.

For the collateral page update, as the past few months, the funding rate is so low and the USDX project actually not encounter meaningful minting activities bigger than the threshold, therefore there were no auto update since then. And thanks for noting this, we will change the threshold and will update the collateral page accordingly.

**Comment by Define101** [comment]
@brucelsoon does those wallets belong to the project? Why for example 0x667cC3145F9F63bd796a1a62eF504aAa160550E5 keeps depositing ETH and DODO tokens, when those are not even available to deposit on your website?

**Comment by Define101** [comment]
And what is the relationship between USDX and the previous project called Babel Finance

 0x08e69D8665325Fd2d7CCc8852205004548941699

**Comment by Define101** [comment]
And must of the wallets have more than 2/3 years of history

**Comment by brucelsoon** [comment]
Please find the responses to the questions:

1 does those wallets belong to the project? Why for example 0x667cC3145F9F63bd796a1a62eF504aAa160550E5 keeps depositing ETH and DODO tokens, when those are not even available to deposit on your website? 

For BNB: 0x667cC3145F9F63bd796a1a62eF504aAa160550E5, it is our partner’s deposit address, back then we have not set-up the ceffu  custodian co-management account for the service provider therefore we directly deposit money into the trading account in order to run the strategy on time. And thereafter we have been working on Ceffu account set up and all the facilitating infra. And now the new funds will go through Ceffu and mirror to the partner’s trading account and we will publish the collateral addresses soon on website. For Arbitrum One: 0x08e69d8665325fd2d7ccc8852205004548941699; 0x9f2ac08121b020f583f6ac3e17cdc0fe47d7a89f, Ceffu doest not support Arbitrum One deposit yet therefore we deposit the funds directly to partner’s deposit address.  We requested Ceffu to support Arbitrum One and pending their upgrade. 

2 And what is the relationship between USDX and the previous project called Babel Finance 0x08e69D8665325Fd2d7CCc8852205004548941699

There is no direct relationship between USDX and Babel Finance but they share some of the common stakeholders. 

3 And must(some) of the wallets have more than 2/3 years of history

Please refer to response to question 1.

**Comment by Define101** [comment]
If the goal is to make Basis trading (funding rate) why does any of the wallets hold significant balances? At least 50% of the assets should be held as the long side trade, while the other half should be the short position (on a exchange)

**Comment by Define101** [comment]
And since users can only deposit USDT. What are you hedging? Do you buy ETH/BTC with the value users deposit? It does not make any sense.

**Comment by Define101** [comment]
"0x667cC3145F9F63bd796a1a62eF504aAa160550E5" does this belong to https://www.metalpha.net/ ?

**Comment by Define101** [comment]
And who belongs this wallet? 0x9537Bc0546506785bD1eBd19fD67d1F06800D185

**Comment by brucelsoon** [comment]
Please find the responses below:

1 If the goal is to make Basis trading (funding rate) why does any of the wallets hold significant balances? At least 50% of the assets should be held as the long side trade, while the other half should be the short position (on a exchange）

We are deploying multiple-coin strategy, namely the strategy is chasing the higher yield while considering the liquidity, as such we switch between different spost and perpetual contracts and for this reason, those coins will sit with exchange mirror accounts. And since we are using Ceffu mirroring function so these addresses assets will be collected to their cold wallet rather than sitting at individual addresses. 

2 And since users can only deposit USDT. What are you hedging? Do you buy ETH/BTC with the value users deposit? It does not make any sense.

USDT will be used buy different coins spots and hedge through their perpetual to earn funding fees. This is actually the most traditional basis trading strategy in crypto, and the yield was previously only available for high net worth or institutions but we want to democratise it to everyone through DeFi. For fundamental mechanism, please refer to the paper “Fundamentals of Perpetual Futures” by He, Manela, Ross, and Wachter (https://arxiv.org/pdf/2212.06888v5). This paper summarized the comprehensive strategies on how to maximize the return with balanced risks. And for a comparison, please find in the summary onepager in the following link: https://imgur.com/a/Hvp3wua

The multiple-coin strategy is performing better than BTC/ETH strategies in past four years with similar risks. 

If you need to understand further on the mechanism, please also refer to https://docsend.com/view/u32uj8dkatnmkjpb 

3 "0x667cC3145F9F63bd796a1a62eF504aAa160550E5" does this belong to https://www.metalpha.net/ ?

No it belongs to https://www.antalpha.com/ our major partner.

4 And who belongs this wallet? 0x9537Bc0546506785bD1eBd19fD67d1F06800D185

This belongs to SolvBTC, please refer to https://app.solv.finance/dashboards  and also custodied with Antalpha.

**Pull request merged**
