### PR TITLE
Adding ArchiFinance on arbitrum chain to defillama adapters

### PR DESCRIPTION
**Pull request by ArchiFinance**
Twitter Link: https://twitter.com/archi_fi
List of audit links if any: https://certificate.quantstamp.com/full/archi-finance/abb48b19-672a-4390-bf11-59c485978d61/index.html
Website Link: https://archi.finance/
Current TVL: $2.07 M 
Chain: Arbitrum
Coingecko ID: No
Coinmarketcap ID: No
Short Description: Archi Finance is composable leveraged yield farming protocol. It has two sides to it: passive liquidity providers who earns low risk interests by supplying single-asset liquidity; and degen farmers who borrow those assets to achieve a higher APY. GMX will be the platform Archi integrated in v1.
Token address and ticker if any: No
Category: https://defillama.com/protocols/Leveraged%20Farming
Oracle used: Chainlink & GMX
forkedFrom: No
methodology: The TVL of ArchiFinance is calculated by adding the total liquidity and borrowing amount.
Logo:
Logo_Black
Logo_White

### CODE REVIEW

**Comment by ArchiFinance** [comment]
@g1nt0ki

**Comment by llamatester** [comment]
The adapter at projects/archi-finance exports TVL: 
        
 
 
    arbitrum                  2.06 M
    arbitrum-borrowed         1.57 M
    borrowed                  1.57 M
    
    total                    2.06 M

**Comment by ArchiFinance** [comment]
> @ArchiFinance can you verify my refactor?

Okay, it can be like this.

**Comment by ArchiFinance** [comment]
Thx @g1nt0ki

**Pull request merged**
