### PR TITLE
Add BrincX

### PR DESCRIPTION
**Pull request by mentoc2020**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
• BrincX

##### Twitter Link:
• https://twitter.com/Brinc_X

##### List of audit links if any:
• n/a

##### Website Link:
• https://brincx.io

##### Logo (High resolution, will be shown with rounded borders):
• https://raw.githubusercontent.com/mentoc2020/public-storage/main/BRINC%20X-5.png

##### Current TVL:
• $144.58k

##### Treasury Addresses (if the protocol has treasury)
0x30d5D30e43b6167a345f3D71d61673464e16d711

##### Chain:
• ARBITRUM

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
• n/a

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
• n/a

##### Short Description (to be shown on DefiLlama):
• BrincX provides easy-to-use DeFi vaults and analytics to allow users to earn real returns.

##### Token address and ticker if any:
• n/a

##### Category (full list at https://defillama.com/categories) *Please choose only one:
• Yield

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
• n/a

##### forkedFrom (Does your project originate from another project):
• Not forked

##### methodology (what is being counted as tvl, how is tvl being calculated):
• Liquidity deposited in the UniswapV3 Pool

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/brincx exports TVL: 
        
 
 
    arbitrum                  143.54 k
    
    total                    143.54 k

**Comment by g1nt0ki** [comment]
@mentoc2020 there are two issues with the PR, we cant count treasury as tvl and to count something towards treasury metric, the tokens must be in gnosis multisig, not EOAs

**Comment by g1nt0ki** [comment]
when you say we, do you mean the team/team funds or the protocol?
For it to be considered tvl, the uni v3 nfts must be in the smart contract belonging to the protocol.

**Comment by mentoc2020** [comment]
I see... I understand, thank you.

**Comment by llamatester** [comment]
The adapter at projects/brincx exports TVL: 
        
 
 
    arbitrum                  143.54 k
    
    total                    143.54 k

**Comment by mentoc2020** [comment]
If we changed treasury to multisig, would it be possible to register?
*multisig will own the Uniswap Lp token.

**Comment by g1nt0ki** [comment]
so far, it is still in EOA? 0x30d5D30e43b6167a345f3D71d61673464e16d711
once it is in multisig, we can count it towards treasury

But your project still needs to have tvl to be listed, so if you are managing uni v3 positions for an user, it needs to be via smart contracts.

**Pull request closed without merging**
