### PR TITLE
Ethos Reserve integration

### PR DESCRIPTION
**Pull request by 0xTheCrow**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama): 
Ethos Reserve

##### Twitter Link: 
https://twitter.com/EthosReserve 

##### List of audit links if any: 
Code4Arena, Certik

##### Logo (High resolution, will be shown with rounded borders): 
https://ethos-reserve.s3.ca-central-1.amazonaws.com/assets/ethos_icon.svg

##### Current TVL: 
$11,573,779.55 

##### Chain: 
Optimism 

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): 
24370

##### Short Description (to be shown on DefiLlama): 
Ethos Reserve is a decentralized borrowing protocol that allows users to take out 0% interest loans against Bitcoin, Ethereum, or Optimism collateral via the Ethos Reserve Note (ERN). A portion of deposited assets are utilized via private vaults to generate delta neutral yield that is used to create a self-sustaining yield flywheel for the protocol.

Token Information

##### Token address and ticker if any: 
ERN

##### Category (full list at https://defillama.com/categories) *Please choose only one: 
CDP

##### forkedFrom (Does your project originate from another project): 
Liquity

##### methodology (what is being counted as tvl, how is tvl being calculated):
Ethos Reserve TVL is received from the Ethos Reserve subgraph with the help of the Byte Masons token price API.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/ethos exports TVL: 
        
 
 
    optimism                  11.65 M
    
    total                    11.65 M

**Comment by g1nt0ki** [comment]
hi @0xTheCrow , thanks for the PR, I have refactored it a bit here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/6299 let me know if I missed something. We dont count own tokens part of stability pool as tvl, like LUSD in their stability pool, so I have removed that part.

**Comment by 0xTheCrow** [comment]
Hey @g1nt0ki thanks for taking a look! I'm ok with removal of the stability pool tvl, does the same go for the staking pool tvl? It uses the bOATH token. Thanks!

**Comment by g1nt0ki** [comment]
hi, the staked bOATH can be counteed as pool2, not as tvl

**Comment by 0xTheCrow** [comment]
Sure, would you prefer I include the pool2 stat in this PR or would you like to get this PR in and then for me to open another with the pool2 changes? I'm open to either

**Comment by g1nt0ki** [comment]
hi @0xTheCrow closing this as I have merged your changes here with some refactor here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/6299

Please go over the code and let me know if I have introduced some bugs.

**Comment by 0xTheCrow** [comment]
Looks great, thanks for all your help!

**Pull request closed without merging**
