### PR TITLE
Update JEXchange pools

### PR DESCRIPTION
**Pull request by javier-nft**
1st address is our orderbook smart contract
other addresses are liquidity pools

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/jexchange exports TVL: 
        
 
 
    elrond                    70.52 k
    
    total                    70.52 k

**Comment by g1nt0ki** [comment]
@javier-nft thanks for the update, is there some way to query list of pools like WEGLD-JEX and such?

**Comment by javier-nft** [comment]
> @javier-nft thanks for the update, is there some way to query list of pools like WEGLD-JEX and such?

Yes there is this endpoint:
https://api.jexchange.io/pools

and for each pools you can get more details using:
https://api.jexchange.io/pools/{lp_token}
eg: https://api.jexchange.io/pools/LPETHBTC-8b8a1f

**Comment by g1nt0ki** [comment]
thanks, I have updated the adapter

**Comment by javier-nft** [comment]
Thanks.

The TVL dropped a little but I think there is a bug making the TVL X2 using the previous method

```sumTokensExport({ chain: 'elrond', owner: 'erd1qqqqqqqqqqqqqpgqmmxzmktd09gq0hldtczerlv444ykt3pz6avsnys6m9', })```

**Comment by g1nt0ki** [comment]
hi, we will delete the wrong tvl datapoints from the chart

**Pull request merged**
