### PR TITLE
add project fbtc

### PR DESCRIPTION
**Pull request by lyfmantle**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/fbtc exports TVL: 
        
 
 
    ethereum                  44.68 M
    mantle                    24.10 M
    bsc                       755
    
    total                    68.78 M

**Comment by g1nt0ki** [comment]
@lyfmantle thanks for the PR, can you fill in the project details? also, can you share the address on bitcoin network where the coins are locked, I am guessing thats how fbtc is generated?

**Comment by lyfmantle** [comment]
@g1nt0ki hi, thanks for you relay. FBTC is a decentralized protocol that enables the seamless transfer and management of Bitcoin (BTC) across various blockchain networks. here is its details docs: https://docs.fbtc.com/security/bitcoin-reserve-address

**Comment by g1nt0ki** [comment]
@lyfmantle thanks for the details, in a bridge, we like to count tvl on the source chain.

**Comment by llamatester** [comment]
The adapter at projects/fbtc exports TVL: 
        
 
 
    bitcoin                   67.31 M
    
    total                    67.31 M

**Comment by lyfmantle** [comment]
hi, @g1nt0ki, in the updated code, I found that only indexed the tvl of fixed address, but the dynamic addresses that were not indexed. can you help us to index the dynamic address(https://docs.fbtc.com/security/bitcoin-reserve-address#dynamic-address ) part in the code as well?

**Comment by g1nt0ki** [comment]
@lyfmantle thanks for pointing it out, fixed it here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/5346341b19363e559adc04695a895a16ffea88d5

**Pull request merged**
