### PR TITLE
Update Desyn strategy Pools

### PR DESCRIPTION
**Pull request by santinoYoung**
##### Name (to be shown on DefiLlama):
Desyn

##### Chain:
ethereum, arbitrum, merlin, btr, mode, zklink, core, ailayer

Previously segmented based on chain factory contracts, now the strategy is segmented based on pools：
1. Name: Desyn Safe, Category: Farm
2. Name: Desyn Basis Trading,  Category:  Basis Trading
3. Name: Desyn Liquid Strategy,  Category: Yield Aggregator

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/desyn-farm exports TVL: 
        
 
 
    btr                       126.41 M
    mode                      41.39 M
    zklink                    21.47 M
    merlin                    2.23 M
    ethereum                  36.04 k
    arbitrum                  97
    ailayer                   14
    core                      7
    
    total                    191.53 M

**Comment by llamatester** [comment]
The adapter at projects/desyn-basisTrading exports TVL: 
        
 
 
    ethereum                  210
    arbitrum                  0
    merlin                    0
    btr                       0
    mode                      0
    zklink                    0
    core                      0
    ailayer                   0
    
    total                    209.74779

**Comment by llamatester** [comment]
The adapter at projects/desyn-yieldAggregator exports TVL: 
        
 
 
    core                      119.95 M
    btr                       105.85 M
    ethereum                  4.20 M
    merlin                    145
    arbitrum                  56
    mode                      0
    zklink                    0
    ailayer                   0
    
    total                    229.99 M

**Comment by llamatester** [comment]
The adapter at projects/desyn-farm exports TVL: 
        
 
 
    btr                       126.31 M
    mode                      41.40 M
    zklink                    21.47 M
    merlin                    2.24 M
    ethereum                  36.03 k
    arbitrum                  97
    ailayer                   14
    core                      7
    
    total                    191.46 M

**Comment by llamatester** [comment]
The adapter at projects/desyn-yieldAggregator exports TVL: 
        
 
 
    core                      119.89 M
    btr                       105.78 M
    ethereum                  4.20 M
    merlin                    145
    arbitrum                  56
    mode                      0
    zklink                    0
    ailayer                   0
    
    total                    229.87 M

**Review by g1nt0ki — COMMENTED** [review]
I would wait for change to use rest api for pulling pool list with categories, this way, we dont have to keep updating the adapters

**Comment by santinoYoung** [comment]
> I would wait for change to use rest api for pulling pool list with categories, this way, we dont have to keep updating the adapters

This is my apis，https://api.desyn.io/etf/defillama/get_pool_list?strategy_type=StrategyType1，How do I replace the fixed config?

**Comment by llamatester** [comment]
The adapter at projects/desyn-farm exports TVL: 
        
 
 
    core                      0
    zklink                    0
    arbitrum                  0
    btr                       0
    ailayer                   0
    ethereum                  0
    mode                      0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/desyn-basisTrading exports TVL: 
        
 
 
    ethereum                  210
    arbitrum                  0
    merlin                    0
    btr                       0
    mode                      0
    zklink                    0
    core                      0
    ailayer                   0
    
    total                    209.8299

**Comment by llamatester** [comment]
The adapter at projects/desyn-yieldAggregator exports TVL: 
        
 
 
    core                      118.93 M
    btr                       105.11 M
    ethereum                  4.18 M
    merlin                    144
    arbitrum                  56
    mode                      0
    zklink                    0
    ailayer                   0
    
    total                    228.22 M

**Comment by llamatester** [comment]
The adapter at projects/desyn-farm exports TVL: 
        
 
 
    mode                      0
    arbitrum                  0
    zklink                    0
    core                      0
    btr                       0
    ethereum                  0
    ailayer                   0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/desyn-basisTrading exports TVL: 
        
 
 
    ethereum                  210
    arbitrum                  0
    merlin                    0
    btr                       0
    mode                      0
    zklink                    0
    core                      0
    ailayer                   0
    
    total                    209.87715

**Comment by llamatester** [comment]
The adapter at projects/desyn-yieldAggregator exports TVL: 
        
 
 
    core                      118.88 M
    btr                       104.83 M
    ethereum                  4.18 M
    merlin                    144
    arbitrum                  56
    mode                      0
    zklink                    0
    ailayer                   0
    
    total                    227.89 M

**Comment by santinoYoung** [comment]
> The adapter at projects/desyn-farm exports TVL:
> 
> ```
> core                      0
> zklink                    0
> arbitrum                  0
> btr                       0
> ailayer                   0
> ethereum                  0
> mode                      0
> 
> total                    0 
> ```

HI, team, @g1nt0ki  Why is all the data missing after submitting using the rest api?

**Comment by llamatester** [comment]
The adapter at projects/desyn-farm exports TVL: 
        
 
 
    btr                       124.34 M
    mode                      40.45 M
    zklink                    20.59 M
    merlin                    2.05 M
    ethereum                  35.43 k
    arbitrum                  95
    ailayer                   14
    core                      7
    scroll                    0
    linea                     0
    
    total                    187.47 M

**Comment by llamatester** [comment]
The adapter at projects/desyn-basisTrading exports TVL: 
        
 
 
    ethereum                  210
    merlin                    0
    ailayer                   0
    arbitrum                  0
    linea                     0
    zklink                    0
    core                      0
    mode                      0
    btr                       0
    scroll                    0
    
    total                    209.86245

**Comment by llamatester** [comment]
The adapter at projects/desyn-yieldAggregator exports TVL: 
        
 
 
    core                      117.78 M
    btr                       104.14 M
    ethereum                  4.16 M
    merlin                    143
    arbitrum                  54
    mode                      2
    ailayer                   0
    zklink                    0
    scroll                    0
    linea                     0
    
    total                    226.09 M

**Comment by g1nt0ki** [comment]
sorry for the delay

**Comment by llamatester** [comment]
The adapter at projects/desyn-farm exports TVL: 
        
 
 
    btr                       136.91 M
    mode                      44.80 M
    zklink                    24.14 M
    merlin                    2.34 M
    ethereum                  38.99 k
    arbitrum                  105
    ailayer                   15
    core                      7
    linea                     0
    scroll                    0
    
    total                    208.23 M

**Comment by llamatester** [comment]
The adapter at projects/desyn-basisTrading exports TVL: 
        
 
 
    ethereum                  210
    arbitrum                  0
    btr                       0
    mode                      0
    zklink                    0
    core                      0
    ailayer                   0
    linea                     0
    merlin                    0
    scroll                    0
    
    total                    209.94519

**Comment by llamatester** [comment]
The adapter at projects/desyn-yieldAggregator exports TVL: 
        
 
 
    core                      144.44 M
    btr                       114.66 M
    ethereum                  39.58 M
    merlin                    157
    arbitrum                  64
    mode                      10
    zklink                    0
    ailayer                   0
    linea                     0
    scroll                    0
    
    total                    298.69 M

**Comment by santinoYoung** [comment]
> sorry for the delay

Thx~ team

**Comment by llamatester** [comment]
The adapter at projects/desyn-farm exports TVL: 
        
 
 
    btr                       139.17 M
    mode                      45.62 M
    zklink                    25.03 M
    merlin                    2.43 M
    ethereum                  39.68 k
    arbitrum                  107
    ailayer                   15
    core                      8
    linea                     0
    scroll                    0
    
    total                    212.29 M

**Comment by llamatester** [comment]
The adapter at projects/desyn-basisTrading exports TVL: 
        
 
 
    ethereum                  210
    arbitrum                  0
    btr                       0
    mode                      0
    zklink                    0
    core                      0
    ailayer                   0
    linea                     0
    merlin                    0
    scroll                    0
    
    total                    210.20999999999998

**Comment by llamatester** [comment]
The adapter at projects/desyn-yieldAggregator exports TVL: 
        
 
 
    core                      147.26 M
    btr                       116.84 M
    ethereum                  4.47 M
    merlin                    160
    arbitrum                  66
    mode                      11
    zklink                    0
    ailayer                   0
    linea                     0
    scroll                    0
    
    total                    268.57 M

**Comment by santinoYoung** [comment]
@g1nt0ki Hi，Team，tslint what's going on? I didn't touch the file there.

**Comment by llamatester** [comment]
The adapter at projects/desyn-farm exports TVL: 
        
 
 
    btr                       139.53 M
    mode                      45.62 M
    zklink                    25.04 M
    merlin                    2.43 M
    ethereum                  39.81 k
    arbitrum                  107
    ailayer                   15
    core                      8
    linea                     0
    scroll                    0
    
    total                    212.66 M

**Comment by llamatester** [comment]
The adapter at projects/desyn-basisTrading exports TVL: 
        
 
 
    ethereum                  210
    arbitrum                  0
    btr                       0
    mode                      0
    zklink                    0
    core                      0
    ailayer                   0
    linea                     0
    merlin                    0
    scroll                    0
    
    total                    210.20999999999998

**Comment by llamatester** [comment]
The adapter at projects/desyn-yieldAggregator exports TVL: 
        
 
 
    core                      147.44 M
    btr                       116.86 M
    ethereum                  4.48 M
    merlin                    160
    arbitrum                  66
    mode                      11
    zklink                    0
    ailayer                   0
    linea                     0
    scroll                    0
    
    total                    268.78 M

**Pull request merged**
