### PR TITLE
feat: add mango farmers club

### PR DESCRIPTION
**Pull request by graykode**
##### Treasury Addresses (if the protocol has treasury)
**MangoPublicRegistration(0x05Cd3c8Ded966BE2556A8A83190aEF845f24eB76)**

##### Short Description (to be shown on DefiLlama):
The first community token project on Polygon zkEVM

##### Token address and ticker if any:
**usdc(0xA8CE8aee21bC2A48a5EF670afCc9274C7bbbC035)**

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Services

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/mango-farmers-club: 
        
 
  
    
    
    Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="allPairsLength()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    Truncated error stack:
        at Interface.decodeFunctionResult (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/abi/lib/interface.js:388:23)

**Comment by llamatester** [comment]
Error while running adapter at projects/mango-farmers-club: 
        
 
  
    
    
    Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="allPairsLength()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    Truncated error stack:
        at Interface.decodeFunctionResult (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/abi/lib/interface.js:388:23)

**Comment by llamatester** [comment]
Error while running adapter at projects/mango-farmers-club: 
        
 
  
    
    
    Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0x05Cd3c8Ded966BE2556A8A83190aEF845f24eB76","data":"0xf6153ccd","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:654:52
        at Array.forEach (<anonymous>)

**Comment by llamatester** [comment]
The adapter at projects/mango-farmers-club exports TVL: 
        
 
 
    polygon_zkevm             16.10 k
    
    total                    16.10 k

**Comment by llamatester** [comment]
The adapter at projects/mango-farmers-club exports TVL: 
        
 
 
    polygon_zkevm             16.11 k
    
    total                    16.11 k

**Comment by g1nt0ki** [comment]
@graykode thanks for the PR; I have simplified it a bit here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/5969

**Pull request merged**
