### PR TITLE
Baso

### PR DESCRIPTION
**Pull request by basofinace**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Baso Finance

##### Twitter Link:
https://twitter.com/Baso_Finance

##### Website Link:
https://www.baso.finance/

##### Logo (High resolution, will be shown with rounded borders):
https://www.baso.finance/tokens/baso.png

##### Current TVL:
130K

##### Treasury Addresses (if the protocol has treasury)
0x1566F47dc7bCFE0ac3849a50CfEDa8A10aB21059

##### Chain:
base

##### Short Description (to be shown on DefiLlama):
First fully community-owned and decentralized ve(3,3) dex on base

##### Token address and ticker if any:
https://basescan.org/address/0x23E1A3BcDcEE4C59209d8871140eB7DD2bD9d1cE

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### forkedFrom (Does your project originate from another project):
velodrome

##### methodology (what is being counted as tvl, how is tvl being calculated):
USD

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/baso exports TVL: 
        
 
 
    base                      119.99 k
    
    total                    119.99 k

**Comment by g1nt0ki** [comment]
not sure what is changed in this PR

**Comment by basofinace** [comment]
> not sure what is changed in this PR
Hello, has this pull request been approved? How long does it usually take to see the data?

**Comment by g1nt0ki** [comment]
@basofinace it is merged, will be listed in the next 24 hours

**Pull request closed without merging**
