### PR TITLE
feat:add bitparty

### PR DESCRIPTION
**Pull request by bitpartylabs003**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bitparty exports TVL: 
        
 
 
    btr                       0
    
    total                    0

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
what is the this Project? you have provided no details

**Comment by bitpartylabs003** [comment]
Name (to be shown on DefiLlama):Bitparty
Twitter Link: https://twitter.com/BitPartyTech
List of audit links if any: https://scalebit.xyz/reports/BitParty-Final-Audit-Report.pdf
Website Link: https://bitlayer.bitparty.tech/
Logo (High resolution, will be shown with rounded borders):
Current TVL: 0
Treasury Addresses (if the protocol has treasury):None
Chain: Bitlayer
Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)None
Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)None
Short Description (to be shown on DefiLlama): BitParty is the first "Asset Gamified Community Network" in the #BTC ecosystem.
Token address and ticker if any:None
Category (full list at https://defillama.com/categories) *Please choose only one: Staking Pool
Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):None
Implementation Details: Briefly describe how the oracle is integrated into your project:None
Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:None
forkedFrom (Does your project originate from another project):None
methodology (what is being counted as tvl, how is tvl being calculated): Users stake their assets into TVL, which is calculated in aggregate terms.
Github org/user (Optional, if your code is open source, we can track activity):None

**Comment by bitpartylabs003** [comment]
The list has been submitted here
https://github.com/DefiLlama/defillama-server/commit/4f27b4bb3a49e66904a0ede2cdf2896b0b87fe50

**Pull request merged**
