### PR TITLE
Add Onespace

### PR DESCRIPTION
**Pull request by samurai-Nash**
**NOTE**

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

Onespace

##### Twitter Link:

https://twitter.com/1space_me

##### List of audit links if any:

Not yet

##### Website Link:

https://1space.me/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

https://1space.me/images/1SP_logo.png
https://1space.me/images/one.svg

##### Current TVL:

~ $12500

##### Chain:

Solana

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

onespace

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

---

##### Short Description (to be shown on DefiLlama):

It is a cross-chain decentralized crypto platform combines applications for trading, swap, staking, farms, NFTs and more.
We want to create ONE crypto SPACE with a simple and clear interface for decentralized trading.
All of our applications built in Solana network.

##### Token address and ticker if any:

2zzC22UBgJGCYPdFyo7GDwz7YHq5SozJc1nnBqLU8oZb
1SP

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Dexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

None

##### forkedFrom (Does your project originate from another project):

None

##### methodology (what is being counted as tvl, how is tvl being calculated):

Token price and pairs

### CODE REVIEW

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
@samurai-Nash Sorry, but this PR is incomplete, please revert back the changes to PR template file, is the dex liquidity separate from openbook? can you provide some details like contract address of the dex?

**Comment by ZeroQ4** [comment]
> @samurai-Nash Sorry, but this PR is incomplete, please revert back the changes to PR template file, is the dex liquidity separate from openbook? can you provide some details like contract address of the dex?



> 

It is not entirely clear what changes should be returned?

Our DEX uses Jupiter core and Openbook.
https://dex.1space.me/
https://app.1space.me/

TVL:
Raydium
1SP-USDC
$13,889.89

OpenBook
1SP-USDC
$1,025.97

**Comment by samurai-Nash** [comment]
> @samurai-Nash Sorry, but this PR is incomplete, please revert back the changes to PR template file, is the dex liquidity separate from openbook? can you provide some details like contract address of the dex?

It is not entirely clear what changes should be returned?

Our DEX uses Jupiter core and Openbook.
https://dex.1space.me/
https://app.1space.me/

TVL:
Raydium
1SP-USDC
$13,889.89

OpenBook
1SP-USDC
$1,025.97

**Comment by g1nt0ki** [comment]
@samurai-Nash these pool tvl belong to raydium/OpenBook. What tokens are locked in your pools?

I am asking you to revert the changes to `pull_request_template.md` file, that is common for everyone

**Comment by samurai-Nash** [comment]
> @samurai-Nash these pool tvl belong to raydium/OpenBook. What tokens are locked in your pools?
> 
> I am asking you to revert the changes to `pull_request_template.md` file, that is common for everyone

@g1nt0ki We do not block other tokens, we do not have pools. Our DEX are built on the protocol Jupiter and OpenBook, only for trading

**Comment by g1nt0ki** [comment]
> 
> @g1nt0ki We do not block other tokens, we do not have pools. Our DEX are built on the protocol Jupiter and OpenBook, only for trading

Sorry, then we cant list you because you have 0 tvl.

**Comment by samurai-Nash** [comment]
> > @g1nt0ki We do not block other tokens, we do not have pools. Our DEX are built on the protocol Jupiter and OpenBook, only for trading
> 
> Sorry, then we cant list you because you have 0 tvl.

@g1nt0ki Why not? Do you have projects with 0 tvl.

**Comment by g1nt0ki** [comment]
@samurai-Nash We dont track projects with 0 tvl from get go, they have at least pool2/staking

we have some projects that have 0 tvl atm but had tvl at some point.

**Pull request closed without merging**
