### PR TITLE
Add jungledefi adapter

### PR DESCRIPTION
**Pull request by nick3842**
Twitter Link: https://twitter.com/jungledefi

##### List of audit links if any:

Website Link: https://jungledefi.io/

Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): 
https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/GePFQaZKHcWE5vpxHfviQtH5jgxokSs51Y5Q4zgBiMDs/logo.png

Chain: Solana

Coingecko ID (so your TVL can appear on Coingecko):
jungle-defi

##### Short Description (to be shown on DefiLlama):
Jungle Finance is a Defi primitive protocol built on the Solana blockchain, allowing users to create, buy, sell and redeem their staking or farm rewards instantaneously.

Token address and ticker if any: GePFQaZKHcWE5vpxHfviQtH5jgxokSs51Y5Q4zgBiMDs
JFI

Category (full list at https://defillama.com/categories) *Please choose only one: derivatives

##### forkedFrom (Does your project originate from another project):

methodology (what is being counted as tvl, how is tvl being calculated): TVL is calculated by computing the value of LP tokens, wrapped sol, and USDC in the treasury.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/jungle-defi/index.js exports TVL: 
        
 
 
    
    total                    260.69 k

**Comment by g1nt0ki** [comment]
Can this be calculated using on-chain calls instead? We've got a guide on how to use our SDK here: https://docs.llama.fi/list-your-project/submit-a-project

Are the LP tokens staked by users in your app, or are they your token pair in Raydium
Also, technically, treasury is not part of tvl, can you count it under the keyword `treasury`

**Comment by nick3842** [comment]
It's protocol owned liquidity. We may implement an SDK adapter later.

**Comment by waynebruce0x** [comment]
Who deposited the tokens to the contract? The protocol itself? Do you have a dapp I cant seem to find one on the website?

**Comment by nick3842** [comment]
The protocol purchased those LP tokens via a bonding mechanism. Our dapp is in the works

**Comment by waynebruce0x** [comment]
Closing PR following conversation on discord. Let us know if you'd like this reopening

**Pull request closed without merging**
