### PR TITLE
Update Bullish TVL accounts

### PR DESCRIPTION
**Pull request by DenisCarriere**
Update Bullish TVL accounts to include:
- cold account
- withdraw account
- deposit account

TVL reporting from team:
https://coinness.live/news/1044856

image

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bullish exports TVL: 
        
 
 
    eos                       66.84 M
    
    total                    66.84 M

**Comment by llamatester** [comment]
The adapter at projects/bullish exports TVL: 
        
 
 
    eos                       66.84 M
    
    total                    66.84 M

**Comment by DenisCarriere** [comment]
TVL adapter looks accurate

**Comment by g1nt0ki** [comment]
@DenisCarriere Sorry, I am delisting your project, I am not sure why/how you were listed in the first place, you do not look like a dex

**Pull request merged**
