### PR TITLE
[Ready to Merge] Converting to on-chain TVL Calculations - Dyson

### PR DESCRIPTION
**Pull request by Avedith**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/dyson-money: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'forEach')
    Truncated error stack:
    
        at getUniqueAddresses (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/utils.js:137:13)
        at unwrapUniswapV3NFTs (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/unwrapLPs.js:256:14)
        at polygonTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/dyson-money/index.js:34:9)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:51:31)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:146:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:134:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:129:44

**Comment by llamatester** [comment]
The adapter at projects/dyson-money exports TVL: 
        
 
 
    arbitrum                  65.66 k
    polygon                   377.07 k
    optimism                  21.01 k
    
    total                    463.73 k

**Comment by llamatester** [comment]
The adapter at projects/dyson-money exports TVL: 
        
 
 
    polygon-staking           9.95 M
    arbitrum                  65.90 k
    polygon                   376.91 k
    optimism                  20.94 k
    staking                   9.95 M
    
    total                    463.75 k

**Comment by llamatester** [comment]
The adapter at projects/dyson-money exports TVL: 
        
 
 
    polygon-staking           10.12 M
    polygon                   379.09 k
    arbitrum                  66.22 k
    optimism                  21.03 k
    staking                   10.12 M
    
    total                    466.34 k

**Comment by Avedith** [comment]
Don't merge just yet.  Fixing a small issue with calculating TVL in a single-sided vault

**Comment by llamatester** [comment]
The adapter at projects/dyson-money exports TVL: 
        
 
 
    polygon-staking           10.04 M
    arbitrum                  65.68 k
    polygon                   400.39 k
    optimism                  20.80 k
    staking                   10.04 M
    
    total                    486.88 k

**Comment by Avedith** [comment]
All good to merge! :D

**Comment by llamatester** [comment]
The adapter at projects/dyson-money exports TVL: 
        
 
 
    polygon-staking           10.32 M
    arbitrum                  63.22 k
    polygon                   583.93 k
    optimism                  21.98 k
    staking                   10.32 M
    
    total                    669.13 k

**Comment by llamatester** [comment]
The adapter at projects/dyson-money exports TVL: 
        
 
 
    polygon-staking           10.31 M
    arbitrum                  63.19 k
    polygon                   584.00 k
    optimism                  21.98 k
    staking                   10.31 M
    
    total                    669.16 k

**Comment by Avedith** [comment]
Finally good to merge with no further commits. 👍

**Pull request merged**
