### PR TITLE
Add Infinite Trading adapter

### PR DESCRIPTION
**Pull request by luciocc55**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Logo (High resolution, will be shown with rounded borders):
itp

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/infinite exports TVL: 
        
 
 
    optimism                  395.13 k
    base                      29.13 k
    polygon                   23.32 k
    arbitrum                  3.64 k
    
    total                    451.21 k

**Comment by g1nt0ki** [comment]
hi @luciocc55 thanks for the PR, but afraid we cant show your tvl metric as these contract is already counted as part of dhedge. Rejected a similar platform for the same reason: https://github.com/DefiLlama/DefiLlama-Adapters/pull/9966

but if you are charging fees, we can track that/revenue/volume.

Otherwise, we can list tvl part but only for ITP staking part. Shall I update the adapter code to just track the staking?

**Comment by luciocc55** [comment]
Oh yeah that makes total sense @g1nt0ki do you know of other platform already tracking that revenue/volume? so i can maybe use them as an example to do that? not so sure i know how to fetch that on chain.
If There isn't one feel free to remove that from the tvl and just pass it that way. Thanks for the help

**Comment by g1nt0ki** [comment]
hi @luciocc55 two ways of tracking are either tracking token transfers to your fee wallet or (my preferred solution) tracking via event logs when fee is paid

 - token transfer: https://github.com/DefiLlama/dimension-adapters/blob/master/fees/caviar-tangible.ts#L7
 - event log: https://github.com/DefiLlama/dimension-adapters/blob/master/fees/looksrare.ts#L14

**Comment by luciocc55** [comment]
> hi @luciocc55 two ways of tracking are either tracking token transfers to your fee wallet or (my preferred solution) tracking via event logs when fee is paid
> 
> * token transfer: https://github.com/DefiLlama/dimension-adapters/blob/master/fees/caviar-tangible.ts#L7
> * event log: https://github.com/DefiLlama/dimension-adapters/blob/master/fees/looksrare.ts#L14

For this i need to fork dimension-adapters right? like this should be a separate PR right? if so feel free to remove the dhedge portion of this PR and just merge it, thanks for the advice i'll probably follow up soon with a PR to that repo to have revenue as well. thanks

**Comment by g1nt0ki** [comment]
yup, a new PR in the dimensions repo

**Comment by llamatester** [comment]
The adapter at projects/infinite exports TVL: 
        
 
 
    optimism-staking          232.60 k
    staking                   232.60 k
    optimism                  0
    
    total                    0

**Pull request merged**
