### PR TITLE
Add staking data for lumi finance

### PR DESCRIPTION
**Pull request by stephen-lumi**
------ TVL ------
arbitrum-staking          4.68 M
arbitrum                  7.21 M
staking                   4.68 M

total                    7.21 M

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hey, @stephen-lumi thanks for the PR, staking tvl should not be counted within the tvl export, it only needs to be exported as staking

**Comment by alberthuang24** [comment]
@realdealshaman This one is a pledge of our agreement, if we don't count our tvl will be severely underestimated

**Comment by alberthuang24** [comment]
When a stake, we transfer the money from the AMM contract to the stake contract.

**Comment by realdealshaman** [comment]
In this case it is getting counted twice, we have toggles that apply to all projects that have staking and once they are toggled on the staking gets added to the tvl, in this case it will be counted twice

**Comment by stephen-lumi** [comment]
How do I turn this switch on?

**Comment by realdealshaman** [comment]
its on our main page and will also be in the protocol page once it is live
image

Currently we only need to export staking as staking

**Comment by llamatester** [comment]
The adapter at projects/lumi-finance exports TVL: 
        
 
 
    arbitrum-staking          4.86 M
    arbitrum                  5.45 M
    staking                   4.86 M
    
    total                    5.45 M

**Comment by realdealshaman** [comment]
@stephen-lumi I think I misunderstood the adapter at first. But what I want to convey is that we must be careful not to double-count the TVL

**Comment by llamatester** [comment]
The adapter at projects/lumi-finance exports TVL: 
        
 
 
    arbitrum-staking          4.88 M
    arbitrum                  2.59 M
    staking                   4.88 M
    
    total                    2.59 M

**Pull request merged**
