### PR TITLE
add palmy finance

### PR DESCRIPTION
**Pull request by hide-yoshi**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
- Palmy Finance

##### Twitter Link:
- https://x.com/palmyfi

##### List of audit links if any:
- https://github.com/palmy-finance/palmy-protocol/blob/main/audits/Palmy%20Finance%20-%20Zellic%20Audit%20Report.pdf

##### Website Link:
https://app.palmy.finance/

##### Logo (High resolution, will be shown with rounded borders):
- 
image

##### Current TVL:
- 0
  - We haven't officially announced the launch yet.

##### Treasury Addresses (if the protocol has treasury)
- n/a

##### Chain:
- Oasys network

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
- palmy

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
- palmy

##### Short Description (to be shown on DefiLlama):
- Palmy Finance is the first lending protocol backed by Oasys Network.

##### Token address and ticker if any:
- n/a

##### Category (full list at https://defillama.com/categories) *Please choose only one:
- Lending

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
- [Chainsight](https://chainsight.network/)

##### Implementation Details: Briefly describe how the oracle is integrated into your project:
- Get prices from coingecko and other sources and put them into the oracle in Oasys Network.

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
- https://explorer.oasys.games/address/0x180930A5bE82b213411d6Bf3D3F7100F5bFD17BF?tab=contract

##### forkedFrom (Does your project originate from another project):
- Aave V2

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL: Counts the tokens locked in the contracts to be used as collateral to borrow or to earn yield. Borrowed coins are not counted towards the TVL, so only the coins actually locked in the contracts are counted. There's multiple reasons behind this but one of the main ones is to avoid inflating the TVL through cycled lending.

##### Github org/user (Optional, if your code is open source, we can track activity):
- https://github.com/palmy-finance

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/palmy: 
        
 
  
    
    
    Error: TypeError: Cannot read properties of null (reading 'call')
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by hide-yoshi** [comment]
Should I add the Oasys RPC [here](https://github.com/DefiLlama/DefiLlama-Adapters/tree/39043c1a863e4046603a43e271291ece12aa2005?tab=readme-ov-file)?

**Comment by llamatester** [comment]
The adapter at projects/palmy exports TVL: 
        
 
 
    oas                       29
    oas-borrowed              0
    borrowed                  0
    
    total                    28.821306710706217

**Comment by g1nt0ki** [comment]
@hide-yoshi thanks for the PR, we already have support for oasys

**Pull request merged**
