### PR TITLE
1. Farm contract balance added.

### PR DESCRIPTION
**Pull request by hulkakshay**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/prxy: 
        
 
  
    
    
    Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="getTVLInUsd()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.6.4)
    Truncated error stack:
        at Interface.decodeFunctionResult (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/abi/lib/interface.js:388:23)

**Comment by realdealshaman** [comment]
Hey, there is an error with the call being made to the farmProxy address, also what is the farmProxy, how can users participate?

**Comment by hulkakshay** [comment]
> Hey, there is an error with the call being made to the farmProxy address, also what is the farmProxy, how can users participate?

Hey hi Real, i am really not sure why its failing as i checked it worked with me locally.
Also **0x256116a8Ea8bAd13897462117d88082C464B68e1** is the farmProxy address and users can participate by staking.
PRXY token allows holders to farm the Bitcoin fees earned. The more PRXY you stake the higher the APY tier. Rewards are paid each block in BTCpx

**Comment by vrtnd** [comment]
Hi. It tries to call ethereum contracts which is not exist, but exist on ploygon.
https://etherscan.io/address/0x256116a8Ea8bAd13897462117d88082C464B68e1
https://polygonscan.com/address/0x256116a8Ea8bAd13897462117d88082C464B68e1
sdk.api.abi.call errored with params: [
  {
    target: '0x256116a8Ea8bAd13897462117d88082C464B68e1',
    abi: {
      inputs: [],
      name: 'getTVLInUsd',
      outputs: [Array],
      stateMutability: 'view',
      type: 'function'
    },
    chain: 'ethereum'
  }
]

**Comment by realdealshaman** [comment]
I have pushed an update to the adapter so that farmPrxy tvl will be included into polygon staking. @hulkakshay, can we close this pr? please let me know if anything else is needed, happy to help

**Comment by hulkakshay** [comment]
> I have pushed an update to the adapter so that farmPrxy tvl will be included into polygon staking. @hulkakshay, can we close this pr? please let me know if anything else is needed, happy to help

Thank you very much @realdealshaman , just had small request that if we could have a check box for farmProxy that would really good for our users to differentiate...it's a small request hope we can do this...and after that we are good to close these PR .

**Comment by realdealshaman** [comment]
This would require that we give special treatment to Prxy, since it would require that we add a toggle that only PRXY would use, so we would have to say decline. However, It is something that can be added in the description so that anyone that visits the page is aware that this is being counted in staking. If you'd like to provide an updated description, we would be happy to add it to the protocol page

**Comment by hulkakshay** [comment]
> This would require that we give special treatment to Prxy, since it would require that we add a toggle that only PRXY would use, so we would have to decline. However, It is something that can be added in the description so that anyone that visits the page is aware that this is being counted in staking. If you'd like to provide an updated description, we would be happy to add it to the protocol page

Ok @realdealshaman no worries, description would work too for now..we can go head with integration and then close this PR.
Thank you for help and guidance.

**Pull request closed without merging**
