### PR TITLE
[WIP] Add Zora to Uniswap V2 TVL

### PR DESCRIPTION
**Pull request by MSilb7**
Add Zora uniswapV2Factory: https://explorer.zora.energy/address/0x0F797dC7efaEA995bB916f268D919d0a1950eE3C

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/uniswap-v2: 
        
 
  
    
    
    Error: 
        Unknown chain(s): zora
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file
        
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:138:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
The adapter at projects/uniswap-v2 exports TVL: 
        
 
 
    ethereum                  2.39 B
    celo                      0
    avax                      8.46 k
    zora                      0
    bsc                       251.79 k
    optimism                  4.22 k
    arbitrum                  411.76 k
    polygon                   154.65 k
    base                      17.16 M
    
    total                    2.41 B

**Comment by MSilb7** [comment]
I think this works?

There should be TVL in this pool, maybe we need to define Zora WETH somewhere? https://explorer.zora.energy/address/0x3a3F615b05AAD54d8A7Af1D1B20854f0513278Da

**Comment by 0xngmi** [comment]
yeah i think we're missing zora pricing, do you know if theres any json with a mapping between L1 and L2 tokens? like for optimism

**Comment by MSilb7** [comment]
> yeah i think we're missing zora pricing, do you know if theres any json with a mapping between L1 and L2 tokens? like for optimism

Hey, sorry didn't get back here.

WETH is a precompile, so it will be 0x4200000000000000000000000000000000000006 everywhere.

I think other tokens may have different addresses on different chains, but you can read from the superchain tokenlist for mappings: https://github.com/ethereum-optimism/ethereum-optimism.github.io/tree/master

**Pull request merged**
