### PR TITLE
Add YFX V4

### PR DESCRIPTION
**Pull request by yfxcom**
Name (to be shown on DefiLlama):  YFX
Twitter Link: https://twitter.com/YFX_COM
List of audit links if any: https://skynet.certik.com/projects/yfx
Website Link: https://www.yfx.com
Current TVL: 1.41 M
Logo (High resolution, will be shown with rounded borders): https://www.yfx.com/logo/black-yellow-square-400.png
Treasury Addresses (if the protocol has treasury): 
Chain: Arbutrum
Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): yfx 
Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): 9946
Short Description (to be shown on DefiLlama): World-leading decentralized perpetual exchange with up to 100x leverage, high liquidity, low fees, and no slippage
Token address and ticker if any:
	ETH: 0xf55a93b613d172b86c2ba3981a849dae2aecde2f
	Arbitrum:  0x569deb225441FD18BdE18aED53E2EC7Eb4e10D93
Category (full list at https://defillama.com/categories) *Please choose only one: Derivatives
Oracle used (Chainlink/Band/API3/TWAP or any other that you are using): Chainlink、Pyth
forkedFrom (Does your project originate from another project):
methodology (what is being counted as tvl, how is tvl being calculated): Accumulate the token value of each pool
Github org/user (Optional, if your code is open source, we can track activity): https://github.com/yfxcom/yfx_v4_core

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/jaguarswap.js exports TVL: 
        
 
 
    arbitrum                  496
    arbitrum-staking          67
    staking                   67
    arbitrum-pool2            39
    pool2                     39
    
    total                    496.07776894181643

**Comment by llamatester** [comment]
The adapter at projects/tenderize exports TVL: 
        
 
 
    ethereum                  159.99 k
    arbitrum                  82.41 k
    
    total                    242.40 k

**Comment by llamatester** [comment]
The adapter at projects/uniswap exports TVL: 
        
 
 
    ethereum                  2.86 B
    arbitrum                  306.16 M
    base                      186.32 M
    polygon                   112.98 M
    optimism                  75.46 M
    celo                      29.25 M
    bsc                       27.48 M
    rsk                       21.60 M
    avax                      2.77 M
    linea                     1.90 M
    boba                      1.85 M
    scroll                    1.77 M
    filecoin                  725.33 k
    blast                     471.86 k
    era                       371.20 k
    moonbeam                  74.33 k
    
    total                    3.63 B

**Comment by llamatester** [comment]
The adapter at projects/yfx-v3 exports TVL: 
        
 
 
    arbitrum                  1.59 k
    
    total                    1.59 k

**Comment by llamatester** [comment]
The adapter at projects/yfx-v4 exports TVL: 
        
 
 
    arbitrum                  1.42 M
    
    total                    1.42 M

**Comment by yfxcom** [comment]
> The adapter at projects/yfx-v4 exports TVL:
> 
> ```
> arbitrum                  1.42 M
> 
> total                    1.42 M 
> ```

Correct

**Comment by g1nt0ki** [comment]
@yfxcom thanks, added it here without touching other files: https://github.com/DefiLlama/DefiLlama-Adapters/commit/b322192cdbba2d0288e5daea213c636373ce0550

**Pull request closed without merging**
