### PR TITLE
update staking contracts list

### PR DESCRIPTION
**Pull request by wojakfinance**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
Update of the Wojak Finance adaptor to display Wojak Pool TVL.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/wojakfinance: 
        
 
  
    
    
    PromisePoolError: invalid address (argument="address", value=["0x065AAE6127D2369C85fE3086b6707Ac5dBe8210a","0xDF21058099e69D3635005339721C4826c4c47F8A"], code=INVALID_ARGUMENT, version=address/5.6.1) (argument="account", value=["0x065AAE6127D2369C85fE3086b6707Ac5dBe8210a","0xDF21058099e69D3635005339721C4826c4c47F8A"], code=INVALID_ARGUMENT, version=abi/5.6.4)
    Truncated error stack:
        at Function.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
Error while running adapter at projects/wojakfinance: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:223:11

**Comment by llamatester** [comment]
The adapter at projects/wojakfinance exports TVL: 
        
 
 
    dogechain-staking         0
    dogechain                 4.51 k
    staking                   0
    
    total                    4.51 k

**Comment by llamatester** [comment]
The adapter at projects/wojakfinance exports TVL: 
        
 
 
    dogechain                 77.61 k
    dogechain-staking         0
    staking                   0
    
    total                    77.61 k

**Comment by realdealshaman** [comment]
Hey, I have fixed the tvl calculation and added a staking function. You can check the code here:
https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/wojakfinance/index.js

image

lmk if we can close this PR, thanks

**Comment by llamatester** [comment]
The adapter at projects/wojakfinance exports TVL: 
        
 
 
    dogechain                 78.15 k
    dogechain-staking         10.90 k
    staking                   10.90 k
    
    total                    78.15 k

**Comment by wojakfinance** [comment]
thanks.

**Comment by realdealshaman** [comment]
are the wojk tokens in the masterchef, user deposited or are they for rewards?

seems that the calculation remains the same, I have already added the code shown in the link, if it is okay with you, I will close this pr

**Pull request closed without merging**
