### PR TITLE
add jeth

### PR DESCRIPTION
**Pull request by nexeranet**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
jETH

##### Website Link:
https://jettoneth.com
https://jettonethereum.com

##### Logo (High resolution, will be shown with rounded borders):
https://cdn.jettoneth.com/jETH.png

##### Chain:
TON Blockchain (The Open Network)

##### Short Description (to be shown on DefiLlama):
ETH stored on the Ethereum network and mirrored on the TON network.

##### Token address and ticker if any:
ETH address: 0x7e90Ef7D172843dB68e42FC5fAA8CB7C1803Dcfa
TON address: EQCb1SAX1heK9tK8a5CXtYSbdHXkPPAXWKTy3Yz5PH1lglIu
ticker - jETH

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Bridge

##### methodology (what is being counted as tvl, how is tvl being calculated):
Total value of ETH locked on ETH network considered as TVL

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/jeth exports TVL: 
        
 
 
    ton                       0
    
    total                    0.29519702661

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
hi, thanks for the PR, but for the bridge, please track the tokens locked in your contract at source chain

**Comment by g1nt0ki** [comment]
I have merged jbtc, please update this PR to track locked eth in that file. https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/jbtc/index.js

**Comment by nexeranet** [comment]
Thank you @g1nt0ki.  How can I add eth wallets? In coreAssets I don't see eth.  Is it necessary to add eth in wrapped form?

**Comment by g1nt0ki** [comment]
hi @nexeranet you can do something like this

**Comment by g1nt0ki** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/typhoon.js#L7

**Comment by llamabutler** [comment]
Error while running adapter at projects/jeth: 
        
 
  
    
    
    PromisePoolError: Request failed with status code 502
    Truncated error stack:
        at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by llamabutler** [comment]
Error while running adapter at projects/jeth: 
        
 
  
    
    
    Error: Cannot find module './helper/unwrapLPs'
    Require stack:
    - /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/jeth/index.js
    - /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js
    Truncated error stack:
    
        at Object.<anonymous> (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/jeth/index.js:1:42)
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'

**Comment by llamabutler** [comment]
The adapter at projects/jeth exports TVL: 
        
 
 
    ethereum                  979.18 k
    
    total                    979.18 k

**Comment by g1nt0ki** [comment]
hi @nexeranet I have included it in our existing listing

**Pull request closed without merging**
