### PR TITLE
remove enso finance

### PR DESCRIPTION
**Pull request by milonite**
---
##### Name (to be shown on DefiLlama):
Enso

##### Twitter Link:
https://twitter.com/EnsoFinance

##### List of audit links if any:
ChainSecurity, ABDK, MixBytes, CodeArena

##### Website Link:
[enso.finance](https://www.enso.finance/)

This PR removes Enso Finance from the DefiLama adapters.
Enso discontinued V1 and soon will launch V2, hence the TVL and metadata is not relevant/incorrect (still based on vampire attack)

Enso will open a new PR prior launching V2

(a comment wrongly copied by another project has also been deleted)

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/astrowar-finance exports TVL: 
        
 
 
    harmony                   16.81072126986081
    
    total                    16.81072126986081

**Comment by g1nt0ki** [comment]
@milonite we no longer delist protocols when they sunset, we add a event that lets users know about product status but leave it as it is, I am happy to assist in new listing of enso v2 when it is ready. then we will have breakdown like aave v1/v2/v3

**Comment by ConnorSB13** [comment]
It's not that it was sunset, the data being fetched as incorrect.  We did not do the PR ourselves, and was always pointing to the wrong contracts.

**Comment by realdealshaman** [comment]
Hi, @ConnorSB13, we've gone ahead and removed the listing for now. We would greatly appreciate it if you could submit a PR for the new adapter, so we can get it listed as soon as possible. Thank you

**Pull request closed without merging**
