### PR TITLE
Create zookeeper.js

### PR DESCRIPTION
**Pull request by moohooooo**
##### Twitter Link:
https://twitter.com/ZooFarming

##### List of audit links if any:
On progress with Haechi

##### Website Link:
https://www.zookeeper.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://token-icons.vercel.app/icon/wanswap/ZOO.png

##### Current TVL:
30382153.712589074

##### Chain:
Wanchain

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
Not yet

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
Not yet

##### Description/bio (to be shown on DefiLlama):
ZooKeeper brings you a brand new and exciting farming experience, enabling you to enjoy higher rewards and more interesting NFT gameplay and use cases on Wanchain

##### Token address and ticker if any:
https://www.wanscan.org/token/0x6e11655d6ab3781c6613db8cb1bc3dee9a7e111f

##### Category (Yield/Dexes/Lending/Minting):
Yield Farming, NFT

### CODE REVIEW

**Comment by 0xngmi** [comment]
The TVL reported by the endpoint keeps jumping to crazy numbers (like 32532042624194527000). Could you fix it?

**Comment by 0xngmi** [comment]
I will delist ZooKeeper for now. Let me know when this is fixed.

**Comment by moohooooo** [comment]
> I will delist ZooKeeper for now. Let me know when this is fixed.

Ok Sorry for that ... we gonna check on our side and notice later

**Comment by 0xngmi** [comment]
Thanks, we chose to delist since it's currently messing with the interface:
image

**Comment by moohooooo** [comment]
image

We found a problem on my side... We gonna correct it soon... Really sorry for that again T T

**Comment by moohooooo** [comment]
image

we found that problem... We will correct it and for the future too... Really sorry for that again.. I will notice you after we fixed this problem

**Comment by 0xngmi** [comment]
All good, let me know when it's fixed and I'll re-list

**Comment by 0xngmi** [comment]
Thanks, relisted

**Comment by moohooooo** [comment]
Thanks .. Did you clear a wrong data? I still see the wrong data

**Comment by 0xngmi** [comment]
should be fixed now

**Pull request merged**
