### PR TITLE
Add Pangolin DEX

### PR DESCRIPTION
**Pull request by dasconnor**
#### Why are you creating this pull request?
We'd like to list Pangolin on DeFi Llama.

##### Twitter Link:
https://twitter.com/pangolindex

##### List of audit if any:
Same security profile as Uniswap. Uniswap's V2 audits apply.

##### Website Link:
https://pangolin.exchange

##### Contact Email:
pangolindex@protonmail.com

##### Expected TVL:
About 218 million

##### Chain:
Avalanche

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
pangolin

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
8422 (token not exchange, no exchange listing at the moment)

##### Description/bio (to be shown on DefiLlama):
Pangolin is a community-driven DEX that runs on Avalanche. Using the same automated market-making (AMM) model as Uniswap, Pangolin is capable of trading all tokens issued on Ethereum and Avalanche.

##### Token address and ticker if any:
PNG 0x60781C2586D68229fde47564546784ab3fACA982 (on Avalanche)

##### Category (Yield/Dexes/Lending/Minting):
DEX

### CODE REVIEW

**Comment by 0xngmi** [comment]
Thanks!

**Comment by 0xngmi** [comment]
@dasconnor Is there some API where we can see each pairs TVL along with the contract address for it? Would like to verify that the reported total TVL is correct by checking that the sum of TVL pairs checks out and doing some random checks on a few pairs to test whether the values are correct.

**Comment by dasconnor** [comment]
TVL is derived from this analytics page. Data is taken from a graph-node. Pair pages link to their liquidity provider tokens. Let me know if you need any other details!

**Comment by 0xngmi** [comment]
Perfect, that's all I need to do some light verification, thanks!

**Comment by 0xngmi** [comment]
Do you know if there is some way to get a list of all ported tokens along with their ETH counterparts?

**Pull request merged**
