### PR TITLE
feat: update itfx index.js

### PR DESCRIPTION
**Pull request by Braveheartforyou**
##### Current TVL: bsc 4,049,749 USD  heco  2,463,960  oec 1,392,557   conflux 1,625,524  polygon   1,682,599   
all tvl 11,214,389

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

https://coinmarketcap.com/currencies/ins3-finance/

##### Token address and ticker if any:   ITFX

bsc 0x171928f3add0317dd3ed38649ce7cf37433078df
heco 0x0569843257B91A9753351a4d621AdA83F642F57C
oec 0x49AC18d093c6210B2C64db7f6698407801E128cD
conflux cfx:acf2sb8yeas3knvg0vs26whh4xb8ssxpgjxv92h310
polygon 0xeb48CF0caA8B39E0B3b1fEE774caa9F9c45dbcD9

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Insurance

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Have you got contract addresses that I can look at to verify the TVL? 
Did you mean for 'tvl' and 'staking' params to return the same value?

**Comment by Braveheartforyou** [comment]
> Have you got contract addresses that I can look at to verify the TVL? Did you mean for 'tvl' and 'staking' params to return the same value?

hi!  heco Chain  contract addresses 0x099B296D2213f7839ea359Bf62925FE76D57CE15 ,  Get the Stakingamount of lp in the pool through the contract "getSummary", display them on the page and then summarize them。

**Comment by waynebruce0x** [comment]
Contract unverified on hecoscan - is there another way I can query the contract? I don't know the ABI either

**Comment by Braveheartforyou** [comment]
> Contract unverified on hecoscan - is there another way I can query the contract? I don't know the ABI either

 bsc: "https://bsc.ins3.finance/get/summary"  Methos: post   params: { type: bsc }
  heco: "https://heco.ins3.finance/get/summary" Methos: post   params: { type: heco }
  okexchain: "https://oec.ins3.finance/get/summary" Methos: post   params: { type: oec }
  conflux: "https://conflux.ins3.finance/get/summary" Methos: post   params: { type: conflux }
  polygon: "https://polygon.ins3.finance/get/summary" Methos: post   params: { type: polygon }
  
You can query staking and tvl through the above interface!

**Comment by waynebruce0x** [comment]
Can you show me where the TVL is held? The reason I ask, is that from your website I can't really figure out what your TVL is made up of and where it is held. So we need to check your contracts to check your API is using a suitable method of calculating TVL

**Comment by Braveheartforyou** [comment]
> Can you show me where the TVL is held? The reason I ask, is that from your website I can't really figure out what your TVL is made up of and where it is held. So we need to check your contracts to check your API is using a suitable method of calculating TVL

Can you give me an example? Why flux dapp can pass through only one interface?

**Comment by Braveheartforyou** [comment]
> > Can you show me where the TVL is held? The reason I ask, is that from your website I can't really figure out what your TVL is made up of and where it is held. So we need to check your contracts to check your API is using a suitable method of calculating TVL
> 
> Can you give me an example? Why flux dapp can pass through only one interface?

show you code & abi & contracts?

**Comment by waynebruce0x** [comment]
Are the deposits deployed to various different vault strategies? What happens to deposits?

**Comment by Braveheartforyou** [comment]
> Are the deposits deployed to various different vault strategies? What happens to deposits?

No, the deposit will be in the lp pool！The tvl statistics are more complicated, and it is not convenient to display the code. 
Can provide stagedpool contract address:

bsc: 0x4760E7F0E5F58Af974376288ea1E748c4d6a62dE
heco: 0x1F1490f48Be17e05Cf355C0435F86de95979C5c8
oec: 0xC160Df6e9A3a148dfD05f3e5D3e9FBf692378E80
polygon: 0xf10350f784BB08bEC17272d236a179599b80d5B4
conflux: cfx:acdvf3kz5duucf7v0w4jt09u9zk74tggt2m61nwu9s

Can provide proof of tvl [news](https://www.jinse.com/lives/266156.html)

**Comment by waynebruce0x** [comment]
Closing because of inactivity and we never worked out where the protocol TVL was held. Please message us on our Discord server if you would like this reopening. We are keen to list the project but we need to be able to see where the value is locked.

**Pull request closed without merging**
