### PR TITLE
Add TVL tracking for BMX by Morphex

### PR DESCRIPTION
**Pull request by daedboi**
##### Github org/user (Optional, if your code is open source, we can track activity): https://github.com/morphex-labs

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bmx exports TVL: 
        
 
 
    base                      130.69 k
    
    total                    130.69 k

**Comment by llamatester** [comment]
The adapter at projects/morphex-old exports TVL: 
        
 
 
    fantom-staking            127.16 k
    fantom                    997.2206431125372
    staking                   127.16 k
    
    total                    997.2206431125372

**Comment by Define101** [comment]
"projects/morphex-old" what is this?

**Comment by Define101** [comment]
Oh i see , it is to add it to this listing (currently only have a volume adapter) https://defillama.com/protocol/morphex-v1

**Pull request merged**
