### PR TITLE
Feat: Linea support

### PR DESCRIPTION
**Pull request by CristianRicharte6**
##### Current TVL:  217216.65 USD
  - Polygon: 85499.28 USD
  - Linea: 131717.37 USD

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
- A3A: https://www.coingecko.com/en/coins/3a
- EURO3: https://www.coingecko.com/en/coins/euro3

##### Token address and ticker if any: 
Polygon:
  - EURO3 - 0xA0e4c84693266a9d3BBef2f394B33712c76599Ab 
  - A3A - 0x58c7b2828e7f2b2caa0cc7feef242fa3196d03df
Linea:
  - EURO3 - 0x3f817b28da4940f018c6b5c0a11c555ebb1264f9
  - A3A - 0x3d4b2132ed4ea0aa93903713a4de9f98e625a5c7

##### Github org/user (Optional, if your code is open source, we can track activity): https://github.com/3A-DAO/3a-borrowing-protocol

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/3a-dao exports TVL: 
        
 
 
    linea                     143.02 k
    polygon                   92.99 k
    
    total                    236.01 k

**Comment by g1nt0ki** [comment]
@CristianRicharte6 thanks for the PR, included the changes here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/3b303e9531e50f3f08192f55c7a246caf825e5f7

**Comment by CristianRicharte6** [comment]
@g1nt0ki Thanks for including the changes. I can see the TVL for Linea is added but not the Token Information for A3A in linea, just for Polygon and as well for the Stablecoin info. Could you have a look? Please 

https://defillama.com/protocol/3a-dao

- TVL Section
image

- Stablecoin Section
image

**Comment by Define101** [comment]
image

Should be good within 2 hours

**Comment by CristianRicharte6** [comment]
Still missing the address for A3A for Linea in "token information" and the "A3A Liquidity" in Linea. Please check the image :) 

image

**Comment by Define101** [comment]
Its possible to add one token address (one chain only)
Regarding the A3A Liquidity , we get that info from our yields dashboard.

**Pull request closed without merging**
