### PR TITLE
Neopin

### PR DESCRIPTION
**Pull request by g1nt0ki**
project details: https://github.com/DefiLlama/DefiLlama-Adapters/pull/4885

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/neopin-staking exports TVL: 
        
 
 
    klaytn-staking            1.97 M
    klaytn                    11.65 M
    tron                      296.75 k
    staking                   1.97 M
    
    total                    11.95 M

**Comment by llamatester** [comment]
The adapter at projects/neopin exports TVL: 
        
 
 
    klaytn                    2.48 M
    
    total                    2.48 M

**Comment by llamatester** [comment]
The adapter at projects/neopin-staking exports TVL: 
        
 
 
    klaytn                    11.66 M
    tron                      297.11 k
    klaytn-staking            1.92 M
    staking                   1.92 M
    
    total                    11.96 M

**Comment by llamatester** [comment]
The adapter at projects/neopin exports TVL: 
        
 
 
    klaytn                    2.46 M
    
    total                    2.46 M

**Comment by g1nt0ki** [comment]
thanks, what about tron?

**Comment by llamatester** [comment]
The adapter at projects/neopin-staking exports TVL: 
        
 
 
    tron                      294.49 k
    klaytn-staking            1.94 M
    klaytn                    11.38 M
    staking                   1.94 M
    
    total                    11.68 M

**Comment by llamatester** [comment]
The adapter at projects/neopin exports TVL: 
        
 
 
    klaytn                    2.48 M
    
    total                    2.48 M

**Comment by yepp4you** [comment]
> thanks, what about tron?

tron is the address below.
thanks

TTjacDH5PL8hpWirqU7HQQNZDyF723PuCg
https://tronscan.org/#/address/TTjacDH5PL8hpWirqU7HQQNZDyF723PuCg

**Comment by llamatester** [comment]
The adapter at projects/neopin-staking exports TVL: 
        
 
 
    tron                      2.94 k
    klaytn                    11.44 M
    klaytn-staking            1.95 M
    staking                   1.95 M
    
    total                    11.44 M

**Comment by llamatester** [comment]
The adapter at projects/neopin exports TVL: 
        
 
 
    klaytn                    2.49 M
    
    total                    2.49 M

**Comment by yepp4you** [comment]
> 
It seems that tron's staking value is calculated incorrectly.
The formula is as follows.
https://tronscan.org/#/address/TTjacDH5PL8hpWirqU7HQQNZDyF723PuCg

Current Votes * Tron Price = 10815709 *  0.055774 = $603,235.353766 = $603 K

**Comment by llamatester** [comment]
The adapter at projects/neopin-staking exports TVL: 
        
 
 
    tron                      595.73 k
    klaytn                    11.42 M
    klaytn-staking            1.94 M
    staking                   1.94 M
    
    total                    12.02 M

**Comment by llamatester** [comment]
The adapter at projects/neopin exports TVL: 
        
 
 
    klaytn                    2.48 M
    
    total                    2.48 M

**Comment by yepp4you** [comment]
Please change the information displayed on the web.
(https://defillama.com/protocol/neopin-finance)

The information is below.

Category: Dexes

Tab Title: NEOPIN / NEOPIN Pool / NEOPIN Staking

NEOPIN Description: NEOPIN is a blockchain open platform that connects and expands the ecosystem through Gaming, Metaverse, Service, and NFTs, centering on various DeFi services such as staking, yield farming, and swap. 

NEOPIN Pool Description: Provide liquidity directly to the pool of your choice and receive NPT in addition to the base rewards by using a non-custodial wallet NEOPIN Wallet.

NEOPIN Staking Description: Earn rewards by safely delegating your crypto assets to one of the leading node validators NEOPIN.

**Comment by g1nt0ki** [comment]
hi @yepp4you , yes, we will fix it asap

**Comment by yepp4you** [comment]
We created a new dex on polygon (Matic). 

The newly deployed contract information on polygon is shown below.

factory: '0x1289ae78422b94414c1F827C534a1fE8E31E71Aa'
router02: '0x511C180A2E69cA700CeA66f609B8a2357f5980eC'
WMATIC(WETH): '0xFD28c7ceA3c50a060cB4c0059E453C6D4DD9829d'
NPT(Multichain NPT): '0x306ee01a6bA3b4a8e993fA2C1ADC7ea24462000c'
MATIC-NPT (LP Token): '0x2Dae48CFEC770884A2DBC43b43AffB2eCF8d41b2'

**Comment by yepp4you** [comment]
@g1nt0ki 
There was an update regarding staking on KLAYTN, the following addresses have been added. 
We would appreciate it if you could add the address below. 
 contract address: 0xf9d92BAd7b1410dfFB0a204B7aa418C9fd5A898F

**Pull request merged**
