### PR TITLE
Fetch tvl

### PR DESCRIPTION
**Pull request by sruthi23**
##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

knitlogo

##### Chain:
ETH
BSC
MATIC
FANTOM
HECO

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
https://www.coingecko.com/en/coins/knit-finance

##### Short Description (to be shown on DefiLlama): Multi Chain Wrapped Assets ( Coins and NFTs) and Liquid stacking protocol for all the assets.

Developed Single infrastructure which will allow various assets , liquidity to move from one chain to another seamlessely as well enable liquidity staking for DPoS assets

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Wrapping (and we also offer Bridge and Staking)

##### methodology (what is being counted as tvl, how is tvl being calculated): Value of total coins locked with us

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Can this be worked out using on-chain calls? We prefer this because it gives more transparency.

**Comment by sruthi23** [comment]
Updated the functions which pulls data from Coingecko and public chain explorers. Also looping @niksmac for further conversions.

**Comment by niksmac** [comment]
Hey @waynebruce0x does that satisfies the requirements?

**Comment by niksmac** [comment]
Hey @waynebruce0x does that satisfies the requirements?

**Pull request merged**
