### PR TITLE
LP Equilibre Vaults

### PR DESCRIPTION
**Pull request by gaspare100**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/scrubinvest: 
        
 
  
    
    
    PromisePoolError: failed to meet quorum (method="getBlockNumber", params={}, results=[{"weight":1,"start":1682165379897,"error":{"reason":"bad response","code":"SERVER_ERROR","status":502,"headers":{"server":"awselb/2.0","date":"Sat, 22 Apr 2023 12:10:18 GMT","content-type":"text/html","content-length":"122","connection":"close"},"body":"<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n</body>\r\n</html>\r\n","requestBody":"{\"method\":\"eth_blockNumber\",\"params\":[],\"id\":43,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://evm.kava.io"}}], provider={"_isProvider":true,"_events":[],"_emitted":{"block":-2},"disableCcipRead":false,"formatter":{"formats":{"transaction":{},"transactionRequest":{},"receiptLog":{},"receipt":{},"block":{},"blockWithTransactions":{},"filter":{},"filterLog":{}}},"anyNetwork":false,"_network":{"name":"kava","chainId":2222},"_maxInternalBlockNumber":-1024,"_lastBlockNumber":-2,"_maxFilterBlockRange":10,"_pollingInterval":4000,"_fastQueryDate":0,"providerConfigs":[{"provider":{"_isProvider":true,"_events":[],"_emitted":{"block":-2},"disableCcipRead":false,"formatter":{"formats":{"transaction":{},"transactionRequest":{},"receiptLog":{},"receipt":{},"block":{},"blockWithTransactions":{},"filter":{},"filterLog":{}}},"anyNetwork":false,"_network":{"name":"kava","chainId":2222},"_maxInternalBlockNumber":-1024,"_lastBlockNumber":-2,"_maxFilterBlockRange":10,"_pollingInterval":4000,"_fastQueryDate":0,"connection":{"url":"https://evm.kava.io"},"_nextId":44,"_eventLoopCache":{"eth_blockNumber":null},"_internalBlockNumber":null},"priority":0,"stallTimeout":750,"weight":1}],"quorum":1,"_highestBlockNumber":-1,"_internalBlockNumber":{}}, code=SERVER_ERROR, version=providers/5.7.2)
    Truncated error stack:
        at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
The adapter at projects/scrubinvest exports TVL: 
        
 
 
    kava                      1.44 M
    
    total                    1.44 M

**Comment by llamatester** [comment]
The adapter at projects/scrubinvest exports TVL: 
        
 
 
    kava                      1.44 M
    
    total                    1.44 M

**Comment by llamatester** [comment]
The adapter at projects/scrubinvest exports TVL: 
        
 
 
    kava                      1.44 M
    
    total                    1.44 M

**Comment by llamatester** [comment]
The adapter at projects/scrubinvest exports TVL: 
        
 
 
    kava                      1.44 M
    
    total                    1.44 M

**Comment by llamatester** [comment]
Error while running adapter at projects/scrubinvest: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by llamatester** [comment]
Error while running adapter at projects/scrubinvest: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by llamatester** [comment]
Error while running adapter at projects/scrubinvest: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by llamatester** [comment]
The adapter at projects/scrubinvest exports TVL: 
        
 
 
    kava                      1.44 M
    
    total                    1.44 M

**Comment by llamatester** [comment]
The adapter at projects/scrubinvest exports TVL: 
        
 
 
    kava                      1.44 M
    
    total                    1.44 M

**Comment by llamatester** [comment]
The adapter at projects/scrubinvest exports TVL: 
        
 
 
    kava                      1.44 M
    
    total                    1.44 M

**Comment by llamatester** [comment]
The adapter at projects/scrubinvest exports TVL: 
        
 
 
    kava                      1.44 M
    
    total                    1.44 M

**Comment by llamatester** [comment]
The adapter at projects/scrubinvest exports TVL: 
        
 
 
    kava                      1.44 M
    
    total                    1.44 M

**Comment by llamatester** [comment]
The adapter at projects/scrubinvest exports TVL: 
        
 
 
    kava                      1.44 M
    
    total                    1.44 M

**Comment by llamatester** [comment]
The adapter at projects/scrubinvest exports TVL: 
        
 
 
    kava                      1.44 M
    
    total                    1.44 M

**Comment by gaspare100** [comment]
Seems like the LP are not being counted, any suggestion in what is wrong?

**Comment by llamatester** [comment]
The adapter at projects/scrubinvest exports TVL: 
        
 
 
    kava                      1.45 M
    
    total                    1.45 M

**Comment by g1nt0ki** [comment]
@gaspare100 Please stop, closing and reopening the PR, it is annoying.

LP value is not counted because I dont see LP tokens in any of the contracts on the list.

**Comment by gaspare100** [comment]
Hello,
I see, the problem is that the LP is then staked by the contract on the gauge, as this is a autocompounding vault.

Is there a way to fetch the balance for this contract from the gauge?

Gauge -> LP
0xe2C935041aEF672974A31d46c41A4F292982e621 -> 0x09d6561b3795ae237e42f7adf3dc83742e10a2e8
0x69cEf0795FFFa66DfC4Ffc90E8Bd05c399388650 -> 0x7f8ed7d31795dc6f5fc5f6685b11419674361501
0x075CA53543D304c02Ee692C0b691770AEB273dA4 ->  0xeA848151ACB1508988e56Ee7689F004df2B15ced

**Comment by g1nt0ki** [comment]
> Hello, I see, the problem is that the LP is then staked by the contract on the gauge, as this is a autocompounding vault.
> 
> Is there a way to fetch the balance for this contract from the gauge?
> 
> Gauge -> LP 0xe2C935041aEF672974A31d46c41A4F292982e621 -> 0x09d6561b3795ae237e42f7adf3dc83742e10a2e8 0x69cEf0795FFFa66DfC4Ffc90E8Bd05c399388650 -> 0x7f8ed7d31795dc6f5fc5f6685b11419674361501 0x075CA53543D304c02Ee692C0b691770AEB273dA4 -> 0xeA848151ACB1508988e56Ee7689F004df2B15ced

the contracts are not verified so I cant really tell but is there is some way to read the  LP amount deposited by your autocompounding contract into the gauge?

**Comment by gaspare100** [comment]
function getUserInfo(
		address user
	) public view returns (ExtendedInfo memory) ;
	
	
	struct UserInfo {
		uint256 balance;
		uint256 dollarValue;
		uint256 deposited;
		uint256 withdrawn;
		uint256 lastAPR;
		uint256 totalCollateral;
		uint256 totalSupply;
		uint256 lastCompoundTime;
	}

	struct ExtendedInfo {
		UserInfo userInfo;
		address token0;
		address token1;
		uint256 reserve0;
		uint256 reserve1;
		uint totalSupply;
	}
	
	
	so in this case: getUserInfo(anyaddress).userInfo.totalCollateral

**Comment by gaspare100** [comment]
in case you want instead the gauge one:

interface IGauge {
	function notifyRewardAmount(address token, uint amount) external;

	function getReward(address account, address[] memory tokens) external;

	function claimFees() external returns (uint claimed0, uint claimed1);

	function left(address token) external view returns (uint);

	function isForPair() external view returns (bool);

	function rewards() external view returns (address[] memory);

	function withdraw(uint amount) external;

	function deposit(uint amount, uint tokenId) external;

	function balanceOf(address account) external view returns (uint);

	function earned(
		address token,
		address account
	) external view returns (uint);

	function withdrawAll() external;
}


gauge.balanceOf(owner i listed)

**Comment by gaspare100** [comment]
0xe2C935041aEF672974A31d46c41A4F292982e621 -> 0x09d6561b3795ae237e42f7adf3dc83742e10a2e8
0x69cEf0795FFFa66DfC4Ffc90E8Bd05c399388650 -> 0x7f8ed7d31795dc6f5fc5f6685b11419674361501
0x075CA53543D304c02Ee692C0b691770AEB273dA4 -> 0xeA848151ACB1508988e56Ee7689F004df2B15ced

gauge("0xe2C935041aEF672974A31d46c41A4F292982e621").balanceOf("0x2c1C6aaB89272d07B7f78bFe93eefb6D2631Cf94") -> balance of lion compounder

**Comment by llamatester** [comment]
The adapter at projects/scrubinvest exports TVL: 
        
 
 
    kava                      1.67 M
    
    total                    1.67 M

**Pull request merged**
