### PR TITLE
Add TVL for Optim Finance's Liquidity Bonds

### PR DESCRIPTION
**Pull request by danielfarrelly**
##### Name (to be shown on DefiLlama):
Optim Finance Liquidity Bonds

##### Twitter Link:
https://twitter.com/OptimFi

##### List of audit links if any:
https://optim-finance.gitbook.io/optim-finance/products/liquidity-bonds/audit-reports

##### Website Link:
https://optim.finance

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://drive.google.com/file/d/1aHjUT65UwwA83po3YGThkxsTht5ZX3pk/view
https://drive.google.com/file/d/1HhaoXYJLLSJ6hpj6eKUkFcWCJeEOvg6E/view

##### Current TVL:
3.5 M ADA / 908.87 k USD

##### Chain:
Cardano

##### Coingecko ID (so your TVL can appear on Coingecko): 
Does not apply

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): 
Does not apply

##### Short Description (to be shown on DefiLlama):
Optim’s Liquidity Bond platform enables the lending and borrowing of staking rights between users at mutually beneficial rates as determined by buyers and sellers in the market.

##### Token address and ticker if any:
Does not apply

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Does not apply

##### forkedFrom (Does your project originate from another project):
Does not apply

##### methodology (what is being counted as tvl, how is tvl being calculated):
All ADA at valid Optim Pool addresses having received a full pool token mint, all ADA at active Optim Liquidity Bond addresses containing a valid Optim NFT, and all ADA at valid unwritten Optim Liquidity Bond addresses. Only ADA value is counted.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/optim-liquidity-bonds exports TVL: 
        
 
 
    cardano                   908.26 k
    
    total                    908.26 k

**Comment by g1nt0ki** [comment]
@danielfarrelly thanks for the PR

1. Can you please update the adapter to compute tvl on chain
2. amount lent out to stakepools should be counted under 'borrowed' since that ADA is no longer part of your protocol, this is uncollateralized lending?

**Comment by zygomeb** [comment]
@g1nt0ki thanks for your response. 

1. We've debated on how the computation show be done and with (currently available) web APIs it would currently be inaccurate. We make use of franken addresses, composed addresses of a script and a pubkey key. The 'cardano address' is essentially both of those components mashed together. Unfortunately this means that when we query per address current APIs (blockfrost, koios), we are forced to use the 'mashed up' addresses. We possess no knowledge of the full set of those addresses as by the nature of the protocol (enabling borrowers to attach their stake key), they're fully dynamic. 

As such we'd be forced to adopt a heuristic, as opposed to our backend which is able to perform the calculation accurately. Indigo Protocol uses much the same franken addresses technique and they simply query their own server as well.

2. The amount lent to stake pools does not leave out smart contracts. You can think of this protocol as having a pay-as-you-owe structure where you rent out access to the staking power (and rewards) of ADA without it ever leaving a smart contract, our smart contract. 

It is definitely very undercollateralized, but given lack of access to the actual crypto asset, it doesn't bear a traditional counterparty risk. If they borrow side fails to pay up, the loan is simply closed with a pentality applied of some of the prepaid interest.

**Comment by g1nt0ki** [comment]
thanks for patient and detailed explanation.

**Pull request merged**
