### PR TITLE
use correct endpoint for oxygen project

### PR DESCRIPTION
**Pull request by evgeniymelnikov**
Have started using correct endpoint, previous doesn't cover need about tvl calculation.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/oxygen/index.js exports TVL: 
        
 
 
    solana                    25.83 M
    
    total                    25.83 M

**Comment by waynebruce0x** [comment]
What extra TVL is included in this endpoint? is the API open source?

**Comment by at-convexitydmcc** [comment]
We've recently launched Oxygen Light version of the protocol light.oxygen.org . The TVL is a sum of TVL (app.oxygen.org) & TVL (light.oxygen.org)

**Comment by waynebruce0x** [comment]
Are they separate products/contracts? I'm just wondering if there would be any double count

**Comment by at-convexitydmcc** [comment]
They are separate, different Solana programs. There is no double count.

**Pull request merged**
