### PR TITLE
update desyn restaking and desyn yeild Methodology

### PR DESCRIPTION
**Pull request by santinoYoung**
Desyn Restaking: 
##### Methodology
Product: Liquid restaking strategy
TVL: It includes above
Revenue: Staking rewards, management fees, performance fees

Desyn Yield: 
##### Methodology
Product: On-chain restaking
TVL: It includes above
Revenue: Staking rewards, management fees, performance fees

Line graph time: year
Line graph Color: #3B51FE

### CODE REVIEW

**Comment by santinoYoung** [comment]
HI, TEAM, I don't know how to update the Methodology under restaking and yeild, I can only submit it through this issues.

**Comment by santinoYoung** [comment]
Including the time of the line graph has been the theme color of the entire desyn page

**Comment by llamatester** [comment]
The adapter at projects/desyn-farm exports TVL: 
        
 
 
    merlin                    73.95 M
    
    total                    73.95 M

**Comment by llamatester** [comment]
The adapter at projects/desyn exports TVL: 
        
 
 
    ethereum                  5.57 M
    arbitrum                  480
    btr                       57
    
    total                    5.57 M

**Comment by g1nt0ki** [comment]
changes were discussed/fixed in telegram, closing this

**Comment by santinoYoung** [comment]
> changes were discussed/fixed in telegram, closing this

But the Telegraph group didn't respond to this

**Pull request closed without merging**
