### PR TITLE
add ww

### PR DESCRIPTION
**Pull request by 0xbobloblaw**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
White Whale

##### Twitter Link:
https://twitter.com/WhiteWhaleDefi

##### Website Link:
https://whitewhale.money/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://whitewhale.money/logo.svg

##### Current TVL:
364k

##### Chain:
Terra2, Injective, Comdex, Juno

##### Token address and ticker if any:
WHALE

##### Category (full list at https://defillama.com/categories) *Please choose only one:
6

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/White: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:203:11

**Comment by llamatester** [comment]
The adapter at projects/astroport exports TVL: 
        
 
 
    terra2                    30.07 M
    terra                     0
    
    total                    30.07 M

**Comment by llamatester** [comment]
The adapter at projects/benddao exports TVL: 
        
 
 
    ethereum-staking          31.11 M
    ethereum-borrowed         48.50 M
    ethereum-pool2            2.46 M
    ethereum                  240.29 M
    staking                   31.11 M
    borrowed                  48.50 M
    pool2                     2.46 M
    
    total                    240.29 M

**Comment by llamatester** [comment]
The adapter at projects/phoenix-dex exports TVL: 
        
 
 
    terra2                    24.56 k
    
    total                    24.56 k

**Comment by llamatester** [comment]
The adapter at projects/terraswap exports TVL: 
        
 
 
    terra2                    404.20 k
    terra                     0
    
    total                    404.20 k

**Comment by llamatester** [comment]
Error while running adapter at projects/whitewhale: 
        
 
  
    
    
    AxiosError: Request failed with status code 429

**Comment by llamatester** [comment]
The adapter at projects/astroport exports TVL: 
        
 
 
    terra2                    30.17 M
    terra                     0
    
    total                    30.17 M

**Comment by llamatester** [comment]
The adapter at projects/benddao exports TVL: 
        
 
 
    ethereum-borrowed         48.55 M
    ethereum-pool2            2.46 M
    ethereum-staking          31.11 M
    ethereum                  240.42 M
    borrowed                  48.55 M
    pool2                     2.46 M
    staking                   31.11 M
    
    total                    240.42 M

**Comment by llamatester** [comment]
The adapter at projects/phoenix-dex exports TVL: 
        
 
 
    terra2                    24.70 k
    
    total                    24.70 k

**Comment by llamatester** [comment]
The adapter at projects/terraswap exports TVL: 
        
 
 
    terra2                    406.50 k
    terra                     0
    
    total                    406.50 k

**Comment by llamatester** [comment]
Error while running adapter at projects/whitewhale: 
        
 
  
    
    
    AxiosError: Request failed with status code 429

**Comment by g1nt0ki** [comment]
@0xbobloblaw sorry, I have removed your changes, we already have whitewhale listed, but the changes in your PR added new chains but tvl logic was incorrect, for example, you were trying to count entire astroport tvl in terra2 as yours

**Pull request merged**
