### PR TITLE
Add IncrementFi Lending Adapter

### PR DESCRIPTION
**Pull request by swordc**
##### Twitter Link:
Increment Finance
[https://twitter.com/incrementfi](https://twitter.com/incrementfi)

##### List of audit links if any:
[audit-report](https://docs.increment.fi/protocols/decentralized-money-market/audit-report)

##### Website Link:
MainSite: [https://increment.fi](https://increment.fi)
Lending: [https://app.increment.fi/markets](https://app.increment.fi/markets)

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
Project Name: Increment Finance
increment icon

##### Current TVL:
Lending: $349.47K

##### Chain:
Flow Blockchain
[https://www.onflow.org/](https://www.onflow.org/)

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

##### Short Description (to be shown on DefiLlama):
Increment Finance,
One-stop DeFi Platform on Flow Blockchain.
Deposit, earn, borrow, trade. Boost and leverage more liquidity and yield for Fungible Tokens on Flow 🌊

##### Token address and ticker if any:
N/A for now

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Increment Oracle on Flow Blockchain
[https://app.increment.fi/oracle](https://app.increment.fi/oracle)

##### forkedFrom (Does your project originate from another project):
Original

##### methodology (what is being counted as tvl, how is tvl being calculated):
The TVL of lending is calculated by real-time on-chain script.
The totalSupply of each pool will be accumulated according to the current oracle price.
Since the structure of the flow chain is different from others, the tvl data is temporarily obtained through the project's own endpoint: https://app.increment.fi/info/tvl

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/increment-lending: 
        
 
  
    
    
    Error: 
        Unknown chain(s): flow
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file

**Comment by waynebruce0x** [comment]
Can we count supply - borrow instead?

**Comment by swordc** [comment]
> Error while running adapter at projects/increment-lending:
> 
> ```
> Error: 
>     Unknown chain(s): flow
>     Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file
> ```
Added flow chain in chains.json.
Is there anything else that needs to be added for the new blockchain?

**Comment by llamatester** [comment]
The adapter at projects/increment-lending exports TVL: 
        
 
 
    flow                      0
    flow-borrowed             0
    borrowed                  0
    
    total                    0

**Comment by swordc** [comment]
> The adapter at projects/increment-lending exports TVL:
> 
> ```
> flow                      0
> flow-borrowed             0
> borrowed                  0
> 
> total                    0 
> ```

Fixed, changed to fetch api.

**Comment by swordc** [comment]
is everything going well

**Comment by llamatester** [comment]
The adapter at projects/increment-lending exports TVL: 
        
 
 
    flow                      423.55 k
    
    total                    423.55 k

**Pull request merged**
