### PR TITLE
added bzx tvl

### PR DESCRIPTION
**Pull request by eugenesh1**
##### Twitter Link:
https://twitter.com/bzxhq/status/1229626207869657088

##### List of audit links if any:
https://github.com/mattdf/audits/blob/master/bZx/bzx-audit.pdf

##### Website Link:
https://bzx.network/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://bzx.network/images/bzx-media/bZx_logo.svg
https://bzx.network/images/bzx-media/bZx_logo_invert.svg

##### Current TVL:

147382732 USD

##### Chain:
ethereum, bsc, polygon

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
bitcoin-zero

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
5810

##### Description/bio (to be shown on DefiLlama):
Build applications that empower lenders, borrowers, and traders with the most flexible decentralized finance protocol on Ethereum.

##### Token address and ticker if any:
ethereum: 0x56d811088235F11C8920698a204A5010a788f4b3
bsc: 0x4b87642AEDF10b642BE4663Db842Ecc5A88bf5ba
polygon: 0x54cFe73f2c7d0c4b62Ab869B473F5512Dc0944D2

##### Category (Yield/Dexes/Lending/Minting):
Dex/Lending/Yield

### CODE REVIEW

**Comment by eugenesh1** [comment]
Hi guys,
can you please check this PR please

**Comment by 0xngmi** [comment]
Hey, the reason why this PR hasn't been merged is that it doesn't work. The value returned by `tvl()` needs to be an object with the balances of the tokens in the protocol, which is not the case here. Furthermore the different network should be divided within module.exports.

On top of that, we try to avoid APIs in favor of on-chain calls or subgraphs. Here's our reasoning for it: https://github.com/DefiLlama/DefiLlama-Adapters/issues/304

**Comment by eugenesh1** [comment]
ok, got it, the reason I added api calls is that we have gov tokens like bgov and pgov and also LP tokens bgov/bnb and pgov/matic. Will these balances be converted to usd automaticaly?

**Comment by 0xngmi** [comment]
We use coingecko to fetch token price and for LP tokens we unwrap them into their underlying, are bgov and pgov on coingecko?

**Comment by eugenesh1** [comment]
bgov and pgov are listed on coingecko
I will update PR

**Comment by eugenesh1** [comment]
will provide new PR

**Pull request closed without merging**
