### PR TITLE
Arcade.xyz: configure updated subgraph that tracks v2 + v3 entities

### PR DESCRIPTION
**Pull request by sandbochs**
This tracks V3 Vaults and Loans by updating the subgraph url to our subgraph that is tracking both versions of the protocol. I think it makes sense to remove the recently added `arcade-xyz-v3` project folder @g1nt0ki, but thank you for getting us up initially!

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/arcade-xyz exports TVL: 
        
 
 
    ethereum-borrowed         12.49 M
    ethereum                  8.63 M
    borrowed                  12.49 M
    
    total                    8.63 M

**Comment by g1nt0ki** [comment]
hi @sandbochs you prefer tracking both under one listing? (it is fine with us, just checking)

**Comment by llamatester** [comment]
The adapter at projects/arcade-xyz exports TVL: 
        
 
 
    ethereum-borrowed         15.97 M
    ethereum                  8.10 M
    borrowed                  15.97 M
    
    total                    8.10 M

**Comment by sandbochs** [comment]
@g1nt0ki yes we do prefer tracking under 1 listing. I can open another PR to remove the v3 specific project.

**Pull request merged**
