### PR TITLE
Add adapter for Zeta

### PR DESCRIPTION
**Pull request by epsilonsized**
##### Twitter Link:

https://twitter.com/ZetaMarkets

##### List of audit links if any:

N/A

##### Website Link:

https://www.zeta.markets/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
Zeta_logo-03

Zeta_Logo_3

##### Current TVL:

$14,000,000

##### Chain:

Solana

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

##### Short Description (to be shown on DefiLlama):

Zeta Markets is the premier derivatives protocol on Solana. 

##### Token address and ticker if any:
N/A

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Options

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
N/A

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is being counted as all collateral being held on the Zeta smart contract to trade options and futures.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/zeta: 
        
 
  
    
    
    Error: 
        Please move the following keys into the chain: tvl
    
        We have a new adapter export specification now where tvl and other chain specific information are moved inside chain export.
        For example if your protocol is on ethereum and has tvl and pool2, the export file would look like:
        
            module.exports = {
              methodlogy: '...',
              ethereum: {
                tvl: 
                pool2:
              }
            }

**Comment by llamatester** [comment]
The adapter at projects/zeta exports TVL: 
        
 
 
    solana                    14.69 M
    
    total                    14.69 M

**Comment by g1nt0ki** [comment]
sorry, I dont think we can count the insurance fund, also can you update the adapter to make calls directly to solana instead, if you give me a list of addresses where collateral is stored, I can help with modifying the adapter

**Comment by g1nt0ki** [comment]
sorry, I dont think we can count the insurance fund, also can you update the adapter to make calls directly to solana instead, if you give me a list of addresses where collateral is stored, I can help with modifying the adapter

**Comment by kelvinlau20100** [comment]
> sorry, I dont think we can count the insurance fund, also can you update the adapter to make calls directly to solana instead, if you give me a list of addresses where collateral is stored, I can help with modifying the adapter

Just wanted to ask on this, we have followed the same methodology as katana and friktion in presenting our TVL information to you? If it isn't transparent enough, no worries but just wanted to clarify.

**Comment by g1nt0ki** [comment]
> > sorry, I dont think we can count the insurance fund, also can you update the adapter to make calls directly to solana instead, if you give me a list of addresses where collateral is stored, I can help with modifying the adapter
> 
> Just wanted to ask on this, we have followed the same methodology as katana and friktion in presenting our TVL information to you? If it isn't transparent enough, no worries but just wanted to clarify.

thanks for bringing this up, I didnt know there was others doing something like this. I have added it to my todo list to fix how they compute tvl

**Comment by epsilonsized** [comment]
> 

Hey we have dynamic accounts / addresses each time a person creates an option so the easiest format for us is to do what they are doing. Would it be possible to incorporate Zeta's typescript SDK into the adapter?

**Pull request merged**
