### PR TITLE
TapTap

### PR DESCRIPTION
**Pull request by Alice0nly**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
TapTap

##### Twitter Link:
https://x.com/TapTapLand

##### Website Link:
https://www.taptap.land/

##### Current TVL:
90K+ USD

##### Chain:
Taiko

##### Short Description (to be shown on DefiLlama):
TapTap is a community-driven memetoken deployed on the Taiko blockchain. It offers an absolute Fair mint and includes a large jackpot for added excitement. The token's value is entirely determined by all holders.

##### Token address and ticker if any:
0xbeA29cdda3b9d8975b3C925AB45e684BA244b8A3

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Farm

### CODE REVIEW

**Comment by Alice0nly** [comment]
I'd like to sum native eth of those two contracts, but sdk.api2.eth.getBalances not works on Taiko, help plz

**Comment by g1nt0ki** [comment]
@Alice0nly thanks for the PR, can you explain how the protocol works?

**Comment by llamatester** [comment]
The adapter at projects/taptap exports TVL: 
        
 
 
    taiko                     95.83 k
    
    total                    95.83 k

**Comment by g1nt0ki** [comment]
*like what the two contracts are/what they do, and how an user can withdraw the deposited ether

**Comment by Alice0nly** [comment]
> @Alice0nly thanks for the PR, can you explain how the protocol works?

Keyword
Fair Mint, Taiko meme
Background
The basic functionality is similar to xen, please refer to XEN Crypto, which triggered a surge in Ether Gas: How to participate, can you participate, Mint, Stake function;
Term, day logic Calculate Term, day cap based on Global Rank; top 500, max 100 days;
Mint logic Calculate Volume based on Global Rank, Term, day;
Stake logic calculates revenue based on Volume, Stake day;
Single address, mint process is over, can repeat mint;
The following modifications have been made to xen:
- Supply adjustment: no supply cap --> modify to fixed volume cap
- Participation fee adjustment: gas fee mint --> fair mint 
- Prize pool play, similar to fomo3d.
Supply
Uncapped supply is not conducive to long term positive price feedback, so the original uncapped supply is modified to a fixed amount. Here, the original uncapped supply is modified to a fixed supply. The restriction is: if there is no new participant in a period of time (e.g., 3 days) after the last participant in the claimRank, the output of the total supply will be locked.
For example, if there are four users, a,b,c,d, a,b,c participate in cliamRank in turn, choosing a term of 1, 3, and 100 days, with expected payoffs of 10, 33, and 500, respectively. d participates on the fourth day after c's participation, and at this point, the total supply is locked, and the total supply is 10+33+500. If there is a new user who participates 3 days after c's participation, the total supply is locked at the rate of the last user to participate, the total supply changes accordingly, as the last user to participate is deferred backward by 3 days.
Participation Fee
Xen uses a gas fee to participate, and fluctuations in the gas fee can lead to large differences in the cost to the user for the same TERM. Currently modified to participate in events based on a specific price curve, the participation fee portion will be used for two main purposes:
- Reflux to the bottom pool (70%)
- Flowing back into a fomo3d-like prize pool (30%)
Fair Mint Fee Logic Calculates Fees based on Global Rank, the higher the rank, the lower the fee;
Prize Pool
The modified prize pool payout mechanism is to give the prize pool to the last ten players to participate, requiring any one of those ten players to trigger a cliam action. The last player receives 50% of the prize, and the remaining 9 players share the remaining 50%.
It is not possible to display this content outside of the Lark documentation at this time.

**Comment by Alice0nly** [comment]
> *like what the two contracts are/what they do, and how an user can withdraw the deposited ether

they're Xen contract which user can fair mint the $TAP coin and swap pool of WETH/TAP which we provide liquidity.

**Comment by g1nt0ki** [comment]
sorry, still not sure why the WETH in zen contracts should be considered tvl, just so I understand this, the 8.88 ETH jackpot can be won by any user(s) once the round ends? if so, this can be counted as tvl, unsure about the other contract

**Comment by g1nt0ki** [comment]
closing this as there was no response

**Pull request closed without merging**
