### PR TITLE
Add Stablz adapter

### PR DESCRIPTION
**Pull request by onlystables**
##### Name (to be shown on DefiLlama):
Stablz

##### Twitter Link:
https://twitter.com/Stablzone

##### List of audit links if any:
https://hacken.io/audits/stablz/

##### Website Link:
https://stablz.one

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
token

##### Current TVL:
$1.37k

##### Treasury Addresses (if the protocol has treasury)
none

##### Chain:
Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
stablz

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
23430

##### Short Description (to be shown on DefiLlama):
Stablz is a central hub for all things stablecoin yield related. We focus on real yield and are now also opening real world asset pools to combine the flexibility of crypto with the sustainability of traditional business. 

##### Token address and ticker if any:
STABLZ
0xA4Eb9C64eC359D093eAc7B65F51Ef933D6e5F7cd

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
N/A

##### forkedFrom (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is being counted based on the amount of USDT locked up in Stablz's real world asset cannavest pool.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/stablz exports TVL: 
        
 
 
    ethereum                  1.37 k
    
    total                    1.37 k

**Comment by llamatester** [comment]
The adapter at projects/stablz exports TVL: 
        
 
 
    ethereum-staking          2.69 M
    ethereum                  1.37 k
    staking                   2.69 M
    
    total                    1.37 k

**Comment by onlystables** [comment]
hey
the $8 is just whats on there but we move it to fiat to fund the underlying yield generating activity, so better to check deposits in the events listener

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by g1nt0ki** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters/commit/2655eef95b371f21639dd879ee7f734efd4c79ee

**Comment by onlystables** [comment]
works for us!

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by onlystables** [comment]
Do let me know when we are on there already, thank you

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by g1nt0ki** [comment]
https://defillama.com/protocol/stablz

**Pull request merged**
