### PR TITLE
list comdex chain and harbor-protocol on comdex

### PR DESCRIPTION
**Pull request by cgsingh33**
##### Current TVL: 
------ TVL ------

total                    416.78 k 

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list) 
comdex

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
14713

##### Short Description (to be shown on DefiLlama): 
Comdex is a DeFi infrastructure layer for the Cosmos ecosystem. A layer-1 infrastructure for seamless deployment of DeFi applications in the Cosmos ecosystem, powering DeFi in the multi-chain future.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/harbor-protocol.js exports TVL: 
        
 
 
    
    total                    416.77 k

**Comment by cgsingh33** [comment]
> The adapter at projects/harbor-protocol.js exports TVL:
> 
> ```
> total                    416.77 k 
> ```

Yes, TVL fluctuate with time, as the price goes up and down of assets locked as well as user interaction with vaults also alters the TVL

**Comment by g1nt0ki** [comment]
> > The adapter at projects/harbor-protocol.js exports TVL:
> > ```
> > total                    416.77 k 
> > ```
> 
> Yes, TVL fluctuate with time, as the price goes up and down of assets locked as well as user interaction with vaults also alters the TVL

Yeah, the PR looks good, this is a bot message testing the adapter

**Comment by g1nt0ki** [comment]
@cgsingh33 thanks for the adapter, is there some way to get the breakdown. I see an rpc call against this endpoint `/comdex.vault.v1beta1.Query/QueryTVLByAppOfAllExtendedPairs` but dunno how to convert to rest call

this way, we will be able to token breakdown in protocol chart

**Comment by cgsingh33** [comment]
> @cgsingh33 thanks for the adapter, is there some way to get the breakdown. I see an rpc call against this endpoint `/comdex.vault.v1beta1.Query/QueryTVLByAppOfAllExtendedPairs` but dunno how to convert to rest call
> 
> this way, we will be able to token breakdown in protocol chart

https://rest.comdex.one/comdex/vault/v1beta1/tvl-by-app-all-extended-pairs/2

this is the rest call that you are looking for, this gives collateral locked asset-wise, but can contain duplicate assets too, for which you need to add. but after that too you need the price of the asset to calculate the TVL.

**Comment by g1nt0ki** [comment]
thanks, I have made the change here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/97331757282db7e73c4e64af908296108b8800bf

**Pull request merged**
