### PR TITLE
yfx-v3 commit

### PR DESCRIPTION
**Pull request by yfxcom**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
Name (to be shown on DefiLlama):  YFX
Twitter Link: https://twitter.com/YFX_COM
List of audit links if any: https://skynet.certik.com/projects/yfx
Website Link: https://www.yfx.com/
Current TVL: 459K
Logo (High resolution, will be shown with rounded borders): https://www.yfx.com/logo/black-yellow-square-400.png
Treasury Addresses (if the protocol has treasury):
Chain: Arbitrum
Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): yfx
Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): 9946
Short Description (to be shown on DefiLlama): World-leading decentralized perpetual exchange with up to 100x leverage, high liquidity, low fees, and no slippage
Token address and ticker if any:
    ETH: 0xf55a93b613d172b86c2ba3981a849dae2aecde2f
    Heco: 0xf55a93b613d172b86c2ba3981a849dae2aecde2f
    BSC: 0xf55a93b613d172b86c2ba3981a849dae2aecde2f
    TRON: TAP7qf8Ao26ZAKYS5E6SGozUNoSLvBHsGa
    Arbitrum:  0x569deb225441FD18BdE18aED53E2EC7Eb4e10D93
Category (full list at https://defillama.com/categories) *Please choose only one: Derivatives
Oracle used (Chainlink/Band/API3/TWAP or any other that you are using): Chainlink
forkedFrom (Does your project originate from another project): None.
methodology (what is being counted as tvl, how is tvl being calculated): Accumulate the token value of each pool

### CODE REVIEW

**Comment by yfxcom** [comment]
Yes, correct

**Comment by llamatester** [comment]
The adapter at projects/amyfinance exports TVL: 
        
 
 
    arbitrum                  0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/brinc exports TVL: 
        
 
 
    arbitrum                  7.42 k
    
    total                    7.42 k

**Comment by llamatester** [comment]
The adapter at projects/jaguarswap.js exports TVL: 
        
 
 
    arbitrum-staking          0
    arbitrum                  360.93370484560995
    staking                   0
    
    total                    360.93370484560995

**Comment by llamatester** [comment]
Error while running adapter at projects/parrotegg: 
        
 
  
    
    
    Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0xFb15945E38a11450AF5E3FF20355D71Da72FfE8a","data":"0x081e3eda","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:654:52
        at Array.forEach (<anonymous>)

**Pull request merged**
