### PR TITLE
Refactor Algofi adapter

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/algofi-swap exports TVL: 
        
 
 
    algorand                  20.12 M
    algorand-staking          13.81 M
    staking                   13.81 M
    
    total                    20.12 M

**Comment by llamatester** [comment]
The adapter at projects/algofi exports TVL: 
        
 
 
    algorand                  0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/algofi-swap exports TVL: 
        
 
 
    algorand                  20.11 M
    algorand-staking          13.82 M
    staking                   13.82 M
    
    total                    20.11 M

**Comment by llamatester** [comment]
The adapter at projects/algofi exports TVL: 
        
 
 
    algorand                  112.10 M
    algorand-borrowed         17.48 M
    algorand-staking          1.49 M
    borrowed                  17.48 M
    staking                   1.49 M
    
    total                    112.10 M

**Comment by llamatester** [comment]
The adapter at projects/algofi-swap exports TVL: 
        
 
 
    algorand-staking          0
    algorand                  3.69 M
    staking                   0
    
    total                    3.69 M

**Comment by llamatester** [comment]
The adapter at projects/algofi exports TVL: 
        
 
 
    algorand-staking          1.47 M
    algorand                  96.38 M
    algorand-borrowed         17.46 M
    staking                   1.47 M
    borrowed                  17.46 M
    
    total                    96.38 M

**Comment by johnclarke96** [comment]
Hi @g1nt0ki -- I'm reviewing this PR. It might be missing assets given the llamatester output looks significantly different from our current llamatester.

**Comment by llamatester** [comment]
The adapter at projects/algofi-swap exports TVL: 
        
 
 
    algorand-staking          0
    algorand                  3.63 M
    staking                   0
    
    total                    3.63 M

**Comment by llamatester** [comment]
The adapter at projects/algofi exports TVL: 
        
 
 
    algorand-staking          1.34 M
    algorand                  95.33 M
    algorand-borrowed         17.79 M
    staking                   1.34 M
    borrowed                  17.79 M
    
    total                    95.33 M

**Comment by llamatester** [comment]
The adapter at projects/gard exports TVL: 
        
 
 
    algorand-treasury         33.87 k
    algorand-staking          1.17 M
    algorand                  5.23 M
    treasury                  33.87 k
    staking                   1.17 M
    
    total                    5.23 M

**Comment by mccabe-david** [comment]
Hi @g1nt0ki, thanks for refactoring the adapter. I have a few questions:

1. Why is borrowed GARD uncounted? When a user mints GARD, they must eventually return the GARD plus interest to pay off their debt. Is this info not useful for tracking purposes? To see how much GARD has been minted?

2. Why is GARD not included in Treasury TVL? Some of the interest accrued from users having their position open goes to the treasury, which will then be passed on to governance token (i.e. GAIN) holders when they burn their governance tokens. The GARD in the treasury account is earned revenue. 

FYI:
-The GARD protocol has native staking (unlike MAKR, I believe?). A portion of the debt accrued from borrowing GARD goes to supplying rewards for staking pools. 
-GAIN, our governance token, has not been released.

**Comment by g1nt0ki** [comment]
total supply of GARD is useful info but we have different dashboard for tracking stablecoins, maybe tracking there is better? https://defillama.com/stablecoins 

'borrowed' is meant for lending platforms, not for CDPs, we dont have it for any other.

Valid point about GARD, I am re-enabling it. We usually dont allow native tokens in treasury because it can be inflated because team controls the supply and can mint themselves a lot tokens.

Regarding not including treasury in tvl, tvl is user tokens locked in protocol.

**Comment by g1nt0ki** [comment]
@mccabe-david hmm, why is there like 9 trillion GARD in first treasury wallet

**Comment by mccabe-david** [comment]
Thanks for the quick response. The first treasury wallet is from v1, and the GARD in there is not earned revenue. The second treasury wallet only has ~100 GARD in revenue thusfar. You shouldn't count the GARD from the first wallet as treasury. We still haven't moved all GARD into the v2 contracts (there's also ~1.8T unminted GARD in the old v1 reserve as well).

**Comment by mccabe-david** [comment]
If it's helpful, I can take a pass @g1nt0ki

**Comment by mccabe-david** [comment]
I'm having trouble working on the 'algofi' branch on my remote. Here's the treasury() function I wrote,
```
async function treasury() {
  return sumTokens({ owners: [treasuryAddress, v2TreasuryAddress], blacklistedTokens: [tokens.gard] })
  let total = await sumTokens({ owners: [v2TreasuryAddress] })
  let v1 = await sumTokens({ owners: [treasuryAddress], blacklistedTokens: [tokens.gard] })
  for (const [key, value] of Object.entries(v1)) {
    if (value != '0'){
      if (total[key] != '0'){
        total[key] += value
      }
      else{
        total[key] = value
      }
    }
  }
  return total
}
```

**Comment by g1nt0ki** [comment]
> Hi @g1nt0ki -- I'm reviewing this PR. It might be missing assets given the llamatester output looks significantly different from our current llamatester.

hi @johnclarke96 I had the same doubt so I went through the code multiple times, 

For Lending, it is lower because I am not counting `'STBL', 'STBL2', 'BANK'`   because these are tokens native to your protocol, also not counting the LP tokens from your dex as it would be double countng
For dex - this puzzled me for a while as to why it is so low, feel like your UI is misleading, you are displaying cTokens from lending app as underlying tokens? my current guess is, it is lot lower because I am not counting/pricing the CTokens in the dex, again this would be double counting as we are already counting the underlying token as part of lending tvl

But the adapter still a bit incomplete, I am fixing the pool2/staking part.

**Comment by johnclarke96** [comment]
If we were a separate protocol (e.g. Tinyman) how would they categorize an AMM pool of our bTokens? Ultimately, we wrote, tested, and deployed new smart contracts to house this TVL so it should be reflect somewhere in our TVL figure. Otherwise, to fairly apply this rule, you'll need to re-audit many projects since this is a somewhat common practice.

**Comment by llamatester** [comment]
The adapter at projects/algofi-swap exports TVL: 
        
 
 
    algorand                  3.61 M
    
    total                    3.61 M

**Comment by llamatester** [comment]
The adapter at projects/algofi exports TVL: 
        
 
 
    algorand-staking          2.70 M
    algorand                  94.00 M
    algorand-borrowed         17.72 M
    staking                   2.70 M
    borrowed                  17.72 M
    
    total                    94.00 M

**Comment by llamatester** [comment]
The adapter at projects/gard exports TVL: 
        
 
 
    algorand-treasury         33.33 k
    algorand-staking          1.16 M
    algorand                  5.15 M
    treasury                  33.33 k
    staking                   1.16 M
    
    total                    5.15 M

**Comment by llamatester** [comment]
The adapter at projects/algofi-swap exports TVL: 
        
 
 
    algorand                  3.47 M
    
    total                    3.47 M

**Comment by llamatester** [comment]
The adapter at projects/algofi exports TVL: 
        
 
 
    algorand                  93.01 M
    algorand-borrowed         17.48 M
    algorand-staking          2.62 M
    borrowed                  17.48 M
    staking                   2.62 M
    
    total                    93.01 M

**Comment by llamatester** [comment]
The adapter at projects/folks-finance exports TVL: 
        
 
 
    algorand-borrowed         3.07 M
    algorand                  39.73 M
    borrowed                  3.07 M
    
    total                    39.73 M

**Comment by llamatester** [comment]
The adapter at projects/gard exports TVL: 
        
 
 
    algorand-staking          1.17 M
    algorand-treasury         32.92 k
    algorand                  5.06 M
    staking                   1.17 M
    treasury                  32.92 k
    
    total                    5.06 M

**Comment by llamatester** [comment]
The adapter at projects/folks-galgo exports TVL: 
        
 
 
    algorand                  61.70 M
    
    total                    61.70 M

**Pull request merged**
