### PR TITLE
add venombridge tvl

### PR DESCRIPTION
**Pull request by d0-d1**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

VenomBridge

##### Twitter Link:

https://twitter.com/VenomBridge

##### List of audit links if any:

- [certik](https://skynet.certik.com/projects/venom-bridge)

##### Website Link:

https://venombridge.com

##### Logo (High resolution, will be shown with rounded borders):

https://venombridge.com/assets/logo.svg

##### Current TVL:

23.02 M

##### Short Description (to be shown on DefiLlama):

Venombridge.com is a pioneering decentralized cross-chain bridge connecting the Venom Blockchain with Ethereum Virtual Machine (EVM) compatible networks. As the first of its kind on the Venom ecosystem, it enables seamless token transfers between the Venom Blockchain and other major EVM chains like Ethereum, Binance Smart Chain, Avalanche, and Polygon. This trustless bridge facilitates interoperability, allowing users to leverage the strengths of multiple blockchain networks while securely moving digital assets across disparate ecosystems. By bridging the Venom Blockchain with leading EVM platforms, Venombridge.com unlocks new opportunities for decentralized applications and fosters greater adoption of the Venom network within the broader Web3 landscape.

##### methodology (what is being counted as tvl, how is tvl being calculated):

We are summing all bridge’s token vaults balances for each supported networks and express it in USD

### CODE REVIEW

**Comment by g1nt0ki** [comment]
just checked, I dont see tokens on any of these contracts, is the bridge live?

**Comment by d0-d1** [comment]
The VenomBridge is live and operational.

We calculated TVL as a sum of the multivault account (0x4ab740157721105ae503fbad756a578171512525) balances in the evm networks. And total supply of Wrapped Venom (0x46f84dc6564cdd93922f7bfb88b03d35308d87c9) in the evm networks for Venom network TVL. Because it's token is owned by Venom Bridge.

You can check the multivalt account balances in the [debank](https://debank.com/profile/0x4ab740157721105ae503fbad756a578171512525)

And total supply of the Wrapped Venom in the networks:

- ethereum
- bsc
- fantom
- polygon
- avax

Bellow you can find the result of the test execution, that seems to be pretty accurate.

Please let me know if you need any clarification or have additional questions about the methodology used. I'm happy to provide more details.


```bash
❯ node test.js projects/venombridge/index.js
--- bsc ---
USDT                      2.88 M
WBNB                      158.81 k
WBTC                      133.88 k
USDC                      31.81 k
WETH                      26.25 k
YOSHI                     8.73 k
1ART                      4.64 k
DAI                       3.95 k
Total: 3.25 M

--- polygon ---
USDT                      438.16 k
WMATIC                    44.54 k
USDC                      41.14 k
WETH                      26.25 k
DAI                       3.68 k
Total: 553.78 k

--- fantom ---
WFTM                      17.24 k
1ART                      14.14 k
YOSHI                     9.74 k
Total: 41.12 k

--- avax ---
USDT                      567.15 k
USDC                      41.17 k
AVAX                      20.04 k
DAI                       3.63 k
Total: 631.98 k

--- ethereum ---
USDT                      2.53 M
WETH                      557.85 k
WBTC                      66.94 k
USDC                      47.53 k
DAI                       8.14 k
Total: 3.21 M

--- venom ---
VENOM                     14.42 M
Total: 14.42 M

--- tvl ---
VENOM                     14.42 M
USDT                      6.42 M
WETH                      610.35 k
WBTC                      200.83 k
USDC                      161.65 k
WBNB                      158.81 k
WMATIC                    44.54 k
AVAX                      20.04 k
DAI                       19.41 k
1ART                      18.79 k
YOSHI                     18.47 k
WFTM                      17.24 k
Total: 22.10 M

------ TVL ------
bsc                       3.25 M
polygon                   553.78 k
fantom                    41.12 k
avax                      631.98 k
ethereum                  3.21 M
venom                     14.42 M

total                    22.10 M
```

**Comment by llamatester** [comment]
The adapter at projects/venombridge exports TVL: 
        
 
 
    bsc                       3.26 M
    avax                      661.09 k
    polygon                   572.79 k
    fantom                    41.28 k
    ethereum                  3.20 M
    venom                     14.45 M
    
    total                    22.19 M

**Comment by g1nt0ki** [comment]
@d0-d1 sorry, my bad. I was looking at the wrong address, I was looking at the token contracts instead of bridge addresses

**Pull request merged**
