### PR TITLE
Update illuminate's TVL to account for invested principal tokens

### PR DESCRIPTION
**Pull request by sourabhmarathe**
This PR updates Illuminate's `tvl` method to account for the value of `fyToken`'s locked in its pools. To do so, we used the following methodology:

1. Get the balance of PTs held by the pool
2. Get the price of selling 1 PT in that same pool
3. Calculate the overall value in underlying if all PTs were sold at that price

This is in addition to the TVL of the shares token that is already accounted for.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/illuminate-fi exports TVL: 
        
 
 
    ethereum                  241.92 k
    
    total                    241.92 k

**Comment by sourabhmarathe** [comment]
@g1nt0ki Hey! You are correct in stating that `fyToken`s are from our protocol. The reason I felt that they should be considered TVL is that they are explicitly backed by the underlying asset, so in order for a user to `mint` fyTokens in the first place, they have to deposit underlying assets (such as USDC in the one market we have up currently). 

Because of the nature of fixed rates, these fyTokens trade at a discount (and approach 1:1 with the underlying as maturity approaches). I felt that taking this into account would be a fair representation of how much value has been put towards providing liquidity in the pools.

**Comment by g1nt0ki** [comment]
Sorry, but this is not a question of iPT's value, our definition of TVL is value locked by users in a protocol, iPT is not deposited by users, amount deposited - amount withdrawn by users matches  current tvl (about ~20k)?

**Comment by sourabhmarathe** [comment]
> iPT is not deposited by users

It is true that iPTs are not deposited by users. However, they are representative of deposits made in the underlying protocol. With regards to the AMM in question here, we're referring to the iPTs that users have provided to the AMM to provide liquidity. 

> amount deposited - amount withdrawn by users matches current tvl (about ~20k)?

I'm not sure what you mean here -- users do not withdraw from the AMM, but instead pull liquidity out of the pool by burning their LP tokens in exchange for a combination of iPTs and underlying assets. Upon maturity, they may redeem those iPTs for the underlying asset.

**Comment by g1nt0ki** [comment]
@sourabhmarathe 

when a user mints iPT token, yvUSDC is added to your vault: https://etherscan.io/tx/0x0ba8f47b15e1039c1ff874d77037a40a8367d5bf15c23d7c275f9c3f6332a9ca

while burning iPT, it is converted back to USDC and returned  to the user: https://etherscan.io/tx/0x09f243db381546fa2027b5f4c71eb1cd78294f042f3ff6b21a8ba36d32fb8128

This is what I referred to as amuont deposited - withdrawn

so how is USDC/yvUSDC in the vault not representative of tvl of your protocol?  I dont fully understand the AMM you are referring to, is there some other way iPT tokens are minted/backed by?

**Comment by sourabhmarathe** [comment]
@g1nt0ki 

> so how is USDC/yvUSDC in the vault not representative of tvl of your protocol?

It is representative of a portion of value locked in the AMM. However, we feel that it leaves out significant amounts of value that on the other side of the swap.

>  is there some other way iPT tokens are minted/backed by

Yes, in order to acquire iPTs, users must provide qualified PTs to Illuminate. As a result, iPTs represent their lent positions within a given market. In the current market, this means (USDC/JUN23) PTs from Sense, Notional and Swivel are accepted. Given their value, we would like to include these iPTs committed to the AMM as part of TVL. 

These PTs trade at a discount until they mature, which is why the current price of iPTs within the YieldSpace Pool is a good barometer for the total iPT value locked within the AMM.

**Comment by JTraversa** [comment]
To also speak directly to the rationale that DeFiLlama uses for the computation of TVL(https://docs.llama.fi/list-your-project/what-to-include-as-tvl#not-tvl), the only potential qualifier for PTs NOT being included would be if they are wrapped in another protocol?

> We also don't accept assets that your protocol generates and are locked into other protocols, as that's the later protocols TVL, not your project's. See [this](https://github.com/DefiLlama/DefiLlama-Adapters/pull/60#issuecomment-807045050) for rationale

In our case, overcollateralized deposits generate principal tokens across a number of protocols, and TVL would have initially come from Notional, Sense, Pendle, Element, APWine, Swivel, Yield and Tempus and been the "later" protocol's (Illuminate's) TVL, 

And reading deeper into the rationale (https://github.com/DefiLlama/DefiLlama-Adapters/pull/60#issuecomment-807045050) 

>In any case, if we don't consider LP tokens locked inside some other protocols' contracts I don't see a compelling argument for considering them in this case, given that ported tokens would be less "locked" than tokens explicitly locked in contracts.

Specifically, it sounds like the intention is to avoid double counting and to attempt to count "locked" tokens that in many ways are again "locked" in one project and should be considered part of their TVL.

That said, it might be helpful to elaborate on our mechanic slightly. Once iPTs are minted using external principal tokens, the iPT CANNOT be exchanged back into principal tokens, and instead represents the ability to redeem 1 underlying currency when the iPT matures. 

The iPT is at that point fully collateralized and WILL 100% be worth 1 underlying at maturity, and that said we can use a post-maturity example to more easily understand a hypothetical TVL. 

If maturity has passed, external PTs are redeemed for USDC. iPTs are at that point redeemable for 1 USDC, and there is 1 USDC sitting in our contracts to redeem.

This would "magically" have our current TVL increase from ~20k to ~250k in an instant, although the collateral posted to our protocol has not actually changed. Pre-maturity this still should be the case. Each iPT is backed by a the precise amount of value given to each external PT.

**Comment by g1nt0ki** [comment]
@sourabhmarathe @JTraversa thanks for the patient explanation, I missed the lender contract where your protocol forwards the USDC to other protocols like swivel and others https://etherscan.io/address/0x429B47C4AEADD42BBcB118651C8984086Bfc4551

Can you check my changes to your code here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/5983 logic is the same, minor changes on how sdk calls are made

**Pull request merged**
