### PR TITLE
update: remove tvl information about options vaults

### PR DESCRIPTION
**Pull request by yash-trufin**
Hi, apologies for re-raising basically the exact same pull request as last time. But this is exactly what contributes to our tvl at the moment.

We have decommissioned the contract at address `0xcfab8530ccf1f9936daede537d6ebbc75289006d`. There is less than 100 dollars in tvl at this old address. All the customer funds that were locked here have been withdrawn. The remaining amount is the part of the tests done by the TruFin team. The gas cost to take out these funds will be more than the actual value of the these funds and hence there is no point in taking them out.

We only want to show information about the new contract at `0xa43a7c62d56df036c187e1966c03e2799d8987ed`. It has close to 11M USD in tvl. 

Please advice if there is a different way to remove the old listing and show this new one on DefiLlama.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/trufin exports TVL: 
        
 
 
    ethereum                  11.01 M
    
    total                    11.01 M

**Comment by yash-trufin** [comment]
If you lookup TruFin's information on DefiLlama, you will end up at this page 
TruFin Protocol:  [https://defillama.com/protocol/trufin-protocol](https://defillama.com/protocol/trufin-protocol)

And two additional tabs
TruFin: [https://defillama.com/protocol/trufin](https://defillama.com/protocol/trufin)
TruFin MATIC LSD: [https://defillama.com/protocol/trufin-matic-lsd](https://defillama.com/protocol/trufin-matic-lsd)

We only want to show a single tab with the category "Liquid Staking" under the TruFin tab.

**Comment by g1nt0ki** [comment]
hi @yash-trufin, sorry, we dont remove old listings as policy, we still have a few listings that have scammed/rugged

**Comment by yash-trufin** [comment]
I have opened a PR for minor updates to the vault names and descriptions here
[https://github.com/DefiLlama/defillama-server/pull/3874](https://github.com/DefiLlama/defillama-server/pull/3874)

**Comment by g1nt0ki** [comment]
@yash-trufin it is fixed here: https://github.com/DefiLlama/defillama-server/commit/a8b84f7fc2422d0565e6414e061d9618ad7a3b63#diff-0aed1131afc2d6f1cba8d0f54d2af07aef316e73214335d69f5724262cb4d5f5

**Pull request closed without merging**
