### PR TITLE
Depreciate ondofinance to ondofinance-v1 and add new TVL for ondofinance

### PR DESCRIPTION
**Pull request by nickplace**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Ondo Finance v1 (Legacy)

_We want to create a new protocol ondo-finance-v1 and make it's parent Ondo Finance (with the fund TVLs)_

##### Twitter Link:

https://twitter.com/OndoFinance

##### List of audit links if any:
https://docs.ondo.finance/assets/files/Ondo-ABDK-Audit-October-2022-b08d29dce81d383e0d2c05fbf51af385.pdf
https://docs.ondo.finance/assets/files/Ondo-Quantstamp-Audit-January_2022-c670ae4579ad332729bcc271612dda74.pdf

##### Website Link:
https://v1.ondo.finance

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/fluxfinance exports TVL: 
        
 
 
    ethereum                  1.29 M
    ethereum-borrowed         10.06 M
    borrowed                  10.06 M
    
    total                    1.29 M

**Comment by llamatester** [comment]
The adapter at projects/fluxfinance exports TVL: 
        
 
 
    ethereum-borrowed         10.04 M
    ethereum                  1.29 M
    borrowed                  10.04 M
    
    total                    1.29 M

**Comment by llamatester** [comment]
The adapter at projects/ondofinance-v1 exports TVL: 
        
 
 
    ethereum                  0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/fluxfinance exports TVL: 
        
 
 
    ethereum                  27.37 M
    ethereum-borrowed         10.07 M
    borrowed                  10.07 M
    
    total                    27.37 M

**Comment by llamatester** [comment]
The adapter at projects/ondofinance-v1 exports TVL: 
        
 
 
    ethereum                  0
    
    total                    0

**Comment by nickplace** [comment]
@realdealshaman

**Pull request merged**
