### PR TITLE
feat : add x7 eco system tokens

### PR DESCRIPTION
**Pull request by MikeMurpher**
Name (to be shown on DefiLlama): 

X7 Finance

Twitter Link: 

https://twitter.com/X7_Finance

List of audit links if any: 

N/A

Website Link: 

https://x7.finance/

Logo: 

https://x7.finance/X7whitelogo.png

Current TVL: 

348.16K

Chain:

Ethereum

Coingecko ID (so your TVL can appear on Coingecko):

x7r

Coinmarketcap ID (so your TVL can appear on Coinmarketcap):

22184

Short Description (to be shown on DefiLlama):

X7 Finance. Leveraged Decentralized Exchange.
Launch your project on Xchange with 10-1000x the initial liquidity into the Ethereum ecosystem where anyone can Swap, Borrow and Lend!.  Trust no one. Trust code. Long live

Token address and ticker if any:

Ethereum: X7R 0x70008f18fc58928dce982b0a69c2c21ff80dca54

Category (full list at https://defillama.com/categories) 

Dexes

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

N/A

forkedFrom (Does your project originate from another project):

version of the Uniswap V2 Factory, Liquidity Pair, and Router contracts

methodology (what is being counted as tvl, how is tvl being calculated):

All tokens in X7R eco-system

### CODE REVIEW

**Comment by MikeMurpher** [comment]
Apologies.  If I correct the token address to the LP contract address will this be correct.

**Comment by g1nt0ki** [comment]
@MikeMurpher sorry, these are tokens locked in unswap contracts right? what are the user tokens locked in your protocol/dex?

**Comment by g1nt0ki** [comment]
hi @MikeMurpher , we have separate export for treasury, example: https://defillama.com/protocol/ribbon, LPs are okay to be counted under treasury but no native tokens

I would say, tvl of your protocol would be tokens locked in your dex (when it is launched)

**Comment by MikeMurpher** [comment]
Hi @g1nt0ki , thank you for the link when I try returning the treasury only I get the Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains

Is there a way I can default the export TVL to zero

module.exports = {
    ethereum: {
        treasury: getTreasury,
    },
};

**Comment by g1nt0ki** [comment]
hi @MikeMurpher , you can do `tvl: () => ({}),`

**Pull request merged**
