### PR TITLE
Update TVL for Defibox

### PR DESCRIPTION
**Pull request by DenisCarriere**
- [x] update **WAX** TVL using `get24HInfo`
- [x] remove **BSC** temporarily, TVL endpoint is not available at the moment.
- [x] add new Defibox protocols to **EOS** TVL
  - [x] Vault protocol (time lock deposit)
  - [x] Balance protocol (stable token swap pool)

## TVL analysis

https://eos.defibox.io/dataAnalysis/

image

## Defillama TVL tests

```
--- wax ---
WAXP                      163.74 k
Total: 163.74 k 

--- eos-borrowed ---
USDT                      266.78 k
Total: 266.78 k 

--- eos ---
USDT                      15.68 M
EOS                       9.39 M
Total: 25.07 M 

--- tvl ---
USDT                      15.68 M
EOS                       9.39 M
WAXP                      163.74 k
Total: 25.23 M 

--- borrowed ---
USDT                      266.78 k
Total: 266.78 k 

------ TVL ------
wax                       163.74 k
eos-borrowed              266.78 k
eos                       25.07 M
borrowed                  266.78 k

total                    25.23 M 
```

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/defibox: 
        
 
  
    
    
    Error: 
        Found export keys that were not part of specification: bsc
    
        List of valid keys: 
    				
    				tvl
    				staking
    				methodology
    				pool2
    				misrepresentedTokens
    				fetch
    				timetravel
    				borrowed
    				start
    				masterchef
    				doublecounted
    				treasury
    				hallmarks
    				incentivized
    				offers
    				deadFrom
    				broken
    				ownTokens
    				vesting

**Comment by llamatester** [comment]
The adapter at projects/defibox exports TVL: 
        
 
 
    eos-borrowed              0
    wax                       163.74 k
    eos                       25.03 M
    borrowed                  0
    
    total                    25.19 M

**Comment by llamatester** [comment]
The adapter at projects/defibox exports TVL: 
        
 
 
    wax                       163.75 k
    eos-borrowed              266.85 k
    eos                       25.08 M
    borrowed                  266.85 k
    
    total                    25.25 M

**Comment by llamatester** [comment]
The adapter at projects/defibox exports TVL: 
        
 
 
    bsc                       0
    eos-borrowed              270.79 k
    wax                       165.96 k
    eos                       25.10 M
    borrowed                  270.79 k
    
    total                    25.26 M

**Comment by g1nt0ki** [comment]
@DenisCarriere thanks for the PR

**Pull request merged**
