### PR TITLE
Add kumu finance adapter

### PR DESCRIPTION
**Pull request by KumuFinance**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/kumu-finance exports TVL: 
        
 
 
    klaytn-pool2              0
    klaytn-staking            0
    klaytn                    296.25 k
    pool2                     0
    staking                   0
    
    total                    296.25 k

**Comment by llamatester** [comment]
The adapter at projects/gysr exports TVL: 
        
 
 
    ethereum                  6182317347733.55 B
    
    total                    6182317347733.55 B

**Comment by llamatester** [comment]
The adapter at projects/kumu-finance exports TVL: 
        
 
 
    klaytn-staking            5.51 k
    klaytn                    248.71 k
    staking                   5.51 k
    
    total                    248.71 k

**Comment by llamatester** [comment]
The adapter at projects/kumu-finance exports TVL: 
        
 
 
    klaytn-staking            5.53 k
    klaytn                    248.61 k
    staking                   5.53 k
    
    total                    248.61 k

**Comment by g1nt0ki** [comment]
@KumuFinance thanks a lot for the PR

**Pull request merged**
