### PR TITLE
Add RBN Bond TVL (Ribbon Finance)

### PR DESCRIPTION
**Pull request by chuddster**
##### Twitter Link:

https://twitter.com/porterfinance_/status/1534260070153715712

##### Website Link:

https://app.ribbon.finance/

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/ribbon exports TVL: 
        
 
 
    avalanche                 3.91 M
    ethereum-staking          6.11 M
    ethereum                  135.27 M
    solana                    1.14 M
    staking                   6.11 M
    
    total                    140.32 M

**Comment by llamatester** [comment]
The adapter at projects/ribbon exports TVL: 
        
 
 
    avalanche                 3.83 M
    ethereum-staking          5.64 M
    solana                    1.03 M
    ethereum                  116.94 M
    staking                   5.64 M
    
    total                    121.80 M

**Comment by llamatester** [comment]
The adapter at projects/ribbon exports TVL: 
        
 
 
    avalanche                 3.83 M
    solana                    1.03 M
    ethereum-staking          5.64 M
    ethereum                  126.32 M
    staking                   5.64 M
    
    total                    131.18 M

**Comment by chuddster** [comment]
> shouldnt this be part of porter finance tvl?

Hey, good question. 

So for context, Ribbon [partnered](https://twitter.com/ribbonfinance/status/1524583641447239680) with Porter Finance to help other treasuries, including ourselves, issue debt. You do this by collateralizing a native token (as we did) when issuing a bond. The integration with Porter is set up such that the actual issuance is done in the Ribbon Finance portal - so Porter's smart contracts are an extension of our offering.

**Comment by g1nt0ki** [comment]
@chuddster yes, you are offering a bond, but the way I see it, end users dont really interact with this feature, also we rarely count the native tokens under tvl (because it can be manipulated), even for treasury we only count non-native tokens. Can we instead count the tokens raised by selling the bond under 'treasury'?

**Comment by chuddster** [comment]
> @chuddster yes, you are offering a bond, but the way I see it, end users dont really interact with this feature, also we rarely count the native tokens under tvl (because it can be manipulated), even for treasury we only count non-native tokens. Can we instead count the tokens raised by selling the bond under 'treasury'?

**Comment by llamatester** [comment]
The adapter at projects/ribbon exports TVL: 
        
 
 
    avalanche                 3.85 M
    ethereum-staking          5.79 M
    ethereum                  83.18 M
    solana                    855.58 k
    staking                   5.79 M
    
    total                    87.88 M

**Comment by g1nt0ki** [comment]
> @g1nt0ki hey, its true end users don't interact with it - this is a B2B product for other protocols not retail.
> 
> The first bond issuance was us so we are counting RBN as the collateral but in the future it will be other protocols native tokens. Imagine a protocol X with native token Y approaches us and says we want to collateralize 500 Y tokens from our treasury and issue bonds against it. We can count the 500 Y tokens right (because its another protocol's native token) ?

I had to confirm with the team, yes you could count other team's tokens but not your own

**Pull request closed without merging**
