### PR TITLE
add Satsat

### PR DESCRIPTION
**Pull request by edsonElong**
##### Name (to be shown on DefiLlama):
Satsat

##### Twitter Link:
https://twitter.com/satsatstst

##### Website Link:
https://satsat.exchange

##### Logo (High resolution, will be shown with rounded borders):
logo

##### Current TVL:
269.99 M  USDT

##### Chain:
Map Protocol

##### Short Description (to be shown on DefiLlama):
STST is a Community-Oriented Bitcoin Layer2 BRC20 Trading Platform with Fairness, Shared Benefits, Transparency, and Low Gas Fees SATSAT is an order book trading system for BRC20 tokens that is built on the Bitcoin second-layer network,MAP Protocol.

##### Token address and ticker if any:
$STST Map Protocol 0xF5a59f961a8e86285Dae2e45ac4Ae50E4E47Ba97
$STST Bitcore d0c84467a80667bef2c48cdc26cc496f2c1e870915b2f4c8ff31f251c70c9697i0

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Marketplace

##### forkedFrom (Does your project originate from another project):
No, it is built on our own

### CODE REVIEW

**Comment by g1nt0ki** [comment]
Please refactor the code to compute tvl on chain

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
.

**Comment by edsonElong** [comment]
> .

I have resubmitted the statistical code. May I know where the problem is?

**Comment by g1nt0ki** [comment]
hi @edsonElong 

At this point, I am getting 0 tvl because we dont want to rely on your api for token prices & we dont have these coins in our server,  do you have some documentation/api where I can get the mapping between bitocin /brc20 tokens and bridged map addresses? 

    ┌─────────┬─────────────────┬────────┬─────────────┬──────────────────────────────────────────────────┬──────────┐
    │ (index) │      name       │ symbol │   balance   │                      label                       │ decimals │
    ├─────────┼─────────────────┼────────┼─────────────┼──────────────────────────────────────────────────┼──────────┤
    │    0    │ 'STST (brc-20)' │ 'STST' │   '32046'   │ 'map:0xf5a59f961a8e86285dae2e45ac4ae50e4e47ba97' │   '18'   │
    │    1    │     'LSGS'      │ 'LSGS' │ '943390700' │ 'map:0x756af1d3810a01d3292fad62f295bbcc6c200aea' │   '18'   │
    │    2    │     'FOX2'      │ 'FOX2' │ '15073754'  │ 'map:0x1ddecb7126028ea347408edef9d218f74b226d22' │   '18'   │
    │    3    │     'EEAA'      │ 'EEAA' │ '164331308' │ 'map:0x040a66ed7def1c037c5c9848bc5d44dcd3b0fc62' │   '18'   │
    │    4    │ 'ROUP (brc-20)' │ 'ROUP' │  '249436'   │ 'map:0x5a1c3f3aae616146c7b9bf9763e0aba9bafc5eae' │   '18'   │
    │    5    │     'RMUD'      │ 'RMUD' │   '60449'   │ 'map:0xed8b05159460c900f12075c3b901ca274fd7486f' │   '18'   │
    │    6    │ 'MMSS (brc-20)' │ 'MMSS' │    '850'    │ 'map:0x0fbb3b3fb1e928f75b3ed8b506bab4503373fdca' │   '18'   │
    │    7    │     '$JMS'      │ '$JMS' │ '153971869' │ 'map:0x13059981f81bee8bfa656ed519cb57ac5ef7ff81' │   '18'   │
    │    8    │     'LMAP'      │ 'LMAP' │  '1685944'  │ 'map:0xe213e3832173fe6ec8377f54ac3920e141b10d8e' │   '18'   │
    │    9    │     'MMQQ'      │ 'MMQQ' │  '1215566'  │ 'map:0x5a91ca4004ada972d50edc5c012080b3158219b1' │   '18'   │
    │   10    │     'CEXL'      │ 'CEXL' │  '498565'   │ 'map:0x316778e855c77f54ee98b93b6a3c33fcbf6abf55' │   '18'   │
    │   11    │     'ELIM'      │ 'ELIM' │  '709317'   │ 'map:0x43b6e2845c0c227feef792cd6cd07a85dc538205' │   '18'   │
    │   12    │     'LEbb'      │ 'LEbb' │   '1072'    │ 'map:0x4605a9fef84ae1460655dfefedcb56432f95d2d3' │   '18'   │
    │   13    │       '-'       │ 'DOMT' │    '58'     │ 'map:0x30d18ff794d2ec0c13a0ecd4f2c9342d12d5f90a' │   '18'   │
    │   14    │       '-'       │ 'UBCY' │    '19'     │ 'map:0xc79d95c28501da0ba69a7a5567709adc22ec8059' │   '18'   │
    │   15    │       '-'       │ 'BHTL' │ '131666090' │ 'map:0xbe13d75b81f30324b5b6ddf8346af27b10f367e2' │   '18'   │
    │   16    │     'EEAA'      │ 'EEAA' │  '2545167'  │ 'map:0xa0e8557e1d96161beec6cad2d8a13473fbe3e556' │   '18'   │
    │   17    │     'CHN$'      │ 'CHN$' │    '49'     │ 'map:0xcc5d2b8e28885199d7fbb7e461da37b10511da54' │   '18'   │
    │   18    │     'L2LP'      │ 'L2LP' │  '2856313'  │ 'map:0x8b58190e3fc9f0876420b70bc00d85041606ad95' │   '18'   │
    │   19    │     'ctmn'      │ 'ctmn' │  '2280000'  │ 'map:0x49b883bb6b657a5833d0ea70ba6e87cd61d97aea' │   '18'   │
    │   20    │     'FANP'      │ 'FANP' │  '272171'   │ 'map:0x0f4cdf7db43e29802cc6821e3a2c227515ba5f7b' │   '18'   │
    │   21    │ 'XDAO (brc-20)' │ 'XDAO' │   '28710'   │ 'map:0x9596a3f29e53aec45594e8f90a976f163791378c' │   '18'   │
    │   22    │     'K88K'      │ 'K88K' │     '3'     │ 'map:0xf437bb861dbf559862d4b92d96c118b4c388d892' │   '18'   │
    │   23    │ 'RATS (brc-20)' │ 'RATS' │  '534050'   │ 'map:0x6369414f2b0e973c7e85a362141aa1430bc30056' │   '18'   │
    │   24    │     '.RWA'      │ '.RWA' │   '16922'   │ 'map:0xc7117642337870c54557f58881cd4794f0d79857' │   '18'   │
    │   25    │ 'ORDI (brc-20)' │ 'ORDI' │     '0'     │ 'map:0x9ca528368964cfb92cffdd51dcced25e27accef9' │   '18'   │
    │   26    │     'mmai'      │ 'mmai' │   '30115'   │ 'map:0xabeee1a043da110e30fd65769ef143db2576f7c7' │   '18'   │
    └─────────┴─────────────────┴────────┴─────────────┴──────────────────────────────────────────────────┴──────────┘

**Comment by g1nt0ki** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters/pull/8893 has similar issues

**Comment by edsonElong** [comment]
> hi @edsonElong
> 
> At this point, I am getting 0 tvl because we dont want to rely on your api for token prices & we dont have these coins in our server, do you have some documentation/api where I can get the mapping between bitocin /brc20 tokens and bridged map addresses?
> 
> ```
> ┌─────────┬─────────────────┬────────┬─────────────┬──────────────────────────────────────────────────┬──────────┐
> │ (index) │      name       │ symbol │   balance   │                      label                       │ decimals │
> ├─────────┼─────────────────┼────────┼─────────────┼──────────────────────────────────────────────────┼──────────┤
> │    0    │ 'STST (brc-20)' │ 'STST' │   '32046'   │ 'map:0xf5a59f961a8e86285dae2e45ac4ae50e4e47ba97' │   '18'   │
> │    1    │     'LSGS'      │ 'LSGS' │ '943390700' │ 'map:0x756af1d3810a01d3292fad62f295bbcc6c200aea' │   '18'   │
> │    2    │     'FOX2'      │ 'FOX2' │ '15073754'  │ 'map:0x1ddecb7126028ea347408edef9d218f74b226d22' │   '18'   │
> │    3    │     'EEAA'      │ 'EEAA' │ '164331308' │ 'map:0x040a66ed7def1c037c5c9848bc5d44dcd3b0fc62' │   '18'   │
> │    4    │ 'ROUP (brc-20)' │ 'ROUP' │  '249436'   │ 'map:0x5a1c3f3aae616146c7b9bf9763e0aba9bafc5eae' │   '18'   │
> │    5    │     'RMUD'      │ 'RMUD' │   '60449'   │ 'map:0xed8b05159460c900f12075c3b901ca274fd7486f' │   '18'   │
> │    6    │ 'MMSS (brc-20)' │ 'MMSS' │    '850'    │ 'map:0x0fbb3b3fb1e928f75b3ed8b506bab4503373fdca' │   '18'   │
> │    7    │     '$JMS'      │ '$JMS' │ '153971869' │ 'map:0x13059981f81bee8bfa656ed519cb57ac5ef7ff81' │   '18'   │
> │    8    │     'LMAP'      │ 'LMAP' │  '1685944'  │ 'map:0xe213e3832173fe6ec8377f54ac3920e141b10d8e' │   '18'   │
> │    9    │     'MMQQ'      │ 'MMQQ' │  '1215566'  │ 'map:0x5a91ca4004ada972d50edc5c012080b3158219b1' │   '18'   │
> │   10    │     'CEXL'      │ 'CEXL' │  '498565'   │ 'map:0x316778e855c77f54ee98b93b6a3c33fcbf6abf55' │   '18'   │
> │   11    │     'ELIM'      │ 'ELIM' │  '709317'   │ 'map:0x43b6e2845c0c227feef792cd6cd07a85dc538205' │   '18'   │
> │   12    │     'LEbb'      │ 'LEbb' │   '1072'    │ 'map:0x4605a9fef84ae1460655dfefedcb56432f95d2d3' │   '18'   │
> │   13    │       '-'       │ 'DOMT' │    '58'     │ 'map:0x30d18ff794d2ec0c13a0ecd4f2c9342d12d5f90a' │   '18'   │
> │   14    │       '-'       │ 'UBCY' │    '19'     │ 'map:0xc79d95c28501da0ba69a7a5567709adc22ec8059' │   '18'   │
> │   15    │       '-'       │ 'BHTL' │ '131666090' │ 'map:0xbe13d75b81f30324b5b6ddf8346af27b10f367e2' │   '18'   │
> │   16    │     'EEAA'      │ 'EEAA' │  '2545167'  │ 'map:0xa0e8557e1d96161beec6cad2d8a13473fbe3e556' │   '18'   │
> │   17    │     'CHN$'      │ 'CHN$' │    '49'     │ 'map:0xcc5d2b8e28885199d7fbb7e461da37b10511da54' │   '18'   │
> │   18    │     'L2LP'      │ 'L2LP' │  '2856313'  │ 'map:0x8b58190e3fc9f0876420b70bc00d85041606ad95' │   '18'   │
> │   19    │     'ctmn'      │ 'ctmn' │  '2280000'  │ 'map:0x49b883bb6b657a5833d0ea70ba6e87cd61d97aea' │   '18'   │
> │   20    │     'FANP'      │ 'FANP' │  '272171'   │ 'map:0x0f4cdf7db43e29802cc6821e3a2c227515ba5f7b' │   '18'   │
> │   21    │ 'XDAO (brc-20)' │ 'XDAO' │   '28710'   │ 'map:0x9596a3f29e53aec45594e8f90a976f163791378c' │   '18'   │
> │   22    │     'K88K'      │ 'K88K' │     '3'     │ 'map:0xf437bb861dbf559862d4b92d96c118b4c388d892' │   '18'   │
> │   23    │ 'RATS (brc-20)' │ 'RATS' │  '534050'   │ 'map:0x6369414f2b0e973c7e85a362141aa1430bc30056' │   '18'   │
> │   24    │     '.RWA'      │ '.RWA' │   '16922'   │ 'map:0xc7117642337870c54557f58881cd4794f0d79857' │   '18'   │
> │   25    │ 'ORDI (brc-20)' │ 'ORDI' │     '0'     │ 'map:0x9ca528368964cfb92cffdd51dcced25e27accef9' │   '18'   │
> │   26    │     'mmai'      │ 'mmai' │   '30115'   │ 'map:0xabeee1a043da110e30fd65769ef143db2576f7c7' │   '18'   │
> └─────────┴─────────────────┴────────┴─────────────┴──────────────────────────────────────────────────┴──────────┘
> ```

We have added the Token mapping address on BTC in this interface https://order.satsat.exchange//api/queryTokenInfo
able to pass:
curl --location --request POST 'https://order.satsat.exchange//api/queryTokenInfo' \
--header 'Content-Type: application/json' \
--data-raw '{"address":"","tokenSymbol":""}'
inscriptionId is the inscription ID on BTC

**Comment by edsonElong** [comment]
> #8893 has similar issues
Part of the tokens are use https://app.rolluper.xyz/ Crossing the bridge chain
Part of it is directly published on the map chain, which is in the https://app.satsat.exchange/ The transaction conducted above is priced through our API

**Comment by llamatester** [comment]
The adapter at projects/satsat exports TVL: 
        
 
 
    map                       2.00 k
    
    total                    2.00 k

**Comment by g1nt0ki** [comment]
@edsonElong I have added mapping for the tokens I have found on coingecko, sorry for the rest, we cant d much, but wait for coingecko listing.

**Comment by edsonElong** [comment]
> @edsonElong I have added mapping for the tokens I have found on coingecko, sorry for the rest, we cant d much, but wait for coingecko listing.

Thank you. We are working hard to make coingecko include more tokens.

**Comment by edsonElong** [comment]
> @edsonElong I have added mapping for the tokens I have found on coingecko, sorry for the rest, we cant d much, but wait for coingecko listing.

coinmarketcap has included map mainnet
You can check the price of the above token through https://coinmarketcap.com/dexscan/networks/map/?page=1&swap=all
Could you please include more tokens from our mainnet?

**Comment by g1nt0ki** [comment]
yes, unfortunately, we use coingecko apis and not coinmarketcap

**Pull request merged**
