### PR TITLE
Add FolksFinance adapter

### PR DESCRIPTION
**Pull request by stefanofa**
##### Twitter Link:
https://twitter.com/FolksFinance

##### List of audit links if any:
1) https://www.coinspect.com/doc/Coinspect%20-%20Smart%20Contract%20Audit%20-%20Folks%20Finance%20v220314.pdf
2) https://github.com/vantagepointreports/releases/blob/main/VPQ-20210652%20-%20Folks.Finance%20-%20Smart%20Contract%20Audit%20-%20Phase%201_Public_V1.0.pdf
3) https://github.com/runtimeverification/publications/blob/main/reports/smart-contracts/Folks-Finance-Design-Review.pdf

##### Website Link:
https://folks.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
- PNG
FolksFinance_token

- SVG
FolksFinance_Token

##### Current TVL:
3.09M

##### Chain:
Algorand

##### Short Description (to be shown on DefiLlama):
Lending and borrowing protocol with innovative features built on Algorand Blockchain.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Average of high-quality price sources such as Chainlink, CoinGecko, CoinMarketCap, Coinbase etc.

##### forkedFrom (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated):
We perform the sum of the dollar value of all deposits, i.e., [regular deposits](https://app.folks.finance/deposit), [lock&earn ](https://app.folks.finance/lock-and-earn)deposits, and deposits in the [Algo Liquid Governance](https://app.folks.finance/algo-liquid-governance) program.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/folks-finance/index.js exports TVL: 
        
 
 
    borrowed                  474.91 k
    
    total                    3.17 M

**Comment by waynebruce0x** [comment]
Does TVL here include borrowed assets? or is it available liquidity (deposits - borrows)

**Comment by stefanofa** [comment]
> Can exported TVL be changed to available liquidity? So the reported borrowed + reported TVL = about 3.2M

Sure, done!

**Comment by llamatester** [comment]
The adapter at projects/folks-finance/index.js exports TVL: 
        
 
 
    borrowed                  675.96 k
    
    total                    3.45 M

**Pull request merged**
