### PR TITLE
Updated PulsarMoney project addresses

### PR DESCRIPTION
**Pull request by astrarizon**
Added one more address for PulsarMoney project

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/pulsar-money: 
        
 
  
    
    
    PromisePoolError: Request failed with status code 502
    Truncated error stack:
        at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
Error while running adapter at projects/pulsar-money: 
        
 
  
    
    
    PromisePoolError: Request failed with status code 502
    Truncated error stack:
        at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
Error while running adapter at projects/pulsar-money: 
        
 
  
    
    
    PromisePoolError: Request failed with status code 502
    Truncated error stack:
        at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by g1nt0ki** [comment]
@astrarizon thanks for the update

**Comment by astrarizon** [comment]
Hello @g1nt0ki ! We are thankful!
Just a minor question, what is the procedure to also update the Logo?

**Comment by astrarizon** [comment]
logo-white-250

@g1nt0ki

**Comment by realdealshaman** [comment]
Hi @astrarizon I can now confirm that the new logo has been added :+1:

**Pull request merged**
