### PR TITLE
Remove EDMX tvl

### PR DESCRIPTION
**Pull request by afiorenza**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@afiorenza why do you want to remove EDMX?

**Comment by afiorenza** [comment]
@g1nt0ki We don't want to display the TVL on defillama right now

**Comment by g1nt0ki** [comment]
@afiorenza Sorry, I am closing this. We have made it a policy to retain protocol listing even when some have sunset or rugged, one of the reasons is, delisting a protocol now would change existing chain tvl chart.

**Comment by afiorenza** [comment]
@g1nt0ki But we don't want to delist EMDX from Defillama. But we want is to not show the TVL chart as it is not relevant for the users.

**Comment by g1nt0ki** [comment]
ah, removing it is not easy with current set-up, are you on discord? can you join here and post a message: https://discord.defillama.com/

**Comment by g1nt0ki** [comment]
we can continue the chat there

**Pull request closed without merging**
