### PR TITLE
Updated bridge contract, revised TVL calculation method.

### PR DESCRIPTION
**Pull request by BingoCarry**
Name (to be shown on DefiLlama):
BridgeM

Twitter Link:
https://twitter.com/BridgeM_io

List of audit links if any:
N/A (we will provide an audit report in the short future.)

Website Link:
https://bridgem.io/

Logo (High resolution, will be shown with rounded borders):
https://drive.google.com/file/d/1_uI3RQzZLB3T5rkwhZmPkEhYRi0I4pJh/view?usp=sharing

Current TVL:
$ 45,890,504

Treasury Addresses (if the protocol has treasury)
Chain:
Manta 

Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
Short Description (to be shown on DefiLlama):
BridgeM is a decentralized interoperability protocol that seamlessly connects Ethereum Layer 2 and Bitcoin Layer 2, facilitating secure and efficient data communication services.

Token address and ticker if any:
https://pacific-explorer.manta.network/address/0x8Bb6CaE3f1CADA07Dd14bA951e02886ea6bBA183

Category (full list at https://defillama.com/categories) *Please choose only one:
Bridge

Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Implementation Details: Briefly describe how the oracle is integrated into your project:
Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
forkedFrom (Does your project originate from another project):
NO

methodology (what is being counted as tvl, how is tvl being calculated):
Calculate $MANTA & $STONE & USDC that locked in BridgeM contract in USD value.

Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/BridgemEthereumLock: 
        
 
  
    
    
    Error: Multicall failed! 
     [chain: ethereum] [fail count: 1] [abi: function balanceOf(address account) view returns (uint256)]  
        target: 0xec901da9c68e90798bbbb74c11406a32a70652c3 params: 0xd6572c7cd671ecf75d920adcd200b00343959600]

**Comment by llamatester** [comment]
The adapter at projects/BridgemEthereumLock exports TVL: 
        
 
 
    ethereum                  30.50 M
    
    total                    30.50 M

**Comment by llamatester** [comment]
The adapter at projects/BridgemManta exports TVL: 
        
 
 
    manta                     37.07 M
    
    total                    37.07 M

**Comment by g1nt0ki** [comment]
@BingoCarry thanks for the PR

**Comment by llamatester** [comment]
The adapter at projects/bridgem exports TVL: 
        
 
 
    manta                     35.51 M
    ethereum                  27.80 M
    
    total                    63.32 M

**Pull request merged**
