### PR TITLE
ithil v2

### PR DESCRIPTION
**Pull request by OxMarco**
Simply an update on the vault addresses, post [audit](https://twitter.com/ithil_protocol/status/1750189056963592665)

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/ithil exports TVL: 
        
 
 
    arbitrum                  12.89 k
    
    total                    12.89 k

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
@OxMarco thanks for the PR but instead of replacing old vaults, can you retain them? it is helpful if we/others try to recreate historical tvl data

**Comment by llamatester** [comment]
The adapter at projects/ithil exports TVL: 
        
 
 
    arbitrum                  13.03 k
    
    total                    13.03 k

**Comment by g1nt0ki** [comment]
@OxMarco thanks for the PR and retaining the old vaults

**Comment by OxMarco** [comment]
thanks for your guidance

**Pull request merged**
