### PR TITLE
Add Stader TVL adapter

### PR DESCRIPTION
**Pull request by ksrakhilesh**
##### Logo: 
image

### CODE REVIEW

**Comment by 0xngmi** [comment]
could you separate tvl by coin/currency?

**Comment by sid99** [comment]
@0xngmi do you mean in the tvl function ? Something like tvlInUst & tvlInLuna ? Or in the tvl in the description ?

**Comment by realdealshaman** [comment]
Having a distinction in the values returned; that show how much of the tvl is luna and how much is ust

**Comment by sid99** [comment]
@realdealshaman Updated the PR, let us know if this works.

**Comment by 0xngmi** [comment]
ty, that works

**Pull request merged**
