### PR TITLE
Add TeddySwap Dex on Cardano

### PR DESCRIPTION
**Pull request by Mercurial**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Treasury Addresses (if the protocol has treasury)
addr1qxy5u2nktp9rg2d43p73luvvutalulwdadfzhg7ljcsftaf9v92a9ja2cmrgw9t0s57jf7kf4cyhzcn40tvvksrst86qqkux99

##### Chain:
Cardano

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

```json
{"id":"teddyswap","symbol":"tedy","name":"TeddySwap"}
```

##### Short Description (to be shown on DefiLlama):

```
TeddySwap, the "coziest stablecoin DEX on Cardano," aims to revolutionize the Cardano DeFi ecosystem with a secure and efficient stablecoin trading platform. A scalable decentralized exchange and automated liquidity provision protocol for Cardano Stablecoins and Derivatives.
```

##### Token address and ticker if any:
```
TICKER: TEDY
Token Policy: f6696363e9196289ef4f2b4bf34bc8acca5352cdc7509647afe6888f54454459
Link: https://cardanoscan.io/token/f6696363e9196289ef4f2b4bf34bc8acca5352cdc7509647afe6888f54454459
```
##### Category (full list at https://defillama.com/categories) *Please choose only one:
[Dexes](https://defillama.com/protocols/Dexes)

##### forkedFrom (Does your project originate from another project):
It is a fork of Spectrum Finance [https://github.com/spectrum-finance](https://github.com/spectrum-finance)

##### methodology (what is being counted as tvl, how is tvl being calculated):

**Indexing Assets in Each Liquidity Pool:** Identify and catalog the various assets held in each liquidity pool. This step involves recording the types and quantities of assets in each pool.

**Calculating TVL for Each Pool:** For each liquidity pool, calculate the Total Value Locked (TVL). This involves assessing the current market value of all the assets in the pool and summing them up to arrive at the pool's TVL.

**Exposing TVL Data via API**: Make the calculated TVL of each pool available through our API. The endpoint for accessing this data is: https://analytics.teddyswap.org/v1/pools/overview?after=0. This API provides real-time TVL data for each pool.

**Summing Individual Pool TVLs for Total TVL**: Aggregate the TVL figures from each individual pool to determine the overall TVL for the platform. This aggregated figure represents the total amount of capital locked across all our liquidity pools.

The TVL Total is in $ADA the Native Token of Cardano

##### Github org/user (Optional, if your code is open source, we can track activity):

https://github.com/teddy-swap

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/teddyswap exports TVL: 
        
 
 
    cardano                   1.50 M
    
    total                    1.50 M

**Comment by g1nt0ki** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters/discussions/432

**Comment by llamatester** [comment]
The adapter at projects/teddyswap exports TVL: 
        
 
 
    cardano                   2.26 M
    
    total                    2.26 M

**Comment by Mercurial** [comment]
> @Mercurial thanks for the PR, can you update code to compute tvl on chain, we often have trouble with api

hey sorry for the late response, I have updated the code to use blockfrost to lookup the ADA in the pool validator (by validator hash)

Let me know if I missed anything, thank you 🙏🏻

**Comment by g1nt0ki** [comment]
@Mercurial thanks for fixing it, will review this soon

**Comment by Mercurial** [comment]
> @Mercurial thanks for fixing it, will review this soon

looking forward to it, let me know if I missed anything!

**Pull request merged**
