### PR TITLE
Added EOS xSat EVM adapter

### PR DESCRIPTION
**Pull request by nsjames**
##### Name (to be shown on DefiLlama):
EOS XSAT EVM

##### Twitter Link:
https://x.com/exsatnetwork

##### Website Link:
https://exsat.network/

##### Logo (High resolution, will be shown with rounded borders):
ep6sQ44w_400x400

##### Current TVL:
$27.45m

##### Chain:
EOS

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): 
`eos`

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): 
1765

##### Short Description (to be shown on DefiLlama):
The amount of BTC that has been bridged over to the EOS network via the xSat BTC EVM. 

##### Token address and ticker if any:
`btc.xsat`
`BTC`

##### Category (full list at https://defillama.com/categories) *Please choose only one:
15 [Cross Chain](https://defillama.com/protocols/Cross%20Chain)

##### methodology (what is being counted as tvl, how is tvl being calculated):
EOS ExSAT EVM TVL is achieved by querying the total available supply from the [btc.xsat] account. This supply fluctuates as users deposit and withdraw funds from the ExSAT EVM.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/exsat-network/contract-of-consensus

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/eos-exsat-evm exports TVL: 
        
 
 
    eos                       27.42 M
    
    total                    27.42 M

**Comment by nsjames** [comment]
Please let me know if there is any additional information that needs to be provided, or if I need to add anything to the `icons` or `server` repos. 

Thanks!

**Comment by g1nt0ki** [comment]
@nsjames thanks for the PR, can you instead return a list of btc addresses with at least 0.001 BTC and compute tvl using `sumTokens` method, also, can you place the address fetcher code here: https://github.com/seancheen/DefiLlama-Adapters/blob/pr/seancheen/12406/projects/helper/bitcoin-book/fetchers.js#L9


the adapter code would be something like this: https://github.com/seancheen/DefiLlama-Adapters/blob/pr/seancheen/12406/projects/lombard/index.js#L13

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
.

**Comment by llamatester** [comment]
The adapter at projects/eos-exsat-evm exports TVL: 
        
 
 
    eos                       26.82 M
    
    total                    26.82 M

**Comment by nsjames** [comment]
@g1nt0ki thanks for the info

I see there's already another implementation of the exsat bridge calculation in fetchers however it's attributing the TVL to `bitcoin` via the `exsat` adapter. It would be preferable to display that TVL on EOS instead as that is where those BTC effectively are now. 

I've modified the adapter to use that same code to attribute the TVL to EOS, but am unsure how you'd like to handle this.

**Comment by g1nt0ki** [comment]
hi @nsjames for bridge protocols, we count the tokens deposited on the source chain, so counting bitcoin on bitcoin chain is the correct approach.

I would also like to mention that, these bridge tvl would not be counted towards either source or destination chain tvl. https://github.com/DefiLlama/DefiLlama-Adapters/discussions/435

**Comment by zackgall** [comment]
@g1nt0ki the exSat Bridge is different than exSat EVM. I believe the confusion lies in the fact that exSat is the bridge operator and also the builders of the exSat EVM dApp on EOS, which is leveraging most of the wrapped Bitcoins generated by the bridge. These use cases for the wrapped BTC will be expanded on EOS, so this won't be the case for long. They need to be looked at separately.

The exSat bridge generates a wrapped token on EOS (using the btc.xsat token contract) that can be comparable to WBTC on ETH (albeit with much less TVL). WBTC is counted as TVL within many defi applications on Ethereum, so we're looking to make this our version of that on EOS. The exSat Bridge generates these tokens, but then the tokens themselves have their own utility within the ecosystem. The btc.xsat token will soon have it's own liquidity pools in EOS defi projects, so it is important that this distinction is made. If the bridge wasn't being operated by the same team as the dApp, then I don't think we'd have this confusion.

Currently, the exSat EVM is the only project leveraging the wrapped Bitcoin, but that won't be the case for long. Also, the BTC (btc.xsat) staked inside the exSat EVM is locked for 28 days in exchange for mining rewards. This should allow it to qualify as EOS TVL.

The best way to think of this would be if the exSat EVM dApp was staking/locking WBTC instead of btc.xsat. Unfortunately, EOS doesn't have WBTC support, so a different bridge app was needed (exSat Bridge) for wrapping/tokenizing BTC on EOS

exSat Bridge is the wrapper/bridge

exSat EVM is the first dApp that uses the wrapped BTC that is generated by the bridge. It won't be the only dApp though and in the future, we would like to see btc.xsat credited as TVL in other DeFi Protocols within the EOS ecosystem such as Defibox (an AMM and lending protocol)

**Comment by g1nt0ki** [comment]
" WBTC is counted as TVL within many defi applications on Ethereum, so we're looking to make this our version of that on EOS. "

if bridged BTC is used in different EOS or exsat defi apps, it would be counted towards their tvl.

But WBTC supply itself is counted only on bitcoin: https://defillama.com/protocol/wbtc (and not counted toward bitcoin chain tvl since it is a bridge)

**Pull request closed without merging**
