### PR TITLE
Add new project

### PR DESCRIPTION
**Pull request by end0cr1ne**
##### methodology (what is being counted as tvl, how is tvl being calculated): The value of the total supply of mintable items.

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Can we count the collateral / tokens locked in your contracts instead of measuring total supplies? At the moment, as far as I understand, it isn't really counting 'TVL'

**Comment by end0cr1ne** [comment]
That's true though for a game I think this makes sense. All of these tokens are minted and burned within the game with no other use case. So any outstanding Gold tokens for instance, though in users wallets, can only be used to craft in-game items thus they are 'pseudo locked'. Besides, there isn't a staking mechanism so I'm not sure how else to calculate things.

**Comment by waynebruce0x** [comment]
Our definition of TVL is total value of funds locked by users into a protocols smart contracts. It could be that your protocol has no TVL, in which case we cant list it. This is the case with quite a lot of gamefi protocols

**Comment by end0cr1ne** [comment]
Ok, I've re-worked it to only include the value locked in the contract from the crafting mechanism.

**Comment by waynebruce0x** [comment]
Hey I merged it but we're getting 0 TVL because MFF isn't on coingecko. Are there any UniV2 LP tokens with MFF in them?  That we can use to derive the price of MFF instead of using coingecko

**Comment by end0cr1ne** [comment]
Yes there's this LP: https://explorer.mainnet.aurora.dev/token/0x3c508FC05C289BA989CF877bb2e3f6e54eF3fc95
Pool: https://www.trisolaris.io/#/swap?inputCurrency=0x5ce9F0B6AFb36135b5ddBF11705cEB65E634A9dC&outputCurrency=0x78B65477bBa78fc11735801D559C386611d07529

Thanks!

**Review by Pencab — COMMENTED** [review]
end0cr1ne:main

**Pull request merged**
