### PR TITLE
Update Shade Protocol

### PR DESCRIPTION
**Pull request by hoomp3**
+ Silk (CDP Stablecoin)
+ ShadeLend (Lending Protocol)
+ stkd-SCRT (Derivative) under Shade Protocol

Renamed folders to remove potential confusion between shadecash.

Associated PRs:
https://github.com/DefiLlama/icons/pull/522
https://github.com/DefiLlama/defillama-server/pull/3425

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/shadeprotocol-derivatives exports TVL: 
        
 
 
    secret                    2.31 M
    
    total                    2.31 M

**Comment by llamatester** [comment]
The adapter at projects/shadeprotocol-lend exports TVL: 
        
 
 
    secret                    7.43 M
    
    total                    7.43 M

**Comment by llamatester** [comment]
The adapter at projects/shadeprotocol-swap exports TVL: 
        
 
 
    secret                    9.66 M
    
    total                    9.66 M

**Comment by llamatester** [comment]
The adapter at projects/shadeprotocol-derivatives exports TVL: 
        
 
 
    secret                    2.30 M
    
    total                    2.30 M

**Comment by llamatester** [comment]
The adapter at projects/shadeprotocol-lend exports TVL: 
        
 
 
    secret                    7.42 M
    
    total                    7.42 M

**Comment by llamatester** [comment]
The adapter at projects/shadeprotocol-silk exports TVL: 
        
 
 
    secret                    3.74 M
    
    total                    3.74 M

**Comment by llamatester** [comment]
The adapter at projects/shadeprotocol-swap exports TVL: 
        
 
 
    secret                    9.65 M
    
    total                    9.65 M

**Comment by g1nt0ki** [comment]
> I know you guys don't accept fetch adapters anymore, but Secret Network uses encryption for querying the data so I'd have to add in all these https://github.com/scrtlabs/secret.js/blob/87b1f3e88dfeb9f247f3f0885e0db76d034495ff/src/query/compute.ts#L155 and https://github.com/scrtlabs/secret.js/blob/master/src/encryption.ts in a standalone adapter. Not sure if it'd be worth re-implementing here.

I have merged it, hoping that api is stable

**Pull request merged**
