### PR TITLE
Added EclipseFi TVL Adapter

### PR DESCRIPTION
**Pull request by shawayush**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### List of audit links if any: https://github.com/ResonanceCybersecurity/audits/blob/main/CosmWasm%20Smart%20Contract%20Audits/Audit_Report_ECLP-EQN_FINAL_21.pdf
https://github.com/oak-security/audit-reports/tree/main/Eclipse%20Fi

##### Logo (High resolution, will be shown with rounded borders):
image

##### Short Description (to be shown on DefiLlama):
EclipseFi dismantling predatory systems to build a launch and DeFi hub for sustainable growth—aligning and empowering communities and innovative builders to thrive together.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/eclipse exports TVL: 
        
 
 
    neutron                   1.06 M
    
    total                    1.06 M

**Comment by llamatester** [comment]
The adapter at projects/eclipse exports TVL: 
        
 
 
    neutron                   626.65 k
    neutron-pool2             443.60 k
    pool2                     443.60 k
    neutron-staking           42.81 k
    staking                   42.81 k
    
    total                    626.66 k

**Comment by g1nt0ki** [comment]
@shawayush thanks for the PR, I split it based on this: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by AronTurner** [comment]
@g1nt0ki could we have the total TVL added together by default? Right now its only showing 1 vault by default unless you use the switches in the page

**Comment by g1nt0ki** [comment]
only option atm is setting it via url params: https://defillama.com/protocol/eclipsefi?pool2=true&staking=true

**Comment by AronTurner** [comment]
Its just not a good reflection of the overall TVL, as it only shows a partial amount on the main neutron page: https://defillama.com/chain/Neutron

**Comment by g1nt0ki** [comment]
> Its just not a good reflection of the overall TVL, as it only shows a partial amount on the main neutron page: https://defillama.com/chain/Neutron

users need to enable staking/pool2 to see those tvl, sorry, but we have the same rule for all protocols

**Comment by AronTurner** [comment]
Sorry I dont understand, why were they seperated in the first place? The way it was submitted calculated the TVL correctly as its the protocols total TVL. Do we need to adjust our adapter to make it a collated total?

**Comment by AronTurner** [comment]
Yeah that makes sense for the staking, but with the LP pool it's not paired with a governance token but rather a pegged liquid token, so could that be adjusted to be included in the total?

**Comment by g1nt0ki** [comment]
@AronTurner but the value backing the liquid token is already included in tvl right?

**Comment by AronTurner** [comment]
Not quite, we have the single sided which is shown by default, but the lp staking is relegated to pool2 which requires a manual switch to be included, but technically it should be included in the total as both sides are not protocol governance

That would total around ~$1.2M at the time of writing, whereas now its currently a fair bit less than that: https://defillama.com/chain/Neutron

**Comment by AronTurner** [comment]
Just following up on this @g1nt0ki

**Comment by AronTurner** [comment]
Sure let's go with that for the pool2

**Pull request merged**
