### PR TITLE
Add DogeDollar

### PR DESCRIPTION
**Pull request by Centipede5**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/dogedollar exports TVL: 
        
 
 
    dogechain                 1.58 k
    
    total                    1.58 k

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
can you update code to below

    const { sumTokensExport, nullAddress, } = require("../helper/unwrapLPs");

    const DJED_ADDR = '0xA99ef299CdA10AC4Ec974370778fbd27Cfb5CF61'

    module.exports = {
      methodology: 'finds the DOGE balance of the DJED instance backing the stablecoin, aswell as the fallback stablecoin balance',
      start: 14576300,
      dogechain: {
        tvl: sumTokensExport({
          tokensAndOwners: [
            [nullAddress, DJED_ADDR],
          ]
        }),
      }
    };

**Comment by Centipede5** [comment]
> can you update code to below
> 
> ```
> const { sumTokensExport, nullAddress, } = require("../helper/unwrapLPs");
> 
> const DJED_ADDR = '0xA99ef299CdA10AC4Ec974370778fbd27Cfb5CF61'
> 
> module.exports = {
>   methodology: 'finds the DOGE balance of the DJED instance backing the stablecoin, aswell as the fallback stablecoin balance',
>   start: 14576300,
>   dogechain: {
>     tvl: sumTokensExport({
>       tokensAndOwners: [
>         [nullAddress, DJED_ADDR],
>       ]
>     }),
>   }
> }; 
> ```

There is also a fallback stablecoin that can be held by the protocol, but this needs to be pulled manually as it is not yet set (all other stablecoins on dogechain are depegged).

**Comment by llamatester** [comment]
The adapter at projects/dogedollar exports TVL: 
        
 
 
    dogechain                 1.06 k
    
    total                    1.06 k

**Comment by Centipede5** [comment]
i can add th

> > can you update code to below
> > ```
> > const { sumTokensExport, nullAddress, } = require("../helper/unwrapLPs");
> > 
> > const DJED_ADDR = '0xA99ef299CdA10AC4Ec974370778fbd27Cfb5CF61'
> > 
> > module.exports = {
> >   methodology: 'finds the DOGE balance of the DJED instance backing the stablecoin, aswell as the fallback stablecoin balance',
> >   start: 14576300,
> >   dogechain: {
> >     tvl: sumTokensExport({
> >       tokensAndOwners: [
> >         [nullAddress, DJED_ADDR],
> >       ]
> >     }),
> >   }
> > }; 
> > ```
> 
> There is also a fallback stablecoin that can be held by the protocol, but this needs to be pulled manually as it is not yet set (all other stablecoins on dogechain are depegged).

I can update the project after we have sorted that out

**Comment by g1nt0ki** [comment]
@Centipede5 thanks for changing it, can you put up a new PR when backup stablecoin is ready?

**Pull request merged**
