### PR TITLE
Add Mimo Protocol liquidations

### PR DESCRIPTION
**Pull request by m19**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

Hi all, we are on DefiLama already with our protocol: https://defillama.com/protocol/mimo-protocol

This PR is for liquidations

##### Name (to be shown on DefiLlama):

Mimo Protocol

##### Twitter Link:

https://twitter.com/mimo_labs

Question: can we change the Twitter handle on https://defillama.com/protocol/mimo-protocol to @mimo_labs too instead of @mimodefi

##### Website Link:

https://mimo.capital/

---

Current output of script:

```
Liquidable positions:
┌─────────┬─────────┬───────────────────┬───────────────────────┬────────────────────────┐
│ (index) │ symbol  │ percentLiquidable │ totalLiquidableTokens │   totalLiquidableUSD   │
├─────────┼─────────┼───────────────────┼───────────────────────┼────────────────────────┤
│    0    │ 'USDC'  │       0.02        │        563.52         │      '563.524124'      │
│    1    │ 'WETH'  │         0         │         0.29          │  '471.9200710486341'   │
│    2    │ 'WBTC'  │         0         │           0           │     '92.64789024'      │
│    3    │  'ETH'  │         0         │           0           │  '0.1543280445336411'  │
│    4    │ 'WFTM'  │         0         │         0.04          │ '0.023369547115752554' │
│    5    │ 'Total' │        '-'        │          '-'          │        '1.13 k'        │
└─────────┴─────────┴───────────────────┴───────────────────────┴────────────────────────┘
```

### CODE REVIEW

**Comment by 0xStrobe** [comment]
Hi, thanks for the contribution. Will look into the implementation in detail soon but is it correct that currently only ~1k USD of assets are used as collateral on Mimo?

**Comment by m19** [comment]
> Hi, thanks for the contribution. Will look into the implementation in detail soon but is it correct that currently only ~1k USD of assets are used as collateral on Mimo?

Hi @0xStrobe sorry for the late reply. Shouldn't the output mean that there's currently 1.13k worth of assets for liquidation? Our TVL is $20m+ accross all chains

**Comment by 0xStrobe** [comment]
Hi @m19, the output means the amount of assets that are potentially subject to getting liquidated, which means the collaterals used in current open positions. It doesn't mean how many assets can be right now liquidated in a mev liquidator way, but how many assets are subject to liquidation *if* the asset price has fallen to a certain level.

**Comment by 0xStrobe** [comment]
Hi @m19, thanks for the reply. I'll have a closer look into the code. I asked because it's unusual for a CDP protocol with $20m TVL to have only $1k open positions on it. Is there a TLDR on how the protocol works you could point me to to learn more about how the protocol works?

**Comment by m19** [comment]
> Hi @m19, thanks for the reply. I asked because it's unusual for a CDP protocol with $20m TVL to have only $1k open positions on it. Is there a TLDR you could point me to to learn more about how the protocol works?

It is weird to only have $1k in current liquidatable positions at the current price, is that what you mean? I don't think that's weird, liquidations are expected to happen as soon as possible. And as you can see in the output significant liquidations will happen when the prices drop further. 6900 ETH alone ($11m) is avail for liquidation at $607.96-683.95 as per the DefiLama script.

Liquidations are supposed to happen very fast as it's free money for the liquidator. The only positions that are not being liquidated are typically on mainnet Ethereum where the gas cost is too high: 

You can check https://app.mimo.capital/liquidation and switch between networks.

**Comment by 0xStrobe** [comment]
Hi again, @m19. If you mean "liquidations are expected to happen as soon as possible" then you have misunderstood what this dashboard is for as I have suspected. Also no need to be combative and I was not questioning the legitimacy of your protocol, I'm having trouble to understand what Mimo being around for a long time has to do with this PR.

This dashboard is for checking liquidation levels - as in, if I opened a position with ETH collaterals worth $1000 but I only borrowed $100, then at what ETH price would I be liquidated in the future? It would be when ETH price fell to 0.1x of what it is today, so my liquidation price would be like ETH at $160 with size of liquidation size of $100. This is of course simplified as you usually get liquidated before it, so the protocol's configuration will need to be taken into account as well. If you are a CDP, usually 100% of your TVL is liquidatable, unlike lending markets where you can just provide funds to lend out without borrowing anything, so that you earn a % from your deposits.

This dashboard is not for checking how much positions can be liquidated right now up for MEVs to grab, or how much bad debt there is (that is unprofitable to get liquidated by liquidators).

**Comment by 0xStrobe** [comment]
BTW you can check out Liquity or Maker's adapters for reference.

https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/liquidations/maker/index.ts
https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/liquidations/liquity/index.ts

**Pull request merged**
