### PR TITLE
Update Quasar

### PR DESCRIPTION
**Pull request by arhamchordia**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Quasar Vaults

##### Twitter Link:
https://twitter.com/QuasarFi

##### Website Link:
Product : https://app.quasar.fi/
Website : https://www.quasar.fi/

##### Logo (High resolution, will be shown with rounded borders):
https://github.com/cosmos/chain-registry/blob/master/quasar/images/quasar.png

##### Current TVL:
$ 8.11M

##### Chain:
Osmosis, Quasar

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
quasar-2

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/quasar: 
        
 
  
    
    
    Error: Invalid balance: NaN
    Truncated error stack:
        at isValidNumber (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:119:19)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:320:16
        at Array.forEach (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:314:28)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:327:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:55:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:149:9
        at async Promise.all (index 0)

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
hi @arhamchordia 
whats the reason for moving from on chain to api based tvl computation.

`getConfig` caches the response, it is fine for getting vault list, but not for actual tvl, as if the api goes down/goes behind firewall and is unreachable, we will show stale/incorrect tvl numbers

**Comment by g1nt0ki** [comment]
> > hi @arhamchordia whats the reason for moving from on chain to api based tvl computation.
> 
> As we have moved to an outpost model. Our contracts are deployed on Osmosis for now. So, all this metrics are being fetched from api where this is collected from Osmosis on chain data.

hi @arhamchordia if the data/logic is similar between on chain & the api, we prefer the api, reasons: https://github.com/DefiLlama/DefiLlama-Adapters/discussions/432

**Comment by magiodev** [comment]
> > > hi @arhamchordia whats the reason for moving from on chain to api based tvl computation.
> > 
> > 
> > As we have moved to an outpost model. Our contracts are deployed on Osmosis for now. So, all this metrics are being fetched from api where this is collected from Osmosis on chain data.
> 
> hi @arhamchordia if the data/logic is similar between on chain & the api, we prefer the api, reasons: #432

Hey @g1nt0ki, I'm taking over this PR. I understand your concerns about SLA and outages, as well as the centralized nature of the data availability. I could calculate the total USD amount of each vault and for the entire Quasar protocol by performing the same computation we do on the API side. This would essentially involve taking all the vault addresses, iterating over them, querying the total assets inside, and querying i.e. CoinGecko for each denomination to convert coin amounts to USD.

This is kind of easy, but it would come with a trade-off in performance, as each time we would spawn a lot of HTTP calls. Should we take this into account, or can we assume there is a caching system in place?

**Comment by g1nt0ki** [comment]
hi @magiodev 
So far, the amount of http calls the quasar adapter makes is not an issue, yes, we do cache token prices in our server, both to speed up tvl calculation and reduce # calls to coingecko

**Pull request closed without merging**
