### PR TITLE
fix: historical aquarius tvl data

### PR DESCRIPTION
**Pull request by dry-cake**
**NOTE**

- Add start date fetch
- Optimize data fetching

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/aqua-network exports TVL: 
        
 
 
    stellar                   595.37 k
    
    total                    595.37 k

**Comment by dry-cake** [comment]
I'm also posted PR to llama-server with cmc & gecko id
https://github.com/DefiLlama/defillama-server/pull/7836

And could u pls explain, what is flag `misrepresentedTokens: true`?

**Comment by g1nt0ki** [comment]
hi, it is marked as misrepresetedTokens as we dont have token breakdown

**Comment by g1nt0ki** [comment]
hi, I refactored the adapter a bit and ran the refill script, should be visible in the webpage in 2-3 hours

**Comment by dry-cake** [comment]
@g1nt0ki I can't see all TVL history, data is available only from 21 August, but our api contains data from `2024-07-25`.
Is there any problem with code, or with adapter deploy?
image

Thx in advance.

**Pull request closed without merging**
