### PR TITLE
Add Coffin.Meme

### PR DESCRIPTION
**Pull request by SaberDoTcodeR**
##### Name (to be shown on DefiLlama):

* Coffin.Meme

##### Website Link:

* https://coffin.meme

##### Logo (High resolution, will be shown with rounded borders):

* https://coffin.meme/coffin.svg
##### Current TVL:

* 23 k $

##### Treasury Addresses (if the protocol has treasury)

* EQBozwKVDya9IL3Kw4mR5AQph4yo15EuMdyX8nLljeaUxrpM

##### Chain:

* TON Blockchain

##### Short Description (to be shown on DefiLlama):

* Coffin.Meme is a DeFi Platform powered by EVAA Lending Smart contracts to short-sell memecoins and earn money. 

##### Category (full list at https://defillama.com/categories) *Please choose only one:

* [Lending](https://defillama.com/protocols/Lending)

##### forkedFrom (Does your project originate from another project):

* Evaa Protocol

##### methodology (what is being counted as tvl, how is tvl being calculated):

* Balance of Treasury Smart contract

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/coffin-meme exports TVL: 
        
 
 
    ton                       22.97 k
    
    total                    22.97 k

**Comment by llamatester** [comment]
The adapter at projects/coffin-meme exports TVL: 
        
 
 
    ton                       2.41 k
    
    total                    2.41 k

**Comment by SaberDoTcodeR** [comment]
Hi @g1nt0ki, Coffin is a platform for shorting memecoint, with this change memecoins won't be counted as TVL.

**Comment by g1nt0ki** [comment]
no, `onlyWhitelistedTokens` flag is false by default, my change ensures that gas token in included in tvl

**Comment by SaberDoTcodeR** [comment]
`tokens: [ADDRESSES.null]` you added this, which only count the TON native token and not USDT and memecoins

**Pull request merged**
