### PR TITLE
add new Neutral.trade vaults

### PR DESCRIPTION
**Pull request by NeutralTrade**

### CODE REVIEW

**Comment by llamabutler** [comment]
The adapter at projects/neutral-trade exports TVL: 
        
 
 
    solana                    21.63 M
    
    total                    21.63 M

**Comment by NeutralTrade** [comment]
@g1nt0ki see my response to your comment here https://github.com/DefiLlama/DefiLlama-Adapters/pull/12674/files#r1896587757 there was a mix up between vault program ID and vault address I think.

Thanks for the big help 🙏

**Comment by llamabutler** [comment]
The adapter at projects/neutral-trade exports TVL: 
        
 
 
    solana                    20.60 M
    
    total                    20.60 M

**Comment by NeutralTrade** [comment]
it seems to be aligned with our real TVL now.

**Pull request merged**
