### PR TITLE
Added additional account - vigorstaking

### PR DESCRIPTION
**Pull request by yogevmas**
vigorstaking account is also part of Vigor's TVL.

**NOTE**

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/vigor: 
        
 
  
    
    
    Error: Invalid balance: NaN
    Truncated error stack:
        at isValidNumber (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:119:19)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:314:16
        at Array.forEach (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:308:28)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:321:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:146:9
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
Error while running adapter at projects/vigor: 
        
 
  
    
    
    Error: Invalid balance: NaN
    Truncated error stack:
        at isValidNumber (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:119:19)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:314:16
        at Array.forEach (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:308:28)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:321:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:146:9
        at async Promise.all (index 0)

**Review by yogevmas — COMMENTED** [review]
Bug fix

**Comment by llamatester** [comment]
The adapter at projects/vigor exports TVL: 
        
 
 
    eos                       611.63 k
    
    total                    611.63 k

**Comment by g1nt0ki** [comment]
@yogevmas thanks for the PR

**Pull request merged**
