### PR TITLE
Add Poseidollar Protocol

### PR DESCRIPTION
**Pull request by poseidollar**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Logo (High resolution, will be shown with rounded borders):
PDO logo

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
poseidollar , poseidollar-shares

##### Short Description (to be shown on DefiLlama):
Poseidollar - the first algorithmic stablecoin pegged to $USDC running on the Sui Network.

##### Token address and ticker if any:
0x4fc3949a4a8fe3ad9c75cec9724ff2b2d8520506b6129c9d8f0fcc2a1e4a8880::pdo::PDO, 0x3c1227010835ecf9cb8f2bf9993aa9378bb951f0b3a098de6f0ee20385e01c4a::psh::PSH

##### forkedFrom (Does your project originate from another project):
Basis Cash

### CODE REVIEW

**Comment by poseidollar** [comment]
Update Category to Algo-Stables

**Comment by g1nt0ki** [comment]
@poseidollar thanks for the PR, but can you refactor the code a bit.  Your protocol is similar to Tomb, so we can count only the staked non protocol tokens as tvl, staked LP as pool2 and staked own token  (like PSH) under staking: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
.

**Comment by poseidollar** [comment]
@g1nt0ki Sorry for late update, we was removed TVL from expired farming.
Btw, it seem TVL for SCB maybe take wrong price, please check it in production

```
--- sui ---
SUI                       33.60 k
USDC                      7.44 k
SCB                       1.2391374158849187e-9 <==== it seem wrong
Total: 41.03 k 

--- tvl ---
SUI                       33.59 k
USDC                      7.44 k
Total: 41.03 k 

------ TVL ------
sui                       41.03 k

total                    41.03 k
```

**Comment by llamatester** [comment]
The adapter at projects/poseidollar exports TVL: 
        
 
 
    sui                       21.96 k
    
    total                    21.96 k

**Comment by g1nt0ki** [comment]
@poseidollar sorry, will review this soon

**Pull request merged**
