### PR TITLE
feat: add polynomial liquidity layer tvl

### PR DESCRIPTION
**Pull request by Aniket965**
##### Name (to be shown on DefiLlama):
Polynomial

##### Chain:
Polynomial

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/polynomial-liquidity-layer exports TVL: 
        
 
 
    polynomial                1.84 M
    
    total                    1.84 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
what is this product? what are you counting as tvl here? are you counting all bridged tokens as tvl?

**Comment by Aniket965** [comment]
Hey @g1nt0ki this is our liquidity layer, (which is lp side of our trade product) it is total of amount staked by each account currently. not the bridged tvl

**Comment by g1nt0ki** [comment]
> Hey @g1nt0ki this is our liquidity layer, (which is lp side of our trade product) it is total of amount staked by each account currently. not the bridged tvl

can we compute this on chain?

**Comment by Aniket965** [comment]
we can compute this off chain but this will keep on changing as we add collaterals to deposit in which will require us to make changes to this repo quite often @g1nt0ki and the speed of computing will slow down as we add more collaterals

**Comment by g1nt0ki** [comment]
yes, but at the moment it is complete blackbox, we have no idea what is counted towards tvl, if it is the right methodology or how to fix it if the api goes down

**Comment by llamatester** [comment]
The adapter at projects/polynomial-liquidity-layer exports TVL: 
        
 
 
    polynomial                0
    
    total                    0

**Comment by Aniket965** [comment]
Hey @g1nt0ki i found a easier way to calc just by having balances of tokens on the contract, i used same method as other projects where using am i missing something its not showing balance

https://polynomialscan.io/address/0xc133983D6d9140923b5eaE52664221d9099cf119 this contract have balances

**Comment by llamatester** [comment]
The adapter at projects/polynomial-liquidity-layer exports TVL: 
        
 
 
    polynomial                1.95 M
    
    total                    1.95 M

**Comment by g1nt0ki** [comment]
@Aniket965 thanks for the update. We didnt have the token mapping, I fixed it.

**Pull request merged**
