### PR TITLE
Add MuggleLink (Web3 Freelancer Service) on TON blockchain

### PR DESCRIPTION
**Pull request by shawnmuggle**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

MuggleLink

##### Twitter Link:

https://x.com/mugglelink

##### Website Link:

https://muggle.link/

##### Logo (High resolution, will be shown with rounded borders):

https://drive.google.com/drive/folders/1BQsyd55O9ynhjCSW8UFYc1qiGjrpEnuQ
logo_400x400

##### Current TVL:

--- tvl ---
TON                       1.47 k
USDT                      81
Total: 1.55 k 

##### Chain:

TON

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

NA. Not listed.

##### Short Description (to be shown on DefiLlama):

MuggleLink is a Web3 Freelance Service Marketplace. Our mission is to link Muggles and make the world work together by crypto. Channel: https://t.me/MuggleLinkNews

##### Token address and ticker if any:
NA

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Services

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:

NA. we do not use oracle

##### forkedFrom (Does your project originate from another project):

we are original, not forked from any project.

##### methodology (what is being counted as tvl, how is tvl being calculated):

Counts MuggleLink address balance as TVL.

##### Github org/user (Optional, if your code is open source, we can track activity):

https://github.com/mugglelink

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/mugglelink exports TVL: 
        
 
 
    ton                       1.56 k
    
    total                    1.56 k

**Comment by g1nt0ki** [comment]
@shawnmuggle thanks for the PR

**Comment by shawnmuggle** [comment]
Thank you [g1nt0ki](https://github.com/g1nt0ki)

**Comment by shawnmuggle** [comment]
Hi [g1nt0ki](https://github.com/g1nt0ki), thanks for the merge.
The logo is not showing correctly. 
https://defillama.com/protocol/mugglelink

**Pull request merged**
