### PR TITLE
fix horizondex TVL

### PR DESCRIPTION
**Pull request by HorizonDex**
transform balances to linea core assets to fix TVL

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/horizondex exports TVL: 
        
 
 
    linea                     182.01 k
    
    total                    182.01 k

**Comment by g1nt0ki** [comment]
hi @HorizonDex , I thought horizondex is not amm,  `transformDexBalances` works only for amm

**Comment by g1nt0ki** [comment]
but I see that lot of tvl comes from BUSD, `0x7d43aabc515c356145049227cee54b608342c0ad` is there any way to verify that this is bridged, if so we can price this token and it should fix most of your problem?

**Comment by HorizonDex** [comment]
> hi @HorizonDex , I thought horizondex is not amm, `transformDexBalances` works only for amm

Hi @g1nt0ki, ye, sorry, didnt check `transformDexBalances` implementation well
As for bridged tokens, you can check official Celer Bridge post with bridged tokens addresses:
https://twitter.com/CelerNetwork/status/1681513856756219905?s=20

**Comment by g1nt0ki** [comment]
> > hi @HorizonDex , I thought horizondex is not amm, `transformDexBalances` works only for amm
> 
> Hi @g1nt0ki, ye, sorry, didnt check `transformDexBalances` implementation well As for bridged tokens, you can check official Celer Bridge post with bridged tokens addresses: https://twitter.com/CelerNetwork/status/1681513856756219905?s=20 https://blog.celer.network/2023/07/18/celer-announces-cbridge-bridging-support-for-the-linea-mainnet/
> Screenshot 2023-07-21 at 10 07 53

thanks for the info, I have fixed it here: https://github.com/DefiLlama/defillama-server/commit/19c34dc9f537a96c0168ae0ed2e5c6819e4f57ff

**Pull request closed without merging**
