### PR TITLE
ignore errors when bulk quering contract states

### PR DESCRIPTION
**Pull request by ivivanov**
Resolves the stucked TVL on NolusProtocol

### CODE REVIEW

**Comment by ivivanov** [comment]
In case of Nolus - no. 
In case someone else decides to use queryManyContracts function in future it could lead to unexpected behavior.

I could modify queryManyContracts to return the promise pool and the caller of the function to decides if he is going to take additional actions upon error/s and how to use the results

**Comment by g1nt0ki** [comment]
but even in the case of nolus, the rpc is down for some reason, then suddenly wont you get 0 tvl?

**Comment by g1nt0ki** [comment]
ah, it might crash in this step ? `totalLpp += Number(v.balance.amount)`

**Comment by g1nt0ki** [comment]
added `permitFailure`  flag : https://github.com/DefiLlama/DefiLlama-Adapters/commit/a78ef31d93f6b1cdb757835259995ba4da2451f2

**Comment by ivivanov** [comment]
Cool, that will work perfectly fine. Thank you!

**Pull request closed without merging**
