### PR TITLE
Added new project reference WeldFinance

### PR DESCRIPTION
**Pull request by AgrawalAshishS**
This is sub-project of KnitFinance.

Twitter Link: https://twitter.com/KnitFinance
List of audit links if any: https://www.certik.com/projects/knitfinance
Website Link:https://knit.finance
Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

knitlogo

Current TVL:$1012.11
Chain:
KAVA

Short Description (to be shown on DefiLlama): Liquid stacking protocol for all the assets produced by Knit finance and some other generic assets.
MasterChef address over KAVA : https://explorer.kava.io/address/0xAbF3edbDf79dAfBBd9AaDBe2efEC078E557762D7
Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:

Staking
Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):custom
forkedFrom (Does your project originate from another project):no
methodology (what is being counted as tvl, how is tvl being calculated):On destination chain,Sum of value of all assets, where as value of asset is calculated as : total tokens in the chain multiplied by last traded price

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/weldfinance exports TVL: 
        
 
 
    kava                      0
    
    total                    0

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
Can you please change the adapter to compute tvl on chain, or I can do it if your provide contract/token addresses

In case you missed this comment: https://github.com/DefiLlama/DefiLlama-Adapters/pull/4496#issuecomment-1300484030

**Comment by AgrawalAshishS** [comment]
> Can you please change the adapter to compute tvl on chain, or I can do it if your provide contract/token addresses
> 
> In case you missed this comment: [#4496 (comment)](https://github.com/DefiLlama/DefiLlama-Adapters/pull/4496#issuecomment-1300484030)

Our master chef contract on KAVA is - 0xAbF3edbDf79dAfBBd9AaDBe2efEC078E557762D7
Here are token address that we have made available for stack

'0xfA9343C3897324496A05fC75abeD6bAC29f8A40f':'USDC'
'0x5C23409ed30f8Ec851cb9c543BbC7AA22F820403':'kETH',
'0xBB2EcE2BBCD591867F9F994bfDfEfd563e2CEDc7':'kBTC',
'0x72F7CB3e98b34106e5B5801F3be510F6Da8fea6D':'kLTC',
'0x362cbbe5f4c3178DbCe858F3544b653Fc00B8B0d':'kADA',
'0x8c765a721301BB4B973512c1197F778b9ABaDF20':'kMATIC',
'0xFbbbCdf97e021bCadD93DB8Dc4Afafa0814c376E':'kAVAX',
'0x84d600ef31246C4574Ea8A07C126228eC57FAEb7':'kIOST',
'0x19D5E7D84fE8fc4AfdFE4764C1d7d07Fb2182435':'kDASH',
'0x8bE6757129c895E05dee403DD1295682a3fE77F1':'kXRP',
'0x543374C96196Df7B021889541a66ce9c9105Ee3A':'kXLM',
'0x1e2e5CcB972C3BB08D49d6d435eE567eef9e6629':'kDOGE',
'0x0f3F5cfA49b7C752A721d72A17A745d0228F940A':'kBCH',
'0x1bcC64Fbb764ccFb25f946d900Cfb4618F7F9CFE':'kZEC',
'0x16FE41843d3CA657bbFD28e944532f5aAE376d69':'kBSV',
'0xF3989164829dF113f8806af778cD101b499Fc554':'kFRONT',
'0xfb0E0E53Bd9b9D067FE5D2B0e116256EB77df5D4':'kFTM',
'0x087665054b3E9fE96d4D289ff2Fb1CB5397D5AbC':'kLOOM',
'0xa0EEDa2e3075092d66384fe8c91A1Da4bcA21788':'KFT',
'0x58B95953bF04B89C9BBe3D3B1afE0fCB11B73e14':'kALGO',
'0x916834A4C04807A68B5e0A23e44A14e92F4B3Ca0':'kOGN',
'0xEE0Ed1EA60652bD36f3eaAA54248FF742f8E4311':'kKNC',
'0xEA616011E5AC9a5b91e22CaC59b4eC6f562b83f9':'kBRISE',
'0xDD4005B3687f4441c396377c457bED9f8E016415':'kNIN',
'0x31f4099BC3867C167029f7e9eC3CD70E805C9438':'kPLTO',
'0x778bed24D490d5802fa2F325294Eca2191B73Cf7':'kAQA',
'0x410e72a391052B9838573CE603c117B3FE80BEB4':'kPEA',
'0x0b6ada716BE4C41fA8a223d17EA2c39a0E154E89':'kSHIB',


If you can guide to me an example of similar Dapp configuration, I will work to copy it.

**Comment by g1nt0ki** [comment]
@AgrawalAshishS code would be something like:

    const { masterchefExports, } = require("../helper/unknownTokens")

    module.exports = masterchefExports({
      chain: 'kava',
      useDefaultCoreAssets: true,
      masterchef: '0xAbF3edbDf79dAfBBd9AaDBe2efEC078E557762D7',
      nativeToken: '0xa0EEDa2e3075092d66384fe8c91A1Da4bcA21788',
    })
    
    
  Do you have your own website? I dont see a website for weld finance not staking option on knit finance, can you also please check with team for bridge contract details for knit listing

**Comment by llamatester** [comment]
The adapter at projects/weldfinance exports TVL: 
        
 
 
    kava-pool2                0
    kava-staking              0
    kava                      1.01 k
    pool2                     0
    staking                   0
    
    total                    1.01 k

**Comment by llamatester** [comment]
The adapter at projects/weldfinance exports TVL: 
        
 
 
    kava-pool2                0
    kava-staking              0
    kava                      1.01 k
    pool2                     0
    staking                   0
    
    total                    1.01 k

**Comment by AgrawalAshishS** [comment]
> @AgrawalAshishS code would be something like:
> 
> ```
> const { masterchefExports, } = require("../helper/unknownTokens")
> 
> module.exports = masterchefExports({
>   chain: 'kava',
>   useDefaultCoreAssets: true,
>   masterchef: '0xAbF3edbDf79dAfBBd9AaDBe2efEC078E557762D7',
>   nativeToken: '0xa0EEDa2e3075092d66384fe8c91A1Da4bcA21788',
> })
> ```
> 
> Do you have your own website? I dont see a website for weld finance not staking option on knit finance, can you also please check with team for bridge contract details for knit listing


Required code changes are pushed to the branch.
This is still in Beta and public website work is still in progress.

For Knit, we are running bridge using Fireblocks and its callback and withdrawal system. Due to this, we don't need any contract for bridging. Stacking on Knit -https://app.knit.finance/staking is there as initial. Right now our TVL calculated based on information shared in Knit issue chain.

**Comment by AgrawalAshishS** [comment]
Any chance to get this merged today?

**Comment by g1nt0ki** [comment]
> Any chance to get this merged today?

dont think we can list till your website is up, put a comment here with the website once it is ready and I will merge this PR

**Comment by AgrawalAshishS** [comment]
Changes are pushed to branch in pull request, can you please merge it.

Please do share if any concerns related to weld finance.

**Comment by g1nt0ki** [comment]
@AgrawalAshishS I am still very confused about your product, think I have made my concerns very clear. I can see the change sin the PR

If your product is not live, how do you expect us to list it?
If fireblocks is custodying the funds in source chain, sorry you have 0 tvl for knit

**Comment by AgrawalAshishS** [comment]
We are similar to https://defillama.com/protocol/wbtc in terms of TVL.
Their methodology "TVL for WBTC consists of the BTC deposits in custody
that were used to mint WBTC" - is same as us, we too are keeping custody of
source token to mint. Our protocol is already live and transactions are
happening on it. I am facing some issues with KAVA that we are fixing right
now.

Can we have a Telegram group formed for the same - where the appropriate
person can answer quickly and more accurately?

**Comment by g1nt0ki** [comment]
@AgrawalAshishS if you post you/your team member's telegram handle, I can dm. Or one of you can hop onto our discord channel and we can continue the discussion there.

WBTC provides list of custodian addresses so anyone can verify proof of assets, I am asking the same of you. Also, they are not counting the tokens on both source and dest chain.

**Comment by AgrawalAshishS** [comment]
Hi can you please join TG https://t.me/+11qhGImIv5JhNzU1

**Pull request merged**
