### PR TITLE
feat(projects): add jiblend protocol

### PR DESCRIPTION
**Pull request by jiblendxyz**
##### Short Description (to be shown on DefiLlama): 
JIBLEND is a decentralized finance (DeFi) lending protocol allows users to lend and borrow various crypto assets in a secure and decentralized manner. Our platform aims to provide users with a user-friendly interface, competitive interest rates, and a diverse range of supported assets.

##### methodology (what is being counted as tvl, how is tvl being calculated): Counts the tokens locked in the contracts to be used as collateral to borrow or to earn yield

Fees: Interest paid by borrowers
Revenue: Percentage of interest going to treasury

##### Github org/user (Optional, if your code is open source, we can track activity): https://github.com/jiblend

### CODE REVIEW

**Comment by jiblendxyz** [comment]
We have a question, is it possible to track JBC token (native token) while we're waiting for Coingecko ID? Can we get JBC price from https://api.coinstore.com/api/v1/ticker/price;symbol=JBCUSDT or DEX like Jibswap? https://api.jibswap.com/api/v1/jbc_price/

**Comment by llamatester** [comment]
The adapter at projects/jiblend exports TVL: 
        
 
 
    jbc                       9.23 k
    jbc-borrowed              28.954847
    borrowed                  28.954847
    
    total                    9.23 k

**Comment by realdealshaman** [comment]
@jiblendxyz hi, are there any docs or anything in your github that indicates that/how Supra is being used? 

the SimplePriceOracle, is this your own internal oracle?

**Comment by jiblendxyz** [comment]
hi @realdealshaman,

Our comptroller: [0x603122Cdd36abCD164e448e1f3fbd33730edf35a](https://exp-l1.jibchain.net/address/0x603122Cdd36abCD164e448e1f3fbd33730edf35a) is using [0x89661591d76d93a86b6fe6dc464275581a0fd005](https://exp-l1.jibchain.net/address/0x89661591D76D93a86B6Fe6DC464275581a0FD005) for price oracle

the price oracle contract is provide price feed of 2 types.
- JBC price that we feed at our end. (because no oracle provider support this token)
- The rest of tokens (USDC, USDT, ETH, OP, BNB, BTCB, ARB) is provided by Supra.

Supra oracle address is located at [https://supraoracles.com/docs/data-feeds/pull-model/networks](https://supraoracles.com/docs/data-feeds/pull-model/networks) is [0x2FA6DbFe4291136Cf272E1A3294362b6651e8517](https://exp-l1.jibchain.net/address/0x2FA6DbFe4291136Cf272E1A3294362b6651e8517?tab=contract)

Supra storage address is [0xD02cc7a670047b6b012556A88e275c685d25e0c9](https://exp-l1.jibchain.net/address/0xD02cc7a670047b6b012556A88e275c685d25e0c9) (you can see this address `checkSupraSValueFeed` from [0x2FA6DbFe4291136Cf272E1A3294362b6651e8517](https://exp-l1.jibchain.net/address/0x2FA6DbFe4291136Cf272E1A3294362b6651e8517))

and we have set it on the constructor of [0x89661591D76D93a86B6Fe6DC464275581a0FD005](https://exp-l1.jibchain.net/address/0x89661591D76D93a86B6Fe6DC464275581a0FD005?tab=contract)

the worker that update JBC price is [0xE3Cd56CF250E8dCc4940BE992ABfAf78a589c66f](https://exp-l1.jibchain.net/address/0xE3Cd56CF250E8dCc4940BE992ABfAf78a589c66f)
the worker that update the rest tokens is [0x3601c811B78AE101852Dd1B1eeC4d92A1eb22759](https://exp-l1.jibchain.net/address/0x3601c811B78AE101852Dd1B1eeC4d92A1eb22759)

**Comment by jiblendxyz** [comment]
@realdealshaman 
All contract addresses are available here: https://docs.jiblend.xyz/smart-contracts

**Pull request merged**
