### PR TITLE
feat: list nolus chain

### PR DESCRIPTION
**Pull request by ivivanov**
##### Name (to be shown on DefiLlama):
Nolus

##### Twitter Link:
https://twitter.com/NolusProtocol

##### List of audit links if any:
https://hub.nolus.io/en_US/technical-documentation/security

##### Website Link:
https://nolus.io/

##### Logo (High resolution, will be shown with rounded borders):
nolus-small-transp

##### Current TVL:
$1,175,791.59

##### Treasury Addresses (if the protocol has treasury):
N/A

##### Chain:
pirin-1

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
nolus

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

##### Short Description (to be shown on DefiLlama):
Nolus is a semi-permissioned blockchain bridging lenders and borrowers in a DeFi money market. With its DeFi Lease, borrowers can secure up to 150% financing on their initial investments, and access to the underlying leveraged assets through whitelisted strategies. Inspired by traditional leasing, where one pays a fraction upfront and gains ownership after repayment, Nolus' approach cuts down the DeFi sector's high over-collateralization standards. This boosts capital efficiency and offers borrowers better loan terms.

##### Token address and ticker if any:
NLS

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
TWAP

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
The combined total of lending pool assets and the current market value of active leases

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/nolus-protocol

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/nolus exports TVL: 
        
 
 
    nolus                     1.19 M
    
    total                    1.19 M

**Comment by g1nt0ki** [comment]
@ivivanov thanks for the PR but can update code to compute tvl on chain, you can look at other cosmos adapters we have. 

Also, tvl = assets depostied - assets borrowed
also, you can export a 'borrowed' key which shows borrowed value, example: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/hard.js#L15

**Comment by metodi96** [comment]
Hey @g1nt0ki, just wanted to jump in here and clarify the TVL computation. Nolus is a different type of lending market protocol than familiar ones such as AAVE, Compound, and their respective forks. It's an appchain that works in a cross-chain fashion with IBC and Interchain Accounts (Cosmos-specific tech). Each borrow position on Nolus is a separate smart contract instance that registers an Interchain Account (ICA) on a host network that is supported. For now, this is just Osmosis. So, when a borrower comes in to demand a loan from the system, both their initial deposit and the loan provided get parked into that smart contract instance which in turn uses IBC and ICA to swap them to a desired asset, effectively entering a type of cross-chain margin long position on that asset and that entire position acts as collateral in the system. This is the first part of the TVL - the current market value of active borrow (lease) positions. The second part is the available assets (not lent out yet) in the lending pool. 

In addition, we utilize an Extract-Transform-Load (ETL) agent which crawls the blockchain and submits the results in a lightweight PostgreSQL database. The code is fully open source and can be found here: https://github.com/nolus-protocol/extract-transform-load

**Comment by ivivanov** [comment]
Thanks for this clarification @metodi96 and involving our ETL service into the discussion.
@g1nt0ki thanks for your feedback.  To address issues of not calculating the TVL on chain what I plan to implement is actually taking out some of the logic of the ETL and implement it into the Defillama's getApiTvl helper function. In other words I will query the state of the lease contracts and aggregate their value. Hopefully that would be sufficient to pass the code review?

**Comment by g1nt0ki** [comment]
@metodi96 thanks for the clarification, and it is good that source code for the ETL is open source.

The reason I really dislike depending on external api is, they are hairy. We are in the dark when the api goes down/behind firewall/auth/is deprecated. It is hard to get hold of the devs/team and fix it,  Again, is there no way to get a list of lease/vault contracts on chain? in my view, if we can get this list, all that is needed is checking balance of tokens on each (thankfully this is way easier on cosmos chains compared to evm chains)

If there is really no other way, yes, @ivivanov your solution works :)

**Comment by g1nt0ki** [comment]
ooh, any way to get token breakdown? I think the users would like that

**Comment by llamatester** [comment]
The adapter at projects/nolus exports TVL: 
        
 
 
    nolus                     1.14 M
    
    total                    1.14 M

**Comment by g1nt0ki** [comment]
Hi @ivivanov , yeah, merged by mistake, cn you put up a new PR with on chain data?

**Comment by ivivanov** [comment]
@g1nt0ki, absolutely. I just need to fix a few small things.

**Pull request merged**
