### PR TITLE
Track vlCVX in JPEG treasury

### PR DESCRIPTION
**Pull request by 0xmichalis**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/olympus: 
        
 
  
    
    
    Invalid auth: Subscriptions not supported
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/graphql-request/dist/index.js:359:31

**Comment by llamatester** [comment]
Error while running adapter at projects/olympus: 
        
 
  
    
    
    Invalid auth: Subscriptions not supported
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/graphql-request/dist/index.js:359:31

**Comment by 0xmichalis** [comment]
It seems the issue is related to the Olympus adapter:

## Olympus

```
$ node test.js projects/olympus/index.js 

 ------ ERROR ------ 


Invalid auth: Subscriptions not supported
Truncated error stack:
    at /home/michalis/Code/OpenSource/defillama/DefiLlama-Adapters/node_modules/graphql-request/dist/index.js:359:31

```

## JPEG
<details>

```
$ node test.js projects/treasury/jpegd.js 
--- ethereum ---
USDC                      11.37 M
ETH                       11.16 M
USDT                      10.12 M
CVX                       5.69 M
DAI                       4.00 M
TUSD                      1.90 M
pUSDFRAXBP3CRV-f          800.37 k
JPEGETH-f                 729.01 k
WETH                      483.70 k
pETH                      335.55 k
FRAX                      35.68 k
pETH-ETH-f                22.19 k
LINK                      2.69 k
Total: 46.64 M 

--- ethereum-ownTokens ---
JPEG                      12.21 M
WETH                      1.17 M
Total: 13.38 M 

--- tvl ---
USDC                      11.37 M
ETH                       11.16 M
USDT                      10.12 M
CVX                       5.69 M
DAI                       4.00 M
TUSD                      1.90 M
pUSDFRAXBP3CRV-f          800.37 k
JPEGETH-f                 729.01 k
WETH                      483.70 k
pETH                      335.55 k
FRAX                      35.68 k
pETH-ETH-f                22.19 k
LINK                      2.69 k
Total: 46.64 M 

--- ownTokens ---
JPEG                      12.21 M
WETH                      1.17 M
Total: 13.38 M 

------ TVL ------
ethereum                  46.64 M
ethereum-ownTokens        13.38 M
ownTokens                 13.38 M

total                    46.64 M 
```
</details>

## Pirex
<details>

```
$ node test.js projects/pirex/index.js 
--- ethereum ---
CVX                       13.04 M
Total: 13.04 M 

--- arbitrum ---
GLP                       438.17 k
GMX                       405.35 k
Total: 843.52 k 

--- tvl ---
CVX                       13.04 M
GLP                       438.17 k
GMX                       405.35 k
Total: 13.88 M 

------ TVL ------
ethereum                  13.04 M
arbitrum                  843.52 k

total                    13.88 M 

```
</details>

## Redacted

<details>

```
$ node test.js projects/redacted/index.js 
--- ethereum-staking ---
BTRFLY                    32.20 M
Total: 32.20 M 

--- ethereum ---
CVX                       5.35 M
OHM                       3.06 M
cvxcrv-f                  2.61 M
FXS                       606.99 k
CRV                       164.42 k
AURA                      160.69 k
USDC                      11.52 k
cvxCRV                    8.31 k
Total: 11.98 M 

--- staking ---
BTRFLY                    32.20 M
Total: 32.20 M 

--- tvl ---
CVX                       5.35 M
OHM                       3.06 M
cvxcrv-f                  2.61 M
FXS                       606.99 k
CRV                       164.42 k
AURA                      160.69 k
USDC                      11.52 k
cvxCRV                    8.31 k
Total: 11.98 M 

------ TVL ------
ethereum-staking          32.20 M
ethereum                  11.98 M
staking                   32.20 M

total                    11.98 M 
```
</details>

**Comment by llamatester** [comment]
The adapter at projects/pirex exports TVL: 
        
 
 
    ethereum                  12.20 M
    arbitrum                  824.01 k
    
    total                    13.03 M

**Comment by llamatester** [comment]
The adapter at projects/redacted exports TVL: 
        
 
 
    ethereum-staking          30.78 M
    ethereum                  11.69 M
    staking                   30.78 M
    
    total                    11.69 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/jpegd.js exports TVL: 
        
 
 
    ethereum                  43.90 M
    ethereum-ownTokens        12.96 M
    ownTokens                 12.96 M
    
    total                    43.90 M

**Comment by 0xmichalis** [comment]
Moved the Olympus adapter changes in https://github.com/DefiLlama/DefiLlama-Adapters/pull/6378 to avoid blocking the rest of the changes here.

**Comment by g1nt0ki** [comment]
@0xmichalis thanks for the PR

**Pull request merged**
