### PR TITLE
Add bluebit.fi adapter

### PR DESCRIPTION
**Pull request by BluebitFinance**
Twitter Link: https://twitter.com/BlueBitFinance

List of audit links if any: 

Website Link: https://bluebit.fi

Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): https://bluebit.fi/coin/bbt.svg

Current TVL: 431.87K

Chain: Aurora

Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list) bluebit

Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000) bluebit

Short Description (to be shown on DefiLlama): BlueBit Finance is a yield aggregator built on Near’s Aurora EVM. The protocol allows users to earn more yield from DeFi farming in a more secure, accessible, and efficient manner.

Token address and ticker if any: 0x4148d2Ce7816F0AE378d98b40eB3A7211E1fcF0D (Aurora)

Category (full list at https://defillama.com/categories) *Please choose only one: Yield Aggregator

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using): 

forkedFrom (Does your project originate from another project):

methodology (what is being counted as tvl, how is tvl being calculated): The vaults on https://bluebit.fi are included in TVL.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bluebit/index.js exports TVL: 
        
 
 
    aurora                    2.10 M
    
    total                    2.10 M

**Comment by waynebruce0x** [comment]
can the staking TVL be exported as a separate 'staking' export?

**Comment by BluebitFinance** [comment]
Sure ser, we have submitted the "staking" part, thank you!

Regard

**Comment by BluebitFinance** [comment]
As per our application, please note that we have approved running workflows. Thanks!

**Comment by BluebitFinance** [comment]
Thank you very much!

**Pull request merged**
