### PR TITLE
Add wemix, metadium vault tvls & Update ton vault address

### PR DESCRIPTION
**Pull request by rlekdms**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/orbitbridge exports TVL: 
        
 
 
    ripple                    21.50 M
    ton                       630.88 k
    polygon                   850.03 k
    heco                      475.34 k
    celo                      67.42913356206148
    wemix                     977.53 k
    ethereum                  153.19 M
    meta                      160.80 k
    bsc                       2.95 M
    klaytn                    1.78 M
    
    total                    182.51 M

**Comment by g1nt0ki** [comment]
@rlekdms thanks for the PR, I have blacklisted ORU token from tvl, I have added comment on the code as to why.

**Comment by rlekdms** [comment]
@g1nt0ki That tx you put in the comment was probably bridged to provide other Defi's initial liquidity. ORC is still being actively bridged by other users. Please remove ORC from the blacklist.

**Comment by g1nt0ki** [comment]
@rlekdms I agree users do transfer ORC, but the majority comes from this transaction which is made by your team? this is exactly why I dont like including projects own tokens as part of tvl, it can be gamed easily, hypothetically, would you be happy  if synapse moves 400M $ of their own token in their treasury from one chain to another and we count it as tvl?

**Comment by lusterk** [comment]
Hello.
This is Daniel from the Orbit Chain team and in charge of the head of this project.

From two years ago until now, ORC as a DeFi asset for utilizing on KLAYswap. Currently, more than 40 DeFi protocols accepted ORC, including KLAYswap (Klaytn), Meshswap (Polygon), and Megaton Finance (TON). Thus, ORC being blackisted by your team is incomprehensible to us. In addition, the amount of ORC distributed to the team is the result of the Orbit governance official proposal (OIP-5). I would like you to reconsider that there is no centralized part, and ORC is a widely used asset.

**Comment by g1nt0ki** [comment]
> Hello. This is Daniel from the Orbit Chain team and in charge of the head of this project.
> 
> From two years ago until now, ORC as a DeFi asset for utilizing on KLAYswap. Currently, more than 40 DeFi protocols accepted ORC, including KLAYswap (Klaytn), Meshswap (Polygon), and Megaton Finance (TON). Thus, ORC being blackisted by your team is incomprehensible to us. In addition, the amount of ORC distributed to the team is the result of the Orbit governance official proposal (OIP-5). I would like you to reconsider that there is no centralized part, and ORC is a widely used asset.

hi @lusterk , sorry but you have not addressed my concern. is this from your team wallet? https://etherscan.io/tx/0x0a556fcef2a867421ec3941251ad3c10ae1402a23ddd9ad4b1097b686ced89f7 if so, why should it be considered as tvl?

**Comment by 0xngmi** [comment]
We had a similar case with Axelar, and we aren't counting their token into TVL there.

**Pull request merged**
