### PR TITLE
adding AutoBark.js

### PR DESCRIPTION
**Pull request by autobark**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

##### Twitter Link:
https://twitter.com/AutoBarkYield

##### List of audit links if any:
Coming soon

##### Website Link:
http://www.autobark.lol

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://pbs.twimg.com/profile_images/1560448776556273666/48GIp-xk_400x400.jpg

##### Current TVL:
$109,750

##### Chain:
DogeChain

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

##### Short Description (to be shown on DefiLlama):
AutoBark is a Decentralized, Yield Optimizer on DogeChain that allows its users to earn compound interest on their crypto holdings. AutoBark earns you the highest APYs with safety and efficiency in mind.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
N/A

##### forkedFrom (Does your project originate from another project):
Beefy

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL data is pulled from the AutoBark API "https://api.autobark.lol/tvl"

### CODE REVIEW

**Comment by realdealshaman** [comment]
@autobark hey, thanks for the PR. We are currently working on converting fetch adapters to adapters that use on-chain calls. Since this project is on an evm compatible chain we would prefer to have an on-chain adapter for it

**Comment by autobark** [comment]
> 

Ok great, thanks for the note. Anything you need from us in the meantime?

**Comment by realdealshaman** [comment]
could you submit a version that uses on-chain calls?

**Comment by autobarkfinance** [comment]
Hello Defillama team!

> could you submit a version that uses on-chain calls?

Our API calculates the TVL of our vaults based on onchain calls. The involves:

1. getting a list of current vaults from our public repository
2. getting the 'want' of that vault (LP or single token)
3. calculating the underlying tokens of that want and calculating their price
4. calculating the total supply of the LP to match the asset prices and calculate the LP price
5. calculating the exchange ratio of the vault token to the underlying asset
6. calculating the total supply of the vault token 
7. calculating the total $ value locked in the vault
8. adding the $ value of all vaults into the easily retrievable TVL fetch

This process is constantly updated as we add new vaults. It involves axios calls, ABI's of smart contracts, price calculations and more.

In order for us to accurately extend this process of onchain calls to defillama, we essentially need to recreate our existing API, and do so in a way that requires constant updates alongside our current constant updates to our primary API. 

This seems redundant. 

Is it possible for us to share a private API codebase with a member of your dev team? We do not want to make this public at this time.

Or we could consider other solutions?

**Comment by g1nt0ki** [comment]
@autobark I am closing this PR in favor of https://github.com/DefiLlama/DefiLlama-Adapters/pull/3688

I am fetching the vault list from your public git repo and doing the computation

**Comment by g1nt0ki** [comment]
@autobark can you update the public repo with list of current vaults, I am seeing dogmoney and kibbleswap vaults in the UI but can see only yodeswap vaults in repo

**Comment by autobarkfinance** [comment]
> @autobark can you update the public repo with list of current vaults, I am seeing dogmoney and kibbleswap vaults in the UI but can see only yodeswap vaults in repo

Correct list is in this PR. Thanks so much! 
https://github.com/DefiLlama/DefiLlama-Adapters/pull/3689

**Pull request closed without merging**
