### PR TITLE
New vaults

### PR DESCRIPTION
**Pull request by AlgoRai**
New vaults:

- mALGO CALL
- GOLD$ CALL
- GOLD$ PUT
- ALGO LIQ POOL

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/algorai-finance exports TVL: 
        
 
 
    algorand                  4.12 M
    
    total                    4.12 M

**Comment by llamatester** [comment]
The adapter at projects/algorai-finance exports TVL: 
        
 
 
    algorand                  3.04 M
    
    total                    3.04 M

**Comment by g1nt0ki** [comment]
hi @AlgoRai 
Thanks for the PR, I refactored the code a bit, so it pulls token balances from the apps and updated our server, so we fetch token prices from tinyman on top of coingecko, so no need to specify token info per vault.

But I am getting much lower tvl compared to your code, can you check if I did something wrong/missing something?

**Comment by llamatester** [comment]
The adapter at projects/algorai-finance exports TVL: 
        
 
 
    algorand                  3.04 M
    
    total                    3.04 M

**Comment by AlgoRai** [comment]
> hi @AlgoRai Thanks for the PR, I refactored the code a bit, so it pulls token balances from the apps and updated our server, so we fetch token prices from tinyman on top of coingecko, so no need to specify token info per vault.
> 
> But I am getting much lower tvl compared to your code, can you check if I did something wrong/missing something?

Hi @g1nt0ki  

We were including liquidity tokens that our protocol mints to represent TVL that has been deposited through our platform, but ultimately locked with institutional custodians. These tokens (https://algoexplorer.io/asset/1145958888) and (https://algoexplorer.io/asset/1145959061) are not listed on tinyman nor coingecko so it is understandable that they will not be included if we do not specify vault token info.

**Comment by g1nt0ki** [comment]
hmm, in that case, we can count hAlgo/hUSDC converted to algo/usdc but counted under borrowed instead of tvl, because the funds are no longer kept in your smart contract, does that sound good?

**Comment by llamatester** [comment]
The adapter at projects/algorai-finance exports TVL: 
        
 
 
    algorand-borrowed         2.98 M
    algorand                  3.02 M
    borrowed                  2.98 M
    
    total                    3.02 M

**Pull request merged**
