### PR TITLE
Add swap.coffee XROCK staking

### PR DESCRIPTION
**Pull request by SHADOWDANCH**
Changes: 
- Count [XROCK stacked on swap.coffee](https://swap.coffee/stake/XROCK) as TVL.
- Use LP token prices from tonapi.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/swap-coffee exports TVL: 
        
 
 
    ton-staking               683.61 k
    staking                   683.61 k
    ton                       358.18 k
    ton-pool2                 234.47 k
    pool2                     234.47 k
    
    total                    358.18 k

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
sorry, we can count staked XROCK only under staking, and XROCK LP under pool2. We applied similar rules to bountive & brewlabs, you can check the implementation there

**Comment by SHADOWDANCH** [comment]
> sorry, we can count staked XROCK only under staking, and XROCK LP under pool2. We applied similar rules to bountive & brewlabs, you can check the implementation there

But in documentation it says that staking and pool2 is protocol own token, XROCK is not our protocol token.
```
Staking - the platform's own tokens
Pool2 - staked LP tokens where one side of the market is the platform's own governance token.
```

**Comment by g1nt0ki** [comment]
yes, I know what the doc says. thats why I linked to similar projects where we applied the same rule.

**Comment by llamatester** [comment]
The adapter at projects/swap-coffee exports TVL: 
        
 
 
    ton-staking               1.09 M
    staking                   1.09 M
    ton-pool2                 226.59 k
    pool2                     226.59 k
    ton                       0
    
    total                    0

**Comment by g1nt0ki** [comment]
thanks @SHADOWDANCH

**Pull request merged**
