### PR TITLE
Add JPEGd hallmarks

### PR DESCRIPTION
**Pull request by 0xmichalis**
Announcements:
* pETH borrows: https://twitter.com/JPEGd_69/status/1581778490570862592
* JPEG LTV boost: https://twitter.com/JPEGd_69/status/1596838953755512833
* APE staking: https://twitter.com/JPEGd_69/status/1600897997537263618

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/jpeg-d exports TVL: 
        
 
 
    ethereum-staking          893.96 k
    ethereum-treasury         25.57 M
    ethereum-pool2            94.63 k
    ethereum                  15.20 M
    staking                   893.96 k
    treasury                  25.57 M
    pool2                     94.63 k
    
    total                    15.20 M

**Comment by llamatester** [comment]
The adapter at projects/jpeg-d exports TVL: 
        
 
 
    ethereum-staking          884.34 k
    ethereum-treasury         25.56 M
    ethereum-pool2            94.11 k
    ethereum                  15.20 M
    staking                   884.34 k
    treasury                  25.56 M
    pool2                     94.11 k
    
    total                    15.20 M

**Comment by llamatester** [comment]
The adapter at projects/jpeg-d exports TVL: 
        
 
 
    ethereum-treasury         25.55 M
    ethereum-pool2            94.56 k
    ethereum-staking          895.37 k
    ethereum                  15.24 M
    treasury                  25.55 M
    pool2                     94.56 k
    staking                   895.37 k
    
    total                    15.24 M

**Comment by g1nt0ki** [comment]
@0xmichalis thanks for the PRs

**Pull request merged**
