### PR TITLE
chore: update badgerdao treasury addresses

### PR DESCRIPTION
**Pull request by gosuto-inzasheru**
just an update of our treasury addresses as it was noted that your overview strongly differs from our official report (https://lookerstudio.google.com/u/2/reporting/709ff9bc-23d3-46ed-b0aa-d7af77fe6ed9/page/YwQ5C)

this should bring it closer to truth, although with a lot of staked positions missing it still wont be correct.

addresses can be verified [here](https://github.com/Badger-Finance/badger-multisig#multisig-addresses) if necessary.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/treasury/badger-dao.js exports TVL: 
        
 
 
    ethereum                  5.93 M
    ethereum-ownTokens        5.90 M
    ownTokens                 5.90 M
    
    total                    5.93 M

**Comment by g1nt0ki** [comment]
@gosuto-inzasheru thanks for the PR, we can include the staked positions as well, do you maybe have a api to fetch this info or can they be fetched from the chain somehow?

**Comment by gosuto-inzasheru** [comment]
ah great! @g1nt0ki can you maybe provide an example of a js file in which this is done? our most important staked positions are on aura and convex. also just as important are our univ3 positions of treasury controlled liquidity. and indeed we do have a web2 api with price feeds for various assets if that were needed.

happy to add necessary code for this if supported!

**Comment by g1nt0ki** [comment]
@gosuto-inzasheru hope I have covered everything with this commit? https://github.com/DefiLlama/DefiLlama-Adapters/commit/70c44c4a6868e229576547c9e675b03e6d150b98


    --- ownTokens ---
    BADGER                    5.74 M
    DIGG                      92.81 k
    Total: 5.84 M 

    --- tvl ---
    50rETH-50BADGER           5.02 M
    WBTC                      3.54 M
    BADGER                    3.40 M
    20WBTC-80BADGER           2.50 M
    DAI                       1.21 M
    USDC                      1.20 M
    40WBTC-40DIGG-20graviAURA 1.17 M
    USDT                      1.04 M
    LUSD                      692.26 k
    aWBTC                     205.69 k
    GTC                       178.51 k
    WETH                      67.83 k
    rETH                      33.96 k
    ETH                       17.46 k
    BADGERFRAX-f              315
    Total: 20.26 M 

    ------ TVL ------
    ethereum-ownTokens        5.84 M
    ethereum                  20.26 M
    ownTokens                 5.84 M

    total                    20.26 M

**Comment by gosuto-inzasheru** [comment]
`BADGERFRAX-f` should be just under $1m. finally the univ3 badger/wbtc nfts are another $5-6m so considerable.

**Comment by g1nt0ki** [comment]
`BADGERFRAX-f`  should be under a $1m are you sure about this? maybe the contract with those tokens are not included?

univ3 is already included, they show up on the list as badger & wbtc after being unwound

**Pull request merged**
