### PR TITLE
Update Tsunami Finance TVL: add Mantle, remove Aptos

### PR DESCRIPTION
**Pull request by yv-was-taken**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
Updated Tsunami Finance TVL calculation: Adding Mantle. Removing Aptos as that has been sunsetted

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/tsunami-fi exports TVL: 
        
 
 
    mantle                    0
    
    total                    0

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
hi @yv-was-taken thanks for the PR, but can you revert the changes made to the aptos tvl code? 
it was sunset in October? we can perhaps add a hallmark but removing aptos completely, removes chain from your tvl chart and also affects overall chain chart

**Comment by llamatester** [comment]
The adapter at projects/tsunami-fi exports TVL: 
        
 
 
    mantle                    1.29 M
    
    total                    1.29 M

**Comment by yv-was-taken** [comment]
> hi @yv-was-taken thanks for the PR, but can you revert the changes made to the aptos tvl code? it was sunset in October? we can perhaps add a hallmark but removing aptos completely, removes chain from your tvl chart and also affects overall chain chart

Understood. Need to get exact date of sunset for hallmark. Will push momentarily

**Comment by yv-was-taken** [comment]
> hi @yv-was-taken thanks for the PR, but can you revert the changes made to the aptos tvl code? it was sunset in October? we can perhaps add a hallmark but removing aptos completely, removes chain from your tvl chart and also affects overall chain chart

Done!

**Comment by llamatester** [comment]
Error while running adapter at projects/tsunami-fi: 
        
 
  
    
    
    TypeError: number 133174276 is not iterable (cannot read property Symbol(Symbol.iterator))
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:258:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:517:28)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
The adapter at projects/tsunami-fi exports TVL: 
        
 
 
    aptos                     16.52 k
    mantle                    1.29 M
    
    total                    1.30 M

**Comment by g1nt0ki** [comment]
@yv-was-taken thanks for the PR

**Pull request merged**
