### PR TITLE
Add yieldly TVL

### PR DESCRIPTION
**Pull request by Yieldlan**
Currently we are only tracking our locked Algorand, this is adding in the locked Yieldly, as it just started trading today :)

### CODE REVIEW

**Comment by Yieldlan** [comment]
Sorry about the conflict. You are all good to override the conflict in our project file to just be the latest code in our PR

**Comment by Yieldlan** [comment]
The reason we can get the price of Yieldly (Algorand asset) from Uniswap is that we have released a two way bridge in our platform to allow people to move between chains.

**Comment by 0xngmi** [comment]
Could you tell me how much yieldly is staked in USD?

**Comment by Yieldlan** [comment]
Sure!

~500 million yieldly staked

Each yieldly valued around 1c each,

So about ~5 million dollars (USD) worth of yieldly staked on the algorand
chain.

**Comment by 0xngmi** [comment]
Got it, once I have some time I'll port over the changes to the new version (fixing merge conflicts)

**Comment by Yieldlan** [comment]
Sounds good, thanks!

**Comment by Yieldlan** [comment]
Is there anything i can do to help?

**Comment by Yieldlan** [comment]
Should be able to just accept incoming to merge. :)

**Comment by 0xngmi** [comment]
> Should be able to just accept incoming to merge. :)

I imagine you were planning to commit a new version that merged your changes into master

Luckily there's no need, I just merged them and separated staking TVL from the other TVL on c176752ff6720f5a0650af4c54b71793191bd98c

Given that counting staking separately is a new feature it won't be immediately displayed on the site, I need to make some changes to the frontend before that happens.

Also, sorry for the wait, I couldn't merge this right away since there were multiple merge conflicts and thought it would be better to work on this once I had in place a system that could track staking separately, since that has been requested multiple times

**Comment by Yieldlan** [comment]
Hey, so to confirm you have added the staking TVL and it should appear soon?

Our TVL is like ~20 mil total inculding ALGO and Yieldly, but currently still 15 mil on Defillama.

Thanks for following up!

**Comment by spaceforce-dev** [comment]
Hey, just wondering whats going on here? 

i can make a new PR if you want, we are still missing the tvl from this commit! 

thanks for the help.

**Comment by Yieldlan** [comment]
Hey, just wondering whats going on with this commit not being merged?

i can make a new PR if you want, we are still missing the tvl from this
commit!

thanks for the help.

**Comment by 0xngmi** [comment]
> Hey, just wondering whats going on with this commit not being merged?

I already merged this PR, it's just that I didn't do it directly but instead I applied the changes manually

The reason why staking TVL doesn't show up is just because I still haven't made the changes necessary on our frontend to display it

**Comment by spaceforce-dev** [comment]
Gotcha, ok i guess there is nothing we can do for now.

Appreciate the work mate,

thanks

**Comment by 0xngmi** [comment]
Just re-read this as I was going through open PRs. To clear any possible misconceptions, the merge happened in commit c176752ff6720f5a0650af4c54b71793191bd98c, so about 18 days ago

**Comment by Yieldlan** [comment]
Is there any ETA on seeing our extra tvl?

**Comment by 0xngmi** [comment]
The staking TVL was added to our APIs 2 days ago and I just made the necessary UI changes today.

If you select staking on https://defillama.com/settings you should be able to see the extra TVL

**Comment by Yieldlan** [comment]
Ok got it thanks ill close.

I just opened another issue about a crash in the app on a certain page.

**Pull request closed without merging**
