### PR TITLE
Add Compx Adapter

### PR DESCRIPTION
**Pull request by clooneyr**
---
##### Logo (High resolution, will be shown with rounded borders):  
Compx

##### methodology (what is being counted as tvl, how is tvl being calculated):
The tvl that is being counted comes from the total value stored in our users compounding farms. This is done by indexing each individuals compounder and calculating the users dollar position based on the total amount in the specific farm. We are using the fetch functionality as gathering the protocols TVL requires indexing over 100 address, which continually expands.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/compx exports TVL: 
        
 
 
    algorand                  450.90 k
    
    total                    450.90 k

**Comment by g1nt0ki** [comment]
hi @clooneyr ,

I understand it is painful to compute the tvl on chain, but I am reluctant to approve this PR, it is a complete blackbox, if this api is unreachable, I have no way to compute tvl, there is no contract information on your docs, there is no code related to app deployment or stats computation on your github.


Can you share some contract details? I can look into writing the tvl adapter myself when I get some time.

**Comment by llamatester** [comment]
The adapter at projects/compx exports TVL: 
        
 
 
    algorand                  0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/compx exports TVL: 
        
 
 
    algorand                  462.73 k
    
    total                    462.73 k

**Comment by clooneyr** [comment]
Hey @g1nt0ki i have updated the api so it includes the details of the escrow address where the users compounder LPs are being stored. 
I have also included how we are working out the dollar value for the LP position. 
The tvl can now be validated by indexing the escrow's balance to prove on chain funds.
I hope this clears up your concerns, let me know if there are anymore issues

**Pull request merged**
