### PR TITLE
init

### PR DESCRIPTION
**Pull request by dtderitrade**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
DeriTrade

##### Twitter Link:
https://twitter.com/deritrade?lang=en

##### Website Link:
https://deri.trade

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://deritrade.gitbook.io/deritrade/brand-kit

##### methodology (what is being counted as tvl, how is tvl being calculated):
not decided yet but DERITRADE TOKEN will be used to incentives liquidity provider at early stage after fair launch

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/deritrade exports TVL: 
        
 
 
    bsc                       0
    arbitrum                  0
    zksync                    0
    
    total                    0

**Comment by g1nt0ki** [comment]
sorry, we cant list project with 0 tvl. smaller issue with PR is, you have edited PR template file

**Comment by dtderitrade** [comment]
we do have our fair launch smart contract for user to deposit USDC but it will be transfer into cold wallet for security purpose therefore it will be 0 tvl, can we still use this for tvl? but we will have another smart contract which will lock liquidity pool for 2 years in future, can we update it after that?

**Comment by g1nt0ki** [comment]
> we do have our fair launch smart contract for user to deposit USDC but it will be transfer into cold wallet for security purpose therefore it will be 0 tvl, can we still use this for tvl? but we will have another smart contract which will lock liquidity pool for 2 years in future, can we update it after that?

sorry, we can count only the tokens in smart contract as tvl, also if liquidity is going to be locked for two years, I would say users need to be warned about it (in the UI) while depositing

**Comment by dtderitrade** [comment]
i see, ok noted with thanks, will close this PR for now and create another one once we have the smart contract for tvl, thank you

**Pull request closed without merging**
