### PR TITLE
Track Goldsand staking protocol TVL.

### PR DESCRIPTION
**Pull request by gibraltariq**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Logo (High resolution, will be shown with rounded borders):
goldsand-icon

##### Short Description (to be shown on DefiLlama):
Shariah compliant Ethereum (and soon Solana) staking. Purified from interest with competitive yield.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Liquid Staking

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is the sum of deposits minus the sum of withdrawals. Since there is no liquid staking token (yet) and deposited ETH greater than 32 is automatically staked in the beacon chain, the contract balance itself is not the TVL.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/inshallah-network

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/goldsand exports TVL: 
        
 
 
    ethereum                  1.58 M
    
    total                    1.58 M

**Comment by gibraltariq** [comment]
image

i don't see any option to allow edits by maintainers

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
@gibraltariq thanks for the PR, unfortunately, the current implementation is not very scalable since the logs keep going up over time, we might end up with too many logs to cache. 

Is there some other way to pull the amount of ETH staked?

**Comment by g1nt0ki** [comment]
> 
> i don't see any option to allow edits by maintainers

maybe there is an option below participants? or if you try to edit the PR description, it might be a checkbox at the bottom  like this https://github.com/orgs/community/discussions/5634#discussioncomment-2153275

**Comment by g1nt0ki** [comment]
bump

**Comment by gibraltariq** [comment]
hey @g1nt0ki - can we set a max toBlock on await getLogs to 3-4 months out from now and fix the issue by then?

I fup'd with the team and there's no simple fix right now. To avoid using logs, we'd have to add and use another contract variable which would trigger another audit (beyond our budget now).

**Comment by gibraltariq** [comment]
bumping on my end this time :) - wdyt of the above @g1nt0ki

**Comment by g1nt0ki** [comment]
ah, forgot to comment here. I added it with a bit of  a hack. https://github.com/DefiLlama/DefiLlama-Adapters/commit/1282304fc173f737630ead0d82af94c52be7a841

Downside of the hack is, we wont be able fetch old tvl, since we only store the sum.

**Comment by gibraltariq** [comment]
Thank you so much!

**Pull request closed without merging**
