### PR TITLE
add bond-appetit protocol

### PR DESCRIPTION
**Pull request by bondappetit**
##### Twitter Link:
https://twitter.com/DefiBonds

##### List of audit links if any:
* https://github.com/mixbytes/audits_public/tree/4fc7d333e3df57586e0f96cc551819e2c93f3ae9/BondAppetit

##### Website Link:
https://bondappetit.io/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://yadi.sk/i/EzNflynr7leEmg

##### Current TVL:
7950000

##### Chain:
Ethereum, BSC (Soon)

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
* bondappetit-gov-token
* bond-appetite-usd

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
9322

##### Description/bio (to be shown on DefiLlama):
BondAppétit, a DeFi protocol for business loans. BondAppétit provides an infrastructure that connects decentralized finance and traditional debt instruments with the participation of regulated securities and cryptocurrency brokers/dealers.

The Purpose of BondAppétit

For crypto investors

BondAppétit will be the first and the only DeFi protocol with a stablecoin fully backed by real-world assets with fixed periodic income (bonds). Unlike most other DeFi protocols, there will be real fiat cash flows inside the protocol.

The price of the BondAppétit native stablecoin (USDap) equals $1 at all times. The token is issued only if the protocol has sufficient collateral.

For borrowers

Businesses are always looking for cheap financing opportunities. Traditionally, large and mid-sized companies get money through bank and bond financing. With its global reach and intermediary-free environment, the crypto market could become a new source of funding in the near future. The total market capitalization of the crypto market overcame the $1.7 trillion mark and is expected to grow.

However, in its current state (as of April 2021) the DeFi lending market is a poor choice for established businesses. Most protocols suffer from high fees, volatility, and over-collateralization, making them uncompetitive for mid-sized and large businesses in comparison to traditional bank and bond financing.

BondAppétit is determined to deal with these issues and open up new opportunities for businesses to access for a whole new source of liquidity.

##### Token address and ticker if any:
* BAG: 0x28A06c02287e657ec3F8e151A13C36A1D43814b0
* USDap: 0x9a1997C130f4b2997166975D9AFf92797d5134c2

##### Category (Yield/Dexes/Lending/Minting):
Yield

##### [Optional] ETH addresss (to receive a LlamaPunk):
0x6Eff5218f3EBB8A813539DBA87bD5c7D4d2B3dcc

### CODE REVIEW

**Comment by 0xngmi** [comment]
It seems that this is a graphql endpoint you rolled on your own, would it be possible to get historical TVLs from it?

**Comment by bondappetit** [comment]
@0xngmi we have started our protocol just 2 weeks ago and to be honest, it is not critical to lose any historical data in DefiLama. For example, Coingecko, Coinmarketcup and other services that already listed us, have their own data from the beginning of the listing without any history and this is not a problem.

The second thing why we are using the graphQL endpoint is that we will start the BSC part of our protocol in a couple of weeks. And it will be not so easy to accumulate these numbers with 2 separate blockchains in the DefiLama script. We did that in our GraphQL API (like Curve for example) and this is the same source that we are using on our own website. So, the main goal for this type of integration is to exclude any needs to support this script separately.

BTW. If you need any historical data - we can add this feature to our GraphQL API, but we need instructions for that.

I hope we can speed up the process of listing and historical data will not be some kind of stop factor for DefiLama listing. I think we can update this at any time.

**Comment by 0xngmi** [comment]
Okay I'll take it for now, but if you could make it possible to provide a timestamp parameter to your graphql endpoint, that would greatly help and would enable me to get historical data.

Sorry for the delay in answering. Feel free to ping me if I ever take longer than 24 hours to answer.

**Comment by 0xngmi** [comment]
Just took another look at the protocol and it seems that, as it's backed by real world assets, no crypto value is locked in smart contracts and therefore it has no TVL. Is that correct? Is the TVL reported the value of the bonds that are backing your stablecoin?

**Comment by bondappetit** [comment]
@0xngmi thanks! 

I will discuss the timestamp with the team and will return to you as soon as possible.

Our protocol in phase 1 of launch right of now and we are using crypto collateral for our stable coin. For now, TVL shows how much money locked in our staking liquidity pools.

In phase 2 (approximately in July) we will change the collateral from crypto to real-world assets. You can check it in our roadmap - https://bondappetit.io/whitepaper#44

If you have any other questions about our project, feel free to contact me at telegram @vkomissarov to speed up the process ;)

**Comment by 0xngmi** [comment]
Thanks for the explanation, I've listed you on the site.

**Comment by 0xngmi** [comment]
Your API seems to be broken, could you fix it please?

**Pull request merged**
