### PR TITLE
add tvl for toupee.tech

### PR DESCRIPTION
**Pull request by oxSaturn**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

Toupée Tech

##### Twitter Link:

https://twitter.com/toupeetech

##### List of audit links if any:

1. https://2268926613-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F5qfDTx0sJybWgitP8x4j%2Fuploads%2FnzcUOiAySnZr2UQCCpsK%2FPeckShield-Audit-Report-LilToken-v1.0rc%20(1).pdf?alt=media&token=4b8c3f95-1cae-4d7d-bdee-0ddbb2fb2abc
2. https://[2268926613-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F5qfDTx0sJybWgitP8x4j%2Fuploads%2F0dGTom7KMTseCGo56Xg0%2FZokyoAudit.pdf?alt=media&token=9c4acb60-7ad6-49df-ab1c-cc0bfff8d711](https://2268926613-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F5qfDTx0sJybWgitP8x4j%2Fuploads%2F0dGTom7KMTseCGo56Xg0%2FZokyoAudit.pdf?alt=media&token=9c4acb60-7ad6-49df-ab1c-cc0bfff8d711)

##### Website Link:

https://www.toupee.tech/

##### Logo (High resolution, will be shown with rounded borders):

https://www.toupee.tech/_next/image?url=%2Fimages%2Ftokens%2Ftoupee.png&w=128&q=100

##### Current TVL:

$790k

##### Treasury Addresses (if the protocol has treasury)

[0x0cF24278C99d60388dd8A3A663937f1b9f934d09](https://basescan.org/address/0x0cf24278c99d60388dd8a3a663937f1b9f934d09)

##### Chain:

Base

##### Short Description (to be shown on DefiLlama):

A coordination system for ecosystem incentives.

##### Token address and ticker if any:

1. WIG:  0x58Dd173F30EcfFdfEbCd242C71241fB2f179e9B9
2. oWIG:  0xbe1053ec4Ac137c9A5B4462d53d5c2c0B89a2B79
3. vWIG:  0x60c08737877a5262bdb1c1cAC8FB90b5E5B11515

##### Category (full list at https://defillama.com/categories) *Please choose only one:

[Yield](https://defillama.com/protocols/Yield)

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

Chainlink

##### methodology (what is being counted as tvl, how is tvl being calculated):

Counts the number of locked WETH in the Toupee Tech Bonding Curve.

See https://basescan.org/address/0x752de9d1B6F8796D214D2A24A6f6F55ee9Facc71#code, search `bondingCurve.tvl = ITOKEN(TOKEN).getTotalValueLocked() * bondingCurve.priceBASE`:

1. ` ITOKEN(TOKEN).getTotalValueLocked()` will get the number of WETH locked
2. `bondingCurve.priceBASE` is the price of WETH from oracle, in `tvl` function we rely on llama price instead.

##### Github org/user (Optional, if your code is open source, we can track activity):

https://github.com/Toupee-Tech

### CODE REVIEW

**Comment by oxSaturn** [comment]
cc @berabuilder for double check.

**Comment by berabuilder** [comment]
**Treasury Addresses (if the protocol has treasury)**

0x0cF24278C99d60388dd8A3A663937f1b9f934d09

**Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):**
Chainlink

**methodology (what is being counted as tvl, how is tvl being calculated):**

bondingCurve.tvl = ITOKEN(TOKEN).getTotalValueLocked() * bondingCurve.priceBASE

For reference> Multicall:  0x752de9d1B6F8796D214D2A24A6f6F55ee9Facc71

**Comment by oxSaturn** [comment]
> **Treasury Addresses (if the protocol has treasury)**
> 
> 0x0cF24278C99d60388dd8A3A663937f1b9f934d09
> 
> **Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):** Chainlink
> 
> **methodology (what is being counted as tvl, how is tvl being calculated):**
> 
> bondingCurve.tvl = ITOKEN(TOKEN).getTotalValueLocked() * bondingCurve.priceBASE
> 
> For reference> Multicall: 0x752de9d1B6F8796D214D2A24A6f6F55ee9Facc71

Updated.

**Comment by oxSaturn** [comment]
@g1nt0ki ser can we just return the tvl in usd? Seems we have to rely on llama coins api for the price data right? Like if we want to include WIG token, we would have to get WIG token's price listed on llama coins first.

**Comment by oxSaturn** [comment]
> > @g1nt0ki ser can we just return the tvl in usd? Seems we have to rely on llama coins api for the price data right? Like if we want to include WIG token, we would have to get WIG token's price listed on llama coins first.
> 
> hi @oxSaturn thanks for the PR, we prefer having token breakdown. Bit unsure why getTotalValueLocked returns 380 ETH when I see only 24 ETH in the contract, the rest are borrowed?

Right, you can check `debtTotal` here https://basescan.org/address/0x58Dd173F30EcfFdfEbCd242C71241fB2f179e9B9#readContract#F13

`getTotalValueLocked() - debtTotal = WETH balance in that contract`.

**Comment by oxSaturn** [comment]
I've pushed another commit to include staking, so the problem is how to get price of WIG into llama coins api https://github.com/DefiLlama/defillama-server/tree/master/coins. @g1nt0ki Any suggestion? It's `getMarketPrice` from https://basescan.org/address/0x58Dd173F30EcfFdfEbCd242C71241fB2f179e9B9#readContract#F13 multiply the price of WETH:

```
getMarketPrice() * WETH price
```

**Comment by llamatester** [comment]
The adapter at projects/toupee-tech exports TVL: 
        
 
 
    base-borrowed             733.83 k
    base                      47.22 k
    base-staking              773.09 k
    borrowed                  733.83 k
    staking                   773.09 k
    
    total                    47.22 k

**Comment by g1nt0ki** [comment]
hi @oxSaturn 

I have updated code to return borrowed amount under 'borrowed' key, and WIG value is converted to WETH for staking, if you are fine with the changes, I will merge it

**Comment by oxSaturn** [comment]
> hi @oxSaturn
> 
> I have updated code to return borrowed amount under 'borrowed' key, and WIG value is converted to WETH for staking, if you are fine with the changes, I will merge it

Looks great to me, thanks for your help!

**Comment by oxSaturn** [comment]
> hi @oxSaturn
> 
> I have updated code to return borrowed amount under 'borrowed' key, and WIG value is converted to WETH for staking, if you are fine with the changes, I will merge it

cc @berabuilder you good with the changes?

**Comment by berabuilder** [comment]
looks good to me

**Comment by berabuilder** [comment]
@g1nt0ki it says  'no' under audits, but they're submitted above. The protocol went through couple name changes but contract code remained the same

**Pull request merged**
