### PR TITLE
Mellow LRT Protocol

### PR DESCRIPTION
**Pull request by yantsant**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage: https://github.com/mellow-finance/mellow-lrt/blob/main/src/oracles/ChainlinkOracle.sol
https://www.notion.so/mellowprotocol/ChainlinkOracle-05372d197f5c4b5ab2c92163d03c8a80

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/MellowProtocol exports TVL: 
        
 
 
    ethereum                  14.23 k
    
    total                    14.23 k

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
is this v2 of the protocol? if so, can you create a new folder for it instead of removing chains from existing adapter?

**Comment by yantsant** [comment]
It's another version, but we need to replace the old one

**Comment by g1nt0ki** [comment]
we usually dont remove old one, but add the new version as sub protocol, example: https://defillama.com/protocol/aave

**Comment by g1nt0ki** [comment]
added it here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/7ba9981e14ce919b3b4aad8a5088b95c90a78fb8

**Pull request closed without merging**
