### PR TITLE
feat: add astherus TVL

### PR DESCRIPTION
**Pull request by langyoung**
This pr submit Astherus TVL, from https://www.astherus.finance

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@langyoung can you fill in rest of the PR form? 


##### Name (to be shown on DefiLlama):


##### Twitter Link:


##### List of audit links if any:


##### Website Link:


##### Logo (High resolution, will be shown with rounded borders):


##### Current TVL:


##### Treasury Addresses (if the protocol has treasury)


##### Chain:


##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)


##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)


##### Short Description (to be shown on DefiLlama):


##### Token address and ticker if any:


##### Category (full list at https://defillama.com/categories) *Please choose only one:


##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
##### Implementation Details: Briefly describe how the oracle is integrated into your project:
##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:

##### forkedFrom (Does your project originate from another project):


##### methodology (what is being counted as tvl, how is tvl being calculated):


##### Github org/user (Optional, if your code is open source, we can track activity):

**Comment by langyoung** [comment]
> @langyoung can you fill in rest of the PR form?
> 
> ##### Name (to be shown on DefiLlama): Astherus
> ##### Twitter Link: https://x.com/AstherusHub
> ##### List of audit links if any:
> ##### Website Link: https://www.astherus.finance
> ##### Logo (High resolution, will be shown with rounded borders): 
color-light

> ##### Current TVL: 11.66 M 
> ##### Treasury Addresses (if the protocol has treasury)
BSC: 0x128463A60784c4D3f46c23Af3f65Ed859Ba87974
ETH: 0x604DD02d620633Ae427888d41bfd15e38483736E
> ##### Chain: 56, 1
> ##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
> ##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
> ##### Short Description (to be shown on DefiLlama): Astherus is a liquidity hub for staked assets such as LSTs (liquid staking tokens) and LRTs (liquid restaking tokens), aiming to scale their utilization and boost user profitability.
> ##### Token address and ticker if any:
> ##### Category (full list at https://defillama.com/categories) *Please choose only one: [Restaking](https://defillama.com/protocols/Restaking)
> ##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
> ##### Implementation Details: Briefly describe how the oracle is integrated into your project:
> ##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
> ##### forkedFrom (Does your project originate from another project):
> ##### methodology (what is being counted as tvl, how is tvl being calculated):
> ##### Github org/user (Optional, if your code is open source, we can track activity):

**Comment by llamatester** [comment]
The adapter at projects/astherus exports TVL: 
        
 
 
    bsc                       10.97 M
    ethereum                  127.88 k
    
    total                    11.10 M

**Comment by g1nt0ki** [comment]
@langyoung thanks for the PR

**Pull request merged**
