### PR TITLE
kiloex add opbnb , manta

### PR DESCRIPTION
**Pull request by kilo-dev1**
##### Name (to be shown on DefiLlama):
Kiloex

##### Twitter Link:
https://twitter.com/KiloEx_perp

##### List of audit links if any:
https://kiloex.gitbook.io/kiloex/about-kiloex/audit

##### Website Link:
https://app.kiloex.io/#/trade

##### Logo (High resolution, will be shown with rounded borders):
img_v2_d23433ee-4e07-4263-b386-97442a4c9dhu

##### Current TVL:
1440000USDT

##### Treasury Addresses (if the protocol has treasury)
BSC vault 0x1c3f35F7883fc4Ea8C4BCA1507144DC6087ad0fb
BSC position 0xfE03be1b0504031e92eDA810374222c944351356
BSC usdt 0x55d398326f99059fF775485246999027B3197955

opbnb vault 0xA2E2F3726DF754C1848C8fd1CbeA6aAFF84FC5B2
opbnb position 0x1EbEd4024308afcb05E6938eF8Ebd1ec5d6E8C46
opbnb usdt 0x9e5aac1ba1a2e6aed6b32689dfcf62a509ca96f3

manta vault 0xA2E2F3726DF754C1848C8fd1CbeA6aAFF84FC5B2
manta position 0x1EbEd4024308afcb05E6938eF8Ebd1ec5d6E8C46
manta usdt 0xf417f5a458ec102b90352f697d6e2ac3a3d2851f

##### Chain:
BSC,opbnb,manta

##### Short Description (to be shown on DefiLlama):
Next generation perp DEX. Lightning-fast trades,risk-neutral positions and LP-friendly solutions ｜BN🔸MVB VI

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Derivatives

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink Pyth

##### methodology (what is being counted as tvl, how is tvl being calculated):
The first part of the TVL calculation comes from the vault stake funds, while the second part is the collateral portion of the traders' positions.

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/kiloex exports TVL: 
        
 
 
    op_bnb                    0
    manta                     0
    bsc                       543.20 k
    
    total                    543.20 k

**Comment by kilo-dev1** [comment]
Kiloex add opbnb , manta

**Comment by kilo-dev1** [comment]
> The adapter at projects/kiloex exports TVL:
> 
> ```
> op_bnb                    0
> manta                     0
> bsc                       543.20 k
> 
> total                    543.20 k 
> ```

Why isn't the TVL calculated for opbnb and manta? I checked the address configuration and everything seems fine. @llamatester

**Comment by kilo-dev1** [comment]
Kiloex add opbnb,manta

**Comment by llamatester** [comment]
The adapter at projects/kiloex exports TVL: 
        
 
 
    op_bnb                    0
    manta                     0
    bsc                       544.21 k
    
    total                    544.21 k

**Comment by llamatester** [comment]
The adapter at projects/kiloex exports TVL: 
        
 
 
    bsc                       543.76 k
    op_bnb                    360.94 k
    manta                     565.08 k
    
    total                    1.47 M

**Comment by g1nt0ki** [comment]
@kilo-dev1 thanks for the PR

**Comment by kilo-dev1** [comment]
> @kilo-dev1 thanks for the PR

Thank you very much. @g1nt0ki

**Pull request merged**
