### PR TITLE
feat: add bitmap-game tvl

### PR DESCRIPTION
**Pull request by turingczz**
**NOTE**

1. add bitmap-game tvl
2. demo like this:
```
merl                      2.69 M
THE•BITMAP•TOKEN          239.01 k
Total: 2.92 M 

```

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### List of audit links if any:
https://github.com/bitmap-game/bitmap-contracts/blob/main/contracts-audit/Bitmap.Game_202408081835.pdf
https://github.com/bitmap-game/bitmap-contracts/blob/main/contracts-audit/Bitmap_FINAL_1724132123370.pdf

##### Logo (High resolution, will be shown with rounded borders): 
https://drive.google.com/file/d/1YqOZbj-4oU5SdCIrAD-h0G_8KGNc5FCf/view?usp=drive_link

##### Current TVL: 2.92 M 
```
merl                      2.69 M
THE•BITMAP•TOKEN          239.01 k
Total: 2.92 M 
```

##### Treasury Addresses (if the protocol has treasury)
the MERL staking contract：
0xb311c4b8091aff30Bb928b17Cc59Ce5D8775b13A 
the bitmap renting contract:
0x8567bD39b8870990a2cA14Df3102a00A7d72f7E3  

##### Chain: 
Merlin Chain

##### Short Description (to be shown on DefiLlama): 
BitmapGame is a metaverse project centered around the bitmap ecosystem. Users can freely chat, edit their owned bitmaps, and explore or enter others’ bitmaps. Within the app, users can engage in various contracts and projects related to the bitmap ecosystem.

##### Token address and ticker if any:
const BITMAP_TOKEN = '0x7b0400231Cddf8a7ACa78D8c0483890cd0c6fFD6'
const MERL_TOKEN = '0x5c46bFF4B38dc1EAE09C5BAc65872a1D8bc87378'

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Gaming

##### methodology (what is being counted as tvl, how is tvl being calculated):
The value of the token in the MERL staking contract plus the value of the token in the bitmap renting contract.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/bitmap-game

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bitmap-game exports TVL: 
        
 
 
    merlin                    2.87 M
    
    total                    2.87 M

**Comment by llamatester** [comment]
The adapter at projects/bitmap-game exports TVL: 
        
 
 
    merlin                    2.91 M
    
    total                    2.91 M

**Comment by llamatester** [comment]
The adapter at projects/bitmap-game exports TVL: 
        
 
 
    merlin                    2.95 M
    
    total                    2.95 M

**Comment by llamatester** [comment]
The adapter at projects/bitmap-game exports TVL: 
        
 
 
    merlin                    2.71 M
    merlin-staking            233.96 k
    staking                   233.96 k
    
    total                    2.71 M

**Comment by llamatester** [comment]
The adapter at projects/bitmap-game exports TVL: 
        
 
 
    merlin                    2.92 M
    
    total                    2.92 M

**Comment by turingczz** [comment]
@g1nt0ki  thanks，We will fill the detail.  for the TVL, We will do it like the new code, it's shown as:
```
merl                      2.69 M
THE•BITMAP•TOKEN          239.01 k
Total: 2.92 M 
```
cloud you help to check it?

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
please revert your change, more details on why I moved your token to staking: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by llamatester** [comment]
The adapter at projects/bitmap-game exports TVL: 
        
 
 
    merlin                    2.87 M
    merlin-staking            2.64 M
    staking                   2.64 M
    
    total                    2.87 M

**Comment by turingczz** [comment]
@g1nt0ki  Thank you very much for your advice.
I revert the code to your changes, and a few modifications were made.
In our project, the staking is merl token; the TVL is merl token and bitmap-token.

**Comment by g1nt0ki** [comment]
sorry, you cant count the same thing in both staking and tvl, it is doublecounting. you can set tvl to `() => ({})`

**Comment by llamatester** [comment]
The adapter at projects/bitmap-game exports TVL: 
        
 
 
    merlin                    2.93 M
    merlin-staking            0
    staking                   0
    
    total                    2.93 M

**Comment by turingczz** [comment]
@g1nt0ki hello, I revert the code to your changes, and a few modifications were made.
I only set the TVL infomation, not have staking.

**Comment by turingczz** [comment]
@g1nt0ki hello, Can I only set the TVL infomation, not have staking?

**Pull request merged**
