### PR TITLE
Added Firefly Dex 

### PR DESCRIPTION
**Pull request by 0xGreatApe**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/firefly exports TVL: 
        
 
 
    manta                     509.49 k
    
    total                    509.49 k

**Comment by 0xGreatApe** [comment]
will make pull request on `dimension-adapters` + `defillama-server` repos with updated info for firefly dex

**Comment by llamatester** [comment]
The adapter at projects/firefly exports TVL: 
        
 
 
    manta                     509.06 k
    
    total                    509.06 k

**Comment by g1nt0ki** [comment]
> will make pull request on `dimension-adapters` + `defillama-server` repos with updated info for firefly dex

thanks for the PR, please fill in the form in the PR description

**Comment by 0xGreatApe** [comment]
I already submitted another PR for the DefiLlama server with this info. Do I need to do it again here?

Name (to be shown on DefiLlama): Firefly
Twitter Link: @FireFlydexZK
List of audit links if any:
https://docs.fireflydex.io/audits-transparency

https://3574364452-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FhcCwYWiw1t9QdK7cp37u%2Fuploads%2FbNfbMUl1UCiuMIQ5u9Ns%2FOfficial-Firefly%20Audit%20-%20Mykyta%20Mesentsev%20-%20Blockchain%20Auditor.pdf?alt=media&token=f03bedc7-6c1c-4445-b53f-421fbe6624fb",

https://3574364452-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FhcCwYWiw1t9QdK7cp37u%2Fuploads%2FxzNN0bjx1FyRCbCpg98e%2FOfficial%20Firefly%20Audit%20Report-%20Ahmed%20Dalhoum.pdf?alt=media&token=44866712-032e-4262-904e-b1ef4d71f59a

Website Link: https://fireflydex.io/
Logo (High resolution, will be shown with rounded borders):
image
Current TVL: 585.54K
Treasury Addresses (if the protocol has treasury)
Chain: Manta
Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed):  
Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): 
Short Description (to be shown on DefiLlama):  With CEX features on a DEX and ultra-fast transactions, firefly is the Premier Modular DEX
Token address and ticker if any:
Category (full list at https://defillama.com/categories) *Please choose only one: Dexs
Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Implementation Details: Briefly describe how the oracle is integrated into your project:
Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
forkedFrom (Does your project originate from another project): Uniswap V3
methodology (what is being counted as tvl, how is tvl being calculated): Counts the tokens locked on AMM pools, pulling the data from the 'firefly/v3' subgraph
Github org/user (Optional, if your code is open source, we can track activity): firefly-dex

**Comment by 0xGreatApe** [comment]
@g1nt0ki You made a mistake with the name. It should only be 'firefly', all lowercase not 'Firefly Dex'

**Pull request merged**
