### PR TITLE
Add superstate-uscc adapter

### PR DESCRIPTION
**Pull request by bcuccioli**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/superstate exports TVL: 
        
 
 
    ethereum                  96.56 M
    
    total                    96.56 M

**Comment by llamatester** [comment]
The adapter at projects/superstate-uscc exports TVL: 
        
 
 
    ethereum                  15.75 M
    
    total                    15.75 M

**Comment by g1nt0ki** [comment]
sorry, rejecting this. we prefer a single listing

**Comment by bcuccioli** [comment]
@g1nt0ki, for context the conversation I had with @bentura on Discord earlier was the following:

> Bryan: Hi, we have the project 'superstate' which was previously associated to the original fund USTB (e.g. on the frontend https://defillama.com/protocol/superstate#information and in the adapter code). We have a second fund now called USCC that we would like to represent on the frontend / in adapter as well. Is it the right way to think about it that both would be shown under /protocol/superstate or would we have two separate pages? Also should there be two separate adapters or just one which refers to both? Sorry these are probably very noob questions but thanks 🙂

> bentura: Hello. Are there any plans to add more funds in the near future? If it is a relative low number of funds, than separate them into a different products/listings would be the best. Also seems that USCC is more like a cash carry trade (basis trading category), while the USTB seems more like yields from t-bills (different category, RWA)
So basically, we just need an adapter to track your new fund. Let us know what name we should use https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/projects

> Bryan: I don't believe in the near future. Should we rename the existing one then such that we have say superstate-ustb and superstate-uscc, or is renaming a bad idea?

> bentura: No no. No need to modify/rename. Just the new adapter tracking the new fund is enough. We will make the changes internally. Add a parentProtocol and rename the current listing. Just make an adapter called superstate-uscc with the respective code. The rest we will take care off

So very possibly I misunderstood and am doing it wrong, but what should I do here? Thanks!

**Comment by g1nt0ki** [comment]
ah, missed that these are two different type of products.

**Comment by llamatester** [comment]
The adapter at projects/superstate exports TVL: 
        
 
 
    ethereum                  96.41 M
    
    total                    96.41 M

**Comment by llamatester** [comment]
The adapter at projects/superstate-uscc exports TVL: 
        
 
 
    ethereum                  15.74 M
    
    total                    15.74 M

**Pull request merged**
