### PR TITLE
Fix TVL for Elixir

### PR DESCRIPTION
**Pull request by cairoeth**
Fixes TVL calculation by counting deUSD and stETH + ETH commits.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/elixir exports TVL: 
        
 
 
    ethereum                  283.90 M
    ethereum-pool2            55.75 M
    pool2                     55.75 M
    arbitrum                  5.99 M
    
    total                    289.89 M

**Comment by g1nt0ki** [comment]
hi @cairoeth what is backing the deUSD? we got complaints that we were doublecounting by including the value of both the commits & deUSD supply

**Comment by cairoeth** [comment]
@g1nt0ki it's backed by USD, like USDT, DAI, etc. -- as you can see in the diff, i removed the backing address and those tokens so there's no double counting

**Comment by g1nt0ki** [comment]
hmm, but deUSD supply is 169m but address you removed has only 53M worth of USDS

**Comment by cairoeth** [comment]
> hmm, but deUSD supply is 169m but address you removed has only 53M worth of USDS

the rest of the backings are distributed across centralized exchange venues to run the basis trade, as noted [here](https://docs.elixir.xyz/deusd/deusd-architecture/centralized-exchange-execution).

**Comment by 0xpeluche** [comment]
Hello @cairoeth , I'm trying to review the adapter to correct the calculations on my end as well. There are some confusing aspects of the mechanisms for minting deUSD. Were the ETH in the COMMITS_VAULT purchased with users' stablecoins? This would mean that when 100k deUSD is minted, 50k is shorted on Coinbase, and 50k is used to buy stETH and deposited in the commits vaults. If that's the case, we can't count both the deUSD and the stETH at the same time

**Comment by cairoeth** [comment]
@0xpeluche stETH tokens have been committed to mint deUSD in December, but they haven't been used yet meaning they are not part of the deUSD supply so there's no double counting. Even once they are used to mint, deUSD supply would increase and stETH balance would decrease so still no double counting.

**Comment by g1nt0ki** [comment]
@cairoeth thanks for the clarification

**Pull request merged**
