### PR TITLE
add DeGate Project

### PR DESCRIPTION
**Pull request by BergDev22**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### List of audit links if any:
https://github.com/degatedev/protocols/blob/degate1.1.0/packages/loopring_v3/security_audit/DeGate_Report_EN-20231115.pdf

##### Website Link:
https://app.degate.com/

##### Logo (High resolution, will be shown with rounded borders):
https://drive.google.com/file/d/1mkDbd1T2h62EZOeW8iEad2r8ElZ72FuT/view

##### Current TVL:
4659k USD

##### Treasury Addresses (if the protocol has treasury)
0x54D7aE423Edb07282645e740C046B9373970a168

##### Chain:
ETH

##### Short Description (to be shown on DefiLlama):
DeGate is an app-specific ZK Rollup that enables a trustless, fast and low-fee decentralized order book exchange, helping users to trade easy and sleep easy. 

##### Token address and ticker if any:
0x53C8395465A84955c95159814461466053DedEDE

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### forkedFrom (Does your project originate from another project):
loopring

##### methodology (what is being counted as tvl, how is tvl being calculated):
Total Value locked in Smart Contracts, 0x53C8395465A84955c95159814461466053DedEDE

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/degatedev/

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@BergDev22 thanks for the PR

**Comment by llamatester** [comment]
The adapter at projects/degate exports TVL: 
        
 
 
    ethereum                  4.65 M
    
    total                    4.65 M

**Comment by BergDev22** [comment]
Thank you for the help! I discovered an issue - on DeGate's TVL page, ETH is showing as WETH. Is there a way to fix this? Does the TVL code need to be modified? @llamatester  https://defillama.com/protocol/degate

**Comment by g1nt0ki** [comment]
Hi @BergDev22 this is unfortunately expected behaviour: https://github.com/DefiLlama/DefiLlama-Adapters/discussions/436

**Comment by BergDev22** [comment]
hi @g1nt0ki , we plan to update the Website Link to https://degate.com/?utm_source=defillama, how should we handle this

**Comment by g1nt0ki** [comment]
hi @BergDev22, sorry,  we dont support this atm, other teams have requested for this and we have said no.

**Pull request merged**
