### PR TITLE
add deri tvl adapter

### PR DESCRIPTION
**Pull request by shibin2021**
##### Description/bio (to be shown on DefiLlama):
Deri is a decentralized protocol for users to exchange risk exposures precisely and capital efficiently. It is the DeFi way to trade derivatives: to hedge, to speculate, to arbitrage, all on chain. This is achieved by liquidity pools playing the roles of counterparties for users. Withe Deri Protocol, risk exposures are tokenized as NFTs so that they can be imported into other DeFi projects for their own financial purposes. Having provided an effective on-chain mechanism to exchange and hold risk, Deri Protocol has minted one of the most important blocks of the DeFi infrastructure.

Deri V2 inherits all the features of V1 but supports several key new features, such as dynamic mixed margin and liquidity-providing. With such features of Deri V2, multiple tokens are supported as base tokens for liquidity providers to provide as liquidity as well as for traders to deposit as margin. Such a dynamic mixed margin and liquidity framework becomes feasible in the DeFi world because of the functionalities provided by other DeFi infrastructures. Within the framework of Deri V2, derivative trading can achieve an optimal capital efficiency, which is potentially higher than that of centralized exchanges.

##### Token address and ticker if any:
BSC: 0xe60eaf5A997DFAe83739e035b005A33AfdCc6df5
Polygon: 0x3D1D2aFd191b165D140e3E8329E634665fFB0E5e

##### [Optional] ETH addresss (to receive a LlamaPunk):0xa487bf43cf3b10dffc97a9a744cbb7036965d3b9

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hi, @shibin2021 I noticed that you did not add the eth address for Deri (0xa487bf43cf3b10dffc97a9a744cbb7036965d3b9). Should this be included as well?

**Comment by shibin2021** [comment]
Hi @realdealshaman As we haven't deploy V2 pool to Ethereum mainnet, so the current submit is not include the eth tvl.

There are some changes/fix to this PR, could you help with the request below?
1. The project name is "Deri Protocol", not the "Deri".
2. The logo url is updated to "https://app-bak.deri.finance/logo.png"

**Comment by realdealshaman** [comment]
Sure thing, consider it done!

**Comment by shibin2021** [comment]
Thank you, @realdealshaman.  If we team delpoyed a new pool and want to update the tvl adapter, I must request a new PR, right?

**Comment by realdealshaman** [comment]
Yes, please

**Pull request merged**
