### PR TITLE
Add railgun project

### PR DESCRIPTION
**Pull request by liucougar**
##### Twitter Link:
https://twitter.com/railgun_project

##### List of audit links if any:
http://assets.railgun.ch/docs/audits/Railgun%20Audit%20Report%20-%20Zokyo%20November%202021.pdf

https://bafybeiakdhweojvf7zvtp2tr32alzam4yyifbolf7fgrmsshalea7fv55m.ipfs.cf-ipfs.com/docs/Railgun%20Audit%20Report%20-%20ABDK%20July%202021.pdf

##### Website Link:
https://railgun.org/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://assets.railgun.ch/logo

##### Current TVL:
--- ethereum ---
RAIL                      126.63 M
DAI                       254.36 k
USDT                      482.55005431
USDC                      70.4437125
WETH                      35.51934963311826
RENBTC                    1.09932656
MATIC                     0.10017225
SUSHI                     0.016925
RENZEC                    2.3005975e-10
Total: 126.89 M 

--- tvl ---
RAIL                      126.63 M
DAI                       254.36 k
USDT                      482.55005431
USDC                      70.4437125
WETH                      35.51934963311826
RENBTC                    1.09932656
MATIC                     0.10017225
SUSHI                     0.016925
RENZEC                    2.3005975e-10
Total: 126.89 M 

------ TVL ------
ethereum                  126.89 M

total                    126.89 M

##### Chain:
ETH

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
8771

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
3271

##### Short Description (to be shown on DefiLlama):
RAILGUN secures privacy for DEX trading and lending. Built without any bridge or layer-2, RAILGUN is a smart contract system that gives zk-SNARK privacy to any transaction or smart contract interaction on Ethereum.
Using Railgun means users can be untraceable when they trade, use leverage platforms, or add liquidity, with absolutely any dApp on ETH. It allows any user to build up a private balance and trade through it without withdrawing. It is fully on eth layer-1, so it does not trade off security by using layer 2 node system or cross-chain bridges.
RAIL token is the governance token for the RAILGUN DAO, staking these brings special government and economic rights and privileges over the Railgun system.
RAILGUN is already for deployed on Ethereum, BSC, Polygon and more to come.

##### Token address and ticker if any:
RAIL 0xe76c6c83af64e4c60245d8c7de953df673a7a33d
Other contracts:
  delegator: '0xb6d513f6222ee92fff975e901bd792e2513fb53b',
  implementation: '0xc6368d9998ea333b37eb869f4e1749b9296e6d09',
  proxy: '0xbf0Af567D60318f66460Ec78b464589E3f9dA48e',
  proxyAdmin: '0x4f8e20f55f879bee7bc010bd6bd2138b34ac65c8',
  staking: '0xee6a649aa3766bd117e12c161726b693a1b2ee20',
  treasury: '0xc851fbe0f07a326ce0326ccc70c2a62732e74d6c',
  voting: '0xfc4b580c9bda2eef4e94d9fb4bcb1f7a61660cf9',

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Staking
We would prefer Privacy category, if such category exists

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
N/A

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
RAILGUN staked in the staking contract
All ERC20 tokens in the treasury

### CODE REVIEW

**Comment by waynebruce0x** [comment]
since RAIL is your native platform token can this be exported as 'staking'? and the treasury exported separately as 'treasury'? with tvl as (async) => ({})

**Comment by liucougar** [comment]
are you suggesting 2 separate adapters please? or a single one?

do you have an example on exporting "tvl as (async) => ({})"?

**Comment by waynebruce0x** [comment]
like everipedia, but instead of 'staking', you'll want a 'treasury' export

**Comment by waynebruce0x** [comment]
> since RAIL is your native platform token can this be exported as 'staking'? and the treasury exported separately as 'treasury'? with tvl as (async) => ({})

This would set your core TVL to 0 but shouldnt you count the tokens in 0xbf0af567d60318f66460ec78b464589e3f9da48e? Feel free to send a message in our discord server if you need a hand https://discord.gg/buPFYXzDDd

**Comment by liucougar** [comment]
Is this what you are suggesting please?
thanks

**Pull request merged**
