### PR TITLE
Add Juicebox (adapters for V1, V2 and V3)

### PR DESCRIPTION
**Pull request by xBA5ED**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Juicebox

##### Twitter Link:
https://twitter.com/juiceboxETH

##### List of audit links if any:
- [V1 - Hacken](https://hacken.io/wp-content/uploads/2022/01/%D0%A1onstitution-DAO_11012022Audit_Report.pdf)
- [V2 - Certik](https://docs.juicebox.money/assets/files/certik-audit-report-12b48328d22ac38207dad74162cac1db.pdf/)
- [V2 - PeckShield](https://docs.juicebox.money/assets/files/peckshield-audit-report-ab36ee2b5dfb2a387410b4d64276f6ba.pdf/)
- [V3 Migration - berndartmueller](https://hackmd.io/@berndartmueller/2023-01-juice-v3-migration)
- [V3 721Delegate - Code4rena](https://code4rena.com/reports/2022-10-juicebox/)

##### Website Link:
[https://juicebox.money/](https://juicebox.money/)

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://docs.juicebox.money/assets/files/jb-pfp-3e426a72d0ee2c1dc88dd5380a219f90.png/

##### Current TVL:
`15.706 M`

##### Chain:
Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
juicebox

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
15456

##### Short Description (to be shown on DefiLlama):
The programmable crypto fundraising protocol for builders and creators. Light enough for a group of friends, powerful enough for a global network of anons. Community-owned, on Ethereum.

##### Token address and ticker if any:
Ticker: `JBX`

Address: `ETH:0x3abf2a4f8452ccc2cf7b4c1e4663147600646f66`

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Launchpad

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### methodology (what is being counted as tvl, how is tvl being calculated):
All Ether in Juicebox terminals from V1, V2 and V3 are being counted towards TVL.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/juicebox-v1 exports TVL: 
        
 
 
    ethereum                  12.77 M
    
    total                    12.77 M

**Comment by llamatester** [comment]
The adapter at projects/juicebox-v2 exports TVL: 
        
 
 
    ethereum                  86.08 k
    
    total                    86.08 k

**Comment by llamatester** [comment]
The adapter at projects/juicebox-v3 exports TVL: 
        
 
 
    ethereum                  2.73 M
    
    total                    2.73 M

**Comment by g1nt0ki** [comment]
hi xBased, thanks for the PR

**Pull request merged**
