### PR TITLE
feat: update prePO page and TVL

### PR DESCRIPTION
**Pull request by ramenforbreakfast**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
N/A (Do not change)

##### Twitter Link:
N/A (Do not change)

##### List of audit links if any:
N/A (Do not change)

##### Website Link:
https://app.prepo.io

##### Logo (High resolution, will be shown with rounded borders):
N/A (Do not change)

##### Current TVL:
~$121.8k

##### Treasury Addresses (if the protocol has treasury)
N/A (Do not change)

##### Chain:
Blast (81457)

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
N/A (Do not change)

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A (Do not change)

##### Short Description (to be shown on DefiLlama):
N/A (Do not change)

##### Token address and ticker if any:
N/A (Do not change)

##### Category (full list at https://defillama.com/categories) *Please choose only one:
N/A (Do not change)

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
N/A (Do not change)
##### Implementation Details: Briefly describe how the oracle is integrated into your project:
N/A (Do not change)
##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
N/A (Do not change)

##### forkedFrom (Does your project originate from another project):
N/A (Do not change)

##### methodology (what is being counted as tvl, how is tvl being calculated):
WETH and USDB balance of our markets contracts, contracts addresses are listed in our FAQs here https://intercom.help/prePO-help-center/en/articles/9227580-what-are-the-deployed-contract-addresses-for-prepo-v2

##### Github org/user (Optional, if your code is open source, we can track activity):
Remove development activity section since our repo is not public.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/prePo exports TVL: 
        
 
 
    blast                     121.28 k
    
    total                    121.28 k

**Comment by ramenforbreakfast** [comment]
This is a request to update our existing page, any item that has "N/A" means that we do not want this item added or changed from our existing page.

In summary we'd like the following items updated:
- How TVL is calculated, using the new submitted adapter
- Update the website link
- Remove the development activity section

**Comment by llamatester** [comment]
The adapter at projects/prePo exports TVL: 
        
 
 
    blast                     118.88 k
    
    total                    118.88 k

**Comment by g1nt0ki** [comment]
@ramenforbreakfast thaks, included your changes here. we like to include old chain data: https://github.com/DefiLlama/DefiLlama-Adapters/commit/1fbdbf6dce88ad40089b181957acc34f61142a65

**Pull request closed without merging**
