### PR TITLE
Correct TVL for Anzen Finance

### PR DESCRIPTION
**Pull request by bshyong**
**NOTE**
This PR corrects the inaccurate TVL calculation for Anzen Finance merged in https://github.com/DefiLlama/DefiLlama-Adapters/pull/8874

Anzen's TVL should be pulled directly from a single contract SPCT 0xEf5AAcB3c38a5Be7785a361008e27fb0328a62B5 as the source of truth.

SPCT requires USDC deposit to mint.  Additionally deposited USDC in the related contract PCT will automatically be sent to SPCT contract to mint SPCT. Burning SPCT returns USDC to owner and reduces the TVL.

Borrowed amount is calculated by using `executedShares` converted to a USD value using `pooledUSDByShares(shareAmount)`.

Anzen currently has $1.25M TVL and 0% capital utilization rate, so the current borrow amount is 0.

---
##### Name (to be shown on DefiLlama):
Anzen Private Credit

##### Twitter Link:
https://twitter.com/anzenfinance

##### Website Link:
https://anzen.finance/

##### Current TVL:
1.25M

##### Chain:
Ethereum

##### Short Description (to be shown on DefiLlama):
On-chain, institutional grade real world assets

##### Category (full list at https://defillama.com/categories) *Please choose only one:
RWA

##### methodology (what is being counted as tvl, how is tvl being calculated):
Sums the total USDC value deposited to mint SPCT.

### CODE REVIEW

**Comment by g1nt0ki** [comment]
who issues the PCT?

**Comment by bshyong** [comment]
Anzen issues PCT.

**Comment by g1nt0ki** [comment]
okay, here is the issue. When user deposits USDC, it is transferred out our the deposit contract and given as loans in the real world right? We consider this "Uncollateralized Lending"  and count only the tokens still in contract as tvl, and rest as borrowed: https://defillama.com/protocols/Uncollateralized%20Lending

**Comment by bshyong** [comment]
@g1nt0ki I understand that; however we are legally structured like Ondo instead.

The SPCT is equivalent to their OUSG. Anzen SPCT denotes legal ownership in an investment fund that invests in private credit deals.  Ondo OUSG denotes legal ownership in an investment fund that invests in off-chain TBills.

https://defillama.com/protocol/ondo-finance
https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/ondofinance/index.js 

SPCT/OUSG requires KYC and minimum $100,000 deposit size.

PCT is a permissionless token - when user deposits USDC, they get PCT 1:1. These funds can be borrowed by Anzen to mint SPCT owned by the protocol itself.  In this way, PCT holders can also get yields if they are not able to hold SPCT/OUSG directly.

**Comment by g1nt0ki** [comment]
but in ondo's case, it is USG bonds right? if PCTs are bonds/shares traded in stock market and are tokenized, that would be fair comparison, that is not the case here right?

**Comment by bshyong** [comment]
Anzen SPCT is true, legally tokenized fund shares, therefore it is reasonable to reflect TVL that way. SPCT/PCT are always pegged to $1 USDC of assets.

Some other RWA protocols include [Tangible RWA](https://defillama.com/protocol/tangible-rwa) where the TVL reflects the value of tokenized RWA in the protocol, which is mostly real estate properties.  

Anzen has been backed by Circle, Frax, and several other investors to directly tokenize private credit assets so that they are accessible on chain. Through the tokens, this makes the assets freely tradeable. This enables DAOs, Protocols, and general DeFi users to access the RWA-backed yields permissionlessly, on-chain.

**Comment by g1nt0ki** [comment]
@bshyong I am not questioning legitimacy of the project but what I am saying is, this is not tokenization of real world asset like land/stocks or bonds.

**Comment by bshyong** [comment]
I understand what you mean - in this case the assets we are tokenizing are definitely RWA. Our underlying is asset-backed securities (ABS). Using "loan" is not accurate as we are not doing direct lending, we are tokenizing securities. 

In a similar vein, there are several RWA protocols tokenizing private securities, for example shares in non-public startups. Those shares are securities that are not publicly traded but through tokenization, they can be traded on-chain.  

The reason we must use SPCT is that it reflects the true TVL of the assets backing the protocol. After we finish setting up Proof of Reserve with Chainlink, it doesn't make sense for the PoR to show $1.25M but TVL is only $0.05M

**Comment by g1nt0ki** [comment]
hi @bshyong, I am still trying to wrap my head around this part, when USDC is deposited and PCT is minted, what happens to the USDC? there is some mechanism where this is converted to fiat and lent out to private companies?

**Comment by bshyong** [comment]
@g1nt0ki When USDC is deposited and PCT is minted, the USDC is sent to SPCT contract to mint SPCT. 

SPCT is like a security token and represents ownership in true assets. For clarity, SPCT is a pure RWA asset;  the on-chain mechanism for SPCT/PCT works like a stablecoin. 1 token always represents a $1 claim on the value of underlying RWA, so it is pegged to 1 USDC.

Therefore for TVL purposes, this is why we only need to call the SPCT contract and ignore PCT, so there is no double counting.  Anzen SPCT is essentially like [OUSG](https://defillama.com/protocol/ondo-finance), [USYC](https://defillama.com/protocol/hashnote-usyc), [USDM](https://defillama.com/protocol/mountain-protocol), [TNGBL](https://defillama.com/protocol/tangible-rwa) and many other RWAs.

**Pull request closed without merging**
