### PR TITLE
Verified Network / tokenized RWA TVL

### PR DESCRIPTION
**Pull request by kallolborah**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

Verified Network

##### Twitter Link:

https://x.com/veridefi

##### List of audit links if any:

NA

##### Website Link:

www.verified.network

##### Logo (High resolution, will be shown with rounded borders):

Verified 4096 x 2304

##### Current TVL:

USDC 100.15 million

##### Treasury Addresses (if the protocol has treasury)

NA

##### Chain:

Ethereum, Base

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

NA

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

NA

##### Short Description (to be shown on DefiLlama):

The Verified Network is decentralized financial infrastructure connecting issuers, distributors and servicers of tokenized real world assets.

##### Token address and ticker if any:

NA

##### Category (full list at https://defillama.com/categories) *Please choose only one:

RWA

##### forkedFrom (Does your project originate from another project):

No

##### methodology (what is being counted as tvl, how is tvl being calculated):

TVL is calculated as security tokens issued multiplied by price denominated in currency (eg, USDC) at which the security tokens are issued at

##### Github org/user (Optional, if your code is open source, we can track activity):

https://github.com/verified-network

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/verified exports TVL: 
        
 
 
    base                      50.00 M
    ethereum                  50.00 M
    
    total                    100.00 M

**Comment by g1nt0ki** [comment]
I am sorry, but I find it bit hard to believe that users deposited 50M and minted ZTLN on ethereum

**Comment by GemsGame** [comment]
I think you should make proof on numbers by on-chain metrics

**Comment by kallolborah** [comment]
> I am sorry, but I find it bit hard to believe that users deposited 50M and minted ZTLN on ethereum

The first PR we had created a couple of months back counted subscribed capital as TVL. We were told to count minted security tokens as TVL, so we did that which is in this PR.

**Comment by g1nt0ki** [comment]
hi @kallolborah sorry for the late response. I am bit confused as to why you are counting all issued tokens as tvl, did users deposit 100M off chain? 
Also, we made separate listing for zoth, what is the relationship between the two projects? https://github.com/DefiLlama/DefiLlama-Adapters/pull/11578

**Comment by kallolborah** [comment]
@g1nt0ki 

1. We had raised a PR some months back - https://github.com/DefiLlama/DefiLlama-Adapters/pull/10175 where the methodology was mentioned as following, but the PR was rejected for some reason, so we ended up with this one where the number of tokens minted is accounting for TVL. I think we should go back to the previous version. Let us know.
---- from previous PR ----
Cash swapped in to Verified liquidity pools is counted as TVL, and is calculated as follows for
Primary pool : cash swapped in for subscribing to RWA tokens
Secondary pool : cash swapped in for trading RWA tokens (price of RWA token * amount traded)
Margin pool : cash swapped in for trading RWA derivatives ((amount of currency/amount of RWA tokens) * amount traded)
----end-----

2. Zoth is a client and has a token which is minted by a liquidity pool contract on the Verified Network, which is a system of contracts for issuing, distributing and servicing security (RWA) tokens. We have other clients which are not crypto firms like Zoth, and we will keep adding pool addresses frequently. If you do not wish to account for Zoth on Verified, then we can remove the Zoth pool address.

**Comment by g1nt0ki** [comment]
hi @kallolborah I rejected the earlier PR because the project was not yet live.


Current adapter has two issue:

1. right now, only 125k worth of ZTLN is in circulation but you are showing 100M tvl

2. We are already tracking Zoth, this sort of would end up as doublecounting, this is admittedly bit of a grey area, zoth is using you as infrastructure, in the past, for similar cases, we attributed the tvl to the client.

**Pull request closed without merging**
