### PR TITLE
added shimmersea adapter

### PR DESCRIPTION
**Pull request by tanglenaut87**
This PR consists of adding a new dex: ShimmerSea.

Name (to be shown on DefiLlama):
ShimmerSea

Twitter Link:
https://twitter.com/ShimmerSeaDEX

List of audit links if any:
https://github.com/HashEx/public_audits/blob/master/ShimmerSea/ShimmerSea.pdf

Website Link:
https://shimmersea.finance/

Logo (High resolution, will be shown with rounded borders):
https://www.file.io/UNIQ/download/1wWZhC8Zi6h6

Current TVL:
~15.000$

Treasury Addresses (if the protocol has treasury)
n/a

Chain:
ShimmerEVM

Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
n/a

Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
n/a

Short Description (to be shown on DefiLlama):
ShimmerSea is a leading decentralized exchange (DEX) on Shimmer focused on offering a premier trading experience.

Token address and ticker if any:
n/a

Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
n/a

forkedFrom (Does your project originate from another project):
Uniswap

methodology (what is being counted as tvl, how is tvl being calculated):
Counts the tokens locked on AMM pools, pulling the data from subgraph

Github org/user (Optional, if your code is open source, we can track activity):
n/a

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/shimmersea: 
        
 
  
    
    
    Error: Couldn't find block height for chain shimmer_evm, RPC node rugged
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:249:27

**Comment by tanglenaut87** [comment]
The new chain was added 5 days ago https://github.com/DefiLlama/defillama-sdk/blob/master/src/providers.json 
Is it just not published yet or is it necessary to add the chain information for shimmer_evm somewhere else to be in effect for dex listings?

**Comment by llamatester** [comment]
Error while running adapter at projects/shimmersea: 
        
 
  
    
    
    Error: Couldn't find block height for chain shimmer_evm, RPC node rugged
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:249:27

**Comment by llamatester** [comment]
Error while running adapter at projects/shimmersea: 
        
 
  
    
    
    TypeError: Cannot read properties of null (reading 'call')
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/abi/index.js:182:82
        at new Promise (<anonymous>)

**Pull request merged**
