### PR TITLE
Add bsc quartz-defi

### PR DESCRIPTION
**Pull request by quartz-defi**
##### Twitter Link: 
https://twitter.com/quartz_defi

##### Website Link: 
https://bsc-quartz-defi.app/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://raw.githubusercontent.com/quartz-defi/brand-assets/main/tokens%20ames/brand/token/ames-token-1600-round.png

##### Current TVL:
$312,000

##### Chain:
BSC

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
[AMES - amethyst](https://www.coingecko.com/en/coins/amethyst)
[ASHARE - quartz-defi-ashare](https://www.coingecko.com/en/coins/amethyst)

##### Short Description (to be shown on DefiLlama):
AMES is an UST pegged algorithmic stablecoin ecosystem running on BNB blockchain.

The protocol's underlying mechanisms are designed in a way to ensure a peg of AMES:UST is achieved, and once achieved, it is maintained to establish $AMES as a mirrored, liquid asset to $UST. Protocol accomplishes this by introducing unique economic and game-theory centric dynamics into the market through its three tokens.

##### Token address and ticker if any:
AMES - 0xb9e05b4c168b56f73940980ae6ef366354357009
ASHARE - 0xfa4b16b0f63f5a6d0651592620d585d308f749a4

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Yield

##### forkedFrom (Does your project originate from another project):
Unite.finance

##### methodology (what is being counted as tvl, how is tvl being calculated):
The TVL of Quartz.Defi is calculated using the Pancake LP token deposits (AMES/UST, ASHARE/UST, 1QSHARE/UST) in the farms, and the ASHARE deposits found in the Boardroom.

### CODE REVIEW

**Comment by waynebruce0x** [comment]
On line 26 havent these tokens been counted in staking? Same with pool2 tokens on lines 40, 53, 66

**Comment by quartz-defi** [comment]
> On line 26 havent these tokens been counted in staking? Same with pool2 tokens on lines 40, 53, 66

thanks for the reply @waynebruce0x 

You mean that we don't really need that TVL method then?

**Comment by Nemusonaneko** [comment]
Wrote a new adapter and ended up with this. Do these look correct?|
```
$ node test.js projects/quartzdefi_bsc/index.js 
--- bsc ---
Total: 0

--- bsc-staking ---
ASHARE                    55.48 k
Total: 55.48 k

--- bsc-pool2 ---
UST                       109.89 k
AMES                      52.36 k
QSHARE                    34.79 k
ASHARE                    19.01 k
Total: 216.05 k

--- tvl ---
Total: 0

--- staking ---
ASHARE                    55.48 k
Total: 55.48 k

--- pool2 ---
UST                       109.89 k
AMES                      52.36 k
QSHARE                    34.79 k
ASHARE                    19.01 k
Total: 216.05 k

------ TVL ------
bsc                       0
bsc-staking               55.48 k
bsc-pool2                 216.05 k
staking                   55.48 k
pool2                     216.05 k

total                    0```

**Comment by quartz-defi** [comment]
> Wrote a new adapter and ended up with this. Do these look correct?|
> 
> ```
> $ node test.js projects/quartzdefi_bsc/index.js 
> --- bsc ---
> Total: 0
> 
> --- bsc-staking ---
> ASHARE                    55.48 k
> Total: 55.48 k
> 
> --- bsc-pool2 ---
> UST                       109.89 k
> AMES                      52.36 k
> QSHARE                    34.79 k
> ASHARE                    19.01 k
> Total: 216.05 k
> 
> --- tvl ---
> Total: 0
> 
> --- staking ---
> ASHARE                    55.48 k
> Total: 55.48 k
> 
> --- pool2 ---
> UST                       109.89 k
> AMES                      52.36 k
> QSHARE                    34.79 k
> ASHARE                    19.01 k
> Total: 216.05 k
> 
> ------ TVL ------
> bsc                       0
> bsc-staking               55.48 k
> bsc-pool2                 216.05 k
> staking                   55.48 k
> pool2                     216.05 k
> 
> total                    0``` 
> ```

yup it does! do I need to update my code with it? Thanks mate!

**Comment by Nemusonaneko** [comment]
>yup it does! do I need to update my code with it? Thanks mate!

No need. Thanks for confirming!
https://github.com/DefiLlama/DefiLlama-Adapters/commit/e9667df46c0a47e43d8704e3083c0d11534c6c37

**Comment by Nemusonaneko** [comment]
Just realized you have a protocol on harmony. Should we track those together?

**Comment by quartz-defi** [comment]
> Just realized you have a protocol on harmony. Should we track those together?

Yup that would be great! What do you need from us for that one?

**Comment by Nemusonaneko** [comment]
> Yup that would be great! What do you need from us for that one?

No need. Just rewrote the adapter. How does this look?

```
$ node test.js projects/quartzdefi/index.js
--- harmony ---
Total: 0

--- bsc ---
Total: 0

--- bsc-staking ---
ASHARE                    60.06 k
Total: 60.06 k

--- bsc-pool2 ---
UST                       109.33 k
AMES                      52.64 k
QSHARE                    34.31 k
ASHARE                    18.35 k
Total: 214.63 k

--- harmony-staking ---
QSHARE                    23.72 k
Total: 23.72 k

--- harmony-pool2 ---
UST                       43.50 k
QUARTZ                    42.77 k
QSHARE                    18.51 k
WONE                      18.35 k
Total: 123.13 k

--- tvl ---
Total: 0

--- staking ---
ASHARE                    60.06 k
QSHARE                    23.72 k
Total: 83.78 k

--- pool2 ---
UST                       152.82 k
QSHARE                    52.82 k
AMES                      52.64 k
QUARTZ                    42.77 k
ASHARE                    18.35 k
WONE                      18.35 k
Total: 337.76 k

------ TVL ------
harmony                   0
bsc                       0
bsc-staking               60.06 k
bsc-pool2                 214.63 k
harmony-staking           23.72 k
harmony-pool2             123.13 k
staking                   83.78 k
pool2                     337.76 k

total                    0

**Comment by Nemusonaneko** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters/commit/a10ab21d3a33ecdeb3316c0e7edcb1eef604c59f

Commit ^

**Comment by quartz-defi** [comment]
> > Yup that would be great! What do you need from us for that one?
> 
> No need. Just rewrote the adapter. How does this look?
> 
> ```
> $ node test.js projects/quartzdefi/index.js
> --- harmony ---
> Total: 0
> 
> --- bsc ---
> Total: 0
> 
> --- bsc-staking ---
> ASHARE                    60.06 k
> Total: 60.06 k
> 
> --- bsc-pool2 ---
> UST                       109.33 k
> AMES                      52.64 k
> QSHARE                    34.31 k
> ASHARE                    18.35 k
> Total: 214.63 k
> 
> --- harmony-staking ---
> QSHARE                    23.72 k
> Total: 23.72 k
> 
> --- harmony-pool2 ---
> UST                       43.50 k
> QUARTZ                    42.77 k
> QSHARE                    18.51 k
> WONE                      18.35 k
> Total: 123.13 k
> 
> --- tvl ---
> Total: 0
> 
> --- staking ---
> ASHARE                    60.06 k
> QSHARE                    23.72 k
> Total: 83.78 k
> 
> --- pool2 ---
> UST                       152.82 k
> QSHARE                    52.82 k
> AMES                      52.64 k
> QUARTZ                    42.77 k
> ASHARE                    18.35 k
> WONE                      18.35 k
> Total: 337.76 k
> 
> ------ TVL ------
> harmony                   0
> bsc                       0
> bsc-staking               60.06 k
> bsc-pool2                 214.63 k
> harmony-staking           23.72 k
> harmony-pool2             123.13 k
> staking                   83.78 k
> pool2                     337.76 k
> 
> total                    0
> ```

looks good! I think it's just missing the QUARTZ single staking farm. Do you think it would be possible to add that as well? It's poolId 4

**Comment by Nemusonaneko** [comment]
>looks good! I think it's just missing the QUARTZ single staking farm. Do you think it would be possible to add that as well? It's poolId 4

Is it staked in the xQUARTZ contract? If not, can you provide me with the contract the QUARTZ is staked in? Thanks!

**Comment by quartz-defi** [comment]
> > looks good! I think it's just missing the QUARTZ single staking farm. Do you think it would be possible to add that as well? It's poolId 4
> 
> Is it staked in the xQUARTZ contract? If not, can you provide me with the contract the QUARTZ is staked in? Thanks!

oh right also forgot about the xquartz one:

xquartz -> 0xCa1dd590C3ceBa9F57E05540B91AB3F0Ed08580a
single quartz farm -> 0x1da194F8baf85175519D92322a06b46A2638A530

**Comment by Nemusonaneko** [comment]
```$ node test.js projects/quartzdefi/index.js
--- bsc ---
Total: 0

--- harmony ---
Total: 0

--- bsc-staking ---
ASHARE                    60.17 k
Total: 60.17 k

--- bsc-pool2 ---
UST                       109.33 k
AMES                      55.00 k
QSHARE                    34.50 k
ASHARE                    18.50 k
Total: 217.32 k

--- harmony-staking ---
QUARTZ                    402.06 k
QSHARE                    23.88 k
Total: 425.94 k

--- harmony-pool2 ---
UST                       43.56 k
QUARTZ                    42.75 k
QSHARE                    18.66 k
WONE                      18.46 k
Total: 123.43 k

--- tvl ---
Total: 0

--- staking ---
QUARTZ                    402.06 k
ASHARE                    60.17 k
QSHARE                    23.88 k
Total: 486.10 k

--- pool2 ---
UST                       152.89 k
AMES                      55.00 k
QSHARE                    53.16 k
QUARTZ                    42.75 k
ASHARE                    18.50 k
WONE                      18.46 k
Total: 340.75 k

------ TVL ------
bsc                       0
harmony                   0
bsc-staking               60.17 k
bsc-pool2                 217.32 k
harmony-staking           425.94 k
harmony-pool2             123.43 k
staking                   486.10 k
pool2                     340.75 k

total                    0

**Comment by quartz-defi** [comment]
> ```
> --- bsc ---
> Total: 0
> 
> --- harmony ---
> Total: 0
> 
> --- bsc-staking ---
> ASHARE                    60.17 k
> Total: 60.17 k
> 
> --- bsc-pool2 ---
> UST                       109.33 k
> AMES                      55.00 k
> QSHARE                    34.50 k
> ASHARE                    18.50 k
> Total: 217.32 k
> 
> --- harmony-staking ---
> QUARTZ                    402.06 k
> QSHARE                    23.88 k
> Total: 425.94 k
> 
> --- harmony-pool2 ---
> UST                       43.56 k
> QUARTZ                    42.75 k
> QSHARE                    18.66 k
> WONE                      18.46 k
> Total: 123.43 k
> 
> --- tvl ---
> Total: 0
> 
> --- staking ---
> QUARTZ                    402.06 k
> ASHARE                    60.17 k
> QSHARE                    23.88 k
> Total: 486.10 k
> 
> --- pool2 ---
> UST                       152.89 k
> AMES                      55.00 k
> QSHARE                    53.16 k
> QUARTZ                    42.75 k
> ASHARE                    18.50 k
> WONE                      18.46 k
> Total: 340.75 k
> 
> ------ TVL ------
> bsc                       0
> harmony                   0
> bsc-staking               60.17 k
> bsc-pool2                 217.32 k
> harmony-staking           425.94 k
> harmony-pool2             123.43 k
> staking                   486.10 k
> pool2                     340.75 k
> 
> total                    0
> ```

that's it! awesome! Is there any assets or copy that you need for the listing on the Defillama app? Thanks again

**Comment by Nemusonaneko** [comment]
>that's it! awesome! Is there any assets or copy that you need for the listing on the Defillama app? Thanks again
No need. I'll get it listed right away.

**Pull request closed without merging**
