### PR TITLE
Add new SwissBorg wallets

### PR DESCRIPTION
**Pull request by antoineborg**
This PR updates the list of wallets owned by SwissBorg. New wallets addition: https://github.com/SwissBorg/pub/commit/e72ba1486fd4b2a95f27fe437b0c511e6201ec77

### CODE REVIEW

**Comment by llamabutler** [comment]
Error while running adapter at projects/swissborg: 
        
 
  
    
    
    Error: Failed to post https://api.mainnet-beta.solana.com
    Truncated error stack:
    
        at Object.post (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/http.js:47:11)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:282:29
        at async runInChunks (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:405:22)
        at async Object.sumTokens2 (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:229:20)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:173:9
        at async Promise.all (index 0)
        at async Promise.all (index 5)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:216:3

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
hi @antoineborg this code is bit outdated, we have moved all bitcoin addresses to an address book (makes it easier for us to detect two projects using the same BTC address)

Can you add the new BTC address here: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/helper/bitcoin-book/swissborg.js#L7

**Comment by antoineborg** [comment]
hey @g1nt0ki, it's a new addresses for ETH/SOL, no new Bitcoin address :)

**Comment by g1nt0ki** [comment]
@antoineborg damn, I am stupid

**Pull request merged**
