### PR TITLE
add bouncebit-cedefi project

### PR DESCRIPTION
**Pull request by Adolf998**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
BounceBit Cedefi

##### Twitter Link:
https://x.com/bounce_bit

##### Website Link:
https://portal.bouncebit.io/

##### Logo (High resolution, will be shown with rounded borders):
https://oss.bouncebit.io/29c9b1cf446531298a67405329186221-1731294347.png

##### Chain:
ETH
BSC
BounceBit

##### Short Description (to be shown on DefiLlama):
BounceBit CeDeFi combines CeFi and DeFi to generate yield on various assets across multiple chains. The yield is generated via delta-neutral basis trading on centralized exchanges, facilitated by CEX-integrated custody solutions like CEFFU. BounceBit CeDeFi uses the ERC-4626 Tokenized Vault Standard to enable daily rebasing of generated revenue.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Basis Trading

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/BounceBit-Labs

### CODE REVIEW

**Comment by Adolf998** [comment]
We will launch Cedefi V2 version and re-align the different protocols (premium\easy) tomorrow, the overall presentation of Defillama information is clearer in this submission, the project name is BounceBit Cedefi.
BounceBit Cedefi we previously used it as a summary display.After the submit , please help us to delete or hide Bouncebit Premium and Easy, thank you!

**Comment by Adolf998** [comment]
We will be launching the Cedefi V2 version tomorrow, where we have aggregated the previously separated protocols (BounceBit Premium and BounceBit Easy). The PR information submitted this time provides a clearer overall display under the project name “BounceBit Cedefi. After the update, please help us delete or hide the “BounceBit Premium”and “BounceBit Easy”protocols on the Defillama site. Thank you!

**Review by g1nt0ki — COMMENTED** [review]
@Adolf998 thanks for the PR, but is there a graph endpoint to pull the numbers from? current implementation works if it is a small number of logs, but afraid that is not the case here.

**Comment by Adolf998** [comment]
The graph has not been deployed yet, but we are already preparing.
Previously we submitted a dedicated private RPC for DefiLlama that you can use to pull the numbers more reliably. Maybe this can be a good temporary solution.

**Comment by g1nt0ki** [comment]
hmm, the issue is, current rpc setup is common for all adapters, dont want to overload the private rpc. maybe we wait for the graph to be ready?

**Comment by llamatester** [comment]
The adapter at projects/bouncebit-cedefi exports TVL: 
        
 
 
    bouncebit                 171.54 M
    bsc                       39.36 M
    ethereum                  12.48 M
    
    total                    223.38 M

**Comment by Adolf998** [comment]
Hi @g1nt0ki, We have prepared the graph version, Please check it.

**Comment by g1nt0ki** [comment]
thanks @Adolf998

**Pull request merged**
