### PR TITLE
Update Quadrat indexer with BNB chain

### PR DESCRIPTION
**Pull request by ilyamk**
Update Quadrat indexer with BNB chain

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/quadrat exports TVL: 
        
 
 
    polygon                   0
    bsc                       27.121042755321433
    ethereum                  1.96 k
    arbitrum                  0
    optimism                  4.52 k
    
    total                    6.51 k

**Comment by ilyamk** [comment]
@g1nt0ki Hi 👋
If we use logs, the tests have failed by timeout, so we use our subgraph. Please check the prev PR. 
What's wrong with a data? Why is the USD value so small?

**Comment by g1nt0ki** [comment]
hi @ilyamk 

I am not 100% sure why it is showing lower numbers with subgraph and honestly I mistrust graphs, it adds a dependency that has a history of breaking down/serving stale data (faced this with other adapters and hence I try to move away from them)

the adapter might be failing locally runs because you have not configured to use paid rpcs? there is some restriction on public rpcs (which the sdk defaults to) like rate limiting log queries. For me, it runs under 10 seconds, we have also cached the log calls a bit to reduce cost on the server.

**Comment by ilyamk** [comment]
@g1nt0ki how to add our pools to yeilds list? https://defillama.com/yields

**Comment by g1nt0ki** [comment]
Here: https://github.com/DefiLlama/yield-server/blob/master/README.md

**Comment by ilyamk** [comment]
Thanks @g1nt0ki you can close this PR

**Pull request closed without merging**
