### PR TITLE
fix: scallop tvl calculation

### PR DESCRIPTION
**Pull request by nicetomeetyou1**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/scallop: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'find')
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/sui.js:50:36
        at Array.map (<anonymous>)
        at Object.getObjects (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/sui.js:50:20)
        at async suiTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/scallop/index.js:29:25)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:145:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:188:3

**Comment by llamatester** [comment]
Error while running adapter at projects/scallop: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'find')
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/sui.js:50:36
        at Array.map (<anonymous>)
        at Object.getObjects (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/sui.js:50:20)
        at async suiTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/scallop/index.js:29:25)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:145:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:188:3

**Comment by nicetomeetyou1** [comment]
I think the error is due to an RPC problem because it’s running fine on my side.
Screenshot 2024-09-12 at 01 25 03

**Comment by g1nt0ki** [comment]
issue was chunk size, recently they started limiting it to 10 instead of 50

Curious, why do you want to subtract the revenue,  is it still not leftover amount on the contract?

**Comment by nicetomeetyou1** [comment]
Revenue and cash are mixed, because the revenue also earned from interest so its mixed.

**Pull request merged**
