### PR TITLE
fix(umami-finance): update vaults list for tvl and remove staking(deprecated)

### PR DESCRIPTION
**Pull request by Clonescody**
Update the Infos for Umami Finance as part of the creation of the BonsaiDAO ecosystem page (details in discord)

- Updates the list of Umami vaults as we deployed two additional ones on Avalanche
- Removes staking TVL as both the token and staking mechanism have been deprecated so it's not relevant anymore
- Pending an answer to move the treasury tracking as it'll become part of BonsaiDAO and not Umami itself, but will open a new PR for it whenever we're good

The only change to be made would be with regard to oracles, we use Chainlink Datastreams for our vaults which isn't pointed on the website, the rest of the infos are already accurate.

Edit : the twitter account also needs to be updated from @UmamiDao to @UmamiFinance
Edit 2 : gist with all the informations wrt the BonsaiDAO ecosystem https://gist.github.com/Clonescody/f5ba6461586f49a9d3ae0b0a4bc5b7f6

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/umamifinance exports TVL: 
        
 
 
    arbitrum                  15.02 M
    avax                      2.67 k
    
    total                    15.02 M

**Comment by llamatester** [comment]
The adapter at projects/umamifinance exports TVL: 
        
 
 
    arbitrum                  14.90 M
    arbitrum-staking          515.86 k
    staking                   515.86 k
    avax                      2.67 k
    
    total                    14.90 M

**Comment by g1nt0ki** [comment]
@Clonescody thanks for the PR, we will update the twitter handle and oracle info, yeah, a new PR for bonsai treasury would be good, we can set umami treasury to 0, is it already moved?

**Comment by Clonescody** [comment]
> @Clonescody thanks for the PR, we will update the twitter handle and oracle info, yeah, a new PR for bonsai treasury would be good, we can set umami treasury to 0, is it already moved?

Addresses are the same but yeah it's been officially put under the Bonsai umbrella, will make the PR shortly thanks

**Pull request merged**
