### PR TITLE
Update raindex adapter

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/raindex exports TVL: 
        
 
 
    base                      25.77 k
    linea                     4.77 k
    polygon                   3.23 k
    bsc                       1.01 k
    flare                     334
    arbitrum                  314
    ethereum                  2
    
    total                    35.43 k

**Comment by rouzwelt** [comment]
thanks for your help, I was not aware that token list can be fetched like that, looks great, we can leave matchain for now no issues with that,

one final question, does this now support histrical TVL? or we need to add more changes so it supports it?

**Comment by rouzwelt** [comment]
@g1nt0ki one final question, does this now support histrical TVL? or we need to add more changes so it supports it?

**Comment by g1nt0ki** [comment]
> @g1nt0ki one final question, does this now support histrical TVL? or we need to add more changes so it supports it?

no, this supports fetching historic data

**Comment by rouzwelt** [comment]
> > @g1nt0ki one final question, does this now support histrical TVL? or we need to add more changes so it supports it?
> 
> no, this supports fetching historic data
ok thanks, I dont see the historic tvl on the chart atm, it is showing only the tvl for today only, is it a task that should be run so it shows it? 
Screenshot 2024-10-10 at 4 45 08 PM

**Comment by rouzwelt** [comment]
> > @g1nt0ki one final question, does this now support histrical TVL? or we need to add more changes so it supports it?
> 
> no, this supports fetching historic data

@g1nt0ki  ok thanks, I dont see the historic tvl on the chart atm, it is showing only the tvl for today only, ie there seems to be no data backfill, is it a task that should be run so it shows it or something else? 
would appreciate your help, thanks in advance
Screenshot 2024-10-10 at 4 45 08 PM

**Comment by rouzwelt** [comment]
sory to ping you again @g1nt0ki , any update regarding my latest query?

**Pull request merged**
