### PR TITLE
New Project xWin Finance

### PR DESCRIPTION
**Pull request by DainaTsuru**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): "id" 9870
(https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

##### Short Description (to be shown on DefiLlama):
xWIN Finance is a decentralized finance platform that brings innovation and accessibility to the world of crypto investments. With our unique robo-advisor engine, anyone can create a personalized portfolio of cryptocurrency assets and strategies with just a few clicks. Our platform also offers a range of built-in strategies, including long-short strategy, stablecoin alpha, and dollar-cost averaging, for those seeking more stable returns.

For professional fund managers, xWIN Finance provides an exceptional platform to integrate their investment strategies and connect with a global audience without worrying about infrastructure. Our advanced on-chain strategy and performance fee structure features, combined with our user-friendly interface, ensure a seamless and secure experience for fund managers.

##### methodology (what is being counted as tvl, how is tvl being calculated):
Everything that is deposited to the strategies, public vault, private vault, and staked tokens in the liquidity pool.
The strategies, public vault, and private vault all have a function to calculate in USD how much each fund is holding.
The liquidity pool is calculated by checking how many tokens each pool consists of and using our xWinPriceMaster (open source) to calculate the price of all the tokens.

##### Github org/user (Optional, if your code is open source, we can track activity): https://github.com/xwinfinance/xwin-finance-v2

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/xWinFinance exports TVL: 
        
 
 
    bsc                       4.09 M
    
    total                    4.09 M

**Comment by llamatester** [comment]
The adapter at projects/xWinFinance exports TVL: 
        
 
 
    bsc                       4.19 M
    
    total                    4.19 M

**Comment by llamatester** [comment]
The adapter at projects/xWinFinance exports TVL: 
        
 
 
    bsc-staking               640.22 k
    bsc                       1.63 M
    bsc-pool2                 1.93 M
    staking                   640.22 k
    pool2                     1.93 M
    
    total                    1.63 M

**Comment by g1nt0ki** [comment]
@DainaTsuru thanks for the PR, I have refactored it a bit to split pool2 and staking from tvl

**Pull request merged**
