### PR TITLE
Add stGLINT to staking and updated comment

### PR DESCRIPTION
**Pull request by flisko**
-Added stGLINT to staking and updated the comment on stableswap.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/beamswap-stableswap exports TVL: 
        
 
 
    moonbeam                  730.91 k
    
    total                    730.91 k

**Comment by llamatester** [comment]
The adapter at projects/beamswap exports TVL: 
        
 
 
    moonbeam-staking          960.92 k
    moonbeam                  464.13 k
    staking                   960.92 k
    
    total                    464.13 k

**Comment by flisko** [comment]
> The adapter at projects/beamswap exports TVL:
> 
> ```
> moonbeam-staking          960.92 k
> moonbeam                  464.13 k
> staking                   960.92 k
> 
> total                    464.13 k 
> ```

total should be  960.92 k

**Comment by waynebruce0x** [comment]
sadfadsf

Can you tell us which assets we are missing?

**Comment by flisko** [comment]
I wanted to add this PR to just update the $ **staked** value shown here; https://defillama.com/protocol/beamswap
I think i got confused on the output, but I think it's correct, sorry. All good.

**Pull request merged**
