### PR TITLE
For support of Fringe V2 multi-chain and multiple lender assets.

### PR DESCRIPTION
**Pull request by brainspacer**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/fringe: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:217:11

**Comment by llamatester** [comment]
The adapter at projects/fringe exports TVL: 
        
 
 
    ethereum                  26.78 k
    ethereum-borrowed         246.246083
    borrowed                  246.246083
    
    total                    26.78 k

**Comment by llamatester** [comment]
The adapter at projects/fringe-v2 exports TVL: 
        
 
 
    arbitrum                  17.95 k
    optimism                  6.12 k
    arbitrum-borrowed         38.28301237387165
    era                       3.31 k
    optimism-borrowed         779.1627138728036
    era-borrowed              10.000999
    ethereum-borrowed         1.4492241792481002
    ethereum                  351.4095096260272
    polygon                   117.82847192474495
    polygon-borrowed          4.151722392155997
    borrowed                  833.0476718180793
    
    total                    27.85 k

**Comment by g1nt0ki** [comment]
@brainspacer thanks for the PR, I refactored it a bit so we dont depend on web3 npm lib

also, I think it is better if we have a new listing for v2

**Comment by brainspacer** [comment]
@g1nt0ki  refactored "a bit". lol. Thanks !
Cigar for you =====~

**Pull request merged**
