### PR TITLE
add comb

### PR DESCRIPTION
**Pull request by GhostWalker562**
##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): 
logo_background

##### methodology (what is being counted as tvl, how is tvl being calculated): Fetches the total value of staked liquidity pairs in the MasterChef. Fetches the total value of staked liquidity pairs in our auto compounders. Fetches the total value of COMB locked inside of our voting escrow token, zCOMB.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/comb/index.js exports TVL: 
        
 
 
    fantom                    11.51 M
    
    total                    11.51 M

**Comment by waynebruce0x** [comment]
Can zComb TVL be exported as a separate 'staking' export?

**Comment by GhostWalker562** [comment]
Can you further elaborate or point me to a staking export?

**Comment by GhostWalker562** [comment]
@waynebruce0x Moved zCOMB TVL to staking

**Comment by llamatester** [comment]
The adapter at projects/comb/index.js exports TVL: 
        
 
 
    fantom                    10.06 M
    fantom-staking            2.02 M
    staking                   2.02 M
    
    total                    10.06 M

**Pull request merged**
