### PR TITLE
BetSwirl's adapter

### PR DESCRIPTION
**Pull request by RomualdH**
## BetSwirl's adapter

Dear team,
I was not sure about the `misrepresentedTokens`, please advise.

---

##### Twitter Link:
https://twitter.com/BetSwirl

##### List of audit links if any:
- https://github.com/BetSwirl/Smart-Contracts
- Pending with Quillhash

##### Website Link:
https://www.betswirl.com

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
logotype

##### Current TVL:
- BetSwirl has no users TVL yet. 
- Treasury: 323.96 k$.

##### Chain:
Polygon, BNB Smart Chain, Avalanche

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
No yet listed.

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
18453

##### Short Description (to be shown on DefiLlama):
BetSwirl aims to be the decentralized gambling platform: provably fair, non-custodial, licensed, trustless and community driven.
While traditional blockchain casinos target the gambler's demographic, BetSwirl aims to bring innovative gameplay with storytelling coupled with eye-pleasing and creative designs.

##### Token address and ticker if any:
- https://polygonscan.com/token/0x9246a5f10a79a5a939b0c2a75a3ad196aafdb43b
- BETS

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Prediction Market

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink VRF v2.

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
BetSwirl has no users TVL yet.
However, it includes the bankrolls amounts (each tokens amount in the bank allowing players to bet):

---
Best regards,
Romuald

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/BetSwirl exports TVL: 
        
 
 
    bsc                       0
    polygon                   0
    avalanche                 0
    bsc-treasury              287.26 k
    avalanche-treasury        13.75 k
    polygon-treasury          26.08 k
    treasury                  327.09 k
    
    total                    0

**Comment by g1nt0ki** [comment]
@RomualdH I have refactored your code here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/3288

thanks for the PR, it looks good, I just made a minor change. Yeah,  misrepresentedTokens is causing bit of confusion, it is say when you have usd pegged token betUSD, but it is found neither in coingecko nor can its price be fetched from an oracle, so you substitute it with USDC/DAI in balances so it can be counted, then the flag should be set true.

**Comment by RomualdH** [comment]
@g1nt0ki omg I wrote too much code...
Thanks!

**Comment by RomualdH** [comment]
@g1nt0ki The thing is that `sumTokens2` is doing `balanceOf`, but some funds in the Bank contracts aren't owned by the treasury, so it was more accurate with my implementation (`Bank.getBalance(address)` is getting only what's available for players to bet).

**Comment by g1nt0ki** [comment]
@RomualdH I thought about it, but the whole balance can be taken out by your team when they want right? hence I counted everything, but if you prefer, I can revert my change :)

**Comment by RomualdH** [comment]
> @RomualdH I thought about it, but the whole balance can be taken out by your team when they want right? hence I counted everything, but if you prefer, I can revert my change :)

No. Only the balance retrieved from `betBalance` can be withdrawn by the team.

**Comment by g1nt0ki** [comment]
reverted change here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/3290

**Pull request merged**
