### PR TITLE
Add deus protocol

### PR DESCRIPTION
**Pull request by Shing-Ho**
### Twitter Link:
https://twitter.com/DeusDao

### List of audit links if any:
https://coinbae.org/media/files/audit_File_6x5JY82PyC/Deus%20Finance%20Vault%20Audit.pdf
https://coinbae.org/media/files/audit_File_Vv67KcySJw/Deus%20Finance%20Sandtoken%20Audit.pdf
https://coinbae.org/media/files/audit_File_IcoOGFNHeX/Deus%20Finance%20DEAStaking%20Pool%20Audit.pdf

### Website Link:
https://deus.finance/

### Contact Email:
admin@deus.finance

### Current TVL:
$130,103,534

### Chain:
Ethereum, XDai, BSC (Soon)

### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
deus-finance

### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
deus-finance

### Description/bio (to be shown on DefiLlama):
transpose any digitally verifiable asset securely onto the blockchain. DEUS lets you trade real-world assets and derivatives, like stocks and commodities, directly on the Ethereum blockchain.

### Token address and ticker if any:
DEA: 0x80ab141f324c3d6f2b18b030f1c4e95d4d658778
DEUS: 0x3b62f3820e0b035cc4ad602dece6d796bc325325

### Category (Yield/Dexes/Lending/Minting):
Synthetics

### [Optional] ETH addresss (to receive a LlamaPunk):
0x8b9C5d6c73b4d11a362B62Bd4B4d3E52AF55C630

### CODE REVIEW

**Comment by 0xngmi** [comment]
Thanks for submitting! Just took a look and it seems that vaults include pool2 tokens, which we generally don't consider as part of TVL. Would it be possible to change the adapter to substract that from tvl?

**Comment by firstabor** [comment]
Could you elaborate on what exact tokens you are talking about?
DEUS / DEA / UNI-V2 ?

**Comment by 0xngmi** [comment]
From a cursory read of your wiki it seems like the best one to exclude would be DEUS LP tokens.

**Comment by Shing-Ho** [comment]
@0xngmi I've made a new commit. Please check.

**Pull request merged**
