### PR TITLE
Sommelier: Update TVL Calcs to Include new Arbitrum Vault

### PR DESCRIPTION
**Pull request by philipjames44**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/sommelier: 
        
 
  
    
    
    Error: Multicall failed! 
     [chain: ethereum] [fail count: 1] [abi: function balanceOf(address account) view returns (uint256)]  
        target: 0xC47bB288178Ea40bF520a91826a3DEE9e0DbFA4C params: 0xC47bB288178Ea40bF520a91826a3DEE9e0DbFA4C]

**Comment by llamatester** [comment]
The adapter at projects/sommelier exports TVL: 
        
 
 
    arbitrum                  1.78 M
    ethereum                  69.54 M
    
    total                    71.32 M

**Comment by llamatester** [comment]
The adapter at projects/sommelier exports TVL: 
        
 
 
    arbitrum                  1.78 M
    ethereum                  69.54 M
    
    total                    71.32 M

**Comment by g1nt0ki** [comment]
@philipjames44 thanks for the update

**Pull request merged**
