### PR TITLE
Add UPFI Network adapter

### PR DESCRIPTION
**Pull request by inti25**
##### Twitter Link:
https://twitter.com/upfi_network

##### List of audit links if any:
https://www.rdauditors.com/wp-content/uploads/2021/11/UPFI-Network-Smart-Contract-Security-Report.pdf

##### Website Link:
https://upfi.network/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://upfi.network/asset/image/upfi-logo.svg

##### Current TVL:
$1.46 M 

##### Chain:
Solana

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
upfi-network

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
14322

##### Short Description (to be shown on DefiLlama):
UPFI – Stablecoin partially backed by collateral and partially stabilized algorithmically

##### Token address and ticker if any:
EwJN2GqUGXXzYmoAciwuABtorHczTA5LqbukKXV1viH7

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Yield

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Pyth Network

##### forkedFrom (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL data is pulled from the UPFI API "https://api.upfi.network/tvl".

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Is this just counting the UPFI/USDC and UPS/USDC pools?

**Comment by inti25** [comment]
> Is this just counting the UPFI/USDC and UPS/USDC pools?

Hello,
It's total tvl for both pools.

**Comment by waynebruce0x** [comment]
Could you export this as pool2, with tvl as {}? Since both pools include your native token (if I understand correctly)

**Comment by inti25** [comment]
> Could you export this as pool2, with tvl as {}? Since both pools include your native token (if I understand correctly)

i updated my pull request as your comment, please check it again.
Thanks

**Pull request merged**
