### PR TITLE
add wise lending project tvl

### PR DESCRIPTION
**Pull request by byyyyyyyyy**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Wise Lending

##### Twitter Link:
https://twitter.com/Wise_Token

##### List of audit links if any:
(in progress)

##### Website Link:
https://wiselending.com/

##### Logo (High resolution, will be shown with rounded borders):
Wise Lending

##### Current TVL:
($50,000 but this has to be checked actively)

##### Treasury Addresses (if the protocol has treasury):
([[0x87a567060769348c7ff1836e4497b84f844ba99b](https://etherscan.io/address/0x87a567060769348c7ff1836e4497b84f844ba99b)]

##### Chain:
Ethereum

##### Short Description (to be shown on DefiLlama):
A decentralized lend/borrow platform and yield farm aggregator

##### Token address and ticker if any:
WISE 0x66a0f676479Cee1d7373f3DC2e2952778BfF5bd6

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### forkedFrom (Does your project originate from another project):
NOT a fork!

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is all native, but since we built symbiotically on top of Aave and other yield farms, the TVL would also be included by other platforms

##### Github org/user (Optional, if your code is open source, we can track activity):
Open source

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/wise-lending exports TVL: 
        
 
 
    ethereum                  9.37 k
    
    total                    9.37 k

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
sorry, we dont accept fetch adapters anymore. you need to compute tvl on chain, if you share contract details, I can try to write the adapter

**Comment by vm06007** [comment]
> sorry, we dont accept fetch adapters anymore. you need to compute tvl on chain, if you share contract details, I can try to write the adapter

thanks for the feedback @g1nt0ki 
here is our contract that holds all the TVL: https://etherscan.io/address/0x84524baa1951247b3a2617a843e6ece915bb9674

please note there's also Aave and Moo tokens in it:
Screenshot 2023-09-06 at 8 03 27 PM

**Comment by vm06007** [comment]
> @byyyyyyyyy thanks I have added adapter here: [c4d0319](https://github.com/DefiLlama/DefiLlama-Adapters/commit/c4d03195c979d65cf1f4895d9eb26f792cedfd20)
> 
> can you review it when you get time?

Thanks for the initial draft of the adapter, I think we better adjust it so it also includes borrowing shares (borrowed amounts) from the contract so borrowed funds are also counted.

**Comment by vm06007** [comment]
Another approach we can create a view function contract that would output all the TVL from our protocol with a single function (so we can do the logic of existing amount + borrowed amounts within smart-contract call)

**Comment by g1nt0ki** [comment]
> > @byyyyyyyyy thanks I have added adapter here: [c4d0319](https://github.com/DefiLlama/DefiLlama-Adapters/commit/c4d03195c979d65cf1f4895d9eb26f792cedfd20)
> > can you review it when you get time?
> 
> Thanks for the initial draft of the adapter, I think we better adjust it so it also includes borrowing shares (borrowed amounts) from the contract so borrowed funds are also counted.

hi @vm06007 for lending protocols, we count borrowed amount under separate key 'borrowed', but I was not sure how to pull that info for your project, what api call gives me borrowed amount?

**Comment by vm06007** [comment]
Okay thats fine @g1nt0ki could you reopen it? Here is contract that would calculate TVL: https://etherscan.io/address/0x72ff816d4204d7fFf991EbcBc1C8D164Ba36EcF6#readContract#F1

**Comment by vm06007** [comment]
any help with adapter would be highly appreciated!

**Comment by g1nt0ki** [comment]
> Okay thats fine @g1nt0ki could you reopen it? Here is contract that would calculate TVL: https://etherscan.io/address/0x72ff816d4204d7fFf991EbcBc1C8D164Ba36EcF6#readContract#F1

hi @byyyyyyyyy can you put upa new PR as I have squashed and merged other, I cant reopen this one.

Also, sorry but this is no go as there is no token breakdown, I am guessing this includes borrowed amount? https://etherscan.io/address/0x72ff816d4204d7fFf991EbcBc1C8D164Ba36EcF6#readContract#F1

**Pull request closed without merging**
