### PR TITLE
add Hyperdrive

### PR DESCRIPTION
**Pull request by wakamex**
Note this is the new protocol from Delv, the team formerly known as Element Finance. This protocol should be listed under Delv, on our existing page: https://defillama.com/protocol/delv.

##### Website Link:
https://hyperdrive.box/ for the protocol.
https://delv.tech/ for the team.

##### Logo (High resolution, will be shown with rounded borders):
hyperdrive-mark-white(1)

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/hyperdrive.js: 
        
 
  
    
    
    ReferenceError: block is not defined
    Truncated error stack:
    
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/hyperdrive.js:65:64)
        at async tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/hyperdrive.js:74:35)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:171:9
        at async Promise.all (index 0)
        at async Promise.all (index 0)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:214:3

**Comment by llamatester** [comment]
The adapter at projects/hyperdrive.js exports TVL: 
        
 
 
    xdai                      1.72 M
    ethereum                  1.28 M
    linea                     210
    base                      189
    
    total                    3.00 M

**Comment by wakamex** [comment]
I can see the pattern of defining a new protocol in the data.js files and linking them to a parent#name, but I'm not sure if I should be the one doing that.

**Comment by llamatester** [comment]
The adapter at projects/hyperdrive.js exports TVL: 
        
 
 
    xdai                      1.72 M
    ethereum                  1.27 M
    linea                     210
    base                      189
    
    total                    3.00 M

**Comment by wakamex** [comment]
I can remove the `callWithRetry`, but it was necessary to get it to run locally for me, and it doesn't seem to be doing any damage 😋

**Comment by g1nt0ki** [comment]
oh yeah, dont worry about the listing, we will take care of it and add it under delv, thanks again for the PR :)

**Comment by wakamex** [comment]
thanks for the quick response! the Hyperdrive page was loading fine earlier today, but right now it returns `Application error: a client-side exception has occurred (see the browser console for more information).` on https://defillama.com/protocol/hyperdrive.

here's the error in console:
```
TypeError: Cannot read properties of null (reading 'protocolData')
    at P ([...protocol]-ca3cb0669910ea9a.js:1:120316)
    at oo (framework-79bce4a3a540b080.js:1:59417)
    at Wo (framework-79bce4a3a540b080.js:1:68984)
    at Ku (framework-79bce4a3a540b080.js:1:112708)
    at Li (framework-79bce4a3a540b080.js:1:98958)
    at Ni (framework-79bce4a3a540b080.js:1:98886)
    at Pi (framework-79bce4a3a540b080.js:1:98749)
    at bi (framework-79bce4a3a540b080.js:1:95715)
    at framework-79bce4a3a540b080.js:1:45209
    at t.unstable_runWithPriority (framework-79bce4a3a540b080.js:1:129355)
```

**Pull request closed without merging**
