### PR TITLE
move cryptex to cryptex-finance for coinmarketcap corret API fetch; a…

### PR DESCRIPTION
**Pull request by masquel**
Moved project with same name called "Cryptex" (https://coinmarketcap.com/currencies/cryptex-finance/) to folder with `cryptex-finance` id same to CoinMarketCap.
Added CryptEx Locker TVL calculations based on locked LP tokens and team tokens.

##### Twitter Link:
https://twitter.com/ExLocker

##### Website Link:
https://cryptexlock.me/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://cryptexlock.me/logo-200x200.svg

##### Current TVL:
~$40m

##### Chain:
BSC, Polygon, Avalanche, Gnosis, Fantom, Cronos, Aurora, Moonriver 

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
https://www.coingecko.com/en/coins/cryptex

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
https://coinmarketcap.com/currencies/cryptex/

##### Short Description (to be shown on DefiLlama):
CryptEx Locker is part of CryptEx ecosystem which provide LP locker and Team Token Vesting services. CryptEx also providing staking service. Stake CRX to earn 50% of CryptEx locker platform fees.

##### Token address and ticker if any:
0x97a30C692eCe9C317235d48287d23d358170FC40 (Binance Smart Chain) - CRX

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Staking

### CODE REVIEW

**Comment by waynebruce0x** [comment]
So are the cryptex and cryptex finance adapters for separate protocols? Or should we only use 1 of them?

**Comment by masquel** [comment]
@waynebruce0x `cryptex` and `cryptex-finance` are different projects so you might use both of them.

https://coinmarketcap.com/currencies/cryptex-finance/ - this it Cryptex Finance (`cryptex-finance` id on CMC) but called `cryptex` on DeFi Lama and there is no data from DeFi Lama API on CMC page.

https://coinmarketcap.com/currencies/cryptex/ - this is CryptEx (`cryptex` id on CMC), it displays TVL from DeFi Lama API now. But data comes from Cryptex Finance project called `cryptex` (now its Cryptex Finance) on your platfrom.

Thats why I moved current `cryptex` adapter to `cryptex-finance` and added new one for `cryptex` project. After it TVL data on CMC will be relative to projects.

**Comment by realdealshaman** [comment]
@masquel please refrain from updating other protocols in the future, the information used on coingecko and coinmarket cap is not pulled from the protocol name or the name given to the module. We use the ids provided by the APIs of these platforms. Cryptex Finance currently has the ids that are provided by coingecko and coinmarketcap, with your changes now we simply have to sort the module that belongs to each protocol

**Comment by masquel** [comment]
[realdealshaman](https://github.com/realdealshaman) 

Please, check this page on CMC - https://coinmarketcap.com/currencies/cryptex/ it has TVL section from your API, but CryptEx project is not listed on DeFi Lama. Thats why I moved Cryptex FInance adapter to `cryptex-finance` folder same to CMC slug in url.

And also, please check this page - https://coinmarketcap.com/currencies/cryptex-finance/ the project called Cryptex Finance is listed on DeFi Lama but named Cryptex and with `cryptex` id instead of `cryptex-finance`. And there is no information about any TVL for this project on CMC.

TVL data displayed that CMC shows on `CryptEx` project page belongs to `Cryptex Finance`.

**Comment by realdealshaman** [comment]
This likely an error from coinmarketcap as we use their api to find the ids
this is the info we have:
{"id":10368,"name":"Cryptex Finance","symbol":"CTX","slug":"cryptex-finance","is_active":1,

it can be checked here: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data.ts#L3326

I've kept your changes and updated the name for more clarity, however if cmc is using the wrong id, the mistake on their page will remain 

this is the id we will use for your protocol, as provided by the cmc API

{"id":8731,"name":"CryptEx","symbol":"CRX","slug":"cryptex","is_active":1,

**Comment by realdealshaman** [comment]
I've added your listing:

https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts#L2414

**Comment by masquel** [comment]
@realdealshaman will CryptEx be listed on DeFi Lama? I saw Cryptex Finance info was updated, but there is no CryptEx.

**Comment by realdealshaman** [comment]
@masquel Hello, I hope you are doing well. I'm afraid I'm not bringing the best news. We were checking your adapter after it was merged as it was not returning a TVL. The way the TVL is calculated takes a long time to return a result and apparently produces some kind of rpc error, "failed to meet quorum error". Seeing if there was another way to calculate your TVL we realized that the service you offer is similar to the "For Business" services offered by TrustSwap. In their case, we have decided not to add these amounts since the tokens are deposited by the teams and have not been in circulation. Due to the similarity, and to maintain a fair position where the same item is applied to all projects, we cannot add that TVL. We remain at your service to answer any questions

**Comment by masquel** [comment]
@realdealshaman Hello, I see. Maybe we can leave staking then?

**Comment by realdealshaman** [comment]
@masquel Yes, of course, I have modified the adapter so that it only reflects the CRX staked. If you have a link to your audit, I'd be happy to add it to your protocol page.

**Pull request merged**
