### PR TITLE
Chainflip Missing TVL

### PR DESCRIPTION
**Pull request by CumpsD**
This is an update to the Chainflip TVL to also include undeployed liquidity which is locked into the Chainflip system. This was missing from the last update (only deployed and boost liquidity)

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/chainflip exports TVL: 
        
 
 
    ethereum-staking          48.52 M
    staking                   48.52 M
    chainflip                 9.21 M
    ethereum                  0
    
    total                    9.21 M

**Comment by llamatester** [comment]
The adapter at projects/chainflip exports TVL: 
        
 
 
    ethereum-staking          48.52 M
    staking                   48.52 M
    chainflip                 9.21 M
    ethereum                  0
    
    total                    9.21 M

**Comment by g1nt0ki** [comment]
hi @CumpsD by undeployed liquidity, you mean assets deposited in chainflip contract but not part of the dex?

**Comment by CumpsD** [comment]
> hi @CumpsD by undeployed liquidity, you mean assets deposited in chainflip contract but not part of the dex?

no, they are part of the feed, these are assets which are used for "just in time liquidity". it's locked in the system but not assigned to a specific pool, when a swap is incoming it's moved to the correct pool to service that swap. this is done to provide more capital efficiency and less liquidity fragmentation

**Pull request merged**
