### PR TITLE
3A DAO - Adapter

### PR DESCRIPTION
**Pull request by CristianRicharte6**
##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
- A3A: https://www.coingecko.com/en/coins/3a
- EURO3: https://www.coingecko.com/en/coins/euro3

##### Github org/user (Optional, if your code is open source, we can track activity): https://github.com/3A-DAO/3a-borrowing-protocol

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/3a-dao: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:217:11

**Comment by CristianRicharte6** [comment]
@g1nt0ki could you assist here? Please 

The tvl is added to the chain.

**Comment by llamatester** [comment]
Error while running adapter at projects/3a-dao: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:217:11

**Comment by g1nt0ki** [comment]
@CristianRicharte6 thanks for the PR, refactored and merged it

**Comment by CristianRicharte6** [comment]
Hello @g1nt0ki we are not able to see the price and total supply of EURO3 in the UI. Could you have a look? Please

**Comment by g1nt0ki** [comment]
@CristianRicharte6 we show the gov token price in the tvl chart/not the stablecoin, if you want to track stablecoin, you can try to get listed here? https://defillama.com/stablecoins

This is the code base where you can put up a PR: https://github.com/DefiLlama/peggedassets-server

**Pull request merged**
