### PR TITLE
Add IHF project adapter

### PR DESCRIPTION
**Pull request by nghiahoang10**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): 
https://www.coingecko.com/de/munze/ihf-smart-debase-token
(https://api.coingecko.com/api/v3/coins/list)

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): https://coinmarketcap.com/currencies/ihf-smart-debase-token/
(https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/infinity-hedge-fund exports TVL: 
        
 
 
    base                      10.15 M
    
    total                    10.15 M

**Comment by Define101** [comment]
own tokens should be under staking not TVL https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by llamatester** [comment]
Error while running adapter at projects/infinity-hedge-fund: 
        
 
  
    
    
    PromisePoolError: Request failed with status code 400
    Truncated error stack:
        at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
The adapter at projects/infinity-hedge-fund exports TVL: 
        
 
 
    base-staking              10.13 M
    staking                   10.13 M
    base                      0
    
    total                    0

**Pull request merged**
