### PR TITLE
Add Toucan Protocol support

### PR DESCRIPTION
**Pull request by kargakis**
##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

tc_symbol_OnDark_color

tc_symbol_OnBright_color

##### Coingecko ID (so your TVL can appear on Coingecko): 

No governance token yet

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): 

No governance token yet

##### Short Description (to be shown on DefiLlama):

Toucan exists to unlock climate action at scale. The protocol provides tools that allow anyone to bring carbon credits onto the blockchain to improve the carbon market and fuel web3 innovation. Unlocking more ideas, infrastructure and incentives to finance the world’s best climate projects.

##### Token address and ticker if any:

BCT: https://polygonscan.com/token/0x2f800db0fdb5223b3c3f354886d907a671414a7f
NCT: https://polygonscan.com/token/0xd838290e877e0188a4a44700463419ed96c16107

##### Category (full list at https://defillama.com/categories) *Please choose only one:

RWA

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

TBD

##### forkedFrom (Does your project originate from another project):

No

##### methodology (what is being counted as tvl, how is tvl being calculated): 

All supply in our carbon pools should be counted as TVL (BCT, NCT currently). These carbon pools are backed by TCO2 tokens which represent the underlying carbon projects that have been financed. Each 1 TCO2 token represents 1 tonne of carbon credit and can be deposited or redeemed for 1 BCT or NCT, depending on the criteria of the carbon pool that pools all the TCO2s.

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@kargakis sorry, I dont think Defillama can list this project, main reason is, it is real world asset backed, and it is hard to quantify/count it's value. IMO, you are similar to stablecoin issuers and we dont list them either.

**Comment by kargakis** [comment]
@g1nt0ki we are nothing like a stablecoin issuer. Stablecoin issuers custody currencies in exchange for stablecoins, we don't do any custody at all and the carbon credits that live on-chain are the only valid representation (the off-chain credit is simply a database entry and not in circulation anymore). In the future there may be direct issuance of carbon credits on-chain, too.

Regarding the price feeds, currently the most accurate feeds are the Sushiswap pools in Polygon (NCT-USDC, BCT-USDC, BCT-KLIMA) because that's where the majority of liquidity and volume exists but there are oracle integrations in the works, too. Hopefully in the future we have on-chain price feeds also for the underlying TCO2s that are not deposited in the pools but I think starting with the pools today is good enough to track.

**Comment by kargakis** [comment]
My only worry here is that the doublecounting feature excludes protocols altogether, whereas I should be able to exclude only specific parts of Klima's TVL (their BCT and NCT holdings only).

**Comment by g1nt0ki** [comment]
The issue here is counting, counting BCT/NCT supply * price as TVL, but we count DAI supply as TVL but the tokens backing it.

Like you said, ideally we should count underlying TCO2s value, but that is hard, also the TCO2s are bridged/issued your protocol right?

**Comment by kargakis** [comment]
I think it is wrong to be thinking in terms of MakerDAO as DAI is collateralized **debt**. There is no debt relationship between TCO2s and BCT/NCT. Although there is a 1:1 backing, the latter simply is a more liquid asset, hence currently it is a better proxy to track value. Not sure I understand the last question but anyone can use our protocol to bridge tokens, we don't do any bridging/issuance ourselves.

**Comment by g1nt0ki** [comment]
how are TCO2s brought on chain/minted?

**Comment by kargakis** [comment]
Currently bridged by Verra users (Verra is the largest off-chain registry for carbon credits in the voluntary market), but the idea is that we are trying to be infrastructure for anyone to source carbon on-chain. You can read more about the bridging process [here](https://docs.toucan.earth/protocol/bridge/carbon-bridge#how-it-works).

**Comment by g1nt0ki** [comment]
> Currently bridged by Verra users (Verra is the largest off-chain registry for carbon credits in the voluntary market), but the idea is that we are trying to be infrastructure for anyone to source carbon on-chain. You can read more about the bridging process [here](https://docs.toucan.earth/protocol/bridge/carbon-bridge).

yes, they are the users but Toucan is the infra bringing TCO2s on polygon, right?

**Comment by g1nt0ki** [comment]
Sorry, but this is why we cant list the project. BCT/NCT is a  building block for other defi protocols, but I dont see how defi users interact your protocol, they are not locking any crypto native tokens in your protocol.

**Comment by g1nt0ki** [comment]
@kargakis Sorry, this has been bothering me for a while, so I went and had another discussion with the team, they agreed it is okay to list it, but just a bit of warning, if (enough) users complain that this is not defi, I will have no option but to delist it then. Is that okay?


Can you remove the changes to `klima-dao`, I think it is not double counting in this case, you are creating an asset and they are utilizing it

**Comment by kargakis** [comment]
@g1nt0ki reopened at https://github.com/DefiLlama/DefiLlama-Adapters/pull/3451, apparently I cannot push to this PR anymore if I recreate my Github fork.

**Pull request closed without merging**
