### PR TITLE
add tvl of duet.finance

### PR DESCRIPTION
**Pull request by davidduet**
##### Twitter Link:
https://twitter.com/duetprotocol

##### List of audit links if any:
https://linktr.ee/duetaudit

##### Website Link:
https://duet.finance/

##### Logo (High resolution, preferably in .svg and .png, for applicat
Square logo

DUET LOGO-600_600

##### Current TVL:
2901460

##### Chain:
BSC

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
duet-protocol

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
10132

##### Short Description (to be shown on DefiLlama):
A parallel universe which turns flat assets into sharp assets

##### Token address and ticker if any:
0x95ee03e1e2c5c4877f9a298f1c0d6c98698fab7b

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Synthetics

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink/TWAP

##### forkedFrom (Does your project originate from another project):
None

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is the sum of all tokens in the staking pools

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Can we calculate this using onchain calls instead please?

**Comment by davidduet** [comment]
> Can we calculate this using onchain calls instead please?

@waynebruce0x 

Updated to use on-chain calculation.

**Comment by davidduet** [comment]
> Can we calculate this using onchain calls instead please?

@waynebruce0x 

Updated to use on-chain calculation.

**Comment by llamatester** [comment]
The adapter at projects/duet exports TVL: 
        
 
 
    
    total                    2.67 M

**Pull request merged**
