### PR TITLE
add basic configs lukso

### PR DESCRIPTION
**Pull request by JordyDutch**
**NOTE**

Reproduced PR to add LUKSO chain according to [Discord Convo](https://discord.com/channels/823822164956151810/823822165538373696/1247115758987771904)

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

- SigmaSwap Bridge

- Stakingverse

- Universal Page

- Universal Swaps

##### Twitter Link:

https://x.com/sigmaswap.io

https://x.com/stakingverse_io

https://x.com/_universalpage

https://x.com/UniversalSwaps

##### List of audit links if any:

https://docs.sigmaswap.io/docs/audits/

https://docs.stakingverse.io/security-lukso#audit

https://github.com/Universal-Page/contracts/tree/main/audits

https://github.com/Universal-Swaps/protocol-contracts/tree/main/v3-core/audits

##### Website Link:

https://sigmaswap.io

https://stakingverse.io

https://universal.page

https://universalswaps.io

##### Logo (High resolution, will be shown with rounded borders):

SigmaSwap
https://github.com/SigmaSwap-io/token-image/blob/main/SigmaSwap_Logo_Dark_400x400.png?raw=true

Stakingverse
https://github.com/Stakingverse/Images/blob/main/stakingverse-logo.png?raw=true

##### Chain:

LUKSO - chain ID: 42

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

wrapped-lyx-sigmaswap

wrapped-lyx-universalswaps

##### Token address and ticker if any:

SigmaSwap
0x0808e6c4400bde1d70db0d02170b67de05e07ef5 (wLYX - Ethereum mainnet)

Universal Swaps
0x2db41674f2b882889e5e1bd09a3f3613952bc472 (wLYX - LUKSO chain)

##### Category (full list at https://defillama.com/categories) *Please choose only one:

SigmaSwap - Bridge

Stakingverse - Staking pool

Universal Page - NFT Marketplace

Universal Swaps - Dexes

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/symbiosis-finance: 
        
 
  
    
    
    PromisePoolError: Request failed with status code 520
    Truncated error stack:
        at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
The adapter at projects/symbiosis-finance exports TVL: 
        
 
 
    ethereum                  5.17 M
    sei                       869.58 k
    arbitrum                  759.90 k
    era                       466.85 k
    polygon                   418.81 k
    bsc                       344.65 k
    rsk                       231.23 k
    boba_bnb                  220.86 k
    tron                      201.02 k
    merlin                    185.51 k
    scroll                    164.52 k
    linea                     163.45 k
    zklink                    151.81 k
    ftn                       150.25 k
    manta                     142.78 k
    mantle                    139.13 k
    boba                      124.66 k
    optimism                  122.33 k
    base                      122.05 k
    polygon_zkevm             110.52 k
    telos                     108.25 k
    avax                      86.70 k
    metis                     83.71 k
    mode                      52.61 k
    blast                     50.03 k
    arbitrum_nova             39.30 k
    core                      35.57 k
    taiko                     22.62 k
    kava                      10.29 k
    aurora                    4
    boba_avax                 0
    
    total                    10.75 M

**Comment by Define101** [comment]
Thanks for the PR
We made some changes here https://github.com/DefiLlama/DefiLlama-Adapters/pull/10492

**Comment by JordyDutch** [comment]
> Thanks for the PR We made some changes here #10492

Awesome, thanks @Define101. Can I close this PR?

**Pull request closed without merging**
