### PR TITLE
Add ZeUSD Token

### PR DESCRIPTION
**Pull request by shinchann221**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Header: Zoth
Tab: ZeUSD

##### Twitter Link:
https://x.com/zothdotio

##### Website Link:
https://zoth.io

##### Logo (High resolution, will be shown with rounded borders):
https://resources.zoth.io/images/Zoth%20logo.png

##### Current TVL:
2,023,351.431501

##### Treasury Addresses (if the protocol has treasury)
ZTLN-Prime : 0x2243C2e006103720F0a02bf1971D6495e9cDeFFF
USD0++ : 0xEB3729B41AcEcEb59DD7B7ffeC8481b3DEA183a9

##### Chain:
Ethereum, Manta

##### Short Description (to be shown on DefiLlama):
Zoth is an RWA ecosystem bringing institutional-grade yield avenues onchain.

##### Token address and ticker if any:
Ticker: ZeUSD
Address: 0x7DC9748DA8E762e569F9269f48F69A1a9F8Ea761

##### Category (full list at https://defillama.com/categories) *Please choose only one:
CDP

##### methodology (what is being counted as tvl, how is tvl being calculated):
Sums total ZeUSD in circulation across all chains

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/0xZothio/

### CODE REVIEW

**Comment by llamabutler** [comment]
The adapter at projects/zoth-zeusd exports TVL: 
        
 
 
    manta                     1.94 M
    ethereum                  83.01 k
    
    total                    2.02 M

**Comment by shinchann221** [comment]
The ZeUSD token itself is priced at 1 USD. ZeUSD is a fully composable RWA-backed Collateralized Debt Position (CDP) stable token issued on top of high-quality on-chain RWAs like ZTLN-P, USD0++ etc. 

The reason I've created an API and not used on chain methods was because ZTLN-P is not priced by Defillama yet. I'm already in talks with someone from Discord (waynebruce). 

We'll soon introduce other RWAs as Hashnote USYC, OpenEden T-Bill, which have their pricing oracles live.

**Comment by shinchann221** [comment]
Technical Documentation for ZeUSD : https://docs.zoth.io/zoth/tech-center/architecture

**Comment by shinchann221** [comment]
For more transparency here is the code that is there in the API. 

```
import { NextResponse } from 'next/server'
import { createPublicClient, erc20Abi, http } from 'viem'
import { manta } from 'viem/chains'

import { customMainnet } from '@/lib/wallet/chains'

const ZeUSD = '0x7DC9748DA8E762e569F9269f48F69A1a9F8Ea761'

export async function GET() {
    const mainnetClient = createPublicClient({
        chain: customMainnet,
        transport: http()
    })

    const mantaClient = createPublicClient({
        chain: manta,
        transport: http()
    })

    const total_supply = await mainnetClient.readContract({
        abi: erc20Abi,
        address: ZeUSD,
        functionName: 'totalSupply'
    })

    const manta_supply = await mantaClient.readContract({
        abi: erc20Abi,
        address: ZeUSD,
        functionName: 'totalSupply'
    })

    return NextResponse.json({
        ethereum: (Number(total_supply) - Number(manta_supply)).toString(),
        manta: manta_supply.toString()
    })
}
```

**Comment by g1nt0ki** [comment]
hi @shinchann221 
sorry, we cant track zeUSD supply as CDP tvl, for cdp products, we count the assets locked to mint the synth token as tvl, like ether for maker or liquity. 

And in that scenario as well, we cant count ZLTN, we are already tracking it's supply under rwa right? https://defillama.com/protocol/zoth

So, when you add support for minth zeUSD with other tokens, we can track those locked tokens as your tvl. 

For now, we can track the circulating supply of zeUSD in our stablecoin dashboard, this would act like other stablecoins and tradable in the open market? 

https://defillama.com/stablecoins

**Comment by shinchann221** [comment]
> hi @shinchann221 sorry, we cant track zeUSD supply as CDP tvl, for cdp products, we count the assets locked to mint the synth token as tvl, like ether for maker or liquity.
> 
> And in that scenario as well, we cant count ZLTN, we are already tracking it's supply under rwa right? https://defillama.com/protocol/zoth
> 
> So, when you add support for minth zeUSD with other tokens, we can track those locked tokens as your tvl.
> 
> For now, we can track the circulating supply of zeUSD in our stablecoin dashboard, this would act like other stablecoins and tradable in the open market?
> 
> https://defillama.com/stablecoins

Hey @g1nt0ki , 

Thank you for the detailed explanation and feedback. I understand your point about not tracking ZeUSD as TVL under CDP since it reflects the circulating supply rather than the locked assets.

Here are a few points for clarification and potential next steps:

- **Using Our API for Pricing:**
Since ZeUSD is currently not publicly traded yet, can we use our API to provide the pricing required to calculate the total market supply of the stablecoin? This would allow ZeUSD to be listed on the stablecoin dashboard.

- **Future Plans for Open Markets:**
We plan to list ZeUSD on open markets soon. Once that happens, the token pricing can be fetched directly from platforms like CoinGecko or CoinMarketCap instead of relying on our API.

- **Alternative Option: Listing as RWA:**
Alternatively, could ZeUSD be listed as an RWA-backed token for now? Since the token is fixed at $1, TVL can be calculated by multiplying the total supply of ZeUSD with the $1 price provided through our API.

Please let me know which approach works best or if there’s any additional information you need from my side.

Looking forward to your guidance!

**Comment by g1nt0ki** [comment]
hi, 

we cant list ZeUSD as rwa since the product is cdp. 
For listing in stablecoin dashboard, I would wait for it to be publicly traded & listing coingecko, as we dont want to track a stablecoin not in the market.  

Closing this PRfor now, can re-open this when non-zoth related tokens are locked to mint zeUSD

**Pull request closed without merging**
