### PR TITLE
Create blume-fm.js

### PR DESCRIPTION
**Pull request by mergd**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Blume 

##### Twitter Link:
https://twitter.com/blumefm

##### Website Link:

https://blume.fm/

##### Logo (High resolution, will be shown with rounded borders):
https://i.ibb.co/hyVH2m8/blume.png

##### Current TVL:
869.12K

##### Chain:
Blast

##### Short Description (to be shown on DefiLlama):
Blume is a lending protocol with native yield on Blast.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### forkedFrom (Does your project originate from another project):
CompoundV2

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/blume-fm.js: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:220:11

**Comment by llamatester** [comment]
The adapter at projects/blume-fm exports TVL: 
        
 
 
    blast-borrowed            0
    blast                     372.83 k
    borrowed                  0
    
    total                    372.83 k

**Comment by llamatester** [comment]
The adapter at projects/blume-fm exports TVL: 
        
 
 
    blast-borrowed            0
    blast                     940.51 k
    borrowed                  0
    
    total                    940.51 k

**Comment by g1nt0ki** [comment]
@mergd thanks for the PR

Issue was, you were using WETH and the code was looking for native ether. The blacklist is meant for excluding certain tokens, like if your protocol had a synth usd token that it minted and deposited, it needs to be excluded.

**Pull request merged**
