### PR TITLE
Add bsc to mcdex-v3

### PR DESCRIPTION
**Pull request by mc-zhangyang**
We have added bsc tvl, and removed the code related to the mainnet. Currently our project is deployed on arbitrum and bsc, mainnet is deprecated.

### CODE REVIEW

**Comment by 0xngmi** [comment]
can we keep mcdex ethereum even if tvl is almost 0? it will help people see the evolution of mcdex on eth

**Comment by 0xngmi** [comment]
can we keep mcdex ethereum even if tvl is almost 0? it will help people see the evolution of mcdex on eth

**Comment by realmeh** [comment]
Yeah, good suggestion. we will keep mcdex Ethereum TVL. Let's update the pull request.

**Comment by mc-zhangyang** [comment]
We have updated the pull request, please check and merge it.

**Pull request merged**
