### PR TITLE
Add MAYAChain

### PR DESCRIPTION
**Pull request by GiMa-Maya**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Maya Protocol

##### Twitter Link:
https://twitter.com/Maya_Protocol

##### List of audit links if any:
https://docs.mayaprotocol.com/deep-dive/audits

##### Website Link:
https://www.mayaprotocol.com

##### Logo (High resolution, will be shown with rounded borders):
Blue_Icon_Maya

##### Current TVL:
$16,944,708

##### Treasury Addresses (if the protocol has treasury)
-

##### Chain:
MAYAChain (And we have integrated Bitcoin, Ethereum, THORChain and Dash so far)

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
https://coinmarketcap.com/currencies/maya/

##### Short Description (to be shown on DefiLlama):
MAYAChain is an cross-chain Automated Market Maker (AMM). MAYAChain is a friendly fork of THORChain. Similarly, it does not rely on pegging or wrapping assets, instead managing funds directly in on-chain vaults and safeguarding them through economic security. This is achieved using the Tendermint consensus engine, Cosmos-SDK state machine, and GG20 Threshold Signature Scheme (TSS).

##### Token address and ticker if any:
CACAO

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dex

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
No orable.

##### forkedFrom (Does your project originate from another project):
THORChain

##### methodology (what is being counted as tvl, how is tvl being calculated):
All provided liquidity is being counted as TVL. So it's the sum of all liquidity in all pools on Maya.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://gitlab.com/mayachain

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/mayachain: 
        
 
  
    
    
    Error: 
        Unknown chain(s): mayachain, dash
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file

**Comment by llamatester** [comment]
Error while running adapter at projects/mayachain: 
        
 
  
    
    
    Error: Invalid balance: NaN
    Truncated error stack:
        at isValidNumber (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:119:19)
        at addPool (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/mayachain/index.js:56:18)
        at Array.map (<anonymous>)
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/mayachain/index.js:36:27)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)
        at async Promise.all (index 2)

**Comment by g1nt0ki** [comment]
sorry for the delay, will review this soon

**Comment by GiMa-Maya** [comment]
Thanks!

**Comment by llamatester** [comment]
The adapter at projects/mayachain exports TVL: 
        
 
 
    thorchain                 0
    mayachain-staking         0
    mayachain                 0
    bitcoin                   26.00 k
    dash                      851.4
    ethereum                  18.06 k
    staking                   0
    
    total                    44.91 k

**Comment by g1nt0ki** [comment]
> Thanks!

I think I fixed the bug, but the tvl is still low, are you sure the base decimal is 10**8?

**Comment by GiMa-Maya** [comment]
That's not right indeed. Total is around 20m

**Comment by llamatester** [comment]
The adapter at projects/mayachain exports TVL: 
        
 
 
    thorchain                 0
    bitcoin                   25.80 k
    ethereum                  17.95 k
    dash                      842.16
    mayachain-staking         0
    mayachain                 0
    staking                   0
    
    total                    44.60 k

**Comment by llamatester** [comment]
The adapter at projects/mayachain exports TVL: 
        
 
 
    thorchain                 0
    dash                      842.16
    bitcoin                   25.85 k
    mayachain                 0
    mayachain-staking         0
    ethereum                  17.95 k
    staking                   0
    
    total                    44.64 k

**Comment by llamatester** [comment]
The adapter at projects/mayachain exports TVL: 
        
 
 
    bitcoin                   25.51 k
    thorchain                 44.64 k
    mayachain-staking         0
    mayachain                 0
    ethereum                  1.47 M
    dash                      833.58
    staking                   0
    
    total                    1.54 M

**Comment by llamatester** [comment]
The adapter at projects/mayachain exports TVL: 
        
 
 
    bitcoin                   25.47 k
    thorchain                 44.64 k
    dash                      826.9799999999999
    mayachain                 0
    ethereum                  1.46 M
    
    total                    1.53 M

**Comment by llamatester** [comment]
Error while running adapter at projects/mayachain: 
        
 
  
    
    
    ReferenceError: ETH is not defined
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/mayachain/index.js:39:69
        at Array.filter (<anonymous>)
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/mayachain/index.js:39:44)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)
        at async Promise.all (index 2)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by llamatester** [comment]
Error while running adapter at projects/mayachain: 
        
 
  
    
    
    Error: no decimals for 0xdac17f958d2ee523a2206206994597c13d831ec7
    Truncated error stack:
    
        at addPool (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/mayachain/index.js:63:39)
        at Array.map (<anonymous>)
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/mayachain/index.js:43:27)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)
        at async Promise.all (index 2)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by llamatester** [comment]
Error while running adapter at projects/mayachain: 
        
 
  
    
    
    ReferenceError: nativeDecimal is not defined
    Truncated error stack:
    
        at addPool (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/mayachain/index.js:61:42)
        at Array.map (<anonymous>)
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/mayachain/index.js:43:27)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)
        at async Promise.all (index 2)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by llamatester** [comment]
Error while running adapter at projects/mayachain: 
        
 
  
    
    
    TypeError: Cannot read properties of null (reading 'timestamp')
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/computeTVL/blocks.js:104:63

**Comment by llamatester** [comment]
Error while running adapter at projects/mayachain: 
        
 
  
    
    
    ReferenceError: nativeDecimal is not defined
    Truncated error stack:
    
        at addPool (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/mayachain/index.js:61:42)
        at Array.map (<anonymous>)
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/mayachain/index.js:43:27)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)
        at async Promise.all (index 2)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by llamatester** [comment]
The adapter at projects/mayachain exports TVL: 
        
 
 
    mayachain                 0
    bitcoin                   25.50 k
    thorchain                 44.36 k
    dash                      830.28
    ethereum                  1.46 M
    
    total                    1.53 M

**Comment by g1nt0ki** [comment]
@GiMa-Maya hi, this PR has been open for a while, is the tvl correct now?

**Pull request closed without merging**
