### PR TITLE
Add void adapter & treasury

### PR DESCRIPTION
**Pull request by Avedith**
##### Name (to be shown on DefiLlama):
Void

##### Twitter Link:
https://twitter.com/VoidToken_fi

##### List of audit links if any:
N/A

##### Website Link:
https://void.money/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
VOID200x200

##### Current TVL:
$95.4k

##### Treasury Addresses (if the protocol has treasury)
0xf0a793024Ac47e421EB8c4673212dfCcE42f4a97

##### Chain:
Fantom

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
void-ad9a561a-8bca-4c17-9a3f-483f5cf20ac0 (Don't even ask me why it has such a weird ID)

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

##### Short Description (to be shown on DefiLlama):
VOID NEXT GENERATION HYBRID AUTO-REWARDING PROTOCOL  - VOID rewards holders with an automatic $DAI Reflection from the Treasury and with each transaction done with $VOID. Simply hold VOID and earn passive income from multiple revenue streams.

##### Token address and ticker if any:
0x80F2B8CdbC470c4DB4452Cc7e4a62F5277Db7061 (VOID)

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
N/A

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
Counting the LP tokens locked in the Fantom Treasury & counting the tokens locked in the Token Reflections Award contract

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/void exports TVL: 
        
 
 
    fantom                    95.40 k
    
    total                    95.40 k

**Comment by llamatester** [comment]
The adapter at projects/void exports TVL: 
        
 
 
    fantom                    95.40 k
    
    total                    95.40 k

**Comment by Avedith** [comment]
Couldn't get any of the LP unwraps to work, so just counting the LP with sumTokens2 (As they own all of the LP anyways). They are fine with it showing like this anyways.

**Comment by llamatester** [comment]
The adapter at projects/treasury/void.js exports TVL: 
        
 
 
    fantom-ownTokens          27.59 M
    fantom                    95.33 k
    ownTokens                 27.59 M
    
    total                    95.33 k

**Comment by llamatester** [comment]
The adapter at projects/void exports TVL: 
        
 
 
    fantom                    0
    fantom-staking            7.20 k
    staking                   7.20 k
    
    total                    0

**Comment by g1nt0ki** [comment]
hi @Avedith , this is close to OHM only protocol where we count treasury as tvl (bit of grey area), I have decided not do that for new protocol, especially since we now have a treasury metric, so I have moved it there.

**Pull request merged**
