### PR TITLE
Add Ease protocol

### PR DESCRIPTION
**Pull request by dominikpre**
##### Name (to be shown on DefiLlama):
Ease.org DeFi Cover

##### Twitter Link:
https://twitter.com/EaseDeFi

##### List of audit links if any:
https://github.com/EaseDeFi/Audits/blob/main/Dedaub_RCA_Audit.pdf
https://github.com/EaseDeFi/gvToken/tree/main/audits

##### Website Link:
https://ease.org/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://ease.org/wp-content/uploads/2022/03/logo.png

##### Current TVL:
-

##### Chain:
Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
ease

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
WIP

##### Short Description (to be shown on DefiLlama):
Ease is a decentralized coverage protocol that enables users to protect their DeFi tokens without a premium while earning compounding yield.

##### Token address and ticker if any:
0xEa5eDef1287AfDF9Eb8A46f9773AbFc10820c61c - $EASE

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Insurance

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
-

##### forkedFrom (Does your project originate from another project):
-

##### methodology (what is being counted as tvl, how is tvl being calculated):
Tokens that users deposit into our contracts are being counted as TVL.
Additionally, if users stake our $EASE token into our bribing contract or $gvEASE contract, we count that as TVL.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/ease exports TVL: 
        
 
 
    ethereum-staking          158.34 k
    ethereum                  6932.94 B
    staking                   158.34 k
    
    total                    6932.94 B

**Comment by g1nt0ki** [comment]
@dominikpre I dont have permission to edit the code here but I have messaged you how to fix the bug, the code looks good otherwise

**Comment by dominikpre** [comment]
@g1nt0ki Thanks you! But I can't find your message... Fixed the script recently though. Only thing that doesn't seem to work is TVL for Convex deposit tokens.

**Comment by g1nt0ki** [comment]
@waynebruce0x can something be done about convex tokens?

**Comment by llamatester** [comment]
The adapter at projects/ease exports TVL: 
        
 
 
    ethereum-staking          179.83 k
    ethereum                  60.30 k
    staking                   179.83 k
    
    total                    60.30 k

**Comment by dominikpre** [comment]
@g1nt0ki Talked to waynebruce0x already on discord. Think he implemented the prices for the convex prices already :)

**Pull request merged**
