### PR TITLE
Token label

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/01 exports TVL: 
        
 
 
    solana                    12.75 M
    
    total                    12.75 M

**Comment by llamatester** [comment]
The adapter at projects/0vix exports TVL: 
        
 
 
    polygon                   1.20 M
    polygon_zkevm-borrowed    373.36 k
    polygon_zkevm             461.36 k
    borrowed                  373.36 k
    
    total                    1.66 M

**Comment by llamatester** [comment]
The adapter at projects/0x_nodes exports TVL: 
        
 
 
    ethereum                  0
    bsc                       0
    polygon                   0
    fantom                    0
    metis                     0
    avax                      0
    bsc-staking               0
    ethereum-staking          0
    fantom-staking            0
    avax-staking              0
    polygon-staking           5.37 k
    metis-staking             2.23 k
    staking                   7.60 k
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/1bch exports TVL: 
        
 
 
    smartbch-staking          2.03 k
    smartbch                  11.64 k
    staking                   2.03 k
    
    total                    11.64 k

**Comment by llamatester** [comment]
The adapter at projects/1beam exports TVL: 
        
 
 
    moonbeam                  3.09 k
    
    total                    3.09 k

**Comment by llamatester** [comment]
Error while running adapter at projects/1inch: 
        
 
  
    
    
    PromisePoolError: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0xcA11bde05977b3631167028862bE2a173976CA11","data":"0xbce38bd700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000001e00000000000000000000000000000000000000000000000000000000000000280000000000000000000000000000000000000000000000000000000000000032000000000000000000000000000000000000000000000000000000000000003c00000000000000000000000000000000000000000000000000000000000000460000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000005a0000000000000000000000000000000000000000000000000000000000000064000000000000000000000000000000000000000000000000000000000000006e0000000000000000000000000d41b24bba51fac0e4827b6f94c0d6ddeb183cd640000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000056e00000000000000000000000000000000000000000000000000000000000000000000000000000000d41b24bba51fac0e4827b6f94c0d6ddeb183cd640000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000056f00000000000000000000000000000000000000000000000000000000000000000000000000000000d41b24bba51fac0e4827b6f94c0d6ddeb183cd640000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000057000000000000000000000000000000000000000000000000000000000000000000000000000000000d41b24bba51fac0e4827b6f94c0d6ddeb183cd640000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000057100000000000000000000000000000000000000000000000000000000000000000000000000000000d41b24bba51fac0e4827b6f94c0d6ddeb183cd640000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000057200000000000000000000000000000000000000000000000000000000000000000000000000000000d41b24bba51fac0e4827b6f94c0d6ddeb183cd640000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000057300000000000000000000000000000000000000000000000000000000000000000000000000000000d41b24bba51fac0e4827b6f94c0d6ddeb183cd640000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000057400000000000000000000000000000000000000000000000000000000000000000000000000000000d41b24bba51fac0e4827b6f94c0d6ddeb183cd640000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000057500000000000000000000000000000000000000000000000000000000000000000000000000000000d41b24bba51fac0e4827b6f94c0d6ddeb183cd640000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000057600000000000000000000000000000000000000000000000000000000000000000000000000000000d41b24bba51fac0e4827b6f94c0d6ddeb183cd640000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000057700000000000000000000000000000000000000000000000000000000","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    Truncated error stack:
        at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
The adapter at projects/01 exports TVL: 
        
 
 
    solana                    12.73 M
    
    total                    12.73 M

**Comment by llamatester** [comment]
The adapter at projects/0vix exports TVL: 
        
 
 
    polygon_zkevm             460.63 k
    polygon_zkevm-borrowed    373.43 k
    polygon                   1.20 M
    borrowed                  373.43 k
    
    total                    1.66 M

**Comment by llamatester** [comment]
The adapter at projects/0x_nodes exports TVL: 
        
 
 
    ethereum                  0
    bsc                       0
    polygon                   0
    fantom                    0
    metis                     0
    avax                      0
    avax-staking              0
    ethereum-staking          0
    bsc-staking               0
    fantom-staking            0
    polygon-staking           5.37 k
    metis-staking             2.23 k
    staking                   7.60 k
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/1bch exports TVL: 
        
 
 
    smartbch-staking          2.03 k
    smartbch                  11.63 k
    staking                   2.03 k
    
    total                    11.63 k

**Comment by llamatester** [comment]
The adapter at projects/1beam exports TVL: 
        
 
 
    moonbeam                  3.09 k
    
    total                    3.09 k

**Comment by llamatester** [comment]
Error while running adapter at projects/1inch: 
        
 
  
    
    
    PromisePoolError: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0xcA11bde05977b3631167028862bE2a173976CA11","data":"0xbce38bd700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000001e00000000000000000000000000000000000000000000000000000000000000280000000000000000000000000000000000000000000000000000000000000032000000000000000000000000000000000000000000000000000000000000003c00000000000000000000000000000000000000000000000000000000000000460000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000005a0000000000000000000000000000000000000000000000000000000000000064000000000000000000000000000000000000000000000000000000000000006e0000000000000000000000000baf9a5d4b0052359326a6cdab54babaa3a3a96430000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000014a00000000000000000000000000000000000000000000000000000000000000000000000000000000baf9a5d4b0052359326a6cdab54babaa3a3a96430000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000014b00000000000000000000000000000000000000000000000000000000000000000000000000000000baf9a5d4b0052359326a6cdab54babaa3a3a96430000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000014c00000000000000000000000000000000000000000000000000000000000000000000000000000000baf9a5d4b0052359326a6cdab54babaa3a3a96430000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000014d00000000000000000000000000000000000000000000000000000000000000000000000000000000baf9a5d4b0052359326a6cdab54babaa3a3a96430000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000014e00000000000000000000000000000000000000000000000000000000000000000000000000000000baf9a5d4b0052359326a6cdab54babaa3a3a96430000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000014f00000000000000000000000000000000000000000000000000000000000000000000000000000000baf9a5d4b0052359326a6cdab54babaa3a3a96430000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000015000000000000000000000000000000000000000000000000000000000000000000000000000000000baf9a5d4b0052359326a6cdab54babaa3a3a96430000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000015100000000000000000000000000000000000000000000000000000000000000000000000000000000baf9a5d4b0052359326a6cdab54babaa3a3a96430000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000015200000000000000000000000000000000000000000000000000000000000000000000000000000000baf9a5d4b0052359326a6cdab54babaa3a3a96430000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000015300000000000000000000000000000000000000000000000000000000","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    Truncated error stack:
        at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
The adapter at projects/01 exports TVL: 
        
 
 
    solana                    12.74 M
    
    total                    12.74 M

**Comment by llamatester** [comment]
The adapter at projects/0vix exports TVL: 
        
 
 
    polygon                   1.20 M
    polygon_zkevm             460.98 k
    polygon_zkevm-borrowed    373.55 k
    borrowed                  373.55 k
    
    total                    1.66 M

**Comment by llamatester** [comment]
The adapter at projects/0xDAO exports TVL: 
        
 
 
    fantom                    1.42 M
    
    total                    1.42 M

**Comment by llamatester** [comment]
The adapter at projects/0x_nodes exports TVL: 
        
 
 
    ethereum                  0
    bsc                       0
    polygon                   0
    fantom                    0
    metis                     0
    avax                      0
    avax-staking              0
    bsc-staking               0
    fantom-staking            0
    ethereum-staking          0
    metis-staking             2.23 k
    polygon-staking           5.37 k
    staking                   7.60 k
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/0xacid exports TVL: 
        
 
 
    arbitrum                  0
    arbitrum-staking          6.41 M
    staking                   6.41 M
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/1bch exports TVL: 
        
 
 
    smartbch-staking          2.03 k
    smartbch                  11.64 k
    staking                   2.03 k
    
    total                    11.64 k

**Comment by llamatester** [comment]
The adapter at projects/1beam exports TVL: 
        
 
 
    moonbeam                  3.09 k
    
    total                    3.09 k

**Comment by llamatester** [comment]
Error while running adapter at projects/1inch: 
        
 
  
    
    
    PromisePoolError: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0xcA11bde05977b3631167028862bE2a173976CA11","data":"0xbce38bd700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000001e00000000000000000000000000000000000000000000000000000000000000280000000000000000000000000000000000000000000000000000000000000032000000000000000000000000000000000000000000000000000000000000003c00000000000000000000000000000000000000000000000000000000000000460000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000005a0000000000000000000000000000000000000000000000000000000000000064000000000000000000000000000000000000000000000000000000000000006e0000000000000000000000000baf9a5d4b0052359326a6cdab54babaa3a3a96430000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000014a00000000000000000000000000000000000000000000000000000000000000000000000000000000baf9a5d4b0052359326a6cdab54babaa3a3a96430000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000014b00000000000000000000000000000000000000000000000000000000000000000000000000000000baf9a5d4b0052359326a6cdab54babaa3a3a96430000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000014c00000000000000000000000000000000000000000000000000000000000000000000000000000000baf9a5d4b0052359326a6cdab54babaa3a3a96430000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000014d00000000000000000000000000000000000000000000000000000000000000000000000000000000baf9a5d4b0052359326a6cdab54babaa3a3a96430000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000014e00000000000000000000000000000000000000000000000000000000000000000000000000000000baf9a5d4b0052359326a6cdab54babaa3a3a96430000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000014f00000000000000000000000000000000000000000000000000000000000000000000000000000000baf9a5d4b0052359326a6cdab54babaa3a3a96430000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000015000000000000000000000000000000000000000000000000000000000000000000000000000000000baf9a5d4b0052359326a6cdab54babaa3a3a96430000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000015100000000000000000000000000000000000000000000000000000000000000000000000000000000baf9a5d4b0052359326a6cdab54babaa3a3a96430000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000015200000000000000000000000000000000000000000000000000000000000000000000000000000000baf9a5d4b0052359326a6cdab54babaa3a3a96430000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002441d1de97000000000000000000000000000000000000000000000000000000000000015300000000000000000000000000000000000000000000000000000000","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    Truncated error stack:
        at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
The adapter at projects/01 exports TVL: 
        
 
 
    solana                    12.29 M
    
    total                    12.29 M

**Comment by llamatester** [comment]
The adapter at projects/0vix exports TVL: 
        
 
 
    polygon                   1.14 M
    polygon_zkevm-borrowed    266.19 k
    polygon_zkevm             407.77 k
    borrowed                  266.19 k
    
    total                    1.54 M

**Comment by llamatester** [comment]
The adapter at projects/0xDAO exports TVL: 
        
 
 
    fantom                    1.18 M
    
    total                    1.18 M

**Comment by llamatester** [comment]
The adapter at projects/0x_nodes exports TVL: 
        
 
 
    ethereum                  0
    bsc                       0
    polygon                   0
    fantom                    0
    metis                     0
    avax                      0
    ethereum-staking          0
    fantom-staking            0
    avax-staking              0
    bsc-staking               0
    polygon-staking           5.02 k
    metis-staking             2.09 k
    staking                   7.11 k
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/1bch exports TVL: 
        
 
 
    smartbch-staking          1.79 k
    smartbch                  11.33 k
    staking                   1.79 k
    
    total                    11.33 k

**Comment by llamatester** [comment]
The adapter at projects/1beam exports TVL: 
        
 
 
    moonbeam                  3.09 k
    
    total                    3.09 k

**Comment by llamatester** [comment]
Error while running adapter at projects/1inch: 
        
 
  
    
    
    PromisePoolError: Request failed with status code 500
    Truncated error stack:
        at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 2)

**Review by alokeutpal — APPROVED** [review]

**Pull request merged**
