### PR TITLE
Klex

### PR DESCRIPTION
**Pull request by g1nt0ki**
##### Name (to be shown on DefiLlama):
KLEX Finance

##### Twitter Link:
https://twitter.com/klexfinance

##### List of audit links if any:
https://github.com/balancer-labs/balancer-v2-monorepo/tree/master/audits

##### Website Link:
https://klex.finance

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://raw.githubusercontent.com/Klaytn-Defi/assets/master/cypress/klex/icon-dark.svg
https://raw.githubusercontent.com/Klaytn-Defi/assets/master/cypress/klex/icon-white.svg

##### Current TVL:
32.51 M

##### Chain:
Klaytn

##### Short Description (to be shown on DefiLlama):
KLEX is a protocol for programmable liquidity.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### forkedFrom (Does your project originate from another project):
https://github.com/balancer-labs/balancer-v2-monorepo

##### methodology (what is being counted as tvl, how is tvl being calculated):
All StablePhantom, Stable, Weighted, and Lienar pool TVL is added together.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/klex: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:223:11

**Comment by llamatester** [comment]
The adapter at projects/klex exports TVL: 
        
 
 
    klaytn                    18.21 M
    
    total                    18.21 M

**Comment by llamatester** [comment]
The adapter at projects/klex exports TVL: 
        
 
 
    klaytn                    18.21 M
    
    total                    18.21 M

**Comment by llamatester** [comment]
The adapter at projects/klex exports TVL: 
        
 
 
    klaytn                    18.21 M
    
    total                    18.21 M

**Comment by 0xinsanity** [comment]
@g1nt0ki I think it is not counting AaveLinear pools when you made the change. Do you know why that is?

**Comment by g1nt0ki** [comment]
> @g1nt0ki I think it is not counting AaveLinear pools when you made the change. Do you know why that is?

noticed that, is there some reference for mapping the aave tokens? they are bridged via wormhole/portal right? I am unable to find relevant documentation

but even including those, their token amount is negligible right?

**Comment by g1nt0ki** [comment]
like there is 14M difference, just to be clear AaveLinear pools  also keep the tokens in `0xb519Cf56C63F013B0320E89e1004A8DE8139dA27` right?

**Comment by g1nt0ki** [comment]
I will merge this and fix the missing aave tokens

**Pull request merged**
