### PR TITLE
Spectra finance

### PR DESCRIPTION
**Pull request by jeanchambras**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

Spectra

Spectra is the V2 of APWine finance already available at https://defillama.com/protocol/spectra#information and with these adapters [APWine (Spectra V1)](https://github.com/DefiLlama/DefiLlama-Adapters/tree/a9337eb3acc2fe7a53f5d9fbf698ad74b876d7e8/projects/apwine). We would stack from both versions under Spectra Finance.

##### Twitter Link: 

https://twitter.com/spectra_finance

##### List of audit links if any:

 https://code4rena.com/reports/2024-02-spectra
https://github.com/pashov/audits/blob/master/team/pdf/Spectra-security-review.pdf

##### Website Link:

https://www.spectra.finance/

##### Logo (High resolution, will be shown with rounded borders):

logo512

##### Current TVL:

~ $200k on spectra 

##### Treasury Addresses (if the protocol has treasury)

0xDbbfc051D200438dd5847b093B22484B842de9E7

##### Chain:

Ethereum Mainnet [1]
Arbitrum One [42161]

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

id: apwine 

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

id: 10364

##### Short Description (to be shown on DefiLlama):

Spectra is an EVM-centric protocol for interest rate derivatives with an easy-to-use flagship app. The Spectra protocol is permissionless, meaning its services are entirely open for public use. Anyone can create new markets at will, enter a fixed rate, swap yield derivatives,  or become a liquidity provider.

##### Token address and ticker if any:

0x4104b135dbc9609fc1a9490e61369036497660c8
APW

##### Category (full list at https://defillama.com/categories) *Please choose only one:

[Yield](https://defillama.com/protocols/Yield)

##### methodology (what is being counted as tvl, how is tvl being calculated):

TVL counts the assets deposited in Spectra Principal Tokens (PT) and Spectra pools without double-counting assets already deposited in the PT contracts (the pool only counts the asset side).

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/spectra: 
        
 
  
    
    
    Error: TypeError: Cannot read properties of undefined (reading 'stateMutability')

**Comment by llamatester** [comment]
Error while running adapter at projects/spectra: 
        
 
  
    
    
    Error: TypeError: Cannot read properties of undefined (reading 'stateMutability')

**Comment by llamatester** [comment]
The adapter at projects/spectra exports TVL: 
        
 
 
    ethereum                  215.55 k
    arbitrum                  0
    
    total                    215.55 k

**Comment by waynebruce0x** [comment]
Where on the UI can I interact with the markets counted here?

**Comment by jeanchambras** [comment]
Hi sir, it is now available at https://app.spectra.finance/

**Comment by llamatester** [comment]
The adapter at projects/spectra exports TVL: 
        
 
 
    ethereum                  12.44 M
    arbitrum                  0
    
    total                    12.44 M

**Pull request merged**
