### PR TITLE
Add Zombie Network adapter

### PR DESCRIPTION
**Pull request by ZombieNetwork**
##### Twitter Link:
https://twitter.com/ZombieNetworkfi

##### Website Link:
https://zombie-network.fi

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
_discord-profile 1

##### Short Description (to be shown on DefiLlama):
1% Daily ROI Deflationary Token

##### Token address and ticker if any:
0x07709260f6C431bc2CB1480F523F4F7c639a5155 (BLOOD)

##### Category (full list at https://defillama.com/categories) *Please choose only one:
YIELD

##### forkedFrom (Does your project originate from another project):
DRIP NETWORK (https://drip.community)

##### methodology (what is being counted as tvl, how is tvl being calculated):
sum of the liquidity pool and the balance of valut.

### CODE REVIEW

**Comment by waynebruce0x** [comment]
How is TVL calculated on the contract? Can you verify the contract so we can see?

**Comment by llamatester** [comment]
The adapter at projects/zombie-network/index.js exports TVL: 
        
 
 
    klaytn                    7.97 M
    
    total                    7.97 M

**Comment by ZombieNetwork** [comment]
I updated the code so that you can see how to calculate the TVL.
TVL is calculated as the sum of the liquidity pool and the balance of valut.
Please review and merge code.

**Comment by ZombieNetwork** [comment]
@waynebruce0x 
Changed the code so that the price calc contract is not used

**Comment by llamatester** [comment]
The adapter at projects/zombie-network exports TVL: 
        
 
 
    klaytn                    0
    klaytn-pool2              6.43 M
    pool2                     6.43 M
    
    total                    0

**Pull request merged**
