### PR TITLE
remove console.log

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bigdataprotocol exports TVL: 
        
 
 
    ethereum-staking          226.91 k
    ethereum                  466.48 k
    staking                   226.91 k
    
    total                    466.48 k

**Comment by llamatester** [comment]
The adapter at projects/brahmafi exports TVL: 
        
 
 
    ethereum                  2.22 M
    
    total                    2.22 M

**Comment by llamatester** [comment]
The adapter at projects/chest-finance exports TVL: 
        
 
 
    solana                    1.05 M
    
    total                    1.05 M

**Comment by llamatester** [comment]
Error while running adapter at projects/fortube: 
        
 
  
    
    
    Error: invalid BigNumber value (argument="value", value=undefined, code=INVALID_ARGUMENT, version=bignumber/5.6.2)
    Truncated error stack:
        at Function.BigNumber.from (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/bignumber/lib/bignumber.js:239:23)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:92:14
        at Array.forEach (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:91:50
        at Array.map (<anonymous>)
        at mergeBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:90:16)

**Review by alokeutpal — APPROVED** [review]

**Pull request merged**
