### PR TITLE
Add Aloe adapter

### PR DESCRIPTION
**Pull request by haydenshively**
##### Name (to be shown on DefiLlama):
Aloe

##### Twitter Link:
https://x.com/aloecapital

##### List of audit links if any:
https://github.com/aloelabs/aloe-ii/tree/master/audits

##### Website Link:
https://aloe.capital

##### Logo (High resolution, will be shown with rounded borders):
Logo (Primary)

##### Current TVL:
TVL for each chain can be viewed on https://app.aloe.capital/markets

##### Chain:
Ethereum, Optimism, Base, Arbitrum

##### Short Description (to be shown on DefiLlama):
Aloe is a permissionless lending protocol built on Uniswap, featuring risk-isolated pools, dynamic LTVs, and ultra-efficient liquidations.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Uniswap V3 30-minute TWAP with decentralized Oracle Guardian. The Oracle Guardian compares 30-minute and 60-minute TWAPs to detect manipulation. If any is detected, markets can be paused permissionlessly.

##### Implementation Details: Briefly describe how the oracle is integrated into your project:
A combination of price and implied volatility are used to determine borrower health and liquidation eligibility.

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
https://docs.aloe.capital

##### forkedFrom (Does your project originate from another project):
None

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is measured as the sum of all deposits across Aloe's ERC4626 lending vaults. It does not include borrowers' collateral. Total borrows is what you'd expect－the total current outstanding borrows.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/aloelabs

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/aloe exports TVL: 
        
 
 
    ethereum                  7.13 k
    ethereum-borrowed         6.70 k
    base-borrowed             333.50 k
    optimism-borrowed         196.96 k
    optimism                  304.77 k
    base                      509.40 k
    arbitrum-borrowed         369.29 k
    arbitrum                  554.48 k
    borrowed                  906.45 k
    
    total                    1.38 M

**Comment by llamatester** [comment]
The adapter at projects/aloe exports TVL: 
        
 
 
    optimism-borrowed         196.82 k
    ethereum                  7.13 k
    optimism                  304.19 k
    ethereum-borrowed         6.69 k
    base-borrowed             333.49 k
    arbitrum-borrowed         369.12 k
    base                      509.30 k
    arbitrum                  554.22 k
    borrowed                  906.12 k
    
    total                    1.37 M

**Comment by g1nt0ki** [comment]
@haydenshively thanks for the PR, refactored and merged it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/9547

changes made, we dont track borrowed value for legerage farming protocols since the borrowed assets dont leave the protocol, and marked it as doublecounted as we are already counting part of the tvl (borrowed and farmed in dex) for the chain already, this flag affects the chain tvl, not your protocol's :)

**Comment by haydenshively** [comment]
Hi @g1nt0ki, Aloe is not a leveraged farming protocol, and the borrowed assets do leave the protocol. Nothing is double counted. Can we please revert to this version of the PR?

Appreciate your time, thanks!

**Comment by g1nt0ki** [comment]
hi @haydenshively borrowed assets are taken out by the user? I thought it was instead used in providing LP to uni v3 pools, if this is not the case, how does uni v3 pools come into play? 

Marked as doublecounted as I thought the borrowed funds are in uni v3 pools

**Comment by haydenshively** [comment]
The user gets to choose. As on other lending protocols, they could take the borrows out to their wallet and proceed to hold/swap/LP/etc. On Aloe it's just that if they _happen_ to LP, they can do so within a `Borrower` account so that the position counts as collateral.

I don't think AAVE borrows are marked as doublecounted just because a user _may_ use those funds to LP, so I don't think they should be here either.

**Pull request closed without merging**
