### PR TITLE
added treasury

### PR DESCRIPTION
**Pull request by Shivansh070707**
added unore-treasury

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/treasury/unore.js exports TVL: 
        
 
 
    ethereum-ownTokens        1.53 M
    ethereum                  497.21 k
    ownTokens                 1.53 M
    
    total                    497.21 k

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
hi @Shivansh070707 thanks for the PR, but only the first address is a multisig, rest are EOAs? can you comment those out?

**Comment by Shivansh070707** [comment]
Sure

**Comment by llamatester** [comment]
The adapter at projects/treasury/unore.js exports TVL: 
        
 
 
    ethereum-ownTokens        1.53 M
    ethereum                  496.98 k
    ownTokens                 1.53 M
    
    total                    496.98 k

**Comment by Shivansh070707** [comment]
mentioned multisig address

**Comment by SujithSizon** [comment]
Hey @g1nt0ki sujith here from the uno team, do you want us to comment out the EOAs? this wouldn't be useful for us then as those tokens held in those EOAs are part of our treasury assets?

Or do you mean for u to label out the correct multi-sig version?

**Comment by g1nt0ki** [comment]
sorry, we dont count tokens on EOA as tvl or treasury for any project, can you move them to a multisig, or skip them from treasury value shown here?

**Comment by llamatester** [comment]
The adapter at projects/treasury/unore.js exports TVL: 
        
 
 
    ethereum-ownTokens        0
    ethereum                  501.33 k
    ownTokens                 0
    
    total                    501.33 k

**Comment by Shivansh070707** [comment]
hello , I pushed the changes , added only multisig

**Comment by g1nt0ki** [comment]
> hello , I pushed the changes , added only multisig

thanks

**Pull request merged**
