### PR TITLE
feat: veax adapter

### PR DESCRIPTION
**Pull request by flaminisx**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
VEAX

##### Twitter Link:
[https://twitter.com/veaxlabs)](https://twitter.com/veaxlabs)

##### List of audit links if any:
[https://docs.veax.com/overview/security/external-audit/veax-security-audit.pdf](https://docs.veax.com/overview/security/external-audit/veax-security-audit.pdf)

##### Website Link:
[https://veax.com/](https://veax.com/)

##### Logo (High resolution, will be shown with rounded borders):
[https://veax.fra1.cdn.digitaloceanspaces.com/logo-package-veax.zip](https://veax.fra1.cdn.digitaloceanspaces.com/logo-package-veax.zip)

##### Current TVL:
211.34 k

##### Treasury Addresses (if the protocol has treasury)
we don’t have any dedicated treasury address yet.

##### Chain:
NEAR

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
veax

##### Short Description (to be shown on DefiLlama):
Veax is a decentralized automated market maker protocol developed on the Near Protocol, featuring an innovative flexible fee mechanism to enhance liquidity provision efficiency.

##### Token address and ticker if any:
ticker is VEAX, token is not here, so we don’t have address

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
We are using CoinAPI for off-chain price discovery for users, calculating TVL, etc. It doesn’t impact protocol behavior in any way.

##### forkedFrom (Does your project originate from another project):
no

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is a sum of the value for all tokens locked in our smart contract by liquidity providers in exchange pools. To calculate the price in US$, we use weighted average token market prices from CoinAPI for popular tokens, and for other tokens, we derive prices from related exchange pools on VEAX.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/veax exports TVL: 
        
 
 
    near                      211.37 k
    
    total                    211.37 k

**Comment by g1nt0ki** [comment]
@flaminisx thanks for the PR, I have refactored your code here, can you take a look.

**Comment by g1nt0ki** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters/pull/6152

**Comment by flaminisx** [comment]
@g1nt0ki looks good to me, should I close this PR?

**Pull request merged**
