### PR TITLE
Bhavish prediction market integration

### PR DESCRIPTION
**Pull request by manti**
##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
image

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list) 
NA

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000) 
NA

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL/Volume is the total quantity of MATIC held in the Prediction SDK contract

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bhavish exports TVL: 
        
 
 
    polygon                   180.45 k
    
    total                    180.45 k

**Comment by g1nt0ki** [comment]
@manti thanks for the PR, but I see matic being forwarded to this address: https://polygonscan.com/address/0x9184f1fcc0ca6fca00f40a1709932caf66bdde5d#readContract but it holds only about 1.5K worth of matic, are you counting total volume instead of current user amount locked in your protocol?

**Comment by manti** [comment]
@g1nt0ki The contract listed above is one of the contracts for the prediction market. We have nine contracts in total, all of which are SDK-integrated.

Yes, we are counting total volume because users withdraw assets from the protocol every 5 minutes when the round closes; hence, for the prediction market, we should track total volume rather than the present user amount locked in your system.

```
    prediction_contract = {
        "eth" : "0x7a60DDE652a5a9E7514026Cd7a247BcE785133dC",
        "btc" : "0x9184f1fcC0CA6FCA00F40A1709932cAf66BDDE5D",
        "matic" : "0xB98522bAA393621fC1bEFcecfFC9cD033E7f0BcE",
        "bnb" : "0x8f210BBd1E664F28E29E3939cc01cDB34fDacf69",
        "apple" : "0xa7C6fc49E12BbE3FA5d2091FBEfBfbd8AAF4DE95",
        "tesla" : "0x2a69A0Fbabd15487d931140Bee4AF6dC1C4a8B52",
        "amazon" : "0x8550c8408995CAF7168b018d2C32E5D4a273D048",
        "gold" : "0x7533d6741C1297ec8b4Be21fF591D7ae61876891",
        "silver" : "0x0B7C1DE02771438F8130198882af2161f3016123"
    }

**Comment by g1nt0ki** [comment]
> @g1nt0ki The contract listed above is one of the contracts for the prediction market. We have nine contracts in total, all of which are SDK-integrated.
> 
> Yes, we are counting total volume because users withdraw assets from the protocol every 5 minutes when the round closes; hence, for the prediction market, we should track total volume rather than the present user amount locked in your system.
> 
> ```
>     prediction_contract = {
>         "eth" : "0x7a60DDE652a5a9E7514026Cd7a247BcE785133dC",
>         "btc" : "0x9184f1fcC0CA6FCA00F40A1709932cAf66BDDE5D",
>         "matic" : "0xB98522bAA393621fC1bEFcecfFC9cD033E7f0BcE",
>         "bnb" : "0x8f210BBd1E664F28E29E3939cc01cDB34fDacf69",
>         "apple" : "0xa7C6fc49E12BbE3FA5d2091FBEfBfbd8AAF4DE95",
>         "tesla" : "0x2a69A0Fbabd15487d931140Bee4AF6dC1C4a8B52",
>         "amazon" : "0x8550c8408995CAF7168b018d2C32E5D4a273D048",
>         "gold" : "0x7533d6741C1297ec8b4Be21fF591D7ae61876891",
>         "silver" : "0x0B7C1DE02771438F8130198882af2161f3016123"
>     }
> ```

sorry @manti , volume might be more appropriate metric for measuring user activity on your protocol but we cant use a different metric as tvl just for one protocol.  Can you update the adapter to count locked sum instead?

**Comment by g1nt0ki** [comment]
@manti do you want me to list the protocol with reduced tvl or close the PR instead?

**Comment by g1nt0ki** [comment]
closing this, please put a new PR with updated adapter if you still want to be listed

**Pull request closed without merging**
