### PR TITLE
update TVL of FWX 

### PR DESCRIPTION
**Pull request by idea2409**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/fwx exports TVL: 
        
 
 
    avax                      1.91 M
    
    total                    1.91 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
please compute tvl on chain

**Comment by g1nt0ki** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters/discussions/432

**Comment by g1nt0ki** [comment]
*I have just updated the adapter to include permissionless lending pool tvl

**Comment by llamatester** [comment]
The adapter at projects/fwx exports TVL: 
        
 
 
    avax                      399.29 k
    
    total                    399.29 k

**Comment by idea2409** [comment]
I just updated it following your suggestion.
Thank you very much (*＾▽＾)ノ

**Comment by g1nt0ki** [comment]
@idea2409 thanks for the PR, I made a minor fix: caching rest call response, this way, we have the data even if the endpoint becomes unreachable

**Pull request merged**
