### PR TITLE
Add Nord Finance

### PR DESCRIPTION
**Pull request by jvnord**
##### List of audit links if any: 
https://docs.nordfinance.io/security-audits/security-audits

### CODE REVIEW

**Comment by Nemusonaneko** [comment]
Can we get an adapter using our SDK?

**Comment by princeraj-nord** [comment]
> Can we get an adapter using our SDK?

SDK adapter doesn't fit our protocol so we have implemented a fetch adapter.

**Comment by Nemusonaneko** [comment]
> > Can we get an adapter using our SDK?
> 
> SDK adapter doesn't fit our protocol so we have implemented a fetch adapter.

If you have the contracts, I could give the adapter a go.

**Comment by princeraj-nord** [comment]
> > > Can we get an adapter using our SDK?
> > 
> > 
> > SDK adapter doesn't fit our protocol so we have implemented a fetch adapter.
> 
> If you have the contracts, I could give the adapter a go.

We are fetching tvl from our different contracts, all these contracts have holdings in different denominations and we are converting these holdings into a single USD denomination. We are maintaining our own module to calculate the tvl and in this way can easily add another smart contract that contributes to tvl. so fetch adapter fits perfectly to our protocol.

**Comment by waynebruce0x** [comment]
we much prefer on-chain data from sdk adapters, and it'd probably be easier to give nemusona the contract addresses. Our backend calculates the USD value of your tokens in TVL for you, and allows us to fetch historical data (which is useful if there are any outages etc). But if you choose to go the API route please make sure the API is open source so our users can see how it is all calculated , thanks

**Comment by princeraj-nord** [comment]
> we much prefer on-chain data from sdk adapters, and it'd probably be easier to give nemusona the contract addresses. Our backend calculates the USD value of your tokens in TVL for you, and allows us to fetch historical data (which is useful if there are any outages etc). But if you choose to go the API route please make sure the API is open source so our users can see how it is all calculated , thanks

API route fits in our case as of now and we have made tvl-api repo public which can be accessed from the below link. Let me know if any other steps need to be done to merge this PR.
https://github.com/nordfinance/nord-tvl-api

**Comment by waynebruce0x** [comment]
Sorry I've just checked the dapp and the current endpoint wont work because we need TVL to be broken down chain by chain @princeraj-nord

**Comment by princeraj-nord** [comment]
> TVL is consolidated value locked across different product offerings from different chains.

@waynebruce0x We have raised new PR with chain by chain tvl breakdown changes.
 https://github.com/DefiLlama/DefiLlama-Adapters/pull/2221

**Comment by princeraj-nord** [comment]
> Sorry I've just checked the dapp and the current endpoint wont work because we need TVL to be broken down chain by chain @princeraj-nord

@waynebruce0x We have raised new PR with chain by chain tvl breakdown changes.
https://github.com/DefiLlama/DefiLlama-Adapters/pull/2221

**Pull request merged**
