### PR TITLE
Create Strater

### PR DESCRIPTION
**Pull request by danhsucowboy**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

Strater

##### Twitter Link:

https://twitter.com/strater_sui

##### List of audit links if any:

https://github.com/Strater-sui/audit

##### Website Link:

https://www.strater.xyz/

##### Logo (High resolution, will be shown with rounded borders):

Strater's Team Library

##### Current TVL:

9.69 M

##### Chain:

SUI

##### Short Description (to be shown on DefiLlama):

[Strater](https://www.strater.xyz/) is a one-stop DeFi operation hub. We leverage programmable transaction blocks (PTBs) on Sui to revolutionize transaction execution, promising easy interaction and low gas fees. In addition, we offer diverse strategies and frictionless interactions to help our users realize high rewards with our easy-to-use tools

##### Category (full list at https://defillama.com/categories) *Please choose only one:

[Yield Aggregator](https://defillama.com/protocols/Yield%20Aggregator)

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):

No oracle.

In our current products, we focus on providing necessary and commonly used tools and vaults, such as LP token yield farming and leverage features. Additionally, to help our users reduce fees and minimize swap friction from multiple transactions, we utilize a DEX aggregator to help them find the best route to achieve the highest possible yields, no oralce is needed from front end side !

##### forkedFrom (Does your project originate from another project):

No

##### methodology (what is being counted as tvl, how is tvl being calculated):

Sum all token balances on the position that opens through Strater

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at : 
        
 
  > Please revert changes to package.json / package-lock.json

**Comment by danhsucowboy** [comment]
> Error while running adapter at :
> 
> > Please revert changes to package.json / package-lock.json

Is it possible that DeFiLlama could support "[decimal.js](https://mikemcl.github.io/decimal.js/#)" library?
Since it is getting more popular and many DeFi projects or their SDKs are using this library

**Comment by g1nt0ki** [comment]
hi @danhsucowboy, sorry but gonna insist on going the alternative route, using numbers directly instead of proper class like BigNumber, is hacky and bit lossy, but we (defillama) is operating a protocol, so bit of imprecision is fine in this case, also, computationally speaking, number is much faster/uses less resources compared to BigNumber.

I think your code is trying to do something similar to this right? https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/helper/unwrapLPs.js#L269

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
.

**Comment by llamatester** [comment]
The adapter at projects/strater exports TVL: 
        
 
 
    sui                       11.63 M
    
    total                    11.63 M

**Comment by danhsucowboy** [comment]
> hi @danhsucowboy, sorry but gonna insist on going the alternative route, using numbers directly instead of proper class like BigNumber, is hacky and bit lossy, but we (defillama) is operating a protocol, so bit of imprecision is fine in this case, also, computationally speaking, number is much faster/uses less resources compared to BigNumber.
> 
> I think your code is trying to do something similar to this right? https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/helper/unwrapLPs.js#L269

Understood, no problem. I just updated the code.

Also, thanks for your advice; we will think about it later. Before we make sure using number won't have accuracy issue, we would like to use bignumber instead

**Comment by danhsucowboy** [comment]
Hi, @g1nt0ki we've modified the code and need a review. Is it able to merge or not

**Comment by g1nt0ki** [comment]
@danhsucowboy thanks for the PR, I have refactored and merged it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/9156

**Pull request closed without merging**
