### PR TITLE
Add Thorstarter XRUNE

### PR DESCRIPTION
**Pull request by brddmnk**
##### Twitter Link:
https://twitter.com/thorstarter

##### List of audit links if any:
none

##### Website Link:
https://thorstarter.org/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://thorstarter.org/static/img/icons/rounded-xrune.svg

##### Current TVL:
8.16 M

##### Chain:
Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
thorstarter

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
thorstarter

##### Short Description (to be shown on DefiLlama):
Multichain IDO platform born on @THORChain governed by the Valhalla Venture DAO

##### Token address and ticker if any:
0x69fa0feE221AD11012BAb0FdB45d444D3D2Ce71c

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Staking

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
none

##### forkedFrom (Does your project originate from another project):
none

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL comes from the Staking Vaults and Launchpad Tiers

### CODE REVIEW

**Comment by brddmnk** [comment]
List of audit links if any:
https://github.com/HalbornSecurity/PublicReports/blob/master/Solidity%20Smart%20Contract%20Audits/Thorstarter_Smart_Contract_Security_Audit_Report_Halborn_v1_1.pdf

**Comment by waynebruce0x** [comment]
Can XRUNE staking be exported as 'staking' instead of TVL? Similar to the avalaunch adapter

**Comment by brddmnk** [comment]
pushed changes to the main branch according to your comment

**Comment by brddmnk** [comment]
@waynebruce0x

**Pull request merged**
