### PR TITLE
Add TVL for Gamma Strategies vaults on Zyberswap

### PR DESCRIPTION
**Pull request by l0c4t0r**
Gamma Strategies recently started managing LP positions on Zyberswap on arbitrum.  This change incorporates these into the TVL metrics.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/visor exports TVL: 
        
 
 
    ethereum-staking          4.98 M
    arbitrum                  5.07 M
    optimism                  214.63 k
    polygon                   29.14 M
    celo                      45.85493514631631
    ethereum                  3.18 M
    staking                   4.98 M
    
    total                    37.60 M

**Comment by g1nt0ki** [comment]
@l0c4t0r I will be honest, I was bit annoyed that you formatted the file and I have to review entire file instead of few lines.

But thanks for the update, is there some way to make everything rely on on chain data instead of graph? this way we have one less dependency.

**Comment by l0c4t0r** [comment]
Sorry about that - I just have a habit of running the auto formatter and didn't think much about it.

I think we can probably move everything on-chain. There are some bad addresses in the registry contract though so I will need check that we have the correct logic/validation to exclude these. Let me work on it

**Comment by llamatester** [comment]
The adapter at projects/visor exports TVL: 
        
 
 
    ethereum-staking          5.15 M
    celo                      47.38855632338868
    arbitrum                  5.14 M
    polygon                   30.79 M
    optimism                  223.00 k
    ethereum                  3.12 M
    staking                   5.15 M
    
    total                    39.27 M

**Comment by l0c4t0r** [comment]
@g1nt0ki I have refactored to remove all subgraph dependencies.

**Comment by g1nt0ki** [comment]
> @g1nt0ki I have refactored to remove all subgraph dependencies.

thanks again for the refactor

**Pull request merged**
