### PR TITLE
Modify export format

### PR DESCRIPTION
**Pull request by copyNdpaste**
##### Twitter Link:
https://twitter.com/Elysia_HQ

##### List of audit links if any:
defi v2 https://www.certik.com/projects/elysia
ELFI token https://github.com/elysia-dev/elyfi-token/tree/main/audit

##### Website Link:
https://www.elyfi.world/en

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
image

##### Current TVL:
$3730000

##### Chain:
Ethereum, BSC

##### Short Description (to be shown on DefiLlama):
ELYFI is the lending protocol that lends cryptocurrency using asset tokens minted in ELYSIA as collateral.

##### Token address and ticker if any:
0x2781246fe707bb15cee3e5ea354e2154a2877b16
ELYSIA

0x4dA34f8264CB33A5c9F17081B9EF5Ff6091116f4
ELFI

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Lending

##### methodology (what is being counted as tvl, how is tvl being calculated):
tvl : ether deposit + bsc deposit, staking : elfi staking, pool2 : lp with elfi, bsc tvl : deposit

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Error: TVL for key pool2 is not a number, instead it is NaN

**Comment by copyNdpaste** [comment]
@waynebruce0x Hello when i run `node test.js projects/elysia/index.js` on local terminal result was printed well. Why `Error: TVL for key pool2 is not a number, instead it is NaN` was happened on workflow?

image
image

**Comment by waynebruce0x** [comment]
what version of node are you using? It doesnt work for me locally either. What is the objective of this PR?

**Comment by copyNdpaste** [comment]
@waynebruce0x The old PR was merged, but tvl came out to zero due to export setting problems. Therefore, the goal is to modify the export.
v16.14.0
what is the version when github action is running?

**Comment by copyNdpaste** [comment]
i tried node v14.17.0 and worked. with debugger run and node test.js projects/elysia/index.js
image
---
image

**Comment by copyNdpaste** [comment]
I extracted data from subgraph and contracts. I just arranged addresses. Is it enough to using SDK? I dont know well that how to get data from subgraph by using SDK.

subgraph query and url are on apiInfo.json

```
ethereum staking
elfi contract : "0x4da34f8264cb33a5c9f17081b9ef5ff6091116f4"
elfyV1StakingPoolAddress = "0xb41bcd480fbd986331eeed516c52e447b50dacb4"
elfyV2StakingPoolAddress = "0xCD668B44C7Cf3B63722D5cE5F655De68dD8f2750"

elyfi-subgraph https://api.studio.thegraph.com/query/862/elyfi/v0.0.4
ethereum tvl
dai "0x6B175474E89094C44Da98b954EedeAC495271d0F"
usdt "0xdAC17F958D2ee523a2206206994597C13D831ec7"
el "0x2781246fe707bB15CeE3e5ea354e2154a2877B16"

pool2
uniswap-v3-subgraph "https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3"
ELFI of ELFI-DAI pool
DAI of ELFI-DAI pool
ELFI of ELFI-ETH pool
ETH of ELFI-ETH pool

bsc tvl
elyfi-subgraph-bsc "https://api.thegraph.com/subgraphs/name/donguks/elyfi-bsc"
```

**Comment by waynebruce0x** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters/blob/baf0684493bb9f4906af82f216cbe2d95d5514d9/projects/elysia/index.js

**Pull request closed without merging**
