### PR TITLE
add cmdx

### PR DESCRIPTION
**Pull request by cgsingh33**
##### Current TVL: 
---- tvl ----
Bonded Tokens             282.23 M 

Liquidity in Osmosis      26.90 M 

------ TVL ------

total                    309.14 M 

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list) 
comdex

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
14713

##### Short Description (to be shown on DefiLlama): 
Comdex is a decentralized synthetics protocol of the Cosmos ecosystem. Users of Comdex can create and trade a wide range of commodity synthetic assets. Comdex builds solutions to democratize finance by giving investors exposure to an extensive range of asset classes.

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Can you explain what this TVL is counting? I gather that there's a staking pool and an exchange? Can I see a breakdown of TVL on the dapp UI somewhere?

**Comment by cgsingh33** [comment]
@waynebruce0x  TVL is counting the value of total bonded tokens and Current total liquidity in Osmosis.
Metrics coming from https://info.osmosis.zone/token/CMDX and https://look.chillvalidation.com/comdex

**Comment by rajrohit10** [comment]
So TVL is only counted as $CMDX locked on other platform, right? If that's the case then we'll share osmosis pool cmdx token liquidity. That works,right?

**Comment by waynebruce0x** [comment]
TVL is the total value of assets deposited into your contracts. I understand Comdex has a synth exchange? Is there collateral deposited? That would count as TVL. We can't count market cap/price/supply of a token. 

but to me this: https://look.chillvalidation.com/comdex looks a bit like node validating. Maybe I've misunderstood. Feel free to  jump in our discord to discuss.

**Comment by cgsingh33** [comment]
Comdex synth exchange platform is not yet live. TVL is value of bonded tokens in the chain + liquidity in the pool of the token in all the exchanges is what we understood. 
So, if the bonded tokens are not counted, so only the liquidity in the pool will be considered right? As Comdex synth exchange is not up so, we can't show the collateral deposited.

**Comment by waynebruce0x** [comment]
Liquidity of the token on other exchanges will be counted as TVL for those exchanges instead. of CMDX. I think we may have to wait until the synth exchange is live before we list you. But we can help you get listed ASAP then

**Comment by rajrohit10** [comment]
Thanks a lot for clearing that up. That would be great. Let us know if
there’s anything else we need  to share with you.

**Pull request closed without merging**
