### PR TITLE
feat: bigpump

### PR DESCRIPTION
**Pull request by techbless1**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
BigPump

##### Twitter Link:
https://x.com/pocket_fi

##### Website Link:
https://t.me/pocketfi_bot/bigpump?startapp=tech_bless_3232

##### Logo (High resolution, will be shown with rounded borders):
PocketFi

##### Current TVL:
75604155201401

##### Chain:
Ton

##### Short Description (to be shown on DefiLlama):
Create memecoins in 30 seconds, trade, invite Frens, and make a Pump!

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dex

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is calculated on the backend by summing up all the balances of the bonding curves that have not gone to the DEX yet

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bigpump exports TVL: 
        
 
 
    ton                       463.95 k
    
    total                    463.95 k

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
hi @techbless1 thanks for the PR can you compute tvl on chain?

**Comment by techbless1** [comment]
@g1nt0ki thank you for review, fixed on my side, sorry for the inconvinience

**Comment by llamatester** [comment]
The adapter at projects/bigpump exports TVL: 
        
 
 
    ton                       12.96 k
    
    total                    12.96 k

**Pull request merged**
