### PR TITLE
added_usdc_plus_overnight

### PR DESCRIPTION
**Pull request by Kron1749**
Added USDC Plus on Base for Overnight

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/overnight-usdcPlus exports TVL: 
        
 
 
    base                      5.37 M
    
    total                    5.37 M

**Comment by Kron1749** [comment]
> The adapter at projects/overnight-usdcPlus exports TVL:
> 
> ```
> base                      5.37 M
> 
> total                    5.37 M 
> ```

That's good,thank you

**Comment by g1nt0ki** [comment]
@Kron1749 thnaks for the PR, I noticed that we already have a listing for USDC, so updated it: https://github.com/DefiLlama/DefiLlama-Adapters/commit/15c99b5588e4b2c6b4707357df8b36d991e0b253

**Comment by Kron1749** [comment]
> @Kron1749 thnaks for the PR, I noticed that we already have a listing for USDC, so updated it: [15c99b5](https://github.com/DefiLlama/DefiLlama-Adapters/commit/15c99b5588e4b2c6b4707357df8b36d991e0b253)

You don't have a USDC Plus,you only have USD Plus,so the USDC Plus is a new token

here i am trying to list USDC Plus https://github.com/DefiLlama/defillama-server/pull/6148

**Comment by Define101** [comment]
@Kron1749 its already being tracked here https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/overnight-usdPlus/index.js#L9

**Comment by Kron1749** [comment]
> @Kron1749 thnaks for the PR, I noticed that we already have a listing for USDC, so updated it: [15c99b5](https://github.com/DefiLlama/DefiLlama-Adapters/commit/15c99b5588e4b2c6b4707357df8b36d991e0b253)

Yeah,it is,and TVL updated, thank you
But the problem is that USDC should be in here https://defillama.com/protocol/overnight-finance
But there is no USDC+ token

**Comment by Kron1749** [comment]
> @Kron1749 whats the difference between USDC+ and USD+ ?

That's 2 our different tokens like USDT+ and DAI+
the main difference in the address
I see that you tracked the correct tvl for USDC+

But it should be displayed in here https://defillama.com/protocol/overnight-finance near "Overnight USD+" and other Overnight tokens

I made a PR to add this token in here https://github.com/DefiLlama/defillama-server/pull/6148
but @Define101 said that it's already tracked

**Comment by g1nt0ki** [comment]
hi @Kron1749 imo, it was a mistake to have sublisting for each of this, we are not doing it for other protocols, say, for yearn, both yDAI and yETH are tracked in the same listing.

**Comment by Kron1749** [comment]
> hi @Kron1749 imo, it was a mistake to have sublisting for each of this, we are not doing it for other protocols, say, for yearn, both yDAI and yETH are tracked in the same listing.

So,there is no way to add USDC+ as different token, like these tokens
image

**Pull request closed without merging**
