### PR TITLE
🔓 Lockless Protocol : New TVL Adapter

### PR DESCRIPTION
**Pull request by ftm1337**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Lockless Protocol

##### Twitter Link:
https://twitter.com/ftm1337

##### List of audit links if any:
none

##### Website Link:
https://eliteness.network/lockless

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://eliteness.network/lockless/img/lockless.svg

##### Current TVL:
~1000 (on Kava Chain)

##### Chain:
Kava, Echelon

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
no native token, so no coingecko

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
no native token, so no cmc

##### Short Description (to be shown on DefiLlama):
Lockless Protocol provides Liquid Staking services for Assets that have medium to long-term lockup period via its SW-Tokens, unlocking the potential of such locked assets by leveraging DeFi opportunites to earn a yield without compromising on the opportunity cost of locking the asset.

##### Token address and ticker if any:
no native token

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Liquid Staking

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
none

##### forkedFrom (Does your project originate from another project):
original

##### methodology (what is being counted as tvl, how is tvl being calculated):
Any and each 1 SW-Token can only ever be minted by permanent locking of 1 Native token. Hence, the totalSupply() method is used to aggregate the amounts of underlying assets, with their respective prices fed by the DefiLlama SDK.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/Lockless exports TVL: 
        
 
 
    kava                      910.91175
    echelon                   0
    
    total                    910.91175

**Comment by g1nt0ki** [comment]
@ftm1337 not sure if we can list it if there is no way for users to unwrap SWKAVA

**Comment by llamatester** [comment]
The adapter at projects/Lockless exports TVL: 
        
 
 
    kava                      910.9894499999999
    echelon                   0
    
    total                    910.9894499999999

**Comment by ftm1337** [comment]
hi @g1nt0ki , there will be a stablepool for SWKAVA , and all staking rewards (KAVA) are paid to the LP of this pool, and not to the SWKAVA holders.. so SWKAVA would essetially be it's own exit liquidity .. and as it finds more uses elsewhere, the staking crowd will reduce and give more KAVA to the remainin ones..
its a bit of a different model than the regular liquid-staking models, but i think the reduced APR (since we need 2x more to earn the same, as LP is needed) is a good trade-off for actual Liquidity which is 2x the marketcap of issued SWtokens (imagine steth, but with a $18.5 Billion Liquidity (2x of its supply mktcap) to exit positions anytime!).
upto you how you would like to categorize it, but i see it to be similar to tenderize, but on steroids (50% vs 100% to LPs).. so i think its a good fit for liquid staking..

**Pull request merged**
