### PR TITLE
ASTRA DAO TVL

### PR DESCRIPTION
**Pull request by ayush-tm**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Treasury Addresses (if the protocol has treasury): Timelock contract DAO managed -  0xc80B0a04D51f3fd4C91e9D28525709261936Bed1
Vesting contract -  0xaA2Da8F75A6F7C37dd2A3EdcCBF7897759C9C119

##### methodology (what is being counted as tvl, how is tvl being calculated):  To calculate the TVL, we have used the following metrics:
1) Amount invested in the Indexes on the platform => All holdings of indices contract (https://etherscan.io/address/0x17b9B197E422820b3e28629a2BB101949EE7D12B). 
2) Amount of astra staked on the platform in the form of ASTRA or LP tokens of ASTRA/WETH => Total ASTRA staked in the staking contract (https://etherscan.io/address/0xDFE672C671943411fc16197fb8E328662B57CE2C).
3) WETH staked on the platform as part of ASTRA/WETH LP tokens => Fetched all LM positions staked on the platform, used Uniswap V3 Subgraph (https://thegraph.com/hosted-service/subgraph/uniswap/uniswap-v3)  to fetch WETH amount.

Steps to test the script to calculate TVL:
1) run npm install
2) Add Moralis API_KEY  in the script
3) Test using node test.js projects/astra-dao/index.js

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/astra-dao: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by llamatester** [comment]
Error while running adapter at projects/astra-dao: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by g1nt0ki** [comment]
@ayush-tm thanks for the PR, but your code is using multiple npm libs that we dont have/support, so I refactored it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/6313

Also split pool2 and staking from tvl: https://docs.llama.fi/list-your-project/what-to-include-as-tvl


if you are fine with the changes I will merge it.

**Comment by g1nt0ki** [comment]
okay, merged this instead: https://github.com/DefiLlama/DefiLlama-Adapters/pull/6313

**Pull request closed without merging**
