### PR TITLE
feat: Add Hatom Protocol

### PR DESCRIPTION
**Pull request by amilcarrey**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/hatom exports TVL: 
        
 
 
    elrond                    19.01 M
    
    total                    19.01 M

**Comment by llamatester** [comment]
The adapter at projects/hatom exports TVL: 
        
 
 
    elrond                    19.01 M
    
    total                    19.01 M

**Comment by g1nt0ki** [comment]
hi @amilcarrey 

Thanks for the PR, we like graph but like on chain data even more, is there any way to query this info on chain?

Also, would like to split this into two listings, one adapter/listing for liquid staking and another for lending: and the tvl there split between available liquidity under 'tvl' key and borrowed amount under 'borrowed' key. Let me know if you have any doubts

**Comment by amilcarrey** [comment]
Hi @g1nt0ki 

Thanks for answer the PR. Yes, woudn't be a problem consume the info onchain and split it in two diferent listings. Additionally, could you please confirm if I can use GraphQL to fetch the prices of the money markets?

**Comment by g1nt0ki** [comment]
> Hi @g1nt0ki
> 
> Thanks for answer the PR. Yes, woudn't be a problem consume the info onchain and split it in two diferent listings. Additionally, could you please confirm if I can use GraphQL to fetch the prices of the money markets?

yeah, graphQL is good.

**Comment by amilcarrey** [comment]
> Also, would like to split this into two listings, one adapter/listing for liquid staking and another for lending: and the tvl there split between **available liquidity under 'tvl' key** and borrowed amount under 'borrowed' key. Let me know if you have any doubts

@g1nt0ki I have two questions. 

1. Can I use multiversX sdk? I mean install that dependecy. 
2. Regarding the lending adapter. By definition TVL is the sum of cash and borrows. With available liquidity, are you mean that under tvl we must exclude borrows? That woudn't affect the value shown in the frontend?

**Comment by g1nt0ki** [comment]
> > Also, would like to split this into two listings, one adapter/listing for liquid staking and another for lending: and the tvl there split between **available liquidity under 'tvl' key** and borrowed amount under 'borrowed' key. Let me know if you have any doubts
> 
> @g1nt0ki I have two questions.
> 
>     1. Can I use multiversX sdk? I mean install that dependecy.
> 
>     2. Regarding the lending adapter. By definition TVL is the sum of cash and borrows. With available liquidity, are you mean that under tvl we must exclude borrows? That woudn't affect the value shown in the frontend?

yeah, you can install the dependency for sdk, but dont include the updated package.json/lock file. I have a work around server side (dont worry about failing github action for the PR)

we keep a toggle that lets users choose whether to include borrowed amount in overall tvl: 
image

example listing: https://defillama.com/protocol/compound-v3

**Comment by llamatester** [comment]
Error while running adapter at projects/hatom-lending: 
        
 
  
    
    
    TypeError: array.reduce is not a function
    Truncated error stack:
    
        at sumatory (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/hatom/utils.js:4:10)
        at tlv (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/hatom-lending/index.js:56:28)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)
        at async Promise.all (index 2)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by amilcarrey** [comment]
**Liquid staking:**
image


**Lending:**
image

**Comment by llamatester** [comment]
Error while running adapter at projects/hatom-lending: 
        
 
  
    
    
    TypeError: Cannot read properties of null (reading 'values')
    Truncated error stack:
    
        at getMoneyMarketCash (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/hatom/on-chain/index.js:12:32)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/hatom-lending/index.js:17:20
        at async Promise.all (index 0)
        at async tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/hatom-lending/index.js:53:28)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9

**Comment by llamatester** [comment]
The adapter at projects/hatom-lending exports TVL: 
        
 
 
    elrond-borrowed           8.35 M
    elrond                    40.76 M
    borrowed                  8.35 M
    
    total                    40.76 M

**Comment by llamatester** [comment]
The adapter at projects/hatom-liquid-staking exports TVL: 
        
 
 
    elrond                    39.42 M
    
    total                    39.42 M

**Comment by llamatester** [comment]
Error while running adapter at projects/treasury/hatom.js: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by llamatester** [comment]
The adapter at projects/hatom-lending exports TVL: 
        
 
 
    elrond-borrowed           8.35 M
    elrond                    40.71 M
    borrowed                  8.35 M
    
    total                    40.71 M

**Comment by llamatester** [comment]
The adapter at projects/hatom-liquid-staking exports TVL: 
        
 
 
    elrond                    39.38 M
    
    total                    39.38 M

**Comment by llamatester** [comment]
The adapter at projects/hatom-lending exports TVL: 
        
 
 
    elrond-borrowed           9.79 M
    elrond                    41.13 M
    borrowed                  9.79 M
    
    total                    41.13 M

**Comment by llamatester** [comment]
The adapter at projects/hatom-liquid-staking exports TVL: 
        
 
 
    elrond                    39.30 M
    
    total                    39.30 M

**Comment by g1nt0ki** [comment]
hi @amilcarrey I am sorry, I butchered your code, reasons for my changes: 

  - I have been working on adding price support for EGLD tokens with sufficient liquidity to our pricing api, so I removed reliance on your price graph (even though I asked you to go ahead with it earlier, again sorry about this) My thinking here is, now users can see token breakdown of tvl, also see token infows/outflows over time. Also, makes sense from maintainance point, all multiversx adapters are using same price api now, code server side: https://github.com/DefiLlama/defillama-server/blob/master/coins/src/adapters/markets/xexchange.ts

  - Removed dependency on multiversx sdk, I try to keep the code as slim as possible, so I write some unholy code/chain adapter (copied from chain's sdk) to match our own sdk methods, I should have been proactive and done this before you started your work, forgive me. 

You have put in time, understood our codebase and wrote good code, I feel terrible removing it.

**Comment by amilcarrey** [comment]
No problem @g1nt0ki and thanks for now add support to multiversx. 

I have a question regarding how the protocol is shown on the platform. I want to have a tab like morpho, one with a summary  (TVL as a sum of the TVL of this two adapters)  and links to our app, and also two other tabs with the adapters created in this PR. 

image

Can you help me with that? I'm checking [morpho's ](https://defillama.com/protocol/morpho) and [benqi's](https://defillama.com/protocol/morpho) code but they have just the adapters.

**Comment by g1nt0ki** [comment]
hi @amilcarrey yeah, new entry needs to be added here: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/parentProtocols.ts

I have asked another llama to do it asap

**Comment by amilcarrey** [comment]
Thanks @g1nt0ki, you rock!

**Pull request merged**
