### PR TITLE
New kaddex module + Staked KDX

### PR DESCRIPTION
**Pull request by ants88**
- kswap module replaced by new kaddex module
- Staked KDX added to total TVL
- New pools integration

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/kaddex exports TVL: 
        
 
 
    kadena                    295.17 k
    
    total                    295.17 k

**Comment by llamatester** [comment]
The adapter at projects/kaddex exports TVL: 
        
 
 
    kadena                    5.09 M
    
    total                    5.09 M

**Comment by llamatester** [comment]
The adapter at projects/kaddex exports TVL: 
        
 
 
    kadena                    1.07 M
    kadena-staking            0
    staking                   0
    
    total                    1.07 M

**Comment by realdealshaman** [comment]
I see that the pr still needs a bit of adjusting. I'm chatting with KDX | Adrian Cardoso#1695 on discord, I will merge and update to reflect the correct staking tvl

**Pull request merged**
