### PR TITLE
Added KLEX as a DefiLLama Adapter

### PR DESCRIPTION
**Pull request by 0xinsanity**
##### Name (to be shown on DefiLlama):
KLEX Finance

##### Twitter Link:
https://twitter.com/klexfinance

##### List of audit links if any:
https://github.com/balancer-labs/balancer-v2-monorepo/tree/master/audits

##### Website Link:
https://klex.finance

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://raw.githubusercontent.com/Klaytn-Defi/assets/master/cypress/klex/icon-dark.svg
https://raw.githubusercontent.com/Klaytn-Defi/assets/master/cypress/klex/icon-white.svg

##### Current TVL:
32.51 M

##### Chain:
Klaytn

##### Short Description (to be shown on DefiLlama):
KLEX is a protocol for programmable liquidity.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### forkedFrom (Does your project originate from another project):
https://github.com/balancer-labs/balancer-v2-monorepo

##### methodology (what is being counted as tvl, how is tvl being calculated):
All StablePhantom, Stable, Weighted, and Lienar pool TVL is added together.

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hi @0xinsanity , thanks for the PR and adding an onchain calls file. Can we add the code in the onchain.js file to the code in the index.js? This way we only have one file for the project and we can export the tvl per chain Arbitrum and Klaytn if it has tvl in both

**Comment by 0xinsanity** [comment]
@realdealshaman how does this look now? Also, it just supports Klaytn, not Arbitrum!

**Comment by g1nt0ki** [comment]
@0xinsanity can you revert the deletion of package-lock.json

**Comment by 0xinsanity** [comment]
@g1nt0ki copied it back from main!

**Comment by llamatester** [comment]
The adapter at projects/klex exports TVL: 
        
 
 
    klaytn                    33.12 M
    
    total                    33.12 M

**Comment by g1nt0ki** [comment]
@0xinsanity I changed the code to fetch tvl by counting the tokens in vault, but getting only 18M can you have a look at this? https://github.com/DefiLlama/DefiLlama-Adapters/pull/3771

Am I doing something wrong?

**Pull request merged**
