### PR TITLE
add Hatom WTAO Bridge SDK Adapter

### PR DESCRIPTION
**Pull request by carlosalv098**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/hatom-tao-bridge: 
        
 
  
    
    
    ReferenceError: api is not defined
    Truncated error stack:
    
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/hatom-tao-bridge/index.js:13:5)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:49:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:138:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:181:3

**Comment by llamatester** [comment]
The adapter at projects/hatom-tao-bridge exports TVL: 
        
 
 
    elrond                    81.05 k
    
    total                    81.05 k

**Comment by carlosalv098** [comment]
I have added an adapter to the hatom-protocol project. This is a module called Hatom TAO Bridge . This product allows users to bridge their TAO from Bittensor to MultiversX blockchain.

This is our current project here:
https://defillama.com/protocol/hatom-protocol

**Comment by carlosalv098** [comment]
Once this is merged, will it automatically be included in Hatom’s main dashboard?

**Comment by g1nt0ki** [comment]
@carlosalv098 thanks for the PR, can you update it so we count the bridged token tvl on the source chain? yeah, it will be added a new sub protocol on hatom with category as bridge

**Comment by carlosalv098** [comment]
@g1nt0ki Thank you for your feedback. I’d like to point out that the bridge balance on Bittensor represents merely the balance of a single account, whereas the bridge balance on MultiversX reflects the supply of a wrapped token. Wouldn’t you agree that the value represented on the MultiversX side is more indicative of the total value locked (TVL) associated with our protocol?

**Comment by g1nt0ki** [comment]
the reason we have this is, some bridges mint more on the dest than what is locked on the source, also, counting on the source means, users can verify the tvl, and we want to keep the same rule for everyone so bridges dont complain that we are discriminating.

Also, this tvl will be excluded from both source and  dest chain tvl (this applies to all bridges)

**Comment by llamatester** [comment]
Error while running adapter at projects/hatom-tao-bridge: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'balanceTotal')
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/hatom-tao-bridge/index.js:57:56
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:49:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:138:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:181:3

**Comment by llamatester** [comment]
The adapter at projects/hatom-tao-bridge exports TVL: 
        
 
 
    bittensor                 10.63 M
    
    total                    10.63 M

**Comment by carlosalv098** [comment]
thanks! @g1nt0ki

**Pull request merged**
