### PR TITLE
Add swap TVL

### PR DESCRIPTION
**Pull request by Bit-Genie**
Add swap TVL

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bitgenie exports TVL: 
        
 
 
    merlin                    1.63 M
    
    total                    1.63 M

**Comment by g1nt0ki** [comment]
hi @Bit-Genie 
I think it is better to show the dex as a sub listing, so added it here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/0391ece151ca42825b42bc4fb50300415fd63978

**Comment by Bit-Genie** [comment]
> hi @Bit-Genie I think it is better to show the dex as a sub listing, so added it here: [0391ece](https://github.com/DefiLlama/DefiLlama-Adapters/commit/0391ece151ca42825b42bc4fb50300415fd63978)

thank you sir
So will this swap TVL be displayed on this page?
https://defillama.com/protocol/bitgenie?usdInflows=true&twitter=true&tvl=false#information

**Comment by g1nt0ki** [comment]
yeah, we will create a parent protocol, something like https://defillama.com/protocol/inception#information which will display both the farm and dex

**Comment by Bit-Genie** [comment]
> yeah, we will create a parent protocol, something like https://defillama.com/protocol/inception#information which will display both the farm and dex

alright, thank you very much!

**Pull request closed without merging**
