### PR TITLE
Adding New Farm TVL

### PR DESCRIPTION
**Pull request by defininja**
Adding our new farm TVL

New Farm address -  https://bscscan.com/address/0x405960AEAad7Ec8B419DEdb511dfe9D112dFc22d

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/planet-finance exports TVL: 
        
 
 
    bsc-staking               4.059520220935675
    bsc                       3.04 M
    staking                   4.059520220935675
    
    total                    3.04 M

**Comment by llamatester** [comment]
The adapter at projects/planet-green exports TVL: 
        
 
 
    bsc-borrowed              1.53 M
    bsc                       4.39 M
    borrowed                  1.53 M
    
    total                    4.39 M

**Comment by g1nt0ki** [comment]
@defininja thanks for the PR

**Comment by llamatester** [comment]
The adapter at projects/planet-finance exports TVL: 
        
 
 
    bsc-staking               4.109949005128529
    bsc                       3.07 M
    staking                   4.109949005128529
    
    total                    3.07 M

**Comment by llamatester** [comment]
The adapter at projects/planet-green exports TVL: 
        
 
 
    bsc-borrowed              1.54 M
    bsc                       4.44 M
    borrowed                  1.54 M
    
    total                    4.44 M

**Pull request merged**
