### PR TITLE
Stargaze Adapter

### PR DESCRIPTION
**Pull request by effofxprime**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Stargaze

##### Twitter Link:
https://twitter.com/StargazeZone

##### Website Link:
https://www.stargaze.zone

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
light
https://s2.coinmarketcap.com/static/img/coins/200x200/16842.png

dark
https://img.api.cryptorank.io/coins/stargaze1642419194380.png

##### Current TVL:
799,752,138.424651

##### Chain:
Stargaze

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
stargaze

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
stargaze

##### Short Description (to be shown on DefiLlama):
A decentralized, community-owned app chain for NFTs. 100% carbon neutral. ZERO gas. Powered by CosmWasm and $STARS.

##### Token address and ticker if any:
STARS

##### Category (full list at https://defillama.com/categories) *Please choose only one:
25: NFT Marketplace

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
NA

##### forkedFrom (Does your project originate from another project):
NA

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is calculated by summing 4 different items:
querying the total amount staked on chain.
Then querying all STARS pools on the Omosis Dex and checking their bonded amount.
Summing all bonded amounts with the staking amount on chain is the total sum for TVL.

### CODE REVIEW

**Comment by dthevat** [comment]
> **NOTE**
> 
> 1. The protocol is usually listed within 24 hours of merging the PR
> 2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
> 3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
> 4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
> 5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap
> 
> ##### Name (to be shown on DefiLlama):
> Stargaze
> 
> ##### Twitter Link:
> https://twitter.com/StargazeZone
> 
> ##### List of audit links if any:
> ##### Website Link:
> https://www.stargaze.zone
> 
> ##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
> light https://s2.coinmarketcap.com/static/img/coins/200x200/16842.png
> 
> dark https://img.api.cryptorank.io/coins/stargaze1642419194380.png
> 
> ##### Current TVL:
> ##### Chain:
> Stargaze
> 
> ##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
> stargaze
> 
> ##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
> stargaze
> 
> ##### Short Description (to be shown on DefiLlama): A decentralized, community-owned app chain for NFTs. 100% carbon neutral. ZERO gas. Powered by CosmWasm and $STARS.
> ##### Token address and ticker if any:
> ##### Category (full list at https://defillama.com/categories) *Please choose only one: NFT Marketplace
> ##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
> ##### forkedFrom (Does your project originate from another project):
> ##### methodology (what is being counted as tvl, how is tvl being calculated):

**Comment by llamatester** [comment]
Error while running adapter at projects/stargaze: 
        
 
  
    
    
    TypeError: parseFloat(...).div is not a function
    Truncated error stack:
    
        at fetch (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/stargaze/index.js:14:71)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:75:7)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:212:3

**Comment by g1nt0ki** [comment]
@effofxprime There are some issues with what you are counting under tvl, If the caregory is NFT marketplace, I would count the tokens locked in marketplace  contract for Nft offers/pools (this is what we do for sudoswap), not sure why you are tokens staked in chain and on dexes

**Comment by effofxprime** [comment]
> @effofxprime There are some issues with what you are counting under tvl, If the caregory is NFT marketplace, I would count the tokens locked in marketplace contract for Nft offers/pools (this is what we do for sudoswap), not sure why you are tokens staked in chain and on dexes

Stargaze NFT Market place is unique and different from others.  NFT's aren't staked nor are coins locked in any NFT buying process.
Stargaze is a Cosmos based blockchain and is dPOS.  The onchain stake+all pool stake is what the team wants to account for in TVL.  Is it not appropriate for them to be listed in this category then?
I am also speaking on their behalf after communicating back and forth with them about the listing, I could have a member of the team comment on this as well if you find that to be best?

**Comment by dthevat** [comment]
> @effofxprime There are some issues with what you are counting under tvl, If the caregory is NFT marketplace, I would count the tokens locked in marketplace contract for Nft offers/pools (this is what we do for sudoswap), not sure why you are tokens staked in chain and on dexes

Stargaze team member (@dthevat, BD & Data). Stargaze is quite unique and not the traditional ‘NFT Marketplace’ category being the “_the 1st interoperable layer 1 for NFTs_”. @g1nt0ki-What category do you suggest if we do not fit in the 'NFT Marketplace' classification? Are we able to use custom calculations for the final total TVL AND also be classified as a ‘NFT Marketplace’?

@effofxprime is currently calculating the TVL count:
_- I query the on chain bonded amount.
- Then I query all 3 pools on Osmosis dex for how much STARS is currently in the pool.
- I sum all 4 of these together for a final total TVL._


Thanks and feel free to ping me in Telegram via _@suiradt_ if you have any questions and/or concerns.

**Comment by g1nt0ki** [comment]
@effofxprime @dthevat 
 - tokens in Osmosis pools count towards their dex tvl, not yours
 - maybe there is some misunderstanding, but tvl/listing is for projects on chain, not the chain itself, so we are not counting the tokens bonded to it

**Comment by dthevat** [comment]
@g1nt0ki thank you for the update. @effofxprime --> looks as though we cannot bring in the STARS within the Osmosis pools count into our tvl. Are you able to update your calculation? Thanks.

**Comment by effofxprime** [comment]
@g1nt0ki @dthevat 
I have updated the adapter in compliance with everything that has been discussed about how I was calculating the TVL prior.
This currently is the on-chain bonded amount.

**Comment by g1nt0ki** [comment]
@effofxprime sorry, but we do not consider on-chain bonded tokens/staking as protocol tvl.

**Comment by dthevat** [comment]
@g1nt0ki is there any other items you need from the Stargaze team to publish the data on DeFiLlama? Thanks.

**Comment by g1nt0ki** [comment]
hi @dthevat,the issue is, I am not sure what can be counted as tvl, bonded tokens definitely dont classify as tvl.

**Comment by g1nt0ki** [comment]
hmmm, we dont support nft marketplaces/have trouble supporting because we dont know how to value the nfts, there are some NFT lending applications in Ethereum that use price from oracle,  closest example I can think of sudoswap where we count the amount of ethereum locked in pools

**Comment by dthevat** [comment]
Interesting, thank you for the feedback. What is your recommendation for calculating TVL for Stargaze?

**Comment by g1nt0ki** [comment]
> Interesting, thank you for the feedback. What is your recommendation for calculating TVL for Stargaze?

is there stargate locked in offer pools of nfts?

**Comment by g1nt0ki** [comment]
@effofxprime @dthevat is there some way to track fees/revenue? thinking if we can list stargaze with 0 tvl but track those fields like opensea: https://defillama.com/protocol/opensea

**Pull request closed without merging**
