### PR TITLE
update Plunderswap Univ3 Factory

### PR DESCRIPTION
**Pull request by darthgus**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR

Reason/Details - adding uniswapv3factory.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/plunderswap: 
        
 
  
    
    
    Error: 
        Unknown chain(s): 0, 1, 2, 3, 4, 5, 6
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file
        
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'

**Comment by llamatester** [comment]
The adapter at projects/plunderswap exports TVL: 
        
 
 
    zilliqa                   0
    
    total                    0

**Comment by darthgus** [comment]
ok i know I have to combine these, and when i do I get the v2 tvl.  but v3 tvl always shows 0 - how can i diagnose the issue? they are straight uniswap v3 contracts.  chain issue?  Any help would be appriciated.

**Comment by darthgus** [comment]
ill rewrite

**Pull request closed without merging**
