### PR TITLE
adding OFTs and hypeERC20s to swellchain TVL

### PR DESCRIPTION
**Pull request by darvinrio**
Since close to 96% of the TVL comes from LayerZero and HyperLane bridged tokens, I'm adding the supply of these tokens as part of TVL. 

image

this may lead to double counting while aggregating protocol TVL.

### CODE REVIEW

**Comment by llamabutler** [comment]
The adapter at projects/swellchain exports TVL: 
        
 
 
    swellchain                202.03 M
    ethereum                  8.10 M
    
    total                    210.13 M

**Comment by g1nt0ki** [comment]
sorry, no. we track only the canonical bridge tvl here.

**Comment by darvinrio** [comment]
@g1nt0ki thanks for the review.
does it make sense to list this TVL as part of LayerZero Protocol on swellchain ?

**Comment by g1nt0ki** [comment]
@darvinrio even if we update layerzero, we can only count the tokens locked on sonic under sonic tvl of layerzero. 

For bridges, we count tokens on the source chain, and bridge tvl is excluded from chain tvl

**Pull request closed without merging**
