### PR TITLE
add support for linea, polygon, polygonzkEVM

### PR DESCRIPTION
**Pull request by anassohail99**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/a51-finance-v3 exports TVL: 
        
 
 
    polygon-staking           64.05 k
    staking                   64.05 k
    optimism                  3.38 k
    arbitrum                  2.38 k
    base                      2.25 k
    blast                     1.03 k
    manta                     173
    polygon_zkevm             18
    polygon                   18
    bsc                       13
    linea                     9
    scroll                    9
    
    total                    9.29 k

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
hi, can you please revert the formatting changes so it is easier for me to review

**Comment by anassohail99** [comment]
Which formatting changes? the changes by prettier?

**Comment by llamatester** [comment]
The adapter at projects/a51-finance-v3 exports TVL: 
        
 
 
    polygon-staking           64.60 k
    staking                   64.60 k
    optimism                  3.38 k
    arbitrum                  2.39 k
    base                      2.17 k
    blast                     1.04 k
    manta                     173
    polygon_zkevm             18
    polygon                   18
    bsc                       13
    linea                     9
    scroll                    9
    
    total                    9.22 k

**Pull request closed without merging**
