### PR TITLE
Fixed script for nachoxyz.com

### PR DESCRIPTION
**Pull request by bobafettirl**
This fixes a previous script for nachoxyz.com which is brokern

##### Website Link:
nachoxyz.com

##### Current TVL:
$20m

##### Chain:
polygon

##### methodology (what is being counted as tvl, how is tvl being calculated):

The TVL of Nacho Finance is calculated using the Quickswap LP token deposits(NACHO/ETH and NSHARE/MATIC), and the NSHSARE deposits found in the Bowl contract.

### CODE REVIEW

**Comment by bobafettirl** [comment]
Note, this is a tomb fork, i have copied the same code TOMB is using

```
➜ node test.js projects/nacho-finance/index.js 
--- tvl ---
NSHARE                    11.25 M
NACHO                     3.07 M
WETH                      2.91 M
WMATIC                    2.36 M
Total: 19.59 M 

--- polygon ---
NSHARE                    11.25 M
NACHO                     3.07 M
WETH                      2.91 M
WMATIC                    2.36 M
Total: 19.59 M 

------ TVL ------
polygon                   19.59 M

total                    19.59 M 
```

**Comment by waynebruce0x** [comment]
This was a mistake on the tomb adapter, which we have now updated accordingly

**Comment by bobafettirl** [comment]
@waynebruce0x ok, ive updated again to match the latest tomb changes

Is it correct that the total shows as zero?  Seems to be the same for tomb.

```
➜ node test.js projects/nacho-finance/index.js 
--- polygon ---
Total: 0 

--- polygon-staking ---
NSHARE                    7.31 M
Total: 7.31 M 

--- polygon-pool2 ---
NACHO                     2.96 M
WETH                      2.94 M
NSHARE                    1.89 M
WMATIC                    1.88 M
Total: 9.67 M 

--- tvl ---
Total: 0 

--- staking ---
NSHARE                    7.31 M
Total: 7.31 M 

--- pool2 ---
NACHO                     2.96 M
WETH                      2.94 M
NSHARE                    1.89 M
WMATIC                    1.88 M
Total: 9.67 M 

------ TVL ------
polygon                   0
polygon-staking           7.31 M
polygon-pool2             9.67 M
staking                   7.31 M
pool2                     9.67 M

total                    0 
```

**Comment by waynebruce0x** [comment]
yeah this is correct. We're in discussion about having pool2 and staking included in tvl as default.

**Pull request merged**
