### PR TITLE
Add cybro integration for DefiLlama TVL (#1)

### PR DESCRIPTION
**Pull request by cymux**
* feat: add cybro

* style: refactoring

* feat: add new vaults

* feat: set methodology

---------

**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/cybro exports TVL: 
        
 
 
    blast                     23.03 k
    
    total                    23.03 k

**Comment by cymux** [comment]
Name (to be shown on DefiLlama): Cybro

Twitter Link: https://x.com/Cybro_io

List of audit links if any: https://github.com/cybro-io/dapp-contracts-audits

Website Link: https://app.cybro.io/

Logo (High resolution, will be shown with rounded borders): https://cybro.io/cybro.png

Current TVL: $23k

Treasury Addresses (if the protocol has treasury): -

Chain: Blast

Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): cybro

Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): cybro

Short Description (to be shown on DefiLlama):
CYBRO is an AI-based yield aggregator platform on the Blast blockchain

Token address and ticker if any:
0x963eec23618BbC8e1766661d5f263f18094Ae4d5, CYBRO

Category (full list at https://defillama.com/categories) *Please choose only one:
13 Yield Aggregator

Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.): -

Implementation Details: Briefly describe how the oracle is integrated into your project: -

Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage: -

forkedFrom (Does your project originate from another project): -

methodology (what is being counted as tvl, how is tvl being calculated):
We calculate TVL based on the Total Supply of our proxy contracts through which users interact with vault's contracts

Github org/user (Optional, if your code is open source, we can track activity):

**Comment by llamatester** [comment]
The adapter at projects/cybro exports TVL: 
        
 
 
    blast                     23.32 k
    
    total                    23.32 k

**Comment by g1nt0ki** [comment]
@cymux thanks for the PR

**Pull request merged**
