### PR TITLE
add fortress adapter

### PR DESCRIPTION
**Pull request by morazzela**
##### Twitter Link:
https://twitter.com/FortressDAO

##### Website Link:
https://app.fortressdao.finance/

##### Current TVL:
$17,598,585

##### Chain:
Avalanche

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
fortressdao

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
14861

##### Short Description (to be shown on DefiLlama):
An adventure in treasure management on Avalanche

##### Token address and ticker if any:
0xf6d46849db378ae01d93732585bec2c4480d1fd5 (FORT)

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Staking

##### forkedFrom (Does your project originate from another project):
OHM

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL = Treasury Market Value, STAKING = sFORT circulating supply times FORT market price

### CODE REVIEW

**Comment by waynebruce0x** [comment]
For other OHM forks we seperate staking and tvl into seperate exports. Is it possible to do that here? Also we prefer on-chain adapters where possible.

**Comment by morazzela** [comment]
Just separated the tvl and staking parts

**Comment by morazzela** [comment]
Is it possible to integrate the "TheGraph" implementation ?

**Comment by realdealshaman** [comment]
Hey, I tested the adapter and it is returning a value of 0 for the tvl and for staking

**Comment by 0xngmi** [comment]
wrote an adapter for it on 92c3f71

**Comment by morazzela** [comment]
> wrote an adapter for it on [92c3f71](https://github.com/DefiLlama/DefiLlama-Adapters/commit/92c3f7102ec8e29b43c7b6cad4ab1a2a7d675583)

Damn sorry, didn't know it included ohm helper

**Pull request closed without merging**
