### PR TITLE
Add arUSD

### PR DESCRIPTION
**Pull request by 0xAndrewClark**
Twitter Link:
https://twitter.com/protocol_fx

List of audit links if any:
https://github.com/AladdinDAO/aladdin-v3-contracts/blob/main/audit-reports/SECBIT_Concentrator_arUSD_Report_v1.0_20240618.pdf

Website Link:
https://fx.aladdin.club/

Current TVL:
$1,566,661.87

Chain:
ETH

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/arUSD exports TVL: 
        
 
 
    ethereum                  1.57 M
    
    total                    1.57 M

**Comment by g1nt0ki** [comment]
is is wrapped version of rUSD whose backing we are already counting as part of fx protocol tvl?

**Comment by 0xAndrewClark** [comment]
> 这是 rUSD 的包装版本，我们已经将其支持算作 fx 协议 tvl 的一部分了？

arUSD is the tokenized version of rUSD EtherFi Stability Pool vaults from Convex Finance.

> is is wrapped version of rUSD whose backing we are already counting as part of fx protocol tvl?

arUSD is the tokenized version of rUSD EtherFi Stability Pool vaults from Convex Finance.

**Comment by 0xAndrewClark** [comment]
> is is wrapped version of rUSD whose backing we are already counting as part of fx protocol tvl?

arUSD is the tokenized version of rUSD EtherFi Stability Pool vaults from Convex Finance.

**Comment by llamatester** [comment]
The adapter at projects/concentrator exports TVL: 
        
 
 
    ethereum                  25.63 M
    
    total                    25.63 M

**Comment by llamatester** [comment]
The adapter at projects/arUSD exports TVL: 
        
 
 
    ethereum                  1.94 M
    
    total                    1.94 M

**Comment by llamatester** [comment]
The adapter at projects/concentrator exports TVL: 
        
 
 
    ethereum                  25.64 M
    
    total                    25.64 M

**Pull request closed without merging**
