### PR TITLE
feat(benddao): add ape staking information and staking, pool2, treasury

### PR DESCRIPTION
**Pull request by NiobiumZeit**
We have introduced a new feature `ApeStaking`, and have some growth about the TVL. Besides, i have also implemented the filtered TVL staking, pool2 and treasury.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/benddao exports TVL: 
        
 
 
    ethereum-treasury         169.08 k
    ethereum-staking          36.20 M
    ethereum-borrowed         40.47 M
    ethereum                  198.13 M
    ethereum-pool2            2.73 M
    treasury                  169.08 k
    staking                   36.20 M
    borrowed                  40.47 M
    pool2                     2.73 M
    
    total                    198.13 M

**Comment by llamatester** [comment]
The adapter at projects/benddao exports TVL: 
        
 
 
    ethereum-pool2            2.72 M
    ethereum-staking          36.22 M
    ethereum-borrowed         40.36 M
    ethereum-treasury         169.11 k
    ethereum                  231.71 M
    pool2                     2.72 M
    staking                   36.22 M
    borrowed                  40.36 M
    treasury                  169.11 k
    
    total                    231.71 M

**Comment by llamatester** [comment]
The adapter at projects/benddao exports TVL: 
        
 
 
    ethereum-treasury         169.11 k
    ethereum-pool2            2.72 M
    ethereum-borrowed         40.36 M
    ethereum-staking          36.22 M
    ethereum                  231.71 M
    treasury                  169.11 k
    pool2                     2.72 M
    borrowed                  40.36 M
    staking                   36.22 M
    
    total                    231.71 M

**Comment by llamatester** [comment]
The adapter at projects/benddao exports TVL: 
        
 
 
    ethereum-borrowed         40.32 M
    ethereum-staking          36.82 M
    ethereum-treasury         169.05 k
    ethereum-pool2            2.75 M
    ethereum                  231.57 M
    borrowed                  40.32 M
    staking                   36.82 M
    treasury                  169.05 k
    pool2                     2.75 M
    
    total                    231.57 M

**Comment by g1nt0ki** [comment]
@NiobiumZeit thanks for the PR, I have updated it a bit here to separate treasury and ape staking to their own adapters: https://github.com/DefiLlama/DefiLlama-Adapters/pull/5372

**Pull request merged**
