### PR TITLE
Algomint tvl information

### PR DESCRIPTION
**Pull request by UmarFarooq-MP**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Algomint

##### Twitter Link:
https://twitter.com/Algomint_io

##### Website Link:
https://gousd.algomint.io/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

Algomint-token

##### Current TVL:
`$589588.92862443570926166588997135`

##### Chain:
Algorand

##### Short Description (to be shown on DefiLlama):
Next generation blockchain infrastructure combining interoperability and liquidity consolidation.

##### Token address and ticker if any:
https://algoexplorer.io/asset/441139422

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Bridge

##### forkedFrom (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated):
Screenshot 2022-10-13 at 2 28 24 AM

Just to elaborate this picture we calculated the portion for usdc and then lp portion and summed them to extract the tvl.

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@UmarFarooq-MP thanks for the PR, I have refactored your code a bit here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/4300

you are counting the backing of the usd basket right? wouldnt 'Algo-stable' be more appropriate category?

we can create a separate listing for the bridge part, can you share the escrow address  on eth and btc, I can create the adapter

**Comment by g1nt0ki** [comment]
> @UmarFarooq-MP thanks for the PR, I have refactored your code a bit here: #4300
> 
> you are counting the backing of the usd basket right? wouldnt 'Algo-stable' be more appropriate category?
> 
> we can create a separate listing for the bridge part, can you share the escrow address on eth and btc, I can create the adapter

Will wait for your answer before we list

**Comment by UmarFarooq-MP** [comment]
Thanks @g1nt0ki for rebasing the code and merging it , We would love to have a adapter for bridge as well and yes it falls under the category of `Algo-stable` . I am in contact with the team to get the escrow address once i get them i will share them with you .

**Comment by UmarFarooq-MP** [comment]
Hi @g1nt0ki , Just as a general knowledge question. The api endpoint [](https://asia-southeast1-algomint-tvl.cloudfunctions.net/tvlDetails) can be used to get the escrow (custody) addresses that hold the TVL for the bridged assets (BTC and ETH) but you actually do not need to calculate that themselves as we already calculate that ourselves in the api and the amounts can be queried via the api endpoint [](https://asia-southeast1-algomint-tvl.cloudfunctions.net/tvlSummary).

**Comment by g1nt0ki** [comment]
@UmarFarooq-MP just remembered, sorry but we cant count the goUSD portion of tinyman LP under your tvl, we do this to similar protocols like Frax and recently added Ape-fi. The fix is here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/4319

The reason for this is, user can mint 1000 FRAX with 1000$ worth of USDC, then if protocol mints another 1000$ of FRAX without any backing and puts both on LP, LP value is 2000, but protocol is backed by only 1000$

**Comment by UmarFarooq-MP** [comment]
Hey @g1nt0ki thank you for updating and it make sense , i would like to make 2 requests if you can look into it.

1. I see of all the categories I believe CDP would be the most appropriate category. Truthfully the goUSD basket does not exactly fit in to any of the categories they provide based on the exact descriptions of those categories, so it's really a best fit case for us, in which case CDP is the best fit case for the current V1 but when we add crosschain functionality to connect into the wrapper then Bridge would be the best fit category . If you can change it's catagory to CDP that would be super nice.
2. If you can reset the values as the sudden dip on the graph is very discouraging so what about a fresh start?

Looking forward to hear from you.
Thanks!

**Comment by g1nt0ki** [comment]
@UmarFarooq-MP Will delete the data before the drop. 

goUSD can be minted with only USDC in Aglomint right? not sure how CDP or bridge category applies.

**Comment by UmarFarooq-MP** [comment]
@g1nt0ki Right now yes it can only be minted with USDC but following versions of the protocol will allow goUSD to be minted with other USD-backed stablecoins, with the next one in line being USDT.

**Comment by g1nt0ki** [comment]
so, not like Maker right? where user is taking over-collateralized loan, imo that differentiates CDP from 'Algo Stable'

**Pull request merged**
