### PR TITLE
feat: update pricing tokens in coins repo

### PR DESCRIPTION
**Pull request by leeamijo**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by Define101** [comment]
Sorry, we need to understand a bit more about all of those BTC on bitlayer and bouncebit chain

Could you please explain what are these?

https://www.btrscan.com/token/0xd53e6f1d37f430d84efad8060f9fec558b36f6fa?tab=Transfers  - ZBTC
https://www.btrscan.com/token/0xf6718b2701d4a6498ef77d7c152b2137ab28b8a3?tab=Transfers  - stBTC
https://www.btrscan.com/token/0x9a6ae5622990ba5ec1691648c3a2872469d161f9?tab=Transfers  - aBitSTBTC
https://www.btrscan.com/token/0xa984b70f7b41ee736b487d5f3d9c1e1026476ea3?tab=Transfers  - aBitWBTC

**Comment by leeamijo** [comment]
> Sorry, we need to understand a bit more about all of those BTC on bitlayer and bouncebit chain
> 
> Could you please explain what are these?
> 
> https://www.btrscan.com/token/0xd53e6f1d37f430d84efad8060f9fec558b36f6fa?tab=Transfers - ZBTC https://www.btrscan.com/token/0xf6718b2701d4a6498ef77d7c152b2137ab28b8a3?tab=Transfers - stBTC https://www.btrscan.com/token/0x9a6ae5622990ba5ec1691648c3a2872469d161f9?tab=Transfers - aBitSTBTC https://www.btrscan.com/token/0xa984b70f7b41ee736b487d5f3d9c1e1026476ea3?tab=Transfers - aBitWBTC

aBitSTBTC/ aBITWBTC----- https://app.avalonfinance.xyz/?marketName=proto_merlin_v3
ZBTC ---  https://btc.zearn.xyz/
stBTC ---- https://app.lorenzo-protocol.xyz/home

**Comment by Define101** [comment]
We can not price aBitBTC and aBitWBTC , those are receipts tokens. Their value is already being tracked when people deposited btc or wbtc on avalon.

**Comment by leeamijo** [comment]
> We can not price aBitBTC and aBitWBTC , those are receipts tokens. Their value is already being tracked when people deposited btc or wbtc on avalon.

Please merge other tokens. Thanks

**Pull request closed without merging**
