### PR TITLE
Amun's DFI and DMX tokens

### PR DESCRIPTION
**Pull request by Grzesiek-P**
### This PR includes 2 tokens, DFI and DMX. Info on them below:

- DFI:
##### [Optional] ETH addresss (to receive a LlamaPunk): 0xE33f67b82ddF3cABb4af48dd5b447872dc9f2cDe

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

- DMX:

### CODE REVIEW

**Comment by 0xngmi** [comment]
I think it'll be better to list these together under the label of "amun", what do you think?

**Comment by Grzesiek-P** [comment]
@0xngmi Okay, let's do it that way!

**Comment by 0xngmi** [comment]
done, just merged the adapters

**Comment by realdealshaman** [comment]
Thanks for contributing! Your LlamaPunk has been sent: https://opensea.io/0xe33f67b82ddf3cabb4af48dd5b447872dc9f2cde

**Pull request merged**
