### PR TITLE
Update airdao harbor stats collection

### PR DESCRIPTION
**Pull request by AndrewAR2**
##### Name (to be shown on DefiLlama):
Harbor

##### Twitter Link:
https://x.com/airdaostarfleet

##### Website Link:
https://star-fleet.io/harbor/liquid-staking/

##### Logo (High resolution, will be shown with rounded borders):
https://star-fleet.io/_next/static/media/harbor.4ada8788.svg

##### Current TVL:
1.01 M

##### Chain:
Name: AirDAO (AMB-NET) 
RPC: https://network.ambrosus.io/, 
Chainid: 16718

##### Short Description (to be shown on DefiLlama):
What is Harbor?
Harbor is a liquid staking platform that allows users to participate in cryptocurrency staking on AirDAO without sacrificing their liquidity. Harbor makes it easy for users to stake their AirDAO ecosystem tokens and earn rewards, while still being able to use those tokens to trade, lend, and borrow.

When users stake their $AMB on Harbor they receive stAMB in return. stAMB functions as a liquid staking derivative token, similar to other platforms. Unlike traditional liquid staking platforms, users staking $AMB on this platform will receive a hybrid reward structure in the form of $AMB, $BOND, and a new token called $HBR.

##### Token address and ticker if any:
$HBR - platform token https://airdao.io/explorer/address/0xd09270E917024E75086e27854740871F1C8E0E10/ 
$stAMB  -  liquid token https://airdao.io/explorer/address/0x2834C436d04ED155e736F994c1F3a0d05C4A8dE4/ 

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Liquid Staking

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/airdao-harbor exports TVL: 
        
 
 
    airdao                    1.01 M
    
    total                    1.01 M

**Comment by AndrewAR2** [comment]
Sorry for the previous PR - it was not fully completed.

**Comment by g1nt0ki** [comment]
sorry, bit confused about this PR, as far as I can see, the code change has no impact on tvl value, other than methodology update, any else needs to changed?

**Comment by AndrewAR2** [comment]
Sorry, the previous PR contained incorrect/incomplete project data. Please update the project data. Thank you very much!!!

**Comment by AndrewAR2** [comment]
Sorry to bother you, but can I expect the information to be fixed?

**Comment by g1nt0ki** [comment]
sorry for the delay, updated it now: https://github.com/DefiLlama/defillama-server/commit/95027229eb92170dfba978feabe38a9654f976a3

**Comment by AndrewAR2** [comment]
Thank you very much!!!

**Pull request closed without merging**
