### PR TITLE
handle solid forks better

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/3xcalibur: 
        
 
  
    
    
    TypeError: Cannot read properties of null (reading 'timestamp')
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/computeTVL/blocks.js:104:63

**Comment by llamatester** [comment]
The adapter at projects/3xcalibur exports TVL: 
        
 
 
    arbitrum                  8.69 M
    
    total                    8.69 M

**Comment by llamatester** [comment]
The adapter at projects/ABCDEFX exports TVL: 
        
 
 
    kava                      12.02 k
    fantom                    88.65963873587762
    echelon                   0
    kcc                       2.00 k
    multivac                  652.4492082419999
    
    total                    14.76 k

**Comment by llamatester** [comment]
The adapter at projects/Equalizer exports TVL: 
        
 
 
    fantom-staking            7.86 M
    fantom                    33.06 M
    staking                   7.86 M
    
    total                    33.06 M

**Comment by llamatester** [comment]
The adapter at projects/Velocimeter exports TVL: 
        
 
 
    canto-staking             0
    canto                     209.55 k
    staking                   0
    
    total                    209.55 k

**Comment by llamatester** [comment]
The adapter at projects/archly-finance exports TVL: 
        
 
 
    bsc-staking               12.23 k
    fantom-staking            11.19 k
    fantom                    46.31 k
    arbitrum                  50.81 k
    kava-staking              8.92 k
    kava                      13.27 k
    polygon-staking           8.08 k
    arbitrum-staking          8.48 k
    arbitrum_nova-staking     6.72 k
    optimism-staking          7.25 k
    polygon                   23.52 k
    bsc                       70.34 k
    optimism                  34.07 k
    telos-staking             51.86 k
    telos                     205.39 k
    arbitrum_nova             23.64 k
    staking                   114.74 k
    
    total                    467.35 k

**Comment by llamatester** [comment]
The adapter at projects/cone exports TVL: 
        
 
 
    bsc                       61.88 k
    
    total                    61.88 k

**Comment by llamatester** [comment]
The adapter at projects/dystopia exports TVL: 
        
 
 
    polygon                   543.56 k
    
    total                    543.56 k

**Comment by llamatester** [comment]
The adapter at projects/equilibre exports TVL: 
        
 
 
    kava                      19.48 M
    
    total                    19.48 M

**Comment by llamatester** [comment]
The adapter at projects/flair-dex exports TVL: 
        
 
 
    avax                      500.07 k
    
    total                    500.07 k

**Comment by llamatester** [comment]
The adapter at projects/hermes-protocol exports TVL: 
        
 
 
    metis-staking             8.17 M
    metis                     11.18 M
    staking                   8.17 M
    
    total                    11.18 M

**Comment by llamatester** [comment]
The adapter at projects/minerswap exports TVL: 
        
 
 
    ethpow                    0.00028000791816777475
    
    total                    0.00028000791816777475

**Comment by llamatester** [comment]
The adapter at projects/mute exports TVL: 
        
 
 
    era                       1.55 M
    
    total                    1.55 M

**Comment by llamatester** [comment]
The adapter at projects/ramses exports TVL: 
        
 
 
    arbitrum-staking          6.79 M
    arbitrum                  42.97 M
    staking                   6.79 M
    
    total                    42.97 M

**Comment by llamatester** [comment]
The adapter at projects/satin exports TVL: 
        
 
 
    polygon                   25.69 k
    
    total                    25.69 k

**Comment by llamatester** [comment]
The adapter at projects/solidly-v2 exports TVL: 
        
 
 
    ethereum                  21.54 M
    ethereum-staking          42.47 M
    staking                   42.47 M
    
    total                    21.54 M

**Comment by llamatester** [comment]
The adapter at projects/solidly exports TVL: 
        
 
 
    fantom                    1.36 M
    
    total                    1.36 M

**Comment by llamatester** [comment]
The adapter at projects/spartacus-exchange exports TVL: 
        
 
 
    fantom                    2.59 M
    
    total                    2.59 M

**Comment by llamatester** [comment]
The adapter at projects/sterling-finance exports TVL: 
        
 
 
    arbitrum                  2.05 M
    
    total                    2.05 M

**Comment by llamatester** [comment]
The adapter at projects/tarina exports TVL: 
        
 
 
    avax                      108.67 k
    
    total                    108.67 k

**Comment by llamatester** [comment]
The adapter at projects/thena exports TVL: 
        
 
 
    bsc                       109.59 M
    
    total                    109.59 M

**Comment by llamatester** [comment]
The adapter at projects/velocimeter-v2 exports TVL: 
        
 
 
    canto                     7.29 M
    
    total                    7.29 M

**Comment by 0xShad0w** [comment]
Prices for some of the tokens that compose the TVL are incorrect or now showing as 0. This is happening in most of the forks.

**Comment by g1nt0ki** [comment]
hi @0xShad0w can you give me a sample adapter where this is happening? I will look into it

**Pull request merged**
