### PR TITLE
Migrate Voodoo to Base

### PR DESCRIPTION
**Pull request by chicken-juju**
##### Name (to be shown on DefiLlama):

Voodoo Trade

##### Twitter Link:

https://twitter.com/tradevoodoo

##### List of audit links if any:

https://github.com/voodoo-trade/voodoo-contracts/blob/master/voodoo-audits/PeckShield-Audit-Report-Voodoo-v1.0.pdf

##### Website Link:

https://voodoo.trade

##### Logo (High resolution, will be shown with rounded borders):

https://3454642763-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FT6l8q88WIAKZK2Q8MAmD%2Fuploads%2FhJvfb86BjwQ8q9VnPBEr%2FVMX%20token.png?alt=media&token=59257623-f7f9-48b2-9df6-9ac6c23d3ace

##### Current TVL:

$150k

##### Chain:

Base

##### Short Description (to be shown on DefiLlama):

Voodoo Trade is the ultimate ETH-focused perpetual DEX on Base Network. Voodoo caters solely to the ETH/USDC pair, offering the deepest liquidity and most competitive margin fees available, on par with CEX rates. LPs can earn real yield from both margin trades and swaps on Base's most highly traded pair, with no need to hold any tokens besides ETH and stables. Voodoo is a fair launch platform with support from an array of Base Ecosystem stakeholders, and implements a long-term oriented tokenomics system that is the first of its kind for perpetual DEXs.

##### Token address and ticker if any:

Address: `0x44d05c7Bf593b4cC4322088fFCa35613079E8D37`
Ticker: $VMX

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Derivatives

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

- Chainlink
- FastPriceFeed is a custom oracle

##### forkedFrom (Does your project originate from another project):

GMX

##### methodology (what is being counted as tvl, how is tvl being calculated):

TVL falls in two groups

1. VLP: ETH and USDC liquidity in the vault for margin trading
2. pool2: VMX-ETH liquidity tokens from Pancakeswap are staked to earn APR

##### Github org/user (Optional, if your code is open source, we can track activity):

https://github.com/voodoo-trade

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/voodoo-trade exports TVL: 
        
 
 
    base-pool2                0
    base                      152.00 k
    pool2                     0
    
    total                    152.00 k

**Comment by g1nt0ki** [comment]
@chicken-juju thanks for the PR, we would like to retain the fantom tvl (even though it is 0) else, fantom chain tvl history would be affected

**Comment by g1nt0ki** [comment]
so I made a fix here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/8002

**Comment by secretshardul** [comment]
@g1nt0ki the description and token link on Defi Llama is still outdated- still mentioning Fantom. Can you please update? The new description and token link is provided in this PR.

image

**Comment by chicken-juju** [comment]
@g1nt0ki the project description and token address need to be updated still- they mention Fantom. Correct description and address is given in this PR.

image

**Pull request closed without merging**
