### PR TITLE
Updated tvl & tested pass

### PR DESCRIPTION
**Pull request by dtderitrade**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
DeriTrade

##### Twitter Link:
https://twitter.com/deritrade?lang=en

##### Website Link:
https://deri.trade

##### Logo (High resolution, will be shown with rounded borders):
https://deritrade.gitbook.io/deritrade/brand-kit

##### Chain:
Arbitrum, BSC, zkSync

##### Short Description (to be shown on DefiLlama):
DERI Trade brings innovative ideas into Multi-Chain with real yield, copy-trading, and various products (FX, Crypto, Metals & Equity) that beginners can easily start their investing journey with.

##### Token address and ticker if any:
https://bscscan.com/token/0x738EA75B01D8db931B4374c6EBd3DE82d7d3A272

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### forkedFrom (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated):
deposited token (USDC) during fair launch that will be used for token allocation

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/deritrade exports TVL: 
        
 
 
    bsc                       0
    arbitrum                  0
    zksync                    0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/deritrade exports TVL: 
        
 
 
    era                       320
    bsc                       9.18 k
    arbitrum                  445
    
    total                    9.94 k

**Comment by llamatester** [comment]
The adapter at projects/deritrade exports TVL: 
        
 
 
    bsc                       11.31 k
    arbitrum                  661.661
    era                       346.34599999999995
    
    total                    12.32 k

**Comment by llamatester** [comment]
The adapter at projects/deritrade exports TVL: 
        
 
 
    era                       346
    arbitrum                  661
    bsc                       11.30 k
    
    total                    12.30 k

**Comment by llamatester** [comment]
The adapter at projects/deritrade exports TVL: 
        
 
 
    arbitrum                  661
    bsc                       11.30 k
    era                       346
    
    total                    12.30 k

**Comment by g1nt0ki** [comment]
hi @dtderitrade , sorry, if the users cant get back deposited amount, we cant use it as tvl

**Comment by g1nt0ki** [comment]
and I can see the contract splits and forwards tokens to EOA, it does not hold the USDC

**Pull request closed without merging**
