### PR TITLE
Add roup project

### PR DESCRIPTION
**Pull request by butcher-blaviken**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/roup exports TVL: 
        
 
 
    map                       207.22 k
    
    total                    207.22 k

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
I am tempted to just close this PR, there is zero information about the project, you are counting both the token supply and token balance on a contract,  why? there is no comment explaining this.

if roup is a bridge protocol, please provide the BTC address where the brc20 tokens are kept when you mint their equivalent on map protocol

**Comment by llamatester** [comment]
Error while running adapter at projects/roup: 
        
 
  
    
    
    Error: Failed to get https://open-api.unisat.io/v1/indexer/address/bc1pv5lu5aklz64sye9f4zmnjkfg8j6s2tllu3fem4cs9t0hcrnz5e7qy0qw6e/brc20/summary
    Truncated error stack:
    
        at get (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/http.js:32:11)
        at async sumTokens (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/brc20.js:11:34)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:64:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:160:9
        at async Promise.all (index 0)
        at async Promise.all (index 2)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:3

**Comment by llamatester** [comment]
Error while running adapter at projects/roup: 
        
 
  
    
    
    Error: Failed to get https://open-api.unisat.io/v1/indexer/address/bc1pv5lu5aklz64sye9f4zmnjkfg8j6s2tllu3fem4cs9t0hcrnz5e7qy0qw6e/brc20/summary
    Truncated error stack:
    
        at get (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/http.js:32:11)
        at async sumTokens (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/brc20.js:11:34)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:64:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:160:9
        at async Promise.all (index 0)
        at async Promise.all (index 2)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:3

**Comment by butcher-blaviken** [comment]
@g1nt0ki Hello, I provided the BTC addresses, do I need to configure anything else

**Comment by g1nt0ki** [comment]
@butcher-blaviken can you please fill in the project info in the PR description?

**Comment by llamatester** [comment]
Error while running adapter at projects/roup: 
        
 
  
    
    
    Error: Failed to get https://open-api.unisat.io/v1/indexer/address/bc1pv5lu5aklz64sye9f4zmnjkfg8j6s2tllu3fem4cs9t0hcrnz5e7qy0qw6e/brc20/summary
    Truncated error stack:
    
        at get (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/http.js:32:11)
        at async Object.sumTokens (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/brc20.js:11:34)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:64:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:160:9
        at async Promise.all (index 0)
        at async Promise.all (index 2)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:3

**Comment by Define101** [comment]
@butcher-blaviken at least provide the website and twitter links .....

**Comment by butcher-blaviken** [comment]
@Define101  ok, done

**Pull request merged**
