### PR TITLE
QuasarSwap - Nova Network

### PR DESCRIPTION
**Pull request by patriotze**
DEX on Nova Network

**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

##### Twitter Link:
https://

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
Coingecko not tracking Nova Network yet

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
CMC not tracking Nova Network yet

##### Short Description (to be shown on DefiLlama):
First decentralized exchange on the Nova Network! Staking via Farms and Pools, and even NFT staking

##### Token address and ticker if any:
0x356c044B99e9378C1B28A1cAb2F95Cd65E877F33
QSR

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### forkedFrom (Does your project originate from another project):
Pancake Swap

##### methodology (what is being counted as tvl, how is tvl being calculated):

Counts tokens/token value held in the Quasar contracts

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/quasar-swap exports TVL: 
        
 
 
    nova-staking              12.74 k
    nova                      22.43 k
    staking                   12.74 k
    
    total                    22.43 k

**Comment by g1nt0ki** [comment]
do you have a website/twitter  link?

**Comment by patriotze** [comment]
> do you have a website/twitter link?

https://twitter.com/SwapQuasar
https://discord.gg/jznAjdtvTn

**Comment by patriotze** [comment]
> do you have a website/twitter link?

Sorry submitting for someone else, this is their info.

**Comment by g1nt0ki** [comment]
> > do you have a website/twitter link?
> 
> Sorry submitting for someone else, this is their info. https://twitter.com/SwapQuasar https://discord.gg/jznAjdtvTn

I found their website but it seems to be down: https://quasarswap.xyz/

The PR looks good otherwise

**Comment by patriotze** [comment]
> > > do you have a website/twitter link?
> > 
> > 
> > Sorry submitting for someone else, this is their info. https://twitter.com/SwapQuasar https://discord.gg/jznAjdtvTn
> 
> I found their website but it seems to be down: https://quasarswap.xyz/
> 
> The PR looks good otherwise
Yea its down for a few while they fix something, I have relayed the information to them.

**Comment by g1nt0ki** [comment]
thanks

**Comment by patriotze** [comment]
> thanks

It appears their site is back up.

**Comment by patriotze** [comment]
> thanks

Also forgot to add the logo when submitting.

https://gateway.pinata.cloud/ipfs/QmfMASEZKwssMntgwRtHjNK6zqJBZMwoYeqyWcLzRqCbLd

**Comment by llamatester** [comment]
The adapter at projects/quasar-swap exports TVL: 
        
 
 
    nova-staking              5.95 k
    nova                      22.73 k
    staking                   5.95 k
    
    total                    22.73 k

**Pull request merged**
