### PR TITLE
Add Upshift to Defi Listing 

### PR DESCRIPTION
**Pull request by krishnafractol**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Upshift

##### Twitter Link:
https://x.com/upshift_fi

##### List of audit links if any:
https://docs.upshift.finance/architecture/smart-contract-audits

##### Website Link:
https://www.upshift.finance/

##### Logo (High resolution, will be shown with rounded borders):
Upshift_Round

##### Current TVL:
$73.96 million 

##### Treasury Addresses (if the protocol has treasury)
n/a

##### Chain:
Ethereum, Avalanche, Base

##### Short Description (to be shown on DefiLlama):
Upshift opens access to transparent yields backed by secure risk controls. Supply, stake and access cross-chain yields.

##### Token address and ticker if any:
n/a

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield

##### forkedFrom (Does your project originate from another project):
n/a

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is the sum of totalAssets for each erc4626 vault, meaning the sum of user deposits in all vaults.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/upshift exports TVL: 
        
 
 
    base                      36.51 M
    ethereum                  13.98 M
    avax                      3.11 M
    
    total                    53.59 M

**Comment by llamatester** [comment]
The adapter at projects/upshift exports TVL: 
        
 
 
    base                      36.14 M
    ethereum                  25.91 M
    avax                      3.11 M
    
    total                    65.16 M

**Comment by llamatester** [comment]
The adapter at projects/upshift exports TVL: 
        
 
 
    base                      36.14 M
    ethereum                  25.91 M
    avax                      3.11 M
    
    total                    65.16 M

**Comment by llamatester** [comment]
The adapter at projects/upshift exports TVL: 
        
 
 
    base                      36.10 M
    ethereum                  34.72 M
    avax                      3.11 M
    
    total                    73.92 M

**Comment by llamatester** [comment]
The adapter at projects/upshift exports TVL: 
        
 
 
    base                      36.38 M
    ethereum                  34.92 M
    avax                      3.11 M
    
    total                    74.41 M

**Comment by g1nt0ki** [comment]
thanks for the PR

**Pull request merged**
