### PR TITLE
feat: add telos to vapordex

### PR DESCRIPTION
**Pull request by royvardhan**
Added Telos chain support for [Vapordex](https://defillama.com/protocol/vapordex)

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/vapordex-v2: 
        
 
  
    
    
    Error: Missing target!
    Truncated error stack:
    
        at getLogs (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/cache/getLogs.js:12:22)
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/uniswapV3.js:26:28)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:64:29)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:160:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:143:44

**Comment by llamatester** [comment]
The adapter at projects/vapordex-v2 exports TVL: 
        
 
 
    avax                      3.87 k
    telos                     0.320134146802334
    
    total                    3.87 k

**Comment by llamatester** [comment]
The adapter at projects/vapordex exports TVL: 
        
 
 
    avax                      1.94 M
    telos                     0.027517261374513786
    
    total                    1.94 M

**Comment by g1nt0ki** [comment]
@royvardhan thanks for the PR

**Comment by royvardhan** [comment]
> @royvardhan thanks for the PR

Thank you for merging! I don't see Vapordex on this page, why is that so? https://defillama.com/protocols/dexes/Telos

**Pull request merged**
