### PR TITLE
Khala mining staking TVL

### PR DESCRIPTION
**Pull request by jasl**
# Khala Network

##### List of audit links if any: https://www.certik.com/projects/phalanetwork
https://github.com/Phala-Network/prelaunch-token/blob/master/audit/PHAToken-SmartContract-Audit-Report.pdf

##### Website Link:
https://www.phala.network/zh/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

https://drive.google.com/file/d/1XV6oMgTBRUi_QJVM6zofCLM-ThthaZnE/view?usp=sharing
https://drive.google.com/file/d/1O0Kg0nhvw-Gl-uUhuVXoOjxQ-220lGnY/view?usp=sharing

##### Current TVL:

$7.6m

##### Chain:
Kusama

##### Coingecko ID (so your TVL can appear on Coingecko): 
```
pha
```
```
{"id":"pha","symbol":"pha","name":"Phala Network"}
```

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap):

`id:6841`

`{"id":6841,"name":"Phala Network","symbol":"PHA","slug":"phala-network","is_active":1,"status":"active","first_historical_data":"2020-09-13T02:39:27.000Z","last_historical_data":"2022-03-16T10:19:00.000Z","rank":463}`

##### Short Description (to be shown on DefiLlama):

Phala Network is a decentralized computation cloud by organizing a decentralized network of computation nodes around the world, it offers high-performance services without relying on any cloud vendor. 

##### Token address and ticker if any:

https://etherscan.io/token/0x6c5bA91642F10282b576d91922Ae6448C9d52f4E
https://khala.subscan.io/

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Staking

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

Chainlink

##### forkedFrom (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated):

- TVl is counting by the $PHA token staking for computation nodes on Phala Network
- We collate the amount of $PHA for staking to compuation nodes, and use the price oracle to convert the ammount into TVL

### CODE REVIEW

**Comment by jasl** [comment]
Sorry for late respond

>  is this liquid staking?

No

> Do users get transferrable tokens to represent their staked tokens?

No, users won't get transferrable tokens.

Unlike PoS chain staking, mining staking is users promoting computing workers and get reward when workers finish jobs

**Comment by waynebruce0x** [comment]
The team have had a discussion and we think this sounds a lot like chain staking opposed to defi, so we're unable to list it

**Comment by jasl** [comment]
> The team have had a discussion and we think this sounds a lot like chain staking opposed to defi, so we're unable to list it

it's unlike chain staking, a worker can mining or not are not decide by how people stake on it,
people stake worker(s) are because:

1 by our tokenomic, the more stake, the more tokens earn, worker's owner wanna share the earnings
2 the worker has well maintain, stable network and powerful hardware so it can finish more jobs and less offline time

here is our mining & staking introduction doc <https://wiki.phala.network/en-us/learn/tokenomics/mining-staking/> tokenomic doc <https://wiki.phala.network/en-us/learn/tokenomics/tokenomics/>

**Comment by waynebruce0x** [comment]
Sorry it sounds a lot like staking to secure the network - we can only list this kind of staking if its liquid

**Pull request closed without merging**
