### PR TITLE
add solyard

### PR DESCRIPTION
**Pull request by jianfengxiaojianfeng**
##### Twitter Link: 
https://twitter.com/SolyardFinance

##### Website Link: 
https://solyard.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://solyard.finance/logo.png

##### Current TVL:
$13,253,888.78

##### Chain:
Solana

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
No token yet

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
No token yet

##### Description/bio (to be shown on DefiLlama):
Solyard is New Yield Farming Aggregator Optimizer protocol on #Solana

##### Token address and ticker if any:
No token yet

##### Category (Yield/Dexes/Lending/Minting):
Yield

#### [Optional] ETH addresss (to receive a LlamaPunk):

### CODE REVIEW

**Comment by 0xngmi** [comment]
A few minor nitpicks:
- Unless in a few cases where the protocol is built around LPs that contain the governance token (for example FEI) we tend to exclude pool2 TVL
- We are currently working on separating staking TVL from other sources of TVL

Could you modify the API so that TVL is separated by source? One way to do that would be to make an API that returns these 3 tvls separated or another would be to make an API that returns the TVL by pool, both would work for us

**Comment by jianfengxiaojianfeng** [comment]
> A few minor nitpicks:
> 
> * Unless in a few cases where the protocol is built around LPs that contain the governance token (for example FEI) we tend to exclude pool2 TVL
> * We are currently working on separating staking TVL from other sources of TVL
> 
> Could you modify the API so that TVL is separated by source? One way to do that would be to make an API that returns these 3 tvls separated or another would be to make an API that returns the TVL by pool, both would work for us

solved

**Comment by 0xngmi** [comment]
Thanks, that was quick

**Comment by 0xngmi** [comment]
Will merge and then apply some changes to separate TVLs

**Comment by 0xngmi** [comment]
When executing the code I'm getting the following error:
```
 UnhandledPromiseRejectionWarning: Error: unable to verify the first certificate
 ```
 
 Could there be a problem with the certificate chain?

**Comment by 0xngmi** [comment]
@jianfengxiaojianfeng we can't use this adapter due to the problem explained above

**Comment by jianfengxiaojianfeng** [comment]
> @jianfengxiaojianfeng we can't use this adapter due to the problem explained above

solved

**Comment by 0xngmi** [comment]
There seems to be a difference between the tvl reported by your API and the one you report on your website, a pretty big difference actually (about 10x), could you please update the adapter?

**Pull request merged**
