### PR TITLE
Added port finance.

### PR DESCRIPTION
**Pull request by leonardgee**
##### Twitter Link:
https://twitter.com/port_finance

##### List of audit links if any:
Auditted by Bramah System

##### Website Link:
https://port.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/PoRTjZMPXb9T7dyU7tpLEZRQj7e6ssfAE62j2oQuc6y/PORT.png

##### Current TVL:
10M

##### Chain:
Solana

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
https://www.coingecko.com/en/coins/port-finance

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
https://coinmarketcap.com/currencies/port-finance/

##### Description/bio (to be shown on DefiLlama):
Port Finance is a decentralized Money Market protocol on Solana, aiming to provide a full suite of lending products including but not limited to: variable rate lending, fixed rate lending and interest rate swaps.

##### Token address and ticker if any:
https://explorer.solana.com/address/PoRTjZMPXb9T7dyU7tpLEZRQj7e6ssfAE62j2oQuc6y

##### Category (Yield/Dexes/Lending/Minting):
Lending

### CODE REVIEW

**Comment by 0xngmi** [comment]
When running your code with `node test.js projects/portfinance/index.js` I get the following result:
```
--- tvl ---
usd-coin                  0
tether                    0
solana                    0
usdp                      0
mercurial                 0
bitcoin                   0
serum                     0
Total: 0
```

which doesn't seem to be correct

**Comment by leonardgee** [comment]
I was mistaken. The fixed by a new commit:
```
--- tvl ---
solana                    6.60 M
mercurial                 1.06 M
usd-coin                  318.72 k
serum                     17.80 k
tether                    5.40832300125
usdp                      2.2088864627800002
bitcoin                   0.655368
Total: 8.00 M
```

**Comment by 0xngmi** [comment]
It seems that after the last commit was applied this PR doesn't make any changes to the file

**Comment by leonardgee** [comment]
That is correct. However, it seems like Port is still now showing in Defi Llama, is there any action that we need to take?

**Comment by leonardgee** [comment]
Closed due to no effect.

**Comment by leonardgee** [comment]
Additionally, the current TVL calculation is just approximation, what will be a good way for us to provide an accurate calculation?

**Comment by 0xngmi** [comment]
>  However, it seems like Port is still now showing in Defi Llama, is there any action that we need to take?

We implemented it some time ago but back then we were getting different values when making the same query consecutively, we asked on the solana discord about it and were told that it was likely a bad node and to just wait a bit. After that I just forgot, but earlier today I came back to it and fixed a bug to get it listed.

> Additionally, the current TVL calculation is just approximation, what will be a good way for us to provide an accurate calculation?

Why is the current TVL calculation an approximation? Shouldn't it be exact since it's directly querying token balances?

**Comment by 0xngmi** [comment]
Btw, the protocol was listed earlier today https://defillama.com/protocol/port-finance

**Comment by leonardgee** [comment]
> Btw, the protocol was listed earlier today https://defillama.com/protocol/port-finance

Thank you!

> Why is the current TVL calculation an approximation? Shouldn't it be exact since it's directly querying token balances?

The current query is only for the token that hasn't been lent out. However, I think it makes more sense if it also calculated the part that **has** been lent out. Otherwise, when there is more lending happens, the TVL decreases.

**Comment by 0xngmi** [comment]
> The current query is only for the token that hasn't been lent out. However, I think it makes more sense if it also calculated the part that has been lent out. Otherwise, when there is more lending happens, the TVL decreases.

The main issue with this is that people will recursively borrow from your protocol and inflate the tvl if we count borrowed coins as well. That's the reason why we don't count these for other lending markets, and, to keep comparisons straight, we shouldn't do it here either

**Pull request closed without merging**
