### PR TITLE
using graph to get tvl

### PR DESCRIPTION
**Pull request by sameretto**
using graph for tvl

### CODE REVIEW

**Comment by waynebruce0x** [comment]
we try to avoid thegraph because it gives us issues when it falls behind current block

**Comment by sameretto** [comment]
so what can we do about this? We need this data

**Comment by sameretto** [comment]
> we try to avoid thegraph because it gives us issues when it falls behind current block

**Comment by sameretto** [comment]
> we try to avoid thegraph because it gives us issues when it falls behind current block

also its supported in your docs

**Comment by waynebruce0x** [comment]
Yeah it is supported, but as I say, we try to avoid it because your adapter will be broken a lot. I only asked because it looks like it was previously calculated using on-chain calls. What was missing from the adapter before? Maybe I can help add it to the on-chain version

**Comment by sameretto** [comment]
> Yeah it is supported, but as I say, we try to avoid it because your adapter will be broken a lot. I only asked because it looks like it was previously calculated using on-chain calls. What was missing from the adapter before? Maybe I can help add it to the on-chain version

yea we did previously support that but we have new data that cant be achieved with onchain calls due to the team that created it but our graph has it. This adds to our tvl which is why we would like this submitted even though sometimes it might be broken on visits.

**Pull request merged**
