### PR TITLE
Yieldly TVL - First defi contracts on Algorand

### PR DESCRIPTION
**Pull request by Yieldlan**
##### Current TVL:
~ 1 million dollars in Algorand native token locked
Users also have a lot of our Yieldly token locked in our contract, but it does not have a market value yet until we bridge it to Ethereum in a few weeks. We will uncomment those TVL additions when a market value is reached on coingecko.
##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
TBD
##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
TBD
##### Token address and ticker if any: Ticker: YLDY
Address: https://algoexplorer.io/asset/226701642
##### [Optional] ETH addresss (to receive a LlamaPunk): TBD (we will come back for this)

### CODE REVIEW

**Comment by Yieldlan** [comment]
yieldly_logo

**Comment by Yieldlan** [comment]
Yieldly

**Comment by Yieldlan** [comment]
Thanks :)

**Comment by 0xngmi** [comment]
Is it possible to get the algorand staked at different block heights?

**Comment by Yieldlan** [comment]
Hey,

Technically yes you can get the state of the contract at different block heights. 

Although getting it is tricky at the moment because the only full node we have access to is heavily locked down for use with out front end. It's so early in Algorand that even running a node is a huge ordeal.

We decided to use the current application state for our tvl calc because we can get it from the public explorer.

Thanks for merging.

**Comment by 0xngmi** [comment]
got it, well it's always something we can push later

**Comment by Yieldlan** [comment]
We only launched today :)

**Comment by 0xngmi** [comment]
Oh nice, had no idea. No need for this then!

Btw, congrats on the launch!

**Comment by 0xngmi** [comment]
https://twitter.com/DefiLlama/status/1401180813404917760

**Comment by Yieldlan** [comment]
Thanks a lot for the shoutout!

We will get a replacement image for you soon as the one we provided isn’t
suited to a circle.

**Comment by Yieldlan** [comment]
Hey mate, here is a better logo for the Yieldly icon.

Can you please update it for us?

YLDY Token

Cheers

**Comment by Yieldlan** [comment]
[YLDY Token.svg.zip](https://github.com/DefiLlama/DefiLlama-Adapters/files/6604166/YLDY.Token.svg.zip)

**Comment by Yieldlan** [comment]
And here is a svg copy

**Comment by 0xngmi** [comment]
Updated!

**Pull request merged**
