### PR TITLE
add DackieSwap Optimism

### PR DESCRIPTION
**Pull request by DackieSwap**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

Defillama commit

---
##### Name (to be shown on DefiLlama):
DackieSwap

##### Twitter Link:
https://twitter.com/DackieSwap

##### List of audit links if any:
https://github.com/peckshield/publications/blob/master/audit_reports/PeckShield-Audit-Report-DackieSwap-v1.0.pdf

##### Website Link:
https://www.dackieswap.xyz/

##### Logo (High resolution, will be shown with rounded borders):
https://www.dackieswap.xyz/logo.png

##### Current TVL:
~ 1M$

##### Chain:
Optimism

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
https://www.coingecko.com/en/coins/dackieswap

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
https://coinmarketcap.com/currencies/dackieswap/

##### Short Description (to be shown on DefiLlama):
The Premier User-Friendly Multi-chain DEX

##### Token address and ticker if any:
DACKIE (Optimism chain)
https://optimistic.etherscan.io/address/0x47C337Bd5b9344a6F3D6f58C474D9D8cd419D8cA

##### Category (full list at https://defillama.com/categories) *Please choose only one:
DeFi

##### forkedFrom (Does your project originate from another project):
UniSwap V2 & V3

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/DackieSwap

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/dackieswap-v2 exports TVL: 
        
 
 
    base                      55.45 k
    optimism                  10.45 k
    
    total                    65.90 k

**Comment by llamatester** [comment]
The adapter at projects/dackieswap exports TVL: 
        
 
 
    optimism                  0
    base                      0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/dackieswap-v2 exports TVL: 
        
 
 
    base                      55.44 k
    optimism                  10.44 k
    
    total                    65.89 k

**Comment by llamatester** [comment]
The adapter at projects/dackieswap exports TVL: 
        
 
 
    base                      415.08 k
    optimism                  15.64 k
    
    total                    430.72 k

**Comment by g1nt0ki** [comment]
@DackieSwap thanks for the update

**Pull request merged**
