### PR TITLE
fetch solend market and reserves from endpoint

### PR DESCRIPTION
**Pull request by 0xCactus**
This PR dynamically gets new markets and reserves added to solend.

### CODE REVIEW

**Comment by waynebruce0x** [comment]
error: solendConfig.markets is not iterable

**Comment by 0xCactus** [comment]
@waynebruce0x Fixed! 🙏

**Comment by waynebruce0x** [comment]
I've still got an issue: 

 for (const market of solendConfig.markets) {
TypeError: Cannot read properties of undefined (reading 'markets')

**Comment by llamatester** [comment]
The adapter at projects/solend/index.js exports TVL: 
                
 
 
solana                    690.32 M
solana-borrowed           405.92 M
borrowed                  405.92 M

total                    690.32 M

**Comment by 0xCactus** [comment]
@waynebruce0x fixed it for real this time 😄

**Pull request merged**
