### PR TITLE
Dexfinance vaults

### PR DESCRIPTION
**Pull request by tuco-gordian**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/dexfinance-vaults exports TVL: 
        
 
 
    arbitrum                  3.04 M
    base                      2.09 M
    pulse                     808.55 k
    manta                     388.20 k
    bsc                       152.02 k
    avax                      13.24 k
    optimism                  3.99 k
    fantom                    1.57 k
    
    total                    6.50 M

**Comment by tuco-gordian** [comment]
Hi, @g1nt0ki! It would be very cool for us to provide you the API access for fetching TVL. There are few reasons:
1. we have the yield aggregator that supports several completely different types of staking(MasterChefs, SmartChefs, another_few_ones_chefs, PancakeSwap V3 Farms, Uniswap V3 Pools, etc.) that being indexed by a lot of indexation code/microservices on backend side (with custom event-handler system)
2. DexVaults has a factory-based vault creation (when vaults on Beefy created by protocol owners) approach, so every user can creates his own vault(that can be linked with N different farms/poolV3's). 
We don't use subgraph, because backend handling give more flexible and ability for analyzing and statistics. 
We also can provide you all ABI's and factories addresses on all chains, so you can get some values by yourself and check results with our API.

Moreover Debank indexing DexVaults and returns the same TVL value as our API

**Comment by g1nt0ki** [comment]
hi @tuco-gordian yeah, I know it is a pain but we still prefer computing on chain, can you share the abis and factory addresses?

**Comment by tuco-gordian** [comment]
@g1nt0ki yes, sure, where can I send it to you in a private message?

**Comment by g1nt0ki** [comment]
yeah, can you find me in our discord server: https://discord(.)defillama(.)com 

I am uly****

**Comment by g1nt0ki** [comment]
closing this for now

**Pull request closed without merging**
