### PR TITLE
Unlockd Protocol Adapter

### PR DESCRIPTION
**Pull request by leric7**
**NOTE**

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/unlockd: 
        
 
  
    
    
    Error: 
        Found export keys that were not part of specification: nfttvl, apy
    
        List of valid keys: 
    				
    				tvl
    				staking
    				methodology
    				pool2
    				misrepresentedTokens
    				fetch
    				timetravel
    				borrowed
    				start
    				masterchef
    				doublecounted
    				treasury
    				hallmarks
    				incentivized
    				offers
    				deadFrom
    				broken
    				ownTokens
    				vesting

**Comment by llamatester** [comment]
Error while running adapter at projects/unlockd: 
        
 
  
    
    
    Error: invalid address (argument="address", value="", code=INVALID_ARGUMENT, version=address/5.7.0) (argument="provider", value="", code=INVALID_ARGUMENT, version=abi/5.7.0)
    Truncated error stack:
        at AddressCoder.Coder._throwError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/abi/lib/coders/abstract-coder.js:41:16)
        at Array.forEach (<anonymous>)

**Comment by g1nt0ki** [comment]
@leric7 went over the code, looks good, will wait for mainnet launch

**Comment by llamatester** [comment]
The adapter at projects/unlockd exports TVL: 
        
 
 
    ethereum-borrowed         0
    ethereum                  0
    borrowed                  0
    
    total                    0

**Comment by Define101** [comment]
Hello leric7, can you fill out the information section?

**Pull request merged**
