### PR TITLE
updating dead projects

### PR DESCRIPTION
**Pull request by Avedith**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/merlinlab exports TVL: 
        
 
 
    bsc                       0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/witswap exports TVL: 
        
 
 
    ethereum                  0
    
    total                    0

**Comment by Avedith** [comment]
Don't merge yet. :)

**Comment by g1nt0ki** [comment]
> Don't merge yet. :) 

sorry, missed the message, please open a new PR for others.

**Pull request merged**
