### PR TITLE
Add ChopSUI

### PR DESCRIPTION
**Pull request by elthworth**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
ChopSui

##### Twitter Link:
https://twitter.com/OfficialChopSui

##### List of audit links if any:
N/A

##### Website Link:
https://www.chopsui.gg/

##### Logo (High resolution, will be shown with rounded borders):
https://d391b93f5f62d9c15f67142e43841acc.ipfscdn.io/ipfs/bafybeih6zro25qbc6ttjom34mmu3fq74kaajthoc6rl4qh532bmlsvvk5m/chopsuipng.png

##### Current TVL:
ChopSui: N/A

##### Treasury Addresses (if the protocol has treasury)
N/A

##### Chain:
SUI

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

##### Short Description (to be shown on DefiLlama):
At its core, ChopSui provides a comprehensive suite of tools and resources to simplify the process of generating yields in the SUI ecosystem. Users can access a user-friendly dashboard that offers an intuitive interface for managing and executing their yield farming strategies.

##### Token address and ticker if any:
$CHOP
0xa294518fd0c9503f8eaf60eea3f63c1da1dcd115032164b8695de26ecf25a434

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
N/A

##### forkedFrom (Does your project originate from another project):
No.

##### methodology (what is being counted as tvl, how is tvl being calculated):
Total value locked = the number of assets that are being staked in a specific protocol at the moment.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/ChopSuiLab

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/chopsui exports TVL: 
        
 
 
    sui                       0
    
    total                    0

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
hi, if you are an yield protocol, this adapter doesnt make sense, can you fix it?

**Comment by elthworth** [comment]
Hi, we're a startup project and going to build yield strategy platform on Sui.
But currently we have just only dashboard and swap function.
So do you think it would be better to change Category to Dexes for now?

**Comment by g1nt0ki** [comment]
closing this for now, you can put up a new PR with correct adapter when you have some tvl

**Comment by llamatester** [comment]
The adapter at projects/chopsui exports TVL: 
        
 
 
    sui                       0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/chopsui exports TVL: 
        
 
 
    sui                       0
    
    total                    0

**Comment by g1nt0ki** [comment]
hi @elthworth , it is still not showing any tvl, can you please update the adapter, or can I close the PR?

**Pull request closed without merging**
