### PR TITLE
List XRGB into DefiLlama

### PR DESCRIPTION
**Pull request by LevenSton**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
XRGB

##### Twitter Link:
https://twitter.com/XRGB404

##### List of audit links if any:
https://github.com/XRGB/xrgb-contracts-v1/blob/main/audit-report/Certik_XRGB_Audit_Report-v1.0.pdf

##### Website Link:
https://xrgb.xyz/

##### Logo (High resolution, will be shown with rounded borders):
Black-circle-noText

##### Chain:
eth/bsc/linea/base

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
https://www.coingecko.com/en/coins/xrgb

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
https://coinmarketcap.com/currencies/xrgb/

##### Short Description (to be shown on DefiLlama):
XRGB Labs pioneers on the RGB network, aiming to revolutionize digital assets by integrating Bitcoin into Layer 2 solutions for enhanced scalability, speed, and cost-efficiency.
XRGB Launchpad and XRGB Swap together form a comprehensive ecosystem that nurtures creativity and facilitates seamless digital asset exchange on the RGB network.

##### Token address and ticker if any:
0x5cc5e64ab764a0f1e97f23984e20fd4528356a6a

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Bridge

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/XRGB

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/xrgb exports TVL: 
        
 
 
    ethereum                  0
    
    total                    0

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
can you share the bridge address(es) in different chains (including bitcoin for brc20) where tokens are locked when they are bridged to another chain.

We cant list with 0 tvl

**Comment by LevenSton** [comment]
> can you share the bridge address(es) in different chains (including bitcoin for brc20) where tokens are locked when they are bridged to another chain.
> 
> We cant list with 0 tvl

Factory contract address in Ethereum/Base/line/BSC:
0xd0c11Fc959E22b8e9B69c97Ea3cD334d480ce203

XRGB contract address in Ethereum/Base/line/BSC:
0x5cc5e64ab764a0f1e97f23984e20fd4528356a6a

ORDI contract address in Ethereum/Base/line/BSC:
0xec45e3c3c5410cbdbce81dd35edcf9f0f13fc2cb

SATS contract address in Ethereum/Base/line/BSC:
0xbfa536126c1c2b7cba94807a39213fab913950a3

MUBI contract address in Ethereum/Base/line/BSC:
0xaa4f4801c0379ad93f20d6afa610405f6751d0ef

RATS contract address in Ethereum/Base/line/BSC:
0xb0ccc1bddfb93594ceb3e64e68a202c82cb73216

**Comment by g1nt0ki** [comment]
@LevenSton can you share the bitcoin address where brc20 tokens are locked?

**Comment by LevenSton** [comment]
> @LevenSton can you share the bitcoin address where brc20 tokens are locked?

@g1nt0ki btc address:  

bc1ptm05s4f6f8j78zhx62lzx0dep07f2597nlgeltmm4sjn5stdu6gq4sxg2w

**Comment by llamatester** [comment]
Error while running adapter at projects/xrgb: 
        
 
  
    
    
    Error: Failed to get https://open-api.unisat.io/v1/indexer/address/bc1ptm05s4f6f8j78zhx62lzx0dep07f2597nlgeltmm4sjn5stdu6gq4sxg2w/brc20/summary
    Truncated error stack:
    
        at get (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/http.js:33:11)
        at async sumTokens (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/brc20.js:11:34)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:143:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:186:3

**Pull request merged**
