### PR TITLE
fix: compute TVL based on enter and exits instead of balances

### PR DESCRIPTION
**Pull request by 0xtekgrinder**

### CODE REVIEW

**Comment by llamabutler** [comment]
The adapter at projects/rings exports TVL: 
        
 
 
    ethereum                  5
    sonic                     0
    
    total                    5.0249999999999995

**Comment by 0xtekgrinder** [comment]
I tried to make this adapter fetch the vaults concurrently but it looks like it has some weird behaviors when fetching logs

**Comment by llamabutler** [comment]
Error while running adapter at projects/rings: 
        
 
  
    
    
    TypeError: Cannot read properties of null (reading 'args')
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/cache/getLogs.js:52:30
        at Array.map (<anonymous>)
        at getLogs (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/cache/getLogs.js:50:19)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/rings/index.js:52:30
        at async Promise.all (index 1)
        at async tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/rings/index.js:42:7)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:173:9
        at async Promise.all (index 0)

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
sorry, dont agree with this change. Why not count tvl as balance locked in the contract?

Current implementation is more complicated and not scalable as we would have to cache all event logs

**Comment by llamabutler** [comment]
Error while running adapter at projects/rings: 
        
 
  
    
    
    TypeError: Cannot read properties of null (reading 'args')
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/cache/getLogs.js:52:30
        at Array.map (<anonymous>)
        at getLogs (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/cache/getLogs.js:50:19)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/rings/index.js:53:30
        at async Promise.all (index 1)
        at async tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/rings/index.js:43:7)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:173:9
        at async Promise.all (index 0)

**Comment by 0xtekgrinder** [comment]
> sorry, dont agree with this change. Why not count tvl as balance locked in the contract?
> 
> Current implementation is more complicated and not scalable as we would have to cache all event logs

Basically, the USDC assets and so on will later be invested in underlying strategies (steakUSDC, sDAI and so on) so only checking balances will not really works as it will only counts iddle assets

**Comment by g1nt0ki** [comment]
we track steakUSDC, sDAI price, so, they needs to be added to token list, simpler solution?

**Comment by g1nt0ki** [comment]
if it is locked in some strategy without reciept token, we can add custom code to count the value locked in that strategy

**Comment by 0xtekgrinder** [comment]
Closing this as we can just add receipt tokens on the underlying strategies

**Pull request closed without merging**
