### PR TITLE
add plexus

### PR DESCRIPTION
**Pull request by plexusgoon**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
PLEXUS

##### Twitter Link:
https://twitter.com/plexus_fi

##### List of audit links if any:
-

##### Website Link:
https://www.plexus.app/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

Token Symbol_Main

##### Current TVL:
-

##### Treasury Addresses (if the protocol has treasury)
-

##### Chain:
ethereum, polygon, bsc more to be added  

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
hello@plexus.app

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
hello@plexus.app

##### Short Description (to be shown on DefiLlama):
PLEXUS is a Cross-chain aggregator service for mass adoption of blockchain.  All chains, all tokens, and the cheapest swap with just one transaction.

##### Token address and ticker if any:
Plexus(PLX) : 0x60b9c9C167bA57cc376b0FaafC68Df5C9882328e ( ethereum )

##### Category (full list at https://defillama.com/categories) *Please choose only one:
cross chain 

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink price oracle (ethereum)

##### forkedFrom (Does your project originate from another project):
no forked 

##### methodology (what is being counted as tvl, how is tvl being calculated):
There is no TVL  as there is no token distribution yet.

### CODE REVIEW

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
Hi, to be listed in Defillama, there must be some trackable metric, but since you are aggregator I dont think tvl/volume is applicable, is there some way to track your protocol revenue/fees

**Comment by plexusgoon** [comment]
I would like to continue the conversation regarding the Defilama listing.
Do you have a Telegram ID?
I think it would be convenient to talk on telegram.

**Comment by g1nt0ki** [comment]
@plexusgoon we can continue this here or maybe on our discord: https://discord.defillama.com/

**Comment by plexusgoon** [comment]
Although TVL is not yet available, we can still measure trading volume. We
are currently not charging any fees, but we plan to start measuring them
from July onwards.

Is it possible to update the api information on Defilama after initially
uploading basic information? Specifically, we plan to upload an API for
measuring transaction volume at a later time.

**Comment by plexusgoon** [comment]
could you please reply ?

**Comment by g1nt0ki** [comment]
@plexusgoon not sure what metrics to track if we list you, and we dont like listing projects without any metrics, since you are aggregator, trading volume doesnt make sense since it still belongs to underlying bridge app, thats why I asked for revenue/fees. Can we wait for the fee switch to be turned on?

**Pull request closed without merging**
