### PR TITLE
Add Alien Finance Adapter

### PR DESCRIPTION
**Pull request by voidAF**
##### Logo (High resolution, will be shown with rounded borders): 
main_alien

##### Short Description (to be shown on DefiLlama):
Alien Finance is a cutting-edge lending protocol that has been making waves in DeFi. With a focus on innovation, capital efficiency, and user-friendliness, Alien Finance aims to revolutionize the way users utilize capital by lending protocols.

##### Category (full list at https://defillama.com/categories) *Please choose only one: 
Lending

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Red Stone
##### Implementation Details: Briefly describe how the oracle is integrated into your project:
Red Stone’s oracle is used to calculate account’s collateral and debt positions.
##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
https://blastscan.io/address/0x3A9B69eE4b7F238c38380A540B211f682f724968

##### methodology (what is being counted as tvl, how is tvl being calculated):
Token balances in the main pool contract

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@voidAF thanks for the PR, refactored and merged here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/9230

**Comment by Define101** [comment]
https://blastscan.io/address/0x3A9B69eE4b7F238c38380A540B211f682f724968 contract is close, cant confirm nothing.

**Comment by stitch626alien** [comment]
@Define101 
We have verified the contract. Please confirm the oracle's usage as needed.
https://blastscan.io/address/0x3a9b69ee4b7f238c38380a540b211f682f724968#code

Also, can you check on our logo? It doesn't seem to display correctly on DefiLlama website.

**Comment by Define101** [comment]
> @Define101 We have verified the contract. Please confirm the oracle's usage as needed. https://blastscan.io/address/0x3a9b69ee4b7f238c38380a540b211f682f724968#code
> 
> Also, can you check on our logo? It doesn't seem to display correctly on DefiLlama website.

Thanks a lot for the fast reply. We will added the oracle information and the logo

**Pull request closed without merging**
