### PR TITLE
Lago DAO DeFiLlama Listing

### PR DESCRIPTION
**Pull request by matt-lago-finance**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): 
lago_logo_icon_large

##### Token address and ticker if any: 
Token Address - lago.USD2 | Token Ticker - USD2
Token Address - lago.kwUSDC | Token Ticker - kwUSDC
Token Address - lago.kwBTC | Token Ticker - kwBTC

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/LagoDAO exports TVL: 
        
 
 
    kadena                    257.08 k
    
    total                    257.08 k

**Comment by realdealshaman** [comment]
Hey, @matt-lago-finance appreciate your PR. I was able to review it and noticed that USD2 is being counted within the TVL. For other CDP protocols we only count the collateral backing the coin

**Comment by llamatester** [comment]
The adapter at projects/LagoDAO exports TVL: 
        
 
 
    kadena                    235.62 k
    
    total                    235.62 k

**Comment by matt-lago-finance** [comment]
Thanks for letting me know @realdealshaman. I have updated the index.js file to reflect only the kwUSDC collateral which backs the USD2 stablecoin.

**Comment by realdealshaman** [comment]
but there's only a 16.46 K USD2 supply, seems that this adapter is actually tracking the entire USDC supply that was bridged?

**Comment by realdealshaman** [comment]
Hey, can you update the adapters so that only the kwUSDC that is locked to create USD2 is exported?

**Comment by realdealshaman** [comment]
Hey @matt-lago-finance ,  should we close this PR? would be cool if the calls returned the amount of kwUSDC to match what has been locked to mint USD2

**Comment by g1nt0ki** [comment]
closing this due to lack of activity

**Pull request closed without merging**
