### PR TITLE
Update Cellana finance - Fix err text  and add CELL token balances

### PR DESCRIPTION
**Pull request by Centure2222**
We have updated the CELL token balances and fixed text errors, thank sir

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/cellana exports TVL: 
        
 
 
    aptos                     2.77 M
    
    total                    2.77 M

**Comment by llamatester** [comment]
The adapter at projects/cellana exports TVL: 
        
 
 
    aptos                     3.45 M
    
    total                    3.45 M

**Comment by llamatester** [comment]
The adapter at projects/cellana exports TVL: 
        
 
 
    aptos                     3.45 M
    
    total                    3.45 M

**Comment by Centure2222** [comment]
> @Centure2222 thanks for the PR, since cellana token is not there in coingecko, I did bit of a hack, count the other side of the pool as tvl since they are always 50% split, right?

yepp sir

**Pull request merged**
