### PR TITLE
add dradex

### PR DESCRIPTION
**Pull request by DradexDex**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Dradex

##### Twitter Link:
https://twitter.com/Dradex_io

##### Website Link:
https://dradex.xyz/

##### Logo (High resolution, will be shown with rounded borders):
https://dradex.xyz/_next/static/media/logo_dark.jpg

##### Chain:
Solana

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### forkedFrom (Does your project originate from another project):
https://github.com/dradex-io formerly project.

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@DradexDex thanks for the PR, but I am bit unsure the point of tracking a project that has already rugged, but also unable to find any info about the rug part

**Comment by DradexDex** [comment]
> thanks for the PR, but I am bit unsure the point of tracking a project that has already rugged, but also unable to find any info about the rug part

Thanks for reply, At the moment tvl is really zero, but given that we have revived our project, I think it still makes sense. we'll get everything set up soon. It's basically a brand new project on the leftovers of the old one. 
I understand your concern, but I'd like to clarify that the project hasn't been frozen, and there's no information about any fraud or other issues. We are confident in its reliability and continue to monitor its development.
Would be happy to merge and follow up on the listing. Thanks.

**Comment by g1nt0ki** [comment]
hi, we cant list a project with 0 tvl. Can you give bit of background, what is the difference between the new and old? is there a new contract deployment? can you share contract details?

I see the site is still showing few million tvl, this is stale info?

**Comment by DradexDex** [comment]
> hi, we cant list a project with 0 tvl. Can you give bit of background, what is the difference between the new and old? is there a new contract deployment? can you share contract details?
> 
> I see the site is still showing few million tvl, this is stale info?

No, we are working with the old contract, just would like to zero out the tvl figures for now while work is still underway. Our old repository - https://github.com/dradex-io

**Comment by g1nt0ki** [comment]
but what happened with the old team/why did the tvl drop to 0, you have added a "rug pull" event but not giving any details

**Comment by DradexDex** [comment]
> but what happened with the old team/why did the tvl drop to 0, you have added a "rug pull" event but not giving any details

The old team was disbanded and the project was bought out by a new development team. The funds (tvl) from the previous project are still under contract, but we would like to use zero tvl on the re-launch, that's all.

**Comment by llamatester** [comment]
The adapter at projects/dradex exports TVL: 
        
 
 
    solana                    2.53 k
    
    total                    2.53 k

**Comment by g1nt0ki** [comment]
@DradexDex thanks for the clarification, but we cant list project with 0 tvl, so for now, I have updated code to compute tvl using the old dex, once new dex is launch, we can update it to use the new contract

**Pull request merged**
