### PR TITLE
Klap adapter

### PR DESCRIPTION
**Pull request by jchung00**
**Note**: Synapse wrapped assets are being used on KLAP for depositing instead of Orbit bridge assets. We have to add a new trasformKlaytnAddress function for Synapse asset mapping specifically.

##### Twitter Link:
https://twitter.com/klapfinance

##### List of audit links if any:
https://docs.klap.finance/useful-info/audit

##### Website Link:
klap.finance

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://docs.klap.finance/useful-info/brand-assets

##### Current TVL:
50M

##### Chain:
Klaytn

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
No token yet

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
No token yet

##### Short Description (to be shown on DefiLlama):
KLAP (Klaytn Lending Application) is the leading money market on Klaytn.

##### Token address and ticker if any:
KLAP - address not available yet

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
TWAP

##### forkedFrom (Does your project originate from another project):
Aave v2

##### methodology (what is being counted as tvl, how is tvl being calculated):
Same as classic Aave v2 TVL calculation.

Counts the tokens locked in the contracts to be used as collateral to borrow or to earn yield. Borrowed coins are not counted towards the TVL, so only the coins actually locked in the contracts are counted. There's multiple reasons behind this but one of the main ones is to avoid inflating the TVL through cycled lending

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/klap: 
        
 
  
    
    
    Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0x78b6ADDE60A9181C1889913D31906bbF5C3795dD","data":"0x365ccbbf","accessList":null}, code=CALL_EXCEPTION, version=providers/5.6.8)
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:650:52
        at Array.forEach (<anonymous>)

**Comment by jchung00** [comment]
Is there an issue here? Just double checked that the address provider registry is correct.

**Comment by llamatester** [comment]
Error while running adapter at projects/klap: 
        
 
  
    
    
    Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0x78b6ADDE60A9181C1889913D31906bbF5C3795dD","data":"0x365ccbbf","accessList":null}, code=CALL_EXCEPTION, version=providers/5.6.8)
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:650:52
        at Array.forEach (<anonymous>)

**Comment by waynebruce0x** [comment]
It looks like the adapter doesnt run. Did you test with 'node test.js projects/klap/index.js'?

**Comment by jchung00** [comment]
@waynebruce0x let me know if this works!

**Comment by llamatester** [comment]
The adapter at projects/klap exports TVL: 
        
 
 
    fantom-borrowed           0
    fantom                    0
    borrowed                  0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/klap exports TVL: 
        
 
 
    klaytn                    0
    klaytn-borrowed           0
    borrowed                  0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/klap exports TVL: 
        
 
 
    klaytn                    45.28 M
    klaytn-borrowed           117.24 M
    borrowed                  117.24 M
    
    total                    45.28 M

**Comment by llamatester** [comment]
The adapter at projects/klap exports TVL: 
        
 
 
    klaytn                    45.28 M
    klaytn-borrowed           117.25 M
    borrowed                  117.25 M
    
    total                    45.28 M

**Pull request merged**
