### PR TITLE
add alphaX tvl

### PR DESCRIPTION
**Pull request by liberhex**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/alphaX-protocol exports TVL: 
        
 
 
    ethereum                  10.07 k
    arbitrum                  1.54 k
    
    total                    11.61 k

**Comment by g1nt0ki** [comment]
Thanks for the pr

**Comment by Define101** [comment]
@liberhex  please provide the website link and twitter

**Comment by liberhex** [comment]
> @liberhex please provide the website link and twitter
the website: https://alphax.com/
the twitter:  https://x.com/AlphaX_Finance

**Comment by liberhex** [comment]
1. Project Name: AlphaX
2. Token Name: None
3. Official website: https://alphax.com/dex/
4. Project introduction: 
  AlphaX Exchange, established in August 2023, is a cutting-edge cryptocurrency exchange. Designed with professional traders in mind, AlphaX provides a sleek, user-friendly interface that ensures a seamless trading experience. Customer satisfaction is prioritized, with a comprehensive support system available to address any inquiries or concerns.
  AlphaX DEX provides 100% on-chain trading with decentralized security, self-custody wallet integration, and a permanent NO-KYC policy, ensuring complete privacy. With ultra-fast transaction speeds and access to high-potential assets, AlphaX is a versatile platform for traders looking for flexibility and reliability in their trading journey.
  Whether interested in popular cryptocurrencies or exploring new market opportunities, AlphaX Exchange offers a trusted platform to meet all trading needs.
5. Contract Address: 
Mainnet: 0xA61a6E696B7C566DA42B80dA27d96e7104bcec99
Arbitrium: 0x552E7A55802f3350C707a243E402aa50Eda9D286
6. Social Media Links: 
X: https://x.com/AlphaX_Finance
Telegram: https://t.me/AlphaXGlobal
Discord: https://discord.gg/pY8ekXzswB
Instagram: https://www.instagram.com/alphax_global/
7. Contact: emma@alphax.com
8. Audit:  https://github.com/AlphaX-Protocol/AlphaX-Protocol-Contract/blob/master/Audit-Report/AlphaX%20Audit%20final.pdf

**Comment by liberhex** [comment]
could you update the Category from dexes to derivative?

**Pull request merged**
