### PR TITLE
add Vesu adapter

### PR DESCRIPTION
**Pull request by 0xpeluche**
##### Name (to be shown on DefiLlama):
Vesu

##### Twitter Link:
https://x.com/vesuxyz

##### Website Link:
https://www.vesu.xyz/

##### Current TVL:
$1.36M

##### Chain:
Starknet

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lend

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/vesu: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'flat')
    Truncated error stack:
        at CallData.parse (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/starknet/dist/index.js:1924:39)
        at parseOutput (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/starknet.js:38:49)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/starknet.js:83:20
        at Array.forEach (<anonymous>)
        at multiCall (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/starknet.js:80:11)

**Comment by 0xpeluche** [comment]
Works locally 

image

**Comment by llamatester** [comment]
The adapter at projects/vesu exports TVL: 
        
 
 
    starknet                  1.36 M
    starknet-borrowed         14.77 k
    borrowed                  14.77 k
    
    total                    1.36 M

**Comment by g1nt0ki** [comment]
> Works locally
> 
> image

not 100% certain why, but it was failing in my machine. So, I refactored it a bit, starknet helper lib is bit of a hack, I think passing parameters as number string instead of in hex format was the issue, but not 100% sure if that was cause, but works now.

**Pull request merged**
