### PR TITLE
xtokn: adding terminal tvl

### PR DESCRIPTION
**Pull request by cryptopixelfrog**
##### Twitter Link:
https://twitter.com/xtokenterminal

##### List of audit links if any:
https://github.com/xtokenmarket/terminal-mining/tree/master/audits

##### Website Link:
https://app.xtokenterminal.io

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
This is our second PR, and do have the Llama page already -  https://defillama.com/protocol/xtoken, and our logo is already there. If the white and black background logo will be used for other purpose, then please let us know. We will deliver later. 

##### Current TVL:
5.59 M 

##### Chain:
Ethereum Mainnet
Arbitrum
Optimism
Polygon

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
xtoken

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
8599

##### Short Description (to be shown on DefiLlama):
The Capital Markets Platform for Web3

##### Token address and ticker if any:
Token: XTK
Address: 0x7f3edcdd180dbe4819bd98fee8929b5cedb3adeb

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Please keep same info - https://defillama.com/protocol/xtoken

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
-

##### forkedFrom (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL includes deposits made to xToken Terminal and xToken Market.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/xtoken/index.js exports TVL: 
        
 
 
    arbitrum                  0
    optimism                  148.13 k
    polygon                   0
    ethereum                  5.65 M
    
    total                    5.80 M

**Comment by waynebruce0x** [comment]
Can this be calculated using onchain calls?

**Comment by cryptopixelfrog** [comment]
> 

Thanks for picking up our PR.
Actually, the new product - Terminal will have user created pools in it, and there are some dynamic data setting requirements, which it leads us to create product specific API. We want to reflect the dynamically created pools and it's data be displayed in near realtime through all the chains. So adding and using the terminal API is required.

**Comment by waynebruce0x** [comment]
Is there a factory contract or something where we can get all the pools? Is the API open source?

**Comment by cryptopixelfrog** [comment]
> Is there a factory contract or something where we can get all the pools? Is the API open source?

We can get pool from https://etherscan.io/tx/0x1dee8d709978443e71f4cefe56d00dc029b2020ccb5c4bbd793f131500f9dcf7#eventlog(clrInstance is the pool address in DeployedIncentivizedPool event) from block x to block y.
Also, we do have publicly accessible subgraphs(total 4 networks for now) which are actively being updated.
The terminal API gets data from above subgraphs, so it is technically open to public. The main reason we push the DefiLlam updates with API is for dynamic extension of pools and networks.

**Comment by waynebruce0x** [comment]
Could we call directly to the subgraphs instead? It'd make the data more transparent. We try to avoid APIs

**Comment by cryptopixelfrog** [comment]
> Could we call directly to the subgraphs instead? It'd make the data more transparent. We try to avoid APIs

Thanks for reply, We respect the transparency policy, but for managing dynamic pools and net, we still think the API is a way to reduce efforts and time.
We do have another new product that is being developed now which has little bit more complicated protocol, and I will make sure we add a more weight on using subgraph or pure contract calls.

**Comment by waynebruce0x** [comment]
Can the XTK/WETH pool TVL be exported separately as 'pool2'?

**Comment by cryptopixelfrog** [comment]
> Can the XTK/WETH pool TVL be exported separately as 'pool2'?

Would you please give little more explanation regarding the 'pool2'? I guess the reason you think the XTK/WETH need to be exported separately is that you may concern duplication of XTK or WETH value with the our existing pools on main net. The Terminal XTK/WETH pool is entirely different pool which is we create via our Terminal product(https://app.xtokenterminal.io/mining/discover), and our own fund, so there are no dup, and number is not doubled.

**Comment by waynebruce0x** [comment]
Pool2 because the LP contains your own platform token

**Comment by cryptopixelfrog** [comment]
> 57c62d2

I just re-wrote entire code. We no longer use internal API, but uses subgraph.
Cheers

**Comment by llamatester** [comment]
The adapter at projects/xtoken/index.js exports TVL: 
        
 
 
    polygon                   0
    optimism                  100.77 k
    arbitrum                  393.15 k
    ethereum                  4.89 M
    
    total                    5.38 M

**Comment by cryptopixelfrog** [comment]
> does this count the XTK/WETH pool as core TVL?

Yes it is. So the mainnet TVL is this. 
--- ethereum ---
WETH                      1.83 M
...
USDT                      230.87 k
....
Total: 4.81 M 

The  230.87 k is the TVL of XTK/WETH pool + KNIGHT/WETH pool.

**Comment by waynebruce0x** [comment]
> Can the XTK/WETH pool TVL be exported separately as 'pool2'?

We do this for every protocol that we list

**Comment by cryptopixelfrog** [comment]
> 2ab5ce9

I got an idea of pool2, and it has been added. Cheers

**Comment by cryptopixelfrog** [comment]
Thanks for the merge!! We are happy to see the new TVL. I leave additional comment here, since we do see some old links on our page - https://defillama.com/protocol/xtoken. Would it be possible to update the Twitter, Audit, Website link with below new ones please?
----------
Twitter Link:
https://twitter.com/xtokenterminal

List of audit links if any:
https://github.com/xtokenmarket/terminal-mining/tree/master/audits

Website Link:
https://app.xtokenterminal.io/
---------- 
Cheers

**Pull request merged**
