### PR TITLE
Add Hubble Protocol

### PR DESCRIPTION
**Pull request by peroxy**
##### Twitter Link:
https://twitter.com/HubbleProtocol

##### List of audit links if any:
https://hubble-markets.gitbook.io/hubble-protocol-official-docs/documentation/security-audits

##### Website Link:
https://hubbleprotocol.io/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
SVG:
hubble_logo_svg
PNG:
hubble_logo_png

##### Current TVL:
$16,870,376 - https://app.hubbleprotocol.io/stats

##### Chain:
Solana

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
hubble
https://www.coingecko.com/en/coins/hubble

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
16643
https://coinmarketcap.com/currencies/hubble-protocol/

##### Short Description (to be shown on DefiLlama):
Hubble is a decentralized finance (DeFi) protocol built on Solana, the only network with the throughput to onboard the future of DeFi mass adoption. Hubble’s Phase 1 launches a Solana native crypto-backed stablecoin, USDH, that earns users a yield on their multi-asset collateral. Phases 2 and 3 will launch DeFi structured products and undercollateralized loans. Hubble’s mission is to democratize DeFi and make sustainable DeFi services available to the world. Hubble shares the vast majority of its fees with users who stake HBB or USDH within the protocol. 

##### Token address and ticker if any:
[HBB111SCo9jkCejsZfz8Ec8nH7T6THF8KEKSnvwT6XK6](https://explorer.solana.com/address/HBB111SCo9jkCejsZfz8Ec8nH7T6THF8KEKSnvwT6XK6)

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Pyth Network

##### Forked From (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL = Total HBB Staked + Total Collateral + Total Stablecoin (USDH) in Stability Pool

### CODE REVIEW

**Comment by 0xngmi** [comment]
Looks like the protocol is on testnet only? We only track live protocols

**Comment by peroxy** [comment]
Hey, that's why I created a draft pull request, just wanted to have it ready for the launch we are doing this Friday. Hopefully that's OK, I'll mark it as ready for review when we're live on mainnet!

**Comment by peroxy** [comment]
Hey guys, we released on mainnet yesterday and our TVL is being calculated correctly now. Please let me know if the PR is OK.
@0xngmi

**Comment by waynebruce0x** [comment]
What's being counted as TVL? Its hard to tell because its an API - is it open source?

**Comment by peroxy** [comment]
TVL = Total HBB Staked * Current HBB price + Total Collateral of all tokens + Total Stablecoin (USDH) in Stability Pool (stablecoin deposited on our platform)

You can find these in our API response as `collateral.total`, `hbb.staked`, `hbb.price` and `usdh.stabilityPool`. Our API currently is not public since we still have some private stuff in there (private nodes) and would require a bit of a refactor.

We get all of the data on-chain (for collateral prices we use SerumMarket chain data and for HBB price we use Orca chain data). We're still planning on adding/removing collateral tokens so we prefer having all of the logic in one place so it's easier to update. Let me know if this is OK, otherwise I will consult with my team on making the API public (it's planned anyway, but not in the near future).

**Comment by peroxy** [comment]
@waynebruce0x our API is now public:

https://github.com/hubbleprotocol/hubble-public-api

**Comment by waynebruce0x** [comment]
Awesome thanks. Can the TVL from staked HBB be exported as a separate 'staking' export, since its your platforms native token?

**Comment by peroxy** [comment]
Yeah, staked HBB could be exported as a separate export as well.
Would you mind giving me a tip on how to do that? I can't find much info in the docs

**Comment by waynebruce0x** [comment]
I'll do it now

**Comment by peroxy** [comment]
I've already done it, mind checking it out @waynebruce0x ?

**Comment by g1nt0ki** [comment]
@peroxy just a heads up, I have converted the adapter to fetch data from solana instead, in case you add new collaterals, please update the adapter as well: https://github.com/DefiLlama/DefiLlama-Adapters/pull/3536 

Or, is there some some way to fetch the collateral list from solana?

**Comment by elliotkennedy** [comment]
> @peroxy just a heads up, I have converted the adapter to fetch data from solana instead, in case you add new collaterals, please update the adapter as well: #3536
> 
> Or, is there some some way to fetch the collateral list from solana?

Hey @g1nt0ki - thanks for the heads-up - we will continue to maintain the collateral list in the adaptor in the near-term.

One issue we have noticed with our project entry - could you please update our project category from "Lending" -> "CDP"? 

Many thanks

**Comment by g1nt0ki** [comment]
@elliotkennedy it  is updated now

**Pull request merged**
