### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by GoodDaisy**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/cvi exports TVL: 
        
 
 
    arbitrum-staking          161.79 k
    ethereum-pool2            490.46 k
    ethereum-staking          20.95 k
    polygon-staking           113.52 k
    polygon-pool2             17.35 k
    arbitrum                  1.49 M
    ethereum                  98.57 k
    polygon                   102.95 k
    staking                   296.25 k
    pool2                     507.81 k
    
    total                    1.70 M

**Comment by llamatester** [comment]
The adapter at projects/cyclefinance exports TVL: 
        
 
 
    avax-staking              2.44 k
    avax                      18.88 k
    staking                   2.44 k
    
    total                    18.88 k

**Comment by llamatester** [comment]
The adapter at projects/hodlify exports TVL: 
        
 
 
    arbitrum                  193.13 k
    ethereum                  23.79 k
    optimism                  147.44 k
    polygon                   135.74 k
    
    total                    500.10 k

**Comment by g1nt0ki** [comment]
Hi @GoodDaisy ,

Thank you for your contribution and the time you've spent on this pull request. We appreciate your attention to detail and your willingness to help improve our codebase.

After reviewing your changes, we've noticed that the proposed changes address minor comment typos, which, while important, do not require a formal pull request for correction. We usually handle these small issues through direct edits as part of code refactors.

We encourage you to continue contributing to our project, and we're grateful for your efforts. If you come across more substantial issues or would like to work on larger enhancements or bug fixes, please feel free to open a new PR.

Again, thank you for your interest in our project, and we look forward to your future contributions.

**Pull request closed without merging**
