### PR TITLE
feat: Add adapter for Reya

### PR DESCRIPTION
**Pull request by rvaitkus23**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Reya Network

##### Twitter Link:
https://x.com/reya_xyz

##### List of audit links if any:
https://docs.reya.network/more-resources/technical-resources

##### Website Link:
https://reya.network/

##### Logo (High resolution, will be shown with rounded borders):
reya-xl

##### Chain:
Reya

##### Short Description (to be shown on DefiLlama):
Reya Network is the world's first trading-optimized modular Layer 2 solution, merging liquidity and offering exceptional speed and performance efficiency for DeFi trading. The network features advanced cross-margining for improved capital efficiency, a dynamic funding rate for market stability, and high-performance transaction capabilities with 100ms block times and 30K TPS. Reya DEX leverages this innovative network to provide unmatched trading conditions, making it the ideal platform for both retail and institutional traders.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes, Derivatives, Yield Aggregator, Liquidity manager, Synthetics, DEX Aggregator

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Stork and Redstone
##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is computed using fetch balances using network explorer

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/reya exports TVL: 
        
 
 
    reya                      49.23 M
    
    total                    49.23 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
We track projects tvl and sum them up to compute chain tvl, not token supply. 

We do track chain assets as a different metric, can you share the bridge address on other chains when tokens are bridged to yours?

**Comment by rvaitkus23** [comment]
Thank you for your feedback

> We track projects tvl and sum them up to compute chain tvl, not token supply.

Can you help us to provide a suitable adapter?
Here is our address of core proxy 0xa763b6a5e09378434406c003dae6487fbbdc1a80
Using [this API](https://explorer.reya.network/api/v2/addresses/0xA763B6a5E09378434406C003daE6487FbbDc1a80/tokens?type=ERC-20) you can see balances for Wrapped Ether and Reya USD (it is a wrapper for USDC 1:1). As `rUSD` is not registered in coingecko not sure how to pass it as part of balance.

> We do track chain assets as a different metric, can you share the bridge address on other chains when tokens are bridged to yours?

Sure, here it is:
usdc(.e) vaults:
ethereum: 0xdff78a949e47c1e90f3dd6dd7fe2fa72b42a75f7
optimism: 0x9239609eED7c40C6DDcEC25D247Ef205103590B6
polygon: 0xC0acBb471465FCf848746D1837d8358aB891546c
base: 0x77e61C6fcAEe80CA578B818DD583d2b78f99289C
arbitrum: 0xa0E9B6DA89BD0303A8163B81B8702388bE0Fde77

weth vaults:
ethereum: 0x64dF894688c5052BeAdC35371cF69151Ebc5D658
optimism: 0xAd7bdD85fdA879fe7771A2546939972F202C1BaE
polygon: 0x72384be7092144cD9a57526B486827E4eA632351
base: 0x2b3A8ABa1E055e879594cB2767259e80441E0497
arbitrum: 0xD7BBE2f6D1B52A27D2dAC28298DE3974a3d13047

**Comment by rvaitkus23** [comment]
@g1nt0ki Can you help me set the adapter response using the information I have provided above?

**Comment by Define101** [comment]
We made a few changes here https://github.com/DefiLlama/DefiLlama-Adapters/pull/11172

**Comment by rvaitkus23** [comment]
Thank you very much. Can we move forward with this adapter as the bridge adapter is added? 🙏

**Comment by g1nt0ki** [comment]
added adapter here: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/reya-perp/index.js

**Pull request closed without merging**
