### PR TITLE
add stealthpad

### PR DESCRIPTION
**Pull request by CryptoSnowPrince**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
StealthPad

##### Twitter Link:
https://twitter.com/stealthpadxyz

##### Website Link:
https://stealthpad.xyz/

##### Logo (High resolution, will be shown with rounded borders):
logo-sm-3034e372

##### Current TVL:
73.31 k

##### Chain:
Ethereum

##### Short Description (to be shown on DefiLlama):
StealthPad is the next generation decentralized launch pad for stealth coins. We are your one stop platform for stealth launch bot sniper and anti rug fund.

##### Token address and ticker if any:
0xB18F98822C22492Bd6b77D19cae9367f3D60fcBf

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Launchpad

##### methodology (what is being counted as tvl, how is tvl being calculated):
Counts liquidity in lp lock contracts and tokens in the token lock contracts

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/merlin exports TVL: 
        
 
 
    era                       0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/stealthpad exports TVL: 
        
 
 
    ethereum                  73.22 k
    
    total                    73.22 k

**Comment by CryptoSnowPrince** [comment]
Okay

**Comment by llamatester** [comment]
The adapter at projects/stealthpad exports TVL: 
        
 
 
    ethereum                  75.38 k
    
    total                    75.38 k

**Comment by g1nt0ki** [comment]
@CryptoSnowPrince thanks for the PR, I have refactored it a bit, for token lockers/launchpads, we count only the LP as tvl, you can check implementation of pinksale/deeplock/etc.

**Comment by CryptoSnowPrince** [comment]
Excuse me, if so, how about token staking?

**Comment by CryptoSnowPrince** [comment]
Should I add staking option?

**Comment by g1nt0ki** [comment]
> Excuse me, if so, how about token staking?

your own gov token in a staking contract can count towards 'staking' export, so far, our policy is to exclude all non LP tokens from tvl for locker protocols.

**Comment by g1nt0ki** [comment]
> Should I add staking option?

are users being rewarded for locking the token?

**Comment by CryptoSnowPrince** [comment]
Ah, okay, I will add staking option.

**Pull request merged**
