### PR TITLE
update oraichain

### PR DESCRIPTION
**Pull request by phutxorai**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/oraichain.js exports TVL: 
        
 
 
    oraichain                 27.69 M
    ethereum-staking          361.79 k
    bsc-staking               282.06 k
    staking                   643.85 k
    
    total                    27.69 M

**Comment by realdealshaman** [comment]
@phutxorai Hi, thank you for the PR, we currently don't count native chain staking for any chain, you can find the reasoning for this in the following discussion: https://github.com/DefiLlama/DefiLlama-Adapters/discussions/435

**Comment by realdealshaman** [comment]
Hello @phutxorai, could you please confirm whether the staking is for the native chain staking? If it is, we can close this PR. Thank you

**Comment by phutxorai** [comment]
@realdealshaman please wait, our team will remove the counting native chain staking soon

**Comment by g1nt0ki** [comment]
@phutxorai can I close this PR? I dont see any changes in code other than addition of oraichain staking

**Comment by g1nt0ki** [comment]
> Dear @llamatester @g1nt0ki I have a question, from the export result, should we remove which item ? oraichain? ethereum-staking? bsc-staking? staking?

you should remove oraichain, but if you do that, there is no change in code, thats why I asked if I can close this PR

**Comment by phutxorai** [comment]
@g1nt0ki 
We want to add Oraichain into this list as it has been an independent L1 network since 2021. How could we do so?
https://defillama.com/chains

**Comment by g1nt0ki** [comment]
@phutxorai does it have some sort of defi protocol on it, like dex/money market? we can list that

**Comment by phutxorai** [comment]
@g1nt0ki 
We have the **OraiDEX** native to Oraichain network, which supports Swap, Liquidity Pool, and Bridge between Oraichain and other IBC chains or Ethereum/BSC: https://oraidex.io/
 
About **OraiDEX**: https://www.coingecko.com/en/exchanges/oraidex

Also, the Oraichain-powered **Orchai** platform is for lending/borrowing & money market: https://app.orchai.io/dashboard

Native blockchain explorer: https://scan.orai.io/

**Comment by g1nt0ki** [comment]
> @g1nt0ki We have the **OraiDEX** native to Oraichain network, which supports Swap, Liquidity Pool, and Bridge between Oraichain and other IBC chains or Ethereum/BSC: https://oraidex.io/
> 
> About **OraiDEX**: https://www.coingecko.com/en/exchanges/oraidex
> 
> Also, the Oraichain-powered **Orchai** platform is for lending/borrowing & money market: https://app.orchai.io/dashboard
> 
> Native blockchain explorer: https://scan.orai.io/

perfect, we can list both of these, can you help me with the rpc/rest queries, I want to get list of pools/liquidity in each pool (in the dex) and list of money markets, and liquidity/borrowed in each market, I get a bit lost in cosmos

**Comment by phutxorai** [comment]
> perfect, we can list both of these, can you help me with the rpc/rest queries, I want to get list of pools/liquidity in each pool (in the dex) and list of money markets, and liquidity/borrowed in each market, I get a bit lost in cosmos

Oraichain is a layer 1 using PoS and we launched it two years ago. We have assets staked in validators and in DeFi apps.
1. Mainnet staking in validators (~4,025,712 ORAI): --> 
`https://lcd.orai.io/cosmos/staking/v1beta1/pool`

2. OraiDEX
- List of pools and liquidity --> 
`https://lcd.orai.io/cosmwasm/wasm/v1/contract/<contract-address-pair>/smart/eyJwb29sIjp7fX0%3D`
Now we have 8 pairs :
- orai1wkhkazf88upf2dxqedggy3ldja342rzmfs2mep | ORAI-AIRI
- orai1jf74ry4m0jcy9emsaudkhe7vte9l8qy8enakvs | ORAI-ATOM
- orai1d37artrk4tkhz2qyjmaulc2jzjkx7206tmpfug | ORAI-OSMO
- orai1m6q5k5nr2eh8q0rdrf57wr7phk7uvlpg7mwfv5 | ORAI-ORAIX
- orai1c5s03c3l336dgesne7dylnmhszw8554tsyy9yt | ORAI-USDT
- orai1ynmd2cemryhcwtjq3adhcwayrm89l2cr4tws4v | ORAI-KWT
- orai1hr2l03ep6p9lwdkuqu5253fgpzc40xcpwymjfc | USDT-MILKY
- orai15aunrryk5yqsrgy0tvzpj7pupu62s0t2n09t0dscjgzaa27e44esefzgf8 | ORAI-scORAI

3. Orchai:
- List of money markets --> I will update soon
- Liquidity/borrowed in each market --> I will update soon

**Comment by g1nt0ki** [comment]
added oraidex here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/210d72522a45e85c903fea0a4bef012688007ca4#diff-ad922a5bc0a944251606bcdfc414ba44524787c1d7adc4df0c60c25478fcef3a

**Comment by phutxorai** [comment]
> added oraidex here: [210d725#diff-ad922a5bc0a944251606bcdfc414ba44524787c1d7adc4df0c60c25478fcef3a](https://github.com/DefiLlama/DefiLlama-Adapters/commit/210d72522a45e85c903fea0a4bef012688007ca4#diff-ad922a5bc0a944251606bcdfc414ba44524787c1d7adc4df0c60c25478fcef3a)

Thank @g1nt0ki , I've just force-push then this pr was closed. 
We will look up `project/oraidex` and maybe update something, because I've just tested and it didn't show right tvl value.
So when it has right tvl, oraidex will be listed on defillama?
And Oraichain, How about Oraichain as a new chain on DefiLlama?

**Pull request closed without merging**
