### PR TITLE
Feat: add m0

### PR DESCRIPTION
**Pull request by 0xpeluche**
---
##### Name (to be shown on DefiLlama):
m0

##### Twitter Link:
https://x.com/m0foundation

##### List of audit links if any:
https://docs.m0.org/portal/technical/audits

##### Website Link:
https://www.m0.org/

##### Current TVL:
53.6

##### Chain:
ethereum

##### Category (full list at https://defillama.com/categories) *Please choose only one:
RWA

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/m0 exports TVL: 
        
 
 
    ethereum                  53.00 M
    
    total                    53.00 M

**Comment by g1nt0ki** [comment]
lets wait till we get some more clarity on the mint process

**Comment by 0xpeluche** [comment]
I just confirmed with the team, for the m0 collateral, everything seems correct. We cannot retrieve the ISINs of the RWAs directly on-chain, but the collateral we obtain corresponds to the collateral provided by the institution to guarantee the m0 peg

**Comment by llamatester** [comment]
The adapter at projects/m0 exports TVL: 
        
 
 
    ethereum                  54.48 M
    
    total                    54.48 M

**Comment by g1nt0ki** [comment]
my guess is, minter activated would have fewer log events, hence the change.

**Pull request merged**
