### PR TITLE
add increment liquid staking

### PR DESCRIPTION
**Pull request by swordc**
##### Name (to be shown on DefiLlama):
Increment Liquid Staking
(Please help merge this sub-project into **Increment Finance** with both **Increment Swap** and **Increment Lending** in the website)

##### Twitter Link:
https://twitter.com/IncrementFi

##### List of audit links if any:
https://docs.increment.fi/protocols/liquid-staking/audits
Under auditing, we will upload the report in this website.
Please add link in the website first.

##### Website Link:
https://app.increment.fi/staking

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
image

##### Current TVL:
------ TVL ------
flow                      136.01 k
total                    136.01 k 

##### Chain:
Flow

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

##### Short Description (to be shown on DefiLlama):
Liquid Staking Protocol on Flow

##### Token address and ticker if any:
N/A

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Liquid Staking

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
N/A

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
Counting the flow tokens staked by users in the protocol, and tokens locked by unstaking are not counted.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/increment-liquidStaking exports TVL: 
        
 
 
    flow                      135.63 k
    
    total                    135.63 k

**Comment by g1nt0ki** [comment]
hi @swordc thanks for the PR, is there a way to query this via a rest api call to flow chain?

**Comment by g1nt0ki** [comment]
> > hi @swordc thanks for the PR, is there a way to query this via a rest api call to flow chain?
> 
> Hi @g1nt0ki thanks for your prompt reply. Yeah, it has REST api with base64 encoded. Also need to get the token price from the cex. Is there any example?

Sorry, I meant querying this info from the chain instead of your server, this way, there is less dependency, we could always change the blockchain endpoint to query but hard if your service goes down or puts up a firewall

**Comment by g1nt0ki** [comment]
Ah, I see there are other protocols from your team that are using fetch from your server as well, ideally I would like to replace them with blockchain data at some point soon

**Comment by llamatester** [comment]
The adapter at projects/increment-liquidStaking exports TVL: 
        
 
 
    flow                      137.40 k
    
    total                    137.40 k

**Comment by llamatester** [comment]
The adapter at projects/increment-liquidStaking exports TVL: 
        
 
 
    flow                      138.26 k
    
    total                    138.26 k

**Comment by swordc** [comment]
> > > Ah, I see there are other protocols from your team that are using fetch from your server as well, ideally I would like to replace them with blockchain data at some point soon
> > 
> > 
> > I have pushed a on-chain version to query liquid staking tvl. Please help check.
> > In addition, because the tvl calculations of dex and lending are complex and rely on many price oracles off-chain, we will have plans to modify in the future.
> 
> I understand, thanks for changing this to be on chain

Is tvl quoted in usd?

**Comment by g1nt0ki** [comment]
yeah, `flow` is the coingecko id for flow token, so system automatically fetches the price from gecko

**Pull request merged**
