### PR TITLE
Aptos: Added Aries Markets

### PR DESCRIPTION
**Pull request by leofisG**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Aries Markets

##### Twitter Link:
https://twitter.com/AriesMarkets

##### List of audit links if any:
Audit with OtterSec

##### Website Link:
https://ariesmarkets.xyz/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://drive.google.com/drive/folders/1-kRePeVtdVhTLeTvBg9Zn9MkqxFLT-bD

##### Current TVL:
300K

##### Chain:
Aptos

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
Not yet

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
Not yet

##### Short Description (to be shown on DefiLlama):
Aries Markets is a decentralised margin trading protocol on Aptos which allows users to borrow, lend, swap, and trade with margin via an on-chain order book with lightning speed.

##### Token address and ticker if any:
N/A

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Switchboard and Pyth

##### forked from (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated):
Counting the number of tokens that is in the protocols.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/aries-markets exports TVL: 
        
 
 
    aptos                     317.14 k
    
    total                    317.14 k

**Comment by g1nt0ki** [comment]
@weixiang9972 thanks for the PR, can you verify if I computed borrowed tvl correctly here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/4470

**Comment by weixiang9972** [comment]
@g1nt0ki The result is correct. Thank you!

**Comment by Define101** [comment]
Hello thanks for the information
Once you guys have an audit link could you guys please inform us?

**Pull request merged**
