### PR TITLE
Add MantaDAO Adapter

### PR DESCRIPTION
**Pull request by MikeR808**
---
##### Logo (High resolution, will be shown with rounded borders):  

Logo

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): mantadao
 (https://api.coingecko.com/api/v3/coins/list)

##### Short Description (to be shown on DefiLlama): MantaDAO is a decentralized autonomous organization focusing on building unique DeFi solutions on the Kujira blockchain.

MantaDAOs flagship product is MantaSwap which provides a multi-hop router for the Kujira FIN orderbook allowing for best trade execution and routing on any-to-any swaps.

As a DAO, Manta focuses on obtaining liquidity for the Kujira ecosystem through protocol owned liquidity held within its treasury.

##### Token address and ticker if any:  
Denom: factory/kujira1643jxg8wasy5cfcn7xm8rd742yeazcksqlg4d7/umnta
Ticker: MNTA

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/mantadao exports TVL: 
        
 
 
    kujira                    886.36 k
    
    total                    886.36 k

**Comment by llamatester** [comment]
The adapter at projects/mantadao exports TVL: 
        
 
 
    kujira                    886.33 k
    
    total                    886.33 k

**Comment by g1nt0ki** [comment]
hi @MikeR808 we can add it but under treasury if that is fine, also can you split the tvl between ownTokens and other tokens? the listing would look something similar to https://defillama.com/protocol/arbitrum-dao#treasury

does that sound good?

**Comment by MikeR808** [comment]
That sounds absolutely fine! Will refine the adapter and try report as treasury & with ownTokens value.

**Comment by llamatester** [comment]
The adapter at projects/treasury/mantadao.js exports TVL: 
        
 
 
    kujira-ownTokens          1.70 M
    kujira                    632.36 k
    ownTokens                 1.70 M
    
    total                    632.36 k

**Pull request merged**
