### PR TITLE
Stargaze Adapter - Updated for bids

### PR DESCRIPTION
**Pull request by effofxprime**
This PR needs to reference the prior submission:  https://github.com/DefiLlama/DefiLlama-Adapters/pull/4423

An API call was recently made available to query the amount of $STARS locked in NFT bids.
I have updated the adapter to not be a fetch adapter.

I am having a problem that I do not understand right now.  Currently, I have console.log for debugging.
The issue is that the export is showing a zero value for everything but the return for the tvl function does output the correct data in console.log.

Image of output: 
image

Is there something I might have missed that needs updating like the chains.json did?  I couldn't test without first updating that.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/stargaze exports TVL: 
        
 
 
    stars                     0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/stargaze exports TVL: 
        
 
 
    stars                     0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/stargaze exports TVL: 
        
 
 
    stars                     0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/stargaze exports TVL: 
        
 
 
    stars                     12.88 k
    
    total                    12.88 k

**Comment by llamatester** [comment]
The adapter at projects/stargaze exports TVL: 
        
 
 
    stars                     12.88 k
    
    total                    12.88 k

**Comment by effofxprime** [comment]
I was able to resolve the issue and it's now reporting properly.

**Comment by llamatester** [comment]
The adapter at projects/stargaze exports TVL: 
        
 
 
    stars                     12.78 k
    
    total                    12.78 k

**Comment by llamatester** [comment]
The adapter at projects/stargaze exports TVL: 
        
 
 
    stargaze                  0
    
    total                    0

**Review by g1nt0ki — APPROVED** [review]

**Comment by effofxprime** [comment]
> sorry for late reply, I have now added the mapping serverside: [DefiLlama/defillama-server@7a62dc7](https://github.com/DefiLlama/defillama-server/commit/7a62dc786da2769df3fc33f2d488f03d00f288f4) and refactored your code. pricing api takes a while to update after that tvl value will be correct. I will merge this PR once pricing api works for ustars.

No worries, and thank you.  Sorry it was so convoluted, I just like making notes for myself.  Quick question though.  Why do we need to convert it back to ustars?  The way it's represented is ##ustars/10^6, but this API query has already done that for us.  I noticed all the other adapters were converting their utoken to token.

**Comment by g1nt0ki** [comment]
I should update other adapters at some point as well, trying to standardize balances object, now key must always be chain:address and value is balance including decimals,  now key for your export is 'stargaze:ustars' instead of the coingecko id, this gives us bit of flexibility like using different pricing source/symbol from coingecko also, less confusing for users when they read it (or that is the hope)

**Comment by 0xngmi** [comment]
@effofxprime there was a large jump in TVL (over 10x) recently, you can see it in the chart at https://defillama.com/protocol/stargaze

Could you confirm whether this jump is correct?

**Comment by effofxprime** [comment]
Hello @oxngmi, the person who is behind the API is currently traveling, and will be replying later tonight.
image

Please let me know if this will be an issue OR if we need to redo how this data is pulled so it can be separated if it is required.

**Comment by calvingrant** [comment]
Hi @0xngmi, Calvin from Stargaze here. Our marketplace contract was recently updated to a new version, and now escrows NFTs that are for sale. The jump you're seeing is due to the value of the NFTs locked in the marketplace contract. As more NFT collections on our marketplace migrate to the new contract over the coming weeks, we expect that number to rise even more.

**Comment by g1nt0ki** [comment]
hi @calvingrant sorry, can you provide data without those NFT value included? we do not include NFT value in other similar protocols. 

We will remove the new data for now.

**Comment by g1nt0ki** [comment]
my answer to similar question by a sol project https://github.com/DefiLlama/DefiLlama-Adapters/pull/9721#issuecomment-2044478625

**Comment by calvingrant** [comment]
Understood, hopefully we can find a way to include the escrowed TVL in the future. I've reverted the changes on my end, so you can go back to fetching live data. Thanks @g1nt0ki.

**Comment by g1nt0ki** [comment]
reverted my change: https://github.com/DefiLlama/DefiLlama-Adapters/commit/6fb57b939b7cfc9e86a6006f82a60294dfbc2907

**Pull request merged**
