### PR TITLE
Update Sommelier Project: Add 4 new Cellars to TVL

### PR DESCRIPTION
**Pull request by sandbochs**
We recently launched 4 new Cellars built on a new Cellar Version and would like to count them in our Project's TVL.

Each Cellar version has a file and ABI now. The current versions are:
- v0.8.15
- v0.8.16

More to come soon.

Changes:
- Rename aave cellar abi to version
- Move Aave cellar logic into v0.8.15 file
- Add v0.8.16 file to fetch TVL for the 4 new cellars built on that version
- index.js is now just configuration and calling the respective versions tvl function

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/sommelier exports TVL: 
        
 
 
    ethereum                  1.63 M
    
    total                    1.63 M

**Comment by llamatester** [comment]
The adapter at projects/sommelier exports TVL: 
        
 
 
    ethereum                  1.41 M
    
    total                    1.41 M

**Comment by sandbochs** [comment]
In the future, is it kosher to fetch a list of subgraphs from The Graph?

**Comment by g1nt0ki** [comment]
> In the future, is it kosher to fetch a list of subgraphs from The Graph?

thanks for the PR
I dislike subgraphs a bit, half my problems (broken adapters) now are because graph stopped indexing for one reason or another. But I see your point as well, tedious to make PRs everytime there is a new cellar, yes, so using graph api here is good

**Pull request merged**
