### PR TITLE
Add BridgeMutual

### PR DESCRIPTION
**Pull request by solenemep**
##### Twitter Link:
https://twitter.com/Bridge_Mutual

##### List of audit links if any:
https://uploads-ssl.webflow.com/5fac3e348dbd5932a7578690/616041cce2de9c01879bb6f4_bridge%20map.pdf
https://consensys.net/diligence/audits/2021/03/bridge-mutual/
https://uploads-ssl.webflow.com/5fac3e348dbd5932a7578690/611fd32331602b4758b9897a_token_metrics%20(1).pdf
https://uploads-ssl.webflow.com/5fac3e348dbd5932a7578690/60da267d76850e5acfe4e4c2_Bridge%20Mutual%20SC%20Audit_%20ZOkyo.pdf

##### Website Link:
https://www.bridgemutual.io/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://files.slack.com/files-pri/T01JL4SBTDW-F02K3HZ221Z/bridge_logo__1_.png
https://files.slack.com/files-pri/T01JL4SBTDW-F02K5PX0Q12/bridge_logo_png.png
https://files.slack.com/files-pri/T01JL4SBTDW-F02KG623HPT/b_transparent.png

##### Current TVL:
TVL = 15.71 M
Staking = 5.84 M

##### Chain:
Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
{"id":"bridge-mutual","symbol":"bmi","name":"Bridge Mutual"}

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
{"id":8364,"name":"Bridge Mutual","symbol":"BMI"}

##### Short Description (to be shown on DefiLlama):
Protect all your crypto assets and earn profits in exchange for coverage liquidity.

##### Token address and ticker if any:
0x725c263e32c72ddc3a19bea12c5a0479a81ee688

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Insurance

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is calculated on the base of quantity of USDT in protocol. That includes USDT from selling policy, and USDT from providing coverage.
Staking is calculated on the base of quantity of BMI staked in protocol. BMI is the governance token used to vote for policy's legitimacy. It can be staked inside protocol.

### CODE REVIEW

**Comment by 0xngmi** [comment]
can this be merged?

**Comment by solenemep** [comment]
@0xngmi Yes it can be merged. Please not that we are going to bring some update in approximately 14 days.

**Comment by 0xngmi** [comment]
got it, wasn't sure because of the title

**Comment by solenemep** [comment]
Hi @0xngmi, do you have an idea when this PR will be merged ? Thank you

**Review by waynebruce0x — APPROVED** [review]

**Comment by solenemep** [comment]
Hi @waynebruce0x I see that the PR has been merged but I cannot see BridgeMutual on website. Is there a delay ? Is there something left to do ? Thanks

**Comment by 0xngmi** [comment]
https://defillama.com/protocol/bridge-mutual

**Comment by solenemep** [comment]
@0xngmi @waynebruce0x 
Hi, thank you ! 
I had a higher result while testing
Screenshot 2021-10-26 at 13 55 37
Is there an explaination why ?

**Pull request merged**
