### PR TITLE
Add Kinesis to Defi Llama

### PR DESCRIPTION
**Pull request by 0xfuzzylogic**
##### Twitter Link:
https://twitter.com/KinesisLabs

##### Website Link:
https://www.kinesislabs.co/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://ibb.co/vVwHmV3

##### Current TVL:
318.40 k

##### Chain:
evmos

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

##### Short Description (to be shown on DefiLlama):
Kinesis Labs is the native stableswap on Evmos that is designed to become the stablecoin hub for all of Cosmos through low slippage and a unique multi-bridge base pool system.

##### Token address and ticker if any:
N/A

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
N/A

##### forkedFrom (Does your project originate from another project):
Saddle Finance

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is being calculated from all assets in our base pools. To accomplish this, I added celer bridged USDC and USDT as well as canonical FRAX to poolTokens.js.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/kinesis exports TVL: 
        
 
 
    evmos                     318.46 k
    
    total                    318.46 k

**Comment by waynebruce0x** [comment]
Is this a fork of anything?

**Comment by 0xfuzzylogic** [comment]
> The adapter at projects/kinesis exports TVL:
> 
> ```
> evmos                     318.46 k
> 
> total                    318.46 k 
> ```

Yes, this is as intended. Is there a fix needed?

**Comment by 0xfuzzylogic** [comment]
> Is this a fork of anything?

Yep, Saddle Finance

**Pull request merged**
