### PR TITLE
[test] Shiden staking

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/astar-dapps-staking/index.js exports TVL: 
        
 
 
    polkadot                  399.37 M
    
    total                    399.37 M

**Comment by llamatester** [comment]
The adapter at projects/genshiro/index.js exports TVL: 
        
 
 
    polkadot                  3.58 M
    
    total                    3.58 M

**Comment by llamatester** [comment]
The adapter at projects/karura-dex/index.js exports TVL: 
        
 
 
    kusuma                    11.23 M
    
    total                    11.23 M

**Comment by llamatester** [comment]
The adapter at projects/karura-lending/index.js exports TVL: 
        
 
 
    kusuma                    15.71 M
    
    total                    15.71 M

**Comment by llamatester** [comment]
The adapter at projects/karura-staking/index.js exports TVL: 
        
 
 
    kusuma                    12.91 M
    
    total                    12.91 M

**Comment by llamatester** [comment]
The adapter at projects/lightning-network/index.js exports TVL: 
        
 
 
    bitcoin                   158.32 M
    
    total                    158.32 M

**Comment by llamatester** [comment]
The adapter at projects/shiden-dapps-staking/index.js exports TVL: 
        
 
 
    shiden                    11.32 M
    
    total                    11.32 M

**Comment by llamatester** [comment]
The adapter at projects/astar-dapps-staking/index.js exports TVL: 
        
 
 
    polkadot                  399.37 M
    
    total                    399.37 M

**Comment by llamatester** [comment]
The adapter at projects/genshiro/index.js exports TVL: 
        
 
 
    polkadot                  3.58 M
    
    total                    3.58 M

**Comment by llamatester** [comment]
The adapter at projects/karura-dex/index.js exports TVL: 
        
 
 
    kusuma                    11.23 M
    
    total                    11.23 M

**Comment by llamatester** [comment]
The adapter at projects/karura-lending/index.js exports TVL: 
        
 
 
    kusuma                    15.71 M
    
    total                    15.71 M

**Comment by llamatester** [comment]
The adapter at projects/karura-staking/index.js exports TVL: 
        
 
 
    kusuma                    12.91 M
    
    total                    12.91 M

**Comment by llamatester** [comment]
The adapter at projects/lightning-network/index.js exports TVL: 
        
 
 
    bitcoin                   158.32 M
    
    total                    158.32 M

**Comment by llamatester** [comment]
The adapter at projects/shiden-dapps-staking/index.js exports TVL: 
        
 
 
    shiden                    11.32 M
    
    total                    11.32 M

**Comment by g1nt0ki** [comment]
closing this, real PR: https://github.com/DefiLlama/DefiLlama-Adapters/pull/2068

**Pull request closed without merging**
