### PR TITLE
Add CardanceSwap DEX

### PR DESCRIPTION
**Pull request by santoraphael**
The token address and contract addresses might still change. The DEX will be released soon.

##### Twitter Link:
https://twitter.com/CardanceSwap

##### Website Link:
https://cardance.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
logo_cardanceswap

##### Current TVL:
TVL is based on the amount of ADA + amount of Tokens (converted to ADA) that are in Cardance's wallets.
"value": 2758798.004677 ADA

##### Chain:
Cardano

##### Short Description (to be shown on DefiLlama):
Cardance Swap tokens has never been so easy!

##### Token address and ticker if any:
https://cardanoscan.io/token/0fdaa1b8699080ed281faec8dfae54531d07f37fe9a4bdd8f0733e2e44414e4345

**DANCE**

##### Category (full list at https://defillama.com/categories) *Please choose only one:

1. Dexes

##### forkedFrom (Does your project originate from another project):

Cardance is an original project that aims to solve the problem that people who have never had contact with cryptocurrencies have in starting to use them. We want to make it as easy as possible for beginners.

##### methodology (what is being counted as tvl, how is tvl being calculated):
The TVL is calculated based on the value in ADA and tokens that are deposited in DEX. The token value is calculated by obtaining the average market price (considering other Cardance dex), this methodology will be maintained even when Cardance starts its token exchange operations and buy and sell orders.

### CODE REVIEW

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
hi @santoraphael , cardanceswap folder needs to placed under `projects` folder.

Also, can you fetch the tokens via calls to cardano instead of api call to your server, also I am bit confused, your dex is not released but you have a tvl over 1M?

**Comment by santoraphael** [comment]
Hello, how are you?

We made the account based on the DANCE token that is being sold in other DEX and has a unit value that is calculated in the return, if it is the problem we can review this calculation, quietly.

About the TVL coming from an internal URL, we only did it because it would be easier for us to update it if new wallets appear, we can make the call directly from the blockchain (in this case we wouldn't calculate the value of the tokens deposited in our wallet), and only the value in ADA would be considered.

If this is correct, that's fine.

We analyze other projects before creating our service to make it as consistent as possible.

I will send you an update.

**Comment by llamatester** [comment]
The adapter at projects/CardanceSwap exports TVL: 
        
 
 
    cardano                   1.29 M
    
    total                    1.29 M

**Comment by g1nt0ki** [comment]
@santoraphael sorry, I am bit lost. what do you mean by "We made the account based on the DANCE token that is being sold in other DEX and has a unit value that is calculated in the return"

Is there some sort of dex activity in contracts cardanceSwap owns?

**Pull request closed without merging**
