### PR TITLE
added fringe to DeFi Llama

### PR DESCRIPTION
**Pull request by coreycaplan3**
##### Twitter Link:
https://twitter.com/fringefinance

##### List of audit links if any:
https://github.com/HashEx/public_audits/blob/master/Fringe%20Finance/Fringe%20Finance.pdf

##### Website Link:
https://fringe.fi/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://d1fdloi71mui9q.cloudfront.net/MGdS5FKxT1mKvXFTRgSq_EGEicdODOa7Q2fJT

##### Current TVL:
$72,300

##### Chain:
Ethereum Mainnet

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
fringe-finance

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
slug=`fringe-finance` id=`17456 `

##### Short Description (to be shown on DefiLlama):
A safe place for you to invest and borrow against your holdings. Fast, easily and on your own terms.

##### Token address and ticker if any:
0xC9fE6E1C76210bE83DC1B5b20ec7FD010B0b1D15 `FRIN`

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
Gets the value of all tokens locked in Fringe Finance's Primary Lending Platform

### CODE REVIEW

**Comment by g1nt0ki** [comment]
hi, can you please revert the change to package-lock file

**Comment by llamatester** [comment]
The adapter at projects/fringe exports TVL: 
        
 
 
    ethereum                  49.74 k
    
    total                    49.74 k

**Comment by llamatester** [comment]
The adapter at projects/fringe exports TVL: 
        
 
 
    ethereum                  47.83 k
    
    total                    47.83 k

**Comment by llamatester** [comment]
The adapter at projects/fringe exports TVL: 
        
 
 
    ethereum                  47.83 k
    
    total                    47.83 k

**Comment by llamatester** [comment]
The adapter at projects/fatex exports TVL: 
        
 
 
    polygon-staking           48.935085
    polygon                   31.83 k
    staking                   48.935085
    
    total                    31.83 k

**Comment by llamatester** [comment]
The adapter at projects/fringe exports TVL: 
        
 
 
    ethereum                  47.83 k
    
    total                    47.83 k

**Comment by llamatester** [comment]
The adapter at projects/fatex exports TVL: 
        
 
 
    polygon-staking           48.935085
    polygon                   31.83 k
    staking                   48.935085
    
    total                    31.83 k

**Comment by g1nt0ki** [comment]
@coreycaplan3 can you rebase code and put up new PR? looks like lot of unrelated code are changed

**Pull request closed without merging**
