### PR TITLE
Adapter for Staking

### PR DESCRIPTION
**Pull request by heraaggregator**
**NOTE**

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@heraaggregator can you please fill the listing form in the PR description field

**Comment by llamatester** [comment]
The adapter at projects/herafinance exports TVL: 
        
 
 
    metis                     0
    metis-staking             441.42 k
    staking                   441.42 k
    
    total                    0

**Comment by heraaggregator** [comment]
Already PR'd, please check #1314 and #1315

**Comment by g1nt0ki** [comment]
> Already PR'd, please check #1314 and #1315

Not sure why you are referring to those PRs, I am just asking for project details to be listed

**Comment by heraaggregator** [comment]
Sorry, thats my mistake. 
Project Logo PR: [(https://github.com/DefiLlama/defillama-server/pull/1314)]
Project Details PR: [https://github.com/DefiLlama/defillama-server/pull/1315]

**Comment by g1nt0ki** [comment]
> Sorry, thats my mistake. Project Logo PR: [(https://github.com/[DefiLlama/defillama-server/pull/1314](https://github.com/DefiLlama/defillama-server/pull/1314))] Project Details PR: [https://github.com/[DefiLlama/defillama-server/pull/1315](https://github.com/DefiLlama/defillama-server/pull/1315)]

my fault as well for being too hasty, it should appear in the UI in 1-2 hours

**Pull request merged**
