### PR TITLE
Eklipse finance fix

### PR DESCRIPTION
**Pull request by eklipse-finance**
### **Twitter Link:**
https://twitter.com/eklipseFinance

### **Website Link:**
https://eklipse.finance

### **Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):**
Blue

### **Current TVL:**
$46876729.41 USD

### **Chain:**
Klaytn

### **Coingecko ID (so your TVL can appear on Coingecko):**
X

### **Coinmarketcap ID (so your TVL can appear on Coinmarketcap):**
X

### **Short Description (to be shown on DefiLlama):**
Eklipse is the first stable swap in the Klaytn ecosystem.  It is issued being inspired by https://curve.fi/
It is a decentralized exchange (DEX) that minimizes unnecessary losses from swaps  between identical assets.

### **Token address and ticker if any:**
EKL : 0x807c4e063eb0ac21e8eef7623a6ed50a8ede58ca

### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Dexes

### **Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):**
No

### **forkedFrom (Does your project originate from another project):**
- https://curve.fi/
- https://dopple.finance/

### **methodology (what is being counted as tvl, how is tvl being calculated):**
- Swap pool
- Gauge
- Farm
- EKL locked

### CODE REVIEW

**Comment by g1nt0ki** [comment]
Hi again, this PR has merge conflict.

Eklipse finance is was merged yesterday and is listed now: https://defillama.com/protocol/eklipse-finance 

Do you have any issues with how the tvl is computed now?

**Comment by g1nt0ki** [comment]
> Hi, thank you for replying. I think two calculations are excepted:
> 
>     * calculation for farm in which swap pool LP Token is locked
> 
>     * calculation for 3moon LP Token in swap pools

Wouldnt that be double counting? I am already counting all the stablecoins in the pools

**Comment by Kane-Baekdu** [comment]
Actually I wanted below scenario (mayby I misunderstood something):
In defillama, there are the option that enable to show tvl which is added double counting by switching the toggle on. If a user take the switch on, above calculations will be added to tvl of our protocol.

But I’m confused what double counting toggle do. In a specific protocol page in defillama, any changes not happend even if switching double counting on. On the other hand, in a overview page when I take double counting off, tvl of some protocols are excepted

What does double counting switch do?

**Comment by eklipse-finance** [comment]
Actually I wanted below scenario (mayby I misunderstood something):
In defillama, there are the option that enable to show tvl which is added double counting by switching the toggle on. If a user take the switch on, above calculations will be added to tvl of our protocol.

But I’m confused what double counting toggle do. In a specific protocol page in defillama, any changes not happend even if switching double counting on. On the other hand, in a overview page when I take double counting off, tvl of some protocols are excepted

What does double counting switch do?

**Comment by g1nt0ki** [comment]
> I wanted below scenario (mayby I misunderstood something): In defillama, there are the option that enable to show tvl which is added double counting by switching the toggle on. If a user take the switch on, above calculations will be added to tvl of our protocol.
> 
> But I’m confused what double counting toggle do. In a specific protocol page in defillama, any changes not happend even if switching double counting on. On the other hand, in a overview page when I take double counting off, tvl of some protocols are excepted
> 
> What does double counting switch do?

doublecounted toggle is for protocols providing yields, etc. Example: if some protocol uses your 3moon token to give yield, it would show up in their tvl but not overall chain tvl, because we are already counting 3moon value in your protocol

Also, we cant count 3moon tokens in your protocol because we are already adding up the value of underlying tokens to tvl, more info: https://docs.llama.fi/list-your-project/defillama-and-our-methodology#our-methodology

**Comment by eklipse-finance** [comment]
OK. I understand it.
Lastly, could you change our logo to above one?

**Pull request closed without merging**
