### PR TITLE
Subzero adapter

### PR DESCRIPTION
**Pull request by mkrman**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): 

sub

sub-th-border-200x200

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/subzero-plus exports TVL: 
        
 
 
    avax                      0
    avax-staking              0
    avax-pool2                31.63 k
    staking                   0
    pool2                     31.63 k
    
    total                    0

**Comment by mkrman** [comment]
That's the AVAX-only TVL, but I think that's okay. Thanks...

**Comment by llamatester** [comment]
The adapter at projects/subzero-plus exports TVL: 
        
 
 
    avax                      0
    avax-pool2                31.92 k
    avax-staking              0
    pool2                     31.92 k
    staking                   0
    
    total                    0

**Comment by mkrman** [comment]
Just had to change a token address sorry... it doesn't really affect the output though.

**Comment by llamatester** [comment]
The adapter at projects/subzero-plus exports TVL: 
        
 
 
    avax                      0
    avax-pool2                101.05 k
    avax-staking              2.51 k
    pool2                     101.05 k
    staking                   2.51 k
    
    total                    0

**Comment by mkrman** [comment]
Hi, sorry I didn't realize you would add our DEX contracts as well, but thank you! Can you please add this logo on the ZSwap listing? It's this one, the others are fine: https://defillama.com/protocol/subzero-zswap

Where it says "Subzero ZSwap" it could just be "ZSwap" if that's alright, on that one, but having both under the Subzero+ brand is good. Thank you! ❤️ 

logo

logo

**Comment by g1nt0ki** [comment]
@Define101 can you take care of this?

**Comment by Define101** [comment]
Thanks for letting us know.
Changes have been made and should reflect within 1 hour

**Comment by mkrman** [comment]
> Thanks for letting us know. Changes have been made and should reflect within 1 hour

Okay thank you 🙏 I will keep an eye out. I appreciate it!

**Pull request merged**
