### PR TITLE
Add ExinPool

### PR DESCRIPTION
**Pull request by dbarobin**
##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

ExinPool-GitHub

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Does ExinPool have a dapp we can look at? I cant seem to work exinpool.com

**Comment by dbarobin** [comment]
URL: https://mixin.exinpool.com

However, you need Mixin Messenger to authorize access, download at: https://mixin.one/messenger

**Comment by waynebruce0x** [comment]
I havent got mixin - can you tell me whats included in this TVL?

**Comment by dbarobin** [comment]
ExinPool is a staking platform. The TVL data of ExinPool is derived from the current market value of all running node lock positions.

**Comment by waynebruce0x** [comment]
We don't count PoS staking as TVL unless its liquid staking like lido. We don't count most atom, eth2.0, polkadot crowdloan etc staking

**Pull request closed without merging**
