### PR TITLE
Add contracts and hallmarks to BetSwirl

### PR DESCRIPTION
**Pull request by RomualdH**
Hey team!

Making some updates on the BetSwirl adapter...

- New contracts to track: As BetSwirl's Bank contract is immutable, we're deploying new Bank contract for new features. Hence the update on the `banks` list.
- When a new Bank contract is deployed, not all funds (bankrolls) are migrated to the new one. Hence the update from line 31 to 49.
- We've added hallmarks to show when deposit happened on the Bank.

Best regards,
Romuald

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/betswirl exports TVL: 
        
 
 
    bsc                       0
    avax-treasury             139.92 k
    polygon-treasury          101.01 k
    bsc-treasury              118.20 k
    treasury                  359.13 k
    
    total                    0

**Comment by 0xngmi** [comment]
if we are just tracking treasury would be best to move to treasury adapters

**Comment by RomualdH** [comment]
> if we are just tracking treasury would be best to move to treasury adapters

When building this adapter, I was told that treasury is best suited for our bankrolls.

**Comment by g1nt0ki** [comment]
@RomualdH sorry, that was before we had separate adapter/dashboard for treasury, I have updated that adapter instead: https://github.com/DefiLlama/DefiLlama-Adapters/commit/94de66326553459009fa362a879058dcd07f683f

**Pull request closed without merging**
