### PR TITLE
Update Equilibrium website comments

### PR DESCRIPTION
**Pull request by DenisCarriere**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/equilibrium exports TVL: 
        
 
 
    eos                       2.25 M
    
    total                    2.25 M

**Comment by DenisCarriere** [comment]
Correct, the output is about:
```
--- eos ---
eos                       2.19 M
ptokens-btc               48.55 k
Total: 2.24 M 

--- tvl ---
eos                       2.19 M
ptokens-btc               48.55 k
Total: 2.24 M 

------ TVL ------
eos                       2.24 M

total                    2.24 M 
```

**Comment by DenisCarriere** [comment]
also matching their reports on their site https://eosdt.com/en

`798,406.85 + 1,397,334.19 = 2,195,741.04`

image


image

**Comment by g1nt0ki** [comment]
@DenisCarriere I am bit confused what this PR is about. Also with respect to your comment. I see that you added this adapter, is eos account not taken into account while computing tvl?

> Correct, the test output is:
> 
> ```
> --- eos ---
> eos                       2.19 M
> ptokens-btc               48.55 k
> Total: 2.24 M 
> 
> --- tvl ---
> eos                       2.19 M
> ptokens-btc               48.55 k
> Total: 2.24 M 
> 
> ------ TVL ------
> eos                       2.24 M
> 
> total                    2.24 M 
> ```

**Comment by g1nt0ki** [comment]
test output shown is tvl summary break-down per chain, not per token :)

**Comment by DenisCarriere** [comment]
This PR simply updates the comment section of this adapter, it was mistakenly using "Chintai" when it should of been Equilibrium 

the test output hasn't changed

**Comment by DenisCarriere** [comment]
> test output shown is tvl summary break-down per chain, not per token :)

Just to clarify, EOSDT is a stable token DeFi protocol, not a chain

It only has 2 reported assets on EOS chain (EOS & PBTC)

**Pull request merged**
