### PR TITLE
Updating Glacier v2 tvl metrics

### PR DESCRIPTION
**Pull request by discochuck**
Attempting to take the llama magick 0xngmi provided for our v3
factory and apply it to our v2.

**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/glacier-finance exports TVL: 
        
 
 
    avax-staking              106.27 k
    avax                      0
    staking                   106.27 k
    
    total                    0

**Comment by discochuck** [comment]
That's probably not ideal. 

was hopping this would be a quick copy pasta from the glacier v3 code you provided yesterday. The tvl metrics are super dope, and was hopping to do the same for our original v2 tvl metrics, but obviously this is outside of my skill set. 

I was finally able to spin up a virtualbox nodejs environment that actually works, so I'll keep testing locally.

please hold on merging. 

thank you for all the help!

**Comment by Define101** [comment]
Hello disco what are you trying to do?
The current v2 have this TVL
image

**Comment by discochuck** [comment]
Sorry, the first numbers from llamatester through me off. 

that looks right. 

Should be good to go.

**Comment by g1nt0ki** [comment]
> Sorry, the first numbers from llamatester through me off.
> 
> that looks right.
> 
> Should be good to go.

I think this code is buggy because, there is no 'Pool' event here: https://snowtrace.io/address/0xac7b7eac8310170109301034b8fdb75eca4cc491#events maybe you were looking for 'PairCreated' ? 

also, dont fully understand thre reason behind the code change here, existing code works and gives correct tvl right? you want token breakdown?

**Comment by discochuck** [comment]
I was trying to get the same TVL metrics you can see in the attached img from our v3 stats: 
https://defillama.com/protocol/glacier-exchange-v3

but for our v2 factory:
https://defillama.com/protocol/glacier-exchange-v2

Which does have the correct TVL, but doesn't have all the bells and whistles that are shown in
the attached img.


Screenshot 2023-10-02 073523

**Comment by g1nt0ki** [comment]
ah, you will get the breakdown now: https://github.com/DefiLlama/DefiLlama-Adapters/commit/206acfc54203ca3df7a513788192fb763440a135

**Pull request closed without merging**
