### PR TITLE
add MultiSwap TVL first version

### PR DESCRIPTION
**Pull request by oleksiivinogradov**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI

---

##### Twitter Link:

https://twitter.com/openbisea

##### Website Link:

https://openbisea.io

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

https://drive.google.com/open?id=13StMvXFwD2WkcVGeP1QlDATA_YTmECkL&authuser=alex%40callsfreecalls.com&usp=drive_fs

##### Current TVL:

$0.29

##### Chain:

KAVA

##### Short Description (to be shown on DefiLlama):

reinvented DeFi swap with true NFT value

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Dexes

##### forkedFrom (Does your project originate from another project):

Uniswap V3

##### methodology (what is being counted as tvl, how is tvl being calculated):

WETH contract balance

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/MultiSwap: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:219:11

**Comment by g1nt0ki** [comment]
@oleksiivinogradov I am bit confused, you are counting the amount of kava on the contract as tvl, but why? and the contract is called wrapped eth?

**Comment by oleksiivinogradov** [comment]
> @oleksiivinogradov I am bit confused, you are counting the amount of kava on the contract as tvl, but why? and the contract is called wrapped eth?

It's Wrapped KAVA contract, which is used for pairs, which connect with KAVA. The basic idea was to go to all pools and calculate locked WKAVA for each, but the easiest way was just to check the amount of WKAVA on a wrapped KAVA contract.

**Comment by oleksiivinogradov** [comment]
> okay, calling it WETH threw me off, but you still need to count the amount held in pools, not all wrapped kava because users could hold it and not deposit in pools.
> 
> Also, can you verify the code in https://explorer.kava.io/address/0xc13791DA84f43525189456CfE2026C60D3B7F706/transactions

code verification on kava looks like complicated (im using truffle etherscan for verify), I attach same contracts verified on testnet bnb.

**Comment by oleksiivinogradov** [comment]
> okay, calling it WETH threw me off, but you still need to count the amount held in pools, not all wrapped kava because users could hold it and not deposit in pools.
> 

a new code check all pools for WKAVA. But can you clarify TVL methodology? If I have 100 WKAVA and 100 OBS, should I do 200 * $1.81 plus in TVL? Liquidity in paid tokens works too?

**Comment by llamatester** [comment]
The adapter at projects/MultiSwap exports TVL: 
        
 
 
    kava                      0.07531241908524539
    
    total                    0.07531241908524539

**Comment by g1nt0ki** [comment]
@oleksiivinogradov I have refactored your a bit, if you are fine with the changes, I will merge it

**Comment by llamatester** [comment]
The adapter at projects/MultiSwap exports TVL: 
        
 
 
    kava                      0.07531241908524539
    
    total                    0.07531241908524539

**Comment by oleksiivinogradov** [comment]
> @oleksiivinogradov I have refactored your a bit, if you are fine with the changes, I will merge it

I'm fine, please go ahead

**Pull request merged**
