### PR TITLE
add wildbase

### PR DESCRIPTION
**Pull request by legend524**
##### Name (to be shown on DefiLlama):
Wild Base

##### Twitter Link:
https://x.com/lodgecapital

##### Website Link:
https://wildbase.farm

##### Logo (High resolution, will be shown with rounded borders):
https://wildbase.farm/logo.png

##### Current TVL:
$245,199.2 

##### Chain:
Base (ChainId: 8453)

##### Short Description (to be shown on DefiLlama):
Zap into one of the farms to earn WILDx as we prepare a new ecosystem of yield opportunities on BASE. All WILDx sales taxes are burned to reduce inflation and there are no non-native coins for whales to milk. Stay WILD and enjoy the yield! 🤞.

##### Token address and ticker if any:
0xbCDa0bD6Cd83558DFb0EeC9153eD9C9cfa87782E

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield

##### methodology (what is being counted as tvl, how is tvl being calculated):
Uses Uniswap-style factory address to find and price liquidity pairs.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/Lodge-Capital/sum

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/wildbase exports TVL: 
        
 
 
    base                      530.98 k
    
    total                    530.98 k

**Comment by llamatester** [comment]
Error while running adapter at projects/wildbase: 
        
 
  
    
    
    Error: Multicall failed!
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/abi/index.js:286:35

**Comment by llamatester** [comment]
Error while running adapter at projects/wildbase: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by llamatester** [comment]
Error while running adapter at projects/wildbase: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by llamatester** [comment]
The adapter at projects/wildbase exports TVL: 
        
 
 
    base                      27.26 k
    base-staking              27.26 k
    base-pool2                244.98 k
    staking                   27.26 k
    pool2                     244.98 k
    
    total                    27.26 k

**Comment by legend524** [comment]
thanks

**Comment by g1nt0ki** [comment]
@legend524 thanks for the PR

**Comment by llamatester** [comment]
The adapter at projects/wildbase exports TVL: 
        
 
 
    base-pool2                273.94 k
    base-staking              32.35 k
    base                      265.11738495037457
    pool2                     273.94 k
    staking                   32.35 k
    
    total                    265.11738495037457

**Comment by legend524** [comment]
Hi, @g1nt0ki
Please check the code you changed again.
It's not working well  and all values are wrong now.

**Pull request merged**
