### PR TITLE
Algem project

### PR DESCRIPTION
**Pull request by AlgemTeam**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
Algem_Logo_Icon

##### Short Description (to be shown on DefiLlama):
Algem is the native liquid staking DeFi dApp on top of Astar Network offering new ways for ASTR users and holders to earn more.

Algem is developed on two main features offering different solutions for users to stay liquid with their assets (ASTR and other tokens):

--- Liquid staking;

--- Liquid lending.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
6
[Liquid Staking](https://defillama.com/protocols/Liquid%20Staking)

##### methodology (what is being counted as tvl, how is tvl being calculated):

Total ASTR staked via LiquidStaking contract

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/algem exports TVL: 
        
 
 
    astar                     0
    
    total                    0

**Comment by g1nt0ki** [comment]
@AlgemTeam please fill the protocol details in the PR

**Comment by AlgemTeam** [comment]
My bad. Updated.

**Comment by Wevelll** [comment]
> The adapter at projects/algem exports TVL:
> 
> ```
> astar                     0
> 
> total                    0 
> ```

Sorry, can't reproduce:

$ node test.js projects/algem/index.js
--- astar ---
astar                     18.72 k
Total: 18.72 k 

--- tvl ---
astar                     18.72 k
Total: 18.72 k 

------ TVL ------
astar                     18.72 k

total                    18.72 k

**Comment by llamatester** [comment]
The adapter at projects/algem exports TVL: 
        
 
 
    astar                     0
    
    total                    0

**Comment by AlgemTeam** [comment]
> The adapter at projects/algem exports TVL:
> 
> ```
> astar                     0
> 
> total                    0 
> ```



> The adapter at projects/algem exports TVL:
> 
> ```
> astar                     0
> 
> total                    0 
> ```

Somehow test.js in the project root differs. [This](https://gist.github.com/AlgemTeam/137383bb37f6a6f8389ab6c64e04cd44) one works, but there is only one file added with commit

**Comment by g1nt0ki** [comment]
> > The adapter at projects/algem exports TVL:
> > ```
> > astar                     0
> > 
> > total                    0 
> > ```
> 
> > The adapter at projects/algem exports TVL:
> > ```
> > astar                     0
> > 
> > total                    0 
> > ```
> 
> Somehow test.js in the project root differs. [This](https://gist.github.com/AlgemTeam/137383bb37f6a6f8389ab6c64e04cd44) one works, but there is only one file added with commit

it is a bug in the `test.js` file, it is fixed now.

**Pull request merged**
