### PR TITLE
Update convex treasury & tvl adapters

### PR DESCRIPTION
**Pull request by philippe-git**
Updates to convex's treasury and tvl adapters, using only onchain data. Commit messages are self-explanatory for the list of changes made. Please lmk if any of the sdk apis aren't used properly / if something can be improved

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/convex exports TVL: 
        
 
 
    ethereum                  1.22 B
    ethereum-staking          194.06 M
    staking                   194.06 M
    arbitrum                  19.31 M
    polygon                   7.08 M
    fraxtal                   0
    
    total                    1.24 B

**Comment by llamatester** [comment]
The adapter at projects/treasury/convex.js exports TVL: 
        
 
 
    ethereum-ownTokens        31.40 M
    ownTokens                 31.40 M
    ethereum                  5.22 M
    
    total                    5.22 M

**Comment by llamatester** [comment]
The adapter at projects/convex exports TVL: 
        
 
 
    ethereum                  1.22 B
    ethereum-staking          194.71 M
    staking                   194.71 M
    arbitrum                  19.33 M
    polygon                   7.10 M
    fraxtal                   311.36 k
    
    total                    1.24 B

**Comment by llamatester** [comment]
The adapter at projects/treasury/convex.js exports TVL: 
        
 
 
    ethereum-ownTokens        31.51 M
    ownTokens                 31.51 M
    ethereum                  5.25 M
    
    total                    5.25 M

**Comment by g1nt0ki** [comment]
@philippe-git thanks for the update

**Pull request merged**
