### PR TITLE
Add DOVU adapter

### PR DESCRIPTION
**Pull request by justynspooner**
### Name:
DOVU

### Twitter Link:
[@dovuofficial](https://x.com/dovuofficial)

### List of audit links if any:
N/A

### Website Link:
https://dovu.earth

### Logo (High resolution, will be shown with rounded borders):

app-icon-black

### Current TVL:
$4.41 M

### Treasury Addresses (if the protocol has treasury)
0.0.828148
https://hashscan.io/mainnet/account/0.0.828148

### Chain:
Hedera

### Coingecko ID:
`dovu`
https://www.coingecko.com/en/coins/dovu

### Coinmarketcap ID
https://coinmarketcap.com/currencies/dovu-earth/

### Short Description:
Tokenisation infrastructure for the green economy.

### Token address and ticker if any:
0.0.3716059
DOVU

### Category (full list at https://defillama.com/categories) *Please choose only one:
9. [RWA](https://defillama.com/protocols/RWA)

### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Coingecko for exchange rate

### Implementation Details: Briefly describe how the oracle is integrated into your project:
For the exchange rate

### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
https://www.coingecko.com/en/coins/dovu

### forkedFrom (Does your project originate from another project):
N/A

### methodology (what is being counted as tvl, how is tvl being calculated):

The DOVU self custodial staking platform includes any entity that has currently staked tokens and is receiving rewards, tokens can only be staked through the DOVU.market website via an web3 account auth flow.

Users will receive a unique APY based off of their behaviour within the DOVU platform.

TVL is calculated based on the total tokens staked * value in USD.

We use coingecko for the live exchange rate.

### Github org/user
dovuofficial
https://github.com/dovuofficial

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/dovu exports TVL: 
        
 
 
    
    total                    4.41 M

**Comment by g1nt0ki** [comment]
hi, it is hard for us to verify this, can you share contract address on hedera where tokens are staked? also, we track staking under 'staking' key, not tvl

**Comment by llamatester** [comment]
The adapter at projects/dovu exports TVL: 
        
 
 
    hedera-staking            4.39 M
    staking                   4.39 M
    hedera                    0
    
    total                    0

**Comment by g1nt0ki** [comment]
@justynspooner thanks for changing it, but can you share the staking contract address, this way, we will still be compute/show staking value even if the endpoint becomes unreachable

**Comment by justynspooner** [comment]
Thanks @g1nt0ki 

Our staking system doesn't use a smart contract. All staked tokens are held within the stakers' wallets so they always have full custody. The user registers their wallet through our site and then we check their onchain token balance every 12 hours and release staking rewards based on the tokens they hold. The token balances of accounts can be verified throughout any time in history so we can verify how many tokens were held by registered accounts at any point in time.

It wouldn't be hard to verify the figure that our API returns. The only thing that isn't public is the list of accounts that have registered for the DOVU staking platform.

**Comment by g1nt0ki** [comment]
> Thanks @g1nt0ki
> 
> Our staking system doesn't use a smart contract. All staked tokens are held within the stakers' wallets so they always have full custody. The user registers their wallet through our site and then we check their onchain token balance every 12 hours and release staking rewards based on the tokens they hold. The token balances of accounts can be verified throughout any time in history so we can verify how many tokens were held by registered accounts at any point in time.
> 
> It wouldn't be hard to verify the figure that our API returns. The only thing that isn't public is the list of accounts that have registered for the DOVU staking platform.

sorry, if it is not locked in your smart contract, we cant count it as your tvl. Similar example is, people list the same NFT on both opensea and blur for trading, but we dont count it as part of either product's tvl.

**Comment by justynspooner** [comment]
OK, we appreciate where you're coming from on this. We'll close this ticket as the flexibility our current solution provides to our stakers isn't worth the change to them currently. If we move over to a smart contract based solution in the future we'll revisit this adapter. Thanks.

**Pull request closed without merging**
