### PR TITLE
feat(a51-finance): rebrand unipilot to a51-finance

### PR DESCRIPTION
**Pull request by khuzama98**
##### Name (to be shown on DefiLlama):
A51 Finance

##### Twitter Link:
https://twitter.com/A51_Fi

##### List of audit links if any:
v2 - https://github.com/a51finance/unipilot-audits
v3 - https://github.com/a51finance/concentrated-liquidity-tool/blob/main/audits/Hashlock/A51%20Finance%20%20Smart%20Contract%20Audit%20Report%20-%20Revised%20Report%20v2.pdf

##### Website Link:
https://a51.finance/

##### Logo (High resolution, will be shown with rounded borders):
a51

##### Treasury Addresses (if the protocol has treasury)
matic:0x6e1e00ef9303a6a077f855Fb33911d1ff7765246

##### Chain:
same chains for v2, v3 only on arbitrum for now.

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
https://coinmarketcap.com/currencies/a51-finance/

##### Short Description (to be shown on DefiLlama):
A51 Finance is an Autonomous Liquidity Provisioning (ALP) protocol offering customizable tools for creating tailored liquidity strategies empowering LPs with dynamic adjustments based on their preferences.

##### Token address and ticker if any:
address(matic chain): 0xe9E7c09e82328c3107d367f6c617cF9977e63ED0  
ticker: A51

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Liquidity Manager

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/a51finance

NOTE: 
In this PR I have renamed unipilot to A51 Finance V2 and created another folder project for A51 Finance V3, V2 remains same as we have rebranded to A51 so our token also migrated to polygon chain as A51 and new staking is also on polygon.
I would like to represent data in such a format that UI should show 3 tabs 1st tab shows aggregated data of v2, v3 and staking, 2nd tab shows v2 data and 3rd tab shows v3 data.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/a51-finance-v3 exports TVL: 
        
 
 
    arbitrum                  646.2599857318476
    
    total                    646.2599857318476

**Comment by g1nt0ki** [comment]
@khuzama98 thanks for the PR, refactored and included your changes here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/b7d90271c4a3f451ed73bb152f0f955cfb280920

no need to rename folder to change name in front-end, we will take care of it

**Comment by khuzama98** [comment]
@g1nt0ki here it shows $0 in staking even though staking has tvl (shown in the picture below),

image
image

**Comment by g1nt0ki** [comment]
the issue is, your token is not in coingecko where we pull token prices from

**Pull request closed without merging**
