### PR TITLE
add ggpVault

### PR DESCRIPTION
**Pull request by Bookcliff**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
GGP Vault

##### Twitter Link:
N/A

##### List of audit links if any:
https://docs.seafi.app/overview/security

##### Website Link:
https://seafi.app/

##### Logo (High resolution, will be shown with rounded borders):
https://raw.githubusercontent.com/SeaFi-Labs/GGP-Vault-Landing/main/public/favicon.webp?token=GHSAT0AAAAAACN4QDIM5B7LGX3755EX5UEAZOT7ZWQ

##### Current TVL:
$84450.3

##### Treasury Addresses (if the protocol has treasury)
N/A

##### Chain:
Avalanche

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

##### Short Description (to be shown on DefiLlama):
GGP Vault is a protocol that allows you to earn yield on your idle GGP.  

##### Token address and ticker if any:
N/A

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
N/A

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
Sum of the GGP tokens deposited within the vault.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/SeaFi-Labs

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/ggpVault exports TVL: 
        
 
 
    avax                      72.62 k
    
    total                    72.62 k

**Comment by g1nt0ki** [comment]
@Bookcliff thanks for the PR

**Comment by Define101** [comment]
@Bookcliff twitter link? Is this from the same team of OrcaDAO ?

**Comment by Bookcliff** [comment]
> twitter link? Is this from the same team of OrcaDAO ?

Sorry for the delayed response - we don't have a twitter account set up at this time. Nope we're not with OrcaDAO.

Thanks for merging! Appreciate y'alls work

**Pull request merged**
