### PR TITLE
add sakeperp

### PR DESCRIPTION
**Pull request by beichenzhidi**
##### Twitter Link:
https://twitter.com/Sake_Perp_Swap

##### List of audit links if any:
https://sakeperp.fi/audit-report/Smart-Contract-Security-Audit-Report-SakePerp-Protocol-EN.pdf

##### Website Link:
https://www.sakeperp.fi/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://www.sakeperp.fi/_next/image?url=%2Fassets%2Flogo.svg&w=128&q=75

##### Current TVL:
$12,009,709

##### Chain:
BSC

##### Description/bio (to be shown on DefiLlama):
SAKE is a transaction-driven decentralized perpetual contract and spot trading protocol. SakePerp.fi is the first on-chain perpetual contract platform with a dynamic AMM  market maker mechanism that supports single asset collateralization for liquidity providers. 

##### Token address and ticker if any:
https://bscscan.com/address/0x8bd778b12b15416359a227f0533ce2d91844e1ed

### CODE REVIEW

**Comment by 0xngmi** [comment]
Given that all the queries are almost the same, wouldn't it be easier to just merge them into a single one?

**Comment by 0xngmi** [comment]
> chain: bsc

Isn't it on ethereum?

**Comment by 0xngmi** [comment]
I've gone ahead and have written a much shorter adapter for it, you can check it out on https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/sakeperp/index.js

**Comment by beichenzhidi** [comment]
> I've gone ahead and have written a much shorter adapter for it, you can check it out on https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/sakeperp/index.js

Okay, has it been updated to https://defillama.com/home? Why can't I find the information now?

**Comment by beichenzhidi** [comment]
> > chain: bsc
> 
> Isn't it on ethereum?

It is also deployed on ethereum

**Comment by 0xngmi** [comment]
> has it been updated to https://defillama.com/home?

Some updates need to be made to another repo, it should go live later today, cc @realdealshaman

**Comment by 0xngmi** [comment]
> It is also deployed on ethereum
The subgraph you used on this PR seems to be for ethereum, what subgraphs should we use for the other chains?

**Comment by 0xngmi** [comment]
Closing since this has already been live for some days

**Pull request closed without merging**
