### PR TITLE
Add PumpBTC adapter

### PR DESCRIPTION
**Pull request by DeKaiju**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
PumpBTC

##### Twitter Link:
https://x.com/Pumpbtcxyz

##### List of audit links if any:
https://drive.google.com/file/d/1kUmOPM8J63JmzM20H1Cg38oAfPRBJwLy/view?pli=1

##### Website Link:
https://pumpbtc.xyz/

##### Logo (High resolution, will be shown with rounded borders):
https://drive.google.com/file/d/1jIj9IwhrEsnMI4BFBF8TYGxQO_uCZ3-s/view?usp=drive_link

##### Current TVL:
 1.14 M

##### Chain:
ETH/BSC/Mantle

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
 pumpbtc

##### Short Description (to be shown on DefiLlama):
PumpBTC serves as a Liquid Restaking Solution for Babylon. PumpBTC aims to help BTC holders maximize yields through Babylon's liquid staking - essentially rebuilding WBTC with native yield.

##### Token address and ticker if any:
ETH: 0xf469fbd2abcd6b9de8e169d128226c0fc90a012e
BSC: 0xf9C4FF105803A77eCB5DAE300871Ad76c2794fa4
Mantle: 0xC75D7767F2EdFbc6a5b18Fc1fA5d51ffB57c2B37

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Liquid Staking

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL for pumpBTC is calculated based on the total value of WBTC, FBTC, BTCB held in the contract that were utilized in the minting process of pumpBTC.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/pumpbtc/pumpBTC-contract

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/pumpbtc exports TVL: 
        
 
 
    ethereum                  823.36 k
    bsc                       310.20 k
    mantle                    1.42 k
    
    total                    1.13 M

**Comment by llamatester** [comment]
The adapter at projects/pumpbtc exports TVL: 
        
 
 
    ethereum                  823.36 k
    bsc                       310.33 k
    mantle                    1.42 k
    
    total                    1.14 M

**Comment by g1nt0ki** [comment]
@DeKaiju thanks for the PR

**Comment by llamatester** [comment]
The adapter at projects/pumpbtc exports TVL: 
        
 
 
    ethereum                  822.92 k
    bsc                       309.64 k
    mantle                    1.42 k
    
    total                    1.13 M

**Pull request merged**
