### PR TITLE
Get Kamino enabled strategies list from API

### PR DESCRIPTION
**Pull request by peroxy**
The Kamino `api.js` adapter used a hardcoded strategies list that gets outdated very fast (Kamino adds new strategies every week) and the TVL lags behind.

I modified the code to fetch the strategy pubkeys from our public API which returns a list of all currently frontend-enabled strategies, then the TVL fetches the on-chain data using our SDK.

Output looks good:
```
> node test.js projects/kamino/api.js
--- solana ---
USDT                      5.82 M
Total: 5.82 M 

--- tvl ---
USDT                      5.82 M
Total: 5.82 M 

------ TVL ------
solana                    5.82 M

total                    5.82 M 

```

I would also update the `@hubbleprotocol/kamino-sdk` package since we've added a lot of fixes and new stuff to it, but I can't seem to be able to do this in this repo.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/kamino exports TVL: 
        
 
 
    solana                    5.53 M
    
    total                    5.53 M

**Comment by g1nt0ki** [comment]
The version needs to be updated here: https://github.com/DefiLlama/sushi-analytics can add it as part of startup script to update this package as well

**Comment by g1nt0ki** [comment]
Can you put a PR here updating line 10: https://github.com/DefiLlama/sushi-analytics/blob/master/post-install.sh

**Comment by peroxy** [comment]
Added @g1nt0ki https://github.com/DefiLlama/sushi-analytics/pull/7

**Comment by g1nt0ki** [comment]
@peroxy I am blind, I was already doing it: https://github.com/DefiLlama/sushi-analytics/blob/master/post-install.sh#L1

**Comment by peroxy** [comment]
> @peroxy I am blind, I was already doing it: https://github.com/DefiLlama/sushi-analytics/blob/master/post-install.sh#L1

Haha, OK perfect, thanks for the help!

**Pull request merged**
