### PR TITLE
feat: adding in token locker

### PR DESCRIPTION
**Pull request by TheHomelessCoder**
PR is for adding in TVL for BaseSwap token locker- all tokens which are locked should be added to the TVL

Token locker allows people to lock tokens and liquidity for custom durations.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/baseswap exports TVL: 
        
 
 
    base                      53.25 M
    
    total                    53.25 M

**Comment by llamatester** [comment]
Error while running adapter at projects/baseswap: 
        
 
  
    
    
    TypeError: Cannot convert undefined or null to object
    Truncated error stack:
        at ChainApi.addBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/ChainApi.js:148:16)
        at Function.entries (<anonymous>)

**Comment by TheHomelessCoder** [comment]
> Error while running adapter at projects/baseswap:
> 
> ```
> TypeError: Cannot convert undefined or null to object
> Truncated error stack:
>     at ChainApi.addBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/ChainApi.js:148:16)
>     at Function.entries (<anonymous>)
> ```


How are you getting this please, this is what I am seeing without any errors-

```➜  DefiLlama-Adapters git:(main) node test.js projects/baseswap/index.js
--- base ---
WETH                      27.03 M
USDbC                     26.80 M
DAI+                      1.02 M
axlUSDT                   68.15025485637001
Total: 54.85 M

--- tvl ---
WETH                      27.03 M
USDbC                     26.80 M
DAI+                      1.02 M
axlUSDT                   68
Total: 54.85 M

------ TVL ------
base                      54.85 M

total                    54.85 M```

**Comment by TheHomelessCoder** [comment]
> hi, the tokens locked are going to baseswap LPs? if so, it would be double counting.

It can be single tokens or LPs from any exchange, so you are right, I need to call the factory method on `lock.token` and compare to the factory at the top of the file

**Comment by llamatester** [comment]
The adapter at projects/baseswap exports TVL: 
        
 
 
    base                      54.94 M
    
    total                    54.94 M

**Comment by g1nt0ki** [comment]
> > Error while running adapter at projects/baseswap:
> > ```
> > TypeError: Cannot convert undefined or null to object
> > Truncated error stack:
> >     at ChainApi.addBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/ChainApi.js:148:16)
> >     at Function.entries (<anonymous>)
> > ```
> 
> I am seeing this with the updated code, I am not sure how fetchList fully works, but I think it is using the first response with the second, and the result of 2 calls the second with `0 & 1` but it must be `1&2` - is there anything wrong with the original code other than the double count issue?

yeah, it takes care of fetching the item count and querying both 0 & 1

There are two issues, one should not be counting lp tokens from the same dex: because the backing of those lp tokens are already included in tvl, other is we dont include single tokens in "locker" protocol category (you can check implementation of similar protocols like pinksale/deeplock/unicrypt, we include only the LPs locked in it)

**Comment by g1nt0ki** [comment]
closing this for now, we can reopen it once your locker has LPs from dexes not your own?

**Pull request closed without merging**
