### PR TITLE
veRWA adaptor created and data verified

### PR DESCRIPTION
**Pull request by chasebrownn**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
re.al protocol

##### Twitter Link:
https://twitter.com/real_rwa

##### List of audit links if any:
https://drive.google.com/file/d/1UMYLKF1_vyEshz64limENYOTwykWk0d_/view

##### Website Link:
https://www.re.al/

##### Logo (High resolution, will be shown with rounded borders):
image

##### Current TVL:
~$18.5M

##### Chain:
re.al

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
https://www.coingecko.com/en/coins/re-al
ID: 're.al'

##### Short Description (to be shown on DefiLlama):
The DeFi-native L2 for tokenized RWAs, using off-chain yields to build deep onchain liquidity.

##### Token address and ticker if any:
0x4644066f535ead0cde82d209df78d94572fcbf14
$RWA

##### Category (full list at https://defillama.com/categories) *Please choose only one:
RWA

##### methodology (what is being counted as tvl, how is tvl being calculated):
The balance of RWA in the votingEscrowRWA contract is TVL. Reason being, the RWA that's deposited into that contract is locked in exchange for a governance 've' token.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/re-al-Foundation/rwa-contracts

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/real-rwa exports TVL: 
        
 
 
    real                      18.55 M
    
    total                    18.55 M

**Comment by g1nt0ki** [comment]
hi @chasebrownn, thanks for the PR,  we can track this under staking not as tvl: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by chasebrownn** [comment]
That's fine. Does it require any code revisions?

**Comment by llamatester** [comment]
The adapter at projects/real-veRWA exports TVL: 
        
 
 
    real-staking              20.46 M
    staking                   20.46 M
    real                      0
    
    total                    0

**Pull request merged**
