### PR TITLE
map chainge bridge locked assets on Rollux

### PR DESCRIPTION
**Pull request by thomgabriel**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Chainge

##### Twitter Link:
https://x.com/FinanceChainge

##### Website Link:
https://chainge.finance/

##### Logo (High resolution, will be shown with rounded borders):
https://icons.llamao.fi/icons/protocols/chainge-finance?w=48&h=48

##### Current TVL:
14.00 M

##### Treasury Addresses (if the protocol has treasury)
0x66ff2f0AC3214758D1e61B16b41e3d5e62CAEcF1

##### Chain:
Rollux

##### Short Description (to be shown on DefiLlama):
Chainge Finance stands as the most liquid cross-chain aggregated DEX with over 70bn in aggregated liquidity. The mobile app boasts over 20 integrated DEXs and 29 chains. From a cross-chain wallet and instant cross-chain roaming to decentralized earning solutions and smart escrow contracts, Chainge is an DeFi app powered and secured by the innovative Fusion DCRM tech

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Cross Chain

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is calculated by summing the balances of all tokens (USDC, USDT, WBTC, WETH, WSYS, and native SYS) held in the Chainge treasury address (0x66ff2f0AC3214758D1e61B16b41e3d5e62CAEcF1) on the Rollux network. These tokens are used to provide liquidity for cross-chain swaps.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/chainge: 
        
 
  
    
    
    Error: unable to verify the first certificate
    Truncated error stack:
        at AxiosError.from (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/axios/dist/node/axios.cjs:873:14)
        at RedirectableRequest.emit (node:events:517:28)
        at ClientRequest.emit (node:events:517:28)
        at TLSSocket.socketErrorListener (node:_http_client:501:9)
        at TLSSocket.emit (node:events:517:28)
        at async fetch (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/chainge.js:5:15)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:61:7)
        at async Promise.all (index 2)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:214:3

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
@thomgabriel thanks for the PR, we already have an adapter for chainge, can you update that one: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/chainge.js#L5

**Comment by llamatester** [comment]
Error while running adapter at projects/chainge.js: 
        
 
  
    
    
    Error: unable to verify the first certificate
    Truncated error stack:
        at AxiosError.from (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/axios/dist/node/axios.cjs:873:14)
        at RedirectableRequest.emit (node:events:517:28)
        at ClientRequest.emit (node:events:517:28)
        at TLSSocket.socketErrorListener (node:_http_client:501:9)
        at TLSSocket.emit (node:events:517:28)
        at async fetch (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/chainge.js:21:15)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:61:7)
        at async Promise.all (index 3)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:220:3

**Comment by thomgabriel** [comment]
@g1nt0ki done

**Comment by g1nt0ki** [comment]
can I remove the fusion part of the tvl? it has been broken for a while now

**Comment by thomgabriel** [comment]
@g1nt0ki I'll reach out to them to check if there's an updated version of their API for tracking all their TVL. I should have it back to you soon

**Comment by thomgabriel** [comment]
@g1nt0ki Yes, you can remove it, they changed their service into a cross-chain aggregator, so that API's TVL info is not valid anymore, thanks mate

**Comment by g1nt0ki** [comment]
merged it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/12019

**Pull request closed without merging**
