### PR TITLE
v2 update

### PR DESCRIPTION
**Pull request by YeeeeeHan**
This PR aims to enhance the reliability and performance of the REPL's TVL page. 
- We have noticed that there are significant fluctuations in Repl's TVL on the DefiLlama frontend. This is probably caused by service reliability issues with repeated and frequent on-chain calculation on a public blockchain node, which could be costly and unstable.
- We have optimized the calculation and updated the code for better robustness and stability. In the new update, miner data is directly obtained from the filecoin chain, and all calculations are cached. This reduces the overhead on the DefiLlama frontend.
- The Repl protocol has also undergone a V2 update. We have reflected corresponding changes in the new update as well. The TVL calculation method remains unchanged.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/repl exports TVL: 
        
 
 
    filecoin                  12.92 M
    
    total                    12.92 M

**Comment by llamatester** [comment]
The adapter at projects/repl exports TVL: 
        
 
 
    filecoin                  12.92 M
    
    total                    12.92 M

**Comment by g1nt0ki** [comment]
hi @YeeeeeHan I am fairly certain it is not node issue as other filecoin adapters are fine, also if it is a node issue, the adapter should fail instead of returning lower tvl, maybe there was some bug in the code? 

We really dont like apis, you can find the reason here: https://github.com/DefiLlama/DefiLlama-Adapters/discussions/432

**Comment by llamatester** [comment]
The adapter at projects/repl exports TVL: 
        
 
 
    filecoin                  15.24 M
    
    total                    15.24 M

**Comment by llamatester** [comment]
The adapter at projects/repl exports TVL: 
        
 
 
    filecoin                  15.42 M
    
    total                    15.42 M

**Comment by YeeeeeHan** [comment]
@g1nt0ki Got it, I understand where you are coming from now, we have pushed a new change to remove APIs and align with #432

**Comment by YeeeeeHan** [comment]
@g1nt0ki Just wondering could you also point me to documentation on how often/ when defillama performs re-calculation? I can't seem to find documentation on it, thank you!

**Comment by g1nt0ki** [comment]
> @g1nt0ki Got it, I understand where you are coming from now, we have pushed a new change to remove APIs and align with #432

@YeeeeeHan thanks for refactoring the code, sorry for being a pain in the ass.

There is no documentation, we have agents that compute/update all protocol tvl every hour

**Pull request merged**
