### PR TITLE
add tvl for oin-finance

### PR DESCRIPTION
**Pull request by 442879722**
##### Twitter Link:
https://twitter.com/financeoin?s=21

##### List of audit links if any:
https://oin-finance.gitbook.io/925/misc.-resources/documentation

##### Website Link:
https://oin.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://github.com/aurora-is-near/bridge-assets/blob/master/tokens/oin.svg

##### Current TVL:
$8042694

##### Chain:
near,etherscan

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
oin-finance

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
6870

##### Short Description (to be shown on DefiLlama):
A robust turnkey stablecoin issuance platform built for the multi-chain universe

##### Token address and ticker if any:
0x9aeb50f542050172359a0e1a25a9933bc8c01259
https://etherscan.io/address/0x9aeB50f542050172359A0e1a25a9933Bc8c01259

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
None

##### forkedFrom (Does your project originate from another project):
None

##### methodology (what is being counted as tvl, how is tvl being calculated):
tvl of staking pool + tvl of stability pool

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Do you mind reverting your changes to pull_request_template.md ? So the info is only in the PR description

**Comment by 442879722** [comment]
done

**Comment by 0xngmi** [comment]
would it be possible to get a script that calculates tvl from on-chain calls?

**Comment by 442879722** [comment]
> would it be possible to get a script that calculates tvl from on-chain calls?
we have fixed that, please review it

**Comment by 442879722** [comment]
stNEAR and nUSDO are two completely different assets and are deposited into different pools respectively, users can also obtain nUSDO in other approaches and deposit it into the stable pool

**Comment by 442879722** [comment]
hence, we have different tvl for stability pool and staking pool

**Comment by 442879722** [comment]
Hi there, I found that the PR has been successfully merged, so when can I view the tvl info on your web page

**Comment by waynebruce0x** [comment]
Theres an issue with the adapter, it returns no TVL

**Comment by waynebruce0x** [comment]
I've pushed a fix, should be on the UI today

**Pull request merged**
