### PR TITLE
chore(zharta): update add colateral estimated value

### PR DESCRIPTION
**Pull request by developerfred**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/zharta: 
        
 
  
    
    
    Error: Invalid balance: NaN
    Truncated error stack:
        at isValidNumber (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:119:19)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:318:16
        at Array.forEach (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:312:28)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:325:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:53:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:147:9
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
Error while running adapter at projects/zharta: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:204:11

**Comment by llamatester** [comment]
Error while running adapter at projects/zharta: 
        
 
  
    
    
    TypeError: Cannot create property 'coingecko:0' on string '25152980769257755000async (_, _b, _cb, { api }) => sumTokens2({ api, balances, tokensAndOwners, tokens, owner, owners, transformAddress, unwrapAll, resolveLP, blacklistedLPs, blacklistedTokens, skipFixBalances, ownerTokens, resolveUniV3, })'
    Truncated error stack:
        at Object.sumSingleBalance (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:115:25)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:318:16
        at Array.forEach (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:312:28)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:325:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:53:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:147:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)

**Comment by llamatester** [comment]
Error while running adapter at projects/zharta: 
        
 
  
    
    
    Error: Unexpected value from fetchEstimatedValue(): [object Promise]
    Truncated error stack:
    
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/zharta/index.js:31:15)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:31)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:147:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:135:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:130:44

**Comment by llamatester** [comment]
Error while running adapter at projects/zharta: 
        
 
  
    
    
    Error: Invalid balance: NaN
    Truncated error stack:
        at isValidNumber (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:119:19)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:318:16
        at Array.forEach (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:312:28)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:325:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:53:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:147:9
        at async Promise.all (index 0)

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
sorry, there are few bugs here, but main issue is, can we fetch all collateral on chain? right now, we suppot pricing only bluechip nfts (which has chainlink oracles) but I am trying expand support.

I dislike using api, they are blackbox and maintenance nightmare

**Comment by developerfred** [comment]
> sorry, there are few bugs here, but main issue is, can we fetch all collateral on chain? right now, we suppot pricing only bluechip nfts (which has chainlink oracles) but I am trying expand support.
> 
> I dislike using api, they are blackbox and maintenance nightmare

Sure, I'll see if I can get that data solely on-chain.

**Pull request closed without merging**
