### PR TITLE
add izumi adapter

### PR DESCRIPTION
**Pull request by LpcAries**
##### List of audit links if any:
https://docsend.com/view/ura947u6ck3urpqb 
https://docsend.com/view/2bif3vfinpv657mh

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded [borders):]
izumi-logo-symbol

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
izumi-finance

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
16305

##### Short Description (to be shown on DefiLlama):
iZUMi Finance LiquidBox is a platform providing programmable Liquidity As A Service (LaaS) on the top of UniswapV3. It allows liquidity providers earn additional liquidity mining rewards as well as trading fees on UniswapV3. On the other side, it will help protocols attract liquidity in an efficient and lasting way.

##### Token address and ticker if any:
IZI on Ethereum: 0x9ad37205d608B8b219e6a2573f922094CEc5c200 
IZI on Polygon: 0x60D01EC2D5E98Ac51C8B4cF84DfCCE98D527c747 
IZI on Arbitrum: 0x60D01EC2D5E98Ac51C8B4cF84DfCCE98D527c747

##### methodology (what is being counted as tvl, how is tvl being calculated):
The izumi platfom maintains a set of Liquidity Mining Pools. Each pool is a mining contract. The overall tvl is the summation of all tvls in the pools. There are 2 types of assets will be counted as tvl in each pool: 
 1. tokens locked in UniswapV3. 
 2. tokens locked directly in the mining contract. 
In the first case, the mining contract holds a set of NFTs given by UniswapV3. We provide api that regularly loop over the NFTs and calculate their values. 
For the second case, it may contain tokens depending on the mining logic. For example, in "One-Side" mode with "iZi/USDC" pair, the “iZi" token is locked in the mining contract while "USDC" is used to generate UniswapV3 position.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/izumi/index.js exports TVL: 
                
 
 

total                    12.20 M

**Comment by waynebruce0x** [comment]
Can this be calculated using on-chain calls? 
Can the iZi/ETH LP staking be exported as a separate 'pool2' export? 
Is the veiZi locker included in this?
Thanks!

**Comment by McGrady00H** [comment]
> Can this be calculated using on-chain calls? Can the iZi/ETH LP staking be exported as a separate 'pool2' export? Is the veiZi locker included in this? Thanks!

1. The tvl is hard to compute using on-chain calls once a time for now. There are two main reasons,

**Comment by McGrady00H** [comment]
> Can this be calculated using on-chain calls? Can the iZi/ETH LP staking be exported as a separate 'pool2' export? Is the veiZi locker included in this? Thanks!

1. The tvl is hard to compute directly using on-chain calls once a time for now. There are several reasons. a. a brute-force one-stop calculation needs to loop over thousands of NFTs, which is easily crashed in the middle and time-consuming.  Currently, we update the tvl actively in most of the time, that is, when a transaction happens on the chain, we update the delta. We loop over the NFTs at some points to eliminate errors.  b. our protocols are actively updated, recently we have added a new type "Dynamic Range" and we will add the veiZi boosting versions. Tvl calculations for different protocols are diverse. It's not flexible and hard to maintain the logic codes here. 
2. We exported a separate 'pool2' for iZi/ETH in the last commit.
3. The veiZi locker is not included. The tvl currently only calculates the liquidity on Ethereum. We will add tvls on other chains in the next version.

**Comment by llamatester** [comment]
The adapter at projects/izumi/index.js exports TVL: 
                
 
 

total                    12.21 M

**Comment by realdealshaman** [comment]
@LpcAries Hello, I am in the process of listing your project but I see that there is an error in the adapter. Since iZUMi is on Polygon and Arbitrum we need to export the TVL per chain, in its current state we would need to give all the TVL to a single chain. Could you help us separate the TVL?

**Comment by McGrady00H** [comment]
> @LpcAries Hello, I am in the process of listing your project but I see that there is an error in the adapter. Since iZUMi is on Polygon and Arbitrum we need to export the TVL per chain, in its current state we would need to give all the TVL to a single chain. Could you help us separate the TVL?

Currently, the TVL only calculates assets on Ethereum. We will update soon to cover TVLs on Polygon and Arbitrum in the next PR. Sorry for the trouble.

**Comment by realdealshaman** [comment]
No trouble at all, thank you for letting me know, I will get it listed

**Comment by McGrady00H** [comment]
> No trouble at all, thank you for letting me know, I will get it listed

We updated a version and created a new PR, which separates the TVL on different chains~ https://github.com/DefiLlama/DefiLlama-Adapters/pull/2009

**Pull request merged**
