### PR TITLE
Add QUSD and WQ tokens

### PR DESCRIPTION
**Pull request by KyrylR**
This PR was created to add tracking information for QUSD and WQ tokens on the Defi Lama platform.

> Note: the price is calculated for the QUSD token: QUSD is created similarly to how the DAI token is created. There are 3 assets backing the token: BTC, USDC, and DAI.

The methodology for price oracles is described here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/9193.

Also, Q was recently listed, and WQ is just a token wrapper contract with logic only for wrapping: https://explorer.q.org/address/0xd07178e3eCbC78De110Df84fe1A979D5f349784a?tab=contract.

### CODE REVIEW

**Comment by KyrylR** [comment]
I'm not sure why the linting doesn't work, I ran it locally and it ran successfully, maybe some problem with CI

**Comment by g1nt0ki** [comment]
hi @KyrylR what is qusd?

**Comment by KyrylR** [comment]
Hello @g1nt0ki, it is a synthetic asset that is backed by three collaterals

Here is a document that does not directly describe what QUSD is, but provides relevant information: https://docs.q.org/dapp-savingborrowing/

In a nutshell, it is a USD-pegged stablecoin: https://www.geckoterminal.com/q-mainnet/pools/0x2a36b45be4c04900a5946a1b6bf991adec93adde

However, in the particular case of this pool, it is not active yet, as they require $100k of liquidity on each side. Currently, we have only $45k

Still, this info should give you a brief understanding of what QUSD is

**Comment by KyrylR** [comment]
In addition, we have an audit of the Borrowing section (the place where you can borrow QUSD): 

https://chainsecurity.com/wp-content/uploads/2021/11/ChainSecurity_Q_Blockchain_System_contracts_audit.pdf

https://chainsecurity.com/wp-content/uploads/2022/12/ChainSecurity_Q_Blockchain_System_contracts_v1_2_audit.pdf

**Pull request merged**
