### PR TITLE
cNETA and NETA staking (TVL)

### PR DESCRIPTION
**Pull request by andrehafner**
Live feed from anetaBTC api for all tokens staked in cNETA and NETA
- Uses request() function

**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
anetaBTC

##### Twitter Link:
@anetaBTC

##### List of audit links if any:
(this is the code that grabs the staked and creates an output)
https://github.com/andrehafner/my.ergoport.dev/tree/main/aneta

##### Website Link:
https://anetabtc.io/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
cNETA and NETA logo in link below is anetaBTC_logo.png
anetaBTC logo is available with black or white text in link below
https://drive.google.com/drive/folders/13IGRgf9wNCPfckTQ6DSMaIo9gE-wx0zm

##### Current TVL:
cNETA = 39508431
NETA = 184519882.546561

##### Chain:
cNETA = CARDANO
NETA = ERGO

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
n/a

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
n/a

##### Short Description (to be shown on DefiLlama):
AnetaBTC is a fully on-chain, decentralized protocol that allows Bitcoin to be directly wrapped on the Ergo and Cardano blockchains. AnetaBTC enables Bitcoin holders to unlock the value of their assets in a secure and efficient environment to provide yield, without selling any Bitcoin and without any third-party custodian involvement.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
https://defillama.com/protocols/Bridge

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
n/a

##### forkedFrom (Does your project originate from another project):
Token on Cardano
Token on ERGO

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is achieved by making a call to anetaBTC's API:
https://my.ergoport.dev/cgi-bin/aneta/c_neta_TVL.pl
and
https://my.ergoport.dev/cgi-bin/aneta/neta_TVL.pl
and consists of all staked c_NETA and NETA.

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@andrehafner thanks for the PR, but staked cNeta/neta in ergo would count towards staking, your tvl is the amount of btc minted in cardano/ergo . What are the minted btc token addressses?

**Comment by andrehafner** [comment]
Hey @g1nt0ki , thanks for the note.
There is no wBTC yet. They wanted to add staking/locked numbers for cNETA and NETA which from what I understood is part of TVL. Is that not something you would allow? Cheers!

**Comment by llamatester** [comment]
The adapter at projects/aada exports TVL: 
        
 
 
    cardano-staking           300.90 k
    cardano                   506.07 k
    staking                   300.90 k
    
    total                    506.07 k

**Comment by llamatester** [comment]
The adapter at projects/anetabtc exports TVL: 
        
 
 
    cardano                   0
    cardano-staking           159.82 k
    ergo-staking              684.66 k
    staking                   844.47 k
    
    total                    0

**Pull request merged**
