### PR TITLE
Added mvlp vault

### PR DESCRIPTION
**Pull request by babayega**
Added new vault TVL

### CODE REVIEW

**Comment by g1nt0ki** [comment]
I am thinking of closing this as we have already started pricing sMVLP on the backend: https://github.com/DefiLlama/DefiLlama-Adapters/pull/5662,

question: would fetching bps give much different number compared to pricing 1 sMVLP = 1 MVLP ?

**Comment by g1nt0ki** [comment]
@babayega this is a mooToken right? 0x2ee50C34392E7e7a1D17B0A42328a8D1Ad6894e3

**Comment by g1nt0ki** [comment]
@babayega sorry, I didnt look at the code properly, I have fixed it here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/2c90475213e4699db7e0f9c03840691e11f5eb9b

https://github.com/DefiLlama/defillama-server/commit/8149265bf09c39d6d5fc8c114096afcab3e7ecd4

**Comment by babayega** [comment]
Hey @g1nt0ki, I can still see a considerable difference in the TVL. Shall I raise a new PR.
Please help to resolve this ASAP.

**Comment by g1nt0ki** [comment]
@babayega what difference do you see? I am checking token balance on your contracts and summing them up, is any of the token mispriced?

**Pull request closed without merging**
