### PR TITLE
Add Phase protocol

### PR DESCRIPTION
**Pull request by 0xPhase**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Phase

##### Twitter Link:
https://twitter.com/0xPhase

##### List of audit links if any:
https://omniscia.io/reports/0xphase-core-protocol-643d1d1f88c1770014f3a77b/
https://omniscia.io/reports/0xphase-balancer-implementation-645cb15ec7eedb00140139f7/

##### Website Link:
https://phase.cash

##### Logo (High resolution, will be shown with rounded borders):
https://phase.cash/favicon.png

##### Current TVL:
1467$

##### Treasury Addresses (if the protocol has treasury)
https://basescan.org/address/0x088e2ab0eeb3bec31586b752ff10473d37208daf

##### Chain:
Base

##### Short Description (to be shown on DefiLlama):
Phase aims to be a liquidity platform, allowing users to borrow a rock-solid stablecoin while earning yield at the same time. Using your collateral, even while borrowing CASH, you can earn interest.

##### Token address and ticker if any:
CASH 0xbe92452bb46485AF3308e6d77786bFBE3557808d

##### Category (full list at https://defillama.com/categories) *Please choose only one:
CDP

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink, Custom for Bond (Bond price based on CASH in Bond)

##### forkedFrom (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is total deposited assets in all vaults
Borrowed is total borrowed CASH
Staking is total staked CASH in Bond

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/0xphase
https://github.com/0xphase/core

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/phase exports TVL: 
        
 
 
    base-staking              0
    base-borrowed             0
    base                      1.69 k
    staking                   0
    borrowed                  0
    
    total                    1.69 k

**Comment by llamatester** [comment]
The adapter at projects/phase exports TVL: 
        
 
 
    base-staking              0
    base                      1.71 k
    staking                   0
    
    total                    1.71 k

**Comment by g1nt0ki** [comment]
@0xPhase thanks for the PR, one change I have made is, disabling minted CASH as borrowed, right now we are not doing it for other protocols, say like FRAX/Maker

**Comment by 0xPhase** [comment]
> @0xPhase thanks for the PR, one change I have made is, disabling minted CASH as borrowed, right now we are not doing it for other protocols, say like FRAX/Maker

That's totally fine! Wasn't sure so I decided to include it "just in case". Thanks for the awesome site <3

**Pull request merged**
