### PR TITLE
feat: add solidlizard-lending

### PR DESCRIPTION
**Pull request by slzbro**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
SolidLizard Lending

##### Twitter Link:
https://twitter.com/solidlizardfi

##### Website Link:
https://lending.solidlizard.finance/

##### Logo (High resolution, will be shown with rounded borders):
https://lending.solidlizard.finance/img/scales-480px.png

##### Current TVL:
53k USD

##### Treasury Addresses (if the protocol has treasury)
0xAD87e8d2F7E74C93BBC9Ba61FbC168f066530519

##### Chain:
Arbitrum One

##### Short Description (to be shown on DefiLlama):
SolidLizard Lending is a highly scalable decentralized lending protocol powered by Arbitrum.

##### Token address and ticker if any:
0xe6AF844d5740B6B297B6Dd7Fb2ce299Ee9E3d16F $SCALES

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Chainlink, Pyth

##### forkedFrom (Does your project originate from another project):
Compound Finance

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL: Same as Compound Finance, we just count all the tokens supplied (not borrowed money) on the lending markets

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/solidlizard-lending exports TVL: 
        
 
 
    arbitrum-staking          0
    arbitrum-borrowed         2.56 k
    arbitrum                  51.08 k
    staking                   0
    borrowed                  2.56 k
    
    total                    51.08 k

**Comment by llamatester** [comment]
The adapter at projects/solidlizard-lending exports TVL: 
        
 
 
    arbitrum-borrowed         2.54 k
    arbitrum-staking          0
    arbitrum                  50.71 k
    arbitrum-pool2            0
    borrowed                  2.54 k
    staking                   0
    pool2                     0
    
    total                    50.71 k

**Comment by g1nt0ki** [comment]
@slzbro thanks for the PR

**Comment by llamatester** [comment]
The adapter at projects/solidlizard-lending exports TVL: 
        
 
 
    arbitrum-borrowed         2.54 k
    arbitrum                  50.71 k
    arbitrum-pool2            0.000049152894286276806
    arbitrum-staking          0
    borrowed                  2.54 k
    pool2                     0.000049152894286276806
    staking                   0
    
    total                    50.71 k

**Pull request merged**
