### PR TITLE
Sirius-finance

### PR DESCRIPTION
**Pull request by sirius0xnomad**
##### Twitter Link:
https://twitter.com/Sirius_Finance

##### List of audit links if any:
https://github.com/SiriusFinance/siriusfinance-contract/blob/main/audit/PeckShield-Audit-Report-SiriusFinance-v1.0.pdf

##### Website Link:
https://www.sirius.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://www.sirius.finance/logo.png

##### Current TVL
$15.5 million

##### Chain
AstarNetwork

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
sirius-finance

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
19492

##### Short Description (to be shown on DefiLlama):
The first cross-chain stablecoin amm & LP center on Astarnetwork

##### Token address and ticker if any:
0x9448610696659de8F72e1831d392214aE1ca4838

##### Category (full list at https://defillama.com/categories) *Please choose only one:
DEX

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
no

##### forkedFrom (Does your project originate from another project):
Curve

##### methodology (what is being counted as tvl, how is tvl being calculated):
Sirius Finance Tvl Calculation

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/sirius-finance/index.js exports TVL: 
        
 
 
    astar                     0
    
    total                    0

**Comment by waynebruce0x** [comment]
Is 0 TVL expected? We need some TVL to list your project. Please use 'node test.js projects/sirius-finance/index.js ' to check your output

**Comment by ronald-sirius** [comment]
> Is 0 TVL expected? We need some TVL to list your project. Please use 'node test.js projects/sirius-finance/index.js ' to check your output

Thanks for pointing out, We have already fixed the issue and gonna push again.

**Comment by sirius0xnomad** [comment]
update index.js

**Comment by llamatester** [comment]
The adapter at projects/sirius-finance/index.js exports TVL: 
        
 
 
    astar                     18.55 M
    
    total                    18.55 M

**Pull request merged**
