### PR TITLE
Update Reserve 

### PR DESCRIPTION
**Pull request by larrythecucumber321**
Reserve's eUSD now uses wrapped Compound v2 tokens. This PR accounts for the wrapped assets to correct the current [Reserve TVL](https://defillama.com/protocol/reserve), which has dropped since the update 

```

--- tvl ---
aUSDC                     4.47 M
aUSDT                     4.40 M
cUSDT                     4.38 M
cUSDC                     4.38 M
rETH                      2.07 M
wstETH                    2.07 M
USDbC                     638.46 k
USDC                      624.75 k
eUSD3CRV-f                621.10 k
sDAI                      425.39 k
aBasUSDbC                 155
WETH                      91
USDT                      23
DAI                       19
aUSDP                     17
aDAI                      9
aBUSD                     1
cbETH                     1
Total: 24.08 M 

------ TVL ------
ethereum-staking          9.13 M
base-staking              28.74 k
ethereum                  23.44 M
base                      638.71 k
staking                   9.16 M

total                    24.08 M 
```

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/reserve: 
        
 
  
    
    
    PromisePoolError: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0xcA11bde05977b3631167028862bE2a173976CA11","data":"0xbce38bd700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000d00000000000000000000000000000000000000000000000000000000000001a0000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000002e00000000000000000000000000000000000000000000000000000000000000380000000000000000000000000000000000000000000000000000000000000042000000000000000000000000000000000000000000000000000000000000004c00000000000000000000000000000000000000000000000000000000000000560000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000006a0000000000000000000000000000000000000000000000000000000000000074000000000000000000000000000000000000000000000000000000000000007e000000000000000000000000000000000000000000000000000000000000008800000000000000000000000000000000000000000000000000000000000000920000000000000000000000000320623b8e4ff03373931769a31fc52a4e78b5d700000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a08231000000000000000000000000a2b328c4e49b6d31fd2cdec7bb2223e3e97e52fe00000000000000000000000000000000000000000000000000000000000000000000000000000000320623b8e4ff03373931769a31fc52a4e78b5d700000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000001517780cbb53f3d9f4e20f2d021f10f404885e1200000000000000000000000000000000000000000000000000000000000000000000000000000000320623b8e4ff03373931769a31fc52a4e78b5d700000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a0823100000000000000000000000018ba6e33ceb80f077deb9260c9111e62f21ae7b800000000000000000000000000000000000000000000000000000000000000000000000000000000320623b8e4ff03373931769a31fc52a4e78b5d700000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000006bbf36d911797a6de22a9c5fa8570563d675128500000000000000000000000000000000000000000000000000000000000000000000000000000000320623b8e4ff03373931769a31fc52a4e78b5d700000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a08231000000000000000000000000df8bcfbf1cb943f8522ddb5b5ed73f939c1e5cfd00000000000000000000000000000000000000000000000000000000000000000000000000000000320623b8e4ff03373931769a31fc52a4e78b5d700000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a08231000000000000000000000000c163c7ddc8b1f0057ed710056ab35ed225754cc000000000000000000000000000000000000000000000000000000000000000000000000000000000320623b8e4ff03373931769a31fc52a4e78b5d700000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a08231000000000000000000000000d8f3511f7fb9cb5235071024a08ec8804b406ff800000000000000000000000000000000000000000000000000000000000000000000000000000000320623b8e4ff03373931769a31fc52a4e78b5d700000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a0823100000000000000000000000064cd8978f4e698f961bca2d5c5f45470ed47fca800000000000000000000000000000000000000000000000000000000000000000000000000000000320623b8e4ff03373931769a31fc52a4e78b5d700000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a0823100000000000000000000000088d4a7d64e8b51025ef9ae369cea5438cfa472a800000000000000000000000000000000000000000000000000000000000000000000000000000000320623b8e4ff03373931769a31fc52a4e78b5d700000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a08231000000000000000000000000ffa151ad0a0e2e40f39f9e5e9f87cf9e45e819dd00000000000000000000000000000000000000000000000000000000000000000000000000000000320623b8e4ff03373931769a31fc52a4e78b5d700000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000007db3c57001c80644208fb8aa81ba1200c7b0731d00000000000000000000000000000000000000000000000000000000000000000000000000000000320623b8e4ff03373931769a31fc52a4e78b5d700000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a08231000000000000000000000000b96703268bc65b04621d7a7c75d0f2d8b19f0a3700000000000000000000000000000000000000000000000000000000000000000000000000000000320623b8e4ff03373931769a31fc52a4e78b5d700000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a08231000000000000000000000000bcb3118d20c30a319f4ca04b302247f6e3635a6800000000000000000000000000000000000000000000000000000000","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    Truncated error stack:
        at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by larrythecucumber321** [comment]
Strange... this works for me, not sure I'm understanding this error 
image

**Comment by g1nt0ki** [comment]
@larrythecucumber321 thanks for the PR

**Comment by llamatester** [comment]
The adapter at projects/reserve exports TVL: 
        
 
 
    ethereum-staking          8.54 M
    base-staking              27.04 k
    ethereum                  24.48 M
    base                      637.40 k
    staking                   8.57 M
    
    total                    25.12 M

**Pull request merged**
