### PR TITLE
feat: add ParaSpace ApeStaking tab

### PR DESCRIPTION
**Pull request by jfzhou5**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/paraspace exports TVL: 
        
 
 
    ethereum-borrowed         20.21 M
    ethereum                  94.65 M
    borrowed                  20.21 M
    
    total                    94.65 M

**Comment by llamatester** [comment]
Error while running adapter at projects/paraspace-ape-staking: 
        
 
  
    
    
    TypeError: Cannot read properties of null (reading 'poolId')
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/paraspace-ape-staking/index.js:48:44
        at Array.filter (<anonymous>)
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/paraspace-ape-staking/index.js:48:22)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:25)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:147:9
        at async Promise.all (index 0)
        at async Promise.all (index 0)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:192:3

**Comment by llamatester** [comment]
The adapter at projects/paraspace exports TVL: 
        
 
 
    ethereum-borrowed         20.24 M
    ethereum                  94.68 M
    borrowed                  20.24 M
    
    total                    94.68 M

**Comment by jfzhou5** [comment]
image
Local running is ok.

**Comment by jfzhou5** [comment]
@g1nt0ki can you help to view this issue ?

**Comment by llamatester** [comment]
The adapter at projects/paraspace-ape-staking exports TVL: 
        
 
 
    ethereum                  37.79 M
    
    total                    37.79 M

**Pull request merged**
