### PR TITLE
Add Darkness TVL to DarkCrypto

### PR DESCRIPTION
**Pull request by darkcrypto-warrior**
Twitter Link:
https://twitter.com/DarkCryptoFi

List of audit links if any:
Website Link:
https://www.darkcrypto.finance/

Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://www.darkcrypto.finance/images/dark.svg

Current TVL:
$80,482,697

Chain:
Cronos

Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
darkcrypto

Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
17118

Short Description (to be shown on DefiLlama):
DarkCrypto Finance is the first ecosystem running around an algorithmic token pegged to CRO on Cronos chain. DarkVerse will be our ecosystem using DARK as the main token. It contains: DeFi App (Vaults, Stablecoin swap, lending), GameFi, NFT Apps, Betting DApps, MetaVerse applications

Token address and ticker if any:
0x83b2AC8642aE46FC2823Bc959fFEB3c1742c48B5
$DARK

Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Algo-Stables

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
forkedFrom (Does your project originate from another project):
Tomb Finance

methodology (what is being counted as tvl, how is tvl being calculated):
DarkCrypto TVL is amount staked on the platform (Farm, Vault, Boardroom) and TVL of ecosystem products (DarkNess,...)

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/darkcrypto/index.js exports TVL: 
                
 
 
cronos-staking            16.22 M
cronos-pool2              24.72 M
cronos                    30.22 M
staking                   16.22 M
pool2                     24.72 M

total                    30.22 M

**Comment by waynebruce0x** [comment]
Is this double counting the TVL reported by the Darkness adapter? You can choose one or the other but not both

**Comment by darkcrypto-warrior** [comment]
Hi @waynebruce0x 

Darkness is a product of the DarkCrypto ecosystem. It has the same discord and Twitter. Hence Can you add Darkness TVL to DarkCrypto TVL?

**Comment by darkcrypto-warrior** [comment]
Could you set the mode double count for DarkCrypto? 
When someone activates the toggles "Double Count" they can see Darkness TVL?

**Pull request closed without merging**
