### PR TITLE
savvy adapter

### PR DESCRIPTION
**Pull request by glupta**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Savvy

##### Twitter Link:
https://twitter.com/SavvyDeFi

##### List of audit links if any:
https://github.com/HalbornSecurity/PublicReports/blob/master/Solidity%20Smart%20Contract%20Audits/Savvy_DeFi_Smart_Contract_Securtity_Audit_Report_Halborn_Final.pdf

##### Website Link:
https://savvydefi.io/

##### Current TVL:
$685,480

##### Treasury Addresses (if the protocol has treasury)
0x4f54Cab19B61138e3c622a0bD671C687481eC030

##### Chain:
Arbitrum

##### Short Description (to be shown on DefiLlama):
Savvy is a non-liquidating, auto-repaying, interest-free borrowing platform. Borrow up to 50% of the value of the collateral using Savvy synths. You can borrow in stablecoins, Ethereum, or Bitcoin derivatives and repay in kind, eliminating the need for liquidations. Loans are backed against the future yield of the collateral.

##### Token address and ticker if any:
SVY: 0x43aB8f7d2A8Dd4102cCEA6b438F6d747b1B9F034
svBTC: 0xeEE18334c414A47FB886a7317E1885b2Bfb8c2A6
svETH: 0xf7728582002ef82908c8242CF552E969BA863Ffa
svUSD: 0xF202Ab403Cd7E90197ec0f010ee897E283037706

##### Category (full list at https://defillama.com/categories) *Please choose only one:
CDP

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### methodology (what is being counted as tvl, how is tvl being calculated):
Total user deposits

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/savvy: 
        
 
  
    
    
    ReferenceError: api is not defined
    Truncated error stack:
    
        at staking (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/savvy/index.js:12:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:29)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:136:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:131:44

**Comment by llamatester** [comment]
The adapter at projects/savvy exports TVL: 
        
 
 
    arbitrum                  0
    
    total                    0

**Comment by g1nt0ki** [comment]
hi @glupta I have refactored the code to fetch balances on chain: https://github.com/DefiLlama/DefiLlama-Adapters/pull/6653 if you are fine with the changes, I can merge it.

**Comment by llamatester** [comment]
The adapter at projects/savvy exports TVL: 
        
 
 
    arbitrum                  340.52 k
    
    total                    340.52 k

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
I dislike this implementation. We do do more calls in other places, but just checking all possible addresses against all possible tokens does not sound like a good idea,  it is 19 owners * 14 addresses.

Why is savvyToken (svBTC) balances checked?  imo, it can be skipped as tvl is backing of those tokens, 
similarly, I am unsure why we are checking for tokens in veSVY (should be part of staking, check my implementation), WrapTokenGateway, SavvySwapWETH and such, they will never have tokens right? 

This is also missing aToken tvl, so need to query the aToken value in yield tokens

Can you please rework this PR a bit and restrict the number of calls?

**Comment by llamatester** [comment]
The adapter at projects/savvy exports TVL: 
        
 
 
    arbitrum                  339.97 k
    
    total                    339.97 k

**Comment by glupta** [comment]
SavvySwaps currently do not hold tokens but they will. The aToken TVL is captured in the savvyAArbTokens. Is the updated pr better?

**Comment by llamatester** [comment]
The adapter at projects/savvy exports TVL: 
        
 
 
    arbitrum                  685.11 k
    
    total                    685.11 k

**Comment by g1nt0ki** [comment]
@glupta thanks for fixing it

**Pull request merged**
