### PR TITLE
add uniBTC adapter

### PR DESCRIPTION
**Pull request by Trisome-Bedrock**
##### Current TVL: 143.19706090 uniBTC

| Chain    | Total Supply of uniBTC |
|----------|------------------------|
| BSquared | 1887515830 / 1e8       |
| Bitlayer | 91617365 / 1e8         | 
| Merlin   | 19834431 / 1e8         | 
| Ethereum | 11523136417 / 1e8      | 
| Mantle   | 300939 / 1e8           |
| Optimism | 809966108 / 1e8        |                                                                                                                       |

##### Token address and ticker if any:

| Chain    | uniBTC Contract | Vault Contract                                                                                                                         |
|----------|-----------------|----------------------------------------------------------------------------------------------------------------------------------------|
| BSquared | [0x93919784C523f39CACaa98Ee0a9d96c3F32b593e](https://explorer.bsquared.network/address/0x93919784C523f39CACaa98Ee0a9d96c3F32b593e) | [0xF9775085d726E782E83585033B58606f7731AB18](https://explorer.bsquared.network/address/0xF9775085d726E782E83585033B58606f7731AB18) |
| Bitlayer | [0x93919784C523f39CACaa98Ee0a9d96c3F32b593e](https://www.btrscan.com/address/0x93919784C523f39CACaa98Ee0a9d96c3F32b593e?tab=Transactions) | [0xF9775085d726E782E83585033B58606f7731AB18](https://www.btrscan.com/address/0xF9775085d726E782E83585033B58606f7731AB18?tab=Transactions) |
| Merlin   | [0x93919784C523f39CACaa98Ee0a9d96c3F32b593e](https://scan.merlinchain.io/address/0x93919784C523f39CACaa98Ee0a9d96c3F32b593e) | [0xF9775085d726E782E83585033B58606f7731AB18](https://scan.merlinchain.io/address/0xF9775085d726E782E83585033B58606f7731AB18)      |
| Ethereum | [0x004E9C3EF86bc1ca1f0bB5C7662861Ee93350568](https://etherscan.io/address/0x004e9c3ef86bc1ca1f0bb5c7662861ee93350568) | [0x047D41F2544B7F63A8e991aF2068a363d210d6Da](https://etherscan.io/address/0x047d41f2544b7f63a8e991af2068a363d210d6da)             |
| Mantle   | [0x93919784C523f39CACaa98Ee0a9d96c3F32b593e](https://mantlescan.xyz/address/0x93919784C523f39CACaa98Ee0a9d96c3F32b593e) | [0xF9775085d726E782E83585033B58606f7731AB18](https://mantlescan.xyz/address/0xF9775085d726E782E83585033B58606f7731AB18)           |
| Optimism | [0x93919784C523f39CACaa98Ee0a9d96c3F32b593e](https://optimistic.etherscan.io/address/0x93919784C523f39CACaa98Ee0a9d96c3F32b593e) | [0xF9775085d726E782E83585033B58606f7731AB18](https://optimistic.etherscan.io/address/0xF9775085d726E782E83585033B58606f7731AB18)                                                                                                                          |

##### Github org/user (Optional, if your code is open source, we can track activity): https://github.com/Bedrock-Technology

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/unibtc exports TVL: 
        
 
 
    bsquared                  0
    ethereum                  0
    btr                       0
    optimism                  0
    merlin                    0
    mantle                    0
    
    total                    0.0001467051769409044

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
please update adapter to count locked bitcoins on bitcoin, instead of counting supplies on other chains

**Comment by g1nt0ki** [comment]
*update code to count amount of WBTC/other tokens locked in the vaults on given chain instead of counting token supply

**Comment by Trisome-Bedrock** [comment]
Thank you for your feedback. However, is it a better idea for us to continue with uniBTC statistics when considering the following aspects of our protocol:

1. The uniBTC project does not directly interact with Bitcoin's BTC, but:
(1) It accepts users' wrapped BTC tokens from the blockchains of both the Ethereum and Bitcoin ecosystems.
(2) It also accepts users' native BTC tokens from Bitcoin layer 2 blockchains.

2. The amount of uniBTC is equivalent to the sum of locked tokens (either wrapped BTC or native BTC) from various blockchains and has the following features:
(1) One wrapped/native BTC is always equivalent to one uniBTC. 
(2) uniBTC assets are only minted when users deposit wrapped/native BTC into the Vault contract.
(2) uniBTC assets are only burned when users claim their wrapped/native BTC from the Vault contract.

3. The total supply of uniBTC provides a consistent view of TVL because:
(1) Wrapped/native BTC have various decimals (18 or 8 as supported by our protocol), while uniBTC has a constant 8 decimals.
(2) The locked assets in the Vault contract may be transferred to other ecosystem parties (e.g., FBTC1 contract) for restaking operations. But from the user's view, their corresponding deposited wrapped/native BTC and the minted uniBTC remain locked and undergo no changes.

**Comment by g1nt0ki** [comment]
uniBTC supply might be equivalent to tvl, but we prefer show users the underlying composition

**Comment by Trisome-Bedrock** [comment]
Understood. Let me try improvements.

**Comment by 0xpeluche** [comment]
@Trisome-Bedrock  Hey, I've done the changes at #11236 if you want to take a look

**Comment by g1nt0ki** [comment]
merged here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/11236

**Comment by Trisome-Bedrock** [comment]
> @Trisome-Bedrock Hey, I've done the changes at #11236 if you want to take a look

Thanks a lot for your support. I'll take a look soon and ask for clarification if I have any doubts.

**Pull request closed without merging**
