### PR TITLE
feat : ✨Update Stake DAO tvl with new api endpoints

### PR DESCRIPTION
**Pull request by LucasRamadour**
#### Update of the Stake DAO adaptor

---

- Update to new endpoints for deployed strategies on Curve, Pendle, Balancer, Yearn and Pancakeswap.
- Add logic for fetching pancake ERC20 strategies tvl on-chain for Binance Smart Chain.
- Remove deprecated ANGLE strategies from the adaptor.
- Include veSDT into the TVL

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/stakedao exports TVL: 
        
 
 
    ethereum                  70.25 M
    ethereum-staking          9.70 M
    staking                   9.70 M
    bsc                       3.06 M
    polygon                   416.52 k
    avax                      246.09 k
    arbitrum                  195.86 k
    
    total                    74.16 M

**Comment by LucasRamadour** [comment]
@g1nt0ki reverted

**Comment by g1nt0ki** [comment]
@LucasRamadour thanks for reverting it. I have updated bsc part to use multicall so adapter runs slightly faster and we pay bit less to rpc providers

**Comment by LucasRamadour** [comment]
Ah my bad ! Thank you very much

**Pull request merged**
