### PR TITLE
Add Convergence-RFQ Adapter

### PR DESCRIPTION
**Pull request by ateeqrehmani**
**NOTE**

##### Short Description (to be shown on DefiLlama): A fully-on-chain liquidity network for market makers and protocols.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/convergence-rfq exports TVL: 
        
 
 
    solana                    1
    
    total                    0.5499901

**Comment by g1nt0ki** [comment]
hi, why not compute tvl on chain?

**Comment by ateeqrehmani** [comment]
@g1nt0ki 
Hey, thanks for the response!
Is on-chain calculations must? Currently, we're facing hurdles with on-chain calculations, which we plan to address in the next phase. For now, we have  handled it off-chain.

**Comment by g1nt0ki** [comment]
afraid so, we have had issues with apis: https://github.com/DefiLlama/DefiLlama-Adapters/discussions/432

**Comment by g1nt0ki** [comment]
closing this due to inactivity

**Pull request closed without merging**
