### PR TITLE
Create index.js

### PR DESCRIPTION
**Pull request by Paramseh**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Lila Finance

##### Twitter Link:
twitter.com/LilaFinance

##### Website Link:
www.lila.finance

##### Logo (High resolution, will be shown with rounded borders):
www.lila.finance/vite.png

##### Current TVL:
1.85k

##### Treasury Addresses (if the protocol has treasury)
0xA8Caa9144e3C5A836F70B9CB8f6492Af0108e582

##### Chain:
arbitrum

##### Short Description (to be shown on DefiLlama):
Lila Finance swaps interest rates on yield-generating protocols, allowing users to earn a fixed or floating rate. 

##### Token address and ticker if any:
0xDF53cC6771ceC9b4Ef97AC726725a16b0fb41Aa3
LilaPosition (LILA)
(Its a ERC721 (not a token but a tradable position asset))

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
None

##### forkedFrom (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated):
Since we allow interest rate swaps on other protocols. (Currently only Aave but Radient, Stargate, etc down the road)
Simplest way was to record our pools' balances of standard tokens and aave tokens and report that as our tvl as users deposits get turned into aave tokens, if you need us to convert it back I can make the edits but wanted to confirm from you if you guys auto convert the prices/values of the assets.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/Lila-Finance
https://github.com/paramseh

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/lila-finance exports TVL: 
        
 
 
    arbitrum                  1.85 k
    
    total                    1.85 k

**Comment by Paramseh** [comment]
We have had additional deposits since I created the PR, TVL numbers are not accurate but live numbers can be found on our site. www.lila.finance

**Comment by llamatester** [comment]
The adapter at projects/lila-finance exports TVL: 
        
 
 
    arbitrum                  2.76 k
    
    total                    2.76 k

**Comment by Paramseh** [comment]
Amended changes please review

**Comment by llamatester** [comment]
The adapter at projects/lila-finance exports TVL: 
        
 
 
    arbitrum                  2.76 k
    
    total                    2.76 k

**Comment by llamatester** [comment]
The adapter at projects/lila-finance exports TVL: 
        
 
 
    arbitrum                  2.76 k
    
    total                    2.76 k

**Comment by g1nt0ki** [comment]
@Paramseh thanks for the PR

**Pull request merged**
