### PR TITLE
 Pando TVL Adapters 

### PR DESCRIPTION
**Pull request by lyricat**
##### Twitter Link: 

Pando: https://twitter.com/pando_im
4swap: https://twitter.com/4swapOrg

##### List of audit links if any:

IOActive & LeastAuthority: https://docs.pando.im/docs/security/audit-reports

##### Website Link:

https://pando.im

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

Pando

##### Current TVL:

$289,259,092.55

##### Chain:

Mixin Network: https://mixin.one

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

N/A

##### Short Description (to be shown on DefiLlama):

Pando is a set of open financial protocols which includes 3 major protocols: 
- Pando Lake/4swap: a decentralized protocol for automated liquidity provision built with the Mixin Trusted Group
- Pando Leaf: a decentralized financial network to minting stablecoins
- Pando Rings: a decentralized protocol where you can lend or borrow cryptocurrencies

##### Token address and ticker if any:

N/A

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:

- Pando Lake/4swap: Assets
- Pando Leaf: Minting
- Pando Rings: Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

Pando Pricing Oracle: https://docs.pando.im/docs/leaf/key-concepts/price-oracles/

##### forkedFrom (Does your project originate from another project):

N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):

Add all protocols' tvl together.

### CODE REVIEW

**Comment by 0xngmi** [comment]
please avoid using APIs and instead extract the data from on-chain calls

**Comment by lyricat** [comment]
> please avoid using APIs and instead extract the data from on-chain calls

Mixin Network doesn't support contract, so there is no on-chain calls yet,

**Comment by 0xngmi** [comment]
Looks good to me, should we separate it into multiple protocols or do you think putting it all under pando is better? If we put it all under one protocol there might be some double counting to consider (eg: pUSD being used on 4pool but I've had a look and it's very minor)

For now I'll merge and remove borrowing on rings from tvl (same methodology we use for all money markets)

Is it possible to get historical tvl data?

**Comment by 0xngmi** [comment]
thanks for the PR, always love listing more stuff

**Comment by lyricat** [comment]
> should we separate it into multiple protocols or do you think putting it all under pando is better? 

Thank you. I will discuss the suggestion with Pando community.

> Is it possible to get historical tvl data?

- Lake and 4swap have an API to get historical tvl, please check this link: https://docs.pando.im/developer/lake/apis/stat
- We have a plan to add similar APIs to Rings and Leaf, but they are not ready yet.

**Pull request merged**
