### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by KlayLend-Finance**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama): 
KlayLend Finance

##### Twitter Link: 
https://twitter.com/Klaylend

##### List of audit links if any: 
https://github.com/solidproof/projects/tree/main/KlayLend

##### Current TVL:
$143556

##### Chain:
Klaytn

##### Short Description (to be shown on DefiLlama):
KlayLend is a decentralized lending & borrowing protocol and staking platform running on Klaytn.

##### Token address and ticker if any:
Token Name
KLD
Contract Address
0xb8c460aD6aC97797A57BDb08D7187b4710B4Fdf8

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/klaylend exports TVL: 
        
 
 
    klaytn-pool2              0
    klaytn-staking            0
    klaytn                    53.43 k
    pool2                     0
    staking                   0
    
    total                    53.43 k

**Comment by llamatester** [comment]
The adapter at projects/kumu-finance exports TVL: 
        
 
 
    klaytn-staking            9.39 k
    klaytn                    323.80 k
    staking                   9.39 k
    
    total                    323.80 k

**Comment by llamatester** [comment]
The adapter at projects/klaylend exports TVL: 
        
 
 
    klaytn-pool2              24.21 k
    klaytn                    142.77 k
    klaytn-staking            19.76 k
    pool2                     24.21 k
    staking                   19.76 k
    
    total                    142.77 k

**Comment by realdealshaman** [comment]
Hey @KlayLend-Finance how's it going? I'm getting ready to list Klaylend so that it appears on Defillama but it seems that the tvl belongs to the farm portion of the dapp hence "Farm" would be a more fitting category

**Comment by KlayLend-Finance** [comment]
> Hey @KlayLend-Finance how's it going? I'm getting ready to list Klaylend so that it appears on Defillama but it seems that the tvl belongs to the farm portion of the dapp hence "Farm" would be a more fitting category

Hi we will list lending function in the coming future. Farming is our first stage.

After I double-checked, the twitter link should be  **https://twitter.com/Klaylend** instead of klex's account.

**Pull request merged**
