### PR TITLE
add grim tvl adapter

### PR DESCRIPTION
**Pull request by AriesML**
**Twitter Link:** https://twitter.com/financegrim

**List of audit links if any:** https://solidity.finance/audits/GrimVault/

**Website Link:** https://app.grim.finance/

Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): https://www.grim.finance/assets/img/grim/grim-logo-flip.png

**Current TVL:** $2,220,000

**Chain:** Fantom

**Coingecko ID (so your TVL can appear on Coingecko):** (https://www.coingecko.com/en/coins/grimtoken)

**Coinmarketcap ID (so your TVL can appear on Coinmarketcap):** (https://coinmarketcap.com/currencies/grimtoken/)

**Description/bio (to be shown on DefiLlama):** Grim Finance is a Smart Yield Optimizer Platform that allows users to stake LP-Tokens issued from the AMM’s in Smart Grim Vaults, which automatically harvest and re-stake their rewards as LP-Tokens for a compounding effect. Helping users reap more rewards, hassle-free. 

**Token address and ticker if any:** GRIM, REAPER

**Category (Yield/Dexes/Lending/Minting):** Yield Optimizer

### CODE REVIEW

**Comment by 0xngmi** [comment]
No need to repeat the same code twice

**Comment by 0xngmi** [comment]
Hey, there seems to be an issue with your API that makes our query fail on our server. I'm not sure why it's happening since it seems to work fine on my machine, but the query always fails on our server. Haven't looked too much into it yet, but thinking that the issue might be related to a different set of SSL certificates being used

**Comment by 0xngmi** [comment]
Just looked into our logs and the issue seems to be that your api returns 503 when queried from our backend:

Here's the response we get:
```
  status: 503,
    statusText: 'Service Temporarily Unavailable',
    headers: {
      date: 'Wed, 01 Sep 2021 13:58:44 GMT',
      'content-type': 'text/html; charset=UTF-8',
      'transfer-encoding': 'chunked',
      connection: 'close',
      'x-frame-options': 'SAMEORIGIN',
      'permissions-policy': 'accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()',
      'cache-control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
      expires: 'Thu, 01 Jan 1970 00:00:01 GMT',
      'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
      'report-to': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=IXOt12UGBL%2BsUehvXIOufaxV%2BD4I0tauzMR3PysGxSfAxg8hdoK6cC11nP%2BgUti8hRiqMG%2FwUaGoi8m5Os4q0k418f%2B6Zlyw9g4ziFWC4BV5u2vS99M5Y0M0r7m7N0uogrVR"}],"group":"cf-nel","max_age":604800}',
      nel: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
      server: 'cloudflare',
      'cf-ray': '687f03e26def97b4-FRA',
      'alt-svc': 'h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400, h3=":443"; ma=86400'
    },
    config: {
      url: 'https://api.grim.finance/tvl',
      method: 'get',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function (anonymous)],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      data: undefined
    },
```

**Comment by AriesML** [comment]
Thanks 0xngmi, what domain should I enable for this cross origin request?

**Comment by 0xngmi** [comment]
Our request shouldn't come from any domain, it's coming directly from our lambda functions on a AWS datacenter

**Comment by AriesML** [comment]
I turned off some automated bot detection features from cloudflare, perhaps this will help. Otherwise we should sync up offline for further diagnosis.

**Comment by 0xngmi** [comment]
great, if it works it should pop up on defillama after 1 hour

**Comment by 0xngmi** [comment]
https://defillama.com/protocol/grim-finance

**Pull request merged**
