### PR TITLE
added erc4626 vaults for functionx that locks LP tokens

### PR DESCRIPTION
**Pull request by freeelancer**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Chain:
FunctionX

##### Short Description (to be shown on DefiLlama):
LP tokens are locked in the added vaults, the tvl should be the value of these LP tokens.
**Currently the value is not showing as the sumERC4626VaultsExport does not work for these new vaults as the tokens being locked are LP tokens.**

##### methodology (what is being counted as tvl, how is tvl being calculated):
LP tokens are locked in the added vaults, the tvl should be the value of these LP tokens.

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/baklava-space exports TVL: 
        
 
 
    avax-staking              9.21 M
    avax-pool2                429.78 k
    avax                      325.86 k
    functionx                 5.61 M
    staking                   9.21 M
    pool2                     429.78 k
    
    total                    5.93 M

**Comment by llamatester** [comment]
The adapter at projects/baklava-space exports TVL: 
        
 
 
    avax-pool2                429.88 k
    avax-staking              9.20 M
    avax                      326.01 k
    functionx                 5.61 M
    pool2                     429.88 k
    staking                   9.20 M
    
    total                    5.93 M

**Comment by LanceLan96** [comment]
Hi @g1nt0ki Currently the value is not showing as the sumERC4626VaultsExport does not work for these new vaults as the tokens being locked are LP tokens. You can see this in the comment in the code, we require some help for this.

**Comment by g1nt0ki** [comment]
@freeelancer I updated code to resolve the LP tokens, but am seeing very low value. what is the expected tvl value from LPs?

**Comment by LanceLan96** [comment]
> @freeelancer I updated code to resolve the LP tokens, but am seeing very low value. what is the expected tvl value from LPs?

just checked, yeap it is correct. Thanks for such quick response

**Comment by freeelancer** [comment]
> @freeelancer I updated code to resolve the LP tokens, but am seeing very low value. what is the expected tvl value from LPs?

yeap, just noticed your update, its correct. Thanks for the quick response!

**Pull request merged**
