### PR TITLE
Tetu V2 on Base

### PR DESCRIPTION
**Pull request by belbix**
We are launching Tetu V2 on Base network
https://v2-base.tetu.io/
The same logic as on Polygon

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/tetu: 
        
 
  
    
    
    Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0xb8bA82F19A9Be6CbF6DAF9BF4FBCC5bDfCF8bEe6","data":"0x82af54c9","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:654:52
        at Array.forEach (<anonymous>)

**Comment by llamatester** [comment]
Error while running adapter at projects/tetu: 
        
 
  
    
    
    Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0xb8bA82F19A9Be6CbF6DAF9BF4FBCC5bDfCF8bEe6","data":"0x82af54c9","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:654:52
        at Array.forEach (<anonymous>)

**Comment by belbix** [comment]
Hm, weird, works with Alchemy RPC

--- ethereum ---
USDC                      591.6892
Total: 591.6892 

--- base ---
USDC                      32.12 k
Total: 32.12 k 

--- bsc ---
USDC                      280.852475
Total: 280.852475 

--- polygon ---
USDC                      11.13 M
Total: 11.13 M 

--- fantom ---
Total: 0 

--- tvl ---
USDC                      11.17 M
Total: 11.17 M 

------ TVL ------
ethereum                  591.6892
base                      32.12 k
bsc                       280.852475
polygon                   11.13 M
fantom                    0

total                    11.17 M

**Comment by llamatester** [comment]
Error while running adapter at projects/tetu: 
        
 
  
    
    
    Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0x6E4D8CAc827B52E7E67Ae8f68531fafa36eaEf0B","data":"0x8d8523910000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000046e8e75484ee655c374b608842acd41b2ec3f11c","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:654:52
        at Array.forEach (<anonymous>)

**Comment by belbix** [comment]
Error data simulated in tenderly is fine
https://dashboard.tenderly.co/belbix/tetu/simulator/d86b8f41-d131-4f10-be93-eadba8976a3f

**Comment by llamatester** [comment]
Error while running adapter at projects/tetu: 
        
 
  
    
    
    Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0x6E4D8CAc827B52E7E67Ae8f68531fafa36eaEf0B","data":"0x8d852391000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000010000000000000000000000007f52d49c8a9779e93613fb14cf07be1500ab9c3a","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:654:52
        at Array.forEach (<anonymous>)

**Comment by g1nt0ki** [comment]
thanks for the PR, it works when I tested it locally

**Pull request merged**
