### PR TITLE
Add defenderfinance project

### PR DESCRIPTION
**Pull request by defenderfinance**
**NOTE**

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Short Description (to be shown on DefiLlama):
DEFENDER FINANCE
An algo-stable yield farming, with
- Innovative & strong mechanisms and features
- Trustworthy, reliable and hardworking team

##### Token address and ticker if any: 
SWDB: '0xc91324601B20ea0e238B63c9fAfca18d32600722',
SHDB: '0x9562Ca0C2b05D089063F562fC3Ecc95e4424AD02',

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/defenderfinance: 
        
 
  
    
    
    Error: 
        Please move the following keys into the chain: tvl
    
        We have a new adapter export specification now where tvl and other chain specific information are moved inside chain export.
        For example if your protocol is on ethereum and has tvl and pool2, the export file would look like:
        
            module.exports = {
              methodlogy: '...',
              ethereum: {
                tvl: 
                pool2:
              }
            }

**Comment by llamatester** [comment]
The adapter at projects/defenderfinance exports TVL: 
        
 
 
    bsc                       0
    bsc-treasury              0
    bsc-pool2                 22.69 k
    treasury                  0
    pool2                     22.69 k
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/defenderfinance exports TVL: 
        
 
 
    bsc                       0
    bsc-treasury              166.6073713926531
    bsc-pool2                 20.49 k
    treasury                  166.6073713926531
    pool2                     20.49 k
    
    total                    0

**Comment by g1nt0ki** [comment]
I removed SWDB from treasury because we dont count own tokens under treasury

**Comment by Define101** [comment]
Hello, we will use this logo, as the one you provided will not fit in. 
image

**Pull request merged**
