### PR TITLE
Add TVL for EUrxb

### PR DESCRIPTION
**Pull request by IntegralTeam**
#### Why are you creating this pull request?
Adding the TVL of EURxb

##### Twitter Link:
https://twitter.com/EURxbfinance

##### List of audit if any:
https://github.com/EURxbfinance/audits

##### Website Link:
https://app.eurxb.finance/

##### Contact Email:
contact@eurxb.finance

##### Expected TVL:
396 000 000 USD

##### Chain:
Mainnet Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko):
None

##### Description/bio (to be shown on DefiLlama):
The EURxb is an ERC20 Euro Stable coin that earns real time interest of 7% per annum for the duration of the protocol's bond reserves' term. The EURxb is collateralised by ISIN registered securities (green bonds) as ERC721 NFTs which is further overcollateralized (at a rate of 133%) by tokenized ERC721 NFT security assets.

##### Token address and ticker if any:
0x0beAD9a1bcc1b84D06E3f2df67E3549Fd55aB054

### CODE REVIEW

**Comment by 0xngmi** [comment]
Thanks for submitting this PR. We are working on some infraestructure changes that will add extra options to the site and will allow customization on what to consider for TVL, but until then, we don't consider TVL from non-crypto assets (that's why we haven't listed some stablecoins for example).

Once these changes have been made we'll merge your PR.

**Comment by IntegralTeam** [comment]
@0xngmi, Hi! Could you please give more details why our token EURxb is considered as non-crypto asset?
Its ERC-20 token that is sold on uniswap.

**Comment by DefiLlama** [comment]
TVL is value locked inside a protocol. If you are a stable coin then you have no value locked although we will make some changes to list more assets.

**Comment by 0xngmi** [comment]
Merging this for now, we'll keep it unlisted until we solve the problem discussed above.

**Pull request merged**
