### PR TITLE
feat(hidden-hand): add hidden hand tvl

### PR DESCRIPTION
**Pull request by albuquerque-rafael**
##### Logo (High resolution, will be shown with rounded borders): 

logo

##### Short Description (to be shown on DefiLlama):
Hidden Hand is a marketplace for governance incentives. Protocols can leverage Hidden Hand to enable more efficient governance processes and to engage their voters, while users can earn extra yield on their favorite vote escrowed governance tokens through bribes.

##### methodology (what is being counted as tvl, how is tvl being calculated):
Sums bribe tokens deposited on Hidden Hand Reward Distributors, Bribe Vaults and Harvester contracts

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/hidden-hand: 
        
 
  
    
    
    PromisePoolError: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0xcA11bde05977b3631167028862bE2a173976CA11","data":"0xbce38bd700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000500000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000028000000000000000000000000000000000000000000000000000000000000003200000000000000000000000000c880f6761f1af8d9aa9c466984b80dab9a8c9e80000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000000a390de04b7717b078cf5c8a7eb891130d4a843b000000000000000000000000000000000000000000000000000000000000000000000000000000001509706a6c66ca549ff0cb464de88231ddbe213b0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000000a390de04b7717b078cf5c8a7eb891130d4a843b0000000000000000000000000000000000000000000000000000000000000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab10000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000000a390de04b7717b078cf5c8a7eb891130d4a843b00000000000000000000000000000000000000000000000000000000000000000000000000000000912ce59144191c1204e64559fe8253a0e49e65480000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000000a390de04b7717b078cf5c8a7eb891130d4a843b00000000000000000000000000000000000000000000000000000000000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e58310000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000000a390de04b7717b078cf5c8a7eb891130d4a843b00000000000000000000000000000000000000000000000000000000","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    Truncated error stack:
        at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
Error while running adapter at projects/hidden-hand: 
        
 
  
    
    
    PromisePoolError: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0xcA11bde05977b3631167028862bE2a173976CA11","data":"0xbce38bd700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000500000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000028000000000000000000000000000000000000000000000000000000000000003200000000000000000000000000c880f6761f1af8d9aa9c466984b80dab9a8c9e80000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000000a390de04b7717b078cf5c8a7eb891130d4a843b000000000000000000000000000000000000000000000000000000000000000000000000000000001509706a6c66ca549ff0cb464de88231ddbe213b0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000000a390de04b7717b078cf5c8a7eb891130d4a843b0000000000000000000000000000000000000000000000000000000000000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab10000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000000a390de04b7717b078cf5c8a7eb891130d4a843b00000000000000000000000000000000000000000000000000000000000000000000000000000000912ce59144191c1204e64559fe8253a0e49e65480000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000000a390de04b7717b078cf5c8a7eb891130d4a843b00000000000000000000000000000000000000000000000000000000000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e58310000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000000a390de04b7717b078cf5c8a7eb891130d4a843b00000000000000000000000000000000000000000000000000000000","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    Truncated error stack:
        at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
The adapter at projects/hidden-hand exports TVL: 
        
 
 
    arbitrum                  4.10978304
    optimism                  0.11904
    ethereum                  2.61 M
    
    total                    2.61 M

**Comment by g1nt0ki** [comment]
> > Error while running adapter at projects/hidden-hand:
> > ```
> > PromisePoolError: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0xcA11bde05977b3631167028862bE2a173976CA11","data":"0xbce38bd700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000500000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000028000000000000000000000000000000000000000000000000000000000000003200000000000000000000000000c880f6761f1af8d9aa9c466984b80dab9a8c9e80000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000000a390de04b7717b078cf5c8a7eb891130d4a843b000000000000000000000000000000000000000000000000000000000000000000000000000000001509706a6c66ca549ff0cb464de88231ddbe213b0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000000a390de04b7717b078cf5c8a7eb891130d4a843b0000000000000000000000000000000000000000000000000000000000000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab10000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000000a390de04b7717b078cf5c8a7eb891130d4a843b00000000000000000000000000000000000000000000000000000000000000000000000000000000912ce59144191c1204e64559fe8253a0e49e65480000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000000a390de04b7717b078cf5c8a7eb891130d4a843b00000000000000000000000000000000000000000000000000000000000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e58310000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000000a390de04b7717b078cf5c8a7eb891130d4a843b00000000000000000000000000000000000000000000000000000000","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
> > Truncated error stack:
> >     at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
> >     at async Promise.all (index 0)
> > ```
> 
> TVL currently working only for ethereum. Optimism and Arbitrum return error when calling `tryAggregate`. Can you guys help me understand why?

I think this graph is wrong: https://api.thegraph.com/subgraphs/name/albuquerque-rafael/hidden-hand-optimism returning ethereum tokens

**Comment by llamatester** [comment]
The adapter at projects/hidden-hand exports TVL: 
        
 
 
    arbitrum                  4.1071008
    optimism                  14.71 k
    ethereum                  2.56 M
    
    total                    2.57 M

**Pull request merged**
