### PR TITLE
Remove brahma-fi adapter

### PR DESCRIPTION
**Pull request by Pradeep-selva**
Removing Brahma.fi's TVL from being displayed on DefiLlama

### CODE REVIEW

**Comment by g1nt0ki** [comment]
hi  @Pradeep-selva why do you want to delist brahma? usually unless there is a good reason, we dont do it

**Comment by Pradeep-selva** [comment]
> hi  @Pradeep-selva why do you want to delist brahma? usually unless there is a good reason, we dont do it

We’d like to delist because this instance was to track the vaults which was our primary product, which we fully wound down last year. 

We are now building a new product called Console, which is a separate product for execution and not a protocol in itself.  [](https://www.brahma.fi/) is representing Console as core product, We want to make sure users don’t get confused by looking at Brahma and seeing stale data from smart contracts which aren’t associated to console, which is more like a wallet in design.

**Comment by g1nt0ki** [comment]
what if we add a hallmark saying that this product is wound down in favor of new product: console ? example: https://defillama.com/protocol/amun

**Comment by Pradeep-selva** [comment]
> what if we add a hallmark saying that this product is wound down in favor of new product: console ? example: https://defillama.com/protocol/amun

That wouldn't help us sir because Brahma is now associated with Console, which is a whole different direction. Brahma before was smart contract vaults, and now it's an on-chain execution suite, self custodial on top of Safe wallets.

So a user/lead seeing Brahma on DeFillama would be very confused. If we did another smart contract product with deposits we would have made a separate tab for it. But in this case it's a total rebranding as now Brahma = self custodial execution suite now 

So we believe the best is to remove it as we have had leads confusing this and thinking our product isn't used. Hope this explains the situation better

**Comment by g1nt0ki** [comment]
hi @Pradeep-selva I understand your point, checked with rest of the team, they felt the same way, issue is if we delist you, affects chain tvl history among other issues. Maybe we can rename the listing/product to make it clear that is not console, or we can add a warning banner?

**Comment by Pradeep-selva** [comment]
> hi @Pradeep-selva I understand your point, checked with rest of the team, they felt the same way, issue is if we delist you, affects chain tvl history among other issues. Maybe we can rename the listing/product to make it clear that is not console, or we can add a warning banner?

Ok ser, so, best we can do :/ 

rename Page Title to: "Brahma Vaults [Sunset]"
add event line on 28/02/2023 ""Brahma vaults discontinued, Brahma Console announced [not tracked here]"

Change Protocol information to:
Brahma Vaults managed interactions and risk with multiple chains, dApps and instruments in a fully transparent and composable way, to earn yield, hedge and deploy capital in an efficient manner.

Change website hyperlink to final vault recap blog: https://www.brahma.fi/blog/withdrawal-mode-brahma-vaults

**Comment by g1nt0ki** [comment]
closing this as fixed: https://defillama.com/protocol/brahma-vaults-(sunset)

**Pull request closed without merging**
