### PR TITLE
zkSwap Dex on zkSync Era

### PR DESCRIPTION
**Pull request by ZkSwapFinance**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
zkSwap Finance

##### Twitter Link:
https://twitter.com/zkSwap_finance

##### List of audit links if any:
https://github.com/ZkSwapFinance/Audit-Reports

##### Website Link:
https://zkswap.finance/

##### Logo (High resolution, will be shown with rounded borders):
https://zkswap.finance/logo.png

##### Current TVL:
4.02k

##### Chain:
zkSync Era

##### Short Description (to be shown on DefiLlama):
zkSwap.finance is the first decentralized Swap-to-Earn DeFi DEX that pioneers a unique incentive model rewarding both liquidity providers and traders.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### forkedFrom (Does your project originate from another project):
SyncSwap

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is total liquidity of all liquidity pools, using Uniswap TVL calculator.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/ZkSwapFinance

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/zkSwap-finance exports TVL: 
        
 
 
    era                       4.02 k
    
    total                    4.02 k

**Comment by llamatester** [comment]
The adapter at projects/zkSwap-finance exports TVL: 
        
 
 
    era                       4.05 k
    
    total                    4.05 k

**Comment by ZkSwapFinance** [comment]
Hello @llamatester @g1nt0ki ,

Could you please update our audit report?
https://github.com/Vital-block/Smart-Contract-Audit/blob/main/ZKSWAP%20FINANCE%20AUDIT%20REPORT.pdf

**Comment by g1nt0ki** [comment]
done

**Comment by ZkSwapFinance** [comment]
> done

Thank you so much!

**Pull request merged**
