### PR TITLE
Yiedl Vaults

### PR DESCRIPTION
**Pull request by lubin-rci**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
YIEDL Vaults

##### Twitter Link:
https://twitter.com/Yiedl_DAO

##### List of audit links if any:
https://docs.yiedl.ai/yiedl-vault-smart-contracts/smart-contract-audit-reports

##### Website Link:
https://vaults.yiedl.ai

##### Logo (High resolution, will be shown with rounded borders):
https://info.yiedl.ai/yiedl_vaults_circle.png

##### Current TVL:
550k

##### Treasury Addresses (if the protocol has treasury)
NA

##### Chain:
Optimism

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
NA

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
NA

##### Short Description (to be shown on DefiLlama):
YIEDL presents an innovative solution to the limitations of traditional asset management systems, leveraging AI and blockchain to provide users with access to high-performing investment strategies, low fees, and a transparent investment experience. The decision-making impacting the investment layer is driven by a collective intelligence where a global community of data scientists participates in a decentralized and distributed AI competition, in which they will be directly rewarded or penalized for their ability to forecast the market.

##### Token address and ticker if any:
We have 3 vaults, each of which has their own share token.

Y-UP [0x2494A64ea1B3AB49b0A9F185087E77BC2049863C](https://optimistic.etherscan.io/token/0x2494A64ea1B3AB49b0A9F185087E77BC2049863C)
Y-DOWN [0xE6f8f2af4e9a5C2D71Ba37FfE7646d7201ff6d42](https://optimistic.etherscan.io/token/0xE6f8f2af4e9a5C2D71Ba37FfE7646d7201ff6d42)
Y-NEUTRAL [0x90A039797E93f2c671DE25DD24E5333b5e8F9Ab3](https://optimistic.etherscan.io/token/0x90A039797E93f2c671DE25DD24E5333b5e8F9Ab3)

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Indexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
NA

##### forkedFrom (Does your project originate from another project):
NA

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL here is the summed TVL of the 3 vaults.
Each YIEDL vault holds positions in Synthetix Perps. 
The TVL for each vault is the sum of the value of the positions plus any flat (idle) sUSD. Flat sUSD may be necessary for certain strategies.

Adjustments to the portfolio allocation are made periodically.

Each vault maintains an average entry price table that is updated on portfolio rotation, or when deposits or redemptions are made. The value of each position is calculated by computing the profit/loss based on the price movement against the average entry price.

$$ value_{position} = abs(size) \times averageEntryPrice + size \times (currentPrice - averageEntryPrice) $$

The TVL, for a vault with positions in `n` assets, is:

$$ TVL = \sum_{i=0}^{n}value_{position(i)} + FlatSUSD $$

The methodology presented here can also be found in this [section](https://docs.yiedl.ai/yiedl-vault-smart-contracts/smart-contract-details#average-entry-price-table-and-tvl) of the YIEDL Vaults documentation.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/rocketcapital-ai/vaults_synthetix

### CODE REVIEW

**Comment by lubin-rci** [comment]
> @lubin-rci thanks for the PR, it mostly looks good, only thing that I dont understand is why you dont look for tvl at current block instead compute an eligible block and look there

Hi @g1nt0ki ,

The reason for that is the portfolio rotation, onboarding (deposits) and offboarding (redemptions) are operations that take multiple transactions to complete. (For example, reducing $100 worth of the BTC position, transferring $100 over to the ETH position contract, and increasing $100 worth of the ETH position.) 
During that time, the `size` parameter is being adjusted, and the computation for the TVL will not be accurately reflected until the entire operation has been completed.

If any of the 3 operations (portfolio rotation, onboarding or offboarding) are in session, the TVL returned is the TVL at the block where the operation was started.

If no operations are in session, then the TVL is computed simply based on the the latest block.

Hope this makes sense, please let me know if you have further questions!

**Comment by g1nt0ki** [comment]
@lubin-rci thanks for the explanation

**Comment by Define101** [comment]
@lubin-rci what happen to the twitter acc?

**Comment by lubin-rci** [comment]
> @lubin-rci what happen to the twitter acc?

Hi @Define101,

My apologies, here is the latest and correct account:
https://twitter.com/yiedlai

**Pull request merged**
