### PR TITLE
Stablecomp new vault

### PR DESCRIPTION
**Pull request by matteocelani**
# Description 

Added the following 3 new vaults to the StableComp protocol:

1. **3Crv**: `0x937A459c8F282abA432f5D5e14bD801ff848A1E3`
2. **crvUSDUSDT-f**: `0xE7E4632b22EC828f4804Ae8019F40f0a949F6BE5`
3. **crvFRAX**: `0xdd1722A31ae4D26946134Dc003775f7a6A92E61E`

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/stablecomp exports TVL: 
        
 
 
    ethereum                  25.95 k
    
    total                    25.95 k

**Comment by g1nt0ki** [comment]
@matteocelani thanks for the update, any way to fetch the vault list via rest endpoint?

**Comment by danyeah** [comment]
hello @g1nt0ki we can setup one straight away, how'd you like the data to be formatted? 
is same format as https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/stablecomp/contracts.json ok?

**Comment by g1nt0ki** [comment]
@danyeah yeah, that sounds good, thanks :)

**Comment by danyeah** [comment]
Hello
Here's the endpoint
https://services.stablecomp.com/vaults

**Comment by g1nt0ki** [comment]
thanks, updated it

**Pull request merged**
