### PR TITLE
add kivach

### PR DESCRIPTION
**Pull request by Taump**
##### Name (to be shown on DefiLlama):
Kivach

##### Twitter Link:
https://twitter.com/ObyteOrg

##### List of audit links if any:
-

##### Website Link:
https://kivach.org/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://kivach.org/logo-inverse.svg
https://kivach.org/logo.svg

##### Current TVL:
1.21k

##### Treasury Addresses (if the protocol has treasury)
-

##### Chain:
Obyte

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
byteball

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
1492

##### Short Description (to be shown on DefiLlama):
Support open-source projects with donations in crypto, and they will automatically forward a part of your donation to other open-source projects that made them possible

##### Token address and ticker if any:
-

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Payments, but maybe a new category is required for donations

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
-

##### forkedFrom (Does your project originate from another project):
-

##### methodology (what is being counted as tvl, how is tvl being calculated):
The TVL is the USD value of all undistributed donations received through Kivach.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/kivach exports TVL: 
        
 
 
    obyte                     1.19 k
    
    total                    1.19 k

**Comment by llamatester** [comment]
The adapter at projects/kivach exports TVL: 
        
 
 
    obyte                     1.28 k
    
    total                    1.28 k

**Comment by llamatester** [comment]
The adapter at projects/kivach exports TVL: 
        
 
 
    obyte                     1.32 k
    
    total                    1.32 k

**Comment by g1nt0ki** [comment]
@Taump thanks for the PR

**Comment by g1nt0ki** [comment]
Right now, your project is kinda unique in this, will add that category when there more of similar kind

**Pull request merged**
