### PR TITLE
WINR Protocol

### PR DESCRIPTION
**Pull request by allinJB**
…nction

🔍 chore(abi.js): export getReserve function for use in index.js

**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/winr-protocol exports TVL: 
        
 
 
    arbitrum                  5.09 M
    
    total                    5.09 M

**Comment by g1nt0ki** [comment]
@allinJB thanks for the PR, why are trying to count the entire supply of your gov token as tvl? I have removed that part, if you are fine with the changes, I can merge and list the project

**Comment by allinJB** [comment]
Thank you for prompt answer @g1nt0ki . 

We would like to show "total supply" and "tvl" on vault together. That was our intention.

After we submit this also we would like to show each token inside the index token of ours.

Changes are fine. Thank you for it. Should i add total supply also ? If yes, how can i add it other than I did

**Comment by g1nt0ki** [comment]
hi @allinJB , WINR token supply is your marketcap, sorry, we cant show it as tvl

**Comment by llamatester** [comment]
The adapter at projects/winr-protocol exports TVL: 
        
 
 
    arbitrum                  5.26 M
    
    total                    5.26 M

**Comment by Define101** [comment]
Please completed the format

**Comment by allinJB** [comment]
I would like to add branched out tvl data. Should i add now or should i wait for first iteration of listing ?

**Comment by g1nt0ki** [comment]
> I would like to add branched out tvl data. Should i add now or should i wait for first iteration of listing ?

what do you mean?

**Comment by allinJB** [comment]
We would like to add more data to show on DefiLlama. Should i wait current pr "data" is displayed on DefiLlama or should i create new PR. Does it intervene

**Comment by g1nt0ki** [comment]
ah, you need not wait, feel free to put up a new PR :)

**Comment by allinJB** [comment]
I just talked with tech team. Could you delete forked from GMX and change category to "Prediction Market" please

**Comment by g1nt0ki** [comment]
we fixed it

**Pull request merged**
