### PR TITLE
feat:Remove veth1.0 and update bifrost tvl

### PR DESCRIPTION
**Pull request by killbond007**
feat:Remove veth1.0 and update bifrost tvl

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bifrost-staking exports TVL: 
        
 
 
    ethereum                  23.53 M
    moonriver                 259.37 k
    bifrost                   16.94 M
    moonbeam                  1.66 M
    filecoin                  442.05 k
    
    total                    42.84 M

**Comment by g1nt0ki** [comment]
hi killbond007, a stupid question, the staking/redeeming of filecoin/moonbeam happens on bifrost chain or their own respective chains?

**Comment by killbond007** [comment]
> hi killbond007, a stupid question, the staking/redeeming of filecoin/moonbeam happens on bifrost chain or their own respective chains?

Sorry maybe am not get it. What do you mean by staking happen on Bifrost? User can stake with Bifrost on Bifrost chain, but we stake the underlying asset on destination chain.

**Comment by killbond007** [comment]
> > > hi killbond007, a stupid question, the staking/redeeming of filecoin/moonbeam happens on bifrost chain or their own respective chains?
> > 
> > 
> > Sorry maybe am not get it. What do you mean by staking happen on Bifrost? User can stake with Bifrost on Bifrost chain, but we stake the underlying asset on destination chain.
> 
> For example, users stake polygon tokens with Lido, but this staking/unstaking happens on ethereum, so we count it towards polygon tvl on ehtereum chain for Lido, does it make sense?

Thanks for clarification, we agree with it. TVL should be counted for the chain where the LSD minted.

**Comment by g1nt0ki** [comment]
hi @killbond007 can I close this PR?

**Comment by killbond007** [comment]
> hi @killbond007 can I close this PR?

Hello @g1nt0ki , so we can't merge thie PR ? we just want to listing our vFIL in https://defillama.com/chain/Filecoin tvl ranking , like this PR https://github.com/DefiLlama/DefiLlama-Adapters/pull/5882.

**Comment by g1nt0ki** [comment]
> > hi @killbond007 can I close this PR?
> 
> Hello @g1nt0ki , so we can't merge thie PR ? we just want to listing our vFIL in https://defillama.com/chain/Filecoin tvl ranking , like this PR #5882.

the reason I am reluctant to do this is, staking/unstaking happens on bifrost chain, okay I will merge this but if some user/other team complains, I would revert it back.

**Comment by wodlj1314** [comment]
@g1nt0ki let me clarify this, BIfrost has multiple liquid staking tokens, but ETH and FIL liquid stakings are directly staked via Ethereum and Filecoin mainnet, so TVL should be counted for Ethereum and Filecoin as well.

**Pull request merged**
