### PR TITLE
add OKC chain to impossible finance swap

### PR DESCRIPTION
**Pull request by acceleratedmonkey**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/impossiblefi: 
        
 
  
    
    
    Error: 
        Unknown chain(s): okc
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file

**Comment by realdealshaman** [comment]
Hey, @acceleratedmonkey thanks for the PR, we actually export okc as okexchain, also did you mean to remove "kava", I see it was deleted

**Comment by acceleratedmonkey** [comment]
oh right, thanks it was accidentally removed

**Comment by llamatester** [comment]
The adapter at projects/impossiblefi exports TVL: 
        
 
 
    bsc-staking               731.73 k
    boba                      0.07536100000000151
    moonbeam                  0.00020151267371998246
    kava                      4.061
    avax                      1.22 M
    okexchain                 806.523518
    aurora                    45.10 k
    bsc                       2.42 M
    staking                   731.73 k
    
    total                    3.68 M

**Pull request merged**
