### PR TITLE
Thorswap

### PR DESCRIPTION
**Pull request by dtmkeng**

### CODE REVIEW

**Comment by llamatester** [comment]
The thorswap adapter exports: 
        
 
 _______________________________________
    Volume for 19/10/2022
    _______________________________________
    
    THORCHAIN 👇
    Backfill start time: 13/7/2022
    24h volume: 10220431.395800818
    Total volume: 2541894575.817749

**Comment by llamatester** [comment]
The thorswap adapter exports: 
        
 
 _______________________________________
    Volume for 19/10/2022
    _______________________________________
    
    THORCHAIN 👇
    Backfill start time: 13/7/2022
    24h volume: 10220431.395800818
    Total volume: 2541894575.817749

**Comment by llamatester** [comment]
The thorswap adapter exports: 
        
 
 _______________________________________
    Volume for 1/11/2022
    _______________________________________
    
    THORCHAIN 👇
    Backfill start time: 26/7/2022
    24h volume: 22905300.9230694
    Total volume: 2258186843.586665

**Comment by dtmkeng** [comment]
need. to https://github.com/DefiLlama/adapters/tree/master/aggregators

**Pull request merged**
