### PR TITLE
Update claimswap dashboard api url

### PR DESCRIPTION
**Pull request by TurutuParapara**
https://defillama.com/protocol/claimswap

we are claimswap in klaytn.

and we updated our dashboard api

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/claimswap exports TVL: 
        
 
 
    klaytn-staking            253.44 k
    klaytn                    3.27 M
    staking                   253.44 k
    
    total                    3.27 M

**Comment by g1nt0ki** [comment]
hi @TurutuParapara is there some bug in your dashboard? I tried to compute tvl on chain and I got only 3.08M: https://github.com/DefiLlama/DefiLlama-Adapters/commit/8d6a6b4f7f8de4fb7eabad38829eb767adfd943a

**Comment by TurutuParapara** [comment]
@g1nt0ki We launch v2 swap. and dashboard returns v1 + v2 tvl.  you compute only v1 tvl.

v2 have usdc-usdt stableswap pool

you can check here 
https://scope.klaytn.com/account/0xF8C8F1346c2f99F9Dd250e7986477Fb13A7af0D6?tabId=txList

https://github.com/claimswap/claimswap-contract

**Comment by g1nt0ki** [comment]
@TurutuParapara ah, I missed that. I think it is better to have separate listing for v2, I have created this: https://github.com/DefiLlama/DefiLlama-Adapters/commit/19fe0c3ad0d9a65d4b232ca1df2c94a7b8622453

**Comment by TurutuParapara** [comment]
@g1nt0ki  Thank you.

**Pull request closed without merging**
