### PR TITLE
ADD:letsfil

### PR DESCRIPTION
**Pull request by honey1129**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/letsfil exports TVL: 
        
 
 
    filecoin                  0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/letsfil exports TVL: 
        
 
 
    filecoin                  9.38
    
    total                    9.38

**Comment by g1nt0ki** [comment]
@honey1129 the code loos good, can you fill the project details in the form in PR description?

**Comment by honey1129** [comment]
- Name (to be shown on DefiLlama): FilFi
- Twitter Link: https://twitter.com/filfi_io
- List of audit links if any:
- Website Link: filfi.io
- Logo :https://internal-api-drive-stream.feishu.cn/space/api/box/stream/download/v2/cover/QvqjbfA5aoeJqsxFemxcepMrnng/?fallback_source=1&height=1280&mount_node_token=PehSdNMZnoNZa2xnvk3cbJW3ned&mount_point=docx_image&policy=equal&width=1280

- Current TVL: 35,000 FIL deposit 
- Treasury Addresses (if the protocol has treasury)
- Chain: Filecoin 
- Coingecko ID ：filecoin
- Coinmarketcap ID ：2280
- Short Description (to be shown on DefiLlama): FilFi is a DeFi protocol that creates the liquidity of Filecoin assets, providing services such as staking pool, lending, Joint Mining, hashrate trading, and FID funds. Tokenized assets are seamlessly connected to DEX for maximum liquidity. The goal of FilFi is to create a permissionless liquidity market for the Filecoin community, achieve fully decentralized DeFi, reduce trust costs, expand social participation, and accelerate the construction of the Filecoin network.
- Token address and ticker if any:
- Category (full list at https://defillama.com/categories) *Please choose only one: Liquid Staking
- Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
- forkedFrom (Does your project originate from another project):
- methodology (what is being counted as tvl, how is tvl being calculated):

**Comment by honey1129** [comment]
@g1nt0ki the above is our latest project information,thank you very much.

**Comment by honey1129** [comment]
@g1nt0ki Hi,admin.Our projects's category is seem wrong! There is the true category:**Liquid Staking**

**Pull request merged**
