### PR TITLE
feat: added BooFinance adapter

### PR DESCRIPTION
**Pull request by jccrlz**
##### Twitter Link:
[https://twitter.com/Boo_Finance](https://twitter.com/Boo_Finance)

##### Website Link:
[https://www.boofinance.io/](https://www.boofinance.io/)

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
[https://www.boofinance.io/assets/images/general/boofi-ghost.svg](https://www.boofinance.io/assets/images/general/boofi-ghost.svg)

##### Current TVL:
37M

##### Chain:
43114

##### Coingecko ID (so your TVL can appear on Coingecko): 
boo-finance  ([https://www.coingecko.com/en/coins/boo-finance](https://www.coingecko.com/en/coins/boo-finance))

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap)
boo-finance  ([https://coinmarketcap.com/currencies/boo-finance](https://coinmarketcap.com/currencies/boo-finance))

##### Short Description (to be shown on DefiLlama):
The Boo Finance Protocol is pioneering DeFi 3.0 with optimized, competitive yield-farming and staking with deflationary NFTs and DAO on the Avalanche Network.

##### Token address and ticker if any:
BOOFI ([0xb00f1ad977a949a3ccc389ca1d1282a2946963b0](https://snowtrace.io/token/0xb00f1ad977a949a3ccc389ca1d1282a2946963b0))

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Yield

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
TWAP

##### forkedFrom (Does your project originate from another project):
BooFinance doesn't use any fork.

##### methodology (what is being counted as tvl, how is tvl being calculated):
The total TVL for BooFinance is obtained from within our Oracle and accounts the Cauldron, Well of Souls and Stake TVLs

### CODE REVIEW

**Comment by 0xngmi** [comment]
pls use on-chain calls instead

**Comment by jccrlz** [comment]
Hey @0xngmi , thanks for the Input, I can see many projects using their own APIs to fetch this data, so my guess is that the problem is requesting the data directly from the contracts on the current timestamp?. 

If that's the case, we can deliver just that!

**Comment by 0xngmi** [comment]
I try to minimize APIs used (explanation for that here: https://github.com/DefiLlama/DefiLlama-Adapters/discussions/432).

There's some cases were we use APIs, these are mostly legacy adapters or adapters that would be difficult to write with on-chain calls.

Really suggest reading the linked discussion about it.

**Comment by jccrlz** [comment]
I understand your concern and I think it's valid, we could easily provide calculations for Stake and the Well of Souls TVLs
The Cauldron though is more complicated because 

- We have a growing list of tokens. 
- We calculate the prices of Tokens and LP Tokens from different sources (ATM Trader Joe, Lydia, Pangolin) by our selves using different strategies that won't be available on your adapters. 
- If we did all the calculations on-chain through our TWAP Oracle pricing data, liquidity will be different because their prices are not updated with the same frequency ending on inaccurate results. 
- The amount of requests to do this properly is considerable, we keep it synchronized and under control by refreshing under Smart Contract event emissions along Cron jobs, It feels really counterproductive to create a completely new system.
It probably won't be good for your nodes either.

I would appreciate it if we can get to a middle ground on this, thank you  @0xngmi

**Comment by 0xngmi** [comment]
is your api and all the parts needed to reproduce the results open source? that would help a lot

**Comment by jccrlz** [comment]
It isn't ATM I'm afraid, but we are willing to release one publicly if it helps!

**Comment by waynebruce0x** [comment]
Closing since nemusona has written an on-chain version. Please message us in discord if you'd like any changes to be made, the PR reopening, or anything else

**Comment by jccrlz** [comment]
> Closing since nemusona has written an on-chain version. Please message us in discord if you'd like any changes to be made, the PR reopening, or anything else

thanks for the support guys, means a lot!

**Pull request closed without merging**
