### PR TITLE
Add WSPP Adapter

### PR DESCRIPTION
**Pull request by WSPPmultichain**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/wspp exports TVL: 
        
 
 
    kardia                    299.76 k
    kardia-staking            928.5338795726066
    staking                   928.5338795726066
    
    total                    299.76 k

**Comment by realdealshaman** [comment]
Hey, thanks a lot for submitting the adapter. Would it be possible to have the adapter provide an on-chain calculation that returns the tvl? We are working on converting all previously merged api adapters to on-chain to improve transparency so we'd prefer to not merge another api adapter. Also, please revert the changes to the listing template, you can add the listing info here as a comment and we'll pull it from there, thanks again

**Comment by WSPPmultichain** [comment]
Twitter Link:
https://twitter.com/robowolf8
List of audit links if any:
ttps://www.certik.com/projects/wolf-safe-poor-people
Website Link:
main Website ->> https://wolfsafepoorpeople.com
Dapps -->> https://wolfible.com
Docs -->> https://docs.wolfible.com
Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://wolfible.com/images/logo-wspp.png

Current TVL:

BSC -->> $40.000
Polygon -->> $5000
Fantom -->> $3000
KardiaChain -->> $3000
Avalanche -->> $3000

Chain:
BSC, Polygon, Fantom, Avalanche, KardiaChain

Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

BSC ->> "id":"wolfsafepoorpeople"
Polygon, Fantom, Avalanche, KardiaChain ->> "id":"wolfsafepoorpeople-polygon"

Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
BSC ->>  "id":10841
Polygon, Fantom, Avalanche, KardiaChain ->>  "id":13119

Short Description (to be shown on DefiLlama):
WolfSafePoorPeople is a NFT , Staking & Yield Farming Dapps

Token address and ticker if any:
BSC -->> https://bscscan.com/token/0x46d502fac9aea7c5bc7b13c8ec9d02378c33d36f
Polygon -->> https://polygonscan.com/token/0x46d502fac9aea7c5bc7b13c8ec9d02378c33d36f
Fantom -->> https://ftmscan.com/token/0x685a211c9d96d0c8c9d22b7ae309538d4c69c15c
KardiaChain -->> https://explorer.kardiachain.io/token/0xccB32737C6dFfddFFB24CA8A96b588ac7b1822e7
Avalanche -->> https://snowtrace.io/token/0xe668f8030bf17f3931a3069f31f4fa56efe9dd54

Category (full list at https://defillama.com/categories) *Please choose only one:
Yield

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
forkedFrom (Does your project originate from another project):
methodology (what is being counted as tvl, how is tvl being calculated):

**Comment by g1nt0ki** [comment]
@WSPPmultichain sorry, I am closing this PR, I have copied your listing info to https://github.com/DefiLlama/DefiLlama-Adapters/pull/3551. What do you want the protocol to be called WolfSafePoorPeople or Wolfible ?

**Comment by WSPPmultichain** [comment]
WolfSafePoorPeople
please

**Pull request closed without merging**
