### PR TITLE
feat update fortube-v3 tvl

### PR DESCRIPTION
**Pull request by lrmuyi**

### CODE REVIEW

**Comment by 0xngmi** [comment]
I took a look at this one month ago but I couldn't really find where the TVL reported on that endpoint is coming from:

**Comment by 0xngmi** [comment]
The numbers on the previous image are outdated now but if you could help me find out how that number is calculated I'd appreciate it.

**Comment by zhuoyue95** [comment]
The TVL is calculated from sum of the product of the value locked (in token amount) and its current price for each asset, in which the value locked for each asset requires more complicated calculation due to accrued and unaccrued interest for both deposits and loans. We calculate the value locked for an asset as follows:

value_locked = deposits - withdrawals - loans + repayments + repayments_through_liquidation

**Comment by 0xngmi** [comment]
Thanks for the PR!

**Pull request merged**
