### PR TITLE
Use different tron api

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/binance exports TVL: 
        
 
 
    tron                      11.12 B
    bsc                       11.70 B
    ethereum                  35.12 B
    bitcoin                   6.76 B
    
    total                    64.70 B

**Comment by llamatester** [comment]
The adapter at projects/bitfinex exports TVL: 
        
 
 
    algorand                  5.85 M
    zilliqa                   3.99 M
    aptos                     1.96 M
    solana                    4.70 M
    elrond                    555.41 k
    tron                      304.76 M
    ethereumclassic           4.29 M
    near                      2.95 M
    avax                      2.62 M
    fantom                    2.92 M
    polygon                   15.19 M
    bitcoin                   3.36 B
    ethereum                  1.58 B
    tezos                     2.20 M
    cardano                   3.08 M
    cosmos                    774.70 k
    eos                       8.77 M
    
    total                    5.31 B

**Comment by llamatester** [comment]
The adapter at projects/huobi exports TVL: 
        
 
 
    bitcoin                   742.74 M
    solana                    3.25 M
    avax                      21.71 M
    algorand                  31.76 M
    tron                      148.41 M
    ethereum                  832.63 M
    polygon                   15.59 M
    
    total                    1.80 B

**Comment by llamatester** [comment]
The adapter at projects/kucoin exports TVL: 
        
 
 
    tron                      123.66 M
    algorand                  136.12 M
    eos                       51.84 M
    kcc                       960.23 k
    arbitrum                  27.21 M
    ethereum                  1.69 B
    bitcoin                   309.24 M
    
    total                    2.34 B

**Comment by llamatester** [comment]
The adapter at projects/okex exports TVL: 
        
 
 
    bitcoin                   1.51 B
    polygon                   33.45 M
    avax                      3.10 M
    tron                      283.70 M
    arbitrum                  215.97 M
    ethereum                  3.69 B
    
    total                    5.73 B

**Comment by SamuelRoguez** [comment]
Perfesto

**Pull request merged**
