### PR TITLE
MarSwap Update

### PR DESCRIPTION
**Pull request by topleft1562**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/marswap: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:192:11

**Comment by llamatester** [comment]
Error while running adapter at projects/marswap: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:192:11

**Comment by topleft1562** [comment]
Any help as to why this isnt working? Mimic'd other platforms with multiple

**Comment by llamatester** [comment]
The adapter at projects/marswap exports TVL: 
        
 
 
    bsc                       2.36 k
    shibarium                 865.66 k
    ethereum                  14.69 k
    
    total                    882.70 k

**Comment by llamatester** [comment]
Error while running adapter at projects/marswap: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:192:11

**Comment by llamatester** [comment]
The adapter at projects/marswap exports TVL: 
        
 
 
    cronos                    0
    bsc                       2.36 k
    base                      0
    ethereum                  14.70 k
    shibarium                 867.82 k
    
    total                    884.88 k

**Comment by topleft1562** [comment]
Thanks! got it.

**Comment by llamatester** [comment]
The adapter at projects/marswap exports TVL: 
        
 
 
    base                      0
    cronos                    0
    bsc                       2.36 k
    ethereum                  14.70 k
    
    total                    17.05 k

**Comment by llamatester** [comment]
Error while running adapter at projects/marswap: 
        
 
  
    
    
    TypeError: TVL_SHIBARIUM_V1.map is not a function
    Truncated error stack:
    
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/marswap/index.js:14:37)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:48:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:137:9
        at async Promise.all (index 0)
        at async Promise.all (index 2)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:180:3

**Comment by llamatester** [comment]
Error while running adapter at projects/marswap: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:192:11

**Comment by llamatester** [comment]
The adapter at projects/marswap exports TVL: 
        
 
 
    base                      0
    cronos                    0
    bsc                       2.39 k
    shibarium                 875.78 k
    ethereum                  14.86 k
    
    total                    893.03 k

**Comment by llamatester** [comment]
The adapter at projects/marswap exports TVL: 
        
 
 
    cronos                    0
    base                      0
    bsc                       2.39 k
    ethereum                  14.85 k
    shibarium                 880.23 k
    
    total                    897.47 k

**Pull request merged**
