### PR TITLE
Typus/safu

### PR DESCRIPTION
**Pull request by WayneAl**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Typus Safu

##### Twitter Link:
https://x.com/typusfinance

##### Website Link:
https://typus.finance/safu/

##### Logo (High resolution, will be shown with rounded borders):
same as Typus Finance

##### Current TVL:
403.70 k 

##### Chain:
SUI

##### Short Description (to be shown on DefiLlama):
Typus SAFU is the first principal-protected structured product on the Sui Blockchain. It offers safe yields with 99.99% principal protection, zero fees for both bull and bear strategies, and potential upside through options. This product is designed to securely maximize your crypto returns.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
[Yield](https://defillama.com/protocols/Yield)

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Pyth, Supra

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/Typus-Lab

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/typus-finance exports TVL: 
        
 
 
    sui                       9.00 M
    
    total                    9.00 M

**Comment by llamatester** [comment]
The adapter at projects/typus-safu exports TVL: 
        
 
 
    sui                       403.10 k
    
    total                    403.10 k

**Comment by WayneAl** [comment]
Hi, this Typus Safu is under the parent protocol Typus Finance, 
and we want rename the original Typus Finance as Typus DOV.
Thank you!

Typus Finance
  1. Typus DOV
  2. Typus Safu

**Comment by llamatester** [comment]
The adapter at projects/typus-finance exports TVL: 
        
 
 
    sui                       9.02 M
    
    total                    9.02 M

**Comment by llamatester** [comment]
The adapter at projects/typus-safu exports TVL: 
        
 
 
    sui                       404.09 k
    
    total                    404.09 k

**Comment by g1nt0ki** [comment]
@WayneAl thanks for the PR

**Pull request merged**
