### PR TITLE
Get protocol integration

### PR DESCRIPTION
**Pull request by mantasfam**
Get protocol is already listed on DefiLlama, but its TVL is not yet calculated.
https://defillama.com/protocol/get-protocol

This script provides GET protocol staked value calculation.
https://token.get-protocol.io/

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/get-protocol exports TVL: 
        
 
 
    ethereum                  0
    polygon                   0
    polygon-staking           564.64 k
    ethereum-staking          5.34 M
    staking                   5.90 M
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/get-protocol exports TVL: 
        
 
 
    ethereum                  5.34 M
    polygon                   564.64 k
    
    total                    5.90 M

**Comment by g1nt0ki** [comment]
@mantasfam you were right in your initial commit, we count own tokens under staking

**Comment by llamatester** [comment]
The adapter at projects/get-protocol exports TVL: 
        
 
 
    ethereum                  0
    polygon                   0
    polygon-staking           564.74 k
    ethereum-staking          5.28 M
    staking                   5.85 M
    
    total                    0

**Pull request merged**
