### PR TITLE
Adding BakerFi to DefiLlama

### PR DESCRIPTION
**Pull request by hvasconcelos**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
 BakerFi

##### Twitter Link:

[@BakerFi_](https://twitter.com/bakerfi_)

##### Website Link:
https://bakerfi.xyz/

##### Logo (High resolution, will be shown with rounded borders):
https://bakerfi.xyz/logo-512-color.png

##### Current TVL:
1200$

##### Chain:
arbitrum

##### Short Description (to be shown on DefiLlama):
BakerFi is an innovative DeFi protocol designed to optimize asset growth through efficient staking, re-staking, and recursive strategies, all aimed at enhancing the APY for users. Our platform automates these strategies, streamlining capital allocation, and offers a user-friendly interface accessible to all levels of expertise. Whether you're a novice or seasoned investor, BakerFi provides a seamless experience to maximize your returns.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Liquid Staking

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Pyth Network

##### Implementation Details: Briefly describe how the oracle is integrated into your project:
The Oracles are used to calculated positions and manage strategy liquidations .

##### methodology (what is being counted as tvl, how is tvl being calculated):
It retrieves the total amount of assets deployed on BakerFi vaults, on all the chains.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/baker-fi

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bakerfi exports TVL: 
        
 
 
    arbitrum                  1.29 k
    
    total                    1.29 k

**Comment by llamatester** [comment]
The adapter at projects/bakerfi exports TVL: 
        
 
 
    arbitrum                  1.36 k
    
    total                    1.36 k

**Comment by g1nt0ki** [comment]
@hvasconcelos thanks for the PR

**Comment by Define101** [comment]
And its from the same team correct? https://defillama.com/protocol/bepro-network

**Comment by Define101** [comment]
Also is TKAI the new bepro token? Or both tokens are separated

**Comment by hvasconcelos** [comment]
> And its from the same team correct? https://defillama.com/protocol/bepro-network

No. This is a completely new project.

**Comment by hvasconcelos** [comment]
> Also is TKAI the new bepro token? Or both tokens are separated

Bepro is Bepro Network Token and TKAI is the Taikai Network Token . This project does not belong to LayerX company.

**Comment by hvasconcelos** [comment]
> @hvasconcelos Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
> 
> And maybe remove the private comments from your team members on the notion docs page. After running them on google translation, they do not look very good to be honest

Currently, we are working on the documentation, we have only a draft version.

**Pull request merged**
