### PR TITLE
Add MultiBit($MUBI) Protocol

### PR DESCRIPTION
**Pull request by pipi-multibit**
##### Name (to be shown on DefiLlama):
MultiBit Protocol

##### Twitter Link:
https://twitter.com/Multibit_Bridge

##### List of audit links if any:
https://github.com/multibit-repo
https://t.me/multibitprotocol

##### Website Link:
https://multibit.exchange/

##### Logo (High resolution, will be shown with rounded borders):
https://raw.githubusercontent.com/multibit-repo/MediaResources/b9043b0d17aeae453113f53e94c0a784e859043a/logo.svg
https://github.com/multibit-repo/MediaResources/blob/main/logo.svg

##### Current TVL:

```txt
--- polygon ---
MUBI 5.126428208
Total: 5.126428208

--- ethereum ---
MUBI 247.93 M
BSSB 87.69 M
foox 7.58 M
Rait 6.20 M
WHEE 117.51 k
USDT 12.04 k
Total: 349.53 M

--- bsc ---
MUBI 752.5983565604056
B2B 132.08803643759242
Total: 884.686392997998

--- tvl ---
MUBI 247.93 M
BSSB 87.69 M
foox 7.58 M
Rait 6.20 M
WHEE 117.51 k
USDT 12.04 k

------ TVL ------
polygon 5.126428208
ethereum 349.53 M
bsc 884.686392997998

total 349.53 M
```

**Hot Wallet:**
- `bc1p6r6hx759e3ulvggvd9x3df0rqh27jz59nvfjd2fzmh3wqyt6walq82u38z`

**Cold wallet:**
- `bc1pyyms2ssr0hagy5j50r5n689e6ye0626v3c98j5fw0jk6tz3vrgts7nt56g`
- `bc1qmcrpqanjnrw58y0fvq08fqchgxv5aylctew7vxlkalfns3rpedxsx4hxpu`

##### Chain:
Ethereum、BSC、Polygon

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

```json
{ "id": "multibit", "symbol": "mubi", "name": "Multibit" }
```

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

```json
{
  "id": 28412,
  "name": "Multibit",
  "symbol": "MUBI",
  "slug": "multibit"
}
```

##### Token address and ticker if any:
`0x38e382F74dfb84608F3C1F10187f6bEf5951DE93`

##### Category (full list at https://defillama.com/categories) \*Please choose only one:
Bridge

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
NUll

##### forkedFrom (Does your project originate from another project):
Creator

##### methodology (what is being counted as tvl, how is tvl being calculated):
```txt
When a user passes the bridge from the BTC chain using BRC20 assets, Tokens will be minted on the EVM chain.

When users use ERC20 assets from the EVM chain to pass through the bridge, Tokens will be burned in the EVM chain.

Since BRC20 assets cannot be calculated, only the assets generated when crossing the bridge need to be calculated.
```

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/multibit-repo

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/mutibit exports TVL: 
        
 
 
    polygon                   5.06147664
    bsc                       875.4780313490106
    ethereum                  343.63 M
    
    total                    343.63 M

**Comment by llamatester** [comment]
The adapter at projects/mutibit exports TVL: 
        
 
 
    bsc                       887.3498786874064
    polygon                   5.137689743999999
    ethereum                  351.02 M
    
    total                    351.02 M

**Comment by g1nt0ki** [comment]
hi @pipi-multibit can you share the bridge address on bitcoin where the brc20 tokens are locked? I will try to add support for it, we prefer counting tvl at source chain for bridges.

Also, we cant count MUBI or BSSB as tvl, these are tokens related to the project

**Comment by pipi-multibit** [comment]
> hi @pipi-multibit can you share the bridge address on bitcoin where the brc20 tokens are locked? I will try to add support for it, we prefer counting tvl at source chain for bridges.
> 
> Also, we cant count MUBI or BSSB as tvl, these are tokens related to the project

@g1nt0ki 
Thanks for your comment.
I will resubmit the code and update the code content.

This is the asset wallet for BTC

**Hot Wallet:** `https://www.oklink.com/cn/btc/address/bc1p6r6hx759e3ulvggvd9x3df0rqh27jz59nvfjd2fzmh3wqyt6walq82u38z/balance`

**Cold wallet:**
`https://www.oklink.com/cn/btc/address/bc1pyyms2ssr0hagy5j50r5n689e6ye0626v3c98j5fw0jk6tz3vrgts7nt56g/balance`

**Comment by pipi-multibit** [comment]
I will resubmit a PR

**Comment by llamatester** [comment]
The adapter at projects/multibit exports TVL: 
        
 
 
    bsc-staking               0
    polygon-staking           0
    bitcoin                   0
    bitcoin-staking           0
    ethereum-staking          182.20 M
    bsc                       1.03 k
    ethereum                  398.39 M
    polygon                   6.1916602880000005
    staking                   182.20 M
    
    total                    398.39 M

**Comment by llamatester** [comment]
The adapter at projects/multibit exports TVL: 
        
 
 
    bsc-staking               0
    polygon-staking           0
    bitcoin                   0
    bitcoin-staking           0
    ethereum-staking          182.20 M
    bsc                       1.03 k
    polygon                   6.1916602880000005
    ethereum                  398.39 M
    staking                   182.20 M
    
    total                    398.39 M

**Comment by pipi-multibit** [comment]
# Update log
- Added Staking asset view

**Comment by g1nt0ki** [comment]
hi @pipi-multibit sorry for the delay, I was working on adding support for pricing brc20 token on server-side: https://github.com/DefiLlama/defillama-server/commit/fcfb6dbe5074d41ebba3900d751b1a2edff6448b

now that that is done, I will work on adding support for adding brc20 token balances on wallets

**Comment by g1nt0ki** [comment]
hi @pipi-multibit I have refactored the code here to use tvl from bitcoin side: https://github.com/DefiLlama/DefiLlama-Adapters/pull/8476

**Comment by pipi-multibit** [comment]
> hi @pipi-multibit I have refactored the code here to use tvl from bitcoin side: #8476

@g1nt0ki 

Thank you very much for the code refactoring, is there anything I can do for you?

I see that the branch has been merged #8476 ,
 how can I check it in defillama.com?

**Comment by g1nt0ki** [comment]
it is listed here: https://defillama.com/protocol/multibit-protocol

I have replied to your comment

**Pull request closed without merging**
