### PR TITLE
Add sturgeon and refactor code

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/sturgeon exports TVL: 
        
 
 
    real                      0
    
    total                    0.32333489729074066

**Review by a17 — CHANGES_REQUESTED** [review]
While reviewing I found two problems:

* need to use `getTotalAmounts`, i requested changes
* arcUSD. as example, has price on coingecko (coingeckoId: 'arcana-2'), but not show price by this URL `https://coins.llama.fi/prices/current/real:0xb08f026f8a096e6d92eb5bcbe102c273a7a2d51c,real:0x4644066f535ead0cde82d209df78d94572fcbf14,real:0x90c6e93849e06ec7478ba24522329d14a5954df4,real:0x83fedbc0b85c6e29b589aa6bdefb1cc581935ecd,real:0xaec9e50e3397f9ddc635c6c429c8c7eca418a143,real:0x25ea98ac87a38142561ea70143fd44c4772a16b6,real:0x75d0cbf342060b14c2fc756fd6e717dfeb5b1b70,real:0xce1581d7b4ba40176f0e219b2cac30088ad50c7a,real:0x835d3e1c0aa079c6164aad21dcb23e60eb71af48`

**Comment by a17** [comment]
@g1nt0ki As I understand it, the test script uses a deployed API, which does not know about Coingeco ID for arcUSD and others tokens.
That is, the second problem can be solved by itself.

**Comment by llamatester** [comment]
The adapter at projects/sturgeon exports TVL: 
        
 
 
    real                      7.82 k
    
    total                    7.82 k

**Comment by g1nt0ki** [comment]
@a17 thanks for the review, fixed based on your comments

**Pull request merged**
