### PR TITLE
jewelswap-farm-update

### PR DESCRIPTION
**Pull request by combased-dev**
This is an update for already existing JewelSwap farm module, adding two new farms and LPs

@g1nt0ki not sure why the deployment fails, it could be because of your custom backend hook.

Also, is there any way to kinda include DefiLama as an iFrame widget to our website with up to date data? :)

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/jewelswap-lev-farming: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by Define101** [comment]
Hello Combased Dev
Regarding the iframe, yes would be possible
image
image

<iframe width="640px" height="360px" src="https://defillama.com/chart/protocol/jewelswap?&include_pool2_in_tvl=true&include_staking_in_tvl=true&include_borrowed_in_tvl=true" title="DefiLlama" frameborder="0"></iframe>

**Comment by combased-dev** [comment]
thanks @Define101, let me know when you can approve the PR, thanks!

**Comment by combased-dev** [comment]
thanks, @realdealshaman let me know once this should be reflected in the website, to double-check :)

**Pull request merged**
