### PR TITLE
add sdk adapter for project liquid finance protocol

### PR DESCRIPTION
**Pull request by bof195**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Liquid Finance Protocol

##### Twitter Link:
https://twitter.com/liquid_finance

##### List of audit links if any:
N/A

##### Website Link:
https://liquidfinance.xyz/

##### Logo (High resolution, will be shown with rounded borders):
Liquid_Finance_Logo

##### Current TVL: 
$27k

##### Treasury Addresses (if the protocol has treasury)
N/A

##### Chain:
Archway

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

##### Short Description (to be shown on DefiLlama):
Liquid Finance is a liquid staking protocol where users can stake ARCH for sARCH on the Archway blockchain.

##### Token address and ticker if any:
N/A

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Liquid Staking

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
N/A

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL equals the sum of ARCH staked in the Liquid Finance Stake Pool and ARCH liquidity provided in the Liquid Finance Instant Unstaking Queue, multiplied by the current ARCH price.

##### Github org/user (Optional, if your code is open source, we can track activity):
N/A

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/liquid-finance-protocol exports TVL: 
        
 
 
    archway                   27.43 k
    
    total                    27.43 k

**Comment by bof195** [comment]
this is correct!

**Comment by llamatester** [comment]
The adapter at projects/liquid-finance-arch exports TVL: 
        
 
 
    archway                   26.80 k
    
    total                    26.80 k

**Comment by g1nt0ki** [comment]
thanks for the PR, it looks good, I just renamed the folder

**Pull request merged**
