### PR TITLE
Use numoen subgraph for more accurate data

### PR DESCRIPTION
**Pull request by kyscott18**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Numoen

##### Twitter Link:
twitter.com/numoen

##### List of audit links if any:
https://www.certik.com/projects/numoen
https://github.com/code-423n4/2023-01-numoen-findings

##### Website Link:
numoen.com

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
numoen

##### Current TVL:
57k

##### Treasury Addresses (if the protocol has treasury)
N/a

##### Chain:
Arbitrum, Celo

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
N/a

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/a

##### Short Description (to be shown on DefiLlama):
An automated liquidity provider for an option-like derivative called Power Tokens

##### Token address and ticker if any:
N/a

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Derivatives

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
N/a

##### forkedFrom (Does your project originate from another project):
N/a

##### methodology (what is being counted as tvl, how is tvl being calculated):
Count all assets currently in underlying AMMS and assets being used as collateral (no double counting)

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/numoen exports TVL: 
        
 
 
    arbitrum                  56.47 k
    celo                      610.3675246436591
    
    total                    57.08 k

**Comment by g1nt0ki** [comment]
hi @kyscott18, I am not a fan of graphs as it is maintenance headache compared to using logs, can you verify that this refactor is correct: https://github.com/DefiLlama/DefiLlama-Adapters/commit/4af92619b26a25b8328c30f7378b1986f7962240


the issue was, I was looking at only one of two factories in arbitrum `0x1B327eFf5033922B0f88FC4D56C29d7AF5a8ecdB`, noticed that tvl in this factory is not included in graph/your PR. is that intentional? should I ignore it as well?

**Comment by kyscott18** [comment]
Hi @g1nt0ki this look correct. Does it also output the same number? The factory `0x1B327eFf5033922B0f88FC4D56C29d7AF5a8ecdB` is our beta version and it makes sense to include it as well I just forgot. Thank you

**Comment by g1nt0ki** [comment]
yup, the numbers match, I verified it earlier, closing this PR.

**Pull request closed without merging**
