### PR TITLE
Use Rari API

### PR DESCRIPTION
**Pull request by TransmissionsDev**
This PR updates the Rari Capital TVL fetching to use our API instead of fetching manually.

### CODE REVIEW

**Comment by 0xngmi** [comment]
Thanks for the PR. Do you have an API/subgraph from which we could pull historical TVLs or vault addresses? I'm trying to improve the historical graphs of protocols by moving the adapters to a new standard that makes it possible to get a protocol's TVL at a point in time.

**Comment by TransmissionsDev** [comment]
> Thanks for the PR. Do you have an API/subgraph from which we could pull historical TVLs or vault addresses? I'm trying to improve the historical graphs of protocols by moving the adapters to a new standard that makes it possible to get a protocol's TVL at a point in time.

We have a prometheus instance that tracks our TVL... would that be useable?

**Comment by 0xngmi** [comment]
Is prometheus [this](https://prometheus.io/)? If we can query TVL by timestamp or if we can get a list of timestamps and TVLs associated that would be enough.

**Comment by TransmissionsDev** [comment]
> Is prometheus [this](https://prometheus.io/)? If we can query TVL by timestamp or if we can get a list of timestamps and TVLs associated that would be enough.

Yep yep. When you guys start doing retroactive fetching let us know and we can help get everything setup

**Comment by 0xngmi** [comment]
It seems like the API endpoint is down

**Comment by TransmissionsDev** [comment]
> It seems like the API endpoint is down @TransmissionsDev

Indeed sorry! Working on resolving asap.

**Pull request merged**
