### PR TITLE
Please add Liquity TVL 

### PR DESCRIPTION
**Pull request by edmulraney**
##### List of audit links if any: 
- Trail of Bits: https://github.com/trailofbits/publications/blob/master/reviews/Liquity.pdf
- Coinspect: https://www.coinspect.com/liquity-audit/

##### Coingecko ID (so your TVL can appear on Coingecko): 
- liquity https://www.coingecko.com/en/coins/liquity
- liquity-usd https://www.coingecko.com/en/coins/liquity-usd

##### Token address and ticker if any:
- LQTY: https://etherscan.io/token/0x6DEA81C8171D0bA574754EF6F8b412F2Ed88c54D
- LUSD: https://etherscan.io/token/0x5f98805A4E8be255a32880FDeC7F6728C6568bA0

### CODE REVIEW

**Comment by 0xngmi** [comment]
# the fastest listing in the wild west
image

**Comment by 0xngmi** [comment]
Sent [llamapunk #2](https://opensea.io/assets/0x495f947276749ce646f68ac8c248420045cb7b5e/51396440632719600673961636451910493832954413281301989130995708881239764107265). Thanks for the adapter!

**Comment by 0xngmi** [comment]
Hey, recently noticed that defipulse has a different TVL from ours, is there something we are missing in our calculation?

**Comment by edmulraney** [comment]
Hey @0xngmi they started including the deposited LUSD in the Stability Pool as TVL. I can make a PR next week

**Pull request merged**
