### PR TITLE
Add Agdex Adapter

### PR DESCRIPTION
**Pull request by yuyin-zhang**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
**AGDEX**

##### Twitter Link:
**https://x.com/agdex_io**

##### List of audit links if any:
**https://docs.agdex.io/aduit**

##### Website Link:
**https://agdex.io/**

##### Logo (High resolution, will be shown with rounded borders):
agdexLogo

##### Current TVL:
**$1.521k**

##### Treasury Addresses (if the protocol has treasury)
**N/A**

##### Chain:
**APTOS**

##### Short Description (to be shown on DefiLlama):
**Next-gen Decentralized Perpetual Exchange. Instantly trade BTC, ETH, APT, and more with up to 100x leverage directly from your wallet. No sign-up. No deposits are needed.**

##### Category (full list at https://defillama.com/categories) *Please choose only one:
**Derivatives**

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
**PYTH, SWITCHBOARD, SUPRA**

##### Implementation Details: Briefly describe how the oracle is integrated into your project:
**Our protocol utilizes multiple oracles for price retrieval and monitoring, ensuring strict control over data sources and their reliability. The aforementioned oracle contracts are referenced to construct the smart contracts, with rigorous checks on oracle parameters such as the latest update time and data credibility.**

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
**GitHub: https://github.com/agdex-io/perpetual-contract
Contract Explorer: https://explorer.aptoslabs.com/account/0xfa69897532f069bc0806868eaeec3328727d90c0cec710a17dde327e0bfab44f/modules/code/admin?network=mainnet
You can verify the proper use of oracles in our smart contracts through our official repository and the APTOS Explorer.**

##### forkedFrom (Does your project originate from another project):
**N/A**

##### methodology (what is being counted as tvl, how is tvl being calculated):
**Our protocol uses APT, BTC, ETH, USDT, and USDC as liquidity assets. These assets are aggregated as AGLP, which is a synthetic token. The TVL is calculated by retrieving the quantity of staked assets in the liquidity pools through on-chain data from smart contracts.**

##### Github org/user (Optional, if your code is open source, we can track activity):
**https://github.com/agdex-io**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/agdex: 
        
 
  
    
    
    Error: Failed to post https://fullnode.mainnet.aptoslabs.com/v1/view
    Truncated error stack:
    
        at Object.post (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/http.js:47:11)
        at async function_view (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/aptos.js:103:20)
        at async tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/agdex/index.js:35:5)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:173:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:216:3

**Comment by yuyin-zhang** [comment]
hi, how did you run the adapter? how can I debug on my side? Thank you.

**Comment by g1nt0ki** [comment]
hi @yuyin-zhang the command to test adapter is `node test.js projects/agdex` 

I am unsure why it is failing

**Comment by yuyin-zhang** [comment]
> hi @yuyin-zhang the command to test adapter is `node test.js projects/agdex`
> 
> I am unsure why it is failing

thank uu, checking the code

**Comment by llamatester** [comment]
Error while running adapter at projects/agdex: 
        
 
  
    
    
    Error: Failed to post https://fullnode.mainnet.aptoslabs.com/v1/view
    Truncated error stack:
    
        at Object.post (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/http.js:47:11)
        at async function_view (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/aptos.js:103:20)
        at async tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/agdex/index.js:35:5)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:173:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:216:3

**Comment by llamatester** [comment]
The adapter at projects/agdex exports TVL: 
        
 
 
    aptos                     2.87 k
    
    total                    2.87 k

**Comment by yuyin-zhang** [comment]
Hiii, just pushed a new one

**Pull request merged**
