### PR TITLE
Adding Dinari to DefiLlama

### PR DESCRIPTION
**Pull request by joshualyguessennd**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Dinari

##### Twitter Link:
[https://x.com/dinariglobal?s=21](https://x.com/dinariglobal?s=21)

##### Website Link:
[https://dinari.com](dinari.com)

##### Logo (High resolution, will be shown with rounded borders):
[https://drive.google.com/file/d/1G6Kqut3Z3_9c-maaaInHFNnsoASJWh_1/view?usp=sharing](logo)

##### Current TVL:
280,874.47

##### Treasury Addresses (if the protocol has treasury)
0x5993493bBAE251122Bd2dAb106D12a809fdB852d

##### Chain:
Arbitrum

##### Short Description (to be shown on DefiLlama):

Dinari dShares revolutionizes access to global stock markets by leveraging blockchain technology, enabling seamless, transparent trading of real-world assets worldwide. Our platform bridges traditional finance and DeFi, democratizing investment in major stocks for a global audience.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
RWA

##### methodology (what is being counted as tvl, how is tvl being calculated):
The total value of dshare(stock token) on-chain

##### Github org/user (Optional, if your code is open source, we can track activity):
[https://github.com/dinaricrypto/sbt-contracts](dinaricrypto/sbt-contracts)

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/dinari exports TVL: 
        
 
 
    arbitrum                  35.15 k
    
    total                    35.15 k

**Comment by llamatester** [comment]
The adapter at projects/dinari exports TVL: 
        
 
 
    arbitrum                  35.15 k
    
    total                    35.15 k

**Comment by llamatester** [comment]
The adapter at projects/dinari exports TVL: 
        
 
 
    arbitrum                  35.15 k
    
    total                    35.15 k

**Comment by llamatester** [comment]
The adapter at projects/dinari exports TVL: 
        
 
 
    arbitrum                  35.15 k
    
    total                    35.15 k

**Comment by llamatester** [comment]
The adapter at projects/dinari exports TVL: 
        
 
 
    arbitrum                  0
    
    total                    0

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
hi @joshualyguessennd can you do what we did for backedfi, add a coins adapter similar to this: https://github.com/DefiLlama/defillama-server/blob/master/coins/src/adapters/rwa/backed.ts

and here, you count only the token supply. the perk of this is, when other protocols use your tokens, they are automatically priced.

**Comment by jaketimothy** [comment]
> hi @joshualyguessennd can you do what we did for backedfi, add a coins adapter similar to this: https://github.com/DefiLlama/defillama-server/blob/master/coins/src/adapters/rwa/backed.ts
> 
> and here, you count only the token supply. the perk of this is, when other protocols use your tokens, they are automatically priced.

To clarify, we would open a PR for `defillama-server`. Then would we close this PR or change it to only return total supply?

**Comment by g1nt0ki** [comment]
hi @joshualyguessennd you update this PR to return only the token supply

**Comment by joshualyguessennd** [comment]
> hi @joshualyguessennd you update this PR to return only the token supply

does it mean we have to open another PR on `defillama-server` to track the total value of our assets on-chain ?

**Comment by llamatester** [comment]
The adapter at projects/dinari exports TVL: 
        
 
 
    arbitrum                  0
    
    total                    0

**Comment by g1nt0ki** [comment]
hi @joshualyguessennd I have refactored and merged the PR here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/9116

Added coins adapter here: https://github.com/DefiLlama/defillama-server/commit/f5e3e356a7e43cf90d10b5945ebfc73fee0da1a8

not the best solution atm, because every time there is a new type of share issued, one needs to check if it has an oracle and then put up a PR in two repos, but we can start with it and improve later on?

**Pull request closed without merging**
