### PR TITLE
We update Cellana Finance calculatot TVL

### PR DESCRIPTION
**Pull request by Centure2222**
In Aptos have 2 format token is: coin && fungible asset, were updated  my fungible asset in my system. Thank mate

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/cellana exports TVL: 
        
 
 
    aptos                     23.11 M
    
    total                    23.11 M

**Comment by g1nt0ki** [comment]
I dont understand this PR

**Comment by Centure2222** [comment]
> I dont understand this PR

On the token platform, there are 2 token standards. With previous PRs, I updated the TVL of "Coins". With this PR, I updated the TVL of "the fungible assets" we support.
Please check here
https://aptos.dev/standards/fungible-asset/
https://aptos.dev/standards/aptos-coin

**Comment by llamatester** [comment]
The adapter at projects/cellana exports TVL: 
        
 
 
    aptos                     22.41 M
    
    total                    22.41 M

**Comment by Centure2222** [comment]
> I dont understand this PR

oh, sorry ,before that I pushed missing code, my bad. Please check, thank you

**Pull request merged**
