### PR TITLE
Added New Farm Pool

### PR DESCRIPTION
**Pull request by 0xAces**
We recently deployed a new Curve YUSD LP Farm Pool.
Added the new pool to the adapter.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/yetiFinance exports TVL: 
        
 
 
    avalanche-staking         2.05 M
    avalanche-pool2           3.24 M
    avalanche                 699.37 M
    staking                   2.05 M
    pool2                     3.24 M
    
    total                    699.37 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
changes to the adapter is fine but can you please revert the change to package-lock.json file

**Comment by 0xAces** [comment]
> changes to the adapter is fine but can you please revert the change to package-lock.json file

reverted:)

**Comment by llamatester** [comment]
The adapter at projects/yetiFinance exports TVL: 
        
 
 
    avalanche-staking         2.08 M
    avalanche-pool2           3.29 M
    avalanche                 659.53 M
    staking                   2.08 M
    pool2                     3.29 M
    
    total                    659.53 M

**Pull request merged**
