### PR TITLE
Add Z Protocol

### PR DESCRIPTION
**Pull request by antonklyr**
##### Name (to be shown on DefiLlama):
Z Protocol

##### Twitter Link:
https://x.com/zprotocolxyz

##### Website Link:
https://app.zprotocol.xyz

##### Logo (High resolution, will be shown with rounded borders):
https://app.zprotocol.xyz/images/graphics/zlogo-token.png

##### Current TVL:
$120k (Adapter is missing prices of ZP and SCROLLY which are not yet listed on coingecko, bringing the total TVL displayed by defillama to, currently, about $42k)

##### Treasury Addresses (if the protocol has treasury):
0xAC7019601E2Bb218Db421EC7EC8aE2c8FB1A10F9

##### Chain:
SCROLL

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed):
z-protocol

##### Short Description (to be shown on DefiLlama):
Z Protocol is a cutting-edge DeFi platform on the Scroll network, featuring a DEX, yield farming, NFT staking, liquidity pools, and a vault system. Our goal is to create a stable ecosystem where users can easily participate in DeFi activities, fostering growth and innovation within our community.

##### Token address and ticker if any:
0x2147a89fb4608752807216D5070471c09A0DcE32
Ticker: ZP

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### forkedFrom (Does your project originate from another project):
Dex part is a Uniswap V2 fork, the rest is entirely in-house

##### methodology (what is being counted as tvl, how is tvl being calculated):
All of Z Protocol's DEX liquidity is counted. All of the liquidity locked through Z Protocol's FarmMaster is counted, unless it was already counted as DEX liquidity.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/zprotocol exports TVL: 
        
 
 
    scroll                    42.27 k
    scroll-pool2              0
    scroll-staking            0
    pool2                     0
    staking                   0
    
    total                    42.27 k

**Comment by llamatester** [comment]
The adapter at projects/zprotocol-dex exports TVL: 
        
 
 
    scroll                    64.86 k
    
    total                    64.86 k

**Comment by llamatester** [comment]
The adapter at projects/zprotocol-masterchef exports TVL: 
        
 
 
    scroll-staking            50.44 k
    staking                   50.44 k
    scroll                    0
    
    total                    0

**Comment by g1nt0ki** [comment]
@antonklyr thanks for the PR, I refactored it a bit to split between dex & masterchef

**Comment by llamatester** [comment]
The adapter at projects/zprotocol-dex exports TVL: 
        
 
 
    scroll                    64.86 k
    
    total                    64.86 k

**Comment by llamatester** [comment]
The adapter at projects/zprotocol-masterchef exports TVL: 
        
 
 
    scroll-staking            50.44 k
    staking                   50.44 k
    scroll                    0
    
    total                    0

**Comment by antonklyr** [comment]
Appreciate the much clearer and accurate rework! Thanks!

**Pull request merged**
