### PR TITLE
add MetaTdex into volume/adapters

### PR DESCRIPTION
**Pull request by phpwufeng**
**NOTE**

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
MetaTdex

##### Twitter Link:
https://twitter.com/MetaTdex

##### Website Link:
https://www.metatdex.com/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

圆型logo

Lark20221107-214721
Lark20221107-214739

##### Current TVL:
------ TVL ------
bsc 65.19 k
heco 643.39 k
total 708.59 k

##### Chain:
BSC、HECO

##### Short Description (to be shown on DefiLlama):
MetaTdex is a decentralized order matching trading platform

##### Token address and ticker if any:
0x445cC9518cF7bc7386A2e3aaF510650b0FB05f5F（BSC）
0x86040C76AAE5CBB322364CAF8820b0E8902e97E5（HECO）

##### Category (full list at https://defillama.com/categories) *Please choose only one:
DEX
##### methodology (what is being counted as tvl, how is tvl being calculated):

TVL: Total Locked Value of MetaTdex Trading Orders
Calculation method: quantity of all entrusted orders * corresponding entrusted price

### CODE REVIEW

**Comment by llamatester** [comment]
The metatdex adapter exports: 
        
 
 _______________________________________
    Volume for 6/11/2022
    _______________________________________
    
    Error: Can't get block of chain bsc
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:108:31
        at step (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:44:23)
        at Object.next (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:25:53)
        at fulfilled (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:16:58)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
    ------ ERROR ------
    Error: Couldn't find block height for chain bsc, RPC node rugged
        at Object.<anonymous> (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:222:27)
        at step (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:44:23)
        at Object.throw (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:25:53)
        at rejected (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:17:65)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by dtmkeng** [comment]
gm @phpwufeng seems like the volume from the current  includes daily volume but does not have historical data, you can rewrite like https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/volumes/adapters/tinyman

**Comment by phpwufeng** [comment]
> gm @phpwufeng seems like the volume from the current includes daily volume but does not have historical data, you can rewrite like https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/volumes/adapters/tinyman
@dtmkeng 
Thank you very much,Already modified to historical data 
here is the api for volumes
Heco: http://www.public_tdex.com/volumes?chain_id=56
Bsc: http://www.public_tdex.com/volumes?chain_id=128
api Documentation
http://www.public_tdex.com/get_volumes

**Comment by dtmkeng** [comment]
> 

okay, have another question `max_swap_amount` is value USD?

**Comment by llamatester** [comment]
The metatdex adapter exports: 
        
 
 _______________________________________
    Volume for 7/11/2022
    _______________________________________
    
    BSC 👇
    Backfill start time: 23/8/2022
    24h volume: 806251.3257722855
    Total volume: 616739770.2675707
    HECO 👇
    Backfill start time: 20/5/2022
    24h volume: 982523.161221981
    Total volume: 2560348431.2744036

**Comment by phpwufeng** [comment]
> Already modified to historical data



> Thank you very much,Already modified to historical data

@dtmkeng yes,max_swap_amount is value USD
Already modified to historical data
 BSC:"http://public.tdex.cz/get_volumes_list?chain_id=56"
 HECO:"http://public.tdex.cz/get_volumes_list?chain_id=128"

**Comment by phpwufeng** [comment]
> > 
> 
> okay, have another question `max_swap_amount` is value USD?

@dtmkeng When will it be shown in the Dex section

**Comment by dtmkeng** [comment]
> 

around 1 - 4 h

**Comment by phpwufeng** [comment]
> > 
> 
> around 1 - 4 h
@dtmkeng 
Hi, we are still not listed on DEX, is there anything else we need to do please tell us why, thanks

**Comment by phpwufeng** [comment]
> need

@g1nt0ki

**Comment by phpwufeng** [comment]
> Hi, we are still not listed on DEX, is there anything else we need to do please tell us why, thanks
@g1nt0ki @dtmkeng 
Hi, we are still not listed on DEX, is there anything else we need to do please tell us why, thanks

**Pull request merged**
