### PR TITLE
Pythagorean bonding curves

### PR DESCRIPTION
**Pull request by Taump**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/perpetual exports TVL: 
        
 
 
    obyte                     716.804988902867
    
    total                    716.804988902867

**Comment by llamatester** [comment]
The adapter at projects/perpetual exports TVL: 
        
 
 
    obyte                     716.7973544535337
    
    total                    716.7973544535337

**Comment by g1nt0ki** [comment]
@Taump thanks for the PR, I renamed the folder

**Comment by Define101** [comment]
@Taump what is the website?

**Comment by Taump** [comment]
@Define101  https://pyth.ooo/

**Comment by Define101** [comment]
Damm, i didnt even click the link. It was so similiar with the Pyth (oracles) i assume you had made a mistake
Thanks a lot @Taump

**Pull request merged**
