### PR TITLE
Add QuickSwap V3 Adapter

### PR DESCRIPTION
**Pull request by lilchizh**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  only if the PR is for listing a new protocol else it can be ignored/replaced with reason/details about the PR
3. For updating listing info It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push package-lock.json file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
QuickSwap V3

##### Twitter Link:
https://twitter.com/QuickswapDEX

##### List of audit links if any:
ABDK Consulting - https://algebra.finance/static/ABDK_Algebra_Audit-b4a20379efce1d26b7fbe9127582df6a.pdf
Hexens - https://algebra.finance/static/Hexens_Algebra_Audit-0918594cb7666296d9f57295d9274270.pdf

##### Website Link:
https://quickswap.exchange/#/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
image

##### Current TVL:
$ 27.34m

##### Chain:
Polygon

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
DEX - https://www.coingecko.com/en/exchanges/quickswap-v3
Token - https://www.coingecko.com/en/coins/quickswap

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
DEX ID - 4098
Token ID - 19966

##### Short Description (to be shown on DefiLlama):
QuickSwap is a [decentralized exchange](https://coinmarketcap.com/alexandria/glossary/decentralized-exchange-dex) that runs on Polygon Network to offer cheaper and faster transactions. Its [automated market maker](https://coinmarketcap.com/alexandria/glossary/automated-market-maker-amm) integrates upgradeable [smart contracts](https://coinmarketcap.com/alexandria/glossary/smart-contract) on [Ethereum](https://coinmarketcap.com/currencies/ethereum/) and renders [intermediaries](https://coinmarketcap.com/alexandria/glossary/intermediary-middleman) obsolete. The exchange is based on open-source software and prioritizes decentralization, [censorship resistance](https://coinmarketcap.com/alexandria/glossary/censorship-resistance) and security. It benefits from ultra-low gas prices compared to Ethereum, as well as fast and simple trading execution.

##### Token address and ticker if any:
0xb5c064f955d8e7f38fe0460c556a72987494ee17 - QUICK

##### Category (full list at https://defillama.com/categories) *Please choose only one:
DEX

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
No

##### forkedFrom (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated):
Value locked in pools. Going through all pools and counting volume.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/quickswap-v3: 
        
 
  
    
    
    Error: balanceOf multicall failed
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:64:19
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/quickswap-v3/index.js:80:14
        at runMicrotasks (<anonymous>)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:60:25)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:167:9
        at async Promise.all (index 0)
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
The adapter at projects/quickswap-v3 exports TVL: 
        
 
 
    polygon                   27.31 M
    
    total                    27.31 M

**Comment by llamatester** [comment]
The adapter at projects/quickswap-v3 exports TVL: 
        
 
 
    polygon                   27.59 M
    
    total                    27.59 M

**Comment by aesedepece** [comment]
@g1nt0ki any chance to update the oracle info now that QuickSwap has announced that they are using Witnet?

- https://twitter.com/QuickswapDEX/status/1630941808581550080
- https://medium.com/witnet/witnet-providing-price-feeds-to-quickswap-on-polygon-mainnet-5743017d6299

**Comment by g1nt0ki** [comment]
I have added it

**Comment by aesedepece** [comment]
Thanks a lot @g1nt0ki! Is there a better way to request this type of updates? There are a few more protocols relaying on the Witnet oracle that don't show that info on DL right now. Normally we suggest our users to declare the oracle when they submit the adapter on this repo. But most times the integration happens without us even noticing, as Witnet is totally permissionless :wink:

**Comment by aesedepece** [comment]
Oh, I think I found the answer based on @g1nt0ki's commit history. The oracle info is found in these two files:
- https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data.ts
- https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts

Is it OK to make PRs on [DefiLlama/defillama-server](https://github.com/DefiLlama/defillama-server) when we need to get this info updated? Thanks a lot!

**Comment by g1nt0ki** [comment]
@aesedepece yup, PR with some proof that protocol is using witnet works

**Pull request merged**
