### PR TITLE
Added Waxfusion adapter

### PR DESCRIPTION
**Pull request by mdcryptonfts**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

WaxFusion

##### Twitter Link:

https://twitter.com/waxfusion_io

##### Website Link:

https://waxfusion.io

##### Logo (High resolution, will be shown with rounded borders):

https://waxfusion.io/static/media/lsWAX_logo.bb9a135dcdee7d3a52ec.png

##### Current TVL:

550,000 WAX ($16.5k USD)

##### Treasury Addresses (if the protocol has treasury)

pol.fusion

##### Chain:

WAX

##### Short Description (to be shown on DefiLlama):

Liquid Staking protocol on WAX Blockchain with multiple reward streams.

##### Token address and ticker if any:

Address: token.fusion
Ticker: LSWAX

##### Category (full list at https://defillama.com/categories) *Please choose only one:*

Liquid Staking

##### forkedFrom (Does your project originate from another project):

No

##### methodology (what is being counted as tvl, how is tvl being calculated):

TVL counts:
- WAX deposited into the protocol contracts by users
- WAX that is staked by the protocol (user deposits are staked to generate yield)
- Protocol owned WAX (treasury)

##### Github org/user (Optional, if your code is open source, we can track activity):

User: mdcryptonfts
Project Repo: https://github.com/mdcryptonfts/waxfusion

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/waxfusion exports TVL: 
        
 
 
    wax                       16.56 k
    
    total                    16.56 k

**Comment by mdcryptonfts** [comment]
I wanted to clarify something since I realized there may be some confusion with the info I provided.

The "treasury" address I mentioned is protocol owned liquidity that is permanently locked in the contracts, and compounds daily when new revenue is earned. That POL is used to generate more rewards that are given to stakers.

It is meant to be counted as TVL since it is actually locked value, and grows with the protocol. It can never be withdrawn, and is not a "team allocation" that we can spend. It belongs to the protocol itself.

**Comment by llamatester** [comment]
The adapter at projects/alcor exports TVL: 
        
 
 
    wax                       598.16 k
    eos                       33.51 k
    
    total                    631.67 k

**Comment by llamatester** [comment]
The adapter at projects/waxfusion exports TVL: 
        
 
 
    wax                       17.05 k
    
    total                    17.05 k

**Comment by g1nt0ki** [comment]
@mdcryptonfts thanks for the PR

**Pull request merged**
