### PR TITLE
new farm address added

### PR DESCRIPTION
**Pull request by defininja**
**NOTE**

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Planet Farm

##### Website Link:
https://app.planet.finance/

##### Current TVL:
$4,356,791

##### Chain:
BSC

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
planet-finance

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
planet-finance

##### Short Description (to be shown on DefiLlama):
Planet is a decentralized financial protocol consisting of different planets, each their own application, designed to enable anyone to freely activate their capital.

##### Token address and ticker if any:
0x72b7d61e8fc8cf971960dd9cfa59b8c829d91991

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/planet-finance exports TVL: 
        
 
 
    bsc-staking               1.78 M
    bsc                       8.29 M
    staking                   1.78 M
    
    total                    8.29 M

**Comment by defininja** [comment]
Changes
- new farm address
- added new staking address
- added gamma and aqua infinity vault balances

**Comment by g1nt0ki** [comment]
@defininja looks good, can you remove the `console.logs`

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
Sorry, looked into it more closely, see that you are doublecounting tokens, we are already counting your LP tokens in https://defillama.com/protocol/blue-planet

if you think staked gamma/aqua token is not counted, staking should be updated, they cant be included as part of tvl

**Comment by g1nt0ki** [comment]
closing this as doublecountng tvl

**Pull request closed without merging**
