### PR TITLE
feat: updated Flashstake TVL metrics

### PR DESCRIPTION
**Pull request by umarsa**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

This PR will update the TVL metrics for Flashstake.

This is a new version of Flashstake and the project token address is now 0xB1f1F47061A7Be15C69f378CB3f69423bD58F2F8

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/flashstake exports TVL: 
        
 
 
    ethereum                  541.28 k
    
    total                    541.28 k

**Comment by realdealshaman** [comment]
Hey @umarsa thanks for the PR. We are moving away from using fetch adapters, is it possible to updated the adapter so that it provides the tvl making on-chain calls?

**Comment by umarsa** [comment]
@realdealshaman I can start putting together something but this will likely take some time. It would need to still use some fetching from the uniswap subgraph to read the pool addresses though - would this be okay?

also, can we merge this one for now and I will create another PR once the entire adaptor is more on-chain?

The current TVL displayed on the existing adaptor is also using fetching but the values are incorrect since its for a previous version of the protocol

**Comment by realdealshaman** [comment]
seems that we would only need to account for weth and usdc that are deposited for tvl and flash tokens for the staking. what else would be counted?

**Comment by umarsa** [comment]
Flashstake TVL consists of all principal tokens deposited into all the active strategies - at the moment there are USDC and WETH strategies but we plan to add more over time. The current fetch API takes all of this into consideration.

TVL also consists of Flash tokens that users have staked into the Flashback contract here: 0xb89494ab70001a2f25372b5e962046908188feea (read only call getTotalLocked())

and the LP tokens locked by users at the following contracts: 0x57d551a18aae2c9de6977425f1df34dcd5db4977 0xcb1205ac28693beda01e0b66e9b4d06231609bfd

again, read-only call getTotalLocked()

@realdealshaman

**Comment by umarsa** [comment]
@realdealshaman thanks for answering my questions on Discord. I have to leave now but I believe this is now in a more acceptable format?

**Comment by llamatester** [comment]
The adapter at projects/flashstake exports TVL: 
        
 
 
    ethereum-pool2            127.90 k
    ethereum-staking          356.61 k
    ethereum                  67.24 k
    pool2                     127.90 k
    staking                   356.61 k
    
    total                    67.24 k

**Pull request merged**
