### PR TITLE
add bouncebit-lsd & bouncebit-premium

### PR DESCRIPTION
**Pull request by Adolf998**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bouncebit-lsd exports TVL: 
        
 
 
    bouncebit                 5.63 M
    
    total                    5.63 M

**Comment by llamatester** [comment]
The adapter at projects/bouncebit-premium exports TVL: 
        
 
 
    bouncebit                 72.64 M
    bsc                       0
    ethereum                  0
    
    total                    72.64 M

**Comment by Adolf998** [comment]
Our chain is mainly cedefi, which consists of two protocols, LSD and Cedefi-Premium. but currently BBTC and BBUSD have no price display on BNB Chian and ETH, Can we get the price through the graph in the DEX?
BBTC and BBUSD are wrapped WBTC/BTCB USDT from ETH and BNB chain.  Wrapping occurs on the respective chains and then bridged to BounceBit Chain.  Assets are store in CEFFU custody to allow CEX mirroring.  Methodology is similar to Ethena.

BounceBit-LSD
> BounceBit natively provides a Liquid Staking smart contract. If you stake your BTC or BB, you will receive a Liquid Staking Derivative (LSD). This LSD is like a voucher that testifies that you are delegating your assets to a validator.

BounceBit-Premium
> Premium Yield Generation is a CeDeFi product on the BounceBit platform that earns yield via Funding Rate Arbitrage on centralized exchanges. Counterparty-risk is minimized by the use of off-exchange settlement solutions.

**Comment by llamatester** [comment]
The adapter at projects/bouncebit-lsd exports TVL: 
        
 
 
    bouncebit                 384.91 M
    
    total                    384.91 M

**Comment by llamatester** [comment]
The adapter at projects/bouncebit-premium exports TVL: 
        
 
 
    bouncebit                 73.57 M
    ethereum                  0
    bsc                       0
    
    total                    73.57 M

**Comment by llamatester** [comment]
The adapter at projects/bouncebit-lsd exports TVL: 
        
 
 
    bouncebit                 386.47 M
    
    total                    386.47 M

**Comment by llamatester** [comment]
The adapter at projects/bouncebit-premium exports TVL: 
        
 
 
    bouncebit                 72.56 M
    ethereum                  0
    bsc                       0
    
    total                    72.56 M

**Comment by Adolf998** [comment]
Hello @g1nt0ki , Could you please help us change the name of BBSCAN to **BounceBit LSD**, So users can better understand, Thanks.

**Pull request merged**
