### PR TITLE
Basin on Arbitrum

### PR DESCRIPTION
**Pull request by soilking**
Updated adapter for Basin protocol to include tvl on Arbitrum. Otherwise, none of the other info/metadata etc is changed.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/basin exports TVL: 
        
 
 
    arbitrum                  6.85 M
    ethereum                  6.08 k
    
    total                    6.85 M

**Comment by llamatester** [comment]
The adapter at projects/basin exports TVL: 
        
 
 
    ethereum                  6.07 k
    arbitrum                  0
    
    total                    6.07 k

**Comment by g1nt0ki** [comment]
@soilking can you check if my implementation is correct? I manually checked all the wells on arbitrum, maybe the upgraded event pulls unrelated contracts?

**Comment by soilking** [comment]
The arbitrum wells can be upgradeable, the addresses emitted in the `BoreWell` event in this case are the underlying implementations. The other logs call I added was to search for which contract (if any) emitted that `Upgraded` event. If there is such an event, then the pooled tokens are not in the implementation address but rather in the address emitting `Upgraded`.

**Comment by g1nt0ki** [comment]
> The arbitrum wells can be upgradeable, the addresses emitted in the `BoreWell` event in this case are the underlying implementations. The other logs call I added was to search for which contract (if any) emitted that `Upgraded` event. If there is such an event, then the pooled tokens are not in the implementation address but rather in the address emitting `Upgraded`.

do you have an example?

**Comment by g1nt0ki** [comment]
*like a transaction with ungraded event

**Comment by soilking** [comment]
Here is an example: https://arbiscan.io/tx/0xe530c3ced2dd6ff9e7e8a4e8b721150ebd3de3420935d9b06ac557f296bb7532#eventlog

What are you trying to achieve? I believe the original code I submitted was accounting for this properly.

**Comment by g1nt0ki** [comment]
hmm, I see what you are doing, but the issue with that implementation is, as time goes by, there will be more event log calls, in my implementation, it is always against one contract, but in your case, it grows.

It is sort of hidden, but we cache each of these event log result (per target), and if we dont cache, it is too expensive. But my implementation is wrong, is there some other way to get the upgraded contract? the new contract is not verified

**Comment by soilking** [comment]
Unfortunately this is the only way to get it on chain currently. Would it work for you if instead we pulled the list of wells from our subgraph? The upgradeable wells have a hardcoded mapping there until an on chain solution can be developed.

**Comment by g1nt0ki** [comment]
> Unfortunately this is the only way to get it on chain currently. Would it work for you if instead we pulled the list of wells from our subgraph? The upgradeable wells have a hardcoded mapping there until an on chain solution can be developed.

yup, this is a good solution

**Comment by g1nt0ki** [comment]
*pulling list of wells from subgraph

**Comment by llamatester** [comment]
The adapter at projects/basin exports TVL: 
        
 
 
    arbitrum                  6.69 M
    ethereum                  5.98 k
    
    total                    6.69 M

**Comment by soilking** [comment]
Great, this is done

**Comment by llamatester** [comment]
The adapter at projects/basin exports TVL: 
        
 
 
    arbitrum                  6.79 M
    ethereum                  6.07 k
    
    total                    6.80 M

**Pull request merged**
