### PR TITLE
Streamflow: return tvl by token

### PR DESCRIPTION
**Pull request by Yolley**
Hi, as requested we now return TVL by token according to the documentation.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/streamflow exports TVL: 
        
 
 
    solana                    1.03 B
    sui                       4.31 M
    ethereum                  1.12 k
    bsc                       94
    aptos                     79
    polygon                   3
    
    total                    1.03 B

**Comment by 0xngmi** [comment]
why did you put everything in core tvl and deleted vesting?

**Comment by llamatester** [comment]
Error while running adapter at projects/streamflow: 
        
 
  
    
    
    Error: Failed to get https://metabase.internal-streamflow.com/_public/api/v1/stats/accumulated/by-token
    Truncated error stack:
    
        at get (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/http.js:33:11)

**Comment by llamatester** [comment]
The adapter at projects/streamflow exports TVL: 
        
 
 
    vesting                   807.45 M
    solana-vesting            803.74 M
    solana                    7.80 M
    sui-vesting               3.71 M
    sui                       24.27 k
    ethereum                  1.12 k
    bsc-vesting               94
    aptos                     17
    ethereum-vesting          7
    bsc                       1
    polygon-vesting           1
    polygon                   0
    aptos-vesting             0
    
    total                    7.82 M

**Comment by llamatester** [comment]
The adapter at projects/streamflow exports TVL: 
        
 
 
    vesting                   838.30 M
    solana-vesting            834.26 M
    sui-vesting               4.05 M
    solana                    1.20 M
    bsc-vesting               99
    aptos                     17
    ethereum-vesting          7
    sui                       2
    polygon-vesting           1
    ethereum                  0
    polygon                   0
    bsc                       0
    aptos-vesting             0
    
    total                    1.20 M

**Comment by g1nt0ki** [comment]
@Yolley thanks for the PR

**Pull request merged**
