### PR TITLE
 🌶 added Tanukix DEX on the Taiko chain

### PR DESCRIPTION
**Pull request by andreiashu**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

TanukiX

##### Twitter Link:

https://x.com/Tanuki_DEX

##### List of audit links if any:

https://docs.xave.co/contract-audits/fxpool-final-audit

##### Website Link:
https://www.tanukix.com/

##### Logo (High resolution, will be shown with rounded borders):

66546b5de2296386b5d6e44a_Tanukix Logo

##### Current TVL:

$37

##### Chain:

Taiko

##### Short Description (to be shown on DefiLlama):

TanukiX is the One Stop Stablecoin Shop on Taiko.

##### Category (full list at https://defillama.com/categories) *Please choose only one:

[Dexes](https://defillama.com/protocols/Dexes)

##### forkedFrom (Does your project originate from another project):
Balancer, Xave Finance

##### methodology (what is being counted as tvl, how is tvl being calculated):
Sum of all the tokens locked in TanukiX Pools, including FXPools, Weighted Pools, and ComposableStable Pools

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/tanukix exports TVL: 
        
 
 
    taiko                     26
    
    total                    26.496911903805

**Comment by andreiashu** [comment]
It seems that DefiLlama does not recognize DAI token on Taiko chain yet?
TVL above is basically USDC + USDT in the pools, but is missing the DAI TVL

**Comment by llamatester** [comment]
The adapter at projects/tanukix exports TVL: 
        
 
 
    taiko                     37
    
    total                    37.497708142283

**Comment by g1nt0ki** [comment]
@andreiashu thanks for the PR, I fixed the issue

**Pull request merged**
