### PR TITLE
Sharky

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/sharky exports TVL: 
        
 
 
    solana                    0
    solana-borrowed           5.11 M
    borrowed                  5.11 M
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/sharky exports TVL: 
        
 
 
    solana-borrowed           5.86 M
    solana                    594.03 k
    borrowed                  5.86 M
    
    total                    594.03 k

**Comment by g1nt0ki** [comment]
@cotemper  @Restuta  can you please review my fix and see if the logic is correct?

**Comment by Restuta** [comment]
What is "solana                    594.03 k"  in that table and why total is equal to that? Also if that is a number in SOL that doesn't seem to be correct.

> TVL is the total principal of all current offers and taken loans.

I could be wrong but it feels like the code is doing something else. From the code it seems that it compute TVL as "value locked in not yet taken loans"

Let me clarify how I think it should be computed.

I think it's fair to say that TVL of sharky is total value of all offers (not yet taken loans) + the total borrowed amount.

You can see those two numbers here https://sharky.fi/beta/orderbooks (data is pulled from chain):

CleanShot 2023-04-07 at 16 06 30@2x


So following those numbers:

the borrowed amount is 288K SOL
not yet taken loans (offers) is 317.7K - 288K = 29.7K SOL
TVL = 317.7K SOL

Does it align with your understanding?

**Comment by g1nt0ki** [comment]
@Restuta we let the users decide if they want to include borrowed amount under tvl, thats why it is shown as a separate field, this is standard practice we apply to all lending protocols, the reason for this is, some protocols have inflated metrics by cyclic lending/borrowing

**Pull request merged**
