### PR TITLE
update B2B TVL func and category

### PR DESCRIPTION
**Pull request by b2b-money-org**
## update B2B TVL func and category
- add staking contract
- chage the category to **CDP**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/back-to-bitcoin exports TVL: 
        
 
 
    bsc                       2.63 M
    
    total                    2.63 M

**Comment by llamatester** [comment]
The adapter at projects/back-to-bitcoin exports TVL: 
        
 
 
    bsc                       5.27 M
    bsc-staking               220.51 k
    staking                   220.51 k
    
    total                    5.27 M

**Comment by llamatester** [comment]
The adapter at projects/back-to-bitcoin exports TVL: 
        
 
 
    bsc                       5.27 M
    bsc-pool2                 220.51 k
    pool2                     220.51 k
    
    total                    5.27 M

**Comment by g1nt0ki** [comment]
@b2b-money-org are you issuing some stablecoin when users lock BTC? else not sure how this can be considered CDP

**Comment by b2b-money-org** [comment]
> @b2b-money-org are you issuing some stablecoin when users lock BTC? else not sure how this can be considered CDP

Not issue yet, we will conduct it next week.

**Pull request merged**
