### PR TITLE
update NAVI tvl

### PR DESCRIPTION
**Pull request by ComeOnOliver**
Correct NAVI tvl by mulplying the index and Add NAVX and VSUI token address to the core token address

**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/navi exports TVL: 
        
 
 
    sui                       141.08 M
    sui-borrowed              90.92 M
    borrowed                  90.92 M
    
    total                    141.08 M

**Comment by ComeOnOliver** [comment]
> The adapter at projects/navi exports TVL:
> 
> ```
> sui                       141.08 M
> sui-borrowed              90.92 M
> borrowed                  90.92 M
> 
> total                    141.08 M 
> ```

Sorry, what's the issue here?

**Comment by g1nt0ki** [comment]
@ComeOnOliver thanks for the fix, without going into the details, we want to keep core assets list small, so reverted that change.

**Comment by llamatester** [comment]
The adapter at projects/navi exports TVL: 
        
 
 
    sui                       137.37 M
    sui-borrowed              90.24 M
    borrowed                  90.24 M
    
    total                    137.37 M

**Comment by ComeOnOliver** [comment]
> @ComeOnOliver thanks for the fix, without going into the details, we want to keep core assets list small, so reverted that change.

is there any way that we can add NAVX, vSui to the NAVI's page, even not core assets list?

**Pull request merged**
