### PR TITLE
Add pembrock.js

### PR DESCRIPTION
**Pull request by valar999**
##### Short Description (to be shown on DefiLlama):
PembRock Finance is the first leveraged yield farming protocol built on the NEAR blockchain. Users can provide liquidity, farm with leverage, stake, and take governance decisions to secure the future of the platform, all on a fast, secure, cheap, and user-friendly blockchain.

PEM is the native token with versatile functionality that helps PembRock Finance to operate. It is used:
To stake within the PembRock Finance ecosystem — with rewards paid out in PEM.
As a part of the reward mechanism for interacting with the PembRock protocol.
As an additional bonus for those who provide funds to the liquidity pools.
For DAO participation — users can stake PEM to receive xPEM, PembRock’s governance token.

PembRock Finance is also founded by NEAR guild masters and has secured a $75,000 grant from the NEAR Foundation.

PembRock Finance is established by Igor Stadnyk, who also serves as CEO. His software development background and a proven track record of launching and leading blockchain projects since 2012 help in building PembRock as a strong financial tool with solid tech components. He has mining pool Minerall, blockchain outsources company INC4 and IoT blockchain-based ecosystem Ambrosus behind his back.

Furthermore, the team of PembRock Finance is fully transparent and presented on the platform’s web page. There are professionals with diverse backgrounds in blockchain projects and other different fields.

##### methodology (what is being counted as tvl, how is tvl being calculated): Summary of all tokens deposited to PembRock Lend Pools (mainnet contract)

### CODE REVIEW

**Comment by g1nt0ki** [comment]
hi @valar999, thanks for the PR, 
Can you update the adapter to compute tvl using on chain calls instead of calling your api?

**Comment by g1nt0ki** [comment]
It is mainly for transparency and also reducing dependency on other services

**Comment by vitalii427** [comment]
Hi @g1nt0ki

**Comment by llamatester** [comment]
Error while running adapter at projects/pembrock.js: 
        
 
  
    
    
    Error: invalid BigNumber value (argument="value", value="111648.8186151186317081387477715022471419017947541", code=INVALID_ARGUMENT, version=bignumber/5.6.2)
    Truncated error stack:
        at Function.BigNumber.from (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/bignumber/lib/bignumber.js:239:23)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:331:16
        at Array.forEach (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:325:28)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:337:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:60:30)

**Comment by vitalii427** [comment]
> Error while running adapter at projects/pembrock.js:
> 
> ```
> Error: invalid BigNumber value (argument="value", value="111648.8186151186317081387477715022471419017947541", code=INVALID_ARGUMENT, version=bignumber/5.6.2)
> Truncated error stack:
>     at Function.BigNumber.from (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/bignumber/lib/bignumber.js:239:23)
>     at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:331:16
>     at Array.forEach (<anonymous>)
>     at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:325:28)
>     at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:337:3)
>     at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:60:30)
> ```

Yes, it is incompatibility in tests with near heleper. I've done quick fix locally but decided not to commit it

**Comment by vitalii427** [comment]
@g1nt0ki pls approve workflows once more

**Comment by g1nt0ki** [comment]
@valar999 thanks for changing the adapter to be on-chain, I had missed your last commit when I merged: I had made a different fix here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/3528

**Pull request merged**
