### PR TITLE
Add kleva

### PR DESCRIPTION
**Pull request by kleva-dev**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Kleva Protocol

Twitter Link:
https://twitter.com/kleva_protocol

List of audit links if any:
https://docs.kleva.io/audit-report/peckshield
https://docs.kleva.io/audit-report/sooho
https://docs.kleva.io/audit-report/scvsoft

Website Link:
https://kleva.io/

Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): https://kleva.io/static/images/kleva.logo.svg
Current TVL: $71400386
Chain: Klaytn
Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
N/A

Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

Short Description (to be shown on DefiLlama):
KLEVA Protocol is the first Leveraged Yield Farming Protocol on KLAYTN, with aim to become the largest Lending Protocol for Leveraged Yield Farmers and Lenders.

Token address and ticker if any:
KLEVA: 0x5fff3a6c16c2208103f318f4713d4d90601a7313

Category (full list at https://defillama.com/categories) *Please choose only one:
Yield

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
N/A

forkedFrom (Does your project originate from another project):
Alpaca Finance

methodology (what is being counted as tvl, how is tvl being calculated):
TVL is counted as the sum of Lending TVL and Farming TVL

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@kleva-dev I had closed the earlier PR from kleva as it was fetch adapter and when I reached out to the team and asked whether they can change it to on chain adapter, there said they didnt have time atm and would look into it later: https://github.com/DefiLlama/DefiLlama-Adapters/pull/2466

Can you update the adapter to compute the tvl using onchain calls? let me know if you need some help

**Comment by kleva-dev** [comment]
@g1nt0ki 

Looking up both the Lending TVL and the Farming TVL through the on-chain contract required quite a bit of code, so we replaced it with an external API call. The price of all LP Tokens must be inquired, and new work must be done whenever a pool is added. On the other hand, this API we provided is a separate API developed by the Kleva protocol data team, and new data is updated every day.

Also, when I see other DeFis in Klaytn among the repositories I referenced when writing this code, TVL is returned as an external API call. Is there a problem with external API calls mounted on the adapter?

Here are the codes I referenced.

**<Claimswap>**
```
async function fetchLiquidity() {
  const claimswapInfo = await retry(async bail => axios.get('https://data-api.claimswap.org/dashboard/allpool'));
  let totalValue = 0;
  for (const pool of claimswapInfo.data) {
    totalValue = totalValue + pool.liquidity;
  }

  return toUSDTBalances(totalValue.toFixed(2));
}
```
In the above code, TVL is returned as a simple external API call.
https://github.com/DefiLlama/DefiLlama-Adapters/pull/1713/files

**<Klayswap>**
```
async function fetchLiquidity() {
  const klayswapInfo = await retry(async bail => await axios.get('https://s.klayswap.com/stat/klayswapInfo.json'))
  const recentPoolInfo = klayswapInfo.data.recentPoolInfo;
  var totalLiquidity = new BigNumber('0');

  for (const pool of recentPoolInfo) {
    totalLiquidity = totalLiquidity.plus(pool.poolVolume);
  }

  // Single-sided deposits
  const SinglePoolInfo = klayswapInfo.data.leveragePoolInfo.single;
  var totalSingleSided = new BigNumber('0');

  for (const spool of SinglePoolInfo) {
    totalSingleSided = totalSingleSided.plus(spool.totalDepositVol);
  }

  return toUSDTBalances(totalLiquidity.plus(totalSingleSided).toFixed(2));
}
```

https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/klayswap/index.js

In the case of klayswap, TVL is also returned through an external API call.

Please check again, we hope that this code will be listed in the adapter.

**Comment by kleva-dev** [comment]
@g1nt0ki 
Okay. I edited the code and re-uploaded it. Please check again.

**Comment by g1nt0ki** [comment]
@kleva-dev thanks for changing the adapter code, I am reviewing it now

**Comment by llamatester** [comment]
The adapter at projects/kleva exports TVL: 
        
 
 
    klaytn                    53.98 M
    
    total                    53.98 M

**Comment by g1nt0ki** [comment]
@kleva-dev the code mostly looks good but I made two changes:
1. remove dependency on price api and we have token breakdown
2. Count tokens remaining in vaults that are not being farmed instead of all deposited tokens, we have applied same logic/rule for alpaca finance: https://github.com/DefiLlama/DefiLlama-Adapters/blob/bc78e57f7c5b28da546a86adee81e31dc22b3f34/projects/alpaca-finance/lyf.js#L110 

If you are fine with the changes, we can merge and list it

**Comment by kleva-dev** [comment]
@g1nt0ki 

2. Lending TVL should be sum of counting **tokens remaining in vaults** and counting **tokens being used in farming as debt tokens**

**Comment by g1nt0ki** [comment]
> @g1nt0ki
> 
>     2. Lending TVL should be sum of counting **tokens remaining in vaults** and counting **tokens being used in farming as debt tokens**
> 
> 
> Could you change the code to follow the rule above?

imo, users deposit 54M and 18M of those is used for farming, correct? hence the tvl is 54M.

We have similar rule for lending platforms, we do not count the amount borrowed under TVL for aave/compound

**Comment by kleva-dev** [comment]
@g1nt0ki Even so, TVL is calculated lower than actual TVL.

After reviewing your code, the return value of `getLendingTVL` only returns 6 lending pools.
However, In KLEVA, we have 7 lending pools including KLAY, KLEVA, WEMIX, ETH, USDT, USDC, KDAI.
I think KLAY lending pool TVL is excluded in your code.

Could you check again?
image

**Comment by g1nt0ki** [comment]
Sorry, you are correct, I have fixed the bug here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/4266

**Pull request merged**
