### PR TITLE
add new op contracts

### PR DESCRIPTION
**Pull request by 0xChupaCabra**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/vfat: 
        
 
  
    
    
    Error: Multicall failed! 
     [chain: optimism] [fail count: 3] [abi: function positions(uint256 tokenId) view returns (uint96 nonce, address operator, address token0, address token1, int24 tickSpacing, int24 tickLower, int24 tickUpper, uint128 liquidity, uint256 feeGrowthInside0LastX128, uint256 feeGrowthInside1LastX1...

**Comment by g1nt0ki** [comment]
I tried a fix but still failing for other reasons

**Comment by 0xChupaCabra** [comment]
@g1nt0ki it looks like new contracts have the same positions method of the old ones, so i thought the error locally was coming from the RPC itself because of too many calls.
I will try to get it fixed asap

**Comment by g1nt0ki** [comment]
hi @0xChupaCabra I fixed it here with a bit of refactor: https://github.com/DefiLlama/DefiLlama-Adapters/pull/10722

**Pull request closed without merging**
