### PR TITLE
add fetch adapter for axelar

### PR DESCRIPTION
**Pull request by aditya-manit**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/axelar.js exports TVL: 
        
 
 
    
    total                    120.99 M

**Comment by llamatester** [comment]
Error while running adapter at projects/axelar.js: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:224:11

**Comment by aditya-manit** [comment]
> Error while running adapter at projects/axelar.js:
> 
> ```
> Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
> Truncated error stack:
> 
>     at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:224:11
> ```

Hey @g1nt0ki looks like https://github.com/DefiLlama/DefiLlama-Adapters/pull/4480/commits/ef512c99d34cc28e89cdb120bc999c2b071fefcc causes some issues, test is now failing

**Comment by aditya-manit** [comment]
Looks like it was some path issue, can you merge this: https://github.com/DefiLlama/DefiLlama-Adapters/pull/4486

I fixed it

**Pull request merged**
