### PR TITLE
Listing: Streamflow

### PR DESCRIPTION
**Pull request by srdjanrist**
---
##### methodology (what is being counted as tvl, how is tvl being calculated): 
TVL = All Locked value in the protocol - stables - L1 tokens
Most of it is out of the circulations.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/streamflow exports TVL: 
        
 
 
    solana                    130.31 M
    
    total                    130.31 M

**Comment by g1nt0ki** [comment]
@srdjanrist thanks for the PR but it needs some additional work,

can you split the tvl into two, this is what we are doing for other streaming protocols
  * tvl: count only SOL ans stable spl tokens locked in your  contract
  * vesting: count all other SPL tokens value
  
also can you update adapter to compute tvl on chain?

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
.

**Comment by llamatester** [comment]
The adapter at projects/streamflow exports TVL: 
        
 
 
    solana                    203.91 k
    solana-vesting            130.42 M
    vesting                   130.42 M
    
    total                    203.91 k

**Comment by 0xngmi** [comment]
> 50k streams

is a bot creating streams? that seems like an insane amount of streams to have

**Comment by andjelboskovic** [comment]
> > 50k streams
> 
> is a bot creating streams? that seems like an insane amount of streams to have

Hey @0xngmi ,

Part of the Streamflow team here.

There are many cases of our protocol.

Some teams have deep integration of our SDK where they do vested in-game reward distribution, and some do vested airdrops to their player base.

More than 95% of our streams we can account for directly to our customers or partners, so we are sure bots have not produced the streams, even though it's technically possible.

Let me know if you have more questions,

**Comment by llamatester** [comment]
The adapter at projects/streamflow exports TVL: 
        
 
 
    solana                    203.91 k
    solana-vesting            130.42 M
    vesting                   130.42 M
    
    total                    203.91 k

**Comment by llamatester** [comment]
The adapter at projects/streamflow exports TVL: 
        
 
 
    solana                    203.71 k
    solana-vesting            130.29 M
    vesting                   130.29 M
    
    total                    203.71 k

**Pull request merged**
