### PR TITLE
Only1: include TVL

### PR DESCRIPTION
**Pull request by dn-l**
##### Twitter Link:
Not changed

##### Website Link:
https://only1.app

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
Not changed

##### Current TVL:
9590754.7615458 $LIKE

##### Chain:
Not changed

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
Not changed

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
Not changed

##### Short Description (to be shown on DefiLlama):
Not changed

##### Token address and ticker if any:
Not changed

##### forkedFrom (Does your project originate from another project):
Not a fork

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is the sum of all tokens in the staking pools

### CODE REVIEW

**Comment by waynebruce0x** [comment]
The reason your TVL is exported as 'staking' is because all of the TVL we have recorded is in 'LIKE' tokens - which is your native token.

**Comment by dn-l** [comment]
@waynebruce0x should it be USD? Please guide me, I just want coingecko to display the correct number. Currently it is 0

**Comment by waynebruce0x** [comment]
exporting in terms of tokens is correct, but we exclude 'staking' of native tokens in core TVL. That's why it's not showing up on coingecko - this method is consistent across all projects.

**Comment by dn-l** [comment]
@waynebruce0x but Raydium's TVL is not 0, their staking is also in native tokens (RAY) https://api.llama.fi/tvl/raydium

**Comment by waynebruce0x** [comment]
The Raydium adapter counts liquidity in the AMM pools, so its not all RAY tokens

**Comment by dn-l** [comment]
Any reason why you exclude staking in the native token? It doesn't make much sense to me.

**Comment by waynebruce0x** [comment]
It was a feature requested by the community, so now users get the option of whether or not to include native token staking and pool2. I think the main reason is that people were interested to see how much 'external' value is locked in protocol contracts.

**Comment by dn-l** [comment]
@waynebruce0x by design our token has a governance role, the UI for it is not implemented yet but will be in the future. Does it change anything?

**Comment by 0xngmi** [comment]
No, it doesn't. You can find a longer explanation for this on https://github.com/DefiLlama/DefiLlama-Adapters/discussions/438. Coingecko and other 3rd parties that integrate us have to decide for themselves if they want to include staking or not into their definition of TVL, coingecko doesn't include it so your TVL on their page is displayed as 0. We provide all data in our API but how TVL is defined is up to whoever integrates us (or users on our site how can choose to turn on staking or not)

**Comment by dn-l** [comment]
Ok closing then

**Pull request closed without merging**
