### PR TITLE
Adding new staking, removing old one

### PR DESCRIPTION
**Pull request by gaspare100**
**NOTE**

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/scrub exports TVL: 
        
 
 
    cronos                    0
    kava                      0
    kava-staking              103.76 k
    cronos-staking            5.53 k
    kava-pool2                294.19 k
    cronos-pool2              14.47 k
    staking                   109.29 k
    pool2                     308.66 k
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/scrub exports TVL: 
        
 
 
    cronos                    0
    kava                      0
    kava-staking              103.76 k
    kava-pool2                294.19 k
    cronos-staking            5.53 k
    cronos-pool2              14.47 k
    staking                   109.29 k
    pool2                     308.66 k
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/scrub exports TVL: 
        
 
 
    cronos                    0
    kava                      0
    cronos-staking            5.53 k
    kava-staking              103.76 k
    kava-pool2                294.19 k
    cronos-pool2              14.47 k
    staking                   109.29 k
    pool2                     308.66 k
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/scrub exports TVL: 
        
 
 
    cronos                    0
    kava                      0
    kava-staking              213.48 k
    kava-pool2                289.89 k
    cronos-staking            5.54 k
    cronos-pool2              14.48 k
    staking                   219.01 k
    pool2                     304.38 k
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/scrub exports TVL: 
        
 
 
    cronos                    0
    kava                      0
    kava-staking              226.09 k
    kava-pool2                289.89 k
    cronos-staking            5.54 k
    cronos-pool2              14.48 k
    staking                   231.63 k
    pool2                     304.38 k
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/scrub exports TVL: 
        
 
 
    cronos                    0
    kava                      0
    kava-staking              213.04 k
    cronos-staking            5.54 k
    cronos-pool2              14.48 k
    kava-pool2                289.92 k
    staking                   218.57 k
    pool2                     304.40 k
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/scrub exports TVL: 
        
 
 
    cronos                    0
    kava                      0
    kava-staking              213.48 k
    cronos-staking            5.54 k
    cronos-pool2              14.48 k
    kava-pool2                289.92 k
    staking                   219.01 k
    pool2                     304.40 k
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/scrub exports TVL: 
        
 
 
    cronos                    0
    kava                      0
    cronos-staking            5.54 k
    kava-staking              216.91 k
    kava-pool2                292.16 k
    cronos-pool2              14.47 k
    staking                   222.45 k
    pool2                     306.64 k
    
    total                    0

**Comment by gaspare100** [comment]
Single lion stake and tiger stake are separate contracts from the masonry, i changed the refences to that everything is actually properly reflected. Tiger staking will go live only on kava tomorrow, cronos lion stake is deprecated and thus removed

**Pull request merged**
