### PR TITLE
DackieSwap CLMM integrate with Defillama

### PR DESCRIPTION
**Pull request by DackieSwap**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
DackieSwap

##### Twitter Link:
https://twitter.com/DackieSwap

##### List of audit links if any:
Not yet

##### Website Link:
https://dackieswap.xyz

##### Logo (High resolution, will be shown with rounded borders):
https://dackieswap.xyz/logo.png

##### Current TVL:
10k

##### Treasury Addresses (if the protocol has treasury)
Not yet

##### Chain:
Base

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): 
dackieswap

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): 
dackieswap

##### Short Description (to be shown on DefiLlama):
#1 Native and Most Trusted DEX on Base

##### Token address and ticker if any:
0xc2bc7a73613b9bd5f373fe10b55c59a69f4d617b
DACKIE

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### forkedFrom (Does your project originate from another project):
PancakeSwap V3

##### methodology (what is being counted as tvl, how is tvl being calculated):
Using TheGraph

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/dackieswap

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/dackieswap exports TVL: 
        
 
 
    base                      0
    
    total                    0

**Comment by DackieSwap** [comment]
Hi @llamatester , tetu that failed eslint is not our project.

**Comment by waynebruce0x** [comment]
We need non zero TVL to list the project

**Comment by llamatester** [comment]
The adapter at projects/dackieswap exports TVL: 
        
 
 
    base                      19.42 k
    
    total                    19.42 k

**Comment by DackieSwap** [comment]
@waynebruce0x I update the block number, now has TVL ser.

**Comment by DackieSwap** [comment]
@waynebruce0x want to change our description. There're some type

"#1 Native and Most Trusted DEX on Base"

Please help

**Comment by DackieSwap** [comment]
Hi @waynebruce0x ,

We just audited, please update this link to our protocol DackieSwap V3
https://github.com/peckshield/publications/blob/master/audit_reports/PeckShield-Audit-Report-DackieSwap-v1.0.pdf

**Comment by Define101** [comment]
So the v3 is audited but not the v2 correct?

**Pull request merged**
