### PR TITLE
add abacus

### PR DESCRIPTION
**Pull request by 0xShad0w**
Hi thanks for listing. Mantle TVL will show once coingecko fixes a pricing issue

##### Token address and ticker if any:
abcRAM (Arbitrum) - 0x9EfCFc5b49390FC3fb9B58607D2e89445Bb380BF
abcPHAR (Avalanche) - 0xd5d0A9b3f2C264b955Ae7161cfA6D38A7aEa60a7
abcCLEO (Mantle) - 0xCffbE0E73c750731EdB38C14Bc81A39dAc91819d
liveTHE (BSC) - 0xCdC3A010A3473c0C4b2cB03D8489D6BA387B83CD
liveRETRO (Polygon) - 0xCaAF554900E33ae5DBc66ae9f8ADc3049B7D31dB

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/abacus exports TVL: 
        
 
 
    bsc                       6.12 M
    arbitrum                  2.52 M
    avax                      866.70 k
    polygon                   75.85 k
    mantle                    0
    
    total                    9.58 M

**Comment by llamatester** [comment]
The adapter at projects/abacus exports TVL: 
        
 
 
    bsc                       8.09 M
    arbitrum                  3.01 M
    avax                      1.08 M
    mantle                    456.27 k
    polygon                   149.44 k
    
    total                    12.79 M

**Comment by g1nt0ki** [comment]
hi @0xShad0w instead of counting staked tokens as tvl, I am counting tokens locked/converted to abcTokens, that should be fine right?

**Comment by 0xShad0w** [comment]
> hi @0xShad0w instead of counting staked tokens as tvl, I am counting tokens locked/converted to abcTokens, that should be fine right?

Yes ser! Makes sense, thank you!

**Pull request merged**
