### PR TITLE
Fix waves adapters

### PR DESCRIPTION
**Pull request by KardanovIR**
Fixed source domain for 4 waves adapters and added one missing.

---
##### Name (to be shown on DefiLlama):
Puzzle Lend

##### Twitter Link:
https://twitter.com/puzzle_lend

##### List of audit links if any:
–

##### Website Link:
https://lend.puzzleswap.org/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://lend.puzzleswap.org/static/media/darkLogo.3fc27cfb4522b8fa08b5933d75df4501.svg

##### Current TVL:
1175507.6129786454

##### Treasury Addresses (if the protocol has treasury)
–

##### Chain:
Waves

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
puzzle-swap

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
–

##### Short Description (to be shown on DefiLlama):
Puzzle Lend is the safest Lending Protocol built on the Waves blockchain 🧩

##### Token address and ticker if any:
PUZZLESWAP

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
TWAP

##### forkedFrom (Does your project originate from another project):
–

##### methodology (what is being counted as tvl, how is tvl being calculated):
The sum of TVL of 4 separated pools. TVL in every pool calculated as tokenAmount * tokenPrice, where tokenPrice is from coingecko.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/neutrino exports TVL: 
        
 
 
    waves                     7.44 M
    
    total                    7.44 M

**Comment by llamatester** [comment]
The adapter at projects/pluto exports TVL: 
        
 
 
    waves                     1.72 M
    
    total                    1.72 M

**Comment by llamatester** [comment]
The adapter at projects/swop exports TVL: 
        
 
 
    waves                     14.69 M
    
    total                    14.69 M

**Comment by llamatester** [comment]
The adapter at projects/vires exports TVL: 
        
 
 
    waves                     45.48 M
    waves-borrowed            33.14 M
    borrowed                  33.14 M
    
    total                    45.48 M

**Comment by llamatester** [comment]
The adapter at projects/puzzle-lend.js exports TVL: 
        
 
 
    waves                     1.33 M
    
    total                    1.33 M

**Comment by llamatester** [comment]
The adapter at projects/neutrino exports TVL: 
        
 
 
    waves                     7.48 M
    
    total                    7.48 M

**Comment by llamatester** [comment]
The adapter at projects/pluto exports TVL: 
        
 
 
    waves                     1.71 M
    
    total                    1.71 M

**Comment by llamatester** [comment]
The adapter at projects/swop exports TVL: 
        
 
 
    waves                     14.76 M
    
    total                    14.76 M

**Comment by llamatester** [comment]
The adapter at projects/vires exports TVL: 
        
 
 
    waves                     45.39 M
    waves-borrowed            33.08 M
    borrowed                  33.08 M
    
    total                    45.39 M

**Comment by llamatester** [comment]
The adapter at projects/puzzle-lend exports TVL: 
        
 
 
    waves                     1.33 M
    
    total                    1.33 M

**Comment by g1nt0ki** [comment]
@KardanovIR thank you, I have been waiting for this

**Comment by g1nt0ki** [comment]
@KardanovIR noticed an issue with tvl calculation, can you split borrowed amount from tvl, right now you are count total supplied as tvl, it should be (supplied - borrowed), we will wait with the listing

**Comment by KardanovIR** [comment]
@g1nt0ki thank you very much! 
PuzzleLend tvl calculation has been fixed on the service side, so the adapter should correct data now.

**Pull request merged**
