### PR TITLE
include new vaults and hallmarks for Vaultka

### PR DESCRIPTION
**Pull request by 0xKMG**
1. Add GMXV2 leverage and lending vault 
2. Add hallmarks for vaults that have impact on TVLs

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/vaultka: 
        
 
  
    
    
    AxiosError: Request failed with status code 403

**Comment by llamatester** [comment]
Error while running adapter at projects/vaultka: 
        
 
  
    
    
    AxiosError: Request failed with status code 403

**Comment by 0xKMG** [comment]
Hi Team, the local test is passing but not Github Action, any reason for that?

**Comment by llamatester** [comment]
The adapter at projects/vaultka exports TVL: 
        
 
 
    arbitrum                  1.83 M
    
    total                    1.83 M

**Pull request closed without merging**
