### PR TITLE
bolide: consider total supply BLID on tvl

### PR DESCRIPTION
**Pull request by Scriptoz**
Bolide: update TVL after contracts upgrade

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bolide exports TVL: 
        
 
 
    bsc-staking               846.78 k
    bsc-pool2                 108.93 k
    bsc                       3.60 M
    staking                   846.78 k
    pool2                     108.93 k
    
    total                    3.60 M

**Comment by g1nt0ki** [comment]
@Scriptoz this is counting staking value again under tvl, why?

**Comment by Scriptoz** [comment]
> @Scriptoz this is counting staking value again under tvl, why?

@g1nt0ki The user is able to boost APY by depositing BLID into the vault smart contract. Another option is to put BLID onto the staking pool. It is different contracts and the logic behind them. Since it is put in the vault, we calculate it as TVL

**Comment by g1nt0ki** [comment]
@Scriptoz so you have two different contracts for staking? but even in that case, it would still be counted under staking, not tvl.

**Comment by g1nt0ki** [comment]
But still it is native token so goes into staking: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by llamatester** [comment]
The adapter at projects/bolide exports TVL: 
        
 
 
    bsc-pool2                 110.96 k
    bsc                       3.65 M
    bsc-staking               952.05 k
    pool2                     110.96 k
    staking                   952.05 k
    
    total                    3.65 M

**Comment by Scriptoz** [comment]
> But still it is native token so goes into staking: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

@g1nt0ki Ok, thank you. The calculation has been updated according your comment.

**Pull request merged**
