### PR TITLE
add MUX TVL adapter

### PR DESCRIPTION
**Pull request by xionyk**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
MUX

##### Twitter Link:
https://twitter.com/muxprotocol

##### List of audit links if any:
https://www.certik.com/projects/mux-protocol

##### Website Link:
https://mux.network/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
MUX Black

##### Current TVL:
fantom                    1.45 M
bsc                       1.86 M
arbitrum                  6.76 M
avax                      1.38 M

total                    11.45 M

##### Chain:
Arbitrum,  Binance, Avalanche, Fantom

##### Short Description (to be shown on DefiLlama):
Trade crypto on the MUX protocol with zero price impact, up to 100x leverage and no counterparty risks.

##### Token address and ticker if any:
MCB：0x4e352cf164e64adcbad318c3a1e222e9eba4ce42

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Derivatives

##### methodology (what is being counted as tvl, how is tvl being calculated):
This is the total value of all tokens in the MUXLP Pool. The liquidity pool consists of a token portfolio used for margin trading and third-party DEX mining.

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hey, @xionyk thanks for the PR. Should we simply rebrand MCDEX to MUX Protocol?
https://defillama.com/protocol/mcdex

**Comment by xionyk** [comment]
Hey,@realdealshaman thanks for your advice, but the TVL information of MUX Protocol is actually different from that of MCDEX. If possible, we would like to remove the MCDEX and use the MUX Protocol

**Comment by llamatester** [comment]
The adapter at projects/mux exports TVL: 
        
 
 
    bsc                       1.21 M
    avax                      735.08 k
    fantom                    736.35 k
    arbitrum                  7.84 M
    
    total                    10.53 M

**Comment by xionyk** [comment]
Okey, I also think it is better to do a separate listing for MUX , so there is no need to change the adapter of MCDEX. This pr is submitted for MUX. The on-chain TVL of MUX can be obtained through this adapter.

**Comment by realdealshaman** [comment]
but you are not calling any contracts, can tvl be returned by token instead of fetching from your api?

**Comment by xionyk** [comment]
At present, it is the best way for us to fetch TVL through the api. If this method is not allowed, we will try other ways.

**Comment by realdealshaman** [comment]
we're trying to move away from using apis and are currently in the process of re-writing adapters that had been merged

**Comment by llamatester** [comment]
The adapter at projects/mux exports TVL: 
        
 
 
    bsc                       527.50 k
    arbitrum                  6.12 M
    avax                      167.24 k
    fantom                    113.10 k
    
    total                    6.93 M

**Pull request merged**
