### PR TITLE
Pawnfi

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/pawnfi-ape-staking exports TVL: 
        
 
 
    ethereum                  170.84 k
    
    total                    170.84 k

**Comment by llamatester** [comment]
The adapter at projects/pawnfi-lending exports TVL: 
        
 
 
    ethereum-borrowed         660.44 k
    ethereum                  652.53 k
    borrowed                  660.44 k
    
    total                    652.53 k

**Comment by llamatester** [comment]
The adapter at projects/pawnfi-nft exports TVL: 
        
 
 
    ethereum                  1.31 M
    ethereum-pool2            273.12 k
    pool2                     273.12 k
    
    total                    1.31 M

**Comment by llamatester** [comment]
The adapter at projects/pawnfi exports TVL: 
        
 
 
    
    total                    4.19 M

**Comment by dirk-pawnfi** [comment]
Just to clarify, LBP is a liquidity adding strategy that we raise liquidity from the users and help them add into Uniswap V3.
P-Token value is not counted in pawnfi-nft - there are only NFTs calculated
In our lending part, we only calculate Erc-20s and P-Token, which does not include NFTs. so we believe they are not double counted. 
We would love to proceed the merge and share with our community. Kindly let us know what is the next step, thanks.

**Pull request merged**
