### PR TITLE
Dyson - add fee-receiving wallets to TVL

### PR DESCRIPTION
**Pull request by Avedith**
Adding gnosis wallets that receive the fees from each pool to total TVL.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/dyson-money exports TVL: 
        
 
 
    polygon-staking           10.33 M
    arbitrum                  52.83 k
    polygon                   631.05 k
    optimism                  13.74 k
    staking                   10.33 M
    
    total                    697.62 k

**Comment by realdealshaman** [comment]
@Avedith Hi, are the wallet addresses you're trying to add Gnosis safes?

**Comment by 0xngmi** [comment]
we cant enforce that only fees will be on those gnosis safes, and seeing that the tvl there is negligible id rather exclude them

**Comment by ponury1990** [comment]
proszę o pomoc ja nie rozumiem bardzo co mam zrobić żebym mogł otrzymać wypłaty

**Comment by ponury1990** [comment]
Proszę mi pomoc w najprostszy sposób dotrzymać jakakolwiek płynność finansowa proszę

**Comment by Avedith** [comment]
@0xngmi Yeh, fair enough. I was having that same thought that we couldn't technically count it as TVL until it is locked in the ylSPHERE contract. Will close the PR then. :)

**Pull request closed without merging**
