### PR TITLE
add(tvl): florence finance

### PR DESCRIPTION
**Pull request by bbjansen**
##### Name (to be shown on DefiLlama):
Florence Finance

##### Twitter Link:
https://twitter.com/FinanceFlorence

##### List of audit links if any:
https://github.com/pashov/audits/blob/master/solo/FlorenceFinance-security-review.md

##### Website Link:
https://florence.finance/

##### Logo (High resolution, will be shown with rounded borders):
https://cdn.florence.finance/brand/logo/symbol/light-4x.png

##### Current TVL:
5.4M

##### Treasury Addresses (if the protocol has treasury)
N/A

##### Chain:
Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): 
N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): 
N/A

##### Short Description (to be shown on DefiLlama):
Florence is a DeFi platform that allows users to seamlessly integrate real-world (SME) yield into their cryptocurrency portfolio in the most transparent and sustainable way. By tokenizing real-world assets and collateral, Florence enables their composability within DeFi.

##### Token address and ticker if any:
N/A

##### Category (full list at https://defillama.com/categories) *Please choose only one:
RWA

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
N/A

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
The platform TVL is the sum of all loans outstanding of each vault on the platform, on-chain. 

The adapter queries the set of vault IDs from the vault registry contract using the read method ``getLoanVaultIds``. Once the vault IDs have been fetched, the IDs are used as arguments to fetch the vault address for each vault using the read method ``getLoanVault``. Once the addresses have been gathered, the adapter loops over the set and uses the ``loansOutstanding``read call to receive each vault's total loans outstanding (which is the sum of all on-chain loans) which is then aggregated into a final EURS balance using the ``sumSingleBalance`` utils function.

The Loans Outstanding unit (vault token) is equivalent to 1 EURS (stasis) as platform users will be able to convert these at a 1:1 ratio at any time through the platform's intermediary token (FLR). This means that the total TVL of the entire platform (all vaults) is the sum of all loans outstanding for each vault and is denominated in EURS.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/florence-finance/

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/florence-finance exports TVL: 
        
 
 
    ethereum                  5.46 M
    
    total                    5.46 M

**Comment by g1nt0ki** [comment]
hi @bbjansen thanks for the PR, we consider this 'undercollaterized lending', so would like to count only deposited amount that is not lent out as tvl, but I guess all that show up on chain are already borrowed?

**Comment by alexflorence** [comment]
> hi @bbjansen thanks for the PR, we consider this 'undercollaterized lending', so would like to count only deposited amount that is not lent out as tvl, but I guess all that show up on chain are already borrowed?

Our protocol, in a nutshell, works like this:

1) A delegate finds a real-world lending opportunity and creates a funding request
2) A funder fills the request and funds (stablecoins) are transferred from their wallet to the delegates wallet
3) The funder receives FLR equivalent to the funds they committed which are deposited into the vault
4) The delegate deploys this into the real-world (off-chain) within the bounds of a legal loan agreement
5) The delegate transfers interest from the real-world loan back into the vault where
 
This is a real effort, especially connecting real-world borrowers with crypto funders. We have proper documentation for all the underlying loan agreements and lending activity. I am not sure if we can bring this on-chain in a way that would satisfy your criteria for TVL - we probably can not. Having idle funds on-chain defeats the purpose of our protocol as the goal is it have it lent out to real-world parties.

Is it possible to just categorize this as "borrowed" or make it visible in some other way?

**Comment by g1nt0ki** [comment]
>  "Is it possible to just categorize this as "borrowed" or make it visible in some other way?"
  
  Yes, this works, this is what we do in Maple's case

**Pull request closed without merging**
