### PR TITLE
Update TVL data

### PR DESCRIPTION
**Pull request by crispyfisherman**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
## Description

Hi, we want to correct the TVL data. The original code didn't give the right coin type.

By the way, can we change the DoubleUp protocol this way?

image

Cause Pumpup and Unihouse are two different projects on DoubleUp, one is a Launchpad, and the other is a Yield protocol. It will be better to list these projects under DoubleUp like this separately

- DoubleUp
   - Pumpup
   - Unihouse Protocol

### CODE REVIEW

**Comment by crispyfisherman** [comment]
Hey, @g1nt0ki thanks for merging our updates.

is there a change that we could change the name of our protocol in this structure?

- DoubleUp
  - Pumpup
  - Unihouse Protocol

**Comment by crispyfisherman** [comment]
> @crispyfisherman what are those 2 listing? Can only find this one https://defillama.com/protocol/doubleup-pumpup#information
> 
> What is the unihouse?

Hi @Define101 

The Pumpup and Unihouse Protocol are two different projects on DoubleUp

[Pumpup](https://www.doubleup.fun/pumpup) is the first memecoins launch pad on SUI

image

[Unihouse Protocol](https://www.doubleup.fun/unihouse) is a Yield Protocol that operates through a series of "houses," each representing different assets such as SUI or BUCK. Users can stake their assets in these houses to earn profits in alignment with that house's overall performance.

image

We initially listed Pumpup on DeFiLlama with support from Mysten Labs. Recently, we launched the Unihouse Protocol and requested its separate listing on DeFiLlama. 

However, it turns out that the two projects have been merged, which was not the outcome we expected. 

Is there a way to list them as two distinct projects under DoubleUp?

**Comment by g1nt0ki** [comment]
@crispyfisherman currect code is only for the unihouse right? can you put up a new adapter for laundpad part?

**Comment by crispyfisherman** [comment]
> @crispyfisherman currect code is only for the unihouse right? can you put up a new adapter for laundpad part?

We should already have one, if it doesn't, we can put up a new one

**Pull request merged**
