### PR TITLE
EVAA adapter

### PR DESCRIPTION
**Pull request by sepezho**
EVAA protocol adapter

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/evaa exports TVL: 
        
 
 
    ton                       66.32 k
    
    total                    66.32 k

**Comment by sepezho** [comment]
Yes it is true you can see it from https://app.evaa.finance/market

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
can you please fill in the project details, the form was in the PR description.

**Comment by g1nt0ki** [comment]
is there some  way to pull the total borrowed info on chain? also, thanks for the PR :)

**Comment by sepezho** [comment]
yes, we can pull onchain total borrow & total supply via tonapi url

**Comment by sepezho** [comment]
does total supply & total borrow needed?

**Comment by g1nt0ki** [comment]
> does total supply & total borrow needed?

strictly speaking, total borrowed is not required, but thought it would be nicer for your protocol users to see. For lending protocols, we consider only the available liquidity and not total supplied as tvl as users can leverage/loop suuple-borrow

I will merge this PR for now, so we get you listed and then you can put up a PR for tracking borrowed amount.

**Comment by g1nt0ki** [comment]
*supply

**Pull request merged**
