### PR TITLE
feat: Add Ledgity Yield TVL adapter

### PR DESCRIPTION
**Pull request by LilaRest**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Ledgity Yield

##### Twitter Link:
https://twitter.com/LedgityYield

##### List of audit links if any:
N/A

##### Website Link:
https://ledgity.finance/

##### Logo (High resolution, will be shown with rounded borders):
High-res profile picture can be downloaded here:
https://github.com/LedgityLabs/LedgityYield/blob/main/public/assets/logo/pfp.png

##### Current TVL:
$7.61k

##### Chain:
- Linea
- Arbitrum

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

##### Short Description (to be shown on DefiLlama):
Ledgity Yield is a stablecoin yield protocol backed by Real World Assets (RWA).
It provides stablecoins' holders with a stable and high-efficiency yield solution. 

##### Token address and ticker if any:
Ticker: `LUSDC`

Addresses:
- Arbitrum One: 0xd54d564606611A3502FE8909bBD3075dbeb77813
- Linea: 0x4af215dbe27fc030f37f73109b85f421fab45b7a

##### Category (full list at https://defillama.com/categories) *Please choose only one:
RWA

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
None

##### forkedFrom (Does your project originate from another project):
None

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is calculated by taking the sum of all USDC deposited in LUSDC pools cross-chains.

##### Github org/user (Optional, if your code is open source, we can track activity):
- Org: https://github.com/LedgityLabs
- Main repo: https://github.com/LedgityLabs/LedgityYield

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/ledgity-yield exports TVL: 
        
 
 
    arbitrum                  3.54 k
    linea                     4.13 k
    
    total                    7.67 k

**Comment by g1nt0ki** [comment]
hi, this might be rwa but it is uncollateralized lending, so we can count the USDC left in the contracts as tvl & and LUSDC supply - usdc in the contracts under 'borrowed'

This is what we do for similar protocols.

**Comment by LilaRest** [comment]
> hi, this might be rwa but it is uncollateralized lending, so we can count the USDC left in the contracts as tvl & and LUSDC supply - usdc in the contracts under 'borrowed'

Hey @g1nt0ki!
Deposited USDC are collateralized in a 1:1 ratio (in USD) by the off-chain RWA portofolio.
PoR (Proof-of-Reserve) will be available on-chain in the future to provide collateral transparency.

USDC retained on the contract are dormant funds used to enable users to make instant withdrawals, they aren't "not yet borrowed funds".

The total value of USDCs locked into the protocol is represented by the total supply of LUSDC, as LUSDCs are minted in a 1:1 ratio for each USDC deposited.

**Comment by g1nt0ki** [comment]
sorry, but there is no way for us to verify the off chain data, there are some protocols on defilama which borrow money  in chain and do arb on cex but  again since we cant verify the data, we count only on chain value as tvl.

**Comment by LilaRest** [comment]
> sorry, but there is no way for us to verify the off chain data, there are some protocols on defilama which borrow money in chain and do arb on cex but again since we cant verify the data, we count only on chain value as tvl.

That's clear, I understand.
Do you consider on-chain PoR as a way to verify the off-chain data?

Or, when LUSDC will be listed on DEXs and will have a value of $1, would it be possible to consider the totalSupply() of LUSDC as TVL?

**Comment by g1nt0ki** [comment]
hi @LilaRest 

Yeah, on chain PoR could work, not sure how it can be done for RWA though, closest example I can think of is, holding tokenized treasury tokens/bonds.

No, method of using LUSDC supply * price would not work.

**Comment by LilaRest** [comment]
> No, method of using LUSDC supply * price would not work.
I'm not sure to understand why it wouldn't.
AFAIK this how for example stUSDT computes its TVL too.
Can you explain what's the difference here?

**Comment by g1nt0ki** [comment]
@LilaRest good question, I would say it is about my pay grade. If I had a choice, stUSDT wouldnt be listed at all

**Comment by LilaRest** [comment]
> good question, I would say it is about my pay grade. If I had a choice, stUSDT wouldnt be listed at all

Who should we reach to answer this question?
I think this is how Overnight's stablecoins TVL is computed too.
And what about the one of Tangible, Ondo, BackedFi? They all use off-chain RWA collateral.

**Comment by 0xngmi** [comment]
stUSDT and Ondo are tokenization protocols that just bring some rwa stuff on-chain, your protocol seems to be closer to protocols like maple, where money deposited is then lent to some entity (that then uses it to buy RWA assets)

**Comment by LilaRest** [comment]
Hey @0xngmi ! Thanks for your answer.
Only our wording is different than stUSDT and Ondo ones (for legal reasons). But technically speaking, our financial setup are highly similar.

stUSDT is not tokenizing RWA directly, this is explained on the main page of their website : "This decentralized **intermediary** to real-world assets allows holders to ..."

Same thing for Ondo, their USDY acts as an intermediary between stablecoins investment and yield generated by the collateral RWA portfolio.

**Comment by LilaRest** [comment]
Hey @0xngmi @g1nt0ki ! Any news?

**Comment by g1nt0ki** [comment]
@LilaRest sorry, if we list you, we can do it only under "uncollateralized lending"

**Comment by g1nt0ki** [comment]
closed as we are at an impasse and no activity for more than two months

**Pull request closed without merging**
