### PR TITLE
add adapter for mushrooms finance

### PR DESCRIPTION
**Pull request by mushroomsforest**

### CODE REVIEW

**Comment by mushroomsforest** [comment]
@DefiLlama thanks for taking time to review and merge this PR.

**Comment by DefiLlama** [comment]
Hey guys your endpoint is down, please fix asap.

**Comment by mushroomsforest** [comment]
> 
> 
> Hey guys your endpoint is down, please fix asap.

sorry, one of our alchemy node got capacity exceed, it should be fine now.

**Comment by DefiLlama** [comment]
Looks like down again. Would appreciate if you could do a web3 script!

**Comment by mushroomsforest** [comment]
> 
> 
> Looks like down again. Would appreciate if you could do a web3 script!

sorry it get fixed now. We will make it more robust next week to avoid this downtime. Web3 script (directly interact with Ethereum contract) might need frequent update/commit/review since we are adding vaults/pools(modules which holds the TVL) every a few week. Really appreciate your support.

**Pull request merged**
