### PR TITLE
add rfx-exchange

### PR DESCRIPTION
**Pull request by zjesko**
##### Name (to be shown on DefiLlama):
RFX Exchange

##### Twitter Link:
https://x.com/RFX_exchange

##### List of audit links if any:
https://github.com/rfx-exchange/rfx-deployments/tree/main/audits

##### Website Link:
https://rfx.exchange

##### Current TVL:
1.33M

##### Chain:
zksync era

##### Short Description (to be shown on DefiLlama):
The first derivatives exchange with smart liquidity. Maximise your yield. Create your own trading pairs. Built on ZkSync Era

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Derivatives

##### Implementation Details: Briefly describe how the oracle is integrated into your project: 
Prices are provided by an off-chain system and posted on-chain upon a transaction being executed by the keepers

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
https://docs.rfx.exchange/oracle-system

##### methodology (what is being counted as tvl, how is tvl being calculated):
The total amount of assets held as liquidity across all RFX markets

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/rfx-exchange exports TVL: 
        
 
 
    era                       1.38 M
    
    total                    1.38 M

**Comment by g1nt0ki** [comment]
thanks for the PR

**Comment by llamatester** [comment]
The adapter at projects/rfx-exchange exports TVL: 
        
 
 
    era                       1.37 M
    
    total                    1.37 M

**Comment by zjesko** [comment]
hello @g1nt0ki 

RFX has been marked as GMXv2 fork
Even though the interfaces are similar, the codebase is has deviated substantially. Is it possible to get that removed?

**Comment by g1nt0ki** [comment]
hi @zjesko 

But the code is forked from gmx v2 & customized? or is the code written from scratch?

**Comment by zjesko** [comment]
hey @g1nt0ki 

we referred to gmx in the intitial stages over a year ago, but now have introduced a lof features and modifications like adding a novel common pool and permissionless markets. Also the oracles work in a completely different manner leveraging a dual oracle setup involving pyth and stork. The revenue share mechanism is also distinct with an addition of insurance fund

would request you to please remove the fork tag as it mispresents our product

**Pull request merged**
