### PR TITLE
add ESLint config

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/algodex.js exports TVL: 
        
 
 
    algorand                  28.12 k
    
    total                    28.12 k

**Comment by llamatester** [comment]
The adapter at projects/algodex.js exports TVL: 
        
 
 
    algorand                  28.10 k
    
    total                    28.10 k

**Comment by llamatester** [comment]
The adapter at projects/0xDAO exports TVL: 
        
 
 
    fantom                    1.59 M
    
    total                    1.59 M

**Comment by llamatester** [comment]
The adapter at projects/0x_nodes exports TVL: 
        
 
 
    ethereum                  0
    bsc                       0
    polygon                   0
    fantom                    0
    metis                     0
    avax                      0
    ethereum-staking          0
    avax-staking              0
    fantom-staking            0
    bsc-staking               0
    polygon-staking           6.40 k
    metis-staking             3.16 k
    staking                   9.56 k
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/1swap exports TVL: 
        
 
 
    moonriver                 19.36 k
    
    total                    19.36 k

**Comment by llamatester** [comment]
The adapter at projects/abracadabra exports TVL: 
        
 
 
    fantom                    90.23 k
    avax                      163.10 k
    arbitrum                  4.46 M
    ethereum                  59.32 M
    
    total                    64.03 M

**Comment by llamatester** [comment]
The adapter at projects/adamantfinance exports TVL: 
        
 
 
    polygon-staking           776.08 k
    polygon-pool2             253.17 k
    cronos-staking            574.845
    arbitrum-staking          11.44 k
    arbitrum                  27.72 k
    polygon                   1.72 M
    cronos                    17.19 k
    staking                   788.10 k
    pool2                     253.17 k
    
    total                    1.76 M

**Comment by llamatester** [comment]
The adapter at projects/alchemix exports TVL: 
        
 
 
    ethereum-staking          6.76 M
    optimism                  552.39 k
    ethereum                  63.16 M
    fantom                    107.20 k
    staking                   6.76 M
    
    total                    63.82 M

**Comment by llamatester** [comment]
The adapter at projects/algodex.js exports TVL: 
        
 
 
    algorand                  27.61 k
    
    total                    27.61 k

**Comment by llamatester** [comment]
The adapter at projects/algorai-finance exports TVL: 
        
 
 
    algorand                  331.14 k
    
    total                    331.14 k

**Comment by llamatester** [comment]
The adapter at projects/alkemi exports TVL: 
        
 
 
    ethereum                  405.58 k
    
    total                    405.58 k

**Comment by llamatester** [comment]
The adapter at projects/anyswap exports TVL: 
        
 
 
    ethereum                  90.40 M
    optimism                  47.2669
    kardia                    0
    cronos                    0
    rsk                       20.76 k
    telos                     648.20 k
    bsc                       102.74 M
    syscoin                   758.02 k
    ontology_evm              0
    ethereumclassic           21.88 k
    okexchain                 16.98 M
    hoo                       0
    tomochain                 0
    xdai                      282.05 k
    velas                     0
    thundercore               0
    fuse                      2.17 k
    heco                      1.06 M
    polygon                   3.25 M
    bittorrent                0
    fantom                    506.86 M
    boba                      0
    kcc                       739.52 k
    shiden                    639.97 k
    astar                     8.49 k
    clv                       0
    conflux                   0
    metis                     0
    moonbeam                  16.33 M
    moonriver                 32.03 M
    cube                      0
    dogechain                 2.35 M
    milkomeda                 1.26 M
    milkomeda_a1              0
    ronin                     0
    kava                      0
    iotex                     1.87 M
    klaytn                    0
    evmos                     49.26 k
    smartbch                  0
    ethpow                    0
    bitgert                   0
    fusion                    183.88 k
    arbitrum                  283.80 k
    arbitrum_nova             0
    celo                      51.2026468634656
    oasis                     432.36 k
    avax                      3.71 M
    rei                       80.24 k
    dfk                       0
    godwoken_v1               0
    aurora                    0
    harmony                   595.49 k
    
    total                    783.58 M

**Comment by llamatester** [comment]
The adapter at projects/atmossoft.js exports TVL: 
        
 
 
    fantom                    0
    fantom-pool2              0
    bsc-pool2                 0
    pool2                     0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/auraswap exports TVL: 
        
 
 
    polygon-staking           0
    polygon                   1.05 k
    staking                   0
    
    total                    1.05 k

**Comment by llamatester** [comment]
The adapter at projects/avalaunch exports TVL: 
        
 
 
    avax                      0
    avax-staking              5.03 M
    avax-pool2                11.79 k
    staking                   5.03 M
    pool2                     11.79 k
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/avault exports TVL: 
        
 
 
    astar                     3.90 M
    
    total                    3.90 M

**Comment by llamatester** [comment]
Error while running adapter at projects/barnbridge: 
        
 
  
    
    
    Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0xaCD2c6b9f8Caf18cf182d6EFd8f1a7b0B0C6A141","data":"0x66eb06fa","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:654:52
        at Array.forEach (<anonymous>)

**Review by alokeutpal — APPROVED** [review]

**Pull request merged**
