### PR TITLE
Redacted v2

### PR DESCRIPTION
**Pull request by swheel33**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Parent: Redacted
Redacted v2
Pirex

##### Twitter Link:
https://twitter.com/redactedcartel

##### List of audit links if any:
Redacted v2: https://omniscia.io/reports/redacted-cartel-butterfly-token-v2/
Pirex: https://omniscia.io/pirex-multi-token-convex-wrapper/

##### Website Link:
Redacted v2: https://redacted.finance
Pirex: https://pirex.io

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
Redacted v2: https://app.redacted.finance/assets/images/tokens/BTRFLY.png
Pirex: https://pirex.io/favicon.png

##### Current TVL:
Redacted v2: 48.25 M
Pirex: 6.15 M

##### Chain:
Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
id: redacted

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
id: 21324

##### Short Description (to be shown on DefiLlama):
Redacted v2: The Redacted ecosystem is a product suite of smart contracts empowering on-chain liquidity, governance, and cash flow for DeFi protocols.
Pirex: Pirex is a product by Redacted which creates liquid wrappers that allow for auto-compounding and the tokenization of future yield/vote events

##### Token address and ticker if any:
BTRFLY: 0xc55126051b22ebb829d00368f4b12bde432de5da

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Services

##### methodology (what is being counted as tvl, how is tvl being calculated):
Redacted v2: TVL is calculated from the total treasury assets captured from bonding, in addition to the amount of rlBTRFLY currently locked in the protocol.
Pirex: TVL is calculated from the total supply of pxCVX, designating the amount of CVX locked in the protocol.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/redacted exports TVL: 
        
 
 
    ethereum                  48.46 M
    
    total                    48.46 M

**Comment by llamatester** [comment]
The adapter at projects/pirex exports TVL: 
        
 
 
    ethereum                  6.24 M
    
    total                    6.24 M

**Comment by realdealshaman** [comment]
Hey, why would locked BTRFLY tokens not be considered staking tvl?

**Comment by llamatester** [comment]
The adapter at projects/redacted exports TVL: 
        
 
 
    ethereum-staking          22.01 M
    ethereum                  23.16 M
    staking                   22.01 M
    
    total                    23.16 M

**Comment by llamatester** [comment]
The adapter at projects/pirex exports TVL: 
        
 
 
    ethereum                  6.22 M
    
    total                    6.22 M

**Pull request merged**
