### PR TITLE
Add Dxsale / DxEcosystem TVL

### PR DESCRIPTION
**Pull request by DaRabus**
##### Current TVL: 
Should be around 13 Billions
image

##### Chain:
ETH / BSC / POLYGON / AVAX / FANTOM / HECO / OEC / KCC / ARBITRUM / GNOSIS / HARMONY / CELO /CRONOS / MOONRIVER / SMARTBCH / MILKOMEDA

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list):
dxsale-network

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000):
https://coinmarketcap.com/currencies/dxsale-network/

##### Short Description (to be shown on DefiLlama): 
With currently 16 supported chains, Dx is the biggest IDO Launchpad in the crypto space. As a truly decentralized token management platform, we aim for a low-barrier approach to launching your project. Instead of a steep learning curve and cumbersome interfaces, our platform will provide all the necessary tools to create and launch your project with no prior coding skills required. Of course, you can also use our platform if you’re just here to invest in a project you deem interesting. This will be the first decision you will face:

##### Token address and ticker if any:
https://etherscan.io/address/0xF063fE1aB7a291c5d06a86e14730b00BF24cB589

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Launchpad

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
None

##### forkedFrom (Does your project originate from another project):
No, first of its kind since Aug20

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is accounted by summing up the locked values from our newer contracts we introduced with Version 3.3 which we can fetch by a storage contract pretty fast, then we add up all the older locks we had, these are the V3 Archives which are quite big, since the contracts didnt yet have a single method to fetch all necessary data, this takes a while to fetch them, at the end the locked tokens are LPs are stored in an array which is then defined by the helper functions from defillama

### Comment:

May you got an idea if i could somehow improve the speed, actually the script takes more than 20h right now on my machine to finish up all the calculations, which is quite a big amount of time, but yeah we have more than 30'000 locks to query over 15 Blockchains.

Seems like there is no "transformAddress" function from SmartBCH yet around, so i keep this out for now

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@DaRabus for starters, thanks for the PR, I see that you have put a lot of effort into it.

I am going to a take a bit of time to review it, quite a bit of code. Current methodology for launchpads is, we count only the LPs, since it is very hard for get pricing of everything, cant really rely on pools or coingecko for price as pools can have low liquidity and would not reflect actual token price. You can check our code for Pinksale/Deeplock/unicrypt for confirmation.

yeah, sorry 20 hours is no go, we try to keep  adapter run under 5 minutes, and we try to update info every hour. I took a brief glance at your code, I think I know how it can be improved, I will give it a try and keep you posted :)

**Comment by g1nt0ki** [comment]
@DaRabus for me, the calls to `getStorageLockDataV33/AllLockRecord` abi fails, I am not sure why. is the abi correct? Failed in both ethereum and in bsc network

**Comment by DaRabus** [comment]
@g1nt0ki  Hey, yes i've seen an error, i accidently used the same ABI for Token/Lp Lockers, the name is the same, but the return for the LP locks is different

I updated it.

**Comment by DaRabus** [comment]
@g1nt0ki  Now it's also way faster

image

**Comment by g1nt0ki** [comment]
@DaRabus hi, I did some code refactor here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/3246 

Also, I have disabled some lockers, they were containing tokens or empty and in moonriver's case the new LP locker is pointing to wrong address? at least in the explorer I didnt see any contract, so I commented it out.

Give it a try and let me know if any of the chains still have some issue

**Comment by g1nt0ki** [comment]
with the test run results: https://github.com/DefiLlama/DefiLlama-Adapters/pull/3247

**Pull request merged**
