### PR TITLE
Add hallmark of FTX collapse event

### PR DESCRIPTION
**Pull request by yym-mtrlabs**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/amulet-liquidity-staking: 
        
 
  
    
    
    Error: failed to get info about account DEg9mNnxwqJQiYz2mXpVJmq8Yyx14oZ2SaYpHS7mB2mx: StructError: Expected the value to satisfy a union of `type | type`, but received: [object Object]
    Truncated error stack:
        at Connection.getAccountInfo (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@solana/web3.js/lib/index.cjs.js:7656:13)
        at async tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/amulet-liquidity-staking/index.js:7:27)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:51:25)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:146:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:191:3

**Comment by llamatester** [comment]
The adapter at projects/amulet-liquidity-staking exports TVL: 
        
 
 
    solana                    62.03 k
    
    total                    62.03 k

**Comment by llamatester** [comment]
The adapter at projects/amulet-protocol exports TVL: 
        
 
 
    solana                    21.60 k
    
    total                    21.60 k

**Comment by llamatester** [comment]
The adapter at projects/amulet-liquidity-staking exports TVL: 
        
 
 
    solana                    62.03 k
    
    total                    62.03 k

**Comment by llamatester** [comment]
The adapter at projects/amulet-protocol exports TVL: 
        
 
 
    solana                    21.60 k
    
    total                    21.60 k

**Comment by yym-mtrlabs** [comment]
@g1nt0ki Hi thanks for helping to merge.

Checked the updated page at https://defillama.com/protocol/amulet , seems on the merged page there are duplicated hallmark of FTX collapse. Understand that this is because the same hallmark is added in both of the sub page, may I check whether its possible to keep only one in the merged page?

**Pull request merged**
