### PR TITLE
update synapse

### PR DESCRIPTION
**Pull request by BlazeWasHere**
```
------ TVL ------
moonriver                 4.24 M
moonbeam                  313.96 k
avalanche                 162.68 M
bsc                       79.23 M
ethereum                  68.95 M
ethereum-pool2            63.61 M
aurora                    29.86 M
cronos                    651.9599640854019
fantom                    118.07 M
optimism                  40.50 M
harmony                   27.85 M
polygon                   44.64 M
arbitrum                  145.78 M
boba                      11.85 M
metis                     23.53 M
pool2                     63.61 M

total                    757.50 M 
```
work @llamatester

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/synapse/index.js exports TVL: 
        
 
 
    moonbeam                  313.96 k
    moonriver                 4.24 M
    optimism                  40.50 M
    ethereum-pool2            63.61 M
    ethereum                  68.92 M
    bsc                       79.23 M
    polygon                   44.64 M
    avalanche                 162.68 M
    cronos                    651.9599640854019
    fantom                    118.08 M
    harmony                   27.85 M
    boba                      11.85 M
    arbitrum                  145.78 M
    metis                     23.53 M
    aurora                    29.86 M
    pool2                     63.61 M
    
    total                    757.46 M

**Comment by BlazeWasHere** [comment]
marking as a draft, need to add terra

**Comment by g1nt0ki** [comment]
Hi @BlazeWasHere 

Can you explain this address in ethereum pool2 '0xe59AD064E83b83259C03030AC497e8b733F25407', it does not look like a masterchef

Also, this is the part I dont understand, when I am counting at bridges + pools, I am getting only about 550M, but in your calculation it is 757M. Am I missing something important?

**Comment by BlazeWasHere** [comment]
> Hi @BlazeWasHere
> 
> Can you explain this address in ethereum pool2 '0xe59AD064E83b83259C03030AC497e8b733F25407', it does not look like a masterchef

It is LaaS by Ondo, had asked this to @0xngmi before and was allowed to be counted as pool2.

> Also, this is the part I dont understand, when I am counting at bridges + pools, I am getting only about 550M, but in your calculation it is 757M. Am I missing something important?

You do not count locked nusd/neth assets which are either in pools or on mainnet bridge contract, and missing some tokens on some chains e.g NEWO, GMX, NFD, JEWEL - it is quite cumbersome to see what is missing as you have not left comment of token symbols in config.js.

**Comment by g1nt0ki** [comment]
This is result of current adapter run, I have included GMX, DOG, JEWEL, XJEWEL
Missing Newo is 1.5M
Is JEWEL locked on the same bridge as xJEWEL in harmony because I am seeing only 10.
But I am counting the USDC/T and ETH on bridges, that should cancel out not count nusd/neth right?


    --- terra ---
    terrausd                  5.29 M
    Total: 5.29 M 

    --- aurora ---
    USDT                      10.83 M
    USDC                      10.59 M
    UNKNOWN (aurora:0x0000000000000000000000000000000000000000) 0
    Total: 21.43 M 

    --- moonriver ---
    MOVR                      120.95 k
    Total: 120.95 k 

    --- moonbeam ---
    UNKNOWN (moonbeam:0x0db6729c03c85b0708166ca92801bcb5cac781fc) 0
    WGLMR                     0
    Total: 0 

    --- boba ---
    WETH                      1.61 M
    DAI                       1.36 M
    USDT                      1.31 M
    USDC                      1.26 M
    Total: 5.55 M 

    --- ethereum ---
    WETH                      61.55 M
    USDT                      28.44 M
    GOHM                      22.60 M
    USDC                      17.38 M
    DAI                       15.74 M
    HIGH                      7.54 M
    FRAX                      4.62 M
    DOG                       383.00 k
    SDT                       208.01 k
    SYN                       9.03 k
    SFI                       309.05647719356455
    Total: 158.47 M 

    --- metis ---
    USDC                      11.78 M
    WETH                      2.22 M
    UNKNOWN (metis:0xe3c82a836ec85311a433fbd9486efaf4b1afbf48) 0
    UNKNOWN (metis:0x0000000000000000000000000000000000000000) 0
    Total: 14.00 M 

    --- ethereum-pool2 ---
    WETH                      9.57 M
    SYN                       9.43 M
    Total: 18.99 M 

    --- cronos ---
    USDC                      137.15 k
    CRO                       0
    Total: 137.15 k 

    --- optimism ---
    WETH                      10.94 M
    USDC                      3.96 M
    Total: 14.90 M 

    --- avax ---
    USDT                      21.04 M
    DAI                       18.74 M
    USDC                      17.28 M
    AWETH                     15.93 M
    avalanche-2               3.85 M
    SYN                       12.94 k
    GOHM                      6.15 k
    Total: 76.87 M 

    --- fantom ---
    USDT                      16.60 M
    USDC                      13.53 M
    WETH                      11.28 M
    MIM                       412.48 k
    FTM                       5.50 k
    Total: 41.83 M 

    --- arbitrum ---
    WETH                      23.84 M
    GMX                       16.44 M
    USDT                      15.99 M
    USDC                      14.87 M
    MIM                       443.61 k
    Total: 71.58 M 

    --- bsc ---
    USDT                      18.38 M
    BUSD                      14.83 M
    USDC                      14.10 M
    SYN                       5.23 k
    HIGH                      3.20 k
    WBNB                      528.6111999999999
    Total: 47.32 M 

    --- harmony ---
    xjewel                    21.26 M
    DAI                       3.96 M
    USDC                      3.91 M
    USDT                      3.86 M
    WETH                      3.18 M
    WAVAX                     167.61 k
    harmony                   186.21704870000002
    JEWEL                     12.792
    Total: 36.32 M 

    --- polygon ---
    USDT                      13.51 M
    DAI                       11.58 M
    USDC                      11.07 M
    MATIC                     6.85 k
    Total: 36.16 M 

    --- tvl ---
    USDT                      129.96 M
    USDC                      119.87 M
    WETH                      114.62 M
    DAI                       51.39 M
    GOHM                      22.61 M
    xjewel                    21.26 M
    GMX                       16.44 M
    AWETH                     15.93 M
    BUSD                      14.83 M
    HIGH                      7.55 M
    terrausd                  5.29 M
    FRAX                      4.62 M
    avalanche-2               3.85 M
    MIM                       856.09 k
    DOG                       383.00 k
    SDT                       208.01 k
    WAVAX                     167.61 k
    MOVR                      120.95 k
    SYN                       27.20 k
    MATIC                     6.85 k
    FTM                       5.50 k
    WBNB                      528.6111999999999
    SFI                       309.05647719356455
    harmony                   186.21704870000002
    JEWEL                     12.792
    UNKNOWN (aurora:0x0000000000000000000000000000000000000000) 0
    UNKNOWN (moonbeam:0x0db6729c03c85b0708166ca92801bcb5cac781fc) 0
    WGLMR                     0
    UNKNOWN (metis:0xe3c82a836ec85311a433fbd9486efaf4b1afbf48) 0
    UNKNOWN (metis:0x0000000000000000000000000000000000000000) 0
    CRO                       0
    Total: 529.98 M 

    --- pool2 ---
    WETH                      9.57 M
    SYN                       9.43 M
    Total: 18.99 M 

    ------ TVL ------
    terra                     5.29 M
    aurora                    21.43 M
    moonriver                 120.95 k
    moonbeam                  0
    boba                      5.55 M
    ethereum                  158.47 M
    metis                     14.00 M
    ethereum-pool2            18.99 M
    cronos                    137.15 k
    optimism                  14.90 M
    avax                      76.87 M
    fantom                    41.83 M
    arbitrum                  71.58 M
    bsc                       47.32 M
    harmony                   36.32 M
    polygon                   36.16 M
    pool2                     18.99 M

    total                    529.98 M 


Sorry, I know it is cumbersome but can you please have a look, there is a huge difference between our calculations, maybe I am missing something obvious like jewel, or UST which I am seeing only 5.3M

**Comment by g1nt0ki** [comment]
hi @BlazeWasHere did you have some time to look into this?

**Pull request closed without merging**
