### PR TITLE
Update Crownfinance TVL

### PR DESCRIPTION
**Pull request by 0xcrownlabs**
##### Twitter Link: 
https://twitter.com/CrownFi_

##### List of audit links if any:
https://github.com/solidproof/projects/blob/main/Crown%20Finance/SmartContract_Audit_Solidproof_Crown%20Finance.pdf

##### Website Link:
crownfinance.io

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://github.com/0xcrownlabs/logo

##### Short Description (to be shown on DefiLlama):
Crown Finance aims to bulid the best yield aggregator on Cronos. Join and use vaults to autocompound you assets.

##### Token address and ticker if any:
0xf287E8999fcbea602D2c5DD699ea2FF7f3685964

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Is the API open source?

**Comment by waynebruce0x** [comment]
I think we already have an onchain adapter for this and would prefer to continue using onchain calls

**Comment by 0xcrownlabs** [comment]
TVL should contain what is staked in the vaults sir. 

Api is not open-sourced

**Comment by 0xcrownlabs** [comment]
> TVL should contain what is staked in the vaults sir.
> 
> Api is not open-sourced

TVL should contain what is staked in the vaults sir.

Api is not open-sourced

> I think we already have an onchain adapter for this and would prefer to continue using onchain calls

TVL should contain what is staked in the vaults sir.

Api is not open-sourced

**Comment by 0xcrownlabs** [comment]
> 



> > TVL should contain what is staked in the vaults sir.
> > Api is not open-sourced
> 
> TVL should contain what is staked in the vaults sir.
> 
> Api is not open-sourced
> 
> > I think we already have an onchain adapter for this and would prefer to continue using onchain calls
> 
> TVL should contain what is staked in the vaults sir.
> 
> Api is not open-sourced

Could you update the stat on https://defillama.com/protocol/crown-finance . It's not showing the accurated number as in our newly updated file.

**Comment by 0xcrownlabs** [comment]
> Is the API open source?

@waynebruce0x

**Comment by waynebruce0x** [comment]
How can we calculate using onchain calls instead? 

We get all pools from 0x596008a6fb314a18100f36209635853d7ea80eba, then using poolInfo2.amount0 to get the total deposits of each pool/strategy - is that correct?

**Comment by waynebruce0x** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters/pull/2962

**Pull request closed without merging**
