### PR TITLE
Hinkal Protocol TVL.

### PR DESCRIPTION
**Pull request by ThakerJayam**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### List of audit links if any:
a) https://github.com/zokyo-sec/audit-reports/blob/main/Hinkal/Hinkal_Zokyo_Feb20th_2024.pdf
b) https://certificate.quantstamp.com/full/hinkal-protocol/66b9b783-8b42-4a4e-89ed-3ef2a2df5958/index.html
c) https://github.com/Secure3Audit/Secure3Academy/blob/main/audit_reports/Hinkal/Hinkal_final_Secure3_Audit_Report.pdf

##### Logo (High resolution, will be shown with rounded borders):
hinkal_without_text_gradient_black

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/Hinkal exports TVL: 
        
 
 
    base                      3.15 M
    ethereum                  1.08 M
    arbitrum                  84.35 k
    optimism                  16.06 k
    polygon                   8.12 k
    bsc                       4.52 k
    avax                      643
    
    total                    4.35 M

**Comment by g1nt0ki** [comment]
@ThakerJayam thanks for the PR, refactored and merged here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/9891/files

is there some way to dynamically pull supported tokens on chain? atm, we are pulling it through ankr appi, but it is not always accurate.

**Comment by ThakerJayam** [comment]
> @ThakerJayam thanks for the PR, refactored and merged here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/9891/files
> 
> is there some way to dynamically pull supported tokens on chain? atm, we are pulling it through ankr appi, but it is not always accurate.

Not sure @g1nt0ki. Even we have this hassle of maintaining all supported tokens but haven't found a good way to do that yet.

BTW, I have a small change in the Description. I want to change the name from "Hinkal Protocol" to just "Hinkal". Should I just edit that in the PR you made?

**Comment by g1nt0ki** [comment]
hi @ThakerJayam updated name here: https://github.com/DefiLlama/defillama-server/commit/9595d8f2608add55c1950e960e97e734da785d5c

**Pull request closed without merging**
