### PR TITLE
Hermes V2 - Maia V2 - TALOS

### PR DESCRIPTION
**Pull request by 0xLightt**
This entry is for 3 new protocols to be added to Maia DAO Ecosystem (maia-dao-ecosystem). Please let me know if you wish for me to create 3 separate PRs.

##### Name 

- hermes-v2: Hermes V2
- maia-v2: Maia V2
- talos: TALOS:

##### Twitter Link:

- hermes-v2: https://x.com/HermesOmnichain
- maia-v2: https://twitter.com/MaiaDAOEco
- talos: https://x.com/TalosOmnichain

##### List of audit links if any:

The following audits were for the 3 platforms:
- https://github.com/Zellic/publications/blob/master/Maia%20DAO%20February%202023%20-%20Zellic%20Audit%20Report.pdf
- https://code4rena.com/audits/2023-05-maia-dao-ecosystem

This audit only includes a Hermes contract:
- https://github.com/Zellic/publications/blob/master/Maia%20DAO%20V2%20Ecosystem%20-%20Zellic%20Audit%20Report.pdf

##### Website Link:

The same link is appropriate for all:

- hermes-v2: https://app.maiadao.io/ or https://www.maiadao.io/
- maia-v2: https://app.maiadao.io/ or https://www.maiadao.io/
- talos: https://app.maiadao.io/strategies

##### Logo (High resolution, will be shown with rounded borders):

- hermes-v2: 
image

- maia-v2: 
image

- talos: 
image

##### Current TVL:

We have cross-chain tokens that are redeemable 1:1 for majors (like ETH, USDC and USDT) on other chains. The value for these tokens is not being picked up in hermes-v2 TVL.

- hermes-v2: 503.13 k (4.04 M staked)
- maia-v2 (staked, not staked is zero): 724.11 k
- talos (staked, not staked is zero): 4.17 k

##### Treasury Addresses (if the protocol has treasury)

- hermes-v2 (all on Arbitrum):
  - 0x07D87055E82EAf4851Dfa251a5d79A7E99Bd789A
  - 0xb97c3D79Af827c915E5F6B492e6bd99D653F8cC7
  - 0xaCE7B2BbD13acE4E23F622209c46C9F2885edd49
  - 0x716147a2169246c09f47D9880Bf85D49093A92C4
  - 0xB4523B4541Ab27337AB8389188a545BF3d07d5E3
- maia-v2:
  - Mainnet: 0x10B03389B893D7Fe037A3BdC762a2850DD772C3a
  - Arbitrum: 0x744f3EC772AAA9f0d40398b90F9E856EF88D118A

talos doesn't have a treasury.

##### Chain:

Arbitrum

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

- hermes-v2: hermes-protocol
- maia-v2: maia

talos does not have a token.

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

- hermes-v2: hermes-protocol
- maia-v2: maia

talos does not have a token.

##### Short Description (to be shown on DefiLlama):

- hermes-v2:
Creating deep unified omnichain concentrated liquidity.

- maia-v2:
Maia simplifies your BurntHermes experience to maximize your yields.

- talos:
Decentralized liquidity management strategies functioning as a pool together of concentrated liquidity LPs, allowing users to renting out their Hermes-Boost.

##### Token address and ticker if any:

- hermes-v2:
  - address: 0x45940000009600102A1c002F0097C4A500fa00AB
  - ticker: HERMES
- maia-v2: maia
  - address: 0x00000000ea00F3F4000e7Ed5Ed91965b19f1009B
  - ticker: MAIA

talos does not have a token.

##### Category (full list at https://defillama.com/categories) *Please choose only one:

All 3 are Yield.

##### forkedFrom (Does your project originate from another project):

None of the three is a straight fork. But they use core logic from other protocol's contracts.

- hermes-v2: 
I don't think it qualifies as a fork. But will leave this here if you prefer to decide yourselves. Feel free to ask anything.
The logic was completely re-written codebase from V1 that was a Solidly fork with minor fixes.
Due to the size of the protocol, we adapted multiple contracts from other projects for our use cases:
- Voting (for gauges and governance) and rewards distributions from FEI's Flywheel-V2:
  - Ours: 
    - https://github.com/Maia-DAO/hermes-v2/tree/main/src/erc-20
    - https://github.com/Maia-DAO/hermes-v2/tree/main/src/rewards
  - FEI:
    - https://github.com/Maia-DAO/hermes-v2/blob/main/src/erc-20/ERC20Gauges.sol
- Uniswap V3 NFT staking from UniswapV3Staker from Uniswap:
  - Ours:
    - https://github.com/Maia-DAO/hermes-v2/tree/main/src/uni-v3-staker
  - Uniswap:
    - https://github.com/Uniswap/v3-staker

- maia-v2: 
NA

- talos: 
This one I am not sure. I still don't think it qualifies as a fork. But will leave this here if you prefer to decide yourselves. Feel free to ask anything.
We adapted Popsicle Finance Uniswap V3 strategies for our use case:
  - Ours:
    - https://github.com/Maia-DAO/talos
  - Popsicle:
    - https://github.com/Popsicle-Finance/PopsicleV3Optimizer

##### methodology (what is being counted as tvl, how is tvl being calculated):

- hermes-v2: The sum of All staked Uniswap V3 NFTs and burnt Hermes for staked TVL.
- maia-v2: Total Maia staked in VoteMaia.
- talos: The sum of all TALOS strategies' Uniswap V3 NFTs.

##### Github org/user (Optional, if your code is open source, we can track activity):
The same for all protocols:
- https://github.com/Maia-DAO

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/hermes-v2 exports TVL: 
        
 
 
    arbitrum-staking          4.11 M
    staking                   4.11 M
    arbitrum                  511.56 k
    
    total                    511.56 k

**Comment by llamatester** [comment]
The adapter at projects/maia-v2 exports TVL: 
        
 
 
    arbitrum-staking          722.57 k
    staking                   722.57 k
    arbitrum                  0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/talos exports TVL: 
        
 
 
    arbitrum-staking          4.27 k
    staking                   4.27 k
    arbitrum                  0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/maia-dao exports TVL: 
        
 
 
    metis                     1.54 M
    
    total                    1.54 M

**Comment by llamatester** [comment]
The adapter at projects/hermes-v2 exports TVL: 
        
 
 
    arbitrum-staking          3.95 M
    staking                   3.95 M
    arbitrum                  454.31 k
    
    total                    454.31 k

**Comment by llamatester** [comment]
The adapter at projects/talos exports TVL: 
        
 
 
    arbitrum-staking          5.04 k
    staking                   5.04 k
    arbitrum                  0
    
    total                    0

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
@0xLightt thanks for the PR,  I refactored it a bit.

  - Merged maia staking v2 into maia
  - all uni nfts in talos end up in hermes v2? sorry, this sounds like doublecounting, we cant track talos

**Comment by 0xLightt** [comment]
Thank you!

Yes, they end up in Hermes-v2. No worries! 

Hermes V2 also ends up in Uniswap V3. There is also TVL in Ulysses that is staked in Hermes (that is not being accounted atm). It would be nice to have the full value of all staked NFTs. Is there any way to add the cross-chain token's value without doublecounting?

**Comment by g1nt0ki** [comment]
yeah, this is the problem, if we count ulysses part of tvl in hermes, it would be doublecounting

**Comment by llamatester** [comment]
The adapter at projects/maia-dao exports TVL: 
        
 
 
    metis                     1.55 M
    
    total                    1.55 M

**Comment by llamatester** [comment]
The adapter at projects/hermes-v2 exports TVL: 
        
 
 
    arbitrum-staking          3.99 M
    staking                   3.99 M
    arbitrum                  459.19 k
    
    total                    459.19 k

**Review by g1nt0ki — APPROVED** [review]

**Pull request merged**
