### PR TITLE
Added the Banx project to the TVL

### PR DESCRIPTION
**Pull request by vedamire**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by vedamire** [comment]
> Error while running adapter at projects/banx:
> 
> ```
> Error: 410 Gone:  {"jsonrpc":"2.0","error":{"code": 410, "message":"The RPC call or parameters have been disabled."}, "id": "67c105fd-3867-41d0-808f-e4849a76b0f3" } 
> 
> Truncated error stack:
>     at ClientBrowser.callServer (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@solana/web3.js/lib/index.cjs.js:6474:18)
> ```

Yeah, I noticed that too when I tried doing calls using the public rpc. Looks like it's too limited on Solana.

Can you please try to make the test putting this RPC TO .env ```SOLANA_RPC```? https://mainnet.helius-rpc.com/?api-key=edc01bc7-f50a-4750-bb57-0faab1c50800

If you need, I can just hardcode this rpc for my adapter

**Comment by llamatester** [comment]
The adapter at projects/banx exports TVL: 
        
 
 
    solana                    1.09 M
    
    total                    1.09 M

**Comment by vedamire** [comment]
> Error while running adapter at projects/banx:
> 
> ```
> Error: 410 Gone:  {"jsonrpc":"2.0","error":{"code": 410, "message":"The RPC call or parameters have been disabled."}, "id": "67c105fd-3867-41d0-808f-e4849a76b0f3" } 
> 
> Truncated error stack:
>     at ClientBrowser.callServer (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@solana/web3.js/lib/index.cjs.js:6474:18)
> ```

I've just put our dedicated RPC and it works, could you please check again?

**Comment by vedamire** [comment]
> The adapter at projects/banx exports TVL:
> 
> ```
> solana                    1.09 M
> 
> total                    1.09 M 
> ```

Yes, it returns the TVL. Is it supposed to return anything else?

**Comment by Timikcool** [comment]
> @vedamire thanks for the PR. I didnt have running locally as we have our own custom rpc. Was worried that someone will abuse your api, so reverted back to free solana one.
> 
> We always show borrewed separate from tvl for lending protocols. but think it is about time to track solana bluechip nft prices, do you have recommendation how to pull this info from on chain/opensoure apis? Ideally two (or more) is better, so we are fine if one stops working

Tensor API + Magic Eden API

can connect you with both teams

**Comment by g1nt0ki** [comment]
> > @vedamire thanks for the PR. I didnt have running locally as we have our own custom rpc. Was worried that someone will abuse your api, so reverted back to free solana one.
> > We always show borrewed separate from tvl for lending protocols. but think it is about time to track solana bluechip nft prices, do you have recommendation how to pull this info from on chain/opensoure apis? Ideally two (or more) is better, so we are fine if one stops working
> 
> Tensor API + Magic Eden API
> 
> can connect you with both teams

hi @Timikcool sorry, for the late reply, are you in our discord?

**Pull request merged**
