### PR TITLE
Added Racoon.Bet project

### PR DESCRIPTION
**Pull request by racoon-supply-rac**
##### Name (to be shown on DefiLlama):
Racoon.Bet

##### Twitter Link:
https://twitter.com/RacoonSupply

##### List of audit links if any:
None

##### Website Link:
https://www.racoon.bet/

##### Current TVL:
1.6k - This is our game reserves only. We will add volume soon. Total played so far is 2.5M USD

##### Treasury Addresses (if the protocol has treasury)
The TVL are the treasuries:
juno: { tvl: () => tvl("juno", "juno1puyjxrxkkwc9ms63a297vx2aln4kqsaeegnclknt99py59elandses9f3j") },
migaloo: { tvl: () => tvl("migaloo", "migaloo1q6vmqprwvay5p3l0d763v50ufunt7fwfnfwp85wne5xan4meeqpsdvzyvy") },
chihuahua: { tvl: () => tvl("chihuahua", "chihuahua18s2dazpmva4t38rtnrlj3gjpsntmcdrk6v9220kt4yxckhqus3vssqsrgp") },

##### Chain:
Migaloo
Juno Network
Chihuahua Chain

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): 
None

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): 
None

##### Short Description (to be shown on DefiLlama):
Racoon.Bet is a fully on-chain gaming platform governed by the Racoon NFTs DAO. It currently operates on 3 different blockchain within the Cosmos Ecosystem.

##### Token address and ticker if any:
Not listed

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Gaming

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
None

##### forkedFrom (Does your project originate from another project):
None

##### methodology (what is being counted as tvl, how is tvl being calculated):
On-chain game reserves

##### Github org/user (Optional, if your code is open source, we can track activity):
racoon-supply-rac

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/racoon-bet exports TVL: 
        
 
 
    chihuahua                 455.43214537
    migaloo                   682.1221555
    juno                      429.23440800000003
    
    total                    1.57 k

**Comment by llamatester** [comment]
The adapter at projects/racoon-bet exports TVL: 
        
 
 
    juno                      427.962749711904
    migaloo                   681.2801654886651
    chihuahua                 455.4321377677916
    
    total                    1.56 k

**Comment by g1nt0ki** [comment]
hi @racoon-supply-rac I reverted the merge here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/7285 it was a mistake.

project treasury is different metric, it is not user deposits in these addresses right? (like can users withdraw these tokens?)

**Comment by racoon-supply-rac** [comment]
hey @g1nt0ki

You're right, this is the project's treasury! Is there an easy way to display project treasury and users volume instead of TVL?

Thanks!

**Comment by g1nt0ki** [comment]
hi @racoon-supply-rac we can thse values under treasury, check our for your listing in few hours :)

**Pull request merged**
