### PR TITLE
Listing: Keom Protocol

### PR DESCRIPTION
**Pull request by daedlock**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Keom Protocol

##### Twitter Link:
https://twitter.com/keomProtocol

##### List of audit links if any:
- https://assets.website-files.com/622a09bc809cd190f58b7b15/627cd4450f5eb2df769b4ac1_PeckShield-Audit-Report-0VIX-v1.0.pdf
- https://assets.website-files.com/622a09bc809cd190f58b7b15/627a5d6eea14146296b3261b_0VIX_Audit_Report_by_WatchPug.pdf
- https://assets.website-files.com/622a09bc809cd190f58b7b15/631729e5bf942d7d0b47e5d2_omniscia-0vix-compressed.pdf
- [PeckShield-Audit-Report-0VIX-ERC4626Wrappers-v1.0.pdf](https://github.com/DefiLlama/DefiLlama-Adapters/files/12513064/PeckShield-Audit-Report-0VIX-ERC4626Wrappers-v1.0.pdf)

##### Website Link:
https://keom.io

##### Logo (High resolution, will be shown with rounded borders):
image

##### Chain:
- PolygonPoS
- Polygon zkEVM

##### Short Description (to be shown on DefiLlama):
Keom is an innovative DeFi platform powered by cutting-edge AI technology and hard-coded compliance measures. It offers a suite of intelligent trading products, setting new standards for risk assessment, prioritizing regulatory compliance, and providing unique features like the Dynamic Interest Rate Curve and real-time liquidity risk measurement. With a community-led approach and AI-assisted trading, Keom simplifies complex data for traders while ensuring a secure and rewarding DeFi experience.

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
- Chainlink
- Pyth

##### forkedFrom (Does your project originate from another project):
- Compound V2

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/keom exports TVL: 
        
 
 
    polygon                   942.12 k
    polygon_zkevm             470.78 k
    polygon_zkevm-borrowed    157.75 k
    borrowed                  157.75 k
    
    total                    1.41 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
care to explain why you copied 0vix contract details?

**Comment by Define101** [comment]
We will close this PR and make the necessary changes to 0vix listing ( the rebrand)

**Comment by daedlock** [comment]
> We will close this PR and make the necessary changes to 0vix listing ( the rebrand)

@0xngmi can you attend this? I guess we either want to keep it as 2 separate listings as discussed OR update 0vix and remove the hallmark as this will interfere with the branding strategy.

**Comment by Define101** [comment]
> > We will close this PR and make the necessary changes to 0vix listing ( the rebrand)
> 
> @0xngmi can you attend this? I guess we either want to keep it as 2 separate listings as discussed OR update 0vix and remove the hallmark as this will interfere with the branding strategy.

https://defillama.com/protocol/keom-protocol
What is wrong? "Because the contracts are not changed. Keom is a rebrand of 0VIX"

**Comment by daedlock** [comment]
> > > We will close this PR and make the necessary changes to 0vix listing ( the rebrand)
> > 
> > 
> > @0xngmi can you attend this? I guess we either want to keep it as 2 separate listings as discussed OR update 0vix and remove the hallmark as this will interfere with the branding strategy.
> 
> https://defillama.com/protocol/keom-protocol What is wrong? "Because the contracts are not changed. Keom is a rebrand of 0VIX"

The hallmark showing the protocol was hacked. This has to be either removed or if that's not possible, we are fine with having a new listing for keom and leaving 0vix as a legacy listing

**Comment by g1nt0ki** [comment]
> > > > We will close this PR and make the necessary changes to 0vix listing ( the rebrand)
> > > 
> > > 
> > > @0xngmi can you attend this? I guess we either want to keep it as 2 separate listings as discussed OR update 0vix and remove the hallmark as this will interfere with the branding strategy.
> > 
> > 
> > https://defillama.com/protocol/keom-protocol What is wrong? "Because the contracts are not changed. Keom is a rebrand of 0VIX"
> 
> The hallmark showing the protocol was hacked. This has to be either removed or if that's not possible, we are fine with having a new listing for keom and leaving 0vix as a legacy listing
> 
> **EDIT: listing keom like that is hurting the rebrand and I am asking you to kindly revert this listing ASAP. @0xngmi advised that we have 2 separate listings**
> 
> @Define101

hi @daedlock if you have a new project/product, we can create a new listing for it, but this is existing project and the hallmark indicates what happened, so we cant remove it

**Comment by daedlock** [comment]
> > > > > We will close this PR and make the necessary changes to 0vix listing ( the rebrand)
> > > > 
> > > > 
> > > > @0xngmi can you attend this? I guess we either want to keep it as 2 separate listings as discussed OR update 0vix and remove the hallmark as this will interfere with the branding strategy.
> > > 
> > > 
> > > https://defillama.com/protocol/keom-protocol What is wrong? "Because the contracts are not changed. Keom is a rebrand of 0VIX"
> > 
> > 
> > The hallmark showing the protocol was hacked. This has to be either removed or if that's not possible, we are fine with having a new listing for keom and leaving 0vix as a legacy listing
> > **EDIT: listing keom like that is hurting the rebrand and I am asking you to kindly revert this listing ASAP. @0xngmi advised that we have 2 separate listings**
> > @Define101
> 
> hi @daedlock if you have a new project/product, we can create a new listing for it, but this is existing project and the hallmark indicates what happened, so we cant remove it

I understand. Can we have Keom listed separately from 0vix then? Thanks

**Comment by g1nt0ki** [comment]
We close this PR for now, you put up a new PR with new contract for keom? and we leave legacy listing as it is under the anme of 0VIX?

**Comment by daedlock** [comment]
> We close this PR for now, you put up a new PR with new contract for keom? and we leave legacy listing as it is under the anme of 0VIX?

Keom will have the same contract addresses as 0VIX for Lending. For margin trading and other features there will be new contracts.

For now, can you revert this listing to 0VIX and have a separate listing for Keom without the "Hacked" hallmark?

**Comment by g1nt0ki** [comment]
No, we cant do that. We cant count the same tvl for two different listings

**Comment by 0xngmi** [comment]
Fundamentally the issue is that they're the same contracts, so we can have 2 listings for the same thing

**Pull request closed without merging**
