### PR TITLE
Added Gaj Finance

### PR DESCRIPTION
**Pull request by Gajesh2007**
##### Twitter Link:
https://twitter.com/GajFinance

##### List of audit links if any:
https://solidity.finance/audits/Gaj-NFT-Farming/

##### Website Link:
https://gaj.finance

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://raw.githubusercontent.com/PolyGaj/assets/main/logo200x200.png

##### Chain:
Polygon

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
gaj

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
gaj-finance

##### Description/bio (to be shown on DefiLlama):
Gaj, previously known as PolyGaj, is a multichain platform covering the two most promising subsects of cryptocurrency namely DeFi and NFT. With a vision to be a one-stop solution for users who want to experience both DeFi and NFT and with humble beginnings, Gaj picked up steam due to its unique offerings, especially focused on users who now had a variety of options to earn 

The team behind Gaj wanted the platform to be robust and quick so that the user experience could be enriched and hence the natively picked up Polygon protocol to built its platform as the protocol promised low transaction fees, extremely fast transactions, staking reward offerings, and enough headroom to scale. 
With the rise in demand for Gaj and with a mission to expand its users base. Gaj slowly decided to expand to a multichain level, a giant step of the Gaj in the true sense. With the first bridge deployed already, Gaj opened its door to the Binance Smart Chain users with many more bridges to come. 

To be a one-stop solution, Gaj launched a variety of products at the intersection of DeFi and NFT. These products were designed in a manner that the user can experience the power of both DeFi and the potential of  NFT’s along with great opportunities to earn additional income by staking hodling, and bidding. The range of products that Gaj is providing are all powered by its native token - $GAJ 

##### Token address and ticker if any:
0xf4b0903774532aee5ee567c02aab681a81539e92
GAJ

##### Category (Yield/Dexes/Lending/Minting):
Yield

### CODE REVIEW

**Comment by 0xngmi** [comment]
Are the GAJ tokens on these two contracts tokens that have been staked there and are earning rewards or tokens that are being used as rewards for the other tokens that are staked there?

**Comment by Gajesh2007** [comment]
In MasterChef, They were earning GAJ but we stopped the farms few days back
In NFT Farming Contact, They earn NFTs

**Comment by iamjustaspore** [comment]
@0xngmi To clarify, these are GAJ tokens staked by users, so they are Gaj Finance's TVL.  Feedback is welcome.

**Comment by Gajesh2007** [comment]
@0xngmi removed masterchef. Added other things.

**Pull request merged**
