### PR TITLE
add astarfarm tvl

### PR DESCRIPTION
**Pull request by lilpacy**
##### Twitter Link:
https://twitter.com/AstarFarm

##### List of audit links if any:
N/A

##### Website Link:
https://astarfarm.com/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
astarfarm_profile

##### Current TVL:
17.19k

##### Chain:
Astar

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

##### Short Description (to be shown on DefiLlama):
Astar Farm is a defi & gamefi Dapps works on Astar network.

##### Token address and ticker if any:
0x992bad137Fc8a50a486B5C6375f581964b4A15FC

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Gaming

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
N/A

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
Users' locked ASTR to our dapp contract.
When users farm their ASTR as seeds, their ASTR is locked to our dapp contract.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/astarfarm exports TVL: 
        
 
 
    astar                     18.71 k
    
    total                    18.71 k

**Comment by lilpacy** [comment]
I apologize for our late development. Finally, we finished making our contract upgradeable. So our contract address has been fixed.

**Comment by Define101** [comment]
Do you guys have a token? What is the symbol?
Or you guys only use ASTR token? (token from astar network)
We only need the token address and their symbol

**Comment by lilpacy** [comment]
> Do you guys have a token? What is the symbol? Or you guys only use ASTR token? (token from astar network) We only need the token address and their symbol

Oh, sorry we don't have any token. We only use ASTR native token.  
I just deleted "Token address and ticker".

**Pull request merged**
