### PR TITLE
new strategy zkSync era tvl

### PR DESCRIPTION
**Pull request by brddmnk**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/parallax: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by llamatester** [comment]
The adapter at projects/parallax exports TVL: 
        
 
 
    ethereum                  111.31 k
    arbitrum-staking          16.18 k
    era                       5.42 k
    arbitrum-pool2            27.44 k
    arbitrum                  69.71 k
    staking                   16.18 k
    pool2                     27.44 k
    
    total                    186.44 k

**Comment by llamatester** [comment]
The adapter at projects/parallax exports TVL: 
        
 
 
    arbitrum-staking          16.18 k
    ethereum                  111.31 k
    arbitrum-pool2            27.44 k
    era                       5.42 k
    arbitrum                  69.71 k
    staking                   16.18 k
    pool2                     27.44 k
    
    total                    186.44 k

**Comment by g1nt0ki** [comment]
thanks for the PR, I have included your changes here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/4ac7f0ff347d6839555c25a6cb51f9280543a262

**Pull request closed without merging**
