### PR TITLE
update tvl for NBC alpha

### PR DESCRIPTION
**Pull request by elykct**
Hi team,

Please help to review our update of TVL.
Thank you in advance.

---
NBC team.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/newbitcoin: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:206:11

**Comment by llamatester** [comment]
Error while running adapter at projects/newbitcoin: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:206:11

**Comment by g1nt0ki** [comment]
hi, it is better to list the dex a new listing, can you provide project details? like website of the dex

**Comment by llamatester** [comment]
The adapter at projects/newbitcoincity-dex exports TVL: 
        
 
 
    nos                       440.02 k
    
    total                    440.02 k

**Comment by llamatester** [comment]
The adapter at projects/newbitcoincity-dex exports TVL: 
        
 
 
    nos                       440.31 k
    
    total                    440.31 k

**Comment by g1nt0ki** [comment]
merged here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/8106

**Pull request closed without merging**
