### PR TITLE
compound v1 fix

### PR DESCRIPTION
**Pull request by 0xngmi**
@g1nt0ki could you help me review this one? i was refilling compound data and noticed some weird stuff going on with compound adapter

fixed it here but im not sure if i'm missing anything. also the cache bit that we do with that markets array seems sus and i don't now if it's actually needed (not entirely sure how the two wbtc tokens work, the legacy one and the current one)

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/compound-onchain exports TVL: 
        
 
 
    ethereum                  2.64 B
    ethereum-borrowed         943.80 M
    borrowed                  943.80 M
    
    total                    2.64 B

**Comment by llamatester** [comment]
The adapter at projects/compound-onchain exports TVL: 
        
 
 
    ethereum                  2.26 B
    ethereum-borrowed         927.85 M
    borrowed                  927.85 M
    
    total                    2.26 B

**Comment by g1nt0ki** [comment]
> The adapter at projects/compound-onchain exports TVL:
> 
> ```
> ethereum                  2.64 B
> ethereum-borrowed         943.80 M
> borrowed                  943.80 M
> 
> total                    2.64 B 
> ```

it looks good, I was bit concerned that it was showing 2.64B instead of 2.26B maybe someone did pull 300M between then and now.

**Comment by g1nt0ki** [comment]
I see that cache is used only when we are below certain block, but not sure if it will hold up, unless all those markets are created at same time, some calls will fail and adapter will break, but leaving it as it is, we can fix fix if/when we need to refill before that block

**Pull request merged**
