### PR TITLE
Add Q Infinity Adapter

### PR DESCRIPTION
**Pull request by KyrylR**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Logo (High resolution, will be shown with rounded borders):

https://gold-managing-prawn-9.mypinata.cloud/ipfs/QmNMs2519B3nZizuQuJtJSNnX2Eigte3aDyusjavhdShLc

##### Short Description (to be shown on DefiLlama): 

Q Infinity campaign incentivizes bridging and locking WETH, USDC, and ELK tokens on the Q mainnet to earn points redeemable for QGOV token rewards. Users can earn additional points as well by engaging with Q protocol twitter.

##### Category (full list at https://defillama.com/categories) *Please choose only one: 

[Launchpad](https://defillama.com/protocols/Launchpad)

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):

To track the USD equivalent value of the underlying assets, the Q DeFi Risk Expert panel selects a set of trusted oracles. This approach is inspired by the original MakerDAO oracle approach. The Expert Panel consists of multiple members from multiple organizations.

##### Implementation Details: Briefly describe how the oracle is integrated into your project:

The current version is a basic price feed oracle, as given in https://gitlab.com/q-dev/system-contracts/-/blob/master/contracts/defi/oracles/FxPriceFeed.sol . There are plans to change this to medianizer approach based oracles in the future, e.g. see here: https://gitlab.com/q-dev/system-contracts/-/blob/master/contracts/defi/oracles/FxPriceFeedMedianizer.sol?ref_type=heads

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:

https://q-dev.gitlab.io/system-contracts/mainnet/#/contracts/defi/oracles/FxPriceFeed

##### methodology (what is being counted as tvl, how is tvl being calculated):

TVL counts the USD value of WETH, USDC, and ELK tokens that have been bridged from Ethereum to the Q mainnet using 
either the Omnibridge or ELKnet bridge and then locked in the Q Infinity campaign contracts.

The minimum amounts to be counted are:
* 0.1 WETH
* 300 USDC
* 2500 ELK

TVL is calculated by summing the USD value of all locked WETH, USDC and ELK balances, using price feeds for each asset.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/q-infinity exports TVL: 
        
 
 
    q                         0
    
    total                    0

**Comment by KyrylR** [comment]
As for the bridge, perhaps this could be useful: https://github.com/DefiLlama/DefiLlama-Adapters/pull/9193

**Comment by g1nt0ki** [comment]
is this project live?

**Comment by KyrylR** [comment]
@g1nt0ki It will be live in a week

**Comment by g1nt0ki** [comment]
sorry, we dont list protocols that are not yet live, can you reopen the PR once it is live?

**Comment by KyrylR** [comment]
Sure

**Pull request closed without merging**
