### PR TITLE
Jewelswap update

### PR DESCRIPTION
**Pull request by combased-dev**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Logo (High resolution, will be shown with rounded borders):
https://drive.google.com/file/d/1u7M20OVys2t9mufdoisnxWkSEiy7nmJw/view?usp=sharing

##### Short Description (to be shown on DefiLlama): 
First Peer-to-pool NFT Lending Protocol, AMM marketplace, Leveraged Yield Farming, Liquid Staking on MultiversX.

##### methodology (what is being counted as tvl, how is tvl being calculated): 
TVL consists of 5 modules and uses both on-chain and off-chain data (due to NFTs). The modules are the following: 
Staking EGLD -  Liquid Staking
Staking ASH - Yield (converts ASH into EGLD)
Lending (NFT) and Farms - Lending (uses NFT prices and loans backed by EGLD)
Ashswap Farms - Leveraged Farming (calculates LP value)
Onedex Farms - Farm (calculates LP value)

All TVL is calculated in EGLD and then converted into USD using the latest EGLD price from Xexchange. We can't use **only on-chain data** due to the unavailability of an oracle in MultiversX. Once oracle is live, we'll transition to on-chain data.

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/jewelswap-lev-farming exports TVL: 
        
 
 
    elrond                    282.90 k
    
    total                    282.90 k

**Comment by llamatester** [comment]
The adapter at projects/jewelswap-nft exports TVL: 
        
 
 
    elrond                    393.19 k
    
    total                    393.19 k

**Comment by llamatester** [comment]
The adapter at projects/jewelswap-lev-farming exports TVL: 
        
 
 
    elrond                    282.67 k
    
    total                    282.67 k

**Comment by llamatester** [comment]
The adapter at projects/jewelswap-nft exports TVL: 
        
 
 
    elrond                    392.88 k
    
    total                    392.88 k

**Comment by g1nt0ki** [comment]
closing in favor of https://github.com/DefiLlama/DefiLlama-Adapters/pull/6887

**Comment by llamatester** [comment]
The adapter at projects/jewelswap-lev-farming exports TVL: 
        
 
 
    elrond                    258.95 k
    
    total                    258.95 k

**Comment by llamatester** [comment]
Error while running adapter at projects/jewelswap-nft: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'total_lending_amount')
    Truncated error stack:
    
        at getNftsTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/jewelswap-nft/index.js:93:68)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)
        at async Promise.all (index 2)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by llamatester** [comment]
The adapter at projects/jewelswap-lev-farming exports TVL: 
        
 
 
    elrond                    275.47 k
    
    total                    275.47 k

**Comment by llamatester** [comment]
The adapter at projects/jewelswap-lev-farming exports TVL: 
        
 
 
    elrond                    275.59 k
    
    total                    275.59 k

**Comment by llamatester** [comment]
The adapter at projects/jewelswap-nft exports TVL: 
        
 
 
    elrond                    374.34 k
    
    total                    374.34 k

**Comment by llamatester** [comment]
The adapter at projects/jewelswap-lev-farming exports TVL: 
        
 
 
    elrond                    275.59 k
    
    total                    275.59 k

**Comment by llamatester** [comment]
The adapter at projects/jewelswap-nft exports TVL: 
        
 
 
    elrond                    374.41 k
    
    total                    374.41 k

**Comment by combased-dev** [comment]
@g1nt0ki why does lint fails? Don't get it...

**Comment by g1nt0ki** [comment]
will check it soon

**Comment by combased-dev** [comment]
@g1nt0ki perfect, I hope it will be approved today 👌

**Comment by llamatester** [comment]
Error while running adapter at projects/jewelswap-lev-farming: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by g1nt0ki** [comment]
@combased-dev it will be listed soon, only major change that I made was not include nfts as collateral in tvl

**Comment by combased-dev** [comment]
@g1nt0ki thanks! So we will be getting leveraged yield farming and also nft lending? 

Can I add the merged project now - with those 2 + our liquid staking modules? :) Then it will be truly great 👌

**Comment by g1nt0ki** [comment]
does this liquid staking adapter look right? https://github.com/DefiLlama/DefiLlama-Adapters/commit/0ce0d3c39b0a8a6e0923446e91374e0760d29d59

**Comment by g1nt0ki** [comment]
tvl is 3924 EGLD, counting JWLEGLD supply as tvl

**Comment by combased-dev** [comment]
@g1nt0ki Oh nice 👍 We do have ASH staking as well, ideally it should be used with JWLEGLD in the same module. Here https://app.jewelswap.io/stake/ASH

**Comment by combased-dev** [comment]
Also @g1nt0ki thanks for the twitter announcement, but this one is a bit incorrect 😅


https://twitter.com/defillama/status/1683933951176630272?s=46&t=rhAbIBFYswjdG0ycz3OhyA

It should be named NFTs Lending

NFTs are used as collateral for borrowing EGLD. Bulk loans, bulk repay/redeem supported. Mortgage support included as well. 14+ top NFT collections in MultiversX

**Comment by combased-dev** [comment]
@g1nt0ki perfect! Talked with a team, it would be great to **separate** ASH staking from EGLD 🙏 Here are the categories, which would represent all our modules correctly:

Currently nft marketplace should be category NFT Lending.
Ash staking should be category Yield.
egld liquid staking should be category Liquid Staking.
Lending pool should be category Lending (**not yet pushed, I will push ASAP**).

**Comment by combased-dev** [comment]
@g1nt0ki updated. No need to separate, we can put ASH and EGLD under same - liquid staking.

**Comment by g1nt0ki** [comment]
@combased-dev lending pool tvl is already included in leveraged farming tvl

**Comment by combased-dev** [comment]
@g1nt0ki correct, but there is also not urilized tokens. We should include them as well. What do you suggest? Sum it on-chain? Here is lending SC

https://explorer.multiversx.com/accounts/erd1qqqqqqqqqqqqqpgq96n4gxvmw8nxgxud8nv8qmms5namspc5vmusg930sh

**Comment by g1nt0ki** [comment]
@combased-dev we are already reading the balances here, right? https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/jewelswap-lev-farming/index.js#L55

**Pull request merged**
