### PR TITLE
Add cetable psm to tvl

### PR DESCRIPTION
**Pull request by danhsucowboy**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
### Description
Hi, we want to add cetable psm to our tvl, which cetable is a tokenized lp pair combined with USDC and USDT

Also, we already listed our stablecoin [BUCK](https://defillama.com/stablecoin/bucket-protocol-buck-stablecoin) to DeFiLlama. But it doesn't connect with our protocol page.

Is there anything we could do to show the stablecoin information on the bucket-protocol page?

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bucket-protocol exports TVL: 
        
 
 
    sui                       9.98 M
    
    total                    9.98 M

**Comment by g1nt0ki** [comment]
looks good, thanks for the PR

**Comment by Define101** [comment]
"Is there anything we could do to show the stablecoin information on the bucket-protocol page?"
Should be good within 2 hours

**Comment by danhsucowboy** [comment]
> "Is there anything we could do to show the stablecoin information on the bucket-protocol page?" Should be good within 2 hours

Hi @Define101, thanks a lot.

But it seems to have some issues on the [page](https://defillama.com/protocol/bucket-protocol)

image

**Comment by Define101** [comment]
Hello. Thanks for the report. Will look into in a bit

**Comment by Define101** [comment]
Should be good within 2 hours

**Pull request merged**
