### PR TITLE
Add 0xAcid

### PR DESCRIPTION
**Pull request by IoJupiterI**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
0xAcid

##### Twitter Link:
https://twitter.com/0xAcidDAO

##### Website Link:
https://0xacid.com/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://0xacid.com/acid_200_200.png

##### Current TVL:
6.4M

##### Treasury Addresses (if the protocol has treasury)
0x5f41fff9d70c734eb012f1a0a322980c1863aba4 (Arbitrum and Ethereum)

##### Chain:
Arbitrum

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
acid

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
23890

##### Short Description (to be shown on DefiLlama):
Unleash the true power of LSD
Bringing maximum LSD yield profits to Acid holders with our innovative revenue models.

##### Token address and ticker if any:
0x29C1EA5ED7af53094b1a79eF60d20641987c867e

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Liquid Staking

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
None

##### forkedFrom (Does your project originate from another project):
None

##### methodology (what is being counted as tvl, how is tvl being calculated):
ACID staked in the staking contract

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/0xacid: 
        
 
  
    
    
    Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0x29C1EA5ED7af53094b1a79eF60d20641987c867e","data":"0x70a0823100000000000000000000000000a842038a674616f6a97e62f80111a536778282","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:654:52
        at Array.forEach (<anonymous>)

**Comment by llamatester** [comment]
The adapter at projects/0xacid exports TVL: 
        
 
 
    arbitrum                  0
    arbitrum-staking          0
    staking                   0
    
    total                    0

**Comment by IoJupiterI** [comment]
please help, why staking is zero

**Comment by Avedith** [comment]
@IoJupiterI It would be because your coin is not listed on CoinGecko, so it has no source to price the ACID token for TVL.

**Comment by IoJupiterI** [comment]
OK. Coingecko has listed us https://www.coingecko.com/en/coins/usd-coin

**Comment by g1nt0ki** [comment]
yeah, I think the issue would fix itself.

**Pull request merged**
