### PR TITLE
feat: include tokens loans collateral in the TVL for Rain

### PR DESCRIPTION
**Pull request by solwhitey**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

Hello, I made a PR yesterday to integrate/support Rain.fi, and it has been accepted, thank you! 

I updated my PR to count the collateral of a loan as TVL from our other program. 
We support both tokens and NFTs loan, although it's not really possible to have the value of the NFT as collateral, we can get it for tokens, so that's why I add it here :)

Thank you in advance!

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/rain: 
        
 
  
    
    
    TypeError: token.replace is not a function
    Truncated error stack:
        at ChainApi.add (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/ChainApi.js:123:23)
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/rain/index.js:14:9)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:53:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:149:9
        at async Promise.all (index 0)
        at async Promise.all (index 0)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:194:3

**Comment by g1nt0ki** [comment]
@solwhitey thanks, I have fixed the bug here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/8341

**Comment by g1nt0ki** [comment]
@solwhitey will try to add pricing support for sol NFTs soon  :crossed_fingers:

**Comment by g1nt0ki** [comment]
can you share some documentation for the oracle, I will try to read up, also check what else is in the market and try to price at least the bluechip NFTs

**Pull request closed without merging**
