### PR TITLE
xBacked adapter

### PR DESCRIPTION
**Pull request by JCastrejonE**
**NOTE**

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.

**Discord chat copy explaining why a fetch adapter is needed in this particular case**
Captura de Pantalla 2023-01-09 a la(s) 15 15 18
Captura de Pantalla 2023-01-09 a la(s) 15 16 18

SDK URL: https://github.com/xBacked-DAO/xbacked-sdk

2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
xBacked

##### Twitter Link:
https://twitter.com/xbacked

##### List of audit links if any:
https://github.com/xBacked-DAO/xbacked-audits

##### Website Link:
https://www.xbacked.io/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://github.com/xBacked-DAO/press-kit-assets/
https://raw.githubusercontent.com/xBacked-DAO/press-kit-assets/main/Icons/gov-token.png

##### Current TVL:
0

##### Chain:
Algorand

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

##### Short Description (to be shown on DefiLlama):
The xUSD stablecoin is a decentralized, over-collateralized cryptocurrency pegged to the US Dollar. xUSD is supported on the Algorand blockchain.

##### Token address and ticker if any:
Ticker: xUSD
Address: 760037151 (https://algoexplorer.io/asset/760037151)

##### Category (full list at https://defillama.com/categories) *Please choose only one:
CDP

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Custom oracle aggregating from CEXs. Code is available at https://github.com/xBacked-DAO/xbacked-temp-oracle

##### forkedFrom (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is the sum of all collateral deposited into CDPs of the xBacked protocol.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/xbacked: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:203:11

**Comment by llamatester** [comment]
Error while running adapter at projects/xbacked: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:203:11

**Comment by llamatester** [comment]
Error while running adapter at projects/xbacked: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:203:11

**Comment by llamatester** [comment]
Error while running adapter at projects/xbacked: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:203:11

**Comment by g1nt0ki** [comment]
Hi, looks good but I am going to leave it open till it has some tvl, can you update code to this?

    const { get } = require('../helper/http');

    module.exports = {
      timetravel: false,
      misrepresentedTokens: true,
      methodology: "Sums the total locked collateral value in usd across all vaults.",
      algorand: {
        tvl: async () => {
          return { tether: await get('http://mainnet.collector.xbacked.io:4001/api/v1/getTVL') };
        }
      },
    }
    
 Also, can you post a message here when you have tvl, I will merge it

**Comment by llamatester** [comment]
The adapter at projects/xbacked exports TVL: 
        
 
 
    algorand                  0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/xbacked exports TVL: 
        
 
 
    algorand                  758
    
    total                    758

**Comment by JCastrejonE** [comment]
> Also, can you post a message here when you have tvl, I will merge it

@g1nt0ki We now have TVL. Thanks!

**Pull request merged**
