### PR TITLE
add staking tlv for hxro network

### PR DESCRIPTION
**Pull request by kchaliki**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
HXRO Network

##### Twitter Link:
https://twitter.com/HxroNetwork

##### List of audit links if any:
https://docs.hxro.network/hxro-token/staking-and-governance/15-9-2022-audit

##### Website Link:
https://hxro.com/

##### Current TVL:
$7.2M

##### Chain:
Solana (token also on Ethereum)

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
hxro

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
hxro

##### Short Description (to be shown on DefiLlama):
An open primitive powering on-chain derivatives for market-based applications

##### Token address and ticker if any:
0x4bd70556ae3f8a6ec6c4080a0c327b24325438f3
HXRO

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Derivatives

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Pyth, Jiritsu, Switchboard

##### methodology (what is being counted as tvl, how is tvl being calculated):
USD value of staked HXRO tokens

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/hxro-network exports TVL: 
        
 
 
    solana                    6.73 M
    
    total                    6.73 M

**Comment by g1nt0ki** [comment]
@kchaliki is this the staking tokenAccount? https://solscan.io/account/6vykmaEg9HNQnJ1Uw9hfNBwfDLFEdK4CovhLa7som1QW

Also, we count staking under 'staking' field rather than tvl: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by kchaliki** [comment]
Hi @g1nt0ki - thanks for looking at my PR! No there are 3 token accounts, they all hold different "kinds" of HXRO:

6kU9EA8ApkD3eCYjoR3e8MkJzvjcVb8nTFUQhGKMjA7r holds normal HXRO as staked by standard token holders

5vvUbUk6CUinwRV8YT2GDhf4byfA8dsvU3MWZJT9nxvY holds LHXRO, this represents HXRO that is locked by our staking contracts until a fixed deadline and is what strategic investors in the project receive

DB8v2eyqQXueoSLYNFoxoBv1DFr7XuhMLtwPUEcrM5KP holds esHXRO, this represents HXRO that is escrowed by our staking contracts and is what is received by stakers as a result of fees, rewards, incentives etc. This can be restaked (which is what this account holds) or converted to HXRO at 1/365 per day

LHXRO & esHXRO is of course backed 1:1 with HXRO.

Our API returns the sum of the 3 so was the easiest to use. I have made the change to label staking size correctly per some other projects

**Comment by llamatester** [comment]
The adapter at projects/hxro-network exports TVL: 
        
 
 
    solana                    0
    solana-staking            7.24 M
    staking                   7.24 M
    
    total                    0

**Comment by g1nt0ki** [comment]
@kchaliki thanks for breaking it down. LHXRO feels bit like vesting, think it needs to be excluded. can you update code to below? I prefer on chain calls (easier to maintain)


    const { sumTokens2 } = require('../helper/solana')
    const sdk = require('@defillama/sdk')

    async function staking() {
      const esHRXOKey = 'solana:CPwspzHc4bKtBQGNRhpRG9v3qRiPLWP28GrfZepwmBSz'
      const balances = await sumTokens2({
        tokenAccounts: [
          '6kU9EA8ApkD3eCYjoR3e8MkJzvjcVb8nTFUQhGKMjA7r',
          'DB8v2eyqQXueoSLYNFoxoBv1DFr7XuhMLtwPUEcrM5KP',
        ]
      })

      if (balances[esHRXOKey]) sdk.util.sumSingleBalance(balances, 'HxhWkVpk5NS4Ltg5nij2G671CKXFRKPK8vy271Ub4uEK', balances[esHRXOKey], 'solana')
      delete balances[esHRXOKey]
      return balances
    }

    module.exports = {
      solana: {
        tvl: () => 0, staking,
      }
    }

**Comment by kchaliki** [comment]
For sure @kchaliki - done, thanks

**Comment by llamatester** [comment]
Error while running adapter at projects/hxro-network: 
        
 
  
    
    
    TypeError: data.data.forEach is not a function
    Truncated error stack:
    
        at getTokenAccountBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:134:15)
        at async sumTokens2 (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:345:27)
        at async staking (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/hxro-network/index.js:6:20)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:51:25)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:146:9
        at async Promise.all (index 1)
        at async Promise.all (index 0)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:191:3

**Comment by kchaliki** [comment]
> Error while running adapter at projects/hxro-network:
> 
> ```
> TypeError: data.data.forEach is not a function
> Truncated error stack:
> 
>     at getTokenAccountBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:134:15)
>     at async sumTokens2 (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:345:27)
>     at async staking (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/hxro-network/index.js:6:20)
>     at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:51:25)
>     at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:146:9
>     at async Promise.all (index 1)
>     at async Promise.all (index 0)
>     at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:191:3
> ```

hm looking into this

**Comment by kchaliki** [comment]
@g1nt0ki is this some kind of Solana RPC throttling?

**Comment by llamatester** [comment]
Error while running adapter at projects/hxro-network: 
        
 
  
    
    
    TypeError: data.data.forEach is not a function
    Truncated error stack:
    
        at getTokenAccountBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:134:15)
        at async sumTokens2 (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:345:27)
        at async staking (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/hxro-network/index.js:6:20)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:51:25)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:146:9
        at async Promise.all (index 1)
        at async Promise.all (index 0)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:191:3

**Comment by g1nt0ki** [comment]
thanks, yeah looks like rpc issue, we use a different on server-side

**Comment by g1nt0ki** [comment]
@Define101 can you take care of this?

**Pull request merged**
