### PR TITLE
Add OptionFlow Finance on Cardano

### PR DESCRIPTION
**Pull request by MuesliSwapTeam**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
OptionFlow

##### Twitter Link:
https://twitter.com/OptionFlowTeam

##### List of audit links if any:
https://twitter.com/OptionFlowTeam/status/1735371906432549344?s=20

##### Website Link:
https://optionflow.finance

##### Logo (High resolution, will be shown with rounded borders):
https://drive.google.com/file/d/1vl_7zonPt1oe1hAZiH7JrYEochMI-S6i/view?usp=sharing

##### Current TVL:
0 ADA (mainnet launch planned today)

##### Treasury Addresses (if the protocol has treasury)
None

##### Chain:
Cardano (ADA)

##### Short Description (to be shown on DefiLlama):
OptionFlow is a decentralized option writing and trading platform on the Cardano blockchain.

##### Token address and ticker if any:
[1ddcb9c9de95361565392c5bdff64767492d61a96166cb16094e54be.OPT](https://cardanoscan.io/token/1ddcb9c9de95361565392c5bdff64767492d61a96166cb16094e54be.4f5054) 
Ticker: OPT

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Options

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
None

##### forkedFrom (Does your project originate from another project):
None

##### methodology (what is being counted as tvl, how is tvl being calculated):
We calculate the tokens on resting orders on the order book contracts. TVL is equal to the liquidity in the option contract plus the resting orders in the order book

##### Github org/user (Optional, if your code is open source, we can track activity):
None

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/optionflow exports TVL: 
        
 
 
    cardano                   39.795624000000004
    
    total                    39.795624000000004

**Comment by g1nt0ki** [comment]
hi @MuesliSwapTeam 
Thanks for the PR, but can you refactor it a bit so it pulls data on chain, like if you provide the address/script where the tokens are kept, we can pull tokens and price them using our internal api

**Comment by MuesliSwapTeam** [comment]
Do you provide adapters for this for Cardano? If so, we can happily use them to provide an adapter. As it looks from the docs however, we could only find adapters to pull Ethereum data on chain. OptionFlow protocol is not on Ethereum, it is only on Cardano.

**Comment by g1nt0ki** [comment]
@MuesliSwapTeam we have rudimentary support for cardano: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/helper/chain/cardano.js#L98

**Comment by g1nt0ki** [comment]
also: https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/projects/helper/chain/cardano

**Pull request closed without merging**
