### PR TITLE
Add Compound v3 market for Base

### PR DESCRIPTION
**Pull request by kevincheng96**
Add tracking for the newly launched Compound v3 market on Base.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/compound-v3 exports TVL: 
        
 
 
    polygon-borrowed          18.21 M
    base-borrowed             1.23 M
    ethereum-borrowed         438.22 M
    arbitrum-borrowed         5.73 M
    base                      3.85 M
    ethereum                  826.80 M
    polygon                   38.76 M
    arbitrum                  19.36 M
    borrowed                  463.39 M
    
    total                    888.77 M

**Comment by g1nt0ki** [comment]
@kevincheng96 thanks

**Comment by llamatester** [comment]
The adapter at projects/compound-v3 exports TVL: 
        
 
 
    polygon-borrowed          18.21 M
    base-borrowed             1.23 M
    polygon                   38.76 M
    base                      3.85 M
    ethereum                  826.91 M
    arbitrum-borrowed         5.73 M
    ethereum-borrowed         438.37 M
    arbitrum                  19.36 M
    borrowed                  463.55 M
    
    total                    888.88 M

**Comment by llamatester** [comment]
The adapter at projects/lemuriafinance.js exports TVL: 
        
 
 
    milkomeda                 31.69 k
    
    total                    31.69 k

**Pull request merged**
