### PR TITLE
metalswap project added

### PR DESCRIPTION
**Pull request by MultiChainSoftware**
Added "metalswap" folder with index.js file for MetalSwap project listing.

**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

##### Token address and ticker if any: ticker XMT, addresses:
ETH: 0x3E5D9D8a63CC8a88748f229999CF59487e90721e
BNB: 0x582c12b30f85162fa393e5dbe2573f9f601f9d91
POLYGON: 0xadBe0eac80F955363f4Ff47B0f70189093908c04

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/metalswap exports TVL: 
        
 
 
    bsc                       3.79 M
    polygon                   4.09 M
    ethereum                  15.82 M
    
    total                    23.71 M

**Comment by g1nt0ki** [comment]
Hi @MultiChainSoftware, can you please fill the project details in the PR description field

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
@MultiChainSoftware there some issues with the PR, you can not count entire LP as your tvl, only the staked part as `pool2`, and staked XMT tokens needs to be counted under `staking` not tvl, if you give me the staking contract addresses for  staked LPs in different chains, I can refactor your code and fix it myself

**Comment by MultiChainSoftware** [comment]
> Hi @MultiChainSoftware, can you please fill the project details in the PR description field

Done

**Comment by g1nt0ki** [comment]
> @MultiChainSoftware there some issues with the PR, you can not count entire LP as your tvl, only the staked part as `pool2`, and staked XMT tokens needs to be counted under `staking` not tvl, if you give me the staking contract addresses for staked LPs in different chains, I can refactor your code and fix it myself

@MultiChainSoftware can you share the staking contracts

**Comment by MultiChainSoftware** [comment]
> > @MultiChainSoftware there some issues with the PR, you can not count entire LP as your tvl, only the staked part as `pool2`, and staked XMT tokens needs to be counted under `staking` not tvl, if you give me the staking contract addresses for staked LPs in different chains, I can refactor your code and fix it myself
> 
> @MultiChainSoftware can you share the staking contracts

New commit should address the problem, let me know if everything is fine

**Comment by g1nt0ki** [comment]
@MultiChainSoftware thanks, for splitting tvl between pool2 and staking. But you still cant count entirer LP as your pool2 only the staked tokens

**Comment by MultiChainSoftware** [comment]
> @MultiChainSoftware thanks, for splitting tvl between pool2 and staking. But you still cant count entirer LP as your pool2 only the staked tokens

please check last commit

**Comment by g1nt0ki** [comment]
@MultiChainSoftware okay, let it be. I dont understand your last commit. All I see is, something added as polygon tvl.

 I will fix the rest.

**Comment by llamatester** [comment]
The adapter at projects/metalswap exports TVL: 
        
 
 
    ethereum                  0
    bsc                       0
    bsc-staking               3.21 M
    ethereum-staking          8.98 M
    polygon-pool2             291.54 k
    staking                   12.19 M
    pool2                     291.54 k
    
    total                    0

**Pull request merged**
