### PR TITLE
Listing HEADLINE (Algorand DeFi protocol)

### PR DESCRIPTION
**Pull request by headline-design**
##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

icon (1)
icon (1)

##### Short Description (to be shown on DefiLlama):
HEADLINE Crypto is a Texas-based blockchain project and token from the team behind AlgoPay, AlgoCloud, Vaults Protocol, FORUM, PIPELINE-UI, and Algo Astros.

##### Token address and ticker if any:
HDL
https://coinmarketcap.com/currencies/headline-inc

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Synthetics

##### methodology (what is being counted as tvl, how is tvl being calculated):

TVL is calculated by iterating through the list of stakers, finding stakers who have been banned (due to failing to maintain their committed ASA balances with 10% variance), and subtracting their staked amount from the known total vault staked amount at the time the staking registration period expired.

### CODE REVIEW

**Comment by g1nt0ki** [comment]
Hi, thanks for the PR, I have a few questions

1. HDL is your own token right? If users state it, it would count towards 'staking' not 'tvl'
2. If all the HDL comes from user staking, can we compute staking value from querying amount of HDL in 'ALPWZJB6DRFNZIMP4SG44V27Z2YNKJ4DNEWVQ2HZ4JJBE4SUTVMTL4X35Q'?
3. I dislike that HDL amount is hardcorded in the file, is this fixed? 
4. Is there some way to deteremine/fetch HDL price? ideally from call to algorand chain

**Comment by headline-design** [comment]
1. Yes. However, the actual token that is permanently locked by users in the smart contract-controlled address is sHDL, which represents not only HDL, but also various "NFTs." Please clarify if you would like us to change the category to staking or merely change the function name in the object at the bottom of the code.

2. No.The ALPW... address is the TinyMan USDC/HDL pool and is used to calculate the value of HDL in dollars.

Also, the HDL in the pool address does NOT come from users staking: it is the reward amount deposited by Headline. What is actually staked by the users is sHDL, which is a token of a promise that users will maintain an equal balance of real HDL and select NFT's with a 10% allowed variance for 6 months. Users who break this condition are banned from the protocol

The staking address itself is: UNCB45HXL3SGDPJANZZ22JWOJQ7UKAXWPMWUSDABVDGD36QYU45ISFLQNM. Its HDL and sHDL balances can be directly queried with this address, however, it is impossible to prevent anyone from sending additional asas  to any Algorand address that is opted into them. Therefore, the staking protocol only records approved group transactions in the stakers app local state, and querying these addresses is the only way (with the existing TEAL contract) to accurately recalculate the staked total when taking into account users that have been banned for breaking the program rules. 

3. It is fixed for the time being. However, the HDL amount is merely the "reward" side of the fund that was initially deposited into the account. This amount will be used to pay out the rewards when the protocol term of 6 months has passed. 

4. Yes, and this is already done in the code as described above. (Also, price is available on CoinMarketCap - https://coinmarketcap.com/currencies/headline-inc/)

**Comment by g1nt0ki** [comment]
@headline-design thanks for the detailed response.

For starters, vaultHDL is the reward your team has put for staking right? if so, sorry it cant be counted towards either staking or tvl.

Regarding sHDL is the staking contract, this is a permanently locked pledge token? can never be withdrawn from the contract and used anywhere?

**Comment by headline-design** [comment]
@headline-design thanks for the detailed response.

Our pleasure! We are happy to clarify any and all points.

For starters, vaultHDL is the reward your team has put for staking right? if so, sorry it cant be counted towards either staking or tvl.

That's correct, Vault HDL is the reward. We can remove this from the PR.

Regarding sHDL is the staking contract, this is a permanently locked pledge token? can never be withdrawn from the contract and used anywhere?

That is correct. sHDL is locked and cannot be removed from the contract.

**Comment by g1nt0ki** [comment]
Sorry, I think this is an issue. We have a policy of not counting unvested funds/tokens as tvl. We have a similar issue with streaming income protocols.

**Pull request closed without merging**
