### PR TITLE
SSL tvl

### PR DESCRIPTION
**Pull request by vickcharles**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### List of audit links if any: https://github.com/zokyo-sec/audit-reports/blob/main/Tren%20Finance/Tren%20Finance_Zokyo_audit_report_Nov19th_2024.pdf

Omniscia Tren Finance Audit

##### Logo (High resolution, will be shown with rounded borders):

pfp

##### Current TVL:
Not Applicable: We have not deployed mainnet

##### Treasury Addresses (if the protocol has treasury) 

0x727763929490cccf903c916589F3d33A95C5A266

### CODE REVIEW

**Comment by llamabutler** [comment]
Error while running adapter at projects/tren-finance: 
        
 
  
    
    
    Error: 
        Found export keys that were not part of specification: yields
    
        List of valid keys: 
    				
    				tvl
    				staking
    				methodology
    				pool2
    				misrepresentedTokens
    				fetch
    				timetravel
    				borrowed
    				start
    				doublecounted
    				hallmarks
    				isHeavyProtocol
    				deadFrom
    				ownTokens
    				vesting
        
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'

**Comment by llamabutler** [comment]
Error while running adapter at projects/tren-finance: 
        
 
  
    
    
    Error: 
        Please move the following keys into the chain: tvl
    
        We have a new adapter export specification now where tvl and other chain specific information are moved inside chain export.
        For example if your protocol is on ethereum and has tvl and pool2, the export file would look like:
        
            module.exports = {
              methodlogy: '...',
              ethereum: {
                tvl: 
                pool2:
              }
            }
    
        
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'

**Comment by llamabutler** [comment]
Error while running adapter at projects/tren-finance: 
        
 
  
    
    
    Error: Invalid balance: NaN
    Truncated error stack:
    
        at isValidNumber (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:114:19)
        at Object.sumSingleBalance (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:85:5)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:351:16
        at Array.forEach (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:345:28)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:358:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:54:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:173:9
        at async Promise.all (index 0)

**Comment by llamabutler** [comment]
Error while running adapter at projects/tren-finance: 
        
 
  
    
    
    Error: Invalid balance: NaN
    Truncated error stack:
    
        at isValidNumber (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:114:19)
        at Object.sumSingleBalance (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:85:5)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:351:16
        at Array.forEach (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:345:28)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:358:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:54:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:173:9
        at async Promise.all (index 0)

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
is this PR meant for yield repo? https://github.com/DefiLlama/yield-server

**Comment by llamabutler** [comment]
The adapter at projects/tren-finance exports TVL: 
        
 
 
    arbitrum                  0
    
    total                    0

**Comment by llamabutler** [comment]
The adapter at projects/tren-finance exports TVL: 
        
 
 
    arbitrum                  0
    
    total                    0

**Comment by llamabutler** [comment]
The adapter at projects/tren-finance exports TVL: 
        
 
 
    arbitrum                  0
    
    total                    0

**Comment by llamabutler** [comment]
The adapter at projects/tren-finance exports TVL: 
        
 
 
    arbitrum                  118.45 k
    
    total                    118.45 k

**Comment by llamabutler** [comment]
The adapter at projects/tren-finance exports TVL: 
        
 
 
    arbitrum                  110.42 k
    
    total                    110.42 k

**Comment by g1nt0ki** [comment]
thanks for the PR, refactored and merged it

**Pull request closed without merging**
