### PR TITLE
feat: add zkLend project

### PR DESCRIPTION
**Pull request by stacey-zklend**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
Name (to be shown on DefiLlama): zkLend
Twitter Link:  https://twitter.com/zklend/
List of audit links if any:  
Website Link: https://zklend.com/  
Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):  https://logo.zklend.com/
Current TVL: $938,562.09
Chain: Starknet
Coingecko ID (so your TVL can appear on Coingecko):  
Coinmarketcap ID (so your TVL can appear on Coinmarketcap):  
Short Description (to be shown on DefiLlama): zkLend is an L2 money-market protocol built on StarkNet, combining zk-rollup scalability, superior transaction speed, and cost-savings with Ethereum's security. The protocol offers a dual solution: a permissioned and compliance-focused solution for institutional clients, and a permissionless service for DeFi users - all without sacrificing decentralisation.
Token address and ticker if any:
Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one: Lending
Oracle used (Chainlink/Band/API3/TWAP or any other that you are using): Pragma
forkedFrom (Does your project originate from another project): No
methodology (what is being counted as tvl, how is tvl being calculated): Value of user supplied asset on zkLend

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/zklend exports TVL: 
        
 
 
    starknet                  938.57 k
    
    total                    938.57 k

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
can you please update the adapter to compute tvl on chain instead and split borrowed tvl and display it under "borrowed" key

**Comment by llamatester** [comment]
The adapter at projects/zklend exports TVL: 
        
 
 
    starknet                  963.35 k
    starknet-borrowed         201.17 k
    borrowed                  201.17 k
    
    total                    963.35 k

**Comment by stacey-zklend** [comment]
> can you please update the adapter to compute tvl on chain instead and split borrowed tvl and display it under "borrowed" key

Added borrowed tvl, thanks.

**Comment by stacey-zklend** [comment]
> > > can you please update the adapter to compute tvl on chain instead and split borrowed tvl and display it under "borrowed" key
> > 
> > 
> > Added borrowed tvl, thanks.
> 
> sorry, tvl is still not being computed on chain

Hi, updated code and now tvl and borrowed tvl is base on chain data. Thanks.

**Comment by g1nt0ki** [comment]
@stacey-zklend looks good, thanks for fixing it.

**Pull request merged**
