### PR TITLE
Update Sphere Data

### PR DESCRIPTION
**Pull request by SimsalaCrypto**
**NOTE**

Updating some data which are atm incorrect on DefiLlama for Sphere

---

##### methodology (what is being counted as tvl, how is tvl being calculated): Everything in our treasuries is being used for TVL, the TVL stems from the https://multifarm.fi/ calculation

---

Thank you!

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/sphere-finance exports TVL: 
        
 
 
    polygon                   11.64 M
    
    total                    11.64 M

**Comment by g1nt0ki** [comment]
@SimsalaCrypto thanks for the PR but can you compute the TVL on chain?

**Comment by SimsalaCrypto** [comment]
Hi there and thank you for the prompt response! The  assets are being used in products similarly to Beefy and that’s why we opted to use the same method for TVL like Beefy did via an API (we’re autocompounding most of our assets in contracts). Hope there’s no problem with that. @g1nt0ki

**Comment by realdealshaman** [comment]
Hey, thanks a lot for submitting the adapter. We are working on converting all previously merged api adapters to on-chain to improve transparency so we'd prefer to not merge another api adapter.

**Comment by SimsalaCrypto** [comment]
hey, thank you for the response. Will forward this to my team. I totally understand the urge for transparency. Will try to look into fixing the adapter with onchain calls!

**Comment by SimsalaCrypto** [comment]
But wouldn’t this cause a lot more pull requests due to the amount of updates every project would require to add new vaults, etc. or is there a good way to mitigate this?

**Comment by g1nt0ki** [comment]
> But wouldn’t this cause a lot more pull requests due to the amount of updates every project would require to add new vaults, etc. or is there a good way to mitigate this?

Yeah, unforunate consequence, but sometimes it is possible to fetch vault list on chain, this way we no longer need to manually update the adapters

**Comment by llamatester** [comment]
The adapter at projects/sphere-finance exports TVL: 
        
 
 
    polygon                   11.98 M
    
    total                    11.98 M

**Comment by llamatester** [comment]
The adapter at projects/sphere-finance exports TVL: 
        
 
 
    polygon                   982.94 k
    polygon-staking           0
    staking                   0
    
    total                    982.94 k

**Comment by llamatester** [comment]
The adapter at projects/unknown exports TVL: 
        
 
 
    bsc-staking               0
    bsc                       2.39 M
    staking                   0
    
    total                    2.39 M

**Pull request closed without merging**
