### PR TITLE
Added new KFT token for stacking.

### PR DESCRIPTION
**Pull request by InbuiltFinanceDev**
Twitter Link: https://twitter.com/Inbuiltfinance

List of audit links if any: 

Website Link: http://inbuilt.finance/

Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

Inbuilt Finance

Current TVL: $928.0649

Chain: KAVA

Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

Coinmarketcap ID (so your TVL can appear on Coinmarketcap): https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000

Short Description (to be shown on DefiLlama): Liquid stacking protocol for all the assets.

Token address and ticker if any: 

Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one: Staking

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using): custom

forkedFrom (Does your project originate from another project): no

methodology (what is being counted as tvl, how is tvl being calculated): Total values of all token stacked on our platform.

We are not directly connected with Knit. They have given us funding and adding tokens to our pools.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/inbuilt-finance exports TVL: 
        
 
 
    kava                      1.74 k
    
    total                    1.74 k

**Comment by g1nt0ki** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters/pull/5114

I see that you have re-opened the PR, why exactly is KFT being added to the masterchef if there is no relation with the team?

**Comment by InbuiltFinanceDev** [comment]
> #5114
> 
> I see that you have re-opened the PR, why exactly is KFT being added to the masterchef if there is no relation with the team?

We are not directly connected with Knit. They have given us funding and adding tokens to our pools.

**Comment by g1nt0ki** [comment]
> > #5114
> > I see that you have re-opened the PR, why exactly is KFT being added to the masterchef if there is no relation with the team?
> 
> We are not directly connected with Knit. They have given us funding and adding tokens to our pools.

In that case, we can include it under staking, not as tvl

**Comment by InbuiltFinanceDev** [comment]
> > > #5114
> > > I see that you have re-opened the PR, why exactly is KFT being added to the masterchef if there is no relation with the team?
> > 
> > 
> > We are not directly connected with Knit. They have given us funding and adding tokens to our pools.
> 
> In that case, we can include it under staking, not as tvl

Asking our marketing team to answer this.

**Comment by InbuiltFinanceDev** [comment]
What is the difference couting in stacking vs in tvl. and why not TVL?

**Comment by g1nt0ki** [comment]
https://docs.llama.fi/list-your-project/what-to-include-as-tvl

> What is the difference couting in stacking vs in tvl. and why not TVL?

**Comment by InbuiltFinanceDev** [comment]
> https://docs.llama.fi/list-your-project/what-to-include-as-tvl
> 
> > What is the difference couting in stacking vs in tvl. and why not TVL?

Can you please clarify : when usdc bridged through multichain is accepted as tvl and will kft bridged through multichain will be accepted?

**Comment by g1nt0ki** [comment]
> > https://docs.llama.fi/list-your-project/what-to-include-as-tvl
> > > What is the difference couting in stacking vs in tvl. and why not TVL?
> 
> Can you please clarify : when usdc bridged through multichain is accepted as tvl and will kft bridged through multichain will be accepted?

the issue is quite simple, it costs you/knit team nothing to mint 10M$ worth of Knit tokens and deposit n your protocol, this is the reason why we cant accept it as tvl

**Comment by InbuiltFinanceDev** [comment]
> > > https://docs.llama.fi/list-your-project/what-to-include-as-tvl
> > > > What is the difference couting in stacking vs in tvl. and why not TVL?
> > 
> > 
> > Can you please clarify : when usdc bridged through multichain is accepted as tvl and will kft bridged through multichain will be accepted?
> 
> the issue is quite simple, it costs you/knit team nothing to mint 10M$ worth of Knit tokens and deposit n your protocol, this is the reason why we cant accept it as tvl

KFT was minted at time of launch and there is no mint function attached to it. If we use multichain version of KFT will that be counted as TVL?

**Comment by g1nt0ki** [comment]
@InbuiltFinanceDev sorry, no. no version of KFT can be included as tvl here.

**Comment by InbuiltFinanceDev** [comment]
It has been noted that Web3 prides itself on being a permissionless and open platform without restrictions. However, it has come to our attention that KFT has not been included without a genuine reason, which has resulted in a negative impact on our TVL, potential customers who were supposed to stake, and genuine KFT holders who miss out on getting rewards. This situation is also reinforcing the belief that Web3 being open is not entirely true.

We kindly request that the appropriate parties look into this matter and provide a genuine reason for the exclusion of KFT, as well as a resolution that will enable us to return our grant and ensure that genuine KFT holders are not left out of getting rewards. Thank you for your time and consideration.

**Comment by InbuiltFinanceDev** [comment]
Thanks for getting back 
Web3 always prides itself on being a permissionless and open platform without restrictions. However, it has come to our attention that KFT has not been included without a genuine reason, which will result in lose of initial boost of marketing, a negative impact on growth and TVL, potential customers who were supposed to stake, and genuine KFT holders who miss out on getting rewards and as well Kava chain not getting TVL. This situation is also reinforcing the belief that Web3 being open is not entirely true.

We kindly request you to reconsider your  decision and enable us to retain our grant and ensure that genuine KFT holders are not left out of getting rewards. Thank you for your time and consideration.

**Comment by g1nt0ki** [comment]
Sorry, I am closing this story.

Web3 means I have no control over what you do, your protocol would work the same whether we include KFT as part of your TVL or not.

**Pull request closed without merging**
