### PR TITLE
Add new dxsale chains and cleanup old unused chains

### PR DESCRIPTION
**Pull request by DaRabus**
Updated some DxSale Chains and removed some unused once

https://github.com/DefiLlama/DefiLlama-Adapters/pull/5576

https://github.com/DefiLlama/DefiLlama-Adapters/pull/3207

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/dxsale: 
        
 
  
    
    
    Error: Error: No RPCs available for arbitrum

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
hi, it mostly looks good but can you revert the changes where you remove some chains? it will break our server since these chains are currently supported, also would mess up those chain's tvl history

**Comment by DaRabus** [comment]
> hi, it mostly looks good but can you revert the changes where you remove some chains? it will break our server since these chains are currently supported, also would mess up those chain's tvl history

Ok, HECO i will leave away since the chain doesn't exist anymore.

**Comment by llamatester** [comment]
Error while running adapter at projects/dxsale: 
        
 
  
    
    
    Error: TypeError: Cannot read properties of null (reading 'call')

**Comment by g1nt0ki** [comment]
@DaRabus refactored the code a bit and included your changes here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/59998d9d27becca6113cdf24ffe9f37f33dd0151 this will hopefully make it more easy to add new chains in the future

**Pull request closed without merging**
