### PR TITLE
feat: add PSM TVL and new collaterals

### PR DESCRIPTION
**Pull request by tyler-tsai**
Add fdUSD, USDT, solvBTC.bbn as new collaterals and we have vUSDT LSR TVL

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/helio-money exports TVL: 
        
 
 
    bsc                       220.69 M
    bsc-staking               29.42 M
    staking                   29.42 M
    bsc-pool2                 1.01 M
    pool2                     1.01 M
    
    total                    220.69 M

**Comment by tyler-tsai** [comment]
@g1nt0ki can we specify a read method of TVL?
for example: getTotalNetDepositAmount
https://bscscan.com/address/0x5763DDeB60c82684F3D0098aEa5076C0Da972ec7#readProxyContract

**Comment by g1nt0ki** [comment]
why use netDeposits when it is simpler to check token balance. That aside, we do prefer checking token balance than reading state as tvl

**Comment by tyler-tsai** [comment]
> why use netDeposits when it is simpler to check token balance. That aside, we do prefer checking token balance than reading state as tvl

As we can see, I use this address but somehow sum function doesn't get its balances.

**Comment by g1nt0ki** [comment]
are you sure, I do see it: 
image

**Comment by llamatester** [comment]
The adapter at projects/helio-money exports TVL: 
        
 
 
    bsc                       216.99 M
    bsc-staking               27.99 M
    staking                   27.99 M
    bsc-pool2                 1.07 M
    pool2                     1.07 M
    
    total                    216.99 M

**Comment by llamatester** [comment]
The adapter at projects/helio-money exports TVL: 
        
 
 
    bsc                       220.48 M
    bsc-staking               27.99 M
    staking                   27.99 M
    bsc-pool2                 1.07 M
    pool2                     1.07 M
    
    total                    220.48 M

**Comment by tyler-tsai** [comment]
@g1nt0ki it does work, thanks for checking. Can you share the command you tried?

**Comment by g1nt0ki** [comment]
`node test.js projects/helio-money`

**Comment by g1nt0ki** [comment]
hi @tyler-tsai can I merge this now?

**Comment by tyler-tsai** [comment]
There is still something needed to be confirmed, I will tag you once PR is
ready, would that be ok?

**Comment by g1nt0ki** [comment]
yeah, tag me when it is ready

**Comment by llamatester** [comment]
The adapter at projects/helio-money exports TVL: 
        
 
 
    bsc                       258.81 M
    bsc-staking               30.30 M
    staking                   30.30 M
    bsc-pool2                 1.50 M
    pool2                     1.50 M
    
    total                    258.81 M

**Comment by tyler-tsai** [comment]
@g1nt0ki Sorry for asking twice in such a short time. I’d appreciate it if you could take a look when you have time. Thank you again!

**Review by g1nt0ki — APPROVED** [review]

**Pull request merged**
