### PR TITLE
TVL adapter for ZEEBU

### PR DESCRIPTION
**Pull request by dsarvaiya**
updated pool2 staking details of various pools for base chain

### CODE REVIEW

**Comment by llamabutler** [comment]
Error while running adapter at projects/Zeebu: 
        
 
  
    
    
    SyntaxError: Unexpected token ':'
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:127:12
        at Object.<anonymous> (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:259:3)
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'

**Comment by llamabutler** [comment]
The adapter at projects/Zeebu exports TVL: 
        
 
 
    staking                   9.41 M
    bsc-staking               9.32 M
    base-pool2                4.21 M
    pool2                     4.21 M
    ethereum-staking          86.66 k
    base-staking              7.53 k
    ethereum                  0
    base                      0
    bsc                       0
    
    total                    0

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
https://github.com/DefiLlama/DefiLlama-Adapters/pull/12684#pullrequestreview-2499718260

**Comment by dsarvaiya** [comment]
as per your suggestion, we update and consider DEX pool amount under pool2 not as TVL.
Kindly suggest us more on the same

**Comment by g1nt0ki** [comment]
no, tokens in dex pools belong to that dex's tvl. Only dex's LP tokens deposited in contracts controlled by your team count towards your pool2

**Comment by llamabutler** [comment]
The adapter at projects/Zeebu exports TVL: 
        
 
 
    staking                   9.50 M
    bsc-staking               9.41 M
    ethereum-staking          87.49 k
    base-staking              7.71 k
    base-pool2                888
    pool2                     888
    ethereum                  0
    base                      0
    bsc                       0
    
    total                    0

**Comment by llamabutler** [comment]
The adapter at projects/Zeebu exports TVL: 
        
 
 
    staking                   9.37 M
    bsc-staking               9.27 M
    ethereum-staking          86.25 k
    base-staking              7.64 k
    base-pool2                885
    pool2                     885
    ethereum                  0
    
    total                    0

**Pull request merged**
