### PR TITLE
Nomad

### PR DESCRIPTION
**Pull request by Jrachman**

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Can this be changed to count tokens on the destination chain opposed to source chain?

**Comment by waynebruce0x** [comment]
@Jrachman any update?

**Comment by Jrachman** [comment]
@waynebruce0x finished! let me know if there is anything else to change :)

**Comment by llamatester** [comment]
Error while running adapter at projects/nomad: 
        
 
 
    
        Unknown chain(s): milkomedaC1
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file

**Comment by Jrachman** [comment]
> Error while running adapter at projects/nomad:
> 
> ```
>     Unknown chain(s): milkomedaC1
>     Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file
> ```

updated!

**Comment by llamatester** [comment]
The adapter at projects/nomad exports TVL: 
        
 
 
    milkomeda                 0
    moonbeam                  0
    ethereum                  55.50 M
    
    total                    55.50 M

**Pull request merged**
