### PR TITLE
Update cream TVL

### PR DESCRIPTION
**Pull request by 0xyolo**

### CODE REVIEW

**Comment by eason1305** [comment]
Twitter Link: https://twitter.com/creamdotfinance

List of audit links if any: https://github.com/trailofbits/publications/blob/master/reviews/CREAMSummary.pdf

Website Link: https://app.cream.finance

Logo: https://docs.cream.finance/press-kit#cream-logo

Current TVL: $29m

Chain: Ethereum, BSC, FTM, Polygon, Arbitrum, Avalanche

Coingecko ID (so your TVL can appear on Coingecko): cream-2

Coinmarketcap ID (so your TVL can appear on Coinmarketcap): cream-finance

Short Description (to be shown on DefiLlama): 

Token address and ticker if any: CREAM (https://etherscan.io/address/0x2ba592F78dB6436527729929AAf6c908497cB200)

Category: Lending

Oracle used: Chainlink & Band Protocol

forkedFrom: Compound

methodology: lending - borrow

**Comment by eason1305** [comment]
Twitter Link: https://twitter.com/ibdotxyz

List of audit links if any: https://github.com/trailofbits/publications/blob/master/reviews/CREAMSummary.pdf

Website Link: https://ib.xyz

Logo: https://drive.google.com/file/d/1TvIkugqwoWl0MO57eU29gxutzhejkbLL

Current TVL: $29m

Chain: Ethereum, FTM, Avalanche

Coingecko ID (so your TVL can appear on Coingecko): 

Coinmarketcap ID (so your TVL can appear on Coinmarketcap):

Short Description (to be shown on DefiLlama):

Token address and ticker if any: IB (https://ftmscan.com/address/0x00a35FD824c717879BF370E70AC6868b95870Dfb)

Category: Lending

Oracle used: Chainlink & Band Protocol

forkedFrom: Compound

methodology: lending - borrow

**Comment by 0xngmi** [comment]
I see that you also included some regular cream markets (not just ib), is that correct?

**Comment by jeremyHD** [comment]
> I see that you also included some regular cream markets (not just ib), is that correct?

correct

**Pull request merged**
