### PR TITLE
Add Evergreen DAO on HAQQ Network

### PR DESCRIPTION
**Pull request by VorobevSA**
##### Name (to be shown on DefiLlama):
Evergreen DAO

##### Twitter Link:
https://twitter.com/Islamic_Coin

##### List of audit links if any:
https://haqq.network/audits

##### Website Link:
https://islamiccoin.net/

##### Logo (High resolution, will be shown with rounded borders):
https://haqq.network/assets/media-kit/islamic-mark.png

##### Current TVL:
2.0b ISLM

##### Treasury Addresses (if the protocol has treasury)
haqq1jv65s3grqf6v6jl3dp4t6c9t9rk99cd89c30hf

##### Chain:
haqq (HAQQ Network)  

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
islamic-coin

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
islamic-coin

##### Short Description (to be shown on DefiLlama):
Evergreen DAO is introduced to fund projects benefiting the global Muslim community, grants to ecosystem maintainers, bug bounties, marketing activities and other initiatives which the community decides are helpful for the HAQQ Network and/or the Muslim community.

##### Token address and ticker if any:
ISLM (Minimal denom aISLM)

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Indexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Not used

##### methodology (what is being counted as tvl, how is tvl being calculated):
Direct receipt of the balance of the community pool on the cosmos network blockchain (Haqq network)

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/haqq-network

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/evergreen-dao exports TVL: 
        
 
 
    haqq                      0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/evergreen-dao exports TVL: 
        
 
 
    haqq                      0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/evergreen-dao exports TVL: 
        
 
 
    haqq                      0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/evergreen-dao exports TVL: 
        
 
 
    haqq                      0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/evergreen-dao exports TVL: 
        
 
 
    haqq                      0
    
    total                    0

**Comment by g1nt0ki** [comment]
hi, are you trying to count the tokens in your treasury as tvl? https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by g1nt0ki** [comment]
hi @VorobevSA what do you mean by blocked? Just to be clear, we dont treat project treasury as tvl

**Comment by g1nt0ki** [comment]
how?

**Comment by g1nt0ki** [comment]
example of offers: you approve OpenSea/Blur to sell your NFT but the NFT remains in your wallet

**Pull request closed without merging**
