### PR TITLE
add scallop

### PR DESCRIPTION
**Pull request by djchrisssssss**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

##### Twitter Link: 

https://twitter.com/Scallop_io

##### Website Link: 

https://scallop.io

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): 

SCA

##### Current TVL:  

5.732992

##### Chain: 

Solana

##### Short Description (to be shown on DefiLlama):

Scallop is a diverse no-loss protocol on Solana, maximize the potential yield with no principal loss.

##### Category (full list at https://defillama.com/categories) *Please choose only one:

6

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

Switchboard, Pyth

##### methodology (what is being counted as tvl, how is tvl being calculated):

Scallop TVL is the total value of Scallop Pools funds.

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@djchrisssssss thanks for the PR, but can you compute the tvl using on chain calls instead?

**Comment by nathanramli** [comment]
Hi @g1nt0ki,
We have done some updates. 
Please review it. Thank you.

**Comment by llamatester** [comment]
The adapter at projects/scallop exports TVL: 
        
 
 
    solana                    0
    
    total                    0

**Comment by nathanramli** [comment]
> The adapter at projects/scallop exports TVL:
> 
> ```
> solana                    0
> 
> total                    0 
> ```

Are these tests not run on the mainnet?

**Comment by g1nt0ki** [comment]
@djchrisssssss there was bug,  I have fixed it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/3488 
The PR was perfect otherwise

**Pull request merged**
