### PR TITLE
feat: Add ZooDAO Adapter

### PR DESCRIPTION
**Pull request by Roy412**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Treasury Addresses (if the protocol has treasury)
0x084eaEF922d6976F412DF50FBA8b23b49f073985

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

{"id":"zoodao","symbol":"zoo","name":"ZooDAO"}

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

“zoodao” https://coinmarketcap.com/currencies/zoodao/

##### Short Description (to be shown on DefiLlama):
ZooDAO is a no-loss yield farming game for NFTs powered by DeFi yields. Stake, Vote, Earn.

##### Token address and ticker if any:
ZOO: 
Moonbeam: 0x7cd3e6e1A69409deF0D78D17a492e8e143F40eC5
Ethereum:  0x09F098B155D561Fc9F7BcCc97038b7e3d20bAF74
Fantom: 0x1ac0c9592E2480649e9471c1548F60564b37a46B
Arbitrum: 0x1689A6E1f09658FF37d0bB131514E701045876dA

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield

##### forkedFrom (Does your project originate from another project):
No fork

##### methodology (what is being counted as tvl, how is tvl being calculated):
Counts the supplied value of FRAX and ZOO through ZooDAO's contracts.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/zoodao exports TVL: 
        
 
 
    moonbeam                  322.01 k
    
    total                    322.01 k

**Comment by llamatester** [comment]
The adapter at projects/zoodao exports TVL: 
        
 
 
    moonbeam                  321.74 k
    moonbeam-staking          0
    staking                   0
    
    total                    321.74 k

**Comment by g1nt0ki** [comment]
@Roy412 thanks for the PR, I have made a minor refactor.
We count own tokens under staking. ZOO token is not getting priced now because not much liquidity/trading volume (my guess and looks like that on coingecko)

**Comment by Roy412** [comment]
> @Roy412 thanks for the PR, I have made a minor refactor. We count own tokens under staking. ZOO token is not getting priced now because not much liquidity/trading volume (my guess and looks like that on coingecko)

Hi, @g1nt0ki Thanks for your review and refactoring. You're right, most of the liquidity/trading volume is on Moonbeam but seems Coingecko doesn't care about Moonbeam. We can just merge this PR to have only FRAX TVL priced.

**Pull request merged**
