### PR TITLE
monocerus on manta

### PR DESCRIPTION
**Pull request by pullstacker**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Monocerus

##### Twitter Link:
https://x.com/monocerusworld

##### List of audit links if any:
https://shellboxes.com/audit/reports/CerusToken_Security_Audit_Report.pdf

##### Website Link:
https://monocerus.world

##### Logo (High resolution, will be shown with rounded borders):
https://monocerus.world/images/logo2.png

##### Current TVL:
23435 usd

##### Chain:
Manta

##### Short Description (to be shown on DefiLlama):
Monocerus is a Massive Multi-players Online Role Playing Game (MMORPG) 3.0 with Gamified CLMM Dex feature

##### Token address and ticker if any:
0x657218E3535B32EDef9a722E35dcd6EA40E1202e CERUS on Manta
0x6F0167Dca1fAB2AaBe20cf56B7a7E1FdB47AC388 CERUS on Avalanche

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Gaming

##### forkedFrom (Does your project originate from another project):
Uniswap V3

##### methodology (what is being counted as tvl, how is tvl being calculated):
https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/monocerus/index.js

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/monocerusworld

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/monocerus exports TVL: 
        
 
 
    manta                     25.01 k
    
    total                    25.01 k

**Comment by pullstacker** [comment]
> The adapter at projects/monocerus exports TVL:
> 
> ```
> manta                     25.01 k
> 
> total                    25.01 k 
> ```

confirmed

**Comment by realdealshaman** [comment]
Hey @pullstacker , thanks for the pr however, since monocerus was also previously on Avalanche we'd prefer to not remove that data, we keep all previously listed data even when operations on a chain are discontinued

**Comment by llamatester** [comment]
The adapter at projects/monocerus exports TVL: 
        
 
 
    manta                     23.53 k
    
    total                    23.53 k

**Comment by pullstacker** [comment]
> Hey @pullstacker , thanks for the pr however, since monocerus was also previously on Avalanche we'd prefer to not remove that data, we keep all previously listed data even when operations on a chain are discontinued

Hi @realdealshaman we've put back avax, thanks

**Comment by pullstacker** [comment]
> The adapter at projects/monocerus exports TVL:
> 
> ```
> manta                     23.53 k
> 
> total                    23.53 k 
> ```

confirmed

**Comment by realdealshaman** [comment]
Thanks for understanding. I will close this pr since no changes are being added. Thanks again

**Pull request closed without merging**
