### PR TITLE
Add B² Buzz TVL

### PR DESCRIPTION
**Pull request by Stonepapa**
Add B² Buzz TVL

**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):  
```
B² Buzz
```

##### Protocol Information: 
```
Launched by B² Network, B² Buzz is a staking event where a user can deposit major cryptocurrency assets from Bitcoin, Ethereum, BNB Chain, and Polygon. By doing so, a user will receive a certain amount of Parts which can be used to assemble Mining Rigs. Mining Rigs are employed to mine B² native tokens.
```
 
##### Twitter Link: 
```
https://twitter.com/BsquaredNetwork
```

##### List of audit links if any:
```
```

##### Website Link: 
```
https://www.bsquared.network/
```

##### Logo (High resolution, will be shown with rounded borders): 
```
https://ipfs.io/ipfs/Qmc1rHyVsnqDo4AW8e9fuhEuQsnMmaKw4Yk2KFEPgc2dCv
```

##### Current TVL: 
```
401.86 M 
```

##### Treasury Addresses (if the protocol has treasury)
```
bitcoin: bc1qva5m5e7da2zm590z03tdnj42u9q2uye3hgrehwrzgg8j4kxq9seq9rvw0m
brc20: bc1q97ctqygjgj0ljxgge4q735ujxvlad8smass7f0axc6x3ggffr8xqwn69hc
ethereum: 0xeea3A032f381AB1E415e82Fe08ebeb20F513c42c
polygon: 0x01cE88498ED095d386e09834D32Fd8f1FeCd184a
bsc:  0x0A80028d73Faaee6e57484E3335BeFda0de7f455
```

##### Chain:
```
bitcoin | ethereum | polygon | bsc
```

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
```
```

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
```
```

##### Short Description (to be shown on DefiLlama):
```
Launched by B² Network, B² Buzz is a staking event where a user can deposit major cryptocurrency assets from Bitcoin, Ethereum, BNB Chain, and Polygon. By doing so, a user will receive a certain amount of Parts which can be used to assemble Mining Rigs. Mining Rigs are employed to mine B² native tokens.
```

##### Token address and ticker if any: 
```
```

##### Category (full list at https://defillama.com/categories) *Please choose only one: 
```
Farm
```

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
```
```
##### Implementation Details: Briefly describe how the oracle is integrated into your project:
```
```
##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
```
```

##### forkedFrom (Does your project originate from another project):
```
```

##### methodology (what is being counted as tvl, how is tvl being calculated): 
```
Staking tokens via BSquared Network Buzz counts as TVL
```

##### Github org/user (Optional, if your code is open source, we can track activity): 
```
https://github.com/b2network
```

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/bsquared: 
        
 
  
    
    
    Error: Failed to get https://open-api.unisat.io/v1/indexer/address/bc1q97ctqygjgj0ljxgge4q735ujxvlad8smass7f0axc6x3ggffr8xqwn69hc/brc20/summary
    Truncated error stack:
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:139:35
        at get (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/http.js:32:11)
        at async sumTokens (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/brc20.js:11:34)
        at async Promise.all (index 1)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:64:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:160:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)

**Comment by llamatester** [comment]
Error while running adapter at projects/bsquared: 
        
 
  
    
    
    Error: Failed to get https://open-api.unisat.io/v1/indexer/address/bc1q97ctqygjgj0ljxgge4q735ujxvlad8smass7f0axc6x3ggffr8xqwn69hc/brc20/summary
    Truncated error stack:
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:139:35
        at get (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/http.js:32:11)
        at async sumTokens (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/brc20.js:11:34)
        at async Promise.all (index 1)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:64:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:160:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)

**Comment by llamatester** [comment]
Error while running adapter at projects/bsquared: 
        
 
  
    
    
    Error: Failed to get https://open-api.unisat.io/v1/indexer/address/bc1q97ctqygjgj0ljxgge4q735ujxvlad8smass7f0axc6x3ggffr8xqwn69hc/brc20/summary
    Truncated error stack:
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:139:35
        at get (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/http.js:32:11)
        at async sumTokens (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/brc20.js:11:34)
        at async Promise.all (index 1)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:64:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:160:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)

**Comment by g1nt0ki** [comment]
@Stonepapa thanks for the PR

**Pull request merged**
