### PR TITLE
add Konverter porotocol

### PR DESCRIPTION
**Pull request by WemadeDeFiDev**
---
##### Github org/user (Optional, if your code is open source, we can track activity): N/A

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/konverter exports TVL: 
        
 
 
    wemix                     529.84 k
    
    total                    529.84 k

**Comment by llamatester** [comment]
The adapter at projects/konverter exports TVL: 
        
 
 
    wemix                     226.88 k
    
    total                    226.88 k

**Comment by llamatester** [comment]
The adapter at projects/konverter exports TVL: 
        
 
 
    wemix                     22.70 k
    
    total                    22.70 k

**Comment by g1nt0ki** [comment]
@WemadeDeFiDev tvl lower for two reasons, I skipped 3Pool tvl being included in  WCD pool, as underlying token tvl is already counted. Right now WCD is not priced by by system, can you try to get it listed on coingecko?

**Comment by WemadeDeFiDev** [comment]
@g1nt0ki Thank you for your explanation.
We are applied for coingecko listing and waiting for the result.

**Pull request merged**
