### PR TITLE
Add duckpools

### PR DESCRIPTION
**Pull request by TanBeige**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Logo (High resolution, will be shown with rounded borders):
https://cdn.discordapp.com/attachments/998405262245363815/1135745392999415858/quackslogo_1.png
quackslogo_1

##### Short Description (to be shown on DefiLlama):
Decentralized lending platform built on Ergo featuring lending pools, algorithmic interest rates, overcollateralized loans and leveraged borrowing.

##### Token address and ticker if any:
089990451bb430f05a85f4ef3bcb6ebf852b3d6ee68d86d78658b9ccef20074f
$QUACKS

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/duckpools.js: 
        
 
  
    
    
    ReferenceError: value is not defined
    Truncated error stack:
    
        at duckpoolsTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/duckpools.js:7:32)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by llamatester** [comment]
Error while running adapter at projects/duckpools.js: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by llamatester** [comment]
The adapter at projects/duckpools.js exports TVL: 
        
 
 
    ergo                      18.81 k
    
    total                    18.81 k

**Comment by llamatester** [comment]
Error while running adapter at projects/duckpools.js: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by llamatester** [comment]
The adapter at projects/duckpools.js exports TVL: 
        
 
 
    ergo                      266.07 k
    
    total                    266.07 k

**Comment by llamatester** [comment]
The adapter at projects/duckpools.js exports TVL: 
        
 
 
    ergo                      82.35 k
    
    total                    82.35 k

**Comment by llamatester** [comment]
The adapter at projects/duckpools.js exports TVL: 
        
 
 
    ergo                      82.35 k
    
    total                    82.35 k

**Comment by llamatester** [comment]
The adapter at projects/duckpools.js exports TVL: 
        
 
 
    ergo                      2.33 k
    
    total                    2.33 k

**Comment by llamatester** [comment]
The adapter at projects/duckpools.js exports TVL: 
        
 
 
    ergo                      676.6542138955901
    
    total                    676.6542138955901

**Comment by llamatester** [comment]
The adapter at projects/duckpools.js exports TVL: 
        
 
 
    ergo                      18.69 k
    
    total                    18.69 k

**Comment by llamatester** [comment]
The adapter at projects/duckpools.js exports TVL: 
        
 
 
    ergo                      104.05 k
    
    total                    104.05 k

**Comment by llamatester** [comment]
The adapter at projects/duckpools.js exports TVL: 
        
 
 
    ergo                      138.61 k
    
    total                    138.61 k

**Comment by TanBeige** [comment]
We're good to go now!

**Comment by g1nt0ki** [comment]
hi @TanBeige thanks for the PR, looks good, is there some way we can query for borrowed amount as well?

**Comment by TanBeige** [comment]
Hey @g1nt0ki, no problem. We will be adding borrowed amount eventually, not sure when yet.

**Pull request merged**
