### PR TITLE
Evaluation of STSW-lBTC pool not based on market prices

### PR DESCRIPTION
**Pull request by friedger**
There is only a tiny market for lBTC or STSW, see for example https://coinmarketcap.com/exchanges/stackswap/

##### List of audit links if any:
https://coinmarketcap.com/exchanges/stackswap/

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/stackswap.js exports TVL: 
        
 
 
    
    total                    1.28 M

**Comment by waynebruce0x** [comment]
This change seems to decrease TVL significantly - is that expected?

**Comment by friedger** [comment]
That is expected.
Note, that I am not project owner, just a caring user.

**Comment by friedger** [comment]
The numbers went into a report that goes a little viral: https://twitter.com/SarahGG9938/status/1539335215973249024

**Comment by 0xngmi** [comment]
what is lucid bitcoin?

**Comment by 0xngmi** [comment]
btw we are investigating this

**Comment by Rapha-btc** [comment]
Concerns raised by Sarah-toshi seem valid: why backing a vault using governance tokens, this is similar to Terra LUNA... why not changing this with collateral such as STX or BTC? changing this even at a loss

hard decisions right in the LT is the way to go!

**Pull request merged**
