### PR TITLE
update touch.fan tvl

### PR DESCRIPTION
**Pull request by TouchFan**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Touch.fan

##### Twitter Link:
https://twitter.com/TouchFanGlobal

##### Website Link:
https://www.touch.fan/

##### Logo (High resolution, will be shown with rounded borders):
https://app.touch.fan/favicon.png

##### Chain:
zkSync Era

##### Short Description (to be shown on DefiLlama):
TOUCH your favorite celebrity

##### Token address and ticker if any:
0x9842114F1d9c5286A6b8e23cF0D8142DAb2B3E9b
0xB075F49F4Bea5204d22B42E8d442e8E9e3400AF8

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Sofi

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/TouchFan/TouchFan

### CODE REVIEW

**Comment by g1nt0ki** [comment]
no clue why you closed and put up the exact same PR: https://github.com/DefiLlama/DefiLlama-Adapters/pull/8179

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
.

**Comment by TouchFan** [comment]
How should I change it now?

**Comment by g1nt0ki** [comment]
this PR includes your changes? https://github.com/DefiLlama/DefiLlama-Adapters/pull/8183/files 

or is it missing something?

**Comment by TouchFan** [comment]
Why should I modify my code? Does it not comply with the regulations? My lp value has not been counted.

**Comment by TouchFan** [comment]
image

**Comment by TouchFan** [comment]
Can I add the total value of LP to my tvl?

**Pull request closed without merging**
