### PR TITLE
create syde adapter

### PR DESCRIPTION
**Pull request by fivestarsfi**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Syde

##### Twitter Link:
https://x.com/sydefi

##### Website Link:
https://app.syde.fi/

##### Logo (High resolution, will be shown with rounded borders):
https://github.com/fivestarsfi/syde-logo

##### Current TVL:
None
the launch of Mainnet took place today

##### Treasury Addresses (if the protocol has treasury)
None

##### Chain:
TON

##### Short Description (to be shown on DefiLlama):
This is the first synthetic derivatives protocol on the TON blockchain

##### Token address and ticker if any:
current mainnet version have three synt pools:
Syde Btc Pool - EQA2J0WCTdYdG-XeyMpPBTeu2dWB2f0oFiV4KVRfV0gewF4E
Syde Eth Pool  - EQD-7ycFO3yeh0EeT2wgXoOQmu64rdDBXqGm4nHDInPfCxJG
Syde Eur Pool - EQDXvkuKPZahcTDRHSybwiU0E5VpiGFP2QS2iHr082JmtTT9

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Synthetics

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Pyth
##### Implementation Details: Briefly describe how the oracle is integrated into your project:
Prices are pulled out of wormhole (from pyth pusher in wormhole network) and verified completely on the chain directly on the smart-contract. It turns out that the security of these prices is provided by 19 keys of wormhole validators.
##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
https://x.com/sydefi/status/1854211051341918254
##### methodology (what is being counted as tvl, how is tvl being calculated):
Amount of usd provided as collateral for minted assets (300usd needed to mint 100usd worth of asset, as c-ratio is 300%)

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/sydefi

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/syde exports TVL: 
        
 
 
    ton                       15
    
    total                    15.395417199679999

**Comment by g1nt0ki** [comment]
@fivestarsfi thanks for the PR, can you fill in the projects in the PR description

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
.

**Comment by fivestarsfi** [comment]
> @fivestarsfi thanks for the PR, can you fill in the projects in the PR description

hello! i'm sorry for answering so late. I have updated the PR description

**Pull request merged**
