### PR TITLE
Giveth TVL Adapter

### PR DESCRIPTION
**Pull request by mateodaza**
Creates Giveth Adapter

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/giveth exports TVL: 
        
 
 
    xdai-pool2                88.77 k
    ethereum-staking          112.77 k
    xdai-staking              874.47 k
    xdai                      963.70 k
    ethereum                  156.01 k
    ethereum-pool2            43.17 k
    pool2                     131.94 k
    staking                   987.24 k
    
    total                    1.12 M

**Comment by realdealshaman** [comment]
Hey, @mateodaza thank you for the PR. I reviewed it and I see that staking and pool2 amounts are also being counted into the regular tvl export. We need to change the tvl export to "tvl: ()=>({})" on each chain, this will still allow staking and pool2 to be displayed when the staking and pool2 toggles are used but prevents double-counting. I can merge the PR once it is updated with the changes mentioned

**Comment by mateodaza** [comment]
@realdealshaman thanks for your feedback! now it's solved :)

**Comment by llamatester** [comment]
The adapter at projects/giveth exports TVL: 
        
 
 
    ethereum                  0
    xdai                      0
    xdai-staking              881.07 k
    xdai-pool2                88.97 k
    ethereum-staking          113.61 k
    ethereum-pool2            43.49 k
    staking                   994.68 k
    pool2                     132.46 k
    
    total                    0

**Comment by mateodaza** [comment]
Thanks a lot for merging this @realdealshaman, I have a question

I can see the values of staking and pool2 in there but the TVL in general doesn't show anything, do you think it's a better idea to sum both amounts in the tvl function and remove staking and pool2, so the graph looks better and not a "0" like this?


image

**Comment by realdealshaman** [comment]
you have to check the staking and pool2 options to toggle on that type of TVL
we have some info on why it is separated here: https://github.com/DefiLlama/DefiLlama-Adapters/discussions/438

**Pull request merged**
