### PR TITLE
Add Ethos Reserve V2 and V2.1 TVL

### PR DESCRIPTION
**Pull request by Kquach12**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/ethos exports TVL: 
        
 
 
    optimism-pool2            1.38 M
    optimism                  8.05 M
    pool2                     1.38 M
    
    total                    8.05 M

**Comment by g1nt0ki** [comment]
@Kquach12 thanks for the PR, I refactored the code a bit here, why is the balance on the pool lower than `getEntireSystemColl`, collaterals dont move out of pool right? 

https://github.com/DefiLlama/DefiLlama-Adapters/pull/8640

**Comment by Kquach12** [comment]
> @Kquach12 thanks for the PR, I refactored the code a bit here, why is the balance on the pool lower than `getEntireSystemColl`, collaterals dont move out of pool right?
> 
> #8640

@g1nt0ki  a portion of the pool's deposited collateral is moved into a collateral/version specific vault. Currently only the Ethos V1 vaults are active, so that would explain why the activePool's balance is less than `getEntireSystemColl`

**Comment by g1nt0ki** [comment]
> > @Kquach12 thanks for the PR, I refactored the code a bit here, why is the balance on the pool lower than `getEntireSystemColl`, collaterals dont move out of pool right?
> > #8640
> 
> @g1nt0ki a portion of the pool's deposited collateral is moved into a collateral/version specific vault. Currently only the Ethos V1 vaults are active, so that would explain why the activePool's balance is less than `getEntireSystemColl`. I had a look at your refactor, and I believe that if you want to stick with checking the activePool's balance instead of `getEntireSystemColl`, I can also provide the Ethos specific vault contracts as well so you can get the full deposited collateral balance.

yeah, thought it was something like that, can you share the vault contracts, I will add it.

**Comment by Kquach12** [comment]
> > > @Kquach12 thanks for the PR, I refactored the code a bit here, why is the balance on the pool lower than `getEntireSystemColl`, collaterals dont move out of pool right?
> > > #8640
> > 
> > 
> > @g1nt0ki a portion of the pool's deposited collateral is moved into a collateral/version specific vault. Currently only the Ethos V1 vaults are active, so that would explain why the activePool's balance is less than `getEntireSystemColl`. I had a look at your refactor, and I believe that if you want to stick with checking the activePool's balance instead of `getEntireSystemColl`, I can also provide the Ethos specific vault contracts as well so you can get the full deposited collateral balance.
> 
> yeah, thought it was something like that, can you share the vault contracts, I will add it.

For sure, here they are:

V1
- wETH: 0x1225c53F510877074d0D1Bace26C4f0581c24cF7
- wBTC: 0xef82200DC96a14af76f5fB7f27DbaDB5228f6A0C
- OP: 0x6938b5b43b281bF24202437b86bbd2866a79cF6C

V2
- wETH: 0x01Cd26dD056671DED555314d43841d8AaaBC72e3
- wBTC:  0x8669CC362aa0AcB2b15423090B28acdc89163e84

V2.1
- wETH: 0x7c09733834873b1FDB8A70c19eE1A514023f74f9
- wBTC: 0xbb341D8249c1C747708D4e6F7Cd967A2479CAD75
- wstETH: 0xA70266C8F8Cf33647dcFEE763961aFf418D9E1E4


Thanks for the help!

**Comment by g1nt0ki** [comment]
@Kquach12 thanks for the info, I have included it in my PR

**Pull request closed without merging**
