### PR TITLE
add DTX tvl

### PR DESCRIPTION
**Pull request by dtx-devs**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Short Description (to be shown on DefiLlama):
DTX is a decentralized perpetual exchange built with Blast native yield, supporting 100+ crypto markets with up to 100x leverage. 

Unlike order book systems, DTX's unique synthetic architecture guarantees a seamless trading experience for traders by eliminating slippage and ensuring guaranteed order execution. Additionally, it offers flexibility in collateral usage and market-making while simultaneously maximizing capital efficiency for LPs.

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
https://0xdtx.medium.com/introducing-dtx-a-trading-eden-for-defi-degens-b620c9c993ac
##### methodology (what is being counted as tvl, how is tvl being calculated):
These liquidity pools are designed as single-asset vaults following the ERC4626 standard.And it calculate by vault's total assets LP deposited and provided

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/dtx-trade/

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@dtx-devs thanks for the PR

**Comment by llamatester** [comment]
The adapter at projects/dtx exports TVL: 
        
 
 
    blast                     5.45 M
    
    total                    5.45 M

**Comment by Define101** [comment]
@dtx-devs 
"When a user places an order, we query the PYTH contract for the price of the desired token. Once the price is verified, we execute the order at the specified price."

What is the contract address please

**Comment by dtx-devs** [comment]
> @dtx-devs "When a user places an order, we query the PYTH contract for the price of the desired token. Once the price is verified, we execute the order at the specified price."
> 
> What is the contract address please

0x69633B5adA326Ba7a782a4c8ac69E812619414C2

**Pull request merged**
