### PR TITLE
created a creo TVL adapter

### PR DESCRIPTION
**Pull request by grigorevPavel**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Current TVL: 

[https://bscscan.com/token/0x9521728bf66a867bc65a93ece4a543d817871eb7?a=0x077bd3104413c555aa985a585ce9d2174349ddc3](https://bscscan.com/token/0x9521728bf66a867bc65a93ece4a543d817871eb7?a=0x077bd3104413c555aa985a585ce9d2174349ddc3)

##### Treasury Addresses (if the protocol has treasury)

[https://bscscan.com/address/0x9521728bf66a867bc65a93ece4a543d817871eb7](https://bscscan.com/address/0x9521728bf66a867bc65a93ece4a543d817871eb7)

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): 

[https://www.coingecko.com/en/coins/creo-engine](https://www.coingecko.com/en/coins/creo-engine)

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): 

[https://www.coingecko.com/en/coins/creo-engine](https://coinmarketcap.com/currencies/creo-engine/)

##### Short Description (to be shown on DefiLlama):

Connecting worlds in a one-size-fits-all gaming hub & leveling up web3 gaming experience for your benefit

##### Token address and ticker if any:

0x9521728bF66a867BC65A93Ece4a543D817871Eb7

**$CREO** 

##### methodology (what is being counted as tvl, how is tvl being calculated): 

TVL counted from the staking contract

##### Github org/user (Optional, if your code is open source, we can track activity): Open source

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/creo exports TVL: 
        
 
 
    bsc                       0
    bsc-vesting               49.77 M
    bsc-staking               2.56 M
    vesting                   49.77 M
    staking                   2.56 M
    
    total                    0

**Comment by realdealshaman** [comment]
Hey @grigorevPavel thanks for the pr, can you tell me a bit more about the vesting portion? are those tokens locked on UNCX? or where they deposited there using your platform?

**Comment by grigorevPavel** [comment]
> Hey @grigorevPavel thanks for the pr, can you tell me a bit more about the vesting portion? are those tokens locked on UNCX? or where they deposited there using your platform?
Hello, @realdealshaman. We are interested if is everything clear with our answers for you, or do we have to clarify smth else?

**Comment by g1nt0ki** [comment]
I think we need to remove the vesting tvl as, the contract is created/maintained by UNCX team, so tvl belongs to them

**Comment by grigorevPavel** [comment]
> I think we need to remove the vesting tvl as, the contract is created/maintained by UNCX team, so tvl belongs to them

@g1nt0ki Can we remove Vesting TVL adapter completely for now (and just leave staking) in this PR?

**Comment by llamatester** [comment]
The adapter at projects/creo exports TVL: 
        
 
 
    bsc                       0
    bsc-staking               3.42 M
    staking                   3.42 M
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/creo exports TVL: 
        
 
 
    bsc                       0
    bsc-staking               3.43 M
    staking                   3.43 M
    
    total                    0

**Comment by grigorevPavel** [comment]
We have removed all the code connected with Vesting TVL data. Is everything ok for you now? Could you please check the recent changes in this PR :)

**Comment by grigorevPavel** [comment]
@g1nt0ki We have recently updated the comments (description form) in order to remove all vesting info.

**Pull request merged**
