### PR TITLE
Based Finance folder created, added main reward pool tvl, boardroom tvl.

### PR DESCRIPTION
**Pull request by ilyn11**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/basedfinance exports TVL: 
        
 
 
    fantom                    0
    fantom-pool2              196.29 k
    fantom-staking            83.64 k
    pool2                     196.29 k
    staking                   83.64 k
    
    total                    0

**Comment by BasedFinance** [comment]
Name (to be shown on DefiLlama):
Based Next Generation

Twitter Link:
https://twitter.com/BasedDEFI

List of audit links if any:
https://obeliskauditing.com/audits/based3 , https://obeliskauditing.com/audits/based2

Website Link:
https://next-gen.basedfinance.io/

Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
smelt
obol

Current TVL
$1,004,000

Chain:
FTM

Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
obol, smelt

Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

Short Description (to be shown on DefiLlama):
BASED Next Generation protocol is the first pegless seigniorage protocol exploring DeFi on the FTM Network. We are introducing innovative yield strategies whilst providing inclusivity for Based Finance (V1), that successfully finished emissions. Based Next Gen is a multi-token protocol that consists of the following tokens: $OBOL - PEGLESS token with elastic supply. $SMELT - protocol’s underlying Perpetual Print (PP) mechanism emitting OBOL.

Token address and ticker if any:
Obol - 0x1539C63037D95f84A5981F96e43850d1451b6216
Smelt - 0x141FaA507855E56396EAdBD25EC82656755CD61e

Category (full list at https://defillama.com/categories) *Please choose only one:
Yield

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
NODES Oracle - 0x5E92ccb0Bd8071B9793f23eB4D7F3b818aE59536
Chainlink Oracle - 0xf4766552D15AE4d256Ad41B6cf2933482B0680dc

forkedFrom (Does your project originate from another project):
BasedFinance

methodology (what is being counted as tvl, how is tvl being calculated):
(what is counted as tvl, how tvl is calculated): Tvl is calculated from   BshareRewardPool, Acropolis, SmeltRewardPool, Boardroom, Node Contracts, Prometheus NFT pool.

**Comment by llamatester** [comment]
The adapter at projects/basedfinance exports TVL: 
        
 
 
    fantom-pool2              11.54 k
    fantom-staking            78.68 k
    fantom                    931.84 k
    pool2                     11.54 k
    staking                   78.68 k
    
    total                    931.84 k

**Comment by realdealshaman** [comment]
@ilyn11 does this also include the tvl of v1, if so, we should only be updating the existing adapter, we can rebrand and update the logo and other bits of info on the original listing so that the new info is what shows

**Comment by BasedFinance** [comment]
> @ilyn11 does this also include the tvl of v1, if so, we should only be updating the existing adapter, we can rebrand and update the logo and other bits of info on the original listing so that the new info is what shows

Can we have our tvls of both protocols combined in any way? Since its our ecosystem of products.

**Comment by BasedFinance** [comment]
@realdealshaman Can we have our tvls of both protocols combined in any way? Since its our ecosystem of products.

**Comment by llamatester** [comment]
The adapter at projects/based-finance exports TVL: 
        
 
 
    fantom                    0
    fantom-pool2              458.40 k
    fantom-staking            134.46 k
    fantom-treasury           287.27 k
    pool2                     458.40 k
    staking                   134.46 k
    treasury                  287.27 k
    
    total                    0

**Pull request merged**
