### PR TITLE
update Iron Finance TVL data

### PR DESCRIPTION
**Pull request by oramis1008**

### CODE REVIEW

**Comment by 0xngmi** [comment]
Thanks! We were already working on fixing your TVL but I hadn't merged that PR yet since there were some merged conflicts.

**Comment by 0xngmi** [comment]
Btw, I saw that you've included some pool2 LP tokens, we generally don't include these so later I'll go through this and propose a few changes. However since this is quite high priority I'll go ahead and push this live asap.

**Comment by oramis1008** [comment]
Thank you. Please let us know what should be changed and we will update it accordingly.

**Comment by 0xngmi** [comment]
For other projects we avoid including pool2 LPs (LPs with the governance token) on the TVL, so in the case of Iron I imagine this would mean removing all the LPs of TITAN and STEEL

**Pull request merged**
