### PR TITLE
Rumi tvl adapter

### PR DESCRIPTION
**Pull request by aloksGithub**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Rumi Finance

##### Twitter Link:
https://twitter.com/RumiFinance

##### List of audit links if any:
https://hacken.io/audits/rumi-finance/

##### Website Link:
https://app.rumi.finance/

##### Logo (High resolution, will be shown with rounded borders):
https://www.notion.so/image/https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2F3b2f3888-85fa-4074-9df4-12f724559e44%2Faa2fffaf-ed91-425e-a856-83296623e66f%2FColor_logo_with_background.png?table=block&id=479862f4-3f46-4107-80d4-52685d6b040f&spaceId=3b2f3888-85fa-4074-9df4-12f724559e44&width=2000&userId=c5eaa9f1-3d5a-4635-bcd3-03496e73fd32&cache=v2

##### Current TVL:
$76,706

##### Treasury Addresses (if the protocol has treasury)
0xF262Db35f1caC702550A761a7b1B5feaA1b918b6

##### Chain:
Arbitrum

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): 
rumi-finance

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): 
24564

##### Short Description (to be shown on DefiLlama):
Automated Investment strategies bringing superior yields with robust risk management

##### Token address and ticker if any:
Token Not live

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield Aggregator

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL combines the dollar value of the funds that have been deposited on the Rumi Single asset lending vaults and the funds that investors have deposited into Rumi strategies

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/Rumi exports TVL: 
        
 
 
    arbitrum                  76.69 k
    
    total                    76.69 k

**Comment by llamatester** [comment]
The adapter at projects/rumi exports TVL: 
        
 
 
    arbitrum                  72.93 k
    
    total                    72.93 k

**Comment by g1nt0ki** [comment]
hi @aloksGithub 
Thanks for the PR, I have updated code to remove borrowed funds from tvl. The strategies have only about 1.7k abnd borrowed amount is like 3k, is the diff because of the leverage?

**Comment by llamatester** [comment]
The adapter at projects/orderly-network exports TVL: 
        
 
 
    arbitrum                  1.24 M
    near                      8.13 M
    
    total                    9.37 M

**Comment by llamatester** [comment]
The adapter at projects/rumi exports TVL: 
        
 
 
    arbitrum                  72.78 k
    
    total                    72.78 k

**Comment by aloksGithub** [comment]
Hi @g1nt0ki
The balance returned by the strategies already excludes the borrowed tokens. Right now, the TVL is excluding the funds in the lending vault. Could you revert back to commit fecc677?

**Comment by g1nt0ki** [comment]
reverted change here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/f5e5489df44f033b779fbbc0daa9a629584c5d7d

**Pull request merged**
