### PR TITLE
Add TVL trackers for Sobal DEX on Neon EVM

### PR DESCRIPTION
**Pull request by joehquak**
##### Name (to be shown on DefiLlama):
Sobal

##### Twitter Link:
https://www.twitter.com/sobalfi

##### Website Link:
https://sobal.fi

##### Logo (High resolution, will be shown with rounded borders):
http://app.sobal.fi/images/logos/logo512.png

##### Current TVL:
$30500~

##### Chain:
Neon EVM - 245022934

##### Short Description (to be shown on DefiLlama):
Sobal is a flexible and powerful decentralised exchange residing on Neon EVM within the Solana chain!

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### forkedFrom (Does your project originate from another project):
Balancer

##### methodology (what is being counted as tvl, how is tvl being calculated):
Tokens held in the central Vault for all liquidity pools.

##### Github org/user (Optional, if your code is open source, we can track activity):
Sobal

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/sobal exports TVL: 
        
 
 
    neon_evm                  0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/sobal exports TVL: 
        
 
 
    neon_evm                  29.74 k
    
    total                    29.74 k

**Comment by joehquak** [comment]
In case reference is needed for the token mappings, this is the official tokenlist from NeonEVM

https://raw.githubusercontent.com/neonlabsorg/token-list/main/tokenlist.json

**Comment by llamatester** [comment]
The adapter at projects/sobal exports TVL: 
        
 
 
    neon_evm                  26.95 k
    
    total                    26.95 k

**Comment by g1nt0ki** [comment]
> In case reference is needed for the token mappings, this is the official tokenlist from NeonEVM
> 
> https://raw.githubusercontent.com/neonlabsorg/token-list/main/tokenlist.json

thanks, this was really helpful. I have refactored your code a bit and removed the mapping here as I have added it server side

**Comment by joehquak** [comment]
Awesome! Many thanks @g1nt0ki great catch there 😁

**Pull request merged**
