### PR TITLE
add hats.finance

### PR DESCRIPTION
**Pull request by shayzluf**
**NOTE**

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
Hats logo darkblue bg

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/hats exports TVL: 
        
 
 
    ethereum                  1.88 M
    
    total                    1.88 M

**Comment by llamatester** [comment]
The adapter at projects/hats exports TVL: 
        
 
 
    ethereum-staking          0
    ethereum-pool2            0
    ethereum-masterchef       1.87 M
    ethereum                  1.87 M
    staking                   0
    pool2                     0
    masterchef                1.87 M
    
    total                    1.87 M

**Comment by shayzluf** [comment]
@g1nt0ki any reason the total on [defillama](https://defillama.com/protocol/hats.finance) is double then the result here?
Screen Shot 2023-01-24 at 21 22 08

**Comment by g1nt0ki** [comment]
yeah, it does not make sense, looking into it

**Comment by shayzluf** [comment]
> yeah, it does not make sense, looking into it

thanks

**Comment by g1nt0ki** [comment]
I think the bug is, it is counting masterchef key under tvl, will fix it soon

**Pull request merged**
