### PR TITLE
improve compoundExports performance

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/channels: 
        
 
  
    
    
    Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (code=CALL_EXCEPTION, version=providers/5.6.5)
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:652:52
        at Array.forEach (<anonymous>)

**Comment by llamatester** [comment]
Error while running adapter at projects/channels: 
        
 
  
    
    
    Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (code=CALL_EXCEPTION, version=providers/5.6.5)
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:652:52
        at Array.forEach (<anonymous>)

**Comment by llamatester** [comment]
The adapter at projects/channels exports TVL: 
        
 
 
    arbitrum-borrowed         8.41 k
    bsc-borrowed              76.50 k
    arbitrum                  60.33 k
    bsc                       552.95 k
    heco-borrowed             3.47 M
    heco                      30.49 M
    borrowed                  3.55 M
    
    total                    31.10 M

**Comment by llamatester** [comment]
The adapter at projects/neku exports TVL: 
        
 
 
    bsc-borrowed              0.066524779288
    bsc                       8.19 k
    moonriver-borrowed        50.21 k
    moonriver                 187.86 k
    arbitrum-borrowed         177.05 k
    arbitrum                  121.81 k
    borrowed                  227.26 k
    
    total                    317.85 k

**Comment by llamatester** [comment]
The adapter at projects/ram.js exports TVL: 
        
 
 
    thundercore               1.21 M
    thundercore-borrowed      1.89 M
    borrowed                  1.89 M
    
    total                    1.21 M

**Comment by llamatester** [comment]
The adapter at projects/wepiggy.js exports TVL: 
        
 
 
    optimism-borrowed         311.85 k
    optimism                  999.09 k
    moonriver-borrowed        24.30 k
    bsc                       2.24 M
    oasis                     62.54 k
    polygon-borrowed          192.79 k
    moonriver                 46.08 k
    heco-borrowed             21.44 k
    aurora                    40.48 k
    polygon                   500.30 k
    arbitrum-borrowed         1.90 M
    bsc-borrowed              907.37 k
    oasis-borrowed            39.10 k
    aurora-borrowed           17.04 k
    arbitrum                  1.78 M
    heco                      47.25 k
    ethereum-borrowed         9.94 M
    harmony-borrowed          44.09 k
    harmony                   138.88 k
    ethereum                  9.38 M
    okexchain                 2.42 M
    okexchain-borrowed        703.02 k
    borrowed                  14.10 M
    
    total                    17.66 M

**Comment by g1nt0ki** [comment]
I changed nothing in the code, but it just works the third time, think heco rpc rugs sometimes

**Pull request merged**
