### PR TITLE
Add Bentobox adapter and update Trident subgraphs

### PR DESCRIPTION
**Pull request by HHK-ETH**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Sushi BentoBox

##### Twitter Link:
https://twitter.com/SushiSwap

##### Website Link:
https://www.sushi.com/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
Same as other sushi adapters

##### Current TVL:
800m (methodology to be confirmed)

##### Chain:
"ethereum", "polygon", "fantom", "bsc", "avax", "arbitrum", "optimism", "xdai", "harmony", "moonbeam", "moonriver", "celo"

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
sushi

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
sushiswap

##### Short Description (to be shown on DefiLlama):
BentoBox is a token vault that generates yield for the capital deposited into it, protocols can be built on top such as Kashi, Trident, Limit Order and Furo.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL of BentoBox consist of tokens deposited into it minus Trident, Furo and Kashi TVL since they are built on it.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/sushiswap-kashi: 
        
 
  
    
    
    Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="toAmount(address,uint256,bool)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    Truncated error stack:
        at Interface.decodeFunctionResult (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/abi/lib/interface.js:388:23)
        at runMicrotasks (<anonymous>)

**Comment by HHK-ETH** [comment]
Results for Bentobox:

------ TVL ------
moonriver                 0
moonbeam                  0.49845
xdai                      16.59 k
fantom                    473.25 k
harmony                   0
avax                      433.49 k
optimism                  2.24 k
celo                      0
bsc                       12.74 k
ethereum                  703.63 M
arbitrum                  118.18 M
polygon                   570.50 k

total                    823.32 M 


Llamatester is having an issue with kashi, see this pr: https://github.com/DefiLlama/DefiLlama-Adapters/pull/3979

**Comment by llamatester** [comment]
Error while running adapter at projects/sushiswap-kashi: 
        
 
  
    
    
    Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="toAmount(address,uint256,bool)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    Truncated error stack:
        at Interface.decodeFunctionResult (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/abi/lib/interface.js:388:23)
        at runMicrotasks (<anonymous>)

**Comment by llamatester** [comment]
The adapter at projects/sushiswap-kashi exports TVL: 
        
 
 
    avax-borrowed             53.342277652542165
    avax                      7.71 k
    arbitrum-borrowed         5.37 k
    arbitrum                  52.84 k
    polygon                   215.60 k
    bsc-borrowed              4.17 k
    ethereum-borrowed         285.06 k
    polygon-borrowed          25.84 k
    ethereum                  1.14 M
    bsc                       30.20 k
    borrowed                  320.49 k
    
    total                    1.44 M

**Comment by llamatester** [comment]
The adapter at projects/sushiswap-trident exports TVL: 
        
 
 
    optimism                  64.59 k
    metis                     209.46 k
    kava                      1.10 M
    polygon                   1.85 M
    
    total                    3.23 M

**Comment by llamatester** [comment]
The adapter at projects/sushiswap-bentobox exports TVL: 
        
 
 
    moonriver                 0
    harmony                   0
    fantom                    164.61 k
    avax                      383.09 k
    arbitrum                  3.78 M
    xdai                      16.62 k
    moonbeam                  0.467915
    celo                      0
    bsc                       12.71 k
    ethereum                  243.37 M
    optimism                  2.38 k
    polygon                   582.51 k
    
    total                    248.31 M

**Comment by llamatester** [comment]
The adapter at projects/sushiswap-trident exports TVL: 
        
 
 
    metis                     209.46 k
    kava                      1.11 M
    polygon                   1.84 M
    optimism                  64.25 k
    
    total                    3.23 M

**Comment by llamatester** [comment]
Error while running adapter at projects/sushiswap-bentobox: 
        
 
  
    
    
    Failed to decode `block.number` value: `subgraph QmeriT6YnRYKKBHtZKsxVvHhb8eSKK9FhuMFR8kVpGWVMA has only indexed up to block number 30753857 and data for block number 30753966 is therefore not yet available`
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/graphql-request/dist/index.js:359:31

**Comment by g1nt0ki** [comment]
other than that, minor changes I made were, include block so we can refill history and future proof graph calls with more than 1000 tokens, when I find time, I will try to update other adapters to reduce code duplication

**Comment by Define101** [comment]
Hi guys, just one question. Do you guys prefer Sushiswap Trident or Sushi Trident
image

**Comment by Define101** [comment]
Since all the others are just Sushi "something"

**Comment by HHK-ETH** [comment]
> > The adapter at projects/sushiswap-bentobox exports TVL:
> > ```
> > moonriver                 0
> > harmony                   0
> > fantom                    164.61 k
> > avax                      383.09 k
> > arbitrum                  3.78 M
> > xdai                      16.62 k
> > moonbeam                  0.467915
> > celo                      0
> > bsc                       12.71 k
> > ethereum                  243.37 M
> > optimism                  2.38 k
> > polygon                   582.51 k
> > 
> > total                    248.31 M 
> > ```
> 
> @HHK-ETH the TVL here is lower because I have blacklisted MIM

Yea sounds good to me, asked the team if they're good with that, will let you know if they have any request.

**Comment by HHK-ETH** [comment]
> Hi guys, just one question. Do you guys prefer Sushiswap Trident or Sushi Trident image

Sushi Trident would be better yea, thanks!

**Comment by Define101** [comment]
Thanks HHK-ETH , btw notice that sushi kashi logo was not showing up. I have made the fix and should be on the website within 1 hour

**Pull request merged**
