### PR TITLE
add yaka finance

### PR DESCRIPTION
**Pull request by FrostStarBook**
##### Short Description (to be shown on DefiLlama):
Yaka Finance is Sei's native liquidity engine, a ve(3,3)-styled DEX and launchpad to drive robust Sei ecosystem growth.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/yakafinance exports TVL: 
        
 
 
    sei                       460.52 k
    
    total                    460.52 k

**Comment by g1nt0ki** [comment]
thanks for the PR

**Comment by FrostStarBook** [comment]
I want to update the logo, do I need to submit a new PR?
Here is the new logo: https://i.ibb.co/x82GWtQG/Yaka-logo-transparent.png

**Comment by realdealshaman** [comment]
Hi @FrostStarBook, I had previously updated it to this logo:
image
let me know if this one is okay, or if you prefere that I use the one above, but it won't be transparent, will have a white background if I use the png

**Pull request merged**
