### PR TITLE
correct own tokens

### PR DESCRIPTION
**Pull request by mabePearl**
**NOTE**
I corrected the list of own tokens.

Pearl as a protocol owns only Pearl token whose address is this one 0xCE1581d7b4bA40176f0e219b2CaC30088Ad50C7A
All the others, none belongs to pearl as a defi exchange.
0xaec9e50e3397f9ddc635c6c429c8c7eca418a143 - arcUSD arcana project under re.al
0x4644066f535ead0cde82d209df78d94572fcbf14 - RWA - re.al network token
0x25ea98ac87a38142561ea70143fd44c4772a16b6 - MORE - stack protocol project.

Pearl is a dex like any other, and none of the above tokens is in our governance. We are mix of UniV3 and Solidly protocol.

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/pearl-v2 exports TVL: 
        
 
 
    real                      1.48 M
    
    total                    1.48 M

**Comment by mabePearl** [comment]
@g1nt0ki I saw that you did migration, if you can check if my PR and explanation make sense.

**Comment by g1nt0ki** [comment]
hi @mabePearl 

The reason I marked them as own tokens is, it is all part of the same ecosystem/liked projects

**Comment by mabePearl** [comment]
Ecosystem yes, but not part of the same project... Pearl is defi exchange, it doesn't care about tokens. It's like blocking USDC on Base...

**Comment by g1nt0ki** [comment]
I will use a different example, if maker the CDP also has an Uni V3 fork, then I wont count the DAI in the uni v3 dex because eth backing it is already counted towards CDP tvl, does that make sense?

**Pull request closed without merging**
