### PR TITLE
Set up Intercroneswap TVL

### PR DESCRIPTION
**Pull request by Monahawk**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Intercroneswap

##### Twitter Link:
https://twitter.com/IntercroneWorld

##### Website Link:
www.intercroneswap.com

##### Chain:
bsc,tron,bittorrent

##### Token address and ticker if any:
•  Chains: 
•  Tron (TRC20) - InterCrone (ICR)
TKqvrVG7a2zJvQ3VysLoiz9ijuMNDehwy7
https://tronscan.io/#/token20/TKqvrVG7a2zJvQ3VysLoiz9ijuMNDehwy7

•  BSC (BSC20) InterCrone (ICR) 
0x4f60Ad2c684296458b12053c0EF402e162971e00 
https://bscscan.com/token/0x4f60ad2c684296458b12053c0ef402e162971e00

•  BTTC (BRC20) 
InterCrone (ICR_b)
0x252CD063341a1A47933086b93f85417C09C54aec 
https://bttcscan.com/token/0x252cd063341a1a47933086b93f85417c09c54aec

InterCrone (ICR_t)
0x096C64d79A85C8FD2E963c4aBD9373301D2cf801 
https://bttcscan.com/token/0x096c64d79a85c8fd2e963c4abd9373301d2cf801

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Liquid Staking

##### forkedFrom (Does your project originate from another project):
pancake swap

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/intercroneswap: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'call')
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/abi/index.js:154:82
        at new Promise (<anonymous>)

**Comment by realdealshaman** [comment]
Hi, @Monahawk thanks for the PR. Tron does not use the same abi: 'uint256:allPairsLength', The code for the tron tvl would have to be updated so that it can be reflected correctly

**Comment by llamatester** [comment]
The adapter at projects/intercroneswap exports TVL: 
        
 
 
    tron                      139.32 k
    bsc                       98.97 k
    bittorrent                0.07515001078082086
    
    total                    238.29 k

**Comment by llamatester** [comment]
The adapter at projects/intercroneswap exports TVL: 
        
 
 
    tron                      139.33 k
    bittorrent                0.0751567934768208
    bsc                       98.91 k
    
    total                    238.24 k

**Comment by g1nt0ki** [comment]
@Monahawk thanks for the PR, it is not forgotten, I started refactoring this to be on chain then it blew up: https://github.com/DefiLlama/DefiLlama-Adapters/pull/6310

**Comment by g1nt0ki** [comment]
merged it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/6340

**Pull request closed without merging**
