### PR TITLE
Add Sonic Market, Sonic Market AMM

### PR DESCRIPTION
**Pull request by Dorvin**
### I have submitted two separate projects, so I have labeled each item with "SONIC-MARKET" or "SONIC-MARKET-AMM"(or "BOTH") to indicate which project it pertains to. I would appreciate it if you could review them carefully.

---
##### Name (to be shown on DefiLlama):
"SONIC-MARKET": Sonic Market
"SONIC-MARKET-AMM": Sonic Market AMM

##### Twitter Link:
"BOTH": https://x.com/sonic_market

##### List of audit links if any:
"SONIC-MARKET": https://github.com/Sonic-Market/core/blob/master/audits/Clober_V2.pdf

##### Website Link:
"BOTH": https://www.sonic.market/

##### Logo (High resolution, will be shown with rounded borders):
"BOTH"
"img width="600" alt="Profile(1_1)_whiteSymbol_1200px" src="https://github.com/user-attachments/assets/44a4b490-cd70-4746-acff-5274eae53f18" /"

##### Current TVL:
"SONIC-MARKET"
```
--- sonic ---
S                         0.11615
Total: 0.11615 

--- tvl ---
Total: 0.11615 

------ TVL ------
sonic                     0

total                    0.11615 
```

"SONIC-MARKET-AMM"
```
--- sonic ---
wS                        7.96 k
Total: 7.96 k 

--- tvl ---
wS                        7.96 k
Total: 7.96 k 

------ TVL ------
sonic                     7.96 k

total                    7.96 k 
```

##### Chain:
"BOTH"
- sonic

##### Short Description (to be shown on DefiLlama):
"SONIC-MARKET": Sonic Market is a fully on-chain orderbook DEX protocol built on Sonic, offering instant settlement and trustless trading in a decentralized environment. By leveraging the composability of on-chain infrastructure, it integrates seamlessly with third-party protocols for advanced trading strategies. It provides a highly efficient and customizable trading experience through its innovative use of on-chain central limit orderbooks.
"SONIC-MARKET-AMM": Sonic Market AMM is an automated market maker protocol native to Sonic

##### Category (full list at https://defillama.com/categories) *Please choose only one:
"BOTH": Dexes

##### forkedFrom (Does your project originate from another project):
"SONIC-MARKET-AMM": Uniswap V2

##### methodology (what is being counted as tvl, how is tvl being calculated):
"SONIC-MARKET": TVL consists of assets deposited into the Sonic Market Book Manager contract
"SONIC-MARKET-AMM": TVL consists of assets deposited into the Sonic Market AMM contract

##### Github org/user (Optional, if your code is open source, we can track activity):
"BOTH": https://github.com/Sonic-Market

### CODE REVIEW

**Comment by llamabutler** [comment]
The adapter at projects/sonic-market-cpmm exports TVL: 
        
 
 
    sonic                     7.96 k
    
    total                    7.96 k

**Comment by llamabutler** [comment]
The adapter at projects/sonic-market exports TVL: 
        
 
 
    sonic                     0
    
    total                    0.11615

**Comment by llamabutler** [comment]
The adapter at projects/sonic-market-amm exports TVL: 
        
 
 
    sonic                     7.89 k
    
    total                    7.89 k

**Comment by llamabutler** [comment]
The adapter at projects/sonic-market exports TVL: 
        
 
 
    sonic                     0
    
    total                    0.11513999999999999

**Comment by g1nt0ki** [comment]
thanks for the PR, refactored and merged here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/12778

**Pull request closed without merging**
