### PR TITLE
feat: add STRK staking to zkLend

### PR DESCRIPTION
**Pull request by 9oelM**
[zkLend has launched STRK staking](https://x.com/zkLend/status/1861007513220719077).
This PR adds STRK staked amount to the code.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/zklend exports TVL: 
        
 
 
    starknet                  36.89 M
    starknet-staking          34.70 M
    staking                   34.70 M
    starknet-borrowed         15.42 M
    borrowed                  15.42 M
    
    total                    36.89 M

**Comment by 9oelM** [comment]
@g1nt0ki thanks for the review. So it will have to be a new folder right? will push a commit shortly

**Comment by llamatester** [comment]
The adapter at projects/zklend-strk-staking exports TVL: 
        
 
 
    starknet                  35.93 M
    
    total                    35.93 M

**Comment by g1nt0ki** [comment]
looks good, thanks

**Pull request merged**
