### PR TITLE
feat: adds arbitrum chain info

### PR DESCRIPTION
**Pull request by vhawk19**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/timeswap-v2 exports TVL: 
        
 
 
    polygon                   136.15 k
    ethereum                  127.21 k
    arbitrum                  125.46 k
    
    total                    388.83 k

**Comment by g1nt0ki** [comment]
Please think about the reviewer before formatting file. Instead of reviewing one line, I have to review entire file :(

doesnt help when one needs to be paranoid about changes to the repo.

**Comment by vhawk19** [comment]
Apologies, will take care of this from next time onwards.

**Comment by g1nt0ki** [comment]
:pray: thanks

**Pull request merged**
