### PR TITLE
Smartcredit tvl

### PR DESCRIPTION
**Pull request by Astrit11**
##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://smartcredit.io/file/2021/05/smartcredit-white.png

##### Short Description (to be shown on DefiLlama):
DeFi fixed-term / fixed-interest loans for the borrowers
DeFi personal fixed income funds for the lenders

##### Token address and ticker if any:
https://etherscan.io/token/0x72e9d9038ce484ee986fea183f8d8df93f9ada13

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink and TWAP

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL = Total lending amount + collateral locked - borrowed amount

### CODE REVIEW

**Comment by g1nt0ki** [comment]
Hi, 
can you please fill in the details for the PR, I have no clue what I am reviewing

Also, can you use our sdk to make on chain call to compute tvl? we strongly prefer that over others, we go for graphql only when it is very complicated/ tedious.

If you want some help/assistance with your adapter, please post about what chain it is in either here on in our discord and we will help you :)

**Comment by Astrit11** [comment]
Hi,
Sorry,I updated the details please have a look .

Regarding your question,currently we can not compute tvl,currently we do not support it,maybe in the future we can reconsider it.

**Comment by g1nt0ki** [comment]
@astril11 sorry but your app seems to be down, can you look into that

**Comment by llamatester** [comment]
Error while running adapter at projects/smartcredit.js: 
        
 
  
    
    
    ClientError: GraphQL Error (Code: 503): {"response":{"error":"<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>503 Service Unavailable</title>\n</head><body>\n<h1>Service Unavailable</h1>\n<p>The server is temporarily unable to service your\nrequest due to maintenance downtime or capacity\nproblems. Please try again later.</p>\n</body></html>\n","status":503,"headers":{}},"request":{"query":"\n  {\n    getTVL {\n      platformTVL,\n    }\n  }\n  "}}
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/graphql-request/dist/index.js:340:31
        at step (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/graphql-request/dist/index.js:63:23)
        at Object.next (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/graphql-request/dist/index.js:44:53)
        at fulfilled (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/graphql-request/dist/index.js:35:58)
        at processTicksAndRejections (node:internal/process/task_queues:96:5) {
      response: {
        error: '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n' +
          '<html><head>\n' +
          '<title>503 Service Unavailable</title>\n' +
          '</head><body>\n' +
          '<h1>Service Unavailable</h1>\n' +
          '<p>The server is temporarily unable to service your\n' +
          'request due to maintenance downtime or capacity\n' +
          'problems. Please try again later.</p>\n' +
          '</body></html>\n',
        status: 503,
        headers: Headers { [Symbol(map)]: [Object: null prototype] }
      },
      request: {
        query: '\n  {\n    getTVL {\n      platformTVL,\n    }\n  }\n  ',
        variables: undefined
      }
    }

**Comment by Astrit11** [comment]
Hi @g1nt0ki,
Sorry for that guys we did a deployment yesterday,I think it should be all good now.

**Comment by llamatester** [comment]
The adapter at projects/smartcredit.js exports TVL: 
        
 
 
    
    total                    1.32 M

**Comment by g1nt0ki** [comment]
@Astrit11 hi, sorry, but we compute the tvl bit differently, for lending products, tvl is sum of deposited token value - borrowed amount + collateral value
Borrowed amount is exported separately as  'borrowed' export, 

Also, we do not include native tokens in tvl

Lastly, is there a way to fetch the info via on chain calls, we strongly prefer that over 'fetch', this allows us to fetch a value at certain block and reduces our dependency on others, let me know if you need any help with our adapters, or if you give me the abi and how to calculate tvl/fetch info from chain, I can write the adapter :)

**Comment by Astrit11** [comment]
Hi @g1nt0ki,

I updated the tvl calculation but to be honest how to include the borrowed  amount on the export,can you give me an example using fetch?

Regarding native tokens,this is borrowing / lending of native tokens. Would this then be included in TVL if native tokens are borrowed OR lent?

As I mention earlier currently it is very hard to go into on chain calculation.

**Comment by g1nt0ki** [comment]
@Astrit11 I checked with the team regarding this, the issue is native token makes bulk of your tvl

**Comment by Astrit11** [comment]
Hi @g1nt0ki  

We just launched this Release. We introduced the rewards just with this Release, with good rewards for native tokens, which obviously our community prefers to receive (our community did not had this opportunity in the previous Release).

Assets will be transferred from the previous Release into the current Release. It will just take little time to get other assets transferred from the previous Release.

So, we are just in the scale up phase. The twitter announcement should go out by tomorrow (not yet announced on twitter).

**Comment by g1nt0ki** [comment]
@Astrit11 Hi, I looked at your app again, it looks like staking, even in your UI, for smartcredit token you call it "stake" while others say "lend"

I have updated your code a bit to reflect this, if you change to below code, I will approve:

    const { graphQuery } = require('./helper/http')
    const sdk = require('@defillama/sdk')
    const { default: BigNumber } = require('bignumber.js')

    const endPoint = 'https://d2c7awq32ho327.cloudfront.net/graphql'
    const queryBody = '{\n  collateralsStatistics {\n    lockedCollateralAmount\n    lockedCollateralValueInUSD\n    unlockedCollateralAmount\n    unlockedCollateralValueInUSD\n    minCollateralRatio\n    currency {\n      symbol\n      exchangeRate\n      ethAddress\n      decimalPlaces\n    }\n  }\n  underlyingsStatistics {\n    totalBorrowedAmount\n    totalBorrowedValueInUSD\n    totalLendedAmount\n    totalLendedValueInUSD\n    maxAPY\n    minInterestRate\n    currency {\n      symbol\n      exchangeRate\n      ethAddress\n      decimalPlaces\n    }\n  }\n}'
    const SMART_CREDIT = '0x72e9D9038cE484EE986FEa183f8d8Df93f9aDA13'.toLowerCase()

    async function getStats() {
      return graphQuery(endPoint, queryBody)
    }

    function replaceEth(addr) {
      if (addr.toLowerCase() === '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee')
        return '0x0000000000000000000000000000000000000000'
      return addr
    }

    async function tvl() {
      const balances = {}
      const stats = await getStats()
      stats.underlyingsStatistics.forEach(item => {
        if (item.currency.ethAddress.toLowerCase() === SMART_CREDIT) return
        sdk.util.sumSingleBalance(balances, replaceEth(item.currency.ethAddress), BigNumber(item.totalLendedAmount).minus(item.totalBorrowedAmount).toFixed(0))
      })
      stats.collateralsStatistics.forEach(item => {
        sdk.util.sumSingleBalance(balances, replaceEth(item.currency.ethAddress), BigNumber(item.lockedCollateralAmount).plus(item.unlockedCollateralAmount).toFixed(0))
      })
      return balances
    }

    async function staking() {
      const balances = {}
      const stats = await getStats()
      stats.underlyingsStatistics.forEach(item => {
        if (item.currency.ethAddress.toLowerCase() !== SMART_CREDIT) return
        sdk.util.sumSingleBalance(balances, replaceEth(item.currency.ethAddress), BigNumber(item.totalLendedAmount).minus(item.totalBorrowedAmount).toFixed(0))
      })
      return balances
    }

    module.exports = {
      timetravel: false,
      ethereum: {
        tvl,
        staking,
      }
    }

**Comment by Astrit11** [comment]
HI @g1nt0ki ,
First of all I want to thank you for your time!

I will discuss with the team regarding this changes but i have one more question,
With the required changes does it mean that in dashboard we will show this part ex:

------ TVL ------
ethereum                  102.15 k
ethereum-staking          1.40 M
staking                   1.40 M

total                    102.15 k 

And the total tvl will be only 102.15 k  without the staking right?

**Comment by g1nt0ki** [comment]
> HI @g1nt0ki , First of all I want to thank you for your time!
> 
> I will discuss with the team regarding this changes but i have one more question, With the required changes does it mean that in dashboard we will show this part ex:
> 
> ------ TVL ------ ethereum 102.15 k ethereum-staking 1.40 M staking 1.40 M
> 
> total 102.15 k
> 
> And the total tvl will be only 102.15 k without the staking right?

yes, that is correct :)

**Comment by Astrit11** [comment]
> @Astrit11 Hi, I looked at your app again, it looks like staking, even in your UI, for smartcredit token you call it "stake" while others say "lend"
> 
> I have updated your code a bit to reflect this, if you change to below code, I will approve:
> 
> ```
> const { graphQuery } = require('./helper/http')
> const sdk = require('@defillama/sdk')
> const { default: BigNumber } = require('bignumber.js')
> 
> const endPoint = 'https://d2c7awq32ho327.cloudfront.net/graphql'
> const queryBody = '{\n  collateralsStatistics {\n    lockedCollateralAmount\n    lockedCollateralValueInUSD\n    unlockedCollateralAmount\n    unlockedCollateralValueInUSD\n    minCollateralRatio\n    currency {\n      symbol\n      exchangeRate\n      ethAddress\n      decimalPlaces\n    }\n  }\n  underlyingsStatistics {\n    totalBorrowedAmount\n    totalBorrowedValueInUSD\n    totalLendedAmount\n    totalLendedValueInUSD\n    maxAPY\n    minInterestRate\n    currency {\n      symbol\n      exchangeRate\n      ethAddress\n      decimalPlaces\n    }\n  }\n}'
> const SMART_CREDIT = '0x72e9D9038cE484EE986FEa183f8d8Df93f9aDA13'.toLowerCase()
> 
> async function getStats() {
>   return graphQuery(endPoint, queryBody)
> }
> 
> function replaceEth(addr) {
>   if (addr.toLowerCase() === '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee')
>     return '0x0000000000000000000000000000000000000000'
>   return addr
> }
> 
> async function tvl() {
>   const balances = {}
>   const stats = await getStats()
>   stats.underlyingsStatistics.forEach(item => {
>     if (item.currency.ethAddress.toLowerCase() === SMART_CREDIT) return
>     sdk.util.sumSingleBalance(balances, replaceEth(item.currency.ethAddress), BigNumber(item.totalLendedAmount).minus(item.totalBorrowedAmount).toFixed(0))
>   })
>   stats.collateralsStatistics.forEach(item => {
>     sdk.util.sumSingleBalance(balances, replaceEth(item.currency.ethAddress), BigNumber(item.lockedCollateralAmount).plus(item.unlockedCollateralAmount).toFixed(0))
>   })
>   return balances
> }
> 
> async function staking() {
>   const balances = {}
>   const stats = await getStats()
>   stats.underlyingsStatistics.forEach(item => {
>     if (item.currency.ethAddress.toLowerCase() !== SMART_CREDIT) return
>     sdk.util.sumSingleBalance(balances, replaceEth(item.currency.ethAddress), BigNumber(item.totalLendedAmount).minus(item.totalBorrowedAmount).toFixed(0))
>   })
>   return balances
> }
> 
> module.exports = {
>   timetravel: false,
>   ethereum: {
>     tvl,
>     staking,
>   }
> }
> ```

**Comment by llamatester** [comment]
The adapter at projects/smartcredit.js exports TVL: 
        
 
 
    ethereum-staking          1.50 M
    ethereum                  136.87 k
    staking                   1.50 M
    
    total                    136.87 k

**Pull request merged**
