### PR TITLE
[Baseline] - Adapter Update for V2

### PR DESCRIPTION
**Pull request by brightiron**
- Add V2 Contract and include reserves and borrows for v2 in TVL/Borrow calcs

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/baseline exports TVL: 
        
 
 
    blast-borrowed            56.47 M
    borrowed                  56.47 M
    blast                     11.53 M
    
    total                    11.53 M

**Comment by llamatester** [comment]
The adapter at projects/baseline exports TVL: 
        
 
 
    blast                     75.73 M
    blast-borrowed            56.17 M
    borrowed                  56.17 M
    
    total                    75.73 M

**Comment by llamatester** [comment]
The adapter at projects/baseline exports TVL: 
        
 
 
    blast                     76.26 M
    blast-borrowed            57.85 M
    borrowed                  57.85 M
    
    total                    76.26 M

**Comment by llamatester** [comment]
The adapter at projects/baseline exports TVL: 
        
 
 
    blast-borrowed            58.00 M
    borrowed                  58.00 M
    blast                     11.51 M
    
    total                    11.51 M

**Comment by g1nt0ki** [comment]
hi  @brightiron thanks for the PR, but I dont think we should count locked YES as tvl, we dont do it for v1 either.

**Comment by brightiron** [comment]
> hi @brightiron thanks for the PR, but I dont think we should count locked YES as tvl, we dont do it for v1 either.

thanks for merging @g1nt0ki . can we at least track YES collateral under 'staking'? It's a very important concept to track, as this value is technically locked in the protocol. 
The YES we are tracking is deposited into the protocol by an EOA as collateral in exchange for a loan

**Pull request merged**
