### PR TITLE
Feat: Add UniBTC

### PR DESCRIPTION
**Pull request by 0xpeluche**
#11222

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/unibtc exports TVL: 
        
 
 
    ethereum                  8.68 M
    optimism                  470.03 k
    bsquared                  1.64 k
    btr                       1.52 k
    merlin                    1.34 k
    mantle                    189
    
    total                    9.15 M

**Comment by llamatester** [comment]
The adapter at projects/unibtc exports TVL: 
        
 
 
    ethereum                  8.71 M
    bsquared                  1.09 M
    optimism                  470.52 k
    btr                       53.62 k
    merlin                    11.49 k
    mantle                    189
    
    total                    10.34 M

**Comment by llamatester** [comment]
The adapter at projects/unibtc exports TVL: 
        
 
 
    ethereum                  8.72 M
    bsquared                  1.09 M
    optimism                  470.52 k
    btr                       53.69 k
    merlin                    11.50 k
    mantle                    189
    
    total                    10.35 M

**Comment by llamatester** [comment]
The adapter at projects/unibtc exports TVL: 
        
 
 
    ethereum                  8.71 M
    bsquared                  1.09 M
    optimism                  470.52 k
    btr                       53.61 k
    merlin                    11.48 k
    mantle                    189
    
    total                    10.33 M

**Comment by llamatester** [comment]
The adapter at projects/unibtc exports TVL: 
        
 
 
    ethereum                  8.95 M
    bsquared                  1.16 M
    optimism                  481.49 k
    btr                       55.07 k
    merlin                    11.77 k
    mantle                    193
    
    total                    10.65 M

**Comment by Trisome-Bedrock** [comment]
@0xpeluche 
Could you please include the Merlin WBTC token [here](https://github.com/0xpeluche/DefiLlama-Adapters/blob/a2cde18e4f45b1063ce0c9e5b757ea7a18a393c3/projects/unibtc/index.js#L23)? It is also supported by the [uniBTC](https://github.com/Bedrock-Technology/uniBTC) protocol.

**Pull request merged**
