### PR TITLE
Add Q Saving adapter

### PR DESCRIPTION
**Pull request by KyrylR**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### List of audit links if any:
https://chainsecurity.com/wp-content/uploads/2021/11/ChainSecurity_Q_Blockchain_System_contracts_audit.pdf

https://chainsecurity.com/wp-content/uploads/2022/12/ChainSecurity_Q_Blockchain_System_contracts_v1_2_audit.pdf

##### Logo (High resolution, will be shown with rounded borders): 
https://blush-brilliant-blackbird-377.mypinata.cloud/ipfs/QmZatSLr3huwARyotBa8fJhcJDyW9dURNuAeHwTDHN5CNv

##### Short Description (to be shown on DefiLlama):

The QUSD Saving is fully integrated into the governance of the Q Protocol. 

By this, it is called an “Integrated Application”. These are systems of smart contracts which are bound by and benefit from
aspects of Q’s governance and are thereby deeply integrated into Q’s governance
framework. In return for the governance services they provide, Q Token Holders can receive
all or part of the fees generated by such Integrated Applications. Thus, Q breaks with the
conventional wisdom of the blockchain space, where the blockchain layer is separate from
the application layer. This radically changes the economics of Q compared to other
blockchains, since fees that are generated by Integrated Applications are available for
distribution to Q stakeholders.

The Q Saving benefits QUSD holders that opt-in to save their assets and earn rewards for it. The rewards are covered fully by the revenue generated from QUSD borrowers. 

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Staking Pool

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
QUSD does not require an Oracle. The underlying assets which are used to borrow against do have MakerDAO inspired oracles where a trusted oracle is used. If the price of 1 QUSD depegs from 1 USD then there is an economic incentive to either create more QUSD supply (bring the price down) or pay-back outstanding loans by buying QUSD from the market (bring the price up). 

##### Implementation Details: Briefly describe how the oracle is integrated into your project:
Does not apply for QUSD saving

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
Does not apply for QUSD saving.

##### forkedFrom (Does your project originate from another project):
It was highly inspired by MakerDAOs saving module but not directly forket from it. 

##### methodology (what is being counted as tvl, how is tvl being calculated):
So far, every 1 QUSD deposited into saving is counted as 1 USD TVL. With the start of the first DEXes on Q, there are first LP pairs QUSD <> wBTC, QUSD <> USDC, QUSD <> DAI . In the near future it will be reasonable to change the 1 USD assumption and provide an average of the existing liquidity pools weighted by their individual liquidity size. To avoid manipulation, a criterium should be 500k USD TVL or more to be counted in as a valid price reference for QUSD. 

##### Github org/user (Optional, if your code is open source, we can track activity):
https://gitlab.com/q-dev/system-contracts/-/blob/master/contracts/defi/Saving.sol 
https://gitlab.com/q-dev/system-contracts/-/blob/master/contracts/defi/token/StableCoin.sol

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/q-saving exports TVL: 
        
 
 
    q                         0
    q-staking                 21.82 k
    staking                   21.82 k
    
    total                    0

**Comment by KyrylR** [comment]
We are still preparing the Q Saving logo, we will provide it as soon as possible

**Comment by g1nt0ki** [comment]
hi @KyrylR thanks for the PR, I am slightly confused, how is there QUSD already in the saving contract, what is backing it? atm, for CDPs, we dont count the sablecoins in saving module, not even under staking, you can check our makerdao or liquity tvl adapter.

**Comment by g1nt0ki** [comment]
closing this as there were no response

**Comment by g1nt0ki** [comment]
hi, so instead of counting the staked STC, can you count the locked USDC/DAI/WBTC as tvl? we can then list it as CDP, also, can you share the bridge address on ethereum side?

**Comment by KyrylR** [comment]
Yep, sure here is a Bridge Address on the Ethereum side: https://etherscan.io/address/0x4663DF344CCc2dc54a332f5C27C008D766773856

**Comment by KyrylR** [comment]
> hi, so instead of counting the staked STC, can you count the locked USDC/DAI/WBTC as tvl? 

So, I need to change the logic of the adapter

Should I retrieve how many USDC/DAI/WBTC are locked in the Borrower contract and count it as TVL?

If it is OK, I will proceed with quick fix

**Comment by KyrylR** [comment]
I have changed the logic slightly, but I still struggle because the TVL is 0, and I have not been able to find a way to set a correct price

Actually, there are quite a lot of (bridged) tokens: https://explorer.q.org/address/0xb9c29d9A24B233C53020891D47F82043da615Dcc

**Comment by llamatester** [comment]
The adapter at projects/q-borrowing exports TVL: 
        
 
 
    q                         292.30 k
    
    total                    292.30 k

**Comment by llamatester** [comment]
The adapter at projects/q-borrowing exports TVL: 
        
 
 
    q                         369.59 k
    
    total                    369.59 k

**Comment by g1nt0ki** [comment]
@KyrylR thanks for the PR

**Pull request merged**
