### PR TITLE
add layerx-porotocol

### PR DESCRIPTION
**Pull request by wgou**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Treasury Addresses (if the protocol has treasury):
bc1pjmhcax3yuhyxxu7lf02ncurxvpp43mphfzx49jzd6uc0k7pfwrhsjkj3ue

##### Short Description (to be shown on DefiLlama):
Layerx Protocol is a game aggregation platform based on the Bitlayer network. It mainly serves the BRC20 ecosystem. Users pass BRC20 tokens through the cross-chain bridge of our platform, cross-chain to Bitlayer, and then participate in the Gamefi ecosystem of the platform.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/layerx-protocol exports TVL: 
        
 
 
    btr                       0
    
    total                    0

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
what is LSLOR?
please fill in the project details.

Also, we cant count projects own token as tvl: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by wgou** [comment]
The layerx protocol provides a BRC20 cross-chain bridge. Currently, it supports Inscription SLOR to participate in the GameFi ecosystem across cross-chains. SLOR cross-chain to Bitlayer will be exchanged for LSLOR Token at a 1:1 ratio.

**Comment by g1nt0ki** [comment]
if it is bridge, please provide the bitcoin address where the tokens are stored. also, please fill the project details in PR description

**Comment by wgou** [comment]
Are you replying here? BTC storage address: bc1pjmhcax3yuhyxxu7lf02ncurxvpp43mphfzx49jzd6uc0k7pfwrhsjkj3ue

**Comment by g1nt0ki** [comment]
hmm, I dont see slor on coingecko. Can you try to get it listed there first? because I dont know how to price the tokens otherwise. and we cant list a bridge with 0 tvl

**Pull request closed without merging**
