### PR TITLE
fix eklipse adapter

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/eklipse/index.js exports TVL: 
        
 
 
    klaytn                    53.41 M
    klaytn-staking            2.41 M
    klaytn-pool2              441.46 k
    staking                   2.41 M
    pool2                     441.46 k
    
    total                    53.41 M

**Comment by eklipse-finance** [comment]
Hi, @g1nt0ki ! Is it something wrong to fix eklipse adapters? There isn't eklipse page in defillama.
How can I help you? What should I do?

**Comment by g1nt0ki** [comment]
@eklipse-finance that sounds wrong, let me check

**Comment by eklipse-finance** [comment]
Thank you so much!

**Pull request merged**
