### PR TITLE
Accumulate

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/accumulated-finance exports TVL: 
        
 
 
    ethereum                  0
    arbitrum                  0
    velas-staking             0
    ethereum-staking          162.13 k
    arbitrum-staking          0
    velas                     69.36 k
    staking                   162.13 k
    
    total                    69.36 k

**Comment by g1nt0ki** [comment]
> Hi @g1nt0ki If it's not possible to add WACME to the core assets (are there any special requirements for this?), then I guess we have no other options.

LST is meant for chain's gas token like ethereum/solana/avax, cant be used for project's gov token.

**Comment by ilzheev** [comment]
@g1nt0ki WACME is a wrapped version of ACME, and ACME is a gas token for Accumulate Network.
https://explorer.accumulatenetwork.io
It's non-EVM, so we deployed liquid staking for ACME on EVM chains (Ethereum/Arbitrum).

Does it make sense now to include WACME as a core asset and add it to our LST TVL?

**Comment by ilzheev** [comment]
There are deployment contracts/accounts for WACME liquid staking.
https://github.com/AccumulatedFinance/deployments/blob/main/WACME.md

You can check corresponding ACME staking account on Accumulate chain:
https://explorer.accumulatenetwork.io/acc/accumulated.acme/staking

**Comment by g1nt0ki** [comment]
@ilzheev ah got it, changed it to tvl instead now

**Pull request merged**
