### PR TITLE
Weft Finance Integration

### PR DESCRIPTION
**Pull request by atoumbre**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama): 
Weft Finance

##### Twitter Link: 
https://twitter.com/Weft_Finance

##### List of audit links if any: 
https://github.com/pessimistic-io/audits/blob/main/Weft%20Finance%20Security%20Analysis%20by%20Pessimistic.pdf

##### Website Link:
https://docs.weft.finance

##### Logo (High resolution, will be shown with rounded borders):
https://res.cloudinary.com/daisvxhyu/image/upload/v1692817771/weft/weft-icon.png

##### Current TVL:
39.94 k 

##### Chain:
radix

##### Short Description (to be shown on DefiLlama):
Weft Finance is a decentralized lending and borrowing application built on Radix DLT

##### Token address and ticker if any:
resource_rdx1tk3fxrz75ghllrqhyq8e574rkf4lsq2x5a0vegxwlh3defv225cth3
WEFT

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### methodology (what is being counted as tvl, how is tvl being calculated):
Our TVL represent value of assets available in our lending pools. So TVL is total deposit amount deducted with total borrowed amount.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/WeftFinance

### CODE REVIEW

**Comment by g1nt0ki** [comment]
thanks for the PR, included your changes here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/8345

**Comment by g1nt0ki** [comment]
oh, is there some way to track the borrowed amount as well?

**Comment by atoumbre** [comment]
> oh, is there some way to track the borrowed amount as well?

Yes there is. We can get deposit amount and borrowed amont from pool component state. We have an sdk that make the process easy from javascript.

**Comment by atoumbre** [comment]
> > > oh, is there some way to track the borrowed amount as well?
> 
> > 
> 
> > Yes there is. We can get deposit amount and borrowed amont from pool component state. We have an sdk that make the process easy from javascript.
> 
> 
> 
> I am trying to keep the amount of dependencies to a minimum, is there someway to fetch this info on chain?

No dependency are required. I tried to use our toolkit but at the end , it was not necessary as all data are on chain.

**Comment by g1nt0ki** [comment]
yup, merged changes from your other PR, thanks again for the PR.

**Pull request closed without merging**
