### PR TITLE
Add HedgeFarm

### PR DESCRIPTION
**Pull request by tudorhedged**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

HedgeFarm

##### Twitter Link:

[https://twitter.com/hedge_farm](https://twitter.com/hedge_farm)

##### List of audit links if any:

None

##### Website Link:

[https://hedgefarm.finance](https://hedgefarm.finance)

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

[https://hedgefarm.finance/hedgefarm-icon.png](https://hedgefarm.finance/hedgefarm-icon.png)

##### Current TVL:

75'000 USDC

##### Chain:

Avalanche

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

None

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

None

##### Short Description (to be shown on DefiLlama):

A DeFi protocol that provides alpha yield vaults for your crypto.

HedgeFarm allows you to access crypto investment vaults that will suit your needs depending on what type of crypto assets you want to invest in and what type of risk you are ready to take for the performance you'll get.

##### Token address and ticker if any:

None

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Yield

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

None

##### forkedFrom (Does your project originate from another project):

None

##### methodology (what is being counted as tvl, how is tvl being calculated):

The TVL is the amount of USDC deposited in the strategy and that we put to work.

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@tudorhedged how exactly is the yield generated?

**Comment by tudorhedged** [comment]
@g1nt0ki The yield is generated through an in-house DeFi (CPPI)[https://www.investopedia.com/terms/c/cppi.asp] strategy. Basically, we run epochs of 28 days where we put 80% of the funds on Stargate, with 10% we execute long/short trades following our internal trading algo and the remaining 10% are for liquidity to support trading operations.

**Comment by g1nt0ki** [comment]
I guess we can resolve stargate LP to get value deposited there, and 10% set aside can be counted by reading USDC balance on the contract, how does the long/short trade work? is it on chain?

**Comment by tudorhedged** [comment]
I'm not sure what you want to do here? Epochs last 28 days on the strategy and in between it's difficult for us to estimate the current total value in the contract. Can't we have something similar to options yield which have a 7-day epoch and TVL not changing before the end of the epoch? For example: Friktion USDC Crab Strategy

**Comment by llamatester** [comment]
The adapter at projects/hedgefarm exports TVL: 
        
 
 
    avax                      76.35 k
    
    total                    76.35 k

**Comment by tudorhedged** [comment]
Understood. So yes Stargate can be computed on chain but I don't think we can compute the longs/shorts on-chain. Even in our contract, it's not live while the epoch is running.

**Pull request merged**
