### PR TITLE
update to include vault TVL

### PR DESCRIPTION
**Pull request by Amirjab21**
This change adds Popcorns new vaults to the TVL calculation.

These vaults are listed in the Vault Registry.

**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/popcorn: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by llamatester** [comment]
The adapter at projects/popcorn exports TVL: 
        
 
 
    bsc                       0
    arbitrum                  0
    polygon-staking           240.65 k
    arbitrum-staking          38.60 k
    ethereum-staking          4.37 M
    bsc-staking               36.20 k
    polygon                   11.04 k
    ethereum                  329.42 k
    staking                   4.69 M
    
    total                    340.47 k

**Comment by g1nt0ki** [comment]
will try to review this soon

**Comment by llamatester** [comment]
The adapter at projects/popcorn exports TVL: 
        
 
 
    bsc                       0
    arbitrum                  0
    arbitrum-staking          40.73 k
    bsc-staking               38.25 k
    polygon-staking           254.22 k
    ethereum-staking          4.62 M
    polygon                   11.06 k
    ethereum                  329.89 k
    staking                   4.95 M
    
    total                    340.95 k

**Comment by g1nt0ki** [comment]
@Amirjab21 can you review my commit, think the refactor is fine but a second pair of eyes doesnt hurt

**Comment by Amirjab21** [comment]
Looks good to me - thanks so much for that useful refactor @g1nt0ki

**Comment by g1nt0ki** [comment]
@Amirjab21 wdym? can you give some details?

**Comment by Amirjab21** [comment]
@g1nt0ki 

You see how staking is separated into its own category with its own key?

I'd like to have a separate category for vaults but it complained about having to use keys from a fixed set when I tried to add a key for vaults.

**Comment by g1nt0ki** [comment]
> @g1nt0ki
> 
> You see how staking is separated into its own category with its own key?
> 
> I'd like to have a separate category for vaults but it complained about having to use keys from a fixed set when I tried to add a key for vaults.

staking is kept separate because we dont consider it as tvl, but tokens in the vault are part of your tvl, or do you  want to treat vaults as a separate product?

**Comment by Amirjab21** [comment]
@g1nt0ki 

We ideally want to keep vaults in the TVL but also separate it out so that we can easily see the TVL specifically in the vaults from the API.

**Pull request merged**
