### PR TITLE
updated how we get treasury value

### PR DESCRIPTION
**Pull request by sameretto**
using one endpoint than multiple to retrieve treasury value

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/hector exports TVL: 
        
 
 
    fantom-staking            18.88 M
    fantom-borrowed           468.99 k
    fantom                    67.64 M
    staking                   18.88 M
    borrowed                  468.99 k
    
    total                    67.64 M

**Comment by waynebruce0x** [comment]
Is the debank API open source?

**Comment by sameretto** [comment]
> Is the debank API open source?

I'm not sure. What is the concern?

**Comment by waynebruce0x** [comment]
We prefer to use transparent data sources

**Comment by sameretto** [comment]
> We prefer to use transparent data sources

Anyone can use the Api from DeBank.. All it does is read data from certain wallets and we calculate the total of all wallets to get the TVL. would you like the source of wallets from debank to see?

**Comment by waynebruce0x** [comment]
Yeah please that'd be great

**Comment by sameretto** [comment]
> Yeah please that'd be great
these are the following assets/wallets we own to calculate our TVL.. all of the detail is in the following links:
https://debank.com/profile/0x4bfb33d65f4167ebe190145939479227e7bf2cb0
https://debank.com/profile/0xcb54ea94191b280c296e6ff0e37c7e76ad42dc6a
https://debank.com/profile/0x677d6ec74fa352d4ef9b1886f6155384acd70d90
https://debank.com/profile/0x3cdf52cc28d21c5b7b91d7065fd6dfe6d426fcc5
https://debank.com/profile/0x8a43e670619973944cb573bb23688c24cc0b5131
https://debank.com/profile/0xbe4b73f5caff476ed0cdb4c043236fce81f4dc6c
https://debank.com/profile/0x35796ce4ed757075d346c1bc374d67628fadcbb1

**Comment by sameretto** [comment]
> > Yeah please that'd be great
> > these are the following assets/wallets we own to calculate our TVL.. all of the detail is in the following links:
> > https://debank.com/profile/0x4bfb33d65f4167ebe190145939479227e7bf2cb0
> > https://debank.com/profile/0xcb54ea94191b280c296e6ff0e37c7e76ad42dc6a
> > https://debank.com/profile/0x677d6ec74fa352d4ef9b1886f6155384acd70d90
> > https://debank.com/profile/0x3cdf52cc28d21c5b7b91d7065fd6dfe6d426fcc5
> > https://debank.com/profile/0x8a43e670619973944cb573bb23688c24cc0b5131
> > https://debank.com/profile/0xbe4b73f5caff476ed0cdb4c043236fce81f4dc6c
> > https://debank.com/profile/0x35796ce4ed757075d346c1bc374d67628fadcbb1

we use this endpoint to get the data from the addresses above
https://docs.open.debank.com/en/reference/api-pro-reference/user#get-user-complex-protocol-list

**Comment by waynebruce0x** [comment]
If you want I can change the adapter code from subgraph to on-chain calls to those addresses, or we can keep the subgraph code. However we don't use debank so we cant merge this update as it is.

**Comment by sameretto** [comment]
> If you want I can change the adapter code from subgraph to on-chain calls to those addresses, or we can keep the subgraph code. However we don't use debank so we cant merge this update as it is.

May I ask why Debank is not a source of info you guys can use? Its just a platform that aggregates all data from other websites.

**Comment by waynebruce0x** [comment]
Because its not transparent and impossible to maintain from our end. With the contract addresses you have left, we can help build an onchain adapter for you

**Pull request closed without merging**
