### PR TITLE
Add Celery protocol

### PR DESCRIPTION
**Pull request by mainnet-pat**
##### Short Description (to be shown on DefiLlama):
The first Blockchain Annuity that will replace your savings account! Earn 100% APY!

##### methodology (what is being counted as tvl, how is tvl being calculated):
Contract function is called to get the total staked CLY tokens in the smart contract

### CODE REVIEW

**Comment by mainnet-pat** [comment]
We do not have etherscan-grade explorer which allows for contract decompilation.

However, you can see the audit source code of the CLY contract https://github.com/MaxHastings/Celery/blob/234558af1b4b60e9b45206e5efdab52fa044a870/contracts/Celery.sol#L160

What this function returns is mostly the `CLY.balanceOf(CLY)` scaled by some time factor.

**Comment by waynebruce0x** [comment]
Why the time factor? Typically we'd just use a token balance, since thats what is 'locked' in the contract

**Comment by mainnet-pat** [comment]
Celery is a compounding annuity system which rewards holders for locking their funds. They report the total tokens staked including staking interest made over staking time t (as per their whitepaper https://celery.cash/whitepaper.pdf).

If you are uncomfortable with this, I can set the staking tvl to `CLY.balanceOf(CLY)` without this scaling factor.

**Comment by waynebruce0x** [comment]
Yeah can we change to just read the token balance - thanks

**Comment by llamatester** [comment]
The adapter at projects/celery exports TVL: 
        
 
 
    smartbch                  0
    smartbch-staking          642.03 k
    staking                   642.03 k
    
    total                    0

**Comment by mainnet-pat** [comment]
a humble ping

**Pull request merged**
