### PR TITLE
New adapter for v2 of Atlendis protocol

### PR DESCRIPTION
**Pull request by olivblad**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/atlendis-v2 exports TVL: 
        
 
 
    mode                      5.45 M
    polygon                   751.14 k
    polygon-borrowed          749.87 k
    borrowed                  749.87 k
    mode-borrowed             0
    
    total                    6.20 M

**Comment by llamatester** [comment]
The adapter at projects/atlendis-v2 exports TVL: 
        
 
 
    mode                      5.47 M
    polygon                   752.01 k
    polygon-borrowed          750.75 k
    borrowed                  750.75 k
    mode-borrowed             0
    
    total                    6.23 M

**Comment by llamatester** [comment]
The adapter at projects/atlendis-v2 exports TVL: 
        
 
 
    polygon-borrowed          749.22 k
    borrowed                  749.22 k
    polygon                   941
    mode-borrowed             0
    mode                      0
    
    total                    941.0078602802641

**Comment by g1nt0ki** [comment]
@olivblad thanks for the PR, is there some way to fetch the borrowed value on chain? I have refactored the code a bit, we count only the part not yet lent out as tvl, rest only under borrowed.

**Comment by olivblad** [comment]
hi @g1nt0ki, thanks for checking our PR, and thanks for the refacto.

To answer your question: 
**No**, our contracts don't expose the borrowed value, so no easy way for you to retrieve this value on chain **but** we definitely expose it on our API.

Few remarks on my end :

I see you changed the queried fields, adding `accruedInterests`, `id`, removing `issuedLoan` from bulletLoans; i understand the desire to refacto so i propose you to merge both queries into this one : 
````
 query tvl($chainId: Int!) {
    rcls(chainId: $chainId) {
      tvl
      token {
        address
      }
      currentLoan {
        borrowedAmount
      }
    }
    bulletLoans(chainId: $chainId) {
      tvl
      token {
        address
      }
      issuedLoan {
        borrowedAmount
      }
    }
  }
````

To be noted: 
- `id` is not needed, it's just the ID from our db and this field has no use here;
- `accruedInterests` is used for us to show our users the earnings they're currently making on a position that is borrowed, but for the TVL and Borrowed Amount, no need to be retrieved;
- `bulletLoans` is a specific product we propose on our protocol, you can see it as another pool, so it must be treated the same way as rcl, that's why you need to query the `issuedLoan` field (equiv to `currentLoan` in rcl)

I see you're using you own API in order to fetch balances on chain and I take note of your remark about your TVL definition (sum of the deposits that are not borrowed yet or the balance of token in the pool). 
Why not .. but since we directly get those pieces of information in the query to our API, why bothering fetching again on chain ? happy to discuss this point further.

In order not to repete the querying process, i suggest we compute tvl such as : 
TVL = "queried-tvl-field" - "queried-borrowedAmounts-field"
and
we use the borrowedAmount retrieved in the first query (via our API)

wdty ?

How do you want to proceed from now ? Shall i open a new PR adjusting the merged-code ?

If you want to sync to quickly talk on this, don't hesitate,

cheers

**Pull request merged**
