### PR TITLE
Some changes: add more pools, change description and add TVL collateral

### PR DESCRIPTION
**Pull request by munikes**
When do some more change:
1. Add more AMM pool we have ETHIX.
2. Change methodology description.
3. Add all TVL that we have on collateral contracts.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/ethichub exports TVL: 
        
 
 
    celo                      1.01 M
    ethereum                  9.20 M
    celo-pool2                10.84 k
    celo-staking              77.61 k
    ethereum-staking          379.09 k
    ethereum-pool2            73.81 k
    pool2                     84.65 k
    staking                   456.70 k
    
    total                    10.21 M

**Comment by munikes** [comment]
Sorry @g1nt0ki, you are probably absolutely right, but I am a simple programmer within EthicHub and they assure me within the financial engineering department that our collateral reserve is precisely our TVL and that it is not counted twice. Staking and pools are other contracts that have nothing to do with our collateral reserve, they belong to our incentive reserve, which of course we are not counting for the TVL, we only count the fact that those ethix are staked.
In this PR, in addition to adding the TVL, we have added the new pools that we did not have before and we have changed the description of our methodology.
To make everything much clearer, I am going to show you a couple of graphs that better explain all the Ethichub accounts.

**Comment by g1nt0ki** [comment]
@munikes 

1. We count only non-protocol tokens deposited by the users under TVL, protocol gov tokens deposited by the users under staking. What you are counting as your tvl is not deposited by the user and is your own gov token: https://etherscan.io/tx/0x998bcbdc361ca6fe4d2f2c2b785e1079237f874331a1440f1d5eaf905bb4f443 

2. Not sure why you are counting LP tokens under staking, they are already counted under pool2
3. tokens (except ETHIX token) held by the treasury/team multisig  can be counted under 'treasury' not in pool2/staking/tvl

**Comment by g1nt0ki** [comment]
I have refactored the code a bit, it should look like this:

    const sdk = require('@defillama/sdk');
    const { transformCeloAddress } = require('../helper/portedTokens');
    const { pool2 } = require("../helper/pool2");
    const { staking, stakings } = require('../helper/staking');
    const { unwrapBalancerToken, unwrapBalancerPool, unwrapUniswapLPs, sumTokens2 } = require('../helper/unwrapLPs');

    // Mainnet
    const ETHIX_TOKEN = '0xFd09911130e6930Bf87F2B0554c44F400bD80D3e';
    const COLLATERAL_RESERVE_MAINNET = '0xb97Ef216006d72128576D662CFFEd2B4406E3518';
    const STAKED_ETHIX_MAINNET = '0x5b2bbbe7DFD83aA1f1CD0c498690E6EcC939CC2D';
    const MULTISIG_ETHICHUB_MAINNET = '0xA8f0A7dC8695c2233D847c7E34719830cdFaa4E1';
    // Uniswap Mainnet Staking (Stake Contract + Multisig)
    const UNISWAP_LP_ETHIXWETH = '0xb14b9464b52F502b0edF51bA3A529bC63706B458';
    const STAKED_UNISWAP_LP_CONTRACT = '0x89cea15F68950DF830dFE3630d635a9eD79478F5';
    // Balancer Mainnet Staking (Multisig)
    const BALANCER_LP_ETHIXDAI = '0x69183d2ce96B6b8962f3013e0Af4545F26F00293';
    // Bonds Mainnet
    const MINIMICE_ETH = '0x21320683556BB718c8909080489F598120C554D9';
    // Originators
    const ORIGINATOR_BRAZIL = '0x3B61CD481Be3BA62a9a544c49d6C09FCb804d0e3';
    const ORIGINATOR_HONDURAS = '0x7435C0232A69270D19F8E4010571175c3f1dd955';

    // -------------------
    // Celo
    const ETHIX_TOKEN_CELO = '0x9995cc8F20Db5896943Afc8eE0ba463259c931ed';
    const COLLATERAL_RESERVE_CELO = '0xA14B1D7E28C4F9518eb7757ddeE35a18423e1567';
    const STAKED_ETHIX_CELO = '0xCb16E29d0B667BaD7266E5d0Cd59b711b6273C6B';
    const MULTISIG_ETHICHUB_CELO = '0xB721E887FA79Ce52f9F86958C128fa9eD3f1c5D3';
    // Ubeswap Celo Staking (Stake Contract + Multisig)
    const UBESWAP_LP_ETHIXCUSD = '0x62cfA295864cfF683CDE9B47D4bACC77B885DdB7';
    const STAKED_UBESWAP_LP_CONTRACT = '0xbfa2748a60976Cd18b835C75C6a20328E9a72684';
    // Balancer Mainnet Staking (SymmChef + Multisig)
    const SYMMETRIC_LP_ETHIXCELO = '0xaD2F9f4CD2Ae4f2dD2841EB1ea7e162fb4767D4D';
    const STAKED_SYMMETRIC_LP_CONTRACT = '0x359a3060A68488F0ea43D5cD8F6F53fe81A15f59';
    // Bonds Celo
    const MINIMICE_CELO = '0x0f497a790429685a3CfD43b841865Ee185378ff0';

    async function treasuryMainnet(timestamp, block) {
      const balances = {};
      await unwrapBalancerToken({ block, owner: MULTISIG_ETHICHUB_MAINNET, balancerToken: BALANCER_LP_ETHIXDAI, balances });
      return sumTokens2({ balances, block, tokens: [UNISWAP_LP_ETHIXWETH], owner: MULTISIG_ETHICHUB_MAINNET })
    }

    async function treasuryCelo(timestamp, _, { celo: block }) {
      const chain = 'celo'
      const balances = {};
      await unwrapBalancerPool({ chain, block, owner: MULTISIG_ETHICHUB_CELO, balancerPool: SYMMETRIC_LP_ETHIXCELO, balances })
      return sumTokens2({ balances, chain, block, tokens: [UBESWAP_LP_ETHIXCUSD], owner: MULTISIG_ETHICHUB_CELO, resolveLP: true })
    }

    async function pool2Celo(timestamp, _, { celo: block }) {
      const chain = 'celo'
      const balances = {};
      await unwrapBalancerPool({ chain, block, owner: STAKED_SYMMETRIC_LP_CONTRACT, balancerPool: SYMMETRIC_LP_ETHIXCELO, balances })
      return sumTokens2({ balances, chain, block, tokens: [UBESWAP_LP_ETHIXCUSD], owner: STAKED_UBESWAP_LP_CONTRACT, resolveLP: true })
    }

    module.exports = {
      timetravel: true,
      misrepresentedTokens: false,
      methodology: `
        1. Our general TVL is the ETHIX locked in our collateral reserves. They are found in our compensation reserves in different chains and in bond issuance contracts. These ETHIX would only move when a farmer's default appears.
        2. In the different AMM pools we have blocked an initial amount of LP tokens, in a multisig belonging to Ethichub.
        3. We have ETHIX staked in the different staking contracts in the chains where we operate. There are staked ETHIX, staked LP tokens, and ETHIX belonging to staked originator nodes.
        Active networks: ETH/CELO/GNOSIS.
        All our pools and staking options are in: https://ethix.ethichub.com, and info about project: https://ethichub.com
        `,
      start: 1608640693,
      ethereum: {
        tvl: () => ({}),
        pool2: staking(STAKED_UNISWAP_LP_CONTRACT, UNISWAP_LP_ETHIXWETH),
        staking: stakings([STAKED_ETHIX_MAINNET, ORIGINATOR_BRAZIL, ORIGINATOR_HONDURAS], ETHIX_TOKEN),
        treasury: treasuryMainnet,

      },
      celo: {
        pool2: pool2Celo,
        staking: staking(STAKED_ETHIX_CELO, ETHIX_TOKEN_CELO, 'celo'),
        treasury: treasuryCelo,
      },
      hallmarks: [
        [1608640694, "Ethix launch"],
        [1655719625, "Ethix on Celo network"],
        [1626704101, "Originator Brazil"],
        [1634714203, "Originator Honduras"],
        [1610472600, "Grand Opening Cryptocafé in Madrid"],
      ]
    };

**Comment by g1nt0ki** [comment]
closed due to lack of activity

**Pull request closed without merging**
