### PR TITLE
:sparkles: Add Unitus protocol.

### PR DESCRIPTION
**Pull request by Skyge**
##### Github org/user (Optional, if your code is open source, we can track activity): https://github.com/UnitusLabs

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/unitus exports TVL: 
        
 
 
    optimism                  2.54 M
    polygon-borrowed          288.55 k
    polygon                   277.02 k
    optimism-borrowed         2.46 M
    arbitrum                  6.73 M
    arbitrum-borrowed         5.04 M
    bsc                       2.97 M
    bsc-borrowed              1.78 M
    ethereum-borrowed         1.42 M
    ethereum                  5.16 M
    conflux-borrowed          48.60 k
    conflux                   1.86 M
    borrowed                  11.03 M
    
    total                    19.53 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
this is a duplicate of dforce adapter

**Comment by g1nt0ki** [comment]
hi @Skyge if this is a rebrand, maybe we can remove the these contracts from dforce, create a sublisting for unitus under dforce?

**Comment by Skyge** [comment]
@g1nt0ki Hi, yes, rebrand. So how to make a sublisting? Is there a documentation about this?

**Comment by g1nt0ki** [comment]
> @g1nt0ki Hi, yes, rebrand. So how to make a sublisting? Is there a documentation about this?

I will take care :)

**Comment by g1nt0ki** [comment]
split here:. https://github.com/DefiLlama/DefiLlama-Adapters/commit/b7d53f0b02e1df03418f7b57688671943b96ca39

**Comment by Skyge** [comment]
@g1nt0ki Sorry, I think I am wrong. It is spin off，spin off lending from dforce as a separated brand, named unitus, details are here: https://snapshot.org/#/dforcenet.eth/proposal/0x89c90f647cbd1df112636b5bdc4d8dfa3f5e5d177c70cad3f5dc13e146f46b20

**Comment by g1nt0ki** [comment]
@Skyge all good, it is a new listing now: https://defillama.com/protocol/unitus

**Pull request closed without merging**
