### PR TITLE
fetch kujira contracts from canonical source

### PR DESCRIPTION
**Pull request by codehans**
Updates the Kujira protocol adapters to fetch the contract lists from a published json file. The old methods of hard-coding contract addresses or fetching via code ID is fragile and needs updating every time either a contract is added or a new code ID for a protocol is created

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bow exports TVL: 
        
 
 
    kujira                    2.96 M
    
    total                    2.96 M

**Comment by llamatester** [comment]
The adapter at projects/fin exports TVL: 
        
 
 
    kujira                    2.73 M
    
    total                    2.73 M

**Comment by llamatester** [comment]
The adapter at projects/ghost exports TVL: 
        
 
 
    kujira-borrowed           859.95 k
    kujira                    5.46 M
    borrowed                  859.95 k
    
    total                    5.46 M

**Comment by llamatester** [comment]
The adapter at projects/kujira exports TVL: 
        
 
 
    kujira                    2.29 M
    
    total                    2.29 M

**Comment by llamatester** [comment]
The adapter at projects/orca-kujira exports TVL: 
        
 
 
    kujira                    140.60 k
    
    total                    140.60 k

**Comment by g1nt0ki** [comment]
@codehans thanks, it looks good.

**Pull request merged**
