### PR TITLE
eth-arb-pol tvl add

### PR DESCRIPTION
**Pull request by fensa08**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/kromatika: 
        
 
  
    
    
    Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="totalSupply()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.6.4)
    Truncated error stack:
        at Interface.decodeFunctionResult (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/abi/lib/interface.js:388:23)

**Comment by realdealshaman** [comment]
@fensa08 , had already looked into this from your prior PR and the contracts appear to only contain staked KROM tokens. Seems to be the reason why the calls to find a tvl are failing

**Comment by realdealshaman** [comment]
@fensa08 , can we close this PR now

**Comment by fensa08** [comment]
> @fensa08 , can we close this PR now

@realdealshaman working on a workaround, its almost done - im having some encountering some weird issues with arbitrum, although it works on other chains. Regardless, will enclose it shortly

**Comment by llamatester** [comment]
Error while running adapter at projects/kromatika: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:223:11

**Comment by fensa08** [comment]
@llamatester @realdealshaman  any updates ?

**Comment by realdealshaman** [comment]
there shouldn't be a need to use web3 and to add your own rpc since this is already happening for all adapters. also, adding the abi into the index.js file or leaving it in its own file doesn't change anything

**Comment by g1nt0ki** [comment]
@fensa08 what are you trying to do here?

**Comment by fensa08** [comment]
@g1nt0ki since our protocol also manages the V3 LP positions, I am trying to add those values aswell. To be specific, the manager contracts (on several chains) are pinged so I can fetch all active positions in order to extract the value of the liquidity involved (for every position), which is later added to the overall TVL. For that purpose I am using ethers library & I need a provider to call the contracts.

**Comment by g1nt0ki** [comment]
@fensa08 okay, I understand what you are trying to do here, optimism has one abi, other chains have different abi, right?

I took a look at your code again, also at the etherscan, is there a better way to get a list of active orders in ethereum and others? current way is not very efficient, you are querying 1500 ids and using that to get data, but most of these calls would fail, and what if there are more than 1500 orders? 

Is there a better way to do this?

**Comment by fensa08** [comment]
@g1nt0ki unfortunately yes, not all chains have the same ABI. It would have been better if all chains had Optimism's ABI.

Another alternative would be using Uniswap's multicall contract, but the request will be unsuccessful since multicall requires all calls to be successful (call(s) could revert if there is no active order for given index, so the multicall will revert altogether).

Another option is to keep a record of active orders, so we do not make 1500 calls per chain. Once order is completed/cancelled, it cannot change its state back to active. If keeping a record of active orders is acceptable, then thats the best way to go.

**Comment by g1nt0ki** [comment]
@fensa08 took me  a long time, but finally fixed it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/5090 

I am hoping that it is correct implementation, can you verify?

**Pull request closed without merging**
