### PR TITLE
Nabla Finance

### PR DESCRIPTION
**Pull request by yellowBirdy**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

##### Name (to be shown on DefiLlama):
Nabla Finance

##### Twitter Link: 
https://twitter.com/NablaFi

##### List of audit links if any:  
https://github.com/pashov/audits/blob/master/team/pdf/Nabla-security-review.pdf

##### Website Link: 
https://nabla.fi

##### Logo (High resolution, will be shown with rounded borders): 
https://www.dropbox.com/scl/fi/6hg54jjfd8ld4td27m4gt/gr1-3.png?rlkey=vtkxi8air40h43u5186fz637i&dl=0

##### Treasury Addresses (if the protocol has treasury): [on arb
](arb:0x8F7447a6a04857855Caf75ecb1600d2984a7285D)

##### Chain: 
Arbitrum One, Base

##### Short Description (to be shown on DefiLlama):
Nabla Finance is a yield bearing token protocol where the organic yield is generated by the hyper-efficient Nabla AMM. 

##### Token address and ticker if any:  
Not yet deployed

##### Category (full list at https://defillama.com/categories) *Please choose only one:  
DEXES

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Nabla utilises a dual oracle system consisting of a chosen price oracle and a Volatility Guard oracle. 
**Pyth** is being used for prices and **EV.GO** for volatility guard.

##### Implementation Details: Briefly describe how the oracle is integrated into your project:
**Price oracles** are integrated through Oracle Adapters that conform to a standardised interface, 
ensuring seamless interoperability within the protocol. 
These adapters are responsible for registering the price feeds of the tokens traded on the platform 
and fetching the necessary price data to facilitate protocol operations.
The currently available Oracle Adapters for Nabla include:
[Pyth](https://docs.nabla.fi/protocol-overview/oracle-details/pyth) Adapter

This adapter utilises Pyth Network price feeds to provide reliable and up-to-date price information for various assets. It includes functionalities to register, unregister, and update price feeds, and it ensures accurate price information by requiring periodic updates to the price feeds. 
It allows to set criteria on  price staleness and confidence interval. In practice w operate with with v. low staleness tolerance e.g. 2s.

**EV.GO Oracle**
EV.GO stands for Excessive Volatility Guard Oracle. In order to mitigate toxic order flow generated by unavoidable lags in price propagation we’ve built a novel, ultra fast onchain oracle. It is able to signal potentially dangerous price movements before the actual price reaches the chain.

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
https://docs.nabla.fi/protocol-overview/oracle-details/architecture
https://docs.nabla.fi/developers/contract-addresses-and-details/nabla-mainnet-alpha#pyth-adapter
https://docs.pyth.network/price-feeds/contract-addresses/evm
	
	Verify Pyth contract address:
	cast call 0xA5900362310C0f577b6A63ee66552711Ee3f8EeB "getPythContractAddress()" --rpc-url $ARBITRUM_MAINNET_RPC_URL 
0x000000000000000000000000ff1a0f4744e8582df1ae09d5611b887b6a12925c

##### methodology (what is being counted as tvl, how is tvl being calculated):
Balances of respective assets of our pool contracts. All Nabla pools ale single asset pools.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/NablaFinance

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/nabla exports TVL: 
        
 
 
    arbitrum                  195.54 k
    base                      22.65 k
    
    total                    218.20 k

**Comment by llamatester** [comment]
The adapter at projects/nabla exports TVL: 
        
 
 
    arbitrum                  196.16 k
    base                      22.58 k
    
    total                    218.73 k

**Comment by llamatester** [comment]
The adapter at projects/nabla exports TVL: 
        
 
 
    arbitrum                  196.16 k
    base                      22.58 k
    
    total                    218.73 k

**Comment by g1nt0ki** [comment]
thanks for the PR

**Pull request merged**
