### PR TITLE
[WIP] add Coinspot CEX adapter

### PR DESCRIPTION
**Pull request by Avedith**
##### Name (to be shown on DefiLlama):
Coinspot

##### Twitter Link:
https://twitter.com/coinspotau/

##### Website Link:
https://www.coinspot.com.au/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://www.coinspot.com.au/public/img/coinspot-logo-40x40.png **To be updated with higher quality before merge**

##### Current TVL:
TBA

##### Treasury Addresses (if the protocol has treasury)
TBA

##### Chain:
TBA

##### Short Description (to be shown on DefiLlama):
TBA

##### Category (full list at https://defillama.com/categories) *Please choose only one:
TBA

##### methodology (what is being counted as tvl, how is tvl being calculated):
TBA

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/coinspot exports TVL: 
        
 
 
    ethereum                  3.79 M
    
    total                    3.79 M

**Comment by llamatester** [comment]
The adapter at projects/coinspot exports TVL: 
        
 
 
    polygon                   8.42 M
    fantom                    206.46 k
    bsc                       76.64 k
    ethereum                  9.93 M
    
    total                    18.63 M

**Comment by llamatester** [comment]
The adapter at projects/coinspot exports TVL: 
        
 
 
    polygon                   8.40 M
    bsc                       76.70 k
    fantom                    206.92 k
    ethereum                  12.12 M
    
    total                    20.81 M

**Comment by Avedith** [comment]
Some of these wallets are unknown if they are owned by Coinspot. Currently waiting to hear back from Coinspot with wallets

**Comment by llamatester** [comment]
The adapter at projects/dyson-money exports TVL: 
        
 
 
    optimism                  1.92 k
    arbitrum                  947.92 k
    polygon-staking           11.41 M
    polygon                   396.73 k
    staking                   11.41 M
    
    total                    1.35 M

**Comment by llamatester** [comment]
The adapter at projects/coinspot exports TVL: 
        
 
 
    fantom                    187.48 k
    polygon                   8.85 M
    ethereum                  12.02 M
    bsc                       82.84 k
    
    total                    21.13 M

**Comment by g1nt0ki** [comment]
@Avedith need any help with this?

**Comment by g1nt0ki** [comment]
> Some of these wallets are unknown if they are owned by Coinspot. Currently waiting to hear back from Coinspot with wallets

Ah I see

**Comment by Avedith** [comment]
@g1nt0ki Yeh, basically waiting to hear back from them, but that could take a while. Will re-open the PR once I hear something back from them

**Pull request closed without merging**
