### PR TITLE
Add swap.coffee staking and pool2 adapter

### PR DESCRIPTION
**Pull request by SHADOWDANCH**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/swap-coffee exports TVL: 
        
 
 
    ton-staking               213.74 k
    staking                   213.74 k
    ton-pool2                 111.94 k
    pool2                     111.94 k
    ton                       0
    
    total                    0

**Comment by g1nt0ki** [comment]
thanks for the PR

**Comment by Define101** [comment]
@SHADOWDANCH please provide website link and twitter link at least

**Comment by SHADOWDANCH** [comment]
> @SHADOWDANCH please provide website link and twitter link at least

https://swap.coffee/
https://x.com/swap_coffee_ton
It's already on defillama

**Pull request merged**
