### PR TITLE
Add Flash.Trade 

### PR DESCRIPTION
**Pull request by UjjwalGupta49**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Logo (High resolution, will be shown with rounded borders):
flash01
flash02

##### Implementation Details: Briefly describe how the oracle is integrated into your project:
Reading price from Pyth: At the time of initializing an asset, the admin configures the state with the matching price_data account from Pyth and defines the necessary divergence, confidence and staleness thresholds. Subsequently, the price is read from the price_data account through a custom pricing function that first validates that the price is not stale by comparing the last_updated_time on the price_account against the current time to be within the defined threshold. The custom pricing function then computes a measure of volatility as deviation between the spot and ema price reported by the oracle's price_account and then resolves into min and max price by reporting the spot price as the max price and discounting the same by a factor of confidence interval as min price. The combination of max and min price is then used differentially for various instructions on the program.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/flash-trade: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:217:11

**Comment by llamatester** [comment]
Error while running adapter at projects/flash-trade.js: 
        
 
  
    
    
    AxiosError: Request failed with status code 429
    Truncated error stack:
        at settle (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/axios/dist/node/axios.cjs:1970:12)
        at IncomingMessage.emit (node:events:529:35)

**Comment by llamatester** [comment]
Error while running adapter at projects/flashtrade: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:217:11

**Comment by llamatester** [comment]
Error while running adapter at projects/flashtrade: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:217:11

**Comment by llamatester** [comment]
Error while running adapter at projects/flashtrade: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:217:11

**Comment by llamatester** [comment]
Error while running adapter at projects/flashtrade: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:217:11

**Comment by llamatester** [comment]
Error while running adapter at projects/flashtrade: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:217:11

**Comment by g1nt0ki** [comment]
@UjjwalGupta49 thanks for the PR

**Comment by llamatester** [comment]
Error while running adapter at projects/flashtrade: 
        
 
  
    
    
    AxiosError: Request failed with status code 429
    Truncated error stack:
        at settle (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/axios/dist/node/axios.cjs:1970:12)
        at IncomingMessage.emit (node:events:529:35)

**Pull request merged**
