### PR TITLE
Add Arcane Dex project

### PR DESCRIPTION
**Pull request by 0xandee**
##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/arcanedex: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:206:11

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
we prefer computing tvl on chain, can you share contract details. Also, can you please fill in rest of the PR form, I see a lot of blanks including category/website

**Comment by 0xandee** [comment]
> we prefer computing tvl on chain, can you share contract details. Also, can you please fill in rest of the PR form, I see a lot of blanks including category/website

Hi I fill the rest of PR form

**Comment by 0xandee** [comment]
> Error while running adapter at projects/arcanedex:
> 
> ```
> Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
> Truncated error stack:
> 
>     at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:206:11
> ```

what should we do if we don't have TVL

**Comment by g1nt0ki** [comment]
so, you are more of a dex aggregator rather than a dex?

**Comment by 0xandee** [comment]
> so, you are more of a dex aggregator rather than a dex? 

Yes that's right

**Comment by g1nt0ki** [comment]
okay, added volume adapter here, will be listed soon: https://github.com/DefiLlama/dimension-adapters/pull/1021/files

**Pull request closed without merging**
