### PR TITLE
Fix ram

### PR DESCRIPTION
**Pull request by flash-boys**
Fix TVL

### CODE REVIEW

**Comment by 0xngmi** [comment]
Thanks!

**Comment by flash-boys** [comment]
Hi, seems liked this is resolved but we are still delisted, when can we be relisted?

**Comment by 0xngmi** [comment]
Sorry I forgot to re-list, my bad. I'll clean up the data and re-list in a few hours :)

**Comment by flash-boys** [comment]
Here reminding you again mate still don't see it being relisted. Please kindly help us out, cheers

**Pull request merged**
