### PR TITLE
Add Secta Finance

### PR DESCRIPTION
**Pull request by 0xhedgie**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Secta Finance

##### Twitter Link:
https://twitter.com/SectaFinance

##### Website Link:
https://secta.finance/

##### Logo (High resolution, will be shown with rounded borders):
https://www.secta.finance/logo.png

##### Current TVL:
linea                     2.29 k

total                    2.29 k 

##### Chain:
Linea

##### Short Description (to be shown on DefiLlama):
Secta is a Linea-native decentralized exchange (DEX) and launchpad. It supports Uniswap V2 and V3 pools on the DEX and aims to be top interface into decentralized finance on Linea.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### forkedFrom (Does your project originate from another project):
PancakeSwap

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/secta-finance

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/secta exports TVL: 
        
 
 
    linea                     2.29 k
    
    total                    2.29 k

**Comment by 0xhedgie** [comment]
@llamatester should I set the TVL value on the PR description?

**Comment by 0xhedgie** [comment]
what should I prepare more to list secta on DefiLlama?

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
please split the adapter into two, one for v2 & v3 and use our helper function to compute the tvl on chain

**Comment by llamatester** [comment]
The adapter at projects/secta-v2 exports TVL: 
        
 
 
    linea                     2.53 k
    
    total                    2.53 k

**Comment by llamatester** [comment]
The adapter at projects/secta-v3 exports TVL: 
        
 
 
    linea                     148.13560009037687
    
    total                    148.13560009037687

**Comment by 0xhedgie** [comment]
@g1nt0ki @llamatester updated the PR following your request.

**Pull request merged**
