### PR TITLE
Feat: Add HiYield TVL

### PR DESCRIPTION
**Pull request by shallcdn**
##### Name (to be shown on DefiLlama):
HiYield

##### Twitter Link:

https://twitter.com/hiyield_xyz
##### Website Link:
https://www.hiyield.xyz/

##### Logo (High resolution, will be shown with rounded borders):
 - N/A

##### Current TVL:
- Avax:   1.89 M
- Canto: 1.02 M

##### Treasury Addresses (if the protocol has treasury)
- Canto: 0x0E4289a95207CA653b60B0eB0b5848f29F4C3f72
- Avax: 0x8475509d391e6ee5A8b7133221CE17019D307B3E, 0xce6050625fe3F79bBfC4d236aBAaBE51AB59e660

##### Chain:
- Avalanche
- Canto

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
-  N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
-  N/A

##### Short Description (to be shown on DefiLlama):
- Enabling access to traditional capital markets for web3 natives

##### Token address and ticker if any:
-  N/A

##### Category (full list at https://defillama.com/categories) *Please choose only one:
- RWA

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
-  N/A
##### Implementation Details: Briefly describe how the oracle is integrated into your project:
-  N/A
##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
-  N/A
##### forkedFrom (Does your project originate from another project):
-  N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
- Sums the total supply of HiYield's issued tokens.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/lydialabs/DefiLlama-Adapters

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/hiyield exports TVL: 
        
 
 
    avax                      1.89 M
    canto                     1.02 M
    
    total                    2.91 M

**Comment by g1nt0ki** [comment]
hi @shallcdn thanks for the PR, but I think you need to split it into two products, one is tokenization of treasury bills and such, other is lending, in the lending part only the amount left in contract should be counted as tvl and rest marked as borrowed

**Comment by theconnectooor** [comment]
> hi @shallcdn thanks for the PR, but I think you need to split it into two products, one is tokenization of treasury bills and such, other is lending, in the lending part only the amount left in contract should be counted as tvl and rest marked as borrowed

hi @g1nt0ki - thanks for reviewing our PR! i'm part of the HiYield team and would like to clarify one detail

our landing page may be misleading (being worked on), but HiYield no longer has a lend/borrow market and instead operates w/ a vault structure

our current deployment is similar to others in the 'RWA' category such as 'Maple RWA', 'OpenEden' and others where deposited USDC in our vaults is off-boarded to purchase the RWAs, which are then tokenized on-chain

similar to the other protocols, I was thinking the following would be the best methodology for calculating the TVL of HiYield's tokenized assets: 
_**methodology**: "Sums the total supply of HiYield's issued tokens."_

let us know what you think

**Comment by g1nt0ki** [comment]
got it, refactored and merged here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/9458

**Pull request closed without merging**
