### PR TITLE
update untangled tvl and borrowed

### PR DESCRIPTION
**Pull request by tanpx12**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/untangled exports TVL: 
        
 
 
    celo                      255.86 k
    celo-borrowed             255.83 k
    borrowed                  255.83 k
    
    total                    255.86 k

**Comment by g1nt0ki** [comment]
hi, think there was a mistake in the original adapter, tvl should be value not yet lent out, that is not the case here?

**Comment by tanpx12** [comment]
Hi, we have a different approach for the TVL value. We define TVL as the value of the pool value which includes the collateral value and its available reserve. So that is why we need this update.

**Comment by g1nt0ki** [comment]
atm, there is an on chain collateral + reserve of 255k? can you share the contract where it is locked?

**Comment by tanpx12** [comment]
Our pool instance address is 0x4f60444be7c10946b1b8d20032a7076357d6c5aa. You can see a NFT called Loan Asset Token which represent the real world asset that the borrower have deposited as collateral in the pool. The pool reserve is kept in a multisig wallet (0x5b7BA6471681C61b4994dC5072B0D0C0fFad4A2b), you can check the reserve value in this address. 

Pool Instance: https://celoscan.io/address/0x4f60444be7c10946b1b8d20032a7076357d6c5aa
Loan Asset Token mint: https://celoscan.io/address/0x4f60444be7c10946b1b8d20032a7076357d6c5aa#nfttransfers
Pot wallet: https://celoscan.io/address/0x5b7ba6471681c61b4994dc5072b0d0c0ffad4a2b

**Comment by g1nt0ki** [comment]
sorry, unsure how this slipped through, for similar (rwa) lending protocols, we treat only on chain collateral as tvl, sorry, we cant make an exception here. 

Can you update code to, count only tokens not yet lent out as tvl?

**Comment by untangled-finance** [comment]
Hi @g1nt0ki our protocol is very comparable to Centrifuge - You can see from CFG page here https://defillama.com/protocol/centrifuge their TVL" The pool value is made up of the NAV (the value of the assets in the pool) and the Pool Reserve (undeployed capital in the pool). "

In our case, as in the case of CFG, on chain collaterals consist of NFTs which are the financings in the pool

**Comment by g1nt0ki** [comment]
yes, in centrifuge, we are counting only the tokens not yet lent out as tvl. The difference here, you are asking use NFT value as tvl, we can not do that as there is no independent way for us/the market to verify the NFT valuation. We said the same thing to Joltify recently: https://defillama.com/protocol/joltify-rwa#information

**Comment by untangled-finance** [comment]
Actually in centrifuge you counted both 
- when only "TVL" tab is active then TVL only counts reserve (token not yet lent out)
- when "borrowed" tab is active then TVL also counts the amount borrowed (ie token lent out, representing by NFT)

In the case of Untangled the TVL only counts reserve.

We should have the same way of reporting as in CFG for consistency and accuracy 

I have recorded a video for ease of reference @g1nt0ki @tanpx12  https://jam.dev/c/b40121da-9f9c-448b-a420-3d008d7d7c7f

**Comment by untangled-finance** [comment]
In fact in your example https://defillama.com/protocol/joltify-rwa#information - TVL is treated the same way as centrifuge - so only Untangled is currently incorrect 'borrowed' TVL

**Comment by g1nt0ki** [comment]
> In fact in your example https://defillama.com/protocol/joltify-rwa#information - TVL is treated the same way as centrifuge - so only Untangled is currently incorrect 'borrowed' TVL

what are you talking about, in your PR you are counting the same thing in both tvl and borrowed. We are perfectly fine showing the borrowed value

**Comment by untangled-finance** [comment]
Thanks. @tanpx12 please update the PR for the borrowed so we are consistent with both cases above

**Comment by llamatester** [comment]
The adapter at projects/untangled exports TVL: 
        
 
 
    celo-borrowed             255.87 k
    borrowed                  255.87 k
    celo                      31
    
    total                    30.99809611206

**Comment by tanpx12** [comment]
I've just updated the TVL back to the old one. Pls check.

**Comment by g1nt0ki** [comment]
@tanpx12 thanks, this is mostly good, but I still dont understand where the 30$ comes from, this is supposed to be the reserves left in the pot/pools? but also, how to get a pot linked to a pool, and the pot is a safe wallet? (Sorry for all the questions)

**Comment by tanpx12** [comment]
This 30$ is from some of our pilot pools. So before launching an actual pool, we create some pilot pools to test on mainnet and these pools are still recorded in the list of the pool that we have launched.

**Pull request merged**
