### PR TITLE
add Arrow Markets

### PR DESCRIPTION
**Pull request by TerrenceAddison**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Arrow Markets

##### Twitter Link:
https://x.com/ArrowMarkets

##### Website Link:
arrow.markets

##### Logo (High resolution, will be shown with rounded borders):
image

##### Current TVL:
~5k

##### Chain:
Avalanche

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): 
arrow-token

##### Short Description (to be shown on DefiLlama):
First of its kind hybrid web3 options platform, optimized for user experience (UX). Come and join us!

##### Token address and ticker if any:
ARROW - 0x5c5e384Bd4e36724B2562cCAA582aFd125277C9B

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Options

##### Implementation Details: Briefly describe how the oracle is integrated into your project: 
Determining option settlement price
##### methodology (what is being counted as tvl, how is tvl being calculated):
currently only considers staking as part of TVL.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/arrowmarkets exports TVL: 
        
 
 
    avax                      5.42 k
    
    total                    5.42 k

**Comment by g1nt0ki** [comment]
thanks for the PR, I have refactored and added it

**Comment by TerrenceAddison** [comment]
@g1nt0ki can you tell me how I can have our logo on the defillama page?

**Comment by TerrenceAddison** [comment]
@g1nt0ki also seems like the code you refactored separated TVL with staking, is that the supposed intent?

**Comment by g1nt0ki** [comment]
hi @TerrenceAddison , we will fix the logo to the one on this PR.

Regarding staking, yes: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Pull request closed without merging**
