### PR TITLE
Adapter for Alongside

### PR DESCRIPTION
**Pull request by sarascahya**
**NOTE**

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
AMKT-Circle

##### methodology (what is being counted as tvl, how is tvl being calculated): TVL is counted as the market cap of the index; which is calculated as totalSupply * marketPrice

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/alongside: 
        
 
  
    
    
    AxiosError: Request failed with status code 400

**Comment by g1nt0ki** [comment]
@sarascahya is the project live, also, how can I get index composition, I think your tvl would be sum of all underlying token values, right?

**Comment by JamesEBall** [comment]
@g1nt0ki Hi, our project is not live. We can fetch the sum of underlying values as our TVl (NAV) - this is our market cap

**Comment by JamesEBall** [comment]
@g1nt0ki Can DefiLlama keep API keys secure for us? We have a way we can feed you nav using a 3rd party service but you would need an API key.

**Comment by g1nt0ki** [comment]
@JamesEBall there must be contract holding all the underlying assets right? maybe you can share the contract and asset addresses?

**Comment by g1nt0ki** [comment]
@JamesEBall we have a way of keeping api keys safe, but I dont like relying on 3rd party api as it is a blackbox and our users cant verify tvl themselves

**Comment by JamesEBall** [comment]
@g1nt0ki The asset is backed by funds held in custody which back our asset, so we would have to share the API key to read the custodian account to get our NAV/TVL. The other option is we are partnering with an on-chain oracle which would be able to provide a verified source for our NAV but this is not ready yet.

**Comment by g1nt0ki** [comment]
hi @JamesEBall , I prefer the second option, we wait for it to go live?

**Comment by JamesEBall** [comment]
@g1nt0ki No problem. Yep if that is ok with you, can we leave this for a couple of weeks and we will get round to updating it. Cheers :)

**Review by ponury1990 — APPROVED** [review]

**Review by ponury1990 — APPROVED** [review]

**Review by ponury1990 — APPROVED** [review]

**Comment by llamatester** [comment]
The adapter at projects/alongside exports TVL: 
        
 
 
    ethereum                  2.09 M
    
    total                    2.09 M

**Comment by g1nt0ki** [comment]
@JamesEBall is the oracle ready?

**Comment by JamesEBall** [comment]
if you're happy with this implementation that works better for us. Considering NAV of the index almost always has price parity with market price

**Comment by Define101** [comment]
Is it live already?
The website does not work

**Comment by Define101** [comment]
And is alongside a fork from any other protocol?

**Comment by JamesEBall** [comment]
@Define101, Alongside is live - and no, it is not a fork of any other protocol.

**Pull request merged**
