### PR TITLE
Added warp-dex adapter

### PR DESCRIPTION
**Pull request by bro-n-bro-0**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

warp-dex

##### Twitter Link:

https://twitter.com/cyber_devs

##### Website Link:

https://cyb.ai/warp

##### Logo (High resolution, will be shown with rounded borders):

https://cyb.ai/warp.82cde4275b.png

##### Current TVL:

$364000

##### Chain:

bostrom (cosmos)

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

bostrom

##### Short Description (to be shown on DefiLlama):

Semantic non-deterministic Superintelligence consensus computer

##### Category (full list at https://defillama.com/categories) *Please choose only one:

[Services](https://defillama.com/protocols/Services)

##### forkedFrom (Does your project originate from another project):

Cosmos-sdk based

##### methodology (what is being counted as tvl, how is tvl being calculated):

Counts the liquidity on all pools.

##### Github org/user (Optional, if your code is open source, we can track activity):

https://github.com/cybercongress/go-cyber

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/warp-dex exports TVL: 
        
 
 
    bostrom                   0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/warp-dex exports TVL: 
        
 
 
    bostrom                   0
    
    total                    0

**Comment by bro-n-bro-0** [comment]
Hey! Can you lead me with the tokens registry? 
I've no idea where I need to map ibc and hashes or native tokens with coingecko ID to grab USD price and get non-zero TVL

**Comment by g1nt0ki** [comment]
@bro-n-bro-0 let me check

**Comment by g1nt0ki** [comment]
@bro-n-bro-0 are these pools x*y=k ?
can you put up a PR here to this repo to track bridged assets to your chain like stargaze here: https://github.com/cosmostation/chainlist/blob/main/chain/stargaze/assets.json

this will help us price the ibc tokens, (no need to add them to core token list) other option is adding mapping like what I just did

**Comment by bro-n-bro-0** [comment]
> @bro-n-bro-0 are these pools x*y=k ? can you put up a PR here to this repo to track bridged assets to your chain like stargaze here: https://github.com/cosmostation/chainlist/blob/main/chain/stargaze/assets.json
> 
> this will help us price the ibc tokens, (no need to add them to core token list) other option is adding mapping like what I just did

@g1nt0ki 
Yes, it's x*y=k pools. Like crescent 

I've added assets to cosmostation chainlist. Waiting for their review.
https://github.com/cosmostation/chainlist/pull/1102

**Comment by bro-n-bro-0** [comment]
hey @g1nt0ki ! 

The PR with the assets was merged 

https://github.com/cosmostation/chainlist/pull/1102

**Comment by bro-n-bro-0** [comment]
@g1nt0ki looks like it's still zero :( 

What the next steps?

**Comment by g1nt0ki** [comment]
we are not pricing it, let me check the coins server

**Comment by g1nt0ki** [comment]
think I found the issue, put up a PR: https://github.com/cosmostation/chainlist/pull/1120

**Comment by bro-n-bro-0** [comment]
> think I found the issue, put up a PR: [cosmostation/chainlist#1120](https://github.com/cosmostation/chainlist/pull/1120)

Alright, the 1120 is merged

**Comment by llamatester** [comment]
The adapter at projects/warp-dex exports TVL: 
        
 
 
    bostrom                   606.66 k
    
    total                    606.66 k

**Pull request merged**
