### PR TITLE
FNDZdao TVL Added

### PR DESCRIPTION
**Pull request by michaelsimdev**
##### Twitter Link: 
https://twitter.com/fndzDAO

##### List of audit links if any: 
https://github.com/FNDZdao/public/blob/main/FNDZ%20full%20platform%20%2B%20staking%20audit%2015%20June.pdf

##### Website Link: 
https://fndz.io

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://drive.google.com/file/d/1n0YbuE7eh7RNEm8lze5s9ch3BWc8nCgS/view?usp=sharing

##### Current TVL: 
522890

##### Chain: 
Binance Smart Chain

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
fndz-token

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
11452

##### Short Description (to be shown on DefiLlama):
FNDZ Protocol is an EVM-based protocol for a decentralized on-chain social trading platform. FNDZ makes copy trading simple by connecting users with an ecosystem of top performing cryptocurrency traders.

##### Token address and ticker if any:
https://bscscan.com/address/0x7754c0584372D29510C019136220f91e25a8f706

##### Category (full list at https://defillama.com/categories) *Please choose only one:
1.Dexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is comprised of tokens deposited to the trader vaults and index vaults and staked FNDZ.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/fndzdao exports TVL: 
        
 
 
    bsc                       527.24 k
    
    total                    527.24 k

**Comment by realdealshaman** [comment]
Hey @michaelsimdev , thanks for the PR, is there a way to have the TVL of FNDZ Protocol calculated using on-chain calls?

**Comment by michaelsimdev** [comment]
@realdealshaman Thanks for swift check. We calculated it on our backend. As you can see our app, we keep tracked history to show graph data. And we use that data to calculate TVL.

**Comment by michaelsimdev** [comment]
Should we have to pull out the staking value individually?
What can I do to add staking item for the fetch adapter?
bsc: {
fetch,
staking: calcStaking
}

Isn't working for that?

**Comment by g1nt0ki** [comment]
closing this PR and wait for new one with on chain adapter

**Pull request closed without merging**
