### PR TITLE
Add Rootstock Infrastructure Framework

### PR DESCRIPTION
**Pull request by jonathansmirnoff**
##### Logo (High resolution, will be shown with rounded borders):
RIF symbol 400X400px-01

##### Github org/user: https://github.com/riflabs/RIF-Token/

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/rsk-token exports TVL: 
        
 
 
    rsk                       137.30 M
    
    total                    137.30 M

**Comment by g1nt0ki** [comment]
RIF is a ERC677 token on rsk right, why should it's supply be counted as tvl?

**Comment by llamatester** [comment]
The adapter at projects/rsk-token exports TVL: 
        
 
 
    rsk                       161.59 M
    
    total                    161.59 M

**Comment by jonathansmirnoff** [comment]
@g1nt0ki thanks so much for your review. I loved the refactor that you did in my code.
You are right about the question that you asked. RIF token is used as a collateral in other protocol, such as [Rif On Chain](https://rifonchain.com/)
I will close this PR and open another one.

**Pull request closed without merging**
