### PR TITLE
Add Sharky TVL

### PR DESCRIPTION
**Pull request by cotemper**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Sharky

##### Twitter Link:
https://twitter.com/SharkyFi

##### Website Link:
https://sharky.fi

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
sharky

##### Current TVL:
$5.85M

##### Chain:
Solana

##### Short Description (to be shown on DefiLlama):
Sharky is the #1 escrowless NFT lending and borrowing protocol on Solana. Users can borrow SOL against their NFTs or Lend SOL and earn a high % APY. 

##### Category (full list at https://defillama.com/categories) *Please choose only one:
14 NFT Lending

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is the total principal of all current offers and taken loans.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/sharky exports TVL: 
        
 
 
    solana-borrowed           5.03 M
    solana-offers             803.93 k
    solana                    5.84 M
    borrowed                  5.03 M
    offers                    803.93 k
    
    total                    5.84 M

**Comment by llamatester** [comment]
The adapter at projects/sharky exports TVL: 
        
 
 
    solana                    5.84 M
    
    total                    5.84 M

**Review by Restuta — APPROVED** [review]

**Comment by g1nt0ki** [comment]
hi @cotemper thanks for the PR, I have refactored it a bit here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/5790

Instead of counting all loans, count only active loans and under 'borrowed' field, if you are fine with the changes I can merge it.

**Comment by cotemper** [comment]
> hi @cotemper thanks for the PR, I have refactored it a bit here: #5790
> 
> Instead of counting all loans, count only active loans and under 'borrowed' field, if you are fine with the changes I can merge it.

Hi, @g1nt0ki.
Thanks for your refactoring. Looks good to me.
I also wonder if we can also add `offers` above `borrowed`.

**Comment by Restuta** [comment]
@g1nt0ki just to make sure I understand, by counting "active loans" do you mean "taken loans" and NOT counting offers placed on the order books? If so why not? The SOL in those offers is still part of the platform TVL.

it's not a massive difference for us, since our utilization of the value locked is very high, but it could be for other protocols that don't use the order-book model

The current breakdown is as follows:

CleanShot 2023-04-03 at 21 15 22@2x

So it's 90% utilized, but we are in a somewhat unique position there.

**Comment by Restuta** [comment]
E.g. I noticed that TVL here https://github.com/DefiLlama/DefiLlama-Adapters/pull/3519 being counted as the value in amount borrowed + value in pools. I am assuming our "pools" (orderbooks) should also count then?

**Comment by g1nt0ki** [comment]
@cotemper we have an export key called "offers" but not many projects are using it and we are thinking of removing it. This is for funds probably available but still on user wallets
@Restuta I think approving frakt was a mistake on my part, need to refactor them at some point

Just so I understand: 

 - when an user offers a loan, is the SOL locked in a contract or remain in their wallet? if locked in contract, it should count towards tvl
 - I need some help here, technically the NFTs locked by the users while there is active loan count towards your tvl, but I dont know a good way to price SOL NFTs, can you recommend some reliable way to get floor price of NFTs? preferably some on chain oracles (I used chainlink prices for bluechip NFTs in Ethereum), maybe a reputed API would also work

**Comment by Restuta** [comment]
> when an user offers a loan, is the SOL locked in a contract or remain in their wallet? if locked in contract, it should count towards tvl

It is locked in the contract. It's like a one-sided order book. 

> I need some help here, technically the NFTs locked by the users while there is active loan count towards your tvl, but I dont know a good way to price SOL NFTs, can you recommend some reliable way to get floor price of NFTs? preferably some on chain oracles (I used chainlink prices for bluechip NFTs in Ethereum), maybe a reputed API would also work

Yeah, we were not thinking of counting those, since the pricing of NFTs is a highly complex topic. We are thinking of switching to https://docs.hellomoon.io/docs/nft-collection-listing-stats and/or https://docs.simplehash.com/reference/floor-price-model for pricing. I am not sure if they provide on-chain feeds, but for v1 I propose just ignoring the price of the collateral. 

I'd love to add it in v2 of this whenever we find a reliable source of pricing and decide how to do it. E.g. just taking floor price and multiplying by number of locked NFTs is probably not the best approach.

**Comment by Restuta** [comment]
@g1nt0ki I think TVL calculation is incorrect, I Looked at the dash:

https://defillama.com/protocol/sharky

Our TVL is ~5M, 250K sol

**Comment by Restuta** [comment]
If you are not counting borrowed volume, could you please elaborate why is that so? Is there a separate metric for that?

**Comment by g1nt0ki** [comment]
hi @Restuta , yeah, borrowed is shown as separate metric, try expanding tvl
image

users can enable the filter to include it in the chart 
image

**Pull request merged**
