### PR TITLE
feat: add sui tvl

### PR DESCRIPTION
**Pull request by anxia0818**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/cetus: 
        
 
  
    
    
    Error: 
        Unknown chain(s): sui
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file

**Comment by anxia0818** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by anxia0818** [comment]
add sui chain in projects/helper/chains.json

**Comment by anxia0818** [comment]
Can it only be obtained through on-chain calls now? Is it not compatible with previous api acquisition?

**Comment by anxia0818** [comment]
@g1nt0ki

**Comment by g1nt0ki** [comment]
@anxia0818 I prefer on chain adapters where it is possible, they are less of a blackbox, users can see the logic, tend to break less often and we have a chance to fix it when it breaks compared to relying on APIs

**Comment by g1nt0ki** [comment]
@anxia0818 I have added on chain adapter here, can you review it? also, is there some way to review the token list? right now, I am seeing two USDC tokens on cetus

**Comment by g1nt0ki** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters/blob/321ddfea4428f7b875668651d2ff38d40fdb052e/projects/cetus/index.js#L4

**Comment by g1nt0ki** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters/blob/321ddfea4428f7b875668651d2ff38d40fdb052e/projects/cetus/index.js

**Comment by anxia0818** [comment]
tvl value is correct thanks!

**Pull request closed without merging**
