### PR TITLE
veritableDAO tvl calculations initial commit

### PR DESCRIPTION
**Pull request by veritable-dao**
##### Twitter Link:
https://twitter.com/VeritableDao

##### Website Link:
https://veritable.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
logo.svg in repository

##### Current TVL:
10$

##### Chain:
Polygon

##### Short Description (to be shown on DefiLlama):
Truly decentralized approach of the **DAO** control ⚖️

##### Token address and ticker if any:
0x6397835430a5a5f8530F30C412CB217CE3f0943b

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Yield

##### methodology (what is being counted as tvl, how is tvl being calculated):
Fetch liquidity in QuickSwap pair using subgraph of QuickSwap, and get balances of collateral using polygon scan api, and Coingecko prices.

### CODE REVIEW

**Comment by waynebruce0x** [comment]
can this be calculated using on-chain calls instead? masterChefExports() from /projects/helper/masterchef.js might be useful

**Comment by veritable-dao** [comment]
Damn :( I look for this function and for me it's hard to understand, can you help with that on-chain calls?

**Comment by waynebruce0x** [comment]
yeah no worries - masterchef is 0xE139E30D5C375C59140DFB6FD3bdC91B9406201c and VRT is 0x6397835430a5a5f8530F30C412CB217CE3f0943b?

**Comment by veritable-dao** [comment]
Yes correct, thank you!

**Comment by veritable-dao** [comment]
Hi, i guess it should be 10$ because of initial liquidity of VRT-USDC pair, and also we need to redeploy MasterChef contract, because we got mistake with start/end time is this ok to change address of it in near future ?

**Comment by waynebruce0x** [comment]
Yeah its fine to change the masterchef, just submit a PR with the change when its ready. I'll close this PR, merge the PR I made, and should be listed in the next 24 hours

**Pull request closed without merging**
