### PR TITLE
Heliswap DEX

### PR DESCRIPTION
**Pull request by RAMTO**
##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
Heliswap

##### Short Description (to be shown on DefiLlama): 
The first DEX on the Hedera network supporting swaps between HTS, ERC20s and HBAR. Open-sourced, completely trustless and permissionless. Built on the Hedera Smart Contract Service with the aim to become the defacto AMM being a public good within the network.

##### methodology (what is being counted as tvl, how is tvl being calculated):
Some note: 
Calling read contract methods on Hedera network is not free. 
So HeliSwap dex is using additional backend listening for contract events from the mirror node.
That's the reason the `fetch` method is used here, although is not recommended by your side.

Steps for TVL calculation.
1. Request to IPFS in order to get a list of whitelisted tokens
2. Calling an internal endpoint with whitelisted tokens addresses as param. Endpoint is returning all pools data, with the current tvl denominated in USD.
3. Aggregating the total TVL from all pools.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/heliswap exports TVL: 
        
 
 
    
    total                    7.23 M

**Comment by RAMTO** [comment]
> The adapter at projects/heliswap exports TVL:
> 
> ```
> total                    7.23 M 
> ```

I guess current TVL is constantly changing, now I see is $7.25 M

**Comment by llamatester** [comment]
Error while running adapter at projects/heliswap: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:201:11

**Comment by g1nt0ki** [comment]
hi @RAMTO thanks for the PR, it looks good. do you mind creating a PR for dex volume as well? we have some documentation here: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/volumes/README.md

**Comment by g1nt0ki** [comment]
I just removed the try catch block as we like to be notified if something breaks

**Comment by RAMTO** [comment]
> hi @RAMTO thanks for the PR, it looks good. do you mind creating a PR for dex volume as well? we have some documentation here: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/volumes/README.md

Thanks for merging
Will start working on volumd data as well :)

**Pull request merged**
