### PR TITLE
Add BlastName project

### PR DESCRIPTION
**Pull request by blastnamedev**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
BlastName

##### Twitter Link:
https://twitter.com/BlastName_

##### Website Link:
https://blastname.com

##### Logo (High resolution, will be shown with rounded borders):
https://app.blastname.com/static/img/bns.png

##### Current TVL:
$1,450,577

##### Chain:
Blast

##### Short Description (to be shown on DefiLlama):
The 1st decentralized domain name built on Blast

##### Token address and ticker if any:
0x0c2fFacD70c1D1CB04D4803Dea055DD9D4B57601

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Services

##### forkedFrom (Does your project originate from another project):
ENS

##### methodology (what is being counted as tvl, how is tvl being calculated):
Staking pools, Bank

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/orgs/BlastNameCom

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/blastname exports TVL: 
        
 
 
    blast                     1.25 M
    
    total                    1.25 M

**Comment by blastnamedev** [comment]
The adapter's TVL is different from our TVL because it cannot get BND and BNS prices. Should I manually get our token's prices then add to the TVL?

**Comment by g1nt0ki** [comment]
@blastnamedev thanks for the PR moved LP tvl to pool2, we dont count NFT value as tvl so excluded it.

**Comment by llamatester** [comment]
The adapter at projects/blastname exports TVL: 
        
 
 
    blast                     810.23 k
    blast-pool2               473.54 k
    pool2                     473.54 k
    
    total                    810.23 k

**Pull request merged**
