### PR TITLE
Muuu update

### PR DESCRIPTION
**Pull request by wolfwarrier14**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/muuu exports TVL: 
        
 
 
    astar-staking             14.31 k
    astar                     78.70 k
    staking                   14.31 k
    
    total                    78.70 k

**Comment by llamatester** [comment]
The adapter at projects/muuu exports TVL: 
        
 
 
    astar-staking             14.69 k
    astar                     79.26 k
    staking                   14.69 k
    
    total                    79.26 k

**Comment by llamatester** [comment]
The adapter at projects/muuu exports TVL: 
        
 
 
    astar-staking             16.91 k
    astar                     101.57 k
    staking                   16.91 k
    
    total                    101.57 k

**Comment by llamatester** [comment]
The adapter at projects/muuu exports TVL: 
        
 
 
    astar-staking             16.91 k
    astar                     101.57 k
    staking                   16.91 k
    
    total                    101.57 k

**Comment by llamatester** [comment]
The adapter at projects/muuu exports TVL: 
        
 
 
    astar-staking             17.14 k
    astar                     102.08 k
    staking                   17.14 k
    
    total                    102.08 k

**Comment by g1nt0ki** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters/pull/6428 merged here

**Pull request closed without merging**
