### PR TITLE
Update: Torch Finance Rebrand its logo and name

### PR DESCRIPTION
**Pull request by 0xton**
##### Logo (High resolution, will be shown with rounded borders): https://drive.google.com/file/d/1OPa11BFSIFV70JxMJ9hWPG1cqXxOZ1kh/view?usp=sharing

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/torch exports TVL: 
        
 
 
    ton                       56.09 k
    
    total                    56.09 k

**Comment by llamatester** [comment]
The adapter at projects/torch exports TVL: 
        
 
 
    ton                       63.63 k
    
    total                    63.63 k

**Comment by g1nt0ki** [comment]
hi @0xton , what is this yield product? I dont see it on your website

**Comment by llamatester** [comment]
The adapter at projects/torch exports TVL: 
        
 
 
    ton                       71.58 k
    
    total                    71.58 k

**Comment by 0xton** [comment]
As the statistic dashboard shows, wallet means the pool balance and the liquidity is the position value we hold in the router contract.

image

**Review by Rezacb0413 — APPROVED** [review]

**Pull request merged**
