### PR TITLE
Kava Deploy ScrubMoney Draft

### PR DESCRIPTION
**Pull request by gaspare100**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/scrubKava: 
        
 
  
    
    
    TypeError: Cannot read properties of null (reading 'toLowerCase')
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/unknownTokens.js:119:47
        at Array.forEach (<anonymous>)
        at getTokenPrices (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/unknownTokens.js:118:19)

**Comment by llamatester** [comment]
The adapter at projects/scrubKava exports TVL: 
        
 
 
    kava                      0
    kava-staking              0
    kava-pool2                0
    staking                   0
    pool2                     0
    
    total                    0

**Comment by gaspare100** [comment]
We are deploying to Kava Scrub.money, please add. Will tweak when all steps are completed

**Comment by llamatester** [comment]
The adapter at projects/scrubKava exports TVL: 
        
 
 
    kava                      0
    kava-staking              0
    kava-pool2                0
    staking                   0
    pool2                     0
    
    total                    0

**Comment by gaspare100** [comment]
This code refactor removed almost 100k from TVL as it does not add our secondary chef. That was the reason why it was like that....

**Comment by gaspare100** [comment]
@g1nt0ki  please can we restore the version that works?

**Comment by gaspare100** [comment]
Feel free to contact me on Telegram @TheG100

**Comment by g1nt0ki** [comment]
@gaspare100 sorry for late reply, I have fixed the bug here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/4245

**Pull request merged**
