### PR TITLE
Add TVL adapters for Tonic

### PR DESCRIPTION
**Pull request by toniccash**
##### Name (to be shown on DefiLlama):
Tonic

##### Twitter Link:
https://twitter.com/tonic_cash

##### List of audit links if any:
None

##### Website Link:
https://tonic.cash

##### Logo (High resolution, will be shown with rounded borders):
Tonic Logo

##### Current TVL:
$1.12 k

##### Treasury Addresses (if the protocol has treasury)
None (We hadn't launched our token yet)

##### Chain:
Klaytn, WEMIX

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): 
None (We hadn't launched our token yet)

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): 
None (We hadn't launched our token yet)

##### Short Description (to be shown on DefiLlama):
Tonic is a decentralized privacy protocol that enhances the privacy of token transfers on an EVM-based blockchain, making it harder to track them. Forked from Tornado Cash, it currently supports Klaytn and WEMIX as the first-ever crypto mixer protocol.

##### Token address and ticker if any:
None (We hadn't launched our token yet)

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Privacy

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
None

##### forkedFrom (Does your project originate from another project):
Tornado Cash (https://defillama.com/protocol/tornado-cash)

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is the sum of the value of tokens currently deposited in the privacy pools and not yet withdrawn.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/tonic-cash exports TVL: 
        
 
 
    klaytn                    995.5528
    wemix                     127
    
    total                    1.12 k

**Comment by llamatester** [comment]
The adapter at projects/tonic-cash exports TVL: 
        
 
 
    klaytn                    995.9635000000001
    wemix                     127
    
    total                    1.12 k

**Comment by toniccash** [comment]
Our TVL just doubled to $3,874.947! 👏

**Comment by g1nt0ki** [comment]
@toniccash thanks for the PR

**Pull request merged**
