### PR TITLE
added kava and evmos adapters for Photonswap

### PR DESCRIPTION
**Pull request by photonswap-dev**
##### Twitter Link:
https://twitter.com/photonswap_fi

##### Website Link:
https://photonswap.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://photonswap.finance/photon.png

##### Current TVL:
469.14 k CRONOS
169.103953407637 KAVA 
9.709142530008137 EVMOS
##### Chain:
cronos
evmos
kava

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
photonswap

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
1533

##### Short Description (to be shown on DefiLlama):
Multichain AMM styled decentralized exchange (DEX) on Cronos, Kava and EVMOS

##### Token address and ticker if any:
0xbdd4e5660839a088573191A9889A262c0Efc0983 PHOTON on cronos
0xA8eFf8BB28c6193CBE8BcFb8276e9b1dD3380B13 PHOTON on evmos
0xA8eFf8BB28c6193CBE8BcFb8276e9b1dD3380B13 PHOTON on kava

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### forkedFrom (Does your project originate from another project):
UniswapV2

##### methodology (what is being counted as tvl, how is tvl being calculated):
Factory addresses are used to find the LP pairs. TVL is equal to the liquidity on the AMM.

### CODE REVIEW

**Comment by photonswap-dev** [comment]
> Error while running adapter at projects/photonswap:
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'call')
> Truncated error stack:
>     at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/abi/index.js:94:77
>     at new Promise (<anonymous>)
>     at Object.sdk.api.abi.call (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:106:18)
>     at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/getUsdUniTvl.js:51:47
> ```

On it.

**Comment by photonswap-dev** [comment]
@llamatester 

the latest push for multicall for Kava on master branch fixed the issue

**Comment by llamatester** [comment]
Error while running adapter at projects/photonswap: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'call')
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/abi/index.js:94:77
        at new Promise (<anonymous>)
        at Object.sdk.api.abi.call (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:106:18)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/getUsdUniTvl.js:51:47

**Comment by photonswap-dev** [comment]
--- cronos ---
crypto-com-chain          469.14 k
Total: 469.14 k 

--- kava ---
kava                      169.103953407637
Total: 169.103953407637 

--- evmos ---
evmos                     9.709142530008137
Total: 9.709142530008137 

--- tvl ---
crypto-com-chain          469.14 k
kava                      169.103953407637
evmos                     9.709142530008137
Total: 469.32 k 

------ TVL ------
cronos                    469.14 k
kava                      169.103953407637
evmos                     9.709142530008137

total                    469.32 k

**Comment by g1nt0ki** [comment]
> @llamatester
> 
> the latest push for multicall for Kava on master branch fixed the issue

ah, can you run `npm update` and commit the updated package-lock.json file?

**Comment by photonswap-dev** [comment]
> > @llamatester
> > the latest push for multicall for Kava on master branch fixed the issue
> 
> ah, can you run `npm update` and commit the updated package-lock.json file?

Committed updated package.json and package-lock.json after `npm update`
I didn't get issue in the start may be because I used `yarn install`?

**Comment by g1nt0ki** [comment]
> > > @llamatester
> > > the latest push for multicall for Kava on master branch fixed the issue
> > 
> > 
> > ah, can you run `npm update` and commit the updated package-lock.json file?
> 
> Committed updated package.json and package-lock.json after `npm update` I didn't get issue in the start may be because I used `yarn install`?

Yeah, I think so. Also, I think you are using an older version of node/npm, the package-lock file is bit messed up now. If you dont mind, I made similar changes in my PR here, and I would merge that instead? https://github.com/DefiLlama/DefiLlama-Adapters/pull/2927/files

**Pull request closed without merging**
