### PR TITLE
`trufin`: update contract address and tvl calculation

### PR DESCRIPTION
**Pull request by yash-trufin**
This is an update to the existing TruFin Adapter. The changes in the actual TVL calculation are minor.

We want to update some of the protocol information. I have only included the changes below. 

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/trufin exports TVL: 
        
 
 
    ethereum                  10.91 M
    
    total                    10.91 M

**Comment by llamatester** [comment]
The adapter at projects/trufin exports TVL: 
        
 
 
    ethereum                  10.82 M
    
    total                    10.82 M

**Comment by g1nt0ki** [comment]
think it is better to create a new listing for this vault: https://github.com/DefiLlama/DefiLlama-Adapters/commit/d0881734931adeb27a1d594b79559d7d3a34019a

**Comment by g1nt0ki** [comment]
hi @yash-trufin we dont want to update existing listing because it is a different category, hence created a new sub-listing: https://defillama.com/protocol/trufin-matic-lsd 

not sure why it is showing 0, it should fix itself soon

**Pull request closed without merging**
