### PR TITLE
Create Super OETH adapter

### PR DESCRIPTION
**Pull request by micahalcorn**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/super-oeth exports TVL: 
        
 
 
    base                      2.04 M
    
    total                    2.04 M

**Comment by g1nt0ki** [comment]
@micahalcorn thanks for the PR, I noticed that  part of superOETH  tvl comes from OETH, so excluded it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/11497

Also, noticed that part of OETH tvl comes from OETH itself because of the curve LP, so counting only the ETH part of curve LP in tvl.

Let me know if I got something wrong

**Comment by micahalcorn** [comment]
@g1nt0ki thank you for the quick review. Here are a few comments:

1) Super OETH should have a separate adapter. It's not simply OETH bridged to Base. It will be a different product with a different APY. OETH is bridged to both Arbitrum and Base but its TVL is already accounted for in Ethereum due to the wrapped nature (similar to wstETH).

2) I'm not sure OETH's protocol-owned tokens in Curve should be excluded. OETH is very similar in nature to frxETH with both implementing an AMO. Looking at [the Frax Ether adapter](https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/frax-ETH/index.js), it's TVL calculation simply returns the token supply whereas ours returned the vault holdings.

3) OETH happens to have two native staking strategy contracts right now, but this won't be the case in the future. Each time we max out the maximum number of validators in a cluster, we need to deploy a new contract for the next 500. Theoretically, there could be an infinite number of strategy contracts and we would need to update the adapter each time a new one is deployed.

Thanks again for your help.

**Comment by g1nt0ki** [comment]
hi @micahalcorn 

1. Different yes, but not different enough to warrent it's own listing imo especially when most backing it is OETH
2. was unaware of this, will look into fraxETH, you can look into our FRAX adapter implementation, there we exclude all FRAX part of the curve LP and other places
3. Yes, when next staking strategy contract is deployed, can you notify me? I can update the adapter to filter for staking strategies in the vault and use it, this way, it would be more dynamic

**Comment by rafaelugolini** [comment]
> 1. Different yes, but not different enough to warrent it's own listing imo especially when most backing it is OETH

I disagree with you here. If you think about risk management, OETH has only Native Staking + Curve AMO risk, while Super OETH is a new token that inherits OETH risks and adds bridge (wOETH) and Aerodrome AMO.

There is a nice image illustrating what I'm trying to say in [our docs](https://docs.originprotocol.com/protocol/super-oeth)

> 2. was unaware of this, will look into fraxETH, you can look into our FRAX adapter implementation, there we exclude all FRAX part of the curve LP and other places

That's an interesting point of view, but I think that even if it's protocol-owned liquidity, it's available on the market for others to acquire. It would be cool to at least have the option to see both

**Comment by g1nt0ki** [comment]
@micahalcorn I agree that there are different risk profiles but that doesnt affect the tvl of the system.

We have different pov of what tvl is, for defillama, it is money outside the system locked in the protocol, this is why are dont count FRAX part of curve LP owned by FRAX, for similar reason, we dont count LP staked in masterchef  contract of a dex because we already counting tokens backing the LP as part of dex tvl

**Comment by micahalcorn** [comment]
@g1nt0ki I understand your perspective on the TVL calculation.

Back on the topic of Super OETH having a separate adapter, I think it's important for DefiLlama users to see different APYs for OETH and Super OETH. It will be a material difference on the order of 300% higher (or more) for Super OETH. If they're both part of the same adapter, will it be possible for Super OETH to have a separate [yield-server](https://github.com/DefiLlama/yield-server) integration so that users can discover the double-digit yield it will offer?

**Comment by g1nt0ki** [comment]
I think yes, dont think you need multiple tvl adapters to show diff yields

**Pull request closed without merging**
