### PR TITLE
Added unshETH protocol on Ethereum

### PR DESCRIPTION
**Pull request by thepiandao**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

unshETH

##### Twitter Link:

twitter.com/unsheth_xyz

##### List of audit links if any:

n/a

##### Website Link:

unshETH.xyz

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

Transparent background: https://unsheth.xyz/unsheth.png

##### Current TVL:

~80k USD

##### Chain:

Ethereum mainnet

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

none yet - will update

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

none yet - will update

##### Short Description (to be shown on DefiLlama):

unshETH is a protocol that aims to further validator decentralization by creating a "marketplace" for staked ETH liquidity in which LSD protocols can compete for ETH by offering the best yield.

##### Token address and ticker if any:

USH  - 

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Liquid Staking

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

n/a

##### forkedFrom (Does your project originate from another project):

Frax ETH

##### methodology (what is being counted as tvl, how is tvl being calculated):

deposited ETH (as LSDs) + staked USH + SushiSwap LP staked

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/unsheth exports TVL: 
        
 
 
    ethereum                  60.23 k
    
    total                    60.23 k

**Comment by thepiandao** [comment]
yes the TVL adapter mentions this number

**Comment by thepiandao** [comment]
are there any changes you need us to make?

**Comment by realdealshaman** [comment]
@thepiandao Hi, thanks for the PR, and thank you for reaching out. Yes, we kindly ask you to remove the amount for the SushiSwap LP as that TVL is already accounted for in SushiSwap's TVL

**Comment by llamatester** [comment]
The adapter at projects/unsheth exports TVL: 
        
 
 
    ethereum                  61.38 k
    
    total                    61.38 k

**Comment by realdealshaman** [comment]
removed sushi tvl, will merge

**Comment by thepiandao** [comment]
Hi everyone, the ETH deposited number on Defillama is wrong. Can we pls fix
this?

**Pull request merged**
