### PR TITLE
feat: add frigg.eco tvl to DefiLlama

### PR DESCRIPTION
**Pull request by owieth**
##### Name (to be shown on DefiLlama):
frigg.eco

##### Twitter Link:
https://twitter.com/FriggEco

##### Website Link:
https://www.frigg.eco/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
Full Logo - Large - Black - Background Color

##### Chain:
Ethereum

##### Short Description (to be shown on DefiLlama):
Frigg - Invest in a sustainable Future.

##### Token address and ticker if any:
0x90D53b872ce6421122B41a290aCdD22a5eD931bd - ATT

##### Category (full list at https://defillama.com/categories) *Please choose only one:
RWA

<br class="Apple-interchange-newline">[RWA](https://defillama.com/protocols/RWA)

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
none

##### forkedFrom (Does your project originate from another project):
Fork from this repo

##### methodology (what is being counted as tvl, how is tvl being calculated):
Gets the value of all tokens managed through frigg.eco universe (tokensupply * face value of bond)

### CODE REVIEW

**Comment by g1nt0ki** [comment]
I see this a tokenisation of real world asset rather than 'options', can you explain how you determine the price of tokens issued?

**Comment by owieth** [comment]
@g1nt0ki The issuance price is determined in a contract with the client

**Comment by g1nt0ki** [comment]
> @g1nt0ki The issuance price is determined in a contract with the client

that is the price tokens are minted at right? but what is the market price? can users burn their tokens at this price at moment and get their money back?

Usually, for these cases, we rely on oracle price/coingecko listing or price taken from dex pool

**Comment by jack-ox** [comment]
> > @g1nt0ki The issuance price is determined in a contract with the client
> 
> that is the price tokens are minted at right? but what is the market price? can users burn their tokens at this price at moment and get their money back?
> 
> Usually, for these cases, we rely on oracle price/coingecko listing or price taken from dex pool

IssuancePrice determines the price of tokens when they are minted. During the lifecycle of the tokens, users cannot burn their tokens and redeem the issuancePrice. The tokens, however, are traded on Uniswap v3. However, due to shallow liquidity, it is very easy to manipulate pricing there. 

Disclaimer: we are still in the process of completing the 'mint' of the first $3m token. Hence, there is no uniswap pool yet. 

Would we be able to use the issuancePrice in the meantime? Thank you!

**Comment by g1nt0ki** [comment]
> > > @g1nt0ki The issuance price is determined in a contract with the client
> > 
> > 
> > that is the price tokens are minted at right? but what is the market price? can users burn their tokens at this price at moment and get their money back?
> > Usually, for these cases, we rely on oracle price/coingecko listing or price taken from dex pool
> 
> IssuancePrice determines the price of tokens when they are minted. During the lifecycle of the tokens, users cannot burn their tokens and redeem the issuancePrice. The tokens, however, are traded on Uniswap v3. However, due to shallow liquidity, it is very easy to manipulate pricing there.
> 
> Disclaimer: we are still in the process of completing the 'mint' of the first $3m token. Hence, there is no uniswap pool yet.
> 
> Would we be able to use the issuancePrice in the meantime? Thank you!

Regarding issuance price, is it priced against USD or ether? guessing usd (?) also, the decimals for it is always 11?

**Comment by jack-ox** [comment]
> > > > @g1nt0ki The issuance price is determined in a contract with the client
> > > 
> > > 
> > > that is the price tokens are minted at right? but what is the market price? can users burn their tokens at this price at moment and get their money back?
> > > Usually, for these cases, we rely on oracle price/coingecko listing or price taken from dex pool
> > 
> > 
> > IssuancePrice determines the price of tokens when they are minted. During the lifecycle of the tokens, users cannot burn their tokens and redeem the issuancePrice. The tokens, however, are traded on Uniswap v3. However, due to shallow liquidity, it is very easy to manipulate pricing there.
> > Disclaimer: we are still in the process of completing the 'mint' of the first $3m token. Hence, there is no uniswap pool yet.
> > Would we be able to use the issuancePrice in the meantime? Thank you!
> 
> Regarding issuance price, is it priced against USD or ether? guessing usd (?) also, the decimals for it is always 11?

It is always priced against USDC (hence, USD). Decimals for the ERC-20 tokens are always 18

**Comment by g1nt0ki** [comment]
@jack-ox I meant the issuance price, like this line:  https://github.com/DefiLlama/DefiLlama-Adapters/blob/a6589cd89d3dd1d9d7c643feb76c71771cd3b7a5/projects/frigg.eco/index.js#L23

**Comment by owieth** [comment]
> @jack-ox I meant the issuance price, like this line:
> 
> https://github.com/DefiLlama/DefiLlama-Adapters/blob/a6589cd89d3dd1d9d7c643feb76c71771cd3b7a5/projects/frigg.eco/index.js#L23

yeah for the current state, it's always 11 decimals but this will eventually change! (We'll update our listing)

**Comment by jack-ox** [comment]
Thanks for the review and merge @g1nt0ki. Should Frigg.eco show up automatically on defillamma then? Or are there extra steps that we need to take

**Comment by g1nt0ki** [comment]
it is listed now: https://defillama.com/protocol/frigg.eco

**Pull request merged**
