### PR TITLE
add stealthpad

### PR DESCRIPTION
**Pull request by CryptoSnowPrince**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
StealthPad

##### Twitter Link:
https://twitter.com/stealthpadxyz

##### Website Link:
https://stealthpad.xyz/

##### Logo (High resolution, will be shown with rounded borders):
logo-sm-3034e372

##### Current TVL:
75.65 k

##### Chain:
Ethereum

##### Short Description (to be shown on DefiLlama):
StealthPad is the next generation decentralized launch pad for stealth coins. We are your one stop platform for stealth launch bot sniper and anti rug fund.

##### Token address and ticker if any:
0xB18F98822C22492Bd6b77D19cae9367f3D60fcBf

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Launchpad

##### methodology (what is being counted as tvl, how is tvl being calculated):
Counts liquidity in lp lock contracts and tokens in token lock contract

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/stealthpad exports TVL: 
        
 
 
    ethereum                  75.44 k
    ethereum-staking          2.304407324869771
    staking                   2.304407324869771
    
    total                    75.44 k

**Comment by CryptoSnowPrince** [comment]
I want to add audit link again.
What should I do?

**Comment by g1nt0ki** [comment]
@CryptoSnowPrince sorry, there seems to be some confusion, I meant you can count your tokens in staking  contract under staking, not all tokens locked away - we cant do this as we are not doing it for any other locker protocol

I have made the changes here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/7390

you can share the audit link as a comment here or in the other PR and we will add it

**Comment by CryptoSnowPrince** [comment]
Umm.
Anyway, this is audit link.
https://github.com/cyberscope-io/audits/blob/main/1-tba/audit.pdf

**Comment by llamatester** [comment]
The adapter at projects/stealthpad exports TVL: 
        
 
 
    ethereum-staking          1.7255755013178307
    ethereum                  66.42 k
    staking                   1.7255755013178307
    
    total                    66.42 k

**Comment by CryptoSnowPrince** [comment]
So, totally, total  = staking +ethereum, is it right?

**Comment by CryptoSnowPrince** [comment]
And on my projects, there are many token locker and lp locker, staking.
So, I thin total tvl should add these parts.

**Comment by g1nt0ki** [comment]
> And on my projects, there are many token locker and lp locker, staking. So, I thin total tvl should add these parts.

the reason we dont include token tvl is, when I lock an LP, it has a cost: I need equivalent amount/value of ETH to be locked, but only locking tokens, I can mint million or billion and lock, and some lockers had billions in token tvl but only 1k$ liquidity was there, this is why we dont include locked tokens in tvl or staking.

**Comment by CryptoSnowPrince** [comment]
Yes, so, on the defiLlama page, we can see the option for staking and pool2.
I mean, when I add staking option, if I turn on staking toggle, tvl will include staking also.
Is it right?
So, I added staking option on my commit.

**Comment by g1nt0ki** [comment]
@CryptoSnowPrince no, in your commit, you were counting all locked tokens under staking right? I explained why we completely ignore locked tokens and not count it anywhere

**Comment by CryptoSnowPrince** [comment]
Really, Excuse me, it was my first commit and I did new commit after your explain.
Maybe it seems removed.
I will do again.

**Comment by CryptoSnowPrince** [comment]
Ah, I see staking option on the final code.
Thanks.

**Comment by CryptoSnowPrince** [comment]
I will wait to update defillama with my audit link and new tvl calculating.

**Pull request closed without merging**
