### PR TITLE
Add youves

### PR DESCRIPTION
**Pull request by bb4L**
##### Twitter Link:
https://twitter.com/youves_com

##### List of audit links if any:
not yet published

##### Website Link:
https://app.youves.com/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://drive.google.com/drive/folders/1JLbCghv_2DiWTYT6fjhCMNG1A7OmSSMK

##### Current TVL:
17,322,392.619

##### Chain:
Tezos mainnet

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
*NA*

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
*NA*

##### Short Description (to be shown on DefiLlama):
youves is a decentralised, non-custodial and self-governed platform for the creation and management of synthetic assets. Minters of synthetic assets earn a passive income in YOU, the governance token on youves.

##### Token address and ticker if any:
YOU - KT1Xobej4mc6XgEjDoJoHtTKgbD1ELMvcQuL

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Assets

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
ubinetic oracles, https://ubinetic.com/oracles/

##### forkedFrom (Does your project originate from another project):
No

### CODE REVIEW

**Comment by 0xngmi** [comment]
Some questions:
- Does the tvl reported include the uUSD minted?
- Does it include the pool2 on https://app.youves.com/liquidity ?

I don't think it does but I want to make sure

I'll also change the code to fetch xtz price directly from coingecko

**Comment by pascuin** [comment]
>  Does the tvl reported include the uUSD minted?

No it only counts the amount of xtz of all vaults

>  Does it include the pool2 on https://app.youves.com/liquidity

No

**Comment by 0xngmi** [comment]
https://defillama.com/protocol/youves

Listed some hours ago

**Comment by pascuin** [comment]
Very much appreciated! Would love to see this shared on Twitter from your end as well.

**Comment by 0xngmi** [comment]
We always share on twitter, there's just a queue of projects

**Pull request merged**
