### PR TITLE
add cgo finance

### PR DESCRIPTION
**Pull request by cougarswap**
##### Twitter Link:
https://twitter.com/cougarswap

##### List of audit links if any:
N/A

##### Website Link:
https://cgo.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://cgo.finance/logo.png

##### Current TVL:
$121,299 staked

##### Chain:
Cronos

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
https://www.coingecko.com/en/coins/cgo

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

##### Short Description (to be shown on DefiLlama):
Cougar Optimizer - The most ideal Yield Optimizer for leveraging different DeFi protocols and strategies to maximize user profits

##### Token address and ticker if any:
CGO: 0x869c3e35Ef9E5F50003D9a2A80f1D61d670D4CB6

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield Aggregator

##### methodology (what is being counted as tvl, how is tvl being calculated):
Tvl is exported from our API, sum all staked assets from pools.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/cgo-finance exports TVL: 
        
 
 
    cronos                    121.30 k
    
    total                    121.30 k

**Comment by g1nt0ki** [comment]
hi, can you update adapter to compute using on-chain calls instead?

**Comment by cougarswap** [comment]
hi @g1nt0ki ok, I have a question.
Some tokens in our pools is not available in coingecko, so their TVL is not included. How can we resolve it?

**Comment by llamatester** [comment]
The adapter at projects/cgo-finance exports TVL: 
        
 
 
    cronos-staking            10.58 k
    cronos-pool2              24.04 k
    cronos-masterchef         69.38 k
    cronos                    69.38 k
    staking                   10.58 k
    pool2                     24.04 k
    masterchef                69.38 k
    
    total                    69.38 k

**Comment by alexburch93** [comment]
hi @g1nt0ki I updated the cgo adapter, can you check?

**Comment by cougarswap** [comment]
hi @g1nt0ki I updated the cgo adapter, can you check? We're using on-chain method now

**Comment by g1nt0ki** [comment]
@cougarswap  thanks for fixing it so quickly, regarding your earlier question, we have a  `getTokenPrices` method in `unknownTokens`, it is a bit crude, tries to derive token price from LP.

I will merge the code and try to fetch the price of missing tokens

**Comment by alexburch93** [comment]
cool, thanks for your reply and your work. Glad to see my PR merged

**Comment by cougarswap** [comment]
cool, thanks for your reply and your work. Glad to see my PR merged

**Pull request merged**
