### PR TITLE
aded sparkling adapter

### PR DESCRIPTION
**Pull request by Jarekkkkk**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Sparkling Finance

##### Twitter Link:
https://twitter.com/SparklingF92798

##### List of audit links if any:
https://github.com/Sparkling-Finance/contract/blob/main/audit/Sparkling%20Finance%20Audit%20Report.pdf

##### Website Link:
https://sparkling-frontend-v1.vercel.app/

##### Logo (High resolution, will be shown with rounded borders):
sparkling-logo

##### Current TVL:
12.24 M

##### Chain:
sui

##### Short Description (to be shown on DefiLlama):
Sparkling Finance ensures the safety of sBUCK and BUCK for 
[Bucket Protocol](https://bucketprotocol.io/) on SuiNetwork

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Liquid Restaking

##### methodology (what is being counted as tvl, how is tvl being calculated):
staked BUCK token

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/sparkling exports TVL: 
        
 
 
    sui                       12.27 M
    
    total                    12.27 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
how is sparkling involved in sBUCk? bucket protocols seems to have implemented it: https://app.bucketprotocol.io/sbuck

**Comment by Jarekkkkk** [comment]
> how is sparkling involved in sBUCk? bucket protocols seems to have implemented it: https://app.bucketprotocol.io/sbuck

so our protocol is to provide some staking feature for the kinds of yield bearing assets. We help bucket protocol do the yield bearing feature for their BUCK with accumulated interest fees. our site will be launched soon

**Comment by g1nt0ki** [comment]
yeah, but the current contract belongs to bucket protocol right?

**Comment by Jarekkkkk** [comment]
> https://github.com/Sparkling-Finance/Audit/blob/main/Sparkling%20Finance%20Audit%20Report.pdf

yes, so Bucket team  built sBUCK contract first but we will have a generalized contract to accept any coin and create sCoin in our protocol in the future. We've already move the codebase to our protocol and update the audit report, kindly take a look

**Comment by g1nt0ki** [comment]
sorry, we cant count BUCK in bucket protocol's contract as your tvl. Please reach out once you are in production with your contracts and tvl

**Comment by Jarekkkkk** [comment]
> sorry, we cant count BUCK in bucket protocol's contract as your tvl. Please reach out once you are in production with your contracts and tvl

Excuse me sir, may I ask the reasons why we can't count BUCK as TVL? since our contract is responsible for providing yield bearing feature for any underlying tokens. Is it because we can't count resatking assets to TVL ?

**Comment by Jarekkkkk** [comment]
> > > sorry, we cant count BUCK in bucket protocol's contract as your tvl. Please reach out once you are in production with your contracts and tvl
> > 
> > 
> > Excuse me sir, may I ask the reasons why we can't count BUCK as TVL? since our contract is responsible for providing yield bearing feature for any underlying tokens. Is it because we can't count resatking assets to TVL ?
> 
> are you claiming that your team deployed and maintaining this and not bucket team? 0xc6ecc9731e15d182bc0a46ebe1754a779a4bfb165c201102ad51a36838a1a7b8

yes, the Bucket team is the first client of our re-staking service. We recognized the potential of Buck as yield-bearing tokens by distributing their fee revenue to users to become sDAI on Sui. The contract and SDK are handled from our side, but they have an urgent need for an ongoing incentive program, so they released the feature on their site ahead of us.

**Comment by g1nt0ki** [comment]
> > > > sorry, we cant count BUCK in bucket protocol's contract as your tvl. Please reach out once you are in production with your contracts and tvl
> > > 
> > > 
> > > Excuse me sir, may I ask the reasons why we can't count BUCK as TVL? since our contract is responsible for providing yield bearing feature for any underlying tokens. Is it because we can't count resatking assets to TVL ?
> > 
> > 
> > are you claiming that your team deployed and maintaining this and not bucket team? 0xc6ecc9731e15d182bc0a46ebe1754a779a4bfb165c201102ad51a36838a1a7b8
> 
> yes, the Bucket team is the first client of our re-staking service. We recognized the potential of Buck as yield-bearing tokens by distributing their fee revenue to users to become sDAI on Sui. The contract and SDK are handled from our side, but they have an urgent need for an ongoing incentive program, so they released the feature on their site ahead of us.

can you show some proof of this?

**Comment by Jarekkkkk** [comment]
> > > > > sorry, we cant count BUCK in bucket protocol's contract as your tvl. Please reach out once you are in production with your contracts and tvl
> > > > 
> > > > 
> > > > Excuse me sir, may I ask the reasons why we can't count BUCK as TVL? since our contract is responsible for providing yield bearing feature for any underlying tokens. Is it because we can't count resatking assets to TVL ?
> > > 
> > > 
> > > are you claiming that your team deployed and maintaining this and not bucket team? 0xc6ecc9731e15d182bc0a46ebe1754a779a4bfb165c201102ad51a36838a1a7b8
> > 
> > 
> > yes, the Bucket team is the first client of our re-staking service. We recognized the potential of Buck as yield-bearing tokens by distributing their fee revenue to users to become sDAI on Sui. The contract and SDK are handled from our side, but they have an urgent need for an ongoing incentive program, so they released the feature on their site ahead of us.
> 
> can you show some proof of this?

yes, so suiVision has already verified the package from Sparkling.finance
Screenshot 2024-05-03 at 7 00 38 PM


Also Bucket team has mentioned sparkling.finance in their latest interface. 

let me know if you still need anything

**Comment by llamatester** [comment]
The adapter at projects/sparkling exports TVL: 
        
 
 
    sui                       12.33 M
    
    total                    12.33 M

**Comment by g1nt0ki** [comment]
thanks for the details (and patience), will be listed soon :)

**Pull request closed without merging**
