### PR TITLE
Feat: Add Avalon Finance

### PR DESCRIPTION
**Pull request by jsmjsm**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### List of audit links if any: 
https://drive.google.com/file/d/1Gk8yEByAB4OSAsOi0xrXtQDMDjetTKDU/view

##### Website Link:
https://www.avalonfinance.xyz/

##### Current TVL:
- 108.54m

##### Chain:
Merlin

##### Short Description (to be shown on DefiLlama):
 The House of BTC: Borrowing and Lending

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Pyth

##### Implementation Details: Briefly describe how the oracle is integrated into your project: 
https://github.com/avalonfinancexyz/ORACLE

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
METH/USD: https://scan.merlinchain.io/address/0x1280036a9da98f35536c7ef07a78c97b38d10e40
MBTC/USD: https://scan.merlinchain.io/address/0x6717dc0d87a9bd6849f96948c29e8c8875c10096

##### forkedFrom (Does your project originate from another project):
AAVE 

##### methodology (what is being counted as tvl, how is tvl being calculated):
The value of asset in lending pool

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/avalonfinancexyz

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/avalon-finance: 
        
 
  
    
    
    Error: 
        Unknown chain(s): Merlin_Main, Merlin_Innovation
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file

**Comment by llamatester** [comment]
Error while running adapter at projects/avalon-finance: 
        
 
  
    
    
    Error: 
        Unknown chain(s): Merlin
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file

**Comment by llamatester** [comment]
Error while running adapter at projects/avalon-finance: 
        
 
  
    
    
    Error: Llama RPC error! methos: undefined 
    - host: https://merlin.blockpi.network/v1/rpc/public error: execution reverted
    - host: https://rpc.merlinchain.io error: execution reverted

**Comment by llamatester** [comment]
The adapter at projects/avalon-finance exports TVL: 
        
 
 
    merlin                    0
    merlin-borrowed           0
    borrowed                  0
    
    total                    0

**Comment by llamatester** [comment]
Error while running adapter at projects/avalon-finance: 
        
 
  
    
    
    Error: 
        Unknown chain(s): merlin_main_market, merlin_innovation_market
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file

**Comment by llamatester** [comment]
Error while running adapter at projects/avalon-finance: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:196:11

**Comment by llamatester** [comment]
Error while running adapter at projects/avalon-finance: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:196:11

**Comment by llamatester** [comment]
The adapter at projects/avalon-finance exports TVL: 
        
 
 
    merlin                    80.20 M
    merlin-borrowed           0
    borrowed                  0
    
    total                    80.20 M

**Comment by llamatester** [comment]
The adapter at projects/avalon-finance exports TVL: 
        
 
 
    merlin                    83.37 M
    merlin-borrowed           0
    borrowed                  0
    
    total                    83.37 M

**Comment by llamatester** [comment]
The adapter at projects/avalon-finance exports TVL: 
        
 
 
    merlin                    106.27 M
    merlin-borrowed           0
    borrowed                  0
    
    total                    106.27 M

**Comment by g1nt0ki** [comment]
@jsmjsm thanks for the PR

**Pull request merged**
