### PR TITLE
feat: add GAI staking to GOKU

### PR DESCRIPTION
**Pull request by jack-lvsjack**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/goku-money exports TVL: 
        
 
 
    manta                     62.07 k
    manta-staking             0
    staking                   0
    
    total                    62.07 k

**Comment by g1nt0ki** [comment]
hi @jack-lvsjack we are already counting the tokens backing GAI as tvl, thats why we dont want to include staked GAI under staking as that would be doublecounting

**Comment by llamatester** [comment]
The adapter at projects/betafinance exports TVL: 
        
 
 
    avax-borrowed             539.2466850562226
    avax                      52.08 k
    ethereum                  1.34 M
    ethereum-borrowed         17.82 k
    borrowed                  18.36 k
    
    total                    1.39 M

**Comment by llamatester** [comment]
Error while running adapter at projects/dhedge.js: 
        
 
  
    
    
    PromisePoolError: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0xcA11bde05977b3631167028862bE2a173976CA11","data":"0xbce38bd7000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000033000000000000000000000000000000000000000000000000000000000000066000000000000000000000000000000000000000000000000000000000000006e0000000000000000000000000000000000000000000000000000000000000076000000000000000000000000000000000000000000000000000000000000007e0000000000000000000000000000000000000000000000000000000000000086000000000000000000000000000000000000000000000000000000000000008e0000000000000000000000000000000000000000000000000000000000000096000000000000000000000000000000000000000000000000000000000000009e00000000000000000000000000000000000000000000000000000000000000a600000000000000000000000000000000000000000000000000000000000000ae00000000000000000000000000000000000000000000000000000000000000b600000000000000000000000000000000000000000000000000000000000000be00000000000000000000000000000000000000000000000000000000000000c600000000000000000000000000000000000000000000000000000000000000ce00000000000000000000000000000000000000000000000000000000000000d600000000000000000000000000000000000000000000000000000000000000de00000000000000000000000000000000000000000000000000000000000000e600000000000000000000000000000000000000000000000000000000000000ee00000000000000000000000000000000000000000000000000000000000000f600000000000000000000000000000000000000000000000000000000000000fe0000000000000000000000000000000000000000000000000000000000000106000000000000000000000000000000000000000000000000000000000000010e0000000000000000000000000000000000000000000000000000000000000116000000000000000000000000000000000000000000000000000000000000011e0000000000000000000000000000000000000000000000000000000000000126000000000000000000000000000000000000000000000000000000000000012e0000000000000000000000000000000000000000000000000000000000000136000000000000000000000000000000000000000000000000000000000000013e0000000000000000000000000000000000000000000000000000000000000146000000000000000000000000000000000000000000000000000000000000014e0000000000000000000000000000000000000000000000000000000000000156000000000000000000000000000000000000000000000000000000000000015e0000000000000000000000000000000000000000000000000000000000000166000000000000000000000000000000000000000000000000000000000000016e0000000000000000000000000000000000000000000000000000000000000176000000000000000000000000000000000000000000000000000000000000017e0000000000000000000000000000000000000000000000000000000000000186000000000000000000000000000000000000000000000000000000000000018e0000000000000000000000000000000000000000000000000000000000000196000000000000000000000000000000000000000000000000000000000000019e00000000000000000000000000000000000000000000000000000000000001a600000000000000000000000000000000000000000000000000000000000001ae00000000000000000000000000000000000000000000000000000000000001b600000000000000000000000000000000000000000000000000000000000001be00000000000000000000000000000000000000000000000000000000000001c600000000000000000000000000000000000000000000000000000000000001ce00000000000000000000000000000000000000000000000000000000000001d600000000000000000000000000000000000000000000000000000000000001de00000000000000000000000000000000000000000000000000000000000001e600000000000000000000000000000000000000000000000000000000000001ee00000000000000000000000000000000000000000000000000000000000001f60000000000000000000000000110c5b2e0ea7f286c8de0fa3b02509e13a5ca643000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d2000000000000000000000000000000000000000000000000000000000000000000000000000000005ab5dfc9209b5e363dbffa1329d0892a8c459e20000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d200000000000000000000000000000000000000000000000000000000000000000000000000000000ad70535fcdd4513390e4d5133a71190521c1559b000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d2000000000000000000000000000000000000000000000000000000000000000000000000000000000ec7337e3b72066097d812dc4daad50ca55bfe5e000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d200000000000000000000000000000000000000000000000000000000000000000000000000000000c9ffd707d27bebd7fffef5bd10d51944e5ce42af000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d2000000000000000000000000000000000000000000000000000000000000000000000000000000005189b38b4b751730ae9c77b37780497b94b7fe1e000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d2000000000000000000000000000000000000000000000000000000000000000000000000000000004d9d4a9e7a4fd5818718a3229d0b96247f4a46c1000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d2000000000000000000000000000000000000000000000000000000000000000000000000000000007454655ac21b78c0a4b68f906ba1ae4463410d65000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d20000000000000000000000000000000000000000000000000000000000000000000000000000000039c46b6c0e54d7aace0eee6678226e703b2c3d87000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d2000000000000000000000000000000000000000000000000000000000000000000000000000000002dfc6f97e100c1e5de7b5db9198060783904acd9000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d200000000000000000000000000000000000000000000000000000000000000000000000000000000747b93b429687f889df57ec475ee52e50e5745f7000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d2000000000000000000000000000000000000000000000000000000000000000000000000000000001c9f17a8fb79e032f375c8f2517855ecbe4d7fa8000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d200000000000000000000000000000000000000000000000000000000000000000000000000000000b297db568f23bab333a898b468014f3a31d38cdf000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d200000000000000000000000000000000000000000000000000000000000000000000000000000000135cd103ea836364c502fdbc37f4d1e38df70a97000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d2000000000000000000000000000000000000000000000000000000000000000000000000000000005620b746171c60c8edbdde584e76b1e0b1588509000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d20000000000000000000000000000000000000000000000000000000000000000000000000000000036b0d8276800ce6563ee733a1bb80571a2a7157b000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d2000000000000000000000000000000000000000000000000000000000000000000000000000000008aaf116a25cdeb899f8fee04722816300e6eb1aa000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d200000000000000000000000000000000000000000000000000000000000000000000000000000000f44da519cd3b709572729033debfd5c90e86ec2f000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d2000000000000000000000000000000000000000000000000000000000000000000000000000000000b14f4cb2c31d09234a3c797f286ebfbca6ad3a5000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d2000000000000000000000000000000000000000000000000000000000000000000000000000000001d09859dc0f150cf4856a03e3a4aa3a72f4f854b000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d20000000000000000000000000000000000000000000000000000000000000000000000000000000043ba9e03c0f2f797caceee977e7d190a994281a2000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d200000000000000000000000000000000000000000000000000000000000000000000000000000000e2f4091d6bb7c28b5d58d666153847c4be7b97c3000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d2000000000000000000000000000000000000000000000000000000000000000000000000000000009136b03c9e960a550dde2ad6e202aa9ab25ab652000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d200000000000000000000000000000000000000000000000000000000000000000000000000000000a2d975c10ae21f6bf647da01a9e4d47757f3ada6000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d20000000000000000000000000000000000000000000000000000000000000000000000000000000007ecfe247aa9735ecb0363c8b9bcbcd26e4ff62f000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d2000000000000000000000000000000000000000000000000000000000000000000000000000000004d922890bfede323a5809893b6b5ba8bec2ba255000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d20000000000000000000000000000000000000000000000000000000000000000000000000000000095fb7d850badec30733aeffb5d1058e7b84b43fd000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d20000000000000000000000000000000000000000000000000000000000000000000000000000000070886cb84b30d397e3bc9e5b2e8f9e0781049e15000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d20000000000000000000000000000000000000000000000000000000000000000000000000000000063320d008e05fb52cfe3b49ac9510b5a567a57fe000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d200000000000000000000000000000000000000000000000000000000000000000000000000000000503d8b82568a8156668ceeb0b7dcd672eddbf7e5000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d200000000000000000000000000000000000000000000000000000000000000000000000000000000ea9fcb9c99fe546a55ce3aaf038e50b6dc6a68af000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d2000000000000000000000000000000000000000000000000000000000000000000000000000000008c651c24ac4cb0ab83e2d966ef259348bc28f616000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d20000000000000000000000000000000000000000000000000000000000000000000000000000000078daf21f5b4d01ea61b2db4ec3818578c58116e8000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d2000000000000000000000000000000000000000000000000000000000000000000000000000000008c15de0c0342fe4315bf0d5382f257816918c76b000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d2000000000000000000000000000000000000000000000000000000000000000000000000000000009283b3f70179837d10cca8eeef7596a838b23fd7000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d200000000000000000000000000000000000000000000000000000000000000000000000000000000c9b9d7eb070623a24475093fbc0339c9716e01cd000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d200000000000000000000000000000000000000000000000000000000000000000000000000000000ffa98dab3adb6e3972c555cf4a60158085004c00000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d200000000000000000000000000000000000000000000000000000000000000000000000000000000cad6b88059033db43693fbaa6e383ee7ff6c6223000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d200000000000000000000000000000000000000000000000000000000000000000000000000000000c3f9e541c2a2499e9fc7ab01e056881c4d08513f000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d2000000000000000000000000000000000000000000000000000000000000000000000000000000002e7a006314761005cfa4a30565029315b1c5f6e2000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d200000000000000000000000000000000000000000000000000000000000000000000000000000000987c4ccc97444ca303691b01385d3c72a919723d000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d200000000000000000000000000000000000000000000000000000000000000000000000000000000f81a3bf58ada2e1732df1e842515086d1d7775c7000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d20000000000000000000000000000000000000000000000000000000000000000000000000000000056893268d6ad8f73bbf7235e9c96034bbdce3158000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d200000000000000000000000000000000000000000000000000000000000000000000000000000000192fd4a8f020e6d22cf3c0d6131f6da7cbd3b3f8000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d200000000000000000000000000000000000000000000000000000000000000000000000000000000a465a92076d129201cb24478bccd1185ab372a32000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d20000000000000000000000000000000000000000000000000000000000000000000000000000000029777d2eed6105ed9f4513c4d87afb993bd43ebe000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d200000000000000000000000000000000000000000000000000000000000000000000000000000000e1286e0792139041a47773463c51ed89ae78ef2f000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d2000000000000000000000000000000000000000000000000000000000000000000000000000000008e3d578605a4ab8dac4e874f4451165c8d90f76c000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d200000000000000000000000000000000000000000000000000000000000000000000000000000000965733a8f8675757aa3ad619db96685393f92114000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d200000000000000000000000000000000000000000000000000000000000000000000000000000000dd20912a0aecef53f9500cc7cf67a345f9303e4a000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d2000000000000000000000000000000000000000000000000000000000000000000000000000000005b177b3931e40a5fec7d960d1c6515eef12406b9000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000041c5918d200000000000000000000000000000000000000000000000000000000","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    Truncated error stack:
        at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
The adapter at projects/goku-money exports TVL: 
        
 
 
    manta                     225.95 k
    manta-staking             4.95 k
    staking                   4.95 k
    
    total                    225.95 k

**Comment by g1nt0ki** [comment]
closing this as there was no response

**Pull request closed without merging**
