### PR TITLE
Add symbiosis-finance project with fetch adapter

### PR DESCRIPTION
**Pull request by allush**
##### Twitter Link:
https://twitter.com/symbiosis_fi

##### List of audit links if any:
https://github.com/symbiosis-finance/audits/tree/master/Symbiosis%20Protocol

##### Website Link:
https://symbiosis.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://s2.coinmarketcap.com/static/img/coins/64x64/15084.png

##### Current TVL:
3100909.98474

##### Chain:
Ethereum, BNB chain, Avalanche, Polygon

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
symbiosis-finance

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
15084

##### Short Description (to be shown on DefiLlama):
Symbiosis aggregates decentralized exchange liquidity across any EVM and non-EVM networks. Swap any token and transfer liquidity. Yes, any.

##### Token address and ticker if any:
https://etherscan.io/token/0xd38bb40815d2b0c2d2c866e0c72c5728ffc76dd9
Ticker SIS

##### Category (full list at https://defillama.com/categories) *Please choose only one:
https://defillama.com/protocols/Cross%20Chain

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
No used.

##### forkedFrom (Does your project originate from another project):
No forked.

##### methodology (what is being counted as tvl, how is tvl being calculated):

TVL is the amount of liquidity in Symbiosis stable pools.
Simple sum.
Reference - https://app.symbiosis.finance/liquidity/pools

### CODE REVIEW

**Comment by g1nt0ki** [comment]
Hi,

can you please change the adapter to fetch tvl info from chain(s) instead of `fetch`

**Comment by waynebruce0x** [comment]
Yeah to echo what g1nt0ki said, can this be calculated using on-chain calls instead? We've got a guide on how to use our SDK here: https://docs.llama.fi/list-your-project/submit-a-project

Also we need TVL to be broken down chain by chain

**Comment by allush** [comment]
@g1nt0ki @waynebruce0x thanks for your feedback!
According recomendation https://docs.llama.fi/list-your-project/submit-a-project#which-adapter-type-should-i-develop we use fetch adapter. Now symbiosis-finance supports 4 EVM chains: ethereum, bnb, avalance and polygon. At nearest time we will support 2 non-ENV chains: terra and solana.

We thought it right to use the fetch adapter now, because after the introduction of non-EVM chains, we will not be able to fix SDK adapter to get tvl from solana and terra.

Using fetch adapter we wouldn't have to make changes. Right?

**Comment by waynebruce0x** [comment]
Projects like Ribbon use the SDK for their EVM chains and fetch for non-EVM chains. We'd still need TVL to be broken down by chain. Is the API open source? Whats being counted as TVL?

**Comment by llamatester** [comment]
The adapter at projects/symbiosis-finance/index.js exports TVL: 
        
 
 
    ethereum                  1.56 M
    avax                      1.03 M
    bsc                       1.73 M
    polygon                   1.89 M
    
    total                    6.22 M

**Comment by allush** [comment]
> The adapter at projects/symbiosis-finance/index.js exports TVL:
> 
> ```
> ethereum                  1.56 M
> avax                      1.03 M
> bsc                       1.73 M
> polygon                   1.89 M
> 
> total                    6.22 M 
> ```

Yes, it is correct :)

**Pull request merged**
