### PR TITLE
feat: starterra adapter

### PR DESCRIPTION
**Pull request by cryptoethic**
##### Twitter Link:
https://twitter.com/StarTerra_io

##### List of audit links if any:
https://github.com/auditmos/audits/blob/main/2021_08_21_STARTERRA.pdf

##### Website Link:
https://app.starterra.io/
##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://drive.google.com/file/d/1OkLhO3umUuYUE1HbkM97Y4G-54yVCoe3/view

##### Current TVL:
82 370 312.25
##### Chain:
Terra
##### Short Description (to be shown on DefiLlama):
StarTerra is a Gamified LaunchPad with lottery based + guaranteed allocations, Play2Earn and NFT Integration. Through our gamification you, the investor, can strategize your way into larger allocations and be send out into Universe to conquer other planets, moons and galaxies!

##### Token address and ticker if any:
STT  terra13xujxcrc9dqft4p9a8ls0w3j0xnzm6y2uvve8n
##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Staking
##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
we don’t use 
##### forkedFrom (Does your project originate from another project):
No
##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is the sum of Singel Asset Staking tokens i Liquidity pool tokens

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Can the LP tokens be exported as a separate 'pool2' property?

**Comment by cryptoethic** [comment]
@waynebruce0x please check if that is what was requested - another method thet returns TVL accumulated in LP tokens only (measured in ust)

**Comment by waynebruce0x** [comment]
Yes, your changes look good. Can this subtracted from the core 'tvl'?

**Comment by cryptoethic** [comment]
Should it be subtracted?

You mean that `fetch` should return TVL - TVL in pools?

**Comment by waynebruce0x** [comment]
yes, and pool2 should return TVL in pools

**Comment by cryptoethic** [comment]
@waynebruce0x I got it right now ;-) Could you please check?

**Review by waynebruce0x — APPROVED** [review]

**Pull request merged**
