### PR TITLE
Add Orbit Bridge

### PR DESCRIPTION
**Pull request by rlekdms**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI

---

##### Twitter Link:
https://twitter.com/Orbit_Chain

##### List of audit links if any:
https://github.com/orbit-chain/bridge-contract/blob/master/audit/Theori_OrbitBridge_2022_1Q.pdf

##### Website Link:
https://bridge.orbitchain.io/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://bridge.orbitchain.io/images/token/ORC.png

##### Current TVL:
277.31M

##### Chain:
AVAX, BSC, CELO, ETH, FANTOM, HARMONY, HECO, ICON, KLAYTN, POLYGON, MOONRIVER, OEC, ORBIT, XDAI, XRP 

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
"orbit-chain"

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
5326

##### Short Description (to be shown on DefiLlama):
‌Orbit Bridge is an interchain communication protocol that allows communication between heterogeneous blockchains. Through this, users can utilize the various assets of various chains in all dApps through simple transactions on each chain.

##### Token address and ticker if any:
ORC 0x662b67d00A13FAf93254714DD601F5Ed49Ef2F51
https://etherscan.io/token/0x662b67d00a13faf93254714dd601f5ed49ef2f51

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Bridge

##### methodology (what is being counted as tvl, how is tvl being calculated):
Tokens locked in Orbit Bridge contract are counted as TVL

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/orbitbridge exports TVL: 
        
 
 
    harmony                   0
    bsc                       4.62 M
    fantom                    0
    polygon                   397.21 k
    moonriver                 0
    icon                      89.90 k
    xdai                      0
    heco                      1.57 M
    ripple                    28.57 M
    orbit                     0
    ethereum                  236.81 M
    klaytn                    7.00 M
    okexchain                 0
    avalanche                 0
    celo                      71.183913
    
    total                    279.05 M

**Comment by g1nt0ki** [comment]
@rlekdms can you update code to compute tvl using on chain calls instead?

**Comment by rlekdms** [comment]
Sure, I'll update you soon.

**Comment by g1nt0ki** [comment]
closing this now, you can open a new one when the adapter is ready

**Pull request closed without merging**
