### PR TITLE
Upgrades of IntentX & Integration of Core Markets

### PR DESCRIPTION
**Pull request by lemonpac**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by g1nt0ki** [comment]
hi @lemonpac I will wait for you to fix the merge conflict and add some PR description before reviewing

**Comment by llamatester** [comment]
Error while running adapter at projects/core-markets: 
        
 
  
    
    
    Failed to decode `BigInt` value: `invalid digit found in string`
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/graphql-request/dist/index.js:359:31

**Comment by llamatester** [comment]
The adapter at projects/defiplaza.js exports TVL: 
        
 
 
    radixdlt                  4.06 M
    ethereum                  526.11 k
    
    total                    4.58 M

**Comment by llamatester** [comment]
Error while running adapter at projects/core-markets: 
        
 
  
    
    
    Failed to decode `BigInt` value: `invalid digit found in string`
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/graphql-request/dist/index.js:359:31

**Comment by llamatester** [comment]
The adapter at projects/defiplaza.js exports TVL: 
        
 
 
    radixdlt                  4.06 M
    ethereum                  525.78 k
    
    total                    4.58 M

**Comment by llamatester** [comment]
The adapter at projects/core-markets exports TVL: 
        
 
 
    blast                     130.77 k
    
    total                    130.77 k

**Comment by llamatester** [comment]
The adapter at projects/intentx exports TVL: 
        
 
 
    base                      2.80 M
    
    total                    2.80 M

**Comment by lemonpac** [comment]
Name (to be shown on DefiLlama): Core Markets
Twitter Link: https://twitter.com/Core_Markets
Website Link: https://core.markets
Logo (High resolution, will be shown with rounded borders): https://pbs.twimg.com/profile_images/1758619800165564416/Y1EVseO6_400x400.jpg
Chain: Blast
Short Description (to be shown on DefiLlama): Core Markets is a perpetuals intent-based platform on Blast
Token address and ticker if any:
Category (full list at https://defillama.com/categories) *Please choose only one: Derivatives
Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.): Binance
Implementation Details: Briefly describe how the oracle is integrated into your project: Binance price is used for PNL
Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage: https://docs.core.markets
methodology (what is being counted as tvl, how is tvl being calculated): It's being used as TVL the amount of user funds that are retained in the contract

**Pull request merged**
