### PR TITLE
remove v1 vault

### PR DESCRIPTION
**Pull request by shafu0x**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/dyad exports TVL: 
        
 
 
    ethereum                  3.95 M
    
    total                    3.95 M

**Comment by g1nt0ki** [comment]
hi @shafu0x thanks for the PR but why remove that vault, still see quite a bit of WETH in it

**Comment by shafu0x** [comment]
@g1nt0ki this vault is part of DYAD v1 which we don't use anymore. We have a new ETH vault in v2.

**Comment by shafu0x** [comment]
The new weth vault is 0x4fde0131694Ae08C549118c595923CE0b42f8299

which we already count.

**Pull request merged**
