### PR TITLE
update starswap name

### PR DESCRIPTION
**Pull request by fountainchen**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
We need to change the name of Starswap to ensure that it is the same as the one displayed on the website.
source: StarSwap
to: Starswap
In total, there are 3 areas that need to be fixed
Also the tokenInfo information is displayed incorrectly. The link needs to be changed to：
https://stcscan.io/main/tokens/detail/0x8c109349c6bd91411d6bc962e080c4a3::STAR::STAR
##### Twitter Link:
https://twitter.com/StarswapEN

##### Website Link:
https://starswap.xyz/

##### Short Description (to be shown on DefiLlama):
AMM and yield farm on Starcoin

##### Token address and ticker if any:
https://stcscan.io/main/tokens/detail/0x8c109349c6bd91411d6bc962e080c4a3::STAR::STAR
##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### methodology (what is being counted as tvl, how is tvl being calculated):
Starswap's TVL is achieved by making a call to it's API: https://swap-api.starcoin.org/main/v1/farmingTvlInUsd (Farming) and https://swap-api.starcoin.org/main/v1/syrupPoolTvlInUsd (Stake).

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/starswap-starcoin exports TVL: 
        
 
 
    starcoin                  1.17 M
    starcoin-staking          287.42 k
    staking                   287.42 k
    
    total                    1.17 M

**Comment by llamatester** [comment]
The adapter at projects/starswap-starcoin exports TVL: 
        
 
 
    starcoin                  1.17 M
    starcoin-staking          287.42 k
    staking                   287.42 k
    
    total                    1.17 M

**Comment by Define101** [comment]
Shouldn't be this Token Address? 
[0x8489f4554790f5a103f2b0398537eaee68b73884](https://blockscout.com/astar/address/0x8489f4554790F5A103F2B0398537eAEe68B73884)

**Comment by Define101** [comment]
We currently use blockscout explorer for Astar projects

**Pull request merged**
