### PR TITLE
final version of temp fix - tested

### PR DESCRIPTION
**Pull request by k05ta5**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/quantumx-network exports TVL: 
        
 
 
    elrond                    322.78 k
    
    total                    322.78 k

**Comment by g1nt0ki** [comment]
@k05ta5 thanks for the PR, I try to keep the dependencies on this repo to bare minimum, so it is handled slightly differently: https://github.com/DefiLlama/DefiLlama-Adapters/pull/6473

https://github.com/DefiLlama/sushi-analytics/commit/fc451781fbeee0fdd085f44b88d7ce152845971a

**Comment by k05ta5** [comment]
Hi @g1nt0ki and thanks for the comment.
Can you explain a bit better please?
The PR was not merged? And if so, how can I improve it in order to get merged? The two new packages are vital for the script

**Comment by g1nt0ki** [comment]
hi @k05ta5 sorry for late reply, your PR is merged with some changes: https://github.com/DefiLlama/DefiLlama-Adapters/pull/6473/commits

I understand that the npm libs are needed, but I have fixed it with a hack on the backend

**Comment by k05ta5** [comment]
Thank you for the explanation @g1nt0ki 😊💪

**Pull request closed without merging**
