### PR TITLE
Add Starkwars adapter 

### PR DESCRIPTION
**Pull request by cantlee**
Name (to be shown on DefiLlama):
StarkWars

Twitter Link:
https://twitter.com/starknet_wars

List of audit links if any:
no

Website Link:
https://www.starkwars.xyz/

Logo (High resolution, will be shown with rounded borders):
https://www.starkwars.xyz/logo.png

Current TVL:
0 USD

Treasury Addresses (if the protocol has treasury)
no

Chain:
starknet

Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
no

Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
no

Short Description (to be shown on DefiLlama):
StarkWars is the first massive interstellar game on Starknet, offering an immersive experience of space adventure. Explore unknown galaxies, build powerful empires, and engage in intense battles with other players, all within StarkWars.

Token address and ticker if any:
no

Category (full list at https://defillama.com/categories) *Please choose only one:
NFT

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
No

forkedFrom (Does your project originate from another project):
https://github.com/cantlee/DefiLlama-Adapters

methodology (what is being counted as tvl, how is tvl being calculated):
no

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/starkwars: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by llamatester** [comment]
Error while running adapter at projects/starkwars: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by llamatester** [comment]
The adapter at projects/starkwars exports TVL: 
        
 
 
    starknet                  0
    
    total                    0

**Comment by g1nt0ki** [comment]
sorry, we list defi projects not NFTs

**Pull request closed without merging**
