### PR TITLE
Parallel Finance - Yield Account

### PR DESCRIPTION
**Pull request by alvaroparallel**
Yield Account has been added into Parallel Super App.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/parallel-yield exports TVL: 
        
 
 
    
    total                    167.77 M

**Comment by alvaroparallel** [comment]
> The adapter at projects/parallel-yield exports TVL:
> 
> ```
> total                    167.77 M 
> ```

Thanks for your fast response, this number is correct.

**Comment by llamatester** [comment]
The adapter at projects/parallel-yield exports TVL: 
        
 
 
    
    total                    160.87 M

**Comment by g1nt0ki** [comment]
@alvaroparallel thanks for the PR, what is this yield TVL composed of?

**Comment by alvaroparallel** [comment]
> @alvaroparallel thanks for the PR, what is this yield TVL composed of?

Parallel Derivative Tokens is used to indicate the sDOT and cDOT free balances. These are derivative tokens that can be deposited into the money market and liquidity pools.

**Comment by g1nt0ki** [comment]
But the underlying is already counted in staking/crowdloan,  sorry but I dont think we can list this

**Comment by alvaroparallel** [comment]
> But the underlying is already counted in staking/crowdloan, sorry but I dont think we can list this

Free balances are not counted in staking and crowdloan, Our tvl is undercounted if this is not included.

**Comment by g1nt0ki** [comment]
I am bit confused, can you expand a bit on "free balances" part?

**Comment by Helen8** [comment]
When users stake or contribute to crowdloans, they get derivative tokens which are the cDOT, cKSM, sDOT, and sKSM. Users may not utilize them right away in other yield generating products, and the balance will remain in the parallel account. These are the free balance that will be subtracted from the yield account when the user chooses to supply on other products.

**Comment by g1nt0ki** [comment]
> When users stake or contribute to crowdloans, they get derivative tokens which are the cDOT, cKSM, sDOT, and sKSM. Users may not utilize them right away in other yield generating products, and the balance will remain in the parallel account. These are the free balance that will be subtracted from the yield account when the user chooses to supply on other products.

my point is, if it not used in any protocol why should it be counted? we are already counting the KSM/DOT backing the c/s tokens.

**Comment by alvaroparallel** [comment]
Hello @g1nt0ki, just for clarification, we are talking about 2 different concepts, the Yield TVL is not a double count, it is eventually the guarantee of tokens that are not used and can be used but that was not counted by the original asset. In short, if you lock 1DOT you will receive a 1SDOT or similar, and it is added to the TVL of MoneyMarket only when it is used in MoneyMarket, when the user decides not to use that money in MoneyMarket, that SDOT exists, but it is not reflected in any account. .. As a result, it should be listed as Yield TVL. Because it is effectively blocked but it has not been accounted for in any tool yet.

**Comment by g1nt0ki** [comment]
> 

yes, but we are counting 1 DOT as part of liquid staking tvl

**Comment by alvaroparallel** [comment]
> > 
> 
> yes, but we are counting 1 DOT as part of liquid staking tvl

Mr. G1ntoki, I think I am not expressing correctly the meaning of the derivatives.

If you bet 1 DOT, you will get an X amount of SDOT as derivative:
However, if you immediately sell that SDOT for another token, the original DOT remains locked for 21 days...
If your point was true, no one would be able to sell their tokens and acquire fresh money as the original DOT is locked for 21 days or 96 weeks (SDOT/CDOT).

As I explained, it is not double counting, they are completely different markets, with different sources of liquidity.

**Comment by g1nt0ki** [comment]
@alvaroparallel  same thing applies for stETH now, we count the underlying ETH, not stETH lying in wallets instead of protocols as yield

**Pull request closed without merging**
