### PR TITLE
update TVL info for vaultka new vault - rum

### PR DESCRIPTION
**Pull request by 0xKMG**
calculation: 

stakedAmount of hlp in the hlpStaking contract x hlp price

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/vaultka exports TVL: 
        
 
 
    arbitrum                  5.91 M
    
    total                    5.91 M

**Comment by g1nt0ki** [comment]
hi @0xKMG the code is good, but do you know how to price HLP on chain? right now we dont have price support for it and need to be added

**Comment by 0xKMG** [comment]
yes, let me update the repo with the code

**Comment by llamatester** [comment]
The adapter at projects/vaultka exports TVL: 
        
 
 
    arbitrum                  5.60 M
    
    total                    5.60 M

**Comment by llamatester** [comment]
The adapter at projects/vaultka exports TVL: 
        
 
 
    arbitrum                  5.42 M
    
    total                    5.42 M

**Comment by llamatester** [comment]
The adapter at projects/vaultka exports TVL: 
        
 
 
    arbitrum                  6.04 M
    
    total                    6.04 M

**Comment by 0xKMG** [comment]
hi @g1nt0ki, I have included the code for calculating HLP price, please note that the price is in 12 decimals. Feel free to refactor the code. Thanks a lot!

**Comment by llamatester** [comment]
The adapter at projects/vaultka exports TVL: 
        
 
 
    arbitrum                  6.04 M
    
    total                    6.04 M

**Comment by llamatester** [comment]
Error while running adapter at projects/vaultka: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Pull request merged**
