### PR TITLE
Add Cyberblast (Blast)

### PR DESCRIPTION
**Pull request by axel-storm**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/cyberblast: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:217:11

**Comment by g1nt0ki** [comment]
@axel-storm thanks for the PR, I have refactored the code here, but will wait with merging as there is no tvl: https://github.com/DefiLlama/DefiLlama-Adapters/pull/9126

**Comment by axel-storm** [comment]
@g1nt0ki thanks! We're not live yet on blast mainnet, should be in few hours

**Comment by g1nt0ki** [comment]
I have merged the other PR

**Pull request closed without merging**
