### PR TITLE
update which project staking falls under and remove "totalTVL" calc

### PR DESCRIPTION
**Pull request by Avedith**
Updating TVL calculation due to slight change in API response.
Also changing staking calc from Sphere Finance to Dyson

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/dyson-money: 
        
 
  
    
    
    Error: 
        Please move the following keys into the chain: staking
    
        We have a new adapter export specification now where tvl and other chain specific information are moved inside chain export.
        For example if your protocol is on ethereum and has tvl and pool2, the export file would look like:
        
            module.exports = {
              methodlogy: '...',
              ethereum: {
                tvl: 
                pool2:
              }
            }

**Comment by llamatester** [comment]
The adapter at projects/dyson-money exports TVL: 
        
 
 
    arbitrum                  29.32 k
    polygon                   295.05 k
    optimism                  21.06 k
    polygon-staking           7.83 M
    staking                   7.83 M
    
    total                    345.44 k

**Comment by llamatester** [comment]
The adapter at projects/sphere-finance exports TVL: 
        
 
 
    polygon                   1.001
    
    total                    1.001

**Comment by llamatester** [comment]
The adapter at projects/dyson-money exports TVL: 
        
 
 
    optimism                  20.98 k
    polygon                   292.37 k
    polygon-staking           7.82 M
    arbitrum                  29.01 k
    staking                   7.82 M
    
    total                    342.36 k

**Comment by llamatester** [comment]
The adapter at projects/sphere-finance exports TVL: 
        
 
 
    polygon                   1.003
    
    total                    1.003

**Comment by llamatester** [comment]
The adapter at projects/dyson-money exports TVL: 
        
 
 
    polygon                   292.10 k
    optimism                  21.15 k
    arbitrum                  29.62 k
    polygon-staking           7.77 M
    staking                   7.77 M
    
    total                    342.87 k

**Comment by llamatester** [comment]
The adapter at projects/sphere-finance exports TVL: 
        
 
 
    polygon                   1.002
    
    total                    1.002

**Comment by llamatester** [comment]
The adapter at projects/dyson-money exports TVL: 
        
 
 
    polygon                   294.21 k
    polygon-staking           8.10 M
    arbitrum                  29.41 k
    optimism                  21.07 k
    staking                   8.10 M
    
    total                    344.69 k

**Comment by llamatester** [comment]
The adapter at projects/sphere-finance exports TVL: 
        
 
 
    polygon                   14.63 M
    
    total                    14.63 M

**Comment by Avedith** [comment]
Using "net_worth_pools" instead of "net_worth" temporarily to display TVL whilst working on new on-chain adapter

**Pull request merged**
