### PR TITLE
Add Universe.XYZ Adapter

### PR DESCRIPTION
**Pull request by wfm-slava**
##### Twitter Link:
https://twitter.com/universe_xyz

##### List of audit links if any:
https://github.com/UniverseXYZ/xyzDAO-PM/tree/master/audits

##### Website Link:
https://universe.xyz

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
XYZ Light Logo
XYZ Dark Logo

##### Current TVL:
$147.1M

##### Chain:
ETHEREUM

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
universe-xyz

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
10979

##### Description/bio (to be shown on DefiLlama):
Universe XYZ - The NFT Universe Built on Ethereum
Launch your own community-driven NFT universe baked with social tools, media services, and distribution - underpinned by the native $XYZ token.

##### Token address and ticker if any:
0x618679df9efcd19694bb1daa8d00718eacfa2883 / $XYZ

##### Category (Yield/Dexes/Lending/Minting):
Yield

##### [Optional] ETH addresss (to receive a LlamaPunk):
0x9eCd0fa468E1757D3B716C43Ec06BBB5aB565D2f

### CODE REVIEW

**Comment by 0xngmi** [comment]
USDC_XYZ_SUSHI_LP_TOKEN is your pool2 token right? If so I'd like to separate it from the other TVL.

If that's okay I'll merge and apply the changes myself

**Comment by 0xngmi** [comment]
I'll interpret the silence as acceptance and go ahead and apply the changes, we can always revert these later or discuss this again later, don't hesitate to re-open this dicussion if that's the case.

**Comment by cezarparaschiv** [comment]
that's right @0xngmi, sorry for the late reply.

**Comment by realdealshaman** [comment]
Thank you for your contribution to Defillama. Your LlamaPunk has been sent: https://opensea.io/0x9ecd0fa468e1757d3b716c43ec06bbb5ab565d2f

**Pull request merged**
