### PR TITLE
feat: add adapter for sICX

### PR DESCRIPTION
**Pull request by Chunn**

### CODE REVIEW

**Comment by g1nt0ki** [comment]
Hi, what is being counted here is all ICX locked up in user's wallets? https://icon.community/learn/icx/

**Comment by Chunn** [comment]
> Hi, what is being counted here is all ICX locked up in user's wallets? https://icon.community/learn/icx/

@g1nt0ki That's right. Is there any problem?

**Comment by g1nt0ki** [comment]
Sorry, we dont list chain staking

**Comment by Chunn** [comment]
> Hi, what is being counted here is all ICX locked up in the user's wallets? https://icon.community/learn/icx/

@g1nt0ki Sorry, I was a bit misunderstanding. This is not the total amount of ICX locked in users' wallets, but the total amount of ICX that has been deposited into the contract for staking (the total amount of ICX held by the contract). Please references https://blog.balanced.network/what-is-sicx/
Thank you!

**Comment by g1nt0ki** [comment]
@Chunn can you provide the staking contract address, and update adapter to query chain api for tvl?

**Comment by llamatester** [comment]
The adapter at projects/sicx/index.js exports TVL: 
        
 
 
    
    total                    14.39 M

**Comment by g1nt0ki** [comment]
@Chunn my bad,it looks good. Sorry, but I refactored your code a bit, so now the tvl comes under chain name, and we fetch the icon price from coingecko (also, now the right tokens are reflected in the defillama listing)

Can you change your adapter to the code below:

    const axios = require("axios")

    const icxApiEndpoint = 'https://ctz.solidwallet.io/api/v3'
    const stakingContract = "cx43e2eec79eb76293c298f2b17aec06097be606e0"

    async function getBalance(address) {
        let response = await axios.post(icxApiEndpoint, {
            jsonrpc: '2.0',
            method: 'icx_getBalance',
            id: 1234,
            params: {
                address,
            }
        })
        return response.data.result
    }

    async function getTotalClaimableIcx() {
        let response = await getBalance(stakingContract)
        return parseInt(response, 16) / 10 ** 18
    }

    async function fetch() {
        let totalClaimableIcx = await getTotalClaimableIcx()
        return { 'icon': totalClaimableIcx }
    }

    module.exports = {
        timetravel: false,
        icon: { tvl: fetch },
    }

**Comment by g1nt0ki** [comment]
Also, is there some way to query the chain/rpc with a timestamp or block field, this way we can fetch historical data/fix old data if our server fails at some point

**Comment by Chunn** [comment]
>Can you change your adapter to the code below:

@g1nt0ki I've updated based on your comment. Thanks for your suggestion! 

>Also, is there some way to query the chain/rpc with a timestamp or block field, this way we can fetch historical data/fix old data if our server fails at some point

I'm not sure about what you need, but I guess you told me about the SDK to get data from the ICON network. It's here https://www.icondev.io/icon-sdks/javascript/javascript-api-reference
If I'm wrong, feel free to let me know. Thank you!

**Comment by llamatester** [comment]
The adapter at projects/sicx/index.js exports TVL: 
        
 
 
    icon                      14.17 M
    
    total                    14.17 M

**Comment by g1nt0ki** [comment]
> 



> > Can you change your adapter to the code below:
> 
> @g1nt0ki I've updated based on your comment. Thanks for your suggestion!
> 
> > Also, is there some way to query the chain/rpc with a timestamp or block field, this way we can fetch historical data/fix old data if our server fails at some point
> 
> I'm not sure about what you need, but I guess you told me about the SDK to get data from the ICON network. It's here https://www.icondev.io/icon-sdks/javascript/javascript-api-reference If I'm wrong, feel free to let me know. Thank you!

I  meant more like if I want to fetch the tvl a week ago or a month ago, it is not possible with the current adapter

**Pull request merged**
