### PR TITLE
add hyfi

### PR DESCRIPTION
**Pull request by mixtapee**
##### Twitter Link:
https://twitter.com/hyper_finance

##### List of audit links if any:
https://hyfi.pro/Hyper-Finance-Skynet-Scanning-Report.pdf

##### Website Link:
https://hyfi.pro

##### Contact Email:
liolivia207@gmail.com

##### Current TVL:
$216,793,264

##### Chain:
BSC

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
None

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
None

##### Description/bio (to be shown on DefiLlama):
Hyper Finance (HyFi.pro) is a decentralized aggregate mining platform based on the ‌Binance‌ Smart Chain.

##### Token address and ticker if any:
HYFI: 0x9a319b959e33369C5eaA494a770117eE3e585318

##### Category (Yield/Dexes/Lending/Minting):
Yield

### CODE REVIEW

**Comment by 0xngmi** [comment]
Thanks for submitting! Could you structure your adapter to follow the guidelines on https://docs.llama.fi/list-your-project/how-to-write-an-sdk-adapter?

**Comment by mixtapee** [comment]
May I ask that adapter must be SDK adapter on BSC?

**Comment by 0xngmi** [comment]
Yep, SDK adapters allow us to get historical values.

**Comment by mixtapee** [comment]
Sorry, can I use hyfi.js(fetch adapter)? Just like the autofarm.js.

**Comment by 0xngmi** [comment]
I have a strong preference for SDK-based adapters since we plan to display the TVL breakdown by currencies on our page in the future (and SDK adapters also allow us to get historical values), but if your pools constantly change I could also accept a fetch adapter, is that your case?

**Comment by 0xngmi** [comment]
API endpoint seems to be broken

**Comment by mixtapee** [comment]
sorry, late to reply this pr. I have update the api already.

**Comment by 0xngmi** [comment]
All good, just listed your project (it will take ~1 hour to show up on our site)

**Comment by mixtapee** [comment]
Hi, I can't find the project on Defi Llama, can you please give me the link for example like this: https://defillama.com/protocol/bunny ? Thanks.

**Comment by 0xngmi** [comment]
Just checked, effectively the adapter is failing with the following error:
```
UnhandledPromiseRejectionWarning: Error: unable to verify the first certificate
```
Which seems to break the SSL handshake

**Comment by mixtapee** [comment]
I google this Error and found the solution in stackoverflow, here is the link:

**Comment by 0xngmi** [comment]
The provided solution doesn't seem to work, getting the following error:
```
Loading latest certificates from https://mxr.mozilla.org/nss/source/lib/ckfw/builtins/certdata.txt?raw=1
Error: getaddrinfo ENOTFOUND mxr.mozilla.org
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'mxr.mozilla.org'
}
undefined



Couldn't download the latest Root CAs, but it's not a big deal.

Use "require('ssl-root-cas')" instead of "require('ssl-root-cas/latest')"
```

Using `require('ssl-root-cas')` alone doesn't work either.

Could you disable forced-https upgrades? Then I would be able to just query the http endpoint and avoid ssl.

**Comment by mixtapee** [comment]
okay, I will make the http endpoint later, do I need to pull request about the http?

**Comment by 0xngmi** [comment]
No need, just ping me and I'll update the adapter

**Comment by mixtapee** [comment]
The http endpoint is here: http://api.hyfi.pro/stat . Thanks for all your help!

**Comment by 0xngmi** [comment]
Thanks, I've already updated it.

**Pull request merged**
