### PR TITLE
Add sns treasuries and neuron fund

### PR DESCRIPTION
**Pull request by NikolasHai**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/neuronfund: 
        
 
  
    
    
    TypeError: Cannot create property 'coingecko:0' on string '1471890682371584'
    Truncated error stack:
        at Object.sumSingleBalance (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:108:25)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:306:16
        at Array.forEach (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:300:28)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:313:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:50:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:137:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)

**Comment by llamatester** [comment]
Error while running adapter at projects/neuronfund: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'add')
    Truncated error stack:
    
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/neuronfund/index.js:16:7)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:48:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:137:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:180:3

**Comment by llamatester** [comment]
The adapter at projects/neuronfund exports TVL: 
        
 
 
    icp                       0
    icp-staking               0
    staking                   0
    
    total                    0

**Comment by llamatester** [comment]
Error while running adapter at projects/snstreasuries: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'add')
    Truncated error stack:
    
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/snstreasuries/index.js:53:7)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:48:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:137:9
        at async Promise.all (index 1)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:180:3

**Comment by llamatester** [comment]
The adapter at projects/neuronfund exports TVL: 
        
 
 
    icp                       0
    icp-staking               0
    staking                   0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/neuronfund exports TVL: 
        
 
 
    icp                       0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/snstreasuries exports TVL: 
        
 
 
    icp                       0
    icp-staking               0
    staking                   0
    
    total                    0

**Comment by llamatester** [comment]
Error while running adapter at projects/snstreasuries: 
        
 
  
    
    
    AxiosError: Request failed with status code 408
    Truncated error stack:
        at settle (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/axios/dist/node/axios.cjs:1970:12)
        at IncomingMessage.emit (node:events:529:35)

**Comment by llamatester** [comment]
The adapter at projects/neuronfund exports TVL: 
        
 
 
    icp                       0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/snstreasuries exports TVL: 
        
 
 
    icp                       0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/neuronfund exports TVL: 
        
 
 
    icp                       0
    
    total                    0

**Comment by llamatester** [comment]
Error while running adapter at projects/snstreasuries: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:192:11

**Comment by llamatester** [comment]
The adapter at projects/neuronfund exports TVL: 
        
 
 
    icp                       0
    
    total                    0

**Comment by llamatester** [comment]
Error while running adapter at projects/snstreasuries: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:192:11

**Comment by llamatester** [comment]
The adapter at projects/neuronfund exports TVL: 
        
 
 
    icp                       0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/dexter-tezos exports TVL: 
        
 
 
    tezos                     0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/neuronfund exports TVL: 
        
 
 
    icp                       0
    
    total                    0

**Comment by llamatester** [comment]
Error while running adapter at projects/snstreasuries: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:192:11

**Comment by llamatester** [comment]
The adapter at projects/neuronfund exports TVL: 
        
 
 
    icp                       0
    
    total                    0

**Comment by llamatester** [comment]
Error while running adapter at projects/snstreasuries: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:192:11

**Comment by llamatester** [comment]
The adapter at projects/neuronfund exports TVL: 
        
 
 
    icp                       0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/snstreasuries exports TVL: 
        
 
 
    icp                       0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/treasury/nns.js exports TVL: 
        
 
 
    icp                       192.97 M
    
    total                    192.97 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/sns.js exports TVL: 
        
 
 
    icp                       61.26 M
    
    total                    61.26 M

**Comment by g1nt0ki** [comment]
@NikolasHai thanks for the PR, I fixed the ICP gecko id and moved it to treasury

**Pull request merged**
