### PR TITLE
Update UNIv3 subgraph api endpoint to include Optimism metrics

### PR DESCRIPTION
**Pull request by rajivpo**
https://github.com/Uniswap/uniswap-v3-info/blob/10e3d4daba3417854db4a02ef37b6b93da95dd09/src/apollo/client.ts#L24

Part of https://github.com/Uniswap/uniswap-v3-info/commit/0bc24999ada26836b708389bf0cae2f3fa69785f

### CODE REVIEW

**Comment by 0xngmi** [comment]
Nice, was just looking into this, but imo it may be better to separate the optimism TVL from the non-optimism tvl, do you know how we should go about doing that?

**Comment by rajivpo** [comment]
Optimism: https://api.thegraph.com/subgraphs/name/ianlapham/uniswap-optimism
Arbitrum: https://api.thegraph.com/subgraphs/name/ianlapham/uniswap-arbitrum-one

Source: https://github.com/Uniswap/uniswap-v3-info/blob/836a38d236595e0ac18ae470102556f55b1da788/src/apollo/client.ts#L52-L95

**Comment by 0xngmi** [comment]
cool, I'll make some changes

**Comment by 0xngmi** [comment]
btw, do you know if there a public RPC node for arbitrum mainnet? I checked https://developer.offchainlabs.com/docs/public_testnet but there seems to only be testnet stuff

**Comment by rajivpo** [comment]
don't, but will inquire

**Comment by rajivpo** [comment]
https://arb1.arbitrum.io/rpc

credit to @TransmissionsDev

**Comment by 0xngmi** [comment]
By any chance do you also know the chainId?

**Comment by rajivpo** [comment]
image

**Comment by 0xngmi** [comment]
Yeah just figured it out by calling eth_chainId, thanks tho

**Comment by 0xngmi** [comment]
Should we list arbitrum uniswap? the TVL is 0.000058$

**Comment by rajivpo** [comment]
lol uhhh maybe wait until there is more tvl?

**Comment by rajivpo** [comment]
@0xngmi seeing that you've added it, I'm going to close this PR

**Pull request closed without merging**
