### PR TITLE
Add Chiliz Governance Staking TVL

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/chiliz-governance-staking exports TVL: 
        
 
 
    chz                       82.99 M
    
    total                    82.99 M

**Comment by Jamesxik6** [comment]
Hey @g1nt0ki ! Thanks for merging this, any idea when it will be reflected in the UI please? Thanks!

**Comment by Jamesxik6** [comment]
Hey @g1nt0ki apologies to message again, I see that we are visible here -> https://defillama.com/protocol/chiliz-governance-staking#information

but we would like to be visible here https://defillama.com/chain/Chiliz did we do something wrong?

**Comment by g1nt0ki** [comment]
@Jamesxik6 protocols marked chain staking dont appear on chain page (same rule for other protocols in this category)

**Comment by Jamesxik6** [comment]
Hey @g1nt0ki seems like this is not visible anymore anywhere on Defillama.. Any reason why please? I also see you've added a "staking" catagory for governance native token TVL - does this mean it can now be added to https://defillama.com/chain/Chiliz ?

**Pull request merged**
