### PR TITLE
Electrowizy

### PR DESCRIPTION
**Pull request by googolev**
Updated vault address as we migrated to new contract

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/electrowizy exports TVL: 
        
 
 
    polygon                   80.37 k
    
    total                    80.37 k

**Comment by llamatester** [comment]
The adapter at projects/electrowizy exports TVL: 
        
 
 
    polygon                   160.49 k
    
    total                    160.49 k

**Comment by g1nt0ki** [comment]
thanks for the PR

**Comment by llamatester** [comment]
The adapter at projects/electrowizy exports TVL: 
        
 
 
    polygon                   80.25 k
    
    total                    80.25 k

**Pull request merged**
