### PR TITLE
[feat] Add Yupana adapter

### PR DESCRIPTION
**Pull request by LikoIlya**
##### Name (to be shown on DefiLlama):

Yupana.Finance

##### Twitter Link:

https://twitter.com/YupanaFinance

##### List of audit links if any:

[InferenceAG](https://github.com/InferenceAG/ReportPublications/blob/master/Inference%20AG%20-%20Madfish%20-%20Yupana%20-%20v1.0.pdf)

##### Website Link:

[Yupana.Finance](https://yupana.finance/)

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

[Logo](https://drive.google.com/file/d/1HnK1wdMIUxTVSHuq4wj-jOR483Dgf-hs/view)

##### Current TVL:

$170k

##### Chain:

[Tezos](https://defillama.com/chain/Tezos)

##### Short Description (to be shown on DefiLlama):

Yupana.Finance is an open-source, decentralized, and non-custodial lending protocol built to securely borrow and lend crypto assets via smart contracts. Depositors provide liquidity in the protocol, receiving passive income, while borrowers take overcollateralized loans.

##### Category (full list at https://defillama.com/categories) *Please choose only one:

[Lending](https://defillama.com/protocols/Lending)

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

[Harbinger](https://harbinger.live/)
[Ubinetic](https://ubinetic.com/oracles/)

##### methodology (what is being counted as tvl, how is tvl being calculated):

TVL counted as total locked liquidity, total borrows and total reserves of each underlying markets. Data gathered from GQL [backend](https://mainnet-api.yupana.finance/v1/graphql)

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/yupana exports TVL: 
        
 
 
    tezos-borrowed            31.21 k
    tezos                     194.07 k
    borrowed                  31.21 k
    
    total                    194.07 k

**Comment by realdealshaman** [comment]
Hey @LikoIlya thanks for the PR, the TVL to be reflected should actually just be the liquidity, the borrowed is then exported as borrowed. This way it doesn't get doublecounted when a users chooses to add the borrowed amount using the toggles. Seems that if we only used (entry.totalLiquid) for tvl and (entry.totalBorrowed) for borrowed, it would coincide with the tvl shown on they Yupana front-end

**Comment by LikoIlya** [comment]
> Seems that if we only used (entry.totalLiquid) for tvl and (entry.totalBorrowed) for borrowed, it would coincide with the tvl shown on they Yupana front-end.

Got it, thanks! Is it okay if `entry.reserves` will stay in TVL counting? Note that `reserves` consist of protocol emergency reserves and developer rewards. If it's okay, the last commit should be ok)

**Comment by LikoIlya** [comment]
The difference between front-end values and defillama is explained with not good price provider for Tezos coins at defillama's helpers. It uses [TezTools](https://api.teztools.io/token/prices) `usdValue` field, which shows outdated or strange prices, like BTC for 33k$ now or kUSD for 1.82$ (but must be around 1$)

**Comment by g1nt0ki** [comment]
> The difference between front-end values and defillama is explained with not good price provider for Tezos coins at defillama's helpers. It uses [TezTools](https://api.teztools.io/token/prices) `usdValue` field, which shows outdated or strange prices, like BTC for 33k$ now or kUSD for 1.82$ (but must be around 1$)

thanks for raising this issue, I will look for a fix

**Comment by realdealshaman** [comment]
was merged in another PR https://github.com/DefiLlama/DefiLlama-Adapters/pull/3819
will close this one

**Pull request closed without merging**
