### PR TITLE
Add Citadao (KNIGHT) adapter

### PR DESCRIPTION
**Pull request by joh90**
- Take from Uniswap V3 LP liquidity from KNIGHT / WETH Pool

**NOTE**

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
Name (to be shown on DefiLlama): citaDAO
Twitter Link: 
https://twitter.com/citadao_io

List of audit links if any: https://docsend.com/view/sfaj6is2r8tzr6rm

Website Link: Citadao.io

Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): https://drive.google.com/file/d/1hAnpO0PPchJwrAkkSkvTa86chdzFYg4i/view?usp=share_link

Current TVL: $1.09M (Based on KNIGHT/WETH)

Chain: Ethereum

Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list) citadao

Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000) 17515

Short Description (to be shown on DefiLlama): CitaDAO is a Decentralized Finance (DeFi) platform for Real Estate to be tokenized on-chain, built on the Ethereum ecosystem. CitaDAO aims to solve the lack of liquidity, access limitation, and lack of composability in the existing real estate ecosystem by creating interoperability with other DeFi applications / primitives that operate on the Ethereum protocol.

Token address and ticker if any: 0x3541A5C1b04AdABA0B83F161747815cd7B1516bC
KNIGHT
Category (full list at https://defillama.com/categories) *Please choose only one: RWA

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):  N/A

forkedFrom (Does your project originate from another project): N/A

methodology (what is being counted as tvl, how is tvl being calculated): This is calculated as the amount of tokens staked in the liquidity pool

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/citadao exports TVL: 
        
 
 
    ethereum                  1.09 M
    
    total                    1.09 M

**Comment by llamatester** [comment]
The adapter at projects/citadao exports TVL: 
        
 
 
    ethereum                  0
    ethereum-staking          197.06 k
    ethereum-pool2            183.83 k
    staking                   197.06 k
    pool2                     183.83 k
    
    total                    0

**Comment by joh90** [comment]
@g1nt0ki yeap this is good for listing, thanks!

we are planning to create another one for the properties TVL too, will make another PR for that

as for that should we create another folder or use this folder?

**Comment by g1nt0ki** [comment]
@joh90 since this listing doesnt have default tvl, I would recommend properties value as default tvl here
if you prefer different listing, that too works. Let me know if you need any help with computing tvl using our sdk.

**Comment by joh90** [comment]
hi @g1nt0ki, need some help to change the name from `citaDAO` to `CitaDAO` instead
for `Name (to be shown on DefiLlama):`
sorry for the change!

thanks!

**Comment by g1nt0ki** [comment]
no worries, it is done: https://github.com/DefiLlama/defillama-server/commit/aa5302c4e525c04ba413b6c90ec2c2da9289b5a9

**Comment by joh90** [comment]
thanks appreciated!

**Pull request merged**
