### PR TITLE
update inverse treasury

### PR DESCRIPTION
**Pull request by webmass**
Updating Inverse treasury:
added missing multisigs on L2s/sidechains and tokens (especially veAERO and veVELO)

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/treasury/inverse.js exports TVL: 
        
 
 
    polygon                   1.4134001709836799
    bsc                       3.54 k
    optimism                  2.04 k
    avax                      0
    arbitrum                  6.51 k
    base                      21.13 k
    ethereum-ownTokens        2.21 M
    ethereum                  5.08 M
    ownTokens                 2.21 M
    
    total                    5.11 M

**Comment by g1nt0ki** [comment]
@webmass thanks for the update

**Comment by webmass** [comment]
> @webmass thanks for the update

hey, is it not possible to account veAERO, veVELO etc? (the solidly forks "vote escrowed" locked tokens)

We have quite a few millions usd in those:
On optimisim:
https://debank.com/profile/0xa283139017a2f5bade8d8e25412c600055d318f8
On base:
https://debank.com/profile/0x586CF50c2874f3e3997660c0FD0996B090FB9764

**Comment by g1nt0ki** [comment]
@webmass it is possible but one needs to manually unwind them, like this: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/tangible/insurance-fund-base.js#L13

can you put up a PR with the change?

**Pull request merged**
