### PR TITLE
Add LeverageX (Javsphere) Earn side TVL

### PR DESCRIPTION
**Pull request by rogi-sh**
Today started the liquidity providing on the earn side of LeverageX. WETH, USDC and cbBTC can be provided.

### CODE REVIEW

**Comment by llamabutler** [comment]
The adapter at projects/javsphere exports TVL: 
        
 
 
    base-vesting              9.80 M
    vesting                   9.80 M
    base-staking              2.49 M
    staking                   2.49 M
    defichain_evm             0
    defichain_evm-staking     0
    defichain                 0
    base                      0
    
    total                    0

**Comment by rogi-sh** [comment]
Did i something wrong, because tvl seems still 0 but the result should be like 159$

**Comment by llamabutler** [comment]
The adapter at projects/javsphere exports TVL: 
        
 
 
    base-vesting              9.80 M
    vesting                   9.80 M
    base-staking              2.49 M
    staking                   2.49 M
    base                      158
    defichain_evm             0
    defichain_evm-staking     0
    defichain                 0
    
    total                    157.62397859518043

**Comment by rogi-sh** [comment]
@g1nt0ki ah thanks how i can add then a second address for the same logic?

**Comment by g1nt0ki** [comment]
can you share the address? I will update the code

**Comment by rogi-sh** [comment]
> can you share the address? I will update the code

@g1nt0ki Yes it is this address: 0xBF35e4273db5692777EA475728fDbBa092FFa1B3 this is the diamond contract without tokensCount and tokens function. Only tokens in it: WETH, USDC and cbBTC. Thank you

**Pull request merged**
