### PR TITLE
Add Yearn Ether

### PR DESCRIPTION
**Pull request by 0xkorin**
##### Name (to be shown on DefiLlama):
Yearn Ether

##### Twitter Link:
https://twitter.com/yearnfi

##### List of audit links if any:
https://chainsecurity.com/security-audit/yearn-yeth-smart-contracts/
https://chainsecurity.com/security-audit/yearn-yeth-periphery/
https://chainsecurity.com/security-audit/yearn-yeth-governance/
https://github.com/mixbytes/audits_public/tree/master/Yearn%20Finance/yETH-bootstrap

##### Website Link:
https://yeth.yearn.fi/

##### Logo (High resolution, will be shown with rounded borders):
https://github.com/SmolDapp/tokenAssets/blob/main/tokens/1/0x1bed97cbc3c24a4fb5c069c6e311a967386131f7/logo.svg

##### Current TVL:
6.4K ETH ($15M)

##### Treasury Addresses (if the protocol has treasury)
N/A

##### Chain:
Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list) 
yearn-ether

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

##### Short Description (to be shown on DefiLlama):
yETH is a user-governed liquidity pool token consisting of various Ethereum Liquid Staking Derivatives (LSTs). The yETH pool is an Automated Market Maker (AMM) for LSTs. Each LST in the yETH pool is priced according to the amount of [beacon chain](https://ethereum.org/en/upgrades/beacon-chain/) ETH it represents.

##### Token address and ticker if any:
`0x1BED97CBC3c24A4fb5C069C6E311a967386131f7` - yETH

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Indexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
N/A

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
Count the total amount of beacon chain Ether underlying the LSTs deposited in the yETH pool

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/yearn

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/yearn-ether exports TVL: 
        
 
 
    ethereum                  0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/yearn-ether exports TVL: 
        
 
 
    ethereum                  15.02 M
    
    total                    15.02 M

**Comment by llamatester** [comment]
The adapter at projects/yearn-ether exports TVL: 
        
 
 
    ethereum                  15.10 M
    
    total                    15.10 M

**Comment by g1nt0ki** [comment]
@0xkorin thanks for the PR, will be listed soon

**Pull request merged**
