### PR TITLE
update core 

### PR DESCRIPTION
**Pull request by naimesin**
Updated cVault.finance (CORE) TVL to include ecosystem and governance tokens. 

Additions include CoreDAO, Delta, and Fanny tokens and respective LPs. All included contracts originate from the cVault Finance team and 'cVault Finance: Deployer' address.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/core exports TVL: 
        
 
 
    ethereum-treasury         86.20 M
    ethereum-borrowed         22.04 M
    ethereum-staking          21.28 M
    ethereum                  131.21 M
    treasury                  86.20 M
    borrowed                  22.04 M
    staking                   21.28 M
    
    total                    131.21 M

**Comment by llamatester** [comment]
The adapter at projects/core exports TVL: 
        
 
 
    ethereum-staking          13.58 M
    ethereum                  12.59 M
    ethereum-treasury         44.48 M
    staking                   13.58 M
    treasury                  44.48 M
    
    total                    12.59 M

**Comment by g1nt0ki** [comment]
@naimesin thanks for the PR, I have refactored it a bit.

Native tokens are not included in tvl, nor is treasury or staking, hence the changes, for more info: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by Cah17** [comment]
👏

**Pull request merged**
