### PR TITLE
Add Reserve Treasury

### PR DESCRIPTION
**Pull request by KevinMoll-ls**
There is another PR to reference this treasury from data.ts in DefiLlama-Server repository

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/treasury/reserve.js exports TVL: 
        
 
 
    ethereum                  12.34 M
    ethereum-ownTokens        832.21 k
    ownTokens                 832.21 k
    
    total                    12.34 M

**Comment by llamatester** [comment]
Error while running adapter at projects/treasury/reserve.js: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/tokenMapping.js:75:50
        at Array.forEach (<anonymous>)
        at getUniqueAddresses (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/tokenMapping.js:75:13)
        at sumTokens2 (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/unwrapLPs.js:722:12)
        at sumTokens (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/sumTokens.js:64:12)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/sumTokens.js:48:25
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:29)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:143:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:131:29
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by g1nt0ki** [comment]
thanks for the PR

**Comment by llamatester** [comment]
The adapter at projects/treasury/reserve.js exports TVL: 
        
 
 
    ethereum                  12.23 M
    ethereum-ownTokens        820.74 k
    ownTokens                 820.74 k
    
    total                    12.23 M

**Pull request merged**
