### PR TITLE
add tvl of project pinkpea

### PR DESCRIPTION
**Pull request by 0xHumbert**
##### Twitter Link:
https://twitter.com/PinkPeaFinance

##### Website Link:
https://pinkpea.finance

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://pinkpea.finance/_nuxt/img/logo.150e75f.png

##### Current TVL:
4.6M

##### Chain:
aurora

##### Short Description (to be shown on DefiLlama):

PinkPea to enable everyone to safely access, control, self-manage, and grow their wealth
through a transparent and secure platform.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield Aggregator

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
ChainlinK

##### forkedFrom (Does your project originate from another project):
originate

##### methodology (what is being counted as tvl, how is tvl being calculated):
staked asset and staked lps

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Can this be calculated using onchain calls please?

**Comment by 0xHumbert** [comment]
modify to abi call

**Comment by llamatester** [comment]
The adapter at projects/pinkpea.js exports TVL: 
        
 
 
    
    total                    4.66 M

**Comment by llamatester** [comment]
The adapter at projects/pinkpea exports TVL: 
        
 
 
    
    total                    4.66 M

**Pull request merged**
