### PR TITLE
add Brickken (BKN)

### PR DESCRIPTION
**Pull request by xaler5**
##### Name (to be shown on DefiLlama):

Brickken

##### Twitter Link:

https://twitter.com/Brickken

##### List of audit links if any:

https://skynet.certik.com/projects/brickken
https://omniscia.io/brickken-protocol-token-implementation/
Coming soon: hacken

##### Website Link:

https://www.brickken.com

##### Logo (High resolution, will be shown with rounded borders):

https://drive.google.com/file/d/1v-584FE2o1XLiRn1tTOw3qWg-9lxTaTE/view?usp=sharing

##### Current TVL:

12,708,000 USD

##### Treasury Addresses (if the protocol has treasury)

https://etherscan.io/address/0x65b9eF846e9989c481c40c01Cb7F128ebf892916

##### Chain:

Ethereum, BSC

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

brickken

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

21822

##### Short Description (to be shown on DefiLlama):

Brickken enables businesses to create digital tokens backed by tokenized Real World Assets (RWA). Through the Token Suite, Clients can raise private or public capital by creating their own custom white-label token store & token offering. 
Capturing the whole token lifecycle, token issuers can also manage both their assets & investors under a seamless dashboard enabling cap table management, dividend distribution, and full investor - compliance.

##### Token address and ticker if any:

https://etherscan.io/token/0x0A638F07ACc6969abF392bB009f216D22aDEa36d

BKN

##### Category (full list at https://defillama.com/categories) *Please choose only one:

RWA

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

Chainlink, Uniswap v3 TWAP

##### forkedFrom (Does your project originate from another project):

N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):

We get the TVL as the value of the freely circulating number of BKNs, we don't differentiate between chains and we cumulate across all chains.

##### Github org/user (Optional, if your code is open source, we can track activity):

github.com/Brickken

Currently not open source, but will be available soon.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/brickken exports TVL: 
        
 
 
    ethereum                  11.67 M
    
    total                    11.67 M

**Comment by xaler5** [comment]
Can't really find the flag to allow mantainers to do modifications, is this deprecated or it's me that I can't find it anymore ?

**Comment by g1nt0ki** [comment]
we cant count circulating supply of your gov token as tvl: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by g1nt0ki** [comment]
*we could count staked token under staking, but that part is not yet live?

**Pull request closed without merging**
