### PR TITLE
Add new Ribbon vaults

### PR DESCRIPTION
**Pull request by kenchangh**
New vaults:
* SPELL
* BADGER
* Ribbon earn
* Pauser contract

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/ribbon exports TVL: 
        
 
 
    solana                    675.14 k
    avalanche                 1.40 M
    ethereum-staking          8.54 M
    ethereum                  85.49 M
    staking                   8.54 M
    
    total                    87.57 M

**Comment by llamatester** [comment]
The adapter at projects/ribbon exports TVL: 
        
 
 
    solana                    674.76 k
    avalanche                 1.40 M
    ethereum-staking          8.50 M
    ethereum                  85.48 M
    staking                   8.50 M
    
    total                    87.55 M

**Comment by llamatester** [comment]
The adapter at projects/ribbon exports TVL: 
        
 
 
    ethereum-staking          9.04 M
    solana                    660.03 k
    avax                      1.40 M
    ethereum                  85.16 M
    staking                   9.04 M
    
    total                    87.22 M

**Comment by g1nt0ki** [comment]
@kenchangh I have refactored the code a bit to reduce the no. of calls

**Pull request merged**
