### PR TITLE
breakdown predy versions

### PR DESCRIPTION
**Pull request by wshino**
The related PR is here:
https://github.com/DefiLlama/dimension-adapters/pull/532

We want to add fees for predy v3.2. I got the reply in the above PR:

```
 it seem tvl adapter does not have breakdown about v320
```

I got the example hydradex. What I want to do in this PR is to breakdown predy TVL into `(v2 and v2.2)`, `v3`, `v3.2`.

##### Name (to be shown on DefiLlama):

Predy Finance

--- FOLLOWING SECTIONS COPY PASTE FROM OUR BEFORE PR ---

Twitter Link:
https://twitter.com/predyfinance

List of audit links if any:
https://www.linkedin.com/posts/zokyo_predy-smart-contract-audit-reportzokyoio-activity-6914551796023627777-8jWC?utm_source=linkedin_share&utm_medium=member_desktop_web

Website Link:
https://www.predy.finance/

Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://user-images.githubusercontent.com/1442395/163708733-eadcbbdc-bf51-4372-922c-2f08b766db07.png

Current TVL:

projects/predy.js
total                    17.29 k 

projects/predy-v3/index.js
total                    5.17 k 

projects/predy-v320/index.js
total                    248.39 k 

Chain:
Arbitrum

Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
Short Description (to be shown on DefiLlama):
Introducing Predy V3.2 on Arbitrum, featuring Squart: a unique perpetual with DeFi gamma from Uniswap LP positions, offering portfolio margin for Squart and ETH trading, simplifying delta-neutral and leveraged LP positions, and addressing liquidity fragmentation by eliminating strikes.

specification:
Introducing Predy V3.2, now available on the Arbitrum chain, featuring our innovative product, "Squart."
Squart is a unique perpetual with DeFi native gamma derived from Uniswap LP positions. Long Squart positions receive a premium based on Uniswap's trading fees in exchange for negative gamma, while short positions pay premiums for positive gamma.
Predy V3.2 allows traders to utilize portfolio margin for Squart and ETH perpetual trading while simplifying the creation of delta-neutral and leveraged LP positions. Rest assured, LP positions will always remain in-range!
Squart addresses the liquidity fragmentation issue commonly found in perpetual options by eliminating strikes. This ensures positions consistently possess gamma, similar to at-the-money options.

Token address and ticker if any:
Category (full list at https://defillama.com/categories) *Please choose only one:
Derivatives

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

forkedFrom (Does your project originate from another project):

methodology (what is being counted as tvl, how is tvl being calculated):
USDC and WETH locked on predy contracts.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/predy-v3 exports TVL: 
        
 
 
    arbitrum                  5.17 k
    arbitrum-borrowed         160.77394171821499
    borrowed                  160.77394171821499
    
    total                    5.17 k

**Comment by llamatester** [comment]
The adapter at projects/predy-v320 exports TVL: 
        
 
 
    arbitrum                  248.28 k
    arbitrum-borrowed         147.46 k
    borrowed                  147.46 k
    
    total                    248.28 k

**Comment by llamatester** [comment]
The adapter at projects/predy.js exports TVL: 
        
 
 
    arbitrum                  17.28 k
    
    total                    17.28 k

**Comment by g1nt0ki** [comment]
hi @wshino thanks for the PR, api.js file is not needed here, so  I have refactored it here to remove it: https://github.com/DefiLlama/DefiLlama-Adapters/pull/6499/files

**Comment by wshino** [comment]
Thank you @g1nt0ki for reviewing and refactoring.

**Pull request closed without merging**
