### PR TITLE
feat(benddao): implement the sdk adapter

### PR DESCRIPTION
**Pull request by NiobiumZeit**
##### Twitter Link:

[Twitter BendDAO](https://twitter.com/BendDAO)

##### List of audit links if any:

- [Certik](https://www.certik.com/projects/bend-dao)

##### Website Link:

[Homepage](https://www.benddao.xyz)

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

[Google Drive](https://drive.google.com/drive/folders/1FTi3gCBEm7bSnV2ifUcSINuFPd1H4YWh?usp=sharing)

##### Current TVL:

65.148 ETH

##### Chain:

- Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

[benddao](https://www.coingecko.com/en/coins/benddao)

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

[bend-dao](https://coinmarketcap.com/currencies/bend-dao/)

##### Short Description (to be shown on DefiLlama):

BendDAO is a decentralized peer-to-pool based NFT liquidity protocol.

##### Token address and ticker if any:

- [Bend](https://etherscan.io/token/0x0d02755a5700414b26ff040e1de35d337df56218)

##### Category (full list at https://defillama.com/categories) *Please choose only one:

[NFT Lending](https://defillama.com/protocols/NFT%20Lending)

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

- [NFTOracle](https://etherscan.io/address/0x7C2A19e54e48718f6C60908a9Cff3396E4Ea1eBA)
- [ReserveOracle](https://etherscan.io/address/0x16ca3E500dA893cF2EEBb6b401247e68ca5BC072)

##### forkedFrom (Does your project originate from another project):

No

##### methodology (what is being counted as tvl, how is tvl being calculated):

ETH reserve and value of collateralized NFTs

### CODE REVIEW

**Comment by waynebruce0x** [comment]
does 'totalLiquidity' include borrowed funds?

**Comment by NiobiumZeit** [comment]
> does 'totalLiquidity' include borrowed funds?

no, it only include availableLiquidity (totalLiquidity - borrowed)

**Comment by NiobiumZeit** [comment]
any new updates in the pr?

**Comment by waynebruce0x** [comment]
Could you look at the conflicts? Then just need to check CI and merge

**Comment by NiobiumZeit** [comment]
@waynebruce0x resolved all conflicts caused by `package-lock.json`, can u merge it?

**Comment by llamatester** [comment]
The adapter at projects/benddao exports TVL: 
        
 
 
    ethereum-borrowed         36.40 M
    ethereum                  108.55 M
    borrowed                  36.40 M
    
    total                    108.55 M

**Pull request merged**
