### PR TITLE
Added package-lock.json again

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/astar-dapps-staking/index.js exports TVL: 
        
 
 
    polkadot                  399.84 M
    
    total                    399.84 M

**Comment by llamatester** [comment]
The adapter at projects/genshiro/index.js exports TVL: 
        
 
 
    polkadot                  3.63 M
    
    total                    3.63 M

**Comment by llamatester** [comment]
Error while running adapter at projects/karura-dex/index.js: 
        
 
 
    
        Unknown chain(s): kusuma
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file

**Comment by llamatester** [comment]
Error while running adapter at projects/karura-lending/index.js: 
        
 
 
    
        Unknown chain(s): kusuma
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file

**Comment by llamatester** [comment]
Error while running adapter at projects/karura-staking/index.js: 
        
 
 
    
        Unknown chain(s): kusuma
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file

**Comment by llamatester** [comment]
The adapter at projects/lightning-network/index.js exports TVL: 
        
 
 
    bitcoin                   153.77 M
    
    total                    153.77 M

**Comment by llamatester** [comment]
The adapter at projects/quarry/index.js exports TVL: 
        
 
 
    solana                    487.07 M
    
    total                    487.07 M

**Comment by llamatester** [comment]
The adapter at projects/astar-dapps-staking/index.js exports TVL: 
        
 
 
    polkadot                  399.84 M
    
    total                    399.84 M

**Comment by llamatester** [comment]
The adapter at projects/genshiro/index.js exports TVL: 
        
 
 
    polkadot                  3.62 M
    
    total                    3.62 M

**Comment by llamatester** [comment]
The adapter at projects/karura-dex/index.js exports TVL: 
        
 
 
    kusuma                    11.27 M
    
    total                    11.27 M

**Comment by llamatester** [comment]
The adapter at projects/karura-lending/index.js exports TVL: 
        
 
 
    kusuma                    15.48 M
    
    total                    15.48 M

**Comment by llamatester** [comment]
The adapter at projects/karura-staking/index.js exports TVL: 
        
 
 
    kusuma                    12.71 M
    
    total                    12.71 M

**Comment by llamatester** [comment]
The adapter at projects/lightning-network/index.js exports TVL: 
        
 
 
    bitcoin                   153.80 M
    
    total                    153.80 M

**Comment by llamatester** [comment]
The adapter at projects/quarry/index.js exports TVL: 
        
 
 
    solana                    487.27 M
    
    total                    487.27 M

**Review by waynebruce0x — APPROVED** [review]

**Comment by llamatester** [comment]
The adapter at projects/astar-dapps-staking/index.js exports TVL: 
        
 
 
    polkadot                  434.26 M
    
    total                    434.26 M

**Comment by llamatester** [comment]
The adapter at projects/genshiro/index.js exports TVL: 
        
 
 
    polkadot                  3.66 M
    
    total                    3.66 M

**Comment by llamatester** [comment]
The adapter at projects/karura-dex/index.js exports TVL: 
        
 
 
    kusuma                    12.05 M
    
    total                    12.05 M

**Comment by llamatester** [comment]
The adapter at projects/karura-lending/index.js exports TVL: 
        
 
 
    kusuma                    17.27 M
    
    total                    17.27 M

**Comment by llamatester** [comment]
The adapter at projects/karura-staking/index.js exports TVL: 
        
 
 
    kusuma                    13.81 M
    
    total                    13.81 M

**Comment by llamatester** [comment]
The adapter at projects/lightning-network/index.js exports TVL: 
        
 
 
    bitcoin                   167.74 M
    
    total                    167.74 M

**Comment by llamatester** [comment]
The adapter at projects/quarry/index.js exports TVL: 
        
 
 
    solana                    520.95 M
    
    total                    520.95 M

**Comment by llamatester** [comment]
Error while running adapter at projects/shiden-dapps-staking/index.js: 
        
 
  
    
    
    Error: Option: unwrapping a None value
        at assert (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@polkadot/util/assert.cjs:37:11)
        at Object.unwrap (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@polkadot/types-codec/base/Option.cjs:241:22)
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/shiden-dapps-staking/index.js:14:22)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:56:25)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:146:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:191:3

**Pull request merged**
