### PR TITLE
Add gasline protocol

### PR DESCRIPTION
**Pull request by zerotwodao**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

Gasline Protocol

##### Twitter Link:

https://twitter.com/gaslinemarkets

##### List of audit links if any:

N/A

##### Website Link:

https://gasline.markets

##### Logo (High resolution, will be shown with rounded borders):

https://gasline.markets/assets/logo.png

##### Current TVL:

Blast: $200

BNB Chain: $200

##### Chain:

Blast, BNB Chain

##### Short Description (to be shown on DefiLlama):

First Baseline fork on Blast and BNB Chain made by Gas404

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Liquidity Manager

##### forkedFrom (Does your project originate from another project):

Baseline

##### methodology (what is being counted as tvl, how is tvl being calculated):

Gas404 token deposited calculated as a TVL ( Minted tokens are calculated as lent )

##### Github org/user (Optional, if your code is open source, we can track activity):

https://github.com/zerotwodao

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/gasline exports TVL: 
        
 
 
    blast                     252.074585961347
    blast-borrowed            252.074585961347
    bsc-borrowed              171.529643399961
    bsc                       171.529643399961
    borrowed                  423.604229361308
    
    total                    423.604229361308

**Comment by llamatester** [comment]
The adapter at projects/gasline exports TVL: 
        
 
 
    blast                     252.045877432399
    blast-borrowed            252.045877432399
    bsc-borrowed              170.87945696846063
    bsc                       170.87945696846063
    borrowed                  422.92533440085964
    
    total                    422.92533440085964

**Comment by g1nt0ki** [comment]
hi @zerotwodao I am bit confused, what is gas404 token, what is backing it?

**Comment by zerotwodao** [comment]
@g1nt0ki It is our DAO token https://docs.gas404.org, Like how YES token used to borrow ETH, Gas404 is being used to borrow GBNB or GETH which is our stablecoin for native assets

**Comment by g1nt0ki** [comment]
in baseline's case, uni v3 is provided when user mints YES token, but in your case, gas LP is deposited to mint? https://www.bscscan.com/tx/0xeb876fa7dcb99b2452433b48df95e1da93f99d78c2214190a6e0c757dde82c50 and for some reason you are counting all the WBNB in the pool as your tvl even though some LP is burnt so can not be recovered? 

Ignoring all that, we are already tracking gasswap: https://defillama.com/protocol/gasswap counting tvl here would be doblecounting (in baseline's case, they are independent of uniswap, unrelated teams)

**Comment by zerotwodao** [comment]
@g1nt0ki We actually don't accept or never count tvl of the LP, you can check our implementation contact for it https://www.bscscan.com/token/0x6d6aa57247911B5BaFC54B46bCFA5Bce2e3663BD#code ( The contract listed here is a proxy implementation ).

All we call the LP is the oracle of it to give the pricing of the minting tokens. So, it is not double counting as the TVL is counted by the deposits of the Gas404 token on the independent Gasline contract. I think you can also think of the lending protocols.

**Comment by zerotwodao** [comment]
@g1nt0ki Could you check the PR again and give us feedback? Thanks.

**Comment by zerotwodao** [comment]
@g1nt0ki It is not backed, We only concentrate liquidity on Gas404Swap and nothing else.

**Comment by g1nt0ki** [comment]
@zerotwodao lets keep the conversation here. we are not counting YES tokens as tvl for baseline, if you are trying to count gas404 as tvl, sorry, you cant

**Comment by zerotwodao** [comment]
@g1nt0ki Would it be possible to list the protocol if we change the backing asset to ETH or BNB? I have thought it since there is no price stability module to keep the price tighter just like the DAI's PSM module. Would it be okay? Will add the commit to this PR right now

**Comment by g1nt0ki** [comment]
yes, if the ETH/BNB is not already counted as part of gasswap tvl, but unsure how you will make that change without deploying new contracts/changing current protocol mechanism

**Comment by llamatester** [comment]
The adapter at projects/gasline exports TVL: 
        
 
 
    blast-borrowed            261.34372314806706
    blast                     3.9450100000000003
    bsc                       0.048826
    bsc-borrowed              251.86856851656145
    borrowed                  513.2122916646285
    
    total                    3.9938360000000004

**Comment by zerotwodao** [comment]
@g1nt0ki Done.

Example TX:

https://blastscan.io/tx/0x7a49af0fcd1083601016649e99bc54b9bed1a5cf59d31ee4ec8e83e888e15f7f

https://blastscan.io/token/0x4300000000000000000000000000000000000004?a=0xd5400cac1d76f29bbb8daef9824317aaf9d3c0a1

For BSC:

https://bscscan.com/tx/0x08cf361ddd31394d7b1b13ab9e7c850c41f63b679ffda163373c5c5611b15ab3

https://bscscan.com/token/0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c?a=0x35138ddfa39e00c642a483d5761c340e7b954f94

This was possible since like I told here https://github.com/DefiLlama/DefiLlama-Adapters/pull/9238#issuecomment-1985042258, we use the proxy contracts.

**Comment by g1nt0ki** [comment]
@zerotwodao thanks for the PR, refactored it a bit and merged it

**Comment by llamatester** [comment]
The adapter at projects/gasline exports TVL: 
        
 
 
    blast-borrowed            260.913119879517
    blast                     3.9388942269401217
    bsc                       0.04886000000000001
    bsc-borrowed              251.55390045693113
    borrowed                  512.4670203364482
    
    total                    3.9877542269401216

**Pull request merged**
