### PR TITLE
Add usd0 & usd0pp adapters

### PR DESCRIPTION
**Pull request by Magicking**
Add USD0 & USD0++ tokens

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/usual-usd0 exports TVL: 
        
 
 
    ethereum                  87.94 M
    
    total                    87.94 M

**Comment by llamatester** [comment]
The adapter at projects/usual-usd0pp exports TVL: 
        
 
 
    ethereum                  46.24 M
    
    total                    46.24 M

**Comment by g1nt0ki** [comment]
@Magicking thanks for the pr but it is lacking info. What are these projects, why are you counting token supply as tvl?

**Comment by Magicking** [comment]
My bad, will get back on the documentation and submit another with the full info

**Pull request closed without merging**
