### PR TITLE
added TeaDao project adapter

### PR DESCRIPTION
**Pull request by AdamTeaDao**
##### Twitter Link:
https://twitter.com/teadaofinance

##### Website Link:
https://teadao.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://raw.githubusercontent.com/Tea-Dao/image/main/logo.png
https://raw.githubusercontent.com/Tea-Dao/image/main/tea_logo_250_250.png

##### Chain:
AVALANCHE

##### Short Description (to be shown on DefiLlama):
The Decentralized marketplace for Investments and Services. 

##### Token address and ticker if any:
0x776fB4B2fA2CFfe3E7C1DDaA71dA52c09d87C37e
TEA
https://snowtrace.io/token/0x776fb4b2fa2cffe3e7c1ddaa71da52c09d87c37e

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Services

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/TeaDao/index.js: 
        
 
  
    
    
    Error: invalid address (argument="address", value=0, code=INVALID_ARGUMENT, version=address/5.6.0) (argument="account", value=0, code=INVALID_ARGUMENT, version=abi/5.6.0)
        at Logger.makeError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/logger/lib/index.js:233:21)
        at Logger.throwError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/logger/lib/index.js:242:20)
        at Logger.throwArgumentError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/logger/lib/index.js:245:21)
        at AddressCoder.Coder._throwError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/ethers/node_modules/@ethersproject/abi/lib/coders/abstract-coder.js:41:16)
        at AddressCoder.encode (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/ethers/node_modules/@ethersproject/abi/lib/coders/address.js:35:18)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/ethers/node_modules/@ethersproject/abi/lib/coders/array.js:74:19
        at Array.forEach (<anonymous>)
        at pack (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/ethers/node_modules/@ethersproject/abi/lib/coders/array.js:60:12)
        at TupleCoder.encode (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/ethers/node_modules/@ethersproject/abi/lib/coders/tuple.js:71:33)
        at AbiCoder.encode (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/ethers/node_modules/@ethersproject/abi/lib/abi-coder.js:93:15) {
      reason: 'invalid address (argument="address", value=0, code=INVALID_ARGUMENT, version=address/5.6.0)',
      code: 'INVALID_ARGUMENT',
      argument: 'account',
      value: 0
    }

**Comment by waynebruce0x** [comment]
This exports empty TVL? is that right?

**Comment by llamatester** [comment]
The adapter at projects/TeaDao/index.js exports TVL: 
        
 
 
    avalanche                 0
    
    total                    0

**Comment by AdamTeaDao** [comment]
yes TVL is 0 actually.

**Comment by waynebruce0x** [comment]
I'm gonna close this PR and we can help you write an adapter when there's some TVL. If you think we should reopen this let us know in Discord

**Comment by AdamTeaDao** [comment]
ok is it possible to merge it to show our project listed on defillama ?

**Pull request closed without merging**
