### PR TITLE
Add GoodGhosting TVL Adapter

### PR DESCRIPTION
**Pull request by Jamchello**
##### Twitter Link:
https://twitter.com/goodghosting

##### Website Link:
https://goodghosting.com/#/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

White = https://drive.google.com/file/d/1awkHPmKzbLfBawbv60SZc52eNLiM5zUU/view?usp=sharing

Black = https://drive.google.com/file/d/1tpD9c7AyZAWzs4ECyyGTMbrwr2yVUtgr/view?usp=sharing

Png = https://drive.google.com/file/d/1R9MD2syGMAb5KBo3098p-id8jAB0cKIj/view?usp=sharing

For a black background this blue one might work as well: https://goodghosting.com/static/media/goodghosting-text.2cc89fe1.svg

##### Current TVL:
~680k
##### Chain:
Celo, Polygon

##### Short Description (to be shown on DefiLlama):
GoodGhosting is a decentralized social savings app that combines game design elements with goal-based saving.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Gaming

##### methodology (what is being counted as tvl, how is tvl being calculated):
Calculating tvl by looking at the value of deposited tokens, and the value of interest bearing aave tokens owned by each game contract.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/good-ghosting exports TVL: 
        
 
 
    celo                      399.00 k
    polygon                   274.26 k
    
    total                    673.26 k

**Comment by g1nt0ki** [comment]
@Jamchello thanks for your PR, I checked your adapter file, it looks good, can you please revert the change to `package-lock.json` file and then I can merge it

**Comment by Jamchello** [comment]
> @Jamchello thanks for your PR, I checked your adapter file, it looks good, can you please revert the change to `package-lock.json` file and then I can merge it

Absolutely, sorry about that 👍

**Comment by Jamchello** [comment]
> @Jamchello thanks for your PR, I checked your adapter file, it looks good, can you please revert the change to `package-lock.json` file and then I can merge it

Resolved 👍

**Comment by llamatester** [comment]
The adapter at projects/good-ghosting exports TVL: 
        
 
 
    celo                      399.00 k
    polygon                   274.53 k
    
    total                    673.53 k

**Comment by RachBLondon** [comment]
@Jamchello @g1nt0ki thanks for getting this merged 🙂

We have had 3 audits though
[Quantstamp](https://certificate.quantstamp.com/full/good-ghosting-core-files-audit)
[Dedaub](https://github.com/Good-Ghosting/goodghosting-protocol-v0/blob/master/docs/audits/dedaub-good-ghosting-core-files-audit.pdf)
[Akee Blockchain](https://github.com/Good-Ghosting/goodghosting-protocol-v0/blob/master/docs/audits/ackee-good-ghosting-core-files-audit.pdf)

Is it possible to update the UI to reflect this?

Thanks!

Rachel

**Pull request merged**
