### PR TITLE
Some fixes for Cega

### PR DESCRIPTION
**Pull request by hildobby**
Some Cega fixes including:
- make max leverage loop include 5
- move getSumFCNProductQueuedDeposit from borrowed tvl to ethereum tvl
- add wbtc as a token for cega v2

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/cega: 
        
 
  
    
    
    Error: Multicall failed! 
     [chain: arbitrum] [fail count: 4] [abi: uint256:queuedDepositsTotalAmount]  
        target: 0xAB8631417271Dbb928169F060880e289877Ff158 
        target: 0xcf81b51AecF6d88dF12Ed492b7b7f95bBc24B8Af 
        target: 0x80ec1c0da9bfBB8229A1332D40615C5bA2AbbEA8 
        target: 0x94C5D3C2fE4EF2477E562EEE7CCCF07...

**Comment by g1nt0ki** [comment]
hi @hildobby why are you moving `getSumFCNProductQueuedDeposit` from borrowed to tvl?

**Comment by llamatester** [comment]
The adapter at projects/cega-v2 exports TVL: 
        
 
 
    ethereum                  9.33 M
    arbitrum                  1.66 M
    
    total                    10.99 M

**Comment by llamatester** [comment]
Error while running adapter at projects/cega: 
        
 
  
    
    
    Error: 429 Too Many Requests: {"jsonrpc":"2.0","error":{"code":-32429,"message":"max usage reached"}}
    Truncated error stack:
        at ClientBrowser.callServer (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@solana/web3.js/lib/index.cjs.js:4892:18)

**Comment by g1nt0ki** [comment]
@hildobby I don't think the last commit changed anything?

**Comment by hildobby** [comment]
> hi @hildobby why are you moving `getSumFCNProductQueuedDeposit` from borrowed to tvl?

Hey @g1nt0ki!

The sum of FCN deposits belongs in protocol TVL and is currently being incorrectly separated. 

FCN (Fixed Coupon Note) is an exotic option structured product – one of Cega’s many exotic options products. It is fundamentally an options trading position and while there are bond-like elements, users depositing in Cega FCNs are locked in a 27 day put option contract (tokenized via the vault token). Users’ final profit and loss are calculated by the FCN smart contract based on oracle prices of underlying assets, and whether their option is in/out of the money.
Reference material from TradFi on exotic options structured products: 
1. DBS (top Asian bank): “Structured products … performance or value is linked to that of an underlying asset … most structured products incorporate “options”, a type of derivative product that can give investors the right to buy or sell something at a pre-determined price (called “Strike Price")". https://www.dbs.com.hk/treasures/investments/structured-investments/structured-products 
2. DBS: “The investor risks being “put” the worst performing stock in the basket if the stocks are below their strike price on maturity. The final redemption amount depends on underlying asset’s performance”: https://www.dbs.com.sg/treasures/investments/product-suite/structured-investments/fixed-coupon-notes 
3. Cega documentation: https://docs.cega.fi/cega/products/derivatives-101/what-are-exotic-options

**Comment by llamatester** [comment]
Error while running adapter at projects/cega: 
        
 
  
    
    
    Error: 429 Too Many Requests: {"jsonrpc":"2.0","error":{"code":-32429,"message":"max usage reached"}}
    Truncated error stack:
        at ClientBrowser.callServer (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@solana/web3.js/lib/index.cjs.js:4892:18)

**Comment by adambawi** [comment]
> > hi @hildobby why are you moving `getSumFCNProductQueuedDeposit` from borrowed to tvl?
> 
> Hey @g1nt0ki!
> 
> The sum of FCN deposits belongs in protocol TVL and is currently being incorrectly separated.
> 
> FCN (Fixed Coupon Note) is an exotic option structured product – one of Cega’s many exotic options products. It is fundamentally an options trading position and while there are bond-like elements, users depositing in Cega FCNs are locked in a 27 day put option contract (tokenized via the vault token). Users’ final profit and loss are calculated by the FCN smart contract based on oracle prices of underlying assets, and whether their option is in/out of the money. Reference material from TradFi on exotic options structured products:
> 
> 1. DBS (top Asian bank): “Structured products … performance or value is linked to that of an underlying asset … most structured products incorporate “options”, a type of derivative product that can give investors the right to buy or sell something at a pre-determined price (called “Strike Price")". https://www.dbs.com.hk/treasures/investments/structured-investments/structured-products
> 2. DBS: “The investor risks being “put” the worst performing stock in the basket if the stocks are below their strike price on maturity. The final redemption amount depends on underlying asset’s performance”: https://www.dbs.com.sg/treasures/investments/product-suite/structured-investments/fixed-coupon-notes
> 3. Cega documentation: https://docs.cega.fi/cega/products/derivatives-101/what-are-exotic-options

+1, Adam from Cega here. Firstly I'd like to say that we're appreciative of the work and shared learning by @hildobby as well as the time you’ve taken to review @llamatester.

This change is important because (1) we want users in the DeFi community to correctly understand exotic options instruments and have spent significant time/resources educating folks already, (2) we want the numbers to tie between Cega and DefiLlama since we’ve gotten reports of confusion/mistrust by the discrepancy, (3) we have been pioneering DeFi exotic options structured products and want our TVL growth to be indicated when comparing to other options protocol. Please let us know how we can be helpful.

**Comment by g1nt0ki** [comment]
@hildobby  @adambawi if I remember correctly, the reason we are counting these under borowed was, when user deposits a token, it is not kept in your smart contract but loaned out to Market makers, if you check the commit history of this adapter, you will see that we were tracking multisig balances at some point. Has that changed?

**Comment by g1nt0ki** [comment]
@adambawi yes, borrowed is not the exact term here, but your protocol no longer has control over these tokens for a period of time right?

**Comment by g1nt0ki** [comment]
what annoys me is, this didnt start as a discussion, the discussion started after I repeatedly asked why something was moved from borrowed to tvl and no explanation was given. 


For what it is worth, I do agree borrowed is not appropriate term here, but we want to differentiate between tokens currently locked in a protocol, and rest, and borrowed is the closest label that we have

**Comment by adambawi** [comment]
@g1nt0ki yes that is correct. The capital is then used by market makers. Is there an issue with having this included in TVL given the reasonings we have provided above? Effectively this proportion of TVL is also paid back to the smart contract every 27 days - would that also be a case for being considered as TVL since the smart contract would actually read the full amount each settlement?

Re: your annoyance: the replies and explanations that we have provided I believe were trying to answer the question of why the “borrowed” amount was moved to TVL.

Alternatively, are we able to work together here so that the TVL is not just labelled as borrowed? Or could the default setting for TVL reading be to include this amount in the TVL and click a toggle to remove it if the user wants to separate? Otherwise it makes it very hard to give Cega a chance at being represented properly for our full services/not valued as highly as it could be when users are glimpsing through defillama.

Again very appreciative of your time for helping us resolve the matter.

**Comment by g1nt0ki** [comment]
@adambawi the code (think an year ago?) was doing exactly that, we counted the tokens on your contract and marked missing ones/held by  mm as borrowed.  we can revert back that if you prefer. this way when the MM returns the funds, it gets counted as tvl.

We are against counting funds outside smart contract as default tvl (there are some protocols who act like funds where they collect money on chain then do activities on cex for yield, but we have said no to them because there is no way, we or anyone else can verify), same for borrowed toggle being enabled by default (as people often loop in lending protocols for leverage/more yield), but there is a ongoing discussion to include passing this toggle settings via link, so if someone share the page link with borrowed toggle on, you open it, it will include borrowed tvl.

**Comment by hildobby** [comment]
> what annoys me is, this didnt start as a discussion, the discussion started after I repeatedly asked why something was moved from borrowed to tvl and no explanation was given.

That one is on me and I'm sorry. I am used to having a `WIP` tag for PRs. That's how it works on Dune's Spellbook for example, see here as it Jeff only steps in once I tag it as ready_for_review: https://github.com/duneanalytics/spellbook/pull/4621

I also happen to be in a different timezone (CET) as @adambawi, hence some of the delays in communication. And I've been working on many projects at once, which is also why I didn't respond promptly.

The goal here definitely was to explain the change from the beginning, I never expected to have this merged without explaining why, I'm sorry about this miscommunication, I'll know better for next time.

**Comment by g1nt0ki** [comment]
@hildobby all good, these things happen

**Comment by adambawi** [comment]
@g1nt0ki I wasn't aware that it was a year ago but it would be good to see if we can revert it so that it's reading TVL when MMs return funds as well.

I can understand the looping mechanism point of view from your side. I wonder if there was a way to include the TVL in the future if we were to show agreements with Market Makers that don't allow them to re-deposit into our vaults (it wouldn't make sense though as there wouldn't really be incentive from the market makers to trade against themselves for our Bond + Option products e.g. paying the premiums to themselves).

What's the eta on passing the toggle settings via link (to include borrowed tvl)? That would help a bit when we refer our users to look at our stats on defillama and how we compare.

**Comment by vsai** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters/pull/8866#issuecomment-1929754202

@g1nt0ki @hildobby `getSumFCNProductQueuedDeposit` is moved from borrowed to TVL because the funds have not yet been lent out

we have a queuing system of deposits where users can deposit throughout the week, and only once a week does all the funds get traded (either borrowed or not). so if it is still in the queue, it is still in the contract, and hasn't been borrowed yet

**Comment by vsai** [comment]
> hi @hildobby why are you moving `getSumFCNProductQueuedDeposit` from borrowed to tvl?

@g1nt0ki @hildobby getSumFCNProductQueuedDeposits(FCN_BOND_AND_OPTIONS_ADDRESSES, api)) is moved from borrowed to TVL because the funds are queued for a trade and have not YET been lent out

we have a queuing system of deposits where users can deposit throughout the week, and only once a week does all the funds get traded, either borrowed (for Bond+option) or not (for Pure Options). So if it is still in the queue, it has not yet been lent out and is still in the smart contract

**Comment by vsai** [comment]
> Error while running adapter at projects/cega:
> 
> ```
> Error: 429 Too Many Requests: {"jsonrpc":"2.0","error":{"code":-32429,"message":"max usage reached"}}
> Truncated error stack:
>     at ClientBrowser.callServer (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@solana/web3.js/lib/index.cjs.js:4892:18)
> ```

@g1nt0ki any idea why this is happening? something we need to fix on our end or on your end?

**Comment by g1nt0ki** [comment]
> > Error while running adapter at projects/cega:
> > ```
> > Error: 429 Too Many Requests: {"jsonrpc":"2.0","error":{"code":-32429,"message":"max usage reached"}}
> > Truncated error stack:
> >     at ClientBrowser.callServer (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@solana/web3.js/lib/index.cjs.js:4892:18)
> > ```
> 
> @g1nt0ki any idea why this is happening? something we need to fix on our end or on your end?

this is an issue if one uses public/free rpc (in this case solana) to run the adapter, in our server, we use paid rpc, so, it will work properly there. you can change it by setting `SOLANA_RPC` env variable or temporarily setting in this file: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/helper/env.js

**Comment by g1nt0ki** [comment]
> > hi @hildobby why are you moving `getSumFCNProductQueuedDeposit` from borrowed to tvl?
> 
> @g1nt0ki @hildobby `getSumFCNProductQueuedDeposits(FCN_BOND_AND_OPTIONS_ADDRESSES, api))` is moved from borrowed to TVL because the funds are queued for a trade and have not YET been lent out
> 
> we have a queuing system of deposits where users can deposit throughout the week, and only once a week does all the funds get traded, either borrowed (for Bond+option) or not (for Pure Options). So if it is still in the queue, it has not yet been lent out and is still in the smart contract

thanks for the explanation, it makes sense

**Comment by g1nt0ki** [comment]
> @g1nt0ki I wasn't aware that it was a year ago but it would be good to see if we can revert it so that it's reading TVL when MMs return funds as well.
> 
> I can understand the looping mechanism point of view from your side. I wonder if there was a way to include the TVL in the future if we were to show agreements with Market Makers that don't allow them to re-deposit into our vaults (it wouldn't make sense though as there wouldn't really be incentive from the market makers to trade against themselves for our Bond + Option products e.g. paying the premiums to themselves).
> 
> What's the eta on passing the toggle settings via link (to include borrowed tvl)? That would help a bit when we refer our users to look at our stats on defillama and how we compare.

@adambawi so, it is like wash trading, some protocols give incentive/yield for borrowing (dont think in your case), so borrowers loop as interest paid is less than yield + interest/yield they get as lender. 

I dont have an eta or even if we will do it :(

but what @vsai mentioned makes sense, @hildobby thanks for the PR

**Pull request merged**
