### PR TITLE
feat: add Apollo DAO NTRN/wstETH and stTIA/TIA vaults

### PR DESCRIPTION
**Pull request by apollo-sturdy**
Added two new vaults for Apollo DAO.

Getting `Unrecognized tokens` for stTIA )`ibc:6569E05DEE32B339D9286A52BE33DFCEFC97267F23EF9CFDE0C055140967A9A5`) and can't find any documentation on how to add missing tokens. Perhaps you guys forgot to update https://docs.llama.fi/list-your-project/how-to-write-an-sdk-adapter? Please advise.

### CODE REVIEW

**Comment by g1nt0ki** [comment]
sorry, too lazy to go through and ensure nothing malicious is in the formatting changes, so included the two vaults here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/23a8b5460214680ad07c686f1e38975402ca3431

this is where we maintain manual token mappings, https://github.com/DefiLlama/defillama-server/blob/master/coins/src/adapters/tokenMapping.json#L236 we will fix stTIA, thanks for the PR :)

**Comment by Define101** [comment]
@apollo-sturdy what are the decimals for STTIA ? https://github.com/DefiLlama/defillama-server/pull/5935

**Comment by apollo-sturdy** [comment]
@g1nt0ki Thanks! Fyi my editor formats with prettier since there is a .prettierrc file in this repo. Assumed you wanted it formatted this way because of that.

**Comment by g1nt0ki** [comment]
@apollo-sturdy lmao, my bad. been maintaining this repo for nearly two years, never noticed that file, nuked it.

**Pull request closed without merging**
