### PR TITLE
ParaSpace: support polygon and zksync

### PR DESCRIPTION
**Pull request by jfzhou5**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/paraspace exports TVL: 
        
 
 
    polygon-borrowed          0
    era-borrowed              0
    arbitrum-borrowed         47.63 k
    ethereum-borrowed         24.02 M
    era                       99
    polygon                   164.66645910193697
    arbitrum                  908.05 k
    ethereum                  58.01 M
    borrowed                  24.07 M
    
    total                    58.92 M

**Comment by jfzhou5** [comment]
@g1nt0ki  The address "0x5bF39BdE21B95d77fb18F27bBCb07F3648720A2e" in zksync era is our deployed WETH contract, So it's price is equal to ETH price, Your team need know this and add the token price in your library...Thank you.

**Comment by g1nt0ki** [comment]
@jfzhou5 thanks I have merged it with a fix here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/6942

Will update price server to include new WETH

**Comment by jfzhou5** [comment]
@g1nt0ki Thank you!

**Pull request closed without merging**
