### PR TITLE
add ramp

### PR DESCRIPTION
**Pull request by RAMPDEFITEAM**
Twitter Link: https://twitter.com/RampDefi

List of audit links if any:https://github.com/RAMP-DEFI/Security-Audits

Website Link: https://appv2.rampdefi.com/ | https://www.rampdefi.com/

Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): 
https://www.rampdefi.com/icons/tokens/ramp.png
https://www.rampdefi.com/icons/tokens/ramp.svg

Current TVL: TVL: $107,791,264

Chain: Binance Smart Chain/POLYGON/Ethereum

Coingecko ID (so your TVL can appear on Coingecko): https://www.coingecko.com/en/coins/ramp

Coinmarketcap ID (so your TVL can appear on Coinmarketcap): https://coinmarketcap.com/currencies/ramp/

Short Description (to be shown on DefiLlama): RAMP is an optimized lending platform that gives users the highest deposit yields and lowest borrowing fees on collateral assets across multiple blockchains.

Token address and ticker if any: 
https://etherscan.io/token/0x33D0568941C0C64ff7e0FB4fbA0B11BD37deEd9f | RAMP
https://bscscan.com/token/0x8519ea49c997f50ceffa444d240fb655e89248aa | RAMP

Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one: Lending

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using): Chainlink

forkedFrom (Does your project originate from another project): Not forked.

### CODE REVIEW

**Comment by michaelFranciscoOV** [comment]
Hi I'm a developer working on this project just would like to let you know that some of our LP tokens do not have prices listed in data aggregators such as coingecko and coinmarketcap, we have our own API endpoint that hosts the prices for these (https://appv2.rampdefi.com/config/appv2/priceinfo).

Please let us know how we can integrate our API so that the sdk can fetch the correct prices, thanks!

Logs from testing: 
```

Couldn't query decimals() for token UNKNOWN (0xECFe2c3c1aC0A5a59227A01f3Dd7044159b11a57) (0xECFe2c3c1aC0A5a59227A01f3Dd7044159b11a57) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at 0xECFe2c3c1aC0A5a59227A01f3Dd7044159b11a57, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (bsc:0xE834bf723f5bDff34a5D1129F3c31Ea4787Bc76a) (bsc:0xE834bf723f5bDff34a5D1129F3c31Ea4787Bc76a) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at bsc:0xE834bf723f5bDff34a5D1129F3c31Ea4787Bc76a, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (bsc:0x59fac9e98479fc9979ae2a0c7422af50bcbb9b26) (bsc:0x59fac9e98479fc9979ae2a0c7422af50bcbb9b26) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at bsc:0x59fac9e98479fc9979ae2a0c7422af50bcbb9b26, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (bsc:0xE482249Cd295C0d1e9D2baAEE71e66de21024C68) (bsc:0xE482249Cd295C0d1e9D2baAEE71e66de21024C68) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at bsc:0xE482249Cd295C0d1e9D2baAEE71e66de21024C68, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (bsc:0x870ee4d19c12a789c61de69e3e5efb42383e4434) (bsc:0x870ee4d19c12a789c61de69e3e5efb42383e4434) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at bsc:0x870ee4d19c12a789c61de69e3e5efb42383e4434, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (bsc:0x1BdCebcA3b93af70b58C41272AEa2231754B23ca) (bsc:0x1BdCebcA3b93af70b58C41272AEa2231754B23ca) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at bsc:0x1BdCebcA3b93af70b58C41272AEa2231754B23ca, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (bsc:0x853784B7BDe87d858555715c0123374242db7943) (bsc:0x853784B7BDe87d858555715c0123374242db7943) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at bsc:0x853784B7BDe87d858555715c0123374242db7943, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (bsc:0xBCf01a42f6BC42F3Cfe81B05519565044d65D22a) (bsc:0xBCf01a42f6BC42F3Cfe81B05519565044d65D22a) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at bsc:0xBCf01a42f6BC42F3Cfe81B05519565044d65D22a, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (bsc:0x89666d026696660e93Bf6edf57B71A68615768B7) (bsc:0x89666d026696660e93Bf6edf57B71A68615768B7) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at bsc:0x89666d026696660e93Bf6edf57B71A68615768B7, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (bsc:0x05faf555522Fa3F93959F86B41A3808666093210) (bsc:0x05faf555522Fa3F93959F86B41A3808666093210) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at bsc:0x05faf555522Fa3F93959F86B41A3808666093210, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (bsc:0xc13aA76AAc067c86aE38028019F414D731b3D86A) (bsc:0xc13aA76AAc067c86aE38028019F414D731b3D86A) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at bsc:0xc13aA76AAc067c86aE38028019F414D731b3D86A, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (bsc:0x0eD7e52944161450477ee417DE9Cd3a859b14fD0) (bsc:0x0eD7e52944161450477ee417DE9Cd3a859b14fD0) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at bsc:0x0eD7e52944161450477ee417DE9Cd3a859b14fD0, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (bsc:0x58F876857a02D6762E0101bb5C46A8c1ED44Dc16) (bsc:0x58F876857a02D6762E0101bb5C46A8c1ED44Dc16) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at bsc:0x58F876857a02D6762E0101bb5C46A8c1ED44Dc16, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (bsc:0x16b9a82891338f9bA80E2D6970FddA79D1eb0daE) (bsc:0x16b9a82891338f9bA80E2D6970FddA79D1eb0daE) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at bsc:0x16b9a82891338f9bA80E2D6970FddA79D1eb0daE, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (bsc:0x74E4716E431f45807DCF19f284c7aA99F18a4fbc) (bsc:0x74E4716E431f45807DCF19f284c7aA99F18a4fbc) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at bsc:0x74E4716E431f45807DCF19f284c7aA99F18a4fbc, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (bsc:0x61EB789d75A95CAa3fF50ed7E47b96c132fEc082) (bsc:0x61EB789d75A95CAa3fF50ed7E47b96c132fEc082) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at bsc:0x61EB789d75A95CAa3fF50ed7E47b96c132fEc082, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (bsc:0x804678fa97d91B974ec2af3c843270886528a9E6) (bsc:0x804678fa97d91B974ec2af3c843270886528a9E6) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at bsc:0x804678fa97d91B974ec2af3c843270886528a9E6, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (bsc:0x824eb9faDFb377394430d2744fa7C42916DE3eCe) (bsc:0x824eb9faDFb377394430d2744fa7C42916DE3eCe) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at bsc:0x824eb9faDFb377394430d2744fa7C42916DE3eCe, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (bsc:0x3cd338c3BB249B6b3C55799F85a589FEbBBFf9Dd) (bsc:0x3cd338c3BB249B6b3C55799F85a589FEbBBFf9Dd) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at bsc:0x3cd338c3BB249B6b3C55799F85a589FEbBBFf9Dd, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (bsc:0xDd5bAd8f8b360d76d12FdA230F8BAF42fe0022CF) (bsc:0xDd5bAd8f8b360d76d12FdA230F8BAF42fe0022CF) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at bsc:0xDd5bAd8f8b360d76d12FdA230F8BAF42fe0022CF, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (bsc:0xA39Af17CE4a8eb807E076805Da1e2B8EA7D0755b) (bsc:0xA39Af17CE4a8eb807E076805Da1e2B8EA7D0755b) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at bsc:0xA39Af17CE4a8eb807E076805Da1e2B8EA7D0755b, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (bsc:0xac109C8025F272414fd9e2faA805a583708A017f) (bsc:0xac109C8025F272414fd9e2faA805a583708A017f) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at bsc:0xac109C8025F272414fd9e2faA805a583708A017f, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (polygon:0xfC40a4F89b410a1b855b5e205064a38fC29F5eb5) (polygon:0xfC40a4F89b410a1b855b5e205064a38fC29F5eb5) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at polygon:0xfC40a4F89b410a1b855b5e205064a38fC29F5eb5, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (polygon:0xadbf1854e5883eb8aa7baf50705338739e558e5b) (polygon:0xadbf1854e5883eb8aa7baf50705338739e558e5b) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at polygon:0xadbf1854e5883eb8aa7baf50705338739e558e5b, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (polygon:0xe55739e1feb9f9aed4ce34830a06ca6cc37494a0) (polygon:0xe55739e1feb9f9aed4ce34830a06ca6cc37494a0) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at polygon:0xe55739e1feb9f9aed4ce34830a06ca6cc37494a0, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (polygon:0x5ef8747d1dc4839e92283794a10d448357973ac0) (polygon:0x5ef8747d1dc4839e92283794a10d448357973ac0) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at polygon:0x5ef8747d1dc4839e92283794a10d448357973ac0, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (polygon:0x6e7a5fafcec6bb1e78bae2a1f0b612012bf14827) (polygon:0x6e7a5fafcec6bb1e78bae2a1f0b612012bf14827) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at polygon:0x6e7a5fafcec6bb1e78bae2a1f0b612012bf14827, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (polygon:0xf6a637525402643b0654a54bead2cb9a83c8b498) (polygon:0xf6a637525402643b0654a54bead2cb9a83c8b498) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at polygon:0xf6a637525402643b0654a54bead2cb9a83c8b498, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (polygon:0x4a35582a710e1f4b2030a3f826da20bfb6703c09) (polygon:0x4a35582a710e1f4b2030a3f826da20bfb6703c09) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at polygon:0x4a35582a710e1f4b2030a3f826da20bfb6703c09, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (polygon:0x853ee4b2a13f8a742d64c8f088be7ba2131f670d) (polygon:0x853ee4b2a13f8a742d64c8f088be7ba2131f670d) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at polygon:0x853ee4b2a13f8a742d64c8f088be7ba2131f670d, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (polygon:0x5ca6ca6c3709e1e6cfe74a50cf6b2b6ba2dadd67) (polygon:0x5ca6ca6c3709e1e6cfe74a50cf6b2b6ba2dadd67) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at polygon:0x5ca6ca6c3709e1e6cfe74a50cf6b2b6ba2dadd67, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (polygon:0x1F1E4c845183EF6d50E9609F16f6f9cAE43BC9Cb) (polygon:0x1F1E4c845183EF6d50E9609F16f6f9cAE43BC9Cb) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at polygon:0x1F1E4c845183EF6d50E9609F16f6f9cAE43BC9Cb, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (polygon:0x1Bd06B96dd42AdA85fDd0795f3B4A79DB914ADD5) (polygon:0x1Bd06B96dd42AdA85fDd0795f3B4A79DB914ADD5) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at polygon:0x1Bd06B96dd42AdA85fDd0795f3B4A79DB914ADD5, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (polygon:0x019ba0325f1988213D448b3472fA1cf8D07618d7) (polygon:0x019ba0325f1988213D448b3472fA1cf8D07618d7) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at polygon:0x019ba0325f1988213D448b3472fA1cf8D07618d7, assuming a price of 0 for it...
RAMP                      37.30 M
RAMP                      14.73 M
RUSD                      9.77 M
RAMP                      6.39 M
CAKE                      2.85 M
ETH                       1.73 M
WBNB                      1.03 M
BTCB                      621.66 k
WETH                      370.17 k
WMATIC                    148.63 k
BUSD                      103.21126316950411
WBTC                      6.469159899999999
USDT                      1.0016770812569415
UNKNOWN (0xECFe2c3c1aC0A5a59227A01f3Dd7044159b11a57) 0
UNKNOWN (bsc:0xE834bf723f5bDff34a5D1129F3c31Ea4787Bc76a) 0
UNKNOWN (bsc:0x59fac9e98479fc9979ae2a0c7422af50bcbb9b26) 0
UNKNOWN (bsc:0xE482249Cd295C0d1e9D2baAEE71e66de21024C68) 0
UNKNOWN (bsc:0x870ee4d19c12a789c61de69e3e5efb42383e4434) 0
UNKNOWN (bsc:0x1BdCebcA3b93af70b58C41272AEa2231754B23ca) 0
UNKNOWN (bsc:0x853784B7BDe87d858555715c0123374242db7943) 0
UNKNOWN (bsc:0xBCf01a42f6BC42F3Cfe81B05519565044d65D22a) 0
UNKNOWN (bsc:0x89666d026696660e93Bf6edf57B71A68615768B7) 0
UNKNOWN (bsc:0x05faf555522Fa3F93959F86B41A3808666093210) 0
UNKNOWN (bsc:0xc13aA76AAc067c86aE38028019F414D731b3D86A) 0
UNKNOWN (bsc:0x0eD7e52944161450477ee417DE9Cd3a859b14fD0) 0
UNKNOWN (bsc:0x58F876857a02D6762E0101bb5C46A8c1ED44Dc16) 0
UNKNOWN (bsc:0x16b9a82891338f9bA80E2D6970FddA79D1eb0daE) 0
UNKNOWN (bsc:0x74E4716E431f45807DCF19f284c7aA99F18a4fbc) 0
UNKNOWN (bsc:0x61EB789d75A95CAa3fF50ed7E47b96c132fEc082) 0
UNKNOWN (bsc:0x804678fa97d91B974ec2af3c843270886528a9E6) 0
UNKNOWN (bsc:0x824eb9faDFb377394430d2744fa7C42916DE3eCe) 0
UNKNOWN (bsc:0x3cd338c3BB249B6b3C55799F85a589FEbBBFf9Dd) 0
UNKNOWN (bsc:0xDd5bAd8f8b360d76d12FdA230F8BAF42fe0022CF) 0
UNKNOWN (bsc:0xA39Af17CE4a8eb807E076805Da1e2B8EA7D0755b) 0
UNKNOWN (bsc:0xac109C8025F272414fd9e2faA805a583708A017f) 0
UNKNOWN (polygon:0xfC40a4F89b410a1b855b5e205064a38fC29F5eb5) 0
UNKNOWN (polygon:0xadbf1854e5883eb8aa7baf50705338739e558e5b) 0
UNKNOWN (polygon:0xe55739e1feb9f9aed4ce34830a06ca6cc37494a0) 0
UNKNOWN (polygon:0x5ef8747d1dc4839e92283794a10d448357973ac0) 0
UNKNOWN (polygon:0x6e7a5fafcec6bb1e78bae2a1f0b612012bf14827) 0
UNKNOWN (polygon:0xf6a637525402643b0654a54bead2cb9a83c8b498) 0
UNKNOWN (polygon:0x4a35582a710e1f4b2030a3f826da20bfb6703c09) 0
UNKNOWN (polygon:0x853ee4b2a13f8a742d64c8f088be7ba2131f670d) 0
UNKNOWN (polygon:0x5ca6ca6c3709e1e6cfe74a50cf6b2b6ba2dadd67) 0
UNKNOWN (polygon:0x1F1E4c845183EF6d50E9609F16f6f9cAE43BC9Cb) 0
UNKNOWN (polygon:0x1Bd06B96dd42AdA85fDd0795f3B4A79DB914ADD5) 0
UNKNOWN (polygon:0x019ba0325f1988213D448b3472fA1cf8D07618d7) 0
Total: 74.93 M

```

**Comment by 0xngmi** [comment]
I'd solve the issue with LP tokens by unwrapping them into their principal

**Comment by michaelFranciscoOV** [comment]
So I get reserves of both tokens in the LP and add them all up right?

**Comment by 0xngmi** [comment]
I'd use
```
const { unwrapUniswapLPs } = require("../helper/unwrapLPs");
```

just grep around to get some examples from the current codebase

**Comment by michaelFranciscoOV** [comment]
Thank you @0xngmi, I was able to update the PR using unwrapUniswapLPs as you suggested

For the remaining unknown tokens:
BSC

bsc:0x870ee4d19c12a789c61de69e3e5efb42383e4434 (Nerve rUSD )
Soon to be removed from the project

bsc:0x8cd6e29d3686d24d3c2018cee54621ea0f89313b (NULS)
CoinGecko: https://www.coingecko.com/en/coins/nuls

bsc:0x85eac5ac2f758618dfa09bdbe0cf174e7d574d5b (TRX)
CoinGecko: https://www.coingecko.com/en/coins/tron-bsc

Polygon

rUSD polygon:0xfC40a4F89b410a1b855b5e205064a38fC29F5eb5
Can be fetched from quickswap subgraph:

```
 const quickswap06URL =
      "https://api.thegraph.com/subgraphs/name/sameepsi/quickswap06";

    const QUERY_RUSD_PRICE = `
      {
        pair(id: "0x5ef8747d1dc4839e92283794a10d448357973ac0") 
          {
            rUSDPrice: token0Price
          }
      }`;

    axios.post(quickswap06URL, { query: QUERY_RUSD_PRICE }).then((res) => {
      const result: any = res.data.data.pair.rUSDPrice;
      setRUSDPolygonPrice(result);
    });
```

Let me know if this can be improved, thanks!


Logs:
```
Couldn't query decimals() for token UNKNOWN (polygon:0xfc40a4f89b410a1b855b5e205064a38fc29f5eb5) (polygon:0xfc40a4f89b410a1b855b5e205064a38fc29f5eb5) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at polygon:0xfc40a4f89b410a1b855b5e205064a38fc29f5eb5, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (bsc:0x870ee4d19c12a789c61de69e3e5efb42383e4434) (bsc:0x870ee4d19c12a789c61de69e3e5efb42383e4434) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at bsc:0x870ee4d19c12a789c61de69e3e5efb42383e4434, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (bsc:0x8cd6e29d3686d24d3c2018cee54621ea0f89313b) (bsc:0x8cd6e29d3686d24d3c2018cee54621ea0f89313b) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at bsc:0x8cd6e29d3686d24d3c2018cee54621ea0f89313b, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (bsc:0x85eac5ac2f758618dfa09bdbe0cf174e7d574d5b) (bsc:0x85eac5ac2f758618dfa09bdbe0cf174e7d574d5b) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at bsc:0x85eac5ac2f758618dfa09bdbe0cf174e7d574d5b, assuming a price of 0 for it...
RAMP                      49.14 M
RAMP                      21.89 M
RUSD                      18.27 M
RAMP                      9.61 M
BUSD                      9.13 M
WETH                      3.80 M
CAKE                      2.79 M
WBNB                      1.99 M
ETH                       1.68 M
BTCB                      1.24 M
WETH                      1.17 M
USDC                      1.10 M
DAI                       447.24 k
WMATIC                    352.39 k
INJ                       183.08 k
NRV                       167.93 k
DOT                       56.16 k
LINK                      32.83 k
LINK                      28.73 k
USDT                      16.44 k
DOGE                      11.53 k
QUICK                     10.86 k
WBTC                      124.26218271
UNKNOWN (polygon:0xfc40a4f89b410a1b855b5e205064a38fc29f5eb5) 0
UNKNOWN (bsc:0x870ee4d19c12a789c61de69e3e5efb42383e4434) 0
UNKNOWN (bsc:0x8cd6e29d3686d24d3c2018cee54621ea0f89313b) 0
UNKNOWN (bsc:0x85eac5ac2f758618dfa09bdbe0cf174e7d574d5b) 0
Total: 123.11 M

```

**Comment by 0xngmi** [comment]
Is the TVL on those tokens high enough to be worth building workarounds for them? If the tvl won't increase >1% I'd just leave it (or if you don't I'll accept PRs with workarounds for them, you can just replace their amounts for equivalent amounts of another asset)

**Comment by michaelFranciscoOV** [comment]
Updated.

I only used one workaround, it's for rUSD. I just added the amount to DAI's amount, both are stablecoin and should always approximately have the same value.

Still missing three tokens but those will be removed from the project soon so it's ok to ignore them. TVL from testing is close to what we have displayed on our site.

I hope this is acceptable, but let me know if there's anything that needs to be changed or improved

```

Couldn't query decimals() for token UNKNOWN (bsc:0x870ee4d19c12a789c61de69e3e5efb42383e4434) (bsc:0x870ee4d19c12a789c61de69e3e5efb42383e4434) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at bsc:0x870ee4d19c12a789c61de69e3e5efb42383e4434, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (bsc:0x8cd6e29d3686d24d3c2018cee54621ea0f89313b) (bsc:0x8cd6e29d3686d24d3c2018cee54621ea0f89313b) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at bsc:0x8cd6e29d3686d24d3c2018cee54621ea0f89313b, assuming a price of 0 for it...
Couldn't query decimals() for token UNKNOWN (bsc:0x85eac5ac2f758618dfa09bdbe0cf174e7d574d5b) (bsc:0x85eac5ac2f758618dfa09bdbe0cf174e7d574d5b) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at bsc:0x85eac5ac2f758618dfa09bdbe0cf174e7d574d5b, assuming a price of 0 for it...
RAMP                      38.24 M
RAMP                      17.07 M
RUSD                      11.97 M
BUSD                      7.78 M
RAMP                      7.41 M
DAI                       3.71 M
WETH                      3.32 M
CAKE                      2.00 M
WBNB                      1.77 M
ETH                       1.72 M
BTCB                      1.14 M
USDC                      1.10 M
WETH                      921.34 k
WMATIC                    291.26 k
NRV                       143.13 k
INJ                       112.27 k
DOT                       101.97 k
LINK                      27.91 k
LINK                      27.74 k
USDT                      14.87 k
QUICK                     10.21 k
DOGE                      9.14 k
WBTC                      116.57848605
UNKNOWN (bsc:0x870ee4d19c12a789c61de69e3e5efb42383e4434) 0
UNKNOWN (bsc:0x8cd6e29d3686d24d3c2018cee54621ea0f89313b) 0
UNKNOWN (bsc:0x85eac5ac2f758618dfa09bdbe0cf174e7d574d5b) 0
Total: 98.89 M

```

**Comment by 0xngmi** [comment]
>  do we need to create a new PR for the update that I made?

yeah imo that would be better

> I just added the amount to DAI's amount, 
Instead of using DAI I'd use another stablecoin that isn't currently being used, like TUSD

**Comment by michaelFranciscoOV** [comment]
Alright, we'll use TUSD, I'll submit a new PR tomorrow, thanks!

**Pull request merged**
