### PR TITLE
add TVL adapter BossWatcher

### PR DESCRIPTION
**Pull request by bosswatcher**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Boss Watcher

##### Twitter Link:
https://twitter.com/bosswatcher

##### Website Link:
http://bosswatcher.xyz

##### Logo (High resolution, will be shown with rounded borders):
http://bosswatcher.xyz/images/bosswatcher.png

##### Current TVL:
1kk, including staking

##### Chain:
BSC

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
https://www.coingecko.com/en/coins/boss

##### Short Description (to be shown on DefiLlama):
Boss Watcher is an easy to use portfolio tracker which gives users real time price performance of their on-chain assets.

##### Token address and ticker if any:
https://www.bscscan.com/address/0x49324d59327fB799813B902dB55b2a118d601547

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Services

### CODE REVIEW

**Comment by g1nt0ki** [comment]
we are gonna count tokens in pancakeswap pool as your tvl: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by bosswatcher** [comment]
@g1nt0ki Thanks for considering. I don't quite understand why the request was rejected in this case, do I need to reopen this pr and include stacking in the tvl count?

**Comment by bosswatcher** [comment]
@g1nt0ki

**Comment by g1nt0ki** [comment]
please read the link I shared

**Pull request closed without merging**
