### PR TITLE
update poopsicle tvl

### PR DESCRIPTION
**Pull request by Narangarig**
##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list) 
Poopsicle

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
Poopsicle

##### Short Description (to be shown on DefiLlama):
One of the purest and the most honest meme tokens on the market. We aren't backed by physical assets like gold, silver nor cashmere. We don't promise any financial gains or stability against inflation. We do however have Metamorphosis, a secret for now.

##### methodology (what is being counted as tvl, how is tvl being calculated):
Included 9 staking(poop, ftm/poop, any/poop, usdc/poop, boo/poop, band/poop, link/poop, gohm/poop, spirit/poop)

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Hey I actually just made an edit to make the exports compatible with our UI. Could you take a look and see if you can resolve the conflicts?

**Comment by Narangarig** [comment]
I have just updated the poopsicle tvl code. Please approve the changes. Completely merged LP values. Example: LP = FTM price + POOP price. Thanks again

**Comment by waynebruce0x** [comment]
I exported them as pool2 because every LP contains native platform token. We do this for all protocols so that users can decide whether or not they include pool2 as part of TVL

**Comment by Narangarig** [comment]
H, just replaced the code. I added pool2 key. Previous integration was only poop tv shows. Now added native tokens in pool2.

**Comment by Narangarig** [comment]
Hi, the current branch is showing 0 TVL unless you enable the pool 2 check box. Although every LP includes our native platform token which $POOP in this case. Why show 0 unless "POOL 2 button" is checked? We would like to show total TVL number as soon as you pull up our project.

**Comment by waynebruce0x** [comment]
Because all of the LP tokens are for pool2 markets. We use this same methodology for all of the protocols on defillama

**Comment by enkhee1117** [comment]
Hi, I am Enkh. One of the devs working at Poopsicle. We may not understand nuance between pool2 and regular TVL. All of our liquidity farming uses either SpiritSwap or SpookySwap. For instance, there is a farming for LP that includes $FTM/$POOP. Am I correct to say that $POOP portion of the LP is not included in total TVL measure but included in Pool2 since $POOP is the token of our project?

**Comment by waynebruce0x** [comment]
We count pool2 separately from TVL. Pool2 being money that is providing liquidity to an AMM pool where one of the tokens is from the protocol (except on some cases where those assets are performing an active function such as being used as collateral).

So in the case of poopsicle all of the liquidity farming will fall under pool2

**Pull request closed without merging**
