### PR TITLE
add STG staking contracts + linea chain

### PR DESCRIPTION
**Pull request by thekoenekamp**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/stargatefinance exports TVL: 
        
 
 
    goerli                    25.18 k
    avax-staking              456.20 k
    polygon-staking           202.66 k
    bsc-staking               432.65 k
    ethereum-staking          716.53 k
    fantom-staking            25.69 k
    bsc                       54.10 M
    polygon                   33.14 M
    base-staking              0
    optimism                  18.73 M
    base                      25.27 M
    arbitrum                  101.47 M
    fantom                    3.37 M
    avax                      39.46 M
    ethereum                  95.23 M
    linea-staking             0
    linea                     12.92 M
    metis                     3.31 M
    kava                      1.83 M
    staking                   1.83 M
    
    total                    388.87 M

**Comment by llamatester** [comment]
Error while running adapter at projects/stargatefinance: 
        
 
  
    
    
    TypeError: addresses.forEach is not a function
    Truncated error stack:
    
        at getUniqueAddresses (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/tokenMapping.js:80:13)
        at sumTokens2 (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/unwrapLPs.js:689:12)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/staking.js:27:32
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:29)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:136:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:131:44

**Comment by g1nt0ki** [comment]
@thekoenekamp thanks for the PR

**Comment by llamatester** [comment]
The adapter at projects/stargatefinance exports TVL: 
        
 
 
    fantom-staking            25.53 k
    goerli                    25.11 k
    ethereum-staking          712.12 k
    avax-staking              453.38 k
    polygon-staking           201.33 k
    bsc-staking               429.98 k
    fantom                    3.35 M
    base                      25.24 M
    linea-staking             0
    linea                     12.89 M
    base-staking              0
    bsc                       54.12 M
    arbitrum                  101.39 M
    polygon                   33.09 M
    ethereum                  95.16 M
    avax                      39.60 M
    kava                      1.83 M
    optimism                  18.71 M
    metis                     3.31 M
    staking                   1.82 M
    
    total                    388.72 M

**Pull request merged**
