### PR TITLE
TVL Adapter for Javsphere 

### PR DESCRIPTION
**Pull request by rogi-sh**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Javsphere

##### Twitter Link:
https://twitter.com/Javsphere

##### Website Link:
https://www.javsphere.com/

##### Logo (High resolution, will be shown with rounded borders):
jav-token-v2

##### Current TVL:
10678530.6 $

##### Chain:
DefiMetaChain  L2 - ChainId 1130 EVM - L1 is defichain

##### Short Description (to be shown on DefiLlama):
The Gateway to the real-world assets on Bitcoin with DeFi Meta Chain and its revolutionary decentralized applications built with Ethereum Virtual Machine from DeFiChain.

##### Token address and ticker if any:
The link for the javsphere token JAV will be launched in April 2024 on defimetachain.
https://blockscout.mainnet.ocean.jellyfishsdk.com/token/0x66F3Cf265D2D146A0348F6fC67E3Da0835e0968E

##### Category (full list at https://defillama.com/categories) *Please choose only one:
[RWA](https://defillama.com/protocols/RWA)

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):

https://explorer.mydefichain.com/oracles
##### Implementation Details: Briefly describe how the oracle is integrated into your project:
Oracles are used for our RWAs on defichain (L1). On the defichainmetachain (L2) javsphere uses the token for Trading (TradeX https://app.javsphere.com/trade-x) and upcoming products to build up portfolio or leverage positions.

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
https://docs.javsphere.com/
https://blog.defichain.com

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL ist calculated as folows: We count the total value locked in all our products (dusd staking, 
1 year bond and 2 year bond).  

##### Github org/user (Optional, if your code is open source, we can track activity):
All the smart contracts will be deployed here before token launch in April. 
https://github.com/Javsphere

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/javsphere: 
        
 
  
    
    
    Error: 
        Unknown chain(s): defimetachain
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file
        
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:138:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
Error while running adapter at projects/javsphere: 
        
 
  
    
    
    TypeError: Cannot create property 'coingecko:0' on string '10678530.60'
    Truncated error stack:
        at Object.sumSingleBalance (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:108:25)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:307:16
        at Array.forEach (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:301:28)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:314:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:51:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:138:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)

**Comment by llamatester** [comment]
The adapter at projects/javsphere exports TVL: 
        
 
 
    defichain                 10.34 M
    
    total                    10.34 M

**Comment by llamatester** [comment]
The adapter at projects/javsphere exports TVL: 
        
 
 
    defichain                 10.32 M
    
    total                    10.32 M

**Comment by llamatester** [comment]
The adapter at projects/javsphere exports TVL: 
        
 
 
    defichain                 7.04 M
    defichain_evm             3.65 M
    
    total                    10.68 M

**Comment by llamatester** [comment]
The adapter at projects/javsphere exports TVL: 
        
 
 
    defichain_evm             3.65 M
    defichain                 7.04 M
    
    total                    10.68 M

**Comment by rogi-sh** [comment]
The yield is coming from negative interest (NI) rate of vaults which borrow DUSD. So if NI is like -20% users can earn dusd from take a loan. This NI is depending on how many people sell DUSD. If they sell there is a fee which is used for the NI and is distributed along the vault holders. We utilize this and and created  a product around this on app.javsphere.com/stake-x.  Here our docs for this product: https://docs.javsphere.com/products/dusd-staking

**Comment by rogi-sh** [comment]
and why is a vault with 12M DUSD considered as tvl? -> because we build a product around this feature and this is one part of javsphere products tvl. Javsphere is currently a provider which connects defichain and defichain_evm by building products for both sides.

**Pull request merged**
