### PR TITLE
Add WhaleSwap adapter

### PR DESCRIPTION
**Pull request by coj337**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI

---

##### Twitter Link:
https://twitter.com/whaleloans

##### List of audit links if any:
https://github.com/Whale-Swap/audits/blob/878e4671851d65c4fc9a35a7d2fec94a483e1d72/WhaleSwap_Audit.pdf

##### Website Link:
https://whaleswap.finance

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://raw.githubusercontent.com/Whale-loans/whale-assets/main/logo_symbol.svg

##### Current TVL:
$53662

##### Chain:
Adapter is currently just BNB (Where we have our farming & staking launched) but the exchange is on all these chains with those coming to it soon:
- BNB Chain
- Polygon
- Optimism
- Arbitrum
- Avalanche
- Fantom

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
TBD

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
TBD

##### Short Description (to be shown on DefiLlama):
The next-generation, cross-chain decentralized exchange.

##### Token address and ticker if any:
Address: 0xDDed222297B3d08DAFDAc8f65eeB799B2674C78F
Ticker: POD

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
N/A

##### forkedFrom (Does your project originate from another project):
Uniswap

##### methodology (what is being counted as tvl, how is tvl being calculated):
Liquidity locked in the exchange

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/whaleswap: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:219:11

**Comment by Define101** [comment]
Hi guys just to make sure, is the same team behind the Whale Loans correct?
Should we add the protocols under the same "group", here is an example of AAVE https://defillama.com/protocol/aave
The image above show how it looks 
image

**Comment by Define101** [comment]
Quick note: all of them have an individual page for it each one just like any protocol
image

**Comment by Define101** [comment]
Sure 
Removed whaleloans and added whaleswap 
Should be live within 1 hour

**Comment by coj337** [comment]
Thanks! The listing appears to have missed the audit (linked in this PR) and the description seems to have be from a different project, any chance that can be fixed up?

**Pull request merged**
