### PR TITLE
Adding New Staking Contract Support to Decuabte Adapter

### PR DESCRIPTION
**Pull request by Pierre764**
Update Decubate Staking Pools in Adapter

This PR adds support for new staking pools within the Decubate adapter. The update ensures accurate TVL calculations by including balances from both the original and newly added staking contracts.

**Changes:**
- Added new staking pool contract address to the `stakingPools` array.
- Updated the `staking` function to iterate over multiple pool addresses, aggregating the total balance.

This update is crucial for maintaining accurate TVL metrics on DefiLlama for the Decubate project. Please let me know if any further modifications or information is required.

**Note:** I've enabled "Allow edits by maintainers" to facilitate any necessary adjustments to this PR.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/decubate exports TVL: 
        
 
 
    bsc                       0
    bsc-staking               21.85 M
    staking                   21.85 M
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/decubate exports TVL: 
        
 
 
    bsc                       0
    bsc-staking               21.79 M
    staking                   21.79 M
    
    total                    0

**Comment by g1nt0ki** [comment]
@Pierre764 thanks for the PR

**Comment by Pierre764** [comment]
@g1nt0ki Thanks for the update 🤝

**Pull request merged**
