### PR TITLE
Add Fusion DEX TVL

### PR DESCRIPTION
**Pull request by SuperDev321**
##### Twitter Link:
https://twitter.com/NovaFinOfficial

##### List of audit links if any:
https://docs.novanetwork.io/fusion/features/farms-and-lp-mining
https://docs.novanetwork.io/fusion/features/staking-and-saving#call-staking

##### Website Link:
https://fusion.novanetwork.io/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
512x512_App_Icon

##### Current TVL:
32.38k
##### Chain:
fantom

##### Short Description (to be shown on DefiLlama):
A fully decentralized protocol for automated liquidity provision on Fantom and Nova.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### forkedFrom (Does your project originate from another project):
furylabsfinance

##### methodology (what is being counted as tvl, how is tvl being calculated):
Counts tokens held in the fusion contracts

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/fusion exports TVL: 
        
 
 
    fantom-pool2              0
    fantom-staking            34.11 k
    fantom                    34.11 k
    fantom-masterchef         34.11 k
    pool2                     0
    staking                   34.11 k
    masterchef                34.11 k
    
    total                    34.11 k

**Comment by waynebruce0x** [comment]
On the UI it looks like you have 185k in your pool 2, but the adapter shows 0, is this correct? Is the project on fantom or nova?

**Comment by SuperDev321** [comment]
Hi Wayne.
it's on both, but the adapter is only capturing Fantom atm since it is not supporting nova network yet. If you can support Nova network, it will be better.
And I just fixed pool2.
Thank you.

**Comment by SuperDev321** [comment]
Hi Wayne.
Could you tell me when you can approve my pull request?

**Comment by waynebruce0x** [comment]
We just added Nova chain, if you also want to add that

**Comment by nova-network-inc** [comment]
> We just added Nova chain, if you also want to add that

Hi Wayne, we will need to make some adjustments to the information submitted:

**List of audit links if any:** N/A

**Website Link:** https://novanetwork.io/

**Logo:** https://novanetwork.io/wp-content/uploads/2021/11/cropped-512SNT.png

**Chains:**
Fantom Opera
Nova Network

**Coingecko ID:** supernova

**Coinmarketcap ID:** supernova

**Short Description:** Nova Network is an EVM compatible smart contracts platform, and Fusion is its officially supported DeFi protocol.

**Token address and ticker if any:**
Fantom Opera: 0x69D17C151EF62421ec338a0c92ca1c1202A427EC
Nova Network: NATIVE

Please let me know if we need to submit the information above on a separate pull request or if you can adjust it manually there. Thanks.

**Comment by waynebruce0x** [comment]
No thats fine thanks, 
Is this a non-standard masterchef contract? Do the masterchef helper functions not work?

**Comment by SuperDev321** [comment]
Our masterchief is a little different from masterchef contract. (We just used our SNT token as reward token. And it is also using as staking token.)
So we just copied from mastercef function of helper and adjusted a little.
-----
We just added nova network tvl.
But for now, our nova network tokens  are on on coingecko.
So we used the token prices of fantom network.
nova NUSD -> fantom USDC
nova native token(SNT) -> fantom SNT
Please let me know if it is possible.

**Comment by llamatester** [comment]
Error while running adapter at projects/fusion: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'call')
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/abi/index.js:94:77
        at new Promise (<anonymous>)
        at Object.sdk.api.abi.call (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:108:18)
        at getPoolInfo (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/fusion/index.js:27:23)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/fusion/index.js:131:28)

**Comment by SuperDev321** [comment]
Just fixed that error. It was because of coindgecho id.

**Comment by llamatester** [comment]
Error while running adapter at projects/fusion: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'call')
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/abi/index.js:94:77
        at new Promise (<anonymous>)
        at Object.sdk.api.abi.call (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:108:18)
        at getPoolInfo (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/fusion/index.js:27:23)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/fusion/index.js:131:28)

**Comment by SuperDev321** [comment]
It was because the rpc was missing.
Just added nova rpc on env file. (env.sample)

**Comment by nova-network-inc** [comment]
@llamatester Any news?

**Comment by llamatester** [comment]
Error while running adapter at projects/fusion: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'call')
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/abi/index.js:94:77
        at new Promise (<anonymous>)
        at Object.sdk.api.abi.call (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:108:18)
        at getPoolInfo (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/fusion/index.js:27:23)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/fusion/index.js:131:28)

**Comment by g1nt0ki** [comment]
hi @nova-network-inc is your chain okay? we are having some trouble querying the rpc, getting `Error: failed to meet quorum`

**Comment by g1nt0ki** [comment]
okay, I am an idiot, fixed it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/3156

**Pull request merged**
