### PR TITLE
update(saddle): Adding additional pools

### PR DESCRIPTION
**Pull request by westonnelson**
Updating Saddle Finance integration with DeFi Llama:

Twitter Link: https://twitter.com/saddlefinance
List of audit links:
Certik: https://github.com/saddle-finance/saddle-audits/blob/master/10-29-2020_Certik.pdf
OpenZeppelin: https://blog.openzeppelin.com/saddle-contracts-audit/
Quantstamp: https://github.com/saddle-finance/saddle-audits/blob/master/12-09-2020_Quantstamp.pdf

Website Link: https://saddle.finance/
Chains: Ethereum, Arbitrum, Evmos, Optimism, Fantom
Coingecko ID: saddle-finance
Short Description: Saddle is a decentralized automated market maker on multiple blockchains, optimized for pegged value crypto assets such as stablecoins and wBTC.
Token address and ticker if any:
Ethereum: 0xf1Dc500FdE233A4055e25e5BbF516372BC4F6871 - Ticker $SDL
Etherscan: https://etherscan.io/token/0xf1dc500fde233a4055e25e5bbf516372bc4f6871
Category: DEXs

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/saddle: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:219:11

**Comment by westonnelson** [comment]
I just fetched upstream and now it appears as though it may be all set?!

I am almost wondering if I should just create a whole new adapter...or if that is not necessary.

I did notice that the specific token $nUSD on Arbitrum reflects odd in the code - but I don't know/can't imagine that would be the issue here...maybe needing total TVL somewhere else is all I can think of at the moment.

**Comment by g1nt0ki** [comment]
@westonnelson I am rewriting the adapter now :)

**Comment by westonnelson** [comment]
@g1nt0ki - legend. I really don't know what the bug was here but thank you!!!! Having the fresh adapter will be huge I think for likely future PRs - I will get one to fly through flawlessly soon I promise :)

**Pull request closed without merging**
