### PR TITLE
Feature/1205267245821359 defilama krest adapter

### PR DESCRIPTION
**Pull request by neutrinoks**
- Added krest-staking folder to projects/ (regular TVL adapter)
- Added krest to projects/helpers/chains.json
- Added package @polkadot/api by using `yarn add @polkadot/api`

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/krest-staking exports TVL: 
        
 
 
    krest                     7.53 k
    
    total                    7.53 k

**Comment by neutrinoks** [comment]
> The adapter at projects/krest-staking exports TVL:
> 
> ```
> krest                     7.53 k
> 
> total                    7.53 k 
> ```

Yes, that is correct :+1:

**Comment by neutrinoks** [comment]
What about this error-issue from GitHub checks? Nothing from my changes...

**Comment by llamatester** [comment]
The adapter at projects/krest-staking exports TVL: 
        
 
 
    krest                     7.51 k
    
    total                    7.51 k

**Comment by g1nt0ki** [comment]
hi @neutrinoks 

You can ignore the lint error that is failing this PR

But, atm we dont track chain staking or count towards chain tvl, only tvl from defi protocols, you can find the reasoning here: https://github.com/DefiLlama/DefiLlama-Adapters/discussions/435

**Comment by neutrinoks** [comment]
Ah ok, so regular staking doesn't count and hasn't to be reported to the TVL? I thought it might be included anyway, because in the FAQ/Wiki it is not under "Not TVL" :upside_down_face: 
The reason why we wanted to get listed on DeFiLama is because we want to have an EVM ChainID from chainlist.org, but they refused our PR because we were not listed on DeFiLama -_- Krest is quite new and online since a month round about... Things have to be figured out... What do you suggest to us?

**Comment by g1nt0ki** [comment]
@neutrinoks do you have any defi apps on top of your chain like dex/lending?

Also, bit surprised about the criteria is being on defillama, can you check again with chainlist?

**Comment by neutrinoks** [comment]
> @neutrinoks do you have any defi apps on top of your chain like dex/lending? 
We are currently integrating a DEX, but so far only on test-networks, not on krest online, it will take some more time.

> Also, bit surprised about the criteria is being on defillama, can you check again with chainlist?
Yes, I am currently working on another PR on their repo and will try to contact them today - will see how they respond :+1:

**Comment by neutrinoks** [comment]
Still waiting for our PR (will probably take a couple of days):
https://github.com/ethereum-lists/chains/pull/3363

**Comment by neutrinoks** [comment]
We have listed our networks on chainlist.wtf, and everything seems to work so far :+1: I will close this...

**Pull request closed without merging**
