### PR TITLE
new staking vaults added

### PR DESCRIPTION
**Pull request by brddmnk**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/parallax exports TVL: 
        
 
 
    ethereum                  113.44 k
    arbitrum                  90.84 k
    
    total                    204.28 k

**Comment by llamatester** [comment]
The adapter at projects/parallax exports TVL: 
        
 
 
    arbitrum-staking          16.31 k
    ethereum                  113.35 k
    arbitrum-pool2            30.46 k
    arbitrum                  74.75 k
    staking                   16.31 k
    pool2                     30.46 k
    
    total                    188.09 k

**Comment by g1nt0ki** [comment]
@brddmnk thanks for the PR, I have updated it so we dont count your own tokens as tvl: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by brddmnk** [comment]
> @brddmnk thanks for the PR, I have updated it so we dont count your own tokens as tvl: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

@g1nt0ki thanks
But as I can see staking own token is allowed in tvl
https://d.pr/i/xctOEK

**Comment by g1nt0ki** [comment]
@brddmnk yeah, under staking key (not under 'tvl'), that was the change I made

**Comment by brddmnk** [comment]
@g1nt0ki yes but according to https://docs.llama.fi/list-your-project/what-to-include-as-tvl it's in TVL Filters and not in "Not TVL"
so it should be counted but also shown in staking key
am I right?

**Comment by brddmnk** [comment]
and also from docs.llama.fi:
"The stakings and pool2 functions make it really simple to add any native token TVL."
and it's ok to me to separate TVL into different types but it's not showing on parallax protocol at defillama.com

**Comment by brddmnk** [comment]
now it shows up thanks a lot @g1nt0ki

**Comment by g1nt0ki** [comment]
missed the message, it takes a few hours to reflect in the UI :)

**Pull request merged**
