### PR TITLE
Add Extra Finance TVL

### PR DESCRIPTION
**Pull request by ExtraFi**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
### Logo (High resolution, will be shown with rounded borders):
image

### Short Description (to be shown on DefiLlama):

Extra Finance is a community-driven lending & leveraged yield farming protocol built on Optimism.

### Category (full list at [https://defillama.com/categories](https://defillama.com/categories)) *Please choose only one:

Yield

### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

TWAP & Chainlink

### methodology (what is being counted as tvl, how is tvl being calculated):

Value of total LP tokens deposited + lending deposits that are not borrowed.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/extra: 
        
 
  
    
    
    PromisePoolError: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0xcA11bde05977b3631167028862bE2a173976CA11","data":"0xbce38bd700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000500000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000001a0000000000000000000000000000000000000000000000000000000000000022000000000000000000000000000000000000000000000000000000000000002a000000000000000000000000079c912fef520be002c2b6e57ec4324e260f38e500000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000418160ddd00000000000000000000000000000000000000000000000000000000000000000000000000000000e8537b6ff1039cb9ed0b71713f697ddbadbb717d0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000418160ddd0000000000000000000000000000000000000000000000000000000000000000000000000000000047029bc8f5cbe3b464004e87ef9c9419a48018cd0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000418160ddd000000000000000000000000000000000000000000000000000000000000000000000000000000009056eb7ca982a5dd65a584189994e6a27318067d0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000418160ddd000000000000000000000000000000000000000000000000000000000000000000000000000000005edac6b8ea08d535c01981d75b3361481c0ee9990000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000418160ddd00000000000000000000000000000000000000000000000000000000","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    Truncated error stack:
        at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
Error while running adapter at projects/extra: 
        
 
  
    
    
    PromisePoolError: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0xcA11bde05977b3631167028862bE2a173976CA11","data":"0xbce38bd700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000500000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000001a0000000000000000000000000000000000000000000000000000000000000022000000000000000000000000000000000000000000000000000000000000002a000000000000000000000000079c912fef520be002c2b6e57ec4324e260f38e5000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000004d21220a700000000000000000000000000000000000000000000000000000000000000000000000000000000e8537b6ff1039cb9ed0b71713f697ddbadbb717d00000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000004d21220a70000000000000000000000000000000000000000000000000000000000000000000000000000000047029bc8f5cbe3b464004e87ef9c9419a48018cd00000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000004d21220a7000000000000000000000000000000000000000000000000000000000000000000000000000000009056eb7ca982a5dd65a584189994e6a27318067d00000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000004d21220a7000000000000000000000000000000000000000000000000000000000000000000000000000000005edac6b8ea08d535c01981d75b3361481c0ee99900000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000004d21220a700000000000000000000000000000000000000000000000000000000","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    Truncated error stack:
        at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
The adapter at projects/extra exports TVL: 
        
 
 
    optimism                  161.12 k
    
    total                    161.12 k

**Comment by llamatester** [comment]
The adapter at projects/extra exports TVL: 
        
 
 
    optimism                  184.67 k
    
    total                    184.67 k

**Comment by g1nt0ki** [comment]
@ExtraFi thanks for the PR, I have refactored it a bit  to pull the info via logs instead of graph

**Comment by ExtraFi** [comment]
> @ExtraFi thanks for the PR, I have refactored it a bit to pull the info via logs instead of graph

thanks

**Pull request merged**
