### PR TITLE
add btcusd in base network

### PR DESCRIPTION
**Pull request by tlatkdgus1**
##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by g1nt0ki** [comment]
hi @tlatkdgus1 , this is a bridged token? how is it bridged?

**Comment by tlatkdgus1** [comment]
> hi @tlatkdgus1 , this is a bridged token? how is it bridged?

1. Yes, It is a bridged token 
2. using lock&mint method.

**Comment by g1nt0ki** [comment]
okay, I have added it here: https://github.com/DefiLlama/defillama-server/commit/b3fba2663644bd3f518ffd9c43f63b52bb0f3a7e

**Comment by tlatkdgus1** [comment]
> okay, I have added it here: [DefiLlama/defillama-server@b3fba26](https://github.com/DefiLlama/defillama-server/commit/b3fba2663644bd3f518ffd9c43f63b52bb0f3a7e)

Thank you :)

**Comment by tlatkdgus1** [comment]
> okay, I have added it here: [DefiLlama/defillama-server@b3fba26](https://github.com/DefiLlama/defillama-server/commit/b3fba2663644bd3f518ffd9c43f63b52bb0f3a7e)

Is it correct that this will be included in the URL below a little later?
https://defillama.com/stablecoin/bitcoin-usd

**Comment by g1nt0ki** [comment]
ah, you wanted it there. Can you share the bridge details and where token is locked in the bifrost network? https://github.com/DefiLlama/peggedassets-server/blob/master/src/adapters/peggedAssets/bitcoin-usd-btcfi/index.ts this file needs to be updated

**Comment by tlatkdgus1** [comment]
> 아, 거기에 원하셨군요. 브리지 세부 정보와 토큰이 bifrost 네트워크에서 잠긴 위치를 공유해 주실 수 있나요? https://github.com/DefiLlama/peggedassets-server/blob/master/src/adapters/peggedAssets/bitcoin-usd-btcfi/index.ts 이 파일을 업데이트해야 합니다.

Thank you, so is there any code or reference?

**Comment by tlatkdgus1** [comment]
> ah, you wanted it there. Can you share the bridge details and where token is locked in the bifrost network? https://github.com/DefiLlama/peggedassets-server/blob/master/src/adapters/peggedAssets/bitcoin-usd-btcfi/index.ts this file needs to be updated

BtcUSD is locked on [0xD85EB87caB9041ad00764b95796702b1104F42D7 ](https://explorer.mainnet.bifrostnetwork.com/address/0xD85EB87caB9041ad00764b95796702b1104F42D7)(Vault contract)- Bifrost Chain

and minted by [0x4F7aB59b5AC112970F5dD66D8a7ac505c8E5e08B ](https://basescan.org/address/0x4f7ab59b5ac112970f5dd66d8a7ac505c8e5e08b)(Vault contract) on Base chain

**Comment by tlatkdgus1** [comment]
@g1nt0ki Hello I hope you are having a great day.
I am wondering whether you had a chance to look at the details of our bridge.
Feel free to let me know if you have any questions.

**Pull request closed without merging**
