### PR TITLE
Sablier updates

### PR DESCRIPTION
**Pull request by PaulRBerg**
Made a few changes to the Sablier adapters.

- Renamed `sablier-v2` to `sablier-lockup`
- Renamed `sablier` to `sablier-legacy`

### CODE REVIEW

**Comment by PaulRBerg** [comment]
Can you please merge this PR at the same with https://github.com/DefiLlama/defillama-server/pull/8909, to avoid any downtime?

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
it is hard to tell, is there any logic change other than moving around code & renaming folders? 

We will change the name, but renaming folders actually break our system

**Comment by PaulRBerg** [comment]
Hey @g1nt0ki thanks for merging the PRs/.

> Is there any logic change other than moving around code & renaming folders?

No, but as per the other PR (https://github.com/DefiLlama/defillama-server/pull/8909#event-15742112278), we've renamed our product. Renaming the folders would keep them in sync with the new product names.

If it's too much of a hassle, happy to stick with `sablier` and `sablier-v2`, though in that case, I'd like to add a comment in the JavaScript code to explain the folder names.

I see that the following URLs all return 404 now:

- https://defillama.com/protocol/sablier-v1
- https://defillama.com/protocol/sablier-legacy
- https://defillama.com/protocol/sablier-v2
- https://defillama.com/protocol/sablier-lockup

**Comment by g1nt0ki** [comment]
hi @PaulRBerg sorry, missed the comment about PR in server repo, give it a few hours. Feel like this is a bug with new listings (or renaming protocol in your case), it should fix itself

**Comment by PaulRBerg** [comment]
Alright, thank you!

**Comment by PaulRBerg** [comment]
Hey @g1nt0ki, I see that the `/sablier-legacy` and the `/sablier-lockup` links work correctly. Thanks very much for that!

However, I am getting 404 not found errors for the `/sablier-v1` and `/sablier-v2` links.

Would it be possible to set redirects from `/sablier-v1` to `/sablier-legacy`, and from to `/sablier-v2` to `sablier-lockup`, pretty please?

**Comment by g1nt0ki** [comment]
> Hey @g1nt0ki, I see that the `/sablier-legacy` and the `/sablier-lockup` links work correctly. Thanks very much for that!
> 
> However, I am getting 404 not found errors for the `/sablier-v1` and `/sablier-v2` links.
> 
> Would it be possible to set redirects from `/sablier-v1` to `/sablier-legacy`, and from to `/sablier-v2` to `sablier-lockup`, pretty please?

hi, we should add a redirect, unfortunately we dont have that setup atm.

**Review by francescoiesu — COMMENTED** [review]
Ok

**Pull request merged**
