### PR TITLE
Lion Cave Tracking

### PR DESCRIPTION
**Pull request by gaspare100**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/scrub exports TVL: 
        
 
 
    cronos                    0
    kava                      0
    kava-pool2                208.23 k
    kava-staking              749.42 k
    cronos-staking            380.25219389742
    cronos-pool2              991.8497640753601
    pool2                     209.22 k
    staking                   749.80 k
    
    total                    0

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
This is not being added to total tvl in the end

**Comment by gaspare100** [comment]
Thanks! i missed it!  fixed now

**Comment by llamatester** [comment]
Error while running adapter at projects/scrub: 
        
 
  
    
    
    TypeError: Cannot read properties of null (reading 'toLowerCase')
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/cache/sumUnknownTokens.js:122:47
        at Array.forEach (<anonymous>)
        at getTokenPrices (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/cache/sumUnknownTokens.js:121:19)

**Comment by llamatester** [comment]
Error while running adapter at projects/scrub: 
        
 
  
    
    
    TypeError: Cannot read properties of null (reading 'toLowerCase')
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/cache/sumUnknownTokens.js:122:47
        at Array.forEach (<anonymous>)
        at getTokenPrices (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/cache/sumUnknownTokens.js:121:19)

**Comment by gaspare100** [comment]
Not sure what this error is about?

**Comment by llamatester** [comment]
Error while running adapter at projects/scrub: 
        
 
  
    
    
    TypeError: Cannot read properties of null (reading 'toLowerCase')
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/cache/sumUnknownTokens.js:122:47
        at Array.forEach (<anonymous>)
        at getTokenPrices (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/cache/sumUnknownTokens.js:121:19)

**Comment by llamatester** [comment]
Error while running adapter at projects/scrub: 
        
 
  
    
    
    TypeError: Cannot read properties of null (reading 'toLowerCase')
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/cache/sumUnknownTokens.js:122:47
        at Array.forEach (<anonymous>)
        at getTokenPrices (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/cache/sumUnknownTokens.js:121:19)

**Comment by llamatester** [comment]
Error while running adapter at projects/scrub: 
        
 
  
    
    
    TypeError: Cannot read properties of null (reading 'toLowerCase')
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/cache/sumUnknownTokens.js:122:47
        at Array.forEach (<anonymous>)
        at getTokenPrices (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/cache/sumUnknownTokens.js:121:19)

**Comment by llamatester** [comment]
Error while running adapter at projects/scrub: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:204:11

**Comment by llamatester** [comment]
The adapter at projects/scrub exports TVL: 
        
 
 
    kava                      0
    kava-staking              5.86 M
    kava-pool2                208.68 k
    staking                   5.86 M
    pool2                     208.68 k
    
    total                    0

**Comment by gaspare100** [comment]
Removed cronos as it's a no longer used chain. I would also like if possible to remove the cronos chain data compeltely from the tvl tracking retroactively, as everything tied to this data is already gone

**Comment by llamatester** [comment]
The adapter at projects/scrub exports TVL: 
        
 
 
    kava                      0
    cronos                    0
    kava-staking              5.65 M
    kava-pool2                208.73 k
    staking                   5.65 M
    pool2                     208.73 k
    
    total                    0

**Comment by g1nt0ki** [comment]
> Removed cronos as it's a no longer used chain. I would also like if possible to remove the cronos chain data compeltely from the tvl tracking retroactively, as everything tied to this data is already gone

sorry no, we cannot do that.

**Comment by g1nt0ki** [comment]
I dont want to remove past cronos data as it will affect that chain's tvl chart

**Pull request merged**
