### PR TITLE
add wstBfc

### PR DESCRIPTION
**Pull request by tlatkdgus1**
Name (to be shown on DefiLlama): BiFi
Twitter Link: https://twitter.com/bifi_lending
List of audit links if any:
https://github.com/bifrost-platform/BIFI/blob/master/docs/ENG/(ENG)_BiFi_BIFROST_Extension_Theori.pdf
https://github.com/bifrost-platform/BIFI/blob/master/docs/ENG/(ENG)_BiFi_Lending_Sooho_EN_Public.pdf
https://github.com/bifrost-platform/BIFI/blob/master/docs/ENG/(ENG)_BiFi_Token_Hexlant_EN.pdf
https://github.com/bifrost-platform/BIFI/blob/master/docs/ENG/(ENG)_BiFrost_BTC_Extension_CertiK.pdf
https://github.com/bifrost-platform/BiFi-X/blob/main/docs/bifrost_bifix_audit.pdf

Website Link: https://crosschain.bifi.finance/
Logo (High resolution, will be shown with rounded borders): https://raw.githubusercontent.com/bifrost-platform/AssetInfo/master/Protocols/images/bifi.png
Current TVL: 45.04 M
Treasury Addresses (if the protocol has treasury)
Chain: Bifrost Mainnet, Ethereum, BNB Chain, Polygon, Arbitrum, Base
Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
Short Description (to be shown on DefiLlama): Cross-chain collateralized lending with native assets - powered by Bifrost network. Utilize Ethereum, BNB, and Matic, directly from their native chains.
Token address and ticker if any:
Category (full list at https://defillama.com/categories) *Please choose only one: Lending
Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
forkedFrom (Does your project originate from another project): N/A
methodology (what is being counted as tvl, how is tvl being calculated): BiFi is a crosschain lending platform. To calculate the TVL of BiFi, we add all the deposited token and subtract borrowed amount of tokens
Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/bifrost-platform/BIFI

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bifi exports TVL: 
        
 
 
    bitcoin                   36.49 M
    bfc                       7.46 M
    ethereum                  532.48 k
    bsc                       443.98 k
    klaytn                    114.68 k
    ethereum-staking          24.55 k
    staking                   24.55 k
    avax                      10.02 k
    
    total                    45.05 M

**Comment by tlatkdgus1** [comment]
hello. We just launched wstBFC, which is a token with an exchange rate like stETH and wstETH. 

But our token is not registered on coingecko, and in the process of adding it to the repository, we didn't know how to calculate the price, so we applied the exchange rate and added it as a TVL of the BFC token. Is this the right way to do it? Or is there another way to do it? Please help.

**Comment by g1nt0ki** [comment]
hi, I have added price support to our server: https://github.com/DefiLlama/defillama-server/commit/b1860b79603b7b662111bf6fe2e30426c62454ca

Can you share bitcoin addresses where users lock bitcoin for your protocol, we are doing bit of cleanup and tracking all bitcoin addresses here: https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/projects/helper/bitcoin-book

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
.

**Comment by tlatkdgus1** [comment]
> hi, I have added price support to our server: [DefiLlama/defillama-server@b1860b7](https://github.com/DefiLlama/defillama-server/commit/b1860b79603b7b662111bf6fe2e30426c62454ca)
> 
> Can you share bitcoin addresses where users lock bitcoin for your protocol, we are doing bit of cleanup and tracking all bitcoin addresses here: https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/projects/helper/bitcoin-book

Thank you!

We're creating and serving vault addresses as they are requested by users, so we can't provide addresses statically.
[Link](https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/helper/bitcoin-book/fetchers.js#L10)

**Comment by llamatester** [comment]
The adapter at projects/bifi exports TVL: 
        
 
 
    bitcoin                   35.60 M
    bfc                       6.96 M
    ethereum                  515.13 k
    bsc                       422.17 k
    klaytn                    101.93 k
    ethereum-staking          24.55 k
    staking                   24.55 k
    avax                      8.39 k
    
    total                    43.60 M

**Comment by g1nt0ki** [comment]
> > hi, I have added price support to our server: [DefiLlama/defillama-server@b1860b7](https://github.com/DefiLlama/defillama-server/commit/b1860b79603b7b662111bf6fe2e30426c62454ca)
> > Can you share bitcoin addresses where users lock bitcoin for your protocol, we are doing bit of cleanup and tracking all bitcoin addresses here: https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/projects/helper/bitcoin-book
> 
> Thank you!
> 
> We're creating and serving vault addresses as they are requested by users, so we can't provide addresses statically. [Link](https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/helper/bitcoin-book/fetchers.js#L10)

hmm, if it is already counted under cdp product why are we counting it as tvl here.

**Comment by llamatester** [comment]
Error while running adapter at projects/bifi: 
        
 
  
    
    
    ReferenceError: wstBfc is not defined
    Truncated error stack:
    
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/bifi/index.js:72:27)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:173:9
        at async Promise.all (index 0)
        at async Promise.all (index 5)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:216:3

**Comment by llamatester** [comment]
The adapter at projects/bifi exports TVL: 
        
 
 
    bitcoin                   35.60 M
    bfc                       6.96 M
    ethereum                  515.13 k
    bsc                       422.17 k
    klaytn                    101.93 k
    ethereum-staking          24.55 k
    staking                   24.55 k
    avax                      8.39 k
    
    total                    43.61 M

**Comment by tlatkdgus1** [comment]
> > > 안녕하세요, 저희 서버에 가격 지원을 추가했습니다: [DefiLlama/defillama-server@b1860b7](https://github.com/DefiLlama/defillama-server/commit/b1860b79603b7b662111bf6fe2e30426c62454ca) 
> > > 프로토콜을 위해 사용자가 비트코인을 잠근 비트코인 ​​주소를 공유할 수 있나요? 저희는 여기에서 모든 비트코인 ​​주소를 정리하고 추적하고 있습니다: https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/projects/helper/bitcoin-book
> > 
> > 
> > 감사합니다!
> > 우리는 사용자의 요청에 따라 볼트 주소를 생성하고 제공하고 있으므로 정적으로 주소를 제공할 수 없습니다. [링크](https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/helper/bitcoin-book/fetchers.js#L10)
> 
> 음, 이미 CDP 제품으로 계산되었다면 왜 여기서는 TVL로 계산할까요?

i'm sorry. I added multiple projects and it got confusing.

I'll ask the team to clarify this and comment back.

**Comment by g1nt0ki** [comment]
thanks @tlatkdgus1

**Comment by llamatester** [comment]
The adapter at projects/bifi exports TVL: 
        
 
 
    bfc                       7.40 M
    ethereum                  521.92 k
    bsc                       438.67 k
    klaytn                    111.41 k
    ethereum-staking          21.55 k
    staking                   21.55 k
    avax                      9.21 k
    
    total                    8.48 M

**Comment by tlatkdgus1** [comment]
> thanks @tlatkdgus1

I checked, and it looks like this has been migrated to btcfi, so it should be deleted from BiFi.

Thank you for checking that out.

**Pull request merged**
