### PR TITLE
Add Kanvas TVL Adapter 

### PR DESCRIPTION
**Pull request by hamman247**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/Kanvas exports TVL: 
        
 
 
    kava-staking              0
    kava-pool2                0.0001267951855186855
    kava                      0.185981
    staking                   0
    pool2                     0.0001267951855186855
    
    total                    0.185981

**Comment by g1nt0ki** [comment]
@hamman247 can you please fill n the project details in PR

**Comment by g1nt0ki** [comment]
also, can you rename the folder as 'kanvas'

**Comment by hamman247** [comment]
Twitter Link: http://Twitter.com/kanvastrade

List of audit links if any: https://www.certik.com/projects/boofinance 

Website Link: https://www.kanvas.trade

Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): https://modernmobsters.tk/modernmobsters/kava_protocol/Kava_Frontend-main/Kava_Frontend-main/Kanavs_Logo.png

Current TVL: $2

Chain: Kava EVM

Coingecko ID (so your TVL can appear on Coingecko): N/A

Coinmarketcap ID (so your TVL can appear on Coinmarketcap): N/A

Short Description (to be shown on DefiLlama): We are a Fork of BooFinance based on the Kava EVM blockchain. Our primary goals are to provide value to our users and to create the largest an NFT marketplace on Kava.

Token address and ticker if any: 0xe005097aD7EeA379CE404011EEF68359B052cd0A  KVS

Category (full list at https://defillama.com/categories) *Please choose only one: NFT Marketplace

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using): TWAP https://explorer.kava.io/address/0x9DB69cC8db5B3bf22127734C609Add56B6C77Ae7/transactions

forkedFrom (Does your project originate from another project): BooFinance

methodology (what is being counted as tvl, how is tvl being calculated): tokens deposited in our farms, Staked Kanvas tokens and liquidity held in pools paired with our tokens are considered as TVL for our protocol. We hope to add additional ways for value to be locked into our protocol in the future.

**Comment by llamatester** [comment]
The adapter at projects/kanvas exports TVL: 
        
 
 
    kava-staking              0
    kava                      0.185981
    kava-pool2                0.012784006568757887
    staking                   0
    pool2                     0.012784006568757887
    
    total                    0.185981

**Pull request merged**
