### PR TITLE
Added Cakepie Adapter

### PR DESCRIPTION
**Pull request by karan-magpie**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### List of audit links if any: 1. https://github.com/peckshield/publications/blob/master/audit_reports/PeckShield-Audit-Report-Cakepie-v1.0.pdf
2. https://github.com/blocksecteam/audit-reports/blob/main/solidity/blocksec_cakepie_v1.0-signed.pdf

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at undefined: 
        
 
  \n Please revert changes to package.json / package-lock.json

**Comment by llamatester** [comment]
Error while running adapter at : 
        
 
  > Please revert changes to package.json / package-lock.json

**Comment by llamatester** [comment]
The adapter at projects/cakepie exports TVL: 
        
 
 
    bsc                       12.57 M
    
    total                    12.57 M

**Comment by g1nt0ki** [comment]
@karan-magpie thanks for the PR, sorry I removed bulk of the code that you added, main reason was, to keep the repo light, we already have support for pulling cake NFT values, I tweaked it a bit to pull if the nft is staked

**Comment by g1nt0ki** [comment]
@karan-magpie I am making an assumption that all pools that are going to be rewarded are v3, we might have to tweak the code a bit if you start supporting v2 LPs, but that is unlikely?

**Pull request merged**
