### PR TITLE
zkfox tvl

### PR DESCRIPTION
**Pull request by zkfoxdev**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/zkfox exports TVL: 
        
 
 
    era-borrowed              0
    era                       43.43 k
    borrowed                  0
    
    total                    43.43 k

**Comment by g1nt0ki** [comment]
@zkfoxdev can you please fill the form in the PR description, also I feel the there is double counting in your code, liquidity mining has started? All the tokens I see are compound tokens and for some reason they are being counted twice, also, borrowed tokens should not be counted towards tvl. If you are fine with my changes, we can merge the PR

**Comment by zkfoxdev** [comment]
@g1nt0ki ok,
Name (to be shown on DefiLlama):zkFox
Twitter Link:https://twitter.com/zk_zkfox
List of audit links if any:no
Website Link:https://zkfox.io
Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):https://zkfox.io/static/token-dfox.png
Current TVL:$43160
Treasury Addresses (if the protocol has treasury)
Chain:zkSync Era
Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
Short Description (to be shown on DefiLlama):zkFox is a leveraged income aggregator focusing on the DeFi ecology, built on zkSync. It is committed to building a complete ecological infrastructure of the public chain, allowing users to use leverage more conveniently to obtain higher returns.
Token address and ticker if any:0xaAf72D359ABC19751aC01f52f33A820041903322
Category (full list at https://defillama.com/categories) *Please choose only one:Leveraged Farming
Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):other
forkedFrom (Does your project originate from another project):no
methodology (what is being counted as tvl, how is tvl being calculated):Deposit funds+pool2 funds

**Comment by llamatester** [comment]
The adapter at projects/zkfox exports TVL: 
        
 
 
    era-borrowed              0
    era                       43.03 k
    borrowed                  0
    
    total                    43.03 k

**Pull request merged**
