### PR TITLE
Add Standard Protocol TVL on Mode

### PR DESCRIPTION
**Pull request by hskang9**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Standard Protocol

##### Twitter Link:
https://twitter.com/standardweb3

##### List of audit links if any:
https://github.com/standardweb3/standard-2.0-contracts/blob/main/audits/defimoon-2023/Standard%20Audit%20Report.pdf

##### Website Link:
https://standardweb3.com

##### Logo (High resolution, will be shown with rounded borders):
https://pbs.twimg.com/profile_images/1661304359370514432/czPQjwk7_400x400.jpg

##### Current TVL:
$551.8920279017999

##### Treasury Addresses (if the protocol has treasury)
None

##### Chain:
Mode

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
standard-protocol

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
standard-protocol

##### Short Description (to be shown on DefiLlama):
Standard Protocol has built a fully decentralized orderbook exchange where users match peer-to-peer. 

##### Token address and ticker if any:
$STND, 0x9040e237C3bF18347bb00957Dc22167D0f2b999d on Ethereum

##### Category (full list at https://defillama.com/categories) *Please choose only one:
DEXes

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
None
##### Implementation Details: Briefly describe how the oracle is integrated into your project:
None
##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
https://docs.standardweb3.com
##### forkedFrom (Does your project originate from another project):
None

##### methodology (what is being counted as tvl, how is tvl being calculated):
Balances of placed tokens to be matched in orderbook 

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/standardweb3

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/standard: 
        
 
  
    
    
    Error: Llama RPC error! methos: undefined 
    - host: https://1rpc.io/mode error: execution reverted
    - host: https://mainnet.mode.network error: execution reverted

**Comment by llamatester** [comment]
Error while running adapter at projects/standard: 
        
 
  
    
    
    Error: Llama RPC error! methos: undefined 
    - host: https://1rpc.io/mode error: execution reverted
    - host: https://mainnet.mode.network error: execution reverted

**Comment by g1nt0ki** [comment]
unsure why you are trying to delete those adapters, were they deployed by the same team? added your adapter here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/0660a1a05338f1dce98341915be24734ee3863b8

**Comment by hskang9** [comment]
Previous dev ran away after trying to embezzle the company fund, and UI is deprecated.

**Comment by g1nt0ki** [comment]
> Previous dev @billjhlee ran away after trying to embezzle the company fund, and UI is deprecated.

yeah, but we still need to preserve tvl history, so leave it as it is.

**Pull request closed without merging**
