### PR TITLE
feat: add line token rewards

### PR DESCRIPTION
**Pull request by Taump**
---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/line-token-rewards exports TVL: 
        
 
 
    obyte                     708.57 k
    
    total                    708.57 k

**Comment by g1nt0ki** [comment]
@Taump sorry, we can not count tokens held in wallets as tvl

**Comment by Taump** [comment]
@g1nt0ki The tests failed because there is no TVL adapter, and we can't create one as balances in wallets are not counted as TVL. Here, the rewards are based on balances in certain tokens held in wallets. Not sure if this yield adapter is still eligible.

**Comment by g1nt0ki** [comment]
closing this now, we can show yield without an adapter

**Comment by Define101** [comment]
Listing details
    id: "4953",
    name: "LINE Token Rewards",

**Pull request closed without merging**
