### PR TITLE
Add ParaSpace

### PR DESCRIPTION
**Pull request by jfzhou5**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/paraspace exports TVL: 
        
 
 
    ethereum-borrowed         15.56 M
    ethereum                  42.64 M
    borrowed                  15.56 M
    
    total                    42.64 M

**Comment by llamatester** [comment]
The adapter at projects/paraspace exports TVL: 
        
 
 
    ethereum                  42.53 M
    ethereum-borrowed         15.42 M
    borrowed                  15.42 M
    
    total                    42.53 M

**Comment by llamatester** [comment]
The adapter at projects/paraspace exports TVL: 
        
 
 
    ethereum-borrowed         15.42 M
    ethereum                  42.53 M
    borrowed                  15.42 M
    
    total                    42.53 M

**Comment by g1nt0ki** [comment]
> The adapter at projects/paraspace exports TVL:
> 
> ```
> ethereum-borrowed         15.42 M
> ethereum                  42.53 M
> borrowed                  15.42 M
> 
> total                    42.53 M 
> ```

the numbers I get here are quite different from yours: https://github.com/DefiLlama/DefiLlama-Adapters/pull/5268 

any idea why? 

Note: need to add 2M to tvl and 9M to borrowed as cAPE is not yet priced (will be fixed soon), so borrowed amount matches, but not tvl 42.53M vs 36.8 after breaking down into individual tokens/nfts


--- borrowed ---
WETH                      2.47 M
USDC                      2.31 M
APE                       1.17 M
USDT                      198.46 k
stETH                     13.56 k
DAI                       11
Total: 6.17 M 

--- tvl ---
BAYC                      18.72 M
MAYC                      8.17 M
WETH                      3.68 M
USDC                      2.74 M
BAKC                      340.73 k
OTHR                      304.61 k
USDT                      244.66 k
WPUNKS                    105.61 k
stETH                     75.83 k
MOONBIRD                  71.58 k
AZUKI                     68.60 k
PPG                       41.99 k
CloneX                    40.62 k
⚇                         20.38 k
APE                       5.98 k
DAI                       2.08 k
Total: 34.63 M 

------ TVL ------
ethereum-borrowed         6.17 M
ethereum                  34.63 M
borrowed                  6.17 M

total                    34.63 M

**Comment by jfzhou5** [comment]
There are 3 reasons for the difference: 
1. We use the on-chain oracle price to calculate NFT TVL. the oracle price is different from your price. 
2. SAPE and cAPE are based on ApeCoin, their prices are the same as ApeCoin, And their TVL and borrowed are not included in your calculation.
3. For the special NFT UNI-V3-POS, its TVL isn't included in your TVL.

**Comment by jfzhou5** [comment]
I reference Benddao's calculation, we just convert all token TVL to ETH price-based TVL.

**Comment by g1nt0ki** [comment]
okay, found the issue, you are using bendDAO oracle and we are relying on chainlink oracles.

**Comment by jfzhou5** [comment]
I see you have merged the PR you raised which TVL is 34.63 M, but we want to show the 42.53M. is there any problem ? @ @g1nt0ki

**Comment by g1nt0ki** [comment]
> There are 3 reasons for the difference:
> 
>     1. We use the on-chain oracle price to calculate NFT TVL. the oracle price is different from your price.
> 
>     2. SAPE and cAPE are based on ApeCoin, their prices are the same as ApeCoin, And their TVL and borrowed are not included in your calculation.
> 
>     3. For the special NFT UNI-V3-POS, we have the on-chain method to get the price for every NFT, its TVL isn't included in your TVL.

@jfzhou5 sorry,  I had missed this comment, but we are including the uni v3 positions and staking now (right?) https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/paraspace/helper/index.js#L24

**Pull request merged**
