### PR TITLE
Track borrowed assets for JPEG'd

### PR DESCRIPTION
**Pull request by kargakis**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/jpeg-d exports TVL: 
        
 
 
    ethereum-staking          2.00 M
    ethereum-treasury         38.62 M
    ethereum-borrowed         10.37 M
    ethereum-pool2            159.22 k
    ethereum                  10.52 M
    staking                   2.00 M
    treasury                  38.62 M
    borrowed                  10.37 M
    pool2                     159.22 k
    
    total                    10.52 M

**Comment by g1nt0ki** [comment]
Sorry, I dont think this logic is correct. Borrowed is when tokens deposited by users are borrowed by other users https://docs.llama.fi/list-your-project/what-to-include-as-tvl, pusd is minted in your protocol right?

**Comment by kargakis** [comment]
@g1nt0ki PUSD is minted as leverage on top of deposits (essentially it is borrowed from the protocol) but I guess since you are not tracking DAI as borrowed in MakerDAO then it does not make sense to track here either?

**Comment by kargakis** [comment]
LTV ratio is quite low so borrowed assets here should be way lower than 10M (since TVL is 10M). If you think it makes sense to get this merged, I will need to rework this to subtrack DAO-owned liquidity.

**Comment by g1nt0ki** [comment]
> @g1nt0ki PUSD is minted as leverage on top of deposits (essentially it is borrowed from the protocol) but I guess since you are not tracking DAI as borrowed in MakerDAO then it does not make sense to track here either?

exactly, we dont count the dai for makerdao.

**Pull request closed without merging**
