### PR TITLE
Add Wombat exchange adapter

### PR DESCRIPTION
**Pull request by corey-wombat**
##### List of audit links if any:
- https://hacken.io/audits/#wombat_exchange
- https://github.com/peckshield/publications/blob/master/audit_reports/PeckShield-Audit-Report-Wombat-v1.0.pdf

##### Website Link:
https://www.wombat.exchange/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
wombat_logo_trans-no_text

##### methodology (what is being counted as tvl, how is tvl being calculated):
The TVL is calculated by the sum of all assets, which equivalent to the total deposited tokens + plus the fees generated.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/wombat-exchange exports TVL: 
        
 
 
    bsc                       20.00 M
    
    total                    20.00 M

**Comment by realdealshaman** [comment]
Hey, could you tell us a little about how Chainlink and Band are securing your TVL?

**Comment by corey-wombat** [comment]
> Hey, could you tell us a little about how Chainlink and Band are securing your TVL?

We are not using Chainlink or any other price oracles for securing our TVL. Our stableswap algo does not require asset price input to perform a swap. We just use Chainlink / Band for internal price feed monitoring. You may read our white paper for more details: https://www.wombat.exchange/Wombat_Whitepaper_Public.pdf

**Comment by corey-wombat** [comment]
@realdealshaman 
Could you update the audit links and logo for us?
another audit report from Zokyo: https://www.wombat.exchange/zokyo_wombat_audit_report.pdf
and pls use this logo instead: 
wombat logo-y-icon

**Comment by Define101** [comment]
Of course
Should be live on the website within 1 hour

**Pull request merged**
