### PR TITLE
Lachainbridge integration

### PR DESCRIPTION
**Pull request by kunalgoyal9**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/lachainBridge.js exports TVL: 
        
 
 
    avalanche                 10.17796034000001
    arbitrum                  0
    heco                      1
    polygon                   1.10 k
    fantom                    0.6753858597
    bsc                       45.87 k
    harmony                   0.04401677
    ethereum                  34.80 k
    
    total                    81.78 k

**Comment by kunalgoyal9** [comment]
@g1nt0ki Can't I add latoken supplies on other chains like Ethereum or polygon? They are also contributing to bridge TVL. 

If not what is other alternative for this to show?

**Comment by g1nt0ki** [comment]
@kunalgoyal9 Sorry, I am against the idea of adding latoken to tvl because it is your own token

**Comment by g1nt0ki** [comment]
closing this in favor of https://github.com/DefiLlama/DefiLlama-Adapters/pull/2800

**Pull request closed without merging**
