### PR TITLE
feat: update multi chain

### PR DESCRIPTION
**Pull request by 0xdigiscore**
Hello, we would like to update the basic description of OmniBTC, including supported multi chains.
OmniBTC's lending currently uses sui as the settlement center and supports full-chain lending protocols including arb, op, base, polygon and other chains. Users can supply collateral on any chain and borrow on any chain. Our tvl is to count the assets on each chain contract.
image

##### Name (to be shown on DefiLlama):
OmniBTC

##### Chain:
arbitrum, base, optimism, sui

Short Description (to be shown on DefiLlama):

OmniBTC is an omnichain financial system aiming to connect and unify all the on-chain liquidity.
The hub of the system is DOLA Protocol, a Decentralized Omnichain Liquidity Aggregation Protocol, which enables users & dapps to realize fully composable cross-chain DeFi Transactions.
By using DOLA Protocol and connecting with other DEXs and Bridges, there are some user-friendly omnichain financial applications in OmniBTC, such as OmniSwap/OmniLending.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/omnibtc exports TVL: 
        
 
 
    sui-borrowed              1.11 M
    sui                       723.19 k
    borrowed                  1.11 M
    
    total                    723.19 k

**Comment by llamatester** [comment]
Error while running adapter at projects/omnibtc: 
        
 
  
    
    
    Error: 
        Found export keys that were not part of specification: suiTvl
    
        List of valid keys: 
    				
    				tvl
    				staking
    				methodology
    				pool2
    				misrepresentedTokens
    				fetch
    				timetravel
    				borrowed
    				start
    				doublecounted
    				treasury
    				hallmarks
    				incentivized
    				offers
    				deadFrom
    				broken
    				ownTokens
    				vesting

**Comment by llamatester** [comment]
The adapter at projects/omnibtc exports TVL: 
        
 
 
    arbitrum                  0
    base                      0
    optimism                  0
    polygon                   0
    sui                       723.43 k
    sui-borrowed              1.11 M
    borrowed                  1.11 M
    
    total                    723.43 k

**Comment by llamatester** [comment]
The adapter at projects/omnibtc exports TVL: 
        
 
 
    sui-borrowed              1.12 M
    sui                       726.50 k
    base                      14.412188790999998
    polygon                   16.72 k
    arbitrum                  81.40 k
    optimism                  4.93 k
    borrowed                  1.12 M
    
    total                    829.55 k

**Comment by llamatester** [comment]
The adapter at projects/omnibtc exports TVL: 
        
 
 
    polygon                   16.72 k
    optimism                  4.93 k
    arbitrum                  81.37 k
    sui                       726.40 k
    sui-borrowed              1.12 M
    base                      14.391628745452
    borrowed                  1.12 M
    
    total                    829.43 k

**Comment by llamatester** [comment]
The adapter at projects/omnibtc exports TVL: 
        
 
 
    sui-borrowed              1.11 M
    sui                       724.03 k
    arbitrum                  107.23 k
    base                      21.8224813975
    polygon                   17.01 k
    optimism                  9.97 k
    borrowed                  1.11 M
    
    total                    858.26 k

**Comment by g1nt0ki** [comment]
hi @0xdigiscore 

The PR looks good, is there some way to fetch borrowed in for other chains as well?

**Comment by 0xdigiscore** [comment]
> hi @0xdigiscore
> 
> The PR looks good, is there some way to fetch borrowed in for other chains as well?

Our settlement center is on SUI now, and the borrow of other chains can be calculated through the pool status on SUI. We will raise a pr to solve the borrowed data recently.

**Pull request merged**
