### PR TITLE
Add Bitgert 

### PR DESCRIPTION
**Pull request by MarvinK97**
##### Twitter Link:
https://twitter.com/bitgertbrise

##### Website Link: 
https://bitgert.com/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

https://bitgert.com/wp-content/uploads/2021/12/Bitgert-750-x-250-px-2.png

##### Current TVL: 
167.31 M

##### Chain:
bitgert

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
bitrise-token

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): 
11079

##### Short Description (to be shown on DefiLlama):
The Zero-Cost Gas Fee Blockchain

##### Token address and ticker if any:
Native
BSC: 0x8fff93e810a2edaafc326edee51071da9d398e83
Bitgert: 0x0eb9036cbE0f052386f36170c6b07eF0a0E3f710

##### Category (full list at https://defillama.com/categories) *Please choose only one:
EVM Chain

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
vercel.app
coingecko.com

##### forkedFrom (Does your project originate from another project):
Ethereum

##### methodology (what is being counted as tvl, how is tvl being calculated):
circulating supply * price in usd

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/bitgert: 
        
 
  
    
    
    Error: TVL for key tvl is not a number, instead it is NaN
    Truncated error stack:
    
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:81:11)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:207:3

**Comment by MarvinK97** [comment]
fixed Error

**Comment by llamatester** [comment]
The adapter at projects/bitgert exports TVL: 
        
 
 
    
    total                    166.89 M

**Comment by g1nt0ki** [comment]
@MarvinK97 sorry, I dont think we can count circulating marketcap of bitgert as tvl

**Comment by simone1999** [comment]
ok, can you specify how exectly you would want the TVL of a chain to be calculated? It is clear how to do that on e.g. a DEX where I can just take the Value of the total provided liquidity, but how is that for a Blockchain? Is it the sum of all TVL in all DeFi projects on that chain? also are time locked wrapped coins part of the total value locked and are bridged out and bridged in tokens from other chains part of that TVL?
Thx for your help.

**Pull request closed without merging**
