### PR TITLE
Add Krystal

### PR DESCRIPTION
**Pull request by toidv**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Current TVL: 
------ TVL ------
arbitrum                  938.10 k
ethereum                  127.65 k
base                      0
optimism                  0
polygon                   0

total                    1.07 M

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/krystal exports TVL: 
        
 
 
    arbitrum                  930.77 k
    ethereum                  127.99 k
    polygon                   0
    optimism                  0
    base                      0
    
    total                    1.06 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
setting aside the fact that this is expensive way to compute tvl (partly because you have disabled caching)

the protocol does not hold the tokens/NFTs but users hold them? like here: https://etherscan.io/tx/0xb5bdd815ea0c442ab4ff3ef57e3027eedcc8827834c1b33c81eda9d68bec96fc

if that is the case, sorry but your protocol has no tvl, but we can track other metrics like volume/fees/revenue of your protocol

**Comment by toidv** [comment]
@g1nt0ki, I'm disabling the caching because it sometimes doesn't function correctly in local. We'll re-enable it (restoring the caching). Regarding tvl, we actually use the term "assets under management" as Krystal manages user nftId for operations such as zapIn, zapOut, rebalance, and compound... Additionally, we offer an automation feature (contract, for example: https://arbiscan.io/address/0x47dc0150d74d30118532a436846bd36c3390abc3) where users delegate permission to Krystal to manage their NFTs, a process which differs from the vault approach. How can we reflect these values in DefiLlama? Detailed instructions will really help us

**Comment by g1nt0ki** [comment]
@toidv my guess for log issue is, if you are pulling two diff topics for same contract the cache returns data only from first topic, an oversight on my part not creating unique cache files based on topic hash as well (by default)

Sorry, atm we consider only tokens locked in your protocol as tvl, same reason why we show opensea tvl as 0

**Pull request closed without merging**
