### PR TITLE
Add Avely-Finance staking and swap

### PR DESCRIPTION
**Pull request by Yahook**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Twitter Link:
https://twitter.com/AvelyFinance

##### List of audit links if any:
https://github.com/lucash-dev/audits/blob/main/audit2023-02-27-updated-1.pdf
https://github.com/Dedaub/audits/blob/main/Avely%20Finance/Avely%20Audit%20Report.pdf

##### Website Link:
https://avely.fi/
https://dapp.avely.fi/ - staking
https://dapp.avely.fi/swap - swap

##### Logo (High resolution, will be shown with rounded borders):
https://drive.google.com/file/d/1zxiDwNZ1-D8aCjglUnFIOWufsa54eCkt/view?usp=share_link (png)
https://drive.google.com/file/d/1SmK44rxBh8u6OwtzZ6NelvmJzYUONSnv/view?usp=share_link (svg)

##### Current TVL:
Avely Staking: $333,267
Avely Swap: $275,409.49

##### Chain:
Zilliqa

##### Short Description (to be shown on DefiLlama):
Avely is a leading-edge liquid staking protocol built on the Zilliqa blockchain.

##### Token address and ticker if any:
zil1umc54ly88xjw4599gtq860le0qvsuwuj72s246 - liquid staking token, stZIL

##### Category (full list at https://defillama.com/categories) *Please choose only one:
[Liquid Staking](https://defillama.com/protocols/Liquid%20Staking)

##### methodology (what is being counted as tvl, how is tvl being calculated):
Avely Staking: TVL represents the sum of stakes denominated in ZIL and staked in the native Zilliqa staking contract via the STZIL contract, along with the amount of correspondingly minted StZIL tokens.
Avely Swap: TVL represents the state of the Aswap pool, which consists of a single liquidity pair: Zilliqa native token vs StZIL token.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/avely-finance-staking exports TVL: 
        
 
 
    zilliqa                   331.16 k
    
    total                    331.16 k

**Comment by llamatester** [comment]
The adapter at projects/avely-finance-swap exports TVL: 
        
 
 
    zilliqa                   136.54 k
    
    total                    136.54 k

**Comment by llamatester** [comment]
The adapter at projects/avely-finance-staking exports TVL: 
        
 
 
    zilliqa                   338.87 k
    
    total                    338.87 k

**Comment by llamatester** [comment]
The adapter at projects/avely-finance-swap exports TVL: 
        
 
 
    zilliqa                   139.92 k
    
    total                    139.92 k

**Comment by g1nt0ki** [comment]
@Yahook thanks for the PR

It is mostly good, except for the part where you count stZil supply as tvl, I have removed that. Thanks again.

**Pull request merged**
