### PR TITLE
Add energiswap

### PR DESCRIPTION
**Pull request by 0xngmi**
See #61

### CODE REVIEW

**Comment by TobyKreiselmaier** [comment]
@0xngmi Thank you, that works for me! However, even though #66 is merged, I don't see it on the production site. When do you expect it to be listed?

**Comment by 0xngmi** [comment]
@TobyKreiselmaier Adding a project involves some extra work such as getting their icon, putting all the new data on the database... As of right now there's a bit of a backlog with all the projects that just got merged in #65, so it may take a little bit longer, but eventually we'll add yours :)

**Comment by TobyKreiselmaier** [comment]
@0xngmi Thank you so much! Sounds good...

**Comment by TobyKreiselmaier** [comment]
@0xngmi I see that we are now listed. Great news! Thank you! However, could you please change the blockchain from `Ethereum` to `Energi` as described in the template?

**Comment by 0xngmi** [comment]
> However, could you please change the blockchain from Ethereum to Energi as described in the template?

@TobyKreiselmaier sorry about that, I'll queue that change right up!

**Comment by TobyKreiselmaier** [comment]
@0xngmi Thank you! Now marketing asked me to provide you with better image for our logo as well. Could you please use this?

Energiswap

**Comment by 0xngmi** [comment]
Sure!

**Comment by TobyKreiselmaier** [comment]
@0xngmi Thank you for the Logo and the blockchain update! However, I just saw that we are given category `Others`, Energiswap really is a `DEX`. Please change and also list under `Dexes`.

**Pull request merged**
