### PR TITLE
Upd staking and add tvl

### PR DESCRIPTION
**Pull request by Doctor-Cyclone**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@Doctor-Cyclone hi, what is the reason for the PR? why do want to remove the other chains

**Comment by Doctor-Cyclone** [comment]
@g1nt0ki, In the current staking we use only BSC chain.

**Comment by g1nt0ki** [comment]
yeah, but what about rest of the tvl?

**Comment by g1nt0ki** [comment]
also, what happened on June 24? tvl drops a lot after that

**Comment by Doctor-Cyclone** [comment]
@g1nt0ki, Our liquidity is stuck with Harmony due to their bridge hack.
We closed our cross-chain and now the aggregators of other cross-chain providers.
We have no debt to users. Project funds are stuck.

**Comment by g1nt0ki** [comment]
sorry to hear about project fund

**Comment by llamatester** [comment]
Error while running adapter at projects/rubic: 
        
 
  
    
    
    ReferenceError: sdk is not defined
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/rubic/index.js:11:25
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:59:31)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:162:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:150:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:145:44

**Comment by llamatester** [comment]
Error while running adapter at projects/rubic: 
        
 
  
    
    
    ReferenceError: usdcByChain is not defined
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/rubic/index.js:13:15
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:59:31)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:162:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:150:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:145:44

**Comment by llamatester** [comment]
Error while running adapter at projects/rubic: 
        
 
  
    
    
    ReferenceError: pools is not defined
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/rubic/index.js:13:68
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:59:31)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:166:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:154:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:149:44

**Comment by Doctor-Cyclone** [comment]
Rewrote the file a little bit

**Comment by llamatester** [comment]
Error while running adapter at projects/rubic: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:223:11

**Comment by g1nt0ki** [comment]
add this line to `tvl: () => ({})` under bsc, this would set tvl as 0

**Comment by g1nt0ki** [comment]
sorry, I ended up fixing it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/3581

**Comment by Doctor-Cyclone** [comment]
@g1nt0ki, Can you reset other chain to show only the BSC value?

**Comment by g1nt0ki** [comment]
> @g1nt0ki, Can you reset other chain to show only the BSC value? Or what do I need to do to do that?

in the UI? 

Right now, it will only show bsc tvl as 0, and the staking after my change

**Comment by Doctor-Cyclone** [comment]
@g1nt0ki, And there is a possibility to remove the graph of old stakings and leave only for the current staking?

**Comment by g1nt0ki** [comment]
if you mean historical tvl, the answe is no. 
I left the old staking addresses as there is still some tokens in there, also helpful for refilling old data

**Pull request closed without merging**
