### PR TITLE
solace-fi defillama adapter integration

### PR DESCRIPTION
**Pull request by ssozuer**
##### List of audit links if any:
https://solace.fi/static/media/Solace-Quantstamp-Report.44617837.pdf
https://hacken.io/audits/#solace

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
Logo Color

Logo Color on Black

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
coingecko id: solace

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
cmc id: 15735

##### Short Description (to be shown on DefiLlama):
Solace is a decentralized coverage protocol based on automatic claim assessment, intelligent risk assessment, and acquiring own capital to provide an easy and risk-free experience for users and underwriters.

##### methodology (what is being counted as tvl, how is tvl being calculated):
- Solace underwriting pools
- Solace Staking contracts
- Solace wallet coverage product(Soteria) account balances(https://medium.com/solace-fi/solace-releases-total-wallet-coverage-e82cfa9fee77)

### CODE REVIEW

**Comment by ssozuer** [comment]
Hello,
Because of solace is multichain protocol we've implemented "fetcher" sdk adapter. The TVL implementation details can be found from https://github.com/solace-fi/solace-stats/tree/main/api/tvl.

Thank You
Selcuk

**Comment by waynebruce0x** [comment]
Can TVL be split by chain?

**Comment by ssozuer** [comment]
We can, but we want to display total tvl  across chains.

**Comment by waynebruce0x** [comment]
yeah sure so your headline TVL will be TVL across all chains, but for us to show solace as being on each chain we need a chain by chain breakdown

**Comment by ssozuer** [comment]
@waynebruce0x Is this correct chain separation?

`async function tvl(chain) {
  // github repository https://github.com/solace-fi/solace-stats
  var res = await retry(async bail => await axios.get(`https://stats.solace.fi/tvl?chain=${chain}`));
  var tvl = parseFloat(res["data"]["tvl_usd"]);
  return tvl;
}

module.exports = {
  ethereum: {
    tvl("mainnet")
  },
  bsc: {
    tvl("bsc")
  },
  aurora: {
    tvl("aurora")
  },
  polygon: {
    tvl("polygon")
  }
}`

**Comment by waynebruce0x** [comment]
Yes that works thanks

**Comment by llamatester** [comment]
Error while running adapter at projects/solace-finance/index.js: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:206:11
        at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by ssozuer** [comment]
> Error while running adapter at projects/solace-finance/index.js:
> 
> ```
> Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
>     at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:206:11
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> ```

PR is updated.

**Comment by ssozuer** [comment]
Hey @waynebruce0x any update?

**Comment by llamatester** [comment]
The adapter at projects/solace-finance/index.js exports TVL: 
        
 
 
    bsc                       0
    aurora                    0
    ethereum                  4.08 M
    polygon                   6.18 k
    
    total                    4.08 M

**Comment by waynebruce0x** [comment]
Whats included in these numbers? Can we calculate this on chain instead?

**Comment by ssozuer** [comment]
> 

1- Underwriting Pools(Gnosis addresses)
2- Solace Staking contracts
3- Solace Wallet Coverage contracts(users deposit stablecoins to activate policy coverage for their positions)

I also added the github repository link. It is open source and everyone can see calculation logic and contracts.

I wrote calculations in python. Maybe in the future, we can convert it to javascript and write everything in the index.js file. For now, we don't have enough resource to implement it. Also please don't forget the our all tvl calculation is open source and public. Everyone can see it. I also adding the code in below.


```
from api.utils import *
import asyncio

DATA = {
    "mainnet": {
        "uwp": ["0x5efC0d9ee3223229Ce3b53e441016efC5BA83435"],
        "xslocker": ["0x501Ace47c5b0C2099C4464f681c3fa2ECD3146C1"],
        "soteria": ["0x501ACEbe29eabc346779BcB5Fd62Eaf6Bfb5320E"]
    },
    "polygon": {
        "uwp": ["0xd1108a800363c262774b990e9df75a4287d5c075"],
        "xslocker": ["0x501Ace47c5b0C2099C4464f681c3fa2ECD3146C1"],
        "soteria": ["0x501AcEC83d440c00644cA5C48d059e1840852a64"]
    },
    "aurora": {
        "uwp": ["0x4A6B0f90597e7429Ce8400fC0E2745Add343df78"],
        "xslocker": ["0x501Ace47c5b0C2099C4464f681c3fa2ECD3146C1"],
        "soteria": []
    }
}

ETH_PRICE = 0
SOLACE_PRICE = 0

def fetch_solace_price():
    global SOLACE_PRICE

    if SOLACE_PRICE != 0:
        return SOLACE_PRICE

    w3 = Web3(Web3.HTTPProvider("https://eth-mainnet.alchemyapi.io/v2/{}".format(alchemy_key)))
    usdc_pool = w3.eth.contract(address=w3.toChecksumAddress(SOLACE_USDC_POOL), abi=sushiswap_lp_abi)
    result = usdc_pool.functions.getReserves().call()
    usdc_amount = result[1] // 10**6
    solace_amount = result[0] // 10**18
    solace_price_usd = usdc_amount / solace_amount
    SOLACE_PRICE = solace_price_usd
    return SOLACE_PRICE

def fetch_eth_price():
    global ETH_PRICE
    
    if ETH_PRICE != 0:
        return ETH_PRICE

    for i in range(5):
        try:
            url = "https://api.zapper.fi/v1/prices/0x0000000000000000000000000000000000000000?network=ethereum&timeFrame=hour&currency=USD&api_key=96e0cc51-a62e-42ca-acee-910ea7d2a241"
            response = requests.get(url, timeout=600)
            response.raise_for_status()
            res = response.json()
            # gives prices over the last hour, average
            prices = res["prices"]
            count = 0
            s = 0
            for price in prices:
                count += 1
                s += price[1]
            price = s / count
            if price <= 1000 or price >= 10000:
                raise("price out of range")
            ETH_PRICE = price
            return ETH_PRICE
        except Exception as e:
            print(e)
    raise Exception("error fetching data")

def fetch_positions(address):
    for i in range(5):
        try:
            api_key = "96e0cc51-a62e-42ca-acee-910ea7d2a241" # only key key, public
            url = f"https://api.zapper.fi/v1/balances?api_key={api_key}&addresses[]={address}"
            response = requests.get(url, timeout=600)
            response.raise_for_status()
            return response.text
        except Exception as e:
            print(e)
    raise Exception("error fetching data")

def parse_positions(s):
    try:
        balances = []
        while True:
            index = s.find('{')
            index2 = s.find('}\n')
            if index == -1 or index2 == -1:
                break
            position = json.loads(s[index:index2+1])
            balances.append(position)
            s = s[index2+1:]
        return balances
    except Exception as e:
        raise Exception(f"Error parsing data. Error: {e}")

def clean_positions(positions, account):
    eth_price = fetch_eth_price()
    try:
        clean_positions = []
        account = account.lower()
        for position in positions:
            if 'balances' not in position:
                continue

            # filter out zero balance positions
            if len(position["balances"][account]["products"]) == 0:
                continue
            
            if position["appId"] != "tokens":
                continue
            # flatten
            balanceUSD = 0
            for pos in position["balances"][account]["products"]:
                for asset in pos["assets"]:
                    balanceUSD += asset["balanceUSD"]
            position["balanceUSD"] = balanceUSD
            position["balanceETH"] = balanceUSD / eth_price
            position.pop("balances", None)
            clean_positions.append(position)
        return clean_positions
    except Exception as e:
        raise Exception(f"error cleaning positions data. Error {e}")

def get_tvl_by_zapper(address):
    try:
        tvl_usd = 0
        tvl_eth = 0
 
        positions = fetch_positions(address)
        parsed_positions = parse_positions(positions)
        cleaned_positions = clean_positions(parsed_positions, address)
      
        for position in cleaned_positions:
            tvl_usd += position["balanceUSD"]
            tvl_eth += position["balanceETH"]
        return {"tvl_usd": tvl_usd, "tvl_eth": tvl_eth}
    except Exception as e:
        raise Exception(f"Error occurred while getting tvl value. Error: {e}")

def get_solace_balance(network, address):
    if network == "mainnet":
        w3 = Web3(Web3.HTTPProvider("https://eth-mainnet.alchemyapi.io/v2/{}".format(alchemy_key)))
        solace = w3.eth.contract(address=SOLACE_ADDRESS, abi=erc20Json)
        balance = solace.functions.balanceOf(address).call()
        balance_normalized = balance / ONE_ETHER
        return {"tvl_usd": balance_normalized * SOLACE_PRICE, "tvl_eth": (balance_normalized * SOLACE_PRICE) / ETH_PRICE}
    elif network == "polygon":
        # TODO: implemement
        return {"tvl_usd": 0, "tvl_eth": 0}
    elif network == "aurora":
        # TODO: implement
        return {"tvl_usd": 0, "tvl_eth": 0}
    else:
        return {"tvl_usd": 0, "tvl_eth": 0}

async def get_soteria_tvl(chain, addresses):
    try:
        if len(addresses) == 0:
            return {"tvl_usd": 0, "tvl_eth": 0}

        print("\n################# Soteria TVL Calculation #################")
        tvl_usd = 0
        tvl_eth = 0
        # mainnet and polygon tvl calculation via zapper api
        # TODO: need to implement for aurora
        for v in addresses:
            if chain == "aurora":
                continue

            print(f"\nCalculating tvl for Soteria address {v} in {chain} started")
            result = get_tvl_by_zapper(v)
            tvl_usd += result["tvl_usd"]
            tvl_eth += result["tvl_eth"]
            print(f"{chain}({v}): usd: {result['tvl_usd']} eth: {result['tvl_eth']}")
        return {"tvl_usd": tvl_usd, "tvl_eth": tvl_eth}  
    except Exception as e:
        raise Exception(f"Error occurred while getting tvl values for Soteria. Error: {e}")

async def get_uwp_tvl(chain, addresses):
    try:
        if len(addresses) == 0:
            return {"tvl_usd": 0, "tvl_eth": 0}

        print("\n################# Underwriting Pool TVL Calculation #################")
        tvl_usd = 0
        tvl_eth = 0
        # mainnet and polygon tvl calculation via zapper api
        # TODO: need to implement for aurora
        for v in addresses:
            if chain == "aurora":
                continue

            print(f"\nCalculating tvl for underwriting pool address {v} in {chain} started")
            result = get_tvl_by_zapper(v)
            tvl_usd += result["tvl_usd"]
            tvl_eth += result["tvl_eth"]

            solace_result = {"tvl_usd": 0, "tvl_eth": 0}
            if chain == "mainnet":
                solace_result = get_solace_balance(chain, v)
                tvl_usd += solace_result["tvl_usd"]
                tvl_eth += solace_result["tvl_eth"]
            print(f"{chain}({v}): usd: {result['tvl_usd'] + solace_result['tvl_usd']} eth: {result['tvl_eth'] + solace_result['tvl_eth']}")

        return {"tvl_usd": tvl_usd, "tvl_eth": tvl_eth}  
    except Exception as e:
        raise Exception(f"Error occurred while getting tvl values for underwriting pool. Error: {e}")

async def get_stacked_tvl(chain, addresses):
    try:
        if len(addresses) == 0:
            return {"tvl_usd": 0, "tvl_eth": 0}

        print("\n################# Staked SOLACE TVL Calculation #################")
        tvl_usd = 0
        tvl_eth = 0

        for v in addresses:
            print(f"\nCalculating tvl for staked solace address {v} in {chain} started")
            result = get_solace_balance(chain, v)
          
            print(f"{chain}({v}): usd: {result['tvl_usd']} eth: {result['tvl_eth']}")
            tvl_usd += result["tvl_usd"]
            tvl_eth += result["tvl_eth"]
        return {"tvl_usd": tvl_usd, "tvl_eth": tvl_eth}  
    except Exception as e:
        raise Exception(f"Error occurred while getting tvl values for staked solace. Error: {e}")

async def get_tvl(chain, apps: dict):
    tvl_usd = 0
    tvl_eth = 0
    for k, v in apps.items():
        result = {"tvl_usd": 0, "tvl_eth": 0}
        if k == "uwp":
            result = await get_uwp_tvl(chain, v)
        elif k == "xslocker":
            result = await get_stacked_tvl(chain, v)
        elif k == "soteria":
            result = await get_soteria_tvl(chain, v)
        else:
            print(f"Unsupported tvl operation for {k}")
            continue
        tvl_usd += result["tvl_usd"]
        tvl_eth += result["tvl_eth"]
    return {"chain": chain, "tvl_usd": tvl_usd, "tvl_eth": tvl_eth}

async def calculate_tvl():
    global ETH_PRICE
    global SOLACE_PRICE
    try:
        print("Calculating tvl has been started...")
        ETH_PRICE = fetch_eth_price()
        SOLACE_PRICE = fetch_solace_price()
        tvl_info = {}
        tasks = []
        for chain, addresses in DATA.items():
            tvl_info[chain] = {"tvl_usd": 0, "tvl_eth": 0}
            tasks.append(asyncio.create_task(get_tvl(chain, addresses)))

        completed_tasks, _ = await asyncio.wait(tasks)
        for completed_task in completed_tasks:
            result = completed_task.result()
            chain = result["chain"]
            tvl_info[chain]["tvl_usd"] += result["tvl_usd"]
            tvl_info[chain]["tvl_eth"] += result["tvl_eth"]
        print("Calculating tvl has been finished.\n")

        ETH_PRICE = 0
        SOLACE_PRICE = 0
        print(tvl_info)
        s3_put(S3_TVL_FILE, json.dumps(tvl_info))

    except Exception as e:
        print(f"Error occurred while calculating tvl: Error: {e}")

def main(event, context):
    asyncio.run(calculate_tvl())

if __name__ == '__main__':
   # main(None, None)
   chain = "x"
   tvl = json.loads(s3_get(S3_TVL_FILE))
   if chain:
       if chain in tvl:
            print({"tvl_usd": tvl[chain]["tvl_usd"], "tvl_eth": tvl[chain]["tvl_eth"]})
       else:
            print({"tvl_usd": 0, "tvl_eth": 0})
   else:
        tvl_usd = 0
        tvl_eth = 0
        for k in tvl.keys():
            tvl_usd += tvl[k]["tvl_usd"]
            tvl_eth += tvl[k]["tvl_eth"]
        print( {"tvl_usd": tvl_usd, "tvl_eth": tvl_eth}) 
```

**Comment by waynebruce0x** [comment]
Cool thanks for the explanation - can the solace staking tvl be exported as a separate 'staking' export?

**Comment by ssozuer** [comment]
Hey @waynebruce0x , If it is possible, can we keep it as it is right now? I'll add more stuff later on. And it would be great if you can share a project with staking tvl for the future reference. I couldn't find from docs. Thank you for your patience and help.

**Comment by waynebruce0x** [comment]
The staking needs to be seperated to keep things fair across all listed protocols. If you search through the repo for 'staking' you can find quite a few examples, eg Trader Joe: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/traderjoe/index.js

**Comment by ssozuer** [comment]
Hey @waynebruce0x. I refactored the code from fetch adapter to sdk adapter.  In this final version, everything is in the index.js file. In addition to that, I added our Solace LP pools. It worked well on ethereum but did not worked  on polygon and aurora. I think, at least we're ready for the deployment.. I can create another PR for adding polygon and aurora pools later.

The following is error message from aurora pool2s:

`Failed to get data for LP token at 0x85efec4ee18a06ce1685abf93e434751c3cb9ba9 on chain aurora
/Users/ssozuer/solace-fi/DefiLlama-Adapters/projects/helper/unwrapLPs.js:442
            const token0 = (await tokens0).output.find(call=>call.input.target === lpToken).output.toLowerCase()
                                                                                                  ^

TypeError: Cannot read properties of null (reading 'toLowerCase')
    at /Users/ssozuer/solace-fi/DefiLlama-Adapters/projects/helper/unwrapLPs.js:442:99
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async unwrapUniswapLPs (/Users/ssozuer/solace-fi/DefiLlama-Adapters/projects/helper/unwrapLPs.js:439:7)
    at async sumTokensAndLPsSharedOwners (/Users/ssozuer/solace-fi/DefiLlama-Adapters/projects/helper/unwrapLPs.js:689:9)
    at async /Users/ssozuer/solace-fi/DefiLlama-Adapters/projects/helper/pool2.js:28:9
    at async getTvl (/Users/ssozuer/solace-fi/DefiLlama-Adapters/test.js:54:25)
    at async /Users/ssozuer/solace-fi/DefiLlama-Adapters/test.js:139:9
    at async Promise.all (index 1)
    at async Promise.all (index 3)`

**Comment by llamatester** [comment]
The adapter at projects/solace-finance/index.js exports TVL: 
        
 
 
    polygon                   14.63 k
    aurora                    442.59 k
    ethereum                  3.95 M
    ethereum-pool2            1.75 M
    pool2                     1.75 M
    
    total                    4.41 M

**Pull request merged**
