### PR TITLE
Add drachma exchange protocol TVL

### PR DESCRIPTION
**Pull request by drachma11**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

##### Twitter Link:
https://twitter.com/DrachmaExchange

##### List of audit links if any:
https://github.com/solidproof/projects/blob/main/Drachma%20Exchange/SmartContract_Audit_Solidproof_DrachmaExchange.pdf

##### Website Link:
https://drachma.exchange/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://www.arweave.net/_f_NP1upoIsBn3S_HZZboiuYP_wV112Mv_DqdyqhWgQ?ext=png

##### Current TVL:
$1110k

##### Chain:
Solana

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
n/a

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
n/a

##### Short Description (to be shown on DefiLlama):
The most powerful integrated exchange protocol

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### methodology (what is being counted as tvl, how is tvl being calculated):
drachma exchange TVL is computed by looking at the balances of the accounts holding the tokens backing the drachma vault user. The data comes from https://drachma.exchange/pool.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/drachma-exchange exports TVL: 
        
 
 
    solana                    1.30 M
    
    total                    1.30 M

**Comment by llamatester** [comment]
The adapter at projects/drachma-exchange exports TVL: 
        
 
 
    solana                    1.30 M
    
    total                    1.30 M

**Comment by g1nt0ki** [comment]
@drachma11 is there some way to fetch the token list on chain? so we dont have to update the adapter everytime. I tried fetching the pool info from 'DrBYESnnfEqqnfJu7Mv5NHsY3VrooNSxuDxkb9WSmvZS', but for some reason, I kept getting empty array

**Comment by drachma11** [comment]
> @drachma11 is there some way to fetch the token list on chain? so we dont have to update the adapter everytime. I tried fetching the pool info from 'DrBYESnnfEqqnfJu7Mv5NHsY3VrooNSxuDxkb9WSmvZS', but for some reason, I kept getting empty array

if you want to fetch the token list,you can use 'J1bMZJc4aj6RZVTf5vjDBwrwgoRAnvttkhU4TviuqrtL' address , However, we will not add new assets.

**Pull request merged**
