### PR TITLE
add mojitoswap

### PR DESCRIPTION
**Pull request by bbelly**
##### Twitter Link:
https://twitter.com/MojitoSwap

##### List of audit links if any:
https://github.com/MojitoFinance/mojito-swap-farm/blob/main/doc/PeckShield-Audit-Report-Mojito-v1.0.pdf

##### Website Link:
https://www.mojitoswap.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://photos.app.goo.gl/njiXpxJqGes5EWPN8

##### Current TVL:
$40,274,273

##### Chain:
KCC

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
https://coinmarketcap.com/exchanges/mojitoswap/ (It’s empty, need to be developed，pls use coinmarketcap’s date)

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
https://coinmarketcap.com/exchanges/mojitoswap/

##### Short Description (to be shown on DefiLlama):
Mojito Finance is a decentralized exchange running on KCC, with lots of features that let you earn and win tokens. It is fast, cheap and easily accessible as it is not difficult to use. It has currently opened Trade ,Bar (Farm) and Wine Pools. Other functions are on the way. And it will continue to launch interesting functions such as Cocktail Tickets and NFT in the future.

##### Token address and ticker if any:
0x2ca48b4eea5a731c2b54e7c3944dbdb87c0cfb6f

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Dexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
No,we don’t have oracle

##### forkedFrom (Does your project originate from another project):
No, MojitoSwap is a brand new project.

##### methodology (what is being counted as tvl, how is tvl being calculated):
We count liquidity on the dexes, pulling data from subgraphs

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Can this be done with on-chain calls? We get issues with subgraph when it falls behind current block height

**Comment by bbelly** [comment]
> Can this be done with on-chain calls? We get issues with subgraph when it falls behind current block height

hi,firstly thanks your review.Can i insist use this way  to count the TVL? Because i saw other projects which on kcc also use this way. We use the same node,so we got the same issue. the data on node are fews of block behind the blockchain. If u not give the parameter of  blockheight, it will give latest block to default. If it can be done with subgraph,rellay appreciate it. Otherwise it can't be,then i will try other ways.

**Comment by waynebruce0x** [comment]
getChainTvl() specifies a blockheight, so we can collect historical data. You could copy the getChainTvl() code and edit it to not provide a block height. In this case we won't be able to backfill data and any we wont be able to repair your TVL chart in the case of any adapter issues. We also won't be able to show a breakdown of your TVL by token. I don't know how complex it'd be to write an on-chain adapter for your project, so it's up to you which you think would be better. But with the current adapter I think there will be frequent issues.

**Comment by bbelly** [comment]
> getChainTvl() specifies a blockheight, so we can collect historical data. You could copy the getChainTvl() code and edit it to not provide a block height. In this case we won't be able to backfill data and any we wont be able to repair your TVL chart in the case of any adapter issues. We also won't be able to show a breakdown of your TVL by token. I don't know how complex it'd be to write an on-chain adapter for your project, so it's up to you which you think would be better. But with the current adapter I think there will be frequent issues.

Happy New Year,Sir. Becuase we are extremelly trust the TLV which count by subgraph. So we write a hack for latest block height issue.when block height from helper can't get correct data, we will choose the newest block height from block client synced.Please check that. Thank u again.

**Pull request merged**
