### PR TITLE
fix(bonsai): move umami treasury to bonsai, remove vendor v1

### PR DESCRIPTION
**Pull request by Clonescody**
- Move the Umami treasury to Bonsai now that the [ecosystem page](https://defillama.com/protocol/bonsaidao-ecosystem#information) is live, not sure if the naming is correct or how the link will be made 
- Update treasury tokens list, we also have some TVL deployed in our own vaults I'm not sure how to account for that ?
- Remove Vendor v1 adapter as it only has 1$ of TVL and is deprecated in favor of Vendor v2

I also had a previous PR (#11436) merged to remove $UMAMI staking from the TVL as the token is deprecated and we're encouraging people to migrate to $Bonsai, but the `stakings` call was [added back](https://github.com/DefiLlama/DefiLlama-Adapters/pull/11436/commits/0f33ee2da2730c1f736586fbbde62d37207a041a) not sure why 🤔 I re-removed it in this PR let me know if that's an issue

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/umamifinance exports TVL: 
        
 
 
    arbitrum                  14.93 M
    avax                      2.67 k
    
    total                    14.93 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/bonsai.js exports TVL: 
        
 
 
    arbitrum-ownTokens        1.00 M
    ownTokens                 1.00 M
    arbitrum                  809.35 k
    ethereum                  3.70 k
    
    total                    813.05 k

**Comment by llamatester** [comment]
The adapter at projects/umamifinance exports TVL: 
        
 
 
    arbitrum                  14.93 M
    avax                      2.67 k
    
    total                    14.93 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/bonsai.js exports TVL: 
        
 
 
    arbitrum-ownTokens        1.00 M
    ownTokens                 1.00 M
    arbitrum                  809.26 k
    ethereum                  3.70 k
    
    total                    812.96 k

**Comment by g1nt0ki** [comment]
hi @Clonescody 
I have included your changes in my commit

* vendor v1 - we like to retain deprecated protocols, same reason why I re-added umami staking
* I have set the umami treasury to 0 now
* for including your own vault data, you can add the logic in a tvl and use mergeExports like here: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/treasury/reserve.js#L10

**Pull request closed without merging**
