### PR TITLE
add DeFIL tvl

### PR DESCRIPTION
**Pull request by defil2020**
##### Twitter Link:
[https://mobile.twitter.com/defilofficial](https://mobile.twitter.com/defilofficial)

##### List of audit links if any:
[https://www.slowmist.com/security-audit-certificate.html?id=e84a975074cb9aef9299f9dec92311fd1458d0bbb4163adfadac8e16e0da3c61](https://www.slowmist.com/security-audit-certificate.html?id=e84a975074cb9aef9299f9dec92311fd1458d0bbb4163adfadac8e16e0da3c61)

##### Website Link:
[https://defil.org/](https://defil.org/)

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
[https://defil.org/favicon.ico](https://defil.org/favicon.ico)

##### Current TVL:
$18,061,327.85

##### Chain:
Ethereum, Binance Smart Chain

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
defil

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
11740

##### Short Description (to be shown on DefiLlama):
DeFIL is a decentralized Filecoin lending and finance service platform.

##### Token address and ticker if any:
Ethereum DFL 0x09ce2b746c32528b7d864a1e3979bd97d2f095ab
Ethereum eFIL 0x2a2cb9ba73289d4d068bd57d3c26165dad5cb628
Ethereum DFL-USDT 0xd372a3221021df72eda38f77117d3a95f057e163
Ethereum FILST-USDT 0xa2f6a219a51b4682e34a13a94c160d6c79cdca35
Ethereum FILST-EFIL 0x7393aa9de6585ae2ec5e18abffe1ed07123d0e87
Ethereum FILST 0x7346ad4c8cd1886ff6d16072bcea5dfc0bc24ca2

BSC DFL 0x6ded0f2c886568fb4bb6f04f179093d3d167c9d7
BSC eFIL 0x22b475f3e93390b7e523873ad7073337f4e56c2c
BSC DFL-USDT 0x3558c47c0f2309197857689d84cb620405e2c54d
BSC FILST-USDT 0xecf6aa34b19e31311eb92768888bddd25aa72933
BSC FILST-EFIL 0x3ce2669c9aaf8e717c739b1e9100fa792ad23835
BSC FILST 0x899e2a220cbc6eb1ab154211353eded74bc1e266

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### methodology (what is being counted as tvl, how is tvl being calculated):
Counts DFL,eFIL,FILST,DFL-USDT,FILST-USDT,FILST-EFIL staked in Pool

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Can this be calculated using onchain calls instead? If you can send us your token holder contract addresses we can work on this for you

**Comment by defil2020** [comment]
> 
This is all the token holder addresses we have:
the ethereum DFL holder contract is 0xb685bfdad9da7093168ab75204bbcadf0c69c823
the ethereum eFIL holder contract is 0x036cf3821ea246e935feef1c29ed8ddffac1dbb0
the ethereum DFL-USDT holder contract is 0x6b0c7d013cc0b461490287cc20aa9f34f950a6a6
the ethereum FILST-USDT holder contract is 0x9e08bd9a1e3880902688b32d563046cab74d2f2f
the ethereum FILST-EFIL holder contract is 0x312c6ffe7743b964be6da9131e662af5bac55199
the ethereum FILST holder contract is 0x01aabbad98a7638b7f8d65e7ec42560f1afbbf0c

the BSC DFL holder contract is 0x272257bb03a2b99978a1e6badeba7ccba444d285
the BSC eFIL holder contract is 0x22b475f3e93390b7e523873ad7073337f4e56c2c
the BSC DFL-USDT holder contract is 0x6b6811a710f07b8ac430f6e172833e87c4bd8716
the BSC FILST-USDT holder contract is 0xde6239b3138910c68f318e799b3d332925e9929f
the BSC FILST-EFIL holder contract is 0x6b9ee349810e660dda9e3557c7a7412e5424ea39
the BSC FILST holder contract is 0x6c753ca90bad578504314699580c8b01e067a765

the way to get all token DFL in pool is DFL.balanceOf(holder contract address)
the way to get all token eFIL in pool is eFIL.balanceOf(holder contract address) + contract.totalBorrows()
the way to get all token DFL-USDT in pool is DFL-USDT.balanceOf(holder contract address)
the way to get all token FILST-USDT in pool is FILST-USDT.balanceOf(holder contract address)
the way to get all token FILST-EFIL in pool is FILST-EFIL.balanceOf(holder contract address)
the way to get all token FILST in pool is FILST.balanceOf(holder contract address)

in the end, for lp, we need to calculate how much token0 and token1 lp equals
add these up is TVL

**Comment by waynebruce0x** [comment]
whats the eFIL address on bsc?

**Comment by waynebruce0x** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters/pull/1964
recording:
bsc-staking 2.13 k
ethereum-staking 4.84 M
ethereum 3.98 M
bsc 880.56 k
staking 4.84 M

total 4.86 M

This will go up when 0x2a2cB9bA73289D4D068BD57D3c26165DaD5Cb628 is verified as eFIL on coingecko

**Comment by defil2020** [comment]
> #1964 recording: bsc-staking 2.13 k ethereum-staking 4.84 M ethereum 3.98 M bsc 880.56 k staking 4.84 M
> 
> total 4.86 M
> 
> This will go up when 0x2a2cB9bA73289D4D068BD57D3c26165DaD5Cb628 is verified as eFIL on coingecko

Thank you for your help.
I saw the [files change](https://github.com/DefiLlama/DefiLlama-Adapters/pull/1964/files) in this merge.It seem like miss the value of eFILHolder.totalBorrows()
image

**Comment by defil2020** [comment]
> #1964 recording: bsc-staking 2.13 k ethereum-staking 4.84 M ethereum 3.98 M bsc 880.56 k staking 4.84 M
> 
> total 4.86 M
> 
> This will go up when 0x2a2cB9bA73289D4D068BD57D3c26165DaD5Cb628 is verified as eFIL on coingecko

There's one more question I'd like to ask you.
Why the total is equal 4.86M and total not equal (bsc-staking 2.13 k + ethereum-staking 4.84 M + ethereum 3.98 M + bsc 880.56 k + staking 4.84 M)=14.54M

**Comment by waynebruce0x** [comment]
Is 0x22b475f3e93390b7e523873ad7073337f4e56c2c the eFIL holder or token on bsc? I think I'm missing either the token or holder address because I cant find any totalBorrows function to call

**Pull request closed without merging**
