### PR TITLE
lulo tvl adapter with timetravel

### PR DESCRIPTION
**Pull request by 0xBraunGuy**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Lulo

##### Twitter Link:
https://x.com/uselulo

##### List of audit links if any:
https://docs.lulo.fi/audits

##### Website Link:
https://lulo.fi/

##### Logo (High resolution, will be shown with rounded borders):
image

##### Current TVL:
$30M

##### Chain:
Solana

##### Short Description (to be shown on DefiLlama):
Lulo is a decentralized lending aggregator, which automatically optimizes users deposits by migrating their deposits to the lending pool with the best yield, while allowing for personalized risk settings

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield Aggregator

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is calculated by summing the total USD value of deposited funds in Lulo across all tokens

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/lulo exports TVL: 
        
 
 
    solana                    29.96 M
    
    total                    29.96 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
@0xBraunGuy thanks for the PR

But please compute tvl using on chain data

**Comment by 0xBraunGuy** [comment]
> @0xBraunGuy thanks for the PR
> 
> But please compute tvl using on chain data


We don't store our specific deposits on-chain, It's not possible without adding the SDK's for all 5 different protocols which we integrate.

And doing so, we would still have to fetch ~10k users at 5 different protocols == ~50k on-chain fetches using the 5 different SDK's.

And we would lose historical data doing it that way.

**Comment by g1nt0ki** [comment]
do users interact with contracts deployed by lulo?  right now, the adapter is a blackbox, there is no way for us/our users to verify the data

**Comment by 0xBraunGuy** [comment]
> do users interact with contracts deployed by lulo? right now, the adapter is a blackbox, there is no way for us/our users to verify the data

The smart contracts are just boilerplate deposit and withdraw transactions.  There is no state that we maintain on-chain.  

It's the same dataset we use to support the app itself, and manage user transactions:
https://docs.lulo.fi/api-docs

**Comment by g1nt0ki** [comment]
but for a given token, interaction of all users and all platforms go through the same account controlled by Lulo? like https://solscan.io/account/91vPdPvYZ2W8VgUkQ28r2nePyE7V6qMq1ZyNRB9RrJ1k for PYUSD

but end of (lets say) a transaction where user deposits 100k PYUSD into drift, where is the state recorded? in user controlled account or 91vPdPvYZ2W8VgUkQ28r2nePyE7V6qMq1ZyNRB9RrJ1k? i.e can the user directly interact with drift and withdraw?

**Comment by 0xBraunGuy** [comment]
> but for a given token, interaction of all users and all platforms go through the same account controlled by Lulo? like https://solscan.io/account/91vPdPvYZ2W8VgUkQ28r2nePyE7V6qMq1ZyNRB9RrJ1k for PYUSD
> 
> but end of (lets say) a transaction where user deposits 100k PYUSD into drift, where is the state recorded? in user controlled account or 91vPdPvYZ2W8VgUkQ28r2nePyE7V6qMq1ZyNRB9RrJ1k? i.e can the user directly interact with drift and withdraw?


Yep that's the user controlled account (authority) in the Lulo smart contract.  But the deposited state is kept at Drift/Kamino/Marginfi,etc.  It's just the authority to deposit/withdraw that lives inside Lulo.  The user needs to directly interact with Lulo to withdraw from Drift (wallet -> authority -> Drift), but the tokens/deposited amount are not kept in Lulo.

So in order to fetch TVL on-chain, you would need to query each user / mint / protocol combo, and that requires each protocol's SDK (and thousands of RPC calls).   Which is exactly what our backend does and persists it behind the API.

**Comment by 0xBraunGuy** [comment]
> > but for a given token, interaction of all users and all platforms go through the same account controlled by Lulo? like https://solscan.io/account/91vPdPvYZ2W8VgUkQ28r2nePyE7V6qMq1ZyNRB9RrJ1k for PYUSD
> > but end of (lets say) a transaction where user deposits 100k PYUSD into drift, where is the state recorded? in user controlled account or 91vPdPvYZ2W8VgUkQ28r2nePyE7V6qMq1ZyNRB9RrJ1k? i.e can the user directly interact with drift and withdraw?
> 
> Yep that's the user controlled account (authority) in the Lulo smart contract. But the deposited state is kept at Drift/Kamino/Marginfi,etc. It's just the authority to deposit/withdraw that lives inside Lulo. The user needs to directly interact with Lulo to withdraw from Drift (wallet -> authority -> Drift), but the tokens/deposited amount are not kept in Lulo.
> 
> So in order to fetch TVL on-chain, you would need to query each user / mint / protocol combo, and that requires each protocol's SDK (and thousands of RPC calls). Which is exactly what our backend does and persists it behind the API.

Also, a few portfolio trackers have us integrate.  If you plug the wallet for the above account into Sonar.Watch, you should see the Lulo deposits.

Or similarly for the Lulo authority above:
https://sonar.watch/portfolio/91vPdPvYZ2W8VgUkQ28r2nePyE7V6qMq1ZyNRB9RrJ1k

**Pull request merged**
