### PR TITLE
Topaz adds Topaz NFT Platform adapter including methodology for calcu…

### PR DESCRIPTION
**Pull request by topazso**
…lating the total value locked.

**NOTE**

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Topaz

##### Twitter Link:
https://twitter.com/TopazMarket

##### Website Link:
https://www.topaz.so/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://www.topaz.so/images/topaz-logo.svg

##### Current TVL:
10,278,884 APT

##### Chain:
Aptos

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
n/a 

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
n/a

##### Short Description (to be shown on DefiLlama):
Discover art, culture, & digital expression. The premiere NFT marketplace, built on Aptos.

##### Token address and ticker if any:
n/a

##### Category (full list at https://defillama.com/categories) *Please choose only one:
NFT Marketplace

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
n/a

##### forkedFrom (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated):
The total value locked is calculated by adding up the value locked for each collection listed on the Topaz NFT marketplace. The collection's value locked is calculated by the total # of NFTs in escrow on the platform multiplied by the NFT collection's current floor price.

This is identical to the methodology used by the Blue Move Aptos NFT adapter which is currently live: https://defillama.com/protocol/bluemove

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/topaz exports TVL: 
        
 
 
    aptos                     39.37 M
    
    total                    39.37 M

**Comment by g1nt0ki** [comment]
@topazso I am not merging this yet as I want to rethink how to value NFTs for tvl, probably need to fix blue move as well.

Till now, I have mostly been rejecting NFT marketplaces as I struggle to come up with a good way to value NFTs, if you check opensea/lookrare tvl is set to 0, there are some nft lending platforms where I fetch price of whitelisted nfts from chainlink oracles. 


IMO, floor price is flawed because a NFT project might be dead and forgotten/has no activity for months but still have a floor price, in some ways, same issue as illiquid coins, in their case, I try to find a uni v2 pool with some known token, price the token using that and accept max 5x that value for a protocol

Can we do something similar for NFT pricing? something like either highest live bid or last sell price (say not more than 3 days old) else price it as 0, what do you say?

**Comment by g1nt0ki** [comment]
@business-bluemove

**Comment by topazso** [comment]
@g1nt0ki  Thanks for the quick & detailed response! I'll think about it some more this week.

**Comment by g1nt0ki** [comment]
@topazso I understand that it is not an easy to solve, but if we come up with a good methodology, we can apply to all NFT marketplaces and would be fair comparison

**Comment by g1nt0ki** [comment]
@topazso maybe we can start tracking fees/revenue/volume while we wait for a better methodology for tvl? 

do you have some apis that already track these?

**Comment by business-bluemove** [comment]
Hi @g1nt0ki 

I suggest that we can eliminate the projects which don't have any transactions in the last seven days from the TVL calculating. Then we can keep the old formula for calculating the TVL
What do you think about that?

**Comment by g1nt0ki** [comment]
sounds good to me, @topazso what do you think?

**Comment by g1nt0ki** [comment]
@effofxprime

**Comment by effofxprime** [comment]
> @effofxprime

Hello sir, good to hear from you.
Stargaze folks were talking about listing under a different category all together.  So far, there aren't API's that would track NFT sales.  Bids exist, but no API endpoint either.
We also were thinking that the way how cosmos chains staking works wasn't fully understood and might have been confused to be similar to ETH staking or something similar.

**Comment by g1nt0ki** [comment]
Closing this as there was no activity for a while

**Pull request closed without merging**
