### PR TITLE
Update Cog-Finance Factory 

### PR DESCRIPTION
**Pull request by ControlCplusControlV**
New Deployment of Cog Finance with our new version two factory as the target, so I changed the adapter address to the new factory on Scroll

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/cog-finance exports TVL: 
        
 
 
    scroll                    1.92 k
    scroll-borrowed           335.3890803920102
    borrowed                  335.3890803920102
    
    total                    1.92 k

**Comment by ControlCplusControlV** [comment]
Is it possible to export both alongside each other as a v1 and v2?

**Comment by llamatester** [comment]
The adapter at projects/cog-finance exports TVL: 
        
 
 
    scroll-borrowed           28.20 k
    scroll                    1.04 M
    borrowed                  28.20 k
    
    total                    1.04 M

**Comment by g1nt0ki** [comment]
@ControlCplusControlV thanks for the PR, I have updated it to support multiple factories

**Comment by llamatester** [comment]
The adapter at projects/savvy exports TVL: 
        
 
 
    arbitrum                  520.78 k
    
    total                    520.78 k

**Pull request merged**
