### PR TITLE
Add Cygnus Finance TVL

### PR DESCRIPTION
**Pull request by greatpie**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Cygnus Finance

##### Twitter Link:
https://twitter.com/CygnusFi

##### List of audit links if any:
https://github.com/peckshield/publications/blob/master/audit_reports/PeckShield-Audit-Report-Cygnus-v1.0.pdf

##### Website Link:
https://cygnus.finance/

##### Logo (High resolution, will be shown with rounded borders):
https://www.cygnus.finance/logo.png

##### Current TVL:
3.62 M

##### Chain:
BASE

##### Short Description (to be shown on DefiLlama):
Cygnus Finance is a RWA stablecoin protocol built on pure, short-term U.S. debt assets. It is also the first native interest-bearing stablecoin protocol and the first native RWA protocol on Base. 

##### Token address and ticker if any:
0xCa72827a3D211CfD8F6b00Ac98824872b72CAb49
https://basescan.org/token/0x833589fcd6edb6e08f4c7c32d4f71b54bda02913

##### Category (full list at https://defillama.com/categories) *Please choose only one:
RWA

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Chainlink
##### Implementation Details: Briefly describe how the oracle is integrated into your project:
Chainlink feed gives the on-chain proof that cgUSD tokens are backed 1:1 by U.S. Treasury securities, USDC, and US dollars.
##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
https://twitter.com/chainlink/status/1707711868570140778
##### methodology (what is being counted as tvl, how is tvl being calculated):
Calculates the total cgUSD Supply. The total supply of cgUSD is synchronized with the net value of its asset portfolio, which includes off-chain U.S. Treasuries, on-chain stablecoins, and asset interest. This ensures that Cygnus Finance will always support the redemption of USDC with cgUSD at a 1:1 ratio. 

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/arks-labs

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/cygnus-finance exports TVL: 
        
 
 
    base                      3.63 M
    
    total                    3.63 M

**Comment by g1nt0ki** [comment]
thanks for the PR, refactored and merged here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/9137

**Comment by realdealshaman** [comment]
Hi @greatpie nice to meet you. In reference to the token info, we only add the governance token to the listings, adding other tokens would mess up some of our metrics so we have to follow the same logic for all listings. Do you guys have a governance token? I would be happy to help with adding that in

**Comment by greatpie** [comment]
@realdealshaman GM!  cgUSD is a stablecoin and we haven't issued a governance token yet. So what I need is to add a stablecoin before it can be listed?

**Pull request closed without merging**
