### PR TITLE
add Opulous OVault TVL

### PR DESCRIPTION
**Pull request by hmMachghoul**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Token address and ticker if any:
- https://arbiscan.io/token/0x6a214298e6F8605F6aB52913E4fC4A02Ce66D33A#tokenInfo 
- $OVAULT

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/opulous exports TVL: 
        
 
 
    algorand                  0
    algorand-staking          6.85 M
    arbitrum                  199.69 k
    staking                   6.85 M
    
    total                    199.69 k

**Comment by g1nt0ki** [comment]
hi @hmMachghoul 
Thanks for the PR, but this looks closer to uncollateraized lending rather than RWA. Right now, what we consider RWA is tokenized assets like  houses or stocks & bonds. We you do investment off chain, it is hard for us to verify, this is the reason we have not shown tvl of some protocols that pools funds and acts as Market maker in cexes. 

We can count the USDC left in the contract as tvl, and the ones moved out/converted to fiat under borrowed?

**Comment by frcrz** [comment]
OVAULT has a mix of Music Catalogs, that work just like house, stocks or bonds and we also have music deals in the pool. All the money in OVAULT is being utilized to fund both kinds of deals.

OVAULT currently has 200K in its pool that's being used to fund music deals.

**Comment by g1nt0ki** [comment]
sorry, music deals/catalogues are not the same as tokenized stocks, the are not liquid/non-fungible. Also, it is not like your users get to choose what they want catalogue they want to buy unlike tokenization of stocks

**Comment by llamatester** [comment]
The adapter at projects/opulous exports TVL: 
        
 
 
    algorand                  0
    arbitrum                  0
    arbitrum-borrowed         199.53 k
    algorand-staking          7.62 M
    borrowed                  199.53 k
    staking                   7.62 M
    
    total                    0

**Comment by g1nt0ki** [comment]
@frcrz sorry for the delay, yeah, you cna update the same PR, I have moved the tvl to borrowed, dont worry about the title/description :)

**Pull request merged**
