### PR TITLE
Add Clober V2 Adapter

### PR DESCRIPTION
**Pull request by Dorvin**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Clober V2

##### Twitter Link:
https://x.com/CloberDEX

##### List of audit links if any:
https://github.com/clober-dex/v2-core/blob/master/audits/Clober_V2.pdf

##### Website Link:
https://clober.io/

##### Logo (High resolution, will be shown with rounded borders):
Symbol

##### Current TVL:
```
------ TVL ------
base                      21.98 k
era                       0

total                    21.98 k 
```

##### Chain:
- base
- zksync-era

##### Short Description (to be shown on DefiLlama):
Clober is a fully on-chain orderbook DEX protocol that offers CEX-equivalent trading experience, powered by Limit Order Book with Segment Tree for Efficient Order-matching (LOBSTER) algorithm.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL consists of assets deposited into the Clober Book Manager contract

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/clober-dex

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/clober-v2 exports TVL: 
        
 
 
    base                      21.97 k
    era                       0
    
    total                    21.97 k

**Comment by g1nt0ki** [comment]
thanks for the PR, I have added it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/10616

**Comment by Dorvin** [comment]
thank you : )

**Comment by Dorvin** [comment]
@g1nt0ki Hi, can you modify our Logo? I added a background color.
Symbol White

**Pull request closed without merging**
