### PR TITLE
Update to magik-finance : Add TVL derived from https://magik.farm/

### PR DESCRIPTION
**Pull request by kfukue**
Hello, I picked up this request from the link below :
https://github.com/DefiLlama/DefiLlama-Adapters/projects/2#card-84509930

I am not affiliated with this project but I looked into their code and found these pools (some are empty pools but I created them as placeholders since they exist in their source code).

I made the changes in the yield-server already with the PR below.
PR: https://github.com/DefiLlama/yield-server/pull/186

The only change from the above is that I removed the TVL from the staking and Pool2 pools in the fantom network to prevent double counting. 

I also did not make any changes to the logic of calculating the pool2 and staking TVLs. 

Please review this when you have the chance. Thanks!

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/magik-finance exports TVL: 
        
 
 
    avax                      1.61 M
    cronos                    33.78 k
    aurora                    31.078603
    fantom-staking            170.29 k
    fantom-pool2              285.30 k
    bsc                       1.94 M
    fantom                    32.95 k
    staking                   170.29 k
    pool2                     285.30 k
    
    total                    3.62 M

**Comment by realdealshaman** [comment]
Hey, @kfukue this is awesome, thanks. I think what would be best here is to keep Magik finance the tomb fork separate from this product, Magik farm so that it can be given the correct category and later added as a child of the parent protocol Magik Finance. Something tricky but also needed would be to separate their native token to have it exported as staking tvl

**Comment by kfukue** [comment]
@realdealshaman Thanks for your feedback. That sounds good.  I'll revert the changes for the index.js in the magik-finance folder and move my changes to another new folder 'magik-farm'.  I'll also include the tvl for the single sided native token pool to the staking field and the LP's tvl of those native tokens to the pool2 fields. 
Would I need to add some logic in this repo to link the two projects together (magik-finance and maigk-farm) or are they done on the frontend?

**Comment by kfukue** [comment]
@realdealshaman I moved the magik-farm changes to a new folder 'magik-farm' and included the pool2 and staking TVL from magik.farm.

I filled out the form as much as I can below.
Let me know if you need anything else.
Thanks!

Twitter Link: @MagikDotFinance
List of audit links if any:
Website Link: https://magik.farm/
Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): https://1487356348-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F0btreC6gTgiN91gVbEpk%2Fuploads%2FFMLhRTRu2dwdm8kGr37a%2Fmagik%20logo.png?alt=media&token=b0c57cda-0712-44f1-bc08-bae70d38ce35
Current TVL:~3.77M
Chain: ["fantom","avax","bsc","aurora", "cronos"]
Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list) : magik
Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000) : magik-finance
Short Description (to be shown on DefiLlama): Magik Farm is a decentralized, multi-chain all in one yield optimizer catered to the specific needs of elastic supply defi protocols and their investors. It provides its users an array of automated yield and profit taking strategies, while maximizing compound interest and deflating those tokens’ underlying supply.
Token address and ticker if any:  magik : 0x87a5c9b60a3aaf1064006fe64285018e50e0d020, mshare : 0xc8ca9026ad0882133ef126824f6852567c571a4e
Category (full list at https://defillama.com/categories) *Please choose only one: : Yield Aggregator
Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
forkedFrom (Does your project originate from another project): Beefy
methodology (what is being counted as tvl, how is tvl being calculated):  Grouped by each chain, TVL is USD amount of all of the pools excluding the TVL of the Pool2s and single asset staking of magik and mshare tokens.
Current pool2LP addresses : 
[
  "0xDc71A6160322ad78DaB0abb47C7A581cFE9709Ee", //magik-ftm spirit LP
  "0x392C85cECcf9855986b0044a365A5532aeC6Fa31", //mshare-ftm spirit LP
  "0x4d6b28441c8B293A603243431E6E31F3C2632ddD", //mshare-ftm spirit LP
];

**Comment by llamatester** [comment]
The adapter at projects/magik-farm exports TVL: 
        
 
 
    avax                      1.73 M
    fantom-pool2              178.45 k
    fantom-staking            7.63 k
    bsc                       2.02 M
    fantom                    32.38 k
    aurora                    32.36528
    cronos                    34.98 k
    pool2                     178.45 k
    staking                   7.63 k
    
    total                    3.82 M

**Pull request merged**
