### PR TITLE
add adapter openocean

### PR DESCRIPTION
**Pull request by cformcn**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
OpenOcean

##### Twitter Link:
https://twitter.com/OpenOceanGlobal

##### List of audit links if any:
https://github.com/openocean-finance/Security-Audit-Report

##### Website Link:
https://openocean.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://s3.openocean.finance/image/OOE_LOGO.png

##### Current TVL:
$0

##### Chain:
KAVA

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
openocean_finance

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
openocean

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/openocean exports TVL: 
        
 
 
    ethereum-staking          98.09 k
    avax-staking              344.92192644357385
    bsc-staking               450.07 k
    avax                      19.78 k
    ethereum                  144.63 k
    bsc                       1.05 M
    staking                   548.51 k
    
    total                    1.22 M

**Comment by g1nt0ki** [comment]
@cformcn your PR is broken, the adapter results you are seeing is from https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/openocean.js which we have already listed here: https://defillama.com/protocol/openocean

Do you have a dex in kava, if so, please share the factory address of the dex and I will update the existing listing

**Comment by llamatester** [comment]
The adapter at projects/openocean.js exports TVL: 
        
 
 
    avax-staking              350.47416540905317
    bsc-staking               457.39 k
    avax                      20.10 k
    bsc                       1.07 M
    ethereum-staking          99.67 k
    polygon                   3.33 k
    ethereum                  145.62 k
    kava                      0
    staking                   557.41 k
    
    total                    1.24 M

**Comment by llamatester** [comment]
The adapter at projects/openocean exports TVL: 
        
 
 
    avax-staking              350.47416540905317
    ethereum-staking          99.67 k
    bsc-staking               457.39 k
    avax                      20.10 k
    bsc                       1.07 M
    polygon                   3.33 k
    ethereum                  145.62 k
    kava                      0
    staking                   557.41 k
    
    total                    1.24 M

**Comment by cformcn** [comment]
@llamatester The factory address of the kava chain has been added. please review again, thx.

**Pull request merged**
