### PR TITLE
blastfutures TVL

### PR DESCRIPTION
**Pull request by sbalcin**
Name (to be shown on DefiLlama): Blast Futures (BFX)

Twitter Link: https://twitter.com/BlastFutures

List of audit links if any: https://github.com/BlastFutures/Blast-Futures-Exchange/blob/main/bfx_audit_report_hats.pdf

Website Link: https://bfx.trade/

Logo (High resolution, will be shown with rounded borders): 

Current TVL: $429,116

Treasury Addresses (if the protocol has treasury)

Chain: Blast L2

Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): 

Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): 

Short Description (to be shown on DefiLlama): Blast Futures Exchange (BFX) is a fully integrated perpetual futures exchange with native yield. BFX offers the best rewards and liquidity.

Token address and ticker if any:

Category (full list at https://defillama.com/categories) *Please choose only one: Derivatives

Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):

Implementation Details: Briefly describe how the oracle is integrated into your project:

Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:

forkedFrom (Does your project originate from another project):

methodology (what is being counted as tvl, how is tvl being calculated): Deposits to the exchange contract

Github org/user (Optional, if your code is open source, we can track activity): https://github.com/BlastFutures/Blast-Futures-Exchange

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/blastfutures: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:217:11

**Comment by llamatester** [comment]
Error while running adapter at projects/blastfutures: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:217:11

**Comment by llamatester** [comment]
Error while running adapter at projects/blastfutures: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:217:11

**Comment by llamatester** [comment]
Error while running adapter at projects/blastfutures: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:217:11

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
hi @sbalcin 
thanks for the PR, but please move the volume adapter PR here: https://github.com/DefiLlama/dimension-adapters

and can you update this PR to compute tvl on chain instead?

**Comment by llamatester** [comment]
The adapter at projects/blastfutures exports TVL: 
        
 
 
    blast                     855.90 k
    
    total                    855.90 k

**Comment by g1nt0ki** [comment]
@sbalcin thanks for the PR

**Pull request merged**
