### PR TITLE
Commodo

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/commodo exports TVL: 
        
 
 
    comdex-borrowed           36.48 k
    comdex                    111.88 k
    borrowed                  36.48 k
    
    total                    111.88 k

**Comment by cgsingh33** [comment]
> The adapter at projects/commodo exports TVL:
> 
> ```
> comdex-borrowed           36.48 k
> comdex                    111.88 k
> borrowed                  36.48 k
> 
> total                    111.88 k 
> ```

here the tvl should be total lent amount, and not lent-borrowed.
image

**Comment by g1nt0ki** [comment]
@cgsingh33 to be clear: lent = total deposited, right? 

for lending protocols we count only available amount as some protocols have done cyclic lending to inflate their tvl

**Comment by cgsingh33** [comment]
> @cgsingh33 to be clear: lent = total deposited, right?
> 
> for lending protocols we count only available amount as some protocols have done cyclic lending to inflate their tvl

ok got it

**Pull request merged**
