### PR TITLE
Update logo

### PR DESCRIPTION
**Pull request by erozanov**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

---
##### Name (to be shown on DefiLlama):
Accumulated finance 

##### Logo (High resolution, will be shown with rounded borders):
https://resources.accumulated.finance/platforms/acfi.png

### CODE REVIEW

**Comment by erozanov** [comment]
Hi guys , please update the logo from Accumulated finance . It can be found here 
https://resources.accumulated.finance/platforms/acfi.png. 
Thanks in advance

**Comment by erozanov** [comment]
Also please change Protocol Information from 
Accumulated Finance is a multi-chain liquid staking protocol, integrated with Curve FinanceAccumulated Finance is omnichain modular liquid Staking & restaking protocol

**Comment by Define101** [comment]
Should be good within 2 hours

**Comment by erozanov** [comment]
@Define101 perfect! thank you !. Should I close pr? or you will do it?

**Pull request closed without merging**
