### PR TITLE
new adapter request for agora-plus

### PR DESCRIPTION
**Pull request by agoraaroga**
##### Twitter Link:
https://twitter.com/AgoraDefi

##### List of audit links if any:
https://github.com/Tech-Audit/Smart-Contract-Audits/blob/main/TECHAUDIT_AGORADEFI.pdf

##### Website Link:
https://agoradefi.io/
https://plus.agoradefi.io/#/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
Agora Plus logo

##### Current TVL:
$8,861,892

##### Short Description (to be shown on DefiLlama):
Borrow against your autocompounded LPs. Supply to LP. Autocompound. Stake to Borrow.

##### Token address and ticker if any:
0x0Ed0Ca6872073E02cd3aE005BaF04bA43BE947fA
SYMBOL: AGORA

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
TWAP

##### forkedFrom (Does your project originate from another project):
Compound

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL counts the tokens locked in the contracts to be used as collateral to borrow or to earn yield. Borrowed coins are counted as "Borrowed" TVL and can be toggled towards the regular TVL.

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Should this be combined with the agora adapter?

**Comment by agoraaroga** [comment]
> 

Yes Please, Also please make sure all assets(puff LP tokens) should be included. Because i am getting some diff tvl, It is not included puff LP tokens(on agora plus comptroller: 0x92DcecEaF4c0fDA373899FEea00032E8E8Da58Da).

thanks for you help and support.

**Comment by waynebruce0x** [comment]
I get a total of 57M TVL and 57M borrows with this https://github.com/DefiLlama/DefiLlama-Adapters/pull/1536

**Comment by agoraaroga** [comment]
i think this is not correct it should be approx 62M borrow and approx 63M tvl (total approx 125 M).
are you including NETT market from agora(unitroller: '0x3fe29D7412aCDade27e21f55a65a7ddcCE23d9B3') and all puff LP tokens from agora + (unitroller: 0x92DcecEaF4c0fDA373899FEea00032E8E8Da58Da). 

thanks

**Comment by waynebruce0x** [comment]
You were right, the puff LP tokens were a nightmare to unwrap. I reworked it to now report 63M TVL and 61M borrowed. I think this is the best I can do

**Comment by agoraaroga** [comment]
> You were right, the puff LP tokens were a nightmare to unwrap. I reworked it to now report 63M TVL and 61M borrowed. I think this is the best I can do

yes this is correct figure, Please publish.
thanks

**Pull request merged**
