### PR TITLE
New: project Cables Finance Dex

### PR DESCRIPTION
**Pull request by PawelK-DevBrother**
##### Name (to be shown on DefiLlama):
Cables Finance DEX

##### Twitter Link:
https://twitter.com/CablesFinance

##### List of audit links if any:
https://skynet.certik.com/projects/cablesfinancedex

##### Website Link:
https://www.cables.finance/

##### Logo (High resolution, will be shown with rounded borders):
Cables_Icon

##### Current TVL:
$900,000

##### Treasury Addresses (if the protocol has treasury)
n/a

##### Chain:
43114 

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
n/a

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
n/a

##### Short Description (to be shown on DefiLlama):
The Cables Finance hybrid DEX provides non-custodial access to centralized liquidity on the Avalanche blockchain. Cables is moving the worlds largest market (FX) on-chain with our network of stablecoins and other cryptocurrencies.

##### Token address and ticker if any:
n/a

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
n/a

##### forkedFrom (Does your project originate from another project):
n/a

##### methodology (what is being counted as tvl, how is tvl being calculated):
Cables Finance is a hybrid DEX, which is utilizing team-provided liquidity to settle trades. This token liquidity sits in the wallet "0x5aFF01E3A80790c75F15fc6AEBd615c8343d4126" and is used to settle market orders on the platform. Cables also allows users to create limit orders, which becomes part of the larger orderbook. These limit order funds are stored in the escrow contract starting with "0x294ba5f8F1e54f586a9b0a419B189d7b9b9AE33E" and are the second portion of the platform's TVL.

##### Github org/user (Optional, if your code is open source, we can track activity):
n/a

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/cables-finance-dex exports TVL: 
        
 
 
    avax                      899.99 k
    
    total                    899.99 k

**Comment by PawelK-DevBrother** [comment]
Hi @llamatester, thank you for highlighting it
should I edit PR description?

**Comment by g1nt0ki** [comment]
hi @PawelK-DevBrother thanks for the PR, this is bit unusual one. We consider the tokens users lock up as tvl, but that is not the case here, also majority of the tokens are stored in EOA, that too is an issue. 

Checking with the team as to how to proceed

**Comment by PawelK-DevBrother** [comment]
Hey there, @g1nt0ki! Thank you very much for your response!
Just wanted to check in and see if there are any updates you can share?

**Comment by g1nt0ki** [comment]
> Hey there, @g1nt0ki! Thank you very much for your response! Just wanted to check in and see if there are any updates you can share?

sorry, we cant track it as tvl, but we can list you and measure other metrics like active users/volume/fees etc, does that sound good?

**Comment by PawelK-DevBrother** [comment]
Hi, thank you for the reply.  Can you explain the reasoning a bit more as to why it is not considered TVL in this case?  In the smart contracts for the platform, the settlement wallet is limited to that one EOA and in our eyes is essentially equivalent to a smart contract liquidity pool with protocol-owned liquidity deposited.  As you can see from the activity in the wallet, it is only used to facilitate trading activity for the Cables trading product.

**Comment by g1nt0ki** [comment]
yes, but POL can be considered treasury but not tvl, tvl is user funds locked in the protocol

**Pull request closed without merging**
