### PR TITLE
add stake amount  on Rangers

### PR DESCRIPTION
**Pull request by shengwenzheng**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/rangers exports TVL: 
        
 
 
    rpg                       14.04 M
    
    total                    14.04 M

**Comment by llamatester** [comment]
The adapter at projects/rangers-stake exports TVL: 
        
 
 
    rpg                       2.97 M
    
    total                    2.97 M

**Comment by shengwenzheng** [comment]
The total amount of money miners have staked

**Comment by g1nt0ki** [comment]
sorry, we are not tracking chain staking tvl atm, more info on that: https://github.com/DefiLlama/DefiLlama-Adapters/discussions/435

**Comment by shengwenzheng** [comment]
hello:
{
'rpg:0x3d28ae971e855c9857a30ece42685603e2973444': '55993239775123334439930474',
'rpg:0x228df13ae940d3527e03cf25a0c5bbf498fe1a12': '3643960963859213201121187'
}
--- rpg ---
Total: 0

--- tvl ---
Total: 0

------ TVL ------
rpg 0

total 0


Why is tvl 0?



在 2024-04-15 22:11:42，"g1nt0ki" ***@***.***> 写道：

Closed #9835.

**Pull request closed without merging**
