### PR TITLE
dHEDGE and Toros updates

### PR DESCRIPTION
**Pull request by D-Ig**
Hey,

Pushing updates to dHEDGE and Toros, which include:
* dHEDGE adapter revamp (moved to SDK adapter)
* Add DHT Staking V2 data
* Add hallmarks both to dHEDGE and Toros
* Toros adapter clean-up

For dHEDGE, switching to new adapter type won't affect any previous TVL records on DefiLlama, is this correct?

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/dhedge.js: 
        
 
  
    
    
    Error: Multicall failed!
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/abi/index.js:260:35

**Comment by D-Ig** [comment]
> Error while running adapter at projects/dhedge.js:
> 
> ```
> Error: Multicall failed!
> Truncated error stack:
>     at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/abi/index.js:260:35
> ```

As for the error, I didn't get any errors locally, however, I was using my own RPC endpoints in `.env`. Could you please confirm if I need to address this issue.

**Comment by g1nt0ki** [comment]
hi @D-Ig thanks for the PR, I made a minor fix here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/6521

I too had set rpcs in my env, but probably not good enough OP rpc, so I too was getting error till I split the call into smaller chunks for OP.

**Comment by g1nt0ki** [comment]
"For dHEDGE, switching to new adapter type won't affect any previous TVL records on DefiLlama, is this correct?"

No, it wont

**Pull request closed without merging**
