### PR TITLE
Update plunderswap v2 to use same method as v3, add some more token mappings, include kUSD TVL.

### PR DESCRIPTION
**Pull request by darthgus**
Update plunderswap v2 to use same method as v3, add some more token mappings, include kUSD TVL.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/plunderswap-v3 exports TVL: 
        
 
 
    zilliqa                   268.88 k
    
    total                    268.88 k

**Comment by llamatester** [comment]
The adapter at projects/plunderswap exports TVL: 
        
 
 
    zilliqa                   65.31 k
    
    total                    65.31 k

**Comment by darthgus** [comment]
this matches pretty close to https://plunderswap.com/stats - only a slight difference due to price/tokens that arent on CG.

334.19k (v2/v3 here) vs 346.09k (counting other tokens not on CG).

**Comment by g1nt0ki** [comment]
@darthgus sorry, we cant treat kUSD as 1:1 with USDT when converting 1000$ returns only 766$
image


I have included rest of your changes.

**Pull request closed without merging**
