### PR TITLE
Add adapter for EverRise

### PR DESCRIPTION
**Pull request by beneverrise**
##### Twitter Link:
https://twitter.com/everrise

##### List of audit links if any:
https://www.certik.com/projects/everrise

##### Website Link:
https://www.everrise.com/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://data.everrise.com/icons/smartchain/0x0cd022dde27169b20895e0e2b2b8a33b25e63579.png

image

##### Current TVL:
3.41 M

##### Chain:
Ethereum, BSC, Polygon

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
everrise

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
15257

##### Short Description (to be shown on DefiLlama):
EverRise is a blockchain technology company that offers bridging and security solutions across blockchains through an ecosystem of decentralized applications.

##### Token address and ticker if any:
Same on Ethereum, BSC and Polygon: 0x0cD022ddE27169b20895e0e2B2B8A33B25e63579
RISE

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Staking

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### forkedFrom (Does your project originate from another project):
none

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL comes from the  buyback reserves and cross-chain bridge vaults

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Does everbridge only bridge RISE around? For other projects we havent counted native tokens that have been bridged as TVL - but we can list your staked TVL.

**Comment by beneverrise** [comment]
> Does everbridge only bridge RISE around?

It will bridge other tokens; will add that to the TVL as and when they onboard

> For other projects we havent counted native tokens that have been bridged as TVL - but we can list your staked TVL.

So should be listing the staked TVL as staked, rather than tvl and remove the RISE from the bridge amounts?

**Comment by beneverrise** [comment]
Updated 
```
❯ node test.js .\projects\everrise\index.js
--- polygon ---
matic-network             1.62 M
Total: 1.62 M

--- polygon-staking ---
RISE                      4.72 M
Total: 4.72 M

--- bsc ---
binancecoin               458.77 k
Total: 458.77 k

--- ethereum ---
ethereum                  1.33 M
Total: 1.33 M

--- bsc-staking ---
RISE                      23.28 M
Total: 23.28 M

--- ethereum-staking ---
RISE                      3.56 M
Total: 3.56 M

--- tvl ---
matic-network             1.62 M
ethereum                  1.33 M
binancecoin               458.77 k
Total: 3.41 M

--- staking ---
RISE                      31.56 M
Total: 31.56 M

------ TVL ------
polygon                   1.62 M
polygon-staking           4.72 M
bsc                       458.77 k
ethereum                  1.33 M
bsc-staking               23.28 M
ethereum-staking          3.56 M
staking                   31.56 M

total                    3.41 M

```

**Comment by waynebruce0x** [comment]
Thanks, can you point us to where the MATIC, ETH, BNB is held? Then should be good to go

**Comment by beneverrise** [comment]
> Thanks, can you point us to where the MATIC, ETH, BNB is held? Then should be good to go

Yes in the token contracts

https://etherscan.io/address/0x0cD022ddE27169b20895e0e2B2B8A33B25e63579
https://polygonscan.com/address/0x0cD022ddE27169b20895e0e2B2B8A33B25e63579
https://bscscan.com/address/0x0cD022ddE27169b20895e0e2B2B8A33B25e63579

image

image

image

Then a little bit in the Bridge controller contracts; which pays for the gas for the otherside of the bridge; but that's not a huge amount

https://bscscan.com/address/0x0Dd4A86077dC53D5e4eAE6332CB3C5576Da51281
https://etherscan.io/address/0x0Dd4A86077dC53D5e4eAE6332CB3C5576Da51281
https://polygonscan.com/address/0x0Dd4A86077dC53D5e4eAE6332CB3C5576Da51281

**Comment by beneverrise** [comment]
> Thanks, can you point us to where the MATIC, ETH, BNB is held? Then should be good to go

Or more specifically in the code; these to addresses which the code is querying the balances of https://github.com/DefiLlama/DefiLlama-Adapters/pull/1179/files#diff-599917b63a54588ecf884e8d42c81550a3195738a5eadbeef9416d53b8242947R6-R7

image

**Pull request merged**
