### PR TITLE
Integrating kizuna.exchange

### PR DESCRIPTION
**Pull request by agileurbanite**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Kizuna Exchange

##### Twitter Link:
https://x.com/kizunaexchange

##### Website Link:
https://kizuna.exchange/

##### Logo (High resolution, will be shown with rounded borders):
kizuna-logo

##### Current TVL:
"totalVolumeUSD": "43.66832463653084336830116130873058",
"totalVolumeETH": "0.025",

##### Chain:
https://mode.network
https://mainnet.mode.network/
chainId: 34443

##### Short Description (to be shown on DefiLlama):
Native DEX for the Mode Network with staking modules to incentivize LPs

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### forkedFrom (Does your project originate from another project):
Uniswap V2

##### methodology (what is being counted as tvl, how is tvl being calculated):
  uniswapFactory(id: "0x05CDC3ec49C623dCE7947172fECFc5d3cD8d16cD") {
    totalVolumeUSD
    totalVolumeETH
  }

##### Github org/user (Optional, if your code is open source, we can track activity):
kizuna-dex

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/kizuna exports TVL: 
        
 
 
    mode                      0
    
    total                    0

**Comment by g1nt0ki** [comment]
hi @agileurbanite thanks for the PR, it has two minor issues, no tvl, we cant list a protocol with 0 tvl, and please fill up the PR form

**Comment by agileurbanite** [comment]
> hi @agileurbanite thanks for the PR, it has two minor issues, no tvl, we cant list a protocol with 0 tvl, and please fill up the PR form

@g1nt0ki how can I rerun checks, as we should have TVL now

**Comment by llamatester** [comment]
The adapter at projects/kizuna exports TVL: 
        
 
 
    mode                      2.18 k
    
    total                    2.18 k

**Pull request merged**
