### PR TITLE
[Bucket] move sparkling.finance to Bucket ecosystem

### PR DESCRIPTION
**Pull request by Jarekkkkk**

### CODE REVIEW

**Comment by llamabutler** [comment]
The adapter at projects/bucket-farm exports TVL: 
        
 
 
    sui                       8.71 M
    
    total                    8.71 M

**Comment by Jarekkkkk** [comment]
excuse me @g1nt0ki

since Sparkling.finance and Bucket team are now work together. is that alright we move Sparkling.finance to Bucket's sublist ? just like how we deal with Bucket.farm project ?

**Comment by g1nt0ki** [comment]
hi @Jarekkkkk what exactly is the relationship between sparkling finance & bucket?

**Comment by Jarekkkkk** [comment]
> hi @Jarekkkkk what exactly is the relationship between sparkling finance & bucket?

i'm the creator of Sparkling and help them build the service in the first beginning. and now i'm one of their members

and now Sparkling's service will only exclusive for Bucket

**Comment by g1nt0ki** [comment]
hi @Jarekkkkk Sorry, I think we need to delist sparkling finance, even when you tried to list it, we had this discussion: https://github.com/DefiLlama/DefiLlama-Adapters/pull/10047#issuecomment-2089677344


We dont track DAI locked for sDAI as part of maker tvl,I think same rule should apply here.

**Comment by Jarekkkkk** [comment]
got it, thanks for your detailed information, but can we still list Sparkling finance like it currently shows ?

**Comment by g1nt0ki** [comment]
sorry no, feel like we should not have listed it in the first place.

**Pull request closed without merging**
