### PR TITLE
add oas-jumbo project

### PR DESCRIPTION
**Pull request by CobaltSato**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
OAS Jumbo

##### Twitter Link:
https://x.com/oasjumbo

##### Website Link:
https://oasjumbo.com/

##### Logo (High resolution, will be shown with rounded borders):
https://buncha.gitbook.io/~gitbook/image?url=https%3A%2F%2F3115576436-files.gitbook.io%2F%7E%2Ffiles%2Fv0%2Fb%2Fgitbook-x-prod.appspot.com%2Fo%2Fspaces%252F4cSD4CNCUurgvOSXzi6F%252Ficon%252FnWoPrVdS9evHNFTvBxTf%252Ficon22x.png%3Falt%3Dmedia%26token%3D8246414d-80d6-4fef-9ad9-168eaec2db28&width=32&dpr=3&quality=100&sign=fa8c8719&sv=1

##### Chain:

Oasys

##### Short Description (to be shown on DefiLlama):

This is a service where you can lock $OAS into Oas Jumbo! contract and participate in the lottery for free.

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Liquid Staking

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:

White Paper
https://buncha.gitbook.io/oas-jumbo-1

##### methodology (what is being counted as tvl, how is tvl being calculated):

Get the OAS staking balance through the OAS-Jumbo contract, which stakes OAS on behalf of users.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/oas-jumbo: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:200:11
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
The adapter at projects/oas-jumbo exports TVL: 
        
 
 
    oas                       773.60 k
    
    total                    773.60 k

**Comment by llamatester** [comment]
The adapter at projects/oas-jumbo exports TVL: 
        
 
 
    oas                       754.16 k
    
    total                    754.16 k

**Comment by g1nt0ki** [comment]
thnaks for the PR

**Pull request merged**
