### PR TITLE
add DoggyTomb project (DogeChain)

### PR DESCRIPTION
**Pull request by DoggyTomb**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
DoggyTomb

##### Twitter Link:
https://twitter.com/Doggy_Tomb

##### List of audit links if any:
SOON

##### Website Link:
https://app.doggytomb.dog

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://raw.githubusercontent.com/DoggyTomb/images/main/doggy.png

##### Current TVL:
0

##### Chain:
DogeChain

##### Short Description (to be shown on DefiLlama):
First algorithmic token pegged to $DOGE on DogeChain

##### Token address and ticker if any:
0x7a07120568Cf4C49989770E7F8C1F141a65e574f

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Algo-Stables

##### forkedFrom (Does your project originate from another project):
Tomb Finance

##### methodology (what is being counted as tvl, how is tvl being calculated):
Genesis Pool & Masonry

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/doggytomb exports TVL: 
        
 
 
    dogechain-staking         0
    dogechain-pool2           0
    dogechain                 0
    staking                   0
    pool2                     0
    
    total                    0

**Comment by DoggyTomb** [comment]
hi yes it show 0 because we just deployed but we will start to have TVL tomorrow

**Comment by Define101** [comment]
Hello Doggy, I did take a look at your Twitter 
Saw that you guys are launching tomorrow
Once users start depositing we will list it

**Comment by DoggyTomb** [comment]
Hi @Define101 we launch in few hours. If it's possible to list it in defillama it will help us a lot thanks :)

**Pull request closed without merging**
