### PR TITLE
Add stISLM to stride tvl

### PR DESCRIPTION
**Pull request by brianbodollo**
This PR adds `stISLM` to Stride's TVL metrics. Feel free to ask if you have any questions!

Here is the output from running the tests:

```
--- stride ---
Total: 0

--- stargaze ---
STARS                     463.15 k
Total: 463.15 k

--- haqq ---
ISLM                      4.67 M
Total: 4.67 M

--- dymension ---
DYM                       978.41 k
Total: 978.41 k

--- dydx ---
DYDX                      30.92 M
Total: 30.92 M

--- sommelier ---
SOMM                      75.43 k
Total: 75.43 k

--- terra2 ---
LUNA                      81.18 k
Total: 81.18 k

--- evmos ---
EVMOS                     937.51 k
Total: 937.51 k

--- cosmos ---
ATOM                      29.45 M
Total: 29.45 M

--- umee ---
UX                        81.53 k
Total: 81.53 k

--- comdex ---
CMDX                      28.08 k
Total: 28.08 k

--- juno ---
JUNO                      641.27 k
Total: 641.27 k

--- injective ---
INJ                       637.78 k
Total: 637.78 k

--- celestia ---
TIA                       14.64 M
Total: 14.64 M

--- osmosis ---
OSMO                      13.53 M
Total: 13.53 M

--- tvl ---
DYDX                      30.92 M
ATOM                      29.45 M
TIA                       14.64 M
OSMO                      13.53 M
ISLM                      4.67 M
DYM                       978.41 k
EVMOS                     937.51 k
JUNO                      641.27 k
INJ                       637.78 k
STARS                     463.15 k
UX                        81.53 k
LUNA                      81.17 k
SOMM                      75.42 k
CMDX                      28.08 k
Total: 97.13 M

------ TVL ------
dydx                      30.92 M
cosmos                    29.45 M
celestia                  14.64 M
osmosis                   13.53 M
haqq                      4.67 M
dymension                 978.41 k
evmos                     937.51 k
juno                      641.27 k
injective                 637.78 k
stargaze                  463.15 k
umee                      81.53 k
terra2                    81.17 k
sommelier                 75.42 k
comdex                    28.08 k
stride                    0

total                    97.13 M
```

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/stride exports TVL: 
        
 
 
    dydx                      30.92 M
    cosmos                    29.40 M
    celestia                  14.64 M
    osmosis                   13.52 M
    haqq                      4.67 M
    dymension                 978.41 k
    evmos                     938.09 k
    juno                      642.39 k
    injective                 637.23 k
    stargaze                  461.62 k
    umee                      81.44 k
    terra2                    81.11 k
    sommelier                 75.31 k
    comdex                    27.96 k
    stride                    0
    
    total                    97.08 M

**Comment by llamatester** [comment]
Error while running adapter at projects/stride: 
        
 
  
    
    
    Error: 
        Unknown chain(s): haqq
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file
        
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
The adapter at projects/stride exports TVL: 
        
 
 
    dydx                      31.62 M
    cosmos                    29.87 M
    celestia                  15.24 M
    osmosis                   13.65 M
    islm                      4.73 M
    dymension                 1.02 M
    evmos                     936.79 k
    injective                 648.37 k
    juno                      636.95 k
    stargaze                  462.69 k
    terra2                    82.52 k
    umee                      81.43 k
    sommelier                 74.07 k
    comdex                    28.08 k
    stride                    0
    
    total                    99.08 M

**Comment by brianbodollo** [comment]
hey @realdealshaman 👋 - can I ask why was `haqq` removed from the `helper/chains.json`?

**Comment by realdealshaman** [comment]
Hey, it wasn't removed, it was simply added under the correct name. To
avoid having a duplicate chain entry it should be added as "islm" which was
already there

**Comment by brianbodollo** [comment]
Thank you so much! I apologize for the confusion 🙏

**Pull request merged**
