### PR TITLE
Create wanswap.js

### PR DESCRIPTION
**Pull request by moohooooo**
#### Why are you creating this pull request?
Would like to show Wanswap Dex TVL on Difi Llama

##### Twitter Link:
https://twitter.com/wanswap

##### List of audit if any:
Nope

##### Website Link:
https://wanswap.finance/

##### Contact Email:
suwichalala@gmail.com

##### Expected TVL:
Around 3m

##### Chain:
Wanchain

##### Coingecko ID (so your TVL can appear on Coingecko):
Not yet

##### Token address and ticker if any:
http://wanstakeinsight.com/wanswap_api/cmc

### CODE REVIEW

**Comment by moohooooo** [comment]
**For Bio / details:**
WanSwap is an innovative crosschain automatic market making (AMM) decentralized exchange (DEX) based on Wanchain.

**Comment by 0xngmi** [comment]
The endpoint has been broken for a while, is there any way it could be fixed?

**Comment by moohooooo** [comment]
OK noted I gonna fix it right now

**Comment by moohooooo** [comment]
Ok I have fixed the endpoint of it. Thanks for your notification

**Pull request merged**
