### PR TITLE
Added coingecko prefiix.

### PR DESCRIPTION
**Pull request by ronald-sirius**

### CODE REVIEW

**Comment by ronald-sirius** [comment]
with my PR for test.js, it generates:

--- astar ---
astar                     2.09 M
tether                    345.06 k
dai                       234.89 k
usd-coin                  123.68 k
binance-usd               96.56 k
bitcoin                   14.81 k
bai-stablecoin            12.42 k
origin-dollar             12.34 k
binancecoin               12.08 k
ethereum                  11.65 k
jpy-coin                  7.93 k
Total: 2.96 M 

--- tvl ---
astar                     2.09 M
tether                    345.06 k
dai                       234.89 k
usd-coin                  123.68 k
binance-usd               96.56 k
bitcoin                   14.81 k
bai-stablecoin            12.42 k
origin-dollar             12.34 k
binancecoin               12.08 k
ethereum                  11.65 k
jpy-coin                  7.93 k
Total: 2.96 M 

------ TVL ------
astar                     2.96 M

total                    2.96 M

**Comment by llamatester** [comment]
Error while running adapter at projects/sirius-finance: 
        
 
  
    
    
    ReferenceError: balances is not defined
    Truncated error stack:
    
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/sirius-finance/index.js:107:22)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:59:31)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:162:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:150:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:145:44

**Comment by g1nt0ki** [comment]
@ronald-sirius yes, it was a bug in our `test.js`, we have fixed it there, so reverted your change here.

**Comment by llamatester** [comment]
The adapter at projects/sirius-finance exports TVL: 
        
 
 
    astar                     0
    
    total                    0

**Pull request merged**
