### PR TITLE
feat: add base/opbnb tvl and fulfill bsc tvl tokens

### PR DESCRIPTION
**Pull request by bryansniyve**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/apollox exports TVL: 
        
 
 
    era                       48.60 k
    manta                     569.14 k
    base                      245.20 k
    arbitrum                  2.76 M
    bsc-staking               16.21 M
    bsc-pool2                 2.93 M
    op_bnb                    252.53 k
    ethereum                  3.38 M
    bsc                       37.74 M
    staking                   16.21 M
    pool2                     2.93 M
    
    total                    44.99 M

**Comment by llamatester** [comment]
The adapter at projects/apollox exports TVL: 
        
 
 
    era                       48.91 k
    bsc-pool2                 2.93 M
    ethereum                  3.39 M
    manta                     568.91 k
    arbitrum                  2.74 M
    base                      245.03 k
    bsc-staking               15.97 M
    op_bnb                    253.32 k
    bsc                       36.99 M
    pool2                     2.93 M
    staking                   15.97 M
    
    total                    44.24 M

**Comment by llamatester** [comment]
The adapter at projects/betafinance exports TVL: 
        
 
 
    avax-borrowed             542.957594048876
    avax                      61.44 k
    ethereum-borrowed         17.87 k
    ethereum                  1.27 M
    borrowed                  18.42 k
    
    total                    1.33 M

**Comment by llamatester** [comment]
The adapter at projects/binance exports TVL: 
        
 
 
    ripple                    1.61 B
    algorand                  99.68 M
    aptos                     379.73 M
    avax                      569.78 M
    solana                    1.82 B
    bsc                       8.91 B
    arbitrum                  2.47 B
    optimism                  737.10 M
    polygon                   251.10 M
    tron                      14.16 B
    ethereum                  18.43 B
    polkadot                  683.10 M
    bitcoin                   23.30 B
    litecoin                  392.50 M
    
    total                    73.82 B

**Comment by llamatester** [comment]
The adapter at projects/curve exports TVL: 
        
 
 
    harmony                   0
    ethereum-staking          485.67 M
    base                      2.17 M
    kava                      8.71 M
    moonbeam                  114.08 k
    aurora                    17.10 k
    xdai                      9.27 M
    avax                      12.08 M
    celo                      20.56 M
    arbitrum                  40.08 M
    optimism                  9.35 M
    polygon                   24.76 M
    ethereum                  1.59 B
    fantom                    390.31 k
    staking                   485.67 M
    
    total                    1.72 B

**Comment by llamatester** [comment]
The adapter at projects/cvi exports TVL: 
        
 
 
    ethereum-pool2            664.65 k
    ethereum-staking          30.31 k
    polygon-staking           129.61 k
    arbitrum-staking          156.67 k
    polygon-pool2             18.85 k
    ethereum                  105.20 k
    arbitrum                  172.50 k
    polygon                   77.40 k
    pool2                     683.50 k
    staking                   316.59 k
    
    total                    355.11 k

**Comment by llamatester** [comment]
The adapter at projects/gambit exports TVL: 
        
 
 
    era                       22.80 k
    arbitrum                  94.09 k
    arbitrum-staking          386.91 k
    staking                   386.91 k
    
    total                    116.89 k

**Comment by llamatester** [comment]
The adapter at projects/hopr exports TVL: 
        
 
 
    xdai                      0
    xdai-staking              773.35 k
    staking                   773.35 k
    
    total                    0

**Comment by llamatester** [comment]
Error while running adapter at projects/intentx.js: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:206:11

**Comment by g1nt0ki** [comment]
@bryansniyve thanks for the PR, made a fix where we exlude own token from tvl in bsc.

**Pull request merged**
