### PR TITLE
Add Flow Community Rewards platform

### PR DESCRIPTION
**Pull request by btspoony**
##### Name (to be shown on DefiLlama):

Flow Community Rewards

##### Twitter Link:

https://x.com/flow_blockchain

##### List of audit links if any:

N/A

##### Website Link:

https://rewards.flow.com/

##### Logo (High resolution, will be shown with rounded borders):

Square Collection Image 176x176

##### Current TVL:

$339.27 k (When submitting PR)

##### Treasury Addresses (if the protocol has treasury)

0xa45ead1cf1ca9eda

##### Chain:

Flow

##### Short Description (to be shown on DefiLlama):

Flow Community Rewards is a program where users can redeem points for real-world assets, experiences, and over 100+ partner promotions at the points store. It's consumer-friendly and Web3-ready.
- Educate and reward new user activity
- Elevate engagement across any Flow app
- Grow and retain audiences
- Combine onchain and real-world rewards to engage diverse audiences

##### Token address and ticker if any:

N/A

##### Category (full list at https://defillama.com/categories) *Please choose only one:

[Farm](https://defillama.com/protocols/Farm)

##### forkedFrom (Does your project originate from another project):

N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):

Users need to lock in $FLOW during Season 0(3 months) and they can claim daily airdropped rewards ($FLOW tokens, FTs / NFTs from community projects) during Season 1 (more perks in the future).
All $FLOW tokens are locked in the FlowRewards NFT(as a certificate for rewards), so the locked $FLOW can be counted as a TVL.

##### Github org/user (Optional, if your code is open source, we can track activity):

https://github.com/onflow

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/flow-rewards exports TVL: 
        
 
 
    flow                      339.27 k
    
    total                    339.28 k

**Comment by g1nt0ki** [comment]
hi @btspoony thanks for the PR, we can count it under staking not as tvl, is that fine?

https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by btspoony** [comment]
It is not native staking, but a Farm-type Community Rewards protocol, just built by Flow Foundation.
All Locked $FLOW is locked and stored in the user's NFT, instead of the native staking protocol.
The rewards (including any FT/NFTs from third-party projects) are based on these newly generated $FLOW-binding Rewards NFT.
So I think it can be TVL~
--
For native token staking (which ensure network security), it is here: https://port.flow.com/

**Comment by g1nt0ki** [comment]
Yeah, I understand that it is not native staking, we dont track native staking for chains. But, in this case, users are still staking your tokens, sorry, we can only count this under staking

**Comment by btspoony** [comment]
Close this PR temporarily, as there will be some new plans for this product after discussing.
Thank you for the information you provided. I will submit it again later.

**Comment by h0plo** [comment]
this lockup takes FLOW on Cadence and unlocks as FLOW on FLOW EVM.  This is more so a bridge than it is a staking

**Pull request closed without merging**
