### PR TITLE
feat: udpate pumpbtc adapter logic

### PR DESCRIPTION
**Pull request by xianshui**
NOTE

Please enable "Allow edits by maintainers" while putting up the PR.

If you would like to add a volume adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
If you would like to add a liquidations adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.
Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
Please fill the form below only if the PR is for listing a new protocol else it can be ignored/replaced with reason/details about the PR
For updating listing info It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can edit it there and put up a PR
Do not edit/push package-lock.json file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap
Name (to be shown on DefiLlama):

PumpBTC

Twitter Link:

https://x.com/Pumpbtcxyz

List of audit links if any:

https://drive.google.com/file/d/1kUmOPM8J63JmzM20H1Cg38oAfPRBJwLy/view?pli=1

Website Link:

https://pumpbtc.xyz/

Logo (High resolution, will be shown with rounded borders):

https://drive.google.com/file/d/1jIj9IwhrEsnMI4BFBF8TYGxQO_uCZ3-s/view?usp=drive_link

Current TVL:

1.14 M

Treasury Addresses (if the protocol has treasury)

Chain:

ETH/BSC/Mantle

Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

pumpbtc

Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

Short Description (to be shown on DefiLlama):

PumpBTC serves as a Liquid Restaking Solution for Babylon. PumpBTC aims to help BTC holders maximize yields through Babylon's liquid staking - essentially rebuilding WBTC with native yield.

Token address and ticker if any:

ETH: 0xf469fbd2abcd6b9de8e169d128226c0fc90a012e
BSC: 0xf9C4FF105803A77eCB5DAE300871Ad76c2794fa4
Mantle: 0xC75D7767F2EdFbc6a5b18Fc1fA5d51ffB57c2B37

Category (full list at https://defillama.com/categories) *Please choose only one:

Liquid Staking

Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):

Implementation Details: Briefly describe how the oracle is integrated into your project:

Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:

forkedFrom (Does your project originate from another project):

methodology (what is being counted as tvl, how is tvl being calculated):

TVL for pumpBTC is calculated based on the total value of WBTC, FBTC staked in the contract that were utilized in the minting process of pumpBTC.

Github org/user (Optional, if your code is open source, we can track activity):

https://github.com/pumpbtc/pumpBTC-contract

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/pumpbtc exports TVL: 
        
 
 
    bitcoin                   212.35 M
    bsc                       7.21 M
    mantle                    394.75 k
    base                      33.23 k
    ethereum                  0
    
    total                    219.99 M

**Comment by llamatester** [comment]
The adapter at projects/pumpbtc exports TVL: 
        
 
 
    bitcoin                   212.20 M
    bsc                       7.21 M
    mantle                    394.75 k
    base                      33.27 k
    ethereum                  0
    
    total                    219.84 M

**Comment by llamatester** [comment]
The adapter at projects/pumpbtc exports TVL: 
        
 
 
    bitcoin                   209.97 M
    ethereum                  17.05 M
    bsc                       7.16 M
    mantle                    391.11 k
    base                      36.57 k
    
    total                    234.60 M

**Comment by g1nt0ki** [comment]
thanks for the PR

**Comment by xianshui** [comment]
hi  @g1nt0ki, thanks for  the feedback, will you help to merge the PR today?

**Comment by xianshui** [comment]
hi @g1nt0ki , is there any new feedback? could you help to merge this PR?  thanks.

**Comment by llamatester** [comment]
The adapter at projects/pumpbtc exports TVL: 
        
 
 
    bitcoin                   260.76 M
    ethereum                  20.01 M
    bsc                       7.86 M
    mantle                    450.74 k
    base                      41.40 k
    
    total                    289.11 M

**Comment by llamatester** [comment]
The adapter at projects/avalon-finance-cedefi exports TVL: 
        
 
 
    ethereum                  103.68 M
    ethereum-borrowed         41.13 M
    borrowed                  41.13 M
    
    total                    103.68 M

**Comment by llamatester** [comment]
The adapter at projects/avalon-finance-usda exports TVL: 
        
 
 
    ethereum                  79.81 M
    bsc                       30.40 M
    mantle                    3
    
    total                    110.21 M

**Comment by llamatester** [comment]
Error while running adapter at projects/binance: 
        
 
  
    
    
    Error: Failed to post https://mainnet.helius-rpc.com/?api-key=0109717a-77b4-498a-bc3c-a0b31aa1b3bf
    Truncated error stack:
    
        at Object.post (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/http.js:47:11)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:240:29
        at async runInChunks (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:362:22)
        at async Object.sumTokens2 (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:190:18)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:173:9
        at async Promise.all (index 0)
        at async Promise.all (index 11)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:216:3

**Comment by g1nt0ki** [comment]
sorry for the delay, we were working on a script to consolidate all bitcoin addresses, so put this on hold.

**Pull request merged**
