### PR TITLE
paxe project listing

### PR DESCRIPTION
**Pull request by PaxeFi**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### List of audit links if any: https://skynet.certik.com/projects/paxe 
https://www.cyberscope.io/audits/paxe

##### Logo (High resolution, will be shown with rounded borders):
https://www.paxe.io/logo512.png

##### Treasury Addresses (if the protocol has treasury)
https://www.paxe.io/logo512.png

##### Chain:
Binance smart chain

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
https://www.coingecko.com/en/coins/paxe

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed):  32465
(https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

##### Short Description (to be shown on DefiLlama):
PAXE is a cutting-edge, multi-chain Native Yield portal designed to revolutionize the way users earn yields in the decentralized finance (DeFi) space. By seamlessly integrating with various blockchain networks, PAXE offers a unified platform for depositing and staking tokens across multiple farms, maximizing yield generation and providing unparalleled investment opportunities.

##### Token address and ticker if any: PAXE
https://bscscan.com/token/0xd2a3eec06719d5ac66248003b5488e02165dd2fa

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Farm

##### methodology (what is being counted as tvl, how is tvl being calculated):
total of farming contract and restaking pool

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/paxe: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:200:11
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
The adapter at projects/paxe exports TVL: 
        
 
 
    bsc                       587.49 k
    
    total                    587.49 k

**Comment by PaxeFi** [comment]
updated tvl adapters

**Comment by llamatester** [comment]
The adapter at projects/paxe exports TVL: 
        
 
 
    bsc-staking               29.50 M
    staking                   29.50 M
    bsc                       0
    
    total                    0

**Comment by g1nt0ki** [comment]
hi @PaxeFi is the project live?

**Comment by PaxeFi** [comment]
yes. 
paxe contract address: [https://bscscan.com/token/0xd2a3eec06719d5ac66248003b5488e02165dd2fa](https://bscscan.com/token/0xd2a3eec06719d5ac66248003b5488e02165dd2fa)
here our info: https://stats.paxe.io/

**Comment by g1nt0ki** [comment]
but how are the users staking? I dont see any option in the UI

**Comment by rez404** [comment]
Here farming app: 
https://app.sakaivault.io/farming

in partnership with Sakai

**Comment by PaxeFi** [comment]
Check this : https://app.sakaivault.io/farming

**Comment by PaxeFi** [comment]
paxe treasury wallet : https://bscscan.com/address/0x513624C9569819123b2F7F4D8916f796152BB7e9
We posted the wrong above

**Pull request merged**
