### PR TITLE
add pwndao

### PR DESCRIPTION
**Pull request by Vojtch159**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Logo (High resolution, will be shown with rounded borders):
pwn

##### Short Description (to be shown on DefiLlama):
PWN is a peer-to-peer lending protocol designed for long-term mortgage-like loans of digital assets, backed by other digital assets. Borrowers can receive a fixed-duration loan of fungible tokens backed by fungible or non-fungible tokens, while lenders can earn interest by granting these loans. The protocol is trustless, immutable and operates without the need for oracles or protocol-managed liquidations.

##### Github org/user (Optional, if your code is open source, we can track activity): https://github.com/PWNFinance

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/pwn: 
        
 
  
    
    
    AxiosError: Request failed with status code 429

**Comment by Vojtch159** [comment]
Oh, shoot. Not sure why the test is failing since they run just fine for me locally.

```
vojtch:DefiLlama-Adapters/ (main) $ node test.js projects/pwn/index.js                                                                                                    [14:00:43]
--- polygon ---
Total: 0 

--- ethereum ---
MATIC                     2.37 k
DAI                       192.34657534246574
HOPR                      32.957729
USDC                      2
XCN                       1.6613934426228676
LORDS                     0.093781
TKX                       0.00006817200000000001
aUSDC                     0.000001
BNB                       2.4071000000000004e-7
Total: 2.59 k 

--- tvl ---
MATIC                     2.37 k
DAI                       192
HOPR                      33
XCN                       2
USDC                      2
Total: 2.59 k 

------ TVL ------
polygon                   0
ethereum                  2.59 k

total                    2.59 k 
```

**Comment by llamatester** [comment]
The adapter at projects/pwn exports TVL: 
        
 
 
    ethereum                  2.58 k
    polygon                   5.61 k
    
    total                    8.19 k

**Comment by g1nt0ki** [comment]
@Vojtch159 thanks for the PR, i made a minor fix

**Pull request merged**
