### PR TITLE
Request to Add LFBTC Token TVL for Arbitrum, Mantle, Bob, Ethereum, and BSC Chains

### PR DESCRIPTION
**Pull request by zhangdav**
We are requesting to add the TVL calculation of LFBTC tokens corresponding to the owners on Arbitrum, Mantle, Bob, Ethereum, and BSC networks. LFBTC tokens are created when users initiate cross-chain transfers from EVM chains to native BTC. These tokens are locked in specific owner addresses, while users receive an equivalent amount of native BTC on Bitcoin, at a 1:1 ratio for the amount locked.

To avoid double counting, we have removed the corresponding user balances from Bitcoin. For example, we removed 953 BTC from the total Bitcoin balance, and instead, we counted 953 LFBTC tokens distributed across the five owners on these five chains.

We request that the LFBTC token balances on the respective chains be included in the TVL calculations, with these balances aggregated into the original total TVL. Below are the LFBTC token addresses and their respective owners:

Ethereum LFBTC: [Contract Address](https://etherscan.io/address/0x777B2913b1BB171A83cA3cdf79CB40523Ac76fDb)
Owner: 0xAC364d14020f1da0044699691a91f06ca6131Fe3

Arbitrum LFBTC: [Contract Address](https://arbiscan.io/address/0xbbeb34F9d50e0BABe1bd03Fd4120296354510529#readProxyContract)
Owner: 0x68Dc63a2E0520daA7dE253bccBb631f8bBf5A7a8

Mantle LFBTC: [Contract Address](https://mantlescan.info/token/0x93C6afA1882ea5E5bF403cA8fcb5aF87409EeCd0/contract/code)
Owner: 0xC7DA129335F8815d62fBd3ca7183A3b2791CdB5e

BSC LFBTC: [Contract Address](https://bscscan.com/address/0x2B25f4F134a56054b2b6388C2750F1eA3877e02b#code)
Owner: 0x8A0727B87fa1027c419c3aa2caf56C799d5Bd8c5

Bob LFBTC: [Contract Address](https://explorer.gobob.xyz/address/0xd681C5574b7F4E387B608ed9AF5F5Fc88662b37c?tab=txs)
Owner: 0xC7DA129335F8815d62fBd3ca7183A3b2791CdB5e

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/pumpbtc exports TVL: 
        
 
 
    bitcoin                   243.45 M
    ethereum                  25.71 M
    bsc                       10.14 M
    mantle                    622.09 k
    base                      81.18 k
    arbitrum                  20.19 k
    bob                       4.07 k
    
    total                    280.03 M

**Comment by g1nt0ki** [comment]
hi @zhangdav when you say, you have removed it 953 BTC from bitcoin tvl, how did you do it?

**Comment by zhangdav** [comment]
Yes, I have already removed the 953 BTC from Bitcoin's TVL.

I did this by removing the following three accounts from the API at https://dashboard.pumpbtc.xyz/api/dashboard/asset/tokenowners:

bc1q4m5lecu2esyq3vq4vw5n2cgg3kdd8atk6cd9tc
bc1p00puwvly3j8zmqj0cxgd5uzeuklphmzatyqee78y7s37v825vfescs3lu8
bc1pwqcmw37h4ya3ruevgg269eaq57204ex00r8rxdydl0faylgc5hdq83acr6

Together, these accounts held a total of 953 BTC. You can verify that these addresses have been removed by checking the API.

**Comment by llamatester** [comment]
The adapter at projects/pumpbtc exports TVL: 
        
 
 
    bitcoin                   244.87 M
    ethereum                  25.78 M
    bsc                       10.12 M
    mantle                    619.90 k
    base                      81.18 k
    arbitrum                  20.21 k
    bob                       4.06 k
    
    total                    281.50 M

**Comment by zhangdav** [comment]
**Request to Add cbWBTC Owner Balances to Ethereum Mainnet TVL Calculation**

Hi @g1nt0ki 

I kindly request that the cbWBTC balances for the following owners on Ethereum mainnet be added to the TVL and total TVL calculations:

cbWBTC: [0x2260fac5e5542a773aa44fbcfedf7c193bc2c599](https://etherscan.io/address/0x2260fac5e5542a773aa44fbcfedf7c193bc2c599#code)

Owners:
0xc0c687A198D94B0315137a8EaDE116a579622f88
0x77A0545Dc1Dc6bAee8d9c1d436c6688a75Ae5777
0xAC364d14020f1da0044699691a91f06ca6131Fe3
0x3A29CD3052774224E7C2CF001254211C986967B2

Thank you very much for your assistance.

**Comment by zhangdav** [comment]
> hi @zhangdav when you say, you have removed it 953 BTC from bitcoin tvl, how did you do it?

image

From the attached image, you can see that I have removed 953 BTC from the Bitcoin TVL, which has led to a significant drop in today’s TVL. Therefore, I kindly ask that you promptly update the LFBTC TVL for the aforementioned 5 chains. 

Your assistance in this matter is greatly appreciated. Thank you very much.

**Comment by g1nt0ki** [comment]
hi @zhangdav I have updated code, now we count the pump lfbtc as FBTC and I see that cwBTC is already part of the token list in ethereum config

**Comment by zhangdav** [comment]
> hi @zhangdav I have updated code, now we count the pump lfbtc as FBTC and I see that cwBTC is already part of the token list in ethereum config

@g1nt0ki Thank you very much for adding LFBTC. Now, the TVL across all chains and the total TVL on DeFiLlama are displaying correctly. However, LFBTC and FBTC should not be combined together. Additionally, during my testing, I did not see cbBTC on the Ethereum mainnet.

Could you please add LFBTC separately to the corresponding five chains, instead of combining it with FBTC? Also, could you add cbBTC on Ethereum, as shown in the attached image?

I greatly appreciate your help and prompt response.

image

**Pull request closed without merging**
