### PR TITLE
Add adapter: Interlay Dex

### PR DESCRIPTION
**Pull request by bvotteler**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Interlay Dex

##### Twitter Link:
https://twitter.com/InterlayHQ

##### Website Link:
http://interlay.io/

##### Logo (High resolution, will be shown with rounded borders):
Same as https://defillama.com/protocol/interlay

##### Current TVL:
approx. $102k

##### Chain:
Interlay

##### Short Description (to be shown on DefiLlama):
Total value locked on Interlay's DEX

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### methodology (what is being counted as tvl, how is tvl being calculated):
Sum of tokens deposited into the various dex trading pair accounts.

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/interlay-dex: 
        
 
  
    
    
    Error: Data for protocol interlay-dex on chain interlay is undefined on heroku
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/heroku-api.js:11:19
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:63:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:159:9
        at async Promise.all (index 0)
        at async Promise.all (index 0)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:204:3

**Comment by bvotteler** [comment]
I don't know how to fix this issue that I'm also seeing when running tests locally:
```
Error: Data for protocol interlay-dex on chain interlay is undefined on heroku
```

Please let me know if I missed that in some part of the docs.

**Comment by g1nt0ki** [comment]
hi  @bvotteler had a brief look, nothing wrong with your code, I had added some hack to avoid installing polkadot packages in main repo, that is causing this issue, I will take care.

Thanks for the PR :)

**Comment by llamatester** [comment]
Error while running adapter at projects/interlay-dex: 
        
 
  
    
    
    Error: Data for protocol interlay-dex on chain interlay is undefined on heroku
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/heroku-api.js:11:19
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:63:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:159:9
        at async Promise.all (index 0)
        at async Promise.all (index 0)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:204:3

**Comment by g1nt0ki** [comment]
it should after this fix: https://github.com/DefiLlama/sushi-analytics/commit/176fde8b422a34ebc616af5ecc43a3bd6100d24a

Unsure why but `entries()`  doesnt work, so I fetched the keys and pull them one by one

**Comment by bvotteler** [comment]
> it should after this fix: [DefiLlama/sushi-analytics@176fde8](https://github.com/DefiLlama/sushi-analytics/commit/176fde8b422a34ebc616af5ecc43a3bd6100d24a)
> 
> Unsure why but `entries()` doesnt work, so I fetched the keys and pull them one by one

Thank you!

I'll set up a few more local tests to take another peek at what's going on with `entries()` not being available. It seems quite likely I missed something there.

**Pull request merged**
