### PR TITLE
Add KUMA protocol

### PR DESCRIPTION
**Pull request by lukasluecke**
##### Name (to be shown on DefiLlama):
KUMA Protocol

##### Twitter Link:
https://twitter.com/kumaprotocol

##### List of audit links if any:
https://docs.kuma.bond/kuma-protocol/ressources/security-and-audits
* https://code4rena.com/reports/2023-02-kuma
* https://hacken.io/audits/kuma-protocol/

##### Website Link:
https://kuma.bond

##### Logo (High resolution, will be shown with rounded borders):
https://docs.kuma.bond/kuma-protocol/ressources/press-kit

##### Current TVL:
TBD (FRK & EGK are not priced yet, although they are each worth ~1€)
* ~`300k USK`
* ~`100k FRK`
* ~`2M EGK`

##### Chain:
* Ethereum
* Polygon
* Linea

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
`mimo-capital-ag-us-kuma-interest-bearing-token`
https://www.coingecko.com/en/coins/kuma-protocol-us-kuma-interest-bearing-token

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
`us-kuma`
https://coinmarketcap.com/currencies/us-kuma/

##### Short Description (to be shown on DefiLlama):
The KUMA Protocol is a decentralized protocol issuing interest-bearing tokens backed by regulated NFTs, themselves backed by Real World Assets (RWA). At start the KUMA Protocol accepts regulated KUMA NFTs that are backed by sovereign bonds.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
`RWA`

##### methodology (what is being counted as tvl, how is tvl being calculated):
Currently counting supply of interest-bearing tokens directly.

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/kuma exports TVL: 
        
 
 
    linea                     100.93 k
    ethereum                  201.85 k
    polygon                   0
    
    total                    302.79 k

**Comment by lukasluecke** [comment]
Maintainers, please advise on getting the remaining tokens priced correctly.

**Comment by g1nt0ki** [comment]
hi, is there some oracle or rest api where we can pull FRK & EGK prices from? on chain oracle data is preferred, we need to add a coins adapter to fetch token prices periodically. What we have done for backed: https://github.com/DefiLlama/defillama-server/blob/ethers-v6/coins/src/adapters/rwa/backed.ts#L6

**Comment by lukasluecke** [comment]
Thanks, will come up with something similar then 🙂 Should I just open a PR over there then once ready?

**Comment by g1nt0ki** [comment]
> Thanks, will come up with something similar then 🙂 Should I just open a PR over there then once ready?

yup, exactly.

**Pull request merged**
