### PR TITLE
feax:add flux project

### PR DESCRIPTION
**Pull request by cl510804194**
##### Twitter Link:

https://twitter.com/zero1_flux

##### List of audit links if any:

 https://certik.org/projects/flux

##### Website Link:

https://flux.01.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

white rounded:
193withouTitle

black rounded:
192withouTitle

##### Current TVL:

$75,112,820.519

##### Chain:

BSC, HECO, OEC, Conflux，Arbitrum

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

flux-protocol ,  https://www.coingecko.com/en/coins/flux-protocol

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

 9837 ,  https://coinmarketcap.com/currencies/flux-protocol

##### Token address and ticker if any:

FLUX(ETH)	0x7645DdfEecedA57e41f92679c4aCd83c56A81D14
cFLUX(Conflux)	cfx:acgbjtsmfpex2mbn97dsygtkfrt952sp0psmh8pnvz
bFLUX(BSC)	0x1ab6478b47270ff05af11a012ac17b098758e193
hFLUX(Heco)	0xd10852DF03Ea8b8Af0CC0B09cAc3f7dbB15e0433
FLUXK(OEC)	0xd0C6821aba4FCC65e8f1542589e64BAe9dE11228

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:

Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

Chainlink+TWAP

##### forkedFrom (Does your project originate from another project):

no

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Would it be possible to use on-chain calls instead?

**Comment by cl510804194** [comment]
I used the on-chain call before, but it failed during the test. I want to use this method first, and I will switch to on-chain call after about 2 weeks. Can I?

**Comment by waynebruce0x** [comment]
We don't count borrowed funds as TVL. It also seems you count staked FLUX tokens in TVL? We would class that as 'staked' instead. 

For example, on okexchain, your API returns 42M. On your UI it says there is a total supply of 40.8M, a total supply of 1.50M (@$0.67) and a total borrow of 14.6M. I'm assuming 42M = 40.8M + 1.50M * 0.67. 

At DefiLlama we would use TVL = 40.8M - 14.6M = 26.2M, and staking = 1.5M * 0.67 = 1M.

Hope this helps - if you need a hand with getting your on-chain adapter to pass test we're free to help in the discord server.

**Comment by 0xngmi** [comment]
Closing since a new version has been merged on another PR

**Pull request closed without merging**
