### PR TITLE
zkswap finance dex update infomation

### PR DESCRIPTION
**Pull request by ZkSwapFinance**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
zkSwap Finance

##### Twitter Link:
https://twitter.com/zkSwap_finance

##### List of audit links if any:
https://github.com/Vital-block/Smart-Contract-Audit/blob/main/ZKSWAP%20FINANCE%20AUDIT%20REPORT.pdf

##### Website Link:

https://zkswap.finance/

##### Logo (High resolution, will be shown with rounded borders):
https://zkswap.finance/logo.png

##### Current TVL:
250.42k

##### Chain:
zkSync Era

##### Short Description (to be shown on DefiLlama):
zkSwap Finance is the top DEX and the first Swap to Earn DeFi AMM on zkSync Era ecosystem, pioneering a unique incentive model that rewards both liquidity providers & traders.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### forkedFrom (Does your project originate from another project):
SyncSwap

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is total liquidity of all liquidity pools, using Uniswap TVL calculator.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/ZkSwapFinance

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/zkSwap-finance exports TVL: 
        
 
 
    era                       250.47 k
    
    total                    250.47 k

**Comment by Define101** [comment]
Hi, any reason for the changes it the code?

**Comment by ZkSwapFinance** [comment]
@Define101 we want to change `Short Description (to be shown on DefiLlama):` so I created a new PR

**Comment by realdealshaman** [comment]
@ZkSwapFinance I've updated the description, thanks

**Comment by ZkSwapFinance** [comment]
> @ZkSwapFinance I've updated the description, thanks

Thank you so much, @realdealshaman

**Pull request closed without merging**
