### PR TITLE
Update GullNetwork adapter include liquidity

### PR DESCRIPTION
**Pull request by GullNetwork**
update to include liquidity TVL of recently launched AMM

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/gullnetwork exports TVL: 
        
 
 
    manta                     1.60 M
    bsc                       88.91 k
    ethereum                  21.70 k
    base                      0
    
    total                    1.71 M

**Comment by llamatester** [comment]
The adapter at projects/gullnetwork exports TVL: 
        
 
 
    manta                     213.23 k
    bsc                       88.98 k
    ethereum                  21.79 k
    base                      0
    
    total                    324.00 k

**Comment by llamatester** [comment]
The adapter at projects/gullnetwork-amm exports TVL: 
        
 
 
    manta                     1.38 M
    
    total                    1.38 M

**Comment by g1nt0ki** [comment]
@GullNetwork thanks for the PR, I have created a sublisting for the dex

**Pull request merged**
