### PR TITLE
add tvls for all chains

### PR DESCRIPTION
**Pull request by Kostydenis**
Update chain information of Envelop project

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/envelop exports TVL: 
        
 
 
    avax                      0
    optimism                  2.67861
    bsc                       7.43 k
    blast                     3.74 k
    polygon                   9.55 k
    arbitrum                  10.16 k
    ethereum                  587.89 k
    
    total                    618.77 k

**Comment by Kostydenis** [comment]
There is a problem with automatic test. ESLint stops pipeline due to the rule in other project `/projects/earnmos/index.js`. Should I fix it or will you correct it by yourself?

**Comment by g1nt0ki** [comment]
@Kostydenis why are you counting tokens in gnosis safe as your tvl? I have moved farming part to staking here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/9577

**Comment by Kostydenis** [comment]
@g1nt0ki That's ok. Let's count it as staking. Thank you for refactoring

**Comment by llamatester** [comment]
The adapter at projects/envelop exports TVL: 
        
 
 
    arbitrum                  0
    optimism                  0
    bsc-staking               0
    avax                      0
    bsc                       569.3650142571875
    polygon                   88.97460605325293
    polygon-staking           0
    ethereum-staking          0
    blast                     3.75 k
    ethereum                  93.739422428968
    staking                   0
    
    total                    4.50 k

**Comment by llamatester** [comment]
The adapter at projects/envelop exports TVL: 
        
 
 
    arbitrum                  0
    optimism                  0
    avax                      0
    ethereum                  93.557490017084
    ethereum-staking          0
    bsc                       573.0340034288141
    bsc-staking               0
    blast                     3.74 k
    polygon                   88.00274004043865
    polygon-staking           0
    staking                   0
    
    total                    4.50 k

**Comment by llamatester** [comment]
The adapter at projects/envelop exports TVL: 
        
 
 
    arbitrum                  0
    optimism                  0
    avax                      0
    bsc                       573.3125883418403
    polygon                   88.00383657113865
    ethereum                  93.58206419999999
    bsc-staking               0
    ethereum-staking          0
    blast                     3.74 k
    polygon-staking           0
    staking                   0
    
    total                    4.50 k

**Pull request closed without merging**
