### PR TITLE
Add DonaSwap V2 Mainnet Factories for all deployed blockchains

### PR DESCRIPTION
**Pull request by 0xfirechain**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
DONASWAP V2

##### Twitter Link:
https://twitter.com/0xdonaswap

##### Website Link:
https://donaswap.com

##### Logo (High resolution, will be shown with rounded borders):
https://www.donaswap.com/logo.png

##### Current TVL:
1.26k

##### Chain:
All EVM supported running mainnet & testnet networks

##### Short Description (to be shown on DefiLlama):
DONASWAP is the primary multichain dex for the Firechain Ecosystem which sprouted by the Donaswap Token.

##### Token address and ticker if any:
FLAME (Coming Soon)

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### methodology (what is being counted as tvl, how is tvl being calculated):
Factory address (0x8e5dff1c121F661971d02950698f8c5EFc3DfA78) is used to find the LP pairs. TVL is equal to the liquidity on the AMM.

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/donaswap-v2 exports TVL: 
        
 
 
    thundercore               0
    moonbeam                  0
    kava                      0
    polygon                   0
    fantom                    0
    flare                     0
    polygon_zkevm             0
    kcc                       0
    moonriver                 0
    fuse                      0
    core                      0
    metis                     0
    avax                      0
    palm                      0
    arbitrum                  0
    optimism                  0
    linea                     0
    ethereum                  0
    base                      0
    heco                      0
    celo                      0
    kardia                    0
    astar                     0
    dogechain                 0
    aurora                    0
    conflux                   0
    bsc                       1.26 k
    cmp                       0
    fusion                    0
    
    total                    1.26 k

**Comment by llamatester** [comment]
The adapter at projects/donaswap-v2 exports TVL: 
        
 
 
    base                      0
    polygon                   0
    kava                      0
    palm                      0
    kcc                       0
    thundercore               0
    astar                     0
    core                      0
    arbitrum                  0
    ethereum                  0
    metis                     0
    aurora                    0
    moonbeam                  0
    celo                      0
    optimism                  0
    linea                     0
    avax                      0
    flare                     0
    fantom                    0
    polygon_zkevm             0
    heco                      0
    moonriver                 0
    dogechain                 0
    fuse                      0
    bsc                       1.25 k
    conflux                   0
    kardia                    0
    cmp                       0
    fusion                    0
    
    total                    1.25 k

**Comment by g1nt0ki** [comment]
@0xfirechain can you please fill in the project details in the PR description form?

**Comment by 0xfirechain** [comment]
Yes sir, I will.... I saw it to late, my bad!

**Comment by 0xfirechain** [comment]
Name (to be shown on DefiLlama): DONASWAP
Twitter Link: https://twitter.com/0xdonaswap
List of audit links if any:
Website Link: https://donaswap.com
Logo (High resolution, will be shown with rounded borders):  https://www.donaswap.com/logo.png
Current TVL: 1.26k
Treasury Addresses (if the protocol has treasury)
Chain: All EVM supported running mainnet & testnet networks
Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
Short Description (to be shown on DefiLlama): DONASWAP is the primary multichain dex for the Firechain Ecosystem which sprouted by the Donaswap Token.
Token address and ticker if any: FLame (Coming Soon)
Category (full list at https://defillama.com/categories) *Please choose only one: Dexes
Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
forkedFrom (Does your project originate from another project):
methodology (what is being counted as tvl, how is tvl being calculated): "Factory address (0x8e5dff1c121F661971d02950698f8c5EFc3DfA78) is used to find the LP pairs. TVL is equal to the liquidity on the AMM."
Github org/user (Optional, if your code is open source, we can track activity):

**Comment by g1nt0ki** [comment]
@0xfirechain thanks for the details and the PR

**Pull request merged**
