### PR TITLE
0xscans

### PR DESCRIPTION
**Pull request by jscrui**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
0xScans

##### Twitter Link:
https://twitter.com/0xscans

##### Website Link:
https://www.0xscans.com

##### Logo (High resolution, will be shown with rounded borders):
https://0xscans.com/wp-content/uploads/2023/12/cropped-photo_2023-12-02_21-12-39-192x192.jpg

##### Current TVL:
1.7M

##### Chain:
Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): 
0xscans

##### Short Description (to be shown on DefiLlama):
Leveraging AI and automated testing, this revolutionary smart contract analysis tool provides a fast and detailed list of errors, along with the immediate generation of detailed audit reports. These reports outline vulnerabilities and offer actionable insights.

##### Token address and ticker if any:
0x10703ca5e253306e2ababd68e963198be8887c81
SCANS

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Services

##### methodology (what is being counted as tvl, how is tvl being calculated):
Our TVL is calculated by summing all the tokens in our staking pools.

##### Github org/user (Optional, if your code is open source, we can track activity):
jscrui

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/0xscans exports TVL: 
        
 
 
    ethereum                  1.74 M
    ethereum-staking          1.74 M
    staking                   1.74 M
    
    total                    1.74 M

**Comment by jscrui** [comment]
I cant identify what is causing the error on Test_Change/test

**Comment by llamatester** [comment]
The adapter at projects/0xscans exports TVL: 
        
 
 
    ethereum                  0
    ethereum-staking          1.64 M
    staking                   1.64 M
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/0xscans exports TVL: 
        
 
 
    ethereum                  0
    ethereum-staking          1.64 M
    staking                   1.64 M
    
    total                    0

**Pull request merged**
