### PR TITLE
added EveryFinance project

### PR DESCRIPTION
**Pull request by arguiot**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
EveryFinance

##### Twitter Link:
https://x.com/every_finance

##### List of audit links if any:
[Every Finance - Smart Contracts Security Audit Report.pdf](https://github.com/user-attachments/files/16285047/Every.Finance.-.Smart.Contracts.Security.Audit.Report.pdf)

##### Website Link:
https://every.finance

##### Logo (High resolution, will be shown with rounded borders):
every-finance

##### Current TVL:
$57,212

##### Chain:
Ethereum, BSC, Polygon

##### Short Description (to be shown on DefiLlama):
Every Finance proposes decentralized exchange-traded funds (dETFs) with different risks, based on different optimal portfolio allocation strategies and dynamic rebalancing.

##### Token address and ticker if any:

| | ALPHA | BETA | GAMMA | PARITY |
|----------|------------------------------------------|------------------------------------------|------------------------------------------|------------------------------------------|
| Ethereum | 0x8D769F45c94CEA310018d37BD06fc42e7DB060FF | 0x9C1A18A734dFAe6e6f89942f358e7270BecdB002 | 0xbE49a740c48F9D4347De8994c488333d492a4e19 | |
| Polygon | 0xF0aD135A657808a3E576183Eb647872d901CFF02 | 0x0f20180e0F84a8cc4A4821eC24E7d9a9b70ED1A8 | 0x64B41253C0B4fCa4885c3dc24B7562A3B02C02Cc | 0x8Bf57C59A9849bc0973308CC35F439d340AAe060 |
| BSC | 0x53ca73EE747ceD027c677feCCC13b885f31Ee4dF | 0x9C1A18A734dFAe6e6f89942f358e7270BecdB002 | 0xb2d66C5ECcde53e94019556138Cbf41700E5c49E | 0x2A3cdF2dAECa1a1106C0F086e54E5f534Fe4C7e0 |

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Indexes

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
https://docs.every.finance/
##### forkedFrom (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated):
Total Value Locked represents the sum of the money managed in each dETF (Alpha + Beta + Gamma). User invest in the 
fund and receive a token which price is calculated based of the monetary value of that fund. Therefore, the market cap of that token represents the value locked in this fund. The TVL is the sum of those market caps.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/EveryFinance

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/everyfinance exports TVL: 
        
 
 
    bsc                       27.32 k
    polygon                   15.75 k
    ethereum                  13.95 k
    
    total                    57.02 k

**Comment by arguiot** [comment]
I'm not sure how to allow edit from maintainers. I don't see the option on the right.

**Comment by g1nt0ki** [comment]
@arguiot thanks for the PR, I refactored it a bit so we get token breakdown now: https://github.com/DefiLlama/DefiLlama-Adapters/commit/eebc267e1f8dc3921a335454781c9cda7468d05a

**Comment by g1nt0ki** [comment]
@arguiot it is an index right? arent those the tokens forming the index?

**Comment by arguiot** [comment]
It is an index, but the treasury is moved and managed to other addresses. It's not correct to display this information on the TVL.

**Comment by arguiot** [comment]
Yes, in some cases the money can move out. A simple way to check this, is by looking at the Tokens graph. It shows about 13k$ of value when the TVL is far more than this.

**Comment by g1nt0ki** [comment]
"in some cases the money can move out" well, that means the money is no longer locked in your protocol and should not be counted towards tvl?


We don't like relying on oracles or token supply for tvl value as they tend to stale/return incorrect values over time, this is why we pull underlying token data. If some part of the tvl of locked in another protocol, please give me info about it and I will add it to the code.

**Comment by arguiot** [comment]
@g1nt0ki sorry, I said something a bit confusing! Ok, so to accurately view the holdings of the index, here are the address you should track:
SC ON bsc MAINNET
ALPHA
"SafeHouseAlpha"  deployed at 0x56AC037b5cD072621f940344647cc9394224e10f
BETA
"SafeHouseBeta"  deployed at 0x5503AAEb0C81f482503D223147757Fe120366fa2
GAMMA
"SafeHouseGamma"  deployed at 0x7350708656682Ad41DebcEf103f6CA31d960f641
SC ON Polygon MAINNET
ALPHA
"SafeHouseAlpha"  deployed at 0x7350708656682Ad41DebcEf103f6CA31d960f641
BETA
"SafeHouseBeta"  deployed at 0xc4075EE3ad1F5fA3205CF45A92B9B963BdC0F31a
GAMMA
"SafeHouseGamma"  deployed at 0xA70FD08eA376Bf9d9D3954aFDc11A9759862cD43
SC on  Ethereum
Alpha
deploying "SafeHouseAlpha"  deployed at 0x56AC037b5cD072621f940344647cc9394224e10f
Beta
deploying "SafeHouseBeta"  deployed at 0x5503AAEb0C81f482503D223147757Fe120366fa2
Gamma
deploying "SafeHouseGamma"  deployed at 0xD5c0f9aBAe806eBeEe7d957Fee09403390cfF0B3




What I meant is that the money in treasury could move out. Hope this clarifies a bit the situation!

**Comment by g1nt0ki** [comment]
Yup, that's what the current code does, pulls asset list and checks balance in the safe houses: https://github.com/DefiLlama/DefiLlama-Adapters/commit/eebc267e1f8dc3921a335454781c9cda7468d05a

**Pull request closed without merging**
