### PR TITLE
Add random reward

### PR DESCRIPTION
**Pull request by roinevirta**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama): 
Random Reward

##### Twitter Link: 
N/A

##### List of audit links if any: 
N/A

##### Website Link: 
https://www.randomreward.xyz/

##### Logo (High resolution, will be shown with rounded borders):
https://www.randomreward.xyz/static/media/randomreward-removebg.2d55a7d1226af41f8d4a.png

##### Current TVL:
0

##### Treasury Addresses (if the protocol has treasury):
N/A

##### Chain:
Ethereum

##### Short Description (to be shown on DefiLlama):
Simply send ETH to Random Reward for a chance to get more back!

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Services

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/roinevirta/random-rewarder

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/RandomReward exports TVL: 
        
 
 
    ethereum                  0
    
    total                    0

**Comment by g1nt0ki** [comment]
hi @roinevirta these are not assets deposited by the user right?

**Comment by roinevirta** [comment]
@g1nt0ki users may deposit assets into the contract by simply sending ETH into it.

**Comment by g1nt0ki** [comment]
and how will they withdraw the deposited ETH?

**Comment by roinevirta** [comment]
A random function gives all depositors of an epoch a chance of receiving back the ETH deposited within that epoch. One depositor gets allocated the deposited ETH at the end of the epoch. 

Source code here: https://github.com/roinevirta/random-rewarder

**Pull request merged**
