### PR TITLE
Add Francium TVL

### PR DESCRIPTION
**Pull request by Francium-DeFi**
##### Twitter Link:
https://twitter.com/Francium_Defi

##### Website Link:
https://francium.io/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
francium_logo_black_background_with_ring png
francium_logo_black_background png

##### Current TVL:
7,100,000

##### Chain:
Solana

##### Short Description (to be shown on DefiLlama):
Francium is a DeFi yield strategy Platform on Solana, providing leveraged/hedged farming, DeFi strategies & on-chain trading strategies. 
Francium also help users to build their own yield strategy through strategy dev toolbox.
Granted by Solana & Serum.

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Yield

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Pyth

##### forkedFrom (Does your project originate from another project):
not forked. build by our own.

##### methodology (what is being counted as tvl, how is tvl being calculated):
Value of total LP tokens locked + deposits that are not borrowed.

### CODE REVIEW

**Comment by waynebruce0x** [comment]
TVL seems to primarily be staking/farming of LPs - is that right? Could this be exported as staking: { tvl } ?

**Comment by Francium-DeFi** [comment]
> TVL seems to primarily be staking/farming of LPs - is that right? Could this be exported as staking: { tvl } ?

Hi,
As we provide leverage farming, just like Alpha Homora / Alpaca Finance , The current TVL is composed with staking/farming of LPs, along with the assets in our Lending Module that is not borrowed. Asset in the lending pool is also a basic part locked in our platform.
and we accumulated the above two part of data in our given api.

**Comment by 0xngmi** [comment]
Your API endpoint seems to have SSL issues. When querying from a node script we get the error `Error: unable to verify the first certificate`

**Comment by Francium-DeFi** [comment]
> Your API endpoint seems to have SSL issues. When querying from a node script we get the error `Error: unable to verify the first certificate`

Hi, it should work now. Could you please try it again.
Thanks!

**Comment by Francium-DeFi** [comment]
@0xngmi 
this is our audit link: https://www.certik.org/projects/francium
could you please update it?

**Pull request merged**
