### PR TITLE
feat: Add two new Backed Finance tokens

### PR DESCRIPTION
**Pull request by hemulin**
Added two new tokens (bERNX, bZPR1) from Backed Finance

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/backed exports TVL: 
        
 
 
    bsc                       0
    base                      0
    fantom                    0
    avax                      252.82 k
    xdai                      3.70 M
    arbitrum                  236.37332304075917
    ethereum                  44.34 M
    polygon                   60.836880000071126
    
    total                    48.29 M

**Comment by g1nt0ki** [comment]
hi @hemulin can you also put up a PR here to track their price: https://github.com/DefiLlama/defillama-server/blob/master/coins/src/adapters/rwa/backed.ts

**Comment by g1nt0ki** [comment]
are oracles ready for these?

**Comment by hemulin** [comment]
> are oracles ready for these?

Sorry for the delay in reply here @g1nt0ki 

Yes, I see you found the oracles commit.

Thank you for merging :pray:

**Pull request merged**
