### PR TITLE
Added DOV tvl

### PR DESCRIPTION
**Pull request by babayega**
Twitter Link: https://twitter.com/0xPolysynth

List of audit links if any: NA

Website Link: https://polysynth.com/

Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): NA

Current TVL: 1.20 M

Chain: Polygon

Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

Short Description (to be shown on DefiLlama): Polysynth offers structured derivatives for sustainable portfolio growth

Token address and ticker if any: NA

Category (full list at https://defillama.com/categories) *Please choose only one: Options

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using): Chainlink

forkedFrom (Does your project originate from another project): NA

methodology (what is being counted as tvl, how is tvl being calculated): Notional amount added in contracts plus amount reserved in insurance fund, Amount locked in DOV contracts

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/polysynth: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:217:11

**Comment by babayega** [comment]
Hey when I run the test locally, it is successfully running and showing the TVL

`npx node test.js projects/polysynth/index.js`

```
--- polygon ---
WETH                      489.40 k
USDC                      446.51 k
WBTC                      261.08 k
Total: 1.20 M 

--- tvl ---
WETH                      489.40 k
USDC                      446.51 k
WBTC                      261.08 k
Total: 1.20 M 

------ TVL ------
polygon                   1.20 M

total                    1.20 M 
```

The output is as above.
Please let me know if there needs to be done anything else

Also the category is now changed to Options, please change that as well.

**Comment by g1nt0ki** [comment]
hi @babayega I copied your changes, and merged it instead (to get around merge conflicts)

https://github.com/DefiLlama/DefiLlama-Adapters/pull/3030

**Comment by babayega** [comment]
Hey @g1nt0ki  
Have changed the category of our protocol and the short description as well. Can you please make sure these two are updated as well. 
Getting continuous requests from my marketing team for the same. Would be a great help if this is done ASAP.

**Comment by g1nt0ki** [comment]
done https://github.com/DefiLlama/defillama-server/commit/e8bd169aa59b9afb4fd2171bb5073b458b0b1951

**Comment by g1nt0ki** [comment]
UI should update in a few hours

**Pull request closed without merging**
