### PR TITLE
Add Sailing Protocol

### PR DESCRIPTION
**Pull request by nicszerman**
##### Name (to be shown on DefiLlama):
Sailing Protocol

##### Twitter Link:
https://twitter.com/sailingprotocol

##### Website Link:
sailingprotocol.org

##### Logo (High resolution, will be shown with rounded borders):
https://sailingprotocol.org/dist/sailing-sea-isotype.png

##### Current TVL:
$174 USD

##### Chain:
Kava

##### Short Description (to be shown on DefiLlama):
Sailing Protocol brings traditional stocks onchain.

##### Token address and ticker if any:
POST request to https://sailingprotocol.org/api/sailingprotocol/public_analytics/get_onchain_instruments
POST request can be conveniently made here [reqbin.com](https://reqbin.com)

##### Category (full list at https://defillama.com/categories) *Please choose only one:
RWA

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
Value in USD of onchain circulating stocks. Stocks can be redeemed any time when the market is open.

##### Github org/user (Optional, if your code is open source, we can track activity):
Owner git https://github.com/nicszerman
Code will be made open source soon.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/sailingprotocol exports TVL: 
        
 
 
    kava                      173.97152347856505
    
    total                    173.97152347856505

**Comment by g1nt0ki** [comment]
hi @nicszerman thanks for the PR, but the project is not yet live? I tried launching the app on your site

**Comment by nicszerman** [comment]
@g1nt0ki yes it is live! The contracts are deployed and some services have integrated them to use us, including eluter.com for example. The user interface on our website is coming in december.

**Comment by llamatester** [comment]
The adapter at projects/sailingprotocol exports TVL: 
        
 
 
    kava                      183
    
    total                    183

**Comment by nicszerman** [comment]
Thank you! @g1nt0ki

**Comment by josephsued** [comment]
@g1nt0ki Could you change the profile picture of Sailing Protocol to the picture I attached here? Thank you
Untitled design

**Pull request merged**
