### PR TITLE
Add ChainTools Adapter

### PR DESCRIPTION
**Pull request by IamNimrod**
**NOTE**
1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap
---

##### Name (to be shown on DefiLlama): 
ChainTools

##### Twitter Link: 
https://twitter.com/ChaintoolsTech

##### List of audit links if any:
None.

##### Website Link:
https://www.chaintools.wtf/#/Stats

##### Logo (High resolution, will be shown with rounded borders):
https://www.chaintools.wtf/img/icons/logonew.png

##### Current TVL:
~416 600$ 

##### Treasury Addresses (if the protocol has treasury)
Multisig: 0xb0Df68E0bf4F54D06A4a448735D2a3d7D97A2222

##### Chain:
Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
"id":"chaintools"

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
"id":27402

##### Short Description (to be shown on DefiLlama):
ChainTools is revolutionizing the DeFi landscape by offering the first-ever Uniswap V3 no-staking liquidity rewards protocol.

Designed to set a new standard in LP provision, our platform offers a seamless and user-friendly experience that incentivizes both liquidity providers and users to unlock the full potential of Uniswap V3.

ChainTools currently offers the following services to regular DeFi users with plans to add more:
1. ChainSwap - Buy tokens on Arbitrum using mainnet ETH in under 1 minute.
2. ChainLock - New type of token locker - 'isolated lockers' concept. Keeps lock balances in separate contracts. Supports rebase/reflection tokens.
3. ChainForge - Deploy highly customizable token contracts without developer experience.
4. ChainPurge - Gives DeFi users the tool to fight tax-harvesting developers by unclogging all of the swapback tokens in single transaction.

##### Token address and ticker if any:
Address: 0xE155F64B9aD8c81318c313196a60c72e72fD2cD1 
Ticker: CTLS

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
None.

##### forkedFrom (Does your project originate from another project):
No. Used Uniswap v3 Libraries only

##### methodology (what is being counted as tvl, how is tvl being calculated):
First we compute the total CTLS locked, as a sum of the following components:
1. CTLS Balance in Uniswap V3 Pool WETH-CTLS 1% Fee Tier
2. CTLS Balance in Multisig (Treasury)
3. CTLS Balance in Yield Booster
4. CTLS Balance in Yield Vault
5. CTLS Balance in Incentives Wallet

Then we compute the total ETH + WETH locked, as a sum of the following components:
1. WETH Balance in Uniswap V3 Pool WETH-CTLS 1% Fee Tier
2. WETH Balance in Multisig (Treasury)
3. WETH Balance in Yield Vault
4. ETH Balance in Multisig (Treasury)
5. ETH Balance in Yield Booster
6. ETH Balance in Incentives Wallet
7. ETH Balance in Compounding (Keeper) Bot

Combining the dollar amounts of the total CTLS and total ETH + WETH we compute the total current $TVL.

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/chaintools exports TVL: 
        
 
 
    ethereum                  4.24 k
    ethereum-staking          27.31 k
    ethereum-treasury         43.25 k
    staking                   27.31 k
    treasury                  43.25 k
    
    total                    4.24 k

**Comment by llamatester** [comment]
The adapter at projects/chaintools exports TVL: 
        
 
 
    ethereum                  4.24 k
    ethereum-staking          27.83 k
    ethereum-treasury         43.78 k
    staking                   27.83 k
    treasury                  43.78 k
    
    total                    4.24 k

**Comment by g1nt0ki** [comment]
@IamNimrod thanks for the PR, but I have seeing how we could list you. we consider the tokens locked in your protocol as tvl, but so far I am seeing users LPing via Uni V3, and yield is given to people holding LPs 

But users have not locked their LP in your contract, so not sure how the uni v3 LP can be considered your tvl.

**Comment by llamatester** [comment]
The adapter at projects/chaintools exports TVL: 
        
 
 
    ethereum-staking          27.39 k
    ethereum                  4.24 k
    staking                   27.39 k
    
    total                    4.24 k

**Pull request merged**
