### PR TITLE
Update Juice Finance

### PR DESCRIPTION
**Pull request by hoomp3**
Adding Lending Pool that holds WETH.

We also have 2 more vaults, but they don't hold any ERC20s that can be priced, how do we account for them?

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/juice-finance: 
        
 
  
    
    
    TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/unwrapLPs.js:764:41
        at Array.map (<anonymous>)
        at sumTokens2 (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/unwrapLPs.js:764:37)
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/juice-finance/index.js:14:10)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:67:29)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:163:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:151:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:146:44

**Comment by llamatester** [comment]
The adapter at projects/juice-finance exports TVL: 
        
 
 
    blast                     70.40 M
    
    total                    70.40 M

**Comment by waynebruce0x** [comment]
What do the vaults hold? have you got addresses for them? 

Can you track the borrowed amounts from the lending pools? That could be exported as `borrowed`

**Comment by g1nt0ki** [comment]
@hoomp3 I have added support for pricing wUSDBB to our server

**Comment by hoomp3** [comment]
@waynebruce0x 

One of them doesn't hold anything since it creates LP and stakes it into another contract, but I'll add the one that @g1nt0ki added support for and then add the borrowed amounts from the lending pools.

**Pull request merged**
