### PR TITLE
Add PandaLand

### PR DESCRIPTION
**Pull request by mainnet-pat**
##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): https://pandaland.cash/assets/icon-pda.7c4fe3c4.png
icon-pda 7c4fe3c4

##### Short Description (to be shown on DefiLlama):
Pandaland is a blockchain game interactive platform based on SmartBCH. It starts with games and will gradually expand to NFT exchanges, NFT staking, DEX, and more.

##### methodology (what is being counted as tvl, how is tvl being calculated): 
TVL includes all farms in MasterChef contract

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/pandaland: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'push')
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/computeTVL/index.js:252:45
        at new Promise (<anonymous>)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:59:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:160:9
        at async Promise.all (index 1)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:3

**Comment by mainnet-pat** [comment]
I have an issue with `masterChefExports` suggested to be used in https://github.com/DefiLlama/DefiLlama-Adapters/pull/2548#issuecomment-1118769335

It does not properly handle the smartbch price fetching since smartbch is not in the list of chains in sdk https://github.com/DefiLlama/defillama-sdk/blob/62dba10fe5413eda41caca1ee210574b18d1a56b/src/computeTVL/index.ts#L94
When adding it, it fixes the crash but still fetches zero prices. Could you please assit @g1nt0ki ?

**Comment by g1nt0ki** [comment]
the issue is missing transform, coingecko doesnt recognise smartbch tokens yet, I have made a workaround here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/2593

It would ignore tokens not part of this mapping. If you merge main into your branch, the error will disappear

**Comment by llamatester** [comment]
The adapter at projects/pandaland exports TVL: 
        
 
 
    smartbch                  0
    smartbch-masterchef       0
    smartbch-pool2            49.37 k
    smartbch-staking          0
    masterchef                0
    pool2                     49.37 k
    staking                   0
    
    total                    0

**Comment by mainnet-pat** [comment]
thanks a lot @g1nt0ki !

**Pull request merged**
