### PR TITLE
Cowaii Cash

### PR DESCRIPTION
**Pull request by surfacing8671**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on
Cowaii Cash

##### Twitter Link:
https://twitter.com/CowaiiTomb

##### Website Link:
https://cowaii.cash/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://cowaii.cash/static/media/cowaii.43161b31.png

##### Current TVL:
35000

##### Chain:
Dogechain

##### Short Description (to be shown on DefiLlama):
Cowaii Cash is the only vibratile token on the Dogechain.

##### Token address and ticker if any:
COWAII 0xB483CbF402eF2B07060544e4aA4c5690fea32B12
MILK 0xc90163b8d53F319AbE68dd1d8ecC025c72eB3f04

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Algo-stable

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
TWAP

##### forkedFrom (Does your project originate from another project):
Tomb Finance

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/Cowaii_Cash: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:223:11

**Comment by realdealshaman** [comment]
@surfacing8671 dogechain should be exported as dogechain, we also have a helper for unknown tombs otherwise if your tokens are not on coingecko a price cannot be fetched for them. Also, please makesure that your project folder is added to the projects folder -> projects/cowaii-cash/index.js

**Comment by llamatester** [comment]
The adapter at projects/cowaii-cash exports TVL: 
        
 
 
    dogechain                 0
    dogechain-staking         164.844224
    dogechain-pool2           11.739647999999999
    staking                   164.844224
    pool2                     11.739647999999999
    
    total                    0

**Comment by llamatester** [comment]
Error while running adapter at projects/cryptomate.js: 
        
 
  
    
    
    Error: getaddrinfo ENOTFOUND api-finance.cryptomate.me
    Truncated error stack:
    
        at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)

**Pull request merged**
