### PR TITLE
Update avalon finance tvl script

### PR DESCRIPTION
**Pull request by tpktpj**
- Update Avalon finance tvl script

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/avalon-finance exports TVL: 
        
 
 
    borrowed                  424.59 M
    btr-borrowed              211.72 M
    merlin-borrowed           158.96 M
    merlin                    139.37 M
    btr                       123.53 M
    bsc-borrowed              53.67 M
    bsc                       49.34 M
    arbitrum                  244.64 k
    arbitrum-borrowed         244.64 k
    core-borrowed             0
    core                      0
    
    total                    312.48 M

**Comment by tpktpj** [comment]
Please help us to add price mapping for the following unrecognized asset. 

Bitlayer Assets:
```
┌─────────┬───────────────────────────┬───────────────────┬─────────┬──────────────────────────────────────────────────┬──────────┐
│ (index) │           name            │      symbol       │ balance │                      label                       │ decimals │
├─────────┼───────────────────────────┼───────────────────┼─────────┼──────────────────────────────────────────────────┼──────────┤
│    0    │  'Free Bridged SolvBTC'   │    'SolvBTC.m'    │  '112'  │ 'btr:0xe04d21d999faedf1e72ade6629e20a11a1ed14fa' │   '18'   │
│    1    │ 'Bitcow v1 lp stBTC-WBTC' │ 'bcLP-stBTC-WBTC' │  '189'  │ 'btr:0xb88a54ebbda8edbc1c2816ace1dc2b7c6715972d' │   '18'   │
│    2    │ 'Macaron StableSwap LPs'  │    'Stable-LP'    │  '400'  │ 'btr:0xb750f79cf4768597f4d05d8009fcc7cee2704824' │   '18'   │
└─────────┴───────────────────────────┴───────────────────┴─────────┴──────────────────────────────────────────────────┴──────────┘
```

- SolvBTC.m = SolvBTC (https://www.coingecko.com/en/coins/solv-protocol-solvbtc)
- bcLP-stBTC-WBTC = stBTC + WBTC (https://www.coingecko.com/en/coins/bitcoin)
- Stable-LP = stBTC + WBTC (https://www.btrscan.com/address/0xb750f79cf4768597f4d05d8009fcc7cee2704824)

Merlin Assets: 
```
┌─────────┬───────────────────────────┬──────────────┬─────────────┬─────────────────────────────────────────────────────┬──────────┐
│ (index) │           name            │    symbol    │   balance   │                        label                        │ decimals │
├─────────┼───────────────────────────┼──────────────┼─────────────┼─────────────────────────────────────────────────────┼──────────┤
│    0    │   'Bridged BRC20 ordi'    │    'ordi'    │    '366'    │ 'merlin:0x7dcb50b2180bc896da1200d2726a88af5d2cbb5a' │   '18'   │
│    1    │ 'Escrow MerlinSwap Token' │    'esMP'    │ '628405932' │ 'merlin:0x7126bd63713a7212792b08fa2c39d39190a4cf5b' │   '18'   │
│    2    │   'Bridged BRC20 MNER'    │    'MNER'    │   '4256'    │ 'merlin:0x27622b326ff3ffa7dc10ae291800c3073b55aa39' │   '18'   │
│    3    │   'Bridged bsc-20 bnbs'   │    'BNBS'    │   '51873'   │ 'merlin:0x33c70a08d0d427ee916576a7594b50d7f8f3fbe1' │   '18'   │
│    4    │ 'SURF Solv BTC LP TOKEN'  │ 'SolvBTCSLP' │    '22'     │ 'merlin:0x4920fb03f3ea1c189dd216751f8d073dd680a136' │   '18'   │
│    5    │   'SURF WBTC LP TOKEN'    │  'WBTCSLP'   │     '0'     │ 'merlin:0xb00db5faae7682d80ca3ce5019e710ca08bfbd66' │   '18'   │
│    6    │   'SURF MBTC LP TOKEN'    │  'MBTCSLP'   │     '0'     │ 'merlin:0xa41a8c64a324cd00cb70c2448697e248ea0b1ff2' │   '18'   │
└─────────┴───────────────────────────┴──────────────┴─────────────┴─────────────────────────────────────────────────────┴──────────┘
```

- ordi (https://www.coingecko.com/en/coins/ordi)
- esMP (https://www.coingecko.com/en/coins/merlinswap)
- SolvBTCSLP == SolvBTC (https://www.coingecko.com/en/coins/solv-protocol-solvbtc)
- WBTCSLP = WBTC (https://www.coingecko.com/en/coins/bitcoin)
- MBTCSLP = MBTC (https://www.coingecko.com/en/coins/bitcoin)

- MNER (https://www.geckoterminal.com/merlin-chain/pools/0x224988674102f0680169bffb4f29c928771fa1cd)
- BNBS (https://www.geckoterminal.com/bsc/pools/0x076ce92597fa5d0517767ce196ba8e79a31fd49d)

**Comment by tpktpj** [comment]
> Please help us to add price mapping for the following unrecognized asset.
> 
> Bitlayer Assets:
> 
> ```
> ┌─────────┬───────────────────────────┬───────────────────┬─────────┬──────────────────────────────────────────────────┬──────────┐
> │ (index) │           name            │      symbol       │ balance │                      label                       │ decimals │
> ├─────────┼───────────────────────────┼───────────────────┼─────────┼──────────────────────────────────────────────────┼──────────┤
> │    0    │  'Free Bridged SolvBTC'   │    'SolvBTC.m'    │  '112'  │ 'btr:0xe04d21d999faedf1e72ade6629e20a11a1ed14fa' │   '18'   │
> │    1    │ 'Bitcow v1 lp stBTC-WBTC' │ 'bcLP-stBTC-WBTC' │  '189'  │ 'btr:0xb88a54ebbda8edbc1c2816ace1dc2b7c6715972d' │   '18'   │
> │    2    │ 'Macaron StableSwap LPs'  │    'Stable-LP'    │  '400'  │ 'btr:0xb750f79cf4768597f4d05d8009fcc7cee2704824' │   '18'   │
> └─────────┴───────────────────────────┴───────────────────┴─────────┴──────────────────────────────────────────────────┴──────────┘
> ```
> 
> * SolvBTC.m = SolvBTC (https://www.coingecko.com/en/coins/solv-protocol-solvbtc)
> * bcLP-stBTC-WBTC = stBTC + WBTC (https://www.coingecko.com/en/coins/bitcoin)
> * Stable-LP = stBTC + WBTC (https://www.btrscan.com/address/0xb750f79cf4768597f4d05d8009fcc7cee2704824)
> 
> Merlin Assets:
> 
> ```
> ┌─────────┬───────────────────────────┬──────────────┬─────────────┬─────────────────────────────────────────────────────┬──────────┐
> │ (index) │           name            │    symbol    │   balance   │                        label                        │ decimals │
> ├─────────┼───────────────────────────┼──────────────┼─────────────┼─────────────────────────────────────────────────────┼──────────┤
> │    0    │   'Bridged BRC20 ordi'    │    'ordi'    │    '366'    │ 'merlin:0x7dcb50b2180bc896da1200d2726a88af5d2cbb5a' │   '18'   │
> │    1    │ 'Escrow MerlinSwap Token' │    'esMP'    │ '628405932' │ 'merlin:0x7126bd63713a7212792b08fa2c39d39190a4cf5b' │   '18'   │
> │    2    │   'Bridged BRC20 MNER'    │    'MNER'    │   '4256'    │ 'merlin:0x27622b326ff3ffa7dc10ae291800c3073b55aa39' │   '18'   │
> │    3    │   'Bridged bsc-20 bnbs'   │    'BNBS'    │   '51873'   │ 'merlin:0x33c70a08d0d427ee916576a7594b50d7f8f3fbe1' │   '18'   │
> │    4    │ 'SURF Solv BTC LP TOKEN'  │ 'SolvBTCSLP' │    '22'     │ 'merlin:0x4920fb03f3ea1c189dd216751f8d073dd680a136' │   '18'   │
> │    5    │   'SURF WBTC LP TOKEN'    │  'WBTCSLP'   │     '0'     │ 'merlin:0xb00db5faae7682d80ca3ce5019e710ca08bfbd66' │   '18'   │
> │    6    │   'SURF MBTC LP TOKEN'    │  'MBTCSLP'   │     '0'     │ 'merlin:0xa41a8c64a324cd00cb70c2448697e248ea0b1ff2' │   '18'   │
> └─────────┴───────────────────────────┴──────────────┴─────────────┴─────────────────────────────────────────────────────┴──────────┘
> ```
> 
> * ordi (https://www.coingecko.com/en/coins/ordi)
> * esMP (https://www.coingecko.com/en/coins/merlinswap)
> * SolvBTCSLP == SolvBTC (https://www.coingecko.com/en/coins/solv-protocol-solvbtc)
> * WBTCSLP = WBTC (https://www.coingecko.com/en/coins/bitcoin)
> * MBTCSLP = MBTC (https://www.coingecko.com/en/coins/bitcoin)
> * MNER (https://www.geckoterminal.com/merlin-chain/pools/0x224988674102f0680169bffb4f29c928771fa1cd)
> * BNBS (https://www.geckoterminal.com/bsc/pools/0x076ce92597fa5d0517767ce196ba8e79a31fd49d)

PR for this: https://github.com/DefiLlama/defillama-server/pull/7162

**Comment by llamatester** [comment]
Error while running adapter at projects/avalon-finance: 
        
 
  
    
    
    Error: Multicall failed! 
     [chain: merlin] [fail count: 1] [abi: address:UNDERLYING_ASSET_ADDRESS]  
        target: 0xF6171ccbB2FA1Bd9f08cD4Ddf012696FCdec1BD9

**Comment by tpktpj** [comment]
> Error while running adapter at projects/avalon-finance:
> 
> ```
> Error: Multicall failed! 
>  [chain: merlin] [fail count: 1] [abi: address:UNDERLYING_ASSET_ADDRESS]  
>     target: 0xF6171ccbB2FA1Bd9f08cD4Ddf012696FCdec1BD9 
> ```

@waynebruce0x Could you help to check with this? I tried to run the test on my local, but still failed. 
Prob related to this PR? https://github.com/DefiLlama/defillama-server/pull/7219

**Pull request merged**
