### PR TITLE
lachain-yield-market

### PR DESCRIPTION
**Pull request by kunalgoyal9**
##### Twitter Link:
https://twitter.com/0xlachain

##### List of audit links if any:
NA

##### Website Link:
https://app.lachain.io/yield-market

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
image

##### Current TVL:
$3

##### Chain:
lachain

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
NA

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
NA

##### Short Description (to be shown on DefiLlama):
Lachain Yield Market is a single spot to manage yields and launch assets across chains. User can move crypto across chains and protocols in 2 clicks and pay all gas fees in LA.

##### Token address and ticker if any:
NA

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
NA

##### forkedFrom (Does your project originate from another project):
NA

##### methodology (what is being counted as tvl, how is tvl being calculated):
NA

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/lachain-yield-market.js: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'undefined')
    Truncated error stack:
    
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/lachain-yield-market.js:33:30)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:58:25)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:160:9
        at async Promise.all (index 0)
        at async Promise.all (index 0)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:3

**Comment by g1nt0ki** [comment]
Hi Kunal, I am not sure if this should be added. I see aave yield on Polygon chain in UI, but the list of farms is different the one fetched from github,

Also, there usually is an masterchef contract, this looks more like you are counting bridged token supply as yield?

**Comment by llamatester** [comment]
The adapter at projects/lachain-yield-market.js exports TVL: 
        
 
 
    lachain                   7.809467009589014
    
    total                    7.809467009589014

**Comment by g1nt0ki** [comment]
> Hi Kunal, I am not sure if this should be added. I see aave yield on Polygon chain in UI, but the list of farms is different the one fetched from github,
> 
> Also, there usually is an masterchef contract, this looks more like you are counting bridged token supply as yield?

@kunalgoyal9 can you please answer this

**Comment by kunalgoyal9** [comment]
@g1nt0ki yield market on lachain is unique multichain farms aggregator, where users put their funds on single Lachain chain into farms on different chains.

Now I did it from the TVL bridge API. Please let me know for any changes

**Comment by kunalgoyal9** [comment]
@g1nt0ki Yes, these are bridged moo tokens.

When user makes deposit, wrapped deposit tokens are burned on Lachain side, then on External blockchain tokens are unlocked and used to deposit into beefy vault. Then vault mints moo tokens to beefy handler, they are locked, and then the same amount is minted to the user on lachain

**Comment by kunalgoyal9** [comment]
@g1nt0ki Also, we need this lachain-yield market to constitute under Lachain side's TVL.

**Comment by llamatester** [comment]
The adapter at projects/lachain-yield-market.js exports TVL: 
        
 
 
    
    total                    30.536979000000002

**Comment by llamatester** [comment]
The adapter at projects/lachain-yield-market.js exports TVL: 
        
 
 
    lachain                   30.536978999999995
    
    total                    30.536979

**Pull request merged**
