### PR TITLE
add zenlink tvl on bifrost

### PR DESCRIPTION
**Pull request by haike0513**
Add the tvl of zenlink on bifrost

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/zenlink: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by llamatester** [comment]
The adapter at projects/zenlink exports TVL: 
        
 
 
    bifrost                   4.34 M
    moonriver                 461.78 k
    moonbeam                  187.74 k
    astar                     517.48 k
    
    total                    5.51 M

**Comment by g1nt0ki** [comment]
@haike0513 now bifrost dex shows up under zenlink but since about 24 hours ago, we are no longer able to query bifrost rpc from our server, any idea what is going on? we started having similar issues with genshiro earlier this week

**Comment by haike0513** [comment]
> @haike0513 now bifrost dex shows up under zenlink but since about 24 hours ago, we are no longer able to query bifrost rpc from our server, any idea what is going on? we started having similar issues with genshiro earlier this week

I'm not sure about this, I didn't kown your server how to query it, But I can query it local by `https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/bifrost-dex/api.js`.

**Comment by g1nt0ki** [comment]
@haike0513 we run the same queries/call the same script on our server but for some reason, it fails to even connect to the websocket 

Weird, just tried and it works fine. For some reason genshiro still fails. closing this PR as it is fixed on server (so wqe dont lose historical data)

**Pull request closed without merging**
