### PR TITLE
RBX sdk adapter

### PR DESCRIPTION
**Pull request by PeanutArbuckle0**
**NOTE**

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
RBX

##### Twitter Link:
https://twitter.com/RBXtoken

##### List of audit links if any:
https://github.com/cyberscope-io/audits/tree/main/1-rbx

##### Website Link:
https://rbxdefi.com

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://drive.google.com/uc?export=view&id=1GwLKpsYz44ZcAmZVPQcTp1zjHwmlEZcy

##### Current TVL:
$6.56M

##### Chain:
Ethereum, Binance Smart Chain, Avalanche

##### Coingecko ID (so your TVL can appear on Coingecko): 
rbx-token

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): 
13326

##### Short Description (to be shown on DefiLlama):
RBX is a novel ecosystem of Decentralized finance DApps, utilities, infrastructure, and protocols, built to accelerate the flow of digital assets and capital. The RBX suite of products provides everything a trader, or project, needs to be successful, all in one simple widgetized package.

##### Token address and ticker if any:
Ethereum: RBX 0x8254e26e453eb5abd29b3c37ac9e8da32e5d3299
                  RBXS 0xA9639160481b625ba43677bE753E0A70bf58c647

Avalanche: RBX 0xA9639160481b625ba43677bE753E0A70bf58c647

BSC: RBX 0xace3574b8b054e074473a9bd002e5dc6dd3dff1b
         RBXS 0x11dbf6e897804fbed56cff8ac54fc7bdae50e86a

##### Category (full list at https://defillama.com/categories) *Please choose only one: 
Dexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
N/A

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
    All RBX tokens in RBX bridge contracts
    All RBX and RBXS multisig wallets
    All tokens in RBX staking contracts

### CODE REVIEW

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
I am bit confused, why are the tokens in bridges/multisig counted towards protocol tvl?
Also, RBX tokens can be counted towards 'staking' not tvl: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by PeanutArbuckle0** [comment]
I've removed the bridges/multisigs from the tvl calculation, all that's being counted now are the tokens in our staking contracts. Is this sufficient or do those tokens need to be counted as part of 'staking' rather than TVL?

**Comment by llamatester** [comment]
The adapter at projects/rbx exports TVL: 
        
 
 
    ethereum-pool2            0
    ethereum                  72.01 k
    ethereum-staking          196.91 k
    bsc-pool2                 0
    bsc-staking               248.13 k
    bsc                       769.07 k
    pool2                     0
    staking                   445.04 k
    
    total                    841.08 k

**Comment by sycore0** [comment]
why was the RBXS token blacklisted?

**Comment by g1nt0ki** [comment]
@sycore0 sorry, I had missed your comment. RBX token is not blacklisted but counted under 'staking'

**Comment by sycore0** [comment]
> @sycore0 sorry, I had missed your comment. RBX token is not blacklisted but counted under 'staking'

kk gracias

**Pull request merged**
