### PR TITLE
fixed BTC supply

### PR DESCRIPTION
**Pull request by NikolasHai**
This MR proposes the following changes:

1. Change chain name to ICP for ckETH and ckBTC
2. Collect the collective TVL for ckBTC using the ICP API

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/ckbtc: 
        
 
  
    
    
    TypeError: Cannot create property 'coingecko:0' on string '13541247656'
    Truncated error stack:
        at Object.sumSingleBalance (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:115:25)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:328:16
        at Array.forEach (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:322:28)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:335:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:63:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:157:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)

**Comment by g1nt0ki** [comment]
hi @NikolasHai these are bridges right? we count tvl at the source rather than destination

**Comment by NikolasHai** [comment]
> hi @NikolasHai these are bridges right? we count tvl at the source rather than destination

Hi, they are bridges yes. I was looking at the example of [WBTC](https://defillama.com/protocol/wbtc) where the amount of WBTC is also shown on the Ethereum chain not Bitcoin network. That is why I proposed the change to icp.

**Comment by g1nt0ki** [comment]
WBTC is sort of legacy, would like to turn it on chain but was hard to do it the last I tried and didnt find time to try again.

Also, bit of heads  up, irrespective of which chain this is counted under, it wont show up in either chain's tvl: https://github.com/DefiLlama/DefiLlama-Adapters/discussions/435

**Comment by llamatester** [comment]
The adapter at projects/ckbtc exports TVL: 
        
 
 
    bitcoin                   6.28 M
    
    total                    6.28 M

**Pull request merged**
