### PR TITLE
Added listing for new Game Protocol - CatsApes

### PR DESCRIPTION
**Pull request by DheerGupta35959**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/catsapes: 
        
 
  
    
    
    TypeError: addresses.forEach is not a function
    Truncated error stack:
    
        at getUniqueAddresses (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/utils.js:140:13)
        at sumTokens2 (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/unwrapLPs.js:707:14)
        at staking (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/catsapes/index.js:23:14)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:29)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:136:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:131:44

**Comment by llamatester** [comment]
Error while running adapter at projects/catsapes: 
        
 
  
    
    
    PromisePoolError: invalid address (argument="address", value="0xb44a9b6905af7c801311e8f4e76932ee959c663", code=INVALID_ARGUMENT, version=address/5.7.0) (argument="target", value="0xb44a9b6905af7c801311e8f4e76932ee959c663", code=INVALID_ARGUMENT, version=abi/5.7.0)
    Truncated error stack:
        at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
Error while running adapter at projects/catsapes: 
        
 
  
    
    
    PromisePoolError: invalid address (argument="address", value="0xb44a9b6905af7c801311e8f4e76932ee959c663", code=INVALID_ARGUMENT, version=address/5.7.0) (argument="target", value="0xb44a9b6905af7c801311e8f4e76932ee959c663", code=INVALID_ARGUMENT, version=abi/5.7.0)
    Truncated error stack:
        at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
The adapter at projects/catsapes exports TVL: 
        
 
 
    kava                      0
    kava-staking              0
    staking                   0
    
    total                    0

**Comment by DheerGupta35959** [comment]
Why value is showing 0 as It has WKAWA which has value of 65.

**Comment by g1nt0ki** [comment]
@DheerGupta35959 thanks for the PR, I have fixed the adapter

**Comment by llamatester** [comment]
The adapter at projects/catsapes exports TVL: 
        
 
 
    kava-pool2                0
    kava-staking              0
    kava                      49.927735
    pool2                     0
    staking                   0
    
    total                    49.927735

**Pull request merged**
