### PR TITLE
Add Cell adapter

### PR DESCRIPTION
**Pull request by qiwu7**
##### Twitter Link:
https://twitter.com/cellfi_io

##### Website Link:
https://cellfi.io

##### Current TVL:
$215,168.07

##### Chain:
Solana

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
n/a

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
n/a

##### Short Description (to be shown on DefiLlama):
Cell, or Smart Automated Market Making (SAMM), aims to become the liquidity gateway for CLOBs via simplified and automated LP tools.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
n/a

##### forkedFrom (Does your project originate from another project):
no

##### methodology (what is being counted as tvl, how is tvl being calculated):
total assets deposited into the protocol.

### CODE REVIEW

**Comment by 0xngmi** [comment]
pls no fetch adapters

**Comment by waynebruce0x** [comment]
yeah as ngmi says - can we count address balances instead of calling the API?

**Comment by qiwu7** [comment]
Hi @waynebruce0x @0xngmi 

I saw on the `how to build an adapter` part of the [guide](https://docs.llama.fi/list-your-project/submit-a-project#how-to-build-an-adapter)

> if your project is on another chain a fetch adapter is likely the way to go

I have also been following other examples on Solana, such as 
Serum: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/serum.js#L7
Raydium: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/raydium.js#L6

For our protocol, we don't have a single address that stores all the funds, and they are hold on each individual Solana accounts instead.

**Comment by waynebruce0x** [comment]
Yeah thats fine, we were just asking because we prefer onchain adapters for transparency. What's counted as TVL by the API? Is it open source?

**Comment by qiwu7** [comment]
> Yeah thats fine, we were just asking because we prefer onchain adapters for transparency. What's counted as TVL by the API? Is it open source?

Each bot has a solana account, and there is no easy way to aggregate them onchain at the moment. The API is basically adding all the balances of the bots together and report that.

**Comment by waynebruce0x** [comment]
Yeah that makes sense - is it open source so we can check the logic?

**Comment by waynebruce0x** [comment]
@qiwu7

**Comment by waynebruce0x** [comment]
Closing for inactivity

**Pull request closed without merging**
