### PR TITLE
add mojitoswap dexs

### PR DESCRIPTION
**Pull request by dtmkeng**

### CODE REVIEW

**Comment by llamatester** [comment]
The mojitoswap adapter exports: 
        
 
 _______________________________________
    Volume for 21/9/2022
    _______________________________________
    
    KCC 👇
    Backfill start time: 14/10/2021
    24h volume: 1017886.404727408088862158080355709
    Total volume: 1164359302.9335954

**Comment by llamatester** [comment]
The mojitoswap adapter exports: 
        
 
 _______________________________________
    Volume for 21/9/2022
    _______________________________________
    
    KCC 👇
    Backfill start time: 14/10/2021
    24h volume: 1017886.404727408088862158080355709
    Total volume: 1164359302.9335954

**Comment by llamatester** [comment]
The mojitoswap adapter exports: 
        
 
 _______________________________________
    Volume for 23/9/2022
    _______________________________________
    
    KCC 👇
    Backfill start time: 14/10/2021
    24h volume: 693571.2729086686212810524229544933
    Total volume: 1165825245.7508645

**Comment by dtmkeng** [comment]
LG, ty

**Pull request merged**
