### PR TITLE
feat(strips): add strips.finance adpter

### PR DESCRIPTION
**Pull request by developerfred**
ref: https://github.com/strips-finance/defistats/issues/1

##### Twitter Link:
https://twitter.com/stripsfinance

##### Website Link:
https://app.strips.finance/liquidity

##### Chain:
Arbitrum 

##### Token address and ticker if any:
https://arbiscan.io/token/0x326c33fd1113c1f29b35b4407f3d6312a8518431

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Are the changes to the gnosis and dydx files expected?

**Comment by llamatester** [comment]
The adapter at projects/dydx exports TVL: 
        
 
 
    ethereum                  1.02 B
    
    total                    1.02 B

**Comment by llamatester** [comment]
The adapter at projects/strips-finance exports TVL: 
        
 
 
    arbitrum                  0
    
    total                    0

**Comment by developerfred** [comment]
@waynebruce0x is there a way to add sums to calculateUsdUniTvl

**Comment by waynebruce0x** [comment]
Yeah I'd probably use sdk.util.sumChainTvls() - there's a few examples of how its used in the repo

**Pull request closed without merging**
