### PR TITLE
add gravity config

### PR DESCRIPTION
**Pull request by LpcAries**
add gravity config

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/izumi-iziswap: 
        
 
  
    
    
    Error: 
        Unknown chain(s): gravity
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file
        
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by LpcAries** [comment]
I noticed that you support Gravity at https://unpkg.com/@defillama/sdk@5.0.83/build/providers.json, but the adapter can't recognize it. Could someone helps me figure out why?

**Comment by Define101** [comment]
@LpcAries Use the slug "gravitybridge" instead of gravity

**Comment by LpcAries** [comment]
Seems to be a rpc issue, is there a limit rate of request on rpc of gravity?  @Define101

**Comment by g1nt0ki** [comment]
closing this for https://github.com/DefiLlama/DefiLlama-Adapters/pull/11466

Gravitybridge is a different chain

**Comment by LpcAries** [comment]
> closing this for #11466
> 
> Gravitybridge is a different chain

thanks

**Pull request closed without merging**
