### PR TITLE
feat: add love project

### PR DESCRIPTION
**Pull request by Lovedotio**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

##### Name (to be shown on DefiLlama):

Love.io

##### Twitter Link:

Twitter Link: https://twitter.com/lovedotio

##### List of audit links if any:

The Hacken audit is completed but has not been published publicly yet

##### Website Link:

Website Link: https://love.io/

##### Logo (High resolution, will be shown with rounded borders):

https://i.ibb.co/Dt3xX89/image.png

##### Current TVL:

1.40M

##### Treasury Addresses (if the protocol has treasury)

0xb920fCe947c03DE6F0b08BDe3464D57281D1548d

##### Chain:

Pulsechain (PLS), Ethereum mainnet (ETH), Binance Smart Chain (BSC)

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

love-io

##### Short Description (to be shown on DefiLlama):

Love.io is a decentralized protocol for peer to peer value transfer connecting Web3, with traditional Social Media and E-Commerce platforms. The protocol enables peer-to-peer micro-tipping and to earn LOVE loyalty rewards through sophisticated dApps. The protocol enables micro-tipping on X.com, Youtube, Twitch, Instagram, Facebook and much more. Love.io seamlessly integrates peer to peer micro-tipping with brand loyalty rewards, followed by decentralized finance (Defi). Lovefy.com is a global marketplace connecting over 1 million influencers from 89 countries with products from renowned brands such as Gucci, Armani, Versace, Ray Ban, and Dior.

##### Token address and ticker if any:

LOVE

##### Category (full list at https://defillama.com/categories) \*Please choose only one:

Lending, Bridge, Yield

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

MODEFI via Dextools API

##### forkedFrom (Does your project originate from another project):

NO

##### methodology (what is being counted as tvl, how is tvl being calculated):

Total amount of liquidity in liquidity pools on dex’s + total amount of tokens staked in the staking dapp

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/love: 
        
 
  
    
    
    Error: Invalid balance: undefined
    Truncated error stack:
        at isValidNumber (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:119:19)
        at Array.forEach (<anonymous>)
        at tvl_BSC (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/love/index.js:121:7)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:53:23)

**Comment by llamatester** [comment]
The adapter at projects/love exports TVL: 
        
 
 
    ethereum                  0
    pulse                     0
    bsc                       0
    bsc-staking               7.76 M
    pulse-staking             8.16 M
    ethereum-staking          7.90 M
    staking                   23.82 M
    
    total                    0

**Comment by g1nt0ki** [comment]
@Lovedotio thanks for the PR, I have refactored the code a bit, we cant count staked tokens as tvl, also liquidity on uniswap does not count towards your tvl, we can count the staked LP as pool2 though: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by llamatester** [comment]
The adapter at projects/love exports TVL: 
        
 
 
    ethereum                  0
    pulse                     0
    bsc                       0
    ethereum-staking          7.90 M
    pulse-staking             8.16 M
    bsc-staking               7.76 M
    staking                   23.81 M
    
    total                    0

**Comment by Lovedotio** [comment]
Hi, Thank you for the response. 

Let me give you a few more details about the LOVE token. 
### Staking DAPP:
[](https://staking.love.io/)

### You can check the liquidity on our Trading Pairs: 
Trading Pair(LOVE/PLSX): [](https://dexscreener.com/pulsechain/0xeffb56e3402f1993a34887eecaaa3d63da8e3f85)
Trading Pair(LOVE/WETH): [](https://dexscreener.com/pulsechain/0xeffb56e3402f1993a34887eecaaa3d63da8e3f85)
Trading Pair(LOVE/BSC): Soon Pancakeswap for Binance Smart Chain liquidity 

so where should we count the total LOVE token staked by the Users on our staking DAPP(PLS/ETH/BSC)

Kind regards, 
Team love.io

**Comment by Lovedotio** [comment]
Hi, Thank you for the response.
Please address these problems, we have liquidity on different trading pairs. can't we count it as the TVL?

Let me give you a few more details about the LOVE token.

Staking DAPP:
https://staking.love.io/

You can check the liquidity on our Trading Pairs:
Trading Pair(LOVE/PLSX): https://dexscreener.com/pulsechain/0xeffb56e3402f1993a34887eecaaa3d63da8e3f85
Trading Pair(LOVE/WETH): https://dexscreener.com/pulsechain/0xeffb56e3402f1993a34887eecaaa3d63da8e3f85
Trading Pair(LOVE/BSC): Soon Pancakeswap for Binance Smart Chain liquidity

so where should we count the total LOVE tokens staked by the Users on our staking DAPP(PLS/ETH/BSC)?

Staking Contracts

PLS - 0xDd91E607C919Db74e18C2845e4cfb22793c30b2f
BSC - 0x1781e00780AfD93a03Bf5f9dED088a8578cE9B09
ETH - 0xE639E9DC0E302f5dB025713009868c8adE4Ced26

Kind regards,
Team love.io

**Comment by g1nt0ki** [comment]
Again, no lp tvl belongs to the Dex, not your project: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by Lovedotio** [comment]
How can we show APY?

**Pull request merged**
