### PR TITLE
fix: dopex tvl

### PR DESCRIPTION
**Pull request by witherblock**
- Removed deprecated chains
- Removed staking pools
- Added all active SSOVs 
- Refactored SSOV tvl fn to correctly represent TVL
- Added our new CLAMM product (based of UNI V3) TVL

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/dopex exports TVL: 
        
 
 
    arbitrum                  5.25 M
    
    total                    5.25 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/dopex.js exports TVL: 
        
 
 
    ethereum-ownTokens        1.98 M
    arbitrum-ownTokens        45.21 M
    arbitrum                  3.35 M
    ethereum                  2.65 M
    ownTokens                 47.18 M
    
    total                    6.00 M

**Comment by llamatester** [comment]
The adapter at projects/dopex exports TVL: 
        
 
 
    arbitrum                  5.19 M
    
    total                    5.19 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/dopex.js exports TVL: 
        
 
 
    ethereum-ownTokens        1.96 M
    arbitrum-ownTokens        45.29 M
    arbitrum                  3.30 M
    ethereum                  2.65 M
    ownTokens                 47.26 M
    
    total                    5.95 M

**Comment by llamatester** [comment]
The adapter at projects/dopex exports TVL: 
        
 
 
    arbitrum                  5.37 M
    
    total                    5.37 M

**Comment by llamatester** [comment]
The adapter at projects/dopex exports TVL: 
        
 
 
    ethereum                  0
    bsc                       0
    avax                      0
    arbitrum                  3.78 M
    
    total                    3.78 M

**Comment by llamatester** [comment]
The adapter at projects/dopex-clamm exports TVL: 
        
 
 
    arbitrum                  1.77 M
    
    total                    1.77 M

**Comment by g1nt0ki** [comment]
hi @witherblock 
Thanks for the PR, I refactored the code a bit. Re-added the deprecated chains with 0 tvl, as if we remove them, past tvl history for those chains will vanish from the UI

Also, added a new sub-listing for CLAMM product, not all tokens are in Uni pool but some are in options market? I added the code but unsure if I was double counting so commented it out for now. 

Can you go through my changes and see if it is okay? then I will merge and list CLAMM as new product. Oh, we cant cache the response  because if the graph is stale/unreachable, we will end up returning old data.

**Comment by witherblock** [comment]
> hi @witherblock Thanks for the PR, I refactored the code a bit. Re-added the deprecated chains with 0 tvl, as if we remove them, past tvl history for those chains will vanish from the UI
> 
> Also, added a new sub-listing for CLAMM product, not all tokens are in Uni pool but some are in options market? I added the code but unsure if I was double counting so commented it out for now.
> 
> Can you go through my changes and see if it is okay? then I will merge and list CLAMM as new product. Oh, we cant cache the response because if the graph is stale/unreachable, we will end up returning old data.

Hey, some points below:

- The SSOV refactor looks good, although this will simply calculate the token balances of the SSOV contracts.
- For the CLAMM product how would it appear on your site since its a sub listing, CLAMM is part of Dopex's V2 release and SSOV eventually in the next few months will get deprecated as CLAMM introduces newer option markets.
- For CLAMM when an option is purchased the tokens are moved into the options market to act as collateral for the option purchased so yes all tokens are not at UNI-V3.
- What does the doublecounted parameter mean?

**Comment by g1nt0ki** [comment]
- yeah, it is a bit of a shortcut
  - it would look like aave or uniswap page, we will create a parent listing for dopex: https://defillama.com/protocol/aave
  - okay
  - it is a flag we use for chain tvl calculation, here, the tokens users deposit are counted towards both uniswap & dopex tvl, if doublecount flag is not enabled, CLAMM tvl wont count towards arbitrum tvl
image

**Comment by witherblock** [comment]
> * yeah, it is a bit of a shortcut
> 
>     * it would look like aave or uniswap page, we will create a parent listing for dopex: https://defillama.com/protocol/aave
> 
>     * okay
> 
>     * it is a flag we use for chain tvl calculation, here, the tokens users deposit are counted towards both uniswap & dopex tvl, if doublecount flag is not enabled, CLAMM tvl wont count towards arbitrum tvl
>       image

Looks good to me then!

**Pull request merged**
