### PR TITLE
feat: added thala vethl tvl

### PR DESCRIPTION
**Pull request by LawsonGraham**
adding a new tvl metric for Thala - we track the amount of THL vested at some given timestamp, and add this up as the tvl of veTHL. This can be added directly into the Thala tab on UI!

**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/thala-vethl exports TVL: 
        
 
 
    aptos                     3.11 M
    
    total                    3.11 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
hi @LawsonGraham thanks for the PR, but can update the code to compute the locked value on chain? also, this can be added under 'staking' to one of the existing thala adapters instead of a new section: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by 0xl4ws** [comment]
> hi @LawsonGraham thanks for the PR, but can update the code to compute the locked value on chain? also, this can be added under 'staking' to one of the existing thala adapters instead of a new section: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

spoke with one of the mods in discord (ulysses and bentura), given how veTHL is stored, it is not easy to calculate on chain (the resource data on amount staked is stored at user accounts, not easy to track / fetch), and so we rely on indexer to get this data. They mentioned that this is ok. 

For the staking section/organization: currently we create an adapter for different aspects of the protocol (`move-dollar`, `thalaswap`, `thala-lsd`)... so we don't have an umbrella 'adapter'. How should we proceed given this? It kind of applies to multiple of these different adapters so it doesn't make sense to add to one arbitrarily if that makes sense. lmk!

**Comment by 0xl4ws** [comment]
> > hi @LawsonGraham thanks for the PR, but can update the code to compute the locked value on chain? also, this can be added under 'staking' to one of the existing thala adapters instead of a new section: https://docs.llama.fi/list-your-project/what-to-include-as-tvl
> 
> spoke with one of the mods in discord (ulysses and bentura), given how veTHL is stored, it is not easy to calculate on chain (the resource data on amount staked is stored at user accounts, not easy to track / fetch), and so we rely on indexer to get this data. They mentioned that this is ok.
> 
> For the staking section/organization: currently we create an adapter for different aspects of the protocol (`move-dollar`, `thalaswap`, `thala-lsd`)... so we don't have an umbrella 'adapter'. How should we proceed given this? It kind of applies to multiple of these different adapters so it doesn't make sense to add to one arbitrarily if that makes sense. lmk!

also, we can move it to the staking field of another adapter, but we would like to support timetravel for `veTHL`, however the other adapters don't support this... can this be configured to just the staking field? Or how is best to handle this

**Comment by llamatester** [comment]
The adapter at projects/thala-vethl exports TVL: 
        
 
 
    aptos-staking             3.07 M
    staking                   3.07 M
    aptos                     0
    
    total                    0

**Comment by g1nt0ki** [comment]
both are good points, it will show up a new sub listing now

**Pull request merged**
