### PR TITLE
Adding ArchiFinance on arbitrum chain to defillama adapters

### PR DESCRIPTION
**Pull request by ArchiFinance**
Twitter Link: https://twitter.com/archi_fi
List of audit links if any: https://certificate.quantstamp.com/full/archi-finance/abb48b19-672a-4390-bf11-59c485978d61/index.html
Website Link: https://archi.finance/
Current TVL: $2.54M
Chain: Arbitrum
Coingecko ID: NO
Coinmarketcap ID: NO
Short Description (to be shown on DefiLlama): Archi Finance is composable leveraged yield farming protocol. It has two sides to it: passive liquidity providers who earns low risk interests by supplying single-asset liquidity; and degen farmers who borrow those assets to achieve a higher APY. GMX will be the platform Archi integrated in v1.
Token address and ticker if any: No
Category (full list at https://defillama.com/categories): https://defillama.com/protocols/Leveraged%20Farming
Oracle used (Chainlink/Band/API3/TWAP or any other that you are using): Chainlink & GMX
forkedFrom: No
methodology: The TVL of ArchiFinance is calculated by adding the total liquidity and borrowing amount.
Logo:
Logo_Black
Logo_White

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/archi-finance exports TVL: 
        
 
 
    arbitrum                  2.53 M
    
    total                    2.53 M

**Comment by llamatester** [comment]
The adapter at projects/archi-finance exports TVL: 
        
 
 
    arbitrum                  1.29 M
    
    total                    1.29 M

**Comment by g1nt0ki** [comment]
@ArchiFinance thanks for the PR, am I doing some thing wrong? wne I count the balances on the contract, I am getting almost only half the tvl

**Comment by ArchiFinance** [comment]
> 

emm, I retest index.js, the result is 

➜ node test.js projects/archi-finance/index.js
--- arbitrum ---
USDT                      2.54 M
Total: 2.54 M

--- tvl ---
USDT                      2.54 M
Total: 2.54 M

------ TVL ------
arbitrum                  2.54 M

total                    2.54 M

**Comment by ArchiFinance** [comment]
@g1nt0ki I see that you have modified the index. js code. Let me test and take a look.

**Comment by g1nt0ki** [comment]
maybe you are also including borrowed amounts in tvl?

**Comment by ArchiFinance** [comment]
> maybe you are also including borrowed amounts in tvl?

yep

**Comment by g1nt0ki** [comment]
sorry, no. You cant include borrowed amount as tvl.

**Comment by ArchiFinance** [comment]
@g1nt0ki I found that calculating TVL in this way is incorrect for our platform, because unwrapLPs.js simply queries the contract balance, which is incorrect for our platform. I will re-examine and adjust the code accordingly.

**Comment by g1nt0ki** [comment]
> @g1nt0ki I found that calculating TVL this way is incorrect for our platform because unwrapLPs.js only queries the contract balance, which is incorrect for our platform as we also have vsTokens that are not being accounted for. Additionally, there are two executors, which are missing in the code you adjusted. I will re-examine the code and make some adjustments.

the vsTokens are minted by your project right? if so, we cant include it in your tvl, same as cTokens not included in compound tvl. What are the executors? are they smart contracts part of the project holding some tvl?

**Pull request closed without merging**
