### PR TITLE
Added Stakee

### PR DESCRIPTION
**Pull request by kirillmelcin**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama): 
Stakee

##### Website Link: 
https://stakee.org/

##### Logo (High resolution, will be shown with rounded borders): 
https://raw.githubusercontent.com/kirillmelcin/stakee-metadata/main/img/StakeeV3.png

##### Current TVL: 
1,976,418 TON

##### Chain: 
TON

##### Short Description (to be shown on DefiLlama):
Earn TON with best APY at most profitable staking service.

##### Token address and ticker if any:
EQCqC6EhRJ_tpWngKxL6dV0k6DSnRUrs9GSVkLbfdCqsj6TE

##### Category (full list at https://defillama.com/categories) *Please choose only one: 
Liquid Staking

##### methodology (what is being counted as tvl, how is tvl being calculated):
TON locked in the smart contract and sent to the validators to participate in rounds.

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bemo exports TVL: 
        
 
 
    ton                       10.28 M
    
    total                    10.28 M

**Comment by llamatester** [comment]
The adapter at projects/cockfightsgame exports TVL: 
        
 
 
    ton                       225.6734473862
    
    total                    225.6734473862

**Comment by llamatester** [comment]
Error while running adapter at projects/daolama: 
        
 
  
    
    
    Error: Failed to get https://tonapi.io/v2/accounts/EQAwsDboFl_iGuaflNn5959HOamenkvQEQDwakO55CY2SGB8/jettons?currencies=usd
    Truncated error stack:
    
        at get (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/http.js:32:11)
        at async sumTokensAccount (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/ton.js:15:24)
        at async Promise.all (index 0)
        at async sumTokens (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/ton.js:30:3)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:63:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:159:9
        at async Promise.all (index 0)
        at async Promise.all (index 3)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:204:3

**Comment by g1nt0ki** [comment]
@kirillmelcin thanks for the PR

**Pull request merged**
