### PR TITLE
add OliveCash

### PR DESCRIPTION
**Pull request by olive-rose**
##### Twitter Link:

https://twitter.com/OliveCashBsc

##### Website Link:
https://avax.olive.cash

##### Contact Email:
oliver.rose.bsc@gmail.com

##### Current TVL:
4.5M

##### Chain:
Avalanche

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
in progress

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
in progress

##### Description/bio (to be shown on DefiLlama):
OliveCash is a cross chain Yield Farming project running on Binance Smart Chain Avalanche chain.

##### Token address and ticker if any:
0x617724974218A18769020A70162165A539c07E8a
Olive

##### Category (Yield/Dexes/Lending/Minting):
Yield  & DEX

##### [Optional] ETH addresss (to receive a LlamaPunk):
0xbAd35DAee9e3ad5b784907a91ef6e7d775351c46

### CODE REVIEW

**Comment by 0xngmi** [comment]
Thanks for submitting! Just checked the subgraph you use on the PR and the `uniswapFactory` entity doesn't seem to exist on it. Tried changing it to `pangolinFactory` and I'm getting that the `totalLiquidityUSD` of the factory is only 100k, so something seems to be wrong.

**Comment by olive-rose** [comment]
@0xngmi thnx for suggestions. plz check my updates

**Comment by 0xngmi** [comment]
Listed!

**Comment by olive-rose** [comment]
@0xngmi thnx!
when I can see OliveCash on the site?

**Comment by olive-rose** [comment]
https://olive.cash/images/olive256.png

@0xngmi  could you plz update our logo on site

**Comment by 0xngmi** [comment]
>  could you plz update our logo on site

Done (going through CI)

> when I can see OliveCash on the site?

After I list it takes until the next hourly update for it to show up on the site

**Comment by 0xngmi** [comment]
I also made some small changes to the adapter as it wouldn't work otherwise, these shouldn't affect the TVL

**Comment by 0xngmi** [comment]
Sent [llamapunk #1](https://opensea.io/assets/0x495f947276749ce646f68ac8c248420045cb7b5e/51396440632719600673961636451910493832954413281301989130995708880140252479489). Thanks for the adapter!

**Pull request merged**
