### PR TITLE
Astra-dao

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/astra-dao exports TVL: 
        
 
 
    ethereum-staking          1.82 M
    ethereum-pool2            21.50 k
    ethereum                  262.29 k
    staking                   1.82 M
    pool2                     21.50 k
    
    total                    262.29 k

**Comment by g1nt0ki** [comment]
@ayush-tm sorry for the late reply, the numbers dont match? 

``` 
--- ethereum-staking ---
ASTRA                     1.94 M
Total: 1.94 M 

--- ethereum ---
USDT                      213.88 k
USDC                      49.80 k
Total: 263.68 k 

--- ethereum-pool2 ---
ASTRA                     15.35 k
WETH                      7.02 k
Total: 22.37 k 

--- staking ---
ASTRA                     1.94 M
Total: 1.94 M 

--- tvl ---
USDT                      213.88 k
USDC                      49.80 k
Total: 263.68 k 

--- pool2 ---
ASTRA                     15.35 k
WETH                      7.02 k
Total: 22.37 k 

------ TVL ------
ethereum-staking          1.94 M
ethereum                  263.68 k
ethereum-pool2            22.37 k
staking                   1.94 M
pool2                     22.37 k

total                    263.68 k 

``` 


Can we do it over messages/comments here. I dont take calls even from my own team. Reason why I created staking and pool2: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by ayush-tm** [comment]
It was not displaying the staking and pool values on the website, but I saw that it was optional for display for the users. So, it is good.
We are changing our token symbol, as an ASTRA token already exists and is listed on exchanges, and they want us to change the symbol. So what will be the procedure to replicate the change on Defillama?

**Comment by g1nt0ki** [comment]
hmm, changing symbol is bit tricky, think it depends if we are pricing the token via on chain data (from some dex), then it is taken from erc20 contract and that is immutable right? if it is pulled from coingecko, you can change it there and (I think) it is auto updated in our system to match coingecko symbol

**Comment by ayush-tm** [comment]
The ERC20 contract is upgradeable, and we will also change the symbol there. Also, we will be updating it on Coingecko. So, it shouldn't be an issue, right?

**Pull request merged**
