### PR TITLE
feat: add starfish-finance

### PR DESCRIPTION
**Pull request by europa-starfish**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Twitter Link:
https://twitter.com/Starfish_Fi

##### Website Link:
https://app.starfish.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
SEAN-token-icon

##### Current TVL:
127524.4000357312

##### Chain:
Ethereum, Astar

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
https://www.coingecko.com/en/coins/starfish-finance

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
https://coinmarketcap.com/currencies/starfish-finance/

##### Short Description (to be shown on DefiLlama):
Starfish Finance is incubated by the Astar Network program. We are building the next generation multi-chain DeFi x NFT-Fi headquarters. Through gamification of user experience, Starfish Finance offers multi-asset swap, $DOT liquid staking and NFT-Fi on top of an enhanced Balancer V2 model to deepen the liquidity of crypto or NFT trading and financing.

##### Token address and ticker if any:
astar: 0xEe8138B3bd03905cF84aFE10cCD0dCcb820eE08E
eth: 0xA719CB79Af39A9C10eDA2755E0938bCE35e9DE24

Token Ticker: SEAN

##### Category (full list at https://defillama.com/categories) *Please choose only one:
DeFi

##### methodology (what is being counted as tvl, how is tvl being calculated):
Protocol total liquidity + token liquidity on CEX and Ethereum DEX

### CODE REVIEW

**Comment by g1nt0ki** [comment]
I am seeing an option to stake/vest on your site, no other option is available, we cant count  liquidity provided dex/cex that are  not part of your protocol

**Comment by 0xknon** [comment]
@g1nt0ki Thank you for the comment.
No problem. Our API only show TVL that are part of our protocol.

Please check this API:
https://api.starfish.finance/v1/starfish/tvl

**Comment by g1nt0ki** [comment]
@0xknon the api spits out a number but how is it computed? what is included there?

**Comment by europa-starfish** [comment]
Currently, only Sean Staking is computed. 
Later on, we will have our own pool and farm. After that, we will add our pool TVL to the number.

**Pull request closed without merging**
