### PR TITLE
Update Satoshi-Protocol (BEVM) wstBTC tvl

### PR DESCRIPTION
**Pull request by imfeng**
**Update:**
- Adding wstBTC asset as user collateral.

wstBTC contract address: https://scan-mainnet.bevm.io/address/0x2967E7Bb9DaA5711Ac332cAF874BD47ef99B3820
wstBTC price in CoinGecko: https://www.coingecko.com/en/coins/wrapped-stbtc

**Question**:
CoinGecko has already listed wstBTC and it has a price, but when I run `node test.js projects/satoshi-protocol`
although I retrieve the amount of wstBTC, the TVL does not increase. What should I do?

image

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/satoshi-protocol exports TVL: 
        
 
 
    bevm                      799.76 k
    
    total                    799.76 k

**Comment by g1nt0ki** [comment]
@imfeng thanks for the update

**Comment by llamatester** [comment]
The adapter at projects/satoshi-protocol exports TVL: 
        
 
 
    bevm                      795.00 k
    
    total                    795.00 k

**Comment by imfeng** [comment]
Hi @g1nt0ki 
The price for wstBTC is available on CoinGecko, but DeFiLlama isn't using it, so our TVL is missing the value of this asset. How can we incorporate this price?

**Comment by g1nt0ki** [comment]
> Hi @g1nt0ki The price for wstBTC is available on CoinGecko, but DeFiLlama isn't using it, so our TVL is missing the value of this asset. How can we incorporate this price?

can you share coingecko listing details for this?

**Comment by imfeng** [comment]
> > Hi @g1nt0ki The price for wstBTC is available on CoinGecko, but DeFiLlama isn't using it, so our TVL is missing the value of this asset. How can we incorporate this price?
> 
> can you share coingecko listing details for this?

wstBTC contract address: https://scan-mainnet.bevm.io/address/0x2967E7Bb9DaA5711Ac332cAF874BD47ef99B3820
wstBTC price in CoinGecko: https://www.coingecko.com/en/coins/wrapped-stbtc

**Comment by imfeng** [comment]
Hi @g1nt0ki Is there anything information else I need to provide?

**Comment by g1nt0ki** [comment]
@imfeng sorry for the late reply, I have fixed it now

**Comment by imfeng** [comment]
@g1nt0ki thank u very much

**Comment by imfeng** [comment]
@g1nt0ki 
Hi, starting from yesterday, the TVL has suddenly decreased by the value of wstBTC. Could you please check if there is any issue ??
Is there anything I can assist with ??

**Comment by g1nt0ki** [comment]
issue is, we rely on coingecko for price and coingecko is no longer returning price: https://www.coingecko.com/en/coins/wrapped-stbtc

**Pull request merged**
