### PR TITLE
Aeria

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/aeria exports TVL: 
        
 
 
    base                      3.0029999999999997
    
    total                    3.0029999999999997

**Comment by medvi** [comment]
@g1nt0ki Hello!

I got the TVL calculation mixed up a bit. Money from the vaults goes to the strategy address after the start of the epoch. Therefore, we need to call the `totalSupply()` method without parameters. 

Can you please help me fix this?

**Comment by medvi** [comment]
@g1nt0ki 🙏🙏🙏

**Comment by g1nt0ki** [comment]
hi @medvi , this looks like a EOA, why are the funds moved there? https://basescan.org/address/0x8c8ba29f177cdec445f4b5451b57946268d044fa#tokentxns shouldnt they be kept in the vaults?

**Comment by g1nt0ki** [comment]
*I went through your docs, you dont lend funds to the MM right?

**Comment by g1nt0ki** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters/pull/7452

**Comment by medvi** [comment]
Right now this is simple implementation aka [Spin Vaults](https://vault.spin.fi/vaults/near-call-1) but different strategy. Due to the complexity of the strategy currently there is not possibility to implement this strategy fully on-chain. Of course we warn our users about it.

But we will implement fully on-chain solution later.

**Comment by medvi** [comment]
Thank you a lot for your PR

**Comment by medvi** [comment]
> > Right now this is simple implementation aka [Spin Vaults](https://vault.spin.fi/vaults/near-call-1) on Near but different strategy. Due to the complexity of the strategy currently there is no possibility to implement this strategy fully on-chain right now. Of course we warn our users about it.
> > But we will implement fully on-chain solution later.
> 
> so, it is in the team wallet but EOA?

Correct

**Comment by g1nt0ki** [comment]
> > > Right now this is simple implementation aka [Spin Vaults](https://vault.spin.fi/vaults/near-call-1) on Near but different strategy. Due to the complexity of the strategy currently there is no possibility to implement this strategy fully on-chain right now. Of course we warn our users about it.
> > > But we will implement fully on-chain solution later.
> > 
> > 
> > so, it is in the team wallet but EOA?
> 
> Correct

can you move it to a multisig? and I can add the multisig, and I can include that multisig value in overall tvl. Sorry, we have a policy of not counting tvl in EOA

**Comment by medvi** [comment]
Ok, got it

**Pull request merged**
