### PR TITLE
change TONCO TVL calculation

### PR DESCRIPTION
**Pull request by lilchizh**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/tonco exports TVL: 
        
 
 
    ton                       1.31 M
    
    total                    1.31 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
hi, thanks for the PR but I dont understand the changes, can you explain why make this change, I do see part of the issue, it is CLMM dex right? the code treats it like classic v2 amm

**Comment by lilchizh** [comment]
> hi, thanks for the PR but I dont understand the changes, can you explain why make this change, I do see part of the issue, it is CLMM dex right? the code treats it like classic v2 amm

Hi! 

Yes, we are CLAMM DEX, so right now it isn't the most accurate way to calculate TVL. 

Also, we would like to fetch data straight from the blockchain to make it more stable ☺️

**Comment by g1nt0ki** [comment]
@lilchizh thanks for the update, I should have caught the bug earlier

**Pull request merged**
