### PR TITLE
add Nimbora yield-aggregator adapter

### PR DESCRIPTION
**Pull request by 0xSacha**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

Name (to be shown on DefiLlama):
Nimbora

Twitter Link:
https://twitter.com/Nimbora_

List of audit links if any:
No

Website Link:
https://www.nimbora.io/

Logo (High resolution, will be shown with rounded borders):
logo

Current TVL:
550K $ (in STRK)

Treasury Addresses (if the protocol has treasury)
No

Chain:
Starknet

Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed):

Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed):

Short Description (to be shown on DefiLlama):

Maximize your returns in the Starknet ecosystem with Nimbora Yield Aggregator! Automatically allocate funds to the best strategies for optimal performance.

Token address and ticker if any:

Category (full list at https://defillama.com/categories) *Please choose only one:
[Yield](https://defillama.com/protocols/Yield)

Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):

Implementation Details: Briefly describe how the oracle is integrated into your project:

Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
https://docs.nimbora.io/

forkedFrom (Does your project originate from another project): Yearn V3

methodology (what is being counted as tvl, how is tvl being calculated):
Computed by summing the total assets held by each vault aggregator (idle + debt).

Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/0xSpaceShard

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/nimbora-yield-aggregator: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'flat')
    Truncated error stack:
        at CallData.parse (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/starknet/dist/index.js:1924:39)
        at parseOutput (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/starknet.js:38:49)
        at call (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/starknet.js:57:10)

**Comment by llamatester** [comment]
Error while running adapter at projects/nimbora-yield: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'flat')
    Truncated error stack:
        at CallData.parse (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/starknet/dist/index.js:1924:39)
        at parseOutput (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/starknet.js:38:49)
        at call (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/starknet.js:57:10)

**Comment by llamatester** [comment]
Error while running adapter at projects/nimbora-yield: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'flat')
    Truncated error stack:
        at CallData.parse (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/starknet/dist/index.js:1924:39)
        at parseOutput (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/starknet.js:38:49)
        at call (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/starknet.js:57:10)

**Comment by llamatester** [comment]
The adapter at projects/nimbora-yield-aggregator exports TVL: 
        
 
 
    starknet                  527.85 k
    
    total                    527.85 k

**Comment by g1nt0ki** [comment]
hi @0xSacha why add a new adapter instead of including this STRK vault as part of existing adapter: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/nimbora-yield/index.js#L20

**Comment by 0xSacha** [comment]
> hi @0xSacha why add a new adapter instead of including this STRK vault as part of existing adapter: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/nimbora-yield/index.js#L20

Hey @g1nt0ki , it is a different contract logic. The STRK vault is a yield aggregator living on Starknet, while the vaults in https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/nimbora-yield/index.js#L20 are tokenized cross-chain strategies, like LP on L1, and report profits periodically on L2.

**Pull request merged**
