### PR TITLE
add ohmycrypt on Base

### PR DESCRIPTION
**Pull request by OhMyCrypt**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
OhMyCrypt

##### Twitter Link:
https://twitter.com/OhMyCrypt_Off

##### List of audit links if any:
N/A

##### Website Link:
https://ohmycrypt.com/

##### Logo (High resolution, will be shown with rounded borders):
[https://github.com/OhMyCrypt/Brand-kit/blob/main/Logo.png](url)
Logo

##### Current TVL:
0 (launching 26 september, 12:00 CET)

##### Treasury Addresses (if the protocol has treasury)
0x411e216E5C7A4836BAB0308e35D843Ef49A225c4

##### Chain:
Base

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

##### Short Description (to be shown on DefiLlama):
Limit-Order Orderbook DEX aiming to reunite the best of CEXs and DEXs. 

##### Token address and ticker if any:
N/A (Token airdrop on January 7, 2024)

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
N/A

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
The TVL is calculated by taking in consideration the balance of each market contract

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/OhMyCrypt exports TVL: 
        
 
 
    base                      0
    
    total                    0

**Comment by g1nt0ki** [comment]
thanks for the PR, I will leave it open till project is live and has some tvl

**Comment by llamatester** [comment]
The adapter at projects/OhMyCrypt exports TVL: 
        
 
 
    base                      0
    
    total                    0

**Comment by Define101** [comment]
@OhMyCrypt please inform us once the project has some TVL

**Pull request merged**
