### PR TITLE
Create tbac.js

### PR DESCRIPTION
**Pull request by debo24**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
TBAC

##### Chain:
Ethereum

##### Token address and ticker if any:
0xf8b7db3268cc0bd9c61fbfbfde963a3727ba154d
https://etherscan.io/dex/uniswapv3/0xf8b7db3268cc0bd9c61fbfbfde963a3727ba154d

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Liquid Staking

### CODE REVIEW

**Comment by debo24** [comment]
TBAC Added

**Comment by g1nt0ki** [comment]
@debo24 sorry, but this PR looks bit suspicious. Can you provide some additional details about the project? and some proof of ETH deposited for the tokens minted

**Comment by debo24** [comment]
> @debo24 sorry, but this PR looks bit suspicious. Can you provide some additional details about the project? and some proof of ETH deposited for the tokens minted

Sure I will add more links for better references.

**Comment by blockaura-blockchain** [comment]
Hello @g1nt0ki ,

Greeting from BlockAura Team,

I would like to provide all the information for you to clarify details about our project - 

BlockAura Token was launched on BSC Network on 19th September 2022 with the below contract address - https://bscscan.com/token/0x2326c7395d02a8c89a9d7a0b0c1cf159d49ce51c

Initially the community created was on Binance Smart Chain trading with Pancake Swap and then we migrated to the Ethereum network with an upgrade to allow our community to trade on Uniswap where a new smart contract was created and along with it we had created a bridge for Polygon collaborating with the Polygon team to support on their Polygon Bridge.

Below you can find the contract details - 

Ethereum: https://etherscan.io/token/0x85800a01809b9a778c78d5ea70bddddb166da65c
Polygon: https://polygonscan.com/token/0x94f98d16c6ba5c2f649d6d7efb9767b14b0f325b

We are also listed on CoinMarketCap, CoinGeko, Nomics below you can find the links - 

CoinMarketCap: https://coinmarketcap.com/currencies/blockaura/
CoinGeko: https://www.coingecko.com/en/coins/blockaura
Nomics: https://nomics.com/assets/tbac-blockaura

The bridge we created in collaboration with Polygon team was a success to allow a boost in the trading options available for our community and expand our community in a better way.

We also got our token audited with FairyProof below you can find the link for our TBAC 3.0: 
https://fairyproof.com/report/BlockAura

We have participated in multiple Blockchain Events in the last few years, where the founder of the Project Mr. Firoz was a speaker representing the project - 
Diamond Sponsor - https://cryptoexpodubai.com/#Sponsors
Silver Sponsor - https://blockchainweek.com.sg/
Robot Sponsor - https://tresconglobal.com/conferences/blockchain/dubai-mar22/#sponsors

BlockAura is also a member of the Singapore Blockchain Association since July 2022.

Currently, our intention to be listed on Defillama is to get qualified for CBridge and complete the requirements to allow our users to use the bridge and move the token using the cross bridge and create a better trading opportunity on Swap Exchanges to trade with widespread options and liquidity.

Our community was happy to have multiple chain options allowing them to trade on their choice of blockchain and Swap Exchanges. The reason we want to be listed on Cbridge is to a single application allowing them to use to bridge and move their token with ease besides using multiple applications and complicating their process.

We have also got the smart contract BlockAura 3.1 (TBAC) audited by fairyproof - https://fairyproof.com/doc/BlockAura-Token3.1-Audit-Report-100522.pdf

I believe the above information will allow you to give transparency on the project and accept our merge request to further proceed with our process to get listed on Cbridge.

**Comment by g1nt0ki** [comment]
@blockaura-blockchain @debo24 thanks for detailed info. What alarmed me was, you are counting TBAC supply in Ethereum and multiplying it with ether price and calling it your tvl

 What defi product are you offering?

**Comment by nitinjags** [comment]
Hello @g1nt0ki ,

'Updated TBAC' with a new commit - "a1ba34ad16f701a9ad34729139be8fb719211382", to resolve the issue you mentioned above for showing the proper "TVL" value.
I proposed the above commit but was unable to make a pull request as we are lagging with our first pull request.
In this request, we calculate the "TBAC" value according to the liquidations in Uniswap.

To clarify BlockAura (TBAC) is a payments project, where the token is the utility for the blockchain of BlockAura to be launched in March 2023.

Request you to kindly accept our merge request.

**Comment by g1nt0ki** [comment]
@nitinjags are you counting the uniswap liquidity of your token as your tvl? sorry, that tvl belongs to uniswap. Documentation of what is included in tvl: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by blockaura-blockchain** [comment]
Hi @g1nt0ki 
I believe there is confusion over here and would like to clarify the value TVL did take from UniSwap to get the value as we are only available on Swap Exchange for trading where the liquidity pool is been created which would allow us to derive the value for TVL.

I read through the documentation you have sent "Pool2: would be the right category as we are using Uniswap protocol and governance to create our TVL.

I would suggest if we are mistaken over here then kindly explain to us with an example we need to use to create the code for TBAC to be added on Defillama.


Many Thanks,
BlockAura Team.

**Comment by realdealshaman** [comment]
@blockaura-blockchain Hi, qq, how do users interact with your project? Is it only possible to buy TBAC and deposit it to the liquidity pools? If this is the case than it doesn't have its own TVL

**Comment by blockaura-blockchain** [comment]
Hi @realdealshaman ,

Yes, you are right the only way users can buy or trade with TBAC is through the AMM swap exchange we are listed on.

- Uniswap
- MDEX
- Sushiswap

The above three DEX are where any trader can participate in the project.

Looking forward for you to help us further. 


Many Thanks,
BlockAura Team.

**Comment by g1nt0ki** [comment]
@blockaura-blockchain sorry, but if you dont have user tokens locked in your protocol, we cant list you

**Comment by blockaura-blockchain** [comment]
Hello @g1nt0ki ,

We do not have our own protocol but as mentioned above we use UniSwap and other DEX. 

The Cbridge application form mentioned us to be listed on Defillama so we sent a pull request to be listed with you.

Looking forward to your help.


Many Thanks,
BlockAura Team

**Comment by g1nt0ki** [comment]
@blockaura-blockchain I am sorry, we can not help you with this. I am closing the PR.

**Pull request closed without merging**
