### PR TITLE
feat: Add TruFin's TruStake APTOS vault TVL calculation

### PR DESCRIPTION
**Pull request by yash-trufin**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

## TruStake APTOS

Note that this is a listing under the parent protocol : TruFin Protocol

The defillama-server repo will have a data entry that looks something like – 
```
  {
    id: "<id number>",
    name: "TruStake APTOS",
    address: null,
    symbol: "-",
    url: "https://app.trufin.io/trustake/apt",
    description: "The TruStake APTOS vault provides access to APT staking on the Aptos network",
    chain: "Aptos",
    logo: `${baseIconsUrl}/trustake-apt.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Liquid Staking",
    chains: ["Aptos"],
    module: "trufin-trustake-aptos/index.js",
    twitter: "TruFinProtocol",
    forkedFrom: [],
    oracles: [],
    audit_links: ["https://trufin.gitbook.io/docs/developers/security-and-audits#security-audits"],
    parentProtocol: "parent#trufin-protocol",
    listedAt: <timestamp>
  },
```

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/trufin-trustake-aptos exports TVL: 
        
 
 
    aptos                     241
    
    total                    240.96

**Comment by llamatester** [comment]
The adapter at projects/trufin-trustake exports TVL: 
        
 
 
    ethereum                  36.91 M
    aptos                     240
    
    total                    36.91 M

**Comment by yash-trufin** [comment]
@g1nt0ki 

This is a separate liquid staking vault. I was hoping to see the TruFin listings come up
1. TruFin Protocol – sum of trustake matic and trustake aptos 
2. TruStake MATIC – matic lst
3. TruStake APTOS – aptos lst
4. TruFin Legacy Vaults – the deprecated staker

What will the listings look like with your changes?

**Comment by g1nt0ki** [comment]
hi @yash-trufin I merged it because it is a similar product

**Comment by g1nt0ki** [comment]
https://defillama.com/protocol/trustake#information

**Pull request merged**
