### PR TITLE
added onavax dex adapter

### PR DESCRIPTION
**Pull request by fgsilviu**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/onavax exports TVL: 
        
 
 
    avax                      407.10 k
    
    total                    407.10 k

**Comment by g1nt0ki** [comment]
@fgsilviu sorry, I merged it too quickly, can you fill the form in the PR, else it would time to list it.

**Comment by fgsilviu** [comment]
@g1nt0ki I've updated the form, is everything alright on your end?

**Comment by Define101** [comment]
Yes , thank you so much

**Pull request merged**
