### PR TITLE
Block fixes

### PR DESCRIPTION
**Pull request by waynebruce0x**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/api3/index.js exports TVL: 
        
 
 
    ethereum                  0
    ethereum-staking          198.20 M
    staking                   198.20 M
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/asgardfinance/index.js exports TVL: 
        
 
 
    ethereum-staking          56.35 k
    ethereum                  2.18692284832544e-10
    staking                   56.35 k
    
    total                    2.18692284832544e-10

**Comment by llamatester** [comment]
The adapter at projects/axial/index.js exports TVL: 
        
 
 
    avalanche-pool2           341.63 k
    avalanche                 12.85 M
    pool2                     341.63 k
    
    total                    12.85 M

**Comment by llamatester** [comment]
The adapter at projects/baker-guild-finance/index.js exports TVL: 
        
 
 
    fantom-staking            3.89 k
    fantom-pool2              1.92 k
    fantom                    11.87 k
    staking                   3.89 k
    pool2                     1.92 k
    
    total                    11.87 k

**Comment by llamatester** [comment]
The adapter at projects/chaotic.js exports TVL: 
        
 
 
    moonriver                 183.59 k
    
    total                    183.59 k

**Comment by llamatester** [comment]
Error while running adapter at projects/chickenswap/index.js: 
        
 
  
    
    
    ReferenceError: Cannot access 'errorString' before initialization
        at checkExportKeys (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:263:7)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:109:3
        at Object.<anonymous> (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:228:3)
        at Module._compile (node:internal/modules/cjs/loader:1103:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
        at Module.load (node:internal/modules/cjs/loader:981:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
        at node:internal/main/run_main_module:17:47

**Comment by llamatester** [comment]
The adapter at projects/api3/index.js exports TVL: 
        
 
 
    ethereum                  0
    ethereum-staking          198.56 M
    staking                   198.56 M
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/asgardfinance/index.js exports TVL: 
        
 
 
    ethereum-staking          56.35 k
    ethereum                  2.1912835244299997e-10
    staking                   56.35 k
    
    total                    2.1912835244299997e-10

**Comment by llamatester** [comment]
The adapter at projects/axial/index.js exports TVL: 
        
 
 
    avalanche-pool2           348.67 k
    avalanche                 12.83 M
    pool2                     348.67 k
    
    total                    12.83 M

**Comment by llamatester** [comment]
The adapter at projects/baker-guild-finance/index.js exports TVL: 
        
 
 
    fantom-staking            3.90 k
    fantom-pool2              1.92 k
    fantom                    11.87 k
    staking                   3.90 k
    pool2                     1.92 k
    
    total                    11.87 k

**Comment by llamatester** [comment]
The adapter at projects/chaotic.js exports TVL: 
        
 
 
    moonriver                 186.11 k
    
    total                    186.11 k

**Comment by llamatester** [comment]
The adapter at projects/chickenswap/index.js exports TVL: 
        
 
 
    ethereum-staking          8.92 k
    ethereum-pool2            2.17 k
    ethereum                  338.65 k
    staking                   8.92 k
    pool2                     2.17 k
    
    total                    338.65 k

**Comment by llamatester** [comment]
Error while running adapter at projects/coconuts-finance/index.js: 
        
 
  
    
    
    Error: Request failed with status code 503
        at createError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/axios/lib/core/createError.js:16:15)
        at settle (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/axios/lib/core/settle.js:17:12)
        at IncomingMessage.handleStreamEnd (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/axios/lib/adapters/http.js:322:11)
        at IncomingMessage.emit (node:events:532:35)
        at endReadableNT (node:internal/streams/readable:1346:12)
        at processTicksAndRejections (node:internal/process/task_queues:83:21) {
      config: {
        transitional: {
          silentJSONParsing: true,
          forcedJSONParsing: true,
          clarifyTimeoutError: false
        },
        adapter: [Function: httpAdapter],
        transformRequest: [ [Function: transformRequest] ],
        transformResponse: [ [Function: transformResponse] ],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        maxBodyLength: -1,
        validateStatus: [Function: validateStatus],
        headers: {
          Accept: 'application/json, text/plain, */*',
          'User-Agent': 'axios/0.26.1'
        },
        method: 'get',
        url: 'https://coconutsfinance-test.herokuapp.com/api/apys?network=137',
        data: undefined
      },
      request: <ref *1> ClientRequest {
        _events: [Object: null prototype] {
          abort: [Function (anonymous)],
          aborted: [Function (anonymous)],
          connect: [Function (anonymous)],
          error: [Function (anonymous)],
          socket: [Function (anonymous)],
          timeout: [Function (anonymous)],
          prefinish: [Function: requestOnPrefinish]
        },
        _eventsCount: 7,
        _maxListeners: undefined,
        outputData: [],
        outputSize: 0,
        writable: true,
        destroyed: false,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        maxRequestsOnConnectionReached: false,
        _defaultKeepAlive: true,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        _closed: false,
        socket: TLSSocket {
          _tlsOptions: [Object],
          _secureEstablished: true,
          _securePending: false,
          _newSessionPending: false,
          _controlReleased: true,
          secureConnecting: false,
          _SNICallback: null,
          servername: 'coconutsfinance-test.herokuapp.com',
          alpnProtocol: false,
          authorized: true,
          authorizationError: null,
          encrypted: true,
          _events: [Object: null prototype],
          _eventsCount: 10,
          connecting: false,
          _hadError: false,
          _parent: null,
          _host: 'coconutsfinance-test.herokuapp.com',
          _readableState: [ReadableState],
          _maxListeners: undefined,
          _writableState: [WritableState],
          allowHalfOpen: false,
          _sockname: null,
          _pendingData: null,
          _pendingEncoding: '',
          server: undefined,
          _server: null,
          ssl: [TLSWrap],
          _requestCert: true,
          _rejectUnauthorized: true,
          parser: null,
          _httpMessage: [Circular *1],
          [Symbol(res)]: [TLSWrap],
          [Symbol(verified)]: true,
          [Symbol(pendingSession)]: null,
          [Symbol(async_id_symbol)]: 311,
          [Symbol(kHandle)]: [TLSWrap],
          [Symbol(kSetNoDelay)]: false,
          [Symbol(lastWriteQueueSize)]: 0,
          [Symbol(timeout)]: null,
          [Symbol(kBuffer)]: null,
          [Symbol(kBufferCb)]: null,
          [Symbol(kBufferGen)]: null,
          [Symbol(kCapture)]: false,
          [Symbol(kBytesRead)]: 0,
          [Symbol(kBytesWritten)]: 0,
          [Symbol(connect-options)]: [Object],
          [Symbol(RequestTimeout)]: undefined
        },
        _header: 'GET /api/apys?network=137 HTTP/1.1\r\n' +
          'Accept: application/json, text/plain, */*\r\n' +
          'User-Agent: axios/0.26.1\r\n' +
          'Host: coconutsfinance-test.herokuapp.com\r\n' +
          'Connection: close\r\n' +
          '\r\n',
        _keepAliveTimeout: 0,
        _onPendingData: [Function: nop],
        agent: Agent {
          _events: [Object: null prototype],
          _eventsCount: 2,
          _maxListeners: undefined,
          defaultPort: 443,
          protocol: 'https:',
          options: [Object: null prototype],
          requests: [Object: null prototype] {},
          sockets: [Object: null prototype],
          freeSockets: [Object: null prototype] {},
          keepAliveMsecs: 1000,
          keepAlive: false,
          maxSockets: Infinity,
          maxFreeSockets: 256,
          scheduling: 'lifo',
          maxTotalSockets: Infinity,
          totalSocketCount: 1,
          maxCachedSessions: 100,
          _sessionCache: [Object],
          [Symbol(kCapture)]: false
        },
        socketPath: undefined,
        method: 'GET',
        maxHeaderSize: undefined,
        insecureHTTPParser: undefined,
        path: '/api/apys?network=137',
        _ended: true,
        res: IncomingMessage {
          _readableState: [ReadableState],
          _events: [Object: null prototype],
          _eventsCount: 4,
          _maxListeners: undefined,
          socket: [TLSSocket],
          httpVersionMajor: 1,
          httpVersionMinor: 1,
          httpVersion: '1.1',
          complete: true,
          rawHeaders: [Array],
          rawTrailers: [],
          aborted: false,
          upgrade: false,
          url: '',
          method: null,
          statusCode: 503,
          statusMessage: 'Service Unavailable',
          client: [TLSSocket],
          _consuming: false,
          _dumped: false,
          req: [Circular *1],
          responseUrl: 'https://coconutsfinance-test.herokuapp.com/api/apys?network=137',
          redirects: [],
          [Symbol(kCapture)]: false,
          [Symbol(kHeaders)]: [Object],
          [Symbol(kHeadersCount)]: 12,
          [Symbol(kTrailers)]: null,
          [Symbol(kTrailersCount)]: 0,
          [Symbol(RequestTimeout)]: undefined
        },
        aborted: false,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        reusedSocket: false,
        host: 'coconutsfinance-test.herokuapp.com',
        protocol: 'https:',
        _redirectable: Writable {
          _writableState: [WritableState],
          _events: [Object: null prototype],
          _eventsCount: 3,
          _maxListeners: undefined,
          _options: [Object],
          _ended: true,
          _ending: true,
          _redirectCount: 0,
          _redirects: [],
          _requestBodyLength: 0,
          _requestBodyBuffers: [],
          _onNativeResponse: [Function (anonymous)],
          _currentRequest: [Circular *1],
          _currentUrl: 'https://coconutsfinance-test.herokuapp.com/api/apys?network=137',
          [Symbol(kCapture)]: false
        },
        [Symbol(kCapture)]: false,
        [Symbol(kNeedDrain)]: false,
        [Symbol(corked)]: 0,
        [Symbol(kOutHeaders)]: [Object: null prototype] {
          accept: [Array],
          'user-agent': [Array],
          host: [Array]
        }
      },
      response: {
        status: 503,
        statusText: 'Service Unavailable',
        headers: {
          connection: 'close',
          server: 'Cowboy',
          date: 'Mon, 28 Mar 2022 19:01:27 GMT',
          'content-length': '506',
          'content-type': 'text/html; charset=utf-8',
          'cache-control': 'no-cache, no-store'
        },
        config: {
          transitional: [Object],
          adapter: [Function: httpAdapter],
          transformRequest: [Array],
          transformResponse: [Array],
          timeout: 0,
          xsrfCookieName: 'XSRF-TOKEN',
          xsrfHeaderName: 'X-XSRF-TOKEN',
          maxContentLength: -1,
          maxBodyLength: -1,
          validateStatus: [Function: validateStatus],
          headers: [Object],
          method: 'get',
          url: 'https://coconutsfinance-test.herokuapp.com/api/apys?network=137',
          data: undefined
        },
        request: <ref *1> ClientRequest {
          _events: [Object: null prototype],
          _eventsCount: 7,
          _maxListeners: undefined,
          outputData: [],
          outputSize: 0,
          writable: true,
          destroyed: false,
          _last: true,
          chunkedEncoding: false,
          shouldKeepAlive: false,
          maxRequestsOnConnectionReached: false,
          _defaultKeepAlive: true,
          useChunkedEncodingByDefault: false,
          sendDate: false,
          _removedConnection: false,
          _removedContLen: false,
          _removedTE: false,
          _contentLength: 0,
          _hasBody: true,
          _trailer: '',
          finished: true,
          _headerSent: true,
          _closed: false,
          socket: [TLSSocket],
          _header: 'GET /api/apys?network=137 HTTP/1.1\r\n' +
            'Accept: application/json, text/plain, */*\r\n' +
            'User-Agent: axios/0.26.1\r\n' +
            'Host: coconutsfinance-test.herokuapp.com\r\n' +
            'Connection: close\r\n' +
            '\r\n',
          _keepAliveTimeout: 0,
          _onPendingData: [Function: nop],
          agent: [Agent],
          socketPath: undefined,
          method: 'GET',
          maxHeaderSize: undefined,
          insecureHTTPParser: undefined,
          path: '/api/apys?network=137',
          _ended: true,
          res: [IncomingMessage],
          aborted: false,
          timeoutCb: null,
          upgradeOrConnect: false,
          parser: null,
          maxHeadersCount: null,
          reusedSocket: false,
          host: 'coconutsfinance-test.herokuapp.com',
          protocol: 'https:',
          _redirectable: [Writable],
          [Symbol(kCapture)]: false,
          [Symbol(kNeedDrain)]: false,
          [Symbol(corked)]: 0,
          [Symbol(kOutHeaders)]: [Object: null prototype]
        },
        data: '<!DOCTYPE html>\n' +
          '\t<html>\n' +
          '\t  <head>\n' +
          '\t\t<meta name="viewport" content="width=device-width, initial-scale=1">\n' +
          '\t\t<meta charset="utf-8">\n' +
          '\t\t<title>Application Error</title>\n' +
          '\t\t<style media="screen">\n' +
          '\t\t  html,body,iframe {\n' +
          '\t\t\tmargin: 0;\n' +
          '\t\t\tpadding: 0;\n' +
          '\t\t  }\n' +
          '\t\t  html,body {\n' +
          '\t\t\theight: 100%;\n' +
          '\t\t\toverflow: hidden;\n' +
          '\t\t  }\n' +
          '\t\t  iframe {\n' +
          '\t\t\twidth: 100%;\n' +
          '\t\t\theight: 100%;\n' +
          '\t\t\tborder: 0;\n' +
          '\t\t  }\n' +
          '\t\t</style>\n' +
          '\t  </head>\n' +
          '\t  <body>\n' +
          '\t\t<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>\n' +
          '\t  </body>\n' +
          '\t</html>'
      },
      isAxiosError: true,
      toJSON: [Function: toJSON]
    }

**Comment by llamatester** [comment]
The adapter at projects/api3/index.js exports TVL: 
        
 
 
    ethereum                  0
    ethereum-staking          198.90 M
    staking                   198.90 M
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/axial/index.js exports TVL: 
        
 
 
    avalanche-pool2           348.67 k
    avalanche                 12.83 M
    pool2                     348.67 k
    
    total                    12.83 M

**Comment by llamatester** [comment]
The adapter at projects/baker-guild-finance/index.js exports TVL: 
        
 
 
    fantom-staking            3.90 k
    fantom                    11.87 k
    fantom-pool2              1.92 k
    staking                   3.90 k
    pool2                     1.92 k
    
    total                    11.87 k

**Comment by llamatester** [comment]
The adapter at projects/chaotic.js exports TVL: 
        
 
 
    moonriver                 185.35 k
    
    total                    185.35 k

**Comment by llamatester** [comment]
The adapter at projects/chickenswap/index.js exports TVL: 
        
 
 
    ethereum-staking          8.92 k
    ethereum-pool2            2.17 k
    ethereum                  338.65 k
    staking                   8.92 k
    pool2                     2.17 k
    
    total                    338.65 k

**Review by g1nt0ki — APPROVED** [review]

**Pull request merged**
