### PR TITLE
Revert "Revert "fix: hashmix tvl api was down last week, now back online""

### PR DESCRIPTION
**Pull request by g1nt0ki**
Reverts DefiLlama/DefiLlama-Adapters#7446

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/hashmix exports TVL: 
        
 
 
    filecoin                  1.58 M
    
    total                    1.58 M

**Comment by hashmix** [comment]
@g1nt0ki  would you please take care of this PR? The TVL api has been back online for weeks.

**Comment by g1nt0ki** [comment]
hi @hashmix I have not merged as I have not got an answer here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/7445#issuecomment-1713612329

**Comment by hashmix** [comment]
> hi @hashmix I have not merged as I have not got an answer here: [#7445 (comment)](https://github.com/DefiLlama/DefiLlama-Adapters/pull/7445#issuecomment-1713612329)

Sorry for the delayed response. We have answered the comment you mentioned.

**Pull request merged**
