### PR TITLE
add PredX project tvl on ZKLlink

### PR DESCRIPTION
**Pull request by Junpeng-Wang**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/predx exports TVL: 
        
 
 
    zklink                    2
    
    total                    1.9966713299999999

**Comment by realdealshaman** [comment]
Hey @Junpeng-Wang , why didn't you add the other chains like base, sei, and the others to the adapter?

**Comment by Junpeng-Wang** [comment]
> Hey @Junpeng-Wang , why didn't you add the other chains like base, sei, and the others to the adapter?

Sure. I will add more and create another PR. Before that, (1) shall I worry about the current failing check? (2) does the sumTokensExport function also support sei? It gives me error like "PromisePoolError: Failed to get https://sei-rest.publicnode.com/cosmos/bank/v1beta1/balances/...?pagination.limit=1000"

Thanks

**Comment by llamatester** [comment]
The adapter at projects/predx exports TVL: 
        
 
 
    zklink                    2
    
    total                    1.992033972

**Comment by g1nt0ki** [comment]
hi @Junpeng-Wang, it does support sei, think issue was, it was picking cosmos helper for sei instead of evm helper, fixing it.

**Comment by llamatester** [comment]
The adapter at projects/predx exports TVL: 
        
 
 
    zklink                    2
    
    total                    2.0159819999999997

**Comment by llamatester** [comment]
The adapter at projects/predx exports TVL: 
        
 
 
    base                      3.05 k
    btr                       1.11 k
    bsc                       12
    linea                     10
    mantle                    2
    zklink                    2
    
    total                    4.19 k

**Comment by llamatester** [comment]
The adapter at projects/predx exports TVL: 
        
 
 
    base                      3.05 k
    btr                       1.11 k
    bsc                       12
    linea                     10
    mantle                    2
    zklink                    2
    
    total                    4.19 k

**Comment by llamatester** [comment]
The adapter at projects/predx exports TVL: 
        
 
 
    base                      3.05 k
    btr                       1.11 k
    bsc                       12
    linea                     10
    zklink                    2
    mantle                    2
    
    total                    4.19 k

**Comment by Junpeng-Wang** [comment]
> hi @Junpeng-Wang, it does support sei, think issue was, it was picking cosmos helper for sei instead of evm helper, fixing it.

Thanks. I have updated the code to add all other chains we have. The sei chain has been commented out. Please let me know if any other changes are required.

**Comment by g1nt0ki** [comment]
thanks @Junpeng-Wang

**Comment by llamatester** [comment]
The adapter at projects/predx exports TVL: 
        
 
 
    base                      3.05 k
    btr                       1.10 k
    sei                       27
    bsc                       12
    linea                     10
    zklink                    2
    mantle                    2
    
    total                    4.21 k

**Pull request merged**
