### PR TITLE
updated treasury balances

### PR DESCRIPTION
**Pull request by hazelnutcloud**

### CODE REVIEW

**Comment by waynebruce0x** [comment]
is there any particular reason you've changed to thegraph? We get difficulties with thegraph adapters when subgraphs fall behind current block height, so we try to avoid it.

**Comment by hazelnutcloud** [comment]
yes we recently migrated our liquidity to beethoven and I figured trying to get all the balances in our pool through blockchain calls was a bit verbose. It would be a bit easier to maintain this way. Regarding the block height issues, I used timestamp instead of number to query the subgraph so it shouldn't be a problem.

**Comment by 0xngmi** [comment]
the problem still exists since if if it goes through it just means that we are fetching outdated values

**Comment by hazelnutcloud** [comment]
alright I've changed from subgraph query to blockchain calls. appreciate if you could review again. thanks for the guidance!

**Comment by 0xngmi** [comment]
ty, really appreciated, sorry for earlier miscommunication about whether subgraphs were ok. Now there's increasing scrutiny on fantom adapters and we have a strong preference for on-chain ones

**Pull request merged**
