### PR TITLE
Add Swim Protocol

### PR DESCRIPTION
**Pull request by swimkirito**
##### Twitter Link:
https://twitter.com/SwimProtocol

##### List of audit links if any:
https://swim.io/audits/kudelski.pdf

##### Website Link:
https://swim.io/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://swim.io/media

##### Current TVL:
16.5M

##### Chain:
Solana, Ethereum, BNB Chain

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

##### Short Description (to be shown on DefiLlama):
Swim is a multi-chain AMM for native assets, designed to make bridging as easy as possible.

##### Token address and ticker if any:
N/A

##### Category (full list at https://defillama.com/categories) *Please choose only one:
13: Cross Chain

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Pyth, CoinMarketCap

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
Swim Protocol currently has a hexapool consisting of 6 tokens total. TVL is calculated by using Pyth or CoinMarketCap to determine the price and querying the 6 Solana token account balances. Then the account balance for each of the tokens are multiplied by their respective token price and the TVL is the sum of those values.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/swim/index.js exports TVL: 
                
 
 

total                    16.80 M

**Comment by waynebruce0x** [comment]
Can you remove the try/catches and separate TVL by chain?

**Comment by swimkirito** [comment]
> Can you remove the try/catches and separate TVL by chain?

I'm assuming you were referring to having functions to calculate TVL by chain, but the final TVL would still be a sum of all of them. If not let me know and I can make the appropriate changes.

**Comment by waynebruce0x** [comment]
Yeah exactly, if you export like: 
{
  solana: {
    tvl: solanaTvl
  },
  ethereum: {
    tvl: ethTvl
  }
}

etc then we will sum them all up automatically for your total TVL

**Comment by waynebruce0x** [comment]
actually dm, I can change the exports later today for you, thanks for the changes

**Pull request merged**
