### PR TITLE
Streamflow: remove caching

### PR DESCRIPTION
**Pull request by srdjanrist**
Hi everyone.

I have updated the Streamflow adapter, removed caching. 
Since it is faster with the new API, caching doesn't seem necessary. (https://github.com/DefiLlama/DefiLlama-Adapters/pull/5590)

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/streamflow exports TVL: 
        
 
 
    solana                    160.25 k
    solana-vesting            148.02 M
    vesting                   148.02 M
    
    total                    160.25 k

**Comment by llamatester** [comment]
The adapter at projects/streamflow exports TVL: 
        
 
 
    solana-vesting            147.73 M
    solana                    159.93 k
    vesting                   147.73 M
    
    total                    159.93 k

**Comment by llamatester** [comment]
The adapter at projects/streamflow exports TVL: 
        
 
 
    solana-vesting            147.73 M
    solana                    159.93 k
    vesting                   147.73 M
    
    total                    159.93 k

**Comment by imprfekt** [comment]
lesgo! no cache 💃

**Comment by g1nt0ki** [comment]
@srdjanrist it is my fault for the confusing name, but the cache there is not the issue, it is done with run. Caching is done in our back-end, I can fix it.

Is there some way to get token breakdown here? so users can see it on the dashboard as well, think they would be interested in it.

Also, is there a git repo where you maintain the code that users can look at/verify how tvl is computed?

**Comment by andjelboskovic** [comment]
Hey g1nt0ki,

Great to hear that caching can be fixed on the back-end, let us know when that happens.

We can provide a token breakdown.

Do you have an example of an API response structure that we can mimic to provide that information?

We don't have a GitHub repo, but we could expose the dashboards that we use internally to showcase a detailed breakdown of tokens deposited per mint address, tokens processes, number of tokens, (that we fetch from the chain) + the list of token prices that we fetch via APIs on an hourly level.

Does this make sense?

**Comment by g1nt0ki** [comment]
@andjelboskovic yeah, maybe you can add a link to your dashboard in methodology filed? or we can add in description whichever one you prefer.

You can have a look at recent spl governance tvl adapter: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/spl-governance/index.js

https://defillama.com/protocol/spl-governance

**Comment by srdjanrist** [comment]
Hey, we can see that caching is not fixed on the backend so we are closing this PR.

Thank you for the info.

We'll open a new PR to change the methodology file to link to our public dashboard.

**Comment by llamatester** [comment]
The adapter at projects/streamflow exports TVL: 
        
 
 
    solana-vesting            122.50 M
    solana                    136.29 k
    vesting                   122.50 M
    
    total                    136.29 k

**Comment by g1nt0ki** [comment]
> Hey, we can see that caching is not fixed on the backend so we are closing this PR.
> 
> Thank you for the info.
> 
> We'll open a new PR to change the methodology file to link to our public dashboard.

hi @srdjanrist I left this open mainly to keep the discussion going, so you will put a new PR exposing the dasboard api (?) with token breakdown?

**Comment by srdjanrist** [comment]
Hey @g1nt0ki yes, I plan to open a PR that will include this link in methodology part: https://metabase.internal-streamflow.com/public/dashboard/fe3731c1-fbe4-4fb6-8960-515af1d6e72d

**Pull request closed without merging**
