### PR TITLE
XLink

### PR DESCRIPTION
**Pull request by fiftyeightandeight**
##### List of audit links if any: 
https://cdn.alexlab.co/pdf/ALEX_Audit_bridge_coinfabrik_202212.pdf
https://cdn.alexlab.co/pdf/ALEX_Audit_Bridge_2023-04.pdf
https://cdn.alexlab.co/pdf/ALEX_Audit_202310_Bitcoin_Oracle_and_Bridge.pdf

##### Short Description (to be shown on DefiLlama):
XLink is a crucial "Omni-chain Bitcoin Liquidity" connector within the Bitcoin ecosystem. The surge in Bitcoin Layer 2 solutions, alongside the emergence of synthetic BTC variants underline the urgent need for fungibility among these assets to prevent liquidity fragmentation.

Leveraging its unique hub-and-spoke architect, XLink stands as the foremost liquidity aggregator for all Bitcoin L2s. It integrates a cohesive liquidity pool through its aBTC, crucially bridging liquidity gaps in the increasingly diverse Bitcoin ecosystem.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Bridge

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/xlink exports TVL: 
        
 
 
    bitcoin                   9.58 M
    bsc                       2.66 M
    ethereum                  0
    
    total                    12.24 M

**Comment by llamatester** [comment]
The adapter at projects/xlink exports TVL: 
        
 
 
    bitcoin                   9.35 M
    bsc                       2.63 M
    stacks                    0
    ethereum                  0
    
    total                    11.98 M

**Comment by llamatester** [comment]
Error while running adapter at : 
        
 
  > Please revert changes to package.json / package-lock.json

**Comment by llamatester** [comment]
Error while running adapter at projects/xlink: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:198:11
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
Error while running adapter at projects/xlink: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:198:11
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
Error while running adapter at projects/xlink: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:198:11
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
Error while running adapter at projects/xlink: 
        
 
  
    
    
    Error: Data for protocol xlink on chain stacks is undefined on heroku
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/heroku-api.js:18:13
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:143:9
        at async Promise.all (index 0)
        at async Promise.all (index 5)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:186:3

**Comment by llamatester** [comment]
Error while running adapter at projects/xlink: 
        
 
  
    
    
    Error: Data for protocol xlink on chain stacks is undefined on heroku
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/heroku-api.js:18:13
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:143:9
        at async Promise.all (index 0)
        at async Promise.all (index 5)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:186:3

**Comment by g1nt0ki** [comment]
thanks, added it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/10619

I have excluded aBTC on stacks since we are already counting it as part of bitcoin, also, alex token since we exclude gov token from bridge tvl

**Pull request closed without merging**
