### PR TITLE
add Aspida

### PR DESCRIPTION
**Pull request by aspidanet**
##### Name (to be shown on DefiLlama):
Aspida

##### Twitter Link:
https://twitter.com/aspida_net

##### List of audit links if any:
no

##### Website Link:
https://aspidanet.com/

##### Logo (High resolution, will be shown with rounded borders):
https://aspidanet.com/logo512.png

##### Current TVL:
476.06 k as reported by `node test.js projects/aspida/index.js`

##### Treasury Addresses (if the protocol has treasury)
0xD7fCD90BCCDf957d2ff4E791EfDA63F7d9C67b8A

##### Chain:
Ethereum

##### Short Description (to be shown on DefiLlama):
Aspida is an efficient liquid staking protocol that offers a decentralized, secure, and highly compatible staking service and LSD assets. By leveraging the power of liquid staking, Aspida enables users across different layers and networks to earn profitable rewards while maintaining the flexibility to participate in multiple staking opportunities.

##### Token address and ticker if any:
aETH 0xFC87753Df5Ef5C368b5FBA8D4C5043b77e8C5b39

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Liquid staking

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
No

##### forkedFrom (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL  basing on the minting quantity and value of aETH, whose value of is equal to ETH. 
TVL=aETH quantity multiplied by the aETH price (price 1aETH=1ETH)

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/aspidanet

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/aspida exports TVL: 
        
 
 
    ethereum                  476.15 k
    
    total                    476.15 k

**Comment by g1nt0ki** [comment]
@aspidanet thanks for the PR

**Comment by llamatester** [comment]
The adapter at projects/aspida exports TVL: 
        
 
 
    ethereum                  438.32 k
    
    total                    438.32 k

**Comment by Define101** [comment]
@aspidanet what happen to the twitter account? Does not exist

**Comment by aspidanet** [comment]
@Define101 Sorry, the correct link is [aspidanet](https://twitter.com/aspidanet)

**Pull request merged**
