### PR TITLE
update: add metis

### PR DESCRIPTION
**Pull request by eriscrypt**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/wagmi-com exports TVL: 
        
 
 
    metis                     427.90 k
    fantom                    3.51 k
    era                       151.43 k
    kava                      6.27 M
    
    total                    6.85 M

**Comment by llamatester** [comment]
The adapter at projects/wagmi-com exports TVL: 
        
 
 
    metis                     0
    era                       151.44 k
    kava                      6.25 M
    fantom                    3.51 k
    
    total                    6.41 M

**Comment by llamatester** [comment]
The adapter at projects/wagmi-com exports TVL: 
        
 
 
    metis                     427.32 k
    era                       151.43 k
    kava                      6.25 M
    fantom                    3.51 k
    
    total                    6.83 M

**Comment by g1nt0ki** [comment]
@eriscrypt thanks, included your changed here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/70164313b3c30cff68c3b4de826f00051fd705a4

**Pull request closed without merging**
