### PR TITLE
Update Siren TVL calculations

### PR DESCRIPTION
**Pull request by MysticDakra**
Update the tvl so we are calculating the correct value.

##### Twitter Link: 
- https://twitter.com/sirenprotocol?s=20

##### Website Link:
- https://sirenmarkets.com/
- https://app.sirenmarkets.com/trade

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
white_siren_circle

##### Current TVL: 
- 7,895,233.28 

##### Coingecko ID (so your TVL can appear on Coingecko):  
- https://www.coingecko.com/en/coins/siren

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
- Already listed 

##### Description/bio (to be shown on DefiLlama): 
- Decentralized option markets on Ethereum.

##### Token address and ticker if any:
- Ticker: SI
- Address: 0xD23Ac27148aF6A2f339BD82D0e3CFF380b5093de

##### Category (Yield/Dexes/Lending/Minting): 
- Options

##### [Optional] ETH addresss (to receive a LlamaPunk):
- My address: 0x04BD82Bf46de00a048d66E9Eb00C5Bc28A07Cfb5

### CODE REVIEW

**Comment by 0xngmi** [comment]
Looks good to me, should I wait before merging since it's marked as DRAFT?

**Comment by MysticDakra** [comment]
@o

> Looks good to me, should I wait before merging since it's marked as DRAFT?

Thanks for the review! I pushed it up and had someone on our team review it they wanted to change it to sdk instead of a fetch Ill remove draft once its ready.

**Comment by 0xngmi** [comment]
Yeah, tbh I was planning to merge it and then convert it to sdk, but much better if it's already done. Can I use the updated adapter to get the tvl since the creation of siren?

**Comment by MysticDakra** [comment]
Hey this is updated let me know how it looks! And the calculations should be corrected now, I had to change a few other things as well and changed it to an SDK.
If there is anything else you would recommend changing either let me know or you are more than welcome to change it after a merge as well.

**Pull request merged**
