### PR TITLE
fix: split dex & lend tvl

### PR DESCRIPTION
**Pull request by silvercondor**
This is an update to split the TVL as requested in the discord chat.

https://discord.com/channels/823822164956151810/823822533974425621/1240963482120097822

product name 1: Native Swap
product name 2: Native Lend

**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/native exports TVL: 
        
 
 
    mantle                    12.47 M
    ethereum                  10.57 M
    bsc                       514.84 k
    arbitrum                  353.02 k
    polygon                   304.72 k
    avax                      150.00 k
    zeta                      836
    manta                     0
    zklink                    0
    
    total                    24.36 M

**Comment by llamatester** [comment]
The adapter at projects/native-lend exports TVL: 
        
 
 
    zklink                    3.00 M
    arbitrum                  7
    
    total                    3.00 M

**Comment by g1nt0ki** [comment]
@silvercondor looks good

**Comment by g1nt0ki** [comment]
hmm, unsure why this is showing zklink tvl as 3m for lending adapter when I see 0 tvl and 30k as borrowed, @silvercondor the tokens are not kept in lending contract?

**Comment by silvercondor** [comment]
yeah, there's a logic change to keep the tokens in the comptroller. I'll recheck the borrowing portion but output figures match closely to what we have on our internal metrics

**Comment by g1nt0ki** [comment]
ah, I see it now, I will add the borrowed code

**Pull request merged**
