### PR TITLE
feat: add BOB gateway TVL

### PR DESCRIPTION
**Pull request by bvotteler**
Add TVL from gateways on BOB.

From contracts currently shown in the onramp factory's [allOnramps read method](https://explorer.gobob.xyz/address/0x1831d29376eb94bba3ca855af7984db923768b27?tab=read_contract) and for [WBTC](https://github.com/DefiLlama/DefiLlama-Adapters/blob/7ff111f5a7bcb332a62db9cf793256208e1f8b75/projects/helper/coreAssets.json#L1804) and [TBTC](https://github.com/DefiLlama/DefiLlama-Adapters/blob/7ff111f5a7bcb332a62db9cf793256208e1f8b75/projects/helper/coreAssets.json#L1810) tokens.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bob exports TVL: 
        
 
 
    ethereum                  112.43 M
    bob                       1.39 M
    
    total                    113.82 M

**Comment by g1nt0ki** [comment]
hi @bvotteler wdym by gateway on bob? how are the WBTC & TBTC bridged to bob

**Comment by gregdhill** [comment]
Hi @g1nt0ki the WBTC and TBTC are bridged using the canonical bridge (OP Stack) and BOB Gateway is a SC where those tokens are locked. The intent behind this PR is just to capture the TVL in those smart contracts.

**Comment by g1nt0ki** [comment]
I am confused because, these tokens are already counted as tvl on ethereum side (the cannonical bridge) right?

**Comment by bvotteler** [comment]
> I am confused because, these tokens are already counted as tvl on ethereum side (the cannonical bridge) right?

You are right, this was a mistake on my end to add it to this project. 
I will replace this PR with a corrected version.

**Comment by bvotteler** [comment]
Replaced by https://github.com/DefiLlama/DefiLlama-Adapters/pull/11155

**Pull request closed without merging**
