### PR TITLE
Add Spherium cross-chain bridge

### PR DESCRIPTION
**Pull request by AhmedIbrahim336**
##### Twitter Link:
[Twitter](https://twitter.com/SpheriumFinance)

##### List of audit links if any:
[Quillhash](https://github.com/Quillhash/Audit_Reports/blob/master/Spherium%20Smart%20Contract%20Audit%20Report%20-%20QuillAudits.pdf)
[peckshield](https://github.com/peckshield/publications/blob/master/audit_reports/PeckShield-Audit-Report-Spherium-v1.0.pdf)
[HalbornSecurity](https://github.com/HalbornSecurity/PublicReports/blob/master/Solidity%20Smart%20Contract%20Audits/Spherium_Bridge_Smart_Contract_Security_Audit_Report_Halborn_v1_1.pdf
)

##### Website Link:
[spherium.finance](https://spherium.finance/#/)

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
[Google Drive](https://drive.google.com/file/d/1m4CoglNHXE4UpK7YjGBVOB_ke7zajkr8/view?usp=sharing)
[Google Drive](https://drive.google.com/file/d/1hsI7QOY7YsNc4w1ljpY1USsKgQ5KvdeS/view?usp=sharing)

##### Current TVL:
About 46.65K USD (Still to Add Liquidity)

##### Chain:
Ethereum and Binance Smart Chain

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
```json
{"id":"spherium","symbol":"sphri","name":"Spherium"}
```

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
```json
{"id":9869,"name":"Spherium","symbol":"SPHRI","slug":"spherium","is_active":1,"status":"active","first_historical_data":"2021-08-19T16:42:06.000Z","last_historical_data":"2022-03-20T00:47:00.000Z","platform":{"id":1027,"name":"Ethereum","symbol":"ETH","slug":"ethereum","token_address":"0x8a0cdfab62ed35b836dc0633482798421c81b3ec"},"rank":3924}
```

##### Short Description (to be shown on DefiLlama):
Spherium Finance ecosystem offers a complete suite of financial services comprising a universal wallet, token swap platform, money markets, staking services, and cross-chain liquidity transfer. Spherium aims to function as a global financial service provider, extending fundamental financial services to the unbanked.

##### Token address and ticker if any:
SPHRI
[BSC Scan](https://bscscan.com/token/0x8ea93d00cc6252e2bd02a34782487eed65738152)
[Ether Scan](https://etherscan.io/token/0x8a0cdfab62ed35b836dc0633482798421c81b3ec)

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Cross Chain

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
We’ll use Chainlink and Supraoracles

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL will be all liquidity added and locked by protocol participants, projects, or investors to our cross-chain bridge, our DEX, our lending/borrowing money markets, and our staking platform. TVL will be calculated taking the USDT value at any point in time of all the total tokens that have been committed/locked in the ecosystem.

### CODE REVIEW

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
The code is near perfect, only issue I have is, we do not count native tokens as part of tvl, please blacklist your token from tvl calculation and I would approve this PR

**Comment by AhmedIbrahim336** [comment]
> The code is near perfect, only issue I have is, we do not count native tokens as part of tvl, please blacklist your token from tvl calculation and I would approve this PR

You are taking about MATIC and AVAX tokens? Or about the SPHRI token?

**Comment by g1nt0ki** [comment]
SPHRI tokens

**Comment by g1nt0ki** [comment]
@AhmedIbrahim336 do you still want to be listed, I can fix this PR, but it might show the tvl as 0

**Comment by llamatester** [comment]
The adapter at projects/spherium exports TVL: 
        
 
 
    ethereum                  0
    avax                      0
    polygon                   595.5710883013629
    bsc                       1.39 k
    
    total                    1.98 k

**Comment by AhmedIbrahim336** [comment]
@g1nt0ki  We whitelisted our bridge on other chains as well so I will add them then I will open it for review

**Comment by llamatester** [comment]
The adapter at projects/spherium exports TVL: 
        
 
 
    cronos                    0
    ethereum                  0
    moonbeam                  0
    moonriver                 0
    arbitrum                  0
    kcc                       0
    aurora                    0
    okexchain                 0
    avax                      0
    fantom                    0
    optimism                  0
    polygon                   601.5735411108285
    bsc                       1.40 k
    
    total                    2.00 k

**Comment by llamatester** [comment]
The adapter at projects/spherium exports TVL: 
        
 
 
    cronos                    0
    ethereum                  0
    bsc                       1.40 k
    moonriver                 0
    moonbeam                  0
    polygon                   602.0011615034593
    arbitrum                  0
    avax                      0
    fantom                    0
    aurora                    0
    okexchain                 0
    kcc                       0
    optimism                  0
    
    total                    2.00 k

**Pull request merged**
