### PR TITLE
fix: include btc lending and new usdc-usdc.e pair in tvl calculation

### PR DESCRIPTION
**Pull request by 0xKMG**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at undefined: 
        
 
  \n Please revert changes to package.json / package-lock.json

**Comment by 0xKMG** [comment]
let me know if anything need to be fixed on my side, I've run a node test and it was working locally.

**Comment by llamatester** [comment]
The adapter at projects/vaultka exports TVL: 
        
 
 
    arbitrum                  28.30 M
    
    total                    28.30 M

**Comment by g1nt0ki** [comment]
@0xKMG thanks for the PR

**Pull request merged**
