### PR TITLE
Add Shiden network dapps-staking TVL

### PR DESCRIPTION
**Pull request by hskang9**
Update on Shiden network

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Whats the purpose of the staking and what benefit do stakers get?

**Comment by hskang9** [comment]
The purpose of staking is to reward dapp developers that forms ecosystem of the network and stakers get block rewards proportionally to dapp’s staked tokens.

**Comment by hskang9** [comment]
Details: https://docs.astar.network/learn/core-features/dapps-reward

**Comment by waynebruce0x** [comment]
We don't count chain staking, validator nodes etc, and this sounds similar. Have we understood correctly that you signal which dapps are best and then the chain gives money to the ones that have most points?

**Comment by waynebruce0x** [comment]
Closing because of inactivity. Please message us in our discord server if you'd like this reopening

**Comment by hskang9** [comment]
Sorry for late response due to bridge integration. In short, dapps staking is actually different from chain staking in that it rewards dapps in its ecosystem. One can figure out which dapps is most staked from users like in this picture.
Screen Shot 2022-01-24 at 4 12 17 PM

**Comment by hskang9** [comment]
@waynebruce0x can you reopen this PR

**Comment by realdealshaman** [comment]
Hi, @hskang9. Could you help us with the following info for the listing. It will help determine how you would like the info to be displayed on the DefiLlama site. Thanks

Twitter Link:
List of audit links if any:
Website Link:
Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
Current TVL:
Chain:
Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
Short Description (to be shown on DefiLlama):
Token address and ticker if any:
Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
forkedFrom (Does your project originate from another project):
methodology (what is being counted as tvl, how is tvl being calculated):

**Comment by fiexer** [comment]
@realdealshaman here is all the information:

- **Twitter link**: https://twitter.com/ShidenNetwork
- **Audit**: https://certificate.quantstamp.com/view/a-star-network-staking
- **Website link**: https://shiden.astar.network
- **Logo**: https://drive.google.com/drive/folders/1No-5CKE_3UI7OfsEjXdQt2be3K1r0xAb
- **Current TVL**: 12706459 $SDN / $11.3M USD
- **Chian**: Shiden Network
- **Coingecko ID**: shiden
- **Coinmarketcap ID**: 11451
- **Short Description**: Shiden Network is a multi-chain decentralized application layer on Kusama Network. dApp staking is a mechanism that incentives developers who built in the Shiden ecosystem. Users can stake on those dApps to earn staking rewards and at the same time support the project by giving them a daily income.
- **Token address and ticker if any**: $SDN
- **Category**: Staking
- **Methodology**: TVL is calculated based on the amount of $SDN staked

**Comment by fiexer** [comment]
@realdealshaman could you change the logo?
It's now showing the Astar logo instead of the Shiden logo. You can find the logo here as 256px:
https://drive.google.com/file/d/1swB4UBB1Qk4u6YoPLpWiUVuHPGwLdccI/view?usp=sharing

**Comment by realdealshaman** [comment]
I have updated it. Thanks for clarifying. I will reflect on the website in about one hour

**Pull request merged**
