### PR TITLE
Added PunkSwap Factory

### PR DESCRIPTION
**Pull request by ShibaPunkArmy**
Added PunkSwap Factory and Masterchef on Shibarium

opBNB has only Factory for now and was also added into the index.js file

**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/punkswap: 
        
 
  
    
    
    TypeError: addresses.forEach is not a function
    Truncated error stack:
    
        at getUniqueAddresses (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/tokenMapping.js:65:13)
        at sumTokens2 (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/unwrapLPs.js:689:12)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/staking.js:27:32
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:29)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:136:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:131:44

**Comment by llamatester** [comment]
Error while running adapter at projects/punkswap: 
        
 
  
    
    
    TypeError: addresses.forEach is not a function
    Truncated error stack:
    
        at getUniqueAddresses (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/tokenMapping.js:65:13)
        at sumTokens2 (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/unwrapLPs.js:689:12)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/staking.js:27:32
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:29)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:136:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:131:44

**Comment by llamatester** [comment]
The adapter at projects/punkswap exports TVL: 
        
 
 
    op_bnb                    0
    shibarium                 37.48 k
    
    total                    37.48 k

**Comment by ShibaPunkArmy** [comment]
Name (to be shown on DefiLlama):
PunkSwap

Twitter Link:
https://twitter.com/PunkSwapDEX

List of audit links if any:
NONE

Website Link:
https://punkswap.exchange

Logo (High resolution, will be shown with rounded borders):
https://punkswap.exchange/images/punkswapSymbol.webp

Current TVL: 
Treasury Addresses (if the protocol has treasury)

Chain:
shibarium, opBNB

Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed):
(https://api.coingecko.com/api/v3/coins/list)

Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000):
NONE

Short Description (to be shown on DefiLlama):
PunkSwap operates across multiple blockchain networks and has garnered trust from a diverse and extensive user base. We provide a range of products and services for our PUNK token. We invite you to explore our platform and discover the possibilities.

Token address and ticker if any: 
CA (Shibarium): 0x1Bf3f5b633800E6047dEb14cF14C4b49118a3570,
Ticker: PUNK

Category (full list at https://defillama.com/categories) *Please choose only one:
DEXES

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
NONE

forkedFrom (Does your project originate from another project):
PancakeSwap v2

methodology (what is being counted as tvl, how is tvl being calculated):
https://github.com/DefiLlama/DefiLlama-Adapters/pull/7507/commits/c058fe8ba4e6b642dcf48c918727fa5ff026d509

Github org/user (Optional, if your code is open source, we can track activity):
ShibaPunkArmy

**Pull request merged**
