### PR TITLE
Use detailed TVL + include alex staking

### PR DESCRIPTION
**Pull request by hyossid**
Hi, I changed api to use breakdown of previous api. This might be much reasonable for Defillama and future update. 

Please review and let me know if you need further details.

Btw, I want to do remove this checkbox at the right top (Hide MCap Chart) until ALEX price is available in Coingecko, do you mind giving advise to remove this? 

image

And Also, would like to add this functionalities like Citycoin. It seems like need to export "staking" module to get this, but the key in the map of data returned should be always equal to Coingecko key?

image

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/alexlab exports TVL: 
        
 
 
    stacks                    16.09 M
    
    total                    16.09 M

**Comment by waynebruce0x** [comment]
For the staking toggle, it'll be easier to wait until ALEX is listed on coingecko. Or you can use your API to export a USD value of staked ALEX, like:

staking: {
  fetch: staking 
}

I'll ask the frontend team about removing the mcap check box

**Comment by llamatester** [comment]
The adapter at projects/alexlab exports TVL: 
        
 
 
    staking                   14.22 M
    stacks                    16.36 M
    
    total                    16.36 M

**Comment by hyossid** [comment]
> For the staking toggle, it'll be easier to wait until ALEX is listed on coingecko. Or you can use your API to export a USD value of staked ALEX, like:
> 
> staking: { fetch: staking }
> 
> I'll ask the frontend team about removing the mcap check box

thanks, I just added as you advised. It is in USD value, but planning change to breakdown one like above when we have CoinGecko enlisted.

**Comment by hyossid** [comment]
Hi @waynebruce0x  thanks for merging, does it requires some resetting time to be reflected on defillama page? I don't see the values updated yet

**Comment by g1nt0ki** [comment]
> Hi @waynebruce0x thanks for merging, does it requires some resetting time to be reflected on defillama page? I don't see the values updated yet

wait for 2-3 hours

**Pull request merged**
