### PR TITLE
Update Maya provider (need help)

### PR DESCRIPTION
**Pull request by GiMa-Maya**
Goal of this MR is to get TVL for radix fixed. However it's not working

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/mayachain exports TVL: 
        
 
 
    mayachain                 22.37 M
    thorchain                 9.81 M
    bitcoin                   7.42 M
    ethereum                  4.03 M
    arbitrum                  580.13 k
    dash                      249.28 k
    kujira                    193.10 k
    radixdlt                  0
    
    total                    44.65 M

**Comment by GiMa-Maya** [comment]
Don't merge

**Comment by GiMa-Maya** [comment]
For some reason, radix gives 0 tvl, while it should be around 285k. @ericnakagawa could use some help here :)

**Comment by llamatester** [comment]
The adapter at projects/mayachain exports TVL: 
        
 
 
    mayachain                 23.40 M
    thorchain                 10.12 M
    bitcoin                   7.50 M
    ethereum                  4.25 M
    arbitrum                  531.28 k
    radixdlt                  283.01 k
    dash                      270.22 k
    kujira                    211.83 k
    
    total                    46.56 M

**Comment by g1nt0ki** [comment]
@GiMa-Maya I think the issue was line 122

Next time, please tag me, I usually filter out drafts from PR page

**Comment by GiMa-Maya** [comment]
Thanks!! @g1nt0ki, looks good now!

**Comment by GiMa-Maya** [comment]
Ready for merge🫡

**Pull request merged**
