### PR TITLE
graphql-migration

### PR DESCRIPTION
**Pull request by slasher125**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at : 
        
 
  > Please revert changes to package.json / package-lock.json

**Comment by llamatester** [comment]
The adapter at projects/aktionariat exports TVL: 
        
 
 
    ethereum                  9.72 M
    optimism                  7.92 M
    
    total                    17.64 M

**Comment by llamatester** [comment]
Error while running adapter at projects/altr-lend: 
        
 
  
    
    
    TypeError: Only absolute URLs are supported
    Truncated error stack:
        at getNodeRequestOptions (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/node-fetch/lib/index.js:1327:9)
        at new Promise (<anonymous>)
        at new Promise (<anonymous>)

**Comment by llamatester** [comment]
Error while running adapter at : 
        
 
  > Please revert changes to package.json / package-lock.json

**Comment by g1nt0ki** [comment]
thanks @slasher125

**Pull request merged**
