### PR TITLE
Add plexus fee

### PR DESCRIPTION
**Pull request by Plexus-Olivia**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): 
Token-Symbol_192

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list) 
plexus-app

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
23731

##### Short Description (to be shown on DefiLlama):
PLEXUS is a Cross-chain aggregator service for mass adoption of blockchain.  All chains, all tokens, and the cheapest swap with just one transaction.

##### Token address and ticker if any:
Token address: 0x60b9c9C167bA57cc376b0FaafC68Df5C9882328e / Ticker: PLX

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Cross Chain

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### forkedFrom (Does your project originate from another project):
no forked

##### methodology (what is being counted as tvl, how is tvl being calculated):
There is no TVL as there is no token distribution yet.

### CODE REVIEW

**Comment by dtmkeng** [comment]
@Plexus-Olivia hi seem like your api return total fees, do you have api for return daily fees ?
, we run snapshots data every daily day at 0:00 UTC

**Comment by Plexus-Olivia** [comment]
I updated it Please check.

**Comment by dtmkeng** [comment]
@Plexus-Olivia  https://defillama.com/fees/plexus

**Comment by Plexus-Olivia** [comment]
I added a chain and uploaded a Pull request to the dimension-adapters repository. 
https://github.com/DefiLlama/dimension-adapters/pull/358
Please check. Thank you :)

**Pull request closed without merging**
