### PR TITLE
Add zkex DEX adapter

### PR DESCRIPTION
**Pull request by robin0909**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/zkex exports TVL: 
        
 
 
    polygon                   1.76 k
    bsc                       6.32 k
    op_bnb                    6.1086
    arbitrum                  74.20 k
    era                       19.855
    avax                      6.03 k
    linea                     57.42 k
    base                      19.855
    optimism                  4.05 k
    
    total                    149.82 k

**Comment by llamatester** [comment]
The adapter at projects/zkex exports TVL: 
        
 
 
    bsc                       12.25 k
    polygon                   3.54 k
    avax                      6.18 k
    op_bnb                    6.1165
    linea                     57.74 k
    optimism                  4.05 k
    era                       19.92475
    base                      19.92475
    arbitrum                  74.38 k
    
    total                    158.20 k

**Comment by g1nt0ki** [comment]
@robin0909 thanks for the PR

**Comment by Define101** [comment]
@robin0909 please fill the form

**Comment by robin0909** [comment]
> @robin0909 please fill the form

what's the form?

**Comment by Define101** [comment]
Name (to be shown on DefiLlama):
Twitter Link:
List of audit links if any:
Website Link:
Logo (High resolution, will be shown with rounded borders):
Current TVL:
Treasury Addresses (if the protocol has treasury)
Chain:
Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
Short Description (to be shown on DefiLlama):
Token address and ticker if any:
Category (full list at https://defillama.com/categories) *Please choose only one:
Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Implementation Details: Briefly describe how the oracle is integrated into your project:
Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
forkedFrom (Does your project originate from another project):
methodology (what is being counted as tvl, how is tvl being calculated):
Github org/user (Optional, if your code is open source, we can track activity):

**Comment by Define101** [comment]
@robin0909

**Comment by robin0909** [comment]
> **NOTE**
> 
> #### Please enable "Allow edits by maintainers" while putting up the PR.
> > * If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> > * If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.
> 
> 1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
> 2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
> 3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
> 4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
> 5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
> 6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap
> 
> ##### Name (to be shown on DefiLlama):
> * ZKEX
> 
> ##### Twitter Link:
> * https://twitter.com/ZKEX_Official
> 
> ##### List of audit links if any:
> * https://docs.zk.link/appendix/audits
> 
> ##### Website Link:
> * https://app.zkex.com/
> 
> ##### Logo (High resolution, will be shown with rounded borders):
> log
> 
> ```
> <svg width="33" height="32" viewBox="0 0 33 32" fill="none" xmlns="http://www.w3.org/2000/svg" class="small"><path d="M26.7125 8.03631C28.2137 9.9011 29.1611 12.1412 29.4489 14.5067L29.4627 14.6269C29.4724 14.7188 29.5163 14.8039 29.5859 14.8655C29.6556 14.9272 29.7459 14.9611 29.8395 14.9606H32.1186C32.1683 14.9606 32.2175 14.9509 32.2633 14.932C32.3092 14.9132 32.3508 14.8856 32.3859 14.8508C32.4209 14.8159 32.4486 14.7746 32.4674 14.7292C32.4862 14.6838 32.4957 14.6352 32.4954 14.5861V14.5067C32.2949 12.1428 31.5567 9.85425 30.3357 7.81163C30.0922 7.39858 29.8257 6.99915 29.5431 6.61106C29.183 6.11485 28.7941 5.63972 28.3782 5.18809C27.7399 4.49571 27.0419 3.85937 26.2921 3.28624C26.2415 3.24539 26.1864 3.20454 26.1335 3.16596C24.3574 1.84918 22.323 0.912391 20.16 0.415319C19.0954 0.170065 18.0086 0.0309287 16.9159 0L16.1829 0C15.0855 0.0221837 13.9931 0.154495 12.9227 0.394894C12.0023 0.601149 11.1027 0.889031 10.2346 1.25504C9.0404 1.75786 7.91309 2.40343 6.87794 3.1773C6.8274 3.21362 6.77685 3.24993 6.7286 3.28851C5.53025 4.19564 4.4675 5.26529 3.5718 6.46582C3.25704 6.8766 2.97674 7.30326 2.71252 7.74128C1.45925 9.80543 0.702308 12.1262 0.499999 14.5248V14.5748C0.495603 14.6237 0.501133 14.6731 0.516264 14.7199C0.531395 14.7667 0.555825 14.8101 0.588126 14.8475C0.620426 14.8849 0.659949 14.9156 0.704385 14.9377C0.748821 14.9599 0.797279 14.973 0.846926 14.9765H3.16743C3.26213 14.9763 3.35339 14.9414 3.42346 14.8785C3.49353 14.8156 3.5374 14.7291 3.54652 14.636C3.54885 14.5957 3.55345 14.5556 3.56031 14.5157C3.55736 14.4659 3.56358 14.4159 3.57869 14.3682C3.73191 13.1696 4.06004 11.9993 4.55284 10.8936C5.43881 8.88967 6.82741 7.14195 8.58743 5.8156C10.3474 4.48926 12.4207 3.62809 14.6114 3.31348C14.6643 3.30628 14.718 3.31982 14.7609 3.35121C14.8039 3.38259 14.8327 3.42933 14.8412 3.48142C14.8475 3.52512 14.8394 3.56966 14.8182 3.60851L14.8044 3.63121L13.2122 6.35461L10.8665 10.358L9.30184 13.0338L8.44026 14.5067L8.17605 14.9606L7.666 15.8321C7.64055 15.8726 7.62483 15.9184 7.62005 15.966V16.0477C7.62525 16.0944 7.64095 16.1393 7.666 16.1793L8.17605 17.053L8.44026 17.507L9.30184 18.9776L10.8665 21.6556L13.2076 25.6613L14.7998 28.3847L14.8182 28.4119C14.8433 28.4585 14.8492 28.5128 14.8347 28.5636C14.8201 28.6144 14.7862 28.6576 14.7401 28.6843C14.7008 28.7052 14.6557 28.7132 14.6114 28.7069C13.6638 28.5724 12.7344 28.3334 11.8406 27.9943C10.2266 27.3836 8.75133 26.4625 7.50033 25.2844C6.24934 24.1063 5.24749 22.6947 4.55284 21.1313C4.05758 20.0245 3.72713 18.8526 3.5718 17.6522C3.5718 17.6045 3.55801 17.5569 3.55342 17.507C3.55113 17.4661 3.55113 17.4252 3.55342 17.3844C3.54223 17.2933 3.49778 17.2094 3.4284 17.1484C3.35903 17.0874 3.2695 17.0535 3.17662 17.053H0.879091C0.778946 17.053 0.682869 17.0922 0.611841 17.1619C0.540813 17.2317 0.500606 17.3263 0.499999 17.4252C0.498764 17.4358 0.498764 17.4465 0.499999 17.457V17.507C0.702859 19.9033 1.4598 22.2218 2.71252 24.2837C2.97592 24.7243 3.26275 25.1508 3.5718 25.5614C3.91679 26.0244 4.28725 26.4684 4.6815 26.8913C5.30714 27.5665 5.99219 28.1855 6.7286 28.741L6.87794 28.8545C7.91249 29.6219 9.03727 30.2627 10.2277 30.7631C11.0929 31.1279 11.9894 31.415 12.9067 31.621C13.9827 31.8578 15.0806 31.9848 16.1829 32H16.9227C18.0178 31.9733 19.1072 31.8356 20.1737 31.5892C21.0759 31.3821 21.9578 31.0965 22.809 30.7359C23.9887 30.2367 25.1039 29.6006 26.1312 28.8409C26.1841 28.8 26.2392 28.7614 26.2898 28.7183C27.0439 28.1477 27.7444 27.5112 28.3828 26.8165C28.7992 26.3661 29.1882 25.8917 29.5477 25.3957C29.8303 25.0077 30.0968 24.606 30.3403 24.1929C31.5584 22.1526 32.2951 19.8673 32.4954 17.507C32.5039 17.4553 32.5019 17.4026 32.4896 17.3518C32.4773 17.3009 32.4549 17.253 32.4237 17.2108C32.3925 17.1685 32.3531 17.1329 32.3078 17.1058C32.2626 17.0787 32.2123 17.0608 32.16 17.053H32.1209H29.8418C29.7487 17.053 29.6589 17.0867 29.5895 17.1478C29.52 17.2089 29.4757 17.2931 29.465 17.3844L29.4512 17.507C29.1154 20.2565 27.8918 22.8261 25.9617 24.8348C24.0316 26.8436 21.4977 28.1846 18.7355 28.6593C18.6592 28.6717 18.5809 28.6607 18.5111 28.6278C18.4412 28.595 18.3833 28.5418 18.3449 28.4755L18.2944 28.3869L16.5482 25.4026L16.5023 25.3231L14.9538 22.6746L12.6126 18.6689L12.2611 18.0675C12.2274 18.0109 12.2095 17.9465 12.2092 17.8808C12.2089 17.8151 12.2262 17.7506 12.2594 17.6936C12.2925 17.6367 12.3403 17.5895 12.3979 17.5567C12.4555 17.5239 12.5208 17.5067 12.5873 17.507H17.8578C17.8929 17.5067 17.9273 17.4973 17.9575 17.4798C17.9878 17.4623 18.0128 17.4372 18.0302 17.4071L18.2392 17.053L18.7883 16.1135C18.8094 16.0822 18.8206 16.0455 18.8206 16.0079C18.8206 15.9704 18.8094 15.9337 18.7883 15.9024L18.2507 14.9606L18.021 14.6043C18.0032 14.5747 17.978 14.5502 17.9478 14.5331C17.9176 14.516 17.8834 14.5069 17.8486 14.5067H12.5873C12.488 14.5043 12.3935 14.4635 12.3244 14.393C12.2552 14.3226 12.2168 14.2281 12.2174 14.1299C12.2176 14.0643 12.2358 14 12.2702 13.9438L12.6218 13.3424L14.9515 9.33901L16.5 6.6905L16.5459 6.61106L18.2921 3.63121L18.3426 3.54269C18.3815 3.477 18.4397 3.42449 18.5094 3.39208C18.5791 3.35967 18.6571 3.34888 18.7332 3.36113C21.8829 3.90607 24.7214 5.57163 26.7125 8.04312V8.03631Z" fill="white"></path><path d="M21.9269 16.1792L21.4076 17.053L21.1434 17.5069L20.4243 18.7347L18.2141 22.5338C18.1791 22.5902 18.1606 22.655 18.1606 22.7211C18.1606 22.7872 18.1791 22.852 18.2141 22.9083L19.5214 25.146C19.5714 25.232 19.6539 25.2949 19.7508 25.3209C19.8478 25.3468 19.9511 25.3337 20.0383 25.2845C20.0958 25.2504 20.1439 25.2028 20.1784 25.146L22.1796 21.7191L23.7879 18.9775L24.6471 17.5069L24.9137 17.053L25.4237 16.1792C25.445 16.1378 25.4597 16.0934 25.4674 16.0476V15.9659C25.4602 15.9192 25.4454 15.874 25.4237 15.832L24.9137 14.9605L24.6471 14.5066L23.7879 13.0337L22.1796 10.2921L20.1784 6.86746C20.1457 6.80984 20.098 6.76186 20.0403 6.72848C19.9825 6.69509 19.9168 6.67749 19.8499 6.67749C19.783 6.67749 19.7173 6.69509 19.6596 6.72848C19.6018 6.76186 19.5541 6.80984 19.5214 6.86746L18.2141 9.10519C18.1791 9.16155 18.1606 9.22635 18.1606 9.29243C18.1606 9.35851 18.1791 9.4233 18.2141 9.47966L20.4335 13.2788L21.1526 14.5066L21.4168 14.9605L21.9269 15.832C21.9553 15.8807 21.9725 15.9349 21.9774 15.9909V16.0204C21.9725 16.0763 21.9553 16.1306 21.9269 16.1792Z" fill="white"></path></svg>
> ```
> 
> ##### Current TVL:
> bsc 12.25 k polygon 3.54 k avax 6.18 k op_bnb 6.1165 linea 57.74 k optimism 4.05 k era 19.92475 base 19.92475 arbitrum 74.38 k
> 
> total 158.20 k
> 
> ##### Treasury Addresses (if the protocol has treasury)
> * No
> 
> ##### Chain:
> * eth/bsc/polygon/avax/arb/op/zksync/linea/scroll/polygon zkevm/manta/mantle/metis/base/opbnb
> 
> ##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
> * No
> 
> ##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
> * No
> 
> ##### Short Description (to be shown on DefiLlama):
> * Multi-Chain Super DEX
> 
> ##### Token address and ticker if any:
> * No
> 
> ##### Category (full list at https://defillama.com/categories) *Please choose only one:
> * Derivatives
> 
> ##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.): No
> ##### Implementation Details: Briefly describe how the oracle is integrated into your project: No
> ##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage: No
> ##### forkedFrom (Does your project originate from another project):
> * No
> 
> ##### methodology (what is being counted as tvl, how is tvl being calculated):
> * Total assets owned by MLP pools.
> 
> ##### Github org/user (Optional, if your code is open source, we can track activity):
> * No

@Define101  filled the form

**Pull request merged**
