### PR TITLE
fix errors + onchain polygon

### PR DESCRIPTION
**Pull request by iospap**
Polygon data is sourced onchain, avoiding subgraph.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/visor exports TVL: 
        
 
 
    arbitrum                  208.19 k
    ethereum-staking          3.81 M
    celo                      48.15931260274498
    optimism                  5.51 M
    ethereum                  2.43 M
    polygon                   329.63 k
    staking                   3.81 M
    
    total                    8.48 M

**Comment by llamatester** [comment]
The adapter at projects/visor exports TVL: 
        
 
 
    ethereum-staking          3.81 M
    celo                      48.21063649726752
    optimism                  5.53 M
    arbitrum                  208.43 k
    ethereum                  2.43 M
    polygon                   329.78 k
    staking                   3.81 M
    
    total                    8.50 M

**Comment by llamatester** [comment]
Error while running adapter at projects/visor: 
        
 
  
    
    
    Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="getHypervisorData()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    Truncated error stack:
        at Interface.decodeFunctionResult (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/abi/lib/interface.js:388:23)

**Comment by llamatester** [comment]
The adapter at projects/visor exports TVL: 
        
 
 
    ethereum-staking          3.39 M
    arbitrum                  193.80 k
    celo                      45.68846468805104
    optimism                  5.14 M
    ethereum                  2.31 M
    polygon                   1.04 M
    staking                   3.39 M
    
    total                    8.69 M

**Comment by g1nt0ki** [comment]
@iospap sorry, I missed your latest change. I was refactoring this already to use multiCall, would it be possible to add the registry for others as well? I prefer on chain as it is more reliable/breaks less often

My changes on top of your code: https://github.com/DefiLlama/DefiLlama-Adapters/pull/5194

**Pull request closed without merging**
