### PR TITLE
Add Pegasus Finance

### PR DESCRIPTION
**Pull request by andy-t-wang**
##### Twitter Link:
https://twitter.com/0xPegasusFi

##### Website Link:
https://www.pegasusfinance.xyz/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
Pega (3)
Pega

##### Current TVL:
$354.56k

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

NA
##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
NA

##### Short Description (to be shown on DefiLlama):
A speculation-focused interest rate perp with novel tokenomics on Optimism. 

##### Token address and ticker if any:
$PEGA: 0x18607aDc70d68E196D12019d49b0607b99312853

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Derivatives

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Multi-Cloud platform bot oracle

##### forkedFrom (Does your project originate from another project):
NA

##### methodology (what is being counted as tvl, how is tvl being calculated):
POL including treasury weth + weth deposited as liquidity in the perpetual

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/pegasusfinance exports TVL: 
        
 
 
    optimism                  363.14 k
    
    total                    363.14 k

**Comment by g1nt0ki** [comment]
@andy-t-wang can you explain the treasury part a bit? these are not user funds right? then they go under 'treasury' not 'tvl'

**Comment by g1nt0ki** [comment]
Also, can you please revert the changes to package-lock.json file?

**Comment by g1nt0ki** [comment]
> At a high level, we use POL to act as the liquidity for our perpetual. The liquidity comes from WETH raised from token sales. This value is strictly for use in the protocol. None of the treasury is used to invest etc so I figured it counted for TVL since our liquidity pool = the treasury balance.

hmmm, it is tricky but can you keep the WETH in liquidity contract as 'tvl', but can you move the WETH in treasury to 'treasury' export? My reasoning is, user has no access to the weth in treasury right?

**Comment by llamatester** [comment]
The adapter at projects/pegasusfinance exports TVL: 
        
 
 
    optimism                  372.00 k
    
    total                    372.00 k

**Comment by andy-t-wang** [comment]
Ok made the change. Eventually, all the treasury will move into the liquidity pool. Will we need to submit another push for that?

**Comment by llamatester** [comment]
The adapter at projects/pegasusfinance exports TVL: 
        
 
 
    optimism                  192.18 k
    optimism-treasury         180.20 k
    treasury                  180.20 k
    
    total                    192.18 k

**Pull request merged**
