### PR TITLE
add credix project

### PR DESCRIPTION
**Pull request by MaximPiessen**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/credix exports TVL: 
        
 
 
    solana                    0
    
    total                    0

**Comment by g1nt0ki** [comment]
@MaximPiessen thanks for the PR, can you try to compute tvl via calls to solana instead of your own api?

**Comment by MaximPiessen** [comment]
Can you please check again? Just ran it locally and it seems to work fine on my side. Now added the retry like: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/serum.js

**Comment by llamatester** [comment]
The adapter at projects/credix exports TVL: 
        
 
 
    
    total                    9.38 M

**Comment by g1nt0ki** [comment]
@MaximPiessen we push for people to call blockchain because it more transparent, we accept api calls as last option. If you give me the solana addresses, maybe I can help with changing the adapter to use solana calls

**Comment by g1nt0ki** [comment]
I personally, would like to update legacy adapters using api calls to solana calls when I find time

**Comment by MaximPiessen** [comment]
Done!

**Comment by llamatester** [comment]
The adapter at projects/credix exports TVL: 
        
 
 
    
    total                    9.38 M

**Comment by g1nt0ki** [comment]
Hi @MaximPiessen , sorry noticed it just now, you cannot include outstanding loans under tvl, you can export it separately under the key 'borrowed', if you want, I can merge the PR and do it

**Comment by MaximPiessen** [comment]
Please go ahead and do it :) Thanks!

**Pull request merged**
