### PR TITLE
Projects/spherium

### PR DESCRIPTION
**Pull request by haidarally**
##### Twitter Link:
https://twitter.com/SpheriumFinance

##### List of audit links if any:

https://github.com/Quillhash/Audit_Reports/blob/master/Spherium%20Smart%20Contract%20Audit%20Report%20-%20QuillAudits.pdf
https://github.com/peckshield/publications/blob/master/audit_reports/PeckShield-Audit-Report-Spherium-v1.0.pdf
https://github.com/HalbornSecurity/PublicReports/blob/master/Solidity%20Smart%20Contract%20Audits/Spherium_Bridge_Smart_Contract_Security_Audit_Report_Halborn_v1_1.pdf

##### Website Link:

https://spherium.finance/#/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

https://drive.google.com/file/d/1m4CoglNHXE4UpK7YjGBVOB_ke7zajkr8/view?usp=sharing
https://drive.google.com/file/d/1hsI7QOY7YsNc4w1ljpY1USsKgQ5KvdeS/view?usp=sharing

##### Current TVL:
N/A (Still to Add Liquidity)
##### Chain:

Ethereum and Binance Smart Chain

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

"id":"spherium","symbol":"sphri","name":"Spherium"

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

{"id":9869,"name":"Spherium","symbol":"SPHRI","slug":"spherium","is_active":1,"status":"active","first_historical_data":"2021-08-19T16:42:06.000Z","last_historical_data":"2022-03-20T00:47:00.000Z","platform":{"id":1027,"name":"Ethereum","symbol":"ETH","slug":"ethereum","token_address":"0x8a0cdfab62ed35b836dc0633482798421c81b3ec"},"rank":3924}

##### Short Description (to be shown on DefiLlama):

Spherium Finance ecosystem offers a complete suite of financial services comprising a universal wallet, token swap platform, money markets, staking services, and cross-chain liquidity transfer. Spherium aims to function as a global financial service provider, extending fundamental financial services to the unbanked.

##### Token address and ticker if any:

SPHRI
https://bscscan.com/token/0x8ea93d00cc6252e2bd02a34782487eed65738152
https://etherscan.io/token/0x8a0cdfab62ed35b836dc0633482798421c81b3ec

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Cross Chain

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
We’ll use Chainlink and Supraoracles

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL will be all liquidity added and locked by protocol participants, projects, or investors to our cross-chain bridge, our DEX, our lending/borrowing money markets, and our staking platform. TVL will be calculated taking the USDT value at any point in time of all the total tokens that have been committed/locked in the ecosystem.

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Can this be calculated onchain instead? is the dex a univ2 fork and money market compound?

**Comment by llamatester** [comment]
Error while running adapter at projects/Spherium/index.js: 
        
 
  
    
    
    Error: Request failed with status code 401
        at createError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/axios/lib/core/createError.js:16:15)
        at settle (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/axios/lib/core/settle.js:17:12)
        at IncomingMessage.handleStreamEnd (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/axios/lib/adapters/http.js:322:11)
        at IncomingMessage.emit (node:events:532:35)
        at endReadableNT (node:internal/streams/readable:1346:12)
        at processTicksAndRejections (node:internal/process/task_queues:83:21) {
      config: {
        transitional: {
          silentJSONParsing: true,
          forcedJSONParsing: true,
          clarifyTimeoutError: false
        },
        adapter: [Function: httpAdapter],
        transformRequest: [ [Function: transformRequest] ],
        transformResponse: [ [Function: transformResponse] ],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        maxBodyLength: -1,
        validateStatus: [Function: validateStatus],
        headers: {
          Accept: 'application/json, text/plain, */*',
          apikey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnQiOiJzcGhyaS1mcm9udGVuZCIsIm9rIjp0cnVlLCJpYXQiOjE2NDQ5MjM3NzR9.aWsS3qwM2324szhEbOesc7EhStqp0jX22nBkQizPg-g',
          'User-Agent': 'axios/0.26.1'
        },
        method: 'get',
        url: 'https://app.spherium.finance/api/v1/amountLocked?network=ETH&includeMeta=true',
        data: undefined
      },
      request: <ref *1> ClientRequest {
        _events: [Object: null prototype] {
          abort: [Function (anonymous)],
          aborted: [Function (anonymous)],
          connect: [Function (anonymous)],
          error: [Function (anonymous)],
          socket: [Function (anonymous)],
          timeout: [Function (anonymous)],
          prefinish: [Function: requestOnPrefinish]
        },
        _eventsCount: 7,
        _maxListeners: undefined,
        outputData: [],
        outputSize: 0,
        writable: true,
        destroyed: false,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        maxRequestsOnConnectionReached: false,
        _defaultKeepAlive: true,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        _closed: false,
        socket: TLSSocket {
          _tlsOptions: [Object],
          _secureEstablished: true,
          _securePending: false,
          _newSessionPending: false,
          _controlReleased: true,
          secureConnecting: false,
          _SNICallback: null,
          servername: 'app.spherium.finance',
          alpnProtocol: false,
          authorized: true,
          authorizationError: null,
          encrypted: true,
          _events: [Object: null prototype],
          _eventsCount: 10,
          connecting: false,
          _hadError: false,
          _parent: null,
          _host: 'app.spherium.finance',
          _readableState: [ReadableState],
          _maxListeners: undefined,
          _writableState: [WritableState],
          allowHalfOpen: false,
          _sockname: null,
          _pendingData: null,
          _pendingEncoding: '',
          server: undefined,
          _server: null,
          ssl: [TLSWrap],
          _requestCert: true,
          _rejectUnauthorized: true,
          parser: null,
          _httpMessage: [Circular *1],
          [Symbol(res)]: [TLSWrap],
          [Symbol(verified)]: true,
          [Symbol(pendingSession)]: null,
          [Symbol(async_id_symbol)]: 114,
          [Symbol(kHandle)]: [TLSWrap],
          [Symbol(kSetNoDelay)]: false,
          [Symbol(lastWriteQueueSize)]: 0,
          [Symbol(timeout)]: null,
          [Symbol(kBuffer)]: null,
          [Symbol(kBufferCb)]: null,
          [Symbol(kBufferGen)]: null,
          [Symbol(kCapture)]: false,
          [Symbol(kBytesRead)]: 0,
          [Symbol(kBytesWritten)]: 0,
          [Symbol(connect-options)]: [Object],
          [Symbol(RequestTimeout)]: undefined
        },
        _header: 'GET /api/v1/amountLocked?network=ETH&includeMeta=true HTTP/1.1\r\n' +
          'Accept: application/json, text/plain, */*\r\n' +
          'apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnQiOiJzcGhyaS1mcm9udGVuZCIsIm9rIjp0cnVlLCJpYXQiOjE2NDQ5MjM3NzR9.aWsS3qwM2324szhEbOesc7EhStqp0jX22nBkQizPg-g\r\n' +
          'User-Agent: axios/0.26.1\r\n' +
          'Host: app.spherium.finance\r\n' +
          'Connection: close\r\n' +
          '\r\n',
        _keepAliveTimeout: 0,
        _onPendingData: [Function: nop],
        agent: Agent {
          _events: [Object: null prototype],
          _eventsCount: 2,
          _maxListeners: undefined,
          defaultPort: 443,
          protocol: 'https:',
          options: [Object: null prototype],
          requests: [Object: null prototype] {},
          sockets: [Object: null prototype],
          freeSockets: [Object: null prototype] {},
          keepAliveMsecs: 1000,
          keepAlive: false,
          maxSockets: Infinity,
          maxFreeSockets: 256,
          scheduling: 'lifo',
          maxTotalSockets: Infinity,
          totalSocketCount: 2,
          maxCachedSessions: 100,
          _sessionCache: [Object],
          [Symbol(kCapture)]: false
        },
        socketPath: undefined,
        method: 'GET',
        maxHeaderSize: undefined,
        insecureHTTPParser: undefined,
        path: '/api/v1/amountLocked?network=ETH&includeMeta=true',
        _ended: true,
        res: IncomingMessage {
          _readableState: [ReadableState],
          _events: [Object: null prototype],
          _eventsCount: 4,
          _maxListeners: undefined,
          socket: [TLSSocket],
          httpVersionMajor: 1,
          httpVersionMinor: 1,
          httpVersion: '1.1',
          complete: true,
          rawHeaders: [Array],
          rawTrailers: [],
          aborted: false,
          upgrade: false,
          url: '',
          method: null,
          statusCode: 401,
          statusMessage: 'Unauthorized',
          client: [TLSSocket],
          _consuming: false,
          _dumped: false,
          req: [Circular *1],
          responseUrl: 'https://app.spherium.finance/api/v1/amountLocked?network=ETH&includeMeta=true',
          redirects: [],
          [Symbol(kCapture)]: false,
          [Symbol(kHeaders)]: [Object],
          [Symbol(kHeadersCount)]: 36,
          [Symbol(kTrailers)]: null,
          [Symbol(kTrailersCount)]: 0,
          [Symbol(RequestTimeout)]: undefined
        },
        aborted: false,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        reusedSocket: false,
        host: 'app.spherium.finance',
        protocol: 'https:',
        _redirectable: Writable {
          _writableState: [WritableState],
          _events: [Object: null prototype],
          _eventsCount: 3,
          _maxListeners: undefined,
          _options: [Object],
          _ended: true,
          _ending: true,
          _redirectCount: 0,
          _redirects: [],
          _requestBodyLength: 0,
          _requestBodyBuffers: [],
          _onNativeResponse: [Function (anonymous)],
          _currentRequest: [Circular *1],
          _currentUrl: 'https://app.spherium.finance/api/v1/amountLocked?network=ETH&includeMeta=true',
          [Symbol(kCapture)]: false
        },
        [Symbol(kCapture)]: false,
        [Symbol(kNeedDrain)]: false,
        [Symbol(corked)]: 0,
        [Symbol(kOutHeaders)]: [Object: null prototype] {
          accept: [Array],
          apikey: [Array],
          'user-agent': [Array],
          host: [Array]
        }
      },
      response: {
        status: 401,
        statusText: 'Unauthorized',
        headers: {
          date: 'Sun, 03 Apr 2022 12:45:40 GMT',
          'content-type': 'application/json; charset=utf-8',
          'content-length': '40',
          connection: 'close',
          'x-powered-by': 'Express',
          'access-control-allow-origin': '*',
          'x-ratelimit-limit': '100',
          'x-ratelimit-remaining': '99',
          'x-ratelimit-reset': '1648990364',
          etag: 'W/"28-G36aRqyWRGRcYDrKXWiO8oyQmls"',
          'strict-transport-security': 'max-age=15552000; includeSubDomains',
          'cf-cache-status': 'DYNAMIC',
          'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
          'report-to': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=6UXcOyiMgP7W%2FvYv9IPgukfbwelM6xdCexmIpOggcmsyFXRrkMibPu6A3%2FSTUc3Gp6IlY3ZKLDt175q41u4tDR%2BIauXpuysWBPtp76b%2FMs9T6a0g8AD%2FualY3rbgiz36zMME%2FZSN"}],"group":"cf-nel","max_age":604800}',
          nel: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
          'x-content-type-options': 'nosniff',
          server: 'cloudflare',
          'cf-ray': '6f61e7160bb87dfc-LAX'
        },
        config: {
          transitional: [Object],
          adapter: [Function: httpAdapter],
          transformRequest: [Array],
          transformResponse: [Array],
          timeout: 0,
          xsrfCookieName: 'XSRF-TOKEN',
          xsrfHeaderName: 'X-XSRF-TOKEN',
          maxContentLength: -1,
          maxBodyLength: -1,
          validateStatus: [Function: validateStatus],
          headers: [Object],
          method: 'get',
          url: 'https://app.spherium.finance/api/v1/amountLocked?network=ETH&includeMeta=true',
          data: undefined
        },
        request: <ref *1> ClientRequest {
          _events: [Object: null prototype],
          _eventsCount: 7,
          _maxListeners: undefined,
          outputData: [],
          outputSize: 0,
          writable: true,
          destroyed: false,
          _last: true,
          chunkedEncoding: false,
          shouldKeepAlive: false,
          maxRequestsOnConnectionReached: false,
          _defaultKeepAlive: true,
          useChunkedEncodingByDefault: false,
          sendDate: false,
          _removedConnection: false,
          _removedContLen: false,
          _removedTE: false,
          _contentLength: 0,
          _hasBody: true,
          _trailer: '',
          finished: true,
          _headerSent: true,
          _closed: false,
          socket: [TLSSocket],
          _header: 'GET /api/v1/amountLocked?network=ETH&includeMeta=true HTTP/1.1\r\n' +
            'Accept: application/json, text/plain, */*\r\n' +
            'apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnQiOiJzcGhyaS1mcm9udGVuZCIsIm9rIjp0cnVlLCJpYXQiOjE2NDQ5MjM3NzR9.aWsS3qwM2324szhEbOesc7EhStqp0jX22nBkQizPg-g\r\n' +
            'User-Agent: axios/0.26.1\r\n' +
            'Host: app.spherium.finance\r\n' +
            'Connection: close\r\n' +
            '\r\n',
          _keepAliveTimeout: 0,
          _onPendingData: [Function: nop],
          agent: [Agent],
          socketPath: undefined,
          method: 'GET',
          maxHeaderSize: undefined,
          insecureHTTPParser: undefined,
          path: '/api/v1/amountLocked?network=ETH&includeMeta=true',
          _ended: true,
          res: [IncomingMessage],
          aborted: false,
          timeoutCb: null,
          upgradeOrConnect: false,
          parser: null,
          maxHeadersCount: null,
          reusedSocket: false,
          host: 'app.spherium.finance',
          protocol: 'https:',
          _redirectable: [Writable],
          [Symbol(kCapture)]: false,
          [Symbol(kNeedDrain)]: false,
          [Symbol(corked)]: 0,
          [Symbol(kOutHeaders)]: [Object: null prototype]
        },
        data: { error: 'Not authorized, token failed' }
      },
      isAxiosError: true,
      toJSON: [Function: toJSON]
    }

**Comment by llamatester** [comment]
The adapter at projects/Spherium/index.js exports TVL: 
        
 
 
    ethereum                  19.40 k
    bsc                       3.42 k
    
    total                    22.82 k

**Comment by haidarally** [comment]
> Can this be calculated onchain instead? is the dex a univ2 fork and money market compound?



> Can this be calculated onchain instead? is the dex a univ2 fork and money market compound?

The calculation is done by our API which just returns the sum of TVL in our bridges. For now our only product on mainnet is the Multichain Bridge, which is not a fork of any project.

**Comment by haidarally** [comment]
> Do you have a deposit/mint or AMM mechanism for the bridge? Can you share contract addresses? We can help write an on-chain adapter

Yes we do have a lock and mint mechanism for the bridge. The TVL value is derived from the sum of (tokens locked in the smart contract x token price). 

Using our TVL APIs, we ll be able to also get the TVL locked in all our services (including those which not live right now) without updating this repo.


Please share your thoughts.

**Comment by waynebruce0x** [comment]
We'd prefer to use on-chain calls because its easier to maintain from our side and more transparent. Whenever you add new services we can get them loaded onto the UI usually within 24 hours, we dont mind new PRs or even doing the code ourselves if you let us know what needs adding

**Comment by haidarally** [comment]
> We'd prefer to use on-chain calls because its easier to maintain from our side and more transparent. Whenever you add new services we can get them loaded onto the UI usually within 24 hours, we dont mind new PRs or even doing the code ourselves if you let us know what needs adding

Okay, will add this to our backlog and create a new PR
Closing this one, thanks

**Pull request closed without merging**
