### PR TITLE
Update cbridge

### PR DESCRIPTION
**Pull request by Dominator008**
Add contract addresses on zkSync Era, Polygon zkEVM, Linea and Scroll

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/celerbridge: 
        
 
  
    
    
    PromisePoolError: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0xcA11bde05977b3631167028862bE2a173976CA11","data":"0xbce38bd70000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000001c00000000000000000000000000000000000000000000000000000000000000260000000000000000000000000985458e523db3d53125813ed68c274899e9dfab40000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a08231000000000000000000000000841ce48f9446c8e281d3f1444cb859b4a6d0738c00000000000000000000000000000000000000000000000000000000000000000000000000000000985458e523db3d53125813ed68c274899e9dfab40000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a0823100000000000000000000000078a21c1d3ed53a82d4247b9ee5bf001f4620ceec00000000000000000000000000000000000000000000000000000000000000000000000000000000bd8064cdb96c00a73540922504f989c64b7b8b960000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a08231000000000000000000000000841ce48f9446c8e281d3f1444cb859b4a6d0738c00000000000000000000000000000000000000000000000000000000000000000000000000000000bd8064cdb96c00a73540922504f989c64b7b8b960000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a0823100000000000000000000000078a21c1d3ed53a82d4247b9ee5bf001f4620ceec00000000000000000000000000000000000000000000000000000000","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    Truncated error stack:
        at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
The adapter at projects/celerbridge exports TVL: 
        
 
 
    clv                       0
    conflux                   0
    milkomeda                 0
    oasis                     0
    rei                       0
    era                       774.84 k
    linea                     231.66 k
    polygon_zkevm             243.95 k
    optimism                  4.68 M
    aurora                    95.46 k
    celo                      103.80929747973519
    xdai                      346.42618345535
    syscoin                   1.61443
    fantom                    10.27 k
    okexchain                 1.16 k
    moonbeam                  0
    boba                      44.01 k
    avax                      565.65 k
    moonriver                 0
    scroll                    219.37 k
    bsc                       6.79 M
    ethereum                  78.57 M
    arbitrum                  4.51 M
    astar                     0
    polygon                   2.28 M
    shiden                    3.29 M
    metis                     84.53 k
    heco                      3.01 k
    
    total                    102.40 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
hi @Dominator008, thanks for the PR, sorry but I am gonna insist on reverting lint/formatting changes, I am tired of reviewing more code than I have to

**Comment by g1nt0ki** [comment]
included your changes here :vulcan_salute:

**Comment by g1nt0ki** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters/commit/a42f97ea2ecf3f619ad59ad55cea70a3f2984145

**Comment by Dominator008** [comment]
Thanks!

**Pull request closed without merging**
