### PR TITLE
Add nutbox TVL

### PR DESCRIPTION
**Pull request by terryyyyyy**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Twitter Link:
 https://twitter.com/NutboxDao

##### Website Link: 
https://app.nutbox.io

##### Logo (High resolution, will be shown with rounded borders):
nutcoin

##### Current TVL:
-- bsc --
Total: 21.68 k

-- enuls --
Total: 0

-- Moonbeam -- 
Total: 0

-- Astar --
Total: 0

##### Chain:
BSC
Enuls
Moonbeam
Astart

##### Short Description (to be shown on DefiLlama):
Nutbox is a staking DAO platform for everyon. Every DAO can issue their token easily and open staking pool easily.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
[Liquid Staking](https://defillama.com/protocols/Liquid%20Staking)

##### methodology (what is being counted as tvl, how is tvl being calculated):
Get tokens price from main DEX from the blockchain. And get the amount of staking Tokens of our pool. Then calculate the TVL

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/nutbox exports TVL: 
        
 
 
    bsc                       40.57 k
    enuls                     0
    
    total                    40.57 k

**Comment by llamatester** [comment]
Error while running adapter at projects/nutbox: 
        
 
  
    
    
    ReferenceError: balances is not defined
    Truncated error stack:
    
        at enulsTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/nutbox/index.js:167:5)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)
        at async Promise.all (index 5)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by llamatester** [comment]
The adapter at projects/nutbox exports TVL: 
        
 
 
    bsc                       21.68 k
    enuls                     0
    
    total                    21.68 k

**Comment by g1nt0ki** [comment]
@terryyyyyy thanks for the PR. I have refactored it a bit here to rely on logs instead: https://github.com/DefiLlama/DefiLlama-Adapters/pull/6251

Also, since you provide staking infrastructure, I have moved it to staking instead of tvl

Can you review it? if you are fine with the changes, I will merge the other PR

**Comment by terryyyyyy** [comment]
Hi:
	Thank for your refactory of the code, yes please merge the PR.

**Pull request closed without merging**
