### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by intswapamm**
---
##### Name (to be shown on DefiLlama):

Intswap 

##### Twitter Link:

https://twitter.com/Intswap_amm

##### List of audit links if any:

https://github.com/Vital-block/Smart-Contract-Audit/blob/main/INTSWAP%20CONTRACT%20AUDITING%20REPORT.pdf

##### Website Link:

https://intswap.io/

##### Logo (High resolution, will be shown with rounded borders):

https://github.com/Intswap-Labs/intswap-core-v1/blob/main/assets/intswapLogo.jpg

##### Current TVL:

$ 1.67 k

##### Treasury Addresses (if the protocol has treasury)

No

##### Chain:

Zksync Era

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

No

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

No

##### Short Description (to be shown on DefiLlama):

The first multichain NFT AMM enables LP Mining by staking NFT/FT LP Tokens to earn compound trading fee, royalty fee and beyond.

##### Token address and ticker if any:

Not yet

##### Category (full list at https://defillama.com/categories) *Please choose only one:

NFT Marketplace

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

No

##### forkedFrom (Does your project originate from another project):

No

##### methodology (what is being counted as tvl, how is tvl being calculated):

Sum up all the ETH in pools

##### Github org/user (Optional, if your code is open source, we can track activity):

https://github.com/Intswap-Labs/intswap-core-v1

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/intswap exports TVL: 
        
 
 
    era                       1.67 k
    
    total                    1.67 k

**Comment by g1nt0ki** [comment]
hi @intswapamm 

Thanks for the PR, I refactored it here but I am getting much lower tvl: https://github.com/DefiLlama/DefiLlama-Adapters/pull/7228

is there some bug in my code or in your graph?

**Comment by intswapamm** [comment]
> hi @intswapamm
> 
> Thanks for the PR, I refactored it here but I am getting much lower tvl: #7228
> 
> is there some bug in my code or in your graph?


We include the value of NFT when calculating tvl, so similar to other FT AMMs, tvl = 2 * sum(all pools' eth bal), and in order to deal with non-standard NFT, there is another factory for generating large tokenId types NFT AMM pair, which address is 0x92e86E8a37c0D823baA521cA78545badD927d8C5.

**Comment by g1nt0ki** [comment]
> > hi @intswapamm
> > Thanks for the PR, I refactored it here but I am getting much lower tvl: #7228
> > is there some bug in my code or in your graph?
> 
> We include the value of NFT when calculating tvl, so similar to other FT AMMs, tvl = 2 * sum(all pools' eth bal), and in order to deal with non-standard NFT, there is another factory for generating large tokenId types NFT AMM pair, which address is 0x92e86E8a37c0D823baA521cA78545badD927d8C5.

thought so, but yours is still higher like 3 * eth value instead of 2 *

**Comment by g1nt0ki** [comment]
merged the other PR with 2x eth value

**Pull request closed without merging**
