### PR TITLE
New Caviar V2 adapter

### PR DESCRIPTION
**Pull request by chasebrownn**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed):  (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

caviar-3

##### Short Description (to be shown on DefiLlama):

Caviar is the liquid wrapper for vePEARL on re.al. Stake and claim USDC rewards daily, exit at any time.

##### Token address and ticker if any:
0xB08F026f8a096E6d92eb5BcbE102c273A7a2d51C
- CVR

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/pearl-caviar exports TVL: 
        
 
 
    real                      64.52 M
    
    total                    64.52 M

**Comment by chasebrownn** [comment]
Logo: 
image

**Comment by chasebrownn** [comment]
Twitter: https://twitter.com/PearlFi_

Note: Please include this adapter under PearlFi

**Comment by g1nt0ki** [comment]
@chasebrownn thanks for the PR, I added it under existing listing.

**Pull request closed without merging**
