### PR TITLE
Create moonbase.js

### PR DESCRIPTION
**Pull request by TheMoonBaseAlpha**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Moonbase Alpha

##### Twitter Link:
https://twitter.com/MBaseAlpha

##### List of audit links if any:
https://www.rdauditors.com/wp-content/uploads/2023/03/Moonbase-Alpha-Security-Audit-Report-1.pdf

##### Website Link:
https://exchange.themoonbase.app/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://res.cloudinary.com/dneze7unl/image/upload/v1680692758/logo_wprsfs.png

##### Current TVL:
6.11 k

##### Chain:
Arbitrum

##### Short Description (to be shown on DefiLlama):
Moonbase Alpha is an all in one decentralized haven for everything blockchain.
The Moon is just the beginning for this high velocity rocket charged Exchange,
Launchpad, DAO, Farms, Staking, Lending and NFT.

##### Token address and ticker if any:
0xB536AE2B2Ed085eA0197C67e3948b7cBF40010c3

##### Category (full list at https://defillama.com/categories) *Please choose only one:
DEXES

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### forkedFrom (Does your project originate from another project):
Uniswap V2

##### methodology (what is being counted as tvl, how is tvl being calculated):
AMM

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/moonbase.js exports TVL: 
        
 
 
    arbitrum                  6.11 k
    
    total                    6.11 k

**Comment by llamatester** [comment]
The adapter at projects/moonbase.js exports TVL: 
        
 
 
    arbitrum                  6.18 k
    
    total                    6.18 k

**Comment by TheMoonBaseAlpha** [comment]
@g1nt0ki  

Hi,
Recently Moonbase Alpha is being added in the defilama but mistakenly you have spelled MROCK wrong.
Please update the token symbol from MROOK to MROCK.

Token address is here: https://arbiscan.io/address/0xB536AE2B2Ed085eA0197C67e3948b7cBF40010c3

**Comment by Define101** [comment]
Hello TheMoonBaseAlpha, I am sorry about this.
The correct symbol should be live within 1 hour

**Pull request merged**
