### PR TITLE
Add Solid World protocol

### PR DESCRIPTION
**Pull request by andreistefanwork**
**NOTE**

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Solid World

##### Twitter Link:
https://twitter.com/solidworldhq

##### List of audit links if any:
https://github.com/Dedaub/audits/tree/main/Solid%20World

##### Website Link:
https://www.solid.world/

##### Logo (High resolution, will be shown with rounded borders):
https://app.solid.world/favicon.png

##### Current TVL:
$1.07M

##### Chain:
Polygon

##### Short Description (to be shown on DefiLlama):
Solid World is a commodity production financing platform that makes prepaid carbon markets truly liquid and transparent

##### Token address and ticker if any:
https://polygonscan.com/address/0xEF6Ab48ef8dFe984FAB0d5c4cD6AFF2E54dfdA14

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
https://polygonscan.com/address/0xc0Dadf5ecB92A77F476e3b5F3b8fFD6D66928293

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is a measure of the health of the Solid World ecosystem. It's the total amount of value that is locked up in our staking contract, and it's calculated by adding up the value of all the LP tokens that are staked. The LP tokens represent the amount of liquidity that has been provided to the Solid World platform.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/solid-world

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/solid-world exports TVL: 
        
 
 
    polygon                   1.07 M
    
    total                    1.07 M

**Comment by andreistefanwork** [comment]
Is it possible to create a new protocol category?

**Comment by g1nt0ki** [comment]
> Is it possible to create a new protocol category?

hi @andreistefanwork this falls under 'Yield' category, in the future if there are more products of similar kind, we can create 'RWA Yield' category.

The code looks good, one question though: who mints/issues CRISP tokens? if it is your tam, we can count CRISP supply as tvl, this part as pool2 and the category as RWA

**Comment by andreistefanwork** [comment]
hey @g1nt0ki, yes we mint the CRISP-M tokens based on real world assets (mangrove forward carbon credits)

just to make sure we're on the same page, do you suggest us exporting: 
```
{
   tvl: ... the value in USD of CRISP-M total supply ...,
   pool2: ...the exact logic we currently have in the async function tvl(...)...
}
```
?

**Comment by g1nt0ki** [comment]
yup, exactly. And your category would be RWA, sound good?

**Comment by llamatester** [comment]
The adapter at projects/solid-world exports TVL: 
        
 
 
    polygon                   529.07 k
    polygon-pool2             1.07 M
    pool2                     1.07 M
    
    total                    529.07 k

**Comment by andreistefanwork** [comment]
yep, sounds great!

**Pull request merged**
