### PR TITLE
Add OmniBTC

### PR DESCRIPTION
**Pull request by 0xdigiscore**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
OmniBTC

##### Twitter Link:
https://twitter.com/OmniBTC

##### Website Link:
https://omnilending.omnibtc.finance/lending

##### Logo
OmniBTC
 (High resolution, will be shown with rounded borders):

##### Current TVL:
1.66M

##### Chain:
Sui

##### Short Description (to be shown on DefiLlama):
A decentralized cross-chain swap and lend/borrow platform, aiming to connect and unify all the on-chain liquidity.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/orgs/OmniBTC/repositories

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/omnibtc exports TVL: 
        
 
 
    sui                       1.66 M
    
    total                    1.66 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
hi, thanks for the PR, but we dont like relying on app api for tvl computation, it is blackbox and tend to break over time, can you turn it into on chain? you can look at other sui adapters for reference

**Comment by 0xdigiscore** [comment]
In fact, we refer to deepbook-sui, they also provide interfaces:
https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/deepbook-sui/index.js

**Comment by 0xdigiscore** [comment]
> hi, thanks for the PR, but we dont like relying on app api for tvl computation, it is blackbox and tend to break over time, can you turn it into on chain? you can look at other sui adapters for reference

In fact, we refer to deepbook-sui, they also provide interfaces:
https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/deepbook-sui/index.js

**Comment by llamatester** [comment]
Error while running adapter at projects/omnibtc: 
        
 
  
    
    
    Error: 
        Found export keys that were not part of specification: borrow
    
        List of valid keys: 
    				
    				tvl
    				staking
    				methodology
    				pool2
    				misrepresentedTokens
    				fetch
    				timetravel
    				borrowed
    				start
    				doublecounted
    				treasury
    				hallmarks
    				incentivized
    				offers
    				deadFrom
    				broken
    				ownTokens
    				vesting

**Comment by llamatester** [comment]
Error while running adapter at projects/omnibtc: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'data')
    Truncated error stack:
    
        at call (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/sui.js:78:41)
        at async Object.getDynamicFieldObject (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/sui.js:54:11)
        at async Promise.all (index 1)
        at async fetchDataBasedOnPoolId (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/omnibtc/index.js:27:10)
        at async borrow (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/omnibtc/index.js:67:23)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 1)
        at async Promise.all (index 1)

**Comment by llamatester** [comment]
Error while running adapter at projects/omnibtc: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'data')
    Truncated error stack:
    
        at call (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/sui.js:78:41)
        at async Object.getDynamicFieldObject (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/chain/sui.js:54:11)
        at async Promise.all (index 0)
        at async fetchDataBasedOnPoolId (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/omnibtc/index.js:27:10)
        at async tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/omnibtc/index.js:61:23)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)

**Comment by llamatester** [comment]
The adapter at projects/omnibtc exports TVL: 
        
 
 
    sui-borrowed              1.06 M
    sui                       1.80 M
    borrowed                  1.06 M
    
    total                    1.80 M

**Comment by 0xdigiscore** [comment]
> hi, thanks for the PR, but we dont like relying on app api for tvl computation, it is blackbox and tend to break over time, can you turn it into on chain? you can look at other sui adapters for reference

Hello, we have already used the calculation method on the chain, please review again.

**Comment by llamatester** [comment]
The adapter at projects/omnibtc exports TVL: 
        
 
 
    sui-borrowed              1.06 M
    sui                       1.80 M
    borrowed                  1.06 M
    
    total                    1.80 M

**Comment by g1nt0ki** [comment]
> > hi, thanks for the PR, but we dont like relying on app api for tvl computation, it is blackbox and tend to break over time, can you turn it into on chain? you can look at other sui adapters for reference
> 
> Hello, we have already used the calculation method on the chain, please review again.

hi @0xdigiscore , thanks for turning it on chain, I made a refactor here where available liquidity is counted as tvl instead of token supplied, we apply this methodology to all lending protocols: https://github.com/DefiLlama/DefiLlama-Adapters/pull/7168

**Comment by 0xdigiscore** [comment]
> > > hi, thanks for the PR, but we dont like relying on app api for tvl computation, it is blackbox and tend to break over time, can you turn it into on chain? you can look at other sui adapters for reference
> > 
> > 
> > Hello, we have already used the calculation method on the chain, please review again.
> 
> hi @0xdigiscore , thanks for turning it on chain, I made a refactor here where available liquidity is counted as tvl instead of token supplied, we apply this methodology to all lending protocols: #7168

Ok, thx for your great work! Have a nice day!

**Pull request closed without merging**
