### PR TITLE
Add "JellyBeanSwap"

### PR DESCRIPTION
**Pull request by jellybeanswap**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
JellyBeanSwap

##### Twitter Link:
https://twitter.com/jellybeanswap

##### Website Link:
https://jellybeanswap.xyz

##### Logo (High resolution, will be shown with rounded borders):
https://github.com/cyberminter/jellybeanswap-branding/blob/main/brand/logo.png

##### Current TVL:
--- bsc ---
WBNB                      46.01051118703294
Total: 46.01051118703294
27611,83 USD

##### Chain:
BSC

##### Short Description (to be shown on DefiLlama):
Jelly bean swap is an BSC DEX made by Cyberminter the makers of the 1800 member cryptocurrency institute.  The dapp allows users to trade on the BSC blockchain. 

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### methodology (what is being counted as tvl, how is tvl being calculated):
Uses factory(0x320827adb3f759a386348b325c54803b2b3a7572) address and whitelisted tokens address to find and price Liquidity Pool pairs

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/cyberminter

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/jellybeanswap exports TVL: 
        
 
 
    bsc                       47.64258449051784
    
    total                    47.64258449051784

**Comment by jellybeanswap** [comment]
Thanks for merging. Also I would like to inquire about the Defillama whitelist for Blowfish within my protocol. Where can I find information regarding the conditions and other related data? Or is the whitelist given automatically after listing on defillama?

**Comment by g1nt0ki** [comment]
what is blowfish? what whitelist?

**Comment by jellybeanswap** [comment]
> what is blowfish? what whitelist?
Something like having a domain hosted on defillama be on the whitelist. We couldn't find more information. If you're not aware of this, could you clarify it with your team?
src:
https://github.com/DefiLlama/url-directory
https://docs.blowfish.xyz/reference/scan-domain-1
Good response:
`[
  {
    "domain": "",
    "status": "PROCESSED",
    "riskScore": 0,
    "labels": [
      "source=defi_llama_whitelist"
    ],
    "warnings": []
  }
]`

**Comment by g1nt0ki** [comment]
sorry, not sure what criteria they use for whitelist, you need to as them

**Pull request merged**
