### PR TITLE
glyph exchange tvl and staking data

### PR DESCRIPTION
**Pull request by bswan-glyph**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Glyph Exchange

##### Twitter Link:
https://twitter.com/glyph_exchange

##### Website Link:
https://glyph.exchange

##### Logo (High resolution, will be shown with rounded borders):
glyph-exchange-logo

##### Current TVL:
550k usd

##### Chain:
Core

##### Short Description (to be shown on DefiLlama):
Glyph Exchange is the flagship DEX for Bitcoin DeFi on the Core blockchain. The platform drives EVM liquidity to amplify Bitcoin-Powered crypto asset trading,c onnecting EVMs to Bitcoin Building Bitcoin-Fi on CoreDAO

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/GlyphExchange: 
        
 
  
    
    
    Invalid value provided for argument `block`: Object({"number": Null})
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/graphql-request/dist/index.js:359:31

**Comment by g1nt0ki** [comment]
thanks for the PR, fixed it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/9506

**Comment by bswan-glyph** [comment]
Thanks for defillama team help, There is a problem. We still have staking data in our code, but you may have accidentally overwritten it.

Staking contract
`CoreStaking: 0x6bf16B2645b13db386ecE6038e1dEF76d95696fc`
stake token is native core and stCORE
`stCORE: 0xb3A8F0f0da9ffC65318aA39E55079796093029AD`

When we wrote the staking adapter, we found that `helper/staking.js` could not obtain the price of stCORE, resulting in only the staking tvl of the native core being calculated.

Our exchange has related pairs

```
SwapFactory: 0x3E723C7B6188E8Ef638DB9685Af45c7CB66f77B9

USDT/WCORE: 0xee37760ed192fcee0abf03ee8ceaba4ac2e4b6f3
stCORE/WCORE: 0x40320a9b3e8458ce3dd3e0ad79fc5208f00510a3

USDT: 0x900101d06a7426441ae63e9ab3b9b0f63be145f1
stCORE: 0xb3a8f0f0da9ffc65318aa39e55079796093029ad
wCORE: 0x191e94fa59739e188dce837f7f6978d84727ad01
```

Could you help me adjust the staking adapter? Finally, thanks again to the defillama team

**Comment by g1nt0ki** [comment]
sorry, it is fixed now

**Pull request closed without merging**
