### PR TITLE
add bevmswap-v1

### PR DESCRIPTION
**Pull request by opiatoon-o**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bevmswap-v1 exports TVL: 
        
 
 
    bevm                      48.88 k
    
    total                    48.88 k

**Comment by g1nt0ki** [comment]
can you please fill in the project details in the description field?

**Comment by g1nt0ki** [comment]
@opiatoon-o thanks for the PR, included your adapter here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/05a0013bf3737d5fa51e7f6f3545a38686040351

**Comment by opiatoon-o** [comment]
pull request have already closed, How should I fill out the form listing info?

**Comment by opiatoon-o** [comment]
> pull request have already closed, How should I fill out the form listing info?
@g1nt0ki


> **NOTE**
> 
> #### Please enable "Allow edits by maintainers" while putting up the PR.
> > * If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> > * If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.
> 
> 1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
> 2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
> 3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
> 4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
> 5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
> 6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap
> 
> ##### Name (to be shown on DefiLlama):
Bevmswap
> ##### Twitter Link:
https://twitter.com/BEVMSwap
> ##### List of audit links if any:
https://github.com/Bevmswap/audits
> ##### Website Link:
https://bevmswap.xyz
> ##### Logo (High resolution, will be shown with rounded borders):
https://bevmswap.xyz/logo-512.png
> ##### Current TVL:
48.88 k 
> ##### Treasury Addresses (if the protocol has treasury)
> ##### Chain:
bevm
> ##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
> ##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
> ##### Short Description (to be shown on DefiLlama):
Bevmswap is an AMM DEX on BTC L2, EVM-Compatible.

Bevmswap focuses on providing the best trading experience and superior liquidity efficiency for BTC ecosystem DeFi users through constant function market makers (CFMM) ,centralized liquidity protocol, and VeToken governance model.

Unlike other DEXs, Bevmswap supports liquidity pools made up of yield tokens, allowing contributors to earn double returns from both yield token profits and providing liquidity.
> ##### Token address and ticker if any:
> ##### Category (full list at https://defillama.com/categories) *Please choose only one:
> ##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
> ##### Implementation Details: Briefly describe how the oracle is integrated into your project:
> ##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
> ##### forkedFrom (Does your project originate from another project):
> ##### methodology (what is being counted as tvl, how is tvl being calculated):
> ##### Github org/user (Optional, if your code is open source, we can track activity):

**Pull request closed without merging**
