### PR TITLE
add cygnusdao on zkevm

### PR DESCRIPTION
**Pull request by swan-of-bodom**
Adding `polygon_zkevm` to CygnusDAO

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/cygnusdao exports TVL: 
        
 
 
    polygon_zkevm-borrowed    0
    arbitrum-borrowed         1.40 k
    polygon-borrowed          3.68 k
    arbitrum                  3.40 k
    polygon_zkevm             2.31 k
    polygon                   11.68 k
    borrowed                  5.07 k
    
    total                    17.39 k

**Comment by llamatester** [comment]
The adapter at projects/cygnusdao exports TVL: 
        
 
 
    polygon-borrowed          3.68 k
    polygon_zkevm-borrowed    369.04801333399996
    arbitrum-borrowed         1.40 k
    arbitrum                  3.40 k
    polygon                   11.69 k
    polygon_zkevm             2.31 k
    borrowed                  5.45 k
    
    total                    17.40 k

**Comment by swan-of-bodom** [comment]
I forgot to add the total borrows calculation on zkEVM. Also added the native USDC deployed on zkEVM as `USDC_CIRCLE` on coreAssets and fixed the USDC token on Arbitrum, we are using USDC_CIRCLE on arb.

https://polygon.technology/blog/bridged-usdc-standard-contracts-are-live-on-polygon-zkevm

```
Legacy bridged USDC: ​​0xA8CE8aee21bC2A48a5EF670afCc9274C7bbbC035

New bridged USDC: 0x37eAA0eF3549a5Bb7D431be78a3D99BD360d19e5
```

**Comment by llamatester** [comment]
The adapter at projects/cygnusdao exports TVL: 
        
 
 
    polygon-borrowed          3.68 k
    polygon_zkevm-borrowed    378.974993
    polygon                   11.74 k
    arbitrum-borrowed         1.40 k
    polygon_zkevm             2.45 k
    arbitrum                  8.34 k
    borrowed                  5.46 k
    
    total                    22.52 k

**Comment by g1nt0ki** [comment]
@swan-of-bodom thanks for the PR, made  a tiny refactor so borrowed amount is counted as USDT everywhere (so we dont have change tokens based on chain)

**Pull request merged**
