### PR TITLE
Fix/sanctum lsts tvl calculation

### PR DESCRIPTION
**Pull request by alkinemk**
the same way some protocols issuing an LST count this LST in their money market, stake pools infinity TVL should count towards the total stake pool TVL

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/sanctum-validator-lsts: 
        
 
  
    
    
    Error: 429 Too Many Requests: {"jsonrpc":"2.0","error":{"code":-32429,"message":"exceeded limit for getProgramAccounts"}}
    Truncated error stack:
        at ClientBrowser.callServer (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@solana/web3.js/lib/index.cjs.js:4944:18)

**Comment by g1nt0ki** [comment]
"the same way some protocols issuing an LST count this LST in their money market" 

No, we dont, it might be included in money market part of the protocol, but excluded from the parent protocol: for example https://defillama.com/protocol/benqi#information overall tvl is lower than LSD + money markets

**Comment by alkinemk** [comment]
interesting, how do you do it with marginfi and their LST? it almost adds up

is deducting from overall tvl but reflecting subprotocols tvl correctly an option?

**Comment by alkinemk** [comment]
@g1nt0ki 

interesting, how do you do it with marginfi and their LST on solana? it almost adds up

is deducting from overall tvl but reflecting subprotocols tvl correctly an option?

**Comment by g1nt0ki** [comment]
we have added code to exclude blacklist/remove LST value from overall tvl.

sorry, dont think it applies in your case. https://defillama.com/protocol/sanctum#information shows value of all three together.

**Pull request closed without merging**
