### PR TITLE
Sakka

### PR DESCRIPTION
**Pull request by Sakka-Finance**
**NOTE**

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Sakka.Finance

##### Twitter Link:
https://twitter.com/SakkaFinance

##### List of audit links if any:
https://secureblock.io/reports/d64e1f68-0d7b-4f7f-93e7-7cfdabfabfcf.pdf

##### Website Link:
https://www.sakka.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://github.com/Sakka-Finance/SAK/blob/main/SAK.png

##### Chain:
Binance Smart Chain, Klaytn

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
https://coinmarketcap.com/currencies/sakka-finance/

##### Short Description (to be shown on DefiLlama):
Sakka is a Revolutionary Defi & Web 3.0 Betting Platform based on Binance Smart Chain and Klaytn. Users can earn by staking or betting on their preferred national team in World Cup 2022.

##### Token address and ticker if any:
0x37CDC46C78Cf403F1Da8a1eeBCffB3ed1DD01868

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yields

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
None

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is calculated by the sum of the total staking value and the amount users put in the betting pool

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/Sakka-Finance: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:200:11

**Comment by llamatester** [comment]
The adapter at projects/sakka exports TVL: 
        
 
 
    bsc-staking               1.20 k
    bsc-pool2                 4.00 k
    bsc                       79.74 k
    klaytn-pool2              0
    klaytn-staking            0
    klaytn                    19.45 k
    staking                   1.20 k
    pool2                     4.00 k
    
    total                    99.20 k

**Review by g1nt0ki — COMMENTED** [review]
@Sakka-Finance thanks for the PR, can you clarify one thing, where are the staked assets stored? I cant find it on the masterchef contract

**Comment by g1nt0ki** [comment]
closing this as there was no response

**Pull request closed without merging**
