### PR TITLE
update contracts

### PR DESCRIPTION
**Pull request by coslendteam**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/coslend exports TVL: 
        
 
 
    evmos-borrowed            0.748985
    evmos                     6.518281
    borrowed                  0.748985
    
    total                    6.518281

**Comment by g1nt0ki** [comment]
@coslendteam what about existing borrowed tvl: https://coslend.com/#/markets 
Maybe we can count the tvl of both?

**Comment by g1nt0ki** [comment]
the code: 

    const { usdCompoundExports } = require("../helper/compound");
    const sdk = require('@defillama/sdk')

    const getExport = comptroller => usdCompoundExports(
      comptroller,
      "evmos",
      undefined, undefined, {
      blacklist: [
        '0x269bd2505045947d410582128bc65105d285e66e', // MockToken
      ]
    }
    )
    const comptrollers = ['0x2C8b48Dc777C26dc857E1040D8ef3Bdd3B1ef499', '0x5b32B588Af5F99F4e5c4038dDE6BDD991024F650'].map(getExport)

    module.exports = {
      evmos: {
        tvl: sdk.util.sumChainTvls(comptrollers.map(i => i.tvl)),
        borrowed: sdk.util.sumChainTvls(comptrollers.map(i => i.borrowed)),
      },
    };

**Comment by coslendteam** [comment]
@g1nt0ki Due to security problem, we have deprecated the whole set of old smart contracts, please don't count both, just the new one.

**Pull request merged**
