### PR TITLE
Add support adapter for terrafloki on terra blockchain

### PR DESCRIPTION
**Pull request by TerraFloki**
Twitter Link:
https://twitter.com/TerraFloki

List of audit links if any:
Website Link:
https://terrafloki.io/

Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://terrafloki.io/terrafloki_logo.png

Current TVL:
$ 3,508,070.34

Chain:
Terra Blockchain

Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
Short Description (to be shown on DefiLlama):
TerraFloki is the 2nd Decentralised Exchange (DEX) launched on Terra. Main utility of TerraFloki DEX is trading $TFLOKI and NFT Tickets (needed to ensure the NFT-as-a-Subscription model of NFT distribution). NFTs are essential building blocks of the Flokiverse – an emerging P2E ecosystem with an open economy.

Token address and ticker if any:
TFLOKI terra1u2k0nkenw0p25ljsr4ksh7rxm65y466vkdewwj

Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Dexes

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
No

forkedFrom (Does your project originate from another project):
No

methodology (what is being counted as tvl, how is tvl being calculated):
TVL is the sum of value locked in TerraFloki stakings means
- Liquidity pool for trading pair TFLOKI/UST
- Staking of TFLOKI tokens for ticket farming
- Staking of LP for ticket farming

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Can this be separated out into 3 different module.exports:

pool2: Liquidity pool for trading pair TFLOKI/UST
staking: Staking of TFLOKI tokens for ticket farming
tvl: Staking of LP for ticket farming

**Comment by TerraFloki** [comment]
@waynebruce0x Done 😄

**Comment by TerraFloki** [comment]
Hi @waynebruce0x why just staking of LP for ticket farming is counted as a general TVL. Shouldn't it be staking of TFLOKI as well as trading pair as well? Can we sum them up? This will make the data more reliable.

**Comment by waynebruce0x** [comment]
We split native token staking and pool2 (where one half of the pool is native token) into separate exports. This was a community request and enables users to filter out parts of TVL if they want to

**Pull request merged**
