### PR TITLE
Add Lisk adapter

### PR DESCRIPTION
**Pull request by nagdahimanshu**
##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
ID: 1214

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/lisk exports TVL: 
        
 
 
    ethereum                  228.07 M
    
    total                    228.07 M

**Comment by g1nt0ki** [comment]
hi @nagdahimanshu, I have already added an adapter for this: https://github.com/DefiLlama/DefiLlama-Adapters/commit/c8c4e698b9f894de6b33f160f8ab2811dec07c6f

**Comment by g1nt0ki** [comment]
*to display list lisk chain tvl, we need to list defi projects on top of the chain, we automatically aggregate their tvl and show as chain tvl

**Comment by g1nt0ki** [comment]
yes, thats what the adapter I linked to does

**Comment by g1nt0ki** [comment]
*I have removed the blacklist: https://github.com/DefiLlama/DefiLlama-Adapters/commit/4fe936579e573232977287eb065bd2344445119f

**Pull request closed without merging**
