### PR TITLE
Add ChargeDefi adapter

### PR DESCRIPTION
**Pull request by chargedefi**
##### Twitter Link:
https://twitter.com/ChargeDeFi

##### List of audit links if any:
https://www.certik.com/projects/chargedefi

##### Website Link:
https://www.chargedefi.fi/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://www.chargedefi.fi/static/media/charge.53089c19.png

##### Current TVL:
22.5 M

##### Chain:
BSC

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

1. chargedefi-charge
2. chargedefi-static

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

1. chargedefi
2. chargedefi-static

##### Short Description (to be shown on DefiLlama):
ChargeDeFi is a combination of an Algorithmic Stablecoin with rebase mechanics. With Charge the project aims to lay the foundations of a sustainable ecosystem on the Binance smart chain. It features rebasing mechanics to protect the value of the $Static token and keep it pegged to $1 BUSD. We see the rebase mechanic as a temporary solution that can be lowered over time and eventually turned off. Enabling strong guardrails for the project at launch and protecting the ecosystem while the team expands on the use-cases and ecosystem.

##### Token address and ticker if any:

1. $Charge: 0x1C6bc8e962427dEb4106aE06A7fA2d715687395c
2. $Static: 0x7dEb9906BD1d77B410a56E5C23c36340Bd60C983

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Yield

##### methodology (what is being counted as tvl, how is tvl being calculated):
The TVL of Charge Defi is calculated using the Pancake LP token deposits (Static/BUSD and Charge/BUSD), and the Charge deposits found in the Boardroom.

### CODE REVIEW

**Comment by 0xngmi** [comment]
what is static and what relationship does it have with charge?

**Comment by chargedefi** [comment]
ChargeDefi is essentially a seigniorage protocol. 
Static is the dollar token that expands over peg and rebases under. 
Charge is the share token.

**Comment by waynebruce0x** [comment]
Can Charge-BUSD farm be separated out into a separate pool2 export, and Charge boardroom be separated out into a staking export?

**Comment by chargedefi** [comment]
@waynebruce0x done :)

**Pull request merged**
