### PR TITLE
Add Goldlink

### PR DESCRIPTION
**Pull request by 0xnirmal**
##### Name (to be shown on DefiLlama):
GoldlLink

##### Twitter Link:
https://x.com/goldlinkfinance

##### List of audit links if any:
https://github.com/GoldLink-Protocol/goldlink-contracts-v1/tree/main/audits

##### Website Link:
https://app.goldlink.io/

##### Logo (High resolution, will be shown with rounded borders):
https://substackcdn.com/image/fetch/w_176,h_176,c_fill,f_webp,q_auto:good,fl_progressive:steep,g_auto/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fb15c6a14-686c-4a2c-9dfd-ee23da2a9aa4_500x500.png

##### Current TVL:
$818,876.80

##### Chain:
Arbitrum

##### Short Description (to be shown on DefiLlama):
GoldLink Protocol is an institutional-grade prime brokerage protocol on Arbitrum. The protocol provides undercollateralized and non-custodial on-chain lending, offering new levels of sophistication, transparency, and security for institutional borrowers and lenders.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Leveraged Farming

##### methodology (what is being counted as tvl, how is tvl being calculated):
Net Deposits in the GMX Vault

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/GoldLink-Protocol

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/goldlink exports TVL: 
        
 
 
    arbitrum                  818.82 k
    arbitrum-borrowed         164.10 k
    borrowed                  164.10 k
    
    total                    818.82 k

**Comment by llamatester** [comment]
The adapter at projects/goldlink exports TVL: 
        
 
 
    arbitrum                  819.64 k
    arbitrum-borrowed         164.26 k
    borrowed                  164.26 k
    
    total                    819.64 k

**Comment by llamatester** [comment]
The adapter at projects/goldlink exports TVL: 
        
 
 
    arbitrum                  818.83 k
    
    total                    818.83 k

**Comment by g1nt0ki** [comment]
@0xnirmal thanks for the PR, we dont show borrowed for leveraged farming as the money doesnt leave the contract

**Pull request merged**
