### PR TITLE
Add Echo Lending  Adapter

### PR DESCRIPTION
**Pull request by Efrain9502**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Echo Lending

##### Twitter Link:
https://x.com/EchoProtocol_

##### List of audit links if any:
MoveBit

##### Website Link:
https://www.echo-protocol.xyz/

##### Logo (High resolution, will be shown with rounded borders):
https://www.echo-protocol.xyz/images/echo.png

##### Current TVL:
$10

##### Chain:
Aptos

##### Short Description (to be shown on DefiLlama):
Bridge, Restake and Earn Yield from BTC assets on Move

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### methodology (what is being counted as tvl, how is tvl being calculated):
In echo-lending/index.js, tvl and borrowed are exported, representing the total deposits and total borrowings, respectively.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/echo-lending exports TVL: 
        
 
 
    aptos                     0
    aptos-borrowed            0
    borrowed                  0
    
    total                    0

**Comment by Efrain9502** [comment]
Currently, there are only four tokens, with their decimal places as follows: APT: 8, USDT: 6, USDC: 6, and aBTC: 10. Among them, aBTC is a token generated by our cross-chain bridge protocol and is pegged to BTC at a 1:1 ratio.

**Comment by g1nt0ki** [comment]
thanks for the PR, I have refactored and merged it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/11426

**Comment by echo-pro-dev** [comment]
> refactored
Hi, I have a question about the tvl, why did you exclude aBTC for tvl?

**Comment by echo-pro-dev** [comment]
A brief introduction of aBTC, it is a cross-chain token on Aptos, it's 1:1 pegged with BTC, the DefiLlama already recorded its value, refer this PR https://github.com/DefiLlama/DefiLlama-Adapters/pull/11194 .

**Pull request closed without merging**
