### PR TITLE
add cswap-dex

### PR DESCRIPTION
**Pull request by cardanoshield**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

CSWAP DEX

##### Twitter Link: 

https://twitter.com/CswapDEX

##### List of audit links if any:

N/A

##### Website Link:

https://cswap.fi

##### Logo (High resolution, will be shown with rounded borders):

cswap-logo-240x240

##### Current TVL:

$70,030

##### Treasury Addresses (if the protocol has treasury)

addr1q9qsry2sert87tvheethvlggl0uxrzk9tm7vnkv954ljg5vynfm4suge6dyedrh928yejhmgd0xq59dckj8x69pwem2qhw3gln

##### Chain:

Cardano

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

N/A

##### Short Description (to be shown on DefiLlama):

The first DEX for NFTs on Cardano. Instant Liquidity. Powered by an orderbook/AMM hybrid.

##### Token address and ticker if any:

N/A

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Dexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

N/A

##### forkedFrom (Does your project originate from another project):

N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):

Locked ADA + NFT stock * Buy Price for each pool

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/cswap-dex exports TVL: 
        
 
 
    cardano                   69.84 k
    
    total                    69.84 k

**Comment by g1nt0ki** [comment]
hi, can you update code to compute tvl on chain instead of relyig on your api?

**Comment by cardanoshield** [comment]
> hi, can you update code to compute tvl on chain instead of relyig on your api?

It is a good point, our team can definitely get this done but don't have the bandwidth to do it at the moment.

Would it possible for this to be merged for now just so we have the data in place going forward?

**Comment by cardanoshield** [comment]
> hi, can you update code to compute tvl on chain instead of relyig on your api?

It is a good thought, however, the problem is that our current code relies on a commerical Blockfrost API license and we don't want to expose our blockfrost API keys...

**Comment by cardanoshield** [comment]
> hi, can you update code to compute tvl on chain instead of relyig on your api?

As I said above, we have a dependency on blockfrost API for computing these values, and we can't expose our blockfrost keys...Any suggestions? Would like to get this merged ASAP. Thanks!

**Comment by cardanoshield** [comment]
Other cardano dapps such as levvy finance also use self-published figures for this adapter.

**Comment by g1nt0ki** [comment]
> > hi, can you update code to compute tvl on chain instead of relyig on your api?
> 
> As I said above, we have a dependency on blockfrost API for computing these values, and we can't expose our blockfrost keys...Any suggestions? Would like to get this merged ASAP. Thanks!

hi, sorry, missed this comment, you dont need to expose your project api keys: you can use ours: https://github.com/DefiLlama/DefiLlama-Adapters/blob/e86e45f3d846223b995b9a4db03ed34d94d8d349/projects/helper/chain/cardano/blockfrost.js

**Comment by cardanoshield** [comment]
Great! I'll work with the team on getting the on-chain code in here.

> > > hi, can you update code to compute tvl on chain instead of relyig on your api?
> > 
> > 
> > As I said above, we have a dependency on blockfrost API for computing these values, and we can't expose our blockfrost keys...Any suggestions? Would like to get this merged ASAP. Thanks!
> 
> hi, sorry, missed this comment, you dont need to expose your project api keys: you can use ours: https://github.com/DefiLlama/DefiLlama-Adapters/blob/e86e45f3d846223b995b9a4db03ed34d94d8d349/projects/helper/chain/cardano/blockfrost.js

**Comment by g1nt0ki** [comment]
closing this for now, please put up a new PR when you are ready, and comment here if you need my assistance with anything.

**Pull request closed without merging**
