### PR TITLE
fix loxodrome

### PR DESCRIPTION
**Pull request by wangjj250wo**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Loxodrome

##### Twitter Link:
https://twitter.com/_Loxodrome

##### List of audit links if any:
https://app.secure3.io/203ca47f68/preview

##### Website Link:
https://dapp.loxodrome.xyz

##### Logo (High resolution, will be shown with rounded borders):
https://bafkreiesz623spibua5hpbwp2cxyv3yljykxn7vgxl5hmhgkasxro3opma.ipfs.nftstorage.link/

##### Current TVL:
88.7k

##### Treasury Addresses (if the protocol has treasury)
none

##### Chain:
IoTeX

##### Short Description (to be shown on DefiLlama):
Loxodrome is a pioneering DePIN-Focused Dex on the IoTeX, 
establishing itself as the first native liquidity marketplace focused on DePIN.

##### Token address and ticker if any:
0xE18568f86dA705F8Ee9f89fA87162216739BDC56

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
none
##### Implementation Details: Briefly describe how the oracle is integrated into your project:
none
##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
none
##### forkedFrom (Does your project originate from another project):
Thena

##### methodology (what is being counted as tvl, how is tvl being calculated):
1. Get pair information:
Use the getPairs function to get pair information from the specified factory contract, including the address of each pair.
2. getTokenInfo:
Use the API's multiCall function to get the addresses of the two tokens in each pair, and to get the voter addresses associated with each pair.
3. Build the list of owner tokens:
Organize the obtained token information into a list of owner tokens, where each element contains the addresses of the two tokens and the address of the corresponding transaction pair.
4. Calculate TVL:
Call the sumTokensExport function, passing in the API object, the balance information, the list of owner tokens, and the unwrapped LP flag to calculate the total TVL.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/loxodrome exports TVL: 
        
 
 
    iotex                     84.89 k
    
    total                    84.89 k

**Comment by g1nt0ki** [comment]
why are you checking for tokens on the gauge? when user provides LP, it never goes there right? only the LP token is deposited there?

**Comment by llamatester** [comment]
The adapter at projects/loxodrome exports TVL: 
        
 
 
    iotex                     85.66 k
    
    total                    85.66 k

**Comment by llamatester** [comment]
The adapter at projects/Loxodrome exports TVL: 
        
 
 
    iotex                     85.66 k
    
    total                    85.66 k

**Comment by wangjj250wo** [comment]
Sorry，You're right. I'll remove checking for tokens on gauge and resubmitted

**Pull request closed without merging**
