### PR TITLE
Add LINKSWAP adapter

### PR DESCRIPTION
**Pull request by giovannidisiena**
This PR adds an adapter for the YF Link community-governed automated market maker LINKSWAP.

### CODE REVIEW

**Comment by giovannidisiena** [comment]
> Please let me know:
> 
> * Project bio
> * Audit (if any)
> * Twitter
> * Main Website

@DefiLlama thanks for the quick merge, please see below :)

* Bio: LINKSWAP is an Automated Market Maker focused on empowering the Chainlink community.
* Audit: [Quantstamp](https://certificate.quantstamp.com/full/linkswap).
* Twitter: [@YFLinkio](https://twitter.com/yflinkio).
* Main site: [yflink.io](https://yflink.io), trade on [linkswap.app](https://linkswap.app).

**Comment by DefiLlama** [comment]
Listed, thanks for your time!

**Comment by giovannidisiena** [comment]
@DefiLlama thanks for the quick listing! Just a couple of small changes if you don't mind?

* YFLink should be changed to YF Link (with the space)
* Could we include links to both linkswap.app and the Quantstamp audit please?
* The current TVL does not include our governance vault, which will have a separate PR up soon

**Comment by giovannidisiena** [comment]
Hi @DefiLlama, in addition to the above request I have now opened #18. Please test and let me know if any further changes need to be made. Thanks!

**Comment by DefiLlama** [comment]
Updated

**Pull request merged**
