### PR TITLE
add project

### PR DESCRIPTION
**Pull request by xbankingorg**
Name: XBANKING
Twitter Link: https://x.com/strongbuycrypto
List of audit links if any: -
Website Link: https://xbanking.org/
Logo: https://xbanking.org/logo.png
Current TVL: $190.430.000 TVL
Treasury Addresses (if the protocol has treasury): No
Chain: No
Coingecko ID: https://www.coingecko.com/en/coins/xbanking
Coinmarketcap ID: No
Short Description (to be shown on DefiLlama): Non-custodial staking & liquid pools provider.
Token address and ticker if any: 0x33E80a92a9Ea73dD02f6e732D1702d58c68388cA XB
Category: Staking Pool
Oracle used: Own
forkedFrom: No
Github org/user: https://github.com/xbankingorg

NOTE

If you would like to add a volume adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
If you would like to add a liquidations adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.
Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
Please enable "Allow edits by maintainers" while putting up the PR.
Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
Please fill the form below only if the PR is for listing a new protocol else it can be ignored/replaced with reason/details about the PR
For updating listing info It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can edit it there and put up a PR
Do not edit/push package-lock.json file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/xbanking: 
        
 
  
    
    
    TypeError: sumTokensAccount is not a function
    Truncated error stack:
    
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/xbanking/index.js:8:9)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:53:29)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:149:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:137:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:132:44

**Comment by llamatester** [comment]
Error while running adapter at projects/xbanking: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading '1')
    Truncated error stack:
    
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/xbanking/index.js:19:60)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:53:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:149:9
        at async Promise.all (index 0)
        at async Promise.all (index 2)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:194:3

**Comment by llamatester** [comment]
Error while running adapter at projects/xbanking: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading '1')
    Truncated error stack:
    
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/xbanking/index.js:20:60)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:53:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:149:9
        at async Promise.all (index 0)
        at async Promise.all (index 2)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:194:3

**Comment by llamatester** [comment]
Error while running adapter at projects/xbanking: 
        
 
  
    
    
    ReferenceError: tonTotalSupply is not defined
    Truncated error stack:
    
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/xbanking/index.js:20:62)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:53:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:149:9
        at async Promise.all (index 0)
        at async Promise.all (index 2)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:194:3

**Comment by llamatester** [comment]
The adapter at projects/xbanking exports TVL: 
        
 
 
    ton                       0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/xbanking exports TVL: 
        
 
 
    ethereum                  0
    
    total                    0

**Comment by llamatester** [comment]
Error while running adapter at projects/xbanking: 
        
 
  
    
    
    Error: 
        Found export keys that were not part of specification: EthereumTvl
    
        List of valid keys: 
    				
    				tvl
    				staking
    				methodology
    				pool2
    				misrepresentedTokens
    				fetch
    				timetravel
    				borrowed
    				start
    				doublecounted
    				treasury
    				hallmarks
    				incentivized
    				offers
    				deadFrom
    				broken
    				ownTokens
    				vesting

**Comment by llamatester** [comment]
The adapter at projects/xbanking exports TVL: 
        
 
 
    ethereum                  0
    
    total                    0

**Comment by llamatester** [comment]
Error while running adapter at projects/xbanking: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:206:11

**Comment by llamatester** [comment]
Error while running adapter at projects/xbanking: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:206:11

**Comment by llamatester** [comment]
The adapter at projects/xbanking exports TVL: 
        
 
 
    fantom-pool2              0
    fantom                    759.3775069031284
    pool2                     0
    
    total                    759.3775069031284

**Comment by llamatester** [comment]
The adapter at projects/xbanking exports TVL: 
        
 
 
    fantom                    0.08974312590127587
    fantom-pool2              11.091405361583034
    pool2                     11.091405361583034
    
    total                    0.08974312590127587

**Comment by g1nt0ki** [comment]
@xbankingorg thanks for the PR, I refactored it a bit. We count only the tokens left on the contract as tvl, rest is marked as borrowed.

**Comment by llamatester** [comment]
The adapter at projects/xbanking exports TVL: 
        
 
 
    fantom                    0.08974312590127587
    fantom-borrowed           792.1985280556341
    fantom-pool2              11.091405361583034
    borrowed                  792.1985280556341
    pool2                     11.091405361583034
    
    total                    0.08974312590127587

**Comment by xbankingorg** [comment]
> @xbankingorg thanks for the PR, I refactored it a bit. We count only the tokens left on the contract as tvl, rest is marked as borrowed.

we will change our tvl calculator soon

**Pull request merged**
