### PR TITLE
feat: add Defusion ( Liquid Staking on VICTION )

### PR DESCRIPTION
**Pull request by khiemsoft**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
[deFusion]

##### Twitter Link:
https://x.com/deFusionxyz

##### Website Link:
https://www.defusion.xyz/

##### Logo (High resolution, will be shown with rounded borders):
https://drive.google.com/file/d/15QlZ4x5C7gGbbsxeTpxtMrwkuFn_SNkO/view

##### Current TVL:
$2,318,246.43

##### Chain:
Viction

##### Short Description (to be shown on DefiLlama):
[deFusion] is an Infra-liquidity staking platform, designed exclusively for users on Viction seeking a secure and smooth staking experience. With cutting-edge technology and a commitment to transparency, deFusion provides Automated Rewards Distribution Solution (ARDS), ensuring a fusion of stability and efficiency in the ever-evolving blockchain landscape. Using SVIC - tokenized equivalents of your holdings unlocks the door to Viction's expansive ecosystem of utilities.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Liquistaking

##### methodology (what is being counted as tvl, how is tvl being calculated):
The TVL is the total of all staked pools on [deFusion], using the staked on https://www.defusion.xyz/pools as the source.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/defusion exports TVL: 
        
 
 
    tomochain-staking         987.03 k
    staking                   987.03 k
    tomochain                 0
    
    total                    0

**Comment by g1nt0ki** [comment]
@khiemsoft thanks for the PR, can you fill in the project details also, compute the tvl on chain so users can verify

**Comment by khiemsoft** [comment]
> @khiemsoft thanks for the PR, can you fill in the project details also, compute the tvl on chain so users can verify

Also updated on the commit, thanks for your review

**Comment by g1nt0ki** [comment]
maybe you forgot to push the commit?

**Comment by khiemsoft** [comment]
> maybe you forgot to push the commit?

@g1nt0ki Sorry for the detail. I updated the above description, not the commit.

**Comment by g1nt0ki** [comment]
@khiemsoft thanks, refactored and merged here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/10360

**Pull request closed without merging**
