### PR TITLE
feat: fix mango address to Treasury

### PR DESCRIPTION
**Pull request by graykode**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Treasury Addresses (if the protocol has treasury)
**MangoPublicRegistration(0x4eA8496D4D1d4EcF6eD6DaeA95D1A0856F8A5177)**

##### Short Description (to be shown on DefiLlama):
The first community token project on Polygon zkEVM

##### Token address and ticker if any:
**usdc(0xA8CE8aee21bC2A48a5EF670afCc9274C7bbbC035)**

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Services

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/mango-farmers-club exports TVL: 
        
 
 
    polygon_zkevm             0
    
    total                    0

**Comment by graykode** [comment]
Hi @g1nt0ki, 

I was wondering when our project will be shown on frontend?! Thanks :) (cc, https://github.com/DefiLlama/DefiLlama-Adapters/pull/5969)

Thank you for your time and help.

**Comment by g1nt0ki** [comment]
@graykode just to be clear, what does this contract do?  can users withdraw the USDC deposited here?

**Comment by graykode** [comment]
@g1nt0ki To clarify, the treasury contract only holds USDC from our public sale, and does not allow for withdrawals. Therefore, users cannot withdraw USDC from this contract.

**Comment by graykode** [comment]
This is our contracts architecture!
image

**Comment by g1nt0ki** [comment]
> @g1nt0ki To clarify, the treasury contract only holds USDC from our public sale, and does not allow for withdrawals. Therefore, users cannot withdraw USDC from this contract.

so, how can it be considered tvl? we dont count project treasury as tvl for other projects

**Pull request merged**
