### PR TITLE
P

### PR DESCRIPTION
**Pull request by kodon1411**

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@kodon1411 is this PR correct? I dont see your code

**Comment by kodon1411** [comment]
wait . i forgot to fill it out lol

**Comment by g1nt0ki** [comment]
@kodon1411 I still dont see any of your changes, what are you trying to do? https://github.com/DefiLlama/DefiLlama-Adapters/pull/5059/commits

**Comment by kodon1411** [comment]
> @kodon1411 I still dont see any of your changes, what are you trying to do? https://github.com/DefiLlama/DefiLlama-Adapters/pull/5

**Comment by kodon1411** [comment]
but we see that the project that we submitted has been successful

**Comment by kodon1411** [comment]
Thank you in advance

**Comment by g1nt0ki** [comment]
> but we see that the project that we submitted has been successful

that is because I added it here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/099962ff54ad828706df55c227b7aeb298e1af55

closing this PR.

**Comment by kodon1411** [comment]
Thanks 🙏🙏🙏

**Pull request closed without merging**
