### PR TITLE
Add fetch adapter for Demeter

### PR DESCRIPTION
**Pull request by MasterRadule**
##### methodology (what is being counted as tvl, how is tvl being calculated): TVL is being calculated as sum of farming tvl and staking tvl. Farming tvl is being calculated as sum of liquidity in all farming pools (liquidity of A/B pool is being calculated as "number of tokens A in liquidity * price of A + number of tokens B in liquidity * price of B"). Staking tvl is being calculated as sum of tvl in all staking pools (same principle as for farming pools).

### CODE REVIEW

**Comment by MasterRadule** [comment]
> @MasterRadule thanks for the PR, is there some way to fetch this info from on chain calls, also is staked demeter tokens being counted towards tvl?

@g1nt0ki Thanks for the feedback. SORA network on which Demeter Farming platform is running is made in Substrate and is heading to be Polkadot parachain. So everything you need to call on-chain, you can through Polkadot portal: https://polkadot.js.org/apps/?rpc=wss://ws.sora2.soramitsu.co.jp#/chainstate. Here you can select demeterFarmingPlatform pallet and query pools. As a parameters you need to provide asset id of second token in farming pair (there are only pairs with XOR (SORA token) so it is always the first token in farming pair) and you should provide asset id of reward token. I am providing example of XOR/DEO farming pool info (reward token is DEO also) in attachments.

Pools
 
As a result, I got info about all pools where poolAsset is DEO and rewardAsset is DEO (XOR/DEO farming pool and DEO staking pool). There you can see how many LP or DEO tokens are in pools.

Info about asset ids of all tokens on SORA and info about pairs liquidity on Polkaswap (SORA's DEX, you have it on DefiLLama) you can find on https://tools.cerestoken.io/.
And here is the platform: https://farming.deotoken.io/.


Yes, staked Demeter (DEO) tokens is being calculated towards TVL because it is ordinary staking pool same as Ceres and XST staking pools on the platform. 5.4% of total TVL on platform is from DEO staking.

**Comment by MasterRadule** [comment]
Hi @g1nt0ki, is there any update?

**Comment by g1nt0ki** [comment]
@MasterRadule I am struggling a bit with this, can I send you a message over discord, think i could use your help

**Comment by g1nt0ki** [comment]
main issue I am facing right now is, encoding the storage key and decoding response. I am trying to avoid '@polkadot/api' since it is heavy but failing miserably in the encoding part and finding right documentation as to how to do it

**Comment by MasterRadule** [comment]
@g1nt0ki you can contact me on Discord, my username is Radule#9824 but I am more active on Telegram so it would be better to write there (@DanijelCeresToken username).

**Comment by llamatester** [comment]
The adapter at projects/demeter exports TVL: 
        
 
 
    heco                      538.61 k
    heco-staking              61.78 k
    staking                   61.78 k
    
    total                    538.61 k

**Comment by MasterRadule** [comment]
Hello @g1nt0ki how is going? What does it mean @llamatester message?

**Comment by llamatester** [comment]
The adapter at projects/demeter exports TVL: 
        
 
 
    heco                      542.77 k
    heco-staking              58.52 k
    staking                   58.52 k
    
    total                    542.77 k

**Comment by g1nt0ki** [comment]
@MasterRadule I wanted to see what the tvl is if I ran the adapter but there seems to be some bug. It is running some other adapter

**Comment by Define101** [comment]
Hello, is the Address token correct? Can't find it on the Sora Explorer
And could you send us the logo again? The files are missing

**Comment by MasterRadule** [comment]
@g1nt0ki @Define101

**Pull request merged**
