### PR TITLE
add TokensFarm adapter

### PR DESCRIPTION
**Pull request by casualuser**
##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://drive.google.com/file/d/1yrWcvbguLfTF2QsgTZpCaU4-qkhbWJq2/view

##### methodology (what is being counted as tvl, how is tvl being calculated): The worth in $ of all tokens on each farm contract

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/tokensfarm/index.js exports TVL: 
        
 
 
    
    total                    23.94 M

**Comment by waynebruce0x** [comment]
Can TVL be broken down chain by chain?

**Comment by casualuser** [comment]
@waynebruce0x at the moment there is no possibility to split TVL by chain because it was calculated altogether
it may be implemented but it will take some time

please let us know if we can update this later

**Comment by waynebruce0x** [comment]
we have to assign TVL to a chain in our database so we're unable to list as is

**Pull request closed without merging**
