### PR TITLE
Kurrency klaytn

### PR DESCRIPTION
**Pull request by WemadeDeFiDev**
##### Token address and ticker if any:
* KCD
  * Klaytn: 0x54640a6B9F5a6B0eaE043f0A6fd69A4431323356

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/kurrency-klaytn exports TVL: 
        
 
 
    klaytn                    134.67 k
    
    total                    134.67 k

**Comment by llamatester** [comment]
The adapter at projects/kurrency exports TVL: 
        
 
 
    klaytn                    135.12 k
    wemix                     475.13 k
    
    total                    610.25 k

**Comment by g1nt0ki** [comment]
hi @WemadeDeFiDev usually when same team launches similar product in new chain, we keep it in one listing, so I merged it

**Comment by llamatester** [comment]
The adapter at projects/kurrency exports TVL: 
        
 
 
    klaytn                    135.12 k
    wemix                     475.13 k
    
    total                    610.25 k

**Pull request merged**
