### PR TITLE
abracadabra protocol

### PR DESCRIPTION
**Pull request by zashton**
##### Twitter Link:
https://twitter.com/MIM_Spell

##### List of audit links if any:
Nil

##### Website Link:
https://abracadabra.money/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://abracadabra.money/img/Token_MIM.12c48248.svg

##### Current TVL:
$63m

##### Chain:
ETH

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
spell-token

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
Nil

##### Description/bio (to be shown on DefiLlama):
Abracadabra.money is a spell book that allows users to produce magic internet money ($MIM) which is a stable coin that you can swap for any other traditional stable coin.

##### Token address and ticker if any:
0x090185f2135308bad17527004364ebcc2d37e5f6
$SPELL

##### Category (Yield/Dexes/Lending/Minting):
Lending/Yield

##### [Optional] ETH addresss (to receive a LlamaPunk):

Their stablecoin token $MIM is not listed on coingecko yet hence SDK showing $0, its value will be pegged to $1

### CODE REVIEW

**Comment by 0xngmi** [comment]
Should I replace MIM with a stablecoin in order to get the correct TVL?

**Comment by 0xngmi** [comment]
Or better to just wait?

**Comment by zashton** [comment]
> Or better to just wait?

hmmm .. maybe we can put with a stablecoin first. its trading price now is same as a stablecoin on curve. https://crv.to

**Comment by 0xngmi** [comment]
Got it, can you create a PR with the change?

**Comment by 0xngmi** [comment]
Btw, it's already live https://defillama.com/protocol/abracadabra

Should I announce it now or wait till your change lands?

**Comment by zashton** [comment]
> Btw, it's already live https://defillama.com/protocol/abracadabra
> 
> Should I announce it now or wait till your change lands?

ok gimme a min i'll just swop it with dai

**Pull request merged**
