### PR TITLE
Angle

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/angle exports TVL: 
        
 
 
    ethereum-staking          3.55 M
    xdai                      0
    avax                      102.71 k
    polygon                   251.81730000000002
    arbitrum                  3.19 k
    celo                      392.4562823301078
    bsc                       133.9827159353719
    optimism                  17.38 k
    ethereum                  15.71 M
    staking                   3.55 M
    
    total                    15.83 M

**Comment by GuillaumeNervoXS** [comment]
Hi @g1nt0ki, I just saw your PR and the `agEUR` hold by the multisig are not AMOs they were minted from collaterals owned by the governance. 
There has been a period, after Euler hack, where the DAO had agEUR from AMO on the multisig but it was only a temporary state. Now all agEUR on the multisig were minted from actual collaterals and need to be counted in the TVL as it is treasury to the DAO. 

Also, the Transmuter holds bC3M as collateral, but coingecko doesn't have any feed for that. Do you know how we can add the price so it is counted in the TVL? It would be bad to not have it in the TVL as it is and will be a large share of the Transmuter reserves. 

Thanks

**Comment by g1nt0ki** [comment]
> Hi @g1nt0ki, I just saw your PR and the `agEUR` hold by the multisig are not AMOs they were minted from collaterals owned by the governance. There has been a period, after Euler hack, where the DAO had agEUR from AMO on the multisig but it was only a temporary state. Now all agEUR on the multisig were minted from actual collaterals and need to be counted in the TVL as it is treasury to the DAO.
> 
> Also, the Transmuter holds bC3M as collateral, but coingecko doesn't have any feed for that. Do you know how we can add the price so it is counted in the TVL? It would be bad to not have it in the TVL as it is and will be a large share of the Transmuter reserves.
> 
> Thanks

Hi @GuillaumeNervoXS

even if the agEUR is not from AMOs, we are already counting the collaterals backing them in the tvl right, wouldnt counting agEURs again be doublecounting? 

is there any way to determine bC3M price/value on chain? like some oracle proving price? if so we acn add an coin adapter to price it

**Comment by GuillaumeNervoXS** [comment]
Hi @g1nt0ki, thanks for your answer

It would be if it was all coming from either Angle PSM or CDPs, but if it was bought on a DEX then it wouldn't. Because let's say the protocol had a surplus in ETH, it swaps those ETH for agEUR on an AMM. If we don't count the agEUR in the TVL the operation is a net negative for the protocol, as it "lost" ETH and it didn't get agEUR for it. 

Awesome for the price feed, and yes I have been discussing it with @waynebruce0x on Discord, there is a Chainlink like oracle (contract: 0x2F123cF3F37CE3328CC9B5b8415f9EC5109b45e7). And so if there are other assets like that not on coingecko we should notify DefiLlama team? 

Again thank you so much for your help 👌

**Comment by g1nt0ki** [comment]
hi @GuillaumeNervoXS 

sorry, but those are the rules. the issue is agEUR contract is still under your control, hard for outsiders to tell what is minted and what is bought from dex

Yeah, if our price api does not include some token, you can reach out in our discord or create an issue here :)

**Pull request merged**
