### PR TITLE
Add bsdETH for listing

### PR DESCRIPTION
**Pull request by KevinMoll-ls**
Name (to be shown on DefiLlama):
bsdETH (Reserve Protocol)

Twitter Link:
https://x.com/reserveprotocol

List of audit links if any:
https://github.com/reserve-protocol/protocol/blob/master/audits/Ackee%20-%20abch-reserve-protocol-report-1.1.pdf
https://github.com/reserve-protocol/protocol/blob/master/audits/Solidified%20-%20Audit%20Report%20-%20Reserve%20Protocol.pdf
https://github.com/reserve-protocol/protocol/blob/master/audits/Trail%20of%20Bits%20-%20Reserve%20Org%20-%20Final%20Report.pdf
https://github.com/reserve-protocol/protocol/blob/master/audits/Halborn%20-%20Reserve_Protocol_Smart_Contract_Security_Audit_Report_Halborn_Final.pdf
https://code4rena.com/reports/2023-01-reserve
https://github.com/reserve-protocol/protocol/blob/master/audits/Code4rena%20-%20Reserve%20Audit%20Report%20-%20Release%203.0.0%20(core).md
https://github.com/reserve-protocol/protocol/blob/master/audits/Code4rena%20-%20Reserve%20Audit%20Report%20-%20Release%203.0.0%20(collaterals).md
https://github.com/reserve-protocol/protocol/blob/master/audits/Reserve%20Audit%20Report%203_1_0%20-%20Trust%20Security.pdf

Website Link:
https://app.reserve.org/base/token/0xcb327b99ff831bf8223cced12b1338ff3aa322ff/overview

Logo (High resolution, will be shown with rounded borders):
https://app.reserve.org/svgs/bsdeth.svg

Current TVL:
$8.49M

Chain:
Base

Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
based-eth

Short Description (to be shown on DefiLlama):
A yield generating Ethereum Liquid Staking Token basket with over-collateralization protection. Deposits are currently eligible for pre-launch DIVA token allocations per the terms in this proposal: https://www.tally.xyz/gov/diva/proposal/38314542060713027082977990523280607813521163704798044817782268218160075499416?chart=0

Token address and ticker if any:
0xCb327b99fF831bF8223cCEd12B1338FF3aA322Ff
bsdETH

Category (full list at https://defillama.com/categories) *Please choose only one:
Liquid Staking

Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Chainlink

Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
https://reserve.org/protocol/smart_contracts/

methodology (what is being counted as tvl, how is tvl being calculated):
TVL consists of the bsdETH supply along with the RSR tokens deposited to the protocol as overcollaterization.

Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/reserve-protocol/protocol

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bsd-eth exports TVL: 
        
 
 
    base                      8.56 M
    
    total                    8.56 M

**Comment by g1nt0ki** [comment]
@KevinMoll-ls thanks for the PR, but we are already counting this tvl as part of https://defillama.com/protocol/reserve#information

**Comment by KevinMoll-ls** [comment]
Hello @g1nt0ki, 

Thank you reviewing the PR, here at Reserve we would like to list several Rtokens individually at Defillama, we were starting with bsdETH, is there any issue listing this one?

**Comment by g1nt0ki** [comment]
@KevinMoll-ls sorry, we dont support listing individual RTokens atm, it would be too much work for us to maintain.

**Comment by KevinMoll-ls** [comment]
Hello @g1nt0ki,

Thank you for your response. I understand that listing all individual RTokens would be challenging to maintain. However, we would like to request the addition of just nine specific RTokens (eUSD, ETH+, hyUSD, USDC+, USD3, rgUSD, bsdETH, iUSD, and Vaya) as sub-projects included on the Reserve (RSR) main page. We have noticed that [Overnight Finance (OVN)](https://defillama.com/protocol/overnight-finance) lists their sub-projects and those seem to be part of the main TVL, we believe that this approach could work well for Reserve as well.

We are open to discussing this further and would appreciate your consideration. Thank you.

**Comment by g1nt0ki** [comment]
so, overnight was a mistake, we dont want to repeat that, they wanted to add more tokens, that's when we said no, and not to do it for other protocols either.

**Pull request closed without merging**
