### PR TITLE
Count tokens wrapped in an ArcadeVault towards Arcade.xyz TVL

### PR DESCRIPTION
**Pull request by sandbochs**
This PR fetches all created vaults by parsing event logs matching the `VaultCreated(address,address)` signature. TVL is now calculated as all whitelisted NFTs vaulted and owned by our escrow contract, Loan Core.

I also split out the whitelisted NFT list into it's own file for maintainability. 

Can we update our description to:
`Decentralized NFT marketplace for lending & borrowing`

### CODE REVIEW

**Comment by sandbochs** [comment]
I'm going to open an additional PR that will update the NFT whitelist.

**Comment by sandbochs** [comment]
Not sure why the action is getting hung up. This is what I get locally with an Alchemy RPC.
```
➜  DefiLlama-Adapters git:(update-arcade-xyz-vaults) ✗ node test.js projects/arcade-xyz/index.js
--- ethereum ---
WPUNKS                    5.29 M
BAYC                      3.39 M
MAYC                      603.17 k
CloneX                    382.38 k
PPG                       251.97 k
BAKC                      210.01 k
OTHR                      156.61 k
BEANZ                     41.01 k
MOONBIRD                  36.35 k
DOODLE                    31.25 k
⚇                         30.46 k
AZUKI                     21.44 k
CDB                       2.88 k
WOW                       2.51 k
TOADZ                     1.81 k
LAND                      1.18 k
GOBLIN                    865.0434416864492
Total: 10.45 M

--- tvl ---
WPUNKS                    5.29 M
BAYC                      3.39 M
MAYC                      603.17 k
CloneX                    382.38 k
PPG                       251.97 k
BAKC                      210.01 k
OTHR                      156.61 k
BEANZ                     41.01 k
MOONBIRD                  36.35 k
DOODLE                    31.25 k
⚇                         30.46 k
AZUKI                     21.44 k
CDB                       2.88 k
WOW                       2.51 k
TOADZ                     1.81 k
LAND                      1.18 k
GOBLIN                    865
Total: 10.45 M

------ TVL ------
ethereum                  10.45 M

total                    10.45 M
```

**Comment by g1nt0ki** [comment]
@sandbochs  have refactored your code a bit here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/5503 but still, it is a lot of calls, right now around 90k (3k vaults * 42 nfts)

can this be improved somehow? maybe we can use the graph to first get a list of active loans? https://protocol-sg.arcade.xyz/subgraphs/name/arcade/protocol-v2

**Comment by sandbochs** [comment]
@g1nt0ki i can use a graph for sure. I thought graph calls were banned so I went ahead with the full on chain implementation.

**Comment by llamatester** [comment]
The adapter at projects/arcade-xyz exports TVL: 
        
 
 
    ethereum                  10.46 M
    
    total                    10.46 M

**Comment by sandbochs** [comment]
@g1nt0ki I've updated the PR to use the subgraph to fetch all active vaults which turns out to be `201` reducing the calls to `8,442`

**Comment by llamatester** [comment]
The adapter at projects/arcade-xyz exports TVL: 
        
 
 
    ethereum                  10.44 M
    ethereum-borrowed         10.44 M
    borrowed                  10.44 M
    
    total                    10.44 M

**Comment by sandbochs** [comment]
@g1nt0ki added total borrowed value as well

**Comment by llamatester** [comment]
The adapter at projects/arcade-xyz exports TVL: 
        
 
 
    ethereum-borrowed         10.44 M
    ethereum                  10.44 M
    borrowed                  10.44 M
    
    total                    10.44 M

**Comment by llamatester** [comment]
The adapter at projects/indexcoop exports TVL: 
        
 
 
    ethereum                  63.26 M
    
    total                    63.26 M

**Comment by llamatester** [comment]
The adapter at projects/sommelier exports TVL: 
        
 
 
    ethereum                  14.89 M
    
    total                    14.89 M

**Comment by llamatester** [comment]
The adapter at projects/arcade-xyz exports TVL: 
        
 
 
    ethereum-borrowed         10.47 M
    ethereum                  10.39 M
    borrowed                  10.47 M
    
    total                    10.39 M

**Comment by llamatester** [comment]
The adapter at projects/indexcoop exports TVL: 
        
 
 
    ethereum                  63.49 M
    
    total                    63.49 M

**Pull request merged**
