### PR TITLE
chore: add new ethereum GBPT token to contracts

### PR DESCRIPTION
**Pull request by ChinmayGopal931**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
DFX Contract Update

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/dfx exports TVL: 
        
 
 
    polygon                   774.55 k
    ethereum                  2.56 M
    
    total                    3.33 M

**Comment by llamatester** [comment]
Error while running adapter at projects/dfx: 
        
 
  
    
    
    Error: Multicall is missing a target
    Truncated error stack:
        at Object.<anonymous> (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/abi/index.js:230:35)
        at new Promise (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/dfx/index.js:23:19
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:29)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:15

**Comment by llamatester** [comment]
The adapter at projects/dfx exports TVL: 
        
 
 
    polygon                   705.07 k
    ethereum                  2.09 M
    arbitrum                  68.01 k
    
    total                    2.87 M

**Comment by llamatester** [comment]
The adapter at projects/dfx exports TVL: 
        
 
 
    polygon                   704.03 k
    arbitrum                  67.98 k
    ethereum                  2.09 M
    
    total                    2.86 M

**Comment by llamatester** [comment]
The adapter at projects/dfx exports TVL: 
        
 
 
    polygon                   704.03 k
    ethereum                  2.09 M
    arbitrum                  67.98 k
    
    total                    2.86 M

**Comment by llamatester** [comment]
The adapter at projects/dfx exports TVL: 
        
 
 
    polygon                   700.16 k
    arbitrum                  67.88 k
    ethereum                  2.18 M
    
    total                    2.95 M

**Comment by g1nt0ki** [comment]
@ChinmayGopal931 thanks for the PR, I have updated code so we no longer need to manually update contract list, it is instead pulled from the logs.

**Comment by ChinmayGopal931** [comment]
@g1nt0ki TVL still seems to be incorrect. I think the issue might be becuase of CADC token price calculation? The dfx website quotes the correct balances . 
Ex for tvl on arbitrum 
here are the addresses: 
https://arbiscan.io/address/0xcd8a5ea5c44a231cb42f13056f55c65af32cb565
https://arbiscan.io/address/0x3c3badfbf97ec7caebff761694dd642f2c8b11e8

Arbitrum tvl should be around 84 not 67.

**Pull request merged**
