### PR TITLE
Add bahamut network and lolik project.

### PR DESCRIPTION
**Pull request by loliklabs**
##### Name (to be shown on DefiLlama):
Lolik Staking Pool

##### Website Link:
www.lolik.com

##### Logo (High resolution, will be shown with rounded borders):
https://lolik.com/lolik.png

##### Current TVL:
1,837,489.138 FTN = $ 2,516,900.74

##### Treasury Addresses (if the protocol has treasury)
0xb0d3c1ce860e7Bb003043969cBD10C389FF38194
Scanner link - https://ftnscan.com/address/0xb0d3c1ce860e7Bb003043969cBD10C389FF38194

##### Chain:
Bahamut

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): 
lolik-staked-ftn

##### Short Description (to be shown on DefiLlama):
Lolik is a decentralized liquid staking platform that supports staking on leading EVM blockchains including Ethereum, Polygon, and Bahamut. Anyone can participate in the staking process with their web3 wallet (e.g. MetaMask) directly through the platform, and earn daily rewards.

##### Token address and ticker if any:
address on Bahamut blockchain: 0x780Fb5AcA83F2e3F57EE18cc3094988Ef49D8c3d
scanner link - https://ftnscan.com/address/0x780Fb5AcA83F2e3F57EE18cc3094988Ef49D8c3d/contracts#address-tabs
ticker - stFTN

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Liquid Staking

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
None

##### forkedFrom (Does your project originate from another project):
Lido

##### methodology (what is being counted as tvl, how is tvl being calculated):
Staked tokens are counted as TVL based on the chain that they are staked on and where the liquidity tokens are issued.

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/lolik: 
        
 
  
    
    
    Error: Failed to call getTotalPooledFtn() on https://eth-mainnet.gateway.pokt.network/v1/5f3453978e354ab992c4da79 reason: null code: CALL_EXCEPTION
    Truncated error stack:
        at formError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:242:17)

**Comment by loliklabs** [comment]
Please note that the testing of the Adapter is failing due to Lolik being on Bahamut blockchain, which isn't yet on DefiLlama.

**Comment by llamatester** [comment]
The adapter at projects/lolik exports TVL: 
        
 
 
    ftn                       2.67 M
    
    total                    2.67 M

**Comment by g1nt0ki** [comment]
@loliklabs thanks for the PR

**Pull request merged**
