### PR TITLE
Update arkadiko.js

### PR DESCRIPTION
**Pull request by philipdesmedt**
Our protocol got a major upgrade (to v2.0) and our reserve contracts got changed through our migration. This is an update to reflect those changes and updates the reserves for DefiLlama.

**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/arkadiko.js exports TVL: 
        
 
 
    stacks                    13.01 M
    
    total                    13.01 M

**Comment by philipdesmedt** [comment]
@g1nt0ki thanks for merging!

I believe there is one token in the `arkadiko-vaults-pool-active-v1-1` token not accounted for, namely wSTX (https://explorer.hiro.so/address/SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR.wstx-token?chain=mainnet). This is simply wrapped STX, about $3.5M missing from the TVL. Could you add this?

**Comment by g1nt0ki** [comment]
fixed it

**Comment by philipdesmedt** [comment]
@g1nt0ki thanks a lot!

**Comment by TheLogistician** [comment]
Phillip.  I am an Arkadiko user and have been trying to unstake my Diko for over a month now.  On four different occasions your protocol would not unstake after a 9 day cooldown and now it wont even cool down at all.  No support so I have had to take to twitter and will unfortunately need to continue to do so until someone acknowledges the problem.  If I continue to get no support I am going to file a legal complaint.  Please help!

**Pull request merged**
