### PR TITLE
add DeFIL arbitrum tvl

### PR DESCRIPTION
**Pull request by defil2020**
##### Twitter Link:
https://mobile.twitter.com/defilofficial

##### List of audit links if any:
https://www.artemisclouds.com/audit_en/202203251921.html

##### Website Link:
https://defil.org/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://defil.org/favicon.ico

##### Current TVL:
$13,021,206.29

##### Chain:
Ethereum, Binance Smart Chain, Arbitrum

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
defil

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
11740

##### Short Description (to be shown on DefiLlama):
DeFIL is a decentralized Filecoin lending and finance service platform.

##### Token address and ticker if any:
Arbitrum DFL 0x31635A2a3892dAeC7C399102676E344F55d20Da7
Arbitrum eFIL 0x66ba30d5D7c66aFd4ed41c3498eC9e20a03a1368

Arbitrum UniswapV3 DFL-USDT pool 0x27a664dFBcBAe7E7DFec8B489473392fCe2b0C2C
Arbitrum UniswapV3 eFIL-USDT pool 0xF8E5a77a4f187cFb455663B37619257565439F6A

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### methodology (what is being counted as tvl, how is tvl being calculated):
UniswapV3 eFIL-USDT pool Value + UniswapV3 DFL-USDT pool Value

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Do you have a staking contract for these UniV3 pools? You cant just count the whole pool I'm afraid, the coins need to be in your own contracts

**Comment by defil2020** [comment]
> 

Since our reward is based on the fee increment of LP, and the fee increment cannot be obtained through the pledged NFT information, we directly obtain the fee increment of each person in the entire pool for DFL distribution. We are the developer and owner of this project. You can check the relevant information on our GitHub homepage to see that we have released contracts on the three chains of ETH, BSC, and Aribitrum. Although these LPs have not been pledged to our platform, we hope You can agree that these TVLs belong to us.

**Comment by defil2020** [comment]
> Do you have a staking contract for these UniV3 pools? You cant just count the whole pool I'm afraid, the coins need to be in your own contracts

I have another question that DeFIL rewards LP on arbitrum, and the LP of UNI V3 of arbitrum is in the form of NFT. If NFT is pledged to platform's contract, can you get the value of NFT of UNI V3? and then calculate to come up with the ultimate TVL?

**Comment by defil2020** [comment]
> > Do you have a staking contract for these UniV3 pools? You cant just count the whole pool I'm afraid, the coins need to be in your own contracts
> 
> I have another question that DeFIL rewards LP on arbitrum, and the LP of UNI V3 of arbitrum is in the form of NFT. If NFT is pledged to platform's contract, can you get the value of NFT of UNI V3? and then calculate to come up with the ultimate TVL?

image

**Pull request closed without merging**
