### PR TITLE
interport: add EON, Scroll and opBNB chains

### PR DESCRIPTION
**Pull request by dev-dozer**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/interport-finance exports TVL: 
        
 
 
    avax                      130.76 k
    era                       700.92 k
    optimism                  349.32 k
    ethereum-staking          72.99 k
    arbitrum                  327.07 k
    base                      26.18 k
    bsc                       1.43 M
    polygon                   476.77 k
    fantom                    0
    linea                     282.46 k
    polygon_zkevm             150.06 k
    eon                       30.55 k
    ethereum                  308.29 k
    ethereum-pool2            0
    staking                   72.99 k
    pool2                     0
    
    total                    4.22 M

**Comment by llamatester** [comment]
The adapter at projects/interport-finance exports TVL: 
        
 
 
    ethereum-staking          72.99 k
    base                      25.05 k
    op_bnb                    79.93 k
    era                       700.46 k
    arbitrum                  326.72 k
    avax                      130.66 k
    fantom                    0
    polygon                   476.20 k
    polygon_zkevm             149.93 k
    linea                     283.22 k
    ethereum                  307.97 k
    bsc                       1.43 M
    optimism                  350.11 k
    scroll                    475.58 k
    ethereum-pool2            0
    eon                       30.53 k
    staking                   72.99 k
    pool2                     0
    
    total                    4.77 M

**Comment by dev-dozer** [comment]
We noticed that the value of pool2 was incorrectly specified in the test - it is zero. In fact, there is a different meaning there. On our part, all data is correct. Please check this moment

**Comment by g1nt0ki** [comment]
@dev-dozer thanks for the PR, pool2 being 0 must be a temp bug, it is shown correctly in the UI & when I tried running locally
image

**Pull request merged**
