### PR TITLE
Add handle Synthetic Perpetuals adapter (hSP)

### PR DESCRIPTION
**Pull request by rellfy**
#####  Overview
1. Rename the folder `handlefi-fxpreps` to `handlefi-amm`. Note that the previous `handlefi-fxpreps` directory (for the previous handlePerps project, live at https://defillama.com/protocol/handle.fi-perps) is now a spot-only trading, hence we are renaming it to AMM.
2. Create an indexing file for handle synthetic perpetuals (hSP) on Arbitrum One

##### Name (to be shown on DefiLlama):
handle.fi

##### Twitter Link:
https://twitter.com/handle_fi

##### Website Link:
https://handle.fi

##### Logo (High resolution, will be shown with rounded borders):
Can use existing (https://defillama.com/protocol/handle.fi)

##### Chain:
Arbitrum One

##### Short Description (to be shown on DefiLlama):
handle Synthetic Perpetuals (hSP)

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Derivatives

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
1:1 fxUSD to USD peg.
Underlying CDP peg ensures collateralisation based on Chainlink.

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
hSP deposits

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/handlefi-hsp exports TVL: 
        
 
 
    arbitrum                  6.33 k
    
    total                    6.33 k

**Comment by g1nt0ki** [comment]
hi @rellfy , 

thanks for the PR, I have refactored your code here. Reverted name change, as changing folder name does not update the UI but only breaks our server.  I will do the change in another repo, but if is pure amm, what is backing the FX tokens? like, the vaults have only about 255k$ of WETH, but the pools has only 2k$ ETH, rest 1.4M$ are fx tokens

**Comment by seahound** [comment]
hey @g1nt0ki its not a "pure AMM", but we thought this may make it easier for user to understand its function. happy for you to revert and leave name as is. thnks

**Comment by g1nt0ki** [comment]
hi @seahound , sorry but you still havent answered the question, what is backing the fx tokens

**Comment by seahound** [comment]
all circulating fxtokens are backed by cdp assets, hPSM assets, curve pool LPs, xFX vault LP tokens , POL. this is not what we're addressing here with this PR

we wanted to simply add the new handle synthetic perps pool vault contract.

**Comment by g1nt0ki** [comment]
@seahound prep pool part is clear

But I think we need to refactor amm listing, we are already tracking cdp assets in the tvl, can you share the POL part backing it? I will update amm listing to use non handle fi tokens in the vault, and value of tokens in POL

**Comment by seahound** [comment]
the methodolgy and constituents behind hLP - handle Liquidity Pool - (fork of GLP) which is what we were proposing to change to call AMM (for no other reason than be clearer to users)  was extensivly discussed with the llama team when first added. it was added as a seperate pool based these discussions if you're now going to change approach/discount all our protocol stablecoins as part of this pool that's both incorrect and unhelpful.

so happy for you to leave as it stands or we alternatively just revert the entire PR

**Comment by seahound** [comment]
sure, its not an issue. and yes absolutely all circulating fxTokens are fully backed.

the intent of the PR was solely  to add hSP (for the perps launch) (other mods were "chores" really) - if you want to expand scope to adding more data for hLP - then we can do this in a seperate PR perhaps?

**Comment by g1nt0ki** [comment]
I have merged hSP adapter here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/8123

**Comment by g1nt0ki** [comment]
> sure, apologies @g1nt0ki its not an issue. and yes absolutely all circulating fxTokens are fully backed.
> 
> the intent of the PR was solely to add hSP (for the perps launch) (other mods were "chores" really) - if you want to expand scope to adding more data for hLP - then we can do this in a seperate PR perhaps?

hi @seahound can you provide POL details and I will update prep/amm listing

**Comment by g1nt0ki** [comment]
@seahound bump

**Comment by rellfy** [comment]
@g1nt0ki hi there,

We are preparing a page that will show the breakdown of all protocol assets and liabilities. We'll report back next week with that. But to reiterate, all circulating fxTokens are fully backed.  Thanks for your patience.

**Pull request closed without merging**
