### PR TITLE
Add ReHold V2

### PR DESCRIPTION
**Pull request by bifot**
Hello,

We've released the ReHold V2, which has the new smart contracts.

Certik audit: https://skynet.certik.com/projects/rehold
Contracts repo: https://github.com/rehold-io/smart-contracts-v2

Thank you!

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/rehold exports TVL: 
        
 
 
    arbitrum                  259.15 k
    polygon                   166.79 k
    avax                      55.69 k
    optimism                  91.68 k
    bsc                       66.35 k
    
    total                    639.66 k

**Comment by llamatester** [comment]
Error while running adapter at projects/rehold-v2: 
        
 
  
    
    
    AxiosError: Request failed with status code 429

**Comment by llamatester** [comment]
The adapter at projects/rehold-v2 exports TVL: 
        
 
 
    avax                      0
    arbitrum                  0
    optimism                  0
    polygon                   33.33879
    bsc                       3.75 k
    
    total                    3.78 k

**Comment by g1nt0ki** [comment]
@bifot looks good, not sure why removed fantom in v1, I added it back

**Comment by bifot** [comment]
@g1nt0ki thanks! we've delisted the fantom on v1

**Comment by g1nt0ki** [comment]
ah, we like to leave it there for historical reasons, the system is setup in such a way if we remove it now, it will remove fantom tvl from the time chart completely

**Comment by bifot** [comment]
can we keep 2 audits?

v1: https://github.com/peckshield/publications/blob/master/audit_reports/PeckShield-Audit-Report-ReHold-v1.0.pdf
v2: https://skynet.certik.com/projects/rehold

**Comment by g1nt0ki** [comment]
hi @bifot one of the audit is for v1 or both are for v2? right now, we have attached the first one to v1: https://defillama.com/protocol/rehold-v1

**Comment by bifot** [comment]
the first audit is for v1, the second is for v2

i think now everything is good on our page ok defillama

thanks

**Pull request merged**
