### PR TITLE
add Kolibri

### PR DESCRIPTION
**Pull request by touhonoob**
##### Twitter Link:
https://twitter.com/hovereng

##### List of audit links if any:
https://kolibri.finance/docs/security-report.pdf

##### Website Link:
https://kolibri.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://ipfs.io/ipfs/QmXJ5VNnPKCx9tToRkZDSb6MjuEPybzMN9yMyf4HuNxJ9M
https://hover.engineering/img/hover-logo.4f738b67.svg

##### Current TVL:
21,669,777

##### Chain:
Tezos

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

##### Short Description (to be shown on DefiLlama):
```
Kolibri is an Tezos based stablecoin built on Collateralized Debt Positions (CDPs) known as Ovens.
Kolibri uses CDPs (referred to as an Oven) to collateralize a soft pegged USD-stable value asset, kUSD.
```

##### Token address and ticker if any:
kUSD
KT1K9gCRgaLRFKTErYt1wVxA3Frb9FjasjTV

##### Category (Yield/Dexes/Lending/Minting) *Please choose only one:
Minting

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
https://harbinger.live/

##### forkedFrom (Does your project originate from another project):
N/A

### CODE REVIEW

**Comment by 0xngmi** [comment]
Does this only include collateral tokens backing the stablecoins or is there other stuff baked into this tvl?

**Comment by touhonoob** [comment]
> Does this only include collateral tokens backing the stablecoins or is there other stuff baked into this tvl?

The TVL here = `Collateralized XTZ * Current XTZ Price`

https://p.datadoghq.com/sb/e72980047-19c18eb0c4504886f0ba9bef6660b723?theme=dark&tpl_var_Network=mainnet&tv_mode=true&from_ts=1630695295105&to_ts=1630781695105&live=true

**Comment by realdealshaman** [comment]
@touhonoob, I came to the realization that Kolibri has a governance token( kDAO:KT1JkoE42rrMBP9b2oDhbx6EUr26GcySZMUH ). I will update the listing so that it reflects that this token is available, let us know if for some reason you would prefer to not have this token added

**Comment by Fitblip** [comment]
Hi friends! @realdealshaman / @touhonoob / @0xngmi 

I'm one of the members of Hover Labs (who bootstrapped/created Kolibri and the DAO). Thanks a ton for listing this :) happy to answer whatever questions anyone has or help provide data. I have a new dashboard that we'll be rolling out soon that shows overall TVL as well as TVL breakdowns for the farms and liquidity pool if any of that is of interest:

image

One thing though is that the icon on the site is not for Kolibri, but our logo for Hover Labs instead - https://hover.engineering/

If you don't mind, can you update it to use 

The kUSD logo - https://kolibri-data.s3.amazonaws.com/logo.png:

 

Or maybe the icon on the [main site](https://kolibri.finance) - https://kolibri.finance/img/hummingbird.ce25bc0f.svg



Either is fine! Thanks again for including this project!

**Comment by realdealshaman** [comment]
Hello, nice to meet you. I just updated the Kolibri logo and it will be reflected on the website in a few moments. Thank you for your availability and attention. In the same way, we remain open to your suggestions if there is something that you would like to update to the code and the way that TVL is being pulled, this can be done with a pull request. Input from a project's Team is very much welcome. Thanks for commenting

**Pull request merged**
