### PR TITLE
Add LSULP pool to Root Finance TVL calculation in index.js

### PR DESCRIPTION
**Pull request by RootFinanceRadix**
This update adds the LSULP pool to the TVL calculation for Root Finance on Radix.

- Pool ID: component_rdx1czmq3me09q7p7g7hgsyaqctfw3he4hl6ypg6em2h7nyd2umk0dhhnq
- Resource ID: resource_rdx1thksg5ng70g9mmy9ne7wz0sc7auzrrwy7fmgcxzel2gvp8pj0xxfmf

**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/root-finance exports TVL: 
        
 
 
    radixdlt                  448.09 k
    radixdlt-borrowed         203.72 k
    borrowed                  203.72 k
    
    total                    448.09 k

**Comment by g1nt0ki** [comment]
thanks @RootFinanceRadix

**Comment by RootFinanceRadix** [comment]
Hi there!

Thank you for the fast response.

The TVL displayed on Defillama is incorrect unfortunately. As you can see
in the screenshot below we have 900k plus TVL at the moment.

Is there something we can do to help you fix this?

Thank you.



Il giorno lun 25 nov 2024 alle 17:07 g1nt0ki ***@***.***> ha
scritto:

**Comment by g1nt0ki** [comment]
hi, the issue is, we dont have price support for LSUP

can you extend this to add price support for it? https://github.com/DefiLlama/defillama-server/blob/master/coins/src/adapters/markets/ociswap.ts#L30

**Pull request merged**
