### PR TITLE
add MeowProtocol

### PR DESCRIPTION
**Pull request by hnustfeng**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
MeowProtocol

##### Twitter Link:
https://twitter.com/0xMeowProtocol

##### List of audit links if any:
https://f8t2x8b2.rocketcdn.me/wp-content/uploads/2023/12/VAR-0xMeowProtocol-231127-V2.pdf

##### Website Link:
https://meowprotocol.xyz/

##### Logo (High resolution, will be shown with rounded borders):
logo

##### Current TVL:
16.18K

##### Chain:
Ethereum, Scroll

##### Short Description (to be shown on DefiLlama):
Meow is a decentralized lending protocol that focuses on providing lending services for a variety of asset categories.

Our vision is to build a Permissionless Financial Autonomous World, creating diverse opportunities for users to compose their financial assets.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
DeFi/Lending

##### methodology (what is being counted as tvl, how is tvl being calculated):
https://meowprotocol.gitbook.io/doc/about-supply-and-borrow/borrow-interest-and-deposit-apy

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/0xMeowProtocol/contract.git

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/MeowProtocol: 
        
 
  
    
    
    Error: Llama RPC error! methos: undefined 
    - host: https://rpc.ankr.com/scroll error: header not found
    - host: https://1rpc.io/scroll error: header not found
    - host: https://rpc.scroll.io error: header not found
    - host: https://scroll.blockpi.network/v1/rpc/public error: header not found
    - host: https://rpc-scroll.icecreamswap.com error: header not found
    - host: https://scroll-mainnet.public.blastapi.io error: header not found
    - host: https://scroll-mainnet.chainstacklabs.com error: header not found

**Comment by llamatester** [comment]
The adapter at projects/MeowProtocol exports TVL: 
        
 
 
    ethereum-borrowed         7.541909787942338
    ethereum                  5.96 k
    scroll-borrowed           663.8231504669365
    scroll                    6.27 k
    borrowed                  671.3650602548788
    
    total                    12.23 k

**Comment by g1nt0ki** [comment]
@hnustfeng thanks for the PR

**Comment by llamatester** [comment]
The adapter at projects/MeowProtocol exports TVL: 
        
 
 
    scroll                    8.99 k
    ethereum-borrowed         7.528814197819485
    scroll-borrowed           1.18 k
    ethereum                  6.00 k
    borrowed                  1.19 k
    
    total                    14.99 k

**Pull request merged**
