### PR TITLE
Create index.js for cardstarter

### PR DESCRIPTION
**Pull request by mafaiq**

### CODE REVIEW

**Comment by 0xngmi** [comment]
Since we don't count pool2 towards TVL for other protocols should I remove `0x94ae6d2390680ac6e6ee6069be42067d6ad72e2a` from the array?

**Comment by mafaiq** [comment]
What do u mean by pool2 ser?

You can stake cards/eth LP on cardstarter platform for cswap rewards.

So that should be normal farming, right?

Sorry im not on discord atm

**Comment by 0xngmi** [comment]
pool2 = the LP pair where one of the tokens is the governance token

> You can stake cards/eth LP on cardstarter platform for cswap rewards.

For other protocols we are not counting this towards the TVL, you could argue that this is TVL since it's money locked but the general consensus seems to be that this shouldn't be counted as TVL since it's nothing specific to the protocol

**Comment by mafaiq** [comment]
I see, i'll look into it later tonight to find out whether thats for
governance or not.

But afai understood, thats a farm to mint more cswap tokens,

And the the cards staking pool is to take part in the IDOs.

**Comment by 0xngmi** [comment]
Isn't cards their own token?

**Comment by mafaiq** [comment]
Yeah, but i meant they have multiple reasons to stake their token on the
platform.

Mainly as a way to be eligible for partaking in IDOs

**Pull request merged**
