### PR TITLE
Micro Credit Project request

### PR DESCRIPTION
**Pull request by sarp07**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): 
"https://coinmarketcap.com/currencies/microcredittoken/"
(https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

##### Short Description (to be shown on DefiLlama):
"MC Project is a decentralized platform that brings together social investors and the poor with the goal of eradicating poverty in line with the United Nations Sustainable Development Goals by 2030. MC Project is inspired by the proven success of the Grameen Microfinance Model and aims to provide a more effective financial tool for poverty eradication.

MC Project leverages the core values of blockchain technology, such as decentralization, transparency, and trust, to facilitate the challenges of financial inclusion through cryptocurrencies. Social investors, in addition to contributing to a purely social cause, the eradication of poverty worldwide, will also stake their micro credit project assets using the lock-up process for 3 – 6 – 9 – 12-month periods and receive dividend bonuses. They will also benefit from price increases on cryptocurrency exchanges and other platforms where MC Project is listed.

MC Project, driven by the goal of a world without poverty, will play a role in the adoption of Happytalism practices worldwide and bring new momentum to the global microfinance system and social entrepreneurship. As a Web3 micro credit distribution platform, it aims to revolutionize financial inclusion by offering decentralized microfinance solutions to those in need."

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/microcreditplatform: 
        
 
  
    
    
    Error: Multicall failed! 
     [chain: haqq] [fail count: 2] [abi: function balanceOf(address account) view returns (uint256)]  
        target: 0x0CE35b0D42608Ca54Eb7bcc8044f7087C18E7717 params: 0x951d1571C75C519Cc3D09b6B71595C6aCe1c06dB]
        target: 0xA8759ca1758fBd8db3BA14C31d2284ae58a64CD1 params: 0x951d1571C75C519Cc3D0...
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
The adapter at projects/microcreditplatform exports TVL: 
        
 
 
    haqq                      0
    
    total                    0 
    
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:225:11
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
Error while running adapter at projects/microcreditplatform: 
        
 
  
    
    
    Error: Multicall failed! 
     [chain: haqq] [fail count: 2] [abi: function balanceOf(address account) view returns (uint256)]  
        target: 0x80b5a32E4F032B2a058b4F29EC95EEfEEB87aDcd params: 0x951d1571C75C519Cc3D09b6B71595C6aCe1c06dB]
        target: 0xA8759ca1758fBd8db3BA14C31d2284ae58a64CD1 params: 0x951d1571C75C519Cc3D0...
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
Error while running adapter at projects/microcreditplatform: 
        
 
  
    
    
    Error: Multicall failed! 
     [chain: haqq] [fail count: 2] [abi: function balanceOf(address account) view returns (uint256)]  
        target: 0x80b5a32E4F032B2a058b4F29EC95EEfEEB87aDcd params: 0x951d1571C75C519Cc3D09b6B71595C6aCe1c06dB]
        target: 0xA8759ca1758fBd8db3BA14C31d2284ae58a64CD1 params: 0x951d1571C75C519Cc3D0...
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
The adapter at projects/microcreditplatform exports TVL: 
        
 
 
    islm                      0
    
    total                    0

**Comment by g1nt0ki** [comment]
@sarp07 thanks for the PR but we can not count MCT token as tvl

**Comment by g1nt0ki** [comment]
what does this investment contract do?

**Comment by sarp07** [comment]
This project is about microcredit. They want to see it in Defillama MCT is a native token for the platform and this platform will use axlUSDC in this contract. The investment contract is used for investment and the invested tokens are withdrawn and distributed as loans and the distributed loans are recorded in the name of the investor in the loan database contract. After the 12-month or 48-week loan payment period, the transaction fee is added and the loan is collected. The investment amount is added to the profit share contract so that the investor can claim. So what do I need to do to be considered as MCT token?

**Comment by g1nt0ki** [comment]
is this app live? I dont see any option in your webpage for users to deposit axlUSDC into investment contract. We can count only the axlUSDC on the contract as tvl, if there is a way to query borrowed value, we can track under 'borrowed' key

**Comment by sarp07** [comment]
Oh, got it, 
This app not live yet. We will publish soon and also added option for axlUSDC but how can we list MCT for tvl?

**Comment by g1nt0ki** [comment]
hmm, we will wait for project to be live before listing, and again, we cant count MCT as tvl: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by llamatester** [comment]
The adapter at projects/microcreditplatform exports TVL: 
        
 
 
    islm                      0
    
    total                    0

**Comment by g1nt0ki** [comment]
@sarp07  I am closing this PR for now, you can comment here/reopen it when the project is live

**Comment by sarp07** [comment]
Hello @g1nt0ki,

we are live with "https://app.microcredittoken.com/"

you said to me "when you are live..", you can list on defillama to this now.

**Comment by sarp07** [comment]
Yes no one added, but after the DeFiLlama listing, the submission will be made.

**Pull request closed without merging**
