### PR TITLE
add optifi adapter

### PR DESCRIPTION
**Pull request by LeoOptiFi**
Twitter Link:
https://twitter.com/OptifiLabs

List of audit links if any:
 https://optifi.gitbook.io/optifi/security/audit-report

Website Link:
https://www.optifi.app/

Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): https://drive.google.com/file/d/16m0gIp-HTlPOKSnkm1gS024uaUDP2U72/view?usp=sharing
Current TVL: 411.24 k
Chain: Solana
Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
N/A

Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

Short Description (to be shown on DefiLlama):
OptiFi is an option DEX with portfolio margining and delta-neutral options market making vaults on Solana. The automatic options market maker (OMM) with a delta-neutral strategy allows all users to deposit USDC to generate yield while limiting delta risk by providing liquidity on OptiFi.

Token address and ticker if any:
N/A

Category (full list at https://defillama.com/categories) *Please choose only one:
Options

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Pyth and Switchboard

forkedFrom (Does your project originate from another project):
N/A

methodology (what is being counted as tvl, how is tvl being calculated):
OptiFi uses the total of amm usdc balance, user usdc balance in the options margin account, and serum market pcVault to calculate TVL. The data doesn’t include Mango positions so there’s a difference from what is displayed on our app.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/optifi exports TVL: 
        
 
 
    solana                    412.17 k
    
    total                    412.17 k

**Comment by g1nt0ki** [comment]
@LeoOptiFi  what do you think of this? https://github.com/DefiLlama/DefiLlama-Adapters/pull/3615 I tried turning our adapter completely on-chain, is that correct implementation?

**Comment by LeoOptiFi** [comment]
so you mean I have to turn our adapter to on-chain, rather then call api way?

**Comment by g1nt0ki** [comment]
> so you mean I have to turn our adapter to on-chain, rather then call api way?

preferable yes, but I think I have already done that, wanted you to review my implementation: https://github.com/DefiLlama/DefiLlama-Adapters/blob/2037698045c240aa62cb6e028a7a5408bf69b5ba/projects/optifi/index.js

**Comment by g1nt0ki** [comment]
@LeoOptiFi sorry, I have merged the other one for now (I had more changes in solana helper that other other adapters were dependent on, so had to merge the branch). Please have a look when you have time and let me know if there is some bug

**Comment by LeoOptiFi** [comment]
hello, thank you for trying to help us complete the optifi adapter, and we also checked the code, the content is perfect, but the balance of the serum pcVault is missing. The way we are thinking of now is to hardcode these vaults, and here is the vault address

**Comment by LeoOptiFi** [comment]
```
[
    "38WWL1VwNmMPqVg51U1VrpW2ytrWMJJCwtemvgt8raSu",
    "DYMoBxD7kZ8dsRz5sDassSoSxGH9LeCSwLRYyAtp3QG5",
    "4AVQH2MHvU2hBDZ8nDe9Wg6r98un6KpjmjMM2N21pY5d",
    "FogPyqBdiTEWZVud3XVpqPMoW8Gfd7osB4jTitoodrzo",
    "BPWwKZd95fAiDKuit72TWNPqkFwtHiHkgb5LrRc6EABs",
    "8o8auMW3vy4qhGcd9a1BUkForN4spz2cWaztNgyMzKtP",
    "6P4XFpiuV6gUo2MiKAPEnWt7gDSxH6F872dbJBzCESyg",
    "2xPo4TLK66wA8Uy1uHRsYmXizcXbBKAhaFHHuWBh6M1n",
    "HxiAa3msfgczD75qXEWM5FeqsgAwGvX7ycM5sopP3LYc",
    "6usPMgY7vGxQSTJ3Xfd5HsziD6dcfzMxWXZtHZ2Qgidh",
    "BTV3Xm7SMH5YxHYKvaBBtwGXxAoMXVMyr5Kz3yScdyHT",
    "6ErKVzqLwq6oZriVMkCQLsP2a6U8pJ9YUQpnijBdnyxq",
    "9MovPBQYQJSfxYaEA7UDs8pvBmAtjLXb7ycFwZUKjc26",
    "5XeZa78PipX7b93BGDDwv6fWnjVeL4s6epicCDais8fD",
    "F3G9AMW6CYMSJtGFYL7qcLTo3enfui9gquTvpFRb4F14",
    "8d2oaNY2tkRXXoEifar64FkH9rvTGqVEcaZd1aYWmx9Q",
    "8tJE3sQLUZLe89CfQfeeypnDYsizmkMxALnxwWwMcqrS",
    "8ggcSPawAgzNEQ8RUtspPCZZvTpeT3bFEw7tMQvydch",
    "H8yssBnCci6b6w2aMJsMzXFX9dQzDAT6XxbxEuwKhSzA",
    "649nbpVo6iEU7jMzpMJmQQ9H7vzNLPnyg6YDUbE2vJGe",
    "3UsAjfdEzJWo7WyCvV5cqk4xKG2FR9JKHM7MiRxu8t9D",
    "81AaLXcFUFnU1bEajrM9tGcfNKej4wEUqeo17K3DNw5G",
    "9kuVJFwtvpZR466De9nZYTHZJHBVjA52p1pCt7EUgbff",
    "2PbrkRgZpKmADRrYvTshooC3YqGFewt1JguaP8wAtQrZ",
    "FsctDV8armyXZAVidRXQJ1SCMTD5r299PQY5eVNs5x3d",
    "JDYCZomM2Ew1urspaQGqBLXao1Ur3gb27gTTG9yZQhKd",
    "9rkoEntjgEu1vX92cSCyUpnymRUEUoNRsL1WnT5XMftr",
    "DzXUm5eGk6GdA4HkakMfjPskV2LUST3eoX49goTKUWHM",
    "HpfnM4hganS3Vgz1RwgGstdFA4uRkDKkiUDKqFZpdDvd",
    "FzmPZafEkEheA8gGkuhZXe6RBrEUEprqBpL44VuzK9p9",
    "4i4TCmqjRbhV1E7e556GR6d9ePpUjXRC8pN57nRw17Ce",
    "FQt1fLVLSH47Tnc2GU4ErcgAqtVC6wtSvRFJYkYrzmAK"
]
```

**Comment by g1nt0ki** [comment]
I have added it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/3647 , closing this PR

**Pull request closed without merging**
