### PR TITLE
Added rivrkitty farm

### PR DESCRIPTION
**Pull request by rivrkitty**
##### Twitter Link:
https://twitter.com/RivrKitty

##### List of audit links if any:
https://github.com/rivrkitty/rivrkitty-contracts/raw/master/audits/TechRate.pdf

##### Website Link:
https://www.rivrkitty.com

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://raw.githubusercontent.com/solarbeamio/solarbeam-tokenlist/main/assets/moonriver/0xC2b0435276139731d82Ae2Fa8928c9b9De0761c1/logo.png

##### Current TVL:
$163,351.00

##### Chain:
Moonriver

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
rivrkitty

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
14934

##### Short Description (to be shown on DefiLlama):
An Emerging Play‑to‑Earn KittyVerse Blending DeFi & NFTs.

##### Token address and ticker if any:
0xC2b0435276139731d82Ae2Fa8928c9b9De0761c1 RKITTY

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Staking

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
API3

##### forkedFrom (Does your project originate from another project):
Farm is forked from Solarbeam Distributor contract (which is a fork of PancakeSwap Chef contract).

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is being calculated on our API with using Huckleberry graph api. TVL comes from our farm which have 2 pool types: 
- normal ones - standard one like it is on
- with additional rewards - which works in a way that it sends LP to external farm which give additional reward

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Can this be exported as 'pool2', with core tvl as 0? If I understand correctly this counts the liquidity in FINN-RKITTY and MOVR-RKITTY pools. We separate pools where one side is the platform native token from core tvl, by request from the community.

**Comment by rivrkitty** [comment]
> Can this be exported as 'pool2', with core tvl as 0? If I understand correctly this counts the liquidity in FINN-RKITTY and MOVR-RKITTY pools. We separate pools where one side is the platform native token from core tvl, by request from the community.

Thanks for input. Could you tell me what should I do when I have such module exports?
Are there any docs for this?

```
module.exports = {
  moonriver: {
    fetch,
  },
  fetch,
};

```

**Comment by waynebruce0x** [comment]
On second thoughts - it'd probably be easier if we made an on-chain adapter. Are all the LP tokens staked in 0x995ef3a5D14b66Ac5C7Fa1a967F8D9Cd727452bA or are there other contracts?

**Comment by rivrkitty** [comment]
> On second thoughts - it'd probably be easier if we made an on-chain adapter. Are all the LP tokens staked in 0x995ef3a5D14b66Ac5C7Fa1a967F8D9Cd727452bA or are there other contracts?

Yeah, but problem is that adapters requires to retrieve data in specified timestamp/block which currently is not possible on our api.

**Comment by waynebruce0x** [comment]
On-chain adapter in #1051 , let me know if there are any issues with this adapter. Closing this PR for now.

**Pull request closed without merging**
