### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by OPtitudeFi**
**NOTE**

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Optitude Finance

##### Twitter Link:
https://twitter.com/TrueOptitude

##### Website Link:
optitude.finance

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://github.com/OPtitudeFi/Logo

##### Current TVL:
0

##### Chain:
Optimism

##### Short Description (to be shown on DefiLlama):
Optitude, a yield aggregator specially built for Layer2 users.

##### Token address and ticker if any:
https://optimistic.etherscan.io/address/0xAd669b6cf06704e9D3b8D1d85A275623A1bD8288#code
OPT

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield Aggregator

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/optitude exports TVL: 
        
 
 
    optimism                  0
    optimism-pool2            0
    optimism-staking          0
    pool2                     0
    staking                   0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/optitude exports TVL: 
        
 
 
    optimism                  0
    optimism-pool2            0
    pool2                     0
    
    total                    0

**Comment by Define101** [comment]
image
Is the website live already?

**Comment by OPtitudeFi** [comment]
> image Is the website/protocol live already?

Still under development. We haven't launched yet

**Comment by OPtitudeFi** [comment]
> Thanks for the reply Could you please inform us once it's live please?
Our website is now live, you can check it out now

**Comment by OPtitudeFi** [comment]
> Thanks for the reply Could you please inform us once it's live please?

Our website is now live, you can check it out now

**Comment by OPtitudeFi** [comment]
> 感谢您的回复 ，请在直播后通知我们好吗？
@Define101 
The website is live, you can check it out

**Comment by OPtitudeFi** [comment]
> Thanks for the reply Could you please inform us once it's live please?

The website is live, you can check it out @Define101

**Comment by g1nt0ki** [comment]
sorry, missed the message earlier

**Comment by g1nt0ki** [comment]
@OPtitudeFi the adapter is not working, can you please take a look at the code

**Comment by g1nt0ki** [comment]
@OPtitudeFi okay, I have fixed the issue but, it still wont show up in the UI unless there is some tvl, (this is how the UI is set-up)

**Pull request merged**
