### PR TITLE
Added saltyio adapter

### PR DESCRIPTION
**Pull request by othernet-global**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Salty.IO

##### Twitter Link:
https://x.com/salty_io

##### List of audit links if any:
Trail of Bits: https://github.com/trailofbits/publications/blob/master/reviews/2023-10-saltyio-securityreview.pdf

ABDK: https://github.com/abdk-consulting/audits/blob/main/othernet_global_pte_ltd/ABDK_OthernetGlobalPTELTD_SaltyIO_v_2_0.pdf

Code4rena: https://code4rena.com/reports/2024-01-salty

##### Website Link:
https://salty.io

##### Logo (High resolution, will be shown with rounded borders):
https://salty.io/images/salt_icon.png

##### Current TVL:
$174k

##### Treasury Addresses (if the protocol has treasury)
0x35fdBd5b52D131629EA5403FF1bc7ff6A1869D60

##### Chain:
Ethereum

##### Short Description (to be shown on DefiLlama):
Decentralized Ethereum exchange with Zero Fees and Native Swap Protection on all swaps.

##### Token address and ticker if any:
0x0110B0c3391584Ba24Dbf8017Bf462e9f78A6d9F SALT

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Chainlink

##### Implementation Details: Briefly describe how the oracle is integrated into your project:
Only used for the UI - providing the price of USDC in dollars.  The USDC price from Chainlink is then used to compute TVL for the UI.

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
https://etherscan.io/address/0x22096408044Db49A4eB871640b351Ccacb675ED6#code

obtainNonUserPoolInformation() in https://salty.io/js/crypto_utils.js

##### forkedFrom (Does your project originate from another project):
Not a fork

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is determine by returning the token reserve balances currently locked in the Pools contract.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/othernet-global/salty-io

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/saltyio exports TVL: 
        
 
 
    ethereum                  116.60 k
    ethereum-staking          0
    ethereum-treasury         0
    staking                   0
    treasury                  0
    
    total                    116.60 k

**Comment by othernet-global** [comment]
> The adapter at projects/saltyio exports TVL:
> 
> ```
> ethereum                  116.60 k
> ethereum-staking          0
> ethereum-treasury         0
> staking                   0
> treasury                  0
> 
> total                    116.60 k 
> ```

It should be about 126k:

--- ethereum-treasury ---
Total: 0 

--- ethereum-staking ---
Total: 0 

--- ethereum ---
usdc                      56.20 k
WETH                      52.14 k
wbtc                      9.05 k
usdt                      8.18 k
Total: 125.58 k 

--- treasury ---
Total: 0 

--- staking ---
Total: 0 

--- tvl ---
usdc                      56.20 k
WETH                      52.14 k
wbtc                      9.05 k
usdt                      8.18 k
Total: 125.58 k 

------ TVL ------
ethereum                  125.58 k
ethereum-treasury         0
ethereum-staking          0
treasury                  0
staking                   0

total                    125.58 k

**Comment by othernet-global** [comment]
Looks like WBTC is not being reported in the test script:

image

**Comment by g1nt0ki** [comment]
@othernet-global thanks for the PR

**Comment by llamatester** [comment]
The adapter at projects/saltyio exports TVL: 
        
 
 
    ethereum                  129.00 k
    ethereum-staking          0
    staking                   0
    
    total                    129.00 k

**Comment by llamatester** [comment]
The adapter at projects/treasury/saltyio.js exports TVL: 
        
 
 
    ethereum                  0
    ethereum-ownTokens        0
    ownTokens                 0
    
    total                    0

**Pull request merged**
