### PR TITLE
Fix CarthageDEX

### PR DESCRIPTION
**Pull request by samisbakedham**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@samisbakedham sorry, your protocol is not yet listed because I still dont trust the subgraph or the trades happening right now, if it is real tokens backed in other protocols, the prices on graph make no sense like eth was 1.9k last I checked, also the price of CNDL token was 10x higher than what coingecko was showing, and I need to check again, but right now buried under other things, but will get back to this sometime next week

**Comment by samisbakedham** [comment]
> @samisbakedham sorry, your protocol is not yet listed because I still dont trust the subgraph or the trades happening right now, if it is real tokens backed in other protocols, the prices on graph make no sense like eth was 1.9k last I checked, also the price of CNDL token was 10x higher than what coingecko was showing, and I need to check again, but right now buried under other things, but will get back to this sometime next week

Fair enough, we have pricing issues yes. Can we list with $0 TVL until Celer bridge integration?

**Comment by g1nt0ki** [comment]
@samisbakedham sorry, checked with others as well. They think 0 TVL is the wrong approach, think best course of action is, we wait for celer bridge integration and you can inform me on discord/put up a PR here.

**Comment by samisbakedham** [comment]
Ok that's fine. Any word on the regulatory aspect of this?

**Comment by g1nt0ki** [comment]
regulatory?

**Comment by samisbakedham** [comment]
> regulatory?

Well, yes. Public market data is regulated in America i think

**Pull request closed without merging**
