### PR TITLE
Molend - mode

### PR DESCRIPTION
**Pull request by asimof**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Molend

##### Twitter Link:
https://t.me/molend_protocol

##### Website Link:
https://molend.org/

##### Logo (High resolution, will be shown with rounded borders):
https://github.com/DefiLlama/DefiLlama-Adapters/assets/159416147/40d27154-a457-458c-8492-017d3725fd88

##### Current TVL:
$79.59

##### Chain:
Mode

##### Short Description (to be shown on DefiLlama):
Molend is a decentralized, non-custodial liquidity market protocol deployed on MODE, where users can participate as depositors or borrowers. The protocol enables depositors to provide liquidity to the market to earn a passive income and borrowers to borrow in an over-collateralized and perpetual fashion.

##### Token address and ticker if any:
N/A

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Pyth

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
see https://docs.molend.org/

##### forkedFrom (Does your project originate from another project):
Aave V2

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/molend-labs

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/molend exports TVL: 
        
 
 
    mode-borrowed             23.005072651905003
    mode                      56.351866687355795
    borrowed                  23.005072651905003
    
    total                    56.351866687355795

**Comment by asimof** [comment]
@Define101 thanks! I just made some slight change to the description, it would be awesome if you could help update: 

> Molend is a decentralized, non-custodial liquidity market protocol deployed on Mode Network, where users can participate as depositors or borrowers. The protocol allows depositors to provide liquidity to the market and earn passive income, while borrowers can borrow in an over-collateralized and perpetual manner.

**Comment by Define101** [comment]
> Molend is a decentralized, non-custodial liquidity market protocol deployed on Mode Network, where users can participate as depositors or borrowers. The protocol allows depositors to provide liquidity to the market and earn passive income, while borrowers can borrow in an over-collateralized and perpetual manner.

We will use this one. Regarding the oracle field. There is no mention in the docs

**Comment by asimof** [comment]
> We will use this one. Regarding the oracle field. There is no mention in the docs

The docs have been updated. Please check whether it works or not for you: https://docs.molend.org/oracles

**Comment by Define101** [comment]
@asimof thanks, confirmed

**Pull request merged**
