### PR TITLE
Wx.network.wx.staking

### PR DESCRIPTION
**Pull request by vba2000**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
wx network

##### Github org/user (Optional, if your code is open source, we can track activity):

Add new adapters: WX staking + WX pools
Add new WAVES assets in helper

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/wx-network-liqudity-pools exports TVL: 
        
 
 
    waves                     0
    waves-pool2               2.14 M
    pool2                     2.14 M
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/wx-network-wx exports TVL: 
        
 
 
    waves                     0
    waves-staking             1.51 M
    staking                   1.51 M
    
    total                    0

**Comment by g1nt0ki** [comment]
hi @vba2000, the helper code looks good, dont think we need a separate adapter for staking part, it can be merged with existing adapter for wx listing? 

wait, these two adapters can be merged and replace this one?

**Comment by g1nt0ki** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/waves-exchange/index.js

**Comment by vba2000** [comment]
Ok

**Comment by vba2000** [comment]
I think 1 product - 1 adapter, i can merge it

**Comment by llamatester** [comment]
The adapter at projects/wx-network exports TVL: 
        
 
 
    waves                     0
    waves-staking             4.88 M
    waves-pool2               1.96 M
    staking                   4.88 M
    pool2                     1.96 M
    
    total                    0

**Comment by vba2000** [comment]
> hi @vba2000, the helper code looks good, dont think we need a separate adapter for staking part, it can be merged with existing adapter for wx listing?
> 
> wait, these two adapters can be merged and replace this one?

Delete waves-exchange, Rename wx-network-waves to wx-network, join all in 1

**Comment by llamatester** [comment]
The adapter at projects/wx-network exports TVL: 
        
 
 
    waves                     0
    waves-staking             4.96 M
    waves-pool2               1.98 M
    staking                   4.96 M
    pool2                     1.98 M
    
    total                    0

**Comment by g1nt0ki** [comment]
@vba2000 sorry for the confusion, we will keep wx-staking as sub listing, as it is liquid staking product, different from dex. I have slightly modified the code here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/9437/files

**Comment by vba2000** [comment]
Ok, thank you!

**Pull request closed without merging**
