### PR TITLE
Kryptonite:SEI Liquid Staking Platform TVL

### PR DESCRIPTION
**Pull request by smithmonnnnnnn**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/kryptonite exports TVL: 
        
 
 
    sei                       1.03 M
    
    total                    1.03 M

**Comment by smithmonnnnnnn** [comment]
Name (to be shown on DefiLlama):
Kryptonite

Twitter Link:
https://twitter.com/Kryptonite_fi

List of audit links if any:

Website Link:
https://kryptonite.finance/

Logo (High resolution, will be shown with rounded borders):
https://app.kryptonite.finance/img/logo.png

Current TVL:
1.03 M

Treasury Addresses (if the protocol has treasury)

Chain:
Sei

Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

Short Description (to be shown on DefiLlama):
The Essential Engine for Liquid Staking, Leverage & Lending on Sei.

Token address and ticker if any:
sei10knxlv9e54z0xcywdhtycc63uf970aefeec73ycqwd75ep9nu45sh66m6a

Category (full list at https://defillama.com/categories) *Please choose only one:
LSD

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
PythOralce

forkedFrom (Does your project originate from another project):
https://github.com/DefiLlama/DefiLlama-Adapters

methodology (what is being counted as tvl, how is tvl being calculated):
Count the value of a user's SEI staked on the platform and the value of the user's SEI/SEILOR liquidity LP added on Astroport.

Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/KryptoniteDAO/

**Comment by realdealshaman** [comment]
Hey, @smithmonnnnnnn thanks for the PR. It looks good except that we can't count the LPs in Astroport as that TVL belongs to Astroport and is already being counted there. Please update so that we are only counting the staked SEI and we can get it merged and listed. Thanks

**Comment by realdealshaman** [comment]
@smithmonnnnnnn I will merge it and make the update to export SEIL-USEI-LP value as pool2. Thanks for the PR

**Comment by smithmonnnnnnn** [comment]
@realdealshaman thank you very much for your help

**Pull request merged**
