### PR TITLE
Implement adapter for Friktion.Fi ($40M TVL, Solana structured products)

### PR DESCRIPTION
**Pull request by smolbirdy**
We have a cron job on GitHub actions that should push the latest snapshot to that repo. Our script has careful santization to make sure only good data is on that file.

Since the protocol is really young and changing, we decided to just get data from the app since that would be more accurate. Due to how the friktion smart contracts are structured, the TVL info for each asset is actually in multiple accounts and changes every week.

##### Twitter Link:
https://twitter.com/friktion_labs

##### List of audit links if any:
None

##### Website Link:
https://friktion.fi/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
logo

##### Current TVL:
```
--- tvl ---
solana                    11.41 M
msol                      10.32 M
bitcoin                   6.91 M
ftx-token                 137.77 k
serum                     133.13 k
ethereum                  121.23 k
Total: 29.03 M 

------ TVL ------

total                    29.03 M
```

##### Chain:
Solana

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
No token yet

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
No token yet

##### Short Description (to be shown on DefiLlama):
Friktion is a crypto-asset portfolio management platform, built to perform across market cycles. Volts, Friktion’s native structured products, offer sustainable income generation and volatility yield strategies. Designed for individuals and DAOs.

##### Token address and ticker if any:
No token yet

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Options

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
N/A

##### forkedFrom (Does your project originate from another project):
original

##### methodology (what is being counted as tvl, how is tvl being calculated):
Methodology is in the `module.exports.methodology`.

Please feel free to change it. I drafted it up in 20 seconds and then decided to not look at it again.

### CODE REVIEW

**Comment by 0xngmi** [comment]
what about just pasting the script that calculates tvl directly into the adapter instead?

**Comment by waynebruce0x** [comment]
Closing this PR since theres an updated version

**Comment by 0xngmi** [comment]
since none of the PRs actually provide a script to calculate TVL that doesn't rely on complete trust in friktion this one seems better just because of extra robustness

**Comment by smolbirdy** [comment]
We promise we will maintain this through the entirety of 2022 (probably later too). And eventually, we may write a proper adapter that reads from account buffers

**Pull request merged**
