### PR TITLE
Update Zunami main contract address

### PR DESCRIPTION
**Pull request by MioGreen**

### CODE REVIEW

**Comment by g1nt0ki** [comment]
This code has a bug, instead of taking the block from function argument, it is using a constant `const startBlock = 14255781`

**Comment by 0xngmi** [comment]
current chart, i guess all caused by the constant block
image

**Comment by waynebruce0x** [comment]
I PRd to fix it

**Comment by MioGreen** [comment]
@MioGreen for now we are going to be deployed only on Ethereum.

**Pull request merged**
