### PR TITLE
Thetanuts finance edit adaptor with new products

### PR DESCRIPTION
**Pull request by bzhongy**
Thetanuts finance edit - add new options products on arbitrum and zkevm, edit hallmark

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/thetanuts: 
        
 
  
    
    
    Error: 
            Incorrect time format for the hallmark: [NaN, Launch of Thetanuts Finance v3] ,please use unix timestamp

**Comment by llamatester** [comment]
The adapter at projects/thetanuts exports TVL: 
        
 
 
    polygon                   174.73 k
    avax                      53.12 k
    boba                      59.84 k
    arbitrum                  89.41 k
    aurora                    4.06 k
    fantom                    639.70 k
    polygon_zkevm             30.81 k
    bsc                       115.28 k
    cronos                    5.84 k
    ethereum                  9.12 M
    
    total                    10.29 M

**Comment by bzhongy** [comment]
Thank you!

**Comment by bzhongy** [comment]
apologies, accidently closed. can we pls merge these changes

**Comment by llamatester** [comment]
The adapter at projects/thetanuts exports TVL: 
        
 
 
    fantom                    678.22 k
    polygon                   158.86 k
    avax                      50.61 k
    bsc                       112.08 k
    arbitrum                  126.80 k
    polygon_zkevm             27.14 k
    boba                      57.11 k
    aurora                    5.17 k
    cronos                    5.54 k
    ethereum                  8.99 M
    
    total                    10.21 M

**Review by g1nt0ki — COMMENTED** [review]
thanks for the PR :)

**Pull request merged**
