### PR TITLE
feat: Add double2win.xyz

### PR DESCRIPTION
**Pull request by 0xweb3loop**
##### Name (to be shown on DefiLlama):
Double

##### Twitter Link:
https://x.com/double2winwin

##### Website Link:
https://www.double2win.xyz/#

##### Logo (High resolution, will be shown with rounded borders):
512x512_App_Icon

##### Current TVL:
23.05M

##### Treasury Addresses (if the protocol has treasury)
-

##### Chain:
Arbitrum

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): 
-

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): 
-

##### Short Description (to be shown on DefiLlama):
Empower crypto AI, DePIN, RWA, and all token projects to solve their on-chain liquidity challenges by offering 300K+ AMM LPs the same benefits exclusive to CEX pro market makers. Attract massive capital into blockchain & AMM ecosystems by offering capital providers positive risk-adjusted yields.

##### Token address and ticker if any:
-

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Liquidity Manager

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
TWAP Price Oracle has been integrated from the contract. Uniswap V3 uses the TWAP and we have used the same logic from our contract regarding with the oracle integration.

##### forkedFrom (Does your project originate from another project):
-

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL has been calculated based on the locked assets and LP tokens from the AssetVault, AMMVault and AMMMigration contracts on Arbitrum

##### Github org/user (Optional, if your code is open source, we can track activity):
[Double](https://github.com/double2win)

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/double2win exports TVL: 
        
 
 
    arbitrum                  23.08 M
    
    total                    23.08 M

**Comment by g1nt0ki** [comment]
unsure how you are getting 23m, I am getting only 5k: https://github.com/DefiLlama/DefiLlama-Adapters/pull/11344

**Comment by g1nt0ki** [comment]
also, it is not very clear what your protocol does

**Comment by 0xdouble** [comment]
> also, it is not very clear what your protocol does

@g1nt0ki First, let me explain what the protocol does. Double enables permissionless & trustless collaboration between the two sides of an AMM LP pool, e.g. token (any token) side and capital (stable, ETH, BTC) side, to win together. Think of it like a liquidity marketplace where capital and token are matched to create an AMM LP position. Double solves the liquidity challenges faced by projects on one side and make AMM LPing profitable for capital providers on the other side. (Hence, the double2win). 

Second, can we add a new category like "liquidity marketplace"? The "liquidity manager" category is not a good fit since Double has nothing to do with concentrated liquidity management. What is the process for adding a new category to the list here: https://defillama.com/categories?

Third, early stages tokens like meme coins have figured out that Double is perfect solution for them since Double's innovations can protect capital providers on volatility and big price drop. Since these tokens are still early and we need to use "sumUnknownTokens" instead of "sumTokens2" to compute the TVL. 

Forth, it seems clear to us that we should close this PR and resubmit a new PR with new code and new category. We will proceed after we receive your guidance on how to create a "new category".

**Comment by g1nt0ki** [comment]
ah, I see that 99% of the supply is locked in your contract https://arbiscan.io/token/0x13654df31871b5d01e5fba8e6c21a5d0344820f5#balances leading to 23m but total of 5k in liquidity sorry cant use `sumUnknownTokens` here

 "liquidity marketplace" is bit niche, once more project offer similar service, we will look into adding this category, thanks for the PR, I just merged my refactor

**Comment by 0xdouble** [comment]
@g1nt0ki Thanks for note. I have further comments and questions:

First, the tokens are "NOT locked" in the smart contract. By design, any holder of any token can deposit tokens into Double on the token side, which is implemented similar to the "supply side" of a lending protocol, e.g. tokens are pooled together. Then when capital providers supple capital (stables/ETH/BTC) into Double, these tokens will be matched based on spot AMM price, and then these tokens will be moved into AMMs along with the capital supplied to create AMM LP positions. This is how Double works. We are impressed by the many creative ways that token projects use Double. For example, the token you referred to is a meme coin that wants to do fair-launch. It deposited most supply into Double so as to build up liquidity over time using capital from the community and to assure the community that there will be no token to dump on them.

Second, what is the common guideline on how much liquidity is needed to use "sumUnknownTokens". I could not find it online. Could you kindly share? And can you also share an example project that uses "sumUnknownTokens" and the liquidity amount it has?

Third, any new innovation always starts as a niche. If DeFiLlama is not ready to add a new category, then the best fit with existing categories is "Services". It is a generic one but better than "Liquidity Manager" category since Double has nothing to do with "manage Liquidity Positions in concentrated liquidity AMMs". We believe we should provide clear information on DeFiLlama instead of confusing information. Are you OK with "Services" category for Double?

**Comment by g1nt0ki** [comment]
Yes, anyone can deposit but in this case one person deposited 99% of the token supply: 
image

and you are arguing that we should include it as tvl

**Comment by 0xdouble** [comment]
It's not a person. It is the meme coin ERC20 contract that deposited into Double but it can't withdraw. So tokens can only be matched with capital and moved into AMMs, but can't be dumped to the community. That's the design.

**Comment by g1nt0ki** [comment]
Well, we shouldn't count it in that case either, since these tokens are not part of circulating supply

**Comment by 0xdouble** [comment]
Well, if they are not part of the circulating supply, how can capital providers supply capital and borrow those tokens to create AMM LP positions?

**Comment by g1nt0ki** [comment]
I will ask a different question, if I create tokenX with 1 billion supply, deposit 99%  of it into my smart contract, and deposit 100 tokens against 100 USDC tokens into LP, so each token is worth 1$ then smart contract holds tvl of 990m? is this really your argument?

**Comment by 0xdouble** [comment]
Of course, that's not my argument. Your argument that those tokens are not in circulation is technically wrong and hence I disagree. 

This is why I think you/DeFiLlama have a guidance on liquidity amount to use "sumUnknownTokens" and I think that's fair. I have asked for the guidance. Again, here is my previous question:

"Second, what is the common guideline on how much liquidity is needed to use "sumUnknownTokens". I could not find it online. Could you kindly share? And can you also share an example project that uses "sumUnknownTokens" and the liquidity amount it has?"

Can you provide the guidance and examples?

**Comment by g1nt0ki** [comment]
hmm, there is no documented guideline for `sumUnknownTokens`, but using it in this case is def wrong.

For example, we have listed a launchpad "Wen markets", it has token generation & LP functionality, but we count only the matic in the contract, not the memecoins in it even though they can be priced.

**Comment by 0xdouble** [comment]
Given that there is no guideline, the fair process should be that projects should have the right to "freely" use the "sumUnknownTokens" and the source code submitted should NOT be modified to remove the usage of "sumUnknownTokens".

I have to respectfully disagree with your opinion. Because the community norm on TVL is the value of circulated tokens deposited into projects' smart contracts. Here is an example to illustrate my point. I was told that Brett, a meme coin on Coinbase' Base L2 chain, has about a market cap of $1.3B, but 90%+ is owned by 1 person even though all tokens are in circulation; and Double's innovations enable a much better approach for the community to supply capital to LP meme coins since capital providers don't face the risk of being dumped. The relevance to our discussion here is that Brett's $1.3B TVL has been counted as Base's total TVL and is about 20% of Base' total TVL. I believe it is fair because Brett is issued natively on Base and all tokens are in circulation, and based on the community norm, Brett's TVL should be counted. 

Your example of "Wen market" is a bad example. I don't believe (not 100% sure) that "sumUnknownTokens" can source price feeds from the bonding curve used by "Wen market". So even if it wants, it can't compute the TVL of those meme coins by using "sumUnknownTokens". When those meme coins have price feeds from AMMs, by design, they have been moved outside smart contracts of "wen market" and should not be counted as TVL of "Wen market".

DeFiLlama has done a great job! To continue its success, it should be unopinionated about each individual token or project. It should maintain the community norm and let the community evaluate those TVL numbers. It is rude to arbitrarily modify the source code based on individual opinion, and merge the PR without further discussion with the project. It makes DeFiLlama look bad to use the argument of "the tokens are not in circulation which is technically wrong since the tokens are in circulation". I am sharing my opinions here because I care about DeFiLlama and sincerely wish its continued success.

**Pull request closed without merging**
