### PR TITLE
Added fxswap/index.js

### PR DESCRIPTION
**Pull request by YP010**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by vrtnd** [comment]
Hi. Thanks for the PR.
Can u rewrite your adapter using rpc call? Fetch adapters are not allowed anymore

**Comment by realdealshaman** [comment]
Hey @YP010 what is the factory address for the amm dex you want listed? I can look into creating the adapter and adding F(x)core into our sdk

**Comment by llamatester** [comment]
The adapter at projects/fxswap exports TVL: 
        
 
 
    functionx                 116.29 k
    
    total                    116.29 k

**Comment by YP010** [comment]
Can I change the website link to the below? 
**Website Link: https://fx-swap.io/#/swap**

**Comment by g1nt0ki** [comment]
@YP010 I have fixed it,  update will reflect in the UI in the next 2-3 hours

**Pull request merged**
