### PR TITLE
[Refactor] Update projects to use `getUniTVL` instead of `uniTvlExport`

### PR DESCRIPTION
**Pull request by Avedith**
Will create a list of projects that have been updated for reference.

- [x] HSwap
- [x] Wanswap
- [x] 3xcalibur

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/hswap.js exports TVL: 
        
 
 
    heco                      51.40 k
    
    total                    51.40 k

**Comment by llamatester** [comment]
The adapter at projects/3xcalibur exports TVL: 
        
 
 
    arbitrum                  4.67 M
    
    total                    4.67 M

**Comment by llamatester** [comment]
The adapter at projects/hswap.js exports TVL: 
        
 
 
    heco                      51.40 k
    
    total                    51.40 k

**Comment by llamatester** [comment]
The adapter at projects/3xcalibur exports TVL: 
        
 
 
    arbitrum                  4.67 M
    
    total                    4.67 M

**Comment by llamatester** [comment]
The adapter at projects/hswap.js exports TVL: 
        
 
 
    heco                      51.60 k
    
    total                    51.60 k

**Comment by llamatester** [comment]
The adapter at projects/wanswap.js exports TVL: 
        
 
 
    wan                       4.88 M
    
    total                    4.88 M

**Comment by g1nt0ki** [comment]
@Avedith any particular reason for this update?

**Comment by llamatester** [comment]
The adapter at projects/3xcalibur exports TVL: 
        
 
 
    arbitrum                  4.66 M
    
    total                    4.66 M

**Comment by llamatester** [comment]
The adapter at projects/BombFinance exports TVL: 
        
 
 
    fantom                    261.01 k
    
    total                    261.01 k

**Comment by llamatester** [comment]
The adapter at projects/Equalizer exports TVL: 
        
 
 
    fantom-staking            9.74 M
    fantom                    41.89 M
    staking                   9.74 M
    
    total                    41.89 M

**Comment by llamatester** [comment]
The adapter at projects/alligator-exchange exports TVL: 
        
 
 
    avax-staking              501.89783208
    avax                      13.76 k
    staking                   501.89783208
    
    total                    13.76 k

**Comment by llamatester** [comment]
The adapter at projects/auroraswap exports TVL: 
        
 
 
    aurora-staking            481.90731123059527
    aurora                    274.05 k
    staking                   481.90731123059527
    
    total                    274.05 k

**Comment by llamatester** [comment]
The adapter at projects/bakeryswap exports TVL: 
        
 
 
    bsc-staking               5.39 M
    bsc                       7.93 M
    staking                   5.39 M
    
    total                    7.93 M

**Comment by llamatester** [comment]
The adapter at projects/baoswap exports TVL: 
        
 
 
    xdai                      267.92 k
    
    total                    267.92 k

**Comment by llamatester** [comment]
The adapter at projects/bitindi-dex exports TVL: 
        
 
 
    bitindi                   1.30 M
    
    total                    1.30 M

**Comment by llamatester** [comment]
The adapter at projects/bullionFX exports TVL: 
        
 
 
    ethereum                  62.70 k
    
    total                    62.70 k

**Comment by llamatester** [comment]
The adapter at projects/butterswap exports TVL: 
        
 
 
    heco-staking              0
    bsc-staking               0
    bsc                       78.84 k
    heco                      12.68 k
    staking                   0
    
    total                    91.52 k

**Comment by llamatester** [comment]
The adapter at projects/bxh exports TVL: 
        
 
 
    avax                      2.34 k
    ethereum                  16.82 k
    okexchain                 84.04 k
    bsc                       52.46 k
    heco                      501.54 k
    
    total                    657.19 k

**Comment by llamatester** [comment]
The adapter at projects/camelot exports TVL: 
        
 
 
    arbitrum                  78.17 M
    
    total                    78.17 M

**Comment by llamatester** [comment]
The adapter at projects/cobraswap exports TVL: 
        
 
 
    bsc                       27.62 k
    
    total                    27.62 k

**Comment by llamatester** [comment]
The adapter at projects/crowfi exports TVL: 
        
 
 
    cronos                    97.81 k
    
    total                    97.81 k

**Comment by llamatester** [comment]
The adapter at projects/degenhaus exports TVL: 
        
 
 
    fantom-staking            2.46 k
    fantom                    135.35 k
    staking                   2.46 k
    
    total                    135.35 k

**Comment by llamatester** [comment]
The adapter at projects/dexit-swap exports TVL: 
        
 
 
    dexit                     130.93 k
    
    total                    130.93 k

**Comment by llamatester** [comment]
The adapter at projects/dinosaureggs exports TVL: 
        
 
 
    bsc                       639.98 k
    
    total                    639.98 k

**Comment by llamatester** [comment]
The adapter at projects/duckydefi exports TVL: 
        
 
 
    cronos                    57.52 k
    
    total                    57.52 k

**Comment by llamatester** [comment]
The adapter at projects/duneswap.js exports TVL: 
        
 
 
    oasis                     38.48 k
    
    total                    38.48 k

**Comment by llamatester** [comment]
The adapter at projects/excalibur exports TVL: 
        
 
 
    fantom                    108.13 k
    
    total                    108.13 k

**Comment by llamatester** [comment]
The adapter at projects/frogswap-kekchain exports TVL: 
        
 
 
    kekchain                  150.02853565738442
    
    total                    150.02853565738442

**Comment by llamatester** [comment]
The adapter at projects/fuzzfinance exports TVL: 
        
 
 
    harmony-staking           87.93 k
    harmony                   47.59 k
    staking                   87.93 k
    
    total                    47.59 k

**Comment by llamatester** [comment]
The adapter at projects/gravity-finance exports TVL: 
        
 
 
    polygon                   433.34 k
    
    total                    433.34 k

**Comment by llamatester** [comment]
The adapter at projects/hakuswap exports TVL: 
        
 
 
    avax-staking              7.36 k
    avax                      120.29 k
    staking                   7.36 k
    
    total                    120.29 k

**Comment by llamatester** [comment]
The adapter at projects/hermes-protocol exports TVL: 
        
 
 
    metis-staking             8.02 M
    metis                     10.93 M
    staking                   8.02 M
    
    total                    10.93 M

**Comment by llamatester** [comment]
The adapter at projects/hiveswap exports TVL: 
        
 
 
    map                       559.59 k
    
    total                    559.59 k

**Comment by llamatester** [comment]
The adapter at projects/hswap.js exports TVL: 
        
 
 
    heco                      51.07 k
    
    total                    51.07 k

**Comment by llamatester** [comment]
The adapter at projects/jetfuelfinance exports TVL: 
        
 
 
    bsc-borrowed              2.95 M
    bsc                       1.25 M
    borrowed                  2.95 M
    
    total                    1.25 M

**Comment by llamatester** [comment]
The adapter at projects/jetswap exports TVL: 
        
 
 
    fantom-staking            0
    polygon-staking           0
    bsc-staking               0
    fantom                    60.24 k
    polygon                   384.10 k
    bsc                       682.74 k
    staking                   0
    
    total                    1.13 M

**Comment by llamatester** [comment]
The adapter at projects/wanswap.js exports TVL: 
        
 
 
    wan                       4.88 M
    
    total                    4.88 M

**Comment by llamatester** [comment]
The adapter at projects/3xcalibur exports TVL: 
        
 
 
    arbitrum                  4.66 M
    
    total                    4.66 M

**Comment by llamatester** [comment]
The adapter at projects/BombFinance exports TVL: 
        
 
 
    fantom                    260.64 k
    
    total                    260.64 k

**Comment by llamatester** [comment]
The adapter at projects/Equalizer exports TVL: 
        
 
 
    fantom-staking            9.74 M
    fantom                    41.87 M
    staking                   9.74 M
    
    total                    41.87 M

**Comment by llamatester** [comment]
The adapter at projects/alligator-exchange exports TVL: 
        
 
 
    avax-staking              502.89962416000003
    avax                      13.77 k
    staking                   502.89962416000003
    
    total                    13.77 k

**Comment by llamatester** [comment]
The adapter at projects/auroraswap exports TVL: 
        
 
 
    aurora-staking            482.24244045970875
    aurora                    274.27 k
    staking                   482.24244045970875
    
    total                    274.27 k

**Comment by llamatester** [comment]
The adapter at projects/bakeryswap exports TVL: 
        
 
 
    bsc-staking               5.40 M
    bsc                       7.93 M
    staking                   5.40 M
    
    total                    7.93 M

**Comment by llamatester** [comment]
The adapter at projects/baoswap exports TVL: 
        
 
 
    xdai                      266.98 k
    
    total                    266.98 k

**Comment by llamatester** [comment]
The adapter at projects/bitindi-dex exports TVL: 
        
 
 
    bitindi                   1.30 M
    
    total                    1.30 M

**Comment by llamatester** [comment]
The adapter at projects/bullionFX exports TVL: 
        
 
 
    ethereum                  62.76 k
    
    total                    62.76 k

**Comment by llamatester** [comment]
The adapter at projects/butterswap exports TVL: 
        
 
 
    bsc-staking               0
    bsc                       78.88 k
    heco-staking              0
    heco                      12.78 k
    staking                   0
    
    total                    91.66 k

**Comment by llamatester** [comment]
The adapter at projects/bxh exports TVL: 
        
 
 
    bsc                       52.47 k
    avax                      2.34 k
    ethereum                  16.82 k
    okexchain                 84.18 k
    heco                      508.15 k
    
    total                    663.96 k

**Comment by llamatester** [comment]
The adapter at projects/camelot exports TVL: 
        
 
 
    arbitrum                  78.17 M
    
    total                    78.17 M

**Comment by llamatester** [comment]
The adapter at projects/cobraswap exports TVL: 
        
 
 
    bsc                       27.63 k
    
    total                    27.63 k

**Comment by llamatester** [comment]
The adapter at projects/crowfi exports TVL: 
        
 
 
    cronos                    97.84 k
    
    total                    97.84 k

**Comment by llamatester** [comment]
The adapter at projects/degenhaus exports TVL: 
        
 
 
    fantom-staking            2.45 k
    fantom                    135.36 k
    staking                   2.45 k
    
    total                    135.36 k

**Comment by llamatester** [comment]
The adapter at projects/dexit-swap exports TVL: 
        
 
 
    dexit                     130.97 k
    
    total                    130.97 k

**Comment by llamatester** [comment]
The adapter at projects/dinoexchange exports TVL: 
        
 
 
    bsc-staking               0
    bsc                       7.56 k
    staking                   0
    
    total                    7.56 k

**Comment by llamatester** [comment]
The adapter at projects/dinosaureggs exports TVL: 
        
 
 
    bsc                       640.48 k
    
    total                    640.48 k

**Comment by llamatester** [comment]
The adapter at projects/duckydefi exports TVL: 
        
 
 
    cronos                    57.55 k
    
    total                    57.55 k

**Comment by llamatester** [comment]
The adapter at projects/duneswap.js exports TVL: 
        
 
 
    oasis                     38.51 k
    
    total                    38.51 k

**Comment by llamatester** [comment]
The adapter at projects/excalibur exports TVL: 
        
 
 
    fantom                    108.07 k
    
    total                    108.07 k

**Comment by llamatester** [comment]
The adapter at projects/frogswap-kekchain exports TVL: 
        
 
 
    kekchain                  150.1643080878436
    
    total                    150.1643080878436

**Comment by llamatester** [comment]
The adapter at projects/fuzzfinance exports TVL: 
        
 
 
    harmony-staking           88.00 k
    harmony                   47.23 k
    staking                   88.00 k
    
    total                    47.23 k

**Comment by llamatester** [comment]
The adapter at projects/gravity-finance exports TVL: 
        
 
 
    polygon                   433.55 k
    
    total                    433.55 k

**Comment by llamatester** [comment]
The adapter at projects/hakuswap exports TVL: 
        
 
 
    avax-staking              7.38 k
    avax                      120.35 k
    staking                   7.38 k
    
    total                    120.35 k

**Comment by llamatester** [comment]
The adapter at projects/hiveswap exports TVL: 
        
 
 
    map                       559.98 k
    
    total                    559.98 k

**Comment by llamatester** [comment]
The adapter at projects/hswap.js exports TVL: 
        
 
 
    heco                      51.56 k
    
    total                    51.56 k

**Comment by llamatester** [comment]
The adapter at projects/jetfuelfinance exports TVL: 
        
 
 
    bsc-borrowed              2.95 M
    bsc                       1.25 M
    borrowed                  2.95 M
    
    total                    1.25 M

**Comment by llamatester** [comment]
The adapter at projects/jetswap exports TVL: 
        
 
 
    bsc-staking               0
    fantom-staking            0
    polygon-staking           0
    fantom                    60.24 k
    polygon                   384.25 k
    bsc                       683.22 k
    staking                   0
    
    total                    1.13 M

**Comment by llamatester** [comment]
The adapter at projects/kaco exports TVL: 
        
 
 
    bsc-staking               3.94 k
    shiden-staking            0
    bsc                       16.00 k
    shiden                    54.07 k
    staking                   3.94 k
    
    total                    70.08 k

**Comment by llamatester** [comment]
The adapter at projects/kekswap exports TVL: 
        
 
 
    kekchain                  204.09472641483038
    
    total                    204.09472641483038

**Comment by llamatester** [comment]
The adapter at projects/knightswap exports TVL: 
        
 
 
    fantom-staking            250.23 k
    bsc-staking               559.70 k
    fantom                    908.67 k
    bsc                       7.69 M
    staking                   809.94 k
    
    total                    8.60 M

**Comment by llamatester** [comment]
The adapter at projects/kronosdao exports TVL: 
        
 
 
    bsc-staking               8.890744955849488
    bsc                       3.19 k
    staking                   8.890744955849488
    
    total                    3.19 k

**Comment by llamatester** [comment]
The adapter at projects/kswap exports TVL: 
        
 
 
    kava                      60.79 k
    
    total                    60.79 k

**Comment by llamatester** [comment]
The adapter at projects/latte exports TVL: 
        
 
 
    bsc-staking               0
    bsc                       65.69 k
    staking                   0
    
    total                    65.69 k

**Comment by llamatester** [comment]
The adapter at projects/leonicornswap exports TVL: 
        
 
 
    bsc-staking               64.83 k
    bsc                       27.85 k
    staking                   64.83 k
    
    total                    27.85 k

**Comment by llamatester** [comment]
The adapter at projects/levinswap exports TVL: 
        
 
 
    xdai-staking              540.018043353761
    xdai                      424.67 k
    staking                   540.018043353761
    
    total                    424.67 k

**Comment by llamatester** [comment]
The adapter at projects/wanswap.js exports TVL: 
        
 
 
    wan                       4.88 M
    
    total                    4.88 M

**Comment by Avedith** [comment]
Working on this locally for now. Will resubmit PR later.

**Pull request closed without merging**
