### PR TITLE
feat(projects): add JIBID

### PR DESCRIPTION
**Pull request by leojid**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Logo (High resolution, will be shown with rounded borders): https://github.com/DefiLlama/DefiLlama-Adapters/assets/154349617/2d5279ea-86f5-439d-ac96-28829b24aa89
JIBID

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/jibid exports TVL: 
        
 
 
    jbc                       0
    
    total                    0

**Comment by llamatester** [comment]
Error while running adapter at projects/treasury/jibid.js: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:217:11

**Comment by llamatester** [comment]
The adapter at projects/jibid exports TVL: 
        
 
 
    jbc                       0
    
    total                    0

**Comment by g1nt0ki** [comment]
hi @leojid thanks for the PR, but we cant count this as tvl but maybe under treasury since users will never get their tokens as they are paid as fees?

**Comment by leojid** [comment]
Hello, @g1nt0ki  Actually, 100% of the money from those contracts is our revenue; nevertheless, we are unsure on how to do the right PR. Could you perhaps provide me with guidance on how to achieve that?

The controller contract, 0xaB630401491EAe6B2967D49A78837F99EE93E4f7, receives native tokens from users who purchase a JIBID (the NFT). The multisig contract, 0xb749171763820383471a96a749874239f1c0a6f3, is where we will transfer all funds from the controller contract to distribute tokens to our team. (not intended for users).

**Comment by g1nt0ki** [comment]
hmm, in that case, your tvl is 0. We can track the fees/revenue, but another issue is, JBC is not on coingecko?

**Comment by leojid** [comment]
Hello, @g1nt0ki It is okay if TVL is zero; we only want to put our project on your platform in the hopes that it would help the JBC chain ecosystem develop.

**Comment by g1nt0ki** [comment]
@leojid sorry, we cant list with 0 tvl.

**Comment by leojid** [comment]
@g1nt0ki Ok then waiting for the price on Coingecko and we will discuss on this again. Thanks.

**Comment by g1nt0ki** [comment]
closing this for now, you can put up a new PR when you have some tvl

**Pull request closed without merging**
