### PR TITLE
ParaSpace: add ape tranferred to p2p into TVL

### PR DESCRIPTION
**Pull request by jfzhou5**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/paraspace exports TVL: 
        
 
 
    ethereum-borrowed         15.14 M
    ethereum                  37.90 M
    borrowed                  15.14 M
    
    total                    37.90 M

**Comment by jfzhou5** [comment]
Users supply their BAYC/MACY/BAKC into paraspace lending, then get the nToken like nBAYC, User can do lending using its nToken. But if user joins the p2p listing, the NFT will be transferred from nToken to P2PPairStaking contract, user still holds the nToken and can be used for lending , So the NFT held by P2PPairStaking contract need to be calculated into TVL.

**Comment by jfzhou5** [comment]
Another question, why can not we use our owned on-chain oracle price as the NFT price, you know benddao does that.

**Comment by g1nt0ki** [comment]
> Another question, why can not we use our owned on-chain oracle price as the NFT price, you know benddao does that. I see you refactor my code.

not sure how I missed  it, refactored it now: https://github.com/DefiLlama/DefiLlama-Adapters/commit/0b618ec2b63b6343e907bebdc5ca2f445e27d2ff

**Comment by g1nt0ki** [comment]
reason for not using oracles, users can see token/nft breakdown now, also now nfts are priced the same across protocols as same chainlink oracle

**Pull request merged**
