### PR TITLE
[sunrise-gaming-by-dao] Show total tvl

### PR DESCRIPTION
**Pull request by sunrisedao**
Add total tvl to sunrise-gaming-by-dao

Continue to https://github.com/DefiLlama/DefiLlama-Adapters/pull/486

### CODE REVIEW

**Comment by 0xngmi** [comment]
Hey, before I applied some changes that separate staking and pool2 from the total tvl, which we are applying to all projects, this PR is reverting those changes.

I understand that you'd like us to include all of them under core tvl but could you provide some reasoning as to why should we do so and make an exception for your case (we made one for synthethix since staking is an integral part of their core protocol)

**Comment by sunrisedao** [comment]
When I check my project in https://defillama.com/protocols/staking the TVL is not shows as other projects.

Screen Shot 2021-09-21 at 09 50 55

Could you advice on how to show the tvl as well?

**Comment by 0xngmi** [comment]
you should include staking and pool2 through this
image

**Comment by 0xngmi** [comment]
Closing for now, feel free to re-open with some reasoning

**Pull request closed without merging**
