### PR TITLE
Add KernelDAO project

### PR DESCRIPTION
**Pull request by inmarelibero**
##### Name (to be shown on DefiLlama):
Kernel DAO

##### Twitter Link:
https://x.com/kernel_dao

##### List of audit links if any:
https://kerneldao.gitbook.io/kernel/getting-started/openapi-1

##### Website Link:
https://kerneldao.com

##### Logo (High resolution, will be shown with rounded borders):
https://framerusercontent.com/assets/SG72s8vSesYjrhW2d1JifKiZMo.svg

##### Current TVL:
$44.7M

##### Chain:
BNB

##### Short Description (to be shown on DefiLlama):
Decentralised Security to supercharge & blitzscale BNB, while providing exciting rewards & DeFi opportunities.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Restaking

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
https://kerneldao.gitbook.io/kernel/

### CODE REVIEW

**Comment by llamabutler** [comment]
The adapter at projects/kernel-dao exports TVL: 
        
 
 
    bsc                       44.57 M
    
    total                    44.57 M

**Comment by inmarelibero** [comment]
> The adapter at projects/kernel-dao exports TVL:
> 
> ```
> bsc                       44.57 M
> 
> total                    44.57 M 
> ```

and? is it not ok?

**Comment by g1nt0ki** [comment]
hi @inmarelibero llamabutler is our bot :)

But can you compute the tvl on chain, i.e count balance on tokens locked in your protocol rather than using this contract?

**Comment by inmarelibero** [comment]
@g1nt0ki that contract calls KernelDAO's to know the tvl, so the flow is fully on-chain

on the other hand, I understand the adapter does not hit KernelDAO's contracts directly and that could be desired by defillama

if so, there's no problem in fixing the adapter

**Comment by g1nt0ki** [comment]
hi @inmarelibero thats what I meant, would prefer tvl by looking up balances of tokens locked in your contract, instead of reading it from a contract

**Comment by llamabutler** [comment]
The adapter at projects/kernel-dao exports TVL: 
        
 
 
    bsc                       46.44 M
    
    total                    46.44 M

**Comment by inmarelibero** [comment]
@g1nt0ki adapter is updated, it is now calling directly KernelDAO's smart contract to calculate the total TVL

**Comment by inmarelibero** [comment]
@g1nt0ki any update?

**Comment by g1nt0ki** [comment]
@inmarelibero I have refactored and merged it, thanks for the PR

**Pull request closed without merging**
