### PR TITLE
Algomint TVL update

### PR DESCRIPTION
**Pull request by clooneyr**
This is an update to the Algomint TVL. We have recently launched our new goBTC and goETH baskets. All liquidity tracked is held in the Algomint basket contracts.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/algomint exports TVL: 
        
 
 
    algorand                  1.34 M
    
    total                    1.34 M

**Comment by g1nt0ki** [comment]
hi @clooneyr, can you please revert the formatting changes, it is a nightmare for me to review, sorry about this

**Comment by llamatester** [comment]
Error while running adapter at projects/algomint: 
        
 
  
    
    
    Error: Invalid balance: NaN
    Truncated error stack:
        at isValidNumber (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:119:19)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:319:16
        at Array.forEach (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:313:28)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:326:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:54:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
The adapter at projects/algomint exports TVL: 
        
 
 
    algorand                  1.35 M
    
    total                    1.35 M

**Comment by llamatester** [comment]
The adapter at projects/algomint exports TVL: 
        
 
 
    algorand                  1.35 M
    
    total                    1.35 M

**Comment by clooneyr** [comment]
Hey @g1nt0ki sorry about that, should be all good now

**Comment by g1nt0ki** [comment]
> Hey @g1nt0ki sorry about that, should be all good now

thanks for fixing it, much easier to review

**Pull request merged**
