### PR TITLE
feat: add bigone

### PR DESCRIPTION
**Pull request by LanfordCai**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
BigONE

##### Twitter Link:
https://x.com/BigONEexchange

##### Website Link:
https://big.one

##### Logo (High resolution, will be shown with rounded borders):
https://b.peatio.com/logos/bigone_logo.png 

##### Current TVL:
113865373.4 USDT

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
bigone

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
330

##### Short Description (to be shown on DefiLlama):
BigONE is a global cryptocurrency exchange that provides a platform for trading various cryptocurrencies. It was founded in 2017 and registered in the Seychelles. The group operates in Russia, Brazil, Vietnam, Seychelles, Singapore, Japan, and Indonesia, providing marketing, investment, and blockchain technology research & development.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
CEX

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bigone exports TVL: 
        
 
 
    bitcoin                   75.26 M
    solana                    17.25 M
    ethereum                  14.51 M
    tron                      1.29 M
    
    total                    108.31 M

**Comment by Define101** [comment]
'0xd4dcd2459bb78d7a645aa7e196857d421b10d93f',
       '0x88e343f4599292c2cffe683c1bb93cd3480bdbab',
This two wallets belong to Peatio not BigOne
What is the relationship between both

**Comment by duckuu** [comment]
Peatio is another name for BigONE. It's the original name of BigONE.  
Here are some supports:

https://www.oklink.com/zh-hans/eth/address/0xd4dcd2459bb78d7a645aa7e196857d421b10d93f
https://bloxy.info/address/0xd4dcd2459bb78d7a645aa7e196857d421b10d93f
https://www.coincarp.com/exchange/bigone/wallets/

**Comment by Define101** [comment]
@duckuu https://defillama.com/cex/bigone#information

**Pull request merged**
