### PR TITLE
Add Levvy.fi

### PR DESCRIPTION
**Pull request by theapesociety**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Levvy.Fi

##### Twitter Link:
https://twitter.com/levvyfinance

##### List of audit links if any:
https://levvyprojects.nyc3.cdn.digitaloceanspaces.com/Levvy%20Finance%20Audit.pdf

##### Website Link:
https://www.levvy.fi/

##### Logo (High resolution, will be shown with rounded borders):
https://www.levvy.fi/images/levvy.png

##### Current TVL:
634,000 ADA

##### Chain:
Cardano

##### Short Description (to be shown on DefiLlama):
Levvy is an innovative Peer-to-Peer NFT lending protocol that allows NFT owners to access instant liquidity from lenders at efficient market rates.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### methodology (what is being counted as tvl, how is tvl being calculated):
Counts locked NFTs used as collateral to take out loans as well as locked ADA in loan offers

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@theapesociety sorry, right now, we have limited support for pricing NFTs (support only a handful on ethereum), can you update your PR to count only the amount of ADA in loan pool as tvl and also if possible provide amount of borrowed ADA that we can show that as well on defillama. 

Sorry, this is a policy we have for nftfi at the moment:  not include nft value in tvl if we cant price/whitelist them.

**Comment by theapesociety** [comment]
Thanks for the resposne @g1nt0ki.  The reason we included this was because we saw that several other platforms, including https://defillama.com/protocol/fluidtokens include active loaned out ada in their TVL.  

Should we instead change our TVL to include ada in loan pool + currently borrowed ada?

**Comment by g1nt0ki** [comment]
> Thanks for the resposne @g1nt0ki. The reason we included this was because we saw that several other platforms, including https://defillama.com/protocol/fluidtokens include active loaned out ada in their TVL.
> 
> Should we instead change our TVL to include ada in loan pool + currently borrowed ada?

ah, that might be an oversight on my part. Will fix fluidtokens, can you tell when other ones have similar issue?

I would like something like:

 tvl: ada in pool that can be borrowed
 borrowed: ada borrowed from pool
 
if there is some easy way to get this info onchain that would be even better

**Comment by theapesociety** [comment]
> > Thanks for the resposne @g1nt0ki. The reason we included this was because we saw that several other platforms, including https://defillama.com/protocol/fluidtokens include active loaned out ada in their TVL.
> > Should we instead change our TVL to include ada in loan pool + currently borrowed ada?
> 
> ah, that might be an oversight on my part. Will fix fluidtokens, can you tell when other ones have similar issue?
> 
> I would like something like:
> 
> tvl: ada in pool that can be borrowed borrowed: ada borrowed from pool
> 
> if there is some easy way to get this info onchain that would be even better

Ok just separated the two. I'll try and refind the others that I saw with that similar issue.

As far as on chain, unfortunately each loan is in a separately created contract, so it's a bit difficult to add them all in one query all on chain at the moment on cardano.  However, we do have a feed of loans on our site as well that can verify the activity.

**Comment by llamatester** [comment]
The adapter at projects/levvy-fi exports TVL: 
        
 
 
    cardano-borrowed          129.50 k
    cardano                   271.26 k
    borrowed                  129.50 k
    
    total                    271.26 k

**Comment by g1nt0ki** [comment]
@theapesociety sounds good, just made a minor fix, will merge the PR, do let know other protocols where borrowed amount is counted under tvl, I will fix those as well.

**Pull request merged**
