### PR TITLE
Added Adapter for ZedaSwap

### PR DESCRIPTION
**Pull request by Eminivince**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/ZedaSwap exports TVL: 
        
 
 
    zeta                      39.04 k
    
    total                    39.04 k

**Comment by g1nt0ki** [comment]
@Eminivince thanks, it is merged here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/314b6c8d4a2e1a0af3a7053dcd5db24cb2e6ec89

**Comment by g1nt0ki** [comment]
ah, can you fill in the project details, else we are unsure what to list

**Comment by Eminivince** [comment]
> ah, can you fill in the project details, else we are unsure what to list

Oh. Apologies!


Name (to be shown on DefiLlama):
Twitter Link: https://x.com/zedaswap?s=21
List of audit links if any:
Website Link: https://zedaswap.xyz/
Logo (High resolution, will be shown with rounded borders): https://eminivince.github.io/zedalogo/WhatsApp_Image_2024-01-05_at_6.38.38_PM-removebg-preview.png
Current TVL: 40k
Treasury Addresses (if the protocol has treasury)
Chain: Zetachain
Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
Short Description (to be shown on DefiLlama): Ultrafast native DEX on Zetachain.
Token address and ticker if any: 
Category (full list at https://defillama.com/categories) *Please choose only one: Dex
Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
forkedFrom (Does your project originate from another project): UniswapV2
methodology (what is being counted as tvl, how is tvl being calculated):
Github org/user (Optional, if your code is open source, we can track activity):

**Comment by g1nt0ki** [comment]
thanks @Eminivince

**Pull request closed without merging**
