### PR TITLE
Adding gaspump launchpad

### PR DESCRIPTION
**Pull request by shuva10v**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

GasPump

##### Twitter Link:

https://x.com/gaspump_tv

##### List of audit links if any:

-

##### Website Link:

https://gaspump.tg/#/onboarding

##### Logo (High resolution, will be shown with rounded borders):

NWsrdslE_400x400

##### Current TVL:

130k$

##### Treasury Addresses (if the protocol has treasury)
-

##### Chain:

TON

##### Short Description (to be shown on DefiLlama):
Telegram native launchpad which allows to launch a coin that is instantly tradable for under $2 in one click (like pump fun, but on TON). 

##### Token address and ticker if any:

-

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Launchpad

##### methodology (what is being counted as tvl, how is tvl being calculated):

Each token launched via gaspump has a bonding curve. The TVL is the sum of all bonding curve balances.
  It is slightly different from the address balance, which is composed from curve balance + fees accumulated.

##### Github org/user (Optional, if your code is open source, we can track activity):

https://github.com/gas111-bot

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/gaspump exports TVL: 
        
 
 
    ton                       134.02 k
    
    total                    134.02 k

**Comment by g1nt0ki** [comment]
@shuva10v thanks for the PR, I made a minor change, think you are tracking both sides of the pool, but we track only the TON side as tvl

**Comment by shuva10v** [comment]
@g1nt0ki actually bounding curve balance is already the TON side, it doesn't count. Here is an example of pthe transaction of listing token on DEX](https://tonviewer.com/transaction/bf62497135be92e53e9ebebca6d309dbbc815c25e1dd458f3959ac826a221775), 950TON goes to the DEX and 50TON is the protocol fee. I suppose in this case we should count at least 95% of sum(bounding_curve_balance) as the project TVL.

**Comment by g1nt0ki** [comment]
hi @shuva10v just pushed  the fix

**Pull request closed without merging**
