### PR TITLE
OMAX Swap

### PR DESCRIPTION
**Pull request by pro100skm**
- delist old Omax Swap
- fix new Omax Swap name on Defillama. now its "Swap Omax", should be "Omax Swap" (just like old dex name. we just updated our DEX)

### CODE REVIEW

**Comment by g1nt0ki** [comment]
we have handled it server-side: https://github.com/DefiLlama/defillama-server/pull/5770

**Comment by pro100skm** [comment]
@g1nt0ki update WOMAX address please

**Comment by Alviraafroz** [comment]
> @g1nt0ki update WOMAX address please

@g1nt0ki please look into this new
WOMAX
0x373e4b4E4D328927bc398A9B50e0082C6f91B7bb

Hence the TVL is not fetched properly

**Comment by OMAXCHAIN** [comment]
@g1nt0ki 
please look into the WOMAX adress .
the new adress for WOMAX is

0x373e4b4E4D328927bc398A9B50e0082C6f91B7bb

please remove the old one . hence TVL not fetching writly.

**Pull request closed without merging**
