### PR TITLE
tectonic added borrowed

### PR DESCRIPTION
**Pull request by wilson-ang**

### CODE REVIEW

**Comment by yff2021** [comment]
added borrowed for tectonic

1. included tusd in tvl

2. added borrowed for all assets available

**Comment by yff2021** [comment]
added borrowed for tectonic

1. included tusd in tvl

2. added borrowed for all assets available

**Comment by llamatester** [comment]
The adapter at projects/tectonic/index.js exports TVL: 
        
 
 
    cronos-borrowed           614.08 M
    cronos                    542.95 M
    borrowed                  614.08 M
    
    total                    542.95 M

**Comment by yff2021** [comment]
> The adapter at projects/tectonic/index.js exports TVL:
> 
> ```
> cronos-borrowed           614.08 M
> cronos                    542.95 M
> borrowed                  614.08 M
> 
> total                    542.95 M 
> ```

Looks good, that is the expected output.

**Pull request merged**
