### PR TITLE
Add SilverSwap on Sonic

### PR DESCRIPTION
**Pull request by PolEpie**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
SilverSwap

##### Twitter Link:
https://x.com/SilverSwapDex

##### Website Link:
https://silverswap.io

##### Logo (High resolution, will be shown with rounded borders):
https://cdn.discordapp.com/attachments/596296266674077696/1319345354898145351/Group.png?ex=67659f9c&is=67644e1c&hm=63bb9827fa8a0e90e6986d5a573b0d210fef7c60bcf1ac52c9810e3c97f0183d&

##### Chain:
Sonic

##### Short Description (to be shown on DefiLlama):
SilverSwap is the first premium DEX (Decentralized Exchange) on Sonic that offers fully novel tokenomics, a burn-centric design, unmatchedcswap speeds, and the most effective and high-yielding liquidity provision options.

##### Token address and ticker if any:
$AG 0x005851f943ee2957B1748957F26319e4f9EdeBC1

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### forkedFrom (Does your project originate from another project):
Algebra Integral

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/Spirit-DAO

### CODE REVIEW

**Comment by llamabutler** [comment]
The adapter at projects/silverswap exports TVL: 
        
 
 
    sonic                     330.38 k
    
    total                    330.38 k

**Comment by g1nt0ki** [comment]
thanks for the PR

**Comment by PolEpie** [comment]
Can you make it being forked from algebra please ?

**Comment by g1nt0ki** [comment]
done: https://github.com/DefiLlama/defillama-server/commit/4c0d0087ecd9db2996a842bc9acc61a0b3f25637

**Pull request merged**
