### PR TITLE
Shiden, DaoMaker

### PR DESCRIPTION
**Pull request by waynebruce0x**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/daomaker/index.js exports TVL: 
        
 
 
    ethereum-staking          115.24 M
    ethereum                  58.37 k
    bsc                       13.57 k
    polygon                   153.96 k
    staking                   115.24 M
    
    total                    225.89 k

**Comment by llamatester** [comment]
Error while running adapter at projects/shiden-dapps-staking/index.js: 
        
 
  
    
    
    Error: createType(StorageEntryTypeLatest):: Invalid character
        at createTypeUnsafe (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@polkadot/types/create/createType.cjs:75:18)
        at TypeRegistry.createTypeUnsafe (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@polkadot/types/create/registry.cjs:417:45)
        at TypeRegistry.createType (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@polkadot/types/create/registry.cjs:409:17)
        at extendHeadMeta (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@polkadot/types/metadata/decorate/storage/createFunction.cjs:166:20)
        at extendPrefixedMap (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@polkadot/types/metadata/decorate/storage/createFunction.cjs:186:23)
        at createFunction (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@polkadot/types/metadata/decorate/storage/createFunction.cjs:224:5)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@polkadot/types/metadata/decorate/storage/index.cjs:59:60
        at Object.get [as generalEraInfo] (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@polkadot/util/lazy.cjs:29:17)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@polkadot/api/base/Decorate.cjs:479:247
        at Object.get [as generalEraInfo] (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@polkadot/util/lazy.cjs:29:17)

**Comment by llamatester** [comment]
The adapter at projects/daomaker/index.js exports TVL: 
        
 
 
    ethereum-staking          115.22 M
    bsc                       13.51 k
    ethereum                  58.37 k
    polygon                   154.89 k
    staking                   115.22 M
    
    total                    226.77 k

**Comment by llamatester** [comment]
Error while running adapter at projects/shiden-dapps-staking/index.js: 
        
 
  
    
    
    Error: createType(StorageEntryTypeLatest):: Invalid character
        at createTypeUnsafe (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@polkadot/types/create/createType.cjs:75:18)
        at TypeRegistry.createTypeUnsafe (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@polkadot/types/create/registry.cjs:417:45)
        at TypeRegistry.createType (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@polkadot/types/create/registry.cjs:409:17)
        at extendHeadMeta (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@polkadot/types/metadata/decorate/storage/createFunction.cjs:166:20)
        at extendPrefixedMap (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@polkadot/types/metadata/decorate/storage/createFunction.cjs:186:23)
        at createFunction (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@polkadot/types/metadata/decorate/storage/createFunction.cjs:224:5)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@polkadot/types/metadata/decorate/storage/index.cjs:59:60
        at Object.get [as generalEraInfo] (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@polkadot/util/lazy.cjs:29:17)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@polkadot/api/base/Decorate.cjs:479:247
        at Object.get [as generalEraInfo] (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@polkadot/util/lazy.cjs:29:17)

**Comment by llamatester** [comment]
The adapter at projects/daomaker/index.js exports TVL: 
        
 
 
    ethereum-staking          115.22 M
    bsc                       13.51 k
    ethereum                  58.37 k
    polygon                   154.89 k
    staking                   115.22 M
    
    total                    226.77 k

**Comment by g1nt0ki** [comment]
okay, if I have to guess it is the polkadot module issue, in this branch, I had updated the version and locked.

My guess is, the version of module that you have locally is okay, but not in server which is still outdated?

https://github.com/DefiLlama/DefiLlama-Adapters/pull/2052#issuecomment-1079348309

**Pull request closed without merging**
