### PR TITLE
add ponzi.market adapter

### PR DESCRIPTION
**Pull request by Qu33zZ**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
ponzi.market

##### Twitter Link:
https://x.com/ponzidev

##### Website Link:
https://ponzi.market

##### Logo (High resolution, will be shown with rounded borders):
image

##### Current TVL:
503 USD

##### Chain:
Arbitrum One

##### Short Description (to be shown on DefiLlama):
Our platform offers a game based on a Ponzi scheme with deposits in the Arbitrum network. Users create games by setting minimum and maximum bets, fees, and ROI (return on investment) percentages. New participants' deposits are distributed among previous players. When the ROI is reached, players can withdraw their funds with interest. If no deposits are made within 10 hours, the game ends, and the last participant receives the jackpot, consisting of all remaining deposits.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Ponzi

##### methodology (what is being counted as tvl, how is tvl being calculated):
Ponzi Market's TVL equals to the sum of all ETH balances of all game contracts

### CODE REVIEW

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
@Qu33zZ thanks for the PR but can you update code to compute tvl on chain?

or you can share the contract/factory details and I will try to refactor the adapter

**Comment by Qu33zZ** [comment]
@g1nt0ki Hi, thanks for your review, I've updated the code to compute tvl on chain, can you pls check it again?

**Comment by g1nt0ki** [comment]
@Qu33zZ thanks for the pr

**Comment by llamatester** [comment]
The adapter at projects/ponzi-market exports TVL: 
        
 
 
    arbitrum                  501
    
    total                    501.3485912

**Pull request merged**
