### PR TITLE
Klayswap json

### PR DESCRIPTION
**Pull request by devZooOzys**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
KlaySwap

##### Twitter Link:
https://twitter.com/KLAYswap

##### List of audit links if any:
https://github.com/KlaySwap/klayswap

##### Website Link:
https://klayswap.com/

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/klayswap exports TVL: 
        
 
 
    klaytn-staking            31.71 M
    klaytn                    137.02 M
    staking                   31.71 M
    
    total                    137.02 M

**Comment by llamatester** [comment]
The adapter at projects/meshswap exports TVL: 
        
 
 
    polygon-staking           1.80 M
    polygon                   29.55 M
    staking                   1.80 M
    
    total                    29.55 M

**Comment by devZooOzys** [comment]
Thank you.

**Comment by g1nt0ki** [comment]
@devZooOzys sorry, closing this one as I turned the adapter to use on-chain data: https://github.com/DefiLlama/DefiLlama-Adapters/commit/d437d45485f33f74412608ec0a9fbcef5ddc90fa

**Pull request closed without merging**
