### PR TITLE
Kriya vaults TVL

### PR DESCRIPTION
**Pull request by Knight-101**
We want to add a new sub-category to KriyaDEX

##### Name (to be shown on DefiLlama): 
Our AMM is already listed on DefiLlama under kriya-dex. We now want to separate it as: Kriya (Parent) and Sub-categories (Kriya Swap ; Kriya Earn) 
Currently the project is listed as ‘KriyaDEX’ on Defillama

##### Website Link: 
Kriya : https://app.kriya.finance/
Kriya Swap : https://app.kriya.finance/spot/liquidity
Kriya Earn : https://app.kriya.finance/strategies

##### Current TVL: 
Kriya Swap : $61.12M
Kriya Earn : $59.90K

##### Short Description (to be shown on DefiLlama): 
Here are descriptions we want added / updated
Kriya : 1–stop DeFi protocol on Sui. Offering Swaps, Limit Orders, 1-click leverage lending strategies, Yield Optimiser Vaults and 20x perpetuals
Kriya Swap : Kriya’s native AMM. Supports both stable and constant product curves. One of deepest liquidity source in Kriya’s cross-protocol router
Kriya Earn : Vaults that provide retail investors tokenized access to sophisticated DeFi strategies such as leverage lending, reward auto-compounding and CLMM LP management

##### Category (full list at https://defillama.com/categories) *Please choose only one: Yields
Kriya Earn : Yields
Kriya Swap : Dexes

##### methodology (what is being counted as tvl, how is tvl being calculated):
Kriya Earn : Calculated by aggregating current token wise asset and liabilities balances of all Kriya Earn vaults
Kriya Swap : Sum of token balances across Kriya’s AMM Liquidity pools
Kriya : Sum of TVL / Volume across different Kriya products

##### Github org/user (Optional, if your code is open source, we can track activity):  https://github.com/efficacy-finance

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/kriya-dex-earn: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:196:11

**Comment by llamatester** [comment]
The adapter at projects/kriya-dex-earn exports TVL: 
        
 
 
    sui                       60.86 k
    
    total                    60.86 k

**Comment by g1nt0ki** [comment]
@Knight-101 thanks for the PR

**Comment by Knight-101** [comment]
Hey @g1nt0ki,

As mentioned in the PR description, we want parent heading to be "Kriya" and sub headings "Kriya Swap" & "Kriya Earn".
So can you make the parent/global heading "Kriya" here instead of "KriyaDex"?

image

**Comment by Define101** [comment]
@Knight-101 should be live within 2 hours
https://github.com/DefiLlama/defillama-server/pull/6508

**Comment by Knight-101** [comment]
@g1nt0ki its reflecting now
Thanks a lot!

**Pull request merged**
