### PR TITLE
Update BenSwap TVL for SmartBCH

### PR DESCRIPTION
**Pull request by BenTokenFinance**
Included staking for better accuracy. Tested locally. Please kindly merge. Thanks a lot!

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Is EBEN the native token for Benswap? If so, can the staked EBEN be seperated out into a seperate 'staking' export? And can the EBEN_WBCH LP be exported as 'pool2'?

**Comment by BenTokenFinance** [comment]
I checked that goose finance has all the staking balance included in their general TVL. I believe it is fair for us to do the same.
https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/goose.js

**Comment by 0xngmi** [comment]
got point, we'll change goose finance

**Comment by 0xngmi** [comment]
we are already counting EBEN-BCH funds through calculateUsdUniTvl so i don't think we should count them separately, that's double counting

**Comment by BenTokenFinance** [comment]
EBEN-BCH  pair is not added again to the TVL. What is added here is the WBCH and EBEN staked in the single token pool, Which are not included in any LP pairs.

**Comment by BenTokenFinance** [comment]
I believe this change is a fair representation of what is actually locked on BenSwap (SmartBCH). Please kindly check the code. Thank you sir

**Comment by BenTokenFinance** [comment]
Please check this page for understanding what is added:  https://benswap.cash/pools

**Comment by BenTokenFinance** [comment]
The MCap is also pulling from CoinGecko?

**Comment by 0xngmi** [comment]
will separate staking into a different function

**Comment by 0xngmi** [comment]
Applied some changes on https://github.com/DefiLlama/DefiLlama-Adapters/commit/6331850cb224c72ec802057de2b7c79ac829a587

- Added coins on masterchef
- Added staking on both smartBCH and bsc (although separated, users can choose whether to include it)
- Simplified some code

**Pull request merged**
