### PR TITLE
add Term Structure TVL

### PR DESCRIPTION
**Pull request by imfeng**
##### Name (to be shown on DefiLlama):
[Term Structure](https://app.ts.finance/)

##### Twitter Link:
[https://x.com/TermStructLabs](https://x.com/TermStructLabs)

##### List of audit links if any:
[https://github.com/term-structure/audits](https://github.com/term-structure/audits)

##### Website Link:
[https://ts.finance/](https://ts.finance/)

##### Logo (High resolution, will be shown with rounded borders):
Term Structure logo-round-deep-blue

##### Current TVL:
851.93 K

##### Treasury Addresses (if the protocol has treasury)
N/A

##### Chain:
Ethereum Mainnet

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
https://www.coingecko.com/en/coins/term-structure

##### Short Description (to be shown on DefiLlama):
Term Structure is a non-custodial, fixed rate and maturity lending/borrowing protocol backed by customized Zk-Rollup with orders matched via auction.

##### Token address and ticker if any:
N/A

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Implementation Details: Briefly describe how the oracle is integrated into your project:
[https://docs.ts.finance/protocol-spec/primary-markets/liquidation-mechanism#fully-on-chain-liquidation
](https://docs.ts.finance/protocol-spec/primary-markets/liquidation-mechanism#fully-on-chain-liquidation
)
##### forkedFrom (Does your project originate from another project):
ZkSync Lite

##### methodology (what is being counted as tvl, how is tvl being calculated):
Counts the tokens locked in the contracts

##### Github org/user (Optional, if your code is open source, we can track activity):
[https://github.com/term-structure](https://github.com/term-structure)

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/term-structure: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'assets')
    Truncated error stack:
    
        at _call (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/token.js:109:31)
        at async covalentGetTokens (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/token.js:22:20)
        at async Promise.all (index 0)
        at async sumTokens2 (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/unwrapLPs.js:844:22)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:143:9
        at async Promise.all (index 0)
        at async Promise.all (index 0)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:186:3

**Comment by llamatester** [comment]
The adapter at projects/term-structure exports TVL: 
        
 
 
    ethereum                  695.52 k
    
    total                    695.52 k

**Comment by llamatester** [comment]
The adapter at projects/term-structure exports TVL: 
        
 
 
    ethereum                  695.52 k
    
    total                    695.52 k

**Comment by llamatester** [comment]
The adapter at projects/term-structure exports TVL: 
        
 
 
    ethereum                  851.93 k
    
    total                    851.93 k

**Comment by llamatester** [comment]
The adapter at projects/term-structure exports TVL: 
        
 
 
    ethereum                  846.38 k
    
    total                    846.39 k

**Comment by g1nt0ki** [comment]
thanks for the PR

**Pull request merged**
