### PR TITLE
Add Amulet Protocol

### PR DESCRIPTION
**Pull request by yym-mtrlabs**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Amulet Protocol

##### Twitter Link:
https://twitter.com/AmuletProtocol

##### List of audit links if any:
https://files.amulet.org/public/AmuletGlobalMTRLabs.pdf

##### Website Link:
https://amulet.org/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://files.amulet.org/public/twitter/Avatar_Circle.png

##### Current TVL:
73.56 k USD

##### Chain:
Solana

##### Short Description (to be shown on DefiLlama):
Amulet Protocol ("Amulet") is a decentralized risk protection protocol ("RPP") built for Rust-based ecosystems, starting with the Solana blockchain. Amulet has designed an innovative and open risk protection model which not only effectively addresses the common challenges of existing decentralized RPPs, but also creates a new paradigm shift for the whole risk protection sector.
Amulet's vision is to offer Simple, Reliable Cover for everyone in Web3. With the addition of Amulet, users in the entire Rust-based ecosystem will gain access to a new way to hedge various risks with cover product offerings.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Insurance

##### methodology (what is being counted as tvl, how is tvl being calculated):
Amulet enables users to earn PoS staking rewards on Solana by staking SOL and mint amtSOL. amtSOL can be stake back to mint aUWT which will be used to underwrite covers. Hence, only the amount of SOL staked are counted as our TVL which the value are calculated based on the price get from Coingecko.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/amulet-protocol.js exports TVL: 
        
 
 
    solana                    57.45 k
    
    total                    57.45 k

**Comment by yym-mtrlabs** [comment]
> @yym-mtrlabs thanks for the PR, can the staked sol amount be fetched by calling solana instead of graph?

@g1nt0ki Thanks for the advice. TVL calculation method updated as suggested. Fetched solana onchain statistics are used to calculate of tvl in current script.

Please kindly help to check the most recent changes and let us know if there is any further comment.

**Comment by yym-mtrlabs** [comment]
> 73.80 k USD

Tvl number as :

solana                    73.56 k

total                    73.56 k

**Comment by yym-mtrlabs** [comment]
> @yym-mtrlabs adapter looks good, can you rename file to `projects/amulet-protocol/index.js` and then I will merge it

@g1nt0ki File path updated as suggested. Please kindly let me know for any further comments. Thank you so much!

**Comment by llamatester** [comment]
The adapter at projects/amulet-protocol exports TVL: 
        
 
 
    solana                    95.80 k
    
    total                    95.80 k

**Pull request merged**
