### PR TITLE
added some tokens to coreAssets

### PR DESCRIPTION
**Pull request by simone1999**

### CODE REVIEW

**Comment by g1nt0ki** [comment]
hi @simone1999 , I try to keep this list as small as possible, can you give me good reason while these tokens needs to be added? Also, adding these would lower icecreamswap tvl as some of the tokens you have added are not priced by our server, also, changing labels in coreAssets might have side effects like some other part of the code might be dependent on telos.USDC and now the address is gone or changed.

**Comment by simone1999** [comment]
Thx for the explanation. In that case I would suggest to only add the second WTLOS. Do you think this would make sense?

**Comment by g1nt0ki** [comment]
> Thx for the explanation. In that case I would suggest to only add the second WTLOS. Do you think this would make sense?

just tested, adding it makes no difference. are you sure icecreamswap is not relying on just the first one?

**Comment by g1nt0ki** [comment]
closing this as there was no response

**Pull request closed without merging**
