### PR TITLE
add Defillama adapter fountain-fi

### PR DESCRIPTION
**Pull request by jasm1n33**
NOTE

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a volume adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a liquidations adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  only if the PR is for listing a new protocol else it can be ignored/replaced with reason/details about the PR
4. For updating listing info It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push package-lock.json file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Fountain.Finance

##### Twitter Link:
https://twitter.com/Fountain_Sui

##### List of audit links if any:
https://github.com/Fountain-Fi/contract/tree/main/audit

##### Website Link:
https://fountainxyz.com/#How

##### Logo (High resolution, will be shown with rounded borders):
1000px copy

##### Current TVL:
13.83 M

##### Chain:
Sui

##### Short Description (to be shown on DefiLlama):
Fountain Finance is the asset-distributing system on Sui Network. It allocates different amounts of assets to token stakers with a flexible and dynamic design.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield

##### methodology (what is being counted as tvl, how is tvl being calculated):
total staked sBUCK token amount, which can be redeemed to BUCK token

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/fountain-fi exports TVL: 
        
 
 
    sui                       13.82 M
    
    total                    13.82 M

**Comment by g1nt0ki** [comment]
hi @jasm1n33 thanks for the PR

I am bit confused what fountain fi does, and how it is different from sparkling protocol. So, all the users who have staked BUCK to get sBUCK have deposited all those sBUCK into your protocol?

**Comment by jasm1n33** [comment]
Hi @g1nt0ki,

Anyone can create a reward pool and add rewards to it on Fountain fi, which is a permissionless process. Users can stake tokens into the pool and consequently earn rewards.

**Comment by g1nt0ki** [comment]
yes, but who is rewarding them SUI for staking sBUCK?

**Comment by jasm1n33** [comment]
Anyone can provide SUI rewards for the reward pool in Fountain. Currently, the creator of the sBUCK pool is providing SUI rewards to the pool.

**Comment by g1nt0ki** [comment]
@jasm1n33 refactored and merged here: 

https://github.com/DefiLlama/DefiLlama-Adapters/pull/10193

showing it as staking instead of tvl

**Pull request closed without merging**
