### PR TITLE
Update onedex to include total value staked

### PR DESCRIPTION
**Pull request by damienen**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/onedex: 
        
 
  
    
    
    TypeError: Cannot convert undefined or null to object
    Truncated error stack:
    
        at Function.entries (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:313:10)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:326:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:54:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 1)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by g1nt0ki** [comment]
hi @damienen 

this is value of LP staked right? but underlying tokens of LPs are already counted towards tvl right? if so, we cant include this

**Comment by damienen** [comment]
Yes, that is correct. In the meanwhile, I have added a new endpoint that takes the total value from the OneDex staking module.

This is an independent module that is not included anywhere else. I can provide more documentation or proof if needed after I update the PR

**Comment by llamatester** [comment]
Error while running adapter at projects/onedex: 
        
 
  
    
    
    TypeError: Cannot convert undefined or null to object
    Truncated error stack:
    
        at Function.entries (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:313:10)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:326:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:54:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 1)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by g1nt0ki** [comment]
> Yes, that is correct. In the meanwhile, I have added a new endpoint that takes the total value from the OneDex staking module.
> 
> This is an independent module that is not included anywhere else. I can provide more documentation or proof if needed after I update the PR

hi @damienen by staking (in the new module/endpoint) you mean onedex token staking or something else? is there some way to get this value on chain? this makes the adapter less rigid and more transparent

**Comment by damienen** [comment]
1. OneDex has a permissionless staking module. Whoever has a token can create a staking module with an APR, etc. So it's the summed up value of the staked tokens in those modules.

2. Yes, there is a way to get them on chain, nut it comes with some caveats. In the API we are just taking the on chain value and storing it in a database in order to have historical data. Moreover, if we would get it directly on chain in the adapter we would have some issues: having to add an extra dependency for the MultiversX package amd the queries sometimes fail to get the on-chain value directly.

**Comment by g1nt0ki** [comment]
hi @damienen we have basic support for querying multiversx, used in some adapters: https://github.com/DefiLlama/DefiLlama-Adapters/blob/0af0d7a6aff57bbbe74dfc91eb2ab0a24ae6f8b6/projects/helper/chain/elrond.js#L8

We also have a work-around that support reliance on multiversx sdk: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/jewelswap-nft/index.js#L1

the reason I am pushing for on chain data is, it is transparent and we have few dependencies

**Comment by g1nt0ki** [comment]
@damienen can you help me here?

**Comment by g1nt0ki** [comment]
closing as stale

**Pull request closed without merging**
