### PR TITLE
Blastex adapter created

### PR DESCRIPTION
**Pull request by BlastexNet**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
we can count staked LP under pool2 and staked tokens under staking: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by g1nt0ki** [comment]
you can put `tvl: () => ({})`  to show 0 tvl

**Comment by g1nt0ki** [comment]
also, the site is down?

**Comment by BlastexNet** [comment]
> you can put `tvl: () => ({})` to show 0 tvl

So, if we go this way, then DefiLlama automatically shows TVL locked on the ThrusterSwap? We should calculate in the adapter only additional TVL, not visible for DefiLlama?

**Comment by llamatester** [comment]
The adapter at projects/blastex exports TVL: 
        
 
 
    blast                     0
    blast-pool2               51.57045342493384
    blast-staking             0.000672996331867242
    pool2                     51.57045342493384
    staking                   0.000672996331867242
    
    total                    0

**Comment by BlastexNet** [comment]
> The adapter at projects/blastex exports TVL:
> 
> ```
> blast                     0
> blast-pool2               51.57045342493384
> blast-staking             0.000672996331867242
> pool2                     51.57045342493384
> staking                   0.000672996331867242
> 
> total                    0 
> ```

Is it typical for the total TVL to show as zero? Our project's total TVL should be the combined value of pool2 and staking, as we maintain all LPs and project tokens within the main contract.

**Pull request merged**
