### PR TITLE
Add PearDAO Project

### PR DESCRIPTION
**Pull request by PearDAOCommunity**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/peardao/index.js exports TVL: 
                
 
 
bsc-pool2                 523.45 k
bsc                       1.9590999366424489
pool2                     523.45 k

total                    1.9590999366424489

**Comment by waynebruce0x** [comment]
Can PEX TVL be exported as 'staking'? Thanks

**Comment by PearDAOCommunity** [comment]
> Can PEX TVL be exported as 'staking'? Thanks

@waynebruce0x I'm afraid we can't do this, we checked the docs and the codebase of staking, it seems to be used for single token, which means staking single token to earn the same token.
Currently the farming pool in our product is to stake PEX-BNB LP tokens to earn PEX, which seems more suitable to use pool2 to calculate the value of staked LP tokens.

**Comment by waynebruce0x** [comment]
I mean the PEX in the treasury contract

**Comment by PearDAOCommunity** [comment]
> I mean the PEX in the treasury contract

@waynebruce0x Updated, please check again.

**Comment by llamatester** [comment]
The adapter at projects/peardao/index.js exports TVL: 
                
 
 
bsc-staking               1.6326450000000001
bsc-pool2                 1.32 M
bsc                       5.2471457206648875
staking                   1.6326450000000001
pool2                     1.32 M

total                    5.2471457206648875

**Comment by PearDAOCommunity** [comment]
i think we should be able to do that. Do we have to make the change ourselves?
Possible to guide us on how we should proceed to do that?

------- Original Message -------

**Comment by PearDAOCommunity** [comment]
Hi, the current 2 pools are lp token pool (PEX-BNB), Our PEX Pool will be online pretty soon, and that should be considered as staking. Do you have any recommendation on how we should go about this? Shall we export them as staking first and make the switch later?

As long as the section does not show a extremely low volume, then we should be fine with that.

Thank You.

------- Original Message -------

**Pull request merged**
