### PR TITLE
Add HydraDX

### PR DESCRIPTION
**Pull request by green-jay**
Name (to be shown on DefiLlama): HydraDX
Twitter Link: https://twitter.com/hydra_dx
List of audit links if any: -
Website Link: https://hydradx.io/
Logo (High resolution, will be shown with rounded borders): https://www.polkassets.com/project/hydradx/
Current TVL: 10.03M
Treasury Addresses (if the protocol has treasury): 7L53bUTBopuwFt3mKUfmkzgGLayYa1Yvn1hAg9v5UMrQzTfh
Chain: 2034 (substrate/ parachain on polkadot)
Coingecko ID: hydradx 
Coinmarketcap ID: hydradx
Short Description (to be shown on DefiLlama): HydraDX is an innovative AMM which unlocks unparalleled efficiencies by combining all assets in a single trading pool.
Token address and ticker if any: HDX
Category: DEX
Oracle used (Chainlink/Band/API3/TWAP or any other that you are using): -
forkedFrom (Does your project originate from another project): -
methodology (what is being counted as tvl, how is tvl being calculated): TVL is calculated as sum of all assets listed in the Omnipool recalculated to their respective DAI prices.
Github org/user (Optional, if your code is open source, we can track activity): https://github.com/galacticcouncil/HydraDX-node

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/hydradx exports TVL: 
        
 
 
    
    total                    10.02 M

**Comment by g1nt0ki** [comment]
@green-jay thanks for the PR, but we prefer computing it on chain, can you guide me to as to how to do it, we do use @polkadot/api in some places

**Comment by green-jay** [comment]
> @green-jay thanks for the PR, but we prefer computing it on chain, can you guide me to as to how to do it, we do use @polkadot/api in some places

Hi, that would be a bit more challenging because of the desing of the Omnipool.

To query our chainstate:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fhydradx-rpc.dwellir.com#/chainstate

omnipool.assets // to get all listed assets ids
assetRegistry.assets // to get asset names
assetRegistry.assetMetadataMap // to get asset symbols
system.accounts(AccountId).free // for native asset balance (HDX, id 0)
tokens.accounts(AccountId,assetId).free //for other asset balances

Omnipool AccountId = 7L53bUTBbfuj14UpdCNPwmgzzHSsrsTWBHX5pys32mVWM3C1

Get $ price for assets from somewhere (all should be on gecko) and then sum.

**Comment by green-jay** [comment]
can you please have a look @g1nt0ki ?

**Comment by g1nt0ki** [comment]
> > @green-jay thanks for the PR, but we prefer computing it on chain, can you guide me to as to how to do it, we do use @polkadot/api in some places
> 
> Hi, that would be a bit more challenging because of the desing of the Omnipool.
> 
> To query our chainstate: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fhydradx-rpc.dwellir.com#/chainstate
> 
> omnipool.assets // to get all listed assets ids assetRegistry.assets // to get asset names assetRegistry.assetMetadataMap // to get asset symbols system.accounts(AccountId).free // for native asset balance (HDX, id 0) tokens.accounts(AccountId,assetId).free //for other asset balances
> 
> Omnipool AccountId = 7L53bUTBbfuj14UpdCNPwmgzzHSsrsTWBHX5pys32mVWM3C1
> 
> Get $ price for assets from somewhere (all should be on gecko) and then sum.

thanks, will try to write adapter using this

**Comment by green-jay** [comment]
Awesome, thanks @g1nt0ki . As the PR was closed, what is the next step?

**Comment by g1nt0ki** [comment]
it is listed here: https://defillama.com/protocol/hydradx :)

**Pull request closed without merging**
