### PR TITLE
add trado-spot adapter

### PR DESCRIPTION
**Pull request by LpcAries**
Hi, this is Trado. Our project is divided into two parts: Trado Perp and Trado Spot. For more details, please visit: https://www.trado.one/. We have already submitted the Perp part, and this is the Spot part. We hope to display the total TVL of both parts on one page, named "Trado All." What do we need to do?

##### Twitter Link: 
https://x.com/trado_one

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/trado-spot exports TVL: 
        
 
 
    flow                      430.66 k
    
    total                    430.66 k

**Comment by btspoony** [comment]
@LpcAries is the Twitter URL incorrect?

**Comment by LpcAries** [comment]
> @LpcAries is the Twitter URL incorrect?

Sorry, here is the correct one: 
https://x.com/trado_one

**Comment by btspoony** [comment]
> > @LpcAries is the Twitter URL incorrect?
> 
> Sorry, here is the correct one: https://x.com/trado_one

You can edit the PR to update ~

**Comment by LpcAries** [comment]
done @btspoony

**Pull request merged**
