### PR TITLE
chore : update TVL for adrastea

### PR DESCRIPTION
**Pull request by chauanhtuan185**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Adrastea

##### Twitter Link:
https://x.com/AdrasteaFinance

##### List of audit links if any:
https://github.com/OffsideLabs/reports/blob/public/audits/Adrastea-Aug-2024-OffsideLabs.pdf

##### Website Link:
https://adrastea.fi/

##### Current TVL:
$260k

##### Chain:
Solana

##### Short Description (to be shown on DefiLlama):
Adrastea is a composable leverage protocol that facilitates isolated boosting, with a primary mission to simplify the process and amplify the yield.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is calculated by summing the total USD value of all assets within the protocol. For example USDC deposits and JLP deposits.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/adrastea: 
        
 
  
    
    
    Error: Failed to post https://mainnet.helius-rpc.com/?api-key=0109717a-77b4-498a-bc3c-a0b31aa1b3bf
    Truncated error stack:
    
        at Object.post (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/http.js:47:11)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:227:29
        at async runInChunks (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:349:22)
        at async sumTokens2 (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:177:18)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:177:9
        at async Promise.all (index 0)
        at async Promise.all (index 0)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:220:3

**Comment by llamatester** [comment]
Error while running adapter at projects/adrastea: 
        
 
  
    
    
    Error: Failed to post https://mainnet.helius-rpc.com/?api-key=0109717a-77b4-498a-bc3c-a0b31aa1b3bf
    Truncated error stack:
    
        at Object.post (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/http.js:47:11)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:227:29
        at async runInChunks (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:349:22)
        at async sumTokens2 (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:177:18)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:177:9
        at async Promise.all (index 0)
        at async Promise.all (index 0)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:220:3

**Comment by g1nt0ki** [comment]
hi, in your LRT solayer and other avs SOL is kept here right? https://solscan.io/account/wYPqKV6XuRBSBU1zYiYB1ZTPhkR8PsDRz5kKgmSyum1

I have added the adapter https://github.com/DefiLlama/DefiLlama-Adapters/commit/dbff19c71822b3d7898c4cb2ddb8ce0bd1d4a3ee


Any idea how we can pull the sonicsSOL price on chain?

**Comment by chauanhtuan185** [comment]
Hello @g1nt0ki , thanks for the update. Regarding getting the price of sonicsSOL, unfortunately there is currently no price of the token on the DEX, so we cannot get it. But once you have it, you can use the API to access your team's adapter

**Comment by solanadevmint** [comment]
> hi, in your LRT solayer and other avs SOL is kept here right? https://solscan.io/account/wYPqKV6XuRBSBU1zYiYB1ZTPhkR8PsDRz5kKgmSyum1
> 
> I have added the adapter [dbff19c](https://github.com/DefiLlama/DefiLlama-Adapters/commit/dbff19c71822b3d7898c4cb2ddb8ce0bd1d4a3ee)
> 
> Any idea how we can pull the sonicsSOL price on chain?

Hi @g1nt0ki we have delegate full liquidity to sonicSOL, there is no price feed for it. 

Better representation of tvl would be for now: lrtssol = sSOL price, multiplied by minted lrtsSOL amount

https://solscan.io/token/4tARAT4ssRYhrENCTxxZrmjL741eE2G23Q1zLPDW2ipf#transactions

**Comment by g1nt0ki** [comment]
yeah, thought about that but would be nice to show users token breakdown

**Comment by solanadevmint** [comment]
> yeah, thought about that but would be nice to show users token breakdown

Can we change current model? https://defillama.com/protocol/adrastea-lrt#information 

As you see almost full liquidity is being delegated now

**Comment by g1nt0ki** [comment]
@solanadevmint I have added price support for it now: https://github.com/DefiLlama/defillama-server/commit/916c9a95fc8d8fb98e75e08c4dbe499848bc9e4a#diff-93e93df835cd550d21425ac6564049b0e2726338986a96cddc9bd66a2261321c

**Comment by solanadevmint** [comment]
> @solanadevmint I have added price support for it now: [DefiLlama/defillama-server@916c9a9#diff-93e93df835cd550d21425ac6564049b0e2726338986a96cddc9bd66a2261321c](https://github.com/DefiLlama/defillama-server/commit/916c9a95fc8d8fb98e75e08c4dbe499848bc9e4a#diff-93e93df835cd550d21425ac6564049b0e2726338986a96cddc9bd66a2261321c)

Hi, it doesn't seem to work, as it shows 0 on Defillama

**Comment by solanadevmint** [comment]
Hi @g1nt0ki, shall we do new PR to update this?

**Comment by g1nt0ki** [comment]
sorry, we had some pricing issue, fixed now

**Pull request closed without merging**
