### PR TITLE
update: Unlockd: Fix TVL calculation

### PR DESCRIPTION
**Pull request by leric7**
**NOTE**
- Removed NFT total collateral from TVL.

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Unlockd

##### Twitter Link:
https://twitter.com/Unlockd_Finance

##### Website Link:
https://unlockd.finance

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
logo

##### Current TVL:
197.86 k

##### Chain:
ethereum

##### Short Description (to be shown on DefiLlama):
Earn yield and borrow against your NFTs with the safest loans on the market

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### methodology (what is being counted as tvl, how is tvl being calculated):
Counts the tokens locked in the contracts to be used as collateral to borrow or to earn yield. Borrowed coins are not counted towards the TVL.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/unlockd exports TVL: 
        
 
 
    ethereum                  199.90 k
    ethereum-borrowed         76.9833915428354
    borrowed                  76.9833915428354
    
    total                    199.90 k

**Comment by g1nt0ki** [comment]
@leric7 any reason for skipping NFT tvl?

**Comment by leric7** [comment]
@g1nt0ki , I believe NFT is not the part of our TVL calculation. We only want to consider tokens locked for lending as TVL.

**Comment by g1nt0ki** [comment]
@leric7 we are fine with counting the nfts as well as they are collateral right? but the choice is yours

**Pull request merged**
