### PR TITLE
update index.js

### PR DESCRIPTION
**Pull request by pos-ninja**
Name (to be shown on DefiLlama): Sohei Finance
Twitter Link: https://twitter.com/Soheidotio
List of audit links if any:
Website Link: https://www.sohei.io/
Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
logo
Current TVL: $4000
Treasury Addresses (if the protocol has treasury)
Chain: arbitrum
Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
Short Description (to be shown on DefiLlama): Revolutionizing Liquidity Markets
Token address and ticker if any: 0x7e70e4efbbcc72f21979eb029efa38ecb40238c6
Category (full list at https://defillama.com/categories) *Please choose only one:
Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
forkedFrom (Does your project originate from another project): Compound
methodology (what is being counted as tvl, how is tvl being calculated):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/sohei exports TVL: 
        
 
 
    arbitrum                  4.29 k
    arbitrum-borrowed         34.33284167776527
    borrowed                  34.33284167776527
    
    total                    4.29 k

**Comment by llamatester** [comment]
The adapter at projects/grizzlyfi exports TVL: 
        
 
 
    bsc-staking               9.67 M
    bsc                       16.20 M
    staking                   9.67 M
    
    total                    16.20 M

**Comment by llamatester** [comment]
The adapter at projects/sohei exports TVL: 
        
 
 
    arbitrum-borrowed         34.30011922756697
    arbitrum                  4.29 k
    borrowed                  34.30011922756697
    
    total                    4.29 k

**Comment by g1nt0ki** [comment]
stop spamming

**Pull request closed without merging**
