### PR TITLE
Add GMX

### PR DESCRIPTION
**Pull request by xyse**
Twitter Link:
https://twitter.com/GMX_IO
List of audit links if any:
https://github.com/xvi10/gambit-contracts/tree/master/audits
Website Link:
https://gmx.financial/
Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
image
Current TVL:
~$100 Million
Chain:
Arbitrum
Coingecko ID:
gmx
Short Description (to be shown on DefiLlama):
Decentralized Perpetual Exchange - Trade BTC, ETH and BNB with up to 30x leverage directly from your wallet.
Token address and ticker if any:
0xfc5A1A6EB076a2C7aD06eD22C90d7E710E35ad0a $GMX
Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Dexes
Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink, TWAP

### CODE REVIEW

**Comment by xyse** [comment]
Still in Progress, need to add staked GMX TVL.

**Comment by 0xngmi** [comment]
this is just a rebrand from gambit, right? then I'd change the gambit adapter

**Comment by xyse** [comment]
@0xngmi it is partially, but gambit is still running on bsc. and i dont't know how to return the tvl for both chains in one script. so would it be ok if we leave both? Please also review the code too, used some workarounds because it wasn't be able to get decimals and price for the arbitrum tokens.

I'd be ready to merge it, added the TVL of staked GMX now. TVL it returns seems to be accurate.

**Comment by xyse** [comment]
I removed the gambit adapter and integrated it into the GMX adapter as it is being rebranded. As per your request.

**Comment by 0xngmi** [comment]
yeah, no problem, if both are in there I'll change the code so that both chains get recorded

**Comment by xyse** [comment]
Yeah, I was able to get that working, both chains are being returned separately. As for the GMX staking, should that also be seperate from the other tokens?

**Comment by 0xngmi** [comment]
will move gmx staking to a staking section, if this is wrong and gmx staking is a core part of the product (eg: synthetix) and should be considered core tvl please let me know

**Pull request merged**
