### PR TITLE
Add Polkadex

### PR DESCRIPTION
**Pull request by jaymansfield**
### This PR requires this to be merged at the same time:

https://github.com/DefiLlama/sushi-analytics/pull/13

--------

##### Name (to be shown on DefiLlama):
Polkadex

##### Twitter Link:
https://twitter.com/polkadex

##### List of audit links if any:
Omniscia - https://omniscia.io/polkadex-pdex-erc-token/
Certik - https://skynet.certik.com/projects/polkadex
Hacken - https://hacken.io/audits/polkadex/ 

##### Website Link:
https://polkadex.trade/

##### Logo (High resolution, will be shown with rounded borders):

logo

https://polkadex.trade/brandAssets/PolkadexLogo.zip

##### Current TVL:
$195,000 in assets deposited to our order book dex.

$3.9M in PDEX staked.

##### Treasury Addresses (if the protocol has treasury)
https://polkadex.subscan.io/account/esoEt6uZ9vs23yW8aqTACLf1tViGpSLZKnhPXt5Nq7vQwHGew

##### Chain:
Polkadot parachain

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

polkadex

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

9017

##### Short Description (to be shown on DefiLlama):

Polkadex Orderbook is an order book based decentralized exchange which combines the advantages of centralized and decentralized exchanges minus the disadvantages of both. 

The result is an interoperable, non-custodial DEX with the speed, performance, and trading experience of a CEX. Or, as we like to call it, the CEXier DEX. 

##### Token address and ticker if any:

PDEX

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Dexes

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:

N/A

##### forkedFrom (Does your project originate from another project):

N/A - Custom built

##### methodology (what is being counted as tvl, how is tvl being calculated):

TVL is counting assets deposited to our Order Book for trading.

Visible on chain here: https://polkadex.subscan.io/account/esoEt6uZ3GuFV8EzKB2EAREe3KE9WuRVfmhK1RRtwffY78ArH

We also have 35% of our PDEX supply staked ($3.9M)

https://pdexanalytics.com/ecosystem

##### Github org/user (Optional, if your code is open source, we can track activity):

https://github.com/Polkadex-Substrate

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/polkadex: 
        
 
  
    
    
    Error: Data for protocol polkadex on chain polkadex is undefined on heroku
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/heroku-api.js:12:19
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:143:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:186:3

**Comment by jaymansfield** [comment]
> Error while running adapter at projects/polkadex:
> 
> ```
> Error: Data for protocol polkadex on chain polkadex is undefined on heroku
> Truncated error stack:
> 
>     at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/heroku-api.js:12:19
>     at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
>     at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:143:9
>     at async Promise.all (index 0)
>     at async Promise.all (index 1)
>     at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:186:3
> ```

Requires this to be merged at the same time:

https://github.com/DefiLlama/sushi-analytics/pull/13

**Comment by llamatester** [comment]
Error while running adapter at projects/polkadex: 
        
 
  
    
    
    Error: Data for protocol polkadex on chain polkadex is undefined on heroku
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/heroku-api.js:18:13
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:143:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:186:3

**Comment by jaymansfield** [comment]
> Error while running adapter at projects/polkadex:
> 
> ```
> Error: Data for protocol polkadex on chain polkadex is undefined on heroku
> Truncated error stack:
> 
>     at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/heroku-api.js:18:13
>     at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
>     at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:143:9
>     at async Promise.all (index 0)
>     at async Promise.all (index 1)
>     at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:186:3
> ```


Requires this to be merged at the same time:

https://github.com/DefiLlama/sushi-analytics/pull/13

**Comment by g1nt0ki** [comment]
looks good, thanks for the PR

**Pull request merged**
