### PR TITLE
Use new hubble protocol API with BigNumber

### PR DESCRIPTION
**Pull request by peroxy**
Updating existing Hubble Protocol adapter:
- use new API endpoint
- add BigNumber support

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/hubble/index.js exports TVL: 
        
 
 
    staking                   1.05 M
    solana                    27.69 M
    
    total                    27.69 M

**Comment by g1nt0ki** [comment]
Closing this in favor of https://github.com/DefiLlama/DefiLlama-Adapters/pull/2082 where I have made minor change to the exports.

At some point, can you put a PR where the data is fetched from the chain using our sdk instead of your api because that way, we can compute the tvl at different blocks

**Comment by g1nt0ki** [comment]
Also, please let me know if something is wrong in my PR

**Comment by peroxy** [comment]
LGTM, thanks

**Pull request closed without merging**
