### PR TITLE
Add ovnstable.io

### PR DESCRIPTION
**Pull request by Vorh**
##### Twitter Link:
https://twitter.com/ovnstable

##### List of audit links if any:
In progress

##### Website Link:
https://ovnstable.io/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
- https://drive.google.com/file/d/1Ho70qzEH2Kb7D_44GT_As4UwtLGCixcT/view?usp=sharing - svg
- https://drive.google.com/file/d/1-K3ZcNcg87yqcYW69fLJR-aOL8YgcHdU/view?usp=sharing - png

##### Current TVL:
2 177.15

##### Chain:
Polygon

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
No

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
No

##### Short Description (to be shown on DefiLlama):
Overnight (‘OVN’) is an interest-bearing stablecoin. OVN is pegged to/instantly redeemable in USDC. It is 100+% backed by low-risk, highly liquid, yield-generating DeFi assets. OVN aidrops interest to your wallet daily, no staking required. OVN is your ‘go-to’ stablecoin, the stablecoin you go to when you are not invested nor yield-farming. One buys and holds OVN in order to receive interest on its temporarily available [stablecoin] cash without exposing to risk nor sacrificing liquidity.

##### Token address and ticker if any:
0xcE5bcF8816863A207BF1c0723B91aa8D5B9c6614 OVN

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Yiedl

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
No

##### forkedFrom (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated)
Get the number of OVN tokens. According to the protocol 1 OVN = 1 USDC

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Is it possible to count the USD collateral backing OVN instead of counting the supply? At the moment the adapter is counting market cap opposed to TVL. I understand this is a collateralised stablecoin but we'd still ideally like to count the locked tokens instead.

**Comment by 0xngmi** [comment]
is the address holding all the collateral https://polygonscan.com/address/0x5413e22e6cb029c0c4b289600c97960d0aef940c ?

**Comment by 0xngmi** [comment]
btw one reason to count collateral instead of total supply:
- if your protocol gets hacked our tvl will be wrong

**Comment by Vorh** [comment]
Hello @0xngmi @waynebruce0x! 
Yes agree with you. 
At the moment, most of the assets are located in:
[am3CRV](https://polygonscan.com/address/0xE7a24EF0C5e95Ffb0f6684b813A78F2a3AD7D171)
[am3CRV Gauge ](https://polygonscan.com/address/0x19793B454D3AfC7b454F206Ffe95aDE26cA6912c)
Current total portfolio:
image

I tried to put these tokens to adapter, but got error: 

```
0xE7a24EF0C5e95Ffb0f6684b813A78F2a3AD7D171:unknown
0x19793B454D3AfC7b454F206Ffe95aDE26cA6912c:unknown
```

The rest of the assets are counted correctly: (USDC, amUSDC) 
what should we do?

**Comment by waynebruce0x** [comment]
This is because the curve tokens need unwrapping into their underlying (so we can query the value through coingecko). There are a few projects in the repo that have done this. I understand it might be a bit confusing though, so if you'd prefer, we can put this on our to-do list.

**Comment by waynebruce0x** [comment]
Closing this PR since I've written an updated adapter @ #1051 reporting $2.55k. Let me know if theres anything wrong with it and I can make changes.

**Pull request closed without merging**
