### PR TITLE
Show optional Staking TVL for Sovryn

### PR DESCRIPTION
**Pull request by SkySonR**
This reverts commit c9238b7f2447507d5a8d4fb7bd72ae15013688ba.

**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Sovryn

##### Twitter Link:
https://twitter.com/SovrynBTC

##### List of audit links if any:
 All audit links can be found on the Sovryn wiki here: https://wiki.sovryn.com/en/technical-documents/audits

##### Website Link:
https://app.sovryn.com/

##### Current TVL:
54,078,472.36

##### Chain:
RSK

##### Short Description (to be shown on DefiLlama):
 Sovryn is a non-custodial and permission-less smart contract based system for bitcoin lending, borrowing and margin trading.

##### Token address and ticker if any:
0xEfC78FC7D48B64958315949279bA181C2114abbD

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is calculated as the sum of all tokens (in USD) of all contracts in the following Sovryn protocol contracts:

- AMM liquidity pools
- Lending protocol contracts
- Sovryn Protocol contract that holds margin trading collateral
- Subprotocols - this currently only includes the Mynt Bonding Curve contract
- Zero Lending Protocol - stability pool funds and RBTC collateral
- Mynt Protocol - bitcoin-backed stablecoins that collateralize the DLLR token

TVL is pulled from our API which queries our subgraph and the RSK chain directly. The code for our API is open source and can be found here: https://github.com/DistributedCollective/Sovryn-graph-wrapper/blob/development/src/services/tvl.service.ts

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/sovryn-dex exports TVL: 
        
 
 
    rsk                       19.82 M
    rsk-staking               19.93 M
    staking                   19.93 M
    
    total                    19.82 M

**Comment by g1nt0ki** [comment]
hi @SkySonR thanks for the PR, is there some way where we can compute the dex & staking tvl on chain? I looked the api code that you shared, but it relies on graph data.

**Comment by SkySonR** [comment]
Hi @g1nt0ki ! Many thanks for fast reply. Staking TVL received directly from onchain data:
https://github.com/DistributedCollective/Sovryn-graph-wrapper/blob/development/src/services/tvlSections/staking.ts#L16
https://github.com/DistributedCollective/Sovryn-graph-wrapper/blob/development/src/services/tvl.service.ts#L68

**Comment by g1nt0ki** [comment]
can you share staking contract address and sovryn token address? we have a staking helper function, that takes care of pricing the token.

With regards to calculating tvl with on chain data, it is easier to maintain and for users to verify going through the code.  I tried turning this adapter to be on chain myself, but couldnt find documentation, like if you give me factory/pool abis, I can do the change myself

also: https://github.com/DefiLlama/DefiLlama-Adapters/discussions/432

example for adding staking data: https://github.com/0xfirechain/DefiLlama-Adapters/blob/pr/0xfirechain/8645/projects/Kwikswap/index.js#L24

**Pull request closed without merging**
