### PR TITLE
astarter add dex tvl

### PR DESCRIPTION
**Pull request by magicMax007**
##### Name (to be shown on DefiLlama):
Astarter

##### Twitter Link:
https://twitter.com/AstarterDefiHub

##### List of audit links if any:
Will provide later

##### Website Link:
https://astarter.io/

##### Logo (High resolution, will be shown with rounded borders):
astarter logo

##### Current TVL:
$USD1,079,000

##### Treasury Addresses (if the protocol has treasury)
None

##### Chain:
Cardano

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
Will provide later

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
Will provide later

##### Short Description (to be shown on DefiLlama):
Astarter is a key DeFi infrastructure hub on Cardano that features four core applications: Launchpad(Launchpool), DEX, Money Market & Tech Service Platform, with the backing of EMURGO, a founding entity of the Cardano protocol. Astarter aims to elevate its contribution and bring broader possibilities to the Cardano ecosystem by providing fair, safe, and accessible open finance services to meet existing and future demand in accelerating DeFi apps to empower the next generation of projects built on Cardano.

##### Token address and ticker if any:
Token address will be provided later
Ticker: AA

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Not yet

##### forkedFrom (Does your project originate from another project):
None

##### methodology (what is being counted as tvl, how is tvl being calculated):
Use the amount of stake in the Astarter pool(https://cexplorer.io/pool/pool1drkls8s0zzjydyv3qpjsdj58w3sw02w9wg0pckrsnuazyef2hca), and the amount of liquidity of the dex will be added after the dex goes online

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/astarter exports TVL: 
        
 
 
    cardano                   2.47 M
    
    total                    2.47 M

**Comment by llamatester** [comment]
The adapter at projects/astarter exports TVL: 
        
 
 
    cardano                   6.39 M
    
    total                    6.39 M

**Comment by llamatester** [comment]
The adapter at projects/astarter exports TVL: 
        
 
 
    cardano                   1.03 M
    
    total                    1.03 M

**Comment by g1nt0ki** [comment]
@magicMax007 thanks for the PR, I think it is better if we have sublistings for each product. I have blackedlisted Byron & shelly as they have very low liquidity.

**Pull request merged**
