### PR TITLE
Implement fetch adapter for Devil Finance

### PR DESCRIPTION
**Pull request by deal-with-the-devil**
##### Twitter Link:
https://twitter.com/DevilFinance_io

##### List of audit links if any:
https://github.com/solidproof/smart-contract-audits/blob/main/SmartContract_Audit_Solidproof_Devil.pdf

##### Website Link:
https://www.devilfinance.io/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
DevilFinanceLogo

##### Current TVL:
$ 1,587,637.91

##### Chain:
Fantom Network

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
devil-finance

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
17125

##### Short Description (to be shown on DefiLlama):
Devil Finance is a Decentralized Yield Optimizer platform that allows its users to earn compound interest on their crypto holdings. Devil Finance runs on the Fantom blockchain and offers one of the leading market yield strategies and operations.

##### Token address and ticker if any:
0x174c7106AEeCdC11389f7dD21342F05f46CCB40F 
DEVIL

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Yield

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
None

##### Forked From (Does your project originate from another project):
No

##### Methodology (what is being counted as tvl, how is tvl being calculated):
The fetched value is a JSON object with three key-value pairs:
- `native`, the dollar value of staked native tokens (DEVIL)
- `nativeLP` , the dollar value of liquidity pools where one of thee pooled tokens is the native token (DEVIL), eg. DEVIL-USDC
- `nonNative` , the dollar value of all non-native pools on our platforms

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Can TVL from staked DEVIL be separated into a separate 'staking' export, and DEVIL-XXX LPs be separated as 'pool2'?

**Comment by deal-with-the-devil** [comment]
Hi @waynebruce0x , no problem, we will use the same API endpoint for all three TVLs (single native, LP native, all the others) and will return an object.

**Comment by waynebruce0x** [comment]
perfect, thanks

**Comment by waynebruce0x** [comment]
let me know when the endpoints been updated and I'll merge

**Comment by deal-with-the-devil** [comment]
@waynebruce0x our API now includes all three 'types' of TVLs:

`{"native":66435.4486616081,"nativeLP":55617.87750968675,"nonNative":1464985.247041062}`

PR description has been updated accordingly.

**Pull request merged**
