### PR TITLE
Add Thala LSD

### PR DESCRIPTION
**Pull request by 0xbe1**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

Thala LSD

##### Twitter Link:

https://twitter.com/ThalaLabs

##### List of audit links if any:

https://docs.thala.fi/thala-protocol-design/operations/audits

##### Website Link:

https://app.thala.fi/lsd

##### Logo (High resolution, will be shown with rounded borders):

https://icons.llamao.fi/icons/protocols/thala

##### Current TVL:

$608

##### Treasury Addresses (if the protocol has treasury)

0x9c6d58fa009e08dfb2f5928ded14b3a790a94131da89891466b41ba1e61d83e1

##### Chain:

Aptos

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

https://www.coingecko.com/en/coins/thala-apt

##### Short Description (to be shown on DefiLlama):

Thala's APT liquid staking primitive, designed to enable APT holders to achieve higher yields while leveraging DeFi and fueling the next wave of the DeFi boom on Aptos.

##### Token address and ticker if any:

thAPT: 0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::ThalaAPT
sthAPT: 0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::StakedThalaAPT

(thAPT is the liquid staking token which is loosely pegged to APT, while sthAPT is the yield bearing token that accrues Aptos staking rewards)

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Liquid Staking

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

none

##### forkedFrom (Does your project originate from another project):

none

##### methodology (what is being counted as tvl, how is tvl being calculated):

1 thAPT = 1 APT

##### Github org/user (Optional, if your code is open source, we can track activity):

https://github.com/ThalaLabs

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/thala-lsd: 
        
 
  
    
    
    AxiosError: Request failed with status code 400
    Axios:  failed to parse path `address`: failed to parse "string(Address)": Invalid account address: Hex characters are invalid: Invalid character '<' at position 55

**Comment by llamatester** [comment]
The adapter at projects/thala-lsd exports TVL: 
        
 
 
    aptos                     608.31
    
    total                    608.31

**Comment by 0xbe1** [comment]
We haven't announced the new protocol officially, that's why the TVL is low as of writing. We will announce in 1-2 days

**Comment by g1nt0ki** [comment]
@0xbe1 thanks for the PR

**Comment by 0xbe1** [comment]
@g1nt0ki in the defillama website, can you help put it under the https://defillama.com/protocol/thala umbrella? similar as thalaswap and thala cdp. ty!!!

**Pull request merged**
