### PR TITLE
add inufair dex on zkfair

### PR DESCRIPTION
**Pull request by Inufair**
Name (to be shown on DefiLlama):
INU DEX || INUFAIR

Twitter Link:
https://twitter.com/Inu_ZKFair

List of audit links if any:
Website Link:
http://inufair.xyz/

Logo (High resolution, will be shown with rounded borders):
https://pbs.twimg.com/profile_images/1745726767761891328/Uey-b6yh_400x400.jpg

Chain:
ZKFAIR (ChainId: 42766)

Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed):
Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed):
Short Description (to be shown on DefiLlama):
InuFair Finance galaxy—where DeFi and DEX collide in the most epic ZK Fair adventure! (0.25% Trading Fees) 

Token address and ticker if any:
Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
forkedFrom (Does your project originate from another project):
Uniswap v2

methodology (what is being counted as tvl, how is tvl being calculated):
Counts the tokens locked on AMM pools

Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by g1nt0ki** [comment]
hi @Inufair thanks for the PR, right now there are no pairs/tvl, can you comment here once you have some tvl?

**Comment by llamatester** [comment]
The adapter at projects/Inufair exports TVL: 
        
 
 
    zkfair                    0
    
    total                    0

**Comment by Inufair** [comment]
Pair has been created and small amount of liquidity has been added as well

**Comment by llamatester** [comment]
Error while running adapter at projects/Inufair: 
        
 
  
    
    
    Error: Multicall failed! 
     [chain: zkfair] [fail count: 1] [abi: address:token0]  
        target: 0x9EA46A6c1de014A885930327bEA71Dc6b65F7615 
    Truncated error stack:

**Comment by Inufair** [comment]
Multicall: 0xaA21Af7A29e78734eB4D3a64A1B241d9757bb217

The dex is the forK of pancakeswap v2. Also the Main network coin of zkFair is USDC

**Comment by g1nt0ki** [comment]
I am still getting 0 tvl :(

**Comment by Inufair** [comment]
It might be because the LP amount is very small probably worth like 0.1$. Can't it get listed without tvl?

**Comment by g1nt0ki** [comment]
> It might be because the LP amount is very small probably worth like 0.1$. Can't it get listed without tvl?

no, we cant list with 0 tvl

**Comment by Inufair** [comment]
hello @g1nt0ki  please check it now. Its showing the tvl now

**Pull request merged**
