### PR TITLE
Add key finance

### PR DESCRIPTION
**Pull request by KeyFinanceTeam**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Treasury Addresses (if the protocol has treasury)
0x67cd1C286ba64DC7a4f528fc006DFa963C6fa6C9
0x1ca1b4b77a281b9624541c263e67490F3b9D44c6
0xf35BCcBF9178e60771B05e829A55E472d684c33a

##### Token address and ticker if any:
GMXkey: 0xc5369c88440AB1FC842bCc60d3d087Bd459f20e4
esGmxkey: 0x3a924611895F8484194C9a791fceFb6fC07ddb85
MPkey: 0x40a03B30D0c4D9e5E71164e041EC28CEe6dD9b36

##### Github org/user (Optional, if your code is open source, we can track activity): KeyFinanceTeam, https://github.com/KeyFinanceTeam/key-finance-contracts

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/key exports TVL: 
        
 
 
    arbitrum                  421.98 k
    
    total                    421.98 k

**Comment by g1nt0ki** [comment]
hi, sorry for delayed review, I went through your code but wondering if there is some better way to compute tvl, one big issue is, you are setting price based on recent orders right? but the way our cache is set up, now we will be storing all the logs from the block specified. Even otherwise having a fixed block number means, as time passes, we will be fetching too old logs for no reason, maybe set the block dynamically to last 2 days from the run? also, if there is not enough trade in last two days, set the price of given token as 0? what do you think?

**Comment by g1nt0ki** [comment]
sounds good, can you replace the pricing logic using logs with this?

**Comment by KeyFinanceTeam** [comment]
Are you talking about a complete replacement? No, we still prefer pricing and TVL calculation based on our trading history. Since fixed values are an alternative, we only want to use them when we don't have trading history for the last two days.

**Comment by llamatester** [comment]
The adapter at projects/key exports TVL: 
        
 
 
    arbitrum                  397.33 k
    
    total                    397.33 k

**Comment by llamatester** [comment]
The adapter at projects/key exports TVL: 
        
 
 
    arbitrum                  392.43 k
    
    total                    392.43 k

**Pull request merged**
