### PR TITLE
add market.xyz tvl on fantom + polygon

### PR DESCRIPTION
**Pull request by 0xDaksh**
##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): 
[market-logos.zip](https://github.com/DefiLlama/DefiLlama-Adapters/files/7776017/market-logos.zip)

### CODE REVIEW

**Comment by 0xngmi** [comment]
aren't these comp forks? imo would be better to use the onchain comp helpers here

**Comment by waynebruce0x** [comment]
I refactored into a (mostly) on chain adapter here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/1197 reporting ~72M TVL. I took the MAI x Beefy locked TVL from your stats page though because it was easier than unwrapping the beefy curve LP tokens. Does it look right to you?

**Comment by 0xDaksh** [comment]
@waynebruce0x but why do you need to do it separately? You can just call the oracle on the compound pool and multiply with total supply of that token.

**Comment by waynebruce0x** [comment]
> @waynebruce0x but why do you need to do it separately? You can just call the oracle on the compound pool and multiply with total supply of that token.

I'm not sure how to do that - would the contract be the comptroller at 0x296233b4f2FEf1Ce7977340cEb3cec4CbE3ada42? What function should I call, is the ABI the same as Compounds comptrollers? Do you mean it'll return USD per collateral token?

**Comment by waynebruce0x** [comment]
The other vaults were okay because the tokens are listed on coingecko, which we use to get our token prices. The problem I was trying to get around was that mooCrvxxx tokens arent on coingecko. So we'd usually unwrap LP tokens into their unuderlying (eg 3crv => dai, usdt, usdc) to get the $ value of the LP tokens. This takes quite a few steps, especially with the moo wrapper on top, so I went the stats page route

**Comment by 0xDaksh** [comment]
Before I address the technical concerns, I was wondering why has market been listed on DeFiLlama with incorrect information and non working adapter?

@waynebruce0x

**Comment by waynebruce0x** [comment]
Because we thought we'd write you an on-chain adapter, and get you listed. This happens often and usually teams are happy that we've helped. If you've got a preferred method then please let us know how to do it, or submit a PR for the changes.

**Comment by 0xDaksh** [comment]
No worries, here you go: https://github.com/DefiLlama/DefiLlama-Adapters/pull/1222

**Comment by 0xDaksh** [comment]
@waynebruce0x is this published on the website? Because I see a desprecency in the TVL showed on DeFillama and our internal dashboard.

**Comment by 0xngmi** [comment]
i just checked your pages at https://fantom.market.xyz/ and https://polygon.market.xyz/ and I'm seeing the same values that we report, you need to toggle "borrows" to have the values match since otherwise we only display collateral

**Comment by 0xDaksh** [comment]
yes @0xngmi, the collateral is the TVL we have. Which is higher than what is reported on DeFiLlama.

image

image

image

**Comment by 0xDaksh** [comment]
Hey @0xngmi and @waynebruce0x, any update on this? the difference now is very significant (over 16M) and we would prefer for it to be accounted as others are referring to this data!

**Pull request closed without merging**
