### PR TITLE
[izumi] add volume adapter for iziswap

### PR DESCRIPTION
**Pull request by LpcAries**
Hi, this is izumi team. Since we achieved a dex called iziswap, we'd like to add a volume adapter for it.

### CODE REVIEW

**Comment by llamatester** [comment]
The iziswap adapter exports: 
        
 
 _______________________________________
    Volume for 28/9/2022
    _______________________________________
    
    BSC 👇
    Backfill start time: 5/5/2022
    24h volume: 2141554.190063787
    Total volume: 59268180.49813708
    AURORA 👇
    Backfill start time: 5/8/2022
    24h volume: 9654.612274022096
    Total volume: 213385.40571431472

**Comment by dtmkeng** [comment]
ty @LpcAries I wonder if it's the same as this one? https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/volumes/adapters/izumi-finance/index.ts

**Comment by LpcAries** [comment]
Thanks for reply. @dtmkeng 
Sorry, we didn’t notice the adapter already existed, since we didn’t find our dex on your website. As you said, the adapters have similar functions, but the one of pr supports the chain Aurora. Can you update the existed adapter for supporting Aurora or just use the version of ours?

**Comment by dtmkeng** [comment]
okay, 1 sec

**Comment by dtmkeng** [comment]
could you check this result, Is it correct? @LpcAries 
```
BSC 👇
Backfill start time: 21/6/2022
24h volume: 2239418.0591924787
Total volume: 190091261.4669989
AURORA 👇
Backfill start time: 5/8/2022
24h volume: 405.3383580291993
Total volume: 15080.82334407717

```

**Comment by LpcAries** [comment]
The volDay result is correct, but the tvl seems not correct for me. Our adapter got results like  this.
屏幕快照 2022-09-30 12 24 42
@dtmkeng

**Comment by dtmkeng** [comment]
> The volDay result is correct, but the tvl seems not correct for me. Our adapter got results like this. 屏幕快照 2022-09-30 12 24 42 @dtmkeng

you mean tvl == trading volume ?
seem like my query add `type=4` for time series data is it correct ?
this is up to date code, could you review or open pr for update this
https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/volumes/adapters/izumi-finance/index.ts

**Comment by LpcAries** [comment]
Sorry, my mistake. The up to date code is fine. Thanks a lot.
BTW, about when can we find our index on your website
@dtmkeng

**Comment by dtmkeng** [comment]
> Sorry, my mistake. The up to date code is fine. Thanks a lot. BTW, about when can we find our index on your website @dtmkeng

around 1 h,

**Comment by LpcAries** [comment]
okay, thanks

**Pull request merged**
