### PR TITLE
Add ZTLN token (https://zoth.io)

### PR DESCRIPTION
**Pull request by shinchann221**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Zoth (ZTLN)

##### Twitter Link:
https://x.com/zothdotio

##### List of audit links if any:
NA

##### Website Link:
https://zoth.io

##### Logo (High resolution, will be shown with rounded borders):
https://resources.zoth.io/images/Zoth%20logo.png

##### Current TVL:
$125000

##### Treasury Addresses (if the protocol has treasury)
NA

##### Chain: 
Ethereum

##### Short Description (to be shown on DefiLlama):
Zoth is an RWA ecosystem bringing institutional-grade yield avenues onchain.

##### Token address and ticker if any:
Address - 0x917991d52Aa2fC1b5612A6aa5e4e81d580F97532
Ticker - ZTLN

##### Category (full list at https://defillama.com/categories) *Please choose only one:
RWA

##### forkedFrom (Does your project originate from another project): 
No

##### methodology (what is being counted as tvl, how is tvl being calculated):
Sum of the total supply of Zoth Tokenized Liquid Notes

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/0xZothio/

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@shinchann221 this PR was merged by mistake

For RWA lending protocols, we track the amount on chain as tvl and off chain as borrowed, I am guessing everything the current adapter should be marked as borrowed?  we will delist zoth (https://defillama.com/protocol/zoth)  till we sort this out

**Comment by shinchann221** [comment]
@g1nt0ki 

ZTLN is the **Zoth Tokenized Liquid Notes** product. The product is exclusively available on Zoth's official website - [www.zoth.io](http://www.zoth.io/). 

It's a security token that is backed by portfolio of US Treasury and corporate bonds, hence RWA lending would not be the right category for us. The TVL is computed by the Deposited amount into the product and amount of ZTLN issued to the customer corresponding. 

Our competitors for this product are ONDO, Hash Note etc. We have cross referenced the TVL code from our competitors and hence, we are computing TVL by calculating the amount of tokens transferred to users who have legally subscribed (deposited funds) into the pool share.

Also, the draft PR that you have referenced is for our upcoming product ZeUSD, which is a digital dollar backed by Zoth RWAs with ZTLN being the initial reserve. This product is still under development and is expected to launched in a week or so.

ZeUSD competes with the likes of Anzen's USDZ and Usual Money's USD0 and we will be cross referencing the TVL code accordingly. 

Also, noticed that you have mentioned a pull request from Verified Network. Please note Verified Network is our tech and underlying legal infrastructure provider for the **Zoth Tokenized Liquid Notes product (ZTLN)**. The product can only be exclusively sold on Zoth on the zoth website ([www.zoth.io](http://www.zoth.io/))

**Comment by shinchann221** [comment]
@g1nt0ki I want to remove this token. This product has been discontinued. Please let me know the process.

**Comment by g1nt0ki** [comment]
@shinchann221 is there still tvl? sorry, we dont remove products, but we can add a hallmark that it is discontinued? https://github.com/DefiLlama/DefiLlama-Adapters/discussions/13020

**Comment by shinchann221** [comment]
If that is the case, then can we get the name changed from Zoth (ZTLN) to Zoth as header and ZTLN inside it as a tab. Since we'll be adding a different product soon in place of ZTLN.

**Comment by g1nt0ki** [comment]
yup, that works

**Comment by shinchann221** [comment]
@g1nt0ki Can we do this then? Do I need to create a request somewhere? Or is this it? It'll be updated?

**Pull request merged**
