### PR TITLE
add fetch-adapter for SaucerSwap (hedera-dex) TVL

### PR DESCRIPTION
**Pull request by hhe44**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

##### Twitter Link:
https://twitter.com/SaucerSwapLabs

##### List of audit links if any:
https://docs.saucerswap.finance/resources/audits

##### Website Link:
https://www.saucerswap.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://www.saucerswap.finance/images/tokens/sauce.svg

##### Current TVL:
$15,182,104

##### Chain:
Hedera

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
Not Applicable

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
Not Applicable

##### Short Description (to be shown on DefiLlama):
SaucerSwap is an automated market maker protocol that leverages the Hedera Smart Contract Service to include Solidity smart contract integration with the Hedera Token Service.

##### Token address and ticker if any:
Address: 0.0.731861 (https://hashscan.io/#/mainnet/token/0.0.731861)
Ticker: SAUCE

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Not Applicable

##### forkedFrom (Does your project originate from another project):
Forked from Uniswap V2

##### methodology (what is being counted as tvl, how is tvl being calculated):
We aggregate the liquidity across SaucerSwap pools and convert to USD. This information is retrieved from https://analytics.saucerswap.finance

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hey, thanks a lot for submitting the adapter. We are working on converting all previously merged api adapters to on-chain to improve transparency so we'd prefer to not merge another api adapter. It would be incredibly helpful if the calculation could be submitted to pull the tvl using on-chain calls

**Comment by hhe44** [comment]
Hello - I appreciate the response. Unfortunately Hedera doesn't provide a way for us to calculate the TVL using on-chain calls, at least I'm not aware of any means to do so using their Javascript SDK. 

All pricing data comes from our automated market maker, and not from the chain itself. By the very nature of our DEX, we have to calculate TVL using our own data. This is the case with another dex on the hedera chain called bubbleswap, which is currently listed on DefiLlama. We'd be open to suggestions, but feel that this is the best option available to us.

**Comment by llamatester** [comment]
Error while running adapter at projects/saucerswap: 
        
 
  
    
    
    Error: 
        Found export keys that were not part of specification: getTvl
    
        List of valid keys: 
    				
    				tvl
    				staking
    				methodology
    				pool2
    				misrepresentedTokens
    				fetch
    				timetravel
    				borrowed
    				start
    				masterchef
    				doublecounted
    				treasury
    				hallmarks
    				incentivized
    				offers
    				deadFrom
    				broken
    				ownTokens

**Comment by llamatester** [comment]
The adapter at projects/saucerswap exports TVL: 
        
 
 
    
    total                    14.68 M

**Pull request merged**
