### PR TITLE
feat: add MYX-Finance adapters

### PR DESCRIPTION
**Pull request by jiangmaniu**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):  
- MYX.Finance

##### Twitter Link:
  - https://twitter.com/MYX_Finance

##### List of audit links if any:
  - https://1570067552-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FHCv4CkXABCLemz93mpi7%2Fuploads%2FuhcjNXBHA9yHn3b49ibX%2FPeckShield-Audit-Report-MYX-v1.0.pdf?alt=media&token=0b011c50-cb83-432b-a37b-84fd88c3f5f9
  - https://1570067552-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FHCv4CkXABCLemz93mpi7%2Fuploads%2FjSF3929CurPBEmPKgS1C%2FSlowMist%20Audit%20Report%20-%20MYX%20Protocol.pdf?alt=media&token=1000fd1e-f8b1-42dc-b95b-5aad70928c31
  - https://1570067552-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FHCv4CkXABCLemz93mpi7%2Fuploads%2Fa73mi2pbsoZwjmQ8TN5F%2FSlowMist%20Audit%20Report%20-%20MYX%20Protocol%20Phase2.pdf?alt=media&token=0a349499-a86c-4ccd-b1b0-1c6a8a7608d0

##### Website Link:
  - https://myx.finance/

##### Logo (High resolution, will be shown with rounded borders):
image

##### Current TVL:
  - Arbitrum：4.22m
  - Linea：901.51k

##### Treasury Addresses (if the protocol has treasury)
  - No

##### Chain:
  - Arbitrum
  - Linea

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
  - No

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
  - No

##### Short Description (to be shown on DefiLlama):
  - The first decentralized derivatives protocol with a Matching Pool Mechanism.

##### Token address and ticker if any:
  - No

##### Category (full list at https://defillama.com/categories) *Please choose only one:
  - Derivatives

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
  - Pyth
  
##### Implementation Details: Briefly describe how the oracle is integrated into your project:
- MYX keepers updates and verifies PYTH oracle price every time a trade is executed, the newest price is required.

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
- https://github.com/myx-protocol/myx-contracts

##### forkedFrom (Does your project originate from another project):
  - No

##### methodology (what is being counted as tvl, how is tvl being calculated):
- Total assets owned by MLP pools. 

##### Github org/user (Optional, if your code is open source, we can track activity):
- https://github.com/myx-protocol/myx-contracts

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/myx-finance exports TVL: 
        
 
 
    arbitrum                  4.22 M
    linea                     895.59 k
    
    total                    5.11 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
Please compute tvl onchain

**Comment by llamatester** [comment]
The adapter at projects/myx-finance exports TVL: 
        
 
 
    linea                     0
    arbitrum                  2.2857483231143183e+25 B
    
    total                    2.2857483231143183e+25 B

**Comment by jiangmaniu** [comment]
There seems to be some problem with the subgraph data, it is being debugged.

**Comment by llamatester** [comment]
The adapter at projects/myx-finance exports TVL: 
        
 
 
    linea                     870.62 k
    arbitrum                  5.87 M
    
    total                    6.74 M

**Comment by jiangmaniu** [comment]
@g1nt0ki  The data has been corrected, now get the tvl data from the subgraph

**Comment by llamatester** [comment]
The adapter at projects/myx-finance exports TVL: 
        
 
 
    linea                     870.11 k
    arbitrum                  5.95 M
    
    total                    6.82 M

**Pull request merged**
