### PR TITLE
Addition of new WELD Finance

### PR DESCRIPTION
**Pull request by AgrawalAshishS**
Twitter Link: https://twitter.com/KnitFinance
List of audit links if any: https://www.certik.com/projects/knitfinance
Website Link:https://knit.finance
Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

knitlogo

Current TVL:$9500385
Chain:

ETH
BSC
POLYGON
FANTOM
HECO
REEF
OKEXCHAIN
BITGERT
SYSCOIN
MILKOMEDA
KCC
AVALANCHE
HARMONY
TELOS
XDAI
MOONBEAM
MOONRIVER
KAVA

Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

https://www.coingecko.com/en/coins/knit-finance
Coinmarketcap ID (so your TVL can appear on Coinmarketcap): https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000
Short Description (to be shown on DefiLlama): Multi Chain Wrapped Assets ( Coins and NFTs) and Liquid stacking protocol for all the assets.

Developed Single infrastructure which will allow various assets , liquidity to move from one chain to another seamlessely as well enable liquidity staking for DPoS assets
Token address and ticker if any:https://etherscan.io/address/0xef53462838000184f35f7d991452e5f25110b207
Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:

Bridge
Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):custom
forkedFrom (Does your project originate from another project):no
methodology (what is being counted as tvl, how is tvl being calculated):On destination chain,Sum of value of all assets, where as value of asset is calculated as : total tokens in the chain multiplied by last traded price

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/weldfinance: 
        
 
  
    
    
    AxiosError: Request failed with status code 404
    Axios:  Route GET:/api/public/tvl-weld/kava not found

**Comment by AgrawalAshishS** [comment]
Fixed spell mistake in API.

**Comment by llamatester** [comment]
The adapter at projects/weldfinance exports TVL: 
        
 
 
    kava                      2.50 M
    
    total                    2.50 M

**Comment by g1nt0ki** [comment]
@AgrawalAshishS I am bit confused, we are already counting this tvl under kava chain.

Are you part of Knit team?  the current tvl of knit bridge does not look right, can you share some documentation of where tokens are locked in source chain and how you determine the price of tokens?

**Comment by g1nt0ki** [comment]
@AgrawalAshishS if you are part of knit team, please reach out, I am closing this story and delisting knit till we resolve the tvl issue

**Comment by AgrawalAshishS** [comment]
Sorry for the delayed response. I was trying to find the root cause for
confusion.

We now have 2 applications - Knit Finance and Weld Finance.

Changes part of this commit are not for Knit but for Weld. I think our dev
made a mistake by using the same branch name. Please reject this pull
request.

For Knit Finance TVL is calculated based on token or pegged token's price
available from CoinPulse api. This value is updated every 6 hours.

I have corrected my mistake by creating a new branch for WeldFinance and
opening a fresh pull request for it.

Please let me know if there are any questions and what will need to get
Knit listed again.

Thanks,
Ashish Agrawal* <http://apptheory.com/>*

**Comment by g1nt0ki** [comment]
hi @AgrawalAshishS ,

I have delisted Knit (temporarily)

Can you share the contract addesses on source chain where the tokens are locked, for a token to be included, we should some basic requirement, like being listed on coingecko, I think this is reasonable, we have similar rule for other bridges

Also noticed that tokens are counted as part of tvl of both source and destionation chain? I am guessing only from the the api, unable to verify data on chain hence asking for the contract addresses of the bridges

**Comment by AgrawalAshishS** [comment]
Hi,

Hey guys you can see one of our tokens as valued on CoinGeko :
https://www.coingecko.com/en/coins/knit-finance
Here is link to one of our cold wallet on EtherScan :
https://etherscan.io/address/0x7d6762c69559b9a9208c6609ce21e870a46cfbb4#tokentxns

As you can see there are tokens stored in the wallet. We also consider our
Wrapped assets value same as the original token. This is because when it is
swap back, we unwarp equal amount of the original token. Considering this
as a value we are using that in TVL.

We only consider k tokens value wise on the destination chain.

Please let me know if you have any questions.

Thanks,
Ashish Agrawal* <http://apptheory.com/>*

**Comment by AgrawalAshishS** [comment]
For Knit, we are running a bridge using Fireblocks and its callback and
withdrawal system. Due to this, we don't need any contract for bridging.
Stacking on Knit - https://app.knit.finance/staking is there as initial.
Right now our TVL is calculated based on information I have shared in a
previous email.

Please let me know if you have any questions.

Thanks,
Ashish Agrawal* <http://apptheory.com/>*

**Comment by AgrawalAshishS** [comment]
Hi,

Please do let me know what can we do to get Knit finance listed again.

**Pull request closed without merging**
