### PR TITLE
Updating adapter for CygnusDAO

### PR DESCRIPTION
**Pull request by swan-of-bodom**
Updating the adapter for `CygnusDAO`. We performed an audit on November 2023 and we re-deployed the factory on Polygon and Arbitrum.

Audit: https://github.com/borosorus/CygnusDAO-audit

Old Factory (Polygon): 0x94faE55669327e71E9EC579067ad6C3C3b84e574

New Factory (Polygon & Arbitrum): 0x8796747946871B6b8ea495CCE8d7814b17959296

Thanks!

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/cygnusdao: 
        
 
  
    
    
    TypeError: Cannot convert undefined or null to object
    Truncated error stack:
    
        at Function.entries (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:314:10)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:327:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:55:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:149:9
        at async Promise.all (index 0)
        at async Promise.all (index 2)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:194:3

**Comment by llamatester** [comment]
The adapter at projects/cygnusdao exports TVL: 
        
 
 
    arbitrum-borrowed         1.54 k
    polygon-borrowed          3.50 k
    arbitrum                  2.51 k
    polygon                   5.21 k
    borrowed                  5.04 k
    
    total                    7.72 k

**Comment by swan-of-bodom** [comment]
Also could we add the audit to our page?

**Comment by llamatester** [comment]
The adapter at projects/cygnusdao exports TVL: 
        
 
 
    arbitrum-borrowed         1.54 k
    polygon-borrowed          3.50 k
    arbitrum                  2.53 k
    polygon                   5.21 k
    borrowed                  5.03 k
    
    total                    7.75 k

**Comment by g1nt0ki** [comment]
> Also could we add the audit to our page?

thanks for the PR @swan-of-bodom , yes, we will add the audit as well

**Pull request merged**
