### PR TITLE
Radix: RadLock (Token Locker)

### PR DESCRIPTION
**Pull request by beemdvp**
##### Category (full list at https://defillama.com/categories) *Please choose only one:
Token Locker

##### methodology (what is being counted as tvl, how is tvl being calculated):
Using APIs from ociswap, caviarnine and defiplaza to get underlying token amount, calculate the LP underlying amounts and finally get the XRD value of both sides. Tokens locked in the RadLock component are also counted towards locked tokens.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/radlock exports TVL: 
        
 
 
    radixdlt                  7.82 M
    
    total                    7.82 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
hi @beemdvp thanks for the PR, is there a way to filter for only LP tokens? we treat only locked LP tokens as tvl for token lockers, you can check our implementation for similar protocols like pinksale or deeplock

**Comment by snjak** [comment]
> hi @beemdvp thanks for the PR, is there a way to filter for only LP tokens? we treat only locked LP tokens as tvl for token lockers, you can check our implementation for similar protocols like pinksale or deeplock

Hey, how come regular locks are not counted in? They are real TVL imo. 

Some teams vested tons of tokens for months and years which are definitely locked and out of circulation

**Comment by g1nt0ki** [comment]
sorry, the answer is still no. We dont treat vesting as tvl

**Comment by snjak** [comment]
> sorry, the answer is still no. We dont treat vesting as tvl

Alright, we understand and will make the required changes.

However, I'm curious about the reasoning behind not treating locked or vested tokens as TVL. In many cases, these seem more like 'real' TVL than unlocked LPs, which can be withdrawn at any time, or LSUs on Radix, which are tradeable.

**Comment by llamatester** [comment]
The adapter at projects/radlock exports TVL: 
        
 
 
    radixdlt                  1.44 M
    
    total                    1.44 M

**Comment by beemdvp** [comment]
> hi @beemdvp thanks for the PR, is there a way to filter for only LP tokens? we treat only locked LP tokens as tvl for token lockers, you can check our implementation for similar protocols like pinksale or deeplock

Amended the API to include LPs only

**Comment by g1nt0ki** [comment]
> > sorry, the answer is still no. We dont treat vesting as tvl
> 
> Alright, we understand and will make the required changes.
> 
> However, I'm curious about the reasoning behind not treating locked or vested tokens as TVL. In many cases, these seem more like 'real' TVL than unlocked LPs, which can be withdrawn at any time, or LSUs on Radix, which are tradeable.

Not gonna names the protocols, but some of the launchpads we added, let people mint a big supply and lock 99% or even more, this way, tokens with less than 5k$ in liquidity had 100s of millions mcap, and the launchpad suddenly had billions locked in tvl, now it is not fair comparison with launchpads that did not do this, it is harder to fake uni v2 LPs, since you need equal amount of stablecoin/ETH/bnb


Is there a easy way to pull the tvl on chain? I understand that it is difficult to pull LP value on chain?

**Comment by beemdvp** [comment]
> Is there a easy way to pull the tvl on chain? I understand that it is difficult to pull LP value on chain?

Unfortunately not. If everyone used the native pool components on radix, it would've been easy to pull on-chain. However LPs are also being represented as NFTs alongside fungible token pool units. So this is why a middleware is required to detect the type of pool and then calculate the XRD value of them. Hope that helps :+1:

**Comment by snjak** [comment]
> Not gonna names the protocols, but some of the launchpads we added, let people mint a big supply and lock 99% or even more, this way, tokens with less than 5k$ in liquidity had 100s of millions mcap, and the launchpad suddenly had billions locked in tvl, now it is not fair comparison with launchpads that did not do this, it is harder to fake uni v2 LPs, since you need equal amount of stablecoin/ETH/bnb

Oh completely understandable now, thanks for clarification. 

Will think a bit if we could somehow prevent this from happening, since this means our stats could actually be gamed too.

**Pull request merged**
