### PR TITLE
add perfectswap

### PR DESCRIPTION
**Pull request by perfect-swap**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
PerfectSwap

##### Twitter Link:
https://twitter.com/perfectswapio

##### List of audit links if any:
https://github.com/solidproof/projects/tree/main/2024/PerfectSwap

##### Website Link:
https://perfectswap.io/

##### Logo (High resolution, will be shown with rounded borders):
https://app.perfectswap.io/logo.png

##### Current TVL:
0

##### Chain:
Arbitrum

##### Short Description (to be shown on DefiLlama):
Autonomous decentralized exchange that focuses on optimizing the acquisition of healthy Total Value Locked (TVL) in a capital-efficient manner.

##### Token address and ticker if any:
0x9D91C3d544Fc7f5FDcF680bc249FEca6820e06a6
PRFCT

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### forkedFrom (Does your project originate from another project):
Solidly

##### methodology (what is being counted as tvl, how is tvl being calculated):
Fees: Swap fees paid by users

Revenue: Percentage of swap fees going to treasury and/or token holders

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/perfect-swap

### CODE REVIEW

**Comment by g1nt0ki** [comment]
hi, we cant list projects with 0 tvl, can you post a comment here when you have some tvl?

**Comment by perfect-swap** [comment]
> hi, we cant list projects with 0 tvl, can you post a comment here when you have some tvl?

Yes, so can you list right after we have some tvl? how long will it take to list after I comment here?

**Comment by g1nt0ki** [comment]
> > hi, we cant list projects with 0 tvl, can you post a comment here when you have some tvl?
> 
> Yes, so can you list right after we have some tvl? how long will it take to list after I comment here?

usually a few hours

**Comment by g1nt0ki** [comment]
closing this for now, can re-open it where there is some tvl

**Pull request closed without merging**
