### PR TITLE
add cian adapter

### PR DESCRIPTION
**Pull request by NatureLab**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@NatureLab please fill the project details in the PR form

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
Also, can you explain a bit about how tvl is computed here, is it possible to replace it with on chain/graph calls?

**Comment by NatureLab** [comment]
> @NatureLab请在 PR 表格中填写项目详细信息
Twitter Link: https://twitter.com/CIAN_protocol
List of audit links : 
Website Link: https://cian.app
Logo : https://img.cian.app/cian.svg
Current TVL: $889859.63
Chain: avalanche
Coingecko ID : 
Coinmarketcap ID :
Short Description : CIAN is an open automation platform for onchain applications that allows users to swiftly build, optimize and protect intricate strategies using unrivaled automation primitives. 
Token address and ticker :
Category : Services
Oracle used : Chainlink
forkedFrom : 
methodology : We added the assets of all users smart contract account in our protocol

**Comment by llamatester** [comment]
The adapter at projects/cian exports TVL: 
        
 
 
    avalanche                 889.86 k
    
    total                    889.86 k

**Pull request merged**
