### PR TITLE
Adding adapter for new version of Connext Amarok

### PR DESCRIPTION
**Pull request by legendarykamal**
WIP for Adding adapter for new version of Connext Amarok

**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Connext

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/connext exports TVL: 
        
 
 
    arbitrum                  19.01 k
    moonriver                 117.95 k
    xdai                      2.69 M
    moonbeam                  156.8092648892719
    avax                      219.96 k
    bsc                       796.40 k
    fantom                    1.89 M
    ethereum                  83.59 k
    boba                      25.62 k
    evmos                     135.05 k
    polygon                   590.40 k
    milkomeda                 63.87 k
    cronos                    12.018872229431999
    harmony                   2.7280552024799998e-14
    fuse                      1.16 k
    optimism                  365.13 k
    
    total                    7.00 M

**Comment by llamatester** [comment]
The adapter at projects/connext exports TVL: 
        
 
 
    boba                      25.99 k
    avax                      232.01 k
    milkomeda                 64.16 k
    evmos                     135.34 k
    moonbeam                  157.73204014696705
    xdai                      2.61 M
    ethereum                  83.65 k
    fantom                    1.93 M
    polygon                   593.42 k
    arbitrum                  19.52 k
    moonriver                 118.39 k
    harmony                   2.645746772122e-14
    bsc                       825.26 k
    fuse                      1.16 k
    cronos                    26.144806708
    optimism                  368.41 k
    
    total                    7.01 M

**Comment by llamatester** [comment]
The adapter at projects/connext exports TVL: 
        
 
 
    arbitrum                  19.51 k
    xdai                      2.61 M
    avax                      231.97 k
    fantom                    1.93 M
    moonbeam                  157.87604614200777
    milkomeda                 64.19 k
    moonriver                 118.44 k
    polygon                   593.78 k
    harmony                   2.645746772122e-14
    ethereum                  83.67 k
    boba                      25.99 k
    fuse                      1.16 k
    bsc                       824.90 k
    evmos                     135.47 k
    cronos                    26.170889558
    optimism                  368.71 k
    
    total                    7.01 M

**Comment by llamatester** [comment]
Error while running adapter at projects/connext: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by llamatester** [comment]
Error while running adapter at projects/connext: 
        
 
  
    
    
    Error: 
        Unknown chain(s): gnosis
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file

**Comment by llamatester** [comment]
Error while running adapter at projects/connext: 
        
 
  
    
    
    Error: 
        Unknown chain(s): gnosis
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file

**Comment by g1nt0ki** [comment]
sorry, I have not looked at this PR in a while, will try to review it next week

**Comment by g1nt0ki** [comment]
@legendarykamal I finally had a look at the code, is the dependency on connect sdk necessary? 

Are most chains like fantom/moonriver no longer supported? 

Can you check my changes? https://github.com/DefiLlama/DefiLlama-Adapters/commit/dcdd7d138a18c2f301033db7fcf950086cb52473 connext tvl is now 25m

**Comment by legendarykamal** [comment]
Thank  you just taking a look now 🙌🏻

**Comment by llamatester** [comment]
Error while running adapter at projects/connext: 
        
 
  
    
    
    Error: {
      "instancePath": "/logLevel",
      "schemaPath": "#/properties/logLevel/anyOf/0/type",
      "keyword": "type",
      "params": {
        "type": "string"
      },
      "message": "must be string"
    },{
      "instancePath": "/logLevel",
      "schemaPath": "#/properties/logLevel/anyOf/0/const",
      "keyword": "const",
      "params": {
        "allowedValue": "fatal"
      },
      "message": "must be equal to constant"
    },{
      "instancePath": "/logLevel",
      "schemaPath": "#/properties/logLevel/anyOf/1/type",
      "keyword": "type",
      "params": {
        "type": "string"
      },
      "message": "must be string"
    },{
      "instancePath": "/logLevel",
      "schemaPath": "#/properties/logLevel/anyOf/1/const",
      "keyword": "const",
      "params": {
        "allowedValue": "error"
      },
      "message": "must be equal to constant"
    },{
      "instancePath": "/logLevel",
      "schemaPath": "#/properties/logLevel/anyOf/2/type",
      "keyword": "type",
      "params": {
        "type": "string"
      },
      "message": "must be string"
    },{
      "instancePath": "/logLevel",
      "schemaPath": "#/properties/logLevel/anyOf/2/const",
      "keyword": "const",
      "params": {
        "allowedValue": "warn"
      },
      "message": "must be equal to constant"
    },{
      "instancePath": "/logLevel",
      "schemaPath": "#/properties/logLevel/anyOf/3/type",
      "keyword": "type",
      "params": {
        "type": "string"
      },
      "message": "must be string"
    },{
      "instancePath": "/logLevel",
      "schemaPath": "#/properties/logLevel/anyOf/3/const",
      "keyword": "const",
      "params": {
        "allowedValue": "info"
      },
      "message": "must be equal to constant"
    },{
      "instancePath": "/logLevel",
      "schemaPath": "#/properties/logLevel/anyOf/4/type",
      "keyword": "type",
      "params": {
        "type": "string"
      },
      "message": "must be string"
    },{
      "instancePath": "/logLevel",
      "schemaPath": "#/properties/logLevel/anyOf/4/const",
      "keyword": "const",
      "params": {
        "allowedValue": "debug"
      },
      "message": "must be equal to constant"
    },{
      "instancePath": "/logLevel",
      "schemaPath": "#/properties/logLevel/anyOf/5/type",
      "keyword": "type",
      "params": {
        "type": "string"
      },
      "message": "must be string"
    },{
      "instancePath": "/logLevel",
      "schemaPath": "#/properties/logLevel/anyOf/5/const",
      "keyword": "const",
      "params": {
        "allowedValue": "trace"
      },
      "message": "must be equal to constant"
    },{
      "instancePath": "/logLevel",
      "schemaPath": "#/properties/logLevel/anyOf/6/type",
      "keyword": "type",
      "params": {
        "type": "string"
      },
      "message": "must be string"
    },{
      "instancePath": "/logLevel",
      "schemaPath": "#/properties/logLevel/anyOf/6/const",
      "keyword": "const",
      "params": {
        "allowedValue": "silent"
      },
      "message": "must be equal to constant"
    },{
      "instancePath": "/logLevel",
      "schemaPath": "#/properties/logLevel/anyOf",
      "keyword": "anyOf",
      "params": {},
      "message": "must match a schema in anyOf"
    }
    Truncated error stack:
        at getEnvConfig (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@connext/sdk/dist/config.js:120:15)
        at async SdkShared (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/connext/index.js:39:5)
        at async sdk (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/connext/index.js:45:5)

**Comment by g1nt0ki** [comment]
closing this as I have implemented the changes here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/dcdd7d138a18c2f301033db7fcf950086cb52473

**Pull request closed without merging**
