### PR TITLE
Add Ion Protocol Adapter

### PR DESCRIPTION
**Pull request by DashanMcCain**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Ion Protocol

##### Twitter Link:
https://twitter.com/ionprotocol

##### List of audit links if any:
https://blog.openzeppelin.com/ion-protocol-audit
https://app.hats.finance/audit-competitions/ion-protocol-0x20c44e7b618d58f9982e28de66d8d6ee176eb481/leaderboard

##### Website Link:
https://ionprotocol.io/

##### Logo (High resolution, will be shown with rounded borders):
Ion_Logo

##### Current TVL:
6.08M

##### Chain:
Ethereum

##### Short Description (to be shown on DefiLlama):

Ion Protocol is a price-agnostic lending platform built to support staked and restaked assets. It allows users to participate in lending markets of all kinds, ranging from leveraged staking yields to points multiplier pools and more. Ion focuses on bringing staking-based mechanisms to DeFi, creating an enhanced lending and borrowing experience for users to earn more while risking less.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Chainlink and Redstone

##### Implementation Details: Briefly describe how the oracle is integrated into your project:
Reserve oracles will provide pricing data *with reference to beacon chain balances.* This can come from various sources including LST provider provider exchange rate data, custom centralized Ion oracles, or third-party proof of reserve oracles.

Liquidations will be based on the pricing data provided by reserve oracles, allowing Ion liquidations to be fully price agnostic (in terms of the market price).

The spot oracle, in contrast to the reserve oracle, reflects the ‘market price’ of the asset, the price at which the asset trades at in external markets. This oracle is used by the `IonPool` when opening, altering, or closing debt positions. 

Although the `Liquidation` module reads from the reserve price, it is necessary for the `IonPool` to operate on market price when manipulating positions to prevent the pool from valuing the collateral at a rate higher than the open market. This allows the lending pool to prevent price discrepancy arbitrage while enabling price-agnostic liquidations.

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
[Reserve Oracle](https://docs.ionprotocol.io/devs/smart-contract-architecture/oracles/reserve/reserveoracle)
[Spot Oracle](https://docs.ionprotocol.io/devs/smart-contract-architecture/oracles/spot/spotoracle)
##### forkedFrom (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is calculated using the value of tokens held within contracts only. Borrowed tokens are excluded from the TVL calculation. This exclusion helps prevent artificial inflation of TVL due to cyclical lending practices, ensuring that only tokens actively secured within the contracts contribute to the TVL metric.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/Ion-Protocol

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/ion-protocol exports TVL: 
        
 
 
    ethereum                  6.05 M
    ethereum-borrowed         3.67 M
    borrowed                  3.67 M
    
    total                    6.05 M

**Comment by g1nt0ki** [comment]
@DashanMcCain thanks for the PR, refactored and merged here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/10007

is there some api/github file where we can pull the gem list from? that way, the code would be more dynamic

**Comment by DashanMcCain** [comment]
> @DashanMcCain thanks for the PR, refactored and merged here: #10007
> 
> is there some api/github file where we can pull the gem list from? that way, the code would be more dynamic

Thanks for the response @g1nt0ki, there is no public facing way to access the gem list at the moment, but I can make an endpoint for it. To make this change to the adapter, I would just need to make another PR to this repository since the other repository is for updating listing info only, is this correct?

**Comment by g1nt0ki** [comment]
> > @DashanMcCain thanks for the PR, refactored and merged here: #10007
> > is there some api/github file where we can pull the gem list from? that way, the code would be more dynamic
> 
> Thanks for the response @g1nt0ki, there is no public facing way to access the gem list at the moment, but I can make an endpoint for it. To make this change to the adapter, I would just need to make another PR to this repository since the other repository is for updating listing info only, is this correct?
 yup, that is correct

**Pull request closed without merging**
