### PR TITLE
Submit pegasusdollar.finance

### PR DESCRIPTION
**Pull request by PegasusDollar**
##### Twitter Link: 
https://twitter.com/pegasusdollar

##### List of audit links if any:
https://github.com/peckshield/publications/blob/master/audit_reports/PeckShield-Audit-Report-PegasusDollar-v1.0.pdf
https://github.com/solidproof/projects/tree/main/PegasusDollar

##### Website Link:
https://pegasusdollar.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://raw.githubusercontent.com/PegasusDollar/resource/main/logo-pes.png

##### Current TVL:
59,000,000 $

##### Chain:
Cronos

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
not listed

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
not listed

##### Short Description (to be shown on DefiLlama):
The first algorithmic token pegged to METF running on the Cronos Chain.
Completely decentralized on chain governance.

##### Token address and ticker if any:
PES: 0x8efbaa6080412d7832025b03b9239d0be1e2aa3b
SPES: 0xbbd4650eea85f9dbd83d6fb2a6e8b3d8f32fe1c5

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Algo-Stables

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
twap

##### forkedFrom (Does your project originate from another project):
tomb

##### methodology (what is being counted as tvl, how is tvl being calculated):
pool2. Counts liquidity of the tokens deposited in PESRewardPool and SPESRewardPool.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/pegasusdollar/index.js exports TVL: 
        
 
 
    cronos                    59.03 M
    cronos-pool2              59.03 M
    pool2                     59.03 M
    
    total                    59.03 M

**Comment by PegasusDollar** [comment]
> The adapter at projects/pegasusdollar/index.js exports TVL:
> 
> ```
> cronos                    59.03 M
> cronos-pool2              59.03 M
> pool2                     59.03 M
> 
> total                    59.03 M 
> ```

Yes TVL i submit use tokens:  WCRO, USDT, MMF, METF. token PES, SPES and staked boardroom not submit in code.

**Comment by PegasusDollar** [comment]
It's OK. Can i need change anything, sir?

**Comment by PegasusDollar** [comment]
I just updated the commit description. Please check us out. Thank you!

**Pull request closed without merging**
