### PR TITLE
Add kava tvl

### PR DESCRIPTION
**Pull request by yuhuakukude**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/antimatterDAO exports TVL: 
        
 
 
    ethereum-staking          993.89 k
    arbitrum                  18.16 k
    avax                      9.40 k
    ethereum                  19.87 k
    kava                      503.1996
    bsc                       161.57 k
    staking                   993.89 k
    
    total                    209.51 k

**Comment by llamatester** [comment]
The adapter at projects/antimatterDAO exports TVL: 
        
 
 
    arbitrum                  17.99 k
    avax                      9.18 k
    ethereum-staking          1.01 M
    ethereum                  19.68 k
    kava                      503.70279959999993
    bsc                       161.40 k
    staking                   1.01 M
    
    total                    208.75 k

**Comment by llamatester** [comment]
The adapter at projects/nervenetworkbridge exports TVL: 
        
 
 
    metis                     0
    ethpow                    0
    kava                      0.009429387
    arbitrum                  424.04626360558996
    avax                      76.11 k
    cronos                    10.152825618879117
    tron                      13.63 k
    smartbch                  3.79 k
    iotex                     33.3064787412
    harmony                   3.84 k
    optimism                  0.0015905899999999998
    enuls                     26.38 k
    heco                      9.60 k
    ethereum                  365.03 k
    kcc                       4.94 k
    fantom                    6.42 k
    okexchain                 111.92 k
    polygon                   45.38 k
    bsc                       702.44 k
    klaytn                    0.13828628099999998
    nuls                      5.67 M
    
    total                    7.04 M

**Comment by g1nt0ki** [comment]
@yuhuakukude thanks for PR, I have refactored code to include kava here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/4f256168dadab052db5e31754656d997d74d0ca2

**Pull request closed without merging**
