### PR TITLE
Archimedes Finance TVL Adapter

### PR DESCRIPTION
**Pull request by jrc-archimedes**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Token address and ticker if any:
ARCH: 0x73C69d24ad28e2d43D03CBf35F79fE26EBDE1011
LvUSD: 0x94A18d9FE00bab617fAD8B49b11e9F1f64Db6b36

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/ArchimedesFinance exports TVL: 
        
 
 
    ethereum                  3.85 M
    
    total                    3.85 M

**Comment by realdealshaman** [comment]
@jrc-archimedes Hi, Thanks for submitting the PR. Just wanted to clarify, is lvUSD a token created by your project? If it is, we would only be able to count the value of 3CRV used as collateral, not the lvUSD token itself. Can merge once it is updated

**Comment by llamatester** [comment]
The adapter at projects/ArchimedesFinance exports TVL: 
        
 
 
    ethereum                  4.10 M
    
    total                    4.10 M

**Comment by llamatester** [comment]
The adapter at projects/ArchimedesFinance exports TVL: 
        
 
 
    ethereum                  4.10 M
    
    total                    4.10 M

**Comment by jrc-archimedes** [comment]
> 

Hi, lvUSD is a stable coin created by our organization. I have updated the adapter to display a TVL calculated by the sum of the amount of 3CRV liquidity in the curve pool and the total OUSD held in our protocol's ERC4626 vault.

**Comment by jrc-archimedes** [comment]
@llamatester Thanks for the merge! If we want to make any future updates to our TVL calculation would we open a PR the same way?

**Pull request merged**
