### PR TITLE
DappRadar RADAR staking on sushi masterchef

### PR DESCRIPTION
**Pull request by jo-chemla**
DapRadar RADAR staking on sushi masterchef

##### Twitter Link:
https://twitter.com/dappradar

##### Website Link:
https://dappradar.com

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
white bg: https://avatars.githubusercontent.com/u/48711064?s=280&v=4

##### Current TVL:
500k staked on sushi masterchef (RADAR/WETH LP)

##### Chain:
Eth mainnet

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
dappradar

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
15188

##### Short Description (to be shown on DefiLlama):
Discover, Track & Trade Everything DeFi, NFT and Gaming

##### Token address and ticker if any:
RADAR 0x44709a920fccf795fbc57baa433cc3dd53c44dbe

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Assets

##### methodology (what is being counted as tvl, how is tvl being calculated):
RADAR token can be LP'ed on Sushi and LP can be staked on Sushiswap Masterchef - more TVL soon

### CODE REVIEW

**Comment by 0xngmi** [comment]
should we still merge this after conversation on discord?

**Comment by jo-chemla** [comment]
> should we still merge this after conversation on discord?

yep can be done - conversation was regarding PSP pools which are indeed not pool2

**Comment by 0xngmi** [comment]
but in this case are any LP tokens locked in dappradar contracts?

**Comment by jo-chemla** [comment]
That's completely right, these LP are locked in sushi masterchef, not the protocol contracts themselves. My understanding following the discord conversation was that **pool2**  was for staking of LP of stkTokens, but **staking**  could include the sushi masterchef. Since the protocol is staking only with no other tvl at the moment, it's your call! And I did the same integration for xdefi, whose only TVL is staking, LP staked in sushi masterchef.

**Pull request closed without merging**
