### PR TITLE
Unizen && Shiroswap && 3omb Finance && Geist Updating && Beluga && PearZap && DeepLock && Oceanus Finance && DNA Dollar TVL Adapters

### PR DESCRIPTION
**Pull request by Mohammed18062020**
##### Twitter Link:
Unizen -> https://twitter.com/unizen_io
Shiroswap -> https://twitter.com/shirotokens
3omb Finance -> https://twitter.com/2ombfinance
Beluga -> https://twitter.com/beluga_fi
Pearzap -> https://twitter.com/pearzap
DeepLock -> https://twitter.com/deeplockio
Oceanus Finance -> https://twitter.com/0xOceanus
DNA Dollar -> https://twitter.com/dna_dollar

##### Website Link:
Unizen -> https://www.unizen.io/token/
Shiroswap -> https://shirotoken.com/
3omb Finance -> https://3omb.finance/
Beluga -> https://beluga.fi/
Pearzap -> https://app.pearzap.com/
DeepLock -> https://deeplock.io/
Oceanus Finance -> https://oceanus.finance/
DNA Dollar -> https://dnadollar.com/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
Unizen -> 
image

Shiroswap -> 
image

3omb Finance -> 
image

Beluga -> 
image

Pearzap -> 
image

DeepLock -> 
image

Oceanus Finance -> 
image

DNA Dollar -> 
image

##### Current TVL:
Unizen -> $62.04 M
Shiroswap -> $62,529.83
3omb Finance -> $12,489,418
Beluga -> $5,604,139.67
Pearzap -> $$132,871.241
DeepLock -> $$4,244,404,942.422 (Most of tvl is pml token!)
Oceanus Finance -> $242,145
DNA Dollar -> $680,372

##### Chain:
Unizen -> Ethereum
Shiroswap -> BSC
3omb Finance -> Fantom
Beluga -> Fantom
Pearzap -> BSC, Polygon and Fantom
DeepLock -> BSC
Oceanus Finance -> Metis
DNA Dollar -> Cronos

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
Unizen -> unizen
Shiroswap -> 
3omb Finance -> 
Beluga -> beluga-fi
Pearzap -> 
DeepLock -> deeplock
Oceanus Finance -> sea-oceanus
DNA Dollar -> dna-dollar

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
Unizen -> 9263
Shiroswap -> 16720
3omb Finance -> 
Beluga -> 
Pearzap -> 11105
DeepLock -> 
Oceanus Finance -> 
DNA Dollar -> 

##### Token address and ticker if any:
Unizen Token (ZCX) -> 0xc52c326331e9ce41f04484d3b5e5648158028804
Shiroswap Token (SHIR) -> 0x4ddba615a7F6ee612d3a23C6882B698dFBbef7E7
3omb Finance Token (3OMB)  -> 0x14DEf7584A6c52f470Ca4F4b9671056b22f4FfDE
Beluga Token (BELUGA) -> 0x4a13a2cf881f5378def61e430139ed26d843df9a
Pearzap Token (PEAR):
BSC -> 0xdf7c18ed59ea738070e665ac3f5c258dcc2fbad8
Polygon -> 0xc8bcb58caEf1bE972C0B638B1dD8B0748Fdc8A44
Fantom -> 0x7c10108d4b7f4bd659ee57a53b30df928244b354
DeepLock Tooken (DEEP) -> 0x60de5f9386b637fe97af1cc05f25548e9baaee19
Oceanus Finance Token (SEA) -> 0x41607272ce6f2a42732ae382f00f8f9ce68d78f3
DNA Dollar Token (DNA) -> 0xcc57f84637b441127f2f74905b9d99821b47b20c

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Unizen -> Staking
Shiroswap -> Dexes
3omb Finance -> Yield
Beluga -> Yield
Pearzap -> Dexes
DeepLock -> Assets
Oceanus Finance -> Staking
DNA Dollar -> Yield

### CODE REVIEW

**Comment by Nemusonaneko** [comment]
Should 3omb be added to 2omb finance instead?

**Comment by Mohammed18062020** [comment]
> Should 3omb be added to 2omb finance instead?

I think should be separate even 3omb was created by the same deployer as 2omb, but the project is different, further the other platform like debank separates it from 2omb

**Comment by waynebruce0x** [comment]
> > Should 3omb be added to 2omb finance instead?
> 
> I think should be separate even 3omb was created by the same deployer as 2omb, but the project is different, further the other platform like debank separates it from 2omb

I'm leaning towards combining them, because they share the same docs, twitter, discord server etc

**Comment by Mohammed18062020** [comment]
> > > Should 3omb be added to 2omb finance instead?
> > 
> > 
> > I think should be separate even 3omb was created by the same deployer as 2omb, but the project is different, further the other platform like debank separates it from 2omb
> 
> I'm leaning towards combining them, because they share the same docs, twitter, discord server etc

Yeah, that's what I've seen too. Then we can add it as a advance version of 2omb in the same index.js

**Pull request merged**
