### PR TITLE
update: VyFi tvl update

### PR DESCRIPTION
**Pull request by RyanFelt**
**NOTE**

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/vyfi: 
        
 
  
    
    
    Error: 
        Found export keys that were not part of specification: cardano
    
        List of valid keys: 
    				
    				tvl
    				staking
    				methodology
    				pool2
    				misrepresentedTokens
    				fetch
    				timetravel
    				borrowed
    				start
    				masterchef
    				doublecounted
    				treasury
    				hallmarks
    				incentivized
    				offers
    				deadFrom
    				broken
    				ownTokens
    				vesting

**Comment by llamatester** [comment]
The adapter at projects/vyfi exports TVL: 
        
 
 
    cardano-staking           0
    cardano                   0
    staking                   0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/vyfi exports TVL: 
        
 
 
    cardano-staking           1.53 M
    cardano                   1.53 M
    staking                   1.53 M
    
    total                    1.53 M

**Comment by g1nt0ki** [comment]
@RyanFelt Sorry,  I dont think this PR is correct, it is counting staked part again as tvl

**Comment by RyanFelt** [comment]
> @RyanFelt Sorry, I dont think this PR is correct, it is counting staked part again as tvl

Hey! So right now we only have staking launched, soon we will be launching our DEx, the TVL will be a combination of staking and liquidity pools, for now its just the tokens locked in the staking vaults. Let me know if this makes sense, or if I am doing it wrong?

**Comment by g1nt0ki** [comment]
hi @RyanFelt, I would count staked tvl under 'staking' key like now, when there is dex tvl, we count it under 'tvl', users have a choice to include/exclude staking from overall tvl.

makes sense?

**Comment by RyanFelt** [comment]
> hi @RyanFelt, I would count staked tvl under 'staking' key like now, when there is dex tvl, we count it under 'tvl', users have a choice to include/exclude staking from overall tvl.
> 
> makes sense?

The current app shows our tvl to be $0 which is incorrect  (https://defillama.com/chain/Cardano), staking is part of our tvl that why I was hoping it could be added to overall tvl. I will do as you reccomend but then it does not show the correct data on your app. Let me know how we can resolve this! Thanks for the quick responses

**Comment by llamatester** [comment]
The adapter at projects/vyfi exports TVL: 
        
 
 
    cardano                   0
    cardano-staking           1.58 M
    staking                   1.58 M
    
    total                    0

**Pull request merged**
