### PR TITLE
add linea vault to affine

### PR DESCRIPTION
**Pull request by kiwi0401**
Updating the current tvl to include L2 vaults for Affine 

https://defillama.com/protocol/affine-defi#information

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/affine-defi-liquid exports TVL: 
        
 
 
    ethereum                  817.73 k
    blast                     271.90 k
    linea                     134.81 k
    
    total                    1.22 M

**Comment by g1nt0ki** [comment]
are these tokens bridged from ethereum?

**Comment by kiwi0401** [comment]
> are these tokens bridged from ethereum?

Linea tokens are bridge+native, blast is bridged token

**Comment by g1nt0ki** [comment]
sorry, we can count only the native, can you update the code to remove blast and update linea to count only the native part?

**Comment by llamatester** [comment]
The adapter at projects/affine-defi-liquid exports TVL: 
        
 
 
    ethereum                  942.57 k
    linea                     259.78 k
    
    total                    1.20 M

**Comment by kiwi0401** [comment]
@g1nt0ki ok I removed blast for now, we have native on the way for Blast so once that happens I'll reopen the PR with the native price feed

**Comment by llamatester** [comment]
The adapter at projects/affine-defi-liquid exports TVL: 
        
 
 
    ethereum                  916.83 k
    linea                     255.30 k
    
    total                    1.17 M

**Pull request merged**
