### PR TITLE
ADD ALCHEMIST COIN $MIST to DEFILLAMA :)

### PR DESCRIPTION
**Pull request by wtfix**

### CODE REVIEW

**Comment by 0xngmi** [comment]
Thanks for the PR but we need some code that calculates your TVL

**Comment by wtfix** [comment]
our TVL is in uniswap v2/v3 and some SLP. Do you have any current adapters I can use that would be easy for someone to copy..thanks

**Comment by 0xngmi** [comment]
The closest adapter could be illuvium. If you could provide us the addresses where tokens are locked we could also give it a shot

**Comment by 0xngmi** [comment]
Looking at etherscan I don't see any tokens locked on
```
0x56eD0272f99eBD903043399A51794f966D72E526 Pescadero V2
0x914A766578C2397da969b3ca088e3e757249A435 Old Faithful V2
0x0ec93391752ef1A06AA2b83D15c3a5814651C891 Trinity V2
0x88F12aE68315A89B885A2f1b0610fE2A9E1720B9 Beehive V4
0x872b09f22873Dd22A1CB20c7D7120844650D1B9a NEO
0x1C8c8aF39d69a497943015833E3a7Ae102D1E2BD GEMINI
```

**Comment by 0xngmi** [comment]
Closing. According to our conversation on discord we'll need to wait for the devs to get us a way to get all the addresses that hold tokens

**Pull request closed without merging**
