### PR TITLE
Add DavinciGraph TVL Adaptor

### PR DESCRIPTION
**Pull request by psychoter**
##### Github org/user: https://github.com/DaVinciGraph/DaVinciGraphTokenLocker

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/davincigraph exports TVL: 
        
 
 
    
    total                    912.80 k

**Comment by g1nt0ki** [comment]
hi @psychoter 

Thanks for the PR, I would recommend one fix, is there some way to fetch only the locked LPs? for token lockers, we consider only that as tvl

**Comment by psychoter** [comment]
Hi @g1nt0ki 
Thanks for the feedback. Yes, I'll update the codes to only include locked LPs and try again.

**Comment by llamatester** [comment]
Error while running adapter at projects/davincigraph: 
        
 
  
    
    
    Error: TVL for key tvl is not a number, instead it is NaN
    Truncated error stack:
    
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:75:11)
        at async Promise.all (index 3)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by llamatester** [comment]
The adapter at projects/davincigraph exports TVL: 
        
 
 
    
    total                    174.01 k

**Comment by g1nt0ki** [comment]
@psychoter thanks for the update

**Pull request merged**
