### PR TITLE
feat: add adapter for sceptre staked flr

### PR DESCRIPTION
**Pull request by Harrirbl**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Sceptre Liquid Staking on Flare

##### Twitter Link:
https://twitter.com/SceptreLS

##### Website Link:
flare.sceptre.fi
##### Logo (High resolution, will be shown with rounded borders):
https://static.wixstatic.com/media/c4e15a_b1d59bc51702462891b074e58c05cd25~mv2.png/v1/fill/w_208,h_208,al_c,q_85,enc_auto/200%20sFLR.png

##### Current TVL:
$105.39k

##### Chain:
flare

##### Short Description (to be shown on DefiLlama):
Sceptre Liquid Staking on Flare aims to unlock liquidity on the Flare network.

##### Token address and ticker if any:
sFLR: 0x12e605bc104e93B45e1aD99F9e555f659051c2BB

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Liquid Staking

##### methodology (what is being counted as tvl, how is tvl being calculated):
totalPooledFLR * FLR price

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/sceptre-staked-flr exports TVL: 
        
 
 
    flare                     0
    
    total                    0

**Comment by Harrirbl** [comment]
Hi. For some reason the TVL returns 0, when I run the test. Is there something that I missed? Thanks.
image

**Comment by g1nt0ki** [comment]
thanks for the PR, fixed it

**Comment by llamatester** [comment]
The adapter at projects/sceptre-staked-flr exports TVL: 
        
 
 
    flare                     105.29 k
    
    total                    105.29 k

**Pull request merged**
