### PR TITLE
Binaryx Platform adapter

### PR DESCRIPTION
**Pull request by dmitriy-green**
##### Name (to be shown on DefiLlama):
Binaryx Platform

##### Twitter Link:
https://twitter.com/BinaryxPlatform

##### List of audit links if any:
https://blaize.tech/clients/smart-contract-security-audit-for-binaryx/

##### Website Link:
https://www.binaryx.com/ - MAIN
https://app.binaryx.com/ - APP

##### Logo (High resolution, will be shown with rounded borders):
PNG:
Gradient-3d on White Square

SVG:
Gradient-3d on White Square

##### Current TVL:
$727k+

##### Treasury Addresses (if the protocol has treasury)
--

##### Chain:
Polygon

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): 
--

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed):
--

##### Short Description (to be shown on DefiLlama):
Binaryx Platform is an infrastructure layer for RWA tokenization that opens up new real estate trading & investing opportunities for everyone with an internationally compliant legal framework.

##### Token address and ticker if any:
--

##### Category (full list at https://defillama.com/categories) *Please choose only one:
RWA

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
In-house oracle system for RWA prices regulation

##### forkedFrom (Does your project originate from another project):
--

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL for the Binaryx Platform is calculated by summing the values of all assets, with each asset's value determined by multiplying its token supply by its token price, where the token price is obtained from the priceOracle.

##### Github org/user (Optional, if your code is open source, we can track activity):
--

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/binaryx-platform exports TVL: 
        
 
 
    polygon                   727.61 k
    
    total                    727.61 k

**Comment by dmitriy-green** [comment]
> The adapter at projects/binaryx-platform exports TVL:
> 
> ```
> polygon                   727.61 k
> 
> total                    727.61 k 
> ```

Yes, that's correct

**Comment by g1nt0ki** [comment]
@dmitriy-green thanks for the PR

**Comment by llamatester** [comment]
The adapter at projects/binaryx-platform exports TVL: 
        
 
 
    polygon                   727.48 k
    
    total                    727.48 k

**Pull request merged**
