### PR TITLE
add tBTC bridge adapter

### PR DESCRIPTION
**Pull request by Luna5-threshold**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama): 
tBTC

##### Twitter Link: 
https://twitter.com/TheTNetwork

##### List of audit links if any: 
Least Authority https://leastauthority.com/blog/audits/audit-of-keep-network-tbtc-bridge-v2/

##### Website Link: 
https://threshold.network/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): 
tBTClogowhite
tBTClogo
tBTClogo

##### Current TVL: 
295.99729083 tBTC

##### Chain: 
Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
https://www.coingecko.com/en/coins/tbtc

##### Short Description (to be shown on DefiLlama): 
tBTC is Threshold’s decentralized and permissionless bridge to bring BTC to the Ethereum network. tBTC has been designed to allow bitcoin holders to participate in Ethereum's Decentralized Finance (DeFi) applications. Users wishing to utilize their bitcoin on Ethereum can use the tBTC decentralized bridge to deposit their bitcoin into the system and get a minted tBTC token in their Ethereum wallet.

##### Token address and ticker if any: 
https://etherscan.io/token/0x18084fba666a33d37592fa2633fd49a74dd93a88 
tBTC

##### Category (full list at https://defillama.com/categories) *Please choose only one: 
4 - Bridge

##### methodology (what is being counted as tvl, how is tvl being calculated): 
TVL for tBTC consists of the BTC deposits in custody that were used to mint tBTC

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/tbtc exports TVL: 
        
 
 
    ethereum                  6.41 M
    
    total                    6.41 M

**Comment by realdealshaman** [comment]
@Luna5-threshold Hi, thanks for the PR, should this be a listed along with/as a childProtocol to the KEEP Network listing? 
https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/keep.js

**Comment by Luna5-threshold** [comment]
Hello,

Thanks for the review.
The answer to this is no, the listing for Keep network is related to a
deprecated token, tBTC version 1.

A year ago, Keep Network and NuCypher network merged and the result is
Threshold Network, where there are different products being developed, and
one of them is tBTC version 2 (The one we need to list).

Thanks very much for double checking :)
Kind regards,
Luna5.

**Comment by ThresholdLady** [comment]
@realdealshaman it looks like TVL is showing zero for tBTC on the DefiLlama listing: (https://defillama.com/protocol/tbtc). Can you take a look at this and let me know how to get it fixed? The current MC of tBTC v2 is currently 15 Million+. https://www.coingecko.com/en/coins/tbtc

**Pull request merged**
