### PR TITLE
Eigenlayer TVL Goerli submission

### PR DESCRIPTION
**Pull request by Chris-Moller**
Please let us know if you have any questions.

**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
EigenLayer

##### Twitter Link:
https://twitter.com/eigenlayer

##### List of audit links if any:
https://consensys.net/diligence/audits/2023/03/eigenlabs-eigenlayer/
https://github.com/code-423n4/2023-04-eigenlayer/tree/main/audits/Sigma_Prime_Layr_Labs_Eigen_Layer_2_Security_Assessment_DRAFT.pdf

##### Website Link:
https://www.eigenlayer.xyz/

##### Logo (High resolution, will be shown with rounded borders):
EigenLayerLogo-A

##### Current TVL:
184,521.72 Goerli ETH 

##### Treasury Addresses (if the protocol has treasury)
N/A

##### Chain:
Goerli

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

##### Short Description (to be shown on DefiLlama):
EigenLayer is a protocol built on Ethereum that introduces restaking, a new primitive in cryptoeconomic security. This primitive enables the reuse of ETH on the consensus layer. Users that stake ETH natively or with a liquid staking token (LST) can opt-in to EigenLayer smart contracts to restake their ETH or LST and extend cryptoeconomic security to additional applications on the network to earn additional rewards. 

##### Token address and ticker if any:
N/A

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Restaking

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
N/A

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
The summation of LST balances deposited on EigenLayer and the total balance of solo validator ETH repointed to Eigenlayer.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/eigenlayer exports TVL: 
        
 
 
    goerli                    343.69 M
    
    total                    343.69 M

**Comment by g1nt0ki** [comment]
hi @Chris-Moller, thanks for the PR, the minor issue that I have with the PR is, your are counting goerli ETH as eth, this can be easily fixed.

The bigger issue is, the chain itself, Goerli is not an incentivzed testnet, the token is not really traded in any exchange, and very little liquidity on chain, so I checked with the team and they agreed that it is not a good idea to tracked project on goerli atm. We will revisit this if more users/protocols request for it.

**Comment by Chris-Moller** [comment]
Hi @g1nt0ki, thanks for taking a look. I submitted this because I saw DefiLllama is tracking Stargate on Goerli. Is there a reason you have chosen only to track Stargate on Goerli? Our TVL is comparable, and EigenLayer is [the largest holder of liquid staking tokens](https://restaking.nethermind.io/) on Goerli. If you potentially decide to reconsider, I'm happy to fix the Goerli ETH being counted as ETH issue. Thanks!

**Comment by g1nt0ki** [comment]
I would say ngmi did it partly as a jest. For stargate, we count the amount of ETH from mainnet bridged to Goerli as tvl, given the token distribution and way the chain is run and utter lack of liquidity for GETH makes me reluctant to add more projects. But like I said, if more projects/users ask for this, we would support/track the chain.

**Pull request closed without merging**
