### PR TITLE
fix: adding space for Argo Finance

### PR DESCRIPTION
**Pull request by 0xoats**
https://github.com/DefiLlama/DefiLlama-Adapters/pull/2867

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Whats the purpose of this PR?

**Comment by 0xoats** [comment]
@waynebruce0x sorry trying to add a space from ArgoFinance to Argo Finance
Screenshot 2022-06-03 at 12 20 16

**Comment by realdealshaman** [comment]
@0xoats Hi, I have added the space manually to reflect the correct name. If there's no other changes needed, can we close this PR?

**Comment by 0xoats** [comment]
@realdealshaman yes thank you so much!!

**Pull request closed without merging**
