### PR TITLE
Hectagon adapter update

### PR DESCRIPTION
**Pull request by junga-hectagon**
Thank you for listed my token. In the last pull request, @realdealshaman [commented](https://github.com/DefiLlama/DefiLlama-Adapters/pull/3984) that "all of the tokens being counted are in a treasury contract address, so they should be exported as treasury tvl". But here is the problem. The asset locked address is not only the treasury, because it include dao's assets and community reward assets. And when we checked this pull request created by klima DAO [Here](https://github.com/kargakis/DefiLlama-Adapters/blob/28a25dd742a26c1f97f7f31e090ebb8742dc6afa/projects/klima-dao/index.js) , their tvl calculated by total assets in treasury and dao wallet. So i think my pull request legit.

So could you please approve for my pull request.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/hectagon exports TVL: 
        
 
 
    bsc                       1.03 M
    
    total                    1.03 M

**Comment by g1nt0ki** [comment]
@junga-hectagon I am thinking of closing this in favor of https://github.com/DefiLlama/DefiLlama-Adapters/pull/4028
not sure why native tokens in treasury were counted in the first place, we dont do it for other treasuries. 
Is your code forked from ohm?

**Comment by llamatester** [comment]
The adapter at projects/hectagon exports TVL: 
        
 
 
    bsc                       507.11 k
    
    total                    507.11 k

**Comment by junga-hectagon** [comment]
> The adapter at projects/hectagon exports TVL:
> 
> ```
> bsc                       507.11 k
> 
> total                    507.11 k 
> ```

Fisrt Hectagon treasury doesn't like Olympus. Hectagon treasury contains community reward pool and protocol dao asset (include native token). But it's ok, i've remove counted native token in treasury from total value lock. Could you please check the files change one more time.

**Comment by g1nt0ki** [comment]
@junga-hectagon check https://github.com/DefiLlama/DefiLlama-Adapters/pull/4028#issuecomment-1259145618

it is identical to yours except staking is exported separately

"Hectagon treasury contains community reward pool" does this mean the users can withdraw BUSD from the treasury at some point?

**Pull request closed without merging**
