### PR TITLE
Refactor `defisaver.js`

### PR DESCRIPTION
**Pull request by Cussone**
DeFi Saver is [sunsetting the legacy automation system](https://twitter.com/DeFiSaver/status/1701248327751242101), hence I am updating the adapter to track data from our newer strategies automation system.

Tested everything, and just one thing is not working - there is no L2 block, it's returning undefined when getting TVL for Arbitrum/Optimism?

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/defisaver.js: 
        
 
  
    
    
    SyntaxError: Unexpected token < in JSON at position 0
    Truncated error stack:
    
        at JSON.parse (<anonymous>)
        at async tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/defisaver.js:13:16)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:53:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:149:9
        at async Promise.all (index 0)

**Comment by g1nt0ki** [comment]
hi @Cussone thanks for the PR, I refactored it a bit here, correct block number is passed now, it still fails for ARB: https://github.com/DefiLlama/DefiLlama-Adapters/pull/8320

**Comment by Cussone** [comment]
Hey @g1nt0ki, thank you for checking that. The latest entry was missing on our side, it should work now.

**Comment by llamatester** [comment]
The adapter at projects/defisaver.js exports TVL: 
        
 
 
    ethereum                  400.53 M
    optimism                  818.22 k
    arbitrum                  6.59 M
    
    total                    407.94 M

**Comment by llamatester** [comment]
The adapter at projects/defisaver.js exports TVL: 
        
 
 
    optimism                  818.29 k
    arbitrum                  6.59 M
    ethereum                  400.50 M
    
    total                    407.91 M

**Comment by g1nt0ki** [comment]
thanks for the PR, and setting up the server on your side

**Comment by g1nt0ki** [comment]
hi @Cussone the endpoint is down now?

**Comment by Cussone** [comment]
@g1nt0ki It was, we fixed it. Can you please backfill TVL? We currently have data from June 1st, 2023.

**Comment by g1nt0ki** [comment]
@Cussone I have started the refill script. it should reflect in the UI in few hours.

**Pull request merged**
