### PR TITLE
Add adapter for Edgevana

### PR DESCRIPTION
**Pull request by kaplanmaxe**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama): 

Edgevana

##### Twitter Link: 

https://twitter.com/edgevana

##### List of audit links if any:

https://spl.solana.com/stake-pool#security-audits

##### Website Link: 

https://www.edgevana.com/

##### Logo (High resolution, will be shown with rounded borders): 

https://srv.edgevana.com/img/edgesol.png

##### Current TVL: 

107.60 SOL

##### Chain: 

Solana

##### Short Description (to be shown on DefiLlama):

Liquid Staking solution on Solana, powered by Edgevana

##### Token address and ticker if any:

Token: edge86g9cVz87xcpKpy3J77vbp4wYd9idEV562CCntt
Ticker: edgeSOL

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Liquid Staking

##### forkedFrom (Does your project originate from another project):

SPL Stake Pool

##### methodology (what is being counted as tvl, how is tvl being calculated):

TVL is based on total minted edgeSOL token, which represents the underlying SOL in the stake pool

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/edgevana: 
        
 
  
    
    
    PromisePoolError: Request failed with status code 502
    Truncated error stack:
        at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by kaplanmaxe** [comment]
Hi, I was testing locally and was getting those errors as well. They appear to be coming from cloudflare though and not to do with the code here. Any idea on how I can get past that?

**Comment by g1nt0ki** [comment]
@kaplanmaxe I think our pricing server had bit of an issue, is fine now. is there some way to query amount of SOL staked on chain? I dont see edgeSOL on coingecko, so dont know how to price it

**Comment by llamatester** [comment]
The adapter at projects/edgevana exports TVL: 
        
 
 
    solana                    12.07 k
    
    total                    12.07 k

**Comment by kaplanmaxe** [comment]
Hey @g1nt0ki now that I was able to run it locally, I changed the methodology which I actually think is far more fair (only tracks deposits into the pool itself), and the PR runs as expected without having to hit coingecko (WIP). Let me know if that works!

**Comment by g1nt0ki** [comment]
Looks good, thanks

**Pull request merged**
