### PR TITLE
Baseline Protocol Adapter

### PR DESCRIPTION
**Pull request by brightiron**
Adapter for Baseline Protocol on Blast. 

Please see associated PR: https://github.com/DefiLlama/defillama-server/pull/6064 for listing information in-lieu of detail form in this PR. 

Please note. The Blast ERC-20 YES needs to have a price feed setup by the defillama team.
https://blastscan.io/address/0x20fE91f17ec9080E3caC2d688b4EcB48C5aC3a9C . 

Price can be derived from this univ3 thruster pool: https://blastscan.io/address/0x1d16788b97eDB7d9a6aE66D5C5C16469037Faa00

Thanks frens!

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/baseline exports TVL: 
        
 
 
    blast                     10.21 M
    
    total                    10.21 M

**Comment by g1nt0ki** [comment]
hi @brightiron thanks for the PR, I am not sure if we should count $YES tokens as tvl since it is sort of issued via your platform. 

Regarding counting WETH, I would prefer if we count only the part belonging to your protocol instead of the all WETH in thruster pool, main reason for this is, though unlikely, other can provide liquidity on thruster pool, right?

**Comment by llamatester** [comment]
The adapter at projects/baseline exports TVL: 
        
 
 
    blast                     30.37 M
    
    total                    30.37 M

**Comment by brightiron** [comment]
thanks @g1nt0ki ! 

I agree w/ your assessment on counting wETH . that was my oversight. I updated the latest commit to include only baseline contract managed LP positions. 

On the first question around $YES tokens, given we are POL, do you have any recommendations on how to best represent this if it can't be inside of TVL?

**Comment by 0xngmi** [comment]
From my understanding of the protocol, all the YES in the pool are just coins that have not yet been issued (they get issued when sold) so I wouldn't count any of it.

Also need to add the doublecounted tag since it's doublecounted within thruster tvl.

**Comment by llamatester** [comment]
The adapter at projects/baseline exports TVL: 
        
 
 
    blast                     25.59 M
    
    total                    25.59 M

**Comment by llamatester** [comment]
The adapter at projects/baseline exports TVL: 
        
 
 
    blast-borrowed            22.38 M
    blast                     25.80 M
    borrowed                  22.38 M
    
    total                    25.80 M

**Comment by brightiron** [comment]
> From my understanding of the protocol, all the YES in the pool are just coins that have not yet been issued (they get issued when sold) so I wouldn't count any of it.
> 
> Also need to add the doublecounted tag since it's doublecounted within thruster tvl.

ty for the feedback. added the doublecounting flag. I also removed YES from TVL calc for now.

Since we offer a credit facility I instead added tracking for borrows on reserves and track that under borrowed.

Please feel free to make any additional modifications here to help get a v1 listed. 

thx frens

**Comment by llamatester** [comment]
The adapter at projects/baseline exports TVL: 
        
 
 
    blast-borrowed            22.41 M
    blast                     25.84 M
    borrowed                  22.41 M
    
    total                    25.84 M

**Comment by llamatester** [comment]
The adapter at projects/baseline exports TVL: 
        
 
 
    blast                     31.01 M
    blast-borrowed            29.79 M
    borrowed                  29.79 M
    
    total                    31.01 M

**Comment by g1nt0ki** [comment]
@brightiron thanks for the PR, made a minor code change.

**Comment by fullyallocated** [comment]
Hey guys, there's a function baseline.TotalBAssetCollateral() that counts the total $YES in the system collateralized to borrow ETH. 

This is external $YES not owned by the protocol that factors into circulating supply, it's really really important for people to factor this in because it helps show systemic leverage.

E.g.  
Circulating Supply:       14,149,728.32579 YES
bAssets Collateralized: 9,007,743.47849 YES

There's ~50M worth of $YES that doesn't belong to the protocol in the system. This should be counted as TVL on top of the ETH-side POL.

 I agree that the $YES POL inside the pool should not be counted as TVL.

**Comment by basehunter69** [comment]
@g1nt0ki @0xngmi agree with Fully here. It should by default be included in TVL. Could be another option to add "Collateralized" under TVL

image

**Pull request merged**
