### PR TITLE
Update Mycelium

### PR DESCRIPTION
**Pull request by rogue-hacker**
Updated protocol info in https://github.com/DefiLlama/defillama-server/pull/1126

##### Name (to be shown on DefiLlama):

**Parent protocol:** Mycelium
1. Mycelium Perpetual Swaps
2. Mycelium Perpetual Pools
3. Mycelium Staking

##### Twitter Link:

https://twitter.com/mycelium_xyz

##### Website Link:

https://mycelium.xyz/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

https://icons.llama.fi/mycelium.jpg

##### Current TVL:

Combined TVL of ~$23 million USD (Swaps, Pools, and Staking) 

##### Chain:

Arbitrum

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

`mycelium`

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

`21437`

##### Short Description (to be shown on DefiLlama):

Previously Tracer DAO. Trade with liquidity, leverage and low fees.

##### Token address and ticker if any:

MYC 
`0xC74fE4c715510Ec2F8C61d70D397B32043F55Abe`

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Derivatives

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

Chainlink

##### forkedFrom (Does your project originate from another project):

Mycelium Perpetual Swaps is forked from GMX

##### methodology (what is being counted as tvl, how is tvl being calculated):

Pools: We count liquidity on the Leveraged Pools through PoolFactory contract.
Swaps: We count liquidity in Perpetual Swaps based on the value of tokens in the MLP pool.
Staking: We count liquidity in Staking based on the amount of MYC staked in the LentMyc contract.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/mycelium-pools exports TVL: 
        
 
 
    arbitrum                  1.52 M
    
    total                    1.52 M

**Comment by llamatester** [comment]
The adapter at projects/mycelium-staking exports TVL: 
        
 
 
    arbitrum                  2.31 M
    
    total                    2.31 M

**Comment by llamatester** [comment]
The adapter at projects/mycelium-swaps exports TVL: 
        
 
 
    arbitrum                  18.99 M
    
    total                    18.99 M

**Comment by g1nt0ki** [comment]
@rogue-hacker sorry, we cant count gov token staking as tvl, I have added it under staking here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/4372

@Define101 will update the list details like name, url and description on the server repo. Closing this one

**Pull request closed without merging**
