### PR TITLE
Update Kashi-TVL adaptor

### PR DESCRIPTION
**Pull request by HHK-ETH**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
Update of the Kashi adaptor to display only Kashi TVL and not Bentobox + Kashi TVL.

Since Kashi is a money market, the methodology used is the same as the AAVE one:

=> TVL of Sushiswap Kashi lending consists of the tokens available to borrow and the ones used as collateral, tokens borrowed are not counted to avoid inflating TVL through cycled lending.

The data fetched is 100 block late on current block as subgraphs used are sometime late by few minutes which cause the tests to throw an error.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/sushiswap-kashi: 
        
 
  
    
    
    Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="toAmount(address,uint256,bool)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.6.4)
    Truncated error stack:
        at Interface.decodeFunctionResult (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/abi/lib/interface.js:388:23)
        at runMicrotasks (<anonymous>)

**Comment by HHK-ETH** [comment]
I don't seem to be able to recreate this error in local.

node test.js projects/sushiswap-kashi/index.js is running as intented with no error.

**Comment by realdealshaman** [comment]
@HHK-ETH you are right, there is no error when running the code, however this is what is returned as tvl:
image

Is this correct? If so, I can merge, thanks in advance

**Comment by HHK-ETH** [comment]
Hey! Yes it's the correct TVL, thanks!
It's really far from current numbers since previous adaptor was taking into account bentobox TVL which we don't want anymore.

**Pull request merged**
