### PR TITLE
Add unfederaReserve adapter

### PR DESCRIPTION
**Pull request by batinhell**
##### Twitter Link:
https://twitter.com/Unfederalreser1

##### List of audit links if any:
https://lending-docs.unfederalreserve.com/docs/security/

##### Website Link:
https://unfederalreserve.com

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://raw.githubusercontent.com/UnFederalReserve/token-lists/main/img/logo_eRSDL.png

##### Current TVL:
https://lending.unfederalreserve.com/markets

##### Chain:
Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
unfederalreserve

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
7553

##### Description/bio (to be shown on DefiLlama):
unFederalReserve is a banking SaaS company built on blockchain technology. Our banking products are designed for smaller U.S. Treasury chartered banks and non-bank lenders in need of greater liquidity without sacrificing security or compliance.

##### Token address and ticker if any:
https://etherscan.io/token/0x5218e472cfcfe0b64a064f055b43b4cdc9efd3a6

##### Category (Yield/Dexes/Lending/Minting):
Lending

### CODE REVIEW

**Comment by 0xngmi** [comment]
noticed that this seems to be a fork of compound, in that case it's easier for us to use some other code to keep all of our data sources on-chain

**Comment by 0xngmi** [comment]
Wrote a shorter version that doesn't rely on your api: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/unfederalreserve/index.js

**Comment by 0xngmi** [comment]
listed on https://defillama.com/protocol/unfederalreserve

**Comment by WETEE5296p** [comment]
คับ

**Pull request closed without merging**
