### PR TITLE
Update Ondo and add Flux Finance

### PR DESCRIPTION
**Pull request by nickplace**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Flux Finance

##### Twitter Link:
https://twitter.com/FluxDeFi

##### Website Link:
https://fluxfinance.com

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
flux-avatar-white

##### Current TVL:
$36.47M (including OUSG which Coingecko is not reporting price about)

##### Chain:
Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
OUSG: https://www.coingecko.com/en/coins/ousg (Not related to flux)

##### Short Description (to be shown on DefiLlama):
Flux Finance is a decentralized lending platform supporting permissioned assets.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### forkedFrom (Does your project originate from another project):
Compound v2

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/ondofinance exports TVL: 
        
 
 
    ethereum                  0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/fluxfinance exports TVL: 
        
 
 
    ethereum-borrowed         29.59 M
    ethereum                  3.99 M
    borrowed                  29.59 M
    
    total                    3.99 M

**Comment by realdealshaman** [comment]
@nickplace Hi, I noticed that the OUSG token is listed on both Ondo Finance and Flux Finance. I just want to make sure we're not double-counting here, so could you confirm how these two protocols are related(same team maybe)? Should they be listed together as paretProtocol, child/sub protocol format? Thanks!

**Comment by nickplace** [comment]
@realdealshaman 
1) I can't figure out how to get OUSG's price reported for either protocol. Do you have suggestions?
2) Ondo mints the OUSG from deposited USDC and Flux accepts it as collateral. The USDC is used to buy RWAs so the liquidity is off-chain. That's why we want to report OUSG's total supply as TVL for ondo.
3) Ondo and Flux will not be parent/child protocol. They are separate entities

**Pull request merged**
