### PR TITLE
Add ReHold Adapter

### PR DESCRIPTION
**Pull request by bifot**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

ReHold

##### Twitter Link:

https://twitter.com/rehold_io

##### List of audit links if any:

WIP.

##### Website Link:

https://rehold.io

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

https://rehold.io/android-chrome-512x512.png

##### Current TVL:

```
--- bsc ---
USDT                      150.47 k
Total: 150.47 k 

--- tvl ---
USDT                      150.47 k
Total: 150.47 k 

------ TVL ------
bsc                       150.47 k

total                    150.47 k 
```

##### Chain:

BSC

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

N/A

##### Short Description (to be shown on DefiLlama):

ReHold is an innovative platform that offers the first Dual investments in DeFi. High APRs are accessible due to Uniswap V3 Liquidity Pools with an effective price range for concentrated liquidity.

##### Token address and ticker if any:

N/A

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Yield

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

N/A

##### forkedFrom (Does your project originate from another project):

N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):

TVL calculates as balances of users' tokens on our Vault. https://bscscan.com/address/0xd476ce848c61650e3051f7571f3ae437fe9a32e0

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/rehold.js exports TVL: 
        
 
 
    bsc                       150.44 k
    
    total                    150.44 k

**Comment by llamatester** [comment]
The adapter at projects/rehold exports TVL: 
        
 
 
    bsc                       152.01 k
    
    total                    152.01 k

**Comment by bifot** [comment]
How can I use a dynamic way to load tokens for my Vault smart-contract? We're adding tokens daily and should I create PRs every time to add tokens contract or can I use fetch endpoint? @g1nt0ki

**Comment by g1nt0ki** [comment]
@bifot fixed it here so it is dynamic: https://github.com/DefiLlama/DefiLlama-Adapters/commit/3a167a0e092f15a23397148b413112bb90587c85

**Comment by bifot** [comment]
@g1nt0ki thank you! awesome

**Pull request merged**
