### PR TITLE
Crayon Protocol adapter

### PR DESCRIPTION
**Pull request by c-protocol-team**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Crayon Protocol

##### Twitter Link:
https://twitter.com/c_protocol76151

##### Website Link:
https://xcrayon.network/

##### Logo (High resolution, will be shown with rounded borders):
https://xcrayon.network/img/c-protocol.png

##### Current TVL:
0

##### Chain:
Arbitrum

##### Short Description (to be shown on DefiLlama):
Crayon Protocol is a lending for financing and leveraging protocol for EVM-compatible blockchains.

##### Token address and ticker if any:
ticker: XCRAY
https://arbiscan.io/address/0x2dEbe92EdBbA661362fC8BF062551E7c993ACb02

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is the total value of base coin available for lending and collateral deposited. Borrowed base coin is not included.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/c-protocol

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@c-protocol-team each desk can hold only one type of token right?

**Comment by c-protocol-team** [comment]
> @c-protocol-team each desk can hold only one type of token right?

Each desk holds a base coin, that is available to borrow, and the tokens that are posted by borrowers as collateral.

**Comment by c-protocol-team** [comment]
> I have refactored your code here: #7677
> 
> I would leave it open till there is some tvl, can you post a message once the product is in production?

The product is already deployed in production on Arbitrum.

Your refactored code excludes collateral, i.e., the tokens posted as collateral, from TVL. The tokens array in the original code contained all the tokens that could be posted as collateral or used as base coin on any of the currently deployed desks.

in the original code: TVL = available_base_coin + total_collateral_value

in the refactored code: TVL = available_base_coin

**Comment by g1nt0ki** [comment]
got, will close the other PR, we still cant list projects with 0 tvl, let me know when there is some tvl

**Comment by c-protocol-team** [comment]
Will do. Thank you.

**Comment by g1nt0ki** [comment]
hi, I am closing this PR for now, can you re-open/put up a new PR when there is some tvl?

**Comment by c-protocol-team** [comment]
Yes, we'll do that. Thank you.

**Comment by c-protocol-team** [comment]
Hi, Is there a minimum TVL has to meet or does it just have to be non-zero? Cheers.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by g1nt0ki** [comment]
Non zero is enough

**Pull request closed without merging**
