### PR TITLE
add nft pool

### PR DESCRIPTION
**Pull request by lucas7788**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/wing.js: 
        
 
  
    
    
    Error: 
        Unknown chain(s): nft_pool
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file

**Comment by realdealshaman** [comment]
Hey, @lucas7788 the tvl of the new nft pool needs to be combined with the regular tvl of the chain that it lives on

**Comment by lucas7788** [comment]
> Hey, @lucas7788 the tvl of the new nft pool needs to be combined with the regular tvl of the chain that it lives on

NFT pool is on the Ethereum chain. Do you mean that the TVL of NFT pool should be put together with the wing flash pool on the Ethereum chain?

**Comment by llamatester** [comment]
Error while running adapter at projects/wing.js: 
        
 
  
    
    
    Error: invalid BigNumber string (argument="value", value="NaN", code=INVALID_ARGUMENT, version=bignumber/5.6.2)
    Truncated error stack:
        at Function.BigNumber.from (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/bignumber/lib/bignumber.js:199:27)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:335:16
        at Array.forEach (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:329:28)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:341:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:60:30)

**Comment by lucas7788** [comment]
> Error while running adapter at projects/wing.js:
> 
> ```
> Error: invalid BigNumber string (argument="value", value="NaN", code=INVALID_ARGUMENT, version=bignumber/5.6.2)
> Truncated error stack:
>     at Function.BigNumber.from (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/bignumber/lib/bignumber.js:199:27)
>     at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:335:16
>     at Array.forEach (<anonymous>)
>     at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:329:28)
>     at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:341:3)
>     at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:60:30)
> ```

I have solved this problem, Please take a look again.

**Comment by llamatester** [comment]
The adapter at projects/wing.js exports TVL: 
        
 
 
    ontology-staking          772.07 k
    ontology                  26.79 M
    ethereum                  1.87 M
    ontology-borrowed         30.09 M
    okexchain-staking         11.28 k
    ethereum-borrowed         1.16 M
    bsc-staking               195.23 k
    ethereum-staking          55.80 k
    okexchain-borrowed        358.26 k
    bsc                       6.05 M
    okexchain                 247.90 k
    bsc-borrowed              14.36 M
    ontology_evm-borrowed     8.69 M
    ontology_evm              2.66 M
    ontology_evm-staking      136.43 k
    nft_pool                  425.10 k
    nft_pool-borrowed         371.61 k
    nft_pool-staking          0
    staking                   1.17 M
    borrowed                  55.03 M
    
    total                    38.05 M

**Comment by realdealshaman** [comment]
The way this is being exported, nft pool is being considered a chain. If it lives on Ethereum, it should be counted on ethereum

**Comment by ubunt2022** [comment]
> The way this is being exported, nft pool is being considered a chain. If it lives on Ethereum, it should be counted on ethereum

OK, I will counted on ethereum, Please take a look again.

**Comment by lucas7788** [comment]
> The way this is being exported, nft pool is being considered a chain. If it lives on Ethereum, it should be counted on ethereum

Ok, I will count on ethereum, Please take a look again.

**Pull request merged**
