### PR TITLE
Add Echo Bridge Adapter

### PR DESCRIPTION
**Pull request by Efrain9502**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Echo Bridge

##### Twitter Link:
https://x.com/EchoProtocol_

##### List of audit links if any:
MoveBit

##### Website Link:
https://www.echo-protocol.xyz/

##### Logo (High resolution, will be shown with rounded borders):
https://www.echo-protocol.xyz/images/echo.png

##### Current TVL:
$46696000

##### Chain:
Aptos

##### Short Description (to be shown on DefiLlama):
Bridge BTC assets, restaking, earn interest & borrow on Move

##### Token address and ticker if any:
abtc: 0x1::coin::CoinStore<0x4e1854f6d332c9525e258fb6e66f84b6af8aba687bbcb832a24768c4e175feec::abtc::ABTC>

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Bridge

##### methodology (what is being counted as tvl, how is tvl being calculated):
In `echo-bridge/index.js`, the quantity of ABTC is obtained through `aptos.tvl`, and its ratio to BTC is 1:1.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/echo-bridge exports TVL: 
        
 
 
    aptos                     0
    
    total                    0

**Comment by Efrain9502** [comment]
> The adapter at projects/echo-bridge exports TVL:projects/echo-bridge 的适配器导出 TVL：
> 
> ```
> aptos                     0
> 
> total                    0 
> ```



> The adapter at projects/echo-bridge exports TVL:
> 
> ```
> aptos                     0
> 
> total                    0 
> ```

In `echo-bridge/index.js`, an object will be exported, and the quantity needs to be obtained through `aptos.tvl`.

**Comment by g1nt0ki** [comment]
@Efrain9502 thanks for the PR, but can you share the BTC address where bitcoins are locked when they are minted on aptos side?

**Comment by Efrain9502** [comment]
> @Efrain9502 thanks for the PR, but can you share the BTC address where bitcoins are locked when they are minted on aptos side?

The tokens are locked on the B2 network. The token contract address is 0x796e4D53067FF374B89b2Ac101ce0c1f72ccaAc2, and the lock-up contract address is 0x5b1399B8b97fBC3601D8B60Cc0F535844C411Bd5.

**Comment by g1nt0ki** [comment]
thanks, I have added it

**Pull request closed without merging**
