### PR TITLE
Add Shipyard Finance

### PR DESCRIPTION
**Pull request by LakefrontDevelopment**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Shipyard Finance 

##### Twitter Link:
https://twitter.com/ShipyardFinance 

##### List of audit links if any:
https://www.certik.com/projects/lakefront-finance  

##### Website Link:
https://www.shipyard.finance/ 

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://dev.shipyard.finance/static/media/shipyard-header-no-text.0374aad0.svg  

##### Current TVL:
 150.28 k

##### Chain:
Arbitrum, Avalanche, and Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
 N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
 N/A

##### Short Description (to be shown on DefiLlama):
Shipyard aims to offer diversified barebones yield optimization to crypto native investors through pooled investment vehicles that distribute the cost of operating yield generation strategies (rebalancing, compounding, swapping, etc.) between the participants, resulting in higher yields and less management than an individual investment. 

##### Token address and ticker if any:
N/A

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield Aggregator

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Coingecko, Uniswap 

##### forkedFrom (Does your project originate from another project):
Beefy Finance

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is the sum of all funds deposited across our vault strategies

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/shipyard-finance exports TVL: 
        
 
 
    ethereum                  50.01 k
    arbitrum                  50.06 k
    avax                      50.15 k
    
    total                    150.22 k

**Comment by vrtnd** [comment]
Hi, please rewrite adapter using rpc calls instead of apiю

**Comment by LakefrontDevelopment** [comment]
@vrtnd thanks for your help.

We based our implementation on other existing projects, do we really need to use RPC? 

If yes, could you please point us to a simple implementation?

**Comment by vrtnd** [comment]
I agree about beefy and similar projects, but for new listing it is required to use rpc calls to make adapters more transparent.

**Comment by LakefrontDevelopment** [comment]
@vrtnd could you please review our latest commit?

We're now obtaining the vault balances via RPC and the tokens' price using your API.

**Comment by llamatester** [comment]
The adapter at projects/shipyard-finance exports TVL: 
        
 
 
    avax                      51.21 k
    arbitrum                  49.95 k
    ethereum                  49.50 k
    
    total                    150.66 k

**Comment by vrtnd** [comment]
Everything is okay, last change please add `doublecounted: true` since your protocols is depositing tokens in another protocol

**Comment by llamatester** [comment]
The adapter at projects/shipyard-finance exports TVL: 
        
 
 
    arbitrum                  50.16 k
    ethereum                  49.54 k
    avax                      51.26 k
    
    total                    150.97 k

**Comment by LakefrontDevelopment** [comment]
@vrtnd quick question, would it be acceptable to get the vault addresses dynamically from our API?

That way we wouldn't have to update if whenever we add new vaults.

We'd continue doing the calculations using RPC and your API.

**Comment by vrtnd** [comment]
Yes, sure u can use api for dynamic lists of addresses

**Pull request merged**
