### PR TITLE
Adding Roci.fi (#1)

### PR DESCRIPTION
**Pull request by pavel-filippov-lw**
Adding Roci.fi

##### Name (to be shown on DefiLlama):

RociFi

##### Twitter Link:

https://twitter.com/rocifi

##### List of audit links if any:

https://github.com/rociFi/docs

##### Website Link:

https://roci.fi/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

On black background: https://drive.google.com/file/d/1G0jDPN-oGf4Z9sJxlfQYlrKXljhaCvzB/view?usp=sharing
On white background: https://drive.google.com/file/d/1M-cyXbfVQBxqfKhOqTuESEz8S8EI5Ks2/view?usp=sharing

##### Current TVL:

101k 

##### Chain:

Polygon

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

n/a

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

n/a

##### Short Description (to be shown on DefiLlama):

Under-collateralized lending protocol

##### Token address and ticker if any:

n/a

##### Category (full list at https://defillama.com/categories) \*Please choose only one:

Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

n/a

##### forkedFrom (Does your project originate from another project):

n/a

##### methodology (what is being counted as tvl, how is tvl being calculated):

Total USDC deposited in pools and total deposited collateral.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/rocifiv1 exports TVL: 
        
 
 
    polygon                   102.20 k
    
    total                    102.20 k

**Comment by realdealshaman** [comment]
Hey @pavel-filippov-lw , thanks for the PR. Can we also calculate the borrowed amount and export as borrowed?

**Comment by pavel-filippov-lw** [comment]
@realdealshaman Yes, sure. I'll make a separate PR for that.

**Comment by g1nt0ki** [comment]
@pavel-filippov-lw I have added borrowed here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/3814/files, can you review just to be safe.

Also, is there some way to fetch the pool list via on chain calls?

**Comment by pavel-filippov-lw** [comment]
@g1nt0ki looks good. `poolValue` is exactly the right variable to use in this case. Sadly there is no on-chain discovery for pools in v1, we'll add it in v2.

**Pull request merged**
