### PR TITLE
nirvana v2 adapter

### PR DESCRIPTION
**Pull request by enoch-roots**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Nirvana v2

##### Twitter Link:
https://x.com/nirvana_fi

##### List of audit links if any:
https://scalebit.xyz/reports/20241216-Nirvana-Smart-Contract-Final-Audit-Report.pdf

##### Website Link:
https://www.nirvana.finance/

##### Logo (High resolution, will be shown with rounded borders):
https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/ANAxByE6G2WjFp7A4NqtWYXb3mgruyzZYg3spfxe6Lbo/logo.png

##### Current TVL:
5.2M

##### Chain:
Solana

##### Short Description (to be shown on DefiLlama):
Anchored by an algorithm-owned reserve, the Nirvana platform guarantees a floor price for ANA that permanently ascends with demand, while NIRV provides zero-risk credit.  Together the pair harmonizes risk with reward, and transforms digital assets into durable wealth.

##### Token address and ticker if any:
5DkzT65YJvCsZcot9L6qwkJnsBCPmKHjJz3QU7t7QeRW

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL - Total value in the Nirvana v2 treasury. 
Staking - Total value of ANA tokens locked for staking and collateral.

### CODE REVIEW

**Comment by llamabutler** [comment]
The adapter at projects/nirvana-v2 exports TVL: 
        
 
 
    solana-staking            7.47 M
    staking                   7.47 M
    solana                    5.26 M
    
    total                    5.26 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
hi @enoch-roots thanks for the PR, can you compute the tvl on chain? 
https://github.com/DefiLlama/DefiLlama-Adapters/discussions/432

**Comment by enoch-roots** [comment]
We can compute the amount of tokens, but the issue is to put in terms of USD requires our SDK to compute for the token.  It’s a proprietary AMM that we have created which only computes on this token with a specialized price curve

Eventually we will have other price feeds, but they will likely have to use this API as an oracle anyways under the hood, and so that becomes circular regardless.  The price is deterministic by supply minted

These are the docs for reference and we do have audit
https://docs.nirvana.finance/introduction

I'm also on discord as enochroot in the adapter-requests channel for quicker communication

**Comment by g1nt0ki** [comment]
hi, I dont think we should track staked ANA even under staking as the tokens backing it are already counted towards tvl. 

if you share treasury contract address, I can update code to count external assets in it as tvl.

**Comment by enoch-roots** [comment]
ok @g1nt0ki thanks very much for the info.  These are the two token accounts that hold the market liquidity, I think this is the best we could provide for fully on chain accounting that doesn't include ANA market cap or staked ANA for tvl.   The price of NIRV is pegged to USDC

 USDC vault: FhTJEGXVwj4M6NQ1tPu9jgDZUXWQ9w2hP89ebZHwrJPS
 NIRV vault: EkwPHXXZNAguNoxeftVRXThCQJfD6EaG852pDsYLs2eB

**Comment by g1nt0ki** [comment]
@enoch-roots sorry, we cant include NIRV either, it is backed by ANA right?

**Comment by llamabutler** [comment]
The adapter at projects/nirvana-v2 exports TVL: 
        
 
 
    solana                    2.70 M
    
    total                    2.70 M

**Pull request merged**
