### PR TITLE
add MetaTdex

### PR DESCRIPTION
**Pull request by phpwufeng**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
MetaTdex

##### Twitter Link:
https://twitter.com/MetaTdex

##### Website Link:
 https://www.metatdex.com/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
圆型logo

##### Current TVL:
heco                      2.37 B
bsc                       577.49 M
total                    2.95 B 

##### Chain:
BSC、HECO 

##### Short Description (to be shown on DefiLlama):
MetaTdex is a decentralized order matching trading platform 

##### Token address and ticker if any:
0x445cC9518cF7bc7386A2e3aaF510650b0FB05f5F（BSC） 
0x86040C76AAE5CBB322364CAF8820b0E8902e97E5（HECO）

##### Category (full list at https://defillama.com/categories) *Please choose only one:
DEX

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL: MetaTdex platform cumulative transaction volume
TVL calculation: MetaTdex platform cumulative transaction volume = token price * transaction volume

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@phpwufeng can you please compute the tvl using on chain data, also we consider the value of tokens locked in a protocol as tvl not total transaction volume

**Comment by phpwufeng** [comment]
> @phpwufeng can you please compute the tvl using on chain data, also we consider the value of tokens locked in a protocol as tvl not total transaction volume
ok @g1nt0ki
Current TVL:
------ TVL ------
bsc                       65.19 k
heco                      643.39 k
total                    708.59 k 

methodology (what is being counted as tvl, how is tvl being calculated):
TVL: Total Locked Value of MetaTdex Trading Orders
Calculation method: quantity of all entrusted orders * corresponding entrusted price

**Comment by g1nt0ki** [comment]
@phpwufeng sorry for late reply, is the api you are using open source, will users be able to verify the tvl by going through the code. Else, can you please convert the adapter to be on chain we have several helper functions to assist you, I am happy to help with rewrite if you provide me with the details

**Comment by phpwufeng** [comment]
> 
@g1nt0ki Thank you for your reply,the user can verify tvl(http://public.tdex.cz/get_tvl) through our interface documentation, and then go to the chain to check the commission record through the wallet address

**Comment by g1nt0ki** [comment]
hi @phpwufeng , would I be correct in assuming that user funds are kept in these contracts till order succeeds or is cancelled? 

https://www.bscscan.com/address/0x4bc90496ea2682c6474b2b81ef6b573068e4b1f7
https://www.hecoinfo.com/en-us/address/0x09a28712208bf913b2e79eab446594c9fab2f37c?tab=Contract

**Comment by phpwufeng** [comment]
> hi @phpwufeng , would I be correct in assuming that user funds are kept in these contracts till order succeeds or is cancelled?
> 
> https://www.bscscan.com/address/0x4bc90496ea2682c6474b2b81ef6b573068e4b1f7 https://www.hecoinfo.com/en-us/address/0x09a28712208bf913b2e79eab446594c9fab2f37c?tab=Contract

@g1nt0ki  That's right. If the order is successful or cancelled, the user funds in the contract will be reduced.

**Comment by llamatester** [comment]
The adapter at projects/metatdex exports TVL: 
        
 
 
    heco                      788.75 k
    bsc                       72.87 k
    
    total                    861.61 k

**Comment by phpwufeng** [comment]
Hello , @g1nt0ki , I’m glad to know that we’ve been listed on DeFi section of the project. May I ask why it wasn’t included in the DEX section?

**Comment by g1nt0ki** [comment]
dex volume is a different adapter: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/volumes/README.md 

do you have a api for fetching volume? if you share it here we can add it

**Comment by phpwufeng** [comment]
> dex volume is a different adapter: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/volumes/README.md
> 
> do you have a api for fetching volume? if you share it here we can add it

@g1nt0ki 
Thank you very much, here is the api
api for volumes
Heco: http://www.public_tdex.com/volumes?chain_id=56
Bsc: http://www.public_tdex.com/volumes?chain_id=128
api Documentation
http://www.public_tdex.com/get_volumes
pull requests record
https://github.com/DefiLlama/DefiLlama-Adapters/pull/4570

**Pull request merged**
