### PR TITLE
feat: add HELIX 

### PR DESCRIPTION
**Pull request by helix-integrations**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
HELIX

##### Twitter Link:
https://twitter.com/helix_finance

##### List of audit links if any:
https://helilabs.journey.io/p/helixaudit

##### Website Link:
https://helixfinance.io/

##### Logo (High resolution, will be shown with rounded borders):
Helix Logo (Icon with dark BG)

##### Current TVL:
3.5M USDC

##### Treasury Addresses (if the protocol has treasury) 
N.A

##### Chain: 
Ethereum

##### Short Description (to be shown on DefiLlama):
HELIX is an RWA protocol leveraging Big-Data and proprietary credit analytics to connect on-chain investors with uncorrelated and sustainable yields from real-world assets.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
RWA

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL for HELIX is recorded in the form of total outstanding loans across all HELIX RWA Deals at any point of time, which is basically total principal invested minus total principal repaid till date across all deals
TVL = Total Principal Invested - Total Principal Repaid

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/helix exports TVL: 
        
 
 
    ethereum                  0
    ethereum-borrowed         3.53 M
    borrowed                  3.53 M
    
    total                    0

**Comment by g1nt0ki** [comment]
@helix-integrations thanks for the PR, main thing I changed was, marking debt as borrowed instead of as tvl. This is in line with how we treat other borrowing protocols

**Comment by helix-integrations** [comment]
Thanks @g1nt0ki -- we just noticed that there's another project with name Helix; please suggest what to do in this case?

image

**Comment by g1nt0ki** [comment]
we have listed you as Helix finance: https://defillama.com/protocol/helix-finance

**Pull request merged**
