### PR TITLE
Tvl-v2

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/0xDAO exports TVL: 
        
 
 
    fantom                    516.09 k
    
    total                    516.09 k

**Comment by llamatester** [comment]
The adapter at projects/1beam exports TVL: 
        
 
 
    moonbeam                  2.41 k
    
    total                    2.41 k

**Comment by llamatester** [comment]
The adapter at projects/1inch.js exports TVL: 
        
 
 
    bsc                       611.26 k
    ethereum                  5.65 M
    
    total                    6.26 M

**Comment by llamatester** [comment]
The adapter at projects/1swap exports TVL: 
        
 
 
    moonriver                 19.86 k
    
    total                    19.86 k

**Comment by llamatester** [comment]
The adapter at projects/AnonSocial exports TVL: 
        
 
 
    base                      1.62 k
    
    total                    1.62 k

**Comment by llamatester** [comment]
The adapter at projects/CreampanFinance exports TVL: 
        
 
 
    cronos                    303.02 k
    
    total                    303.02 k

**Comment by llamatester** [comment]
Error while running adapter at projects/DropCopy: 
        
 
  
    
    
    AxiosError: Request failed with status code 429
    Truncated error stack:
        at settle (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/axios/dist/node/axios.cjs:1970:12)
        at IncomingMessage.emit (node:events:529:35)

**Comment by llamatester** [comment]
The adapter at projects/0xDAO exports TVL: 
        
 
 
    fantom                    532.85 k
    
    total                    532.85 k

**Comment by llamatester** [comment]
The adapter at projects/1beam exports TVL: 
        
 
 
    moonbeam                  2.43 k
    
    total                    2.43 k

**Comment by llamatester** [comment]
The adapter at projects/1inch.js exports TVL: 
        
 
 
    ethereum                  5.75 M
    bsc                       619.48 k
    
    total                    6.37 M

**Comment by llamatester** [comment]
The adapter at projects/1swap exports TVL: 
        
 
 
    moonriver                 19.82 k
    
    total                    19.82 k

**Comment by llamatester** [comment]
The adapter at projects/3a-dao exports TVL: 
        
 
 
    polygon                   142.12 k
    
    total                    142.12 k

**Comment by llamatester** [comment]
The adapter at projects/88mph exports TVL: 
        
 
 
    ethereum-staking          29.82 k
    avax                      127.49622442461151
    polygon                   44.30278051745781
    fantom                    2.77 k
    ethereum                  600.77 k
    staking                   29.82 k
    
    total                    603.71 k

**Comment by llamatester** [comment]
The adapter at projects/AnonSocial exports TVL: 
        
 
 
    base                      1.65 k
    
    total                    1.65 k

**Comment by llamatester** [comment]
The adapter at projects/ArchimedesFinance exports TVL: 
        
 
 
    ethereum                  1.88 M
    
    total                    1.88 M

**Comment by llamatester** [comment]
The adapter at projects/AxiaProtocol exports TVL: 
        
 
 
    ethereum                  0
    ethereum-staking          0
    ethereum-pool2            0
    polygon-staking           0
    polygon-pool2             0
    staking                   0
    pool2                     0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/BankofCronos-Loans exports TVL: 
        
 
 
    cronos                    645.6479999999999
    
    total                    645.6479999999999

**Comment by llamatester** [comment]
The adapter at projects/CofferCity exports TVL: 
        
 
 
    kava                      10.993443000000001
    
    total                    10.993443000000001

**Comment by llamatester** [comment]
The adapter at projects/CreampanFinance exports TVL: 
        
 
 
    cronos                    308.64 k
    
    total                    308.64 k

**Comment by llamatester** [comment]
The adapter at projects/DigiFT exports TVL: 
        
 
 
    ethereum                  2.56 M
    
    total                    2.56 M

**Comment by llamatester** [comment]
Error while running adapter at projects/DropCopy: 
        
 
  
    
    
    AxiosError: Request failed with status code 429
    Truncated error stack:
        at settle (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/axios/dist/node/axios.cjs:1970:12)
        at IncomingMessage.emit (node:events:529:35)

**Comment by 0xngmi** [comment]
gib 
gib

**Comment by llamatester** [comment]
The adapter at projects/0xDAO exports TVL: 
        
 
 
    fantom                    530.30 k
    
    total                    530.30 k

**Comment by llamatester** [comment]
The adapter at projects/1beam exports TVL: 
        
 
 
    moonbeam                  2.39 k
    
    total                    2.39 k

**Comment by llamatester** [comment]
The adapter at projects/1inch.js exports TVL: 
        
 
 
    ethereum                  5.86 M
    bsc                       628.15 k
    
    total                    6.49 M

**Comment by llamatester** [comment]
The adapter at projects/1swap exports TVL: 
        
 
 
    moonriver                 19.77 k
    
    total                    19.77 k

**Comment by llamatester** [comment]
The adapter at projects/3a-dao exports TVL: 
        
 
 
    polygon                   149.10 k
    
    total                    149.10 k

**Comment by llamatester** [comment]
The adapter at projects/88mph exports TVL: 
        
 
 
    ethereum-staking          33.16 k
    polygon                   44.60946002498184
    fantom                    2.74 k
    ethereum                  605.31 k
    avax                      127.6283650482979
    staking                   33.16 k
    
    total                    608.22 k

**Comment by llamatester** [comment]
The adapter at projects/AnonSocial exports TVL: 
        
 
 
    base                      1.70 k
    
    total                    1.70 k

**Comment by llamatester** [comment]
The adapter at projects/ArchimedesFinance exports TVL: 
        
 
 
    ethereum                  1.88 M
    
    total                    1.88 M

**Comment by llamatester** [comment]
The adapter at projects/AxiaProtocol exports TVL: 
        
 
 
    ethereum                  0
    polygon-staking           440.13004300464183
    ethereum-staking          861.3687750129974
    polygon-pool2             0
    ethereum-pool2            0
    staking                   1.30 k
    pool2                     0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/BankofCronos-Loans exports TVL: 
        
 
 
    cronos                    672.2736
    
    total                    672.2736

**Comment by llamatester** [comment]
The adapter at projects/CofferCity exports TVL: 
        
 
 
    kava                      10.993443000000001
    
    total                    10.993443000000001

**Comment by llamatester** [comment]
The adapter at projects/CreampanFinance exports TVL: 
        
 
 
    cronos                    319.75 k
    
    total                    319.75 k

**Comment by llamatester** [comment]
The adapter at projects/CthulhuFinance exports TVL: 
        
 
 
    optimism-staking          0
    optimism-pool2            0
    optimism                  0.07650034498615399
    staking                   0
    pool2                     0
    
    total                    0.07650034498615399

**Comment by llamatester** [comment]
The adapter at projects/DigiFT exports TVL: 
        
 
 
    ethereum                  2.56 M
    
    total                    2.56 M

**Comment by llamatester** [comment]
The adapter at projects/DropCopy exports TVL: 
        
 
 
    solana                    15.1376
    
    total                    15.1376

**Comment by llamatester** [comment]
The adapter at projects/E3 exports TVL: 
        
 
 
    base                      129.45 k
    fantom                    117.71 k
    arbitrum                  4.64 k
    
    total                    251.80 k

**Comment by llamatester** [comment]
The adapter at projects/El-Dorado-Exchange exports TVL: 
        
 
 
    arbitrum                  0
    bsc                       86.35 k
    
    total                    86.35 k

**Comment by llamatester** [comment]
The adapter at projects/Guru exports TVL: 
        
 
 
    echelon                   0
    metis                     2.71 k
    polygon                   28.26 k
    avax                      805.608
    arbitrum                  92.20 k
    fantom                    317.65 k
    bsc                       466.56 k
    multivac                  106.74 k
    kcc                       481.962
    
    total                    1.02 M

**Comment by llamatester** [comment]
The adapter at projects/HoneyFarm exports TVL: 
        
 
 
    avax                      0
    avax-pool2                0
    avax-staking              14.022662311381005
    bsc                       0
    bsc-pool2                 0
    bsc-staking               765.0793266728823
    pool2                     0
    staking                   779.1019889842634
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/Hono exports TVL: 
        
 
 
    ethereum                  188.84 k
    
    total                    188.84 k

**Comment by llamatester** [comment]
The adapter at projects/KyborgExchange exports TVL: 
        
 
 
    arbitrum                  0.4588045553587013
    
    total                    0.4588045553587013

**Comment by llamatester** [comment]
The adapter at projects/Lockless exports TVL: 
        
 
 
    echelon                   0
    kava                      13.37 k
    
    total                    13.37 k

**Comment by llamatester** [comment]
The adapter at projects/MFIL exports TVL: 
        
 
 
    filecoin                  3.95 k
    
    total                    3.95 k

**Comment by llamatester** [comment]
The adapter at projects/MantisSwap exports TVL: 
        
 
 
    polygon                   8.79 k
    mode                      81.54 k
    polygon_zkevm             173.78 k
    
    total                    264.11 k

**Comment by llamatester** [comment]
The adapter at projects/Match-Finance exports TVL: 
        
 
 
    ethereum                  151.11 k
    ethereum-staking          61.15 k
    staking                   61.15 k
    
    total                    151.11 k

**Comment by llamatester** [comment]
The adapter at projects/MellowProtocol exports TVL: 
        
 
 
    base                      5.33 k
    polygon_zkevm             3.02 k
    ethereum                  155.09 k
    polygon                   4.86 k
    
    total                    168.30 k

**Comment by llamatester** [comment]
The adapter at projects/MeowProtocol exports TVL: 
        
 
 
    scroll-borrowed           12.07 k
    scroll                    17.94 k
    ethereum-borrowed         707.1341139918253
    ethereum                  7.06 k
    borrowed                  12.78 k
    
    total                    25.00 k

**Comment by llamatester** [comment]
The adapter at projects/MineFi exports TVL: 
        
 
 
    filecoin                  16.78 M
    
    total                    16.78 M

**Comment by llamatester** [comment]
The adapter at projects/MyTrade exports TVL: 
        
 
 
    polygon                   18.94 k
    moonbeam                  192.44724356691856
    
    total                    19.13 k

**Comment by llamatester** [comment]
The adapter at projects/NEKO exports TVL: 
        
 
 
    near                      0
    near-staking              312.03 k
    staking                   312.03 k
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/OT exports TVL: 
        
 
 
    era                       39.45 k
    base                      7.24 k
    
    total                    46.69 k

**Comment by llamatester** [comment]
The adapter at projects/SecuredFinance exports TVL: 
        
 
 
    avax                      3.17 k
    ethereum                  22.52 k
    polygon_zkevm             1.38 k
    arbitrum                  3.13 k
    
    total                    30.20 k

**Comment by llamatester** [comment]
The adapter at projects/SharpeLabs exports TVL: 
        
 
 
    ethereum                  1.88 k
    
    total                    1.88 k

**Comment by llamatester** [comment]
The adapter at projects/aark exports TVL: 
        
 
 
    arbitrum                  4.21 M
    
    total                    4.21 M

**Comment by llamatester** [comment]
The adapter at projects/aave exports TVL: 
        
 
 
    ethereum-staking          334.15 M
    avax                      38.16 M
    avax-borrowed             9.57 M
    ethereum-pool2            14.39 M
    ethereum                  2.32 B
    ethereum-borrowed         844.07 M
    polygon-borrowed          30.19 M
    polygon                   105.25 M
    staking                   334.15 M
    borrowed                  883.83 M
    pool2                     14.39 M
    
    total                    2.46 B

**Comment by llamatester** [comment]
The adapter at projects/abc-pool exports TVL: 
        
 
 
    conflux                   35.18 M
    
    total                    35.18 M

**Comment by llamatester** [comment]
The adapter at projects/abex-finance exports TVL: 
        
 
 
    sui                       2.28 M
    
    total                    2.28 M

**Comment by llamatester** [comment]
The adapter at projects/abracadabra exports TVL: 
        
 
 
    arbitrum                  38.89 M
    kava                      615.05 k
    ethereum                  88.69 M
    bsc                       504.33 k
    avax                      471.06 k
    fantom                    2.17 M
    blast                     10.12 M
    optimism                  0
    
    total                    141.46 M

**Comment by llamatester** [comment]
The adapter at projects/acala-euphrates exports TVL: 
        
 
 
    acala                     18.74 M
    
    total                    18.74 M

**Comment by llamatester** [comment]
The adapter at projects/accumulated-finance exports TVL: 
        
 
 
    manta                     821.85 k
    arbitrum                  36.73 k
    velas                     150.38 k
    bsc                       61.30 k
    zeta                      359.23 k
    ethereum                  211.91 k
    
    total                    1.64 M

**Comment by llamatester** [comment]
The adapter at projects/accumulator exports TVL: 
        
 
 
    shimmer_evm               684.38 k
    
    total                    684.38 k

**Comment by llamatester** [comment]
The adapter at projects/across exports TVL: 
        
 
 
    ethereum                  139.42 M
    
    total                    139.42 M

**Comment by llamatester** [comment]
The adapter at projects/adamantfinance exports TVL: 
        
 
 
    arbitrum-staking          7.17 k
    polygon-staking           406.52 k
    polygon-pool2             287.86 k
    cronos-staking            1.06 k
    arbitrum                  40.56 k
    cronos                    17.18 k
    polygon                   240.64 k
    staking                   414.75 k
    pool2                     287.86 k
    
    total                    298.38 k

**Comment by llamatester** [comment]
The adapter at projects/aelin exports TVL: 
        
 
 
    optimism-staking          104.52 k
    ethereum                  105.263811742608
    optimism-pool2            12.57 k
    optimism                  28.57 k
    ethereum-pool2            6.16 k
    staking                   104.52 k
    pool2                     18.73 k
    
    total                    28.68 k

**Comment by llamatester** [comment]
The adapter at projects/aequinox exports TVL: 
        
 
 
    bsc                       626.78 k
    
    total                    626.78 k

**Comment by llamatester** [comment]
Error while running adapter at projects/aera: 
        
 
  
    
    
    Error: Promise pool failed! 
     PromisePoolError: Failed to call: function tryAggregate(bool requireSuccess, tuple(address target, bytes callData)[] calls) payable returns (tuple(bool success, bytes returnData)[] returnData) target: 0xca11bde05977b3631167028862be2a173976ca11 params: false, 0x1acf26126581f30fec3b2f0824ba8fd3b5c80e84,0x71a97305,0xe75b5b1cdcc09ed29a8f3004bd3254bc06a42361,0x71a97305,0xe2d17f49d4597c98e4b7b681... on chain: [polygon] rpc: https://polygon-rpc.com, https://rpc-mainnet.maticvigil.com, https://endpoints.omniatech.io/v1/matic/mainnet/public, https://rpc-mainnet.matic.quiknode.pro, https://polygon-pokt.nodies.app, https://polygon-mainnet.public.blastapi.io, https://1rpc.io/matic, https://polygon-mainnet.rpcfast.com?api_key=xbhWBI1Wkguk8SNMu1bvvLurPGLXmgwYeC4S6g2H7WdwFigZSmPWVZRxrskEQwIf, https://polygon-bor-rpc.publicnode.com, https://polygon.blockpi.network/v1/rpc/public, https://polygon.api.onfinality.io/public, https://polygon.rpc.blxrbdn.com, https://polygon.drpc.org, https://polygon.gateway.tenderly.co, https://gateway.tenderly.co/public/polygon, https://polygon.meowrpc.com, https://public.stackup.sh/api/v1/node/polygon-mainnet  call reverted, reason: fragment.format is not a function

**Pull request merged**
