### PR TITLE
Remove old Farms

### PR DESCRIPTION
**Pull request by gaspare100**
How can i add the masterchef for the single stake pool of Lion?

**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/scrub exports TVL: 
        
 
 
    cronos                    0
    cronos-staking            150.09 k
    cronos-pool2              357.19 k
    staking                   150.09 k
    pool2                     357.19 k
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/scrub exports TVL: 
        
 
 
    cronos                    0
    cronos-staking            150.13 k
    cronos-pool2              357.08 k
    staking                   150.13 k
    pool2                     357.08 k
    
    total                    0

**Comment by llamatester** [comment]
Error while running adapter at projects/scrub: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:223:11

**Comment by llamatester** [comment]
The adapter at projects/scrub exports TVL: 
        
 
 
    cronos                    0
    cronos-staking            150.28 k
    cronos-pool2              357.39 k
    staking                   150.28 k
    pool2                     357.39 k
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/scrub exports TVL: 
        
 
 
    cronos                    0
    cronos-staking            149.68 k
    cronos-pool2              158.97 k
    staking                   149.68 k
    pool2                     158.97 k
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/scrub exports TVL: 
        
 
 
    cronos                    0
    cronos-staking            149.68 k
    cronos-pool2              356.48 k
    staking                   149.68 k
    pool2                     356.48 k
    
    total                    0

**Comment by llamatester** [comment]
Error while running adapter at projects/scrub: 
        
 
  
    
    
    TypeError: Cannot read properties of null (reading 'toLowerCase')
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/unknownTokens.js:119:47
        at Array.forEach (<anonymous>)
        at getTokenPrices (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/unknownTokens.js:118:19)

**Comment by llamatester** [comment]
The adapter at projects/scrub exports TVL: 
        
 
 
    cronos                    0
    cronos-staking            168.69 k
    cronos-pool2              356.76 k
    staking                   168.69 k
    pool2                     356.76 k
    
    total                    0

**Comment by gaspare100** [comment]
Lion and Bear and Tiger should be added to asset list as this is a tomb fork, otherwise tvl is not right..

**Comment by llamatester** [comment]
The adapter at projects/scrub exports TVL: 
        
 
 
    cronos                    0
    cronos-staking            149.83 k
    cronos-pool2              333.64 k
    staking                   149.83 k
    pool2                     333.64 k
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/scrub exports TVL: 
        
 
 
    cronos                    0
    cronos-staking            0
    cronos-pool2              281.76 k
    staking                   0
    pool2                     281.76 k
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/scrub exports TVL: 
        
 
 
    cronos                    0
    cronos-staking            0
    cronos-pool2              281.78 k
    staking                   0
    pool2                     281.78 k
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/scrub exports TVL: 
        
 
 
    cronos                    0
    cronos-staking            0
    cronos-pool2              281.64 k
    staking                   0
    pool2                     281.64 k
    
    total                    0

**Comment by llamatester** [comment]
Error while running adapter at projects/scrub: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:223:11

**Comment by llamatester** [comment]
Error while running adapter at projects/scrub: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:223:11

**Comment by llamatester** [comment]
Error while running adapter at projects/scrub: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:223:11

**Comment by llamatester** [comment]
Error while running adapter at projects/scrub: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:223:11

**Comment by llamatester** [comment]
Error while running adapter at projects/scrub: 
        
 
  
    
    
    ReferenceError: getTokenPrices is not defined
    Truncated error stack:
    
        at staking (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/scrub/index.js:48:7)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:59:31)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:166:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:154:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:149:44

**Comment by llamatester** [comment]
Error while running adapter at projects/scrub: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:223:11

**Comment by llamatester** [comment]
Error while running adapter at projects/scrub: 
        
 
  
    
    
    ReferenceError: getTokenPrices is not defined
    Truncated error stack:
    
        at staking (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/scrub/index.js:51:7)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:59:31)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:166:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:154:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:149:44

**Comment by llamatester** [comment]
The adapter at projects/scrub exports TVL: 
        
 
 
    cronos                    0
    cronos-staking            563.07 k
    cronos-pool2              357.17 k
    staking                   563.07 k
    pool2                     357.17 k
    
    total                    0

**Comment by gaspare100** [comment]
Please merge when possible, thanks

**Pull request merged**
