### PR TITLE
Update StakeWise ETH and GNO TVL

### PR DESCRIPTION
**Pull request by tsudmi**
Updates StakeWise TVL that counts TVLs of V2 and V3 on Ethereum, and adds rGNO on Gnosis.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/stakewise: 
        
 
  
    
    
    Error: Invalid balance: NaN
    Truncated error stack:
        at isValidNumber (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:119:19)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:319:16
        at Array.forEach (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:313:28)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:326:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:54:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
The adapter at projects/stakewise exports TVL: 
        
 
 
    ethereum                  204.34 M
    xdai                      16.85 M
    
    total                    221.18 M

**Review by g1nt0ki — COMMENTED** [review]
sorry, dont like this update, anyway to get the info onchain? https://github.com/DefiLlama/DefiLlama-Adapters/discussions/432

**Comment by 0xngmi** [comment]
i actually pushed a fix for v3 on ethereum here: c83d9140f780134afec5b2e0d91e3605cb69cbc3

much better since no api is involved

**Comment by llamatester** [comment]
The adapter at projects/stakewise exports TVL: 
        
 
 
    xdai                      14.42 M
    ethereum                  218.96 M
    
    total                    233.38 M

**Comment by tsudmi** [comment]
Hey, @Define101, I reverted to onchain fetch and added rETH2 supply, which is staking rewards in V2.

**Comment by llamatester** [comment]
The adapter at projects/stakewise exports TVL: 
        
 
 
    xdai                      14.54 M
    ethereum                  223.04 M
    
    total                    237.57 M

**Pull request merged**
