### PR TITLE
add UltronStakingHub

### PR DESCRIPTION
**Pull request by backendultron**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama): 
Ultron Staking Hub NFT

##### Twitter Link: 
https://twitter.com/ultron_found

##### Website Link: 
https://ultron.foundation/stakingHubNft

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): 
https://api.ipfsbrowser.com/ipfs/get.php?hash=QmS4W4kY7XYBA4f52vuuytXh3YaTcNBXF14V9tEY6SNqhz

##### Current TVL: 
165.59 M $

##### Chain: 
Ultron

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
https://www.coingecko.com/en/coins/ultron

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
https://coinmarketcap.com/currencies/ultron/

##### Short Description (to be shown on DefiLlama): 
The Staking Hub is an innovative digital asset growth instrument developed by the Ultron Foundation that enables users to receive daily APR returns in ULX coins. The predefined amount of ULX supply is destined for the Staking Hub rewards distribution according to the tokenomics.. Every user has registration and dashboard, with ability to mint NFT and stake it on the protocol for 5 years with vesting schedule. All liquidity is locked on a staking smart-contract and could be claimed at certain timelines.

##### Token address and ticker if any:
0x3a4F06431457de873B588846d139EC0d86275d54

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Staking

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
NaN

##### forkedFrom (Does your project originate from another project):
NaN

##### methodology (what is being counted as tvl, how is tvl being calculated):
Counts how many wULX are locked on the manage contract

### CODE REVIEW

**Comment by vrtnd** [comment]
Hi, thanks for the PR. Your tvl should be changed to staking: 
```
 staking: staking({
      owner: '0xd130811147bb87f313c555e5281b94b9e71b480a', 
      tokens: ['0x3a4F06431457de873B588846d139EC0d86275d54'], 
      chain: 'ultron'
    })
```

**Comment by backendultron** [comment]
> Hi, thanks for the PR. Your tvl should be changed to staking:
> 
> ```
>  staking: staking({
>       owner: '0xd130811147bb87f313c555e5281b94b9e71b480a', 
>       tokens: ['0x3a4F06431457de873B588846d139EC0d86275d54'], 
>       chain: 'ultron'
>     })
> ```

Hi, if i change tvl to staking i get an error, is there any way to avoid this?

`Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains`

**Comment by vrtnd** [comment]
add this ` tvl: () => ({})`

**Comment by llamatester** [comment]
The adapter at projects/ultronStakingHub exports TVL: 
        
 
 
    ultron                    0
    ultron-staking            172.54 M
    staking                   172.54 M
    
    total                    0

**Pull request merged**
