### PR TITLE
Elevenfinance adapter

### PR DESCRIPTION
**Pull request by morazzela**
Re-opened a PR to include multichain TVL changes as @0xngmi requested (#394):

##### Twitter Link:
https://twitter.com/ElevenFinance

##### List of audit links if any:
https://www.certik.org/projects/elevenfinance

##### Website Link:
https://eleven.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
eleven

##### Current TVL:
$60,000,000

##### Chain:
BSC / POLYGON / OKEX / AVALANCHE / FTM

##### Coingecko ID (so your TVL can appear on Coingecko):
eleven-finance

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap):
10271

##### Description/bio (to be shown on DefiLlama):
A high APY, low fee vault ecosystem and leveraged yield farming platform on BSC / Polygon / OKExChain + more.

##### Token address and ticker if any:
Token address (all chains) : 0xacd7b3d9c10e97d0efa418903c0c7669e702e4c0
Ticker : ELE

##### Category (Yield/Dexes/Lending/Minting):
Yield & Lending

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Is it possible to use an on chain adapter for this? Some of this TVL may need to be separated out into staking / pool2.

**Comment by morazzela** [comment]
> Is it possible to use an on chain adapter for this? Some of this TVL may need to be separated out into staking / pool2.

The API is entirely written in Python, that would take a long time to re-code the entire thing in Node.js
Also, Eleven is planning to expand on non EVM chains (SOL) in the future, not sure if on chain adapters support it

IMO this fetch adapter could be a better solution

> Some of this TVL may need to be separated out into staking / pool2.

Got you, will fix this

**Comment by morazzela** [comment]
@waynebruce0x just pushed, all ELE pools and staking has been removed 

concerning the on chain adapter, the team is working on building subgraphs but understand building a fully-on chain SDK for DefiLlama in 5 chains (and more soon), which is over 800 contracts involved is fairly impractical. We use our own api kit to report our stats like many other multichain projects, but all our contracts and code verified and published and easily verifiable on-chain if needed

**Comment by 0xngmi** [comment]
Can you change your API to report the chain on which each pool is? With that I could change the adapter to not have to rely on an up-to-date list of ignored pools

**Comment by morazzela** [comment]
> Can you change your API to report the chain on which each pool is? With that I could change the adapter to not have to rely on an up-to-date list of ignored pools

Not sure I understand correctly, the excluded pools still needs to be hardcoded into the adapter if the info isn't coming from the API ?

**Comment by 0xngmi** [comment]
if the chain was reported in the API we could find out the excluded pools by running `poolName.includes("ELE")`

**Pull request merged**
