### PR TITLE
sumbit project DigiFT- RWA DEX

### PR DESCRIPTION
**Pull request by whucsfzf**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
DigiFT

##### Twitter Link:
https://twitter.com/DigiFTTech

##### List of audit links if any:
No link. Audited by Hacken\Elessar Labs\Numen.

##### Website Link:
https://www.digift.sg

##### Logo (High resolution, will be shown with rounded borders):
image

##### Current TVL:
$2,115,297

##### Treasury Addresses (if the protocol has treasury)
N/A

##### Chain:
Ethereum

##### Short Description (to be shown on DefiLlama):
DigiFT is the first and only RWA DEX enrolled within the Monetary Authority of Singapore (MAS) FinTech Regulatory Sandbox, built on the Ethereum public blockchain. DigiFT enables asset owners to issue, and eligible investors to purchase, blockchain-based security tokens. Investors can also access continuous liquidity on secondary market trading via an Automatic Market Maker mechanism.

##### Token address and ticker if any:
Name: DUST Treasury Token , Token symbol: DUST1223 , Token address: 0x114738B865EEa72468D24465FBBEf013455CF249
Name: Perpetual Bond Referenced Token , Token symbol: PBRT01, Token address: 
0x114738B865EEa72468D24465FBBEf013455CF249

##### Category (full list at https://defillama.com/categories) *Please choose only one:
RWA

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
FeedPrice Contract: 0x7d4d68f18d1be3410ab8d827fb7ebc690f938d2d, deployed on Polygon.

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is calculated by multiplying the token total supply with the corresponding real-world asset's price.

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/DigiFT exports TVL: 
        
 
 
    ethereum                  2.12 M
    
    total                    2.12 M

**Comment by whucsfzf** [comment]
Has any update? Thanks. @llamatester

**Comment by waynebruce0x** [comment]
How come the onchain calls are on polygon but the TVL is recorded as on ethereum?

**Comment by waynebruce0x** [comment]
Also could you verify your oracle contract because at the moment we cant tell what the function does to return price

**Comment by whucsfzf** [comment]
@waynebruce0x  Hi,  all the Security Token are on Ethereum mainnet now. We also have plans to deploy on other chains. We deploy the price oracle contract on the Polygon. When calcing the TVL, we use the price from the polygon.  

The abi of  getTokenPrice is:
{
  "inputs": [
    {
      "internalType": "uint256",
      "name": "chainId",
      "type": "uint256"
    },
    {
      "internalType": "address",
      "name": "tokenAddress",
      "type": "address"
    }
  ],
  "name": "getTokenPrice",
  "outputs": [
    {
      "internalType": "uint128",
      "name": "",
      "type": "uint128"
    }
  ],
  "stateMutability": "view",
  "type": "function"
}
eg:  getTokenPrice(chainId, tokenAddress)

**Comment by llamatester** [comment]
The adapter at projects/DigiFT exports TVL: 
        
 
 
    ethereum                  0
    
    total                    0

**Comment by g1nt0ki** [comment]
hi @whucsfzf can you pleace verify the feed contract in polygon, I have moved the token pricing logic to our coins repo: https://github.com/DefiLlama/defillama-server/commit/85be0ca4ba4a7dba759c24d265c6ad759e093c65

**Comment by whucsfzf** [comment]
OK. I will verify the feed contract. Once done, i will let you know.

**Comment by g1nt0ki** [comment]
thanks @whucsfzf

**Comment by whucsfzf** [comment]
image
It seems the TVL is not correct.  It should be:  ethereum   2.12M

**Comment by g1nt0ki** [comment]
@whucsfzf give it a few hours, it will fix itself

**Comment by whucsfzf** [comment]
Approximately when can it be seen on the DefiLlama website? Thanks.

**Comment by whucsfzf** [comment]
Thanks for your support. Everything is ok now.

**Pull request merged**
