### PR TITLE
Add PulsarMoney Adapter

### PR DESCRIPTION
**Pull request by astrarizon**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Pulsar Money

##### Twitter Link:
https://twitter.com/pulsarmoney

##### Website Link:
https://pulsar.money/

##### Logo (High resolution, will be shown with rounded borders):
Logo

##### Current TVL:
5.06 M

##### Chain:
MultiversX

##### Short Description (to be shown on DefiLlama):
Pulsar Money is a Smart Payments Hub reshaping on-chain payments through advanced transfer modules.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
[Payments](https://defillama.com/protocols/Payments)

##### methodology (what is being counted as tvl, how is tvl being calculated):
The methodology for calculating the TVL of Pulsar Money takes into account the total value of the tokens locked in the smart contract.

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/pulsar-money exports TVL: 
        
 
 
    elrond                    5.07 M
    
    total                    5.07 M

**Comment by llamatester** [comment]
The adapter at projects/pulsar-money exports TVL: 
        
 
 
    elrond                    0
    elrond-vesting            5.10 M
    vesting                   5.10 M
    
    total                    0

**Comment by g1nt0ki** [comment]
@astrarizon thanks for the PR.

 for payments category, we count only stables and native chain token as tvl  and the rest of the tokens under vesting, same rule was applied to coindip and llamapay, hence I made the same change here.

**Comment by astrarizon** [comment]
Understood, thank you very much!

**Pull request merged**
