### PR TITLE
Add GoodDollar adapter

### PR DESCRIPTION
**Pull request by Shloyem**
##### Twitter Link:
https://twitter.com/gooddollarorg

##### List of audit links if any:
https://github.com/GoodDollar/GoodProtocol/tree/master/audits

##### Website Link:
https://www.gooddollar.org/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://github.com/GoodDollar/GoodProtocolUI/blob/master/src/assets/images/G%24%20Coin.png

##### Current TVL:
3.76M$

##### Chain:
Mainnet and Fuse

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
Not there yet

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
6961

##### Short Description (to be shown on DefiLlama):
GoodDollar is a universal basic income protocol and DAO to fight inequality that leverages staking and market incentives to sustainably fund the distribution of free crypto to underserved members all over the world. As of today, GoodDollar UBI serves over 300,000 members from 180 territories; 70,000 which are daily active users.

##### Token address and ticker if any:
Address: 0x67C5870b4A41D4Ebef24d2456547A03F1f3e094B
Ticker: G$

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Staking

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
No

##### forkedFrom (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated):
Aggregation of funds staked in our contracts on Ethereum and Fuse, funds locked in reserve backing G$ token and community treasury. G$ value was converted to USD based on current price at the reserve.

### CODE REVIEW

**Comment by waynebruce0x** [comment]
are delegators given tokens to represent their deposits? like stETH on Lido?

**Comment by sirpy** [comment]
> are delegators given tokens to represent their deposits? like stETH on Lido?
@waynebruce0x if you are referring to the fusestaking contract then at the moment no, but its planned for the second version.

**Comment by waynebruce0x** [comment]
Okay unfortunately we dont count funds staked for securing the network, but we can count your treasury and staking

**Comment by sirpy** [comment]
@waynebruce0x 
i'm not sure what are you talking about, we are not a network. the FuseStaking is doing yield farming. instead of staking in some DEFI protocol it stakes directly in the POS protocol of Fuse generating rewards. those rewards go directly to fund more UBI and increase the DAO treasury.

**Comment by waynebruce0x** [comment]
We don't count POS staking unless its liquid staking (with tokenised deposits like Lido)

**Pull request merged**
