### PR TITLE
Add DAO DAO TVL

### PR DESCRIPTION
**Pull request by NoahSaso**
##### Name (to be shown on DefiLlama):

DAO DAO

##### Twitter Link:

https://twitter.com/DA0_DA0

##### List of audit links if any:

https://github.com/oak-security/audit-reports/blob/master/DAO%20DAO/2022-06-22%20Audit%20Report%20-%20DAO%20DAO%20v1.0.pdf

##### Website Link:

https://daodao.zone

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

svg
png

##### Current TVL:

$8,491,862.56 USDC

##### Chain:

Juno Network

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

N/A

##### Short Description (to be shown on DefiLlama):

Simple, capable, and free DAO tooling. Built with love, by DAO DAO, on Juno.

##### Token address and ticker if any:

N/A

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Services

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

None

##### forkedFrom (Does your project originate from another project):

None

##### methodology (what is being counted as tvl, how is tvl being calculated):

TVL is considered the total number of native and CW20 tokens locked in all DAOs made on DAO DAO.

### CODE REVIEW

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
@NoahSaso Thanks for the PR

can you refactor code to fetch the tvl details on chain, this makes adapter more transparent and less dependent on external api and would work as long as chain is reachable.

I am guessing you are counting dao's treasury funds as tvl, can you exclude the protocol's own token for this? https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by NoahSaso** [comment]
> @NoahSaso Thanks for the PR
> 
> can you refactor code to fetch the tvl details on chain, this makes adapter more transparent and less dependent on external api and would work as long as chain is reachable.
> 
> I am guessing you are counting dao's treasury funds as tvl, can you exclude the protocol's own token for this? https://docs.llama.fi/list-your-project/what-to-include-as-tvl

Hmm, because DAOs are each their own smart contract, it's extremely inefficient to query the chain :/

Given that there are about 2,800 DAOs, and at least 5 queries (sometimes more) per DAO to obtain all of the different tokens and prices for those tokens, querying the chain is pretty excessive here. What do you think?

Also, we don't have any protocol token, so nothing to exclude there.

**Comment by g1nt0ki** [comment]
"Also, we don't have any protocol token, so nothing to exclude there."

Lets take RAW DAO for example, tvl on [your site](https://legacy.daodao.zone/multisig/juno18jy629ehmfp2w4nnnyajj955npuw0ryhrvxauff47s65nev8eyuqnpfsd2) is ~1.3M but it is mostly made up of $RAW tokens

it would be fewer calls if we only fetch the token balances (and count only stable) right? we have rudimentary support for pricing IBC tokens, you can do it by creating a balances object and calling `transformBalances('juno', balances)` I could also add some caching server side, no. of calls is not an issue for us

**Comment by g1nt0ki** [comment]
@NoahSaso can you give me some info on how to collect list of multisigs holding treasury assets ? i have tiny bit of time, I can try to write the adapter myself

**Comment by NoahSaso** [comment]
> "Also, we don't have any protocol token, so nothing to exclude there."
> 
> Lets take RAW DAO for example, tvl on [your site](https://legacy.daodao.zone/multisig/juno18jy629ehmfp2w4nnnyajj955npuw0ryhrvxauff47s65nev8eyuqnpfsd2) is ~1.3M but it is mostly made up of $RAW tokens
> 
> it would be fewer calls if we only fetch the token balances (and count only stable) right? we have rudimentary support for pricing IBC tokens, you can do it by creating a balances object and calling `transformBalances('juno', balances)` I could also add some caching server side, no. of calls is not an issue for us

Ah I see. Hmm, so we could check the governance token of a DAO and then ignore that balance in its treasury. However, it would be difficult to differentiate between a regular CW20 (like USDC) which should be counted and a different DAO's governance CW20, which should not be counted, without querying every DAO's voting module and token contracts. For example, if a *different* DAO owned $RAW, such as the DAO DAO DAO, the $RAW and $USDC contracts look no different.

To solve this, we would query every DAO's core contract for its voting module contract, query the voting module for the governance token address, and then store the list of governance token addresses before calculating the price for all the DAOs. This is totally doable, but means that we cannot reduce the number of queries performed.

I guess the relevant question is: is there a limit to how many queries we can perform? How often does this get run and what are the constraints?

> @NoahSaso can you give me some info on how to collect list of multisigs holding treasury assets ? i have tiny bit of time, I can try to write the adapter myself

The script to total all the balances is actually already written (behind the endpoint currently in the PR), so it would be much quicker for me to modify it to work with this adapter system than to have you rewrite it from scratch. The only question is the performance limit on queries.

**Pull request closed without merging**
