### PR TITLE
Added project return-finance project

### PR DESCRIPTION
**Pull request by Joro-Popov**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Logo (High resolution, will be shown with rounded borders):
appstore

##### Short Description (to be shown on DefiLlama):
Return Finance is a user-friendly, decentralized finance (DeFi) platform that lets you earn high Annual Percentage Yield (APY) on your Euro and U.S. Dollars from DeFi markets. With a focus on security, transparency, and user-centric design, Return-Finance aims to empower users to access and participate in the rapidly evolving world of decentralized finance.

##### methodology (what is being counted as tvl, how is tvl being calculated):
Tvl is the total sum equivalent of usd across all Return Finance liquiridy pools (smart contracts) deployed

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/return-finance exports TVL: 
        
 
 
    polygon                   7.248245599826001
    avax                      5.016414448815
    ethereum                  0
    base                      0
    
    total                    12.264660048641002

**Comment by g1nt0ki** [comment]
hi, can you please fill in the project details

**Comment by Joro-Popov** [comment]
> hi, can you please fill in the project details

Project details are now present in the description

**Comment by llamatester** [comment]
The adapter at projects/return-finance exports TVL: 
        
 
 
    polygon                   5.035326166108
    base                      5.003652508008
    avax                      5.002561198733
    ethereum                  0
    
    total                    15.041539872848999

**Review by Joro-Popov — COMMENTED** [review]
Approved

**Pull request merged**
