### PR TITLE
Add TVL of Klaytn network

### PR DESCRIPTION
**Pull request by MoundJayden**
Qubit is already listed at DefiLlama.

We launch at new network (Klaytn). So we want to display them at DefiLlama.

Please take a look my code and confirm pull request.

Thank you.

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Do you mind resolving the conflicts?

**Comment by MoundJayden** [comment]
Resolved. Someone who is not our team edited qubit's code so I didn't expect conflict.

**Comment by waynebruce0x** [comment]
I can't get the adapter to run - does it work for you if you run 'node test.js projects/qubit/index.js' ? 
Also, is this including borrowed funds in TVL, or subtracting borrowed from supplied?

**Comment by MoundJayden** [comment]
I'll close this pull request and make new one. And our dashboard contract returns TVL value as Supply - Borrow. Thank you.

**Pull request closed without merging**
