### PR TITLE
Track Base Assets for Reserve Protocol

### PR DESCRIPTION
**Pull request by larrythecucumber321**
This PR adds tracking for Reserve's assets on Base. New underlying assets are additionally tracked in this PR; for Stargate and Compound V3.

```

--- ethereum-staking ---
RSR                       5.82 M
Total: 5.82 M 

--- base-staking ---
RSR                       5.55 k
Total: 5.55 k 

--- ethereum ---
aUSDC                     4.55 M
aUSDT                     4.48 M
cUSDT                     4.46 M
cUSDC                     4.46 M
wstETH                    1.47 M
rETH                      1.47 M
USDC                      671.84 k
eUSD3CRV-f                656.92 k
MIM-3LP3CRV-f             656.32 k
DAI                       243.87 k
USDT                      22.778881124999998
aDAI                      8.843147129963457
aBUSD                     0.5041256004259721
EURT                      0.09496055
BUSD                      0.09148754975359999
cDAI                      0.0700270311899772
USDP                      0.0693033877536
TUSD                      0.06915640364550721
3Crv                      0.0666305124327937
cWBTC                     0.02553346297896929
cETH                      0.007099617521523901
WETH                      0.007028229676
WBTC                      0.00028273
Total: 23.10 M 

--- base ---
USDbC                     255.36 k
WETH                      52.13491519930133
DAI                       0.011118670135611863
Total: 255.41 k 

--- staking ---
RSR                       5.83 M
Total: 5.83 M 

--- tvl ---
aUSDC                     4.55 M
aUSDT                     4.48 M
cUSDT                     4.46 M
cUSDC                     4.46 M
wstETH                    1.47 M
rETH                      1.47 M
USDC                      671.84 k
eUSD3CRV-f                656.92 k
MIM-3LP3CRV-f             656.32 k
USDbC                     255.36 k
DAI                       243.87 k
WETH                      52
USDT                      23
aDAI                      9
aBUSD                     1
Total: 23.36 M 

------ TVL ------
ethereum-staking          5.82 M
base-staking              5.55 k
ethereum                  23.10 M
base                      255.41 k
staking                   5.83 M

total                    23.36 M 
```

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/reserve exports TVL: 
        
 
 
    ethereum-staking          5.82 M
    ethereum                  23.10 M
    base-staking              5.53 k
    base                      255.10 k
    staking                   5.82 M
    
    total                    23.36 M

**Comment by llamatester** [comment]
The adapter at projects/reserve exports TVL: 
        
 
 
    ethereum-staking          5.92 M
    base-staking              5.67 k
    ethereum                  23.14 M
    base                      256.80 k
    staking                   5.93 M
    
    total                    23.39 M

**Comment by g1nt0ki** [comment]
@larrythecucumber321 thanks for the PR, I have refactored it a bit, running it in Promise.all ran a bit slow on my computer, so did a bit of hack

**Comment by larrythecucumber321** [comment]
Thank you @g1nt0ki 🙏

**Pull request merged**
