### PR TITLE
🥕 added Carrot tvl adapter

### PR DESCRIPTION
**Pull request by jsblair9**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### List of audit links if any:
- Sec3 Audit: https://deficarrot.com/assets/carrot_final_report.pdf

##### Logo (High resolution, will be shown with rounded borders):
just-carrot-onDark_sq

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
`carrot-2`

##### Short Description (to be shown on DefiLlama):
A liquid yield bearing token that maximizes your earned interest on stablecoins, consistently increasing the token value by intelligently routing funds to capture the highest available yield, without adding speculation risk

##### Token address and ticker if any:
`CRTx1JouZhzSU6XytsE42UQraoGqiHgxabocVfARTy2s`
CRT

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is representative of deposits into the Carrot vault.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/carrot exports TVL: 
        
 
 
    solana                    2.76 M
    
    total                    2.76 M

**Comment by g1nt0ki** [comment]
@jsblair9 thanks for the PR, any idea what I am doing wrong here? https://github.com/DefiLlama/DefiLlama-Adapters/pull/12212

**Comment by jsblair9** [comment]
I will take a look now @g1nt0ki !

**Comment by jsblair9** [comment]
@g1nt0ki looks like it needed a little padding before decoding the strategies  -- I've updated my PR with the refactor.

I'm curious, why go for this method over using the token? It would be preferable to have the full history (which we would get with the token) but I'm assuming we would not with this approach.

**Comment by llamatester** [comment]
The adapter at projects/carrot exports TVL: 
        
 
 
    solana                    2.98 M
    
    total                    2.98 M

**Comment by jsblair9** [comment]
@g1nt0ki opted to pull the IDL over adding the in the layout file. Little more future proof!

**Comment by llamatester** [comment]
The adapter at projects/carrot exports TVL: 
        
 
 
    solana                    2.98 M
    
    total                    2.98 M

**Review by g1nt0ki — APPROVED** [review]
looks good, thanks

**Pull request merged**
