### PR TITLE
iagon added

### PR DESCRIPTION
**Pull request by iagontech**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/iagon exports TVL: 
        
 
 
    cardano-staking           902.93 k
    cardano                   2.43 M
    staking                   902.93 k
    
    total                    2.43 M

**Comment by llamatester** [comment]
The adapter at projects/iagon exports TVL: 
        
 
 
    cardano-staking           902.10 k
    cardano                   2.43 M
    staking                   902.10 k
    
    total                    2.43 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
it is not very clear what is counted as tvl here, can you compute it using on chain data? also, if these are staked LP tokens, they count towards pool2, not tvl: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by g1nt0ki** [comment]
@iagontech thanks for the PR but we cant list projects with 0 tvl, can you comment here once it has some tvl?

**Comment by g1nt0ki** [comment]
@iagontech thanks for fixing it

**Pull request merged**
