### PR TITLE
Add Astrolescent to Radix

### PR DESCRIPTION
**Pull request by timanrebel**
---
##### Name (to be shown on DefiLlama):
Astrolescent

##### Twitter Link:
https://twitter.com/astrolescent

##### List of audit links if any:
-

##### Website Link:
https://astrolescent.com

##### Logo (High resolution, will be shown with rounded borders):
https://astrolescent.com/assets/img/logo-round.png

##### Current TVL:
80k USD

##### Treasury Addresses (if the protocol has treasury)
account_rdx16y6spuy7pvxj3v9ruezge6dvnvjkjja70wmv8fa4c73n4csl9p3pr5

##### Chain:
Radix

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
-

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
-

##### Short Description (to be shown on DefiLlama):
Access the best prices for each trade on Radix.

##### Token address and ticker if any:
ASTRL
resource_rdx1t4tjx4g3qzd98nayqxm7qdpj0a0u8ns6a0jrchq49dyfevgh6u0gj3

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
-

##### forkedFrom (Does your project originate from another project):
-

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is counted by combining our liquidity pools and the option to stake ASTRL to receive a yield. 

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/Astrolescent-Official/

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/astrolescent exports TVL: 
        
 
 
    radixdlt                  79.52 k
    
    total                    79.52 k

**Comment by llamatester** [comment]
The adapter at projects/astrolescent exports TVL: 
        
 
 
    radixdlt                  88.37 k
    
    total                    88.37 k

**Comment by g1nt0ki** [comment]
thanks for the PR

**Comment by llamatester** [comment]
The adapter at projects/astrolescent exports TVL: 
        
 
 
    radixdlt-staking          79.52 k
    radixdlt                  8.85 k
    staking                   79.52 k
    
    total                    8.85 k

**Pull request merged**
