### PR TITLE
Update collateral tokens

### PR DESCRIPTION
**Pull request by Tjudice**
Adding capped collateral tokens to collateral calculation.

Tokens:
MATIC
ENS
BAL
AAVE
LDO
DYDX
CRV
rETH
cbETH

Twitter Link:
https://twitter.com/interestDeFi/

List of audit links if any:
https://gfx.cafe/ip/contracts/-/blob/master/audit/GFX_IP_Protocol_Audit_Report.pdf

Website Link:
https://interestprotocol.io/

Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://interestprotocol.io/images/ip_green.svg

Current TVL:
905k

Chain:
ethereum

Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
interest-protocol

Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
interest-protocol

Short Description (to be shown on DefiLlama):
Interest Protocol is a borrow/lend protocol that is highly capital-efficient thanks to its unique combination of fractional reserves and over-collateralization. Depositors may mint USDi, which is a stablecoin pegged 1-1 with USDC that automatically pays interest to holders via rebasing.

Token address and ticker if any:
stablecoin: 0x2a54ba2964c8cd459dc568853f79813a60761b58
gov token : 0xd909C5862Cdb164aDB949D92622082f0092eFC3d

Category (full list at https://defillama.com/categories) *Please choose only one:
CDP

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
chainlink + uniswap v3 twap anchor

forkedFrom (Does your project originate from another project):
n/a

methodology (what is being counted as tvl, how is tvl being calculated):
For Interest Protocol, TVL = Reserve + Total Collateral Value
Reserve is found through calling USDC.getBalances(USDI)
Deposit Balances are found by obtaining all vaults and their deposits through VaultController.vaultSummaries(1,VaultController.vaultsMinted()), and finding the sum
Capped tokens converted 1:1 to underlying

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/ip exports TVL: 
        
 
 
    ethereum-borrowed         418.75 k
    ethereum                  906.17 k
    borrowed                  418.75 k
    
    total                    906.17 k

**Comment by g1nt0ki** [comment]
this looks good but I think it was a mistake to count borrowed tvl, we dont do it for CDPs like Maker for example

**Comment by Tjudice** [comment]
> this looks good but I think it was a mistake to count borrowed tvl, we dont do it for CDPs like Maker for example

To clarify, we do not include borrowed amount in TVL. Borrows are payed out in USDi. However, users can also mint USDi by providing USDC. So the TVL is the sum of collateral + USDC backing USDi.

**Comment by g1nt0ki** [comment]
> > this looks good but I think it was a mistake to count borrowed tvl, we dont do it for CDPs like Maker for example
> 
> To clarify, we do not include borrowed amount in TVL. Borrows are payed out in USDi. However, users can also mint USDi by providing USDC. So the TVL is the sum of collateral + USDC backing USDi.

yeah I agree, USDC definitely counts, just not USDI owed being counted as borrowed, I have removed that part

**Comment by gfxlabs** [comment]
> > > this looks good but I think it was a mistake to count borrowed tvl, we dont do it for CDPs like Maker for example
> > 
> > 
> > To clarify, we do not include borrowed amount in TVL. Borrows are payed out in USDi. However, users can also mint USDi by providing USDC. So the TVL is the sum of collateral + USDC backing USDi.
> 
> yeah I agree, USDC definitely counts, just not USDI owed being counted as borrowed, I have removed that part

hey i'm a bit confused here - looking at the changes as of this commit https://github.com/DefiLlama/DefiLlama-Adapters/commit/7fd539c792bd09fdcc8a20cb80217a5e9808cb80/

You seem to have removed 
```
const getReserve = async (block) =>{
  return (await sdk.api.abi.call({
    block,
    target: tokens.USDC.address,
    params: [tokens.USDI.address],
    abi: "erc20:balanceOf",
  })).output;
}
```

This is the USDC that you say "definitely counts". 

Are we misunderstanding something?

**Comment by g1nt0ki** [comment]
1. Yes, sumTokens2 takes care of it
2. Yes, we dont consider minted tokens as borrowed for any other CDP, not sure how I missed it for your protocol, you can check it here: https://defillama.com/protocols/CDP

**Pull request merged**
