### PR TITLE
Add swapr to supported platforms

### PR DESCRIPTION
**Pull request by luzzif**
##### Twitter Link:
https://twitter.com/SwaprEth

##### List of audit links if any:
https://gateway.ipfs.io/ipfs/QmNspbn2dQgQMQ9uXkMc7Fjf12RUVVJTzB27ywGeLUXXdn

##### Website Link:
https://swapr.eth.link/#/swap

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
[Light SVG](https://gateway.pinata.cloud/ipfs/QmUUmkmTgcm9dTnychHbHXVVDiJgvUL5beYJE3gbgkf25g)
[Dark SVG](https://gateway.pinata.cloud/ipfs/QmZYAmFfs5ZLmZ4AvP6bED3ABP9LsSoVzc3Q6Za4ed9f7P)

##### Current TVL:
2,683,248.47 USD

##### Chain:
xDai and Ethereum mainnet

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
In progress

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N.A.

##### Description/bio (to be shown on DefiLlama):
A governance-enabled automated-market maker with adjustable fees, made by DXdao.

##### Token address and ticker if any:
N.A.

##### Category (Yield/Dexes/Lending/Minting):
Dexes

##### [Optional] ETH addresss (to receive a LlamaPunk):
0x519b70055af55a007110b4ff99b0ea33071c720a

### CODE REVIEW

**Comment by 0xngmi** [comment]
Thanks for the PR! You are the first person to get right the chain exports, kudos for that!

**Comment by KeenanLukeOM** [comment]
Hey @0xngmi.

I'm Keenan, another DXdao contributor. Thanks for the integration, it looks great!

One comment, the logos we had sent appear to clash a bit with your theme. I've attached a new SVG and PNG that should look a touch better.

[Swapr-light-profile.zip](https://github.com/DefiLlama/DefiLlama-Adapters/files/6346713/Swapr-light-profile.zip)

Appreciate your time!

**Comment by 0xngmi** [comment]
Thanks, I've just changed it. You added 2 pictures and I wasn't sure which one was best so I just picked swapr-light-profile.svg, was that the right one?

**Comment by KeenanLukeOM** [comment]
> Thanks, I've just changed it. You added 2 pictures and I wasn't sure which one was best so I just picked swapr-light-profile.svg, was that the right one?

The PNG had transparency and SVG did not IIRC. Just checked, looks fantastic! 

I reached out to you on Twitter as well regarding this PR and the potential of a joint announcement.

Appreciate the help mate.

**Comment by 0xngmi** [comment]
Got it, just saw your message request

**Comment by 0xngmi** [comment]
Hey, at defillama we are changing how we display audits so we are currently going through them all. However, when we tried to access the ipfs link above it seems like the page doesn't load. Could you provide us with an up to date link to the audit?

**Comment by 0xngmi** [comment]
Please ignore the previous message, it seems like loading the audit just took a very long time

**Comment by KeenanLukeOM** [comment]
> Please ignore the previous message, it seems like loading the audit just took a very long time

Sorry about that! Please give a shout if I can provide anything else from our end. Appreciate the work you do! :)

**Comment by 0xngmi** [comment]
Will do, thanks!

**Pull request merged**
