### PR TITLE
Add SDK adapter for Creampan Finance

### PR DESCRIPTION
**Pull request by Creamapan**
Add SDK adapter for Creampan Finance

**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Short Description (to be shown on DefiLlama):
Creampan provides a liquid staking solution that you can mint ptCRO and ytCRO with CRO or WCRO on Cronos chain. The ptCRO is "principal token" of CRO and ytCRO is "yield token" of CRO. 
The ptCRO is designed to be used freely while the CRO is staked. You can hold, stake, farming, or even sell the ptCRO token when the CRO is staked in the chain. The ytCRO holders will receive "daily CRO reward" of the staked CRO. By separating the principle and yield, both tokens maintain constant price regarding to price of CRO. 
Therefore, delegators receive the real CRO rewards daily, freely participate DeFi earing opportunities without impermanent loss, and able to hedge against price of CRO by selling their ptCRO and holding ytCRO.

##### Token address and ticker if any:
PAN token address: 0xDa6c746E8a14EFE6E0A031F5d632bd2B0adC28Be

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Liquid staking

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL = delegated CRO + flexible CRO in contract

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/CreampanFinance exports TVL: 
        
 
 
    cronos                    139.81 k
    
    total                    139.81 k

**Comment by llamatester** [comment]
The adapter at projects/CreampanFinance exports TVL: 
        
 
 
    cronos                    102.70 k
    
    total                    102.70 k

**Comment by llamatester** [comment]
The adapter at projects/CreampanFinance exports TVL: 
        
 
 
    cronos                    137.26 k
    
    total                    137.26 k

**Comment by g1nt0ki** [comment]
@Creamapan thanks for the PR

**Pull request merged**
