### PR TITLE
add staked lq to tvl

### PR DESCRIPTION
**Pull request by kylixafonso**
### Summary
Add the current LQ staked in the protocol to the TVL.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/liqwid exports TVL: 
        
 
 
    cardano                   15.23 M
    
    total                    15.23 M

**Comment by llamatester** [comment]
The adapter at projects/liqwid exports TVL: 
        
 
 
    cardano                   11.48 M
    cardano-staking           3.72 M
    staking                   3.72 M
    
    total                    11.48 M

**Comment by kylixafonso** [comment]
> > hi @kylixafonso staked IQ should be added under staking not tvl: https://docs.llama.fi/list-your-project/what-to-include-as-tvl
> 
> Thank you very much for fixing this! I actually have a bit of a follow up question, our TVL graph looks a bit odd and we were wondering if there's anything that would turn it a bit more stable? Something like interpolation or maybe it's some flag/value that we don't have set?

One of our users suggested possibly disabling time travel.

**Comment by kylixafonso** [comment]
> > > hi @kylixafonso staked IQ should be added under staking not tvl: https://docs.llama.fi/list-your-project/what-to-include-as-tvl
> > 
> > 
> > Thank you very much for fixing this! I actually have a bit of a follow up question, our TVL graph looks a bit odd and we were wondering if there's anything that would turn it a bit more stable? Something like interpolation or maybe it's some flag/value that we don't have set?
> 
> One of our users suggested possibly disabling time travel.

@g1ntoki

**Comment by g1nt0ki** [comment]
not sure why this is happening, asked another llama to remove invalid data points. can you check if there is some bug in our code? like missing address

**Comment by g1nt0ki** [comment]
@kylixafonso sorry for delayed response. you can timetravel as false, but afraid it wont change much, it is just to let our server know that if there is missing value in past, we wont be able to refill

**Comment by kylixafonso** [comment]
Thank you! I think the issue is not a missing address, even when the TVL is totally out of sync on the DefiLlama app and API, when running `node test.js project/liqwid/index.js` returns the correct value, have tested twice during different times when the TVL fell out of sync.

**Comment by kylixafonso** [comment]
Would us writing up an API to wrap around these queries and using that instead of resorting to the Cardano helper on your repo possibly fix anything here? This was my idea of a work-around.

**Comment by kylixafonso** [comment]
Seems to be fixed! Thank you very much, do you know what the cause was?

**Comment by kylixafonso** [comment]
Turns out it isn't fixed, yesterday TVL was showing the wrong information but an hour+.

**Pull request merged**
