### PR TITLE
Add klayportal tvl

### PR DESCRIPTION
**Pull request by HashQuark-Research1**
##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

hashquark

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/klayportal/index.js exports TVL: 
        
 
 
    klaytn                    20.82 M
    
    total                    20.82 M

**Comment by g1nt0ki** [comment]
HI, do users get some sort of token back when they stake? something like stETH?

**Comment by HashQuark-Research1** [comment]
> HI, do users get some sort of token back when they stake? something like stETH?

Hi, the user won't get the liquid token. They can call "withdraw" to get their origin $KLAY.

**Comment by g1nt0ki** [comment]
Sorry but I dont think this qualifies as defi and afraid we cant list it.

**Comment by HashQuark-Research1** [comment]
> Sorry but I dont think this qualifies as defi and afraid we cant list it.

Hi, we are the same tool like [klaystaion](https://defillama.com/protocol/klaystation) you have list, which is a staking contract to help users get staking functionality in Klaytn. We store the user's assets in our contract, athough we didn't issue an  "ERC20" stand token.  You can find our project at Klaytn ecosystem website: [klaytn ecosystem](https://www.klaytn.com/ecosystem),  the "Staking Service" part.

**Comment by HashQuark-Research1** [comment]
> could you explain what happens with the staked tokens?

Hi, as Klaytn doesn't have the delegation functionality in default, the staked KLAY in our contract will be deposited to our "cnStakingContract", which is our staking account at Klaytn network, to get the ability of staking/delegation. And you need to be a consensus node (CN) to get this staking account at Klaytn network.

**Comment by llamatester** [comment]
The adapter at projects/klayportal exports TVL: 
        
 
 
    klaytn                    18.94 M
    
    total                    18.94 M

**Comment by g1nt0ki** [comment]
> > could you explain what happens with the staked tokens?
> 
> Hi, as Klaytn doesn't have the delegation functionality directly, the staked KLAY in our contract will be deposited to our "cnStakingContract", which is our staking account at Klaytn network, to get the ability of staking/delegation. And node needs to be a consensus node (CN, aka Validator Node) to get this staking account at Klaytn network.
> 
> When users want to withdraw deposited KLAY, they would call our contract, then the KLAY will be sent from our "cnStakingContract" to user's account.

You are correct, I had another discussion with the team, merging the PR now :)

**Pull request merged**
