### PR TITLE
KELLER CL TVL UPDATE

### PR DESCRIPTION
**Pull request by 0xArata**
We have been taking into account only the amount of tokens deposited through the vault without what is in the pool. Therefore, we have modified the adapter so that it only adds the amount deposited in the pool.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/keller exports TVL: 
        
 
 
    scroll                    9.51 k
    scroll-staking            0
    staking                   0
    
    total                    9.51 k

**Comment by llamatester** [comment]
The adapter at projects/keller-CL exports TVL: 
        
 
 
    scroll                    104.27 k
    
    total                    104.27 k

**Comment by g1nt0ki** [comment]
this is steer product already counted as part of steer tvl?

**Comment by g1nt0ki** [comment]
this is a duplicate of https://github.com/DefiLlama/DefiLlama-Adapters/pull/10167#issuecomment-2105085037 where I already mentioned that we wont doublecount tvl

**Pull request closed without merging**
