### PR TITLE
Add Polygon & Base to Guru & E3

### PR DESCRIPTION
**Pull request by ftm1337**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/E3 exports TVL: 
        
 
 
    base                      16.56 k
    fantom                    1.27 k
    arbitrum                  23.96 k
    
    total                    41.78 k

**Comment by llamatester** [comment]
The adapter at projects/Guru exports TVL: 
        
 
 
    echelon                   0
    avax                      1.58 k
    bsc                       109.58 k
    polygon                   2.10 k
    arbitrum                  50.00 k
    fantom                    83.20 k
    metis                     10.38 k
    multivac                  219.06 k
    kcc                       202.20199999999997
    
    total                    476.11 k

**Comment by g1nt0ki** [comment]
@ftm1337 thanks for the PR, for E3 it looks good, but I dislike we have no clue where tvl comes from for Guru. 

For a long time, you still have tvl for echelon even though the chain was delisted, had no liquidity, I had to manually set tvl to 0. Another example is multivac with 219k as tvl, I am struggling to find where it is coming from,  can you break it down per protocol & tokens?

**Comment by ftm1337** [comment]
echelon - i dont know what to do about echelon..its dead but a new team took ever, but its still dead on a similar level.. i think we should remove it entirely from this adapter (i'll edit)
multivac - its mostly from here https://mtv.guru/LF/ (some farms & staking hosted on guru's "Lite Farmlands", its a farms-as-a-service thing)
the calculation is done with the TvlGuru contract, it tracks the onchain price of tokens (and LPs) using their biggest known uni-v2 pool. an easy to follow example would be the polygon version, which started 2 days back https://polygonscan.com/address/0x18c7ad880a07d363f2d034a8523ae34b8068845a it takes in the inputs from the contracts added to it (GuruMultiRewardFarmland in this case, https://polygonscan.com/address/0xc4c807aee35f75c891cb51ef982c98371b1362b4). similarly on all other chains. there are getter methods on the TvlGuru contract to show all the contracts and asset/route/calculation structs for each contract's tvl that it counts. since its all mixed-kind of tvls, defillama puts Guru under the double count category.. since it also includes its own autocompounders/vaults etc. The original intro to the methodology is here https://github.com/DefiLlama/DefiLlama-Adapters/pull/1187 . i guess i can make a little ui that shows a list of all of them in real time, sounds like a nice weekend project

**moving this to a draft for now to delete the echelon part*

**Comment by g1nt0ki** [comment]
@ftm1337 dont remove echelon, it is needed for historical chart reasons (till we find a workaround to skip it from current tvl but maintain in historical chart)

I was just surprised that farm tvl is like 4 times the tvl of dex on multivac, maybe on chain pricing of tokens is wrong?

**Pull request merged**
