### PR TITLE
Add RIZE TVL

### PR DESCRIPTION
**Pull request by zhshy11**
**NOTE**
Add RIZE TVL
#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Twitter Link:
https://x.com/RIZE_Fi

##### Website Link:
https://www.rizefi.com/

##### Logo (High resolution, will be shown with rounded borders):
https://www.rizefi.com/logo.svg

##### Current TVL: 
1M USD

##### Chain:  
Ethereum, SUI

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/rize exports TVL: 
        
 
 
    ethereum                  1.10 M
    
    total                    1.10 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
@zhshy11 thanks for the PR but it is not very clear what your protocol does, also current implementation is not scalable as #logs keep going up over time, also maybe there is a bug as you are counting only the deposits but not withdrawals?

**Comment by zhshy11** [comment]
> @zhshy11 thanks for the PR but it is not very clear what your protocol does, also current implementation is not scalable as #logs keep going up over time, also maybe there is a bug as you are counting only the deposits but not withdrawals?
   
Below are the answers to your questions.
1. The contract does not store TVL information; it can only be obtained by parsing log entries.
2. The contract is cross-chained to the Sui network via whole, allowing users to achieve higher yields. The contract code has also been verified on the etherscan browser.
3. The withdrawal functionality is still in the development phase.

I sincerely hope that the code can be merged quickly, so that everyone can learn about our project.

**Comment by g1nt0ki** [comment]
hi, it is still not very clear what the project does. User deposits into your contract in Ethereum and it brides tokens to SUI? also, dont see the point of hurrying the listing when the project is not open to public and users cant withdraw their coins

**Comment by JackyWYX** [comment]
> hi, it is still not very clear what the project does. User deposits into your contract in Ethereum and it brides tokens to SUI? also, dont see the point of hurrying the listing when the project is not open to public and users cant withdraw their coins

The project RIZE aims at bringing cross-chain high yield APY opportunity to Ethereum community. Currently, RIZE smart contract do the following for user deposit assets:
1. Bridge user assets to SUI with wormhole bridge. The recipient address is a smart contract object on SUI. 
2. Claim the assets on SUI, and deposit user assets to the staking protocol to have yields. 

Our current solution is based on get logs, because it's currently impossible to calculate the TVL on SUI because that will require importing package @mysten/sui.js, which forbids us to calculate the TVL by calling a smart contract read interface. We also checked other SUI projects, which explicitly call for external API for TVL. Since DeFiLlama have explicitly requested us to calculate the TVL on-chain, the only solution we have is to process through logs, which is the solution we have right now. Please give us better instruction on how to calculate the TVL properly. Thanks.

Regarding the withdraw feature, it will be launched when we fully decentralize the protocol in beta version, with cross-chain message sync, deposit&withdraw along with rebase mechanism. You may take a looks at [this doc](https://www.notion.so/High-Level-Design-36d6932e0a4b4e6f84ab099adcc377f1?pvs=4) if you are interested. 

We are currently in alpha stage which allow user to participate early, and we are already public. May I ask how does DefiLlama defines the timing for the listing? And how do you guys evaluate some other protocols only allow deposit, E.g. early stage blast, manta, e.t.c?

**Comment by zhshy11** [comment]
> hi, it is still not very clear what the project does. User deposits into your contract in Ethereum and it brides tokens to SUI? also, dont see the point of hurrying the listing when the project is not open to public and users cant withdraw their coins

Hi, is there anything else that is unclear? I hope to be merged it smoothly.

**Comment by g1nt0ki** [comment]
@JackyWYX cant we read the smart contract state via rest api calls without adding an npm dep? I have done that for a few sui projects

**Comment by llamatester** [comment]
The adapter at projects/rize exports TVL: 
        
 
 
    ethereum                  1.24 M
    
    total                    1.24 M

**Pull request closed without merging**
