### PR TITLE
Metapoly: Project added

### PR DESCRIPTION
**Pull request by AdityaPune**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

##### Twitter Link:
https://twitter.com/metapolyorg

##### List of audit links if any:
Not yet

##### Website Link:
https://www.metapoly.org/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
Please use Twitter PFP

##### Current TVL:
520

##### Chain:
Kava and Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
NA

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
NA

##### Short Description (to be shown on DefiLlama):
Metapoly is the Metaverse Land Bank where you can deposit your NFTs to borrow assets.

##### Token address and ticker if any:
0xEa6cFeAcD4c7f29bD56b0d42083e12f0430cd2D3

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### forkedFrom (Does your project originate from another project):
NA

##### methodology (what is being counted as tvl, how is tvl being calculated):
The amount of USDC deposited and the interest accrued over it, is used to calculate the TVL

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/seeder exports TVL: 
        
 
 
    bsc                       20.52 k
    
    total                    20.52 k

**Comment by llamatester** [comment]
The adapter at projects/metapoly exports TVL: 
        
 
 
    ethereum                  521.838121056
    kava                      0
    
    total                    521.838121056

**Comment by llamatester** [comment]
The adapter at projects/metapoly exports TVL: 
        
 
 
    kava                      0
    kava-borrowed             0
    ethereum-borrowed         0
    ethereum                  520.796528
    borrowed                  0
    
    total                    520.796528

**Comment by g1nt0ki** [comment]
@AdityaPune thanks for the PR, I have updated code to split borrowed tokens from tvl, if you are fine with the logic, I can merge it.

**Comment by AdityaPune** [comment]
@g1nt0ki that works. Please merge the changes for now.

**Comment by Define101** [comment]
Hi guys
Can't find that address Token address
Could you provide us with the link?

**Comment by AdityaPune** [comment]
Hey there, could we skip the token for now?

**Comment by Define101** [comment]
Yes of course
Once you guys have it, feel free to let us know on discord and we will add it

**Comment by AdityaPune** [comment]
Yes, will do

**Comment by Define101** [comment]
And can we use this logo?
image

**Comment by AdityaPune** [comment]
Yes that's correct

**Pull request merged**
