### PR TITLE
Add WOOFi

### PR DESCRIPTION
**Pull request by merlincdj**
##### Twitter Link:
https://twitter.com/WOOnetwork

##### List of audit links if any:
https://www.certik.com/projects/woofiswap

##### Website Link:
https://fi.woo.org/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://oss.woo.org/static/icons/WOOFi.png

##### Current TVL:
$27,362,278

##### Chain:
BSC

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
woo-network

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
1289

##### Short Description (to be shown on DefiLlama):
WOOFi is a multichain DeFi platform which offers the best trade execution and lowest swap fee, opportunities to earn sustainable yields on crypto, and a high-efficiency solution for on-chain liquidity provision.

##### Token address and ticker if any:
Ethereum:0x4691937a7508860f876c9c0a2a617e7d9e945d4b
BSC:0x4691937a7508860f876c9c0a2a617e7d9e945d4b
Fantom:0x6626c47c00f1d87902fc13eecfac3ed06d5e8d8a
Avalanche:0xabc9547b534519ff73921b1fba6e672b5f58d083
Polygon:0x1B815d120B3eF02039Ee11dC2d33DE7aA4a8C603
Arbitrum:0xcAFcD85D8ca7Ad1e1C6F82F651fA15E33AEfD07b
Heco:0x3befb2308bce92da97264077faf37dcd6c8a75e6
OKExChain:0x5427a224E50A9aF4d030AeeCD2a686D41F348DFE
Solana:E5rk3nmgLUuKUiS94gg4bpWwWwyjCMtddsAXkTFLtHEy

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Dexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### methodology (what is being counted as tvl, how is tvl being calculated)
Liquidity - The sPMM liquidity pool.
Stake - The platform's own governance token. Allow users to stake WOO tokens to capture the fee from WOOFi Swap and Earn and increase their yield on WOO token.
Earn - A DeFi yield optimizer.

### CODE REVIEW

**Comment by merlincdj** [comment]
WOOFi will become multi-chain in the future, using our API will be easy to expand in woofi.js.

**Comment by waynebruce0x** [comment]
You'll need to export different chains separately anyway

**Comment by merlincdj** [comment]
I agree, but the work of separate chains can be done in API layer. On the other side, `Earn` can't only using on-chain calls, there're token price factor that from API to calculate the TVL.

**Comment by merlincdj** [comment]
Not open source, aggregate `DODO` on BSC

**Comment by waynebruce0x** [comment]
What's WooPP counting? If the API isn't open source it makes it really hard for us to validate the data coming from it. We'll need an on-chain adapter. We can help write it if you need a hand

**Comment by merlincdj** [comment]
`WooPP`(`0xbf365Ce9cFcb2d5855521985E351bA3bcf77FD3F`) as the liquidity of trading contract, using in contract `WooRouter`(`0x114f84658c99aa6EA62e3160a87A16dEaF7EFe83`) for user to trade.

**Comment by waynebruce0x** [comment]
We'll need an on-chain adapter, because the source of TVL isn't transparent enough. The DefiLlama team can write it for you if you can give use the relevant contract addresses and a short break down on how you're calculating TVL

**Comment by skyinthesea-woo** [comment]
@waynebruce0x  thanks for the detailed explanation and careful review.  This is alex, i'm leading the defi dev of woofi swap and earn. We definitely want to best follow your listing guidelines.

Solution 1: we're willing to add you into our API code repo, so that you can check and monitor our code of calculating TVL (basically it iterates our swap/stake/earn, and extracting the token balance from smart contracts and times the token price). Since it's already finished and being used by our fi.woo.org frontend page.

Solution 2: if still "on-chain" adapters are preferred, we also get a list of our swap/stake/earn smart contracts here. The number of current smart contracts is around 10, but we're adding more earn vaults every week.

We're thinking Solution #1 is the most eng efficient way to go. Also the data API will be actively maintained by our team for any new vaults in the future. But we're also open to the second solution if you guys have the engineering bandwidth to help us on the on-chain adapter.

**Comment by skyinthesea-woo** [comment]
BTW, just added you into our API repo: https://github.com/woonetwork/woofi_swap_backend/invitations

Code to calculate the WooPP (our woo's swap pool)'s TVL:
https://github.com/woonetwork/woofi_swap_backend/blob/792d1ce1e27f61bf7024e97bdd1b318e83a47f3d/helpers.py#L142

Earn's tvl:
https://github.com/woonetwork/woofi_swap_backend/blob/792d1ce1e27f61bf7024e97bdd1b318e83a47f3d/helpers.py#L170

Stake balance:
https://github.com/woonetwork/woofi_swap_backend/blob/792d1ce1e27f61bf7024e97bdd1b318e83a47f3d/api/staking/views.py#L53

**Comment by skyinthesea-woo** [comment]
@waynebruce0x  cool, thanks for your help!!  BTW, our webpage is: https://fi.woo.org/ . Feel free to try our product and also check our TVL on the page :-D

**Pull request merged**
