### PR TITLE
Add missing hallmarks and blast protocol contract

### PR DESCRIPTION
**Pull request by Kostydenis**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/envelop exports TVL: 
        
 
 
    arbitrum                  0
    optimism                  0
    avax                      0
    blast                     3.74 k
    bsc-staking               0
    ethereum-staking          0
    bsc                       573.4248737689401
    ethereum                  93.553489178056
    polygon                   88.00142718403865
    polygon-staking           0
    staking                   0
    
    total                    4.50 k

**Comment by llamatester** [comment]
The adapter at projects/envelop exports TVL: 
        
 
 
    arbitrum                  0
    optimism                  0
    bsc-staking               0
    avax                      0
    polygon-staking           0
    bsc                       573.0655938848581
    polygon                   87.99898262833864
    ethereum-staking          0
    blast                     8.02 k
    ethereum                  93.4858691
    staking                   0
    
    total                    8.78 k

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
I excluded these hallmarks because they have minimal impact on the tvl chart. We usually add only those that cause a big change, like luna crashing. 

The reason for this is, too many events clog up the chart and act as hindrance to the user. but if you really want the hallmarks, can you restrict it to two?

**Comment by llamatester** [comment]
The adapter at projects/envelop exports TVL: 
        
 
 
    arbitrum                  0
    optimism                  0
    avax                      0
    polygon-staking           0
    polygon                   87.7639202747601
    ethereum                  93.879027624629
    ethereum-staking          0
    blast                     8.06 k
    bsc-staking               0
    bsc                       572.5992014940932
    staking                   0
    
    total                    8.82 k

**Comment by Kostydenis** [comment]
Ok, I've made changes and leave only two items

**Pull request merged**
