### PR TITLE
Added new KFT token for stacking.

### PR DESCRIPTION
**Pull request by InbuiltFinanceDev**
Twitter Link: https://twitter.com/Inbuiltfinance

List of audit links if any: 

Website Link: http://inbuilt.finance/

Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

Inbuilt Finance

Current TVL: $928.0649

Chain: KAVA

Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

Coinmarketcap ID (so your TVL can appear on Coinmarketcap): https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000

Short Description (to be shown on DefiLlama): Liquid stacking protocol for all the assets.

Token address and ticker if any: 

Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one: Staking

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using): custom

forkedFrom (Does your project originate from another project): no

methodology (what is being counted as tvl, how is tvl being calculated): Total values of all token stacked on our platform.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/inbuilt-finance exports TVL: 
        
 
 
    kava                      1.33 k
    
    total                    1.33 k

**Comment by g1nt0ki** [comment]
@InbuiltFinanceDev are you linked in any way to weld finance or knit team?

**Comment by g1nt0ki** [comment]
closing this as there was no answer

**Comment by InbuiltFinanceDev** [comment]
We have no relations with Knit team.

**Pull request closed without merging**
