### PR TITLE
Update Velodrome TVL to Handle for V2 on OP Mainnet

### PR DESCRIPTION
**Pull request by MSilb7**
Testing the TVL function to validate correctness.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/velodrome: 
        
 
  
    
    
    TypeError: address.toLowerCase is not a function
    Truncated error stack:
    
        at normalizeAddress (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/tokenMapping.js:98:18)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/cache/uniswap.js:30:15
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:29)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:136:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:131:44

**Comment by MSilb7** [comment]
^ Setting this up may be beyond my understanding, but the content to make whatever changes are required are included

**Comment by llamatester** [comment]
Error while running adapter at projects/velodrome: 
        
 
  
    
    
    TypeError: address.toLowerCase is not a function
    Truncated error stack:
    
        at normalizeAddress (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/tokenMapping.js:98:18)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/cache/uniswap.js:30:15
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:29)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:136:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:131:44

**Comment by g1nt0ki** [comment]
hi @MSilb7 , thanks for the PR, I have fixed it here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/2b0f365c2e69981b9af8171365f7567ab45f95f6

**Pull request closed without merging**
