### PR TITLE
TVL Script correction

### PR DESCRIPTION
**Pull request by Anirudha619**
---
##### Logo :
MagnumLogo

##### Short Description (to be shown on DefiLlama):
Sharpe Magnum is a leveraged staking layer built on top of Lido stETH. Magnum functions as a staking optimizer, enhancing the capital efficiency of staking pools by leveraging staked assets via lending protocols and flashloans while keeping the same underlying guarantees. 

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL calculation methodology involves accounting for the total value of assets engaged in our protocol, which encompasses both staked and leveraged positions, as well as the assets borrowed through flashloans. To compute the Total Value Locked (TVL), we sum up the total amount of stETH staked in the protocol (Total_Staked_stETH), the leveraged amount of stETH used as collateral for borrowed assets (Leveraged_stETH), and the total value of assets borrowed via flashloans (Total_Borrowed_Assets).

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/SharpeLabs exports TVL: 
        
 
 
    ethereum                  57.75 k
    
    total                    57.75 k

**Comment by g1nt0ki** [comment]
@Anirudha619 sorry, I think this computation is wrong, tvl must be "supplied - borrowed" not "supplied+borrowed"

**Comment by rishabhng** [comment]
@g1nt0ki Clarification on TVL Calculation for our Magnum Lido stETH Pool - Seeking Feedback

In light of providing higher transparency, I would like to explain the methodology behind our Total Value Locked (TVL) calculation for our Magnum vault. I encourage you to share your thoughts and feedback on our approach.

Our vault allows users to stake their assets and engage in leveraged positions through Morpho using Magnum. **For every 1 ETH invested, the TVL locked in Morpho through Magnum is 5 ETH** The TVL represents the total value of assets engaged in our protocol, which includes staked and leveraged positions, as well as the assets borrowed through flashloans to create a leveraged position.

To better illustrate our TVL calculation:

User_Deposited_ETH: This is the total amount of ETH a user has deposited in the vault.

Leveraged_stETH: This represents the leveraged amount of stETH used as collateral for borrowed assets.

Total_Borrowed_Assets: This is the total value of assets borrowed via flashloans.

We compute the TVL by summing up these three components:

TVL = User_Deposited_ETH + Leveraged_stETH + Total_Borrowed_Assets

Our TVL calculation for Magnum vault has a direct impact on Morpho's calculation, **as Morpho accounts for 5 ETH locked in their pool for every 1 ETH a user deposits on Magnum** This relationship between the user's deposit and the locked amount in Morpho is a result of leveraging and flashloans.

When a user deposits 1 ETH, our vault locks 5 ETH in Morpho, which can be represented as:

Locked_in_Morpho = User_Deposit × Leverage_Factor

Where, the Leverage_Factor is 5 includes both Lend exposure + Borrow exposure

Please let me know if there any further questions on the TVL calculation and I'd be happy to answer them.

**Comment by g1nt0ki** [comment]
hi @rishabhng, I understand what you are saying but we (defillama) view tvl differently, we consider only total user deposits as tvl. We apply the same rule to other protocols offering leverage like gearbox

**Pull request closed without merging**
