### PR TITLE
update lyve to defillama

### PR DESCRIPTION
**Pull request by LyveFinance**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
LyveFinance

##### Twitter Link:
https://twitter.com/LyveFinance

##### Website Link:
https://www.lyvefi.xyz/

##### Logo (High resolution, will be shown with rounded borders):
https://www.lyvefi.xyz/tokens/lyu.png

##### Current TVL:
$32,578

##### Chain:
linea

##### Short Description (to be shown on DefiLlama):
#1 Stable token $LYU backed by LST 
Move your LST across layer2s freely
Max Asset Flexibility & Capital Efficiency

##### Token address and ticker if any:
0xb20116eE399f15647BB1eEf9A74f6ef3b58bc951

##### Category (full list at https://defillama.com/categories) *Please choose only one:
CDP

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### forkedFrom (Does your project originate from another project):
gravitaprotocol

##### methodology (what is being counted as tvl, how is tvl being calculated):
USD

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/lyve exports TVL: 
        
 
 
    linea                     32.29 k
    
    total                    32.29 k

**Comment by LyveFinance** [comment]
the Category is CDP,I changed it

**Comment by g1nt0ki** [comment]
I think it is better to create a new listing for it instead of cannibalizing an existing listing. Out of curiosity what happened to the dex dapp? I see see about 1.6M tvl

**Comment by g1nt0ki** [comment]
also, can you split it into two PRs, one for tvl metric and other for liquidation?

**Comment by LyveFinance** [comment]
> I think it is better to create a new listing for it instead of cannibalizing an existing listing. Out of curiosity what happened to the dex dapp? I see see about 1.6M tvl

1.6M ?? No, only $32,241

**Comment by llamatester** [comment]
The adapter at projects/lyve exports TVL: 
        
 
 
    linea                     32.33 k
    
    total                    32.33 k

**Comment by g1nt0ki** [comment]
closing this as it is split into two new PRs

**Pull request closed without merging**
