### PR TITLE
Add The Vault

### PR DESCRIPTION
**Pull request by rockooor**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
The Vault

##### Twitter Link:
https://x.com/thevaultfinance

##### List of audit links if any:
https://docs.thevault.finance/risks

##### Website Link:
https://thevault.finance/

##### Logo (High resolution, will be shown with rounded borders):
https://thevault.finance/images/logo/logo.svg

##### Current TVL:
428,663 SOL
$65,977,475.61

##### Chain:
Solana

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
the-vault-staked-sol

##### Short Description (to be shown on DefiLlama):
vSOL is a stake pool that supports community-focused validators. Stake with us now to support the Solana native communities! At The Vault, we believe the Solana network will be the strongest if the network is secured by validators that have a large social stake in Solana. Most top validators by stake amount are not Solana focused entities, but instead represent the crypto industry in general. The Vault stake pool will strive to bring the financial stake in-line with the existing social stake of Solana-centric communities.  

##### Token address and ticker if any:
Address: vSoLxydx6akxyMD9XEcPvGYNGq6Nn66oqVb3UkGkei7
Ticker: vSOL

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Liquid Staking

##### forkedFrom (Does your project originate from another project):
SPL Stake Pool

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is based on total minted vSOL token, which represents the underlying SOL in the stake pool

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/thevault exports TVL: 
        
 
 
    solana                    65.99 M
    
    total                    65.99 M

**Comment by llamatester** [comment]
The adapter at projects/blazestake exports TVL: 
        
 
 
    solana                    344.83 M
    
    total                    344.83 M

**Comment by llamatester** [comment]
The adapter at projects/jpool.js exports TVL: 
        
 
 
    solana                    51.28 M
    
    total                    51.28 M

**Comment by llamatester** [comment]
The adapter at projects/marinade-native exports TVL: 
        
 
 
    solana                    424.15 M
    
    total                    424.15 M

**Comment by llamatester** [comment]
The adapter at projects/solana_miner exports TVL: 
        
 
 
    solana                    0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/thevault exports TVL: 
        
 
 
    solana                    65.96 M
    
    total                    65.96 M

**Comment by g1nt0ki** [comment]
@rockooor thanks for the PR

**Pull request merged**
