### PR TITLE
Lenlen

### PR DESCRIPTION
**Pull request by clarencesea**
##### methodology (what is being counted as tvl, how is tvl being calculated):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/lenlen exports TVL: 
        
 
 
    
    total                    4.33 M

**Comment by realdealshaman** [comment]
@clarencesea Hi, thank you for the PR, however we are no longer accepting fetch adapters and are alternatively working towards updating any that still rely on an api. Can you update the adapter so that it uses on-chain calls instead? We have the compound v3 adapter that can be used as a guide: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/compound-v3/index.js

**Comment by llamatester** [comment]
The adapter at projects/compound-v3 exports TVL: 
        
 
 
    ethereum-borrowed         147.66 M
    ethereum                  489.63 M
    borrowed                  147.66 M
    
    total                    489.63 M

**Comment by llamatester** [comment]
The adapter at projects/lenlen exports TVL: 
        
 
 
    vision-borrowed           1.25 M
    vision                    2.53 M
    borrowed                  1.25 M
    
    total                    2.53 M

**Pull request merged**
