### PR TITLE
Hope-Staking

### PR DESCRIPTION
**Pull request by XuMinhui**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Hope-Staking
---
We Hope
# Hope Finance
## Hope-Staking
Showcase it like this.

##### Twitter Link:
https://twitter.com/Hope_money_

##### Website Link:
https://hope.money/

##### Treasury Addresses (if the protocol has treasury)
HOPE                      2.38 M
Total: 2.38 M 

##### Chain:
Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
https://www.coingecko.com/en/coins/hope-2

##### Category (full list at https://defillama.com/categories) *Please choose only one:
0xc353bf07405304aeab75f4c2fac7e88d6a68f98e

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
https://etherscan.io/address/0x231118439630f93F8A12A2FaA66e95DB138D9B21#readContract

##### forkedFrom (Does your project originate from another project):
https://github.com/DefiLlama/DefiLlama-Adapters

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/hope-staking exports TVL: 
        
 
 
    ethereum                  2.38 M
    
    total                    2.38 M

**Comment by XuMinhui** [comment]
hello, what is the situation now, please?

**Comment by XuMinhui** [comment]
Hi admin, first of all, thanks for the inclusion!

But there are a couple of small issues that I need your help to fix
This is the current catalog
image
The page display we expect is
image
Here is a detailed description of the modifications

1. The first level heading HOPE Money => HopeMoney (note the case and no space), the icon is changed to: https://icons.llamao.fi/icons/protocols/hope-collateral?w=48&h=48
2. the secondary heading "Hope Collateral" is changed to "Hope Staking", the type belongs to "Liquity Satking". The icon for this item should be changed to https://icons.llamao.fi/icons/protocols/hope-collateral?w=48&h=48
3. "HOPE Swap" changed to "Hope Swap" type is "Dexes"
4. "HOPE Lend" changed to "Hope Lend" type is "Lending"

Note: Our team is a group of obsessive-compulsive members and pays close attention to details, we hope you can pay attention to case and icon during the modification process, thank you very much!

**Comment by g1nt0ki** [comment]
hi @XuMinhui ,
name and icon change is fine, we will do it, but second point, where you want to change "Hope Staking" wouldnt work as it is a different product, we are counting backing of HOPE, and we skip HOPE staking as a sub product because it is your own token being staked whose backing we are already counting. "Liquid Staking" is meant for products like Lido stETH or stSTOL

**Comment by XuMinhui** [comment]
Okay, thank you.

And a couple of small requests.
1. Hope Swap's icon doesn't seem to have been replaced, the current edge is a little problematic, his correct one should be
https://icons.llamao.fi/icons/protocols/hope-collateral?w=48&h=48

2. " Hope Collateral" we would still like to see as " Hope Staking" and if it doesn't match the "Liquity Staking" type, we would like it to read as "Hope Staking". "Dexes" instead of "Cross Chain".

3. I would like to show us the prices of the two platform governance tokens, "HOPE" and "LT".
We have CoinGecko link:
HOPE: https://www.coingecko.com/en/coins/hope-2
LT: https://www.coingecko.com/en/coins/light-token
I can also provide adapters that fit the format, but I don't know how to do that!

I think I can get help here, right?

**Comment by XuMinhui** [comment]
ADDITIONAL: Regarding the price display, I tried to look at the current projects that have the option to display the price, but I did not see an example from their adapter code. So I thought it would be helpful to get help from here

**Comment by XuMinhui** [comment]
hey,sir

**Comment by g1nt0ki** [comment]
> ADDITIONAL: Regarding the price display, I tried to look at the current projects that have the option to display the price, but I did not see an example from their adapter code. So I thought it would be helpful to get help from here

hi @XuMinhui price info comes when you set the gecko_id here: https://github.com/DefiLlama/defillama-server/commit/db8c613f7b12d77b9b0c27cf78d85df52df0d7b8#diff-59cced486abfc79f155749e8bc5d663f59a8ba9c04cf016b9b40e94d66b9fc90

**Comment by XuMinhui** [comment]
> Okay, thank you.
> 
> And a couple of small requests.
> 
> 1. Hope Swap's icon doesn't seem to have been replaced, the current edge is a little problematic, his correct one should be
>    https://icons.llamao.fi/icons/protocols/hope-collateral?w=48&h=48
> 2. " Hope Collateral" we would still like to see as " Hope Staking" and if it doesn't match the "Liquity Staking" type, we would like it to read as "Hope Staking". "Dexes" instead of "Cross Chain".
> 3. I would like to show us the prices of the two platform governance tokens, "HOPE" and "LT".
>    We have CoinGecko link:
>    HOPE: https://www.coingecko.com/en/coins/hope-2
>    LT: https://www.coingecko.com/en/coins/light-token
>    I can also provide adapters that fit the format, but I don't know how to do that!
> 
> I think I can get help here, right?



> Okay, thank you.
> 
> And a couple of small requests.
> 
> 1. Hope Swap's icon doesn't seem to have been replaced, the current edge is a little problematic, his correct one should be
>    https://icons.llamao.fi/icons/protocols/hope-collateral?w=48&h=48
> 2. " Hope Collateral" we would still like to see as " Hope Staking" and if it doesn't match the "Liquity Staking" type, we would like it to read as "Hope Staking". "Dexes" instead of "Cross Chain".
> 3. I would like to show us the prices of the two platform governance tokens, "HOPE" and "LT".
>    We have CoinGecko link:
>    HOPE: https://www.coingecko.com/en/coins/hope-2
>    LT: https://www.coingecko.com/en/coins/light-token
>    I can also provide adapters that fit the format, but I don't know how to do that!
> 
> I think I can get help here, right?

What is the problem I mentioned above? Can you help me

**Pull request closed without merging**
