### PR TITLE
ociswap tvl data for basic and precision pools

### PR DESCRIPTION
**Pull request by ChrisPantostin**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/ociswap-basic exports TVL: 
        
 
 
    radixdlt                  3.41 M
    
    total                    3.41 M

**Comment by llamatester** [comment]
The adapter at projects/ociswap-precision exports TVL: 
        
 
 
    radixdlt                  3.23 M
    
    total                    3.23 M

**Comment by g1nt0ki** [comment]
@ChrisPantostin thanks for the PR

what are these pools and can you update the adapter to pull the tvl data on chain?

**Comment by fpieper** [comment]
@g1nt0ki 
These two pools are the currently deployed Ociswap (ociswap.com) pools `Basic Pool` (similar to Uniswap v2) and `Precision Pool` (similar to Uniswap v3)
https://docs.ociswap.com/ociswap-dex/liquidity-pools

The reason why we didn't use on-chain data directly was that many tokens don't have prices on Coingecko yet and therefore we used a similar approach than other dexes on Radix like https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/caviarnine-shapeliquidity/index.js

To protect against manipulation we are filtering and aggregating prices of the tokens across all pools and since this is the critical part there is not much difference between getting the TVL directly or getting the prices from our API and multiply with the token amounts on-chain.

**Pull request merged**
