### PR TITLE
Properly name hyperjump (hyperswap) and add bsc and metis swap tvl

### PR DESCRIPTION
**Pull request by angry-mech**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by g1nt0ki** [comment]
is this your new website? https://quasarswap.xyz/

**Comment by llamatester** [comment]
The adapter at projects/hyperjump exports TVL: 
        
 
 
    metis                     7.79 k
    bsc                       165.84 k
    fantom                    416.02 k
    
    total                    589.65 k

**Comment by angry-mech** [comment]
> is this your new website? https://quasarswap.xyz/

no. its 
hyperjump.app

**Comment by angry-mech** [comment]
> The adapter at projects/hyperjump exports TVL:
> 
> ```
> metis                     7.79 k
> bsc                       165.84 k
> fantom                    416.02 k
> 
> total                    589.65 k 
> ```

thank you!

**Comment by g1nt0ki** [comment]
> > is this your new website? https://quasarswap.xyz/
> 
> no. its hyperjump.app

sorry, pasted the wrong link, we have fixed it in our listing: https://defillama.com/protocol/hyperjump

**Comment by angry-mech** [comment]
hey thanks so much! appreciate it. it would be better if you could list hyperjump with the hyperjump token instead of the hypr token.
it is deployed on fantom opera and bridged by synapse to bsc and metis.

hyperjump ($jump)
fantom: 0x78de9326792ce1d6eca0c978753c6953cdeedd73
metis: 0xE3c82A836Ec85311a433fBd9486EfAF4b1AFbF48
bsc: 0x130025eE738A66E691E6A7a62381CB33c6d9Ae83

**Pull request merged**
