### PR TITLE
Firoza

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/stride exports TVL: 
        
 
 
    cosmos                    23.88 M
    dydx                      23.25 M
    celestia                  8.71 M
    osmosis                   8.29 M
    islm                      5.69 M
    evmos                     778.88 k
    dymension                 719.88 k
    juno                      456.67 k
    injective                 393.55 k
    stargaze                  307.89 k
    terra2                    62.52 k
    sommelier                 46.44 k
    umee                      44.12 k
    comdex                    12.03 k
    stride                    0
    
    total                    72.64 M

**Comment by llamatester** [comment]
The adapter at projects/firoza-finance exports TVL: 
        
 
 
    islm                      49.90 k
    islm-borrowed             50
    borrowed                  50
    
    total                    49.90 k

**Comment by xenothanhojem** [comment]
Hey Team, I see this was closed but not merged into main? What is the process here to get Firoza listed?

**Comment by llamatester** [comment]
The adapter at projects/stride exports TVL: 
        
 
 
    dydx                      25.64 M
    cosmos                    21.44 M
    celestia                  10.17 M
    osmosis                   8.80 M
    islm                      6.25 M
    evmos                     879.72 k
    dymension                 870.74 k
    juno                      505.75 k
    injective                 459.55 k
    stargaze                  308.22 k
    terra2                    64.78 k
    umee                      50.39 k
    sommelier                 46.81 k
    comdex                    14.35 k
    stride                    0
    
    total                    75.50 M

**Comment by llamatester** [comment]
The adapter at projects/firoza-finance exports TVL: 
        
 
 
    islm                      49.91 k
    islm-borrowed             50
    borrowed                  50
    
    total                    49.91 k

**Pull request merged**
