### PR TITLE
Add Capyfi protocol

### PR DESCRIPTION
**Pull request by NicolasMenendez**
##### Short Description (to be shown on DefiLlama): 
Capify is an algorithmic decentralized finance protocol built on the LAchain network that allows users to lend and borrow cryptocurrency assets. Suppliers provide liquidity to the market to earn interest, while borrowers are able to borrow liquidity in an over-collateralized fashion. Capyfi's protocol design and architecture references Compound v2, a proven and audited protocol.

##### methodology (what is being counted as tvl, how is tvl being calculated):
The TVL is calculated by adding the value of total deposits in all markets minus the total borrows.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/capyfi exports TVL: 
        
 
 
    lac                       1.44 M
    lac-borrowed              259.34 k
    borrowed                  259.34 k
    
    total                    1.44 M

**Comment by g1nt0ki** [comment]
can you share project website and twitter account?

**Comment by llamatester** [comment]
The adapter at projects/capyfi exports TVL: 
        
 
 
    lac                       134.88 k
    lac-borrowed              119.15 k
    borrowed                  119.15 k
    
    total                    134.88 k

**Comment by g1nt0ki** [comment]
hi @NicolasMenendez thanks for the PR, right now, there is no price support for la chain token on coingecko, it will be fixed once coingecko adds support

**Comment by NicolasMenendez** [comment]
Hi @g1nt0ki! Thanks for your help. Also, we need to map the token for the stablecoin UXD criptodolar (0xDe09E74d4888Bc4e65F589e8c13Bce9F71DdF4c7) https://coinmarketcap.com/currencies/criptodolar/. LAC is already listed on coinmarketcap , can we use it? https://coinmarketcap.com/currencies/lacoin/.

**Comment by g1nt0ki** [comment]
sorry, due their  T&C we cant pull prices from coinmarketcap

**Pull request merged**
