### PR TITLE
microcreditplatform added for application

### PR DESCRIPTION
**Pull request by sarp07**
Name (to be shown on DefiLlama):
MicroCreditPlatform 

Twitter Link:
https://twitter.com/MicroCreditToken

List of audit links if any:
(N/A)

Website Link:
https://microcredittoken.com/ / http://46.20.15.220/

Logo (High resolution, will be shown with rounded borders):

Current TVL:
(TVL bilgisi hesaplamalarınıza göre doldurulmalı)

Treasury Addresses (if the protocol has treasury):
(N/A)

Chain:
HAQQ Network Testnet

Coingecko ID:
(N/A)

Coinmarketcap ID:
(N/A)

Short Description (to be shown on DefiLlama):
MicroCreditToken is a Web3-based microcredit platform that allows social investors to fund micro-entrepreneurs, ensuring transparency and security through smart contracts.

Token address and ticker if any:
Fake USDT: 0xe5CeD8244f9F233932d754A0B1F7268555FBd3B5
Fake MCT: 0x829e43f497b8873fA5c83FcF665b96A39a1FBeD6
Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

Oracle Provider(s):
(N/A)

Implementation Details:
(N/A)

Documentation/Proof:
(N/A)

forkedFrom (Does your project originate from another project):
(N/A)

methodology (what is being counted as tvl, how is tvl being calculated):
TVL is calculated based on the total value locked in the MicroCreditInvestment, CreditDatabase, and MicroCreditProfitShare contracts.

Github org/user (Optional, if your code is open source, we can track activity):
(N/A)

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/microcreditplatform: 
        
 
  
    
    
    Error: 
        Unknown chain(s): haqq
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file
        
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
Error while running adapter at projects/microcreditplatform: 
        
 
  
    
    
    Error: Multicall failed! 
     [chain: haqq] [fail count: 6] [abi: function balanceOf(address account) view returns (uint256)]  
        target: 0xe5ced8244f9f233932d754a0b1f7268555fbd3b5 params: 0xf79b598e856858527573ce0771b872c88887a055]
        target: 0x829e43f497b8873fa5c83fcf665b96a39a1fbed6 params: 0xf79b598e856858527573...
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
Error while running adapter at projects/microcreditplatform: 
        
 
  
    
    
    Error: Multicall failed! 
     [chain: haqq] [fail count: 6] [abi: function balanceOf(address account) view returns (uint256)]  
        target: 0xe5ced8244f9f233932d754a0b1f7268555fbd3b5 params: 0xf79b598e856858527573ce0771b872c88887a055]
        target: 0x829e43f497b8873fa5c83fcf665b96a39a1fbed6 params: 0xf79b598e856858527573...
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
Error while running adapter at projects/microcreditplatform: 
        
 
  
    
    
    Error: TypeError: Cannot read properties of null (reading 'call')
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
Error while running adapter at projects/microcreditplatform: 
        
 
  
    
    
    Error: Multicall failed! 
     [chain: haqq] [fail count: 6] [abi: function balanceOf(address account) view returns (uint256)]  
        target: 0xe5ced8244f9f233932d754a0b1f7268555fbd3b5 params: 0xf79b598e856858527573ce0771b872c88887a055]
        target: 0xe5ced8244f9f233932d754a0b1f7268555fbd3b5 params: 0x3b724e84fd7479c1bed1...
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
@sarp07 thanks for the PR but is the project live? I have no idea what fake USDT /MCT is

**Comment by sarp07** [comment]
Hello @g1nt0ki we are on live you can check for this.

"https://app.microcredittoken.com/"

**Pull request closed without merging**
