### PR TITLE
Add Nirvana tvl

### PR DESCRIPTION
**Pull request by nirvana-sid**

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Can this be exported as staking since its your own platform token?

solana: {
    tvl: () => ({}),
    staking: tvl
  }

**Comment by llamatester** [comment]
The adapter at projects/nirvana exports TVL: 
        
 
 
    solana                    0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/nirvana exports TVL: 
        
 
 
    solana                    0
    solana-staking            17.52 M
    staking                   17.52 M
    
    total                    0

**Comment by waynebruce0x** [comment]
Thanks - can you send the addresses that these tokens are held in? Coingecko says ANA FDV as about 10M so I'm wondering how TVL can be 18M - can this be calculated onchain instead?

**Comment by nirvana-sid** [comment]
Hey guys,  thanks for doing the due diligence on this.  Apparently, coingecko has some unreliable information.  Here are the links to token accounts on solscan for total ANA supply (FDV) and staked ANA.  These values are being calculated on chain since staked ANA only exists in this wallet. 

ANA: https://solscan.io/token/ANAxByE6G2WjFp7A4NqtWYXb3mgruyzZYg3spfxe6Lbo
Staked ANA: https://solscan.io/account/AS5yy4yhAL9pZZau4Mdfuz8yVPdJ4Avsx3X2VofyLGJ3

Let us know if you have any further questions.  Thank you.

**Comment by llamatester** [comment]
The adapter at projects/nirvana exports TVL: 
        
 
 
    solana                    0
    solana-staking            14.98 M
    staking                   14.98 M
    
    total                    0

**Comment by rinswend** [comment]
@waynebruce0x hello! I'm a Nirvana team member. I think there's some confusion about the TVL methodology that led to an inaccurate result at https://defillama.com/protocol/nirvana . If I understand [your comment](https://github.com/DefiLlama/DefiLlama-Adapters/pull/2914#issuecomment-1149371941) correctly, defillama will put the value from Nirvana's own platform token, ANA, in this optional "staking" category. However the protocol also holds a reserve treasury of stablecoins that currently adds up to ~$12.8M:

* https://solscan.io/account/EwQa93fpN2a6smD7EBFjQEyDt3DP8EMLHLjgAWxG9Qhj
* https://solscan.io/account/GX1bJw7nLj7pot1Kfq8UDrzzZVK3HnuyjY5FycErgrzG
* https://solscan.io/account/6t7ViNDULtkgvmntHsmi1QV73Tez7ZcX6DJvARHkfUJZ

Could be the basis for the protocol's base TVL?

**Pull request merged**
