### PR TITLE
Levva adapter

### PR DESCRIPTION
**Pull request by rudewalt**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Levva

##### Twitter Link:
https://x.com/levva_fi

##### List of audit links if any:
https://github.com/levvafi/levva-vault/blob/main/audit/Levva%20Final%20Report.pdf
https://github.com/levvafi/levva-vault/blob/main/audit/Levva%20Oracle%20Feature%20Final%20Report.pdf
https://github.com/levvafi/levva-vault/blob/main/audit/Levva%20Smart%20Contract%20Audit%20Report.pdf

##### Website Link:
https://levva.fi/

##### Logo (High resolution, will be shown with rounded borders):
levva

##### Current TVL:
1.57M USD

##### Chain:
Ethereum, Arbitrum One

##### Short Description (to be shown on DefiLlama):
Levva is an optimized web3 protocol that offers universal yield and leverage in DeFi. Levva provides infrastructure for efficient on-chain liquidity management and connects liquidity providers to borrowers.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Liquidity manager

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
UniswapV3 TWAP, Chainlink, Pyth

##### methodology (what is being counted as tvl, how is tvl being calculated):
Counts the value of base and quote tokens in every Levva pool and Vault

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/levvafi

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/levva exports TVL: 
        
 
 
    ethereum                  1.40 M
    arbitrum                  40.19 k
    blast                     581
    linea                     0
    
    total                    1.44 M

**Comment by rudewalt** [comment]
Error in other project adapter
https://github.com/DefiLlama/DefiLlama-Adapters/actions/runs/12034156758/job/33550021754?pr=12443#step:5:23

```
/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/stargaze/index.js
  6:3  error  Unreachable code  no-unreachable
```

**Comment by llamatester** [comment]
The adapter at projects/levva exports TVL: 
        
 
 
    ethereum                  1.27 M
    arbitrum                  40.14 k
    blast                     586
    linea                     0
    
    total                    1.31 M

**Comment by llamatester** [comment]
The adapter at projects/levva exports TVL: 
        
 
 
    ethereum                  1.46 M
    arbitrum                  58.20 k
    blast                     585
    linea                     0
    
    total                    1.52 M

**Comment by g1nt0ki** [comment]
thanks for the PR

**Pull request closed without merging**
