### PR TITLE
add project StoneDefi

### PR DESCRIPTION
**Pull request by bibodeng**
##### Twitter Link:
https://twitter.com/DefiStone

##### List of audit links if any:
https://www.certik.com/projects/stonedefi

##### Website Link:
https://stonedefi.io

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://www.stonedefi.io/static/media/stone_logod.ee23eb53.png

##### Current TVL:
5.47 M

##### Chain:
Ethereum/BSC/Polygon/Avalanche

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
https://www.coingecko.com/en/coins/stone-token

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
https://coinmarketcap.com/currencies/stone-token/

##### Short Description (to be shown on DefiLlama):
StoneDefi protocol, One stop solid yield staking for cross-chain assets.

##### Token address and ticker if any:
0xe63d6B308BCe0F6193AeC6b7E6eBa005f41e36AB
https://www.ftftx.com/kline/508457.html

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Yield

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### forkedFrom (Does your project originate from another project):
Yearn

##### methodology (what is being counted as tvl, how is tvl being calculated):
Calculate TVL by sum all chains and pools' staked tokens.

### CODE REVIEW

**Comment by Nemusonaneko** [comment]
I'm in the process in creating an adapter that would use onchain data. May I have the contract to where the BNB is staked for STBNB?

**Comment by bibodeng** [comment]
> 

Yeah, there should be contracts list on StoneDefi's docs here: https://docs.stonedefi.io/contracts/stonebank-contracts-bsc

**Comment by Nemusonaneko** [comment]
> > 
> 
> Yeah, there should be contracts list on StoneDefi's docs here: https://docs.stonedefi.io/contracts/stonebank-contracts-bsc The `StoneBank` contract is maybe what you want.

Ah thanks. Where in the contract does it show the amount of BNB staked?

**Comment by bibodeng** [comment]
Hi, there is a `stbnbMarketCapacityCountByBNB` in contract `stoneBank`
https://bscscan.com/address/0xab850E2567248Eb6AA48cFF9137c609Cc4232261#readContract

**Comment by Nemusonaneko** [comment]
> Hi, there is a `stbnbMarketCapacityCountByBNB` in contract `stoneBank` https://bscscan.com/address/0xab850E2567248Eb6AA48cFF9137c609Cc4232261#readContract

Made a call to that method and it returns 0

**Comment by bibodeng** [comment]
> 

Hi, this value should be read by proxy contract via https://bscscan.com/address/0x63598a507b5901721097b1f1407d2ba89d49b3d4#readProxyContract, StoneBank should be adapt in another project. this PR is for StoneDefi.

**Comment by Nemusonaneko** [comment]
Ah thank you.
This is my result 
```
--- bsc-staking ---
STN                       12.61 k
Total: 12.61 k 

--- polygon-staking ---
STN                       9.14 k
Total: 9.14 k 

--- polygon-pool2 ---
STN                       22.23 k
Total: 22.23 k 

--- ethereum-staking ---
STN                       66.41 k
Total: 66.41 k 

--- polygon ---
WETH                      1.48 M
USDT                      467.54 k
USDC                      76.42 k
WMATIC                    38.90 k
WBTC                      26.10 k
DAI                       12.34 k
QUICK                     2.00 k
SUSHI                     1.58 k
Total: 2.10 M 

--- bsc ---
binancecoin               1.17 M
USDT                      569.72 k
USDC                      60.94 k
WETH                      34.16 k
BUSD                      11.74 k
DAI                       10.62 k
WBNB                      8.72 k
CAKE                      1.85 k
MDX                       1.20 k
BTCB                      50.439
Total: 1.87 M 

--- ethereum-pool2 ---
WETH                      20.14 k
STN                       19.82 k
Total: 39.96 k 

--- ethereum ---
USDT                      348.74 k
DAI                       320.82 k
WETH                      316.32 k
AETHC                     117.57 k
USDC                      102.83 k
TPT                       0
Total: 1.21 M 

--- staking ---
STN                       88.17 k
Total: 88.17 k 

--- pool2 ---
STN                       42.05 k
WETH                      20.14 k
Total: 62.19 k 

--- tvl ---
WETH                      1.83 M
USDT                      1.39 M
binancecoin               1.17 M
DAI                       343.77 k
USDC                      240.19 k
AETHC                     117.57 k
WMATIC                    38.90 k
WBTC                      26.10 k
BUSD                      11.74 k
WBNB                      8.72 k
QUICK                     2.00 k
CAKE                      1.85 k
SUSHI                     1.58 k
MDX                       1.20 k
BTCB                      50.439
TPT                       0
Total: 5.18 M 

------ TVL ------
bsc-staking               12.61 k
polygon-staking           9.14 k
polygon-pool2             22.23 k
ethereum-staking          66.41 k
polygon                   2.10 M
bsc                       1.87 M
ethereum-pool2            39.96 k
ethereum                  1.21 M
staking                   88.17 k
pool2                     62.19 k

total                    5.18 M
 ```

**Comment by Nemusonaneko** [comment]
Code in this commit.
https://github.com/DefiLlama/DefiLlama-Adapters/commit/4b305bafc22efb0204b61ac648ac55c5c7836667

**Comment by Nemusonaneko** [comment]
Just noticed that there is no AVAX TVL. Sorry about that. Do you have the staking addresses for them?

**Comment by bibodeng** [comment]
> 

Cool, Yeah, Avalanche contracts should be publish in here: https://docs.stonedefi.io/

**Comment by Nemusonaneko** [comment]
> > 
> 
> Cool, Yeah, Avalanche contracts should be publish in here: https://docs.stonedefi.io/

Unless I'm missing something, I don't see a section for AVAX contracts?
image

**Comment by bibodeng** [comment]
> contracts

image
hi. Below StoneBank BSC part.

**Comment by Nemusonaneko** [comment]
Just rewrote the adapter and listed the protocol. Should be on our site soon. Sorry for the delay.

**Comment by bibodeng** [comment]
> 

Thanks a lot! Nice job.

**Pull request closed without merging**
