### PR TITLE
Add FerdyFlip TVL

### PR DESCRIPTION
**Pull request by JazzBashara**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
FerdyFlip

##### Twitter Link:
https://twitter.com/ferdyfishh

##### Website Link:
https://www.ferdyflip.xyz/

##### Logo (High resolution, will be shown with rounded borders):
https://www.ferdyflip.xyz/images/ferdy_pfp.png

##### Current TVL:
According to `node test.js projects/ferdyflip/index.js` 160.59 k

##### Treasury Addresses (if the protocol has treasury)
Avalanche: 0x20AfbaC35B333dA4fE7230CC60946F88ee87aAA3 
Base: 0x3b6014e4b38791444a352D687022D6d6d79Eb99c

##### Chain:
Avalanche, Base

##### Short Description (to be shown on DefiLlama):
Decentralized casino with revenue share. No KYC and instant settlements.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Prediction Market

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### methodology (what is being counted as tvl, how is tvl being calculated):
Calculates treasury on Avalanche and Base

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/ferdyflip exports TVL: 
        
 
 
    avax                      130.55 k
    base                      29.87 k
    
    total                    160.42 k

**Comment by g1nt0ki** [comment]
@JazzBashara thanks for the PR

**Comment by llamatester** [comment]
The adapter at projects/ferdyflip exports TVL: 
        
 
 
    avax                      130.25 k
    base                      29.82 k
    
    total                    160.07 k

**Comment by JazzBashara** [comment]
Thank you for merging @g1nt0ki  

Question: to have a further look back at the TVL do I have to specify a timestamp in the exports or am I misunderstanding the purpose?

In this case:

```js
Object.keys(config).forEach((chain) => {
  module.exports[chain] = {
    start: 1675962000, //Fri Feb 10 2023
    tvl: sumTokensExport(config[chain]),
  };
});
```

**Pull request merged**
