### PR TITLE
Add WingRiders DEX

### PR DESCRIPTION
**Pull request by szist**
The token address and contract addresses might still change. The DEX will be released soon.

##### Twitter Link:
https://twitter.com/wingriderscom

##### List of audit links if any:
The whole reported is unpublished at this point.
blogpost: https://medium.com/@wingriderscom/audits-plaudits-and-writing-good-code-c954ae109b2e

##### Website Link:
https://www.wingriders.com/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

WRToken

##### Current TVL:
0 (unreleased)

##### Chain:
Cardano

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
- 

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
- 

##### Short Description (to be shown on DefiLlama):
The DEX on Cardano
Native and fast AMM decentralized exchange platform.

##### Token address and ticker if any:
https://cardanoscan.io/token/c0ee29a85b13209423b10447d3c2e6a50641a15c57770e27cb9d507357696e67526964657273
the token metadata and ID might still change until release

##### Category (full list at https://defillama.com/categories) *Please choose only one:
1. Dexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
- 

##### forkedFrom (Does your project originate from another project):
initial development

##### methodology (what is being counted as tvl, how is tvl being calculated):
Until stablecoins arrive, assuming that the liquidity pools (pair of tokens) contain ADA, the estimated tvl is 2*the ADA amount in the pools. Additionally, the swap requests are accounted for as well.
The dex also supports token-2-token. Once stablecoins are introduced an oracle will be added as well.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/wingriders/index.js exports TVL: 
        
 
 
    cardano                   0
    
    total                    0

**Comment by szist** [comment]
> The adapter at projects/wingriders/index.js exports TVL:
> 
> ```
> cardano                   0
> 
> total                    0 
> ```

Correct, as I said in the note above. It's not released yet. It will be released very soon. We could add the testnet version of the contracts if that would interest you :)

**Comment by waynebruce0x** [comment]
Whats being counted by liquidityPoolLocked and requestLcoked?

**Comment by szist** [comment]
> Whats being counted by liquidityPoolLocked and requestLcoked?

I described this in the details as well. See above.
Basically all the ADA that is locked in the contracts. For LPs this gets multiplied by 2, as the assumption is that in the pool you have equal value for both pairs. 

This is the exact same way method minswap uses, which is already live :).

**Comment by waynebruce0x** [comment]
Thanks - how do the swap requests work? who has custody of the coins?

**Comment by szist** [comment]
> Thanks - how do the swap requests work? who has custody of the coins?

Both liquidity pools and requests are contracts. Requests are basically escrow contracts, where only the user can withdraw the funds. An authorized wallet can trigger the endpoint to fulfill the requests; in this case the LP contract needs to be present in the transaction as well, which verifies if the exchange was done correctly.

The LP contracts are AMM contracts with uniswap v2 model.

**Pull request merged**
