### PR TITLE
feat: add Bitlayer chain, Bitlayer assets and update Avalon bitlayer marekt

### PR DESCRIPTION
**Pull request by tpktpj**
Hi Team. 
This is Avalon Finance. 

Update: 
- added one new chain: Bitlayer (https://www.bitlayer.org/)
- added Bitlayer market for Avalon Finance

Known Issue:
- Bitlayer TVL shows zero. It should be ~272.72K

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/avalon-finance exports TVL: 
        
 
 
    merlin                    202.57 M
    merlin-borrowed           6.85 M
    borrowed                  6.85 M
    bitlayer-borrowed         0
    bitlayer                  0
    
    total                    202.57 M

**Comment by tpktpj** [comment]
Please check and verify the asset on Bitlayer.

```
┌─────────┬───────────────┬──────────┬──────────┬───────────────────────────────────────────────────────┬──────────┐
│ (index) │     name      │  symbol  │ balance  │                         label                         │ decimals │
├─────────┼───────────────┼──────────┼──────────┼───────────────────────────────────────────────────────┼──────────┤
│    0    │ 'Wrapped BTC' │  'WBTC'  │   '0'    │ 'bitlayer:0xfF204e2681A6fA0e2C3FaDe68a1B28fb90E4Fc5F' │   '18'   │
│    1    │   'BITUSD'    │ 'bitusd' │ '265803' │ 'bitlayer:0x07373d112EDc4570B46996Ad1187bc4ac9Fb5Ed0' │   '18'   │
└─────────┴───────────────┴──────────┴──────────┴───────────────────────────────────────────────────────┴──────────┘
```

- WBTC: https://www.btrscan.com/address/0xff204e2681a6fa0e2c3fade68a1b28fb90e4fc5f

- BITUSD: https://www.btrscan.com/address/0x07373d112edc4570b46996ad1187bc4ac9fb5ed0

**Comment by g1nt0ki** [comment]
please avoid PRs with formatting changes, it is a nightmare to review

**Comment by g1nt0ki** [comment]
added it here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/b85e3233721e96c4bccd638a1d56c322d1d5d404

**Pull request closed without merging**
