### PR TITLE
Add Apex DeFi TVL and staking (APEX token)

### PR DESCRIPTION
**Pull request by DJHellscream**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Apex DeFi

##### Twitter Link:
https://x.com/apex314_defi

##### List of audit links if any:
https://www.cyberscope.io/audits/9-apex

##### Website Link:
https://apexdefi.xyz/

##### Logo (High resolution, will be shown with rounded borders):
Apex Logo

##### Current TVL:
$186,000 (This does not include all of the masterchef farms)

##### Treasury Addresses (if the protocol has treasury)
0xbbA86a95257F0803E6C7D53d3036172654aD017c

##### Chain:
Avalanche

##### Short Description (to be shown on DefiLlama):
Apex DeFi is the first and only all-in-one platform for ERC314 tokens, revolutionizing trading and DeFi with seamless integration.

##### Token address and ticker if any:
0x98B172A09102869adD73116FC92A0A60BFF4778F APEX

##### Category (full list at https://defillama.com/categories) *Please choose only one:
DEXES

##### methodology (what is being counted as tvl, how is tvl being calculated):
The Apex DeFi factory contract address is used to obtain the balances held in each token contract as liquidity and the staking contract is used to get the staked APEX balance.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/DJHellscream

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/apexdefi exports TVL: 
        
 
 
    avax                      189.11 k
    avax-staking              25.68 k
    staking                   25.68 k
    base                      2.70 k
    ethereum                  2.18 k
    
    total                    193.99 k

**Comment by llamatester** [comment]
The adapter at projects/apexdefi exports TVL: 
        
 
 
    avax                      98.36 k
    base                      1.41 k
    ethereum                  1.13 k
    
    total                    100.90 k

**Comment by g1nt0ki** [comment]
@DJHellscream thanks for the PR, I refactored it a bit, we cannot include ERC314 token value as tvl since those tokens are generated using your protocol, I have excluded staking for the same reason.

**Comment by DJHellscream** [comment]
@g1nt0ki Okay, is there a place we can further discuss this? I think I understand why you excluded the staking, but for the ERC314 tokens the value I was calculating was the liquidity provided by users. Apex is a launchpad and DEX sort of together. I realize it's a unique situation and would love to further chat about it.

That way we can both be on the same page.

**Pull request merged**
