### PR TITLE
feat: update ZooDAO project

### PR DESCRIPTION
**Pull request by ErnestMironov**
Add Arbitrum support for ZooDao TVL calculation and add ZOO Token calculation in Moonbeam TVL.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/zoodao exports TVL: 
        
 
 
    moonbeam-staking          13.42 k
    moonbeam                  8.96 k
    arbitrum                  276.19 k
    arbitrum-pool2            323.06 k
    staking                   13.42 k
    pool2                     323.06 k
    
    total                    285.15 k

**Comment by g1nt0ki** [comment]
@ErnestMironov thanks for the PR, I refactored it a bit, we count own tokens under staking and LPs under pool2: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

if you are fine with the changes, I will merge the PR

**Comment by ErnestMironov** [comment]
> @ErnestMironov thanks for the PR, I refactored it a bit, we count own tokens under staking and LPs under pool2: https://docs.llama.fi/list-your-project/what-to-include-as-tvl
> 
> 
> 
> if you are fine with the changes, I will merge the PR

Thanks for the help, I agree with the changes, let's do that.

**Comment by ErnestMironov** [comment]
@g1nt0ki I can't find the fsglp data on the ZOODAO page. 
image
image
image

However, they were present in the test logs.  
image

**Pull request merged**
