### PR TITLE
add New Bitcoin TVL

### PR DESCRIPTION
**Pull request by elykct**
##### Github org/user (Optional, if your code is open source, we can track activity): https://github.com/TrustlessComputer

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/newbitcoin exports TVL: 
        
 
 
    
    total                    80.75 k

**Comment by g1nt0ki** [comment]
sorry, it is not very clear to me how smart contracts work in bitcoin

**Review by 0xngmi — CHANGES_REQUESTED** [review]
would it be possible to avoid calling your own api? 

pls see https://github.com/DefiLlama/DefiLlama-Adapters/discussions/432 for reasoning

**Comment by g1nt0ki** [comment]
@elykct can you share NOS rpc details, I am guessing it is evm compatible, if so I can add it to our sdk and you can compute tvl on chain. 

Is there some way to get list of token contracts, like querying factory contract/reading logs?

**Comment by llamatester** [comment]
Error while running adapter at projects/newbitcoin: 
        
 
  
    
    
    Error: 
        Unknown chain(s): nos
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file

**Comment by llamatester** [comment]
Error while running adapter at projects/newbitcoin: 
        
 
  
    
    
    Error: 
        Unknown chain(s): nos
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file

**Comment by g1nt0ki** [comment]
@elykct thanks I have added the rpc to our sdk and merged your changes here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/7666

**Comment by g1nt0ki** [comment]
@elykct is this your uni v3 factory? https://explorer.l2.trustless.computer/address/0x1d12AC81710da54A50e2e9095E20dB2D915Ce3C8

**Pull request closed without merging**
