### PR TITLE
feat: add Sophon chain

### PR DESCRIPTION
**Pull request by lutr0**
update Syncswap

**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Sophon

##### Twitter Link:
https://x.com/sophon

##### List of audit links if any:
https://docs.sophon.xyz/sophon/links/security-and-audits

##### Website Link:
sophon.xyz

##### Logo (High resolution, will be shown with rounded borders):
Sophon_Logo_Black
Sophon_Logo_Main
Sophon_Logo_White

##### Current TVL:
N/A

##### Chain:
Sophon

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Chain

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/sophon-org

### CODE REVIEW

**Comment by llamabutler** [comment]
The adapter at projects/syncswap exports TVL: 
        
 
 
    era                       26.03 M
    linea                     18.49 M
    scroll                    6.46 M
    sophon                    1.72 k
    
    total                    50.98 M

**Comment by llamabutler** [comment]
The adapter at projects/syncswap exports TVL: 
        
 
 
    era                       25.48 M
    linea                     19.17 M
    scroll                    6.34 M
    sophon                    1.72 k
    
    total                    51.00 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
thanks for the PR, it looks good. 

Can you share the bridge address? (where assets are locked in ethereum)

Also, do you know if someone has deployed a multicall3 contract on your chain, using it reduces the #calls we make to the rpc

**Comment by llamabutler** [comment]
The adapter at projects/syncswap exports TVL: 
        
 
 
    era                       25.48 M
    linea                     19.18 M
    scroll                    6.34 M
    sophon                    1.72 k
    
    total                    51.00 M

**Comment by lutr0** [comment]
Sure thing:
L1SharedBridge: [0xD7f9f54194C633F36CCD5F3da84ad4a1c38cB2cB](https://etherscan.io/address/0xD7f9f54194C633F36CCD5F3da84ad4a1c38cB2cB#code)
We are an elastic chain so we share the bridge with zkSync ERA

Multicall: [0x5f4867441d2416cA88B1b3fd38f21811680CD2C8](https://explorer.sophon.xyz/address/0x5f4867441d2416cA88B1b3fd38f21811680CD2C8#contract)

**Comment by llamabutler** [comment]
The adapter at projects/syncswap exports TVL: 
        
 
 
    era                       25.52 M
    linea                     19.12 M
    scroll                    6.35 M
    sophon                    5.94 M
    
    total                    56.93 M

**Pull request merged**
