### PR TITLE
add crescent

### PR DESCRIPTION
**Pull request by lv-koala**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
https://twitter.com/CrescentHub

##### Website Link:
https://app.crescent.network/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://pbs.twimg.com/profile_images/1500704987990880256/PeQ_j_ca_400x400.jpg

##### Short Description (to be shown on DefiLlama):
Crescent is an AMM / Orderbook Hybrid Decentralized Exchange that allows the smoothest method of trading inter-chain assets by the most cost-efficient and sustainable management of liquidity through Orderbook and Ranged liquidity.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
dexes

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
Counts the liquidity on all pools.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/crescent.js exports TVL: 
        
 
 
    crescent                  14.85 M
    
    total                    14.85 M

**Comment by g1nt0ki** [comment]
@lv-koala thanks for the PR, I have not merged it yet because I am trying to turn it from fetch adapter to on chain adapter

**Comment by llamatester** [comment]
The adapter at projects/canto-forte exports TVL: 
        
 
 
    canto                     51.36 k
    
    total                    51.36 k

**Comment by llamatester** [comment]
The adapter at projects/crescent-dex exports TVL: 
        
 
 
    crescent                  15.31 M
    
    total                    15.31 M

**Pull request merged**
