### PR TITLE
Add 

### PR DESCRIPTION
**Pull request by 0xRams**
Name (to be shown on DefiLlama): GroveCoin

Twitter Link: https://twitter.com/GroveToken

List of audit links if any: https://www.certik.com/projects/grovecoin

Website Link: https://www.grovetoken.com/

Logo (High resolution, will be shown with rounded borders):

Current TVL: $3.000.000

Treasury Addresses (if the protocol has treasury)

https://grvscan.io/token/0x640bd16c20ddb3b43cb0851c52f15290f324f1e0

https://grvscan.io/token/0xfed13fe6b5c3776fb2269ab1a9d5534aefe9f41a

https://grvscan.io/token/0xaba3e5797c0a78d103060f1cb78bac3570ee616a

https://grvscan.io/token/0xE85f139488c689038028a3EB8fC38dcC29D4C340/token-transfers

Chain: GroveCoin Chain

Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

Short Description (to be shown on DefiLlama):

Grove Token is a decentralized and secure green Token built for the future of our planet. Our mission is to Create wealth, for all Grovers, by harnessing the opportunities of a secure, decentralized digital currency in an environmentally conscious way. By compensating nature for years of abuse, Grove will create a healthier, wealthier future for all.

Token address and ticker if any:

Category (full list at https://defillama.com/categories) *Please choose only one:

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

forkedFrom (Does your project originate from another project):

methodology (what is being counted as tvl, how is tvl being calculated):

-Staking
-Farming
-Bridge

Protocol : https://app.groveswap.io/swap?chainId=770077

### CODE REVIEW

**Comment by g1nt0ki** [comment]
added here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/0498df42f82cb52278e8dc1b48ffa945084a3ecc

**Comment by 0xRams** [comment]
Please add GroveCoin 🙏

**Comment by g1nt0ki** [comment]
any other apps other than groveswap on grove chain? I have added grove chain here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/a6bcc7f7da67286c96ac61b47c33a5d1bbbd7a4f

**Comment by 0xRams** [comment]
we want to be on the defillama chain list and groveswap to be the protocol 

 more details we want to be here https://defillama.com/chains 
as GroveCoin . and groveswap to protocol

thanks 🙏

**Pull request closed without merging**
