### PR TITLE
Update

### PR DESCRIPTION
**Pull request by fantasy2345**
##### Twitter Link:  
linktr.ee/civfund, https://twitter.com/CivFund 
 
 
##### List of audit links if any: 
https://www.certik.com/projects/civilization 
 
##### Website Link:  
civfund.org 
 
 
##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): 
!civ_logo_graphic_text (https://user-images.githubusercontent.com/89921487/182659481-7d30635d-6cfc-4060-b501-cc3b97d1d7be.png) 
 
 
 
##### Current TVL: 
10.12 M 
 
##### Chain:  
Ethereum 
 
 
##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list): 
{"id":"civilization","symbol":"civ","name":"Civilization"} 
 
##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000) 
{"id":11345,"name":"Civilization","symbol":"CIV","slug":"civilization","is_active":1,"status":"active","first_historical_data":"2021-08-20T21:42:03.000Z","last_historical_data":"2022-08-03T16:07:00.000Z","platform":{"id":1,"name":"Ethereum","symbol":"ETH","slug":"ethereum","token_address":"0x37fe0f067fa808ffbdd12891c0858532cfe7361d"} 
 
##### Short Description (to be shown on DefiLlama): 
Civilization  
The world's first zero-fee DeFi trading system  
Audited, patent-pending technology: DeFi for everyone  
Building towards a community-driven fund 
 
##### Token address and ticker if any: 
https://etherscan.io/address/0x37fe0f067fa808ffbdd12891c0858532cfe7361d 
 
##### Category (full list at https://defillama.com/categories) *Please choose only one: 
1 and 5 
 
##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using): 
chainlink 
 
##### forkedFrom (Does your project originate from another project): 
Masterchef for farm but reviewed and optimized 
 
##### methodology (what is being counted as tvl, how is tvl being calculated): 
total value locked of underlying assets and LP tokens

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/civfund exports TVL: 
        
 
 
    algorand                  7.77 M
    
    total                    7.77 M

**Comment by g1nt0ki** [comment]
@fantasy2345 not sure why you are trying to replace on chain calls with call toyour api, can you explain the reason behind it?

**Comment by fantasy2345** [comment]
> @fantasy2345 not sure why you are trying to replace on chain calls with call toyour api, can you explain the reason behind it?

I only want to show TVL values not stake and pool2

**Comment by g1nt0ki** [comment]
@fantasy2345 can you update adapter to fetch the tvl from on chain calls?

**Comment by fantasy2345** [comment]
> @fantasy2345 can you update adapter to fetch the tvl from on chain calls?

With subgraph?

**Comment by g1nt0ki** [comment]
no, fetching data by making calls against ethereum RPC, you mentioned LPs, can you provide a list/LP factory address, I can help with modifying adapter to make on chain calls

**Comment by fantasy2345** [comment]
> no, fetching data by making calls against ethereum RPC, you mentioned LPs, can you provide a list/LP factory address, I can help with modifying adapter to make on chain calls

In our farm, there are 5 pools.
2 pools are governance token pool and 3 pools are LP token pools.
But I want to sum these 5 pool TVLs.
I don't want to split with stake and pool2.
Farm contract address: 0x8a774F790aBEAEF97b118112c790D0dcccA61099
Governance token pool:
 - 0NE token pool: 0x73a83269b9bbafc427e76be0a2c1a1db2a26f4c2
 - CIV token pool: 0x37fe0f067fa808ffbdd12891c0858532cfe7361d
 LP token pools:
  - 0x6c406daeca809382e649d6c8f768450bf8dbc1dd
  - 0xa65653bb6e1338dbce69191bb1328700881fc051
  - 0xed247449a7ca06db5b27b44b2c092f0b48bbdb77

**Comment by g1nt0ki** [comment]
okay, the contracts are same as what I have but you want them classified differently? Sorry, I was following standard policy: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by fantasy2345** [comment]
> okay, the contracts are same as what I have but you want them classified differently? Sorry, I was following standard policy: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

Yep, I only want to show TVL. Don't need to classified with stake and pool2
Is it possible?

**Comment by g1nt0ki** [comment]
Sorry, no.

**Comment by fantasy2345** [comment]
Why is it impossible?
I can see that many DeFi projects show only TVL

**Comment by fantasy2345** [comment]
MakerDao shows only TVL.
https://defillama.com/protocol/makerdao

**Comment by g1nt0ki** [comment]
@fantasy2345 makerdao's tvl is not staked maker tokens or maker/dai LPs, if users lock non native tokens in your protocol, it will counted towards tvl

**Pull request closed without merging**
