### PR TITLE
Empowa adapter

### PR DESCRIPTION
**Pull request by phillewis**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Empowa

##### Twitter Link:
https://x.com/empowa_io

##### Website Link:
https://empowa.io

##### Logo (High resolution, will be shown with rounded borders):
image

##### Current TVL:
335.92 k

##### Chain:
Cardano

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
empowa

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
19606

##### Short Description (to be shown on DefiLlama):
Empowa is the first RealFi property platform on Cardano that combines emerging technology, sustainable building and decentralised financial inclusion.

##### Token address and ticker if any:
6c8642400e8437f737eb86df0fc8a8437c760f48592b1ba8f5767e81
EMP

##### Category (full list at https://defillama.com/categories) *Please choose only one:
RWA Lending

### CODE REVIEW

**Comment by g1nt0ki** [comment]
I am bit confused, what is counted as tvl here? we cant count your own token as tvl, also bit confused at to what the code considers borrowed. more info on what we classify as tvl: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by phillewis** [comment]
> I am bit confused, what is counted as tvl here? we cant count your own token as tvl, also bit confused at to what the code considers borrowed. more info on what we classify as tvl: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

Thanks for following up on this @g1nt0ki, I appreciate that the unique nature of our platform may make it difficult to understand how tvl is applied compared to other DeFi platforms.

Value is locked either directly in the houses our platform finances (i.e. value borrowed for the houses), or in collateral to secure the houses.  In both cases, contributors hold NFTs that represent how much value they contributed and this is paid back over time to them using EMP tokens that are acquired using the house repayments in fiat.

If the use of the term "borrowed" in the code is misleading then we can change that.  It is just how it is seen from the perspective of the housing developer, as they are "borrowing" value in EMP terms to either finance the house or provide collateral for the house.

Hopefully that makes sense, but I am happy to elaborate if necessary.

**Comment by g1nt0ki** [comment]
hi @phillewis in this flow, what is counted as tvl? 
image


- the local developer can rent EMP used as collateral, so, what do they use as collateral for that rent?

**Comment by phillewis** [comment]
Hey @g1nt0ki 
Arrows 1 (housing finance) and 2 (collateral) which both direct value into the platform.

**Comment by g1nt0ki** [comment]
isnt the accredited inverstors investing in USD? and to collateral is borrowed from the community?

**Comment by phillewis** [comment]
> isnt the accredited inverstors investing in USD? and to collateral is borrowed from the community?

We have only done one round of housing loan to date and that wasn't done using USD, although we do plan to support USD in the future.  That loan is being repaid in EMP.

Regarding collateral, yes that will be borrowed from the community.

At this stage we haven't differentiated between value locked for housing loans and value locked for collateral.

**Comment by phillewis** [comment]
@g1nt0ki please let me know if any additional information is required.

**Comment by g1nt0ki** [comment]
> > isnt the accredited inverstors investing in USD? and to collateral is borrowed from the community?
> 
> We have only done one round of housing loan to date and that wasn't done using USD, although we do plan to support USD in the future. That loan is being repaid in EMP.
> 
> Regarding collateral, yes that will be borrowed from the community.
> 
> At this stage we haven't differentiated between value locked for housing loans and value locked for collateral.

Sorry, this feels circular, everything is linked to EMP. We prefer things that we can track on chain, and count only non protocol tokens as tvl (so no EMP)

In your case, we can count any stablecoin in your pool not yet lent out as tvl, and stablecoins lent out as borrowed, this is what we do for other similar rwa projects.

**Comment by phillewis** [comment]
Hi @g1nt0ki 

Sorry, I don't understand what you mean? Are you saying that only stablecoins can be used to measure TVL on DefiLlama?

Given that our loans are quite long (e.g. 10 years), we chose to use EMP as an asset to lend and provide collateral with, as it allows the token to represent the value of the houses we finance.  If we use an asset external to our system, then its value is influenced by other factors.

I realise that our model is very unique and not like anything else you have reported against, but this doesn't change the fact that there is value locked in both the houses and the collateral.  Each of which are represented by NFTs held by the owners of the value.

**Comment by g1nt0ki** [comment]
> "Sorry, I don't understand what you mean? Are you saying that only stablecoins can be used to measure TVL on DefiLlama?"
Yes,  else it wont be apple to apple comparison with other RWA lending protocols.

**Comment by phillewis** [comment]
> > "Sorry, I don't understand what you mean? Are you saying that only stablecoins can be used to measure TVL on DefiLlama?"
> 
> Yes, else it wont be apple to apple comparison with other RWA lending protocols.

Oh ok, sorry I didn't realise this constraint existed when selecting the category.  I just assumed that you used a token price lookup in order to perform a dollar based comparison.

Are there any categories where non-USD assets can be counted towards TVL?

**Comment by g1nt0ki** [comment]
it is not an issue of pricing the token, rather using platforms own token as tvl.

**Comment by g1nt0ki** [comment]
yes. you can check this discussion: https://github.com/DefiLlama/DefiLlama-Adapters/discussions/438

**Comment by 0xngmi** [comment]
is there a frontend where users like me can deposit funds into your system?

**Comment by phillewis** [comment]
> yes. you can check this discussion: #438

This appears to refer to staking.  We have reported staking separately, as we recognise that this isn't contributing directly to the financing or collateralisation of housing.

**Comment by phillewis** [comment]
> is there a frontend where users like me can deposit funds into your system?

The funds we raise are done through the sale of NFTs.  In the case of NFTs used to finance housing, returns are paid back to the NFT holder.  In the case of raising collateral, the funds are redeemed when the NFT matures by burning it.  We are doing our first collateral raise next month, so you will be able to participate when we open the sale.  Please check our socials for more info.

**Comment by g1nt0ki** [comment]
closing this as we have reached an d

**Comment by phillewis** [comment]
@g1nt0ki after 2 months of no response to my last comments, you just close this PR :(

We have recently completed our first collateral raise for the houses we currently have financed, [https://x.com/empowa_io/status/1795983765568971140](https://x.com/empowa_io/status/1795983765568971140) which I referred to above.

It is very disappointing that just because our project is unique and doesn't fit your traditional definition of how value is locked, that we should be excluded.

**Pull request closed without merging**
