### PR TITLE
Add oraidex v3 to orai

### PR DESCRIPTION
**Pull request by trungbach**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
OraiDEX Pool V3

##### Twitter Link:
https://x.com/oraidex

##### Website Link:
https://oraidex.io/

##### Logo (High resolution, will be shown with rounded borders):
Frame 1864

##### Current TVL:
$6.11 M

##### Chain:
Oraichain

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
tether

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
tether

##### Short Description (to be shown on DefiLlama):
A fully decentralized protocol for automated liquidity provision on Oraichain

##### Token address and ticker if any:
orai12hzjxfh77wl572gdzct2fxv2arxcwh6gykc7qh

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### methodology (what is being counted as tvl, how is tvl being calculated):

TVL: Counts the tokens locked on AMM pools, pulling the data from oraichain-indexer 
Fees: Swap fees paid by users
Revenue: Percentage of swap fees going to treasury and/or token holders

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/oraidex-v3 exports TVL: 
        
 
 
    orai                      6.12 M
    
    total                    6.12 M

**Comment by trungbach** [comment]
Purpose of this PR is to add info for Pool V3 of Oraidex from Oraichain: https://defillama.com/protocol/oraidex#information

**Review by g1nt0ki — COMMENTED** [review]
@trungbach thanks for the PR, but can you update code to fetch tvl from on chain data instead of relying on the indexer?

**Comment by llamatester** [comment]
The adapter at projects/oraidex-v3 exports TVL: 
        
 
 
    orai                      5.06 M
    
    total                    5.06 M

**Comment by llamatester** [comment]
The adapter at projects/oraidex-v3 exports TVL: 
        
 
 
    orai                      5.06 M
    
    total                    5.06 M

**Comment by trungbach** [comment]
> @trungbach thanks for the PR, but can you update code to fetch tvl from on chain data instead of relying on the indexer?

Thank you, i've just updated code to fetch TVL from on-chain data, please review again.

**Comment by g1nt0ki** [comment]
thanks, I have refactored and merged it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/11331

**Pull request closed without merging**
