### PR TITLE
list cswap dex on comdex chain

### PR DESCRIPTION
**Pull request by cgsingh33**
##### Current TVL: 
------ TVL ------

total                     636.24 k

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list) 
comdex

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
14713

##### Short Description (to be shown on DefiLlama): 
Comdex is a DeFi infrastructure layer for the Cosmos ecosystem. A layer-1 infrastructure for seamless deployment of DeFi applications in the Cosmos ecosystem, powering DeFi in the multi-chain future.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/cswap.js exports TVL: 
        
 
 
    
    total                    0

**Comment by cgsingh33** [comment]
> The adapter at projects/cswap.js exports TVL:
> 
> ```
> total                    0 
> ```

image

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
@cgsingh33 thanks for the PR, can you compute tvl using comdex rpc? this way, it is not a blackbox, also, changing RPC endpoint is easier that trying find implementation if stats api is deprecated/down

**Comment by cgsingh33** [comment]
> @cgsingh33 thanks for the PR, can you compute tvl using comdex rpc? this way, it is not a blackbox, also, changing RPC endpoint is easier that trying find implementation if stats api is deprecated/down

These external stats APIs are created for fast rendering of data, we are also using these in our UI, so you can rely on these.

**Comment by g1nt0ki** [comment]
@cgsingh33 sorry, I prefer reliability/maintenance over  speed

**Comment by g1nt0ki** [comment]
I am not familiar with cosmos sdk, often struggle finding correct endpoints to query, if you guide me with querying different pool info (tokens/balances) I can refactor the adapter to fix the rest. this is the rest endpoint right `https://rest.comdex.one/comdex/`

**Comment by cgsingh33** [comment]
> I am not familiar with cosmos sdk, often struggle finding correct endpoints to query, if you guide me with querying different pool info (tokens/balances) I can refactor the adapter to fix the rest. this is the rest endpoint right `https://rest.comdex.one/comdex/`

sure,
https://rest.comdex.one/comdex/liquidity/v1beta1/pools/1
this will give you list of pools with the liquidity of the tokens under balances field, but these are not $ value, for that you need multiply with the token current price.

**Comment by g1nt0ki** [comment]
> > I am not familiar with cosmos sdk, often struggle finding correct endpoints to query, if you guide me with querying different pool info (tokens/balances) I can refactor the adapter to fix the rest. this is the rest endpoint right `https://rest.comdex.one/comdex/`
> 
> sure, https://rest.comdex.one/comdex/liquidity/v1beta1/pools/1 this will give you list of pools with the liquidity of the tokens under balances field, but these are not $ value, for that you need multiply with the token current price.

thanks, I have added it here, can you review the code just to ensure that I have not introduced any bugs: https://github.com/DefiLlama/DefiLlama-Adapters/pull/4978/files

**Pull request merged**
