### PR TITLE
Hedgehog Markets

### PR DESCRIPTION
**Pull request by jkdipeppe**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Hedgehog Markets

##### Twitter Link:
https://x.com/HedgehogMarket

##### Website Link:
https://hedgehog.markets/

##### Logo (High resolution, will be shown with rounded borders):
- [Logo](https://raw.githubusercontent.com/Hedgehog-Markets/resources/refs/heads/master/logo/blue.svg)
- [White dark mode variant](https://raw.githubusercontent.com/Hedgehog-Markets/resources/refs/heads/master/logo/white.svg)
- [Black light mode variant](https://raw.githubusercontent.com/Hedgehog-Markets/resources/refs/heads/master/logo/black.svg)
HedgehogLogoBlue

##### Current TVL:
84.39 k

##### Chain:
Solana

##### Short Description (to be shown on DefiLlama):
Hedgehog Markets is the first Prediction Market market platform on Solana. They offer various markets types and markets that cover any and all topics!

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Prediction Market

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL consists of deposits made into Hedgehog Markets as part of an active bet.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/Hedgehog-Markets

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at : 
        
 
  > Please revert changes to package.json / package-lock.json

**Comment by llamatester** [comment]
Error while running adapter at projects/hedgehog-markets: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:226:11
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
Error while running adapter at : 
        
 
  > Please revert changes to package.json / package-lock.json

**Comment by Juici** [comment]
The solana web3.js 2.0 packages are necessary for the adapter.

**Comment by llamatester** [comment]
Error while running adapter at : 
        
 
  > Please revert changes to package.json / package-lock.json

**Comment by llamatester** [comment]
Error while running adapter at : 
        
 
  > Please revert changes to package.json / package-lock.json

**Comment by g1nt0ki** [comment]
@jkdipeppe thanks for the PR

I have refactored and merged it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/11719

But I ran into an issue, can you take a look at the updated code? unsure how to form the correct struct for parimutuel (this part: https://github.com/DefiLlama/DefiLlama-Adapters/pull/11719/files#diff-2cac38c803ff2d2fd4abd515dca72062fc35c15c67c2a9924edffc5d6ed6903bR269) so, I have disabled it for now

**Comment by llamatester** [comment]
The adapter at projects/hedgehog-markets exports TVL: 
        
 
 
    solana                    72.43 k
    
    total                    72.43 k

**Comment by Juici** [comment]
@g1nt0ki I've removed the additional dependencies and added back parimutuel.

**Review by Rezacb0413 — APPROVED** [review]

**Pull request closed without merging**
