### PR TITLE
CACHE Gold CGT - Added TVL

### PR DESCRIPTION
**Pull request by seigneur**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

##### List of audit links if any:
https://github.com/cache-token/docs/blob/master/CACHE_Gold_Audit_Zerotrust.pdf
https://github.com/cache-token/docs/blob/master/CACHE_Gold_CGT_Audit_Polygon_CertiK.pdf

##### Short Description (to be shown on DefiLlama):
CACHE Gold tokens are fully compliant, public, transparent, redeemable gold-backed tokens.

### CODE REVIEW

**Comment by seigneur** [comment]
--- ethereum ---
USDT                      4.45 M
Total: 4.45 M 

--- tvl ---
USDT                      4.45 M
Total: 4.45 M 

------ TVL ------
ethereum                  4.45 M

total                    4.45 M

**Comment by g1nt0ki** [comment]
sorry @seigneur I dont think we can list cache gold, the way I see it, you are similar to USDT/USDC, we dont list either of those

**Comment by cache-gold** [comment]
> sorry @seigneur I dont think we can list cache gold, the way I see it, you are similar to USDT/USDC, we dont list either of those

CACHE Gold is not really at all similar to USDT or USDC. Those tokens are backed by paper financial instruments that do not have any real time Proof of Reserve. In the case of USDT it would be fair to say 'supposedly backed' and perhaps fractional reserve.  CACHE Gold is more comparable to Maker's DAI with the exception that Maker is backed by a basket of assets whereas CACHE Gold is only backed by physical gold.  The physical gold is distributed among different vaults around the world and has [a real-time Proof of Reserve secured by Chainlink.](https://data.chain.link/ethereum/mainnet/reserves/cachegold-por-usd)  It was actually Chainlinnk that asked us to list on DeFi Llama because without the listing the TVL field will not populate here: https://data.chain.link/users/httpscache.gold

**Comment by llamatester** [comment]
Error while running adapter at projects/cache-gold: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:223:11

**Comment by g1nt0ki** [comment]
I have fixed the bug here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/3644

**Comment by 0xngmi** [comment]
usdt and usdc are also backed by usd

**Comment by cache-gold** [comment]
USDT and USDC are actually not backed by very much USD.  USDC says they are  backed by mostly US Treasuries while USDT claims to be backed by a basket of various financial assets, including some highly questionable assets such as "Secured Loans", "Other Investments (Including Digital Tokens), "Commercial Paper", and "Non-US Treasury Bills".  There is no real time transparency or audits.  USDC and especially USDT are completely different from tokens like DAI and CGT.  You don't know what's really backing them at any given time and they are also not backed by physical real world assets. 

image

**Pull request merged**
