### PR TITLE
add project bouncebit-club

### PR DESCRIPTION
**Pull request by Adolf998**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
BounceBit-Club

##### Twitter Link:
https://x.com/BounceBitClub

##### Website Link:
https://club.bouncebit.io/

##### Chain:
BounceBit Chain

##### Short Description (to be shown on DefiLlama):
BounceBit Club V2 is an holistic blockchain ecosystem on BounceBit Chain. It features Bitcoin integration, AI-powered trading tools, comprehensive DeFi primitives, meme token creation, and GameFi elements. Built on a secure foundation, it offers users a versatile platform to explore, create, and manage diverse blockchain applications through a user-friendly interface, catering to both novice and experienced crypto enthusiasts.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
- BabyBoom(Meme): Launchpad
- Club Stablecoin: CDP
- Club Quanto: Derivatives
- BTCFi: ReStaking

##### methodology (what is being counted as tvl, how is tvl being calculated):
The club contains Meme, stablecoin, Quanto, BTCFi, you can display BabyBoom(Meme),Club Stablecoin,Club Quanto, BTCFi as separate dapps in BounceBit Club.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bouncebit-club exports TVL: 
        
 
 
    bouncebit                 182.41 k
    bouncebit-staking         13
    staking                   13
    
    total                    182.40 k

**Comment by llamatester** [comment]
The adapter at projects/bb-club-cdp exports TVL: 
        
 
 
    bouncebit                 3.68 k
    
    total                    3.68 k

**Comment by llamatester** [comment]
The adapter at projects/bb-club-meme exports TVL: 
        
 
 
    bouncebit                 2.17 k
    
    total                    2.17 k

**Comment by llamatester** [comment]
The adapter at projects/bb-club-quanto exports TVL: 
        
 
 
    bouncebit                 184.63 k
    
    total                    184.63 k

**Comment by llamatester** [comment]
The adapter at projects/bb-club-restaking exports TVL: 
        
 
 
    bouncebit                 6.35 k
    
    total                    6.35 k

**Comment by g1nt0ki** [comment]
@Adolf998 thanks for the PR, I split it based on product type

**Pull request merged**
