### PR TITLE
Fix: pac-finance tvl data

### PR DESCRIPTION
**Pull request by jfzhou5**
Fix PAC Finance TVL and Borrow data. 
The previous data calculated by the aave frame is wrong, And I don't know the reason, So I re-calculate tvl and borrowed data with the new code.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/pac-finance exports TVL: 
        
 
 
    blast                     73.27 M
    blast-borrowed            52.92 M
    borrowed                  52.92 M
    
    total                    73.27 M

**Comment by llamatester** [comment]
The adapter at projects/pac-finance exports TVL: 
        
 
 
    blast                     73.60 M
    blast-borrowed            52.90 M
    borrowed                  52.90 M
    
    total                    73.60 M

**Comment by llamatester** [comment]
The adapter at projects/time-fun exports TVL: 
        
 
 
    base                      247.44 k
    
    total                    247.44 k

**Comment by g1nt0ki** [comment]
@jfzhou5 thanks for the PR, I refactored it a bit

**Pull request merged**
