### PR TITLE
include new vaults into the calculation of TVL 

### PR DESCRIPTION
**Pull request by 0xKMG**
- Add GMXV2 leverage and lending vault Add hallmarks for vaults that have impact on TVLs
- include new vaults and hallmarks for Vaultka (using chainlink oracle instead of off chain oracle by GMX

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/vaultka exports TVL: 
        
 
 
    arbitrum                  1.83 M
    
    total                    1.83 M

**Comment by llamatester** [comment]
The adapter at projects/vaultka exports TVL: 
        
 
 
    arbitrum                  2.46 M
    
    total                    2.46 M

**Comment by g1nt0ki** [comment]
hi @0xKMG, we have price support for most of these tokens, so updated code to use that, but missing token prices for GMX tokens, once I copy your code to our coins repo, they will be priced, will leave this PR open till I fix that part

**Comment by 0xKMG** [comment]
Do I need to edit this PR on my end ?

**Comment by g1nt0ki** [comment]
> Do I need to edit this PR on my end ?

No, but can you review my changes?

**Comment by g1nt0ki** [comment]
*I will remove the gmPrice code once it is copied

**Comment by 0xKMG** [comment]
> > Do I need to edit this PR on my end ?
> 
> No, but can you review my changes?
Sure thing, let me know. I would appreciate if you will merge this PR first, as our TVL is not updated currently for quite some time

**Comment by llamatester** [comment]
The adapter at projects/vaultka exports TVL: 
        
 
 
    arbitrum                  2.55 M
    
    total                    2.55 M

**Pull request merged**
