### PR TITLE
fix lfbtc tvl

### PR DESCRIPTION
**Pull request by Eggman00**
change: lfbtc support and remove fbtc bitcoin mainnet address from TVL.

### CODE REVIEW

**Comment by Eggman00** [comment]
The adapter at projects/bedrock exports TVL:


```
--- optimism ---
WBTC                      111.70 k
Total: 111.70 k

--- bob ---
lfbtc-bedrock-bob         32.62 M
WBTC                      1.86 M
Total: 34.48 M

--- mantle ---
lfbtc-bedrock-mnt         1.32 M
FBTC                      111.00 k
Total: 1.43 M

--- arbitrum ---
wbtc                      909.01 k
Total: 909.01 k

--- ethereum ---
lfbtc-bedrock-eth         125.44 M
wbtc                      1.53 M
FBTC                      311.81 k
cbBTC                     4.80 k
Total: 127.29 M

--- bsc ---
lfbtc-bedrock-eth         24.22 M
BTCB                      589.83 k
FBTC                      88.78 k
Total: 24.90 M

--- mode ---
mBTC                      40.84 k
WBTC                      13.47 k
Total: 54.30 k

--- btr ---
BTC                       697.53 k
WBTC                      147.65 k
Total: 845.18 k

--- merlin ---
M-BTC                     101.04 k
BTC                       9.20 k
Total: 110.24 k

--- bitcoin ---
BTC                       46.67 M
Total: 46.67 M

--- bsquared ---
BTC                       54.04 k
Total: 54.04 k

--- zeta ---
BTC.BTC                   12.47 k
Total: 12.47 k

--- tvl ---
lfbtc-bedrock-eth         149.66 M
BTC                       47.43 M
lfbtc-bedrock-bob         32.62 M
wbtc                      2.44 M
WBTC                      2.14 M
lfbtc-bedrock-mnt         1.32 M
BTCB                      589.83 k
FBTC                      511.59 k
M-BTC                     101.04 k
mBTC                      40.84 k
BTC.BTC                   12.47 k
cbBTC                     4.80 k
Total: 236.86 M

------ TVL ------
ethereum                  127.29 M
bitcoin                   46.67 M
bob                       34.48 M
bsc                       24.90 M
mantle                    1.43 M
arbitrum                  909.01 k
btr                       845.18 k
optimism                  111.70 k
merlin                    110.24 k
mode                      54.30 k
bsquared                  54.04 k
zeta                      12.47 k

total                    236.86 M

```

**Comment by llamatester** [comment]
The adapter at projects/bedrock exports TVL: 
        
 
 
    ethereum                  127.29 M
    bitcoin                   46.67 M
    bob                       34.48 M
    bsc                       24.90 M
    mantle                    1.43 M
    arbitrum                  907.93 k
    btr                       845.56 k
    optimism                  111.71 k
    merlin                    110.28 k
    mode                      54.31 k
    bsquared                  54.06 k
    zeta                      12.47 k
    
    total                    236.87 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
hmm, this change break our bitcoin address book, it must return only array of bitcoin addresses

**Comment by g1nt0ki** [comment]
I have fixed it.

**Comment by Eggman00** [comment]
Thanks!

**Pull request closed without merging**
