### PR TITLE
Add Ramses Exchange

### PR DESCRIPTION
**Pull request by keccakdog**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000) 
untracked listing for now https://coinmarketcap.com/currencies/ramses-exchange/

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/ramses: 
        
 
  
    
    
    Error: Invalid balance: NaN
    Truncated error stack:
        at isValidNumber (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:119:19)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:334:14
        at Array.map (<anonymous>)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:328:25)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:54:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 1)
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
The adapter at projects/ramses exports TVL: 
        
 
 
    arbitrum-staking          2.18 M
    arbitrum                  1.03 M
    staking                   2.18 M
    
    total                    1.03 M

**Comment by llamatester** [comment]
The adapter at projects/ramses exports TVL: 
        
 
 
    arbitrum-staking          2.13 M
    arbitrum                  341.90 k
    staking                   2.13 M
    
    total                    341.90 k

**Comment by 0xShad0w** [comment]
Hey @g1nt0ki ! We updated our logo recently, would you kindly updated it on your end please? Ty

https://cdn.discordapp.com/attachments/368539350973284352/1209077960267534398/newram.png?ex=65e59c99&is=65d32799&hm=e0179011e3bb1584b3fc168dc02edf961d997d2348743b90dd4476117d078576&

**Pull request merged**
