### PR TITLE
Add Rumpel Labs Adapter

### PR DESCRIPTION
**Pull request by jparklev**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

Rumpel Labs

##### Twitter Link:

https://twitter.com/RumpelLabs

##### List of audit links if any:

2024.04.25 | Rumpel Vault | [Kurt Barry (Fixed Point Solutions)](https://github.com/sense-finance/point-tokenization-vault/blob/main/audits/2024.04.25%20FPS%20Points%20Tokenization.pdf)
2024.05.02 | Rumpel Vault | [Ethan Bennett (Dark Linear)](https://github.com/sense-finance/point-tokenization-vault/blob/main/audits/2024.05.02%20Darklinear%20Points%20Tokenization.pdf)
2024.07.15 | Rumpel Wallet | [Kurt Barry (Fixed Point Solutions)](https://github.com/sense-finance/rumpel-wallet/blob/main/audits/2024.07.15%20FPS%20Rumpel%20Wallet.pdf)
2024.07.22 | Rumpel Wallet & Vault Update | [Ethan Bennett (Dark Linear)](https://github.com/sense-finance/rumpel-wallet/blob/main/audits/2024.07.22%20Darklinear%20Rumpel%20Wallet.pdf)
2024.08.26 | Rumpel Wallet & Vault | [Sherlock Public Competition](https://audits.sherlock.xyz/contests/494?filter=questions)

##### Website Link:

https://www.rumpel.xyz/

##### Logo (High resolution, will be shown with rounded borders):

Profile Image

##### Current TVL:

$4.03M

##### Chain:

Ethereum Mainnet

##### Short Description (to be shown on DefiLlama):

Rumpel is a point tokenization protocol. It enables secondary market liquidity and price discovery for offchain loyalty points, unlocking new opportunities for point holders, traders, airdrop hunters, and point issuers.

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Liquid Staking

##### forkedFrom (Does your project originate from another project):

No

##### methodology (what is being counted as tvl, how is tvl being calculated):

Sums up the supported tokens in Rumpel Wallets + Deposits in the Rumpel Point Tokenization Vault

##### Github org/user (Optional, if your code is open source, we can track activity):

https://github.com/sense-finance

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/rumpel exports TVL: 
        
 
 
    ethereum                  4.02 M
    
    total                    4.02 M

**Comment by llamatester** [comment]
The adapter at projects/rumpel exports TVL: 
        
 
 
    ethereum                  4.02 M
    
    total                    4.02 M

**Comment by llamatester** [comment]
The adapter at projects/rumpel exports TVL: 
        
 
 
    ethereum                  4.02 M
    
    total                    4.02 M

**Comment by g1nt0ki** [comment]
thanks for the PR, I have refactored and merged it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/11727

also, added price support for karak wrapped tokens here: https://github.com/DefiLlama/defillama-server/commit/16bedb887c8853b007892975838d4aacee05aa08

**Comment by jparklev** [comment]
> thanks for the PR, I have refactored and merged it here: #11727
> 
> also, added price support for karak wrapped tokens here: [DefiLlama/defillama-server@16bedb8](https://github.com/DefiLlama/defillama-server/commit/16bedb887c8853b007892975838d4aacee05aa08)

Excellent, thank you! To confirm: why remove timetravel? and it looks like the TVL in #11727 is lower than what's reported here – is that right?

**Comment by jparklev** [comment]
Bump on this @g1nt0ki

**Comment by g1nt0ki** [comment]
@jparklev sorry for the late reply, timeTravel flag is true by default, so it was redundant,

the server was not pricing the token when I merged the PR, hence it was showing lower tvl, it should be showing correct tvl now.

**Pull request closed without merging**
