### PR TITLE
fixing farm address and adding governance token

### PR DESCRIPTION
**Pull request by TJakubek**
Fixing an incorrect farm address and adding our governance token to core addresses

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/flarefarm exports TVL: 
        
 
 
    songbird                  6.58 M
    songbird-staking          0
    songbird-pool2            711.00 k
    staking                   0
    pool2                     711.00 k
    
    total                    6.58 M

**Comment by llamatester** [comment]
The adapter at projects/flarefarm exports TVL: 
        
 
 
    songbird-pool2            1.41 M
    songbird                  6.49 M
    songbird-staking          665.48 k
    pool2                     1.41 M
    staking                   665.48 k
    
    total                    6.49 M

**Comment by g1nt0ki** [comment]
not sure why you wanted to add your gov token to core assets, it is not a good idea since the token is not priced in our backend

**Comment by TJakubek** [comment]
> not sure why you wanted to add your gov token to core assets, it is not a good idea since the token is not priced in our backend

ah sorry, I was hoping our gov token would show up in the token breakdown pie chart on our farms page: https://defillama.com/protocol/flrfarm
Is there something else I can do to get this token to show up there?

**Comment by g1nt0ki** [comment]
ah, we should not even be showing a token breakdown as it is incorrect (for example, some tokens are priced in WSGB so show up as WSGB), I will be hiding the breakdown chart for now, ideally this can be fixed by pricing all your tokens, but since we dont have pricing info for SFIN now, it will be assumed to be 0 and wont show up in the breakdown

**Comment by g1nt0ki** [comment]
> Is there a way I can handle the pricing stuff or is that something that your team does internally?

We rely on internal system for pricing, you can have a look at this repo: https://github.com/DefiLlama/defillama-server/tree/master/coins

this is for showing SFIN in the breakdown?

**Pull request merged**
