### PR TITLE
Rei chain first Dapp

### PR DESCRIPTION
**Pull request by tanopwan**
##### Twitter Link:
https://twitter.com/FoodcourtF

##### List of audit links if any:
https://app.inspex.co/library/foodcourt#?scope=foodcourt-amm-farm-wrappedtokens

##### Website Link:
https://reix.foodcourt.finance/#/swap (REI)
https://exchange.foodcourt.finance/#swap (BSC)

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://www.foodcourt.finance/images/coupon.svg

##### Current TVL:
277.07K

##### Chain:
BSC, REI

##### Short Description (to be shown on DefiLlama):
Foodcourt is DEX on REI chain that enable KUMA stable yield farming.

##### Token address and ticker if any: 
REI: 0xbC09220a8e461880DBE5517ecF53bC1b12cAa05D

##### Category (full list at https://defillama.com/categories) *Please choose only one:
[Dexes](https://defillama.com/protocols/Dexes)

##### methodology (what is being counted as tvl, how is tvl being calculated):
on-chain prices and cache in API

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/foodcourt exports TVL: 
        
 
 
    rei                       40.83 k
    bsc                       236.24 k
    
    total                    277.07 k

**Comment by tanopwan** [comment]
@g1nt0ki Hi, this is on chain calls but the result are caches in the api (there are multiple pools)
caches is around 15-30 seconds

**Comment by g1nt0ki** [comment]
@tanopwan by on-chain I meant calls to rpc instead of your server :)

**Comment by tanopwan** [comment]
@g1nt0ki I understand but can we compromise here :D since the server is actually call rpcs and on-chain oracle to calculate the price and TVL otherwise there will be a lot of calculation re-implementing.

**Comment by g1nt0ki** [comment]
@tanopwan can you explain a bit how the tvl is calculated, you have your own dex, and staking? we have some helper functions that makes it easy to compute tvl if you provide the factory address and staking address

**Comment by tanopwan** [comment]
@g1nt0ki sure, to calculate tvl
Each LP: (token0 * token0_price + token1 * token1_price) * staking_amount / total_supply
Then sum all the LP pairs.

it is normal UniswapV2 DEX
FoodcourtRouter: https://bscscan.com/address/0x0F4610aB02920a99f639F675085A5d3e24b0D7ae#code
FoodcourtFactory: https://bscscan.com/address/0xc801C7980c8C7900Bc898B1F38392b235fF64097#code
MasterChef: https://bscscan.com/address/0x07b48c393CabABf6458E72d57b7CcD8f73E94c03#code

**Pull request closed without merging**
