### PR TITLE
AlphaFi TVL

### PR DESCRIPTION
**Pull request by Zorag44**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Logo (High resolution, will be shown with rounded borders): 
alphafi_logo

##### Short Description (to be shown on DefiLlama):
Premier Yield Optimizer on the SUI Blockchain. Earn Safe, Real Yields with AlphaFi.

##### Token address and ticker if any:
Token address: 0xfe3afec26c59e874f3c1d60b8203cb3852d2bb2aa415df9548b8d688e6683f93::alpha::ALPHA
ticker: ALPHA

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/alphafi exports TVL: 
        
 
 
    sui                       10.25 M
    
    total                    10.25 M

**Comment by Zorag44** [comment]
ALPHA token is being shown as unrecognized. It is not being considered for the tvl calculation for ALPHA-SUI pool as well.

ALPHA token address: 0xfe3afec26c59e874f3c1d60b8203cb3852d2bb2aa415df9548b8d688e6683f93::alpha::ALPHA

**Comment by llamatester** [comment]
The adapter at projects/alphafi exports TVL: 
        
 
 
    sui                       9.56 M
    sui-pool2                 369.66 k
    pool2                     369.66 k
    sui-staking               0
    staking                   0
    
    total                    9.56 M

**Comment by g1nt0ki** [comment]
hi  @Zorag44  alpha token is not priced as it is not on coingecko. maybe we should start pricing tokens using cetus data.

I have split staking and pool2 from tvl.

Thanks for the PR

**Pull request merged**
