### PR TITLE
Create index.js

### PR DESCRIPTION
**Pull request by SwftCoins**
Apply to add bridgers to the DefiLlama family

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/bridgers: 
        
 
  
    
    
    Error: Multicall is missing a target
    Truncated error stack:
        at Object.multiCall (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/abi/index.js:199:19)
        at sumTokens (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/unwrapLPs.js:537:47)
        at async sumTokens2 (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/unwrapLPs.js:901:3)
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
Error while running adapter at projects/bridgers: 
        
 
  
    
    
    TypeError: Cannot read properties of null (reading 'getBalance')
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/eth/index.js:52:94
        at Array.map (<anonymous>)
        at sumTokens (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/unwrapLPs.js:527:55)
        at async sumTokens2 (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/unwrapLPs.js:901:3)
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
Error while running adapter at projects/bridgers: 
        
 
  
    
    
    Error: Multicall is missing a target
    Truncated error stack:
        at Object.multiCall (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/abi/index.js:199:19)
        at sumTokens (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/unwrapLPs.js:537:47)
        at async sumTokens2 (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/unwrapLPs.js:901:3)
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
Error while running adapter at projects/bridgers: 
        
 
  
    
    
    TypeError: Cannot read properties of null (reading 'getBalance')
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/eth/index.js:52:94
        at Array.map (<anonymous>)
        at sumTokens (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/unwrapLPs.js:527:55)
        at async sumTokens2 (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/unwrapLPs.js:901:3)
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by g1nt0ki** [comment]
@SwftCoins thanks for the PR, please fill in the project details:

---
##### Name (to be shown on DefiLlama):


##### Twitter Link:


##### List of audit links if any:


##### Website Link:


##### Logo (High resolution, will be shown with rounded borders):


##### Current TVL:


##### Treasury Addresses (if the protocol has treasury)


##### Chain:


##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)


##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)


##### Short Description (to be shown on DefiLlama):


##### Token address and ticker if any:


##### Category (full list at https://defillama.com/categories) *Please choose only one:


##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
##### Implementation Details: Briefly describe how the oracle is integrated into your project:
##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:

##### forkedFrom (Does your project originate from another project):


##### methodology (what is being counted as tvl, how is tvl being calculated):


##### Github org/user (Optional, if your code is open source, we can track activity):

**Comment by g1nt0ki** [comment]
the was mostly good, two issues were, the method you used supports only EVM chains, and we exclude projects own tokens from tvl

**Comment by llamatester** [comment]
The adapter at projects/bridgers exports TVL: 
        
 
 
    ethereum                  376.76 k
    tron                      223.08 k
    bsc                       164.37 k
    arbitrum                  63.82 k
    optimism                  32.82 k
    base                      22.13 k
    avax                      20.75 k
    polygon                   19.48 k
    era                       12.17 k
    heco                      2.83 k
    linea                     2.61 k
    okexchain                 1.97 k
    fantom                    1.62 k
    
    total                    944.41 k

**Comment by SwftCoins** [comment]
> @SwftCoins thanks for the PR, please fill in the project details:
> 
> ##### Name (to be shown on DefiLlama):
> ##### Twitter Link:
> ##### List of audit links if any:
> ##### Website Link:
> ##### Logo (High resolution, will be shown with rounded borders):
> ##### Current TVL:
> ##### Treasury Addresses (if the protocol has treasury)
> ##### Chain:
> ##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
> ##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
> ##### Short Description (to be shown on DefiLlama):
> ##### Token address and ticker if any:
> ##### Category (full list at https://defillama.com/categories) *Please choose only one:
> ##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
> ##### Implementation Details: Briefly describe how the oracle is integrated into your project:
> ##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
> ##### forkedFrom (Does your project originate from another project):
> ##### methodology (what is being counted as tvl, how is tvl being calculated):
> ##### Github org/user (Optional, if your code is open source, we can track activity):

**Comment by llamatester** [comment]
The adapter at projects/bridgers exports TVL: 
        
 
 
    ethereum                  415.29 k
    tron                      190.40 k
    bsc                       164.65 k
    arbitrum                  63.87 k
    optimism                  32.76 k
    base                      22.08 k
    avax                      20.73 k
    polygon                   19.46 k
    era                       12.14 k
    heco                      2.83 k
    linea                     2.61 k
    okexchain                 1.95 k
    fantom                    1.61 k
    
    total                    950.38 k

**Comment by SwftCoins** [comment]
> @SwftCoins thanks for the PR, please fill in the project details:
> 
> ##### Name (to be shown on DefiLlama): Bridgers
> ##### Twitter Link: https://x.com/Bridgersxyz
> ##### List of audit links if any: https://skynet.certik.com/zh-CN/projects/swft
> ##### Website Link: https://bridgers.ai/
> ##### Logo (High resolution, will be shown with rounded borders): https://images.swft.pro/dex/bridgers1.png
> ##### Current TVL: 1 M
> ##### Treasury Addresses (if the protocol has treasury)
> ##### Chain: ethereum, bsc, heco, okexchain, polygon, fantom, arbitrum, tron, solana, base, sui, aptos, ton, era, linea, optimism, avax
> ##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
> ##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
> ##### Short Description (to be shown on DefiLlama): Unbounded Swap, Infinite Possibilities.
> ##### Token address and ticker if any:
> ##### Category (full list at https://defillama.com/categories) *Please choose only one: Dexes
> ##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
> ##### Implementation Details: Briefly describe how the oracle is integrated into your project:
> ##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
> ##### forkedFrom (Does your project originate from another project): No
> ##### methodology (what is being counted as tvl, how is tvl being calculated):
> ##### Github org/user (Optional, if your code is open source, we can track activity):

**Comment by llamatester** [comment]
Error while running adapter at projects/bridgers: 
        
 
  
    
    
    Error: Multicall is missing a target
    Truncated error stack:
        at Object.multiCall (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/abi/index.js:199:19)
        at sumTokens (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/unwrapLPs.js:537:47)
        at async sumTokens2 (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/unwrapLPs.js:901:3)
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
The adapter at projects/bridgers exports TVL: 
        
 
 
    tron                      315.26 k
    ethereum                  208.77 k
    bsc                       87.46 k
    arbitrum                  64.93 k
    optimism                  32.78 k
    polygon                   26.58 k
    base                      21.68 k
    avax                      20.73 k
    era                       12.15 k
    sui                       3.26 k
    heco                      2.83 k
    linea                     2.61 k
    okexchain                 1.97 k
    fantom                    1.59 k
    aptos                     1.35 k
    ton                       391
    solana                    0
    
    total                    804.34 k

**Comment by llamatester** [comment]
The adapter at projects/bridgers exports TVL: 
        
 
 
    tron                      310.93 k
    ethereum                  208.77 k
    bsc                       88.20 k
    arbitrum                  64.93 k
    optimism                  32.78 k
    polygon                   26.58 k
    base                      21.71 k
    avax                      20.73 k
    era                       12.15 k
    sui                       3.26 k
    heco                      2.83 k
    linea                     2.61 k
    okexchain                 1.97 k
    fantom                    1.59 k
    aptos                     1.35 k
    ton                       391
    solana                    0
    
    total                    800.76 k

**Comment by llamatester** [comment]
The adapter at projects/bridgers exports TVL: 
        
 
 
    tron                      309.88 k
    ethereum                  203.94 k
    bsc                       90.19 k
    arbitrum                  64.89 k
    optimism                  32.76 k
    polygon                   26.55 k
    base                      21.70 k
    avax                      20.72 k
    era                       12.15 k
    sui                       3.26 k
    heco                      2.83 k
    linea                     2.61 k
    okexchain                 1.96 k
    fantom                    1.58 k
    aptos                     1.34 k
    ton                       391
    solana                    0
    
    total                    796.77 k

**Comment by g1nt0ki** [comment]
thanks for filling in the details

**Comment by llamatester** [comment]
The adapter at projects/bridgers-ai exports TVL: 
        
 
 
    tron                      220.15 k
    ethereum                  166.16 k
    bsc                       92.07 k
    arbitrum                  56.43 k
    optimism                  35.31 k
    base                      22.85 k
    avax                      20.91 k
    polygon                   17.08 k
    era                       12.25 k
    sui                       4.01 k
    heco                      2.83 k
    linea                     2.60 k
    okexchain                 1.95 k
    fantom                    1.58 k
    aptos                     1.33 k
    ton                       389
    solana                    0
    
    total                    657.90 k

**Pull request merged**
