### PR TITLE
Add iota evm and SEI

### PR DESCRIPTION
**Pull request by StrategicReserve**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/visor: 
        
 
  
    
    
    Error: Llama RPC error! methos: undefined 
    - host: https://evm-rpc.sei-apis.com error: height is not available (requested height: 78353999, base height: 82909999)
    - host: https://evm-rpc.sei-apis.com/ error: height is not available (requested height: 78353999, base height: 82909999)

**Comment by g1nt0ki** [comment]
We are having trouble fetching logs in sei, just there can you share code to pull vaults via graph/your api?

**Comment by StrategicReserve** [comment]
I'll talk to SEI right now

**Comment by g1nt0ki** [comment]
@StrategicReserve maybe we can get strategies via api/graph call just for sei?

**Comment by StrategicReserve** [comment]
submitted new one

**Pull request closed without merging**
