### PR TITLE
Update Renzo TVL

### PR DESCRIPTION
**Pull request by vokkantthakkar**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/renzo exports TVL: 
        
 
 
    ethereum                  791.86 M
    linea                     116.28 M
    arbitrum                  51.80 M
    optimism                  13.62 M
    mode                      12.88 M
    base                      9.75 M
    blast                     9.53 M
    fraxtal                   2.73 M
    bsc                       563.23 k
    
    total                    1.01 B

**Comment by vokkantthakkar** [comment]
yessir, lgtm

**Comment by llamatester** [comment]
The adapter at projects/renzo exports TVL: 
        
 
 
    ethereum                  808.56 M
    linea                     117.15 M
    arbitrum                  52.04 M
    zircuit                   30.02 M
    optimism                  13.72 M
    mode                      12.97 M
    base                      10.03 M
    blast                     9.60 M
    fraxtal                   2.75 M
    bsc                       577.48 k
    
    total                    1.06 B

**Comment by llamatester** [comment]
Error while running adapter at projects/renzo: 
        
 
  
    
    
    ReferenceError: chain is not defined
    Truncated error stack:
    
        at L2Tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/renzo/index.js:9:25)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:29)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:177:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:165:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:160:44
        at Object.<anonymous> (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:263:3)
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
The adapter at projects/renzo exports TVL: 
        
 
 
    ethereum                  809.77 M
    linea                     117.07 M
    arbitrum                  52.00 M
    zircuit                   30.00 M
    optimism                  13.71 M
    mode                      12.96 M
    base                      10.02 M
    blast                     9.59 M
    fraxtal                   2.75 M
    bsc                       576.52 k
    sei                       3.50 k
    
    total                    1.06 B

**Pull request merged**
