### PR TITLE
Add Yapeswap to Project

### PR DESCRIPTION
**Pull request by Torgmeister**
##### Twitter Link:
https://twitter.com/yapeswap

##### Website Link:
https://yape.exchange/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://ibb.co/jzccbqH
Lucy Transparent

##### Current TVL:
$2.9 Mil

##### Chain:
Ethereum

##### Description/bio (to be shown on DefiLlama):
Yapeswap is an Automated Market Maker that enables liquidity providers to earn additional yield by investing idle token reserves from liquidity pools into yield farming and aggregator services hosted by Yearn Finance. The protocol is maintained by independent developers and governed by veYAPE holders.

##### Token address and ticker if any:
0x757BC268bd50DA88b2d0cf1966652B18e56CA803
$YAPE

##### Category (Yield/Dexes/Lending/Minting):
Yield, DEX

##### [Optional] ETH addresss (to receive a LlamaPunk):
0x77FA39F3aDf09BDE9D4F175E40D0854D21a33318

### CODE REVIEW

**Comment by 0xngmi** [comment]
Why create two files, v1 and index?

**Comment by Torgmeister** [comment]
I just created both when I started playing around with it - I copied those from Uniswap folder as a jumping off point as I wasn't quite sure what was what.

**Comment by Torgmeister** [comment]
Anything we can do to speed up the PR? Please let us know if something is not right on your end and we'll try to fix ASAP.

**Comment by 0xngmi** [comment]
hey, the main issue with this PR is that only one file is needed. Furthermore, the current code is much more complicated than it needs to be

**Comment by 0xngmi** [comment]
I've just directly integrated it on d076e298b4c631bcca6bbc5e9774c667b64039dd

**Comment by 0xngmi** [comment]
https://twitter.com/DefiLlama/status/1430305708306694146

**Pull request closed without merging**
