### PR TITLE
init Klaytn Bluewhale

### PR DESCRIPTION
**Pull request by bluewhale-saito**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Bluewhale

##### Twitter Link:
https://twitter.com/BWPM_official

##### Website Link:
https://bwpm.io/

##### Treasury Addresses (if the protocol has treasury)
0xf4546e1d3ad590a3c6d178d671b3bc0e8a81e27d

##### Chain:
Klaytn

##### Token address and ticker if any:
BWPM Vault (sBWPM) 0xf4546e1d3ad590a3c6d178d671b3bc0e8a81e27d
Krill Token (KRILL) 0x83bc9fe9eebfeb1ad4178ac5e7445dc6a7e95718
Pearl Token (PEARL) 0xb3b1b54e3b9a27cee606f1018760abec4274bd35
Clam Token (CLAM) 0xba9725eaccf07044625f1d232ef682216f5371c2
AquaDolpin Vault (sADOL) 0x4f3ac44bb2345d3960e34dd5dfe275249e43ae4a

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bluewhale exports TVL: 
        
 
 
    klaytn                    0
    klaytn-staking            717.50 k
    klaytn-pool2              1.45 k
    staking                   717.50 k
    pool2                     1.45 k
    
    total                    0

**Comment by bluewhale-saito** [comment]
init klaytn bluewhale

**Comment by llamatester** [comment]
The adapter at projects/bluewhale exports TVL: 
        
 
 
    klaytn-staking            0
    klaytn-pool2              2.763439399899
    klaytn                    22.927727056185
    staking                   0
    pool2                     2.763439399899
    
    total                    22.927727056185

**Comment by g1nt0ki** [comment]
@bluewhale-saito thanks for the PR, I refactored it a bit, we can count only the LP staked as your pool2, not all tokens in the LP contract

**Pull request merged**
