### PR TITLE
feat: add defimaster folder

### PR DESCRIPTION
**Pull request by woshifyz**
**Name (to be shown on DefiLlama):  Defi Master**

**Website Link:** https://defimaster.pro/

**Twitter Link:** https://twitter.com/DefiFarmMaster

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/defimaster exports TVL: 
        
 
 
    arbitrum                  74.25 k
    
    total                    74.25 k

**Comment by g1nt0ki** [comment]
@woshifyz thanks for the PR, can you fill ni project details like website/ twitter account and such?

**Comment by woshifyz** [comment]
website:  https://defimaster.pro/
twitter:  https://twitter.com/DefiFarmMaster

**Comment by llamatester** [comment]
The adapter at projects/defimaster exports TVL: 
        
 
 
    arbitrum                  74.16 k
    
    total                    74.16 k

**Pull request merged**
