### PR TITLE
Adapter for Messina.one

### PR DESCRIPTION
**Pull request by AlgoFoundry**
**NOTE**

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Messina.one

##### Twitter Link:
https://twitter.com/MessinaOne

##### Website Link:
https://messina.one

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://messina.one/images/messina-logo-light.jpg
https://messina.one/images/messina-logo-dark.jpg

##### Current TVL:
2.79M

##### Chain:
Algorand, Ethereum

##### Short Description (to be shown on DefiLlama):
Cross-Chain Bridge, enabling the next 1B users to use blockchain.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Bridge

##### forkedFrom (Does your project originate from another project):
Portal

##### methodology (what is being counted as tvl, how is tvl being calculated):
Assets currently held by Messina.one contracts.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/messinaone exports TVL: 
        
 
 
    algorand                  3.55 M
    ethereum                  99.95 k
    
    total                    3.65 M

**Comment by llamatester** [comment]
The adapter at projects/messinaone exports TVL: 
        
 
 
    algorand                  3.56 M
    ethereum                  99.77 k
    
    total                    3.66 M

**Comment by rh-low** [comment]
> **NOTE**
> 
> > If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> 
> 1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
> 2. The protocol is usually listed within 24 hours of merging the PR
> 3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
> 4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
> 5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
> 6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap
> 
> ##### Name (to be shown on DefiLlama):
> Messina.one
> 
> ##### Twitter Link:
> https://twitter.com/MessinaOne
> 
> ##### List of audit links if any:
> ##### Website Link:
> https://messina.one
> 
> ##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
> https://messina.one/images/messina-logo-light.jpg https://messina.one/images/messina-logo-dark.jpg
> 
> ##### Current TVL:
> 2.79M
> 
> ##### Chain:
> Algorand, Ethereum
> 
> ##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
> ##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
> ##### Short Description (to be shown on DefiLlama):
> Cross-Chain Bridge, enabling the next 1B users to use blockchain.
> 
> ##### Token address and ticker if any:
> ##### Category (full list at https://defillama.com/categories) *Please choose only one:
> Bridge
> 
> ##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
> ##### forkedFrom (Does your project originate from another project):
> Portal
> 
> ##### methodology (what is being counted as tvl, how is tvl being calculated):
> Assets currently held by Messina.one contracts.

TVL from test doesn't match mentioned TVL right now because coingecko is fetching incorrect prices for "go" assets right now. This should automatically be fixed when coingecko updates their prices.

**Comment by llamatester** [comment]
The adapter at projects/messinaone exports TVL: 
        
 
 
    algorand                  0
    ethereum                  99.91 k
    
    total                    99.91 k

**Comment by g1nt0ki** [comment]
> The adapter at projects/messinaone exports TVL:
> 
> ```
> algorand                  0
> ethereum                  99.91 k
> 
> total                    99.91 k 
> ```

dont be alarmed,  have made a fix to algorand to fix the query: https://github.com/DefiLlama/DefiLlama-Adapters/commit/0a0e789bca6f97622be2a98d80812d8bcde79c69


Reason I made this change, I am planning to start caching http requests to other servers, so if the endpoint becomes unreachable, I can rely on the cache, this works with config but not with balances, hence the change

**Pull request merged**
