### PR TITLE
Added eos-evm adapter

### PR DESCRIPTION
**Pull request by nsjames**
##### Name (to be shown on DefiLlama):
EOS EVM

##### Twitter Link:
https://twitter.com/EOSNetworkFDN

##### Website Link:
https://eosnetwork.com/

##### Logo (High resolution, will be shown with rounded borders):
rsz_eos-evm

##### Current TVL:
$6.35m

##### Chain:
EOS

##### Short Description (to be shown on DefiLlama):
The EOS EVM is an Ethereum VM compatible environment on EOS. 

##### Token address and ticker if any:
`eosio.evm`
`EOS`

##### Category (full list at https://defillama.com/categories) *Please choose only one:
15 [Cross Chain](https://defillama.com/protocols/Cross%20Chain)

##### methodology (what is being counted as tvl, how is tvl being calculated):
The total amount of EOS that sits on the `eosio.evm` account, which is the total amount of user tokens locked into the EVM. 

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/eosnetworkfoundation

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/eos-evm exports TVL: 
        
 
 
    eos                       6.40 M
    
    total                    6.40 M

**Comment by g1nt0ki** [comment]
this is EOS bridged to exsat chain right? why not include it in this file/listing? https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/exsat/index.js#L10

**Comment by nsjames** [comment]
No, this is a different project. 

It's a smart contract on EOS that acts as an EVM running inside the EOS VM (sub-vm). 

https://eosnetwork.com/eos-evm/

**Comment by g1nt0ki** [comment]
ah, it's the bridge for eos evm

**Comment by nsjames** [comment]
Thanks!

**Pull request merged**
