### PR TITLE
Create panko tvl

### PR DESCRIPTION
**Pull request by inumune**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Panko

##### Twitter Link:
https://x.com/Panko_Finance

##### List of audit links if any:
https://docs.panko.finance/readme/audits

##### Website Link:
https://panko.finance/

##### Logo (High resolution, will be shown with rounded borders):
https://panko.finance/favicon.ico

##### Current TVL:
200k+

##### Chain:
167000

##### forkedFrom (Does your project originate from another project):
Pancake

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/panko exports TVL: 
        
 
 
    taiko                     274.76 k
    
    total                    274.76 k

**Comment by Define101** [comment]
@inumune is a uniswap fork correct? V2 or v3 and what is the factory address

**Comment by inumune** [comment]
> @inumune is a uniswap fork correct? V2 or v3 and what is the factory address

Yes correct, V3 for the non stables 
Factory address: 0x99960D7076297a1E0C86f3cc60FfA5d6f2B507B5

**Comment by llamatester** [comment]
The adapter at projects/panko exports TVL: 
        
 
 
    taiko                     386.56 k
    
    total                    386.56 k

**Comment by g1nt0ki** [comment]
thanks for the PR

**Pull request merged**
