### PR TITLE
add allinx.js

### PR DESCRIPTION
**Pull request by allinxproject**

### CODE REVIEW

**Comment by 0xngmi** [comment]
Could you please:
- fill in all the questions asked on the PR template
- provide an adapter that calculates the TVL from blockchain calls instead of through an API endpoint

**Comment by allinxproject** [comment]
> Could you please:
> 
> * fill in all the questions asked on the PR template
> * provide an adapter that calculates the TVL from blockchain calls instead of through an API endpoint

Description of Readme

“2.Create a function called fetch returning your TVL (and export it)”

I fork the template from venus:

https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/venus.js

"provide an adapter that calculates the TVL from blockchain calls instead of through an API endpoint"

Do you mean to read totalSupply from the contract:

https://docs.llama.fi/submit-a-project

But does the wbtc.js code mean only the get total supply of the token, and what is the relationship with TVL?

**Comment by 0xngmi** [comment]
I've re-written the docs and hopefully now they should be easier to understand.

I've also written a prototype of your adapter on #81, which right now doesn't capture all the TVL because it's missing some LP tokens. Given that the LP contracts were not verified on etherscan and they don't follow the uniswap interface I was unable to unwrap those tokens.

**Comment by 0xngmi** [comment]
Replaced by #82

**Pull request merged**
