### PR TITLE
Add Amet Finance to Defi Llama

### PR DESCRIPTION
**Pull request by amet-finance-core**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Amet Finance

##### Twitter Link:
https://twitter.com/amet_finance

##### List of audit links if any:
https://solidityscan.com/published-report/project/e3ec78102f482ae7

##### Website Link:
https://amet.finance

##### Logo (High resolution, will be shown with rounded borders):
https://storage.amet.finance/icons/amet-logo-high-res.png

##### Current TVL:
$30

##### Chain:
Manta

##### Short Description (to be shown on DefiLlama):
Amet Finance is a decentralized finance platform for on-chain bonds, providing secure financial transactions and investment opportunities in the blockchain ecosystem

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Services

##### methodology (what is being counted as tvl, how is tvl being calculated):
T​otal ​V​alue ​L​ocked on Amet Finance is calculated by considering the total value of assets locked in the on-chain bonds. It includes the value of both the investment and interest tokens locked in the bonds on the platform. The methodology involves tracking the current market value of these tokens to provide an accurate representation of the overall value locked in the Amet Finance ecosystem.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/Amet-Finance/contracts

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/amet-finance exports TVL: 
        
 
 
    manta                     30.38759919
    
    total                    30.38759919

**Comment by llamatester** [comment]
The adapter at projects/amet-finance exports TVL: 
        
 
 
    manta                     20.41039
    
    total                    20.41039

**Comment by g1nt0ki** [comment]
hi @amet-finance-core thanks for the PR

I refactored the code a bit, bit confused what is counted as interest, but I have updated code to could all the token value in the contracts as tvl. Let me know if you are fine with the changes.

**Comment by amet-finance-core** [comment]
> hi @amet-finance-core thanks for the PR
> 
> I refactored the code a bit, bit confused what is counted as interest, but I have updated code to could all the token value in the contracts as tvl. Let me know if you are fine with the changes.

hi @g1nt0ki 

The refactor looks good, but there's a small logical change as well. For the TVL, we calculate the amount of interest token held in the contract plus the multiplication of the investment amount and the purchased bond count. I updated it a bit, so please confirm 👍

**Comment by llamatester** [comment]
The adapter at projects/amet-finance exports TVL: 
        
 
 
    manta                     30.364928250000002
    
    total                    30.364928250000002

**Comment by g1nt0ki** [comment]
Hi @amet-finance-core this bond is issued by your protocol right? If so, we can't include its value in this only the value of tokens backing it/in the contract

**Comment by amet-finance-core** [comment]
> Hi @amet-finance-core this bond is issued by your protocol right? If so, we can't include its value in this only the value of tokens backing it/in the contract

Yes, the bonds issued by our protocol. In our calculations of TVL, we use the interest token locked in the contract for the repayment and the total amount that was raised by selling the bonds. If it cannot be there, just let me know, and I will remove it and only leave the interest locked in the contract.

Please consider that, if we had a button for the issuer to harvest the amount held in the contract (the total investment amount), the amount could be calculated, but if we send it directly to the issuer, then it cannot?

**Comment by g1nt0ki** [comment]
yeah, we are bit strict about this, we count only the tokens locked in a contract. Same reason why we show opensea tvl as 0 because the NFTs remain in user wallet

**Comment by llamatester** [comment]
The adapter at projects/amet-finance exports TVL: 
        
 
 
    manta                     20.41039
    
    total                    20.41039

**Pull request merged**
