### PR TITLE
add avalanche borrowing module

### PR DESCRIPTION
**Pull request by tutacrypto**
Hey llamas, 

small PR to add Avalanche TVL from the borrowing module. Not much TVL yet, mainly to let people know it's live on Avalanche. Cheers! 

cc @g1nt0ki tagging you as you were the last one to update the code

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/angle: 
        
 
  
    
    
    Error: 
        Unknown chain(s): avalanche
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file

**Comment by tutacrypto** [comment]
🤔

**Comment by llamatester** [comment]
The adapter at projects/angle exports TVL: 
        
 
 
    avax                      14.875065000000001
    arbitrum                  614.42 k
    ethereum-staking          8.41 M
    polygon                   352.97 k
    ethereum                  51.36 M
    optimism                  247.90 k
    staking                   8.41 M
    
    total                    52.58 M

**Comment by g1nt0ki** [comment]
@tutacrypto we use "avax" :)

**Pull request merged**
