### PR TITLE
TVL for GenomesDAO

### PR DESCRIPTION
**Pull request by Charles-repo**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
GenomesDAO

##### Twitter Link:
@GenomesDAO

##### Website Link:
https://genomes.io

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://sendgb.com/SfQkdqi0n5O

##### Current TVL:
50.06 k

##### Chain:
Polygon

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
genomesdao

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
15169

##### Short Description (to be shown on DefiLlama):
We believe you should own your own genome, the DNA blueprint of what makes you who you are, so we built Genomes.io. Genomes.io is a private and secure DNA data bank that puts you back in control of your genome utilising AMD SVS-ES Vault and blockchain technology. By addressing privacy, security and ownership concerns of DNA testing and sharing, we are building the world’s largest user-owned genomic data bank to secure the future of personalised medicine.

##### Token address and ticker if any:
0x34667ED7C36cBBbF2d5d5c5c8d6Eb76a094EDb9F, GENE

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Services

##### methodology (what is being counted as tvl, how is tvl being calculated):
SDK Adapter

### CODE REVIEW

**Comment by Charles-repo** [comment]
our project is just service, not a protocol

**Comment by g1nt0ki** [comment]
@Charles-repo from your site, I dont see any defi related activity, are users locking their tokens in your service at any point? if not, not sure if we should list your service

**Comment by Charles-repo** [comment]
we use harvest.finance for liquidity mining, what do you think?

**Comment by Charles-repo** [comment]
@g1nt0ki

**Comment by g1nt0ki** [comment]
sorry, that is harvest.finance tvl, still not yours

**Comment by Charles-repo** [comment]
@g1nt0ki then what could we calculate as tvl for the service?
you're right.
we're not a dex, just a service.
like ethereum doesnt have liquidity

**Comment by g1nt0ki** [comment]
sorry, the way I see, you dont have any web3 interaction in your service (so far) like your user is not staking tokens/any other web3 interaction, we cant list it.

**Pull request closed without merging**
