### PR TITLE
export borrowed

### PR DESCRIPTION
**Pull request by zavodil**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/burrow.cash/index.js exports TVL: 
        
 
 
    near-borrowed             133091749395.30 B
    near                      135.72 M
    borrowed                  133091749395.30 B
    
    total                    135.72 M

**Comment by waynebruce0x** [comment]
Can you check the borrowed value here - is there a decimal conversion issue?

**Comment by zavodil** [comment]
> Can you check the borrowed value here - is there a decimal conversion issue? Please use 'node test.js projects/burrow.cash/index.js ' to check your output

Many thanks, that helped!
@waynebruce0x Please review an update

**Comment by waynebruce0x** [comment]
Sorry I actually wrote a borrowed section for burrow a couple of days ago, thats why we've got a merge conflict. Does this look accurate? https://defillama.com/protocol/burrow

**Pull request closed without merging**
