### PR TITLE
Fetch adapter for FRAKT

### PR DESCRIPTION
**Pull request by rustairov**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@rustairov thanks for the PR, but you instead compute tvl using on chain calls? let me know if you need some help

**Comment by g1nt0ki** [comment]
yes, but right now, the only proof for those statements are your word, I dont even see any description about what is included under tvl

if you share program id and idl, I can try to write the adapter

**Comment by g1nt0ki** [comment]
hi @vedamire , thanks for your detailed and patient answer. 
Right now, we are making our listing process more strict, we accept only on chain adapters
Regarding tvl, you can count the lent out amount under 'borrowed' and rest left in the pool under 'tvl'. Sorry, but dont think you can count NFTs as part of tvl, we are not counting NFT value in any other protocol, example, sudoswap allows you to create a pool with NFTs, but we count only the ether in the pool

**Comment by vedamire** [comment]
> hi @vedamire , thanks for your detailed and patient answer. 
> Right now, we are making our listing process more strict, we accept only on chain adapters
> Regarding tvl, you can count the lent out amount under 'borrowed' and rest left in the pool under 'tvl'. Sorry, but dont think you can count NFTs as part of tvl, we are not counting NFT value in any other protocol, example, sudoswap allows you to create a pool with NFTs, but we count only the ether in the pool

Well, we are NFT loans protocol, it would not really be accurate if we don't count the NFTs value in TVL at least with the floor price value. Of course we can give you means to count our borrowed amount and unutilized deposits. But it will be incomplete data and users will make questions why the tvl differs on DefiLama and our stats. Maybe we can count the snapshotted floor price for NFTs after the loan is taken? We have it onchain

**Comment by g1nt0ki** [comment]
"Maybe we can count the snapshotted floor price for NFTs after the loan is taken? We have it onchain" 

yes, this sounds like a good way forward, can you please update the adapter with this?

**Comment by vedamire** [comment]
> "Maybe we can count the snapshotted floor price for NFTs after the loan is taken? We have it onchain" 
> 
> yes, this sounds like a good way forward, can you please update the adapter with this?

Hey, yes, we will update adapter to rely solely on onchain data

**Comment by g1nt0ki** [comment]
@rustairov I have merged and refactored the code a bit to split borrowed from tvl, can you go through the changes when you have time and see if I have not messed up anything? https://github.com/DefiLlama/DefiLlama-Adapters/pull/3636/files

**Comment by g1nt0ki** [comment]
well, it is weekend, so maybe in a day or so.

**Comment by g1nt0ki** [comment]
https://defillama.com/protocol/frakt

**Pull request merged**
