### PR TITLE
Track Kimberlite Lab's Smart Contract TVL

### PR DESCRIPTION
**Pull request by EVMlord**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Kimberlite Labs

##### Twitter Link:
https://twitter.com/KimberliteLabs

##### List of audit links if any:
https://github.com/TTEB-Finance/SmartContractAudits/blob/main/Dogechain/Kimberlite%20Safe%20Audit%20Report.pdf

##### Website Link:
https://kimberlite.rocks

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://kimberlite.rocks/branding/logo.png
https://kimberlite.rocks/branding/logo.svg

##### Treasury Addresses (if the protocol has treasury)
0xC95056c9c9f5CcaEbc2F343CB4fBc75BFf64Eb78

##### Chain:
Arbitrum

##### Short Description (to be shown on DefiLlama):
Multichain AI based High Yield • Token/LP Locker • Utility NFT Collection

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield

##### methodology (what is being counted as tvl, how is tvl being calculated):
Counts TVL of all the tokens locked on the Kimberlite Safe locker smart contracts.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/kimberlite: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by EVMlord** [comment]
> Error while running adapter at projects/kimberlite:
> 
> ```
> Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
> Truncated error stack:
> 
>     at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11
> ```

Can you clarify please?

**Comment by llamatester** [comment]
Error while running adapter at projects/kimberlite: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by llamatester** [comment]
Error while running adapter at projects/kimberlite: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by llamatester** [comment]
Error while running adapter at projects/kimberlite: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by llamatester** [comment]
Error while running adapter at projects/kimberlite: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by llamatester** [comment]
Error while running adapter at projects/kimberlite: 
        
 
  
    
    
    Error: 
        Please move the following keys into the chain: tvl
    
        We have a new adapter export specification now where tvl and other chain specific information are moved inside chain export.
        For example if your protocol is on ethereum and has tvl and pool2, the export file would look like:
        
            module.exports = {
              methodlogy: '...',
              ethereum: {
                tvl: 
                pool2:
              }
            }

**Comment by llamatester** [comment]
Error while running adapter at projects/kimberlite: 
        
 
  
    
    
    ReferenceError: blacklist is not defined
    Truncated error stack:
    
        at getBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/kimberlite/index.js:30:7)
        at async calculateTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/kimberlite/index.js:14:27)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by llamatester** [comment]
Error while running adapter at projects/kimberlite: 
        
 
  
    
    
    TypeError: Cannot convert undefined or null to object
    Truncated error stack:
    
        at Function.entries (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:313:10)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:326:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:54:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by llamatester** [comment]
Error while running adapter at projects/kimberlite: 
        
 
  
    
    
    TypeError: Cannot convert undefined or null to object
    Truncated error stack:
    
        at Function.entries (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:313:10)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:326:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:54:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by llamatester** [comment]
Error while running adapter at projects/kimberlite: 
        
 
  
    
    
    TypeError: Cannot convert undefined or null to object
    Truncated error stack:
    
        at Function.entries (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:313:10)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:326:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:54:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)
        at async Promise.all (index 4)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by llamatester** [comment]
Error while running adapter at projects/kimberlite: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by llamatester** [comment]
Error while running adapter at projects/kimberlite: 
        
 
  
    
    
    Error: Invalid block: arbitrum
    Truncated error stack:
        at fixBlockTag (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/abi/index.js:126:15)
        at new Promise (<anonymous>)
        at calculateTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/kimberlite/index.js:8:49)
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/kimberlite/index.js:66:47)

**Comment by llamatester** [comment]
Error while running adapter at projects/kimberlite: 
        
 
  
    
    
    Error: Missing calls parameter
    Truncated error stack:
        at Object.<anonymous> (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/abi/index.js:167:31)
        at new Promise (<anonymous>)
        at calculateTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/kimberlite/index.js:7:49)
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/kimberlite/index.js:70:47)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:29)

**Comment by llamatester** [comment]
Error while running adapter at projects/kimberlite: 
        
 
  
    
    
    TypeError: Cannot convert undefined or null to object
    Truncated error stack:
    
        at Function.entries (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:313:10)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:326:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:54:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)
        at async Promise.all (index 0)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by llamatester** [comment]
Error while running adapter at projects/kimberlite: 
        
 
  
    
    
    TypeError: Cannot convert undefined or null to object
    Truncated error stack:
    
        at Function.entries (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:313:10)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:326:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:54:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)
        at async Promise.all (index 0)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by llamatester** [comment]
Error while running adapter at projects/kimberlite: 
        
 
  
    
    
    TypeError: Cannot convert undefined or null to object
    Truncated error stack:
    
        at Function.entries (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:313:10)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:326:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:54:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by llamatester** [comment]
Error while running adapter at projects/kimberlite: 
        
 
  
    
    
    TypeError: Cannot convert undefined or null to object
    Truncated error stack:
    
        at Function.entries (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:313:10)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:326:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:54:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)
        at async Promise.all (index 0)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by llamatester** [comment]
Error while running adapter at projects/kimberlite: 
        
 
  
    
    
    PromisePoolError: unable to determine stateMutability (argument="value", value={"type":"function"}, code=INVALID_ARGUMENT, version=abi/5.7.0)
    Truncated error stack:
        at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
Error while running adapter at projects/kimberlite: 
        
 
  
    
    
    TypeError: Cannot convert undefined or null to object
    Truncated error stack:
    
        at Function.entries (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:313:10)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:326:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:54:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)
        at async Promise.all (index 5)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by llamatester** [comment]
Error while running adapter at projects/kimberlite: 
        
 
  
    
    
    ReferenceError: abi is not defined
    Truncated error stack:
    
        at mapTokensToContract (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/kimberlite/index.js:21:10)
        at calculateTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/kimberlite/index.js:11:33)
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/kimberlite/index.js:51:47)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:29)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:136:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:131:44

**Comment by llamatester** [comment]
Error while running adapter at projects/kimberlite: 
        
 
  
    
    
    ReferenceError: length is not defined
    Truncated error stack:
    
        at mapTokensToContract (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/kimberlite/index.js:32:23)
        at calculateTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/kimberlite/index.js:20:33)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)
        at async Promise.all (index 2)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by llamatester** [comment]
Error while running adapter at projects/kimberlite: 
        
 
  
    
    
    ReferenceError: vault is not defined
    Truncated error stack:
    
        at mapTokensToContract (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/kimberlite/index.js:33:24)
        at calculateTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/kimberlite/index.js:20:33)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)
        at async Promise.all (index 2)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by llamatester** [comment]
The adapter at projects/kimberlite exports TVL: 
        
 
 
    polygon                   10.41
    arbitrum                  225.30871863160826
    core                      0.000153
    metis                     1.001
    dogechain                 0
    bsc                       1.0108320000000002
    
    total                    237.73070363160826

**Comment by llamatester** [comment]
The adapter at projects/kimberlite exports TVL: 
        
 
 
    polygon                   10.42
    metis                     0.999827
    arbitrum                  225.10643982042737
    bsc                       1.01153472
    core                      0.000154
    dogechain                 0
    
    total                    237.53795554042736

**Comment by llamatester** [comment]
Error while running adapter at projects/kimberlite: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'forEach')
    Truncated error stack:
    
        at getUniqueAddresses (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/utils.js:140:13)
        at vestingHelper (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/cache/vestingHelper.js:16:12)
        at getBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/kimberlite/index.js:43:18)
        at async calculateTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/kimberlite/index.js:20:22)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 1)
        at async Promise.all (index 2)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by llamatester** [comment]
Error while running adapter at projects/kimberlite: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'forEach')
    Truncated error stack:
    
        at getUniqueAddresses (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/utils.js:140:13)
        at vestingHelper (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/cache/vestingHelper.js:16:12)
        at getBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/kimberlite/index.js:43:18)
        at async calculateTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/kimberlite/index.js:20:22)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 1)
        at async Promise.all (index 2)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by llamatester** [comment]
Error while running adapter at projects/kimberlite: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'forEach')
    Truncated error stack:
    
        at getUniqueAddresses (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/utils.js:140:13)
        at vestingHelper (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/cache/vestingHelper.js:16:12)
        at getBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/kimberlite/index.js:43:18)
        at async calculateTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/kimberlite/index.js:20:22)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 1)
        at async Promise.all (index 0)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by llamatester** [comment]
Error while running adapter at projects/kimberlite: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by llamatester** [comment]
The adapter at projects/kimberlite exports TVL: 
        
 
 
    arbitrum                  225.50208838440426
    polygon                   10.42
    metis                     0.999737
    dogechain                 0
    core                      0.000154
    bsc                       1.0062297599999999
    
    total                    237.92820914440426

**Comment by llamatester** [comment]
The adapter at projects/kimberlite exports TVL: 
        
 
 
    polygon                   0
    dogechain                 0
    arbitrum                  211.5501705620395
    bsc                       4.77 k
    metis                     0
    core                      15.08 k
    
    total                    20.06 k

**Comment by llamatester** [comment]
The adapter at projects/kimberlite exports TVL: 
        
 
 
    polygon                   0
    arbitrum                  212.0509151123521
    metis                     0
    dogechain                 0
    core                      15.08 k
    bsc                       4.78 k
    
    total                    20.07 k

**Comment by llamatester** [comment]
The adapter at projects/kimberlite exports TVL: 
        
 
 
    arbitrum                  225.51911838440427
    polygon                   10.45
    metis                     0.99944
    core                      0.000155
    dogechain                 0
    bsc                       1.00637808
    
    total                    237.97509146440424

**Comment by llamatester** [comment]
Error while running adapter at projects/kimberlite: 
        
 
  
    
    
    SyntaxError: Cannot convert [object Object] to a BigInt
    Truncated error stack:
    
        at BigInt (<anonymous>)
        at calculateTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/kimberlite/index.js:34:23)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 1)
        at async Promise.all (index 2)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by llamatester** [comment]
The adapter at projects/kimberlite exports TVL: 
        
 
 
    polygon                   0
    arbitrum                  0
    dogechain                 0
    bsc                       0
    metis                     0
    core                      0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/kimberlite exports TVL: 
        
 
 
    polygon                   10.42
    arbitrum                  435.15290089643577
    metis                     1
    core                      14.98 k
    dogechain                 0
    bsc                       5.38 k
    
    total                    20.80 k

**Comment by g1nt0ki** [comment]
hi @EVMlord sorry, missed your messages but there seems to be some double counting going on here, please check my refactor and see if I introduced some bugs: https://github.com/DefiLlama/DefiLlama-Adapters/pull/6025

**Comment by EVMlord** [comment]
> hi @EVMlord sorry, missed your messages but there seems to be some double counting going on here, please check my refactor and see if I introduced some bugs: #6025

Thanks for the updates @g1nt0ki, very neat code 😊

What's your twitter handle?  I'll like to connect.

There are a number of issues though.
1. Project name is **Kimberlite Labs**, not _Kimberlite(KLB)_. We do not have a native token(yet), KLB given to our users on Arbitrum One are bonus points which can be redeemed for ETH. Please fix 🙏
2.  Please category should be **yield**, not _yield aggregator_.
3. Then we got this message under all chain TVL's (we do not deposit into another protocol), should double count be included in the exports and set to false?

image


And finally, 
> methodology:
>     "Counts TVL of all the tokens locked on the Kimberlite Safe locker smart contracts.",

Thanks again! 🤝

**Pull request closed without merging**
