### PR TITLE
Added eth tvl

### PR DESCRIPTION
**Pull request by babayega**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI

---

Added the tvl on eth mainnet

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/polysynth: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:219:11

**Comment by babayega** [comment]
```
--- ethereum ---
WETH                      436.97 k
USDC                      300.32 k
WBTC                      212.07 k
Total: 949.36 k 

--- polygon ---
USDC                      182.88 k
WETH                      155.90 k
WBTC                      84.28 k
Total: 423.06 k 

--- tvl ---
WETH                      592.87 k
USDC                      483.20 k
WBTC                      296.35 k
Total: 1.37 M 

------ TVL ------
ethereum                  949.36 k
polygon                   423.06 k

total                    1.37 M 
```

When I run the tests, getting the above output

**Comment by g1nt0ki** [comment]
@babayega I have removed `underscore` dependency from package.json, not sure how it is working for you locally, but it would fail in our server, can you please update adapter code

**Comment by llamatester** [comment]
The adapter at projects/polysynth exports TVL: 
        
 
 
    ethereum                  1.07 M
    polygon                   385.01 k
    
    total                    1.46 M

**Comment by babayega** [comment]
Removed underscore, please check now

**Comment by g1nt0ki** [comment]
@babayega sorry, I was bit too quick and added your code here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/3274

**Pull request closed without merging**
