### PR TITLE
Hourglass adaptor

### PR DESCRIPTION
**Pull request by alex-hourglass**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Hourglass

##### Twitter Link:
https://x.com/hourglasshq

##### List of audit links if any:
https://github.com/SublimeGroupSecurity/security_audits/tree/main/Hourglass
https://github.com/TheArcadiaGroup/publications/blob/main/audits/HourglassAudit3.pdf

##### Website Link:
https://hourglass.com/

##### Logo (High resolution, will be shown with rounded borders):
hourglass-icon-light-on-dark

##### Current TVL:
7.63 M

##### Chain:
Ethereum, Mantle

##### Short Description (to be shown on DefiLlama):
Hourglass maximizes restaking rewards by time-boosting your stake in the top Web3 protocols.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL accounts for all assets deposited into our boosted vaults. It also includes the amount of FXS time-locked and minted as pitchFXS.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/pitch-foundation

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/hourglass exports TVL: 
        
 
 
    ethereum                  6.55 M
    mantle                    1.10 M
    
    total                    7.65 M

**Comment by llamatester** [comment]
The adapter at projects/hourglass exports TVL: 
        
 
 
    ethereum                  4.41 M
    mantle                    0
    
    total                    4.41 M

**Comment by g1nt0ki** [comment]
thanks for the PR, we will fix missing token prices

**Comment by alex-hourglass** [comment]
Amazing, thanks a lot for the refactor. Way cleaner and future-proof.

Waiting for the token prices fix 🙏

**Comment by g1nt0ki** [comment]
looking into why LBTCv doesnt have price

**Pull request merged**
