### PR TITLE
I want to update the methodology and change logos, can't find this in https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts

### PR DESCRIPTION
**Pull request by ivanvolov**
**NOTE**

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Hedgehog

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://near-space.s3.eu-central-1.amazonaws.com/hedgie-black.png
https://near-space.s3.eu-central-1.amazonaws.com/hedgie-white.png

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
hedgehog

##### methodology (what is being counted as tvl, how is tvl being calculated):
Counts the amount of wETH, USDC & oSQTH in the strategy-controlled pools and treasury

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/hedgehog exports TVL: 
        
 
 
    ethereum                  136.91 k
    
    total                    136.91 k

**Comment by g1nt0ki** [comment]
@ivanvolov this is the place to update methodology, we have to update logo in two other repos, will take care of it. Remind me if it is not fixed in the next 24 hours in the UI

**Comment by ivanvolov** [comment]
@g1nt0ki The methodology and Protocol description are updated, but the logo is not. Also, the coingecko data (https://www.coingecko.com/en/coins/hedgehog) is not updated, how could I do that?

**Comment by g1nt0ki** [comment]
let me check

**Comment by g1nt0ki** [comment]
@ivanvolov For coingecko, I think the reason is, they are not showing token price, so tvl is hidden.
https://defillama.com/protocol/hedgehog I see the logo here, is that not the right one? can you try clearing cache/in private window?

**Comment by ivanvolov** [comment]
@g1nt0ki Thank you, clearing the cache helped! 🎉 🎉 🎉

So, do you have some suggestions about coingecko? Should we create a uniswap pool or is there another way around it?

**Comment by g1nt0ki** [comment]
Not very familiar with the process, I thought they would have detail info here: https://www.coingecko.com/en/methodology but I cant find exact requirement

Can you check with them by mailing support, iirc, probably need to have pool for at least x number of days to prove liquidity exists

**Pull request merged**
