### PR TITLE
illuminex TVL tracking added

### PR DESCRIPTION
**Pull request by party-for-illuminati**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
illumineX

##### Twitter Link:
https://twitter.com/illuminexswap

##### List of audit links if any:
https://dedaub.com/audits/illuminex/illuminex-jan-19-2024/

##### Website Link:
https://illuminex.xyz/swap

##### Logo (High resolution, will be shown with rounded borders):
https://drive.google.com/file/d/1UnS3JTYa5tJKTE_RVupUiaqU_pxtMMjo/view?usp=drive_link

##### Current TVL:
~6.1M$ in liquidity, ~3M$ of liquidity locked in liquidity mining pools and ~11.4M$ worth of $IX tokens locked in single staking

##### Chain:
Oasis Sapphire

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
private-wrapped-ix

##### Short Description (to be shown on DefiLlama):
illumineX is a decentralised cross-chain layer asset bridge offering private swaps and transfers between assets, utilising Oasis Sapphire technology to provide compliant confidential and non-custodial exchange

##### Token address and ticker if any:
IX or pIX: 0xd7f2507CAFe0F04f5C1939999e9bE4E1B36dC219

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Privacy

##### methodology (what is being counted as tvl, how is tvl being calculated):
Counts liquidity on illumineX Exchange, as well as IX token single staking together with liquidity mining locked LP

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/illuminex exports TVL: 
        
 
 
    sapphire-staking          11.74 M
    sapphire-pool2            0
    sapphire                  0
    staking                   11.74 M
    pool2                     0
    
    total                    0

**Comment by party-for-illuminati** [comment]
The pricing for tokens on illumineX isn't available on the DefiLlama backend side. On Discord we've been informed: "They can just make the adapter. and submit the PR We will add support for the tokens we can"

**Comment by llamatester** [comment]
The adapter at projects/illuminex exports TVL: 
        
 
 
    sapphire-staking          10.60 M
    sapphire                  6.11 M
    staking                   10.60 M
    
    total                    6.11 M

**Comment by g1nt0ki** [comment]
@party-for-illuminati thanks for the PR

**Comment by g1nt0ki** [comment]
I have removed pool2, as it would be doublecounting what is already counted as tvl

**Pull request merged**
