### PR TITLE
Update zeepr

### PR DESCRIPTION
**Pull request by JoJo-Joker**
Hello, sorry to bother you again. I have pledged my coins on the contract not in the EOA, and the address 0xbB0390Cf2586e9b0A4FAADF720aE188D140E9fd5 is the token I pledged. I have also listed my tokens and prices (as shown in the pictures) on Coinecko, are these okay? 

But when I finish writing the code and run it, the value I get is still 0, whether it's TVL or quantity. Do I need to make any changes? Or can I refer to which document?

截屏2024-04-09 21 04 38

截屏2024-04-09 21 05 45

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/zeepr exports TVL: 
        
 
 
    arbitrum                  0
    
    total                    0

**Review by g1nt0ki — COMMENTED** [review]
is this your listing? https://www.coingecko.com/en/coins/zeepr why is it linked to a solana address and not your arbitrum address? thats why it is not showing up

**Comment by JoJo-Joker** [comment]
@g1nt0ki 
(0xe46C5eA6Da584507eAF8dB2F3F57d7F578192e13)This is a contract for coins, which also provides a totalMargins method to query the current quantity of zeepr coins. Do you need this method? Or just use the balanceof method directly?

**Comment by JoJo-Joker** [comment]
@g1nt0ki 
I understand. We have multiple chains. May I change the contract address and staking address to Solana? Is the code still written in the current format correct?

**Comment by g1nt0ki** [comment]
@JoJo-Joker I have refactored and merged it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/9796/files

**Comment by JoJo-Joker** [comment]
@g1nt0ki ok, thank you! May I see zeepr on the dashboard now? I don't seem to be able to find it. May I ask which section can I find it in?

**Pull request closed without merging**
