### PR TITLE
Add Adapter for LendeXe Finance TVL & Borrowing metrics

### PR DESCRIPTION
**Pull request by xfujin**
##### Name (to be shown on DefiLlama):
LendeXe Finance

##### Twitter Link:
https://twitter.com/LendeXeFinance

##### List of audit links if any:
https://www.certik.com/projects/lendexe

##### Website Link:
https://lendexe.fi/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://drive.google.com/drive/folders/1Mt43emDKkL4fuks2n-fLb8hyKiRqWFqx?usp=share_link

##### Current TVL:
$517,536.19

##### Treasury Addresses (if the protocol has treasury)
0xBB0ADf43719b426f5F3d8392990f4572403744cB

##### Chain:
Ethereum Mainnet

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
lendexe

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
23619

##### Short Description (to be shown on DefiLlama):
LendeXe is a Web3 ecosystem of various innovative DeFi applications.

The past has shown that Stablecoins are not really stable. This was mainly due to the fact that various Stablecoins were backed by volatile tokens. At the center of LendeXe’s vision is the XSD Stablecoin. This is the safest stablecoins in the market because it is backed by the three largest other Stablecoins: USDT, USDC, BUSD. Even if one of these Stablecoins were to implode for some unknown reason, there are safety mechanics designed for such unlikely cases.

That’s why Lendexe offers several ways to mint XSD Stablecoins in order to help preserve the value of one’s assets during a market downturn. In addition, XSD can be used as collateral for the Lendexe Decentralized Lending Protocol.

Around the XSD Stablecoin, Lendexe has created a variety of products that allow anyone to secure their crypto assets or create passive income with them. From LendeXe Lending to the Ultimate Loan (a loan for 1.5x the value of your collateral).

##### Token address and ticker if any:
0x53011e93f21ec7a74cdfbb7e6548f1abce306833
[LEXE/USDC on Uniswap](https://app.uniswap.org/#/pool/451819)
[LEXE/ETH on Uniswap](https://app.uniswap.org/#/pool/451826)
[LEXE/USDT on P2B](https://p2pb2b.com/trade/LEXE_USDT/)
[LEXE/BTC on P2B](https://p2pb2b.com/trade/LEXE_BTC/)

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### forkedFrom (Does your project originate from another project):
Compound Protocol V2

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is calculated by getting the market addresses from comptroller and calling the getCash() on-chain method to get the amount of tokens locked in each of these addresses, then we get the price of each token from coingecko.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/lendexe exports TVL: 
        
 
 
    ethereum-borrowed         134.67 k
    ethereum                  247.15 k
    borrowed                  134.67 k
    
    total                    247.15 k

**Comment by xfujin** [comment]
As you can see on [our DApps markets page](https://app.lendexe.fi/market), the borrow is returned correctly BUT the supply is missing LEXE price from CoinGecko. I have already started a thread on discord to discuss this issue.

**Comment by llamatester** [comment]
The adapter at projects/lendexe exports TVL: 
        
 
 
    ethereum-borrowed         134.65 k
    ethereum                  247.04 k
    borrowed                  134.65 k
    
    total                    247.04 k

**Comment by g1nt0ki** [comment]
> As you can see on [our DApps markets page](https://app.lendexe.fi/market), the borrow is returned correctly BUT the supply is missing LEXE price from CoinGecko. I have already started a thread on discord to discuss this issue.

Hi, I have blacklisted LEXE as it can be used to manipulate project tvl:  https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Pull request merged**
