### PR TITLE
Removed staking from tvl

### PR DESCRIPTION
**Pull request by Astrit11**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/smartcredit.js exports TVL: 
        
 
 
    ethereum-borrowed         266.42 k
    ethereum                  1.52 M
    borrowed                  266.42 k
    
    total                    1.52 M

**Comment by g1nt0ki** [comment]
you are right, that is not staking, but half your tvl is coming from smartcredit token hence I blacklisted it, sorry. I have disabled staking here:  https://github.com/DefiLlama/DefiLlama-Adapters/pull/3697

**Comment by Astrit11** [comment]
Hi @g1nt0ki ,
Thank you for your response. 

Let me as some questions here:

1. We are lending SMARTCREDIT - lenders are earning cash back rewards for lending (31% at the moment)

2. Borrowers can borrow SMARTCREDIT - they will receive cash back rewards for borrowing (75% at the moment)

3. Borrowers can use SMARTCREDIT as collateral for borrowing

4. If this is not classified as borrowing/lending SMARTCREDIT, then for example -  it looks like you classify lending project token RAMP (https://defillama.com/protocol/ramp) as lending? 80% of their TVL is RAMP.

5. In our case, we have 50% of TVL as SMARTCREDIT.

6. Here is snapshot from our dashboard: https://imgur.com/a/XrLvt3s 

Shouldn’t we handle this consistently?

**Comment by Astrit11** [comment]
@g1nt0ki I understand,than in that case our intention was not to drop  the staking category if our token will not be part of lending category,so could we add that back as it was with borrowed section as well.
Or if I should do it just let me know

**Pull request closed without merging**
