### PR TITLE
fix data with sturdy backend endpoint

### PR DESCRIPTION
**Pull request by mingji**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/sturdy exports TVL: 
        
 
 
    fantom-borrowed           44.88 k
    ethereum-borrowed         7.25 M
    ethereum                  27.68 M
    fantom                    265.70 k
    borrowed                  7.30 M
    
    total                    27.95 M

**Comment by g1nt0ki** [comment]
@mingji I have not merged it yet as I would like to compute tvl on chain, dislike fetching tvl from external service as the  tvl computation is a blackbox, if service becomes unreachable, we have no way to fix it. 

I tried computing tvl myself, but getting lost in the contracts, some of them are not verified, I see that you are depositing curve tokens in convex (?) and farming

**Comment by llamatester** [comment]
The adapter at projects/sturdy exports TVL: 
        
 
 
    fantom-borrowed           44.90 k
    fantom                    158.35 k
    ethereum-borrowed         7.69 M
    ethereum                  28.84 M
    borrowed                  7.74 M
    
    total                    29.00 M

**Comment by mingji** [comment]
@g1nt0ki I removed the endpoint and get the data from the subgraph and smart contract call.
Please check the commit.
Thanks.

**Comment by g1nt0ki** [comment]
@mingji thanks for using graph, will review it soon

**Comment by g1nt0ki** [comment]
@mingji noticed one issue ,you were including assets lent out under tvl, I fixed

Also, noticed that some parts are similar to aave, so I have removed dependency on graph and used our internal helper function here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/5424

**Pull request merged**
