### PR TITLE
Revert "Based Finance folder created, added main reward pool tvl, boardroom tvl."

### PR DESCRIPTION
**Pull request by BasedFinance**
Reverts DefiLlama/DefiLlama-Adapters#3919

Latest pull request by [g1nt0ki] [0d7d264] has wrong logic of tvl construction. 
NFt pool tvl is supposed to be calculated based on standard price of $500 per nft - mint price and deposited value in protocol is always $500 and will not change until end of emissions. 
Twisted Nodes tvl is supposed to be calculated from abi function RewardDebtInDollars - the only accurate method to get correct tvls of all 3 contracts(short, medium, long nodes).

All functionality was implemented in our latest commit which was deleted and refactored with inaccurate calculations.

Please let us know if we can have combined tvls of our 2 protocols since they are building blocks of our ecosystem.

If its impossible to combine tvls, we will edit latest commit and show only tvl of Based-Next-Gen protocol.

thank you.

### CODE REVIEW

**Comment by g1nt0ki** [comment]
hi @BasedFinance

 NFT Pool - the NFTs are your own, is there an option for the users to burn the NFT and get some tokens? if the answer is no, then we cant count it even under staking.
 
 Twisted Nodes - I am counting the tokens deposited by the user, not the reward promised,

**Comment by BasedFinance** [comment]
hi @g1nt0ki .

please let us know if you can include tvl for nft staking only if nfts have a liquidity pair w some kind of token. Nodes tvl is amount of stables that are locked in those contracts.

We are looking at UI on defi llama - and our project doesnt appear on UI w tvl at all. What should we change to make sure its in the list. Looking at Tomb Finance - they have couple tabs for their products - can we have the same tabs for our both protocols?

thank you!

**Comment by BasedFinance** [comment]
@g1nt0ki ,

Ok. Thank you for explaining the nft and node situation. Please let us know what we can change to show our tvl not 0, and possibly have a tab for our products (2 protocols w 2 diff tvls). 

Thank you

**Comment by g1nt0ki** [comment]
@BasedFinance sorry, not much can be done about the tvl part, this the case with most tomb forks: https://defillama.com/forks/Tomb%20Finance as all tvl comes from staking+pool2

We have created a separate tab for V2: https://defillama.com/protocol/based-v2

**Comment by g1nt0ki** [comment]
@Define101 can you help me out with this?

**Comment by Define101** [comment]
So right now the parentProtocol is Based Finance (Image 1)

From what I understand you guys want to rename the Based V2 to Based-Next-Gen + fix the logo category e.t.c
Is that it? 

Adding this https://github.com/DefiLlama/DefiLlama-Adapters/pull/3919#issuecomment-1254327467 information to the Based-Next-Gen is that it?

image

**Comment by BasedFinance** [comment]
@Define101 

Yes. All info we commented on our commit goes to based-next-gen

**Comment by BasedFinance** [comment]
@g1nt0ki 

Hello, 
Could you correct the description for Based V2 please?

Thank you.

**Comment by Define101** [comment]
This one right?

BASED Next Generation protocol is the first pegless seigniorage protocol exploring DeFi on the FTM Network. We are introducing innovative yield strategies whilst providing inclusivity for Based Finance (V1), that successfully finished emissions. Based Next Gen is a multi-token protocol that consists of the following tokens: $OBOL - PEGLESS token with elastic supply. $SMELT - protocol’s underlying Perpetual Print (PP) mechanism emitting OBOL.

**Comment by Define101** [comment]
I have made all the changes, just not sure about the category and the fork part
Since you guys are really similar with protocols like emp (https://defillama.com/protocol/emp-money), tomb fork + nodes

**Comment by BasedFinance** [comment]
@Define101 ,

We thought on that, but Next Gen is pegless and mechanics are different from a tomb fork, obol also has dynamic supply . Thats why we put in description based fork.

Also its not an algo-stable because it is not pegged to any token. Maybe yield category would fit better.

Thank you!

**Comment by Define101** [comment]
Done 
Should reflect on the website within 1 hour
Thanks for letting us know

**Comment by BasedFinance** [comment]
@Define101 ,

Thank you! Could you please change the logo to the one attached, also please let us know why tvl of $210,000 shows as liquid, these deposits are balances of our smelt reward pool.

basedlabs_noborder

Снимок экрана 2022-10-24 в 00 15 29

**Comment by g1nt0ki** [comment]
We dont count pool2/staking/liquid-staking/yield under chain tvl hence it appears greyed out

**Comment by BasedFinance** [comment]
@g1nt0ki Hi, 
Staking on v1 Acropolis ( 0xE5009Dd5912a68B0D7C6F874cD0b4492C9F0e5cD ) and v2 Boardroom ( 0x8ff9eFB99D522fAC6a21363b7Ca54d25477637F6 ) shows 0. According to the code addresses are correct. Can you help please?

**Pull request closed without merging**
