### PR TITLE
Sparkswap Listing

### PR DESCRIPTION
**Pull request by empm0ney**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Sparkswap

##### Twitter Link:
https://twitter.com/sparkswap_

##### List of audit links if any:
https://fleek.ipfs.io/ipfs/bafybeiawdbrvhwwpvmuc6agcxsxpjrigv3bzjtfmwei2zftrjsf3gv4zlm

##### Website Link:
https://sparkswap.xyz

##### Logo (High resolution, will be shown with rounded borders):
https://fleek.ipfs.io/ipfs/bafybeibu3uevnvt4zj4lub2j3naabn3fkbqwiuhyf76ebbl6hg4cko732q

##### Current TVL:
$7,650,000

##### Treasury Addresses (if the protocol has treasury)
NA

##### Chain:
PulseChain

##### Short Description (to be shown on DefiLlama):
Fully Decentralized Layered Yield Farm, AMM, & Bridge on IPFS & Pulsechain 🚀
Earn SPARK through yield farming then stake it to earn PLS from protocol fees and INC rewards!

##### Token address and ticker if any:
0x6386704cD6f7A584EA9D23cccA66aF7EBA5a727e
SPARK

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
PulseX

##### methodology (what is being counted as tvl, how is tvl being calculated):
Farm pools & Sparkler contract

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/empm0ney

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/sparkswap exports TVL: 
        
 
 
    pulse                     7.69 M
    
    total                    7.69 M

**Comment by llamatester** [comment]
The adapter at projects/sparkswap exports TVL: 
        
 
 
    pulse-staking             681.40 k
    pulse                     2.78 M
    pulse-pool2               1.68 M
    staking                   681.40 k
    pool2                     1.68 M
    
    total                    2.78 M

**Comment by g1nt0ki** [comment]
@empm0ney not sure how you are getting 7.6M I am getting only around 5M

**Comment by Define101** [comment]
Btw since its a project from the same team https://defillama.com/protocol/emp-money
We will make a parentProtocol and group both projects under that parentProtocol

**Comment by g1nt0ki** [comment]
@empm0ney sorry, I dont understand, what does this mean? "several of the farm pools are rehypothecated onto PulseX"

**Comment by g1nt0ki** [comment]
ah, got it. I have updated code to include it here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/16f2b6cb9be39a2bd44e8b544326716da8f76fd7

**Pull request merged**
