### PR TITLE
Add Tropykus Protocol

### PR DESCRIPTION
**Pull request by jpreciadom**
##### Twitter Link:
https://twitter.com/tropykus

##### List of audit links if any:
https://firebasestorage.googleapis.com/v0/b/tropycofinance.appspot.com/o/Tropykus%20-%20Smart%20Contract%20Audit%20v210714.pdf?alt=media&token=f4f8e0d5-d577-45a1-85be-4e2d10cc210f
https://firebasestorage.googleapis.com/v0/b/tropycofinance.appspot.com/o/Tropykus%20-%20Smart%20Contract%20Audit%20v211214.pdf?alt=media&token=9a1df569-bce4-4be8-9e3b-bcdd57061b65

##### Website Link:
https://app.tropykus.com/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

signal-2022-02-23-110957_001

signal-2022-02-23-110957_002

##### Current TVL:
84483 USD

##### Chain:
RSK (30)

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

##### Short Description (to be shown on DefiLlama):
Tropykus is a DeFi for Bitcoin lending and borrowing platform focused on Latanamerica.

##### Token address and ticker if any:
N/A

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Money On Chain

##### forkedFrom (Does your project originate from another project):
Compound

##### methodology (what is being counted as tvl, how is tvl being calculated):
The TVL is calculated by adding the value of total deposits in all markets minus the total borrows.

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Is this on testnet? When I try to use the app I get directed to RSK chainId 31, and I can't connect my metamask

**Comment by jpreciadom** [comment]
Hi. No, it is not. The app is only on mainnet. Could you please send mi the app id shown at the bottom-left of the page to verify?

**Comment by jpreciadom** [comment]
I've just checked and it is our last published version running on mainnet. I don't know what is happening.

**Comment by waynebruce0x** [comment]
When I add RSK to metamask myself, the app works. I think your 'add network' prompt is serving the wrong network info (pointing at testnet).

Anyway adapter looks good, merging now. Should be on the UI within 24 hours - just thought I'd let you know about my UX hiccup

**Pull request merged**
