### PR TITLE
Share FRAX and SAFE addies

### PR DESCRIPTION
**Pull request by 0xmichalis**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/asgardfinance exports TVL: 
        
 
 
    ethereum                  2.6301553648508303e-12
    ethereum-staking          0
    staking                   0
    
    total                    2.6301553648508303e-12

**Comment by llamatester** [comment]
The adapter at projects/bprotocol exports TVL: 
        
 
 
    fantom                    68.36 k
    arbitrum                  16.49 k
    polygon                   100.05308915069529
    ethereum                  31.05 M
    
    total                    31.14 M

**Comment by llamatester** [comment]
Error while running adapter at projects/celerbridge: 
        
 
  
    
    
    PromisePoolError: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0xcA11bde05977b3631167028862bE2a173976CA11","data":"0xbce38bd70000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000001c00000000000000000000000000000000000000000000000000000000000000260000000000000000000000000985458e523db3d53125813ed68c274899e9dfab40000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a08231000000000000000000000000841ce48f9446c8e281d3f1444cb859b4a6d0738c00000000000000000000000000000000000000000000000000000000000000000000000000000000985458e523db3d53125813ed68c274899e9dfab40000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a0823100000000000000000000000078a21c1d3ed53a82d4247b9ee5bf001f4620ceec00000000000000000000000000000000000000000000000000000000000000000000000000000000bd8064cdb96c00a73540922504f989c64b7b8b960000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a08231000000000000000000000000841ce48f9446c8e281d3f1444cb859b4a6d0738c00000000000000000000000000000000000000000000000000000000000000000000000000000000bd8064cdb96c00a73540922504f989c64b7b8b960000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a0823100000000000000000000000078a21c1d3ed53a82d4247b9ee5bf001f4620ceec00000000000000000000000000000000000000000000000000000000","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    Truncated error stack:
        at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
The adapter at projects/asgardfinance exports TVL: 
        
 
 
    ethereum                  2.61990383563514e-12
    ethereum-staking          0
    staking                   0
    
    total                    2.61990383563514e-12

**Comment by llamatester** [comment]
The adapter at projects/asymmetry-fi exports TVL: 
        
 
 
    ethereum                  379.91 k
    
    total                    379.91 k

**Comment by llamatester** [comment]
The adapter at projects/bprotocol exports TVL: 
        
 
 
    arbitrum                  16.48 k
    fantom                    68.42 k
    polygon                   99.99645023484136
    ethereum                  31.07 M
    
    total                    31.16 M

**Comment by llamatester** [comment]
Error while running adapter at projects/celerbridge: 
        
 
  
    
    
    PromisePoolError: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0xcA11bde05977b3631167028862bE2a173976CA11","data":"0xbce38bd70000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000001c00000000000000000000000000000000000000000000000000000000000000260000000000000000000000000985458e523db3d53125813ed68c274899e9dfab40000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a08231000000000000000000000000841ce48f9446c8e281d3f1444cb859b4a6d0738c00000000000000000000000000000000000000000000000000000000000000000000000000000000985458e523db3d53125813ed68c274899e9dfab40000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a0823100000000000000000000000078a21c1d3ed53a82d4247b9ee5bf001f4620ceec00000000000000000000000000000000000000000000000000000000000000000000000000000000bd8064cdb96c00a73540922504f989c64b7b8b960000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a08231000000000000000000000000841ce48f9446c8e281d3f1444cb859b4a6d0738c00000000000000000000000000000000000000000000000000000000000000000000000000000000bd8064cdb96c00a73540922504f989c64b7b8b960000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a0823100000000000000000000000078a21c1d3ed53a82d4247b9ee5bf001f4620ceec00000000000000000000000000000000000000000000000000000000","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    Truncated error stack:
        at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by g1nt0ki** [comment]
@0xmichalis thanks

**Pull request merged**
