### PR TITLE
new LP contract address

### PR DESCRIPTION
**Pull request by brddmnk**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/parallax: 
        
 
  
    
    
    PromisePoolError: Request failed with status code 500
    Truncated error stack:
        at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by brddmnk** [comment]
hi
I just changed the contract address
is it good to go?

**Comment by llamatester** [comment]
The adapter at projects/blur-finance exports TVL: 
        
 
 
    bsc                       0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/parallax exports TVL: 
        
 
 
    ethereum                  3.48 k
    arbitrum-staking          232.60 k
    arbitrum                  38.82 k
    era                       7.20 k
    arbitrum-pool2            40.57 k
    staking                   232.60 k
    pool2                     40.57 k
    
    total                    49.51 k

**Comment by llamatester** [comment]
The adapter at projects/scrub exports TVL: 
        
 
 
    kava                      0
    cronos                    0
    kava-staking              348.56 k
    kava-pool2                277.0930061500337
    staking                   348.56 k
    pool2                     277.0930061500337
    
    total                    0

**Pull request merged**
