### PR TITLE
Added aperture tvl

### PR DESCRIPTION
**Pull request by g1nt0ki**
##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

https://aperture.finance/favicon.png

##### Short Description (to be shown on DefiLlama):

    Cross-chain investment ecosystem with a community-driven marketplace for strategies. All your DeFi needs taken care of in one single place.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/aperture/index.js: 
        
 
  
    
    
    Error: connect ETIMEDOUT 104.18.31.143:443
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '104.18.31.143',
      port: 443,
      config: {
        url: 'https://lcd.terra.dev/wasm/contracts/terra1jvehz6d9gk3gl4tldrzd8qzj8zfkurfvtcg99x/store?query_msg={"batch_get_position_info":{"positions":[{"chain_id":3,"position_id":"1387"}]}}',
        method: 'get',
        headers: {
          Accept: 'application/json, text/plain, */*',
          'User-Agent': 'axios/0.21.4'
        },
        transformRequest: [ [Function: transformRequest] ],
        transformResponse: [ [Function: transformResponse] ],
        timeout: 0,
        adapter: [Function: httpAdapter],
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        maxBodyLength: -1,
        validateStatus: [Function: validateStatus],
        transitional: {
          silentJSONParsing: true,
          forcedJSONParsing: true,
          clarifyTimeoutError: false
        },
        data: undefined
      },
      request: <ref *1> Writable {
        _writableState: WritableState {
          objectMode: false,
          highWaterMark: 16384,
          finalCalled: false,
          needDrain: false,
          ending: false,
          ended: false,
          finished: false,
          destroyed: false,
          decodeStrings: true,
          defaultEncoding: 'utf8',
          length: 0,
          writing: false,
          corked: 0,
          sync: true,
          bufferProcessing: false,
          onwrite: [Function: bound onwrite],
          writecb: null,
          writelen: 0,
          afterWriteTickInfo: null,
          buffered: [],
          bufferedIndex: 0,
          allBuffers: true,
          allNoop: true,
          pendingcb: 0,
          constructed: true,
          prefinished: false,
          errorEmitted: false,
          emitClose: true,
          autoDestroy: true,
          errored: null,
          closed: false,
          closeEmitted: false,
          [Symbol(kOnFinished)]: []
        },
        _events: [Object: null prototype] {
          response: [Function: handleResponse],
          error: [Function: handleRequestError]
        },
        _eventsCount: 2,
        _maxListeners: undefined,
        _options: {
          maxRedirects: 21,
          maxBodyLength: 10485760,
          protocol: 'https:',
          path: '/wasm/contracts/terra1jvehz6d9gk3gl4tldrzd8qzj8zfkurfvtcg99x/store?query_msg=%7B%22batch_get_position_info%22:%7B%22positions%22:[%7B%22chain_id%22:3,%22position_id%22:%221387%22%7D]%7D%7D',
          method: 'GET',
          headers: [Object],
          agent: undefined,
          agents: [Object],
          auth: undefined,
          hostname: 'lcd.terra.dev',
          port: null,
          nativeProtocols: [Object],
          pathname: '/wasm/contracts/terra1jvehz6d9gk3gl4tldrzd8qzj8zfkurfvtcg99x/store',
          search: '?query_msg=%7B%22batch_get_position_info%22:%7B%22positions%22:[%7B%22chain_id%22:3,%22position_id%22:%221387%22%7D]%7D%7D'
        },
        _ended: true,
        _ending: true,
        _redirectCount: 0,
        _redirects: [],
        _requestBodyLength: 0,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function (anonymous)],
        _currentRequest: ClientRequest {
          _events: [Object: null prototype],
          _eventsCount: 7,
          _maxListeners: undefined,
          outputData: [],
          outputSize: 0,
          writable: true,
          destroyed: false,
          _last: true,
          chunkedEncoding: false,
          shouldKeepAlive: false,
          maxRequestsOnConnectionReached: false,
          _defaultKeepAlive: true,
          useChunkedEncodingByDefault: false,
          sendDate: false,
          _removedConnection: false,
          _removedContLen: false,
          _removedTE: false,
          _contentLength: 0,
          _hasBody: true,
          _trailer: '',
          finished: true,
          _headerSent: true,
          _closed: false,
          socket: [TLSSocket],
          _header: 'GET /wasm/contracts/terra1jvehz6d9gk3gl4tldrzd8qzj8zfkurfvtcg99x/store?query_msg=%7B%22batch_get_position_info%22:%7B%22positions%22:[%7B%22chain_id%22:3,%22position_id%22:%221387%22%7D]%7D%7D HTTP/1.1\r\n' +
            'Accept: application/json, text/plain, */*\r\n' +
            'User-Agent: axios/0.21.4\r\n' +
            'Host: lcd.terra.dev\r\n' +
            'Connection: close\r\n' +
            '\r\n',
          _keepAliveTimeout: 0,
          _onPendingData: [Function: nop],
          agent: [Agent],
          socketPath: undefined,
          method: 'GET',
          maxHeaderSize: undefined,
          insecureHTTPParser: undefined,
          path: '/wasm/contracts/terra1jvehz6d9gk3gl4tldrzd8qzj8zfkurfvtcg99x/store?query_msg=%7B%22batch_get_position_info%22:%7B%22positions%22:[%7B%22chain_id%22:3,%22position_id%22:%221387%22%7D]%7D%7D',
          _ended: false,
          res: null,
          aborted: false,
          timeoutCb: null,
          upgradeOrConnect: false,
          parser: null,
          maxHeadersCount: null,
          reusedSocket: false,
          host: 'lcd.terra.dev',
          protocol: 'https:',
          _redirectable: [Circular *1],
          [Symbol(kCapture)]: false,
          [Symbol(kNeedDrain)]: false,
          [Symbol(corked)]: 0,
          [Symbol(kOutHeaders)]: [Object: null prototype]
        },
        _currentUrl: 'https://lcd.terra.dev/wasm/contracts/terra1jvehz6d9gk3gl4tldrzd8qzj8zfkurfvtcg99x/store?query_msg=%7B%22batch_get_position_info%22:%7B%22positions%22:[%7B%22chain_id%22:3,%22position_id%22:%221387%22%7D]%7D%7D',
        [Symbol(kCapture)]: false
      },
      response: undefined,
      isAxiosError: true,
      toJSON: [Function: toJSON]
    }

**Comment by llamatester** [comment]
Error while running adapter at projects/aperture/index.js: 
        
 
  
    
    
    Error: Request failed with status code 520
        at createError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/axios/lib/core/createError.js:16:15)
        at settle (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/axios/lib/core/settle.js:17:12)
        at IncomingMessage.handleStreamEnd (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/axios/lib/adapters/http.js:269:11)
        at IncomingMessage.emit (node:events:532:35)
        at endReadableNT (node:internal/streams/readable:1346:12)
        at processTicksAndRejections (node:internal/process/task_queues:83:21) {
      config: {
        url: 'https://lcd.terra.dev/wasm/contracts/terra1jvehz6d9gk3gl4tldrzd8qzj8zfkurfvtcg99x/store?query_msg={"batch_get_position_info":{"positions":[{"chain_id":3,"position_id":"1126"}]}}',
        method: 'get',
        headers: {
          Accept: 'application/json, text/plain, */*',
          'User-Agent': 'axios/0.21.4'
        },
        transformRequest: [ [Function: transformRequest] ],
        transformResponse: [ [Function: transformResponse] ],
        timeout: 0,
        adapter: [Function: httpAdapter],
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        maxBodyLength: -1,
        validateStatus: [Function: validateStatus],
        transitional: {
          silentJSONParsing: true,
          forcedJSONParsing: true,
          clarifyTimeoutError: false
        },
        data: undefined
      },
      request: <ref *1> ClientRequest {
        _events: [Object: null prototype] {
          abort: [Function (anonymous)],
          aborted: [Function (anonymous)],
          connect: [Function (anonymous)],
          error: [Function (anonymous)],
          socket: [Function (anonymous)],
          timeout: [Function (anonymous)],
          prefinish: [Function: requestOnPrefinish]
        },
        _eventsCount: 7,
        _maxListeners: undefined,
        outputData: [],
        outputSize: 0,
        writable: true,
        destroyed: false,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        maxRequestsOnConnectionReached: false,
        _defaultKeepAlive: true,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        _closed: false,
        socket: TLSSocket {
          _tlsOptions: [Object],
          _secureEstablished: true,
          _securePending: false,
          _newSessionPending: false,
          _controlReleased: true,
          secureConnecting: false,
          _SNICallback: null,
          servername: 'lcd.terra.dev',
          alpnProtocol: false,
          authorized: true,
          authorizationError: null,
          encrypted: true,
          _events: [Object: null prototype],
          _eventsCount: 10,
          connecting: false,
          _hadError: false,
          _parent: null,
          _host: 'lcd.terra.dev',
          _readableState: [ReadableState],
          _maxListeners: undefined,
          _writableState: [WritableState],
          allowHalfOpen: false,
          _sockname: null,
          _pendingData: null,
          _pendingEncoding: '',
          server: undefined,
          _server: null,
          ssl: [TLSWrap],
          _requestCert: true,
          _rejectUnauthorized: true,
          parser: null,
          _httpMessage: [Circular *1],
          [Symbol(res)]: [TLSWrap],
          [Symbol(verified)]: true,
          [Symbol(pendingSession)]: null,
          [Symbol(async_id_symbol)]: 23176,
          [Symbol(kHandle)]: [TLSWrap],
          [Symbol(kSetNoDelay)]: false,
          [Symbol(lastWriteQueueSize)]: 0,
          [Symbol(timeout)]: null,
          [Symbol(kBuffer)]: null,
          [Symbol(kBufferCb)]: null,
          [Symbol(kBufferGen)]: null,
          [Symbol(kCapture)]: false,
          [Symbol(kBytesRead)]: 0,
          [Symbol(kBytesWritten)]: 0,
          [Symbol(connect-options)]: [Object],
          [Symbol(RequestTimeout)]: undefined
        },
        _header: 'GET /wasm/contracts/terra1jvehz6d9gk3gl4tldrzd8qzj8zfkurfvtcg99x/store?query_msg=%7B%22batch_get_position_info%22:%7B%22positions%22:[%7B%22chain_id%22:3,%22position_id%22:%221126%22%7D]%7D%7D HTTP/1.1\r\n' +
          'Accept: application/json, text/plain, */*\r\n' +
          'User-Agent: axios/0.21.4\r\n' +
          'Host: lcd.terra.dev\r\n' +
          'Connection: close\r\n' +
          '\r\n',
        _keepAliveTimeout: 0,
        _onPendingData: [Function: nop],
        agent: Agent {
          _events: [Object: null prototype],
          _eventsCount: 2,
          _maxListeners: undefined,
          defaultPort: 443,
          protocol: 'https:',
          options: [Object: null prototype],
          requests: [Object: null prototype] {},
          sockets: [Object: null prototype],
          freeSockets: [Object: null prototype] {},
          keepAliveMsecs: 1000,
          keepAlive: false,
          maxSockets: Infinity,
          maxFreeSockets: 256,
          scheduling: 'lifo',
          maxTotalSockets: Infinity,
          totalSocketCount: 100,
          maxCachedSessions: 100,
          _sessionCache: [Object],
          [Symbol(kCapture)]: false
        },
        socketPath: undefined,
        method: 'GET',
        maxHeaderSize: undefined,
        insecureHTTPParser: undefined,
        path: '/wasm/contracts/terra1jvehz6d9gk3gl4tldrzd8qzj8zfkurfvtcg99x/store?query_msg=%7B%22batch_get_position_info%22:%7B%22positions%22:[%7B%22chain_id%22:3,%22position_id%22:%221126%22%7D]%7D%7D',
        _ended: true,
        res: IncomingMessage {
          _readableState: [ReadableState],
          _events: [Object: null prototype],
          _eventsCount: 3,
          _maxListeners: undefined,
          socket: [TLSSocket],
          httpVersionMajor: 1,
          httpVersionMinor: 1,
          httpVersion: '1.1',
          complete: true,
          rawHeaders: [Array],
          rawTrailers: [],
          aborted: false,
          upgrade: false,
          url: '',
          method: null,
          statusCode: 520,
          statusMessage: 'Origin Error',
          client: [TLSSocket],
          _consuming: true,
          _dumped: false,
          req: [Circular *1],
          responseUrl: 'https://lcd.terra.dev/wasm/contracts/terra1jvehz6d9gk3gl4tldrzd8qzj8zfkurfvtcg99x/store?query_msg=%7B%22batch_get_position_info%22:%7B%22positions%22:[%7B%22chain_id%22:3,%22position_id%22:%221126%22%7D]%7D%7D',
          redirects: [],
          [Symbol(kCapture)]: false,
          [Symbol(kHeaders)]: [Object],
          [Symbol(kHeadersCount)]: 22,
          [Symbol(kTrailers)]: null,
          [Symbol(kTrailersCount)]: 0,
          [Symbol(RequestTimeout)]: undefined
        },
        aborted: false,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        reusedSocket: false,
        host: 'lcd.terra.dev',
        protocol: 'https:',
        _redirectable: Writable {
          _writableState: [WritableState],
          _events: [Object: null prototype],
          _eventsCount: 2,
          _maxListeners: undefined,
          _options: [Object],
          _ended: true,
          _ending: true,
          _redirectCount: 0,
          _redirects: [],
          _requestBodyLength: 0,
          _requestBodyBuffers: [],
          _onNativeResponse: [Function (anonymous)],
          _currentRequest: [Circular *1],
          _currentUrl: 'https://lcd.terra.dev/wasm/contracts/terra1jvehz6d9gk3gl4tldrzd8qzj8zfkurfvtcg99x/store?query_msg=%7B%22batch_get_position_info%22:%7B%22positions%22:[%7B%22chain_id%22:3,%22position_id%22:%221126%22%7D]%7D%7D',
          [Symbol(kCapture)]: false
        },
        [Symbol(kCapture)]: false,
        [Symbol(kNeedDrain)]: false,
        [Symbol(corked)]: 0,
        [Symbol(kOutHeaders)]: [Object: null prototype] {
          accept: [Array],
          'user-agent': [Array],
          host: [Array]
        }
      },
      response: {
        status: 520,
        statusText: 'Origin Error',
        headers: {
          date: 'Fri, 25 Mar 2022 16:44:57 GMT',
          'content-type': 'text/html',
          'transfer-encoding': 'chunked',
          connection: 'close',
          'cache-control': 'no-store, no-cache',
          'cf-cache-status': 'MISS',
          'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
          'set-cookie': [Array],
          server: 'cloudflare',
          'cf-ray': '6f191d3b395c5986-IAD',
          'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'
        },
        config: {
          url: 'https://lcd.terra.dev/wasm/contracts/terra1jvehz6d9gk3gl4tldrzd8qzj8zfkurfvtcg99x/store?query_msg={"batch_get_position_info":{"positions":[{"chain_id":3,"position_id":"1126"}]}}',
          method: 'get',
          headers: [Object],
          transformRequest: [Array],
          transformResponse: [Array],
          timeout: 0,
          adapter: [Function: httpAdapter],
          xsrfCookieName: 'XSRF-TOKEN',
          xsrfHeaderName: 'X-XSRF-TOKEN',
          maxContentLength: -1,
          maxBodyLength: -1,
          validateStatus: [Function: validateStatus],
          transitional: [Object],
          data: undefined
        },
        request: <ref *1> ClientRequest {
          _events: [Object: null prototype],
          _eventsCount: 7,
          _maxListeners: undefined,
          outputData: [],
          outputSize: 0,
          writable: true,
          destroyed: false,
          _last: true,
          chunkedEncoding: false,
          shouldKeepAlive: false,
          maxRequestsOnConnectionReached: false,
          _defaultKeepAlive: true,
          useChunkedEncodingByDefault: false,
          sendDate: false,
          _removedConnection: false,
          _removedContLen: false,
          _removedTE: false,
          _contentLength: 0,
          _hasBody: true,
          _trailer: '',
          finished: true,
          _headerSent: true,
          _closed: false,
          socket: [TLSSocket],
          _header: 'GET /wasm/contracts/terra1jvehz6d9gk3gl4tldrzd8qzj8zfkurfvtcg99x/store?query_msg=%7B%22batch_get_position_info%22:%7B%22positions%22:[%7B%22chain_id%22:3,%22position_id%22:%221126%22%7D]%7D%7D HTTP/1.1\r\n' +
            'Accept: application/json, text/plain, */*\r\n' +
            'User-Agent: axios/0.21.4\r\n' +
            'Host: lcd.terra.dev\r\n' +
            'Connection: close\r\n' +
            '\r\n',
          _keepAliveTimeout: 0,
          _onPendingData: [Function: nop],
          agent: [Agent],
          socketPath: undefined,
          method: 'GET',
          maxHeaderSize: undefined,
          insecureHTTPParser: undefined,
          path: '/wasm/contracts/terra1jvehz6d9gk3gl4tldrzd8qzj8zfkurfvtcg99x/store?query_msg=%7B%22batch_get_position_info%22:%7B%22positions%22:[%7B%22chain_id%22:3,%22position_id%22:%221126%22%7D]%7D%7D',
          _ended: true,
          res: [IncomingMessage],
          aborted: false,
          timeoutCb: null,
          upgradeOrConnect: false,
          parser: null,
          maxHeadersCount: null,
          reusedSocket: false,
          host: 'lcd.terra.dev',
          protocol: 'https:',
          _redirectable: [Writable],
          [Symbol(kCapture)]: false,
          [Symbol(kNeedDrain)]: false,
          [Symbol(corked)]: 0,
          [Symbol(kOutHeaders)]: [Object: null prototype]
        },
        data: '<html>\r\n' +
          '<head><title>520 Origin Error</title></head>\r\n' +
          '<body bgcolor="white">\r\n' +
          '<center><h1>520 Origin Error</h1></center>\r\n' +
          '<hr><center>cloudflare-nginx</center>\r\n' +
          '</body>\r\n' +
          '</html>\r\n'
      },
      isAxiosError: true,
      toJSON: [Function: toJSON]
    }

**Comment by llamatester** [comment]
The adapter at projects/aperture/index.js exports TVL: 
        
 
 
    terra                     7.52 M
    
    total                    7.52 M

**Comment by g1nt0ki** [comment]
I am slightly worried about this PR, we are querying for every position that was created, currently there are 1690, it will only grow, I have asked the team if there is a way where we can get only active positions even that might be too many

The first two runs on the server failed because I was making 100 parallel calls, reduced it to 50 to make it work

**Pull request merged**
