### PR TITLE
add KelpDao

### PR DESCRIPTION
**Pull request by gus-stdr**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Kelp Dao

##### Twitter Link:
https://twitter.com/KelpDAO

##### List of audit links if any:
https://kelp.gitbook.io/kelp/audits

##### Website Link:
https://stage.kelpdao.xyz/

##### Logo (High resolution, will be shown with rounded borders):
kelp

##### Current TVL:
101.23 M

##### Chain:
Ethereum

##### Short Description (to be shown on DefiLlama):
rsETH is a Liquid Restaked Token (LRT) issued by Kelp DAO designed to offer liquidity to illiquid assets deposited into restaking platforms, such as EigenLayer. It aims to address the risks and challenges posed by the current offering of restaking

##### Token address and ticker if any:
0xA1290d69c65A6Fe4DF752f95823fae25cB99e5A7

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Restaking Token

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink and LST token smart contract

##### methodology (what is being counted as tvl, how is tvl being calculated):
Total deposited LSTs in KelpDao and Eigenlayer

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/Kelp-DAO/KelpDAO-contracts

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/flamincome.js exports TVL: 
        
 
 
    ethereum                  80.26 M
    
    total                    80.26 M

**Comment by llamatester** [comment]
The adapter at projects/kelp-dao exports TVL: 
        
 
 
    ethereum                  101.03 M
    
    total                    101.03 M

**Comment by llamatester** [comment]
The adapter at projects/flamincome.js exports TVL: 
        
 
 
    ethereum                  80.30 M
    
    total                    80.30 M

**Comment by llamatester** [comment]
The adapter at projects/kelp-dao exports TVL: 
        
 
 
    ethereum                  101.03 M
    
    total                    101.03 M

**Comment by llamatester** [comment]
The adapter at projects/flamincome.js exports TVL: 
        
 
 
    ethereum                  79.81 M
    
    total                    79.81 M

**Comment by g1nt0ki** [comment]
@gus-stdr thanks for the PR

**Comment by Tobby2sure** [comment]
Hello
It should be KelpDAO, not KelpDao

**Comment by Tobby2sure** [comment]
Can you help break down the tvl into diferent chains?

Arbitrum    0x4186BFC76E2E237523CBC30FD220FE055156b41F

Optimism    0x4186BFC76E2E237523CBC30FD220FE055156b41F

Manta    0x4186BFC76E2E237523CBC30FD220FE055156b41F

Mode    0x4186BFC76E2E237523CBC30FD220FE055156b41F

Blast    0x4186BFC76E2E237523CBC30FD220FE055156b41F

Scroll    0x65421ba909200b81640d98B979d07487C9781B66

Base    0x1Bc71130A0e39942a7658878169764Bbd8A45993

Zksync
0xd4169E045bcF9a86cC00101225d9ED61D2F51af2

Linea
0xD2671165570f41BBB3B0097893300b6EB6101E6C

xlayer
0x5a71f5888ee05b36ded9149e6d32ee93812ee5e9



Wrseth + (rseth not in tokenwrapper) is the TVL of each L2 (Where the addition comes in)

(Rseth total supply - rseth on eth oft contract) is the total TVL on ethereum (where the subtraction is )

**Pull request merged**
