### PR TITLE
Updated Genius Yield Adapter

### PR DESCRIPTION
**Pull request by 4TT1L4**
- Added NMKR staking to the TVL of Genius Yield, since now not only GENS, but also NMKR tokens are locked in the staking contract. (See the [official announcement](https://geniusyield.medium.com/introducing-nmkr-token-nfts-on-the-genius-yield-staking-dapp-db1f3db71ca7) as well)

image

Source: [Staking Contract on Cexplorer](https://cexplorer.io/address/addr1w8r99sv75y9tqfdzkzyqdqhedgnef47w4x7y0qnyts8pznq87e4wh/asset#data)

**The relevant assets:**
 - [GENS Token](https://cardanoscan.io/token/dda5fdb1002f7389b33e036b6afee82a8189becb6cba852e8b79b4fb0014df1047454e53)
 - [NMKR Token](https://cardanoscan.io/token/5dac8536653edc12f6f5e1045d8164b9f59998d3bdc300fc928434894e4d4b52)
 - [Assets locked in the staking contract](https://cexplorer.io/address/addr1w8r99sv75y9tqfdzkzyqdqhedgnef47w4x7y0qnyts8pznq87e4wh/asset#data)

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/genius-yield exports TVL: 
        
 
 
    cardano                   0
    cardano-staking           1.93 M
    staking                   1.93 M
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/genius-yield exports TVL: 
        
 
 
    cardano                   0
    cardano-staking           1.93 M
    staking                   1.93 M
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/grizzlyfi exports TVL: 
        
 
 
    bsc-staking               9.30 M
    bsc                       16.17 M
    staking                   9.30 M
    
    total                    16.17 M

**Comment by llamatester** [comment]
The adapter at projects/aada exports TVL: 
        
 
 
    cardano-staking           346.39 k
    cardano                   1.79 M
    staking                   346.39 k
    
    total                    1.79 M

**Comment by llamatester** [comment]
The adapter at projects/anetabtc exports TVL: 
        
 
 
    cardano                   0
    cardano-staking           1.58 M
    ergo-staking              2.17 M
    staking                   3.75 M
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/djed exports TVL: 
        
 
 
    cardano                   11.32 M
    
    total                    11.32 M

**Comment by llamatester** [comment]
The adapter at projects/genius-yield exports TVL: 
        
 
 
    cardano                   0
    cardano-staking           1.94 M
    staking                   1.94 M
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/liqwid exports TVL: 
        
 
 
    cardano                   7.41 M
    
    total                    7.41 M

**Comment by llamatester** [comment]
The adapter at projects/meld exports TVL: 
        
 
 
    cardano                   0
    cardano-staking           6.22 M
    staking                   6.22 M
    
    total                    0

**Comment by 4TT1L4** [comment]
The changes are working as expected; NMKR has appeared in the token breakdown:

image

And it is also shown on the TVL charts:

image

image

Source: https://defillama.com/protocol/genius-yield (21.03.2023)

**Pull request merged**
