### PR TITLE
update new Minswap contract addresses

### PR DESCRIPTION
**Pull request by longngn**
Signed-off-by: Nguyen Le Vu Long <vulongvn98@gmail.com>

### CODE REVIEW

**Comment by 0xngmi** [comment]
can you please run the code? I'm getting 404s and "'The requested component has not been found.'"

**Comment by 0xngmi** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters/runs/5686069197?check_suite_focus=true

**Comment by longngn** [comment]
@0xngmi I can query it normally on my local env
Here is the script I use:
```js
const axios = require("axios");

async function tvl() {
  const liquidityPoolLocked = (
    await axios.get(
      "https://cardano-mainnet.blockfrost.io/api/v0/addresses/addr1z8snz7c4974vzdpxu65ruphl3zjdvtxw8strf2c2tmqnxz2j2c79gy9l76sdg0xwhd7r0c0kna0tycz4y5s6mlenh8pq0xmsha",
      {
        headers: {
          project_id: "mainnetTV9qV3mfZXbE6e44TVGMe1UoRlLrpSQt",
        },
      }
    )
  ).data.amount.find((token) => token.unit === "lovelace").quantity;
  const batchOrderLocked = (
    await axios.get(
      "https://cardano-mainnet.blockfrost.io/api/v0/addresses/addr1wxn9efv2f6w82hagxqtn62ju4m293tqvw0uhmdl64ch8uwc0h43gt",
      {
        headers: {
          project_id: "mainnetTV9qV3mfZXbE6e44TVGMe1UoRlLrpSQt",
        },
      }
    )
  ).data.amount.find((token) => token.unit === "lovelace").quantity;
  return {
    cardano: (liquidityPoolLocked * 2) / 1e6 + batchOrderLocked / 1e6,
  };
}

tvl().then(console.log);
```

It's also fine with curl:
```bash
curl -H "project_id: mainnetTV9qV3mfZXbE6e44TVGMe1UoRlLrpSQt" https://cardano-mainnet.blockfrost.io/api/v0/addresses/addr1wxn9efv2f6w82hagxqtn62ju4m293tqvw0uhmdl64ch8uwc0h43gt
```

**Comment by llamatester** [comment]
The adapter at projects/minswap/index.js exports TVL: 
        
 
 
    cardano                   210.17 M
    
    total                    210.17 M

**Pull request merged**
