### PR TITLE
Add Antex

### PR DESCRIPTION
**Pull request by FrederickNgoiya**
##### Twitter Link:
https://twitter.com/Antex_Official

##### List of audit links if any:
https://www.certik.com/projects/antex

##### Website Link:
https://antex.org/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

https://assets.coingecko.com/coins/images/20654/large/xa4LH4tP_400x400.jpg

##### Current TVL:
11.42 k 

##### Chain:
BSC

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
antex

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

11708

##### Short Description (to be shown on DefiLlama):

Antex provides the foundational building layers for a new digital economy with following products: stable-coin, crypto/fiat, DEX, launchpad, lock liquidity and lock token and connecting crypto to the real world.

##### Token address and ticker if any:
ANTEX 

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL of the pancake LP

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/antex/index.js exports TVL: 
        
 
 
    bsc                       11.42 k
    
    total                    11.42 k

**Comment by waynebruce0x** [comment]
Do Antex have any of their own smart contracts? This is just counting the TVL of the pancake LP

**Comment by Cocoahomology** [comment]
I found their (only) smart contract: 0xCe43E857c92195BeB417a167B777a11720e6E355

For the individual tokens in the contract I would not count them as circulating tokens, as it seems most have been immediately locked there by teams themselves.

But it also contains Pancake LP's, which I think should be counted. The problem is getting which LP's it holds on-chain, since I think you can lock any LP you want.

They also have this API that returns "total_liquid_lock" that seems to accurately calculate the total value of the Pancake LP's: https://antex.finance/api/token/statistic?platform=bsc&network=main

**Comment by waynebruce0x** [comment]
good find! I think we could probably use the API - I dont mind writing it up today

**Comment by waynebruce0x** [comment]
discord admin says its not an Antex contract

**Comment by Cocoahomology** [comment]
From looking at the discord chat history, it seems like they are not a reliable source of info.

That contract is linked as "Explore Contract" on the 'lock-action' page of the frontend here: https://antex.finance/lock-action

Its token balances also correspond exactly to what is shown on the 'lock' page of the frontend here: https://antex.finance/lock

**Comment by waynebruce0x** [comment]
Nightmare, I deleted the adapter I wrote, I'll start again

**Comment by waynebruce0x** [comment]
Closing because I'm PRing an API adapter as suggested by cocoahomology

**Pull request closed without merging**
