### PR TITLE
feat: klaybank defillama

### PR DESCRIPTION
**Pull request by 0xzero-R**
##### Twitter Link:

https://twitter.com/klaybank

##### List of audit links if any:
- https://github.com/klaybank/klaybank-bondsale/blob/main/audits/%20Hexlant-Bondsale-2022-01-13.pdf.pdf
- https://github.com/klaybank/klaybank-stake/blob/main/audits/Smart_Contract_Audit_Expert-Stake-2022-01-20.pdf
- https://github.com/klaybank/klaybank-stake/blob/main/audits/Smart_Contract_Audit_Hexlant-Stake-2022-02-23.pdf

##### Website Link:

https://app.klaybank.org/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
logo

##### Current TVL:

about $130M

##### Chain:
klaytn

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
None

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
None

##### Short Description (to be shown on DefiLlama):

Klaybank is the first Klaytn based lending protocol that supports Flashloan.

##### Token address and ticker if any:

[0x946bc715501413b9454bb6a31412a21998763f2d](https://scope.klaytn.com/account/0x946bc715501413b9454bb6a31412a21998763f2d) KBT

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
**Lending**

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
**TWAP**

##### forkedFrom (Does your project originate from another project):
[Aave Protocol](https://aave.com/)

##### methodology (what is being counted as tvl, how is tvl being calculated):

Tvl represents the deposited asset.
Staking represents the amount of governance tokens deposited.
bonding represents the amount of lp deposited through bonding sales.

### CODE REVIEW

**Comment by waynebruce0x** [comment]
It seems like maybe your counting borrowed funds as part of TVL? Maybe I'm wrong - if this is the case could you subtract borrows from TVL and use a separate 'borrows' export key for the borrowed funds? Thanks

**Comment by 0xzero-R** [comment]
https://app.klaybank.org/markets 

in this page, market size means depositted amount and total borrowed means borrowed amount.

so for example,

https://app.klaybank.org/markets/0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-0xe4f05a66ec68b54a58b17c22107b02e0232cc8170x4d1227d71e64d79c069221c1f7ff1a492f0fb133

this page shows Reserve size.

Reserve size equals to depositted value.

if u have more question, plz mention me ~!

**Comment by waynebruce0x** [comment]
Reserve Size = Deposited value = Liquidity + Borrows? Can we just count liquidity? about 16M on the market you linked to

**Comment by 0xzero-R** [comment]
No, Reserve size = Deposited value = Only liquidity. not include Borrow amount.

https://app.klaybank.org/markets shows total reserves(that mean liquidity)

total borrowed amount is not shown in our page and do not compute in tvl

**Comment by waynebruce0x** [comment]
okay got it thanks for explaining

**Pull request merged**
