### PR TITLE
Add filet

### PR DESCRIPTION
**Pull request by oxoxll**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI

---

##### Twitter Link:
https://twitter.com/Filet_finance

##### List of audit links if any:
https://www.certik.com/projects/filetstaking 

##### Website Link:
https://www.filet.finance

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
filet

##### Current TVL:
726.57 k

##### Chain:
Filecoin

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
filecoin

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
2280

##### Short Description (to be shown on DefiLlama):
Filet is a decentralized Filecoin mining platform deployed on Filecoin, BSC(BNB Chain), HECO network. We provide staking service with the APY about 30%. FIL holders can stake FIL to mine FIL without any risk. Filet is open source and audited by Certik.

##### Token address and ticker if any:
no

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Staking

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL = The amount of Staked FIL * FIL price

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/filet exports TVL: 
        
 
 
    
    total                    760.31 k

**Comment by xtop-protocol** [comment]
Hi, let me introduce the condition of our platform. Filet is deployed on several chains, some of them are EVM-basis, some of them are not. The total staked FIL is a combination of FIL on BSC, HECO, Filecoin and Mixin network. We can provide contract addresses of BSC and HECO network, but the data of staked FIL on Filecoin/Mixin cannot be counted in. 

Do you accept the way that we provide the API and you can get the exact number?

**Comment by xtop-protocol** [comment]
> @oxoxll can you change the code to on chain adapters, or you can give me the contract addresses and I can make that change :)
Hi, let me introduce the condition of our platform. Filet is deployed on several chains, some of them are EVM-basis, some of them are not. The total staked FIL is a combination of FIL on BSC, HECO, Filecoin and Mixin network. We can provide contract addresses of BSC and HECO network, but the data of staked FIL on Filecoin/Mixin cannot be counted in.

Do you accept the way that we provide the API and you can get the exact number?

**Comment by oxoxll** [comment]
> @oxoxll can you change the code to on chain adapters, or you can give me the contract addresses and I can make that change :)


@g1nt0ki  Hi, let me introduce the condition of our platform. Filet is deployed on several chains, some of them are EVM-basis, some of them are not. The total staked FIL is a combination of FIL on BSC, HECO, Filecoin and Mixin network. We can provide contract addresses of BSC and HECO network, but the data of staked FIL on Filecoin/Mixin cannot be counted in.

Do you accept the way that we provide the API and you can get the exact number?

**Pull request merged**
