### PR TITLE
update crunchy tvl with farmV2, wtz contracts

### PR DESCRIPTION
**Pull request by huydo2105**
Update TVL for Crunchy project from Tezos:
+ Farms V2
+ WTZ Contracts

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/crunchynetwork exports TVL: 
        
 
 
    tezos                     547.58 k
    
    total                    547.58 k

**Comment by llamatester** [comment]
The adapter at projects/crunchynetwork exports TVL: 
        
 
 
    tezos                     230.85 k
    
    total                    230.85 k

**Comment by g1nt0ki** [comment]
@huydo2105 thanks for the PR, there was a minor bug in your code, fixed it and think it is better to have a new sub-listing for wtz as it is close to "liquid staking"

**Comment by llamatester** [comment]
The adapter at projects/crunchynetwork-wtz exports TVL: 
        
 
 
    tezos                     171.54 k
    
    total                    171.54 k

**Pull request merged**
