### PR TITLE
feat: create the DefiLlama Adapter for the Capy Finance project

### PR DESCRIPTION
**Pull request by lainhathoang**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/capy-finance exports TVL: 
        
 
 
    bsquared                  5
    
    total                    5.1236182

**Comment by llamatester** [comment]
The adapter at projects/bunicorn exports TVL: 
        
 
 
    bsc                       350.57 k
    bsc-staking               179
    staking                   179
    
    total                    350.57 k

**Comment by llamatester** [comment]
The adapter at projects/soulswap exports TVL: 
        
 
 
    fantom                    102.62 k
    avax                      41.80 k
    staking                   31.55 k
    fantom-staking            28.98 k
    avax-staking              2.56 k
    borrowed                  732
    fantom-borrowed           392
    avax-borrowed             340
    
    total                    144.42 k

**Comment by llamatester** [comment]
The adapter at projects/capy-finance exports TVL: 
        
 
 
    bsquared                  5
    
    total                    5.1280962

**Comment by llamatester** [comment]
The adapter at projects/bunicorn exports TVL: 
        
 
 
    bsc                       350.91 k
    bsc-staking               179
    staking                   179
    
    total                    350.91 k

**Comment by llamatester** [comment]
The adapter at projects/soulswap exports TVL: 
        
 
 
    fantom                    102.77 k
    avax                      41.69 k
    staking                   31.57 k
    fantom-staking            29.00 k
    avax-staking              2.57 k
    borrowed                  732
    fantom-borrowed           392
    avax-borrowed             340
    
    total                    144.46 k

**Comment by llamatester** [comment]
The adapter at projects/capy-finance exports TVL: 
        
 
 
    bsquared                  5
    
    total                    5.1249579999999995

**Comment by llamatester** [comment]
The adapter at projects/bunicorn exports TVL: 
        
 
 
    bsc                       347.03 k
    bsc-staking               179
    staking                   179
    
    total                    347.03 k

**Comment by llamatester** [comment]
The adapter at projects/capy-finance exports TVL: 
        
 
 
    bsquared                  5
    
    total                    5.1203214

**Comment by g1nt0ki** [comment]
thanks for the PR

**Comment by lainhathoang** [comment]
@g1nt0ki, so where can I upload our project image to fill the `url` field in the form in the `defillama-server` repo?

**Comment by lainhathoang** [comment]
> thanks for the PR

@g1nt0ki, so where can I upload our project image to fill the Logo field in the form above?
I filled out the entire form. How long will it take for the new data to be updated on the UI?

**Comment by lainhathoang** [comment]
@g1nt0ki, I filled out the entire form. How long will it take for the new data to be updated on the UI?

**Pull request merged**
