### PR TITLE
bullionfx added

### PR DESCRIPTION
**Pull request by Devleed**
**NOTE**

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
BullionFX

##### Twitter Link:
https://twitter.com/BullionFx

##### Website Link:
app.bullionfx.com

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://pbs.twimg.com/profile_images/1496017069804224514/3Ta1WtxA_400x400.jpg

##### Current TVL:
2811.705572

##### Chain:
Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
bullionfx

##### Short Description (to be shown on DefiLlama):
Our mission is to bring currency back to the gold standard that can be trusted again. We are democratising access and ownership of gold – therefore allowing everyone to build their wealth safely in a new global economy.

##### Token address and ticker if any:
0xb439b8731ee047799019ef0b745a51d256b116af

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### methodology (what is being counted as tvl, how is tvl being calculated):
Tvl is being calculated by fetching all pairs from factory contract and summing up the pair's dollar value.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bullionFX exports TVL: 
        
 
 
    ethereum                  0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/bullionFX exports TVL: 
        
 
 
    ethereum                  1.81 k
    
    total                    1.81 k

**Comment by llamatester** [comment]
The adapter at projects/bullionFX exports TVL: 
        
 
 
    ethereum                  2.83 k
    
    total                    2.83 k

**Comment by ponury1990** [comment]
Czy znajdzie się ktos kto mnie poprowadzi i zarobię 1 dolara w swej marnej karierze ? Proszę

**Pull request merged**
