### PR TITLE
Add DUAL as Staking

### PR DESCRIPTION
**Pull request by DonDuala**
Adds DUAL as Staking, since DUAL is used in the staking options contracts

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/dual: 
        
 
  
    
    
    Error: 
        Please move the following keys into the chain: staking
    
        We have a new adapter export specification now where tvl and other chain specific information are moved inside chain export.
        For example if your protocol is on ethereum and has tvl and pool2, the export file would look like:
        
            module.exports = {
              methodlogy: '...',
              ethereum: {
                tvl: 
                pool2:
              }
            }

**Comment by llamatester** [comment]
Error while running adapter at projects/dual: 
        
 
  
    
    
    ReferenceError: tokenAccounts is not defined
    Truncated error stack:
    
        at staking (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/dual/index.js:125:33)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:29)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:136:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:131:44

**Comment by llamatester** [comment]
Error while running adapter at projects/dual: 
        
 
  
    
    
    FetchError: request to https://try-rpc.mainnet.solana.blockdaemon.tech/ failed, reason: getaddrinfo ENOTFOUND try-rpc.mainnet.solana.blockdaemon.tech
    Truncated error stack:
        at ClientRequest.<anonymous> (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/node-fetch/lib/index.js:1491:11)
        at ClientRequest.emit (node:events:517:28)
        at TLSSocket.socketErrorListener (node:_http_client:501:9)
        at TLSSocket.emit (node:events:529:35)

**Comment by g1nt0ki** [comment]
> @g1nt0ki is this acceptable? Not sure what this error is

the change looks good, thanks

**Pull request merged**
