### PR TITLE
Update: Crypto Lottery

### PR DESCRIPTION
**Pull request by GemsGame**
Add BSC network

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/crypto-lottery exports TVL: 
        
 
 
    bsc                       0
    polygon                   0.832103
    csc                       50.524007995999995
    
    total                    51.356110996

**Comment by llamatester** [comment]
The adapter at projects/crypto-lottery exports TVL: 
        
 
 
    csc                       50.561585953
    polygon                   0.835279
    bsc                       0
    
    total                    51.396864953

**Comment by llamatester** [comment]
The adapter at projects/crypto-lottery exports TVL: 
        
 
 
    polygon                   0.819967
    bsc                       1.61094
    csc                       50.440440115
    
    total                    52.871347115

**Comment by llamatester** [comment]
The adapter at projects/crypto-lottery exports TVL: 
        
 
 
    polygon                   0.797611
    bsc                       0
    csc                       62.14143757899999
    
    total                    62.939048578999994

**Comment by GemsGame** [comment]
@g1nt0ki 

tvl: sumTokensExport({ chain: 'bsc', owner: BSC_CONTRACT, tokens: [nullAddress] }), 

doesn't work. zero result

**Pull request merged**
