### PR TITLE
add everlend adapter

### PR DESCRIPTION
**Pull request by EvgeniiVoznyuk**
##### Twitter Link:
https://twitter.com/EverlendFinance

##### List of audit links if any:
 in progress

##### Website Link:
https://everlend.finance

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): attached

Black Logo Mark

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Are these additional dependencies critical? gintoki's spent a lot of time over the past few weeks removing dependencies because we were having build time issues

**Comment by EvgeniiVoznyuk** [comment]
Hi @waynebruce0x, pull was updated without additional dependencies. Just api request

**Comment by llamatester** [comment]
Error while running adapter at projects/everlend: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:217:11

**Comment by waynebruce0x** [comment]
Can you please test with 'node test.js projects/everlend/index.js'

**Comment by EvgeniiVoznyuk** [comment]
Hi @waynebruce0x , I fixed a problem and tested with  'node test.js projects/everlend/index.js'. Works without problems

**Comment by llamatester** [comment]
The adapter at projects/everlend exports TVL: 
        
 
 
    
    total                    426.27 k

**Comment by EvgeniiVoznyuk** [comment]
@waynebruce0x  @llamatester Hi guys, can you replace logo with a new one ? because old logo has crop on your platform
logo-mark

**Pull request merged**
