### PR TITLE
Algebra Protocol DEXs

### PR DESCRIPTION
**Pull request by lilchizh**
**NOTE**

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Algebra Protocol

##### Twitter Link:
https://mobile.twitter.com/cryptoalgebra

##### List of audit links if any:
ABDK - https://algebra.finance/static/ABDK_Algebra_Audit-b4a20379efce1d26b7fbe9127582df6a.pdf
Hexens - https://algebra.finance/static/Hexens_Algebra_Audit-0918594cb7666296d9f57295d9274270.pdf
Code4Rena - https://code4rena.com/contests/2022-09-quickswap-and-stellaswap-contest/
Hacken - https://algebra.finance/static/Hacken_Algebra_Audit-317911476f86c632be77388fa51852c0.pdf

##### Website Link:
https://algebra.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
image

##### Current TVL:
We provide V3 services for:
QuickSwap on Polygon - $38.5m
QuickSwap on Dogechain - $1.9m
StellaSwap on Moonbeam - $128k
##### Chain:
Polygon, Dogechain, Moonbeam

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
Token ID - algebra

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
Token ID - 13211

##### Short Description (to be shown on DefiLlama):
Algebra Protocol
Providing DEXs with the best concentrated liquidity solutions. Increase both capital efficiency & user convenience of your project effortlessly.

##### Token address and ticker if any:
0x0169ec1f8f639b32eec6d923e24c2a2ff45b9dd6 - 'ALGB'

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
No

##### forkedFrom (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated):
Fetching TVL from subgraphs of DEXs, which are using our protocol.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/algebra-protocol exports TVL: 
        
 
 
    moonbeam                  130.13 k
    polygon                   38.77 M
    dogechain                 1.96 M
    
    total                    40.86 M

**Comment by lilchizh** [comment]
Don't know why it failed :(

**Comment by llamatester** [comment]
The adapter at projects/algebra exports TVL: 
        
 
 
    polygon-staking           65.30 k
    polygon                   306.55 k
    staking                   65.30 k
    
    total                    306.55 k

**Comment by llamatester** [comment]
The adapter at projects/raydium.js exports TVL: 
        
 
 
    
    total                    38.50 M

**Comment by llamatester** [comment]
The adapter at projects/algebra-protocol exports TVL: 
        
 
 
    moonbeam                  147.07 k
    polygon                   38.73 M
    dogechain                 1.96 M
    
    total                    40.83 M

**Comment by g1nt0ki** [comment]
> Don't know why it failed :(

It was my fault, I had introduced a lint error.

We already have algebra listed: https://defillama.com/protocol/algebra-dex

Also, you are sort of claiming all the tvl in quickswap and stellaswap is yours?

**Comment by lilchizh** [comment]
> > Don't know why it failed :(
> 
> It was my fault, I had introduced a lint error.
> 
> We already have algebra listed: https://defillama.com/protocol/algebra-dex
> 
> Also, you are sort of claiming all the tvl in quickswap and stellaswap is yours?

Thx for the quick fix! :)

Yeah, we do have our own DEX on DefiLLama. 

But we switched our business model from being standalone DEX to providing other DEXs with our technology. TVLs on QuickSwap, Dogechain and StellaSwap are not ours in terms of money source. But we want to introduce ourselves on DefiLlama as a protocol, and combine all TVLs from DEXs, that are using our technology. 

Right now there are 3 of them live: QuickSwap V3 on Polygon, QuickSwap V3 on Dogechain, StellaSwap Pulsar on Moonbeam

**Comment by llamatester** [comment]
The adapter at projects/algebra exports TVL: 
        
 
 
    polygon-staking           64.18 k
    polygon                   305.64 k
    staking                   64.18 k
    
    total                    305.64 k

**Comment by llamatester** [comment]
Error while running adapter at projects/defisaver.js: 
        
 
  
    
    
    Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0xC45d4f6B6bf41b6EdAA58B01c4298B8d9078269a","data":"0x05cc61ad","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:654:52
        at Array.forEach (<anonymous>)

**Comment by g1nt0ki** [comment]
@lilchizh I have merged it for other code changes, sorry, but I am still confused, quickswap v3 codebase/infra is provided by you? If that is the case, they deployed the smart contract/own the tvl in it

**Pull request merged**
