### PR TITLE
OVR info update

### PR DESCRIPTION
**Pull request by marcogianni**
##### methodology (what is being counted as tvl, how is tvl being calculated): We count the tokens locked in the staking contract, the tokens in the pools and the tokens in the IBCO reserve.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/ovr exports TVL: 
        
 
 
    ethereum-staking          427.51 k
    bsc                       171.21 k
    polygon                   24.76 k
    ethereum                  2.22 M
    staking                   427.51 k
    
    total                    2.42 M

**Comment by llamatester** [comment]
The adapter at projects/ovr exports TVL: 
        
 
 
    ethereum-staking          427.12 k
    polygon                   24.76 k
    ethereum                  2.23 M
    bsc                       171.14 k
    staking                   427.12 k
    
    total                    2.42 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
@marcogianni sorry, LP tvl belong to dexes not you, ICBO funds can be counted towards treasury but not towards tvl

https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by llamatester** [comment]
The adapter at projects/ovr exports TVL: 
        
 
 
    ethereum                  0
    ethereum-treasury         1.49 M
    polygon                   586.3448077607645
    ethereum-staking          412.50 k
    ethereum-vesting          6.79 M
    treasury                  1.49 M
    staking                   412.50 k
    vesting                   6.79 M
    
    total                    586.3448077607645

**Comment by jacko06v** [comment]
@g1nt0ki We've updated the adapter, thank you 👍

**Comment by llamatester** [comment]
The adapter at projects/ovr exports TVL: 
        
 
 
    ethereum                  0
    ethereum-vesting          6.79 M
    ethereum-staking          412.50 k
    polygon                   586.3448077607645
    ethereum-treasury         1.49 M
    vesting                   6.79 M
    staking                   412.50 k
    treasury                  1.49 M
    
    total                    586.3448077607645

**Comment by llamatester** [comment]
The adapter at projects/ovr exports TVL: 
        
 
 
    ethereum                  0
    polygon-staking           573.8161293643166
    ethereum-vesting          6.65 M
    ethereum-staking          403.48 k
    staking                   404.05 k
    vesting                   6.65 M
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/treasury/ovr.js exports TVL: 
        
 
 
    ethereum-ownTokens        0
    ethereum                  1.49 M
    ownTokens                 0
    
    total                    1.49 M

**Pull request merged**
