### PR TITLE
add rif on chain protocol

### PR DESCRIPTION
**Pull request by jonathansmirnoff**
##### Logo (High resolution, will be shown with rounded borders):
image

##### Short Description (to be shown on DefiLlama): A secure and censorship resistant stablecoin protocol built on Bitcoin using the Rootstock sidechain.

RIF On Chain is a fully decentralised protocol that gives users the ability to mint USDRIF, a fully crypto collaterised stablecoin and RIF PRO, a leveraged token for RIF holders and traders. 

##### Github org/user (Optional, if your code is open source, we can track activity): https://github.com/money-on-chain/stable-protocol-api

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/rif-on-chain exports TVL: 
        
 
 
    rsk                       22.82 M
    
    total                    22.82 M

**Comment by llamatester** [comment]
The adapter at projects/rif-on-chain exports TVL: 
        
 
 
    rsk                       21.17 M
    
    total                    21.17 M

**Comment by g1nt0ki** [comment]
hi @jonathansmirnoff thanks for the PR.

Are all 22M worth of RIF deposited by the users? I see only 800k USDRIF in circulation here https://dapp.rifonchain.com/ipfs/QmYJU4vWHFxoybwTq9Jkn8PQiKA42m2x5sSfWjVgke1ci4/#/metrics

**Comment by jonathansmirnoff** [comment]
> hi @jonathansmirnoff thanks for the PR.
> 
> Are all 22M worth of RIF deposited by the users? I see only 800k USDRIF in circulation here https://dapp.rifonchain.com/ipfs/QmYJU4vWHFxoybwTq9Jkn8PQiKA42m2x5sSfWjVgke1ci4/#/metrics

You are right, there are 800k [UDSRIF](https://explorer.rsk.co/address/0x3a15461d8ae0f0fb5fa2629e9da7d66a794a6e37) in circulation, and the 22 M was deposited by users ([RoC token]( https://explorer.rsk.co/address/0xcff3fcaec2352c672c38d77cb1a064b7d50ce7e1)).

**Pull request merged**
