### PR TITLE
Bao finance

### PR DESCRIPTION
**Pull request by fabiaz84**
**NOTE**

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama): 
Bao Finance v2

##### Twitter Link: 
https://mobile.twitter.com/baocommunity

##### List of audit links if any: 
In start up phase, no audits as of now. We will update this as soon as we have news.

##### Website Link: 
https://mainnet.app.bao.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
We are undergoing a rebrand in the next few months so an update will be coming, but here is the current logo;
https://github.com/baofinance/bao-ui/blob/master/public/images/icons/icon-512.png

##### Current TVL: 
Approximately 

------ TVL ------
ethereum-staking          438.23 k
ethereum                  2.45 M
staking                   438.23 k

total                    2.45 M

Markets TVL
ETH		1.26k
USDC	25k
bSTBL	166.41k

Baskets
bSTBL (50% aUSDC and 50% aDAI)	403.86k 

Gauges
baoUSD-3crv		901.69k
bSTBL-DAI		481.38k
BAO-ETH			31.69k

Balast
Dai (reserve)	165.29k

veBao
Bao (staking)	438.97k

##### Chain:
Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
bao-finance-v2
{"id":"bao-finance-v2","symbol":"bao","name":"Bao Finance V2"}

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
23016
{"id":23016,"name":"Bao Finance (new)","symbol":"BAO","slug":"bao-finance-new","is_active":0,"status":"untracked"}

##### Short Description (to be shown on DefiLlama):
Traditional finance does not work. Not for most people. It works for wealthy suits. It's great for them. They own the data. They own the marketplace. And if things do not go their way, they change the rules.

Why does this happen? - It all comes down to data. Unfair access to financial data gives institutions their power.

This is why synthetics matter.

Bao Finance is a decentralized, community-run project that uses synthetics to move the power of information from institutions to individuals.

Its mission is to build a platform for creating synthetic assets and markets representing any data in the world. 

The BAO token is a vital part of this vision. It is designed to tackle the problem of mercenary liquidity by rewarding holders who stake their tokens for longer with a more significant share of project revenue, voting power, and liquidity incentives.

##### Token address and ticker if any:
0xce391315b414d4c7555956120461d21808a69f3a 
BAO
Bao Token v2

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Synthetics

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink, to determine the price of underlying assets in our Markets

##### forkedFrom (Does your project originate from another project):
PieDao, Inverse Finance and Curve (goverance), we have migrated away from masterchef which also has a DefiLlama site here https://defillama.com/protocol/bao-finance

##### methodology (what is being counted as tvl, how is tvl being calculated):
Baskets, a token with underlying assets
Markets, deposited collateral assets for baoUSD stable synthetic borrowing
Balast, stabilizer to mint baoUSD stable synthetic with DAI (mint limit capped at 500k)
Gauges, deposited LP's for Bao emissions
Staking, Bao staked as veBao

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bao-finance exports TVL: 
        
 
 
    ethereum-staking          438.99 k
    ethereum                  2.45 M
    staking                   438.99 k
    
    total                    2.45 M

**Comment by llamatester** [comment]
The adapter at projects/pandaswap exports TVL: 
        
 
 
    bsc                       376.34 k
    
    total                    376.34 k

**Comment by llamatester** [comment]
The adapter at projects/bao-baskets exports TVL: 
        
 
 
    ethereum-pool2            1.42 M
    ethereum-staking          415.02 k
    ethereum                  404.33 k
    pool2                     1.42 M
    staking                   415.02 k
    
    total                    404.33 k

**Comment by llamatester** [comment]
The adapter at projects/bao-markets exports TVL: 
        
 
 
    ethereum-borrowed         0
    ethereum                  26.28 k
    borrowed                  0
    
    total                    26.28 k

**Comment by llamatester** [comment]
The adapter at projects/bao-usd exports TVL: 
        
 
 
    ethereum                  165.29 k
    
    total                    165.29 k

**Comment by llamatester** [comment]
The adapter at projects/baoswap exports TVL: 
        
 
 
    xdai                      238.49 k
    
    total                    238.49 k

**Comment by g1nt0ki** [comment]
@fabiaz84 thanks for the PR, hope you dont mind that I refactored it. 

I split it into different protocols, this way one can see tvl change per protocol, also gauge tvl is Pool2, so I moved it there and ve tvl was eing double counted, fixed that.

**Pull request merged**
