### PR TITLE
Add: Avalon USDa

### PR DESCRIPTION
**Pull request by jasmin-avalon**
Avalon USDa is a sub-protocol of Avalon Labs. Avalon USDa allows users to use FBTC as collateral to mint USDa.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/avalon-finance-usda exports TVL: 
        
 
 
    ethereum                  70
    bsc                       12
    mantle                    0
    ethereum-borrowed         0
    mantle-borrowed           0
    bsc-borrowed              0
    borrowed                  0
    
    total                    81.49923308000001

**Comment by llamatester** [comment]
The adapter at projects/avalon-finance-usda exports TVL: 
        
 
 
    ethereum                  70
    bsc                       12
    ethereum-borrowed         0
    mantle-borrowed           0
    mantle                    0
    bsc-borrowed              0
    borrowed                  0
    
    total                    81.49923308000001

**Comment by g1nt0ki** [comment]
hi @jasmin-avalon 

LFBTC is already locked collateral  for USDT borrowing right?

**Comment by jasmin-avalon** [comment]
> hi @jasmin-avalon
> 
> LFBTC is already locked collateral for USDT borrowing right?

Hi @g1nt0ki , the LFBTC locked in Avalon USDa contract will be used as collateral to mint USDa. 
The LFBTC locked in Avalon CeDeFi contract will be used as collateral for USDT.  
These 2 use case are independent. 
Also the code we submit for TVL calculation will only count the LFBTC locked in corresponding contracts and will not lead to double counting.

Here is the user flow:
1. The user deposited FBTC to our contract: https://cn.etherscan.com/tx/0x8f350b436f902b274243652dffc46b4149c8df73c1557eef14588d7da74b3c3a
2. The users minted USDa: https://cn.etherscan.com/tx/0xb20534f0a77fe9d7435d0b7842f46bade659371a72d2d085e61009d8b512b156
3. We converted FBTC into LFBTC: https://cn.etherscan.com/tx/0x24350838cd4d09129b580090c6025e62c21b16a8860d5f2f01c0cd4327a2e39f

For USDT borrowing and USDa minting, LFBTC are locked in different contracts. 
- For USDa, LFBTC is locked in https://cn.etherscan.com/address/0x3f390dd6ef69f68f9877aacc086856a200808693 .
- For USDT borrowing, LFBTC is locked in https://cn.etherscan.com/token/0x3119a1ad5b63a000ab9ca3f2470611eb997b93b9?a=0x02fedcff97942fe28e8936cdc3d7a480fdd248f0

**Comment by llamatester** [comment]
The adapter at projects/avalon-finance-usda exports TVL: 
        
 
 
    ethereum                  25.23 M
    bsc                       57
    mantle                    0
    
    total                    25.23 M

**Comment by g1nt0ki** [comment]
@jasmin-avalon I have removed borrowed since we dont do that for minted tokens, like DAI/LUSD either

**Pull request merged**
