### PR TITLE
Add kamino lending

### PR DESCRIPTION
**Pull request by peroxy**
1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
Kamino Lend should be listed as a new protocol but should be part of Kamino (which already exists on DefiLlama). Please make it similar to how Frax (https://defillama.com/protocol/frax) works, where you have multiple Frax protocols on the same page and accessible via the tab view.

##### Name (to be shown on DefiLlama):
Kamino Lend

##### Twitter Link:
https://twitter.com/kamino_finance

##### List of audit links if any:
https://github.com/hubbleprotocol/kamino-audits

##### Website Link:
https://kamino.finance/

##### Logo (High resolution, will be shown with rounded borders):
please use the same logo that is currently used for Kamino

##### Current TVL:
$342k

##### Chain:
Solana

##### Short Description (to be shown on DefiLlama):
Kamino Lend (K-Lend) is a novel peer-to-pool borrowing primitive designed as foundational infrastructure to power complex financial products with leverage and automation and as a decentralized matchmaker between borrowers and lenders.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Scope, Pyth, Switchboard

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL consists of deposits made to the protocol, borrowed tokens are not counted.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/hubbleprotocol

---
### Notes about this PR:
- we use Anchor 0.26.0 which has new features (like enums), that's why I bumped the package.json version to 0.26.0:
  `"@project-serum/anchor": "^0.26.0",`
- your API currently doesn't support kTokens (Kamino tokens used by the main Kamino program, which are also available in Kamino Lending for borrows/deposits) which meant I would get this message when testing out the adapter:
```
Balance table for [solana] Unrecognized tokens
┌─────────┬──────┬────────┬─────────────────┬───────────────────────────────────────────────────────┬───────────┐
│ (index) │ name │ symbol │     balance     │                         label                         │ decimals  │
├─────────┼──────┼────────┼─────────────────┼───────────────────────────────────────────────────────┼───────────┤
│    0    │ '-'  │  '-'   │  '18491562800'  │ 'solana:9HB4kAMLSYfGFfN142DKMyPyHyZQ8pXF8M1STbDudodY' │ undefined │
│    1    │ '-'  │  '-'   │ '4948136636667' │ 'solana:GYiUmJ8reqYAdTQtx6CRFawHqPXx9yzkUFvaUVE8PskP' │ undefined │
│    2    │ '-'  │  '-'   │  '6269646393'   │ 'solana:4G9USgnbg6fDTQ5AUfpCjM89zqbzWj32xfqvsaAu66DM' │ undefined │
│    3    │ '-'  │  '-'   │ '763617741702'  │ 'solana:Dk2X1HCbwJae44P7FpqdFoeT6LEw4JVyyHvZMHUzHWbi' │ undefined │
│    4    │ '-'  │  '-'   │   '385000484'   │ 'solana:3Fb5DMRWoBLWD36Lp4BtG41LaFjVeEJNCH9YLNPYdVqj' │ undefined │
└─────────┴──────┴────────┴─────────────────┴───────────────────────────────────────────────────────┴───────────┘
```
This meant the TVL of kTokens would not get counted. To counter this I've added a function that checks if a reserve contains kTokens and uses our own internal price Oracle for those only. Since I could not add those to the token balances, I've added them as 'tether' so they get counted towards the total TVL number. Let me know if we can change this, maybe you can integrate the kToken oracle as well.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/kamino-lending: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by peroxy** [comment]
About the failing tests above ^ the package `@hubbleprotocol/scope-sdk` is used by `@hubbleprotocol/kamino-sdk` which is a dependency you guys have installed on your server, see this file which has kamino-sdk as a dependency: 
https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/kamino/api.js

Not sure if there's any way to fix this?

**Comment by llamatester** [comment]
Error while running adapter at projects/kamino-lending: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by g1nt0ki** [comment]
hi @peroxy 

I refactored the code here a bit: https://github.com/DefiLlama/DefiLlama-Adapters/pull/8026 removed parts of the idl not used in tvl computation, also skipped the ktokens, I am guessing the tokens backing those are already included in current kamino tvl? 

can you go over my changes?

**Comment by llamatester** [comment]
Error while running adapter at projects/kamino-lending: 
        
 
  
    
    
    FetchError: request to https://try-rpc.mainnet.solana.blockdaemon.tech/ failed, reason: getaddrinfo ENOTFOUND try-rpc.mainnet.solana.blockdaemon.tech
    Truncated error stack:
        at ClientRequest.<anonymous> (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/node-fetch/lib/index.js:1491:11)
        at ClientRequest.emit (node:events:517:28)
        at TLSSocket.socketErrorListener (node:_http_client:501:9)
        at TLSSocket.emit (node:events:529:35)

**Comment by g1nt0ki** [comment]
closed in favor of https://github.com/DefiLlama/DefiLlama-Adapters/pull/8026
Again, thanks for the PR

**Pull request closed without merging**
