### PR TITLE
Add C3 Exchange

### PR DESCRIPTION
**Pull request by javerett**
##### Name (to be shown on DefiLlama):
C3 Exchange

##### Twitter Link:
https://x.com/C3protocol

##### List of audit links if any:
https://github.com/c3exchange/c3-smartcontracts-v1/tree/main/audits

##### Website Link:
https://c3.io

##### Logo (High resolution, will be shown with rounded borders):
https://docs.c3.io/assets/images/C3-Icon2x.png

##### Current TVL:
$3.56M

##### Treasury Addresses (if the protocol has treasury)
N/A

##### Chain:
N/A

##### Short Description (to be shown on DefiLlama):

C3 Exchange offers the security and autonomy of a self-custodial exchange without compromising the functionality, performance, and ease of use expected from traditional exchanges. Additionally, C3 provides a seamless cross-chain experience, enhancing flexibility and accessibility for users across multiple blockchains.

##### Token address and ticker if any:
N/A

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Cross Chain

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Pyth

##### Implementation Details: Briefly describe how the oracle is integrated into your project:

The Pyth Network is constantly generating aggregated price data from a set of trusted providers. An endpoint is offered by the Price Service (Hermes) from which the Pricecaster backend polls for a set of price updates; the Pyth system will generate a price update dataset along with a Merkle Tree root to proof for each data item inclusion. To secure this proof, it is sent to the Wormhole network where a set of guardians will sign the data and generate a VAA (Verifiable Attestation). Subsequently, the data is processed and stored in the Pricecaster app contract, which is deployed on the blockchain to be consumed by the C3s core smart contract risk engine.

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
https://github.com/c3exchange/c3-smartcontracts-v1/tree/main/pricecaster

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
All assets in the C3 contract are totaled and remapped to common asset names

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/c3exchange/

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/c3 exports TVL: 
        
 
 
    ethereum                  1.54 M
    solana                    909.61 k
    bitcoin                   609.41 k
    avax                      237.54 k
    arbitrum                  153.14 k
    algorand                  81.52 k
    binance                   0
    
    total                    3.53 M

**Comment by llamatester** [comment]
The adapter at projects/c3 exports TVL: 
        
 
 
    avax                      1.52 M
    solana                    915.00 k
    bitcoin                   610.02 k
    ethereum                  260.83 k
    arbitrum                  157.00 k
    algorand                  82.00 k
    binance                   0
    
    total                    3.55 M

**Comment by llamatester** [comment]
The adapter at projects/c3 exports TVL: 
        
 
 
    avax                      1.51 M
    solana                    896.06 k
    bitcoin                   667.67 k
    ethereum                  252.17 k
    arbitrum                  145.41 k
    algorand                  80.17 k
    bsc                       0
    
    total                    3.55 M

**Comment by g1nt0ki** [comment]
@javerett thanks

**Comment by patrickdahdah** [comment]
@g1nt0ki
Thank you for checking and merging the PR!

We are very excited about the C3 listing on DefiLlama. https://defillama.com/protocol/c3-exchange

How can we correct the **category**? We are not a derivatives market; we should be shown as cross-chain.

**Pull request merged**
