### PR TITLE
Add carbondefi sei evm deployment

### PR DESCRIPTION
**Pull request by tiagofilipenunes**
# Description

Carbon DeFi's deployment on Ethereum already exists at https://defillama.com/protocol/carbon-defi. This PR seeks to add Sei support for the new deployment on Sei EVM as well.

# Information

##### Short Description (to be shown on DefiLlama):

Carbon is a decentralized trading protocol allowing users to perform automated trading strategies using custom on-chain limit, range, and concentrated liquidity orders.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/carbondefi: 
        
 
  
    
    
    Error: 
        Unknown chain(s): sei_evm
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file
        
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
Error while running adapter at projects/carbondefi: 
        
 
  
    
    
    Error: Error fetchin cosmos block -
           chain: sei, block: 100, endPoint: https://evm-rpc.sei-apis.com/, error: Request failed with status code 404
    Truncated error stack:
        at getCosmosBlock (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cosmos.js:62:15)
        at async Promise.all (index 1)

**Comment by tiagofilipenunes** [comment]
@g1nt0ki I had sei_evm first and I see you merged them. Seems like there's something wrong with the adapter on the evm side, can you please check? Thanks

**Comment by g1nt0ki** [comment]
so, it was picking cosmos rpc for fetching block height, I fixed it now, but there still seems to be a problem fetching logs, debugging it now

**Comment by tiagofilipenunes** [comment]
@g1nt0ki I got the adapter to run locally too, but when trying to get logs, they come out empty.

There is a hard 2000 block/call limit in the sei evm chain code. Haven't investigated if this is the issue yet, just flagging in case it helps

**Comment by llamatester** [comment]
Error while running adapter at projects/carbondefi: 
        
 
  
    
    
    Error: Multicall failed! 
     [chain: sei] [fail count: 1] [abi: function balanceOf(address account) view returns (uint256)]  
        target: 0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE params: 0xe4816658ad10bF215053C533cceAe3f59e1f1087]

**Comment by tiagofilipenunes** [comment]
@g1nt0ki I've changed our adapter to use a contract call instead of getting logs. Locally with changes to the defillama-sdk repo that separate Sei Cosmos from Sei EVM, it worked. Without these changes, Sei EVM adapters will not be able to perform contract calls.

**Comment by g1nt0ki** [comment]
thanks, merged it here with minor fix: https://github.com/DefiLlama/DefiLlama-Adapters/pull/10500

**Pull request closed without merging**
