### PR TITLE
Added curve pools for maha.xyz

### PR DESCRIPTION
**Pull request by senamakel**
We now have two curve pools for ZAI. The LP is being tracked in pool2 in this PR.

https://curve.fi/#/ethereum/pools/factory-stable-ng-229/deposit
https://curve.fi/#/ethereum/pools/factory-twocrypto-54/deposit

Also removed the old tokens from the treasury.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/mahaxyz exports TVL: 
        
 
 
    ethereum                  20.64 k
    ethereum-pool2            19.11 k
    pool2                     19.11 k
    
    total                    20.64 k

**Comment by llamatester** [comment]
The adapter at projects/treasury/mahaxyz.js exports TVL: 
        
 
 
    ethereum-ownTokens        943.64 k
    ownTokens                 943.64 k
    ethereum                  739.08 k
    
    total                    739.08 k

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
@senamakel thanks for the PR but  pool2 is LP tokens  deposited in contracts owned by your usually for rewarding liquidity providers, not tokens in the pool

**Comment by llamatester** [comment]
The adapter at projects/mahaxyz exports TVL: 
        
 
 
    ethereum-pool2            39.94 k
    pool2                     39.94 k
    ethereum                  21.18 k
    
    total                    21.18 k

**Comment by llamatester** [comment]
The adapter at projects/treasury/mahaxyz.js exports TVL: 
        
 
 
    ethereum-ownTokens        988.88 k
    ownTokens                 988.88 k
    ethereum                  774.50 k
    
    total                    774.49 k

**Comment by llamatester** [comment]
The adapter at projects/mahaxyz exports TVL: 
        
 
 
    ethereum-pool2            39.71 k
    pool2                     39.71 k
    ethereum                  21.22 k
    
    total                    21.22 k

**Comment by llamatester** [comment]
The adapter at projects/treasury/mahaxyz.js exports TVL: 
        
 
 
    ethereum-ownTokens        992.50 k
    ownTokens                 992.50 k
    ethereum                  777.32 k
    
    total                    777.32 k

**Comment by senamakel** [comment]
Hey @g1nt0ki so we've made the changes and added the staking contract for our LP tokens. PFA the new PR.

**Comment by g1nt0ki** [comment]
@senamakel thanks for the fix

**Pull request merged**
