### PR TITLE
XDAO: Added TVL count on Moonbeam, Moonriver, Optimism, OKExChain, Metis...

### PR DESCRIPTION
**Pull request by modagavr**
##### Twitter Link:
https://twitter.com/xdaoapp

##### List of audit links if any:
https://github.com/pessimistic-io/audits/blob/main/xDao%202%20Security%20Recheck.pdf

https://hacken.io/wp-content/uploads/2021/09/xDAO_03092021SCAudit_Report_2.pdf

##### Website Link:
https://www.xdao.app/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://defillama.com/_next/image?url=https%3A%2F%2Ficons.llama.fi%2Fxdao.jpg&w=64&q=75

##### Current TVL:
2.5 M $

##### Chain:
Ethereum, BSC, Polygon, Heco, Avalanche, Fantom, Astar, Optimism, Okexchain, Moonbeam, Moonriver, Metis, Boba

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
XDAO is not listed on exchanges  and Coingecko

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

XDAO is not listed on exchanges  and Coinmarketcap

##### Short Description (to be shown on DefiLlama):
XDAO - MultiChain DAO Ecosystem Built For Decentralized Future, XDAO is the fastest framework to create and manage decentralized autonomous organizations

##### Token address and ticker if any:
XDAO is not listed on exchanges

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Services

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Debank, Covalent, Coingecko

##### forkedFrom (Does your project originate from another project):
None

##### methodology (what is being counted as tvl, how is tvl being calculated):

Added TVL on Optimism, OKExChain, Metis and Boba with Debank and Coingecko API.

Added TVL on Moonbeam and Moonriver with Covalent and Coingecko API.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/xdao.js exports TVL: 
        
 
 
    optimism                  0
    boba                      0
    avax                      18.750392395211364
    ethereum                  152.36 k
    okexchain                 0
    metis                     0
    astar                     142.25 k
    moonbeam                  6.544445038498894
    heco                      1.17 k
    moonriver                 27.1324
    fantom                    78.12799245975174
    bsc                       4.04 M
    polygon                   1.65 M
    
    total                    5.99 M

**Comment by waynebruce0x** [comment]
Can we do this without querying DeBank?

**Comment by modagavr** [comment]
> Can we do this without querying DeBank?

This is the only way that we found to calculate Optimism, OKExChain, Metis and Boba tvl

**Comment by waynebruce0x** [comment]
These chains are still returning 0 though - is that right?

**Comment by modagavr** [comment]
> These chains are still returning 0 though - is that right?

Yes, that's right. We have 0 tvl on these chains right now, also checked manually

**Comment by waynebruce0x** [comment]
Is the debank API open source? Do you know how they're calculating this?

**Comment by modagavr** [comment]
> Is the debank API open source? Do you know how they're calculating this?

I don't know, I just rely on their popularity

**Comment by waynebruce0x** [comment]
Closing for inactivity - if you'd like this reopening please let us know in discord

**Pull request closed without merging**
