### PR TITLE
add Kronosdao

### PR DESCRIPTION
**Pull request by bitch2k**
Twitter Link: https://twitter.com/dao_kronos

List of KYC:
https://www.assuredefi.io/projects/kronos-dao-2/

Website Link:
https://kronosdao.ai/

Chain:
BNB Smart Chain

Short Description (to be shown on DefiLlama):
Kronos DAO is the next evolution of the reserve currency protocol. Nodes, Kronoscharger, Kronospad, Swap, Farms and Pools.

Token address and ticker if any:
0xbeC68a941feCC79E57762e258fd1490F29235D75

Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
KRONOS

### CODE REVIEW

**Comment by bitch2k** [comment]
Twitter Link: https://twitter.com/dao_kronos

List of KYC:
https://www.assuredefi.io/projects/kronos-dao-2/

Website Link:
https://kronosdao.ai/

Chain:
BNB Smart Chain

Short Description (to be shown on DefiLlama):
Kronos DAO is the next evolution of the reserve currency protocol. Nodes, Kronoscharger, Kronospad, Swap, Farms and Pools.

Alex!, [03/05/22 01:07]
alla descrizione?

Token address and ticker if any:
0xbeC68a941feCC79E57762e258fd1490F29235D75


Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
KRONOS

**Comment by llamatester** [comment]
The adapter at projects/kronosdao exports TVL: 
        
 
 
    bsc-staking               80.04 k
    bsc                       247.40 k
    staking                   80.04 k
    
    total                    247.40 k

**Comment by bitch2k** [comment]
Hello,
KronosDAO is now on coinmarketcap.
Is it possible to add a button viewing in our Defillama's page?
Thanks a lot.
That's the link:
https://coinmarketcap.com/currencies/kronosdao/

**Comment by bitch2k** [comment]
Please tell me how to insert Coinmarketcap link in Kronosdao page.
Thanks

**Pull request merged**
