### PR TITLE
Added DexPad adapters

### PR DESCRIPTION
**Pull request by dexpad-dev**
##### Twitter Link:
https://twitter.com/DexPad

##### Website Link:
https://dexpad.io

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://photonswap.finance/dxp.png

##### Current TVL:
477.71 k 
##### Chain:

------ TVL ------
avax                      0.0684573119999989
polygon                   21.526007789401433
kava                      2.002
cronos                    477.69 k

total                    477.71 k 

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
dexpad

##### Short Description (to be shown on DefiLlama):
DexPad is a No-Code Platform for ERC-20 Tokens on multiple EVM-compatible chains. Mint, Lock, Airdrop or Presale your token without any coding knowledge require

##### Token address and ticker if any:
0xe0c41ff9a7032de445771e12c14868cbe061c993
DxP

##### Category (full list at https://defillama.com/categories) *Please choose only one:
services

##### methodology (what is being counted as tvl, how is tvl being calculated):
Counts each LP pair's native token and stable balance, adjusted to reflect locked pair's value. Balances and merged across multiple locker and staking contracts to return sum TVL per chain

### CODE REVIEW

**Comment by waynebruce0x** [comment]
CAn you verify a locker contract so we can see the calculation done inside the contract? Thanks

**Comment by dexpad-dev** [comment]
Hi @waynebruce0x 
I am getting issue in verifying cronos locker contract so I have removed it's TVL and verified contracts for Avax, Polygon and Kava chains.

On Kava chain it's not able to consider USDC address value and shows unknown.

https://explorer.kava.io/token/0xfA9343C3897324496A05fC75abeD6bAC29f8A40f/token-transfers

new TVLs
--- tvl ---
WMATIC                    17.001710610226958
USDC                      5.6277720780000005
WAVAX                     0.07575321599999876
UNKNOWN (kava:0xfa9343c3897324496a05fc75abed6bac29f8a40f) 0
Total: 22.705235904226956 

------ TVL ------
avax                      0.07575321599999876
polygon                   22.629482688226958
kava                      0

total                    22.705235904226956

**Comment by llamatester** [comment]
The adapter at projects/dexpad exports TVL: 
        
 
 
    avax                      0.07109625599999884
    kava                      2.002
    
    total                    2.0730962559999986

**Comment by dexpad-dev** [comment]
new and updated TVL after including Cronos.

------ TVL ------
avax                      0.0684573119999989
polygon                   21.526007789401433
kava                      2.002
cronos                    477.69 k

total                    477.71 k

**Pull request merged**
