### PR TITLE
Add AILayer Chain

### PR DESCRIPTION
**Pull request by Cohiban**
AILayer

Website Link:
https://ailayer.xyz/

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/ainnswap exports TVL: 
        
 
 
    ailayer                   64.21 k
    
    total                    64.21 k

**Comment by Cohiban** [comment]
Logo
https://ailayer.xyz/images/logo.png

**Comment by llamatester** [comment]
The adapter at projects/ainnswap exports TVL: 
        
 
 
    ailayer                   122.58 k
    
    total                    122.58 k

**Comment by g1nt0ki** [comment]
thanks for the PR

**Pull request merged**
