### PR TITLE
Update DerpDEX TVL calculations

### PR DESCRIPTION
**Pull request by geckocoding**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/DerpDEX exports TVL: 
        
 
 
    base                      11.06 k
    era                       83.24 k
    op_bnb                    231.46 k
    
    total                    325.76 k

**Comment by g1nt0ki** [comment]
Hi @geckocoding,  the issue with relying on graph for tvl is tokens like SOLANA 
image

It has 11 holders (including DerpDex LP addresses), last transaction was 10 hours ago. has only 2k worth WBNB, but it paired against other tokens (also not on coingecko) contribute about 180k to tvl. 

We used to rely on graph for uniswap v3, ran into this issue with users creating dummy tokens and getting incorrect tvl

**Comment by geckocoding** [comment]
> Hi @geckocoding, the issue with relying on graph for tvl is tokens like SOLANA image
> 
> It has 11 holders (including DerpDex LP addresses), last transaction was 10 hours ago. has only 2k worth WBNB, but it paired against other tokens (also not on coingecko) contribute about 180k to tvl.
> 
> We used to rely on graph for uniswap v3, ran into this issue with users creating dummy tokens and getting incorrect tvl

Thanks for pointing out this. We also discovered some dummy tokens are occurring on our LPs. However some of the unknown tokens (Not found in coingecko) is actual LP actually. Also, DerpDEX is the DEX that targeting on meme token traders and LPs, so we are wondering is there any other ways other than subgraph can be used for tracking unknown tokens (micro-cap) fairly since there are a lot of meme tokens can be found in DerpDEX (UniswapV3 fork).  

We are looking for the similar ways that can use `getUniTVL` function but on UniswapV3 fork.

**Comment by g1nt0ki** [comment]
let me think a bit more about this, but dont think relying on graph api is the right approach

**Comment by geckocoding** [comment]
> let me think a bit more about this, but dont think relying on graph api is the right approach

Thanks. Hope there is something we can work together on this.

**Comment by g1nt0ki** [comment]
closing this for now, will fix this on coins repo when I get some free time

**Pull request closed without merging**
