### PR TITLE
Upstream/cygnusdao

### PR DESCRIPTION
**Pull request by 0xsnowman**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama): 

> CygnusDAO

##### Twitter Link: 

> https://twitter.com/cygnusdao

##### Website Link: 

> https://cygnusdao.finance/

##### Logo (High resolution, will be shown with rounded borders): 

> https://files.gitbook.com/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FNOhzFVgSva7KRpPaSAC9%2Fuploads%2FvK3Y5TdpvQt1kEXWK4MA%2FcygTokenRound.png?alt=media&token=734dfccb-9dec-4e2e-9901-967c683106ca

##### Current TVL: 

> $12.57k

##### Chain: 

> Polygon

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

> Not yet

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

> Not yet

##### Short Description (to be shown on DefiLlama): 

> CygnusDAO is a decentralized Stablecoin Lending and Leverage Trading protocol for LPs

##### Token address and ticker if any: 

> https://polygonscan.com/token/0xc553a5a789f1bb56a72847b3fda1de3e16e6763f#code

##### Category (full list at https://defillama.com/categories) *Please choose only one: 

> Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

> Chainlink

##### forkedFrom (Does your project originate from another project):

>  No

##### methodology (what is being counted as tvl, how is tvl being calculated): 

> - For USDC lending pool the tvl is counted as total borrows + total cash (ie total available to borrow)
> - For Collateral pools the tvl is counted as LPs held in contract * LP Price (using chainlink oracles)
> - TVL of all shuttles we deployed = borrowable + collateral

##### Github org/user (Optional, if your code is open source, we can track activity): 

> https://github.com/CygnusDAO

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/cygnusdao exports TVL: 
        
 
 
    polygon                   12.51 k
    
    total                    12.51 k

**Comment by llamatester** [comment]
The adapter at projects/cygnusdao exports TVL: 
        
 
 
    polygon                   12.45 k
    
    total                    12.45 k

**Comment by g1nt0ki** [comment]
hi @0xsnowman thanks for the PR, I am getting lower tvl is it because I am excluding borrowed amount?

**Comment by llamatester** [comment]
The adapter at projects/cygnusdao exports TVL: 
        
 
 
    polygon                   7.75 k
    
    total                    7.75 k

**Comment by llamatester** [comment]
The adapter at projects/cygnusdao exports TVL: 
        
 
 
    polygon                   7.75 k
    
    total                    7.75 k

**Comment by 0xHyoga** [comment]
Hi @llamatester just had a look and indeed it is because you are not counting `totalBorrows` at line 27.

Also would it be possible to just query this all through our factory contract like @0xsnowman originally did? Right now we have integrated with hypervisor, but we plan for other dexes like Balancer, etc. who don't have Hypervisor and we'd need to modify the code each time.

The factory uses the exact same logic you used for calculating the TVL, except it also takes into account the `totalBorrows` for borrowable pools and uses all chainlink oracles for this (as we cannot deploy without chainlink).

Factory on polygon: https://polygonscan.com/address/0x94faE55669327e71E9EC579067ad6C3C3b84e574#readContract

Has all the public view functions:

- totalBorrowsUsd()
- allCollateralsTvlUsd()
- allBorrowablesTvlUsd()

- borrowableTvlUsd(poolId)
- collateralTvlUsd(poolId)

- cygnusTvlUsd()

This would make it really easy for us to maintain the adapter.

Thanks.

**Comment by g1nt0ki** [comment]
hi @0xHyoga the thing is we dont view borrowed tokens as tvl, we can count it separately under 'borrowed' key:https://docs.llama.fi/list-your-project/what-to-include-as-tvl 

This is what we do for all lending protocols.

Balancer tokens should not be an issue as our system already supports pricing those :)

**Comment by 0xHyoga** [comment]
Hi @g1nt0ki makes sense thanks. 

Just went thorugh the tvl docs, and it mentions this:

"We also don't accept assets that your protocol generates and are locked into other protocols, as that's the later protocols TVL, not your project's."

All the borrowable deposits (USDC) are actually deposited into other protocols such as Compound and Aave and only removed when users want to borrow from Cygnus. When querying `totalBalance` on borrowable pools it will returns the total usdc deposited in those protocols. Similarily, when querying `totalBalance` on collateral pools it will return the total LP deposited in the DEX. 

So having said that, I guess we can't really be included on DeFi llama since all our deposits (on both borrowable/collateral) are actually deposited into other protocols, and we can't count borrowed amount  as tvl?

**Comment by g1nt0ki** [comment]
> Hi @g1nt0ki makes sense thanks.
> 
> Just went thorugh the tvl docs, and it mentions this:
> 
> "We also don't accept assets that your protocol generates and are locked into other protocols, as that's the later protocols TVL, not your project's."
> 
> All the borrowable deposits (USDC) are actually deposited into other protocols such as Compound and Aave and only removed when users want to borrow from Cygnus. When querying `totalBalance` on borrowable pools it will returns the total usdc deposited in those protocols. Similarily, when querying `totalBalance` on collateral pools it will return the total LP deposited in the DEX.
> 
> So having said that, I guess we can't really be included on DeFi llama since all our deposits (on both borrowable/collateral) are actually deposited into other protocols, and we can't count borrowed amount as tvl?

Just to be clear, if someone deposits a uni v2 LP to borrow some tokens, or say users are lending USDC through your app, and you deposit the excess USDC (not yet borrowed by users ) into compound for extra yield, both these cases, we count it as your tvl as the LP token, or cToken in compounds case is held by you (smart contracts deployed by your team) and would count towards your tvl (but not towards chain's tvl, as we already include tvl from uniswap/compound). 


As for tokens borrowed by users, they is no longer held by your smart contract/in your control hence cant include in your tvl, but under a different key 'borrowed', you can check aave/compound, this is what we do there

Does this make sense?

**Comment by 0xHyoga** [comment]
> > Hi @g1nt0ki makes sense thanks.
> > Just went thorugh the tvl docs, and it mentions this:
> > "We also don't accept assets that your protocol generates and are locked into other protocols, as that's the later protocols TVL, not your project's."
> > All the borrowable deposits (USDC) are actually deposited into other protocols such as Compound and Aave and only removed when users want to borrow from Cygnus. When querying `totalBalance` on borrowable pools it will returns the total usdc deposited in those protocols. Similarily, when querying `totalBalance` on collateral pools it will return the total LP deposited in the DEX.
> > So having said that, I guess we can't really be included on DeFi llama since all our deposits (on both borrowable/collateral) are actually deposited into other protocols, and we can't count borrowed amount as tvl?
> 
> Just to be clear, if someone deposits a uni v2 LP to borrow some tokens, or say users are lending USDC through your app, and you deposit the excess USDC (not yet borrowed by users ) into compound for extra yield, both these cases, we count it as your tvl as the LP token, or cToken in compounds case is held by you (smart contracts deployed by your team) and would count towards your tvl (but not towards chain's tvl, as we already include tvl from uniswap/compound).
> 
> As for tokens borrowed by users, they is no longer held by your smart contract/in your control hence cant include in your tvl, but under a different key 'borrowed', you can check aave/compound, this is what we do there
> 
> Does this make sense?

This makes a lot of sense, thank you. 

The TVL you reported previously then makes sense.

**Comment by llamatester** [comment]
The adapter at projects/cygnusdao exports TVL: 
        
 
 
    polygon-borrowed          8.36 k
    polygon                   13.48 k
    borrowed                  8.36 k
    
    total                    13.48 k

**Comment by g1nt0ki** [comment]
@0xsnowman I have included borrowed value as separate export

**Comment by 0xsnowman** [comment]
Thank you, @g1nt0ki!

**Pull request merged**
