### PR TITLE
Obtain the margins of BSC

### PR DESCRIPTION
**Pull request by JoJo-Joker**
##### Name (to be shown on DefiLlama):
Zeepr

##### Twitter Link:
https://twitter.com/Zeepr_labs

##### List of audit links if any:
N/A

##### Website Link:
https://www.zeepr.io/

##### Current TVL:
2.11B

##### Treasury Addresses (if the protocol has treasury)
N/A

##### Chain:
Arbitrum、BNB Chain、Polygon、EOS EVM、Core

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

##### Short Description (to be shown on DefiLlama):
Zeepr is the world's first decentralized perpetual contract protocol that supports both Coin-margin and U-margin, amplifying traders' profits.

##### Token address and ticker if any:
0xe46C5eA6Da584507eAF8dB2F3F57d7F578192e13

##### Category (full list at https://defillama.com/categories) *Please choose only one:
4.Dexes

##### forkedFrom (Does your project originate from another project):
No

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/Zeeprlabs

##### Logo (High resolution, will be shown with rounded borders):
photo_6336565470735481090_x

Hello, I have a few questions to ask:
1. I want to count tvl on multiple chains. Is this how the code is written?
2.Does the vaults in the function vaultTvl(vaults) method refer to the corresponding contract address?
3.Is tokensAndOwners the token asset address corresponding to the value?
4.What does the lps parameter refer to?

In addition, I call the current code execution node test.js projects/zeepr/index.js and report an error.
Tip: call reverted, reason: too many arguemnts: types/values length mismatch (count=1, expectedCount=0, code=UNEXPECTED_ARGUMENT, version=6.9.2),
But there are corresponding methods and corresponding parameters in my contract. What is the reason for this?

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/zeepr: 
        
 
  
    
    
    Error: 
        Found export keys that were not part of specification: arbitrum, bsc, core, polygon
    
        List of valid keys: 
    				
    				tvl
    				staking
    				methodology
    				pool2
    				misrepresentedTokens
    				fetch
    				timetravel
    				borrowed
    				start
    				doublecounted
    				treasury
    				hallmarks
    				incentivized
    				offers
    				deadFrom
    				broken
    				ownTokens
    				vesting
        
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:138:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
Error while running adapter at projects/zeepr: 
        
 
  
    
    
    Error: Multicall failed! 
     [chain: core] [fail count: 1] [abi: address:totalMargins]  
        target: 0x93614e83C2d2874616B60B550215637eE84c5eAB

**Comment by llamatester** [comment]
Error while running adapter at projects/zeepr: 
        
 
  
    
    
    Error: Multicall failed! 
     [chain: arbitrum] [fail count: 1] [abi: address:totalMargins]  
        target: 0x1c2D10633C78A47786759715d4618296D85D7cD1

**Comment by llamatester** [comment]
Error while running adapter at projects/zeepr: 
        
 
  
    
    
    Error: Multicall failed! 
     [chain: bsc] [fail count: 1] [abi: address:totalMargins]  
        target: 0x88A72cb97E89b9B4bBfAaE90F123f176C59F1Bbc

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
the code structure is mostly fine, it has a few issues though: `tokensAndOwners` accepts arrary of `[token, owner]`   but you passed a single string.

I am unable to check/fix the code as the contract addresses provided are example and not deployed in production.

Example of multiple chain tvl: https://github.com/JoJo-Joker/DefiLlama-Adapters/blob/pr/JoJo-Joker/9520/projects/preon/index.js#L56
https://github.com/JoJo-Joker/DefiLlama-Adapters/blob/pr/JoJo-Joker/9520/projects/prePo/index.js#L10

example code with tokensAndOwners: https://github.com/JoJo-Joker/DefiLlama-Adapters/blob/pr/JoJo-Joker/9520/projects/gainsNetwork.js#L32

**Comment by JoJo-Joker** [comment]
> 代码结构大部分都很好，但有一些问题：`tokensAndOwners`接受数组，`[token, owner]` 但传递了单个字符串。
> 
> 我无法检查/修复代码，因为提供的合约地址是示例，未部署在生产中。
> 
> 多链tvl示例：[https://github.com/JoJo-Joker/DefiLlama-Adapters/blob/pr/JoJo-Joker/9520/projects/preon/index.js#L56 ](https://github.com/JoJo-Joker/DefiLlama-Adapters/blob/pr/JoJo-Joker/9520/projects/preon/index.js#L56) [https://github.com/JoJo -Joker/DefiLlama-Adapters/blob/pr/JoJo-Joker/9520/projects/prePo/index.js#L10](https://github.com/JoJo-Joker/DefiLlama-Adapters/blob/pr/JoJo-Joker/9520/projects/prePo/index.js#L10)
> 
> 带有 tokensAndOwners 的示例代码：https://github.com/JoJo-Joker/DefiLlama-Adapters/blob/pr/JoJo-Joker/9520/projects/gainsNetwork.js#L32

May I ask what tokens in "tokensAndOwners" represent and what owners represent

**Comment by llamatester** [comment]
The adapter at projects/zeepr exports TVL: 
        
 
 
    arbitrum                  0
    
    total                    0

**Comment by JoJo-Joker** [comment]
Hello, may I ask is this correct to write the new code like this? But why is the total output of running node test.js projects/zeepr/index.js all 0.

**Comment by llamatester** [comment]
The adapter at projects/zeepr exports TVL: 
        
 
 
    arbitrum                  0
    
    total                    0

**Pull request closed without merging**
