### PR TITLE
Add DF staking.

### PR DESCRIPTION
**Pull request by Skyge**
Add DF staking to the total TVL.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/dforce/index.js exports TVL: 
        
 
 
    optimism                  693.39 k
    polygon                   10.56 M
    arbitrum                  138.80 M
    bsc                       106.33 M
    ethereum                  65.92 M
    
    total                    322.30 M

**Comment by waynebruce0x** [comment]
Can DF staking TVL be exported as a separate 'staking' export instead of as part of core TVL? thanks

**Comment by Skyge** [comment]
Do you mean like this:
```
module.exports = {
  ethereum:{
    tvl: ethereum
  },
  bsc: {
    tvl: bsc
  },
  arbitrum:{
    tvl: arbitrum
  },
  optimism: {
    tvl: optimism
  },
  polygon: {
    tvl: polygon
  },
staking: { // <<<--- Add at here
  tvl: staking
}
  start: 1564165044, // Jul-27-2019 02:17:24 AM +UTC
}
```

**Comment by llamatester** [comment]
Error while running adapter at projects/dforce/index.js: 
        
 
  
    
    
    FetchError: request to https://api.llama.fi/coins failed, reason: read ECONNRESET
        at ClientRequest.<anonymous> (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/node-fetch/lib/index.js:1491:11)
        at ClientRequest.emit (node:events:520:28)
        at TLSSocket.socketErrorListener (node:_http_client:442:9)
        at TLSSocket.emit (node:events:520:28)
        at emitErrorNT (node:internal/streams/destroy:157:8)
        at emitErrorCloseNT (node:internal/streams/destroy:122:3)
        at processTicksAndRejections (node:internal/process/task_queues:83:21) {
      type: 'system',
      errno: 'ECONNRESET',
      code: 'ECONNRESET'
    }

**Comment by llamatester** [comment]
The adapter at projects/dforce/index.js exports TVL: 
        
 
 
    staking                   371.29 k
    optimism                  693.85 k
    polygon                   10.56 M
    arbitrum                  138.75 M
    bsc                       106.19 M
    ethereum                  65.58 M
    
    total                    322.15 M

**Comment by g1nt0ki** [comment]
> Do you mean like this:
> 
> ```
> module.exports = {
>   ethereum:{
>     tvl: ethereum
>   },
>   bsc: {
>     tvl: bsc
>   },
>   arbitrum:{
>     tvl: arbitrum
>   },
>   optimism: {
>     tvl: optimism
>   },
>   polygon: {
>     tvl: polygon
>   },
> staking: { // <<<--- Add at here
>   tvl: staking
> }
>   start: 1564165044, // Jul-27-2019 02:17:24 AM +UTC
> }
> ```

No, like this:

    ethereum: {
      tvl: ethereum,
      staking,
    }

**Comment by llamatester** [comment]
The adapter at projects/dforce/index.js exports TVL: 
        
 
 
    optimism                  699.99 k
    ethereum-staking          371.55 k
    bsc                       107.02 M
    polygon                   10.57 M
    arbitrum                  138.44 M
    ethereum                  65.77 M
    staking                   371.55 k
    
    total                    322.49 M

**Comment by llamatester** [comment]
The adapter at projects/dforce/index.js exports TVL: 
        
 
 
    optimism                  699.99 k
    ethereum-staking          371.55 k
    polygon                   10.57 M
    arbitrum                  138.44 M
    ethereum                  65.77 M
    bsc                       107.01 M
    staking                   371.55 k
    
    total                    322.49 M

**Review by g1nt0ki — APPROVED** [review]

**Pull request merged**
