### PR TITLE
fixed the minor issue in Gaj

### PR DESCRIPTION
**Pull request by Gajesh2007**

### CODE REVIEW

**Comment by 0xngmi** [comment]
what this PR does is just move tokens from staking into core tvl, is that correct?

**Comment by Gajesh2007** [comment]
correct

**Comment by 0xngmi** [comment]
I'd rather count staking and pool2 separately since that's the methodology we are using for all other projects

**Comment by Gajesh2007** [comment]
Oh. Sure

Is it possible to separate NFT Farm and Jungle Pools and add it in Core TVL

Rewards for Jungle Pools are in DAI

Rewards for NFT farm are in Points

**Comment by Gajesh2007** [comment]
Actually, just want to keep some TVL in core as Coingecko doesn't add Staking in the TVL

**Comment by 0xngmi** [comment]
we can include into core tvl any coins staked that are not
- GAJ
- an LP pool against GAJ

**Comment by Gajesh2007** [comment]
👍🏻

**Comment by 0xngmi** [comment]
Closing, replaced by #564

**Pull request closed without merging**
