### PR TITLE
add BOB chain btc, eth market & BOB chain config

### PR DESCRIPTION
**Pull request by ShoebillFinance**
Hi team

We added New 2 Market (BTC, ETH) on BOB chain.

It looks defillama does not support BOB chain because they just opened their mainnet.

so i added but not sure this is correct way,. :(

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/shoebillFinance-v2 exports TVL: 
        
 
 
    manta                     19.27 M
    borrowed                  2.60 M
    metis                     1.89 M
    manta-borrowed            1.70 M
    wemix-borrowed            455.75 k
    metis-borrowed            404.14 k
    mode                      158.92 k
    bsquared                  116.00 k
    mode-borrowed             39.44 k
    wemix                     23.73 k
    klaytn                    1.85 k
    klaytn-borrowed           369
    bob-borrowed              0
    bsquared-borrowed         0
    bob                       0
    
    total                    21.46 M

**Comment by g1nt0ki** [comment]
@ShoebillFinance thanks for the PR

**Comment by llamatester** [comment]
The adapter at projects/dyorswap exports TVL: 
        
 
 
    blast                     924.32 k
    mode                      36.81 k
    zeta                      30.32 k
    bob                       28.94 k
    degen                     20.04 k
    xlayer                    13.23 k
    merlin                    10.13 k
    
    total                    1.06 M

**Comment by llamatester** [comment]
The adapter at projects/icecreamswap exports TVL: 
        
 
 
    core                      599.98 k
    neon_evm                  13.89 k
    xdc                       7.24 k
    blast                     5.20 k
    telos                     3.29 k
    shimmer_evm               1.74 k
    base                      1.36 k
    dogechain                 1.14 k
    bitgert                   830
    scroll                    551
    bob                       237
    fuse                      0
    
    total                    635.44 k

**Comment by llamatester** [comment]
The adapter at projects/lineabank exports TVL: 
        
 
 
    manta                     95.33 M
    borrowed                  47.94 M
    bsquared                  45.89 M
    zklink                    42.71 M
    zklink-borrowed           26.15 M
    mode                      12.69 M
    mode-borrowed             12.51 M
    scroll                    6.94 M
    manta-borrowed            3.39 M
    scroll-borrowed           3.03 M
    bsquared-borrowed         2.34 M
    linea                     2.15 M
    bob                       755.43 k
    linea-borrowed            519.81 k
    bob-borrowed              0
    
    total                    206.48 M

**Comment by llamatester** [comment]
The adapter at projects/segment-finance exports TVL: 
        
 
 
    borrowed                  1.63 M
    bsc-borrowed              1.63 M
    bsc                       839.18 k
    bsc-staking               74.25 k
    staking                   74.25 k
    op_bnb                    55.32 k
    bob                       7.47 k
    op_bnb-borrowed           3.61 k
    bob-borrowed              20
    
    total                    901.97 k

**Pull request merged**
