### PR TITLE
Update Parcl Tvl

### PR DESCRIPTION
**Pull request by DMJ16**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/parcl: 
        
 
  
    
    
    Error: Invalid balance: NaN
    Truncated error stack:
        at isValidNumber (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:119:19)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:319:16
        at Array.forEach (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:313:28)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:326:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:54:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
The adapter at projects/parcl exports TVL: 
        
 
 
    solana                    995.83 k
    
    total                    995.83 k

**Comment by g1nt0ki** [comment]
@DMJ16 thanks for the PR, I refactored it here so vault list is pulled: https://github.com/DefiLlama/DefiLlama-Adapters/pull/5812/commits/67e0752e00fa5acff9c62ce6ed566e77d9ca9ca4

https://github.com/DefiLlama/DefiLlama-Adapters/pull/5812

**Comment by g1nt0ki** [comment]
can you verify that I have not introduced any bugs?

**Pull request closed without merging**
