### PR TITLE
Feat/adapter Gardens

### PR DESCRIPTION
**Pull request by kamikazebr**
##### Twitter Link:
https://twitter.com/gardensdao

##### Website Link:
https://gardensdao.eth.limo/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
garden_logo_3

gardens_logo

##### Current TVL:
6.95M
image

##### Chain:
XDAI (Gnosis Chain)

##### Short Description (to be shown on DefiLlama):
Gardens is a framework for composable, sufficiently decentralized, and self-improving DAOs

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Services

##### methodology (what is being counted as tvl, how is tvl being calculated):
Uses Gardens and Honeyswap Subgraph to finds USD value of Common Pool treasuries for tokens with greater than $10k of liquidity on Honeyswap

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/gardens exports TVL: 
        
 
 
    xdai                      6.87 M
    
    total                    6.87 M

**Comment by g1nt0ki** [comment]
Hi, I am still going through the adapter file, but for now can you please revert the changes to package.json and lock file? 
We used to have dayjs, here is a sample of what I used instead: https://github.com/DefiLlama/DefiLlama-Adapters/commit/3e36ea5d9255cd31138151cc75a139bbae7798bd

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
package lock file is messed up

**Comment by g1nt0ki** [comment]
Hi @kamikazebr , I refactored your code a little bit, I think the easiest way forward is, with a new PR where you cope paste the description from here and use the below code, would that work for you?

    const { request, gql } = require("graphql-request");
    const sdk = require('@defillama/sdk')

    const SUBGRAPH_HONEYSWAP_V2 =
      "https://api.thegraph.com/subgraphs/name/1hive/honeyswap-v2";
    const SUBGRAPH_GARDENS_XDAI =
      "https://api.thegraph.com/subgraphs/name/1hive/gardens-xdai";


    const balanceAbi = {
      "constant": true,
      "inputs": [
        { "internalType": "address", "name": "_token", "type": "address" }
      ],
      "name": "balance",
      "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
      "payable": false,
      "stateMutability": "view",
      "type": "function"
    }


    const ALL_ORGS_GQL = gql`
      query allOrgs($lastID: ID) {
        organizations(first: 1000, where: { id_gt: $lastID, active: true }) {
          id
          token {
            name
            id
          }
          config {
            conviction {
              requestToken {
                id
                name
              }
              fundsManager
            }
          }
          proposalCount
          active
        }
      }
    `;

    const ALL_TOKEN_PRICE_QUERY = gql`
      query pricesTokens($tokenAddress: [ID]) {
        tokens(where: { id_in: $tokenAddress }) {
          id
          derivedETH
          tradeVolume
          tradeVolumeUSD
          untrackedVolumeUSD
          totalLiquidity
        }
      }
    `;

    async function getAllOrgs() {
      let allFound = false;
      let lastID = "";
      let data = [];

      while (!allFound) {
        const orgs = await request(
          SUBGRAPH_GARDENS_XDAI,
          ALL_ORGS_GQL,
          { lastID }
        );

        const numOrgs = orgs.organizations.length;

        if (numOrgs < 1000) {
          allFound = true;
        }
        lastID = orgs.organizations[numOrgs - 1].id;
        data = data.concat(orgs.organizations);
      }
      return data;
    }

    const chain = 'xdai'

    async function tvl(timestamp, _block, { xdai: block }) {
      const balances = {};

      const orgs = await getAllOrgs()
      const calls = orgs.map(org => {
        return { params: org.config.conviction?.requestToken.id, target: org.config.conviction?.fundsManager, }
      }).filter(i => i.params && i.target)

      const { output } = await sdk.api.abi.multiCall({
        abi: balanceAbi,
        calls, chain, block,
      })

      output.forEach(({ input, output }) => {
        sdk.util.sumSingleBalance(balances, input.params[0].toLowerCase(), output)
      })

      const tokens = Object.keys(balances)
      const calls2 = tokens.map(i => ({ target: i }))

      const { output: decimals } = await sdk.api.abi.multiCall({
        abi: 'erc20:decimals',
        calls: calls2,
        chain, block,
      })

      decimals.forEach(({ input: { target: token }, output: decimal }) => {
        balances[token] /= 10 ** +decimal
      })

      const tokenPrices = await request(
        SUBGRAPH_HONEYSWAP_V2,
        ALL_TOKEN_PRICE_QUERY,
        { tokenAddress: tokens }
      )

      let tvl = 0

      tokenPrices.tokens.forEach(({ id, totalLiquidity, derivedETH }) => {
        if (+totalLiquidity < 1e4 || !balances[id] || !derivedETH) // if liquidity is below 10k or token not found or price is missing, ignore and move on
          return;
        tvl += +balances[id] * +derivedETH
      })

      return {
        tether: tvl
      }
    }

    module.exports = {
      methodology:
        '"Uses Gardens and Honeyswap Subgraph to finds USD value of Common Pool treasuries for tokens with greater than $10k of liquidity on Honeyswap"',
      misrepresentedTokens: true,
      xdai: {
        tvl,
      },
    };

**Comment by kamikazebr** [comment]
> Hi, I am still going through the adapter file, but for now can you please revert the changes to package.json and lock file? We used to have dayjs, here is a sample of what I used instead: [3e36ea5](https://github.com/DefiLlama/DefiLlama-Adapters/commit/3e36ea5d9255cd31138151cc75a139bbae7798bd)

Weird, when i rebased and push forced in my repo the package.json and lock was fine. I deleted my own and get all updates from main and run yarn install again, so i get that package.lock that way.

Part the code calculations of time i just copy paste from Honeyswap to keep it consistenty, so its use dayjs utc plugin. I could refactor that, but also i think better approach its create one subgraph to do all that things and DefiLlama adapters only fetchs that.

With that info in mind, i'm still need revert package json? I'll require refactor to not use utc()?

And thank very much!! <3

**Comment by kamikazebr** [comment]
> e below code, would that work for you?

Looks awesome!!!
The first edition i tried use the sdk, but i choose the hard to way to make it works first and was in mind to change to sdk (because the multicall more efficient) and to subgraph later on.

I'll test, but looking very good. Maybe have advances tricks there for others give maintence, but looks good for me.

Thanks very much again @g1nt0ki for the effort, review and improvements! <3

**Comment by g1nt0ki** [comment]
> > e below code, would that work for you?
> 
> Looks awesome!!! The first edition i tried use the sdk, but i choose the hard to way to make it works first and was in mind to change to sdk (because the multicall more efficient) and to subgraph later on.
> 
> I'll test, but looking very good. Maybe have advances tricks there for others give maintence, but looks good for me.
> 
> Thanks very much again @g1nt0ki for the effort, review and improvements! <3

@kamikazebr you code is good, only bug might be assuming decimals is always 18, but reasonable if they are all generated from same contract? 

honestly, I am starting to dislike graph, when I started out, I thought they were awesome because it removed a burden, but these days when an adapter breaks it is usually broken api/graph down/outdated, thats why I tried to reduce the dependency from 3 graphs to 2. Is there a way to get rid of graphs? for prices it might be tricky (possible if one side of LP is fixed token and we always use the same router)? but for fetching org data, is it possible?

**Comment by kamikazebr** [comment]
> > > e below code, would that work for you?
> > 
> > 
> > Looks awesome!!! The first edition i tried use the sdk, but i choose the hard to way to make it works first and was in mind to change to sdk (because the multicall more efficient) and to subgraph later on.
> > I'll test, but looking very good. Maybe have advances tricks there for others give maintence, but looks good for me.
> > Thanks very much again @g1nt0ki for the effort, review and improvements! <3
> 
> @kamikazebr you code is good, only bug might be assuming decimals is always 18, but reasonable if they are all generated from same contract?
> 
> honestly, I am starting to dislike graph, when I started out, I thought they were awesome because it removed a burden, but these days when an adapter breaks it is usually broken api/graph down/outdated, thats why I tried to reduce the dependency from 3 graphs to 2. Is there a way to get rid of graphs? for prices it might be tricky (possible if one side of LP is fixed token and we always use the same router)? but for fetching org data, is it possible?

Yeah all contracts use 18 decimals. But should wise take that into to threat the correct decimals.

Yeah the graph have been getting some problems, i think with the migration to Graph Network that will get more stability. I really like the graphs idea, but if it not working properly here i can think how to not use that.

I not builded the core contracts and stuffs around that and they are kinda complex. But as far i understand the project each Organization have your own LP created. So what you is saying is possible i get the prices direct from LP contracts to avoid talk with graphs? I'll need research on that, but i not sure if the team will agree spend time on that, i'll need be check.

**Comment by g1nt0ki** [comment]
I understand, for now, lets go with the graph. Can you put up a new PR?

**Comment by kamikazebr** [comment]
> I understand, for now, lets go with the graph. Can you put up a new PR?

Sorry. I misunderstood something. Why need PR? With what content?

I'm confuse now hehe

**Comment by g1nt0ki** [comment]
> > I understand, for now, lets go with the graph. Can you put up a new PR?
> 
> Sorry. I misunderstood something. Why need new PR? With what content?
> 
> I'm confuse now hehe

you could keep the adapter as it is or use the code I pasted in the comments. But in this PR, the package-lock file is wrong/uses older npm version and that would cause issues for us hence I cant merge it.

**Comment by g1nt0ki** [comment]
closing this in favor of https://github.com/DefiLlama/DefiLlama-Adapters/pull/3064

**Pull request closed without merging**
