### PR TITLE
[bwatch] add bwatch adapter

### PR DESCRIPTION
**Pull request by lyricat**
##### Twitter Link: 

No twitter account

##### List of audit links if any:

None

##### Website Link:

https://b.watch

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

512-bw-mtg-ri

##### Current TVL:

$244.35M

##### Chain:

Mixin Network: https://mixin.one/

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

None

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

None

##### Short Description (to be shown on DefiLlama):

B.watch is an decentralized ETF-like crypto asset management platform, which is the only issuer of BOX token.

##### Token address and ticker if any:

None

##### Category (full list at https://defillama.com/categories) *Please choose only one:

[Services](https://defillama.com/protocols/Services)

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

None

##### forkedFrom (Does your project originate from another project):

None

##### methodology (what is being counted as tvl, how is tvl being calculated):

Add all etfs' tvl together.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bwatch exports TVL: 
        
 
 
    
    total                    245.11 M

**Comment by waynebruce0x** [comment]
Is there any way we can verify the API response? What are the contract addresses for the ETF holdings?

**Comment by lyricat** [comment]
> Is there any way we can verify the API response? What are the contract addresses for the ETF holdings?

at present, Mixin Network MTG doesn't support contract. FYI: https://developers.mixin.one/docs/mainnet/mtg

however,  Mixin Team is working on MVM (an EVM compatible VM): https://developers.mixin.one/docs/mainnet/mvm/setup#5-invoke-contract-through-mvm. When MVM is ready, I can ask b.watch to provide a contract to verify all data

**Comment by lyricat** [comment]
> How does the ETF track the vault of the 'holdings' do you know? Where are the holdings?

According to b.watch's explanation, they're using MTG framework to manage the assets. 

b.watch's MTG is a multisig asset management mechanism. There are 5 nodes manage all assets by a 4/5 multisig.

All nodes are signers which is regular Mixin Network users. You can see their uuid from https://mtg-api.b.watch/api/info and read their info by API https://developers.mixin.one/docs/api/users/user

**Pull request merged**
