### PR TITLE
feat: add phuture ethereum tvl

### PR DESCRIPTION
**Pull request by olivermehr**
##### List of audit links if any:
https://www.certik.com/projects/phuture

##### Website Link: 
https://www.phuture.finance

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

Discourse logo round

##### Chain:
Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
phuture

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
phuture

##### Short Description (to be shown on DefiLlama):
Phuture is a decentralised crypto index platform that simplifies investments through automated, themed index funds on Ethereum.

##### Token address and ticker if any:
0xE1Fc4455f62a6E89476f1072530C20CF1A0622dA - PHTR

##### Category (full list at https://defillama.com/categories) *Please choose only one:
indexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
We support Chainlink and TWAP oracles. Our indices currently only use Chainlink oracles

##### forkedFrom (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated):
We attributing the assets held within our index funds as tvl

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/phuture exports TVL: 
        
 
 
    ethereum                  139.97 k
    
    total                    139.97 k

**Comment by waynebruce0x** [comment]
Can this be calculated using onchain calls instead? We get trouble with subgraph when it falls behind current block

**Comment by jn-lp** [comment]
@llamatester @waynebruce0x fixed! please, have a check

**Comment by llamatester** [comment]
The adapter at projects/phuture exports TVL: 
        
 
 
    ethereum                  156.73 k
    
    total                    156.73 k

**Pull request merged**
