### PR TITLE
Add TVL and Treasury of Wand Protocol

### PR DESCRIPTION
**Pull request by wandbuild**
##### Name (to be shown on DefiLlama):

Wand Protocol

##### Twitter Link:

https://twitter.com/WandProtocol

##### Website Link:

https://wand.fi

##### Logo (High resolution, will be shown with rounded borders):

https://twitter.com/WandProtocol/photo

##### Current TVL:

--- blast ---
ETH                       36.46 k
Total: 36.46 k

--- tvl ---
ETH                       36.46 k
Total: 36.46 k

------ TVL ------
blast                     36.46 k

total                    36.46 k

##### Treasury Addresses (if the protocol has treasury)

0x462bd2d3c020f6986c98160bc4e189954f49634b

##### Chain:

Blast

##### Short Description (to be shown on DefiLlama):

A Structured Protocol for Better Asset Utilization

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Lending

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):

Redstone

##### Implementation Details: Briefly describe how the oracle is integrated into your project:

We are using Redstone's classic model price feed for $ETH in chainlink-compatible manner.

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:

https://docs.redstone.finance/docs/smart-contract-devs/price-feeds

##### Github org/user (Optional, if your code is open source, we can track activity):

https://github.com/wandfi/wand-contract-blast

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/treasury/wand.js exports TVL: 
        
 
 
    blast                     3.4219220890211552
    
    total                    3.4219220890211552

**Comment by llamatester** [comment]
The adapter at projects/wand exports TVL: 
        
 
 
    blast                     36.40 k
    
    total                    36.40 k

**Comment by g1nt0ki** [comment]
@wandbuild thanks for the PR

**Comment by wandbuild** [comment]
> @wandbuild thanks for the PR

Thanks for merging. I see Wand TVL is already displayed on: https://defillama.com/protocol/wand-protocol

But I didn't see **treasury** information displayed. Did I miss something in the PR?

**Comment by g1nt0ki** [comment]
maybe there is bit of a delay, check now 
image

**Pull request merged**
