### PR TITLE
Add Mint.club TVL tracker

### PR DESCRIPTION
**Pull request by sydneyitguy**
##### Twitter Link:
https://twitter.com/MintClubPro

##### List of audit links if any:
https://github.com/Steemhunt/mint.club-contract/tree/main/audits

##### Website Link:
https://mint.club/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://mint.club/android-chrome-512x512.png

##### Current TVL:
$401,149

##### Chain:
BSC

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
mint-club

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
10977

##### Description/bio (to be shown on DefiLlama):
Mint Club is a smart token building platform that has no need to code and provides instant liquidity. Anyone can launch a smart token with just a few simple clicks.

##### Token address and ticker if any:
MINT

##### Category (Yield/Dexes/Lending/Minting):
Minting

##### [Optional] ETH address (to receive a LlamaPunk):
0x3035DEE64c8dBe813a464a0263CE0C365C454d54

### CODE REVIEW

**Comment by sydneyitguy** [comment]
Test script `npx @defillama/sdk projects/mint-club/index.js` returns following results:

```
Couldn't query decimals() for token UNKNOWN (0x1f3Af095CDa17d63cad238358837321e95FC5915) (0x1f3Af095CDa17d63cad238358837321e95FC5915) so we'll ignore and assume it's amount is 0
Couldn't find the price of token at 0x1f3Af095CDa17d63cad238358837321e95FC5915, assuming a price of 0 for it...
UNKNOWN (0x1f3Af095CDa17d63cad238358837321e95FC5915) 0
Total: 0
```

Is there a way we can register MINT token as "KNOWN" status?
Price data can be retrieved from 
1. Coin Market Cap - https://coinmarketcap.com/currencies/mint-club/
2. OR from Pancakeswap BNB/MINT pair directly

**Comment by 0xngmi** [comment]
> Can't find the price of mint

Right now we are pulling all pricing data from coingecko, I'll merge this and apply the changes to price the token using pancakeswap

**Comment by sydneyitguy** [comment]
@0xngmi Thanks for your help!
BTW, the token is listed on Coingecko now as well: https://www.coingecko.com/en/coins/mint-club#markets

**Comment by sydneyitguy** [comment]
@0xngmi I saw it's on DefiLlama now: https://defillama.com/protocol/mint-club
but it seems the price doesn't get fetched properly: 
image

Could you have a look? Its CoinGecko ID is: `mint-club`
https://www.coingecko.com/en/coins/mint-club#markets

**Comment by 0xngmi** [comment]
The problem was that the adapter was using the ethereum address and coingecko has the binance one, so it couldn't find it. I've just fixed it

**Comment by sydneyitguy** [comment]
@0xngmi sorry for tagging again, but it seems it still doesn't get the price correctly:
image

Hasn't the fix get merged yet?

**Comment by 0xngmi** [comment]
I merged it in 537acbb4a316c42b4527caec9f50acc2efeda250 but will check everything since the TVL is clearly wrong

**Comment by 0xngmi** [comment]
Should be working fine now, will fix the old data since it's wrong

**Comment by sydneyitguy** [comment]
Looks great! It's working perfectly now. Thanks for your help :)

**Comment by realdealshaman** [comment]
Hey, thank you for contributing to Defillama! Your LlamaPunk has been sent: https://opensea.io/0x3035dee64c8dbe813a464a0263ce0c365c454d54

**Pull request merged**
