### PR TITLE
Added Aqualoan

### PR DESCRIPTION
**Pull request by techaqualoan**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
AQUA

##### Twitter Link:
https://x.com/aqualoan

##### List of audit links if any:
https://github.com/techaqualoan/audits/blob/main/aqualoan_blocksec_audit.pdf
https://github.com/techaqualoan/audits/blob/main/aqua_token_blocksec_audit.pdf

##### Website Link:
https://aqualoan.org

##### Logo (High resolution, will be shown with rounded borders):
https://ik.imagekit.io/cykpetgtn/logo.png

##### Current TVL:
$73.25

##### Treasury Addresses (if the protocol has treasury)
0x918737Bd3fDCDDb2ae30De41e3e89806fC8228bf

##### Chain:
Binance Smart Chain

##### Short Description (to be shown on DefiLlama):
In the fast-paced world of decentralized finance (DeFi), innovation is the driving force behind the success of any ecosystem. As the DeFi landscape continues evolving, we proudly announce Aqualoan, an innovation-driven, decentralized and non-custodial liquidity market.
Aqualoan is an open-source platform designed to create non-custodial liquidity markets, offering variable interest rates on supplied and borrowed assets.
Lendle aims to bring a new level of innovation to the lending and borrowing experience by creating new and exciting features on top of existing lending paradigms.
Liquidity providers earn passive income, with borrowers able to take out loans that are either perpetually overcollateralized or undercollateralized for one-block liquidity.
The Aqualoan protocol distributes fees between the Aqualoan DAO and those who mitigate the protocol's risk in the Safety Module by staking the native token, AQUA.

##### Token address and ticker if any:
0xD1Fb55d61c2494ced556536F898D969e2F6Dd2Bf, AQUA

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/techaqualoan

### CODE REVIEW

**Comment by techaqualoan** [comment]
added Aqualoan

**Comment by llamatester** [comment]
Error while running adapter at projects/aqualoan: 
        
 
  
    
    
    Error: Multicall is missing a target
    Truncated error stack:
        at Object.multiCall (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/abi/index.js:199:19)
        at fetchReserveData (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/aqualoan/index.js:12:35)
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/aqualoan/index.js:38:19)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:29)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:173:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:161:29
        at Array.map (<anonymous>)
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
The adapter at projects/aqualoan exports TVL: 
        
 
 
    bsc                       67
    bsc-borrowed              1
    borrowed                  1
    
    total                    67.4606326098994

**Comment by techaqualoan** [comment]
updated correct address

**Comment by techaqualoan** [comment]
Dear Defilama team!
Would you kindly check and merge?

**Comment by g1nt0ki** [comment]
thanks for the PR

**Pull request merged**
