### PR TITLE
refactoring: use built in functions and prices

### PR DESCRIPTION
**Pull request by ivivanov**
Refactoring the code and start using builtin funcs: sdk.util.sumSingleBalance, transformBalances
This way we are using the default DefiLlama prices and denoms

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/nolus exports TVL: 
        
 
 
    nolus                     576.26 k
    neutron                   748.48 k
    osmosis                   3.36 M
    
    total                    4.68 M

**Comment by ivivanov** [comment]
image
@g1nt0ki any clues why those denoms are reported as Unrecognized when running the tests locally?

**Comment by waynebruce0x** [comment]
Do you know what these assets are? Can you paste the addresses here for me?

**Comment by ivivanov** [comment]
@waynebruce0x sure!
So those are assets on Osmosis Dex:
"Q_ATOM": "ibc/FA602364BEC305A696CBDF987058E99D8B479F0318E47314C49173E8838C5BAC",
"MILK_TIA": "factory/osmo1f5vfcph2dvfeqcqkhetwv75fda69z7e5c2dldm3kvgj23crkv6wqcn47a0/umilkTIA",
"ST_TIA": "ibc/698350B8A61D575025F3ED13E9AC9C0F45C89DEFE92F76D5838F1D3C1A7FF7C9",

For example we are also using ST_TIA on Neutron(Astroport) and everything works fine ("ST_TIA": "ibc/6569E05DEE32B339D9286A52BE33DFCEFC97267F23EF9CFDE0C055140967A9A5")

**Comment by ivivanov** [comment]
Both qAtom and stTia have 6 decimals. Thanks!

**Pull request merged**
