### PR TITLE
add wepiggy

### PR DESCRIPTION
**Pull request by wepiggy-dev**
#### Why are you creating this pull request?
We want to be listed on DefiLlama

##### Twitter Link:
https://twitter.com/wepiggydotcom

##### List of audit if any:
https://github.com/WePiggy/wepiggy-contracts/tree/master/docs/audits

##### Website Link:
https://wepiggy.com/

##### Contact Email:
contact@wepiggy.com

##### Expected TVL:
$Thirty million dollars

##### Chain:
Ethereum mainnet
OKExChain (launch soon) 
##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
https://coinmarketcap.com/exchanges/wepiggy/

##### Description/bio (to be shown on DefiLlama):
WePiggy is an open source, non-custodial crypto asset lending market protocol.
In Wepiggy's market, users can deposit their crypto assets to earn interest, or borrow others by paying interests.

##### Token address and ticker if any:
WePiggyToken : 0x4C78015679FabE22F6e02Ce8102AFbF7d93794eA
FundingHolder[InsurancePayment] : 0xb205d0AeF84C666FBBe441C61DC04fEb844444E6
FundingHolder[ResourceExpansion] : 0x7a603D06007fc09f896Fb75644365AB091A7b91a
FundingHolder[TeamVote] : 0x8C14A40c488E16b055bc4e250563B5480047f01E
FundingHolder[TeamSpending] : 0x209EE6f924a39BdDC9A57c0E263dd5E29CEAc78A
FundingHolder[CommunityRewards] : 0x1fe0F15546858d9A1E84CE2E7908b160608267c5
FundingManager : 0xf18D727C034f47AE2C0FE221C1cf4A15f0557b5F
PiggyBreeder : 0x451032C55F813338b6e73c1c4B24217614165454
Timelock : 0x311aEA58Ca127B955890647413846E351df32554
WPC_AIRDROP_FUNDING_MANAGER: 0x2dd8FFA7923a17739F70C34759Af7650e44EA3BE
WP_PRICE_PROVIDER_V1=0xe212829Ca055eD63279753971672c693C6C6d088
WE_PIGGY_PRICE_ORACLE_V1=0xE4A1E73157EB4b58b1347E2BE2df7ac83467b288
COMPTROLLER=0x0C8c1ab017c3C0c8A48dD9F1DB2F59022D190f0b
STABLECOIN_JUMP_RATE_MODEL=0x8158B34fF8A36dD9E4519d62C52913C24ad5554b
BTC_ETH_JUMP_RATE_MODEL=0xA0a75821220bfC74f8012d5D5745FE472F510075
MAINSTREAM_JUMP_RATE_MODEL=0x678C86dBD6965D65Bf74b73d75b615A37428a87d
P_DAI=0x85166b72c87697a6acfF24101B43Fd54fE28a179
P_USDT=0x5cFad792C4Df1323188180778AeC58E00eAcE32a
P_USDC=0xf8E5b9738BF63ADFFf36a849F9b9C9617c8D8c1f
P_WBTC=0xc12B9D620bFCB48be3e0CCbf0ea80C717333b46F
P_ETH=0x27A94869341838D5783368a8503FdA5fbCd7987c
P_UNI=0x82413f75f0DA101e0FE7F6FF6cBa3461F7e04f29
P_YFII=0x82dE3959c09f665a82C794fAfC1eb34CFCb555Ee
MAX_IMILLION=0x97F3763F8C0bE87Cab0e99Ee4b7806acA772FeDA
PIGGY_DISTRIBUTION=0x3e5496E50793E72e6143a15Bed1c2535F0B0b9b0

##### Category (Yield/Dexes/Lending/Minting):
Lending

### CODE REVIEW

**Comment by 0xngmi** [comment]
A few questions:
- On your twitter there's [a pinned message saying that the token hasn't been released yet](https://twitter.com/wepiggydotcom/status/1324290795055144961), is that outdated?
- I've also checked the funds locked in your P-contracts and PiggyBreeder, which account for around 22M$. Could you please let us know what other contracts hold funds?
- The url you provided to fetch TVL seems to be down for me.

**Comment by wepiggy-dev** [comment]
Hi @0xngmi !
1. This information is valid. At present, WePiggy's platform token WPC is in the blind mining stage. The tokens will be unlocked when release, we will notify you in advance. 
2. WePiggy's funds are locked in pcontracts and piggyBreeder, no other contracts. Fork from Compound, the interface uses the number of deposits which is cash and does not include the amount of borrowings.|
3.Check with the technicians that the url is available, you can try again, please tell me if it still doesn't work 
Thx~

**Comment by 0xngmi** [comment]
Thanks for answering! We are currently in the process of moving our scripts to be web3-based (a problem with fetching data from endpoints is that we cannot fill information from previous blocks, so the graph ends up going from 0 to the current TVL). I've also noticed that you have submitted a PR to defipulse with a web3 script. Would you be okay with me copying that same logic to use over here?

**Comment by wepiggy-dev** [comment]
Thanks for ur reply
We want to confirm the question about ur moving to web3. Is the web3 available at the moment?
Also about the interface, do we need to copy it or do you copy it?
You can send us the details of what we need to do, thank you :)

**Comment by 0xngmi** [comment]
I believe the easiest path would be for me to create a PR porting your adapter and then you could review it.

**Comment by 0xngmi** [comment]
Just made PR #67, using the script that you submitted to defipulse. Could you review it and let me know if it's all okay or if there's something that needs to be added?

**Comment by wepiggy-dev** [comment]
Hi @0xngmi , we tested the RR67 and found it could not work
We have modified and updated PR59 based on requirements, you can check if it's ok?
Thx~
Let me know if there's something that needs

**Comment by 0xngmi** [comment]
Thanks! The new adapter is perfect, I'll merge and we'll soon list it on defillama

**Pull request merged**
