### PR TITLE
feat: add tezos's cdp kolibri

### PR DESCRIPTION
**Pull request by iiAku**
**NOTE**

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### methodology (what is being counted as tvl, how is tvl being calculated):

### CODE REVIEW

**Comment by 0xStrobe** [comment]
Hi, @iiAku. Thanks for the PR.

I am not able to verify it to be working via `ts-node ./liquidations/test.ts ./liquidations/kolibri/index.ts`. I'm getting a 414 error.

```
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "AxiosError: Request failed with status code 414".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

**Comment by iiAku** [comment]
Hi @0xStrobe,
Thanks for the fix invocation.
So I had a look and it looks like it was failing there:
https://github.com/DefiLlama/DefiLlama-Adapters/blob/1c0c3dbfa2bb28f109d62402165833e5e97b881b/liquidations/utils/binResults.ts#L19

Because generated url was too long as I was passing `tezos:owneraddress`, but this does not work and further down the road we do not get prices from this. So i'm now passing `tezos:coingecko` to get xtz price for all ovens, and it now works.

**Comment by 0xStrobe** [comment]
Thanks for the fix, is the `collateralAmount` returned in 6 decimal places?

**Comment by iiAku** [comment]
> Thanks for the fix, is the `collateralAmount` returned in 6 decimal places?

Yes if we are talking about the same thing:
`HumanReadableAmount = collateralAmount.div(1e6)`

**Comment by 0xStrobe** [comment]
Thanks for the PR, merged and will be enabled on frontend soon.

**Pull request merged**
