### PR TITLE
Barnbridge

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/barnbridge exports TVL: 
        
 
 
    arbitrum                  0
    optimism                  725.74 k
    ethereum                  344.36 k
    
    total                    1.07 M

**Comment by llamatester** [comment]
The adapter at projects/barnbridge exports TVL: 
        
 
 
    arbitrum                  0
    optimism                  725.74 k
    ethereum                  344.26 k
    
    total                    1.07 M

**Comment by albertoramires** [comment]
@g1nt0ki the TVL values don't seem to match, seems too big of a difference to be DAI/USDC fluctuations: https://app.barnbridge.com/fixed-yield/pools/

**Comment by g1nt0ki** [comment]
I noticed that too, but looked at the providers and they had equivalent value, these include yields ? https://etherscan.io/address/0x7ac6859e69d6549b39a8367097d7ae5fbff5951e#tokentxns

**Pull request merged**
