### PR TITLE
Update Nexus Mutual pools and assets

### PR DESCRIPTION
**Pull request by horodnicdragos**

### CODE REVIEW

**Comment by 0xngmi** [comment]
Why remove the old pools?

**Comment by roxdanila** [comment]
We're upgrading the pool to a new version and all assets will move over. The upgrade happens in ~30 mins.

**Comment by 0xngmi** [comment]
Okay, that explains why right now the adapter is reporting 0 TVL

**Comment by 0xngmi** [comment]
Seems to be working now, are you seeing any incorrect data?

**Pull request merged**
