### PR TITLE
Add Bunicorn exchange

### PR DESCRIPTION
**Pull request by Buni-HungNguyenThanh**
##### List of audit links if any:
First round completed on May 3, 2021: https://bit.ly/3eqRAPQ
Second round completed on June 11, 2021: https://bit.ly/3wkSeVn

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://buni.finance/assets/logo_on_white_background.png
https://buni.finance/assets/logo_on_balack_background.png

##### Description/bio (to be shown on DefiLlama):
Description: Bunicorn is a highly performed AMM DEX that offers investors yield-earning opportunities through liquidity pools and liquidity farm mining with unique time-locked rewards wrapped into tradable NFTs. 
We aim to address the post-DeFi liquidity crisis through NFT vesting and turn the yield farming rewards into unique NFT collectibles that bring long-term value to both the community and project itself. And the vision is powered by two prominent advance features:
- Pools with the most current optimized AMM models: Balancer-style liquidity bootstrapping pools (LBP) and Kyber-style Amplified pools, Bunicorn ensures the capital efficiency and fair token distribution to prevent bots from front-running. 
- Unique BUNI NFT collectibles generated from yield farming will be backed by a genuinely fantastic game storyline introduced by the Bunicorn team.
Bunicorn is currently built on the Binance Smart Chain (BSC) and plans to expand on multiple chains such as Polkadot, ETH layer 2 and more in the future.

### CODE REVIEW

**Comment by 0xngmi** [comment]
A minor problem with the current code is that the block height is not used. This is a problem because if the subgraph starts lagging we won't be able to detect it

**Comment by 0xngmi** [comment]
Out of curiosity, why did you change from the graph to your own solution?

**Comment by Buni-HungNguyenThanh** [comment]
@0xngmi  
I just edited according to your feedback.
In this latest commit, I fixed the subgraph url because the old subgraph is crashing and can not update the latest data. 
Therefore we have to use fallback subgraph for the time being.

**Comment by 0xngmi** [comment]
I see, is it because it cannot stay up-to-date due to the speed of updates? I've seen that happen with multiple subgraphs on bsc

**Comment by Buni-HungNguyenThanh** [comment]
An exception about RPC was thrown and my subgraph can't syncing data latest :(

**Comment by 0xngmi** [comment]
Got it

**Pull request merged**
