### PR TITLE
added pinjam project

### PR DESCRIPTION
**Pull request by PinjamLabs**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Short Description (to be shown on DefiLlama):
Pinjam is a non-custodial liquidity market by with the unique innovation of achieving 100% capital efficiency by putting unborrowed funds to work.

##### Token address and ticker if any:
$PINKAV: 0xE5274E38E91b615D8822e8512a29A16FF1B9C4Af
https://explorer.kava.io/address/0xE5274E38E91b615D8822e8512a29A16FF1B9C4Af/transactions

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
https://witnet.io/

##### forkedFrom (Does your project originate from another project):
Mainly inspired by Aave on the lending protocol and tokenomics designed originated from Geist.

##### methodology (what is being counted as tvl, how is tvl being calculated):
Currently, total supply of all minted pTokens are counted as TVL.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/pinjam exports TVL: 
        
 
 
    kava-borrowed             296.0014452479513
    kava                      4.52 k
    kava-staking              0
    borrowed                  296.0014452479513
    staking                   0
    
    total                    4.52 k

**Comment by g1nt0ki** [comment]
@PinjamLabs thanks for the PR, I have refactored it a bit so it picks tokens dynamically, can you review my changes.

**Comment by llamatester** [comment]
The adapter at projects/pinjam exports TVL: 
        
 
 
    kava-staking              0
    kava-borrowed             610.8054950443188
    kava                      5.49 k
    staking                   0
    borrowed                  610.8054950443188
    
    total                    5.49 k

**Comment by PinjamLabs** [comment]
Yes, it looks good, definitely saves us the trouble of a future PR from adding more assets, appreciate the improvement! 🙏

**Pull request merged**
