### PR TITLE
Batch Protocol Updates - protocol keys renaming, missing protocols ad…

### PR DESCRIPTION
**Pull request by 0xrmvdao**
Hi, as the core developer team (or part of the team) of the following projects, we want to make some batch updates in our projects. In this way, we want to make it easy to understand the projects both for you, for our customers and for us in the next maintenance processes.

Projects included in the update: **Metavault**, **LineHub**, **Kinetix**, **SparkDEX**, **GrizzlyFi**, **Quickswap**

## Actions
|		| Description |
|-------|-------------|
| key update | protocol exist, but want to change key inside source code |
| remove | project deprecated, need to remove completely from source code |
| new sub protocol | protocol missing, need to add new protocol. adapters will commit too
| no change | no changes required. for informational purposes only

# Metavault

Parent Protocol: Metavault

|      |Existing       |Updates       | Action 
|------|---------------|-------------| -- |
|Metavault Binary Options | metavault-bo			| - | remove
|Metavault Derivatives V1 | metavault.trade         | - | remove
|Metavault Derivatives V2 | metavault-derivatives-v2 | - | no change
| Metavault AMM V2 		  | -						| metavault-amm-v2 | new sub-protocol
| Metavault AMM V3        | metavault-v3 			| metavault-amm-v3 | key update

# LineHub

Parent Protocol: LineHub

|      |Existing       |Updates       | Action 
|------|--------------|-------------| -- |
|LineHub Derivatives  | linehub-perps | linehub-derivatives | key update
| LineHub AMM V2	  | linehub-v2		| linehub-amm-v2 | key update
| LineHub AMM V3      | linehub-v3 | linehub-amm-v3 | key update

# Kinetix

Parent Protocol: Kinetix

|      |Existing       |Updates       | Action 
|------|--------------|-------------| -- |
| Kinetix Derivatives V1  | kinetix | kinetix-derivatives | key update
| Kinetix Derivatives V2  | kinetix-derivatives-v2 | - | no change
| Kinetix AMM V2	  | kinetix-v2		| kinetix-amm-v2 | key update
| Kinetix AMM V3      | kinetix-v3 | kinetix-amm-v3 | key update

# SparkDEX

Parent Protocol: SparkDEX

|      |Existing       |Updates       | Action 
|------|--------------|-------------| -- |
| SparkDEX AMM V2	  | sparkdex-v2 | sparkdex-amm-v2 | key update
| SparkDEX AMM V3     | sparkdex-v3 | sparkdex-amm-v3 | key update

# GrizzlyFi

Parent Protocol: GrizzlyFi

|      |Existing       |Updates       | Action 
|------|--------------|-------------| -- |
| GrizzlyFi Derivatives | grizzly-trade | - | remove
| GrizzlyFi Derivatives V2| grizzly-trade-derivatives-v2 | grizzlyfi-derivatives-v2 | key update
| GrizzlyFi Trade AMM	 | grizzly-trade-amm | - | remove

# Quickswap

Parent Protocol: Quickswap

|      |Existing       |Updates       | Action 
|------|--------------|-------------| -- |
| Quickswap Derivatives | quickperps | quickswap-derivatives | key update
| Quickswap Derivatives V2| - | quickswap-hydra | new sub protocol

#
**PROJECT DASHBOARDS**: We have prepared the following tables to represent the lists we would like to see in the Defillama Dashboards for the projects we develop or provide development support for.
#

### Metavault on Defillama Dashboards
| | DeFi | Volumes > Dexs | Volumes > Perps | Fees/Revenue |
--|---|--|--|--|
Metavault (Parent)| OK | - | - | - 
Metavault DAO | OK | - |- | -
Metavault AMM V2 | OK | OK | - | OK
Metavault AMM V3 | OK | OK | - | OK
Metavault Derivatives V2 | OK | - | OK | OK

### LineHub on Defillama Dashboards
| | DeFi | Volumes > Dexs | Volumes > Perps | Fees/Revenue |
--|---|--|--|--|
LineHub (Parent)| OK | - | - | - 
LineHub AMM V2 | OK | OK | - | OK
LineHub AMM V3 | OK | OK | - | OK
LineHub Derivatives | OK | - | OK | OK

###  Kinetix on Defillama Dashboards
| | DeFi | Volumes > Dexs | Volumes > Perps | Fees/Revenue |
--|---|--|--|--|
Kinetix (Parent)| OK | - | - | - 
Kinetix AMM V2 | OK | OK | - | OK
Kinetix AMM V3 | OK | OK | - | OK
Kinetix Derivatives | OK | - | OK | OK
Kinetix Derivatives V2 | OK | - | OK | OK

###  SparkDEX on Defillama Dashboards
| | DeFi | Volumes > Dexs | Volumes > Perps | Fees/Revenue |
--|---|--|--|--|
SparkDEX (Parent)| OK | - | - | - 
SparkDEX AMM V2 | OK | OK | - | OK
SparkDEX AMM V3 | OK | OK | - | OK

###  GrizzlyFi on Defillama Dashboards

_Notes_: We only provide development support to this project: **GrizzlyFi Derivatives V2**. Other projects are maintained by the core team. This change is only for GrizzlyFi Derivatives V2 protocol.

| | DeFi | Volumes > Dexs | Volumes > Perps | Fees/Revenue |
--|---|--|--|--|
GrizzlyFi (Parent)| OK | - | - | - 
GrizzlyFi Derivatives V2 | OK | - | OK | OK

###  Quickswap on Defillama Dashboards

_Notes_: We only provide development support to these two projects: **Quickswap Derivatives** and **Quickswap Hydra**. Other projects are maintained by the core team. This change is only for Quickswap Derivatives and Quickswap Hydra protocols.
 
| | DeFi | Volumes > Dexs | Volumes > Perps | Fees/Revenue |
--|---|--|--|--|
Quickswap (Parent)| OK | - | - | - 
Quickswap Derivatives | OK | - | OK | OK 
Quickswap Hydra | OK | - | OK | OK

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/kinetix-amm-v3 exports TVL: 
        
 
 
    kava                      2.27 M
    base                      1.54 k
    
    total                    2.27 M

**Comment by llamatester** [comment]
The adapter at projects/quickswap-hydra exports TVL: 
        
 
 
    manta                     989.60 k
    polygon_zkevm             69.11 k
    
    total                    1.06 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
Afraid I have reject this PR for two reasons:

* Changing key breaks our server, it would look for the file which will be missing now. This is the reason, we reject folder renaming. If you want to change listing title, it can be done here: https://github.com/0xmDreamy/defillama-server/blob/fix/update-abracadabra-chains-and-oracles/defi/src/protocols/data.ts

* We do not remove deprecated projects, again it will break our server, and if we delist, chain tvl history will be affected. What we do in these cases is, add hallmark to let users know that product is winding down.

**Comment by g1nt0ki** [comment]
Also, thanks for detailed breakdown, makes it much easier to review :)

**Comment by 0xrmvdao** [comment]
Okay thanks, it was a bit difficult to prepare this PR 😵‍💫 . What can we do for a better organization? We also added a new sub-protocols. Can you add those new protocols?

**Comment by g1nt0ki** [comment]
@0xrmvdao yeah, sorry about this. I have added the new protocols now

By better organization, you mean the folder names in this repo?

**Pull request closed without merging**
