### PR TITLE
init

### PR DESCRIPTION
**Pull request by Piorun-102**
##### Name (to be shown on DefiLlama):
DeFi Exnode

##### Twitter Link:
https://twitter.com/DefiExnode

##### Website Link:
https://defi.exnode.ru/

##### Logo (High resolution, will be shown with rounded borders):

https://dropmefiles.com/J0cy5

##### Current TVL:
137$

##### Treasury Addresses (if the protocol has treasury)
0x8f228373A399df98d54A8a9628CE76BB24bA7CAc

##### Short Description (to be shown on DefiLlama):

DeFi Exnode stands as a decentralized platform for managing assets, operating through the use of smart contracts. It presents users with a secure avenue to invest in digital assets while offering a multitude of investment strategies and portfolios to choose from.

##### methodology (what is being counted as tvl, how is tvl being calculated): 

TVL of DeFi  Exnode corresponds to the capital invested in each investment portfolio

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/defi-exnode: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading '1')
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/defi-exnode/index.js:9:33
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:68:7)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by llamatester** [comment]
The adapter at projects/defi-exnode exports TVL: 
        
 
 
    polygon                   78.26
    xdai                      0
    fantom                    2.23
    arbitrum                  0.21
    ethereum                  0
    bsc                       56.24
    optimism                  0
    avax                      0.57
    aurora                    0
    
    total                    137.51

**Comment by g1nt0ki** [comment]
@Piorun-102 thanks for the PR, but we no longer support fetch api, can you share the contract details, I can help with fix the adapter

**Comment by g1nt0ki** [comment]
@Piorun-102 we prefer computing tvl on chain, like querying the contracts and aggregating the response, we have a lot of wrapper/helper functions in our library. https://docs.llama.fi/list-your-project/functions-weve-written-so-you-dont-have-to

**Comment by Piorun-102** [comment]
> @Piorun-102 we prefer computing tvl on chain, like querying the contracts and aggregating the response, we have a lot of wrapper/helper functions in our library. https://docs.llama.fi/list-your-project/functions-weve-written-so-you-dont-have-to

tokens are stored on clients' wallets, so TVL cannot be obtained from smart contracts

**Comment by g1nt0ki** [comment]
sorry, then you have 0 tvl and we cant list you.

**Pull request closed without merging**
