### PR TITLE
Refactor GARD Adapter

### PR DESCRIPTION
**Pull request by mccabe-david**
Redoes some of the changes to Algorand helper function to count Algo. Adds detail to which tokens are in the protocol. Adds native staking.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/gard exports TVL: 
        
 
 
    algorand-staking          1.24 M
    algorand-borrowed         1.59 M
    algorand-treasury         36.62 k
    algorand                  5.68 M
    staking                   1.24 M
    borrowed                  1.59 M
    treasury                  36.62 k
    
    total                    5.68 M

**Comment by llamatester** [comment]
The adapter at projects/gard exports TVL: 
        
 
 
    algorand-staking          1.24 M
    algorand-borrowed         1.60 M
    algorand-treasury         36.71 k
    algorand                  5.71 M
    staking                   1.24 M
    borrowed                  1.60 M
    treasury                  36.71 k
    
    total                    5.71 M

**Comment by mccabe-david** [comment]
@g1nt0ki What's going on with these PRs? I just want to have the tokens counted as tvl, treasury, etc. begin tracking as soon as possible.

**Comment by mccabe-david** [comment]
I'd rather have this branch not count anything new and be merged than get reverted by someone else.

**Comment by g1nt0ki** [comment]
@mccabe-david I have included your changes in my other PR, I am trying to implement a way to refill history so when I merge my PR, it does not look like there is a sudden huge drop in tvl.

https://github.com/DefiLlama/DefiLlama-Adapters/pull/4493#issuecomment-1295924295

This is the reason why I am not merging other PRs relating to algorand. Also, like we discussed, we cant include 'borrowed' export in your protocol

**Comment by llamatester** [comment]
Error while running adapter at projects/gard: 
        
 
  
    
    
    Error: Couldn't find block height for chain algorand, RPC node rugged
    Truncated error stack:
        at Object.<anonymous> (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:177:27)

**Comment by mccabe-david** [comment]
@g1nt0ki Thanks for the quick reply! Just removed borrowed from exports.

**Comment by llamatester** [comment]
Error while running adapter at projects/gard: 
        
 
  
    
    
    Error: Couldn't find block height for chain algorand, RPC node rugged
    Truncated error stack:
        at Object.<anonymous> (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:177:27)

**Comment by g1nt0ki** [comment]
@mccabe-david closing this as I have finally merged my PR which includes your changes: https://github.com/DefiLlama/DefiLlama-Adapters/pull/4513

**Pull request closed without merging**
