### PR TITLE
implemented tvl function for arbitrove or APL token

### PR DESCRIPTION
**Pull request by deboguer-jng**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000) 
nitro-cartel 

##### Github org/user (Optional, if your code is open source, we can track activity): -

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/arbitrove exports TVL: 
        
 
 
    arbitrum                  1.29 M
    
    total                    1.29 M

**Comment by llamatester** [comment]
The adapter at projects/arbitrove exports TVL: 
        
 
 
    arbitrum                  1.29 M
    
    total                    1.29 M

**Comment by deboguer-jng** [comment]
@llamatester the tests are failing because of:
image

**Comment by llamatester** [comment]
The adapter at projects/flashstake-old exports TVL: 
        
 
 
    ethereum                  4.02 k
    
    total                    4.02 k

**Comment by llamatester** [comment]
The adapter at projects/gyroscope exports TVL: 
        
 
 
    polygon                   2.79 M
    
    total                    2.79 M

**Comment by llamatester** [comment]
The adapter at projects/sudoswap exports TVL: 
        
 
 
    ethereum                  2.45 M
    
    total                    2.45 M

**Comment by llamatester** [comment]
The adapter at projects/arbitrove exports TVL: 
        
 
 
    arbitrum                  1.31 M
    
    total                    1.31 M

**Comment by llamatester** [comment]
The adapter at projects/sablier-v2 exports TVL: 
        
 
 
    avax-vesting              0
    bsc-vesting               0
    bsc                       0.46081399741066453
    xdai                      0.39966440000000003
    optimism                  25.907453443496205
    arbitrum                  1.5981102956650002
    arbitrum-vesting          3.54
    avax                      0.600489172387
    polygon                   130.1109973796178
    xdai-vesting              28.019187
    ethereum-vesting          29.21 k
    ethereum                  9.01 k
    optimism-vesting          537.44 k
    polygon-vesting           0
    vesting                   566.69 k
    
    total                    9.17 k

**Pull request closed without merging**
