### PR TITLE
feat: add superbots tvl

### PR DESCRIPTION
**Pull request by joshua8321**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
SuperBots

##### Twitter Link:
https://twitter.com/SuperBots_Fi

##### List of audit links if any:
https://www.certik.com/projects/superbots

##### Website Link:
https://superbots.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://res.cloudinary.com/drxflpr8j/image/upload/v1664807555/superbots_csbezd.png

##### Current TVL:
620K$

##### Chain:
BSC

##### Short Description (to be shown on DefiLlama):
SuperBots offers decentralized trading solutions, via "vaults" in which users can deposit their capital and which will be traded on decentralized markets in a secure manner.

##### Token address and ticker if any:
BSC contract: 0xbbeb90cfb6fafa1f69aa130b7341089abeef5811

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Services

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Not used

##### forkedFrom (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated):
We count only deposits on vaults + the capital staked in the staking pool.

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@joshua8321 thanks for the PR, can you please export staking tvl separately, also can you compute the product tvl using on chain calls

**Comment by joshua8321** [comment]
@g1nt0ki 
Thanks for the review, I have pushed the fixes, Please check it again

**Comment by joshua8321** [comment]
@g1nt0ki 
Do you have any updates for me?
Thanks

**Comment by g1nt0ki** [comment]
sorry, I am bit buried in PRs, reviewing this now.

**Pull request merged**
