### PR TITLE
Add Ispolink project

### PR DESCRIPTION
**Pull request by mikyjo**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

- Ispolink

##### Twitter Link: 

- https://twitter.com/ispolink

##### Website Link:

- https://www.ispolink.com/

##### Logo (High resolution, will be shown with rounded borders):

- https://github.com/DefiLlama/DefiLlama-Adapters/assets/80850454/e9df9252-c659-4385-a6f6-bdf41fa18a74

##### Current TVL:

- 209k

##### Chain:

- ETH
- BNB
- Polygon
- Manta

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

- ispolink

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

- 9865

##### Short Description (to be shown on DefiLlama):

- Ispolink is a leading ecosystem of AI and Gaming products developing the Future of Work on Web3

##### Token address and ticker if any:

- Ticker: ISP
- ETH: 0xc8807f0f5ba3fa45ffbdc66928d71c5289249014
- BNB: 0xd2e7b964770fcf51df088a5f0bb2d33a3c60cccf
- Polygon: 0x1e289178612F5B6d32f692E312DcF783c74b2162
- Manta: 0xBAb1c57ec0bB0aE81d948503E51d90166459D154

##### Category (full list at https://defillama.com/categories) *Please choose only one:

- Services

##### methodology (what is being counted as tvl, how is tvl being calculated):

- We're counting the number of ISP tokens locked in the native Ispolink protocols

##### Github org/user (Optional, if your code is open source, we can track activity):

- https://github.com/ispolink

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/ispolink exports TVL: 
        
 
 
    manta                     8.64 k
    ethereum                  185.93 k
    bsc                       19.74 k
    
    total                    214.31 k

**Comment by llamatester** [comment]
The adapter at projects/ispolink exports TVL: 
        
 
 
    bsc                       20.00 k
    ethereum                  188.32 k
    manta                     8.75 k
    
    total                    217.07 k

**Comment by llamatester** [comment]
The adapter at projects/ispolink exports TVL: 
        
 
 
    ethereum                  0
    bsc                       0
    manta                     0
    manta-staking             8.74 k
    bsc-staking               19.97 k
    ethereum-staking          188.05 k
    staking                   216.76 k
    
    total                    0

**Comment by g1nt0ki** [comment]
@mikyjo thanks for the PR, refactored it as own tokens are considered staking: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by llamatester** [comment]
The adapter at projects/ispolink exports TVL: 
        
 
 
    ethereum                  0
    bsc                       0
    manta                     0
    manta-staking             8.74 k
    bsc-staking               19.97 k
    ethereum-staking          188.05 k
    staking                   216.76 k
    
    total                    0

**Comment by mikyjo** [comment]
Thanks a lot @llamatester! Appreciate that you refactored and merged my PR!

Wasn't too sure which functions to use, I was just following the llama docs.

**Pull request merged**
