### PR TITLE
makes adding collateral easier

### PR DESCRIPTION
**Pull request by 0xmidnite**
##### Current TVL:
ADDS dpx and gmx tvl, as well as making adding new collaterals easier.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/vesta exports TVL: 
        
 
 
    arbitrum-pool2            619.14 k
    arbitrum                  14.94 M
    pool2                     619.14 k
    
    total                    14.94 M

**Comment by llamatester** [comment]
The adapter at projects/vesta exports TVL: 
        
 
 
    arbitrum                  18.74 M
    arbitrum-pool2            822.84 k
    pool2                     822.84 k
    
    total                    18.74 M

**Comment by g1nt0ki** [comment]
@0xmidnite I have refactored the code a bit and moved curve LP to pool2, if you are fine with the changes, I can merge it. Also, thanks for the PR

**Comment by 0xmidnite** [comment]
This one ready for merge :)

**Pull request merged**
