### PR TITLE
feat: add carmine options tvl

### PR DESCRIPTION
**Pull request by DaveVodrazka**
##### Name (to be shown on DefiLlama):
 - Carmine Options

##### Twitter Link:
 - https://twitter.com/CarmineOptions

##### List of audit links if any:
 - https://carmine.finance/audit/hack-a-chain

##### Website Link:
 - https://carmine.finance/

##### Logo (High resolution, will be shown with rounded borders):
 - https://carmine.finance/assets/logo.svg

##### Current TVL:
 - 73k

##### Chain:
 - Starknet

##### Short Description (to be shown on DefiLlama):
 - Automated Market Maker enabling anyone to buy and sell options at a fair price

##### Token address and ticker if any:
 - CARM 0x03c0286e9e428a130ae7fbbe911b794e8a829c367dd788e7cfe3efb0367548fa

##### Category (full list at https://defillama.com/categories) *Please choose only one:
 - Options

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
 - Pragma

##### methodology (what is being counted as tvl, how is tvl being calculated):
 - TVL is calculated for each pool as the sum of unlocked capital and position of the pool.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/carmine-options exports TVL: 
        
 
 
    starknet                  72.80 k
    
    total                    72.80 k

**Comment by llamatester** [comment]
The adapter at projects/carmine-options exports TVL: 
        
 
 
    starknet                  101.56 k
    
    total                    101.56 k

**Comment by DaveVodrazka** [comment]
Hi @g1nt0ki thank you for the refactor! Allow me to explain the difference between these two ways of calculating TVL and let me know which one you prefer.

We are selling fully collateralized European style options, this means that whenever a user opens a position, capital is locked in. At the time of expiration either some capital is given to the user and the rest is unlocked back into the AMM (expired in the money), or all of the capital is unlocked into the AMM (expired out of the money).

1) `unlocked_capital + pool_position` reflects the value that would be inside the AMM if all of the options were to expire right now. This means that any changes are immediately reflected in the TVL.

2) The sum of the tokens currently held by the AMM will reflect the changes only at the moment options expire, this means that TVL would be steadily going up as the users trade and at the time of expiry the TVL may drop by some amount, depending on how well the traders predicted the market development.

This is somewhat simplified explanation, I hope it makes sense. If you'd like to know more I would love to connect and go into detail!

We, the Carmine dev team, are okay with either variant, but prefer number 1, since it accurately describes TVL at every point in time.

**Comment by g1nt0ki** [comment]
hi @DaveVodrazka thanks for the explanation, sorry, I prefer second variant, because we use the same methodology for other options protocols like Ribbon and Premia.

I understand your pov as well, it comes down to what one views as tvl, I consider both the trader part and the LP part as tvl, so value of all tokens in the contract, maybe at expiry if "in the money", you have a bot that transfers the tokens to the user/trader? (this is what premia does)

Sorry about this but another reason why I prefer my change is, it is safe against rug pulls, to be fair, I have not seen rugs in starknet but there is a ton of them recently in zksync era, my caution has nothing to do with your team but sad state of crypto now. 

I am merging this now so we can list it, but we can keep the conversation going and I can revert my change if you feel strongly about variant 1

**Pull request merged**
