### PR TITLE
fix: marinade tvl

### PR DESCRIPTION
**Pull request by butonium**
Seems the Marinade TVL computation is not taking into account emergencyCoolingDown and it should

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/marinade.js exports TVL: 
        
 
 
    solana                    741.90 M
    
    total                    741.90 M

**Comment by g1nt0ki** [comment]
@butonium I merged it bit too quickly, can you give some details about the emergency cooldown part? https://github.com/DefiLlama/DefiLlama-Adapters/pull/11308

**Comment by g1nt0ki** [comment]
I have re-opened it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/11309

**Comment by butonium** [comment]
> @butonium I merged it bit too quickly, can you give some details about the emergency cooldown part? #11308

sure, so whenever Marinade is unstaking certain validators due to different reasons (not performant enough, downtime, etc.) it will trigger an Emergency Unstake event which unstakes those validators in the next epoch. 

Those unstaked funds are not removed from Marinade's program, are still there but that amount is now under `emergencyCoolingDown`, not `totalActiveBalance`.  

So the TVL should be the sum of all 3 elements: `totalActiveBalance`, `availableReserveBalance`, `emergencyCoolingDown`

**Comment by g1nt0ki** [comment]
thanks for the explanation @butonium

**Pull request merged**
