### PR TITLE
Update Colony - include vesting contract

### PR DESCRIPTION
**Pull request by hbdgr**
Update Colony - include vesting contract

This pull request updates the Colony adapter to include the vesting contract in the TVL calculation.
It also adds hallmarks for important deployments, such as the launch of StakingV2 and StakingV3.

##### methodology

This update was implemented by parsing event logs extracted from the defined period between START_BLOCK and END_BLOCK, specifically targeting when vesting groups were established. Knowing the details about these groups, their amounts, and parameters, and considering the tokens that have already been withdrawn, it was possible to accurately calculate and include only the CLY tokens that are already unlocked and available for claim.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/colony exports TVL: 
        
 
 
    avax-staking              10.34 M
    staking                   10.34 M
    avax-vesting              3.92 M
    vesting                   3.92 M
    avax                      0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/colony exports TVL: 
        
 
 
    avax-staking              10.16 M
    staking                   10.16 M
    avax-vesting              5.84 M
    vesting                   5.84 M
    avax                      0
    
    total                    0

**Comment by g1nt0ki** [comment]
hi @hbdgr sorry, I made a fix that dumbed down the vesting tvl logic. Instead of finding what is vested and not yet withdrawn, we are looking at token balance on the vesting contract.

**Comment by hbdgr** [comment]
@g1nt0ki Thank you for the fix and for merging the changes so quickly!

**Pull request merged**
