### PR TITLE
feat: add RSS3 TVL

### PR DESCRIPTION
**Pull request by HenryQW**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

RSS3

##### Twitter Link:

<https://twitter.com/rss3_>

##### List of audit links if any:
https://github.com/RSS3-Network/Audits

##### Website Link:

https://rss3.io/

##### Logo (High resolution, will be shown with rounded borders):

https://rss3.notion.site/Logo-Primary-ffa72220a48a4150ba991c75a7f5bdfe
https://rss3.notion.site/d1513a3e03434ce8b7d9467e44d4784b?v=633ef1bcd3af458d87a2f00773f266d3

##### Current TVL:

~ $32m

##### Treasury Addresses (if the protocol has treasury)

On both chains: 0x7BB0c7cE05f4A676F91055724F0Db0EcC31f742F

##### Chain:

- Ethereum
- RSS3 VSL

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

rss3

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

17917

##### Token address and ticker if any:

- Ethereum: 0xc98D64DA73a6616c42117b582e832812e7B8D57F
- RSS3 VSL: 0x4200000000000000000000000000000000000042

##### Category (full list at https://defillama.com/categories) *Please choose only one:

The best one to describe this PR is `Staking Pool`.

##### forkedFrom (Does your project originate from another project):

No

##### methodology (what is being counted as tvl, how is tvl being calculated):

TVL is the token bridged from Ethereum to RSS3 VSL.

##### Github org/user (Optional, if your code is open source, we can track activity):

https://github.com/RSS3-network

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/rss3 exports TVL: 
        
 
 
    rss3_vsl-staking          19.04 M
    rss3_vsl                  31.03 M
    staking                   19.04 M
    
    total                    31.03 M

**Comment by HenryQW** [comment]
There seems to be a case-sensitivity issue for `projects/Chocoinu/` and `projects/chocoInu/`, git won't let me commit without deleting one of them. They contain identical files.

**Comment by g1nt0ki** [comment]
> There seems to be a case-sensitivity issue for `projects/Chocoinu/` and `projects/chocoInu/`, git won't let me commit without deleting one of them. They contain identical files.

huh, didnt realize there was this issue, I will fix it.

Your code has two different products combined together, I split it here: bridge & staking.
https://github.com/DefiLlama/DefiLlama-Adapters/commit/950400517ea6cd730cdebc6c14670c952fa5fcf4

Note: bridge tvl is counted towards neither source nor destination chain. Thanks for the PR :)

**Comment by HenryQW** [comment]
Looks good, what are the steps to get them displayed on pages such as:
- https://defillama.com/protocols/Liquid%20Staking
- https://defillama.com/bridges/chains

as well as showing the latest TVL including the staking on: https://defillama.com/chain/RSS3

thanks!

**Pull request closed without merging**
