### PR TITLE
feat: add Tutellus Contracts TVL

### PR DESCRIPTION
**Pull request by victormer**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Tutellus

##### Twitter Link:
https://twitter.com/tutellus

##### List of audit links if any:
None

##### Website Link:
https://tutellus.io/

##### Logo (High resolution, will be shown with rounded borders):
https://d1ddeojt5lrj1t.cloudfront.net/logos/tutellus.svg

##### Current TVL:
Around $1M

##### Treasury Addresses (if the protocol has treasury)
matic:0x5ACB3043da168b59b775eA28F3942597F45e9543

##### Chain:
Polygon (0x89)

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
tutellus

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
tutellus

##### Short Description (to be shown on DefiLlama):
El protocolo de los crypto builders

##### Token address and ticker if any:
0x12a34A6759c871C4C1E8A0A42CFc97e4D7Aaf68d (TUT)

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Services

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### forkedFrom (Does your project originate from another project):
None

##### methodology (what is being counted as tvl, how is tvl being calculated):
Counts the number of TUT tokens (in value) locked in Tutellus contracts using blockchain calls and subgraph for some user-oriented contracts.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/orgs/Tutellus

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/tutellus exports TVL: 
        
 
 
    polygon                   1.36 M
    
    total                    1.36 M

**Comment by g1nt0ki** [comment]
hi @victormer,

can you update your code to something like this: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/dexio-protocol/index.js#L7

so staking value is computed on chain instead of relying on api

**Comment by victormer** [comment]
> hi @victormer,
> 
> can you update your code to something like this: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/dexio-protocol/index.js#L7
> 
> so staking value is computed on chain instead of relying on api

hello @g1nt0ki,

the problem is that we can only scale it using Subgraph, because for each user a new staking contract is deployed (proxies), so api calls are inevitable in this case... we could use a mix of on chain calls + subgraph call, but this way we use api calls anyway so I assumed it is easier for everyone to use only one api call to our backend where we compute everything

**Comment by g1nt0ki** [comment]
hi @victormer I highly dislike apis because they break over time and we are left in the dark, but I guess it is what it is. I refactored and merged it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/7326

**Pull request closed without merging**
