### PR TITLE
Add Ulysses adapter for Maia DAO Ecosystem

### PR DESCRIPTION
**Pull request by 0xLightt**
This is a new adapter, but it should be under "Maia DAO Ecosystem".

##### Name (to be shown on DefiLlama):
Ulysses

##### Twitter Link:
https://twitter.com/MaiaDAOEco

##### List of audit links if any:
- https://github.com/Zellic/publications/blob/master/Maia%20DAO%20Ulysses%20Protocol%20May%202023%20-%20Zellic%20Audit%20Report.pdf
- https://code4rena.com/audits/2023-05-maia-dao-ecosystem
- https://code4rena.com/audits/2023-09-maia-dao-ulysses
- https://github.com/Zellic/publications/blob/master/Maia%20DAO%20Ulysses%20Protocol%20-%20Zellic%20Audit%20Report.pdf

##### Website Link:
https://app.maiadao.io/

##### Logo (High resolution, will be shown with rounded borders):
30920_logo_RM_JK-01

##### Current TVL:
502.99 k

~##### Treasury Addresses (if the protocol has treasury)~

##### Chain:
- arbitrum 
- ethereum
- optimism
- base
- polygon
- bsc
- avax
- metis

~##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)~

~##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)~

##### Short Description (to be shown on DefiLlama):
Ulysses Protocol is a decentralized and permissionless 'Omnichain Liquidity Protocol' owned by the community. It's innovative solution is designed to tackle the challenges presented by an increasingly fragmented liquidity landscape in DeFi, ensuring seamless interoperability and capital efficient cross-chain asset deployment.

~##### Token address and ticker if any:~

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Bridge

~##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):~
~##### Implementation Details: Briefly describe how the oracle is integrated into your project:~
~##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:~

~##### forkedFrom (Does your project originate from another project):~

##### methodology (what is being counted as tvl, how is tvl being calculated):
Deposited tokens into Ports from Branch chains into the Root Chain - Arbitrum.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/Maia-DAO

### CODE REVIEW

**Comment by 0xLightt** [comment]
> optimism                  0
> base                      0
> polygon                   0
> bsc                       0
> avax                      0
> metis                     0

I get this locally, not sure what leads to the difference:
```
------ TVL ------
ethereum                  240.17 k
optimism                  108.51 k
base                      81.41 k
metis                     45.11 k
bsc                       14.38 k
avax                      14.13 k
polygon                   0

total                    503.70 k 
```

Also, the linting is failing due to JustLend adapter, I can fix it here or in another PR if you wish.

**Comment by llamatester** [comment]
The adapter at projects/ulysses exports TVL: 
        
 
 
    ethereum                  229.88 k
    optimism                  99.72 k
    base                      75.55 k
    metis                     42.01 k
    bsc                       14.35 k
    avax                      14.16 k
    polygon                   0
    
    total                    475.67 k

**Comment by llamatester** [comment]
The adapter at projects/ulysses exports TVL: 
        
 
 
    ethereum                  234.15 k
    optimism                  102.87 k
    base                      77.00 k
    metis                     44.08 k
    bsc                       14.35 k
    avax                      14.12 k
    polygon                   0
    arbitrum                  0
    
    total                    486.57 k

**Comment by g1nt0ki** [comment]
@0xLightt thanks for the PR, I got bit lazy so did the bit of a hack.  For bridges, we count the tokens at the source, so updated code to that, and instead of relying on event logs for token list, I use our api to pull all tokens on a given address and unfortunately metis is not supported, so added token list manually for it.

**Comment by 0xLightt** [comment]
Thank you  very much, I'll add addresses for other chains, will also remove arbitrum since Ulysses doesn't have any deposits there.

For context. I avoided doing that so it wouldn't counts for failed deposits. Also in the future we can put those funds to work in something like aave through governance, but we'll update this if we ever do it.

**Comment by g1nt0ki** [comment]
in theory, we price all aave tokens, so (hopefully) there is no need to update this adapter

**Pull request merged**
