### PR TITLE
Adjust the code to use the new Dyson API

### PR DESCRIPTION
**Pull request by WeaverSphere**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/dyson-money exports TVL: 
        
 
 
    optimism                  0
    bsc                       0
    arbitrum                  190.21 k
    kava                      82.32649624
    avax                      77.39730476
    polygon                   1.88 M
    polygon-staking           2.73 M
    staking                   2.73 M
    
    total                    2.07 M

**Comment by WeaverSphere** [comment]
P.S. please adjust the protocol Icon to use one of these as the current one, with the white border looks horrible

PNG
image
SVG
image

**Comment by llamatester** [comment]
The adapter at projects/dyson-money exports TVL: 
        
 
 
    optimism                  0
    bsc                       0
    avax                      77.48740999999998
    arbitrum                  187.27 k
    polygon-staking           2.40 M
    kava                      82.42233999999999
    polygon                   1.82 M
    staking                   2.40 M
    
    total                    2.01 M

**Comment by g1nt0ki** [comment]
looks good, thanks

**Comment by g1nt0ki** [comment]
we will update the icon

**Pull request merged**
