### PR TITLE
Binance new wallet (WIP)

### PR DESCRIPTION
**Pull request by Define101**
Binance new wallet (WIP)

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/binance exports TVL: 
        
 
 
    tron                      17.34 B
    polygon                   395.43 M
    bsc                       19.91 B
    avax                      546.58 M
    optimism                  350.57 M
    arbitrum                  775.61 M
    litecoin                  0
    bitcoin                   19.99 B
    ethereum                  24.45 B
    
    total                    83.76 B

**Comment by Define101** [comment]
Ripple chain not working not sure why
Still need to add solana

**Comment by llamatester** [comment]
Error while running adapter at projects/binance: 
        
 
  
    
    
    TypeError: Found non-callable @@iterator
    Truncated error stack:
    
        at getSolBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:47:19)
        at async Object.sumTokens2 (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:337:24)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)
        at async Promise.all (index 10)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Comment by llamatester** [comment]
Error while running adapter at projects/binance: 
        
 
  
    
    
    TypeError: Found non-callable @@iterator
    Truncated error stack:
    
        at getSolBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:47:19)
        at async Object.sumTokens2 (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:337:24)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:9
        at async Promise.all (index 0)
        at async Promise.all (index 9)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:193:3

**Pull request merged**
