### PR TITLE
added Lore

### PR DESCRIPTION
**Pull request by Deantoshi**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Lore

##### Twitter Link:
https://x.com/LoreFinance

##### List of audit links if any:
[CertiK-Granary-V1-Audit-Report.pdf](https://github.com/user-attachments/files/16571279/CertiK-Granary-V1-Audit-Report.pdf)
https://code4rena.com/audits/2023-02-ethos-reserve-contest#top
https://code4rena.com/reports/2023-02-ethos
https://github.com/GalloDaSballo/Ethos-Reserve-Nov-Peer-Review
https://www.beirao.xyz/blog/SR2-EthosV2

##### Website Link:
https://lore.finance/

##### Logo (High resolution, will be shown with rounded borders):
Lore_TokenLight

##### Current TVL:
260k

##### Treasury Addresses (if the protocol has treasury)
0x5F272Ee6348BDE137D9a6c640c42DDcF0dE3D0aA

##### Chain:
scroll

##### Short Description (to be shown on DefiLlama):
Lore is Modular Reserve Protocol (MRP) that currently contains an Aave v2 Fork that will soon have a Collateralized Debt Position Protocol (CDP) built on top of the borrowing/lending to generate yield for a decentralized stablecoin.

##### Token address and ticker if any:
0x549423E69576b80E91dC836ae37e04209660c4ec

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Chainlink
##### Implementation Details: Briefly describe how the oracle is integrated into your project:
Oracle is used to price assets for borrowing and lending.

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
Chainlink Oracles currently used:
"STONE": "0xD1D60f675fbb6cE30d7305CFe244152317003004",
"ETH": "0x6bF14CB0A831078629D993FDeBcB182b21A8774C",
"wstETH": "0x3a4ea21729f8556547E1243608872C8827DdEEd7",
"USDC": "0x43d12Fb3AfCAd5347fA764EeAB105478337b7200",
"USDT": "0xf376A91Ae078927eb3686D6010a6f1482424954E"

##### forkedFrom (Does your project originate from another project):
Aave V2

##### methodology (what is being counted as tvl, how is tvl being calculated):
260k. Deposits - Borrows

##### Github org/user (Optional, if your code is open source, we can track activity):
N/A

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/lore: 
        
 
  
    
    
    Error: Failed to call: address[]:getAddressesProvidersList target: 0xBc6DE4458b7D6fbf82240ce8cC0CA6a2f4986eb5 on chain: [mode] rpc: https://mainnet.mode.network, https://1rpc.io/mode, https://mode.drpc.org  call reverted, reason: fragment.format is not a function

**Comment by Deantoshi** [comment]
Not sure how to get it to run on the Scroll blockchain, please let me know if there is something I need to update.

**Comment by llamatester** [comment]
Error while running adapter at projects/lore: 
        
 
  
    
    
    Error: Failed to call: address[]:getAddressesProvidersList target: 0xBc6DE4458b7D6fbf82240ce8cC0CA6a2f4986eb5 on chain: [mode] rpc: https://mainnet.mode.network, https://1rpc.io/mode, https://mode.drpc.org  call reverted, reason: fragment.format is not a function

**Comment by llamatester** [comment]
The adapter at projects/lore exports TVL: 
        
 
 
    scroll                    213.37 k
    scroll-borrowed           48.42 k
    borrowed                  48.42 k
    
    total                    213.37 k

**Comment by llamatester** [comment]
The adapter at projects/lore exports TVL: 
        
 
 
    scroll                    213.37 k
    scroll-borrowed           48.42 k
    borrowed                  48.42 k
    
    total                    213.37 k

**Comment by Define101** [comment]
@Deantoshi What happen to the twitter acc?

**Comment by Deantoshi** [comment]
@Define101 we soft launched last Thursday. We will be pushing Lore this week and should have the account verified soon.

**Pull request merged**
