### PR TITLE
change back to backend graph, thegraph as fallback

### PR DESCRIPTION
**Pull request by franzns**
Change back the logic to what was done by @0xngmi here https://github.com/DefiLlama/DefiLlama-Adapters/blob/0d6bcfb2d66d9adb50c20ce6c70a5c257a69a6f6/projects/beethovenx/index.js

We are using our backend to track current number of TVL, which takes all nested assets into account. If the timestamp is older, we use thegraph API as fallback.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/beethovenx exports TVL: 
        
 
 
    fantom                    97.34 M
    optimism                  4.86 M
    
    total                    102.21 M

**Comment by 0xngmi** [comment]
main issue i see with it is that the subgraph could be arbitrarily delayed
eg; we could be ingesting data that is days old with your pr

**Comment by waynebruce0x** [comment]
By passing a blockheight into subgraph queries we can easily see when data is outdated, and debug the issue, but with this implementation we wont be able to debug anything

**Comment by franzns** [comment]
> By passing a blockheight into subgraph queries we can easily see when data is outdated, and debug the issue, but with this implementation we wont be able to debug anything

Would you like to see if data is outdated on thegraph? An option would be to query the meta information that returns the current block it has synced to. Data on the backend is considered current and up to date because it uses a combination of subgraph and onchain calls.

**Comment by waynebruce0x** [comment]
Yeah I think that'd work, thanks

**Comment by llamatester** [comment]
The adapter at projects/beethovenx exports TVL: 
        
 
 
    fantom                    77.51 M
    optimism                  2.70 M
    
    total                    80.20 M

**Comment by llamatester** [comment]
The adapter at projects/beethovenx exports TVL: 
        
 
 
    optimism                  2.70 M
    fantom                    77.64 M
    
    total                    80.34 M

**Comment by franzns** [comment]
@waynebruce0x as discussed, added the getLatestSyncedBlock function for both chains.

**Comment by franzns** [comment]
@waynebruce0x anything I can do to speed this up?

**Pull request merged**
