### PR TITLE
gambit protocol

### PR DESCRIPTION
**Pull request by zashton**
##### Twitter Link:
https://twitter.com/GambitProtocol

##### List of audit links if any:
Nil

##### Website Link:
https://gambit.financial/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://gblobscdn.gitbook.com/spaces%2F-MVFKxuiFJ9KiOZaFnYb%2Favatar-1615183406493.png

##### Current TVL:
$6.67m

##### Chain:
BSC

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
gambit

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
9203

##### Description/bio (to be shown on DefiLlama):
Building a better leverage platform through interest-generating stablecoins.
On Gambit, there is no slippage to enter and exit a position.
Liquidations only occur through Chainlink price updates so the platform does not have sudden wicks from cascading liquidations.

##### Token address and ticker if any:
0x99e92123eb77bc8f999316f622e5222498438784
$GMT

##### Category (Yield/Dexes/Lending/Minting):
Dexes/Lending

### CODE REVIEW

**Comment by 0xngmi** [comment]
Thanks, I've just made a tx with their protocol and it seems like assets end up in https://bscscan.com/address/0xc73a8dcac88498fd4b4b1b2aaa37b0a2614ff67b, so I was thinking of querying the balances there, as that would allow the adapter to work on old block heights and remove trust on the api

**Comment by zashton** [comment]
> Thanks, I've just made a tx with their protocol and it seems like assets end up in https://bscscan.com/address/0xc73a8dcac88498fd4b4b1b2aaa37b0a2614ff67b, so I was thinking of querying the balances there, as that would allow the adapter to work on old block heights and remove trust on the api

hey sorry @0xngmi  just saw this, will send a fresh PR later to pull data thru contract

**Comment by 0xngmi** [comment]
No need, already applied the change after I made the comment, all good :+1:

**Comment by zashton** [comment]
> No need, already applied the change after I made the comment, all good 👍

just got notified by the gambit team they had audits
https://github.com/xvi10/gambit-contracts/tree/master/audits

**Pull request merged**
