### PR TITLE
Add Banana adapter

### PR DESCRIPTION
**Pull request by bananafarm**
##### Twitter Link:
https://twitter.com/bananafarm_io

##### Website Link:
https://bananafarm.io/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
BANA.icon

##### Current TVL: 
568k

##### Chain: 
Boba

##### Short Description (to be shown on DefiLlama):
**Earn more yield! Autocompound on Boba!  Boba has gone bananas after BANANA autocompound coming.**

##### Token address and ticker if any:
BANA: 0xc67b9B1B0557aeAfA10AA1fFa1d7c87087a6149E

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Yield

##### forkedFrom (Does your project originate from another project):
AutoFarm

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is calculated by summing up the values of all LP tokens and our project's rewards token.

### CODE REVIEW

**Comment by waynebruce0x** [comment]
FYI PRs will automatically update when you push changes to the branch/fork you're merging, so you don't need to open a new PR each time.

Same comment as last PR:
Can BANA staking TVL be seperated out into a seperate 'staking' export, and BANA-ETH LP staking be seperated out into a 'pool2' export?

Just repeating it so everyone knows where we're up to

**Comment by bananafarm** [comment]
Hi Waynebruce0x,

Thanks a lot for the information. 
1. BANA staking TVL can not be separated out into a separate 'staking' export.
2. BANA and BANA-ETH LP staking can not be separated out into a 'pool2' export.
If you need any further information, please feel free to let me know.

Regards,

James

**Comment by waynebruce0x** [comment]
We try to keep our method of calculating TVL consistent across all projects. This means native token staking and LP pools need to be separated from core TVL. If it can't be done with the API, can you do it with an adapter that reads coin balances straight from the blockchain?

**Comment by bananafarm** [comment]
Hi Waynebruce0x,

We have evaluated the workload about providing the adapter that reads coin balances straight from the blockchain. Our developers suggest that they have to put it into our next release. 
Could we commit this version so that our project data can be integrated into DefiLlama?  
 
Regards,

James

**Comment by 0xngmi** [comment]
I'll try reframing the question, could you change your api to split your tvl into three categories:
- tvl in the bana pool
- tvl in bana-eth pool (and, in the future, other pools that are against BANA)
- tvl in all other pools

?

**Comment by bananafarm** [comment]
Hi 0xngmi,

Sorry for the confusion. The answer is Yes, we can. And we already committed a new version by referring other projects.

Unfortunately, our developer encountered an error during testing by running node test.js projects/banana/index.js in local environment. Since our project is on Boba network. It looks like that the SDK is not fully support Boba network.
The error message is shown below: 
(node:8073) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'push' of undefined
    at /Users/xxx/workspace_node/DefiLlama-Adapters/node_modules/@defillama/sdk/build/computeTVL/index.js:255:45

We have got stuck for this issue for several days. Could you please help us to list our project, then we could continue our debugging?
Any suggestions will be highly appreciated!

Regards,

James

**Comment by bananafarm** [comment]
Hi 0xngmi,

Sorry to bother you. Could you please let us know what's our next step?
Is it possible to list our project first based on current version?

Thanks a lot!

Regards,

Andy

**Comment by bananafarm** [comment]
Hi @0xngmi , @waynebruce0x,

Sorry to bother you. Could you please let us know what should we do for next step?
We already commit the codes. It is highly appreciated, if you can provide any suggestions to get approval!

Regards,

James

**Comment by waynebruce0x** [comment]
Thanks for separating the TVL, we just need a bit of time to figure out why the adapter isn't working.

**Comment by waynebruce0x** [comment]
is BANA on coingecko? I think that could be causing an issue with the staking() result.
Also the masterchef address seems to have a 0 balance of BANA LP is this right? I think this could also be causing an issue.

**Comment by bananafarm** [comment]
Hi Waynebruce0x,

Thanks a lot for you kind guide!
BANA is not on Coingecko now, unfortunately. 
If DefiLlama can extract all mandatory data from current committed codes, could you please list BananaFarm project first. Then we can focus on troubleshoot the separating TVL issues?

**Comment by waynebruce0x** [comment]
Hey guys please get in touch - I cant make the adapter work. I will write the adapter for you but I need contract addresses.

**Comment by bananafarm** [comment]
Hi Waynebruce,

BananaFarm is yield aggregator which forked from Autofarm. We plan to just show the TVL and staking amount in current stage. The amount of TVL (USD $) can get from the API in committed adapter codes. While for the amount of staking, the BANA tokens (0xc67b9B1B0557aeAfA10AA1fFa1d7c87087a6149E) has been staked in the corresponding Strat contract (0x3C8878107e029d25Ed6fd504072C98D1fB7f6F3B).
Again, thanks a lot for your kind help!

Regards,
James

**Comment by bananafarm** [comment]
Hi Waynebruce,

Sorry to bother you again. Could you please let us know if you need us to provide any further information?
If you need any data, please feel free to let us know.

Thanks for your great help!

Regards,

James

**Comment by bananafarm** [comment]
@waynebruce0x 
Hi Waynebruce,

Sorry to bother you again. Could you please let us know if you need us to provide any further information?
If you need any data, please feel free to let us know.

Thanks for your great help!

Regards,

James

**Comment by bananafarm** [comment]
@waynebruce0x
Hi Waynebruce,

Could you please provide an update to guide us how to move onto the next step?

Thanks for your great help!

Regards,

James

**Comment by waynebruce0x** [comment]
Hey sorry I've only just seen this. I'll get this sorted ASAP

**Comment by bananafarm** [comment]
@waynebruce0x
Hi Waynebruce,

Merry Xmas and happy new year!
Thanks for your help, and if you need any further informaiton, please feel free to let us know.

Regards,

James

**Comment by waynebruce0x** [comment]
sorry for the delay guys

**Comment by waynebruce0x** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters/pull/1263

I get:
boba-staking              8.78 k
boba-pool2                7.70 k
boba                      171.09 k

**Comment by waynebruce0x** [comment]
Do you mind adding any further comments to the new PR instead of this one?

**Pull request merged**
