### PR TITLE
Yeti Finance

### PR DESCRIPTION
**Pull request by 0xAces**
##### Twitter Link: 

https://twitter.com/YetiFinance

##### List of audit links if any: 

- [Dedaub](https://www.dedaub.com/): [Audit Report 1](https://docs.google.com/document/d/1i3PWxOCt_EaFU51aI1YOgWkmPp0EbsV3d3G_ZtvS4Ko/edit), [Audit Report 2](https://docs.google.com/document/d/1DxfCo6KqfKOJfmlQmAlb2UySyFaMDwBNKkDo_nZPIsw/edit)
- [Three Sigma Labas](https://threesigma.xyz/): [Audit Report](https://drive.google.com/file/d/1fpU4V-9iQKUTXRd8ZvmSThdib44bA4xi/view?usp=sharing)
- [Haechi](https://audit.haechi.io/): [Audit Report](https://docs.google.com/document/d/1qYVwps1KgUxdmOoKFdgTDmhhMk4fY9tf0ukYxOAf_CQ/edit)
- [Code Arean](https://code4rena.com/): [Audit Report](https://code4rena.com/reports/2021-12-yetifinance/)

##### Website Link:

https://yeti.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): 

[Yeti Finance Logo](https://1786218689-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F4OftjbgGWmJOiwFRkFKr%2Fuploads%2FEY0hGEkxGQSDHwdicVqb%2FFurry%20Yeti_Furry%20World.png?alt=media&token=f4340014-7ca7-4327-ad2b-0ff651a005cf)

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

yeti-finance

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

19576

##### Short Description (to be shown on DefiLlama):

Yeti Finance is a cutting edge decentralized borrowing protocol built on Avalanche that allows users to borrow up to 11x against base assets like WETH, staked assets like Liquid AVAX, LP tokens - and 21x on yield-bearing stablecoins, all at a 0% interest rate. Users retain all farming and staking rewards when these assets are deposited onto Yeti Finance’s platform, opening up numerous leveraged farming strategies. Yeti Finance also offers cross-margining, something the majority of borrowing protocols don't have. In simple terms, users on Yeti Finance can open up a borrowing position on their entire portfolio instead of just a single asset. Cross-margining makes borrowing against volatile assets much safer as multiple assets can serve as collateral for your loan instead of just one, greatly reducing the risk of liquidations due to asset volatility and flash crashes. Unlock deep liquidity, borrow at the lowest collateral ratios, and borrow against your entire portfolio to gain better protection against liquidations. Yeti Finance is a quantum leap forward in the borrowing landscape and will unlock tens of billions of dollars in new liquidity on Avalanche.

##### Token address and ticker if any:

[0x77777777777d4554c39223C354A05825b2E8Faa3](https://snowtrace.io/token/0x77777777777d4554c39223C354A05825b2E8Faa3)

##### Category (full list at https://defillama.com/categories) *Please choose only one:

CDP

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

Chainlink

##### methodology (what is being counted as tvl, how is tvl being calculated):

Total System Collateral Deposits + YUSDCurve LP Token Farm Staking

### CODE REVIEW

**Comment by 0xngmi** [comment]
we don't count tokens that are backed by other TVL (eg: we don't count DAI in Maker nor MIM in abra)

**Comment by 0xAces** [comment]
> we don't count tokens that are backed by other TVL (eg: we don't count DAI in Maker nor MIM in abra)

are you referring to Stability Pool deposits?

**Comment by 0xAces** [comment]
> we don't count tokens that are backed by other TVL (eg: we don't count DAI in Maker nor MIM in abra)

Hey 0xngmi, 

We use the same liquidation system as Liquity (Users deposit their YUSD, LUSD for Liquity into the Stability Pool). Stabilty Pool deposits are counted toward TVL for Liquity. [https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/liquity/index.js](https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/liquity/index.js).

Please let me know if you have further questions or concerns.

Look forward to hearing from the team :)

**Comment by realdealshaman** [comment]
Hi, I had previously set aside some time to correct this and removed the stabilitypool tvl from liquity forks, somehow I overlooked liquity since I focused on protocols using our liquity helper function.

I've now removed the stabilitypool amount from the liquity adapter as well. Sorry for any confusion it may have caused and if there is any other that I may have missed, please let me know and I will be happy to update it. Thanks

**Comment by 0xAces** [comment]
> Hi, I had previously set aside some time to correct this and removed the stabilitypool tvl from liquity forks, somehow I overlooked liquity since I focused on protocols using our liquity helper function.
> 
> I've now removed the stabilitypool amount from the liquity adapter as well. Sorry for any confusion it may have caused and if there is any other that I may have missed, please let me know and I will be happy to update it. Thanks

Got it! Just removed the stability pool deposits from the calculation.

**Comment by g1nt0ki** [comment]
@0xAces can you please restore changes to `package-lock.json` file

**Comment by llamatester** [comment]
The adapter at projects/yetiFinance/index.js exports TVL: 
        
 
 
    avalanche                 550.36 M
    
    total                    550.36 M

**Comment by 0xAces** [comment]
> @0xAces can you please restore changes to `package-lock.json` file

Done

**Comment by llamatester** [comment]
The adapter at projects/yetiFinance/index.js exports TVL: 
        
 
 
    avalanche                 553.76 M
    
    total                    553.76 M

**Pull request merged**
