### PR TITLE
fix: update Lava data provider address

### PR DESCRIPTION
**Pull request by 0xVolcan**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/lava exports TVL: 
        
 
 
    arbitrum-borrowed         0
    arbitrum                  83.72704957988199
    base-borrowed             74.0316102611174
    base                      188.99544367573083
    borrowed                  74.0316102611174
    
    total                    272.7224932556128

**Comment by llamatester** [comment]
The adapter at projects/lava exports TVL: 
        
 
 
    arbitrum-borrowed         0
    arbitrum                  83.2658130556
    base-borrowed             73.66684834491659
    base                      188.03993357714205
    borrowed                  73.66684834491659
    
    total                    271.30574663274206

**Comment by llamatester** [comment]
The adapter at projects/lava exports TVL: 
        
 
 
    arbitrum-borrowed         0.996044
    arbitrum                  83.89364504816201
    base-borrowed             73.43407193546277
    base                      187.15588875734653
    borrowed                  74.43011593546277
    
    total                    271.04953380550853

**Comment by g1nt0ki** [comment]
@0xVolcan thanks for the PR

**Comment by llamatester** [comment]
The adapter at projects/lava exports TVL: 
        
 
 
    base-borrowed             73.44076302031976
    base                      187.10859749812855
    arbitrum-borrowed         7.257242065154109
    arbitrum                  226.61088459181997
    borrowed                  80.69800508547388
    
    total                    413.71948208994854

**Pull request merged**
