### PR TITLE
fix: replace available_liquidity_tokens with market_size(supplied amount)

### PR DESCRIPTION
**Pull request by EbrahimUmee**
Available_liquidity_tokens is just available to borrow, doesn't take into consideration total supplied/ reserved. market_size name may be misleading. To confirm this number you can multiply the collateral weight * the market size and youll get the available_liquidity_tokens

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/umee exports TVL: 
        
 
 
    umee-borrowed             1.45 M
    umee                      6.44 M
    ethereum                  671.81 k
    ethereum-borrowed         9.05 k
    borrowed                  1.46 M
    
    total                    7.11 M

**Comment by g1nt0ki** [comment]
@EbrahimUmee we dont consider supplied amount as tvl for lending protocols as tvl can be inflated via looping

**Comment by g1nt0ki** [comment]
is there some way to get these numbers by calling rpc instead of this api? https://testnet-client-bff-ocstrhuppq-uc.a.run.app/convexity/assets/all

**Comment by EbrahimUmee** [comment]
Yes you would use these two queries in combination: https://api.mainnet.network.umee.cc/umee/leverage/v1/registered_tokens
https://api.mainnet.network.umee.cc/umee/leverage/v1/market_summary?denom=uumee

Use the first one to get the registry and then call the market_summary for each individual base_denom. 

Supplied is supplied and borrowed is borrowed, all in token amounts,

**Comment by llamatester** [comment]
The adapter at projects/umee exports TVL: 
        
 
 
    ethereum                  706.19 k
    ethereum-borrowed         64.31 k
    umee-borrowed             1.56 M
    umee                      6.67 M
    borrowed                  1.63 M
    
    total                    7.38 M

**Comment by EbrahimUmee** [comment]
So I just pushed an update to use the queries instead of our api

**Comment by EbrahimUmee** [comment]
> we dont consider supplied amount as tvl for lending protocols as tvl can be inflated via looping

I didn't see this sorry, will change to use available_liquidity

**Comment by g1nt0ki** [comment]
> > we dont consider supplied amount as tvl for lending protocols as tvl can be inflated via looping
> 
> I didn't see this sorry, will change to use available_liquidity

@EbrahimUmee thanks for turning it on chain, I have updated it to subtract borrowed amount

**Comment by EbrahimUmee** [comment]
forgot the borrowed amount, thanks

**Pull request merged**
