### PR TITLE
hector

### PR DESCRIPTION
**Pull request by waynebruce0x**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/hector exports TVL: 
        
 
 
    bsc                       589.28 k
    ethereum                  4.33 M
    fantom                    33.29 M
    
    total                    38.21 M

**Comment by llamatester** [comment]
The adapter at projects/hector exports TVL: 
        
 
 
    bsc                       590.02 k
    fantom                    33.10 M
    ethereum                  5.20 M
    
    total                    38.89 M

**Comment by llamatester** [comment]
The adapter at projects/hector exports TVL: 
        
 
 
    fantom-staking            25.63 M
    bsc                       590.08 k
    fantom                    33.08 M
    ethereum                  5.21 M
    staking                   25.63 M
    
    total                    38.88 M

**Review by sameretto — COMMENTED** [review]
looks good to me we have balances on all of these address..

0x4bfb33d65f4167ebe190145939479227e7bf2cb0
0xcb54ea94191b280c296e6ff0e37c7e76ad42dc6a
0x677d6ec74fa352d4ef9b1886f6155384acd70d90
0x3cdf52cc28d21c5b7b91d7065fd6dfe6d426fcc5
0x8a43e670619973944cb573bb23688c24cc0b5131
0x078E3977b30955f4Af9AA1D9DeC4ceB660c36e0c
0xBE4b73f5Caff476Ed0Cdb4C043236fce81f4dC6C
0x35796Ce4Ed757075D346c1bc374D67628fadcbB1

**Comment by sameretto** [comment]
the balance should be higher than this if you check the debank profiles it will show you how much it has in wallet and in protocols

**Pull request merged**
