### PR TITLE
Update TVL Moremoney

### PR DESCRIPTION
**Pull request by BrunoEleodoro**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/moremoney: 
        
 
  
    
    
    TypeError: stratViewer.viewMetadata is not a function
    Truncated error stack:
    
        at useStrategyMetadata (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/moremoney/StrategyMetadata.js:49:43)
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/moremoney/index.js:12:30)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:60:31)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:167:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:155:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:150:44

**Comment by llamatester** [comment]
Error while running adapter at projects/moremoney: 
        
 
  
    
    
    Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="viewMetadata(address,address[],address[])", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    Truncated error stack:
        at Interface.decodeFunctionResult (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/abi/lib/interface.js:388:23)

**Comment by llamatester** [comment]
Error while running adapter at projects/moremoney: 
        
 
  
    
    
    Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="viewMetadata(address,address[],address[])", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    Truncated error stack:
        at Interface.decodeFunctionResult (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/abi/lib/interface.js:388:23)

**Comment by llamatester** [comment]
The adapter at projects/moremoney exports TVL: 
        
 
 
    avax                      1.65 M
    
    total                    1.65 M

**Comment by g1nt0ki** [comment]
sorry, the amount of lines scared me a bit, will review it soon

**Pull request merged**
