### PR TITLE
Update Midas Capital pools and TVL

### PR DESCRIPTION
**Pull request by rhlsthrm**
Adding new chain deployments + pools.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/midas-capital exports TVL: 
        
 
 
    moonbeam-borrowed         0.28666431872023196
    moonbeam                  0.18792478182449804
    bsc                       149.96 k
    bsc-borrowed              87.92 k
    borrowed                  87.92 k
    
    total                    149.96 k

**Comment by rhlsthrm** [comment]
Any idea why Polygon isn't showing up here?

**Comment by g1nt0ki** [comment]
change 

    module.exports = {
      bsc: getTvl("bsc"),
      moonbeam: getTvl("moonbeam"),
    };

to 

    Object.keys(config).forEach(chain => module.exports[chain] = getTvl(chain))

**Comment by g1nt0ki** [comment]
@rhlsthrm I have fixed the bug here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/4195

**Pull request merged**
