### PR TITLE
Add Minterest project TVL for Ethereum mainnet && Mantle networks [ready for review]

### PR DESCRIPTION
**Pull request by Apollo50**
Status: Ready for review

##### Name (to be shown on DefiLlama):
* Minterest

##### Twitter Link:
* https://twitter.com/Minterest

##### List of audit links if any:
* [Trail of Bits,](https://minterest.com/audit-report-trail-of-bits/) March 2022
* [Hacken,](https://minterest.com/audit-report-hacken/) April 2022
* [PeckShield,](https://minterest.com/audit-report-peckshield/) June 2022
* [Zokyo,](https://minterest.com/audit-report-zokyo/) November 2022
* [Zokyo,](https://minterest.com/zokyo-audit-report-2/) February 2023
* [Zokyo,](https://minterest.com/audit-report-zokyo-3/) March 2023
* [Zokyo](https://minterest.com/audit-report-zokyo-4/), October 2023

##### Website Link:
* https://minterest.com/

##### Logo (High resolution, will be shown with rounded borders):
MINTY circle

##### Current TVL:
Screenshot from 2024-01-17 18-54-09

##### Treasury Addresses (if the protocol has treasury)
 No

##### Chain:
* Ethereum
* Mantle

##### Short Description (to be shown on DefiLlama):
* Minterest is a landing protocol which captures more fees than any other lending protocol and redistributes them as rewards back to users who contribute to its governance.

##### Token address and ticker if any:
Address: [0x149caC67F1cd5d80651E7c9Bb359ec285D821a05](https://etherscan.io/address/0x149caC67F1cd5d80651E7c9Bb359ec285D821a05#code)
Ticker: **MINTY**

##### Category (full list at https://defillama.com/categories) *Please choose only one:
* Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
* Ethereum: Chainlink
* Mantle: Api3

##### forkedFrom (Does your project originate from another project):
* Compound

##### methodology (what is being counted as tvl, how is tvl being calculated):
* TVL is calculated by getting the market addresses from Supervisor contract and calling the getCash() on-chain method to get the amount of tokens locked in each market, then we get the price of each token from Coingecko.

##### Github org/user (Optional, if your code is open source, we can track activity):
* https://github.com/minterest-finance

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/minterest exports TVL: 
        
 
 
    ethereum-borrowed         6.11 k
    ethereum                  76.78 k
    mantle-borrowed           0
    mantle                    0
    borrowed                  6.11 k
    
    total                    76.78 k

**Comment by Apollo50** [comment]
> The adapter at projects/minterest exports TVL:
> 
> ```
> ethereum-borrowed         6.11 k
> ethereum                  76.78 k
> mantle-borrowed           0
> mantle                    0
> borrowed                  6.11 k
> 
> total                    76.78 k 
> ```

Team, can I get help with Mantle TVL?

To calculate TVL && Borrowed on Mantle I use the same approach as for the Ethereum.
However, the local test shows me that it can not resolve symbols, names, and decimals for the Mantle network.
As a result, TVL on Mantle is displayed as zero.

Thanks in advance!

**Comment by llamatester** [comment]
The adapter at projects/minterest exports TVL: 
        
 
 
    mantle-borrowed           0.0000029193378019650436
    mantle                    2.82 M
    ethereum                  73.49 k
    ethereum-borrowed         6.09 k
    borrowed                  6.09 k
    
    total                    2.89 M

**Comment by g1nt0ki** [comment]
@Apollo50 thanks for the PR

**Comment by g1nt0ki** [comment]
have have a helper for compound like protocols, so used it.

the reason mantle tokens were not showing up was, mantle tokens need to be prepended with "mantle:"

**Pull request merged**
