### PR TITLE
opendao adapter request

### PR DESCRIPTION
**Pull request by vy5555**
##### Twitter Link: 
https://twitter.com/opendaoprotocol

##### List of audit links if any:
https://opendao.gitbook.io/transparency/audits

##### Website Link: 
https://opendao.io/
https://mint.opendao.io/#/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://mint.opendao.io/assets/img/pOPEN_logo.png
https://mint.opendao.io/assets/img/open-logo-sm.png

##### Current TVL:
$1,589,765

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

https://www.coingecko.com/en/coins/open-governance-token

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

id":7783

##### Short Description (to be shown on DefiLlama):
The Permissionless Stablecoin Minting Protocol,
Mint USDO with the tokens you own. Trade USDO for the tokens you want.

##### Token address and ticker if any:
https://bscscan.com/address/0xabae871b7e3b67aeec6b46ae9fe1a91660aadac5

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Minting

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Can this be done using on-chain calls? Its more transparent than API calls, so we use on-chain where we can.

**Comment by vy5555** [comment]
> Can this be done using on-chain calls? Its more transparent than API calls, so we use on-chain where we can.

I can but i think api will have less maintenance to update the newer mint vault address, because we are adding new vaults after some days(1-2). For transparency purpose you can find the tvl and contract details from https://mint.opendao.io/#/.
thanks

**Comment by Nemusonaneko** [comment]
Wrote an adapter of my own but got this:
```
--- bsc ---
OPEN                      721.50 k
OCP                       357.60 k
LAND                      32.04 k
LIME                      31.85 k
ROSN                      3.96 k
Total: 1.15 M 

--- tvl ---
OPEN                      721.50 k
OCP                       357.60 k
LAND                      32.04 k
LIME                      31.85 k
ROSN                      3.96 k
Total: 1.15 M 

------ TVL ------
bsc                       1.15 M

total                    1.15 M 
```
The TVL is from the underlying tokens in vaults used as collateral to mint USDO.
Vault contracts:
```
 "0x0a234ef34614a4eed1c1430a23b46f95df5f4257", // pOPEN
  "0xfff0cc78a7e7ce5d6ba60f23628ff9a63beee87f", // OCP
  "0x09139d7343953163eacde83845b342c1d08999ef", // LIME
  "0xd90ec012a6b2b549dd2a74024f1e025d0801696c", // LAND
  "0xcfefc606c4c010c242431f60a7afc13461df399c", // ROSEN
```

Where does the extra ~$450K TVL come from?

**Comment by vineet555** [comment]
> Wrote an adapter of my own but got this:
> 
> ```
> --- bsc ---
> OPEN                      721.50 k
> OCP                       357.60 k
> LAND                      32.04 k
> LIME                      31.85 k
> ROSN                      3.96 k
> Total: 1.15 M 
> 
> --- tvl ---
> OPEN                      721.50 k
> OCP                       357.60 k
> LAND                      32.04 k
> LIME                      31.85 k
> ROSN                      3.96 k
> Total: 1.15 M 
> 
> ------ TVL ------
> bsc                       1.15 M
> 
> total                    1.15 M 
> ```
> 
> The TVL is from the underlying tokens in vaults used as collateral to mint USDO. Vault contracts:
> 
> ```
>  "0x0a234ef34614a4eed1c1430a23b46f95df5f4257", // pOPEN
>   "0xfff0cc78a7e7ce5d6ba60f23628ff9a63beee87f", // OCP
>   "0x09139d7343953163eacde83845b342c1d08999ef", // LIME
>   "0xd90ec012a6b2b549dd2a74024f1e025d0801696c", // LAND
>   "0xcfefc606c4c010c242431f60a7afc13461df399c", // ROSEN
> ```
> 
> Where does the extra ~$450K TVL come from?


thank you so much for your support and help,
i think you are not considering the usdo supply and borrow amount at every vault.

users can also Lend and  Mint USDO on every vault. so every vault having usdo underlying token.

**Comment by Nemusonaneko** [comment]
We decided to not count the USDO as TVL.

**Comment by Geek4tek** [comment]
> We decided to not count the USDO as TVL and will only count the tokens used to mint

 I think it's fine, You are consider only  collateral underlying token. But can you Please check, I am getting from Opendao adapter TVL approx (1.16M) by  git "main" branch adapter(https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/opendao/index.js) but it is showing diff data(352.35K) on defilama (https://defillama.com/protocol/opendao)
 thanks

**Comment by vy5555** [comment]
> We decided to not count the USDO as TVL and will only count the tokens used to mint

I think it's fine, You are consider only collateral underlying token. But can you Please check, I am getting from Opendao adapter TVL approx (1.16M) by git "main" branch adapter(https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/opendao/index.js) but it is showing diff data(352.35K) on defilama (https://defillama.com/protocol/opendao)
thanks

**Pull request closed without merging**
