### PR TITLE
add Jioswap 

### PR DESCRIPTION
**Pull request by dezzyboy**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

##### Twitter Link:
https://twitter.com/jioswap

##### Website Link:
https://jioswap.finance

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://app.jioswap.finance/static/media/logo.724338c6.svg
https://raw.githubusercontent.com/JioSwap/jio-logos/main/jioswap-logo.png
##### Current TVL:
200
##### Chain:
Godwoken

##### Short Description (to be shown on DefiLlama):
Jioswap is a cross-chain AMM protocol designed for trading stablecoins and tokenized crypto assets enabling low slippage and Interoperability between chains.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Cross Chain

##### forkedFrom (Does your project originate from another project):
Saddle Finance

##### methodology (what is being counted as tvl, how is tvl being calculated):
Counts as TVL all the Assets deposited on each chain through different Pool Contracts

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/jioswap exports TVL: 
        
 
 
    godwoken                  0
    
    total                    0

**Comment by dezzyboy** [comment]
hmm  this could be because [godwokenV1](https://startwithnervos.com/godwoken)  mainnet chainId(71402) is not added yet  , looks like only mainnetV0 chainId(71394)is added , in that case should i make a PR for the [chainlist extraRPC](https://github.com/DefiLlama/chainlist/blob/main/constants/extraRpcs.json) or should that be done by the nervos godwoken team

**Comment by dezzyboy** [comment]
update looks like godwoken chainid is the right one [here](https://github.com/DefiLlama/chainlist/blob/main/constants/chainIds.js)

**Comment by dezzyboy** [comment]
update: just added ported tokens to helpers  after tests tvl is now acurate

**Comment by llamatester** [comment]
Error while running adapter at projects/jioswap: 
        
 
  
    
    
    Error: invalid BigNumber string (argument="value", value="NaN", code=INVALID_ARGUMENT, version=bignumber/5.6.2)
    Truncated error stack:
        at Function.BigNumber.from (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/bignumber/lib/bignumber.js:199:27)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:335:16
        at Array.forEach (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:329:28)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:341:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:60:30)

**Comment by dezzyboy** [comment]
this seems to be an issue on godwoken only, although tvl was working when testing locally earlier , not anymore, i'll go ahead and remove godwoken for now for further investigation

**Comment by llamatester** [comment]
The adapter at projects/jioswap exports TVL: 
        
 
 
    godwoken_v1               199.98401
    meter                     67.993604
    
    total                    267.977614

**Comment by g1nt0ki** [comment]
> this seems to be an issue on godwoken only, although tvl was working when testing locally earlier , not anymore, i'll go ahead and remove godwoken for now for further investigation

the issue was, current godwoken is configured against v0 in sdk, looks like they have released a v1 just now, need to add it to sdk

**Pull request merged**
