### PR TITLE
update

### PR DESCRIPTION
**Pull request by LyveFinance**
Hello ! I want update Oracle  used
Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
pyth

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/lyve exports TVL: 
        
 
 
    linea                     52.34 k
    
    total                    52.34 k

**Comment by Define101** [comment]
@LyveFinance hello
Could you explain us how Pyth secures your TVL please?

**Comment by LyveFinance** [comment]
> you

We use it to query the prices of ETH and USDT, and based on the exchange rate, we calculate the collateralization ratio of LYU. Additionally, our pool's TVL calculation also utilizes it for price queries.
And you can check their official website; it's also a very outstanding Oracle。
please help us update it

**Comment by LyveFinance** [comment]
> @LyveFinance hello Could you explain us how Pyth secures your TVL please?
@Define101 
We use it to query the prices of ETH and USDT, and based on the exchange rate, we calculate the collateralization ratio of LYU. Additionally, our pool's TVL calculation also utilizes it for price queries.
And you can check their official website; it's also a very outstanding Oracle。
please help us update it

**Comment by Define101** [comment]
We will add it
Should be live in 2 hours

**Pull request closed without merging**
