### PR TITLE
add biconomy

### PR DESCRIPTION
**Pull request by flying-go**
Name (to be shown on DefiLlama):
Biconomy

Twitter Link:
https://x.com/BiconomyCom

List of audit links if any:
Website Link:
https://www.biconomy.com/

Logo (High resolution, will be shown with rounded borders):

Current TVL:
total 12.93 M USDT
ethereum 1.24 M https://etherscan.io/address/0xb03eDB668008459B3c6D948ab5Ab305581DbF69c
bitcoin 1.48 M https://www.blockchain.com/explorer/addresses/btc/bc1qx70fn2550vhjetc748wmg4lzv5gy7t56ns92v8
tron 0.11 M https://tronscan.org/#/address/TEi2hVWDRMo61PAoi1Dwbn8hNXufkwEVyp
Polygon 10.10 M https://polygonscan.com/address/0x366ba28Ec89113454EA6e82bB606426e8cA22780

Treasury Addresses (if the protocol has treasury)
Chain:
Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed):
[Biconomy](https://www.coingecko.com/en/exchanges/biconomy-com) https://www.coingecko.com/en/exchanges/biconomy-com

Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed):
[Biconomy](https://coinmarketcap.com/exchanges/biconomy/)
https://coinmarketcap.com/exchanges/biconomy/

Short Description (to be shown on DefiLlama):
Biconomy is a global digital asset trading platform. We are proud to provide fully transparent trading, listing, and digital asset development services. Thanks to every user for their support to us, please look forward to Biconomy's innovative products!

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/biconomy exports TVL: 
        
 
 
    bitcoin                   1.47 M
    ethereum                  1.23 M
    tron                      108.80 k
    polygon                   4.57 k
    
    total                    2.81 M

**Comment by llamatester** [comment]
Error while running adapter at projects/biconomy: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:200:11
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
The adapter at projects/biconomy exports TVL: 
        
 
 
    polygon                   10.06 M
    bitcoin                   1.47 M
    ethereum                  1.23 M
    tron                      109.09 k
    
    total                    12.86 M

**Comment by g1nt0ki** [comment]
thanks for the PR, I made a new listing for CEX part, but excluded EGX from tvl because it has 17B FDV but very low liquidity and chart looks like this: 
image

**Comment by flying-go** [comment]
Could you please update our name from 'Biconomy Cex' to 'Biconomy.com'?

**Pull request closed without merging**
