### PR TITLE
update btcfi contracts

### PR DESCRIPTION
**Pull request by tlatkdgus1**
##### Github org/user (Optional, if your code is open source, we can track activity): (edited)

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/btcfi exports TVL: 
        
 
 
    bfc                       6.66 M
    
    total                    6.66 M

**Comment by tlatkdgus1** [comment]
Hello DefiLlama Team!

BtcUSD is officially live on mainnet so could you kindly change the BTCFi's category to CDP?

**Comment by g1nt0ki** [comment]
hi @tlatkdgus1 think it is better to create a new sublisting for this, maybe can call this "BTCFi - BtcUSD" ? and the adapter can be named 'btcfi-btcusd/index.js'?

Also, is the cdp code forked from some other project or built in house?

**Comment by tlatkdgus1** [comment]
> hi @tlatkdgus1 think it is better to create a new sublisting for this, maybe can call this "BTCFi - BtcUSD" ? and the adapter can be named 'btcfi-btcusd/index.js'?
> 
> Also, is the cdp code forked from some other project or built in house?

Is it possible to include BtcUSD under the BTCFi? (no sublisting)

and BtcUSD is Standard ERC20, Users stake their Bitcoin and they can mint BtcUSD by using their staked Bitcoin.
The way it works is similar to MakerDao.

**Comment by tlatkdgus1** [comment]
> to be clear, I am proposing two sublistings under btcfi like we have for aave (https://defillama.com/protocol/aave), for for existing farm and other for the cdp. Yeah, I understand how BtcUSD works, was just a title suggestion :)

Thanks :) 

I'll talk with my team tomorrow and get back to you!

**Comment by tlatkdgus1** [comment]
Hi! @g1nt0ki !

I talked with our team and we have two question. 
You provided us the AAVE on DefiLama, and we assume that there will be BTCFi and BtcUSD tab. In case of AAVE, there is a main AAVE and there different versions of AAVE next to main tab. 

If we decided to go with your proposal then will BtcUSD TVL included under BTCFi? Also, will BtcUSD page will only show the TVL of BtcUSD? Basically BTCFi page shows TVL, including BtcUSD and BtcUSD page only shows the TVL of BtcUSD. 

Lastly, we would like to add BtcUSD as stablecoin. Could you kindly let us know how to add BtcUSD under stablecoin page? 
 > https://defillama.com/stablecoins

**Comment by g1nt0ki** [comment]
yup, exactly, BTCFi will have two sub pages, one for farm (existing listing) & one for BTCUSD

**Comment by tlatkdgus1** [comment]
> yup, exactly, BTCFi will have two sub pages, one for farm (existing listing) & one for BTCUSD

Thanks :) I'll update it

and Is it possible to add btcusd to the stables?

**Comment by g1nt0ki** [comment]
@tlatkdgus1 @Define101 added it: https://defillama.com/stablecoin/bitcoin-usd

**Comment by g1nt0ki** [comment]
added cdp listing here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/87dd271f2ecb0d66bf8ac97a7d2360c58cf3a982

**Comment by tlatkdgus1** [comment]
> added cdp listing here: [87dd271](https://github.com/DefiLlama/DefiLlama-Adapters/commit/87dd271f2ecb0d66bf8ac97a7d2360c58cf3a982)

Thanks for your kindness ! :)

Is it possible to change the logo image and name?

Name: BtcUSD
Logo : https://assets.thebifrost.io/images/logo/btcusd.png

**Pull request closed without merging**
