### PR TITLE
Adding BVM network

### PR DESCRIPTION
**Pull request by elykct**
##### Name (to be shown on DefiLlama):
- BVM Network

##### Twitter Link:
- https://twitter.com/NewBitcoinCity

##### List of audit links if any:
- N/A

##### Website Link:
- https://bvm.network/

##### Logo (High resolution, will be shown with rounded borders):
- https://cdn.bvm.network/image/bvm-logo.png

##### Current TVL:
- 1.65M (NOS) + 698K (NAKA)

##### Chain:
- BVM Chain

##### Short Description (to be shown on DefiLlama):
```
BVM is the L2 blockchain meta-protocol, enabling builders to launch their own Bitcoin L2 that utilizes DA layer to solve scalability constraints on Bitcoin.
This approach allows BVM to function as a general-purpose state machine utilizing Bitcoin's security and data availability without additional network or consensus protocol.
```

##### Token address and ticker if any:
- ticker: BVM 
- address: 0x0000000000000000000000000000000000000000

##### Category (full list at https://defillama.com/categories) *Please choose only one:
- Chains

##### forkedFrom (Does your project originate from another project):
- No

##### methodology (what is being counted as tvl, how is tvl being calculated):
1) The BVM's TVL is the sum of Alpha-Chain's TVL (aka NOS https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/newbitcoin/index.js) and Naka-Chain's TVL.
2) The Naka Chain TVL represents the total volume of tokens its DEX (Uniswap v3 fork), including ETH, SATS, ORDI, and WBTC.

##### Github org/user (Optional, if your code is open source, we can track activity):
- N/A

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/bvm: 
        
 
  
    
    
    Error: 
        Unknown chain(s): bvm
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file
        
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:138:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:517:28)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
Error while running adapter at projects/bvm: 
        
 
  
    
    
    TypeError: chainTvl is not a function
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:139:41
        at Array.map (<anonymous>)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:64:29)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:160:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:143:44

**Comment by llamatester** [comment]
Error while running adapter at projects/bvm: 
        
 
  
    
    
    TypeError: chainTvl is not a function
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:139:41
        at Array.map (<anonymous>)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:64:29)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:160:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:143:44

**Comment by llamatester** [comment]
Error while running adapter at projects/bvm: 
        
 
  
    
    
    TypeError: chainTvl is not a function
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:139:41
        at Array.map (<anonymous>)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:64:29)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:160:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:143:44

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
why is chocoinu adapter deleted?

**Comment by khanhj** [comment]
> why is chocoinu adapter deleted?

Sorry my mistake with the out sync fork. Will restore it in next commit. Anyway can you guy check my code and merge please?

**Comment by llamatester** [comment]
Error while running adapter at projects/bvm: 
        
 
  
    
    
    TypeError: chainTvl is not a function
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:139:41
        at Array.map (<anonymous>)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:64:29)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:160:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:143:44

**Comment by llamatester** [comment]
Error while running adapter at projects/bvm: 
        
 
  
    
    
    TypeError: chainTvl is not a function
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:139:41
        at Array.map (<anonymous>)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:64:29)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:160:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:143:44

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
sorry for the late review, the PR has a few issues.

We cant count bridged token as tvl, if you share the bridge address on bitcoin/ethereum, we can track the tokens under bridge protocol. It wont count towards chain's tvl (neither source nor desitination)

For chain tvl, can you share naka chain rpc? I can create a listing for uni v3 fork there, and this will show up as chain tvl

**Comment by g1nt0ki** [comment]
"Taking Arbitrum and BVM as the same case, I think BTC, ETH, USDT, and other valuable assets are bridged to and locked within BVM's smart contract, they should be accounted for in the TVL of BVM network."

but we dont count all bridged assets to arbitrum as their tvl? Please check 0xngmi's answer https://github.com/DefiLlama/DefiLlama-Adapters/discussions/435

**Comment by llamatester** [comment]
Error while running adapter at projects/bvm: 
        
 
  
    
    
    TypeError: chainTvl is not a function
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:139:41
        at Array.map (<anonymous>)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:67:29)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:163:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:151:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:146:44

**Comment by llamatester** [comment]
Error while running adapter at projects/bvm: 
        
 
  
    
    
    TypeError: Cannot read properties of null (reading 'getBlock')
    Truncated error stack:
        at _getCurrentChainBlock (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/blocks.js:84:59)

**Comment by llamatester** [comment]
The adapter at projects/naka-dex exports TVL: 
        
 
 
    naka                      272.48 k
    
    total                    272.48 k

**Comment by g1nt0ki** [comment]
hi @elykct is naka & nos, l2 of bitcoin or side chain/part of bvm, sorry, it cant be both. Dex tvl of nos is already counted as part of "Alpha", so updated adapter to count this tvl under "naka dex"

**Comment by llamatester** [comment]
The adapter at projects/naka-dex exports TVL: 
        
 
 
    naka                      271.85 k
    
    total                    271.85 k

**Comment by g1nt0ki** [comment]
also, how is the ethereum bridged to naka chain?

**Pull request merged**
