### PR TITLE
BusinessBuildersNFTs adapter

### PR DESCRIPTION
**Pull request by ctrlProgrammer**
##### Short Description (to be shown on DefiLlama): 

BusinessBuildersNFTs is a ecosystem based on the blockcchain and NFTs technologies. You can build your own city, create your own business hiring and firing employees and create your own community in our DAPPs. We created an scalable ecosystem including new projects and integrations little by little improving the main project sustainability. 

##### Token address and ticker if any: 

[Meter] - 0x6cfe9adad5215195c1aa9755daed29360e6ab986
[Polygon] - 0xf305012ea754252184f1071c86ae99fac5b40320

##### methodology (what is being counted as tvl, how is tvl being calculated): 

Staking: we include locked tokens on the rewards contracts as staking.
Pool2: Relation between liquidity, token value and total tokens on the liquidity pools.
TVL: Based on the staking and pool2 summation including rewards storage and market liquidity tokens.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/business-builders-nfts exports TVL: 
        
 
 
    polygon-pool2             11.73 k
    polygon-staking           42.17 k
    polygon                   53.90 k
    meter-staking             37.09 k
    meter-pool2               8.31 k
    meter                     45.40 k
    pool2                     20.04 k
    staking                   79.26 k
    
    total                    99.30 k

**Comment by llamatester** [comment]
The adapter at projects/business-builders-nfts exports TVL: 
        
 
 
    polygon-pool2             11.87 k
    polygon-staking           42.69 k
    polygon                   54.56 k
    meter                     45.73 k
    meter-staking             37.36 k
    meter-pool2               8.37 k
    pool2                     20.24 k
    staking                   80.05 k
    
    total                    100.29 k

**Comment by llamatester** [comment]
The adapter at projects/business-builders-nfts exports TVL: 
        
 
 
    polygon                   0
    polygon-staking           45.34 k
    meter-staking             38.93 k
    staking                   84.26 k
    
    total                    0

**Comment by g1nt0ki** [comment]
@ctrlProgrammer we cant count pool2 unless the LP tokens are staked in contracts owned by your team

tvl will be zero in this case, users have option to enable staking and include it under overall tvl.

If you are fine with the changes, we can merge and list it

**Comment by ctrlProgrammer** [comment]
@g1nt0ki sure, it is really cool. Im agree. Maybe you can add the specification on the documentation for the new users.

Thanks a lot for the help.

**Pull request merged**
