### PR TITLE
XY Finance: Add STUCK token config

### PR DESCRIPTION
**Pull request by coolryanc**
Hi DL team @g1nt0ki , we would like to add STUCK token config, could you please help review the PR. Many thanks 🙏

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/xy-finance exports TVL: 
        
 
 
    optimism                  781.17 k
    bsc                       777.26 k
    era                       758.35 k
    ethereum                  744.68 k
    arbitrum                  446.87 k
    polygon                   371.10 k
    linea                     321.73 k
    taiko                     305.15 k
    mantle                    280.46 k
    cronos                    278.81 k
    polygon_zkevm             244.70 k
    scroll                    220.75 k
    blast                     187.38 k
    xlayer                    148.76 k
    avax                      70.10 k
    kcc                       47.73 k
    astar                     17.43 k
    moonriver                 51
    klaytn                    32
    thundercore               15
    base                      14
    ox_chain                  0
    fantom                    0
    wemix                     0
    
    total                    6.00 M

**Comment by g1nt0ki** [comment]
hi, the STUCK in base, how is it bridged in the first place? or is it locked on cronos and minted on base through xy contract?

**Comment by g1nt0ki** [comment]
hmm, then we cant count it on base side, can you go through the config and remove similar tokens? :pray: 

the reason is, we are already counting the token on source chain

**Comment by g1nt0ki** [comment]
merged here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/11224

**Pull request closed without merging**
