### PR TITLE
Factor leverage vault

### PR DESCRIPTION
**Pull request by dimasriat**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Factor (Leverage Vault)

##### Twitter Link:
https://x.com/FactorDAO

##### List of audit links if any:
N/A

##### Website Link:
https://app.factor.fi/studio

##### Logo (High resolution, will be shown with rounded borders):
https://icons.llamao.fi/icons/protocols/factor-v2

##### Current TVL:
$ 21.26K (Total)

##### Treasury Addresses (if the protocol has treasury)
N/A

##### Chain:
Arbitrum

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed):
factor

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): 
factor

##### Short Description (to be shown on DefiLlama):
Factor Leverage Vault is one-click looping, easy switching, easy migration, easy auto-compounding the reward

##### Token address and ticker if any:
N/A

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Leveraged Farming

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
N/A

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is being counted by summing collateral and debt used to add leverage

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/factor-leverage-vault exports TVL: 
        
 
 
    arbitrum                  1.15 k
    
    total                    1.15 k

**Comment by llamatester** [comment]
The adapter at projects/factor-leverage-vault exports TVL: 
        
 
 
    arbitrum                  1.15 k
    
    total                    1.15 k

**Comment by llamatester** [comment]
The adapter at projects/factor-leverage-vault exports TVL: 
        
 
 
    arbitrum                  290.4553434640287
    
    total                    290.4553434640287

**Comment by g1nt0ki** [comment]
@dimasriat thanks for the PR, most of my changes are code refactoring to use our internal library, major change is, instead of adding debt, subtracted it from tvl.

If you are fine with the changes, I can merge and list this

**Comment by dimasriat** [comment]
> @dimasriat thanks for the PR, most of my changes are code refactoring to use our internal library, major change is, instead of adding debt, subtracted it from tvl.
> 
> If you are fine with the changes, I can merge and list this

LGTM 👍

**Pull request merged**
