### PR TITLE
added AITECHs adapter

### PR DESCRIPTION
**Pull request by mj-dcb**
##### Short Description (to be shown on DefiLlama):
Solidus has successfully constructed an environmentally conscious, state-of-the-art High-Performance Computing (HPC) Data Centre spanning over 8,000 square feet. This facility is strategically situated in a highly secure European location. In conjunction with this remarkable achievement, Solidus is poised to unveil the world's pioneering deflationary Artificial Intelligence token, known as AITECH. This token will serve as a payment gateway for licensing Artificial Intelligence as a Service (AIaaS), Blockchain as a Service (BaaS), and accessing HPC resources via their Infrastructure as a Service (IaaS) platform.

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/aitech: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by llamatester** [comment]
Error while running adapter at projects/aitech: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by llamatester** [comment]
Error while running adapter at projects/aitech: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:11

**Comment by mj-dcb** [comment]
@g1nt0ki how can I fix this issue?

**Comment by llamatester** [comment]
The adapter at projects/aitech exports TVL: 
        
 
 
    bsc                       0
    bsc-staking               136.23 k
    staking                   136.23 k
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/aitech exports TVL: 
        
 
 
    bsc                       135.73 k
    
    total                    135.73 k

**Comment by llamatester** [comment]
The adapter at projects/aitech exports TVL: 
        
 
 
    bsc                       0
    bsc-staking               135.96 k
    staking                   135.96 k
    
    total                    0

**Pull request merged**
