### PR TITLE
[JPEGd] – TVL update

### PR DESCRIPTION
**Pull request by 0xleez**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/jpeg-d exports TVL: 
        
 
 
    ethereum-staking          650.40 k
    ethereum-pool2            2.42 M
    ethereum                  50.64 M
    staking                   650.40 k
    pool2                     2.42 M
    
    total                    50.64 M

**Comment by g1nt0ki** [comment]
Hi @0xleez , thanks for the PR.

I have refactored it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/5770

Moved locked jpeg to staking, moved curve auto compounding to pool2, also sorry, we consider only floor price while valuing nfts

**Comment by g1nt0ki** [comment]
@0xleez sorry, I am out right now and answering from my phone, 
Reasoning for my changes: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

- sorry, we can still discuss, revert my changes but you have to understand from my pov, I have to review lot of PRs and add new adapters, fix broken ones, very little time

- multiplier is relevant to you for lending/minting, but we can't have different logic for evaluating nfts on paraspace/sudoswap and you
- tvl is no reflection on how your protocol operates, the tokens are in curve count towards their tvl, we let users decide if they want to include this in yours through pool2 filter
-staking is a bad term, it is the closest we have to own tokens, the reason we split it is explained in the doc

I was not trying to be dismissive, I am open to discussion

**Comment by g1nt0ki** [comment]
@0xleez again, sorry about this. personally I would have kept this PR open until we reach an agreement, but github automatically closes PRs once the commits in them are already part of other branch, useful in most cases, but unfortunate in this case.

Thats why I came back and left a comment.

**Comment by 0xleez** [comment]
@g1nt0ki all good, apologies for the late reply

* re multipliers, nfts are non-fungible so it makes sense to value rare traits higher. on top of that defillama adapters mechanism is open source to allow protocols to calculate the tvl based on their mechanics, why make it open source if you end up deciding what value is locked in a protocol? on defillama floors are unified across platforms due to pricing being provided, but what's the point in unifying rare nft valuations across platforms? the product is live, it works, people are using it as it is and there's no assumption regarding the multiplier. on top of that, the multipliers are closer to the real valuation than the floor.

* re locked jpeg, this is a utility token in this context, it enables higher ltv and trait boosts for nfts. so it's more similar to how locked cvx works except it doesn't have the receipt token (vlCVX). so this is far from staking, also because there's no staking reward.

* re pETH LP tvl. From your docs `Pool2 - staked LP tokens where one side of the market is the platform's own governance token.` – pETH is not the governance token. Besides that, DeFi is composable – if users deposit on the JPEGd platform, it's up to the protocol to decide what strategy it's using behind to make those assets productive, and regardless of the strategy used it doesn't mean the value is not deposited in the JPEGd protocol by the users. Showing the pETH tvl either as pool2 or convex only is wrong in my opinion. On that note, the assets deposited in the convex gauges get deposited on curve – why is the tvl in those gauges also shown as being part of the convex tvl?

imo having an open system means letting protocols implement a reflection of their tvl as it is, not dictate what is part of the tvl based on your own definition. hope this clears things out.

**Comment by 0xleez** [comment]
@g1nt0ki looking forward to hearing your opinion

**Comment by 0xleez** [comment]
@g1nt0ki @0xngmi pinging to see if there's a way we can clarify this

**Comment by g1nt0ki** [comment]
* "why make it open source if you end up deciding what value is locked in a protocol?" Sorry, this is a bad line of argument, all protocols prefer higher tvl and have their own definition of what is tvl, remember the sovryn saga? I agree that some people value some traits higher, but I dont like the idea of doing it just for one protocol/few nft types, also I have not seen any other nft fi project request for this, if more projects/users ask for this, we can revisit and fix this, till then, the answer is no.


* nice comparison with cvx locking, if you check convex, we dont include locked cvx under tvl but under 'staking

* pETH is not gov token, but value of NFTs backing pETH is already counted as part of tvl, then isnt it double counting? we count gauge tvl in convex because that is their product, and we dont count it towards chain tvl as underlying tvl is already counted for curve. We can reach a compromise here and count the value of only the ETH part of the  deposited gauge/LP tokens. would that work for you?

**Comment by 0xleez** [comment]
@g1nt0ki Sure, that works. thank you

**Pull request merged**
