### PR TITLE
List Energyfy Dex project in TVL Listing

### PR DESCRIPTION
**Pull request by abhishekwin**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
energyfi

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
NA

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@abhishekwin thanks for the PR, can you please fill in the project details.

**Comment by llamatester** [comment]
The adapter at projects/energyfi exports TVL: 
        
 
 
    moonbeam                  108.84 k
    
    total                    108.84 k

**Comment by llamatester** [comment]
The adapter at projects/energyfi exports TVL: 
        
 
 
    moonbeam-ownTokens        110.07 k
    moonbeam                  108.63 k
    ownTokens                 110.07 k
    
    total                    108.63 k

**Comment by abhishekwin** [comment]
> @abhishekwin thanks for the PR, can you please fill in the project details.

**Comment by llamatester** [comment]
The adapter at projects/energyfi exports TVL: 
        
 
 
    moonbeam                  103.28 k
    
    total                    103.28 k

**Pull request merged**
