### PR TITLE
added perion to treasury

### PR DESCRIPTION
**Pull request by Jett19672**
**NOTE**

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):    

whitePERC

blackPERC

##### Short Description (to be shown on DefiLlama): 
Perion is a multifaceted DAO on a mission to back and build next generation products and teams at the intersect of web3, eSports, gaming and NFTs. We see web3 as being synonymous with the future of gaming and culture, a future that we will build upon utilitarian web3 technology.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/treasury/perion.js exports TVL: 
        
 
 
    ethereum-ownTokens        11.22 M
    ethereum                  17.74 M
    ownTokens                 11.22 M
    
    total                    17.74 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/alchemix.js exports TVL: 
        
 
 
    ethereum-ownTokens        6.11 M
    ethereum                  12.93 k
    ownTokens                 6.11 M
    
    total                    12.93 k

**Comment by llamatester** [comment]
The adapter at projects/treasury/alpacacity.js exports TVL: 
        
 
 
    bsc-ownTokens             12.22 k
    bsc                       1.58 k
    ethereum-ownTokens        25.61 k
    ethereum                  1.54 k
    ownTokens                 37.82 k
    
    total                    3.12 k

**Comment by llamatester** [comment]
The adapter at projects/treasury/augury.js exports TVL: 
        
 
 
    polygon                   18.81 k
    polygon-ownTokens         1.24 k
    ownTokens                 1.24 k
    
    total                    18.81 k

**Comment by llamatester** [comment]
The adapter at projects/treasury/balancer.js exports TVL: 
        
 
 
    ethereum-ownTokens        36.87 M
    ethereum                  1.55 M
    ownTokens                 36.87 M
    
    total                    1.55 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/bankofcronos.js exports TVL: 
        
 
 
    cronos-ownTokens          0
    cronos                    1.918453
    ownTokens                 0
    
    total                    1.918453

**Comment by llamatester** [comment]
The adapter at projects/treasury/beanstalk.js exports TVL: 
        
 
 
    ethereum-ownTokens        1.47 M
    ethereum                  128.35 k
    ownTokens                 1.47 M
    
    total                    128.35 k

**Comment by llamatester** [comment]
The adapter at projects/treasury/beefy.js exports TVL: 
        
 
 
    arbitrum-ownTokens        35.29 k
    moonriver-ownTokens       9.87 k
    avax-ownTokens            31.99 k
    heco-ownTokens            39.68624857543619
    harmony-ownTokens         0
    polygon                   62.40 k
    polygon-ownTokens         34.49 k
    avax                      33.76 k
    fantom                    3.88 k
    ethereum                  221.78 k
    bsc-ownTokens             88.43 k
    fantom-ownTokens          113.72 k
    moonriver                 11.87 k
    arbitrum                  53.74 k
    ethereum-ownTokens        0
    metis-ownTokens           0
    heco                      1.74 k
    optimism-ownTokens        0
    metis                     23.71 k
    harmony                   147.4743
    bsc                       115.92 k
    optimism                  1.01 M
    ownTokens                 313.83 k
    
    total                    1.54 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/benqi.js exports TVL: 
        
 
 
    avax                      824.33 k
    avax-ownTokens            24.07 M
    ownTokens                 24.07 M
    
    total                    824.33 k

**Comment by llamatester** [comment]
The adapter at projects/treasury/bitdao.js exports TVL: 
        
 
 
    ethereum                  761.55 M
    ethereum-ownTokens        1.84 B
    ownTokens                 1.84 B
    
    total                    761.55 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/convex.js exports TVL: 
        
 
 
    ethereum                  57.74 k
    ethereum-ownTokens        8.74 M
    ownTokens                 8.74 M
    
    total                    57.74 k

**Comment by llamatester** [comment]
The adapter at projects/treasury/dodo.js exports TVL: 
        
 
 
    ethereum-ownTokens        0
    ethereum                  425.58 k
    ownTokens                 0
    
    total                    425.58 k

**Comment by llamatester** [comment]
The adapter at projects/treasury/dydx.js exports TVL: 
        
 
 
    ethereum                  0
    ethereum-ownTokens        95.74 M
    ownTokens                 95.74 M
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/treasury/euler.js exports TVL: 
        
 
 
    ethereum-ownTokens        59.67 M
    ethereum                  27.27 M
    ownTokens                 59.67 M
    
    total                    27.27 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/floor-dao.js exports TVL: 
        
 
 
    ethereum                  444.26 k
    ethereum-ownTokens        569.56 k
    ownTokens                 569.56 k
    
    total                    444.26 k

**Comment by llamatester** [comment]
The adapter at projects/treasury/frax.js exports TVL: 
        
 
 
    ethereum                  163.959
    ethereum-ownTokens        62.29 M
    ownTokens                 62.29 M
    
    total                    163.959

**Comment by llamatester** [comment]
The adapter at projects/treasury/gyro.js exports TVL: 
        
 
 
    bsc-ownTokens             0
    bsc                       20.92 k
    ownTokens                 0
    
    total                    20.92 k

**Comment by llamatester** [comment]
The adapter at projects/treasury/index-coop.js exports TVL: 
        
 
 
    ethereum-ownTokens        3.96 M
    ethereum                  74.00666896119522
    ownTokens                 3.96 M
    
    total                    74.00666896119522

**Comment by llamatester** [comment]
The adapter at projects/treasury/inverse.js exports TVL: 
        
 
 
    optimism-ownTokens        0
    bsc-ownTokens             0
    bsc                       3.93 k
    ethereum-ownTokens        3.06 M
    optimism                  46.66 k
    ethereum                  1.25 M
    ownTokens                 3.06 M
    
    total                    1.30 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/jonesdao.js exports TVL: 
        
 
 
    arbitrum-ownTokens        16.83 M
    arbitrum                  1.85 M
    ownTokens                 16.83 M
    
    total                    1.85 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/jpegd.js exports TVL: 
        
 
 
    ethereum-ownTokens        19.37 M
    ethereum                  35.62 M
    ownTokens                 19.37 M
    
    total                    35.62 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/keeperdao.js exports TVL: 
        
 
 
    ethereum-ownTokens        2.49 M
    ethereum                  40.99 M
    ownTokens                 2.49 M
    
    total                    40.99 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/klima-dao.js exports TVL: 
        
 
 
    polygon-ownTokens         0
    polygon                   42.99 M
    ownTokens                 0
    
    total                    42.99 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/lido.js exports TVL: 
        
 
 
    ethereum-ownTokens        337.71 M
    ethereum                  61.55 M
    ownTokens                 337.71 M
    
    total                    61.55 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/liquity-treasury.js exports TVL: 
        
 
 
    ethereum-ownTokens        984.82 k
    ethereum                  424.66 k
    optimism                  3.27 k
    ownTokens                 984.82 k
    
    total                    427.92 k

**Comment by llamatester** [comment]
The adapter at projects/treasury/mimo-protocol.js exports TVL: 
        
 
 
    polygon                   0
    fantom                    0
    ethereum-ownTokens        502.22 k
    ethereum                  87.73 k
    ownTokens                 502.22 k
    
    total                    87.73 k

**Comment by llamatester** [comment]
The adapter at projects/treasury/mstable.js exports TVL: 
        
 
 
    ethereum-ownTokens        312.07 k
    ethereum                  395.83 k
    ownTokens                 312.07 k
    
    total                    395.83 k

**Comment by llamatester** [comment]
The adapter at projects/treasury/nemesis.js exports TVL: 
        
 
 
    bsc-ownTokens             0
    bsc                       0.44568550116374167
    ownTokens                 0
    
    total                    0.44568550116374167

**Comment by llamatester** [comment]
The adapter at projects/treasury/nexus-mutual.js exports TVL: 
        
 
 
    ethereum-ownTokens        19.20 M
    ethereum                  67.51 k
    ownTokens                 19.20 M
    
    total                    67.51 k

**Comment by llamatester** [comment]
The adapter at projects/treasury/olympus-dao.js exports TVL: 
        
 
 
    ethereum-ownTokens        2.08 M
    ethereum                  5.70 M
    ownTokens                 2.08 M
    
    total                    5.70 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/paladin-finance.js exports TVL: 
        
 
 
    ethereum-ownTokens        9.88 M
    ethereum                  55.21 k
    ownTokens                 9.88 M
    
    total                    55.21 k

**Comment by llamatester** [comment]
The adapter at projects/treasury/perpetual-protocol.js exports TVL: 
        
 
 
    ethereum-ownTokens        1.86 M
    ethereum                  1.67 M
    ownTokens                 1.86 M
    
    total                    1.67 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/rarible.js exports TVL: 
        
 
 
    ethereum-ownTokens        20.71 M
    ethereum                  9.30 M
    ownTokens                 20.71 M
    
    total                    9.30 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/shapeshift.js exports TVL: 
        
 
 
    ethereum-ownTokens        8.01 M
    ethereum                  1.54 M
    ownTokens                 8.01 M
    
    total                    1.54 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/spartacus.js exports TVL: 
        
 
 
    fantom-ownTokens          0
    fantom                    14.29 M
    ownTokens                 0
    
    total                    14.29 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/spookyswap.js exports TVL: 
        
 
 
    fantom-ownTokens          339.35 k
    fantom                    583.65 k
    ownTokens                 339.35 k
    
    total                    583.65 k

**Comment by llamatester** [comment]
The adapter at projects/treasury/sushiswap.js exports TVL: 
        
 
 
    ethereum                  485.02 k
    ethereum-ownTokens        17.76 M
    ownTokens                 17.76 M
    
    total                    485.02 k

**Comment by llamatester** [comment]
The adapter at projects/treasury/synthetix.js exports TVL: 
        
 
 
    ethereum-ownTokens        75.53 M
    ethereum                  6.23 M
    ownTokens                 75.53 M
    
    total                    6.23 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/traderjoe.js exports TVL: 
        
 
 
    avax-ownTokens            30.60 M
    avax                      2.05 k
    ownTokens                 30.60 M
    
    total                    2.05 k

**Comment by llamatester** [comment]
The adapter at projects/treasury/uniswap.js exports TVL: 
        
 
 
    ethereum-ownTokens        2.93 B
    ethereum                  2.7247513276728017
    ownTokens                 2.93 B
    
    total                    2.7247513276728017

**Comment by llamatester** [comment]
The adapter at projects/treasury/uwulend.js exports TVL: 
        
 
 
    ethereum                  2.09 M
    
    total                    2.09 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/venus.js exports TVL: 
        
 
 
    bsc-ownTokens             289.03 k
    bsc                       3.92 M
    ownTokens                 289.03 k
    
    total                    3.92 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/wonderland.js exports TVL: 
        
 
 
    avax-ownTokens            0
    polygon                   0
    avax                      189.64 k
    arbitrum                  73.61 k
    ethereum                  19.55 M
    ownTokens                 0
    
    total                    19.82 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/yearn.js exports TVL: 
        
 
 
    ethereum-ownTokens        150.34 k
    ethereum                  5.09 M
    ownTokens                 150.34 k
    
    total                    5.09 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/perion.js exports TVL: 
        
 
 
    ethereum-ownTokens        11.22 M
    ethereum                  6.52 M
    ownTokens                 11.22 M
    
    total                    6.52 M

**Comment by g1nt0ki** [comment]
@Nemusonaneko @Define101 I have removed `ownTokenOwners` field, it is only needed if you have addresses with own tokens not already part of `owners` field

**Pull request merged**
