### PR TITLE
Updating TVL calculation to include Pylon

### PR DESCRIPTION
**Pull request by VittoriDavide**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
Updating Adapter to show Liquidity held in our Pylon Systems, currently only showing the liquidity on the Pairs

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
zircon-gamma-token

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/zircon-gamma: 
        
 
  
    
    
    TypeError: Cannot convert a BigInt value to a number
    Truncated error stack:
        at isValidNumber (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:118:56)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/zircon-gamma/index.js:25:37
        at Array.forEach (<anonymous>)
        at fetch (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/zircon-gamma/index.js:25:10)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:51:25)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:146:9
        at async Promise.all (index 0)
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
The adapter at projects/zircon-gamma exports TVL: 
        
 
 
    moonriver                 171.60 k
    
    total                    171.60 k

**Comment by realdealshaman** [comment]
@VittoriDavide Hi, thank you for the PR, are the Pylon tokens the same as the LP tokens received for adding liquidity to the Dex?

**Comment by VittoriDavide** [comment]
The Pylon is an intermediary system that enables single sided liquidity, so it keeps the LP Tokens from the Pair and give another LP Token to the user depending on the selected side. But yes the pylon contains the same tokens as the pair. 

Here is an example: 
Pair: [0x89BB1bd89c764e1C2d4AA6469062590732B26323](https://moonriver.moonscan.io/address/0x89bb1bd89c764e1c2d4aa6469062590732b26323#tokentxns)

Pylon: [0xF8aF5f7F2D1a2E17295f99EbAcC1054ddfCD7782](https://moonriver.moonscan.io/address/0xF8aF5f7F2D1a2E17295f99EbAcC1054ddfCD7782#tokentxns)

**Comment by realdealshaman** [comment]
@VittoriDavide  Thank you for the information about Pylon. Unfortunately, we cannot add Pylon as tvl as it would lead to double-counting. We have made similar decisions in the past for other protocols

**Comment by VittoriDavide** [comment]
Hi @realdealshaman the tokens contained in the pylon are different reserves that the one contained in the pair, what would lead this to double counting ?

**Comment by VittoriDavide** [comment]
The LP Tokens contained by the pylon are received once the Pylon adds liquidity to the pair

**Comment by lamagt** [comment]
hi @realdealshaman I think we haven't been super clear about this. We don't want all Pylon liquidity to be counted, only the non-LP token reserves. These can be up to 40% of the pool's total liquidity and it's where most of the deposits go through before being matched with each other and sent into the pool. It's not double-counted by any means

**Comment by llamatester** [comment]
The adapter at projects/zircon-gamma exports TVL: 
        
 
 
    moonriver                 282.83 k
    
    total                    282.83 k

**Comment by g1nt0ki** [comment]
@VittoriDavide @lamagt I am closing this as I have fixed it here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/c1467063f932470bffde396f5429cd2b4d5a5505

I am using logs instead of relying on graph

**Comment by VittoriDavide** [comment]
thanks 👍

**Comment by VittoriDavide** [comment]
Hello @g1nt0ki, I have been attempting to use the same method for BSC, but it is failing miserably. Would you happen to know what might be causing this?

`Error: failed to meet quorum (method="getLogs", params={"filter":{"fromBlock":"0x18a3c9a","toBlock":"0x18a417c","address":"0x05d5E46F9d17591f7eaCdfE43E3d6a8F789Df698","topics":["0xab83557b3a718996d408afe08287d09bafed3590c7ae61a430d518d3199d4590"]}}, results=[{"weight":1,"start":1677148316850,"error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":58,\"error\":{\"code\":-32005,\"message\":\"limit exceeded\"}}","error":{"code":-32005},"requestBody":"{\"method\":\"eth_getLogs\",\"params\":[{\"fromBlock\":\"0x18a3c9a\",\"toBlock\":\"0x18a417c\",\"address\":\"0x05d5e46f9d17591f7eacdfe43e3d6a8f789df698\",\"topics\":[\"0xab83557b3a718996d408afe08287d09bafed3590c7ae61a430d518d3199d4590\"]}],\"id\":58,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://bsc-dataseed.binance.org/"}},{"weight":1,"start":1677148317601,"error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":50,\"error\":{\"code\":-32005,\"message\":\"limit exceeded\"}}","error":{"code":-32005},"requestBody":"{\"method\":\"eth_getLogs\",\"params\":[{\"fromBlock\":\"0x18a3c9a\",\"toBlock\":\"0x18a417c\",\"address\":\"0x05d5e46f9d17591f7eacdfe43e3d6a8f789df698\",\"topics\":[\"0xab83557b3a718996d408afe08287d09bafed3590c7ae61a430d518d3199d4590\"]}],\"id\":50,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://bsc-dataseed1.defibit.io/"}},{"weight":1,"start":1677148318351,"error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":49,\"error\":{\"code\":-32005,\"message\":\"limit exceeded\"}}","error":{"code":-32005},"requestBody":"{\"method\":\"eth_getLogs\",\"params\":[{\"fromBlock\":\"0x18a3c9a\",\"toBlock\":\"0x18a417c\",\"address\":\"0x05d5e46f9d17591f7eacdfe43e3d6a8f789df698\",\"topics\":[\"0xab83557b3a718996d408afe08287d09bafed3590c7ae61a430d518d3199d4590\"]}],\"id\":49,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://bsc-dataseed1.ninicoin.io/"}},{"weight":1,"start":1677148319101,"error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":49,\"error\":{\"code\":-32005,\"message\":\"limit exceeded\"}}","error":{"code":-32005},"requestBody":"{\"method\":\"eth_getLogs\",\"params\":[{\"fromBlock\":\"0x18a3c9a\",\"toBlock\":\"0x18a417c\",\"address\":\"0x05d5e46f9d17591f7eacdfe43e3d6a8f789df698\",\"topics\":[\"0xab83557b3a718996d408afe08287d09bafed3590c7ae61a430d518d3199d4590\"]}],\"id\":49,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://bsc-dataseed2.defibit.io/"}},{"weight":1,"start":1677148319851,"error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":49,\"error\":{\"code\":-32005,\"message\":\"limit exceeded\"}}","error":{"code":-32005},"requestBody":"{\"method\":\"eth_getLogs\",\"params\":[{\"fromBlock\":\"0x18a3c9a\",\"toBlock\":\"0x18a417c\",\"address\":\"0x05d5e46f9d17591f7eacdfe43e3d6a8f789df698\",\"topics\":[\"0xab83557b3a718996d408afe08287d09bafed3590c7ae61a430d518d3199d4590\"]}],\"id\":49,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://bsc-dataseed2.ninicoin.io/"}}], provider={"_isProvider":true,"_events":[],"_emitted":{"block":-2},"disableCcipRead":false,"formatter":{"formats":{"transaction":{},"transactionRequest":{},"receiptLog":{},"receipt":{},"block":{},"blockWithTransactions":{},"filter":{},"filterLog":{}}},"anyNetwork":false,"_network":{"name":"bsc","chainId":56},"_maxInternalBlockNumber":25913867,"_lastBlockNumber":-2,"_maxFilterBlockRange":10,"_pollingInterval":4000,"_fastQueryDate":1677148309558,"providerConfigs":[{"provider":{"_isProvider":true,"_events":[],"_emitted":{"block":-2},"disableCcipRead":false,"formatter":{"formats":{"transaction":{},"transactionRequest":{},"receiptLog":{},"receipt":{},"block":{},"blockWithTransactions":{},"filter":{},"filterLog":{}}},"anyNetwork":false,"_network":{"name":"bsc","chainId":56},"_maxInternalBlockNumber":25913869,"_lastBlockNumber":-2,"_maxFilterBlockRange":10,"_pollingInterval":4000,"_fastQueryDate":1677148317741,"connection":{"url":"https://bsc-dataseed.binance.org/"},"_nextId":59,"_eventLoopCache":{"eth_blockNumber":null},"_internalBlockNumber":{},"_fastBlockNumber":25913869,"_fastBlockNumberPromise":{}},"priority":0,"stallTimeout":750,"weight":1},{"provider":{"_isProvider":true,"_events":[],"_emitted":{"block":25913868},"disableCcipRead":false,"formatter":{"formats":{"transaction":{},"transactionRequest":{},"receiptLog":{},"receipt":{},"block":{},"blockWithTransactions":{},"filter":{},"filterLog":{}}},"anyNetwork":false,"_network":{"name":"bsc","chainId":56},"_maxInternalBlockNumber":25913869,"_lastBlockNumber":25913868,"_maxFilterBlockRange":10,"_pollingInterval":4000,"_fastQueryDate":1677148317779,"connection":{"url":"https://bsc-dataseed1.defibit.io/"},"_nextId":51,"_eventLoopCache":{"eth_blockNumber":null},"_internalBlockNumber":{},"_poller":null,"_bootstrapPoll":null,"_fastBlockNumber":25913869,"_fastBlockNumberPromise":{}},"priority":1,"stallTimeout":750,"weight":1},{"provider":{"_isProvider":true,"_events":[],"_emitted":{"block":25913869},"disableCcipRead":false,"formatter":{"formats":{"transaction":{},"transactionRequest":{},"receiptLog":{},"receipt":{},"block":{},"blockWithTransactions":{},"filter":{},"filterLog":{}}},"anyNetwork":false,"_network":{"name":"bsc","chainId":56},"_maxInternalBlockNumber":25913870,"_lastBlockNumber":25913869,"_maxFilterBlockRange":10,"_pollingInterval":4000,"_fastQueryDate":1677148319103,"connection":{"url":"https://bsc-dataseed1.ninicoin.io/"},"_nextId":50,"_eventLoopCache":{"eth_blockNumber":null},"_internalBlockNumber":{},"_poller":null,"_bootstrapPoll":null,"_fastBlockNumber":25913870,"_fastBlockNumberPromise":{}},"priority":2,"stallTimeout":750,"weight":1},{"provider":{"_isProvider":true,"_events":[],"_emitted":{"block":25913869},"disableCcipRead":false,"formatter":{"formats":{"transaction":{},"transactionRequest":{},"receiptLog":{},"receipt":{},"block":{},"blockWithTransactions":{},"filter":{},"filterLog":{}}},"anyNetwork":false,"_network":{"name":"bsc","chainId":56},"_maxInternalBlockNumber":25913870,"_lastBlockNumber":25913869,"_maxFilterBlockRange":10,"_pollingInterval":4000,"_fastQueryDate":1677148319283,"connection":{"url":"https://bsc-dataseed2.defibit.io/"},"_nextId":50,"_eventLoopCache":{"eth_blockNumber":null},"_internalBlockNumber":{},"_poller":null,"_bootstrapPoll":null,"_fastBlockNumber":25913870,"_fastBlockNumberPromise":{}},"priority":3,"stallTimeout":750,"weight":1},{"provider":{"_isProvider":true,"_events":[],"_emitted":{"block":25913869},"disableCcipRead":false,"formatter":{"formats":{"transaction":{},"transactionRequest":{},"receiptLog":{},"receipt":{},"block":{},"blockWithTransactions":{},"filter":{},"filterLog":{}}},"anyNetwork":false,"_network":{"name":"bsc","chainId":56},"_maxInternalBlockNumber":25913869,"_lastBlockNumber":25913869,"_maxFilterBlockRange":10,"_pollingInterval":4000,"_fastQueryDate":1677148317290,"connection":{"url":"https://bsc-dataseed2.ninicoin.io/"},"_nextId":50,"_eventLoopCache":{"eth_blockNumber":null},"_internalBlockNumber":{},"_poller":null,"_bootstrapPoll":null,"_fastBlockNumber":25913869,"_fastBlockNumberPromise":{}},"priority":4,"stallTimeout":750,"weight":1}],"quorum":1,"_highestBlockNumber":25913867,"_internalBlockNumber":{},"_fastBlockNumber":25913867,"_fastBlockNumberPromise":{}}, code=SERVER_ERROR, version=providers/5.7.2)`

**Comment by VittoriDavide** [comment]
Beth_getlogs seems to be blocked on the main RPC url on [BSC](https://github.com/BNB-Chain-Support/bnb-chain.github.io/blob/master/docs/rpc.md), do you mind if we use the graph for adding BSC network ?

**Comment by g1nt0ki** [comment]
> eth_getlogs seems to be blocked on the main RPC urls on [BSC](https://github.com/BNB-Chain-Support/bnb-chain.github.io/blob/master/docs/rpc.md), do you mind if we use the graph for adding BSC network ?

can you try with env variable BSC_RPC pointing to an archival node? I just verified, it is working in our server,  I prefer logs over graph as it is more maintainable/in our control

**Pull request closed without merging**
