### PR TITLE
Added boosted stake

### PR DESCRIPTION
**Pull request by elRaulito**
Added the details of TVL of Boosted Stake

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/fluidtokens exports TVL: 
        
 
 
    cardano-borrowed          1.27 M
    cardano                   1.54 M
    borrowed                  1.27 M
    
    total                    1.54 M

**Comment by g1nt0ki** [comment]
hi @elRaulito what change on November 22, the tvl jumped: 
image

**Comment by elRaulito** [comment]
Hey we finally added the value of the tokens in the contract as collateral

I remember you wondered if Cardano has a sort of api to check value of
tokens inside an address, where finally it's here and we implemented

I can share the api in case, just don't want to expose it on the adapter



Il Ven 29 Dic 2023, 12:28 g1nt0ki ***@***.***> ha scritto:

**Comment by elRaulito** [comment]
Hey @g1nt0ki any news regarding this? Our community is asking?

**Comment by elRaulito** [comment]
Pinging again @g1nt0ki since this is penalizing our TVL by 400k$ if not merged

**Comment by elRaulito** [comment]
Please, we are close to the official token launch and TVL metric is important for our users 🙏

**Comment by llamatester** [comment]
The adapter at projects/fluidtokens exports TVL: 
        
 
 
    cardano-borrowed          1.43 M
    cardano                   1.43 M
    borrowed                  1.43 M
    
    total                    1.43 M

**Comment by waynebruce0x** [comment]
On your stats page there is 28.93K ADA available, which is about 15K USD. Where is the rest of the 1.43M$ coming from?

**Comment by elRaulito** [comment]
image

Part is coming from all the tokens locked as collateral on FluidTokens

Over 900,000 ADA instead are locked in loans inside the smart contract, why? We released boosted stake, that ADA is not spendable, essentially it's ADA locked inside the contract that can be used only for delegation

**Comment by elRaulito** [comment]
image

Also here the value of the contract according to [TapTools](https://www.taptools.io/pro/profiler?address=addr1wxh6u2fldf77v8ut87hj3epsnw5qwtdf67kdr55n0p7w7rce2s8uw)

**Comment by g1nt0ki** [comment]
@elRaulito sorry for the late review

**Pull request merged**
