### PR TITLE
Fix: AstroportClassic (outdated) -> deadFrom

### PR DESCRIPTION
**Pull request by 0xpeluche**
TVL of AstroportClassic has been flat for several years, and there doesn't seem to be any activity on the protocol using the Terra blockchain anymore

### CODE REVIEW

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
hmm, there might not be much activity, but still there is ton of tvl, need to look into why it is broken. And people are still trading there: https://app.astroport.fi/trade?poolAddress=terra1v3lqxl0eyte9x3nhdgcj8hwvjq76aupnnzz0yll8mxs5cckc29pqvg2scu

**Comment by 0xpeluche** [comment]
Isn't the trading you're showing actually for Terra2 instead? Because there is also an Astroport product https://defillama.com/protocol/astroport#information that is still functional

**Comment by g1nt0ki** [comment]
you are right, the pool I shared is terra2, we still need to figure out why the adapter for v1 is breaking now.

**Comment by llamatester** [comment]
The adapter at projects/astroport-classic exports TVL: 
        
 
 
    terra                     0
    
    total                    0 
    
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:251:11 {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Pull request merged**
