### PR TITLE
defidollar: use yusd/ycrv.balanceOf

### PR DESCRIPTION
**Pull request by atvanguard**
Display DefiDollar APY in terms of the constituent tokens which is more accurate.

### CODE REVIEW

**Comment by atvanguard** [comment]
We would also like to change the logo and name here. What is the process for that? Thank you.

Screenshot 2021-05-14 at 10 05 34 AM

**Comment by 0xngmi** [comment]
Thanks, for the logo/description/name changes you can either submit a PR on https://github.com/DefiLlama/defillama-server or just provide the new ones here and I'll update them

**Comment by itsmnthn** [comment]
> Thank. For the logo/description/name changes you can either submit a PR on https://github.com/DefiLlama/defillama-server or just provide the new ones here and I'll update them

Thank you @0xngmi, I'm leaving changes here only.
**Logo:** Download Logo from here [DFD Logo](https://app.dusd.finance/tokens/DFD.svg) or from [Brand Kit](https://www.notion.so/Media-Kit-138cca20324d4767b4e18f475ad19412)
**Name:** DefiDollar DAO
**Description:** DefiDollar is a Multichain DeFi Protocol Lab

**Comment by 0xngmi** [comment]
Done

**Comment by itsmnthn** [comment]
Thanks 🙏

**Pull request merged**
