### PR TITLE
fix: change balance calculation of Eignepie mswETH leverage vault

### PR DESCRIPTION
**Pull request by 0xKMG**
the balance of mswETH leverage vault cannot be return by balanceOf, add function to handle

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/airpuff exports TVL: 
        
 
 
    ethereum                  16.95 M
    arbitrum                  10.82 M
    ethereum-staking          1.95 M
    staking                   1.95 M
    mode                      1.88 M
    zklink                    34
    
    total                    29.65 M

**Comment by llamatester** [comment]
Error while running adapter at projects/airpuff: 
        
 
  
    
    
    ReferenceError: balInETH is not defined
    Truncated error stack:
    
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/airpuff/index.js:193:38)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:50:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:141:9
        at async Promise.all (index 0)
        at async Promise.all (index 3)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:184:3

**Comment by llamatester** [comment]
The adapter at projects/airpuff exports TVL: 
        
 
 
    ethereum                  16.94 M
    arbitrum                  10.79 M
    ethereum-staking          1.95 M
    staking                   1.95 M
    mode                      1.88 M
    zklink                    34
    
    total                    29.61 M

**Comment by g1nt0ki** [comment]
@0xKMG thanks, I made a minor fix

**Comment by 0xKMG** [comment]
> @0xKMG thanks, I made a minor fix

thanks! I kind of know there should be an api for it, learned a lot from you 🙏🏻

**Pull request merged**
