### PR TITLE
Radioshack

### PR DESCRIPTION
**Pull request by radioshackcreator**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
RadioShack

##### Twitter Link:
https://twitter.com/radioshack

##### List of audit links if any:
https://www.certik.com/projects/radioshack

##### Website Link:
app.radioshack.org

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://static.radioshack.org/images/tokens/RADIO.png

##### Current TVL:
$7.3M

##### Chain:
Polygon, BSC, Ethereum, Avalanche, Fantom

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
radioshack

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
19006

##### Short Description (to be shown on DefiLlama):
RadioShack is a 100 year old brand embedded into the global consciousness, now on a mission to be the first protocol to bridge the gap to mainstream usage of blockchain and cryptocurrencies.

As a first step, RadioShack is fixing the chaotic and dispersed nature of liquidity addition on today's AMMs. To solve this problem, RadioShack aims to significantly reduce the diameter of the graph of swappable tokens, and increase liquidity per pair. This will be achieved by using a single large-degree node (the RADIO node) to create what they refer to as The Starfish Topology: a pairing of the single large node with all swappable pairs.

##### Token address and ticker if any:
ticker: RADIO
Polygon: 0x613a489785C95afEB3b404CC41565cCff107B6E0
BSC: 0x30807D3b851A31d62415B8bb7Af7dCa59390434a
Ethereum: 0x7a5d3A9Dcd33cb8D527f7b5F96EB4Fef43d55636
Avalanche: 0x02Bfd11499847003De5f0F5AA081C43854d48815
Fantom: 0xf899e3909B4492859d44260E1de41A9E663e70F5

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
n/a

##### forkedFrom (Does your project originate from another project):
Uniswap v2

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL = Total liquidity added to liquidity pools

### CODE REVIEW

**Comment by 0xtawa** [comment]
Hi @radioshackcreator ty for submitting the PR. There's a commit fixing the current adapter implementation and just backfilled RadioShack data. I see this PR changes the current adapter by a similar one (`univ2Adapter` function exports a similar object to the one that is exported in this PR, using default fields), could you confirm if the current adapter is OK and therefore I can close this PR or if I should take a look/merge this PR?
U can see the current adapter data here -> https://defillama.com/dex/radioshack

Once u confirm will proceed to enable RadioShack in the dashboard

ty

**Comment by radioshackcreator** [comment]
@0xtawa this is the correct implementation of the RadioShack adapter. Please overwrite the old adapter.

**Comment by llamatester** [comment]
The radioshack adapter exports: 
        
 
 _______________________________________
    Volume for 28/9/2022
    _______________________________________
    
    Error: Can't get block of chain bsc
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:90:31
        at step (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:44:23)
        at Object.next (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:25:53)
        at fulfilled (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:16:58)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
    ------ ERROR ------
    Error: Couldn't find block height for chain bsc, RPC node rugged
        at Object.<anonymous> (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:173:27)
        at step (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:44:23)
        at Object.throw (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:25:53)
        at rejected (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/index.js:17:65)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by llamatester** [comment]
The radioshack adapter exports: 
        
 
 _______________________________________
    Volume for 28/9/2022
    _______________________________________
    
    POLYGON 👇
    Backfill start time: 18/2/2022
    24h volume: 45261.186162033608263522630572278
    Total volume: 53328263.72129156
    BSC 👇
    Backfill start time: 5/3/2022
    24h volume: 11190.5384116660878615517982770602
    Total volume: 23675751.70462683
    ETHEREUM 👇
    Backfill start time: 3/4/2022
    24h volume: 57710.38150671088448785629586483646
    Total volume: 13841468.46494893
    AVAX 👇
    Backfill start time: 3/4/2022
    24h volume: 2148.925697167531726390185979611268
    Total volume: 86885461.11432008
    FANTOM 👇
    Backfill start time: 16/8/2022
    24h volume: 203.5107132961068865664250161249187
    Total volume: 16765.65177375515

**Comment by 0xtawa** [comment]
ty

**Pull request merged**
