### PR TITLE
added cog finance adapter

### PR DESCRIPTION
**Pull request by herpq**
```I ran this adapter and the output was just 0. Seemed odd since other cases that used similar code returned values and I think the tokens / balances do get returned, just not populated in the `api.getBalances()` method. not sure why this is happening but if anyone has any idea, im all ears```

---
##### Name (to be shown on DefiLlama):
Cog Finance

##### Twitter Link:
https://twitter.com/CogFinance

##### List of audit links if any:
https://github.com/CogFinance/Cog-Isolated-Lending/blob/main/audits/VAR_Cog230731.pdf

##### Website Link:
[cog.finance](https://www.cog.finance/)

##### Logo (High resolution, will be shown with rounded borders):
favicon

##### Current TVL:
~10k

##### Chain:
Scroll

##### Short Description (to be shown on DefiLlama):
Cog is a new isolated lending protocol that aims to maximize both decentralization and capital efficiency that many existing solutions are currently lacking. The main objectives are to help users painlessly deploy permissionless isolated borrowing/lending pools, protect users against interest rate manipulation attacks, and enhance the extremely limited capital efficiency of isolated lending as a whole.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### methodology (what is being counted as tvl, how is tvl being calculated):
ERC4626

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/cog-finance exports TVL: 
        
 
 
    scroll                    0
    
    total                    0

**Comment by herpq** [comment]
it's showing wsteth now, i guess the coins / price feeds are being added over time onto scroll?

**Comment by ControlCplusControlV** [comment]
I asked the scroll team for an official [tokenlist](https://scroll-tech.github.io/token-list/scroll.tokenlist.json), maybe ensure the balances for all of those are checked? The Cog adapter itself should be fine for now (working on a couple contracts to make pulling the data easier in the future). Could we maybe get this merged though for initial support?

**Comment by g1nt0ki** [comment]
hi @ControlCplusControlV @herpq 
I have added a coins adapter so tokens bridged to scroll are priced correctly: https://github.com/DefiLlama/defillama-server/commit/95d1dedec3ba69eea0e5f245c76dd5b840452d01

and I have added an adapter that pull new cogs automatically and split between tvl & borrowed: https://github.com/DefiLlama/DefiLlama-Adapters/commit/75261e80ac5c951c8727f567d7f61f8ac5b78d00

can you verify my code?

**Comment by herpq** [comment]
> hi @ControlCplusControlV @herpq I have added a coins adapter so tokens bridged to scroll are priced correctly: [DefiLlama/defillama-server@95d1ded](https://github.com/DefiLlama/defillama-server/commit/95d1dedec3ba69eea0e5f245c76dd5b840452d01)
> 
> and I have added an adapter that pull new cogs automatically and split between tvl & borrowed: [75261e8](https://github.com/DefiLlama/DefiLlama-Adapters/commit/75261e80ac5c951c8727f567d7f61f8ac5b78d00)
> 
> can you verify my code?

Thanks for doing this!

For the adapter, I noticed we actually have the following more pair types (although medium risk will cover what's existing)
- 'event StablePairCreated(address indexed asset, address indexed collateral, address indexed pair)'
- 'event LowPairCreated(address indexed asset, address indexed collateral, address indexed pair)'
- 'event MediumPairCreated(address indexed asset, address indexed collateral, address indexed pair)'
- 'event HighPairCreated(address indexed asset, address indexed collateral, address indexed pair)'

**Comment by g1nt0ki** [comment]
@herpq thanks, I have fixed it here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/da8750aa87cba4cf475c389c794e4cf459fc0a86

**Pull request closed without merging**
