### PR TITLE
Add Lympo

### PR DESCRIPTION
**Pull request by RomanG11**
##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://api.lympo.io/pools/extData/lympo.svg
https://api.lympo.io/pools/extData/lympo.png

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/lympo: 
        
 
  
    
    
    ReferenceError: block is not defined
    Truncated error stack:
    
        at staking (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/lympo/index.js:10:43)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:48:25)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:143:9
        at async Promise.all (index 1)
        at async Promise.all (index 0)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:188:3

**Comment by llamatester** [comment]
The adapter at projects/lympo exports TVL: 
        
 
 
    polygon                   0
    polygon-staking           569.30 k
    staking                   569.30 k
    
    total                    0

**Comment by RomanG11** [comment]
we want to display correct TVL, after your fix the total value was 0.

**Comment by g1nt0ki** [comment]
@RomanG11 sorry, I have moved the tvl to staking, as all of it comes from your own tokens. Protocol lets users stake $SPORT in pools and mine NFTs?

**Comment by RomanG11** [comment]
@g1nt0ki Yes but I see this response after your commit. 

polygon                   0
polygon-staking           569.30 k
staking                   569.30 k

total                    0 


Now it shows this. You may change the code but total TVL must be correct. Thank you for your time

--- polygon ---
SPORT                     567.70 k
Total: 567.70 k

--- tvl ---
SPORT                     567.70 k
Total: 567.70 k

------ TVL ------
polygon                   567.70 k

total                    567.70 k

**Comment by g1nt0ki** [comment]
@RomanG11 that is because you reverted my change: https://github.com/DefiLlama/DefiLlama-Adapters/pull/4772/commits/9a1df773f06b4655aba28994128d9dde282071c5 

Sorry, but I cant merge this PR in its current state

**Comment by llamatester** [comment]
The adapter at projects/lympo exports TVL: 
        
 
 
    polygon-staking           561.19 k
    polygon                   561.19 k
    staking                   561.19 k
    
    total                    561.19 k

**Comment by g1nt0ki** [comment]
sorry, still no. "staking" tvl will automatically be added to main tvl when user enables the "staking" toggle in UI
image

**Comment by RomanG11** [comment]
Ok, I've reverted my changes. Lets try this way

**Comment by llamatester** [comment]
The adapter at projects/lympo exports TVL: 
        
 
 
    polygon                   0
    polygon-staking           563.06 k
    staking                   563.06 k
    
    total                    0

**Pull request merged**
