### PR TITLE
Add adapter: BOB Fusion - season 1

### PR DESCRIPTION
**Pull request by bvotteler**
##### Name (to be shown on DefiLlama):
BOB Fusion - Season 1

##### Twitter Link:
https://twitter.com/build_on_bob

##### List of audit links if any:
tbd (not yet publicly available)

##### Website Link:
https://gobob.xyz

##### Logo (High resolution, will be shown with rounded borders):
BOB_SIGIL_100pc_Orange_1

##### Current TVL:
$94

##### Treasury Addresses (if the protocol has treasury)
n/a

##### Chain:
Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
n/a

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
n/a

##### Short Description (to be shown on DefiLlama):
BOB is a new Bitcoin EVM L2, secured by Bitcoin PoW and connected to ETH as a rollup.

##### Token address and ticker if any:
n/a

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Farm

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
n/a
##### Implementation Details: Briefly describe how the oracle is integrated into your project:
n/a
##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
n/a

##### forkedFrom (Does your project originate from another project):
n/a

##### methodology (what is being counted as tvl, how is tvl being calculated):
Sum of all tokens deposited into BOB's fusion lock contract - [Etherscan link](https://etherscan.io/address/0x61dc14b28d4dbcd6cf887e9b72018b9da1ce6ff7#code#F1#L34) to verified contract

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/bob-collective

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bob-fusion-season-1 exports TVL: 
        
 
 
    ethereum                  94.561808
    
    total                    94.561808

**Comment by llamatester** [comment]
The adapter at projects/bob-fusion-season-1 exports TVL: 
        
 
 
    ethereum                  94.50993700000001
    
    total                    94.50993700000001

**Comment by g1nt0ki** [comment]
@bvotteler thanks for the PR

**Comment by bvotteler** [comment]
> @bvotteler thanks for the PR

Thank you for the fast review, @g1nt0ki 

Quick question: Which contact channel should we use to add the audit link once that's available?

**Comment by g1nt0ki** [comment]
you can post it here or in our discord

**Pull request merged**
