### PR TITLE
Adding Saturn Swap TVL to DefiLlama

### PR DESCRIPTION
**Pull request by NicholasMaselli**
---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/saturnswap exports TVL: 
        
 
 
    cardano                   1.58 M
    
    total                    1.58 M

**Comment by g1nt0ki** [comment]
hi @NicholasMaselli thanks for the PR, is there some easy way to fetch this tvl on chain?

**Comment by NicholasMaselli** [comment]
Hi @g1nt0ki yes! If you are using a Cardano DBSync, all of the assets are located at this smart contract payment key hash:

`1af84a9e697e1e7b042a0a06f061e88182feb9e9ada950b36a916bd5.`

You can loop through all outputs there to get the value of all utxos. Let me know if you need help with this!

**Comment by llamatester** [comment]
Error while running adapter at projects/saturnswap: 
        
 
  
    
    
    PromisePoolError: Request failed with status code 400
    Truncated error stack:
        at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
Error while running adapter at projects/saturnswap: 
        
 
  
    
    
    PromisePoolError: Request failed with status code 400
    Truncated error stack:
        at PromisePoolError.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
The adapter at projects/saturnswap exports TVL: 
        
 
 
    cardano                   101.77 k
    
    total                    101.77 k

**Comment by g1nt0ki** [comment]
hi @NicholasMaselli 
We are getting much lower tvl with on chain data, looked into it, I think the reason is, we dont price some of the tokens on our end, maybe can you get some of these listed on congecko? we pull prices from there and other dexes

**Pull request merged**
