### PR TITLE
ParaX: add ParaX AA TVL

### PR DESCRIPTION
**Pull request by jfzhou5**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/parax-aa: 
        
 
  
    
    
    Error: GraphQL Error (Code: 403): {"response":{"error":"<!DOCTYPE html><html lang=\"en-US\"><head><title>Just a moment...</title><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\"><meta name=\"robots\" content=\"noindex,nofollow\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><link href=\"/cdn-cgi/styles/challenges.css\" rel=\"stylesheet\"><meta http-equiv=\"refresh\" content=\"35\"></head><body class=\"no-js\"><div class=\"main-wrapper\" role=\"main\"><div class=\"main-content\"><noscript><div id=\"challenge-error-title\"><div class=\"h2\"><span class=\"icon-wrapper\"><div class=\"heading-icon warning-icon\"></div></span><span id=\"challenge-error-text\">Enable JavaScript and cookies to continue</span></div></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '2',cZone: 'api.para.space',cType: 'non-interactive',cNounce: '87560',cRay: '801e05b3abbf485e',cHash: '6ca5299003ad7e9',cUPMDTk: \"\\/graphql\\/ethereum?__cf_chl_tk=N4ObqiZ3yIjWfdSJ1lwvCK3UZVzNT3aiodsqdZzmHts-1693912190-0-gaNycGzNCtA\",cFPWv: 'g',cTTimeMs: '1000',cMTimeMs: '60000',cTplV: 5,cTplB: 'cf',cK: \"visitor-time\",fa: \"/graphql/ethereum?__cf_chl_f_tk=N4ObqiZ3yIjWfdSJ1lwvCK3UZVzNT3aiodsqdZzmHts-1693912190-0-gaNycGzNCtA\",md: \"yy0RI2bSF1K3n5JRW4M9UxCDS39qF6ZPPO67GL24nzA-1693912190-0-AVLvu2F-XHq2heaZasfDwIaBahXH6nQi7gmSdIVQ0Kbx7eNvkUIzz4HzaQOuzAVnaVP7ejJZuCEmbNFMy4IUWfJA7BMPZD5J-jj7dCz5Q5vJ9R737K3SEW6s9HQtDtA5JsJPvMv1aUE2t66_Sps_q4_9t8ZIstxcOtlwpzPMHd-vnTMZJD_X94a--X2kkeK2Gf37LKOWZ5ZY3FbZkNmQx02gL3DUs5LTNTVsKoQWVS7XM-Il9JUz4bWVb6FgraEwDQcO5MbStEuwfZl3cF3muJC6I-pb8TdGtP_pEHE8ttanSnoi018DBygVpfxdVm5nAEoB9zud7aEFSJuU8LJztCpojM8X6EzpA6_oOFcukD65SSe_tflgL4F1joacQWEEV0aoeouIHuuxWCllQCly-4dyisO7K0TafEI1gikcXMQCvfCXfBW3-dcS3wc9i2n1kaq8MimaSBN1ZF-WFaW6vO1hxYZxZJDGYjXOtJzdpWiELBJ8e2s9xG6AiBn1W3HDDsc0EbUsEshZAtEKFPhwQ8TTcTg_Qw6vBTsW8zzvJ54MSt_-sK2c63lGX0e-UNnDSaZxfAVqFY2K9QwjFM9bdRS0UpLbvWZCYk-nSxAn0U-_8bn4Na1BWiomLiqEPaQ8_136AUiBYqg_qjTaMzpgPdC8fOetW708dggdhlsR7SiNl0jKkm8NU68TEo2NqVEFngKQUlCK4A7WOndZs3l8FZJc3Nyo89ovaJz6x8pNNwt0hmJ9pQZWoyRT5i8VWDDdDyEZKA3_OmmAV3usv7ByBSx6-W9IyJMZedbrxnXOK73MQzU7prKxWCiSejbdG256dLyZMaB3apGalTCcv2nFuh_tK1-weEXnGoCTEcU9DljDHp0ew2W3ibCrut8pl19zQKuICo9P0g2d5eycB8aVxmR5TjkSI7wa_2ydQ2rQswROC_IOCRvtkvsC4ig3d4Y9bcNhspl2avHUZKI5pPrVTAIf8y4RvSZfWjmzWhq8eXpUDYofgawr37hE1EoXHttn6xkXeKRJMhn6sQGJKXQwO8NSk85x9mu1bsSHdvoy8tocjY49sQrL2pYwliWwbcdSP_rtH9pAohg9xUB-jsNYyDRIOC4QQeTiwrKA34SxZI3DOMyv1sgS-26BT-gB8fGP9bso3oukklSR_dBGqpz8hC92-8nsFbbTYNXukNWC11XZNWbGJAs4VIbu5I_2GRRN1EkkQka9dlNH4TUdK_gEAKpfNA63woLvuNUGZ-OhXSmbnHZcc-dEbxZZmVM7PeKLB5OzEeYpcn7HmeTV90ztpSusiIhoWhJg7PRI0ZfGWgqEdEYW8OfMrfHjkpoRzfNUM-NCD01DFhHoMcAf9NITBjrnK3SOiu_dS9t5rJ_pF5Fz6CTOTMcRxCoA8F5jKWqNnYFjQ1-qVPbokqE1TOslN59sThTE2rqUdwf0F-XfMDfb16CGH0V_kTSXni1oy7gLxUACztkfD3X9f4GrRTdWSiTSHEYBKuDK7jAT9vjL_OykiKXMs92BlttMAoiSZ-tOCsderi4YovrhzHgO5F5Z4JXNUjAqT8FTAm-sUaNTG-URMUgQng0daGHXuNcPu3ou-hwELoYmgydoNmfLRiNqrPB0Gt2fii5IJ_eUwpIilk8S0r2YNRYqgUg9yGjx3ymu4d4frmYO5mYj8nYf_Km6PGHFiLEW5dqvImYTkaNVAbKKv309-8NQJXFVM9aU6uXKHEkJBB7PQmmgHTXU1XD4vjizBEmXe4RZcidKVP8CArGNxbokHnyxZEVPKorcEH0IhdaIMrj7HGtESCupCJQ-fipczUhZudHvWia3eC2JQAaNTMd0YMf1lW6oy2fGcKp3m8J0MG333u5bmIBZ8bFhFhU2vc8FgzOhxcj2iCfZM2IpCpFnSIuqoGXLz6qh0ya2Xiy7lKDBvdplFcGn_ysFFOb0Mw0H4YNaGWWgdBSGBidVtX2MII9_NSI0tdy0Idbup4bSOpJvt1uawYx119YZWcEvfW8XkT7xZc-L_sq2hvJRXHRqUZFIxA9vK6rZx11m-9EF4tzD_V3zTL-4QQHhyn05hyCrQM4OkT0p7FLt6eChNfEAtuyoOfAkFdN2AtrRlN16CfsCFinPZEeonxXJ7QdwYYPWnL7o6CRkjShfqVLUXumm4MRg8X4g5Bb48j2Vee_4eykspXr10tkk0Vg-i5sS58GrzknVrpp_3xCD1zSrypuPbVg_sljyhj3ItrlkePAxj4dXqOo0470wIq1FxJJweAyw4gJ_YMcb-EfUHpEj1TkbAERZ_CO8OpZqFJ5SaKqQ6BUKZLFKN1PNPsFSQXRwsx0UK1cUxdLTXN2BQ41xh0f3EPMPoeyS2iuYtBeRuxmZl4Ap_M-SKqd-8CUKhXIF0EI-t4FGWOdjoNLGxWAFsIc50lL6suh0Sc6GQEyXoGyepcUV-Y6aASngT34wWBS73p_U6b0CFyoRK6w9QgNxFAsoNxVK6d47d4jCvOIrZOrfFXoWqX6vu76dPvtPofDpbCR20jYUfLvxbKlDA1Va7B-1vAjKl5GqtbxLGFAQVxsJffn2WkLqgV7NGmCP9EDQ_6bu72jqpIpkbpmVrcw7qOQm7bdK6ethjTX57qprPxu4xUBHHJeVouwWIOcINQy5S0h_tInVuTHjRwNuk-6QtdZKhkVRGRbjwSjglZwn6MPpqZyYJ2THTj19pxY_anY\",cRq: {ru: 'aHR0cHM6Ly9hcGkucGFyYS5zcGFjZS9ncmFwaHFsL2V0aGVyZXVt',ra: 'bm9kZS1mZXRjaC8xLjAgKCtodHRwczovL2dpdGh1Yi5jb20vYml0aW5uL25vZGUtZmV0Y2gp',rm: 'UE9TVA==',d: 'u1WqWRB9bokvFggU5Jlene2MB4Fr03+RKtmcnbGQsZByq31ZxXB3P1E0up8Nbz1qJmrDlWuEa/JVF8C602iTtPdUZCq6plKNdUQ8V3Mqp7ZrlDz22+Or+FQou+O4TBEohdCvJgBd3OSI/d4xkhi85OaIj7+hsPkWBwKQKBiesfTJAqdhIUB3HSdAHA8kRL+x+OlxHVjv85Qbb4U5NkF61/TsxfT7wnV8DSKnXgc4zZZSzo4BdF3eYp6JgWQ5IQxpDDS/9Wi5w++ZFAftXcgGL3PSOs8SaIV6Mz8G/hIIVrR2xQrtLbdiJE7VuVXro2/Hxl9XB+hZs6tQsRXUXk3iKEWptta6kq0P+Kym2vI3f30h/BRWtt5s79sErxCknhoF35C6eRQpwWbE2m7DUxH76PJcHycGpmw4WqvAoZBXO6Z/906Mwn1TkWVO2AEHmFQWl/va388hbr+lY/H2Ik4/ckBreJNeaMK+1JjVpI+1IoFgJsxiOf9ksaFhIwp4+KccMNvnJBhCzrqvIEcfRadJvFBTDcqpMz5yaaxC7Ei1+M8=',t: 'MTY5MzkxMjE5MC4wMjcwMDA=',cT: Math.floor(Date.now() / 1000),m: 'AHEYi2kj/0VXR4dEfOubQUSEKje6HBo7RJ8g46iapzM=',i1: 'GBD8lPVSNkPJW41Ws9Zw/g==',i2: 'JPdxICca3os9i03CQV+oFw==',zh: 'Z6/e0VNG3NOEdWlNi14+OFx6zHtIQNelBCb5vnMOPpo=',uh: 'o3n6xEt35XQSPgkMHltSudNiWY3D18ZEWvIVxqHkP+4=',hh: 'WGuxJuinNJzvlhPwFiUjUrWhB8r00aqEkJNKygUppL8=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1?ray=801e05b3abbf485e';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, \"\\/graphql\\/ethereum?__cf_chl_rt_tk=N4ObqiZ3yIjWfdSJ1lwvCK3UZVzNT3aiodsqdZzmHts-1693912190-0-gaNycGzNCtA\" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>","status":403,"headers":{}},"request":{"query":"\n  query RootQuery {\n    paraAccountsBalance {\n      totalInUSD\n      totalInETH\n    }\n  }\n"}}
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/graphql-request/dist/index.js:359:31

**Comment by llamatester** [comment]
The adapter at projects/parax-aa exports TVL: 
        
 
 
    ethereum                  192.27 k
    
    total                    192.27 k

**Comment by g1nt0ki** [comment]
hi @jfzhou5 not sure if we should include this, my reasoning is, in some ways this is like a smart wallet/multisig right? also there is tvl over lap between this and para v2 listings?

**Comment by jfzhou5** [comment]
> hi @jfzhou5 not sure if we should include this, my reasoning is, in some ways this is like a smart wallet/multisig right? also there is tvl over lap between this and para v2 listings?
@g1nt0ki  This tvl is the total value locked of all AA accounts created by ParaX and is different from the para v2 listing and is no over lap between this and para v2 listings.

**Comment by g1nt0ki** [comment]
@jfzhou5 I check ed again with the team, we had this discussion before when a service (similar to gnosis safe) tried to count tokens in their contract as tvl, we said no as we dont see it as defi activity, afraid same applies here.

**Comment by jfzhou5** [comment]
So for Ambire wallet and instdapp, What does their tvl consist of?

**Comment by g1nt0ki** [comment]
Ambira wallet, we are tracking only staking: https://defillama.com/protocol/ambire-wallet

instadapp is legacy, yeah I agree it should be removed

**Comment by jfzhou5** [comment]
@g1nt0ki for instadapp should we remove it? if not, it's not fair for us.

**Comment by jfzhou5** [comment]
@g1nt0ki how do reply on this? Is there any plan?

> @g1nt0ki for instadapp should we remove it? if not, it's not fair for us. If you're still having Instadapp's smart contract wallet TVL, it's essential that you include us. Omitting this would not accurately and rarely represent our work

**Comment by jfzhou5** [comment]
@0xngmi In the future ParaX will support user to interact with other protocols like Compound or AAVE with AA account, So Can this part of money be included into ParaX AA tvl like the assets of AA supplied in Compound?

**Comment by g1nt0ki** [comment]
> @0xngmi In the future ParaX will support user to interact with other protocols like Compound or AAVE with AA account, So Can this part of money be included into ParaX AA tvl? like the assets of AA supplied in Compound?

think it comes down to what para AA acts like, leveraging platform or AA wallet, if it is the former, we can count the value in non-para products (to avoid double-counting) as tvl

**Comment by jfzhou5** [comment]
I can descrbe the usage case for you, just like ParaX will develop a AAVE sub-dapp into the Parax frontend, and user can use do some efficient and different txs from AAVE itself like batch txs. In this case ParaX AA project is like a platform, not just a AA wallet. So we want to include the positions of AA in AAVE, Is that ok?

**Comment by jfzhou5** [comment]
ParaX super app is like a Defi aggregator based on AA wallet, we can provider user some strategy of higher defi profit.

**Comment by g1nt0ki** [comment]
> I can descrbe the usage case for you, just like ParaX will develop a AAVE sub-dapp into the Parax frontend, and user can use do some efficient and different txs from AAVE itself like batch txs. In this case ParaX AA project is like a platform, not just a AA wallet. So we want to include the positions of AA in AAVE, Is that ok?

yes, aave tvl should be counted in this case.

**Pull request closed without merging**
