### PR TITLE
add chikn farm

### PR DESCRIPTION
**Pull request by chiknfarm**
##### Twitter Link:
https://twitter.com/chikn_nft

##### Website Link:
https://chikn.farm/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://raw.githubusercontent.com/chiknfarm/contract/main/EGG_TOKEN_LARGE.png

##### Current TVL:
$5563094.04

##### Chain:
Avalanche

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
chikn-egg

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
https://api.coingecko.com/api/v3/simple/price?ids=chikn-egg&vs_currencies=usd&include_market_cap=true&include_24hr_vol=true&include_24hr_change=true

##### Short Description (to be shown on DefiLlama):
10,000 algorithmically generated, unique chikn
NFTs that lay $egg

##### Token address and ticker if any:
0x7761E2338B35bCEB6BdA6ce477EF012bde7aE611

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Staking

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
N/A

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
Egg staked in chikn.farm native ecosystem.

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Can this be calculated using on-chain calls? We prefer this as its more transparent, and allows for historical data. Since this is counting your native token, can it be exported with a 'staking' key instead?

**Comment by chiknfarm** [comment]
Sort of yes and no, the staking records are on chain, the API we offered basically just a sum of all the staked value. We didn't get a chance to to stored a specific value for it, hence we offered our own API to iterate through the staked wallet to calculated the total locked up value of Egg.

**Comment by waynebruce0x** [comment]
What does the API count as TVL? Is it open source?

**Comment by chiknfarm** [comment]
this is basically the code, didn't open source it due to other APIs we are offering for our site.

`const pollEggStakingDetail = async () => {
    try {
        const totalStakedUsers = await feedMainnet.totalEggStakeHolders()
        let highestAmount = 0
        let highestStaker = {
            amount: 0,
            address: 0,
            since: 0

        }
        let totalStakedAmt = 0
        EggStaked.totalStakedHolder = totalStakedUsers
        for (let i = 0; i < totalStakedUsers; i++) {
            const holderAddress = await feedMainnet.eggHolderByIndex(i)
            // console.log('holder address', holderAddress)
            const holder = await feedMainnet.getEggStakeHolders(holderAddress)
            const value = FormatAvaxPrice(holder.amount) // convert to readable number
            if (value > highestAmount) {
                highestStaker = {
                    amount: value,
                    address: holder.user,
                    since: holder.since
                }
                highestAmount = value
            }
            totalStakedAmt += value
        }
        EggStaked.highestStaked = highestStaker
        EggStaked.totalStakedAmount = totalStakedAmt
        EggStaked._lastUpdatedTime = new Date()
    } catch (err) {
        console.log('Error on getting Egg staking detail', err)
        await new Promise(resolve => setTimeout(resolve, 30000))
    }
}`

**Comment by waynebruce0x** [comment]
Since EGG is your native governance token, can you export the TVL as 'staking' with core TVL as 0? 

like or similar: 

async function tvl() {
 return 0
}

module.exports = {
staking: {
fetch
},
fetch: tvl
}

**Comment by chiknfarm** [comment]
Sorry, doesn't really make much sense, do you have a sample project that i can take a look?

**Comment by chiknfarm** [comment]
please let me know if this is what you are after?

**Comment by 0xngmi** [comment]
Looking at coingecko and etherscan the FDV of $EGG appears to be 2.6M, how is it possible that there's 7M staked.
Furthermore looking at $EGG holders (https://snowtrace.io/token/0x7761e2338b35bceb6bda6ce477ef012bde7ae611#balances) it looks like there's no holder with that amount

**Comment by chiknfarm** [comment]
Hi,

we will need to do another PR, we have updated our api so will get that fix

**Pull request merged**
