### PR TITLE
add Staq

### PR DESCRIPTION
**Pull request by cokes123**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
StaQ

##### Twitter Link:
https://twitter.com/StaQ_io

##### Website Link:
https://bitstaq.io/

##### Logo (High resolution, will be shown with rounded borders):
image

##### Current TVL:
0.23 M USDT

##### Chain:
Map Protocol

##### Short Description (to be shown on DefiLlama):
Liquidity for staked tokens in the Bitcoin L2 ecosystem.

##### Token address and ticker if any:
$stMAP 0x9bD1E0a3A727D0d4F4e9A6d59022E071DDc79924

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Liquid Staking

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/bitstaq: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:192:11

**Comment by llamatester** [comment]
The adapter at projects/bitstaq exports TVL: 
        
 
 
    map                       29.77 k
    
    total                    29.77 k

**Comment by g1nt0ki** [comment]
@cokes123 thanks for the PR

**Comment by cokes123** [comment]
@g1nt0ki  thanks 
but our Dapp name is “StaQ” not “bitstaq”, Can you help us modify it? https://defillama.com/protocol/bitstaq

**Comment by Define101** [comment]
Should be live within 2 hours
https://github.com/Define101/defillama-server/commit/f8282afb8b0d6009f012a849b67632468fb6fa2b

**Pull request merged**
