### PR TITLE
Add inSure DeFi

### PR DESCRIPTION
**Pull request by inSureToken**
##### Website Link:
https://insuretoken.net

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
insure

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
insure

##### Short Description (to be shown on DefiLlama):
inSure DeFi is a Decentralized Insurance Ecosystem, trusted by thousands of community members to protect their crypto portfolios from scams, exchange closures, and drastic devaluations. inSure DeFi provides insurance solutions for the crypto space to stabilize and secure Crypto & DeFi portfolios.

##### Token address and ticker if any:
0xcb86c6a22cb56b6cf40cafedb06ba0df188a416e (SURE)

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Insurance

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

### CODE REVIEW

**Comment by 0xngmi** [comment]
Currently the script doesn't work, 0xF4b2aa60Cd469717857a8A4129C3dB9108f54D74 is a gnosis multisig, which doesn't have any currentTVL() method

**Comment by inSureToken** [comment]
> Currently the script doesn't work, 0xF4b2aa60Cd469717857a8A4129C3dB9108f54D74 is a gnosis multisig, which doesn't have any currentTVL() method

Thank you for the best reply! 
What will be the best way to track all the tokens locked in our community vault (gnosis multisig)? 
We are planning to add ETH, BNB, USDT, DAI, MATIC, and other tokens to it. 

We can communicate on telegram as well to resolve this faster. Our official account: t.me/insureteam

**Comment by 0xngmi** [comment]
what's the role of the multisig? is it used as a treasury?

**Comment by inSureToken** [comment]
> what's the role of the multisig? is it used as a treasury?

There are multiple cases play a role in adding new locked value to inSure DeFi project:
1. In order to enable the insurance policy, SURE will be deposited to the gnosis vault (we need to track total $ value of SURE locked at the current time)
2. By decision of the community, in order to grow the capital pool and eventually have well sized surplus pool, the SURE funds will be swapped on the avilable LPs to other tokens. I.e. capital pool is reinvested and tracked in the vault so everything is transparent. (For example BNB, MATIС etc bought from the LPs on DEXs with direct pool or bridge between token pools).
3. When new LPs are created with our partner projects, for example SURE/OVR, SURE/PIN, SURE/VEST etc. the LP tokens will be locked in the community vault (we can tracking of this later, since new SC will be created for each LP)?

**Comment by inSureToken** [comment]
Should we use abi["balanceOf"] instead to track all from Gnosis safe?

**Comment by inSureToken** [comment]
Hi, @0xngmi made changes to track the SURE balance in the treasury address. 
Please let us know if your system can grab the TVL now.

**Comment by 0xngmi** [comment]
where is the sure locked in the multisig coming from?

**Comment by inSureToken** [comment]
> where is the sure locked in the multisig coming from?

Multiple sources:
1. Enabling the insurance policy, SURE is deposited to the gnosis vault - locked  - Capital Pool
2. Initial locked funds of the community (SURE has fixed supply, not mintable) 
3. Future buybacks directly with gnosis safe transaction on DEXs.
4. Contributions from the members.

Let us know if you need more clarifications.

**Comment by inSureToken** [comment]
also, when we add other tokens to the treasury, should we go with the same process of a new pull request describing the changes? (ETH, BNB, OVR, VEST, and others)

**Comment by 0xngmi** [comment]
> also, when we add other tokens to the treasury, should we go with the same process of a new pull request describing the changes? (ETH, BNB, OVR, VEST, and others)

no, if its just adding a new token we can easily make the changes directly or if you make a pr we'll merge automatically, since we have already evaluated methodology before

**Comment by inSureToken** [comment]
> > also, when we add other tokens to the treasury, should we go with the same process of a new pull request describing the changes? (ETH, BNB, OVR, VEST, and others)
> 
> no, if its just adding a new token we can easily make the changes directly or if you make a pr we'll merge automatically, since we have already evaluated methodology before

Sounds good, thank you @0xFondue for the support! Really appreciate your help with this!

**Comment by inSureToken** [comment]
> > > also, when we add other tokens to the treasury, should we go with the same process of a new pull request describing the changes? (ETH, BNB, OVR, VEST, and others)
> > 
> > 
> > no, if its just adding a new token we can easily make the changes directly or if you make a pr we'll merge automatically, since we have already evaluated methodology before
> 
> Sounds good, thank you @0xFondue for the support! Really appreciate your help with this!

@0xngmi Please feel free to reach out if you need any other information from us.

**Comment by inSureToken** [comment]
@0xngmi  it looks like the PR is still not Merged, do you need any other information to merge it?

**Comment by inSureToken** [comment]
@waynebruce0x @0xngmi @BlazeWasHere @siong1987 @ericnakagawa 
Can you please help to merge this PR?

**Pull request closed without merging**
