### PR TITLE
add staked amu token TVL

### PR DESCRIPTION
**Pull request by alexandrosgoh**
add staked amu token TVL

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/amulet-v2: 
        
 
  
    
    
    AxiosError: Request failed with status code 429
    Truncated error stack:
        at settle (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/axios/dist/node/axios.cjs:1970:12)
        at IncomingMessage.emit (node:events:529:35)

**Review by g1nt0ki — COMMENTED** [review]
moving own token tvl to staking: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by g1nt0ki** [comment]
fixed it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/9430

**Comment by alexandrosgoh** [comment]
thanks

**Pull request closed without merging**
