### PR TITLE
Update fantasm contract version 2

### PR DESCRIPTION
**Pull request by ftazm**
##### Twitter Link: 
https://twitter.com/fantasm_finance

##### Website Link:
https://fantasm.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
ms-icon-310x310

##### Current TVL:
10,500,000$

##### Chain:
Fantom Opera

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
fantasm-fxm

##### Short Description (to be shown on DefiLlama):
Fractional-algorithmic Synthetic token on Fantom Opera

##### Token address and ticker if any:
FXM: 0x132b56763C0e73F95BeCA9C452BadF89802ba05e

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Assets

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is calculated as sum of all assets locked in pool and farm contract

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/fantasm/index.js exports TVL: 
        
 
 
    fantom                    3.87 M
    fantom-staking            0
    fantom-pool2              3.48 M
    staking                   0
    pool2                     3.48 M
    
    total                    3.87 M

**Comment by waynebruce0x** [comment]
By swapping one out the old contracts we won't be able to backfill data effectively - is it possible to sum the TVL from both contracts so we can backfill?

**Comment by llamatester** [comment]
The adapter at projects/fantasm/index.js exports TVL: 
        
 
 
    fantom-staking            212.63 k
    fantom                    10.55 M
    fantom-pool2              18.66 k
    staking                   212.63 k
    pool2                     18.66 k
    
    total                    10.55 M

**Comment by ftazm** [comment]
> By swapping one out the old contracts we won't be able to backfill data effectively - is it possible to sum the TVL from both contracts so we can backfill?

Hi, i

**Comment by llamatester** [comment]
The adapter at projects/fantasm/index.js exports TVL: 
        
 
 
    fantom-staking            212.63 k
    fantom                    10.55 M
    fantom-pool2              18.66 k
    staking                   212.63 k
    pool2                     18.66 k
    
    total                    10.55 M

**Pull request merged**
