### PR TITLE
New TVL Adapter for Tangible-ustb protocol

### PR DESCRIPTION
**Pull request by chasebrownn**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### List of audit links if any:
USTB: https://omniscia.io/reports/tangible-ustb-contract-655fb224a7ddc0001831f72e/

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
USTB: real-us-t-bill

##### Short Description (to be shown on DefiLlama):
Tangible is a tokenization protocol that brings valuable, real world assets on chain. Tangible issues the stablecoin USTB (backed by T-bills via Mountain Protocol) as well as Baskets i.e. UKRE, ERC-20's backed by a basket of tokenized (NFTs) yield-generating properties.
Tangible operates on [re.al](http://re.al/), an L2 blockchain dedicated to real world assets (RWAs).

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
NA
##### methodology (what is being counted as tvl, how is tvl being calculated):
We fetch the amount of USTB that's been minted on Ethereum. USTB is only minted with USDM 1:1.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/arcana exports TVL: 
        
 
 
    real                      1.02 M
    
    total                    1.02 M

**Comment by llamatester** [comment]
The adapter at projects/tangible-ustb exports TVL: 
        
 
 
    ethereum                  1.18 M
    
    total                    1.18 M

**Comment by g1nt0ki** [comment]
hi, I thought USTB was wrapped version of mountain usd?

**Comment by llamatester** [comment]
The adapter at projects/arcana exports TVL: 
        
 
 
    real                      1.05 M
    
    total                    1.05 M

**Comment by llamatester** [comment]
The adapter at projects/tangible-ustb exports TVL: 
        
 
 
    ethereum                  1.19 M
    
    total                    1.19 M

**Comment by g1nt0ki** [comment]
I have reverted change to coreAssets file, the tokens there are used for pricing other tokens, so I restrict the # tokens on that file.

**Comment by llamatester** [comment]
The adapter at projects/arcana exports TVL: 
        
 
 
    real                      1.05 M
    
    total                    1.05 M

**Comment by llamatester** [comment]
The adapter at projects/tangible-ustb exports TVL: 
        
 
 
    ethereum                  1.19 M
    
    total                    1.19 M

**Comment by chasebrownn** [comment]
> hi, I thought USTB was wrapped version of mountain usd?

That is correct

**Comment by chasebrownn** [comment]
Anything else needed before merging?

**Comment by g1nt0ki** [comment]
> Anything else needed before merging?

then I am not sure if we should track it

**Comment by g1nt0ki** [comment]
so far, we dont track wrapped token as protocols

**Comment by chasebrownn** [comment]
@g1nt0ki USTB is backed by USDM. USDM is used as collateral, but USTB can depeg on it's own. Completely different projects.

**Comment by g1nt0ki** [comment]
> @g1nt0ki USTB is backed by USDM. USDM is used as collateral, but USTB can depeg on it's own. Completely different projects.

if that is the case, can you share the contract where USDM is stored, we count the tokens locked in a protocol as tvl, not the token supply. For example, maker tvl is locked ether, not dai supply

**Comment by chasebrownn** [comment]
> > @g1nt0ki USTB is backed by USDM. USDM is used as collateral, but USTB can depeg on it's own. Completely different projects.
> 
> if that is the case, can you share the contract where USDM is stored, we count the tokens locked in a protocol as tvl, not the token supply. For example, maker tvl is locked ether, not dai supply

https://etherscan.io/address/0x83fedbc0b85c6e29b589aa6bdefb1cc581935ecd

**Comment by llamatester** [comment]
The adapter at projects/arcana exports TVL: 
        
 
 
    real                      1.09 M
    
    total                    1.09 M

**Comment by llamatester** [comment]
The adapter at projects/tangible-ustb exports TVL: 
        
 
 
    ethereum                  1.08 M
    
    total                    1.08 M

**Pull request merged**
