### PR TITLE
Tranche tvl

### PR DESCRIPTION
**Pull request by hg-tranche**
##### Twitter Link:
https://twitter.com/TrancheFinance

##### List of audit links if any:
https://github.com/tranche-jibrel/Audits

##### Website Link:
https://app.tranche.finance/tranche

##### Current TVL:
6.28 M

##### Chain:
Ethereum, Fantom, Polygon, Avalanche 

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
[tranche-finance](https://api.coingecko.com/api/v3/coins/tranche-finance)

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
8637

##### Token address and ticker if any:
https://etherscan.io/token/0x0aee8703d34dd9ae107386d3eff22ae75dd616d1

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
Yield

### CODE REVIEW

**Comment by waynebruce0x** [comment]
is there a reason we cant use on-chain calls?

**Comment by hg-tranche** [comment]
> is there a reason we cant use on-chain calls?

yes, we seen lot of atoken,ctoken,ytokens prices are not support across different chains are not supported.
ex:
tokens

https://polygonscan.com/address/0x03f44E563dD447449F48f8103b5dF70aFf7CF577 (amUSDC,amWmatic,amDAI etc)

https://ftmscan.com/address/0xe572401aFa7405Ea8EBf657D2b2Ed0Bce0bCf288(yvDAI,yvMIM,yvUSDC etc)

**Comment by waynebruce0x** [comment]
If you can send me the on-chain code you've got, I can unwrap these tokens for you so they count towards TVL. We try to avoid using API calls

**Comment by hg-tranche** [comment]
@waynebruce0x please have a look on new commit.

**Pull request merged**
