### PR TITLE
Add JIBSWAP on JIBCHAIN

### PR DESCRIPTION
**Pull request by jibswaps**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Short Description (to be shown on DefiLlama):
JIBSWAP is a Automated Market Maker (AMM) Decentralized Exchange (DEX) on JIBCHAIN L1 using Uniswap V2 Fork

##### Github org/user (Optional, if your code is open source, we can track activity): https://github.com/jibswap/jibswap-core

### CODE REVIEW

**Comment by jibswaps** [comment]
I think we need to merge [https://github.com/DefiLlama/chainlist/pull/863](https://github.com/DefiLlama/chainlist/pull/863) for adding JIBCHAIN first

**Comment by g1nt0ki** [comment]
@jibswaps thanks for the PR, I have refactored and merged it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/8418

but where can one buy JBC tokens? I am unable to find it in coingecko, so currently you have 0 tvl

**Comment by jibswaps** [comment]
> @jibswaps thanks for the PR, I have refactored and merged it here: #8418
> 
> but where can one buy JBC tokens? I am unable to find it in coingecko, so currently you have 0 tvl

Thank you for the merged, JBC tokens will be listed on CeFi coinstore.com on this December 25. The DEXes will come up after coinstore.

ref: https://twitter.com/CoinstoreExc/status/1736625493838078050

**Comment by jibswaps** [comment]
Hi @g1nt0ki ,
Can we get JBC token price from our AMM pair? Instead of fetching from CeFi or coingecko?

**Comment by g1nt0ki** [comment]
@jibswaps how is the USDT bridged to jibchain, can you share the contract address on the other side where USDT is stored?

**Comment by jibswaps** [comment]
@g1nt0ki USDT will be bridged from bsc, optimism, and more from https://test-f2-jbcbridge.netlify.app/ (this is a temporary url, we didn't publish the official url to users yet)

the contract address of USDT has been confirmed from jibchain dev

USDT: `0xFD8Ef75c1cB00A594D02df48ADdc27414Bd07F8a`
https://exp-l1.jibchain.net/address/0xFD8Ef75c1cB00A594D02df48ADdc27414Bd07F8a

the other token addresses are available here: https://tokenlists.org/token-list?url=https://jibswap.com/tokens.json

**Comment by jibswaps** [comment]
@g1nt0ki this is the contract that store USDT on bsc

https://bscscan.com/address/0x083110e5a5812d8c8400725090c5fdd5df3c2d87

**Comment by g1nt0ki** [comment]
@jibswaps thanks added support here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/a74119c3c2f1fcdc27e1cae89c9258337d64953d

**Comment by jibswaps** [comment]
Hi @g1nt0ki, sorry for interrupt you again.
I just noticed that the logo of Jibchain (JBC) was wrong, how can I change it to this logo?

JBC-logo


Screenshot 2023-12-25 at 23 44 39

Thank you.

**Pull request closed without merging**
