### PR TITLE
Initial version of adapter for GARD protocol

### PR DESCRIPTION
**Pull request by nmadon65**
Adapter for the GARD protocol on Algorand blockchain

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/algogard exports TVL: 
        
 
 
    algorand-borrowed         1.05 M
    algorand                  2.75 M
    borrowed                  1.05 M
    
    total                    2.75 M

**Comment by waynebruce0x** [comment]
The 'borrowed' export is for money markets and not required for cdps - can you remove it? Main TVL part looks good to go

**Comment by nmadon65** [comment]
I changed the file per your request.  The borrowed export was added because users of the protocol can borrow GARD tokens against their supplied ALGOs.

**Comment by llamatester** [comment]
The adapter at projects/algogard exports TVL: 
        
 
 
    algorand                  2.61 M
    
    total                    2.61 M

**Pull request merged**
