### PR TITLE
Add a project named "themisPro"

### PR DESCRIPTION
**Pull request by ThemisCapital**
Name (to be shown on DefiLlama): Themis Protocol
Twitter Link: https://twitter.com/Themis_Pro
Website Link: https://themis.capital/
DEX Link: https://swap.themis.capital/#/swap
Logo (High resolution, will be shown with rounded borders): https://github.com/ThemisCapital/Brand-Asset/blob/main/themisProtocol.png
Treasury Addresses (if the protocol has treasury)：0x0e511806C7AC38cF6d1EeAa9Ee51027e44Dcbf94
Chain: Filecoin-FEVM
USDT is issued by Cbridge, and Cbridge link: https://cbridge.celer.network/

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/themisPro exports TVL: 
        
 
 
    filecoin-staking          0
    filecoin                  0
    staking                   0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/themisPro exports TVL: 
        
 
 
    filecoin-staking          0
    filecoin                  0
    staking                   0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/curve exports TVL: 
        
 
 
    harmony                   0
    ethereum-staking          464.71 M
    celo                      22.26 M
    aurora                    17.30 k
    arbitrum                  80.09 M
    xdai                      16.77 M
    avax                      16.54 M
    optimism                  40.01 M
    kava                      14.35 M
    fantom                    19.99 M
    polygon                   66.40 M
    moonbeam                  523.68 k
    ethereum                  3.52 B
    staking                   464.71 M
    
    total                    3.80 B

**Comment by llamatester** [comment]
The adapter at projects/themisPro exports TVL: 
        
 
 
    filecoin-staking          0
    filecoin                  0
    staking                   0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/curve exports TVL: 
        
 
 
    harmony                   0
    ethereum-staking          464.71 M
    kava                      14.35 M
    moonbeam                  523.80 k
    celo                      22.26 M
    aurora                    17.30 k
    optimism                  40.02 M
    arbitrum                  80.13 M
    fantom                    20.00 M
    avax                      16.55 M
    xdai                      16.74 M
    polygon                   66.42 M
    ethereum                  3.52 B
    staking                   464.71 M
    
    total                    3.80 B

**Comment by llamatester** [comment]
The adapter at projects/themisPro exports TVL: 
        
 
 
    filecoin-staking          0
    filecoin                  0
    staking                   0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/curve exports TVL: 
        
 
 
    harmony                   0
    ethereum-staking          471.98 M
    celo                      22.27 M
    optimism                  40.17 M
    aurora                    17.30 k
    arbitrum                  80.44 M
    avax                      16.57 M
    moonbeam                  525.36 k
    polygon                   66.64 M
    xdai                      16.66 M
    fantom                    20.03 M
    kava                      14.33 M
    ethereum                  3.53 B
    staking                   471.98 M
    
    total                    3.81 B

**Comment by llamatester** [comment]
The adapter at projects/themisPro exports TVL: 
        
 
 
    filecoin-staking          0
    filecoin                  0
    staking                   0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/treasury/themisPro.js exports TVL: 
        
 
 
    filecoin                  0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/curve exports TVL: 
        
 
 
    harmony                   0
    ethereum-staking          467.55 M
    celo                      22.27 M
    arbitrum                  80.13 M
    optimism                  40.07 M
    avax                      16.55 M
    xdai                      16.66 M
    aurora                    17.29 k
    moonbeam                  525.48 k
    polygon                   64.01 M
    fantom                    19.99 M
    kava                      14.32 M
    ethereum                  3.52 B
    staking                   467.55 M
    
    total                    3.80 B

**Comment by llamatester** [comment]
The adapter at projects/themisPro exports TVL: 
        
 
 
    filecoin-staking          0
    filecoin                  0
    staking                   0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/treasury/themisPro.js exports TVL: 
        
 
 
    filecoin                  0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/curve exports TVL: 
        
 
 
    harmony                   0
    ethereum-staking          467.55 M
    celo                      22.27 M
    optimism                  40.07 M
    aurora                    17.29 k
    kava                      14.32 M
    avax                      16.55 M
    moonbeam                  525.48 k
    polygon                   64.01 M
    arbitrum                  80.13 M
    xdai                      16.66 M
    fantom                    20.03 M
    ethereum                  3.52 B
    staking                   467.55 M
    
    total                    3.80 B

**Comment by llamatester** [comment]
The adapter at projects/themisPro exports TVL: 
        
 
 
    filecoin-staking          0
    filecoin                  0
    staking                   0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/treasury/themisPro.js exports TVL: 
        
 
 
    filecoin                  0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/curve exports TVL: 
        
 
 
    harmony                   0
    ethereum-staking          467.17 M
    celo                      22.25 M
    arbitrum                  80.11 M
    optimism                  40.07 M
    xdai                      16.67 M
    avax                      16.55 M
    aurora                    17.29 k
    moonbeam                  525.45 k
    polygon                   64.00 M
    fantom                    20.03 M
    kava                      14.32 M
    ethereum                  3.52 B
    staking                   467.17 M
    
    total                    3.80 B

**Comment by llamatester** [comment]
The adapter at projects/themisPro exports TVL: 
        
 
 
    filecoin-staking          0
    filecoin                  0
    staking                   0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/treasury/themisPro.js exports TVL: 
        
 
 
    filecoin                  0
    
    total                    0

**Comment by g1nt0ki** [comment]
hi @ThemisCapital I have made a slightly different version of your code here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/6649

but how is USDT bridged to FVM? I was unable to any documentation

**Comment by g1nt0ki** [comment]
ah, it is already answered here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/6440#issuecomment-1605812971

**Pull request closed without merging**
