### PR TITLE
Midas Capital adapter

### PR DESCRIPTION
**Pull request by rhlsthrm**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

##### Twitter Link:
https://twitter.com/MidasCapitalxyz

##### List of audit links if any:
https://medium.com/midas-capital/audit-with-zellic-29b63f1be25a

##### Website Link:
https://midascapital.xyz/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
Light - https://github.com/Midas-Protocol/icons/blob/main/social/Light.png
Dark - https://github.com/Midas-Protocol/icons/blob/main/social/Dark.png

##### Current TVL:
$408k

##### Chain:
BSC, Moonbeam (more coming)

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
No token ID

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
No token ID

##### Short Description (to be shown on DefiLlama):
Permissionless isolated lending pools for customizable creation of lending/borrowing markets.

##### Token address and ticker if any:
None yet.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
All

##### forkedFrom (Does your project originate from another project):
Rari Capital

##### methodology (what is being counted as tvl, how is tvl being calculated):
Using Compound built in connectors.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/midas-capital exports TVL: 
        
 
 
    moonbeam-borrowed         0
    moonbeam                  0
    bsc                       77.80 k
    bsc-borrowed              3.35 k
    borrowed                  3.35 k
    
    total                    77.80 k

**Comment by Define101** [comment]
Hi, what is the main oracle you guys use?

**Comment by rhlsthrm** [comment]
> Hi, what is the main oracle you guys use?

Hello! We use Chainlink where available but if not available we either use another oracle provider or else we run our own TWAPs.

**Comment by Define101** [comment]
I see, thanks for the information

**Comment by Define101** [comment]
And btw, the links to your logos are not working
Could you put the image here?

**Comment by rhlsthrm** [comment]
Dark
Light

@Define101

**Pull request merged**
