### PR TITLE
feat: add Diamond protocol

### PR DESCRIPTION
**Pull request by AnnieChi1020**
##### Twitter Link:
https://twitter.com/DiamondProtocol

##### Website Link:
https://dmo.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
- dark background: https://dmo.finance/images/logo-yellow-dark-backgroud.png
- white background: https://dmo.finance/images/logo-white-backgroud.png
- transparent background: https://dmo.finance/images/logo-transparent-backgroud.png

##### Chain:
Ethereum

##### Short Description (to be shown on DefiLlama):
Diamond is a modular vault protocol where #DeFi strategists can build and deploy on-chain strategies without writing code.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink and our own oracle

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/diamond/index.js exports TVL: 
        
 
 
    ethereum                  22.36 k
    
    total                    22.36 k

**Comment by waynebruce0x** [comment]
Where does the ETH counted here sit? Can you verify the contract so we can see what the function we're calling does?

**Comment by llamatester** [comment]
The adapter at projects/diamond/index.js exports TVL: 
        
 
 
    ethereum                  22.36 k
    
    total                    22.36 k

**Comment by AnnieChi1020** [comment]
> Where does the ETH counted here sit? Can you verify the contract so we can see what the function we're calling does?

Hi @waynebruce0x, we plan to verify the contract after finishing the audit. Should we wait til that?

**Pull request merged**
