### PR TITLE
Moveflow

### PR DESCRIPTION
**Pull request by rellyxx**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Logo (High resolution, will be shown with rounded borders):
image

### CODE REVIEW

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
can you fix the merge conflicts by rebasing your commit against main?

Also, can you update code to compute tvl on chain

**Comment by llamatester** [comment]
The adapter at projects/blend-finance exports TVL: 
        
 
 
    bevm                      1.48 k
    bevm-borrowed             0
    borrowed                  0
    
    total                    1.47 k

**Comment by llamatester** [comment]
The adapter at projects/predx exports TVL: 
        
 
 
    zklink                    2
    
    total                    1.996807194

**Comment by llamatester** [comment]
The adapter at projects/moveflow exports TVL: 
        
 
 
    aptos                     1
    
    total                    0.5353056709999999

**Comment by rellyxx** [comment]
projects/blend-finance and  projects/predx nothing to do with this moveflow pr

**Comment by g1nt0ki** [comment]
"projects/blend-finance and projects/predx nothing to do with this moveflow pr" I know, that's why I asked you to rebase your commit instead of merging main branch

**Comment by llamatester** [comment]
The adapter at projects/blend-finance exports TVL: 
        
 
 
    bevm                      1.59 k
    bevm-borrowed             0
    borrowed                  0
    
    total                    1.59 k

**Comment by llamatester** [comment]
The adapter at projects/moveflow exports TVL: 
        
 
 
    aptos                     1
    
    total                    0.5807561525

**Pull request closed without merging**
