### PR TITLE
IntentX TVL net deposits

### PR DESCRIPTION
**Pull request by lemonpac**
We have created this adapter that represent TVL of collateral deposited by users to IntentX platform taking into account the withdraws that might be done

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/intentx.js exports TVL: 
        
 
 
    base                      811.52 k
    
    total                    811.52 k

**Comment by g1nt0ki** [comment]
hi @lemonpac 
thanks for the PR, is this your app's vault: https://basescan.org/address/0x52e2230cdb80edebdadafcf24033608c9a636d7d#code

can we count the USDC balance there as tvl instead of relying on graph? (less dependencies = less chances of adapter breaking)

**Comment by lemonpac** [comment]
Due to the complexity of the protocol is quite difficult to isolate it without using a graph.
All the funds are sent to this wallet 0x52e2230cDb80EDEBDaDafcf24033608C9A636D7D but those funds are not only the ones used in the platform so it would be counting extra TVL.
We'll try to work on a on-chain function to get this isolated data, meanwhile, using the graph is the best choice

**Comment by lemonpac** [comment]
https://basescan.org/address/0x52e2230cdb80edebdadafcf24033608c9a636d7d#tokentxns

**Pull request merged**
