### PR TITLE
Configure external chain deposits for cross-chain Balanced DEX

### PR DESCRIPTION
**Pull request by usr-icon-foundation**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/balanced exports TVL: 
        
 
 
    archway                   0
    binance                   0
    avax                      0
    icon                      0
    
    total                    0

**Comment by usr-icon-foundation** [comment]
- Placed getExternalChainDeposits and computeTVL functions in balanced/helper.js
- Updated balanced/index.js to filter out external deposits from the icon TVL and attribute these external deposits to their origin chains.

llamatester reporting 0 TVL for all chains

**Comment by llamatester** [comment]
The adapter at projects/balanced exports TVL: 
        
 
 
    icon                      4.03 M
    avax                      912.46 k
    archway                   123.75 k
    binance                   35.32 k
    
    total                    5.10 M

**Comment by g1nt0ki** [comment]
@usr-icon-foundation can you share the contracts addresses on avax/bnb chain used as bridge for this, easier to compute tvl by looking at token balances there, also for users to verify on source chain

**Comment by usr-icon-foundation** [comment]
Of course @g1nt0ki 

AVAX
"Asset Manager": 0xdf851B4f0D9b2323e03B3980b1C4Cf56273c0bd9
BSC
"Asset Manager": 0x69e81Cea7889608A63947814893ad1B86DcC03Aa

Here is an overview of all Balanced contract addresses
https://github.com/balancednetwork/balanced-java-contracts/wiki/Contract-Addresses

Let me know if that is sufficient information

**Comment by g1nt0ki** [comment]
thanks @usr-icon-foundation

**Comment by llamatester** [comment]
The adapter at projects/balanced exports TVL: 
        
 
 
    icon                      3.93 M
    avax                      909.69 k
    archway                   122.03 k
    bsc                       33.93 k
    
    total                    4.99 M

**Comment by g1nt0ki** [comment]
for now, I have left it as is, as we dont have price support for hyTB  atm

**Comment by usr-icon-foundation** [comment]
Thanks @g1nt0ki

**Pull request merged**
