### PR TITLE
update harmony tvl

### PR DESCRIPTION
**Pull request by 442879722**

### CODE REVIEW

**Comment by 442879722** [comment]
Hi we have added the tvl info for our 2 other deposited assets

**Comment by waynebruce0x** [comment]
Can you separate the TVL out by chain? Examples of how to structure your module exports can be found in the repo, for example https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/curve/index.js

**Comment by 442879722** [comment]
Hi there, separation completed!

**Comment by 442879722** [comment]
hi there, the pr is merged successfully but the page wbsite doesn't update, could you please give a look? thanks for your time

**Comment by 0xngmi** [comment]
fixed it, exports were wrong

**Pull request merged**
