### PR TITLE
feat: add Manta-MYield

### PR DESCRIPTION
**Pull request by juntingzhang**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Manta-MYield

##### Twitter Link:
https://x.com/CedefiYield

##### Website Link:
https://www.myield.xyz/

##### Logo (High resolution, will be shown with rounded borders):
image

##### Current TVL:
$100861286

##### Chain:
Manta

##### Short Description (to be shown on DefiLlama):
    Unlock the full potential of your mToke within the Manta Pacific. With mETH, mBTC, and mUSD, you can seamlessly integrate DeFi on Manta Pacific and start earning yields on your mToken. Whether you're a CeDeFi user or just getting started, <name> offers a range of opportunities to grow your portfolio and achieve your financial goals.
    Discover how Manta Pacific's innovative DeFi solutions can help you maximize your returns, reduce transaction costs, and take advantage of the most competitive rates in the market. Join the <name> and let your mToken work harder for you.
    Explore the Manta Pacific ecosystem today and see how mETH, mBTC, and mUSD can transform your financial future.

##### Token address and ticker if any:
https://pacific-explorer.manta.network/token/0x649d4524897cE85A864DC2a2D5A11Adb3044f44a
https://pacific-explorer.manta.network/token/0xACCBC418a994a27a75644d8d591afC22FaBA594e
https://pacific-explorer.manta.network/token/0x1468177DbCb2a772F3d182d2F1358d442B553089

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yield

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/manta-myield exports TVL: 
        
 
 
    manta                     75.62 M
    
    total                    75.62 M

**Comment by g1nt0ki** [comment]
thanks for the PR

**Comment by juntingzhang** [comment]
@g1nt0ki Hi, This project allows users to stake the mToken, like MUSD,METH to earn more.

**Comment by juntingzhang** [comment]
@g1nt0ki  Hi, The project allows users to stake MToken to earn more, it's 'Farm' Category, the stake contract is 0x1B9bcc6644CC9b5e1F89aBaAb66904F5a562d4a1, You can see via link:  https://pacific-explorer.manta.network/address/0x1B9bcc6644CC9b5e1F89aBaAb66904F5a562d4a1?tab=tokens

**Comment by juntingzhang** [comment]
@g1nt0ki  
All mtokens including mBTC/mETH/mUSD are under custody only on Ethereum and BSC not on Manta Pacific, there is no double counting on Manta Pacific chain by counting all mtoken value into TVL

The CeDeFi product work flow are as follows:
1.Users deposit wBTC/ETH/Stables on ETH/BSC/Manta chain into CeDeFi contract
2.For ETH/BSC chain deposited assets, Ethereum & BSC ManagerAdapter will direct these assets to Ceffu hot wallet; for Manta chain deposited assets, those assets are bridged out of the network and deposited into Ethereum ManagerAdapter to follow the same process (thus, no asset stays on Manta and mtokens do not contribute to double-counting)
3.The Ceffu hot wallet will reorganize the assets by sending into different cold wallet for security reason (And Ceffu has not supported Manta Pacific chain yet)

Thus, there is no double counting by calculating all mTokens (Including mBTC & mETH & mUSD) into Manta Pacific chain TVL

Attached is the CeDefi product related contract:
1.CeDefi related contract:
Users stake wBTC/ETH/Stables contract on Ethereum - Ethereum ManagerAdapter: 0x82A21E04f1851408e814c3d3Fa64b5d02Aa8D573
Users stake wBTC/ETH/Stables contract on BSC - BSC ManagerAdapter 0x649d4524897cE85A864DC2a2D5A11Adb3044f44a
2.Ceffu hot wallet address: 0x0Ef3F47Af549546A2d59f32fdcA33CB1CfF4AabC

Also attached are mtoken price source from Coingecko:
mBTC price: https://www.coingecko.com/en/coins/manta-mbtc
mETH price: https://www.coingecko.com/en/coins/manta-meth
mStable price: https://www.coingecko.com/en/coins/manta-musd

**Pull request merged**
