### PR TITLE
Add Brewlabs Adapter

### PR DESCRIPTION
**Pull request by brainstormk**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama): 
Brewlabs

##### Twitter Link: 
https://twitter.com/TeamBrewlabs

##### List of audit links if any: 
https://www.certik.com/projects/brewlabs

##### Website Link: 
https://brewlabs.info/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://raw.githubusercontent.com/brewlabs-code/assets/master/blockchains/smartchain/assets/0x6aAc56305825f712Fd44599E59f2EdE51d42C3e7/logo.png

##### Current TVL: 
------ TVL ------
bsc                       9.50 M
polygon                   56.62 k
ethereum                  5.40 M

total                    14.95 M

##### Chain
Ethereum, BSC, Polygon

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
{"id":"brewlabs","symbol":"brewlabs","name":"Brewlabs"}

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
{"id":16405,"name":"Brewlabs","symbol":"BREWLABS","slug":"brewlabs","is_active":1,"status":"active"}

##### Short Description (to be shown on DefiLlama):
Brewlabs offers individuals the opportunity to bring their cryptocurrency ideas to life through smart contract engineering, dapp/web3 development, auditing and launch. Brewlabs offers a suite of tools and DeFI products routing fee revenue back to buy back the BREWLABS token through an innovating treasury buy back model.

##### Token address and ticker if any:
Ethereum: 0xdAd33e12e61dC2f2692F2c12e6303B5Ade7277Ba, BREWLABS
BSC: 0x6aac56305825f712fd44599e59f2ede51d42c3e7, BREWLABS

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Yields

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is made up of staking, yield farming, NFT staking and indexes within the Brewlabs dAPP ecosystem.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/brewlabs exports TVL: 
        
 
 
    polygon                   56.52 k
    bsc                       9.50 M
    ethereum                  5.40 M
    
    total                    14.96 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
hi, this needs to be refactored quite a bit, I can do it but bit busy right now.

Mainly, tvl coming from your own tokens (BREW) should be moved to staking/pool2: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

Also, it is okay to fetch pool/farm config from your server (we cache these responses) but not tvl itself because it is opaque/we are left with broken adapter when project stops maintaining the api

Also, how are you pricing NFTs? most cases, we dont include it at all

**Comment by llamatester** [comment]
The adapter at projects/brewlabs exports TVL: 
        
 
 
    polygon-staking           0
    polygon                   62.41 k
    bsc                       10.23 M
    ethereum                  6.34 M
    bsc-staking               3.81 M
    ethereum-staking          275.16 k
    staking                   4.08 M
    
    total                    16.63 M

**Comment by g1nt0ki** [comment]
I have squashed and merged your changes here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/5230

I am still in two minds, unsure if it should be split into pool2 and staking and tvl set to 0, for now I have left it as it is, will change if some other team/users complain

**Pull request closed without merging**
