### PR TITLE
goal3-lockdrop - goal3 lockdrop tvl

### PR DESCRIPTION
**Pull request by andrewpixelgoal3**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/goal3-lockdrop exports TVL: 
        
 
 
    era                       1.13 M
    
    total                    1.13 M

**Comment by andrewpixelrada** [comment]
> The adapter at projects/goal3-lockdrop exports TVL:
> 
> ```
> era                       1.13 M
> 
> total                    1.13 M 
> ```
era                          1,19M
total                        1,19M

**Comment by andrewpixelrada** [comment]
@llamatester i've pushed new commit to define owners local variable, please check it, thanks!

**Comment by g1nt0ki** [comment]
hi @andrewpixelrada , thanks for the PR, this does not appear to be a smart contract, so funds are transferred to a normal wallet when people lock? https://zksync2-mainnet.zkscan.io/address/0xa5aD8953DE51CeD330E788DDDde19A5f96CaC082/transactions

**Comment by andrewpixelrada** [comment]
> hi @andrewpixelrada , thanks for the PR, this does not appear to be a smart contract, so funds are transferred to a normal wallet when people lock? https://zksync2-mainnet.zkscan.io/address/0xa5aD8953DE51CeD330E788DDDde19A5f96CaC082/transactions

hi @g1nt0ki, yes that’s correct. The smart contract is a lockdrop smart contract, which is intended to raise liquidity for our DAO Treasury. Later this month we will have an official smart contract for our Dapp to store the fund, which prolly means we have to update the contract again on your end? 

Please excuse the confusion, but we’re looking to establish some PR exposure in the zkSync Ecosystem, hence this ‘temporary’ listing. Our project is 6 month old and we are KYC’ed with the zkSync Team,  if that helps with any assurance.

**Comment by g1nt0ki** [comment]
hi @andrewpixelrada , sorry this is very unusual, can you get back when you have moved the funds to a smart contract and we will list it then

**Comment by g1nt0ki** [comment]
> hi @andrewpixelrada , sorry this is very unusual, can you get back when you have moved the funds to a smart contract and we will list it then

.

**Pull request closed without merging**
