### PR TITLE
feat: fix Dinari tvl

### PR DESCRIPTION
**Pull request by jaketimothy**
Our factory contract and order fill data can be used to compute TVL for all our assets. 

This fixes current incorrect tokens and incomplete pricing information in a sustainable way going forward.

Not sure best way to use our trade prices to update USD TVL displayed on DefiLlama, see code change.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/dinari exports TVL: 
        
 
 
    arbitrum                  40.87 k
    
    total                    40.87 k

**Comment by jaketimothy** [comment]
lmk if you'd rather have a PR against https://github.com/DefiLlama/defillama-server/blob/master/coins/src/adapters/rwa/dinari.ts

**Comment by g1nt0ki** [comment]
> lmk if you'd rather have a PR against https://github.com/DefiLlama/defillama-server/blob/master/coins/src/adapters/rwa/dinari.ts

yeah, that is better, can you put up a PR there?

**Comment by jaketimothy** [comment]
> > lmk if you'd rather have a PR against https://github.com/DefiLlama/defillama-server/blob/master/coins/src/adapters/rwa/dinari.ts
> 
> yeah, that is better, can you put up a PR there?

https://github.com/DefiLlama/defillama-server/pull/7036

**Pull request merged**
