### PR TITLE
Metis TVL review

### PR DESCRIPTION
**Pull request by vmmunoza**
The reported TVL does not reflect the proper value locked, even considering just one of the large DeFi protocols like WAGMI, MaiaDAO, NETSWAP, Tethys.

The daily inflow reported also does not reflect the one that can be estimated via value locked in escrow contracts.

Please verify considering the main bridge contract:

0x3980c9ed79d2c191A89E02Fa3529C60eD6e9c04b

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

https://www.coingecko.com/en/chains/metis-andromeda

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

https://coinmarketcap.com/currencies/metisdao/historical-data/

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/metis exports TVL: 
        
 
 
    ethereum                  809.43 M
    
    total                    809.43 M

**Comment by vmmunoza** [comment]
> The adapter at projects/metis exports TVL:
> 
> ```
> ethereum                  809.43 M
> 
> total                    809.43 M 
> ```

This is the one displayed in the DefiLlama site right now:

image

**Comment by g1nt0ki** [comment]
closing this as invalid: https://github.com/DefiLlama/DefiLlama-Adapters/discussions/435

**Comment by vmmunoza** [comment]
> closing this as invalid: #435

You close this without giving any explanation and without addressing the review request?

**Pull request closed without merging**
