### PR TITLE
Add MewFinance 

### PR DESCRIPTION
**Pull request by wombo22**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
can you explain what kind of contract it is that you shared, and what mew does? I checked the [dex page](https://dex.mewfinance.com/ergo/swap?base=0000000000000000000000000000000000000000000000000000000000000000) but is actually spectrum dex pools?

**Comment by wombo22** [comment]
Thanks you g1nt0ki for reviewing. Mew has quite a few tools such as such as p2p escrow contracts, funding mechanisms, a dex which you are correct is utlizing the spectrum pool contracts, etc. 

The contract that I have shared would be the locking of the mew tokens in which people would lock tokens to gain access to benefits such as dex fee, mart sale fee, mart list fee, mart cancel fee, etc. Essentially benefits for all the tools.

Link to benefits/locking page: https://mewfinance.com/tokenomics
Link to MewFinance tools: https://mewfinance.com/

Also, if I could also shorten the description to the following: MEWFinance, a decentralized platform on Ergo blockchain, offers a full-featured exchange for digital asset trading in an open marketplace with an innovative trade house system. It includes a secure crowdfunding protocol for community-driven projects, ensuring transparent, non-custodial control of assets. 

Please let me know if you have any more questions or anything I can clear up.

Thank you!

**Comment by g1nt0ki** [comment]
thanks, tracking locked MEW under staking now, will list asap.

**Comment by wombo22** [comment]
Thanks again for your help!

**Comment by Hq3r** [comment]
> thanks, tracking locked MEW under staking now, will list asap.

GOOD EVENING BUDDY, i am founder of mewfinance , glad to be on defillama , ergo community enjoys it alot !
would like to see how the categories all our extensions, as we are fork of spectrum dex and use same amm pools, can we be listed in dex category too? , for mew daily trading vol, could use this

https://api.crooks-fi.com/tokens/dexStats?dex=Mew
you just need to exclude our vol from spectrum , to differenciate which is which as spectrum shows mew + spectrum .

apart of that,
https://mart.mewfinance.com/ (nfts, tokens p2p tradign tradehouse , marketplace)

smart contract : 2sTiXsgg5x6T8pMqxruCsfKtQh5JcN9TgBWpT6PLkNUg6Gvkg923sXUbwm9iv4Yi2yH6f2e9a6HzY2WF3ScSBVKmCE1WJBvpRLugRY7xxDvYmkdPA1XV1rvhSQTPMoU6fwBuGxuzdjjmWGYyt3jqLJhEHh59X4vpd5GpeEyjvhTxiTc2a1UTpzaeasyLQmYdhGuLFeSvxGgxWMD8mer1aoEq1AiBwkBdSo2DCKo81UPrXFn934cNTpPcUGoG4cTwdhMX7z1N3VyZ74dBbWPDsN6V6oBVaaUW9ggWRwttmTAGQywEobFwgDswEu8XZSRDUXg77ivAywy9DfrjkbutRjNCgh1fExtKG8QWEHkPcALwLaKT7QsKJcEVmC3rGBQSeTHEozx9FPniM47847yxk4A9wG5MaUoFbwiBbFEusWaTsNN9jEP7M8Uw5RFkeyQhooEG1A32R59pgoouXiUc974VXeaP8J1rSey3FD5VjsQc6tFhEdcAN5ULSaWXrHxoHEaHJHZyPQmejzX7hdy 

escrow contract ; 
K8aVsCzYvfyGasbejtfzy5vV4LQ8J7x6kcabAYEsLfZbdP96M33MMf3ZPDqnj8irN7LERHAfobeuHDxRTjZYj1UKm7515r9CM8cPKMQLrb3PrvGdamDwBU5qvpTLE2sdwpEHb9p8fiNWdAF3mhnhfJy5Fzj95HCC1b5PtZ374mZqS7cphzSM9YzLhUj7vxUGd2JUhgWtgyZhR8SDxgmCDUbkY5V4se9oRKaw4uWCBzcmP9Yyqa2Qd7M1sQsnQivketfpi6L57kzPwJdVFxzYZmQLaMaSDrPxBvWqHpQNF2mvHB5zZwbxtNSDs6jMcB6FEfpBDABBvB2GrMJhc1YE8B3Go3ZYw9EX15hir79pkpqhd9AxCRRwDC5i2wPFZjcmZsvAh8aitPEngMsCJpdhT53y2bLHkP6r2EZKjNKLxjWfCgoeustcjpYwgSveHnjuCTdwNMUx4RaremxPEUXv1aNpiRW6iSfAaZr7QVEe4M4JXwqLVEUvwM7Pv7ijrkSvZdbQkRhrfaQHdjV893DzhCHEXLjG

https://store.mewfinance.com/ (phygitals, tokenized real world assets )
shares same contract as mart contract 
2sTiXs....jzX7hdy 

open to help in understanding  all parts about mewfi , and contribute in code if needed :)

**Comment by realdealshaman** [comment]
Hey @wombo22 when you say Spectrum, do you mean ErgoDEX?

**Comment by Hq3r** [comment]
> Hey @wombo22 when you say Spectrum, do you mean ErgoDEX?

yes, spectrum used to be ergodex, now its back to ergodex , my bad 👍

**Comment by realdealshaman** [comment]
I've updated the category, will ping @g1nt0ki so that he can take a look at the other requests

**Pull request closed without merging**
