### PR TITLE
add solhero

### PR DESCRIPTION
**Pull request by solanahero**
##### Twitter Link: 
https://twitter.com/SolheroFi

##### Website Link:
https://solhero.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://github.com/solanahero/logo/blob/main/logo1024.png

##### Current TVL:
789,512

##### Chain:
SOLANA

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
https://www.coingecko.com/en/coins/solhero

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
https://coinmarketcap.com/currencies/solhero-finance/

##### Short Description (to be shown on DefiLlama):
SolHero is a decentralized NFT hero simulation RPG game powered by Solana smart contracts.

##### Token address and ticker if any:
Hero6s7zJXsw9hfCXLVR5stLqgCok3E7CCkpQEoLAk2g

##### Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one:
GameFi

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL consists of staked tokens and raydium LPs

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Can staked HERO be exported as a separate 'staking' export?

**Comment by solanahero** [comment]
> Can staked HERO be exported as a separate 'staking' export?

**Yes ser**

**Comment by solanahero** [comment]
> Can staked HERO be exported as a separate 'staking' export?

hi Bruce Can merge now?

**Comment by waynebruce0x** [comment]
HERO isn't exported as 'staking' though

**Pull request closed without merging**
