### PR TITLE
Update Gambit Tvl

### PR DESCRIPTION
**Pull request by ALPHADA**
**NOTE**

- Update Gambit Tvl

- Please check [this page](https://gambit.trade/vault)  
- 스크린샷 2023-10-12 오전 10 10 51

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/gambit exports TVL: 
        
 
 
    era                       51.64 k
    
    total                    51.64 k

**Comment by llamatester** [comment]
The adapter at projects/gambit exports TVL: 
        
 
 
    era                       51.64 k
    
    total                    51.64 k

**Comment by llamatester** [comment]
The adapter at projects/gambit exports TVL: 
        
 
 
    era                       51.61 k
    
    total                    51.61 k

**Comment by g1nt0ki** [comment]
thanks, included your change here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/412ab4eab578067c2e5ce9858ece5050e135d7d7

**Pull request closed without merging**
