### PR TITLE
refactor: update Sphere TVL to be computed on-chain

### PR DESCRIPTION
**Pull request by Avedith**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/sphere-finance: 
        
 
  
    
    
    Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8","data":"0x70a08231000000000000000000000000a6efac6a6715ccce780f8d9e7ea174c4d85dbe02","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:654:52
        at Array.forEach (<anonymous>)

**Comment by llamatester** [comment]
Error while running adapter at projects/sphere-finance: 
        
 
  
    
    
    Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0x82aF49447D8a07e3bd95BD0d56f35241523fBab1","data":"0x70a08231000000000000000000000000a6efac6a6715ccce780f8d9e7ea174c4d85dbe02","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:654:52
        at Array.forEach (<anonymous>)

**Comment by llamatester** [comment]
Error while running adapter at projects/sphere-finance: 
        
 
  
    
    
    Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9","data":"0x70a08231000000000000000000000000a6efac6a6715ccce780f8d9e7ea174c4d85dbe02","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:654:52
        at Array.forEach (<anonymous>)

**Comment by llamatester** [comment]
The adapter at projects/sphere-finance exports TVL: 
        
 
 
    optimism                  0
    arbitrum                  0
    
    total                    0

**Comment by Avedith** [comment]
It should be showing at least $900 TVL, but not a concern for now as we don't use these chains anymore. Will figure out if there is a bigger issue once I finish the adapter for  BSC and Polygon.

**Comment by llamatester** [comment]
The adapter at projects/sphere-finance exports TVL: 
        
 
 
    optimism                  0
    arbitrum                  0
    binance                   0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/sphere-finance exports TVL: 
        
 
 
    optimism                  0
    arbitrum                  0
    binance                   0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/sphere-finance exports TVL: 
        
 
 
    optimism                  0
    arbitrum                  0
    binance                   0
    
    total                    0

**Comment by llamatester** [comment]
Error while running adapter at projects/sphere-finance: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:203:11

**Comment by llamatester** [comment]
The adapter at projects/sphere-finance exports TVL: 
        
 
 
    binance                   0
    arbitrum                  158.68863195970982
    optimism                  650.3113911864086
    
    total                    809.0000231461185

**Comment by llamatester** [comment]
Error while running adapter at projects/sphere-finance: 
        
 
  
    
    
    PromisePoolError: Cannot read properties of undefined (reading 'network')
    Truncated error stack:
        at Function.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
The adapter at projects/sphere-finance exports TVL: 
        
 
 
    arbitrum                  158.94701423838117
    optimism                  651.4377670883629
    bsc                       18.02 k
    
    total                    18.83 k

**Comment by llamatester** [comment]
Error while running adapter at projects/sphere-finance: 
        
 
  
    
    
    Error: Invalid balance: NaN
    Truncated error stack:
        at isValidNumber (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:119:19)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:317:16
        at Array.forEach (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:311:28)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:324:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:146:9
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
The adapter at projects/sphere-finance exports TVL: 
        
 
 
    arbitrum                  160.0054469068617
    optimism                  654.8260190064304
    bsc                       18.09 k
    
    total                    18.91 k

**Comment by llamatester** [comment]
Error while running adapter at projects/sphere-finance: 
        
 
  
    
    
    PromisePoolError: invalid address (argument="address", value="0x20d61737f972eecb0af5f0a85ab358cd083dd56a,0x1a2ce410a034424b784d4b228f167a061b94cff4,0x826b8d2d523e7af40888754e3de64348c00b99f4", code=INVALID_ARGUMENT, version=address/5.7.0) (argument="account", value="0x20d61737f972eecb0af5f0a85ab358cd083dd56a,0x1a2ce410a034424b784d4b228f167a061b94cff4,0x826b8d2d523e7af40888754e3de64348c00b99f4", code=INVALID_ARGUMENT, version=abi/5.7.0)
    Truncated error stack:
        at Function.createFrom (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
Error while running adapter at projects/sphere-finance: 
        
 
  
    
    
    Error: Invalid balance: NaN
    Truncated error stack:
        at isValidNumber (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:119:19)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:317:16
        at Array.forEach (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:311:28)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:324:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:146:9
        at async Promise.all (index 0)

**Comment by llamatester** [comment]
The adapter at projects/sphere-finance exports TVL: 
        
 
 
    arbitrum                  159.43579715849836
    polygon                   192.28 k
    bsc                       18.10 k
    optimism                  652.9183222534293
    
    total                    211.19 k

**Pull request closed without merging**
