### PR TITLE
Add DonaSwap V3

### PR DESCRIPTION
**Pull request by 0xfirechain**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
DONASWAP V3

##### Twitter Link:
https://twitter.com/0xdonaswap

##### Logo (High resolution, will be shown with rounded borders):
https://www.donaswap.com/logo.png

##### Current TVL:
0

##### Chain:
All EVM supported running mainnet & testnet networks

##### Short Description (to be shown on DefiLlama):
DONASWAP is the primary multichain dex for the Firechain Ecosystem which sprouted by the Donaswap Token.

##### Token address and ticker if any:
FLAME (Coming Soon)

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### methodology (what is being counted as tvl, how is tvl being calculated):
Factory address (0x9C3AFDDEa87a726891A44C037242393D524CAcFE) is used to find the LP pairs. TVL is equal to the liquidity on the AMM.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/donaswap-v3: 
        
 
  
    
    
    Error: No RPCs available for fusion
    Truncated error stack:
        at LlamaProvider._performAction (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/LlamaProvider.js:87:19)

**Comment by llamatester** [comment]
Error while running adapter at projects/donaswap-v3: 
        
 
  
    
    
    Error: No RPCs available for linea
    Truncated error stack:
        at LlamaProvider._performAction (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/LlamaProvider.js:87:19)

**Comment by llamatester** [comment]
Error while running adapter at projects/donaswap-v3: 
        
 
  
    
    
    Error: No RPCs available for moonbeam
    Truncated error stack:
        at LlamaProvider._performAction (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/LlamaProvider.js:87:19)

**Comment by 0xfirechain** [comment]
What seems to be problem? They all pass the test when testing with node test.js projects/donaswap-v3/index.js

**Comment by g1nt0ki** [comment]
fetching logs is expensive, especially if one needs to go back months: https://github.com/DefiLlama/DefiLlama-Adapters/pull/8645#issuecomment-1889177245

**Comment by g1nt0ki** [comment]
closing again as there was no response

**Pull request closed without merging**
