### PR TITLE
Update hydradex

### PR DESCRIPTION
**Pull request by ipetrov22**
The PR renames current `hydradex` adapter to `hydradex-v2` and introduces a new `hydradex-v3` adapter

##### Name (to be shown on DefiLlama):
`Hydradex` should breakdown to `Hydradex-V2` and `Hydradex-V3` as `Uniswap` does

##### Current TVL:
V2 - 521.07 k
V3 - 1.66 M

##### Chain:
Hydra

##### methodology (what is being counted as tvl, how is tvl being calculated):
The newly added `hydradex-v3` adapter uses a subgraph to collect the data. All pool's liquidity is counted towards the TVL.

##### Everything else
Unchanged

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/hydradex-v3 exports TVL: 
        
 
 
    hydra                     1.66 M
    
    total                    1.66 M

**Comment by g1nt0ki** [comment]
@ipetrov22 thanks for the PR, can you share the rpc endpoint of hydra chain so I can convert to compute tvl on chain?

**Comment by ipetrov22** [comment]
> @ipetrov22 thanks for the PR, can you share the rpc endpoint of hydra chain so I can convert to compute tvl on chain?

Greetings! Hydra's RPC is different than Ethereum's and therefore it's complicated to calculate the tvl on chain since we can't use the already setup tools for ETH like chains.

We've used a parser to translate the Hydra RPC calls to ETH format so we can use TheGraph, but we don't have a public instance of it yet.

Therefore the easiest way for the TVL calculation is using the subgraph we have deployed.
Yet, if it's required I could provide an endpoint for a public node that can handle Hydra RPC requests.

Hydra RPC docs: [https://locktrip.gitbook.io/hydra-documentation/essentials/command-lines-rpc-api](https://locktrip.gitbook.io/hydra-documentation/essentials/command-lines-rpc-api)

**Comment by llamatester** [comment]
The adapter at projects/hydradex.js exports TVL: 
        
 
 
    hydra                     520.67 k
    
    total                    520.67 k

**Comment by llamatester** [comment]
The adapter at projects/hydradex exports TVL: 
        
 
 
    hydra                     520.67 k
    
    total                    520.67 k

**Comment by llamatester** [comment]
The adapter at projects/hydradex-v3 exports TVL: 
        
 
 
    hydra                     1.65 M
    
    total                    1.65 M

**Pull request merged**
