### PR TITLE
Limitless TVL

### PR DESCRIPTION
**Pull request by jihyunsong42**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

Hi, I've checked your refactored code, thanks.
but I think TVL is not shown properly as it supposed to. Can you check if there's anything missing?

tvl
tvlll

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/limitless exports TVL: 
        
 
 
    base                      145.32 k
    arbitrum                  0
    linea                     0
    
    total                    145.33 k

**Comment by g1nt0ki** [comment]
hmm, had a brief look, not sure where the issue is, will go through the code again next week

**Comment by jihyunsong42** [comment]
Hi, I am just wondering if you figured out the issue. If  you have any questions please let me know

**Comment by llamatester** [comment]
The adapter at projects/limitless exports TVL: 
        
 
 
    base                      1.56 M
    
    total                    1.56 M

**Comment by llamatester** [comment]
The adapter at projects/limitless exports TVL: 
        
 
 
    base                      1.56 M
    
    total                    1.56 M

**Comment by llamatester** [comment]
The adapter at projects/limitless exports TVL: 
        
 
 
    base                      1.56 M
    
    total                    1.56 M

**Comment by jihyunsong42** [comment]
Hi, I have newly updated the TVL. This should be more accurate

**Comment by g1nt0ki** [comment]
hi @jihyunsong42 I am 100% sure if this is the right approach.

minor issue is, doesnt counting WETH 'tokenBalance'  instead of weth value in the contract which is tokens not yet borrowed lead to double counting


Other part is, my refactor does something similar to your code: https://github.com/DefiLlama/DefiLlama-Adapters/pull/10851 but getting different numbers, also, isnt using current tick to compute amount of tokens deposited or withdrawn leads to incorrect value?

**Pull request closed without merging**
