### PR TITLE
add xei

### PR DESCRIPTION
**Pull request by algtm**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

xei
##### Twitter Link:
https://x.com/XeiFinance

##### Website Link:

https://xei.finance/home
##### Logo (High resolution, will be shown with rounded borders):
https://xei.finance/logo.svg

##### Chain:

sei

##### Short Description (to be shown on DefiLlama):

Upgrade to the next level of decentralized trading on the Sei Network and experience the pulse of the market through XEI’s integration with dynamic meme communities, driving unprecedented trading excitement and opportunities. Launch with XEI Launchpad, where fairness meets innovation for explosive growth in crypto assets.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
dex

##### forkedFrom (Does your project originate from another project):
uniswapV3

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/xei: 
        
 
  
    
    
    Error: Llama RPC error! methos: undefined 
    - host: https://evm-rpc.sei-apis.com error: height is not available (requested height: 78353999, base height: 78893999)
    - host: https://evm-rpc.sei-apis.com/ error: height is not available (requested height: 78353999, base height: 78893999)

**Comment by algtm** [comment]
seems we need archive sei node

**Comment by g1nt0ki** [comment]
hi @algtm yeah, we have been talking to sei team regarding this, in the meantime, do you maintain a graph endpoint, we can rely on that for now.

**Comment by algtm** [comment]
@g1nt0ki I tried to change the block to the nearest block (83978356), still get the same error height is not available (requested height: 78353999, base height: 78896999)

**Pull request closed without merging**
