### PR TITLE
Add TVL adapter for Lido's bLuna

### PR DESCRIPTION
**Pull request by vshvsh**
##### Twitter Link:

www.twitter.com/lidofinance

##### List of audit links if any: 

https://github.com/lidofinance/audits

##### Website Link: 

www.lido.fi

##### Contact Email: 

info@lido.fi

##### Current TVL: 

$765.6m 

##### Chain: 

Ethereum, Terra

##### Coingecko ID (so your TVL can appear on Coingecko): 

lido-dao

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): 

8000

##### Description/bio (to be shown on DefiLlama): 

Stake your ETH with Lido and receive liquid stETH with daily rewards.

##### Token address and ticker if any: 

* LDO;  https://etherscan.io/token/0x5a98fcbea516cf06857215779fd812ca3bef1b32
* stETH; https://etherscan.io/token/0xae7ab96520de3a18e5e111b5eaab095312d7fe84 
* bLUNA; https://finder.terra.money/columbus-4/address/terra1kc87mu460fwkqte29rquh4hc20m54fxwtsx7gp

##### Category (Yield/Dexes/Lending/Minting): 

Yield, Staking

### CODE REVIEW

**Comment by 0xngmi** [comment]
Thanks for the PR! Do you know if there's a way to get bLUNA's TVL at a previous point in time?

**Comment by vshvsh** [comment]
You can do archive requests for the same data (just add `&height=2317393` to a request)  - but we didn't set up a public archive Terra node yet

Can have it in a few days, is it a blocker?

**Comment by 0xngmi** [comment]
Not a blocker but it'd be nice. If it works for you I can merge the PR now and, when the archive node is ready, I'll modify the adapter to also retrieve historical values.

**Comment by 0xngmi** [comment]
If this is a matter of getting an archive node (thus not specific to LIDO), do you know if there's any providers from which we could buy one?

**Comment by vshvsh** [comment]
Don't know any! I think there will be, but for now we'll maintain our own

**Comment by 0xngmi** [comment]
Got it. I've just merged the adapters and pushed the new versions to the server. Can you ping me when you have the archive node available?

**Comment by 0xngmi** [comment]
I've gone ahead and implemented some code to fetch historical values and report the currencies separately. We'll use this to fill the chart and show how the TVL composition evolves over time.

**Comment by vshvsh** [comment]
Just synced an archive node yesterday - do you still need it?

**Comment by vshvsh** [comment]
Oh terra actually made their endpoint an archive node? That code would have worked in April.

**Comment by vshvsh** [comment]
(it took almost a month to sync the archive terra node properly)

**Comment by 0xngmi** [comment]
I'm not sure, I thought so since it seems to respond fine when adding the height parameter but I'm getting some ` 'not found: contract terra1mtwph2juhj0rvjz7dy92gvl6xvukaxu8rfv8ts'` errors that shouldn't be there

**Comment by 0xngmi** [comment]
So it may not be an archive node, running some more tests now

**Comment by vshvsh** [comment]
That contract didn't exist before middle of march - is that consistent with your errors? Also can look at height, this might be a sparsely pruned node with only data available at every X block (typically every 100 by default in that mode)

**Comment by 0xngmi** [comment]
Yep, it seems to be the case, when you query it at height `2792839` (1st of may) it returns an error:
https://lcd.terra.dev/wasm/contracts/terra1mtwph2juhj0rvjz7dy92gvl6xvukaxu8rfv8ts/store?query_msg=%7B%22state%22%3A%20%7B%7D%7D&height=2792839

**Comment by 0xngmi** [comment]
> Also can look at height, this might be a sparsely pruned node with only data available at every X block (typically every 100 by default in that mode)

Will run some tests with other heights, that may be the case

**Comment by vshvsh** [comment]
https://lcd.terra.dev/wasm/contracts/terra1mtwph2juhj0rvjz7dy92gvl6xvukaxu8rfv8ts/store?query_msg=%7B%22state%22%3A%20%7B%7D%7D&height=2792800 works
it's a semi-pruned node, historical queries only work at every 100th block.

**Comment by vshvsh** [comment]
we can get you a proper archive node now, but it'll be less reliable than official endpoint

**Comment by 0xngmi** [comment]
Do you know what's the average blocktime? (to measure precision loss)

**Comment by 0xngmi** [comment]
> (it took almost a month to sync the archive terra node properly)

F

**Comment by 0xngmi** [comment]
> we can get you a proper archive node now, but it'll be less reliable than official endpoint

It seems like 100 blocks of difference only results in an average precision loss of 5 minutes so using the official node will be just fine, that way we also don't impose on you.

Also, thanks for chiming in. Letting me know about pruned nodes just saved me several hours of work :clinking_glasses:

**Comment by 0xngmi** [comment]
Historical data is now available on defillama along with the token breakdown:
image

**Pull request merged**
