### PR TITLE
Chain Expansion: Polygon chain added to the DeFi and DEX sections of MetaTdex project

### PR DESCRIPTION
**Pull request by phpwufeng**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
MetaTdex

##### Twitter Link:
https://twitter.com/MetaTdex

##### Website Link:
https://www.metatdex.com/

##### Chain:
BSC、HECO、POLYGON

##### Token address and ticker if any:
0x445cC9518cF7bc7386A2e3aaF510650b0FB05f5F（BSC）
0x86040C76AAE5CBB322364CAF8820b0E8902e97E5（HECO）
0x17a011150e9feb7bec4cfada055c8df436eb730b（POLYGON）

##### Category (full list at https://defillama.com/categories) *Please choose only one:
DEX

### CODE REVIEW

**Comment by dtmkeng** [comment]
Hi @phpwufeng  thank you for PR, if you need to update the volume adapter you should open pr on this repo https://github.com/DefiLlama/dimension-adapters
sorry I make you confuse

**Comment by phpwufeng** [comment]
> Hi @phpwufeng thank you for PR, if you need to update the volume adapter you should open pr on this repo https://github.com/DefiLlama/dimension-adapters sorry I make you confuse
Hello, @dtmkeng ,is there a detailed instruction document on how to  adding a new Chain Expansion?

**Comment by dtmkeng** [comment]
> 

https://docs.llama.fi/list-your-project/other-dashboards/listing-your-project

**Comment by phpwufeng** [comment]
> > 
> 
> https://docs.llama.fi/list-your-project/other-dashboards/listing-your-project

ok,thank you

**Comment by phpwufeng** [comment]
@dtmkeng Hello ，The codes have been merged, what else do I need to do? https://github.com/DefiLlama/dimension-adapters/pull/218

**Comment by phpwufeng** [comment]
Hello ，@dtmkeng， I have removed the changes to the file "volumes/adapters/metatdex/index.ts" .  The dex page has seen the polygon data, why the home page still can not see

**Comment by phpwufeng** [comment]
> 

Hello ，@dtmkeng， I have removed the changes to the file "volumes/adapters/metatdex/index.ts" . The dex page has seen the polygon data, why the home page still can not see ？

**Comment by phpwufeng** [comment]
@g1nt0ki @dtmkeng  hello，How to show out polygon chain data on the home page ？

**Comment by dtmkeng** [comment]
> @g1nt0ki @dtmkeng hello，How to show out polygon chain data on the home page ？

image

**Comment by phpwufeng** [comment]
@dtmkeng，How to show out polygon chain data on this page （https://defillama.com/chain/Polygon）？

**Comment by phpwufeng** [comment]
> > @g1nt0ki @dtmkeng hello，How to show out polygon chain data on the home page ？
> 
> image
@dtmkeng，How to show out polygon chain data on this page（[https://defillama.com/chain/Polygon]） ？

**Comment by phpwufeng** [comment]
> > @g1nt0ki @dtmkeng hello，How to show out polygon chain data on the home page ？
> 
> image
https://defillama.com/chain/Polygon
image
https://defillama.com
image

**Comment by dtmkeng** [comment]
@phpwufeng  solve conflicts and wait review tvl adapter

**Pull request closed without merging**
