### PR TITLE
add LiquiX

### PR DESCRIPTION
**Pull request by danetteceola**
twitter Link: https://twitter.com/liqui_x

List of audit links if any: https://github.com/LiquiX-Finance/Private-Pool-Vault/blob/main/SlowMist%20Audit%20Report%20-%20LiquiX.pdf

Website Link: https://liquix.finance

Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):https://github.com/LiquiX-Finance/Private-Pool-Vault/tree/main/LiquiX%20Logo%20Pack

Current TVL: $5.98m

Chain: Arbitrum, Optimism, Blast,Polygon

Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list): No Coingecko ID yet

Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000): No Coinmarketcap ID yet

Short Description (to be shown on DefiLlama): A protocol built as one-station LP infrastructure solution.LiquiX offers non-custodial,highly efficient and secure LP service to users via automated execution of algorithm strategies on various dapps and chains aggregated by the protocol.

Token address and ticker if any: Not Issued yet

Category (full list at https://defillama.com/categories) *Please choose only one: Liquidity manager

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):chainlink

forkedFrom (Does your project originate from another project):No

methodology (what is being counted as tvl, how is tvl being calculated):The funds deposited into the vault and those already invested in LP will be counted as the tvl of the protocol.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/liquix exports TVL: 
        
 
 
    arbitrum                  5.90 M
    
    total                    5.90 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
hi, can you refactor the code to compute tvl on chain?

**Comment by danetteceola** [comment]
> hi, can you refactor the code to compute tvl on chain?

hi, I'v tried to create subgraph but can't find a way to submit to hosted service, is there any sdk to call subgraph with apikey?

**Comment by g1nt0ki** [comment]
> > hi, can you refactor the code to compute tvl on chain?
> 
> hi, I'v tried to create subgraph but can't find a way to submit to hosted service, is there any sdk to call subgraph with apikey?

no, meant calling rpc endpoints and computing tvl, if you share the contract addresses and abi, I can give it a shot

**Pull request closed without merging**
