### PR TITLE
add new pools on mainnet and zklink

### PR DESCRIPTION
**Pull request by 0xKMG**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/airpuff exports TVL: 
        
 
 
    ethereum                  17.55 M
    arbitrum                  11.23 M
    mode                      1.74 M
    
    total                    30.52 M

**Comment by llamatester** [comment]
The adapter at projects/airpuff exports TVL: 
        
 
 
    ethereum                  17.35 M
    arbitrum                  11.12 M
    mode                      1.74 M
    zklink                    0
    
    total                    30.21 M

**Comment by g1nt0ki** [comment]
@0xKMG thanks for the PR, I have moved APUFF token to staking, and added code to price missing LSD tokens on server, so code here check only balance in the vault, it will take 2-3 hours to reflect.

**Comment by llamatester** [comment]
The adapter at projects/airpuff exports TVL: 
        
 
 
    ethereum                  15.61 M
    arbitrum                  10.95 M
    mode                      1.72 M
    zklink                    33
    ethereum-staking          10
    staking                   10
    
    total                    28.28 M

**Comment by 0xKMG** [comment]
hi @g1nt0ki, I have checked that 0x6733F0283711F225A447e759D859a70b0c0Fd2bC Vector token price is still missing?

**Pull request merged**
