### PR TITLE
Add TVL and Treasury of Wand Protocol's new $USDB Stable Vault

### PR DESCRIPTION
**Pull request by wandbuild**
##### Name (to be shown on DefiLlama):
Wand Protocol

##### Twitter Link:
https://twitter.com/WandProtocol

##### Website Link:
https://wand.fi

##### Logo (High resolution, will be shown with rounded borders):
https://twitter.com/WandProtocol/photo

##### Current TVL:
--- blast ---
ETH                       125.82 k
USDB                      119.47044
Total: 125.94 k

--- tvl ---
ETH                       125.82 k
USDB                      119
Total: 125.94 k

------ TVL ------
blast                     125.94 k

total                    125.94 k

##### Treasury Addresses (if the protocol has treasury)
0x462bd2d3c020f6986c98160bc4e189954f49634b

##### Chain:
Blast

##### Short Description (to be shown on DefiLlama):
Wand protocol offers stablecoins for low-risk stability and margin tokens for higher volatility, catering to diverse investment strategies through standardized, pooled assets.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
CDP

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Redstone

##### Implementation Details: Briefly describe how the oracle is integrated into your project:
We are using Redstone's classic model price feed for $ETH and $USDB in chainlink-compatible manner.

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
https://docs.redstone.finance/docs/smart-contract-devs/price-feeds

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/wandfi/wand-contract-blast

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/treasury/wand.js exports TVL: 
        
 
 
    blast                     13.676903472803513
    
    total                    13.676903472803513

**Comment by llamatester** [comment]
The adapter at projects/wand exports TVL: 
        
 
 
    blast                     126.02 k
    
    total                    126.02 k

**Comment by wandbuild** [comment]
Wand Protocol just opened a new stable vault for $USDB on blast mainnet. This PR udpates TVL and treasury adapters for that.

**Please also help update Wand Protocol's category from lending to CDP**, thanks for that.

**Comment by g1nt0ki** [comment]
@wandbuild thanks for the PR

**Pull request merged**
