### PR TITLE
add y2k finance

### PR DESCRIPTION
**Pull request by y2bdeveloper**
**NOTE**

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by g1nt0ki** [comment]
I am bit confused by this PR as it is already listed, can you explain?

**Comment by y2bdeveloper** [comment]
We fork from Y2K Finance. Please check the information below. 
Name : Y2B Finance 
Twitter Link: https://twitter.com/Y2BFinance
List of audit links if any:  https://github.com/solidproof/projects/tree/main/Y2B
Website Link: https://y2b.finance/
Logo: https://drive.google.com/file/d/1ik7Vr8c9B5FgFoKAxBK-xheJstHB9Ho6/view 
Current TVL: 102025
Chain: Ethereum
Coingecko ID (so your TVL can appear on Coingecko): y2b
Coinmarketcap ID (so your TVL can appear on Coinmarketcap): 23133
Short Description (to be shown on DefiLlama): Y2B is a crypto-native take on structured products on-chain, the protocol provides exotic peg markets which allow users to hedge, leverage, speculate and trade the different components of pegged assets. The protocol launches with 2 different products Typhoon, a 1155 vault allowing users to take risk or hedge against a potential peg deviation, and Volcano, a liquidation wrapper and aggregator that redefines how collateral auctions for bad debt are conducted.
Token address and ticker if any: 0xF9C12B27cE5058ab98ce11BD53900f84E18C0650
Category (full list at https://defillama.com/categories) : Derivatives
Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
forkedFrom (Does your project originate from another project): Y2K Finance (https://www.y2k.finance/)
methodology (what is being counted as tvl, how is tvl being calculated):

**Comment by llamatester** [comment]
The adapter at projects/y2b-finance exports TVL: 
        
 
 
    ethereum-staking          0
    ethereum                  0
    staking                   0
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/y2b-finance exports TVL: 
        
 
 
    ethereum                  102.03 k
    
    total                    102.03 k

**Pull request merged**
