### PR TITLE
add hydro-protocol

### PR DESCRIPTION
**Pull request by hydro-developer**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):  
Hydro Protocol

##### Twitter Link:  
https://hydroprotocol.finance/twitter

##### List of audit links if any:  
https://hydroprotocol.finance/files/audit_scv.pdf

##### Website Link:  
https://app.hydroprotocol.finance

##### Logo (High resolution, will be shown with rounded borders):
PNG : https://cloudflare-ipfs.com/ipfs/QmXFAAzdsJwrXHMePerDRk6kTpJqhhAYU99zA1jWQ6ojiR
SVG : https://cloudflare-ipfs.com/ipfs/QmWQ6yAkuU3ZdkTzJVtvmQCMMn9ZLhB8RfA7FJCo6jStY1

##### Current TVL:  
21M USD

##### Treasury Addresses (if the protocol has treasury) :  
N/A

##### Chain:  
injective

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)  
N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)  
N/A

##### Short Description (to be shown on DefiLlama): 
Ultimate LSD & LSDFi Infrastructure Platform on Injective

##### Token address and ticker if any:  
inj18luqttqyckgpddndh8hvaq25d5nfwjc78m56lc

##### Category (full list at https://defillama.com/categories) *Please choose only one:  
Liquid Staking

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):  
N/A

##### forkedFrom (Does your project originate from another project):  
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
Staked INJ Value + Locked hINJ + Locked INJ + Locked Hydro

##### Github org/user (Optional, if your code is open source, we can track activity):  
N/A

### CODE REVIEW

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
why are there two listings? 
is the project live and has some tvl? we cant list projects with 0 tvl
Can you please refactor the adapter to be on chain? https://github.com/DefiLlama/DefiLlama-Adapters/discussions/432

**Comment by hydro-developer** [comment]
We are going to launch Hydro project 13:00 (UTC) today.
Then I can give you actual TVL.

Hydro protocol has two tokens. hINJ and Hydro. That's why there are two listing.
Should we remain only one listing?

**Comment by hydro-developer** [comment]
Hydro protocol launched. I updated TVL, please check it.

**Comment by llamatester** [comment]
The adapter at projects/hydro-protocol exports TVL: 
        
 
 
    injective                 29.66 M
    
    total                    29.66 M

**Comment by g1nt0ki** [comment]
@hydro-developer I refactored the adapter a bit, we list based on projects not tokens, so one adapter/listing is enough here. One thing I am 100% sure is, when user autocompounds, the token INJ in those contracts still end up minting hINJ? 

it so, I think autocompound tvl should be skipped since we are already counting hINJ supply as tvl

**Comment by g1nt0ki** [comment]
staked hINJ tvl wont be counted as tvl, as INJ backing those tokens are already included in tvl.

**Pull request merged**
