### PR TITLE
Added Nucleon 

### PR DESCRIPTION
**Pull request by 0xn1c0**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
"id":"nucleon-space"

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
"id":23581

##### Short Description (to be shown on DefiLlama):
Nucleon is a liquid staking solution for Conflux PoS. Nucleon enables users to stake CFX without the overhead of illiquid assets. Users can enjoy liquidity while remaining secure, earning interest, and accessing the broader DeFi ecosystem.
Nucleon's goal is to solve the problems associated with Conflux PoS staking - liquidity, immovability, and accessibility - by making staked CFX liquid. Nucleon aims to open PoS participation with flexible amounts of CFX to improve the security of the Conflux Network.

##### Token address and ticker if any:
Token Address: 0xfe197e7968807b311d476915db585831b43a7e3b
Token Ticker: "NUT"

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL accounts for total amount of CFX Staked on the protocol + the value of All LP Tokens staked on the Masterchef or Pools.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/nucleon exports TVL: 
        
 
 
    conflux                   11.94 M
    
    total                    11.94 M

**Comment by llamatester** [comment]
The adapter at projects/nucleon exports TVL: 
        
 
 
    conflux                   3.24 M
    
    total                    3.24 M

**Comment by llamatester** [comment]
The adapter at projects/nucleon exports TVL: 
        
 
 
    conflux-pool2             171.77 k
    conflux-staking           5.41 M
    conflux                   8.62 M
    pool2                     171.77 k
    staking                   5.41 M
    
    total                    8.62 M

**Comment by llamatester** [comment]
The adapter at projects/nucleon exports TVL: 
        
 
 
    conflux-staking           0
    conflux                   3.49 M
    conflux-pool2             6.55 M
    staking                   0
    pool2                     6.55 M
    
    total                    3.49 M

**Comment by llamatester** [comment]
The adapter at projects/nucleon exports TVL: 
        
 
 
    conflux                   3.54 M
    conflux-pool2             6.58 M
    pool2                     6.58 M
    
    total                    3.54 M

**Comment by g1nt0ki** [comment]
@0xn1c0 thanks for the PR, we dont consider LPs in masterchef as part of tvl hence removed it

**Pull request merged**
