### PR TITLE
[test draft] +ABCDeFx/index.js

### PR DESCRIPTION
**Pull request by ftm1337**
this is a test. please dont merge

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/ABCDeFx exports TVL: 
        
 
 
    xdai                      2.25516872278
    echelon                   623.7420623400001
    
    total                    625.9972310627801

**Comment by llamatester** [comment]
The adapter at projects/VAX exports TVL: 
        
 
 
    multivac                  15.99 k
    
    total                    15.99 k

**Comment by llamatester** [comment]
The adapter at projects/ABCDeFx exports TVL: 
        
 
 
    xdai                      2.2563721442224
    echelon                   623.7420623400001
    
    total                    625.9984344842225

**Comment by llamatester** [comment]
The adapter at projects/VAX exports TVL: 
        
 
 
    multivac                  15.99 k
    
    total                    15.99 k

**Comment by llamatester** [comment]
The adapter at projects/ABCDeFx exports TVL: 
        
 
 
    xdai                      2.2563721442224
    echelon                   623.7420623400001
    
    total                    625.9984344842225

**Comment by ftm1337** [comment]
TVL for VAX (uniswap-like dex) shows up as 15.99K.
But at the official tracker (https://scan.mtv.guru/apr), there is about 6m MTV ($4800) + 5500 usdc in counter assets, so the TVL should be about 21000 :thinking:

**Comment by llamatester** [comment]
The adapter at projects/VAX exports TVL: 
        
 
 
    multivac                  16.04 k
    
    total                    16.04 k

**Comment by llamatester** [comment]
The adapter at projects/VAX exports TVL: 
        
 
 
    multivac                  16.04 k
    
    total                    16.04 k

**Comment by llamatester** [comment]
The adapter at projects/ABCDeFx exports TVL: 
        
 
 
    xdai                      2.2565511843240005
    echelon                   623.7420623400001
    
    total                    625.9986135243241

**Comment by llamatester** [comment]
The adapter at projects/ABCDeFx exports TVL: 
        
 
 
    xdai                      2.2565511843240005
    echelon                   623.7420623400001
    
    total                    625.9986135243241

**Pull request closed without merging**
