### PR TITLE
TVL no longer 0

### PR DESCRIPTION
**Pull request by gaspare100**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/scrubKava: 
        
 
  
    
    
    Error: 
        Please move the following keys into the chain: tvl
    
        We have a new adapter export specification now where tvl and other chain specific information are moved inside chain export.
        For example if your protocol is on ethereum and has tvl and pool2, the export file would look like:
        
            module.exports = {
              methodlogy: '...',
              ethereum: {
                tvl: 
                pool2:
              }
            }

**Comment by llamatester** [comment]
Error while running adapter at projects/scrubKava: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:224:11

**Comment by llamatester** [comment]
Error while running adapter at projects/scrubKava: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:224:11

**Comment by llamatester** [comment]
Error while running adapter at projects/scrubKava: 
        
 
  
    
    
    Error: 
        Please move the following keys into the chain: tvl
    
        We have a new adapter export specification now where tvl and other chain specific information are moved inside chain export.
        For example if your protocol is on ethereum and has tvl and pool2, the export file would look like:
        
            module.exports = {
              methodlogy: '...',
              ethereum: {
                tvl: 
                pool2:
              }
            }

**Comment by llamatester** [comment]
Error while running adapter at projects/scrubKava: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:224:11

**Comment by llamatester** [comment]
Error while running adapter at projects/scrubKava: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:224:11

**Comment by llamatester** [comment]
Error while running adapter at projects/scrubKava: 
        
 
  
    
    
    Error: invalid BigNumber string (argument="value", value="NaN", code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    Truncated error stack:
        at Function.BigNumber.from (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/bignumber/lib/bignumber.js:199:27)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:335:16
        at Array.forEach (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:329:28)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:342:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:61:30)

**Comment by llamatester** [comment]
Error while running adapter at projects/scrubKava: 
        
 
  
    
    
    TypeError: tomb.kava.staking(...).add is not a function
    Truncated error stack:
    
        at tomb.kava.tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/scrubKava/index.js:26:62)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:60:25)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:167:9
        at async Promise.all (index 0)
        at async Promise.all (index 0)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:212:3

**Comment by llamatester** [comment]
Error while running adapter at projects/scrubKava: 
        
 
  
    
    
    Error: invalid BigNumber string (argument="value", value="NaN", code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    Truncated error stack:
        at Function.BigNumber.from (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/bignumber/lib/bignumber.js:199:27)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:335:16
        at Array.forEach (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:329:28)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:342:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:61:30)

**Comment by llamatester** [comment]
Error while running adapter at projects/scrubKava: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:224:11

**Comment by llamatester** [comment]
Error while running adapter at projects/scrubKava: 
        
 
  
    
    
    Error: invalid BigNumber string (argument="value", value="NaN", code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    Truncated error stack:
        at Function.BigNumber.from (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/bignumber/lib/bignumber.js:199:27)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:335:16
        at Array.forEach (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:329:28)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:342:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:61:30)

**Comment by g1nt0ki** [comment]
@gaspare100 not sure what you are trying to achieve here, we already have a toggle that lets users include staking/pool2 as tvl if they want, with this change, it would be doublecounted

**Comment by llamatester** [comment]
Error while running adapter at projects/scrubKava: 
        
 
  
    
    
    ReferenceError: farmsBalace is not defined
    Truncated error stack:
    
        at tomb.kava.tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/scrubKava/index.js:28:1)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:60:25)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:167:9
        at async Promise.all (index 0)
        at async Promise.all (index 0)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:212:3

**Comment by llamatester** [comment]
Error while running adapter at projects/scrubKava: 
        
 
  
    
    
    ReferenceError: pool2 is not defined
    Truncated error stack:
    
        at tomb.kava.tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/scrubKava/index.js:29:21)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:60:25)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:167:9
        at async Promise.all (index 0)
        at async Promise.all (index 0)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:212:3

**Comment by llamatester** [comment]
The adapter at projects/scrubKava exports TVL: 
        
 
 
    kava-staking              114.17 k
    kava-pool2                259.14 k
    kava                      373.31 k
    staking                   114.17 k
    pool2                     259.14 k
    
    total                    373.31 k

**Comment by gaspare100** [comment]
Making sure TVL is reported correctly for Kava, especially because these farms are all provided by us and should be counted as our TVL and not other protocols as we provide all liqudity and rewards.

**Comment by g1nt0ki** [comment]
Sorry, I am still going to close this story since we apply the exact same rule for other tomb forks or other protocols with pool2/staking. If we change yours, we need to change for others as well. Like I said, users can still choose to toggle pool2/staking and it will show up as tvl of your protocol

**Pull request closed without merging**
