### PR TITLE
Track TVL of Increment Protocol

### PR DESCRIPTION
**Pull request by omurovec**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Increment Protocol

##### Twitter Link:
https://x.com/IncrementHQ

##### List of audit links if any:
https://docs.increment.finance/increment/protocol/audits

##### Website Link:
https://increment.finance/

##### Logo (High resolution, will be shown with rounded borders):
!Logomark dark bg

##### Current TVL:
$59.43k

##### Treasury Addresses (if the protocol has treasury)
https://etherscan.io/address/0xcce2065c1DC423451530BF7B493243234Ba1E849

##### Chain:
zkSync Era

##### Short Description (to be shown on DefiLlama):
Increment is a decentralized AMM perpetual swaps protocol on zkSync Era, featuring automatically concentrated liquidity, dynamic fees and parametrizable pools.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Derivatives

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Chainlink
##### Implementation Details: Briefly describe how the oracle is integrated into your project:
Used for pricing collateral assets and index prices for markets.
##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
see "oracles": https://docs.increment.finance/increment/protocol/user-guide/risk-factors#dependencies
for collateral values: https://github.com/Increment-Finance/increment-protocol/blob/main/contracts/Oracle.sol
for index prices: https://github.com/Increment-Finance/increment-protocol/blob/36d6052c9c9996b3e4f148dc05ee7a654e2fbe4d/contracts/tokens/VBase.sol#L70-L86

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is calculated as a total of all deposits into the vault contract which are used as collateral for opening trades or providing liquidity. 1 USDC is assumed to be 1 USD. Chainlink feeds are used for all other collateral assets.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/Increment-Finance

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/increment-protocol: 
        
 
  
    
    
    TypeError: Cannot create property 'coingecko:0' on string '59462629106074395411874'
    Truncated error stack:
        at Object.sumSingleBalance (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:108:25)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:307:16
        at Array.forEach (<anonymous>)
        at fixBalances (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:301:28)
        at computeTVL (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:314:3)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:51:30)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:138:9
        at async Promise.all (index 0)
        at async Promise.all (index 3)

**Comment by llamatester** [comment]
The adapter at projects/increment-protocol exports TVL: 
        
 
 
    era                       59392760.52 B
    
    total                    59392760.52 B

**Comment by llamatester** [comment]
The adapter at projects/increment-protocol exports TVL: 
        
 
 
    era                       59.39 k
    
    total                    59.39 k

**Comment by omurovec** [comment]
Seems like the CI is failing due to the earnmos project, all other tests passing

**Comment by g1nt0ki** [comment]
@omurovec thanks for the PR, refactored and merged here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/9578

**Pull request closed without merging**
