### PR TITLE
Add adapter for Dawn Star Finance

### PR DESCRIPTION
**Pull request by CaVang**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/dawn-star-finance exports TVL: 
        
 
 
    polygon                   334.39 k
    polygon-staking           2.49 k
    polygon-pool2             8.60 M
    staking                   2.49 k
    pool2                     8.60 M
    
    total                    334.39 k

**Comment by llamatester** [comment]
The adapter at projects/dawn-star-finance exports TVL: 
        
 
 
    polygon                   0
    polygon-staking           27.46 k
    polygon-pool2             8.39 M
    staking                   27.46 k
    pool2                     8.39 M
    
    total                    0

**Comment by g1nt0ki** [comment]
@CaVang I notice that you are counting genesis pool towards tvl but all the tokens there are from your team right? I have removed it as part of the refactoring, if you are fine with the change I will merge and list.

**Comment by CaVang** [comment]
hello @g1nt0ki ,

Thanks for your help to refactor our code, I think it can ready to go.
About your question `I notice that you are counting genesis pool towards tvl but all the tokens there are from your team right?`

**Comment by g1nt0ki** [comment]
> hello @g1nt0ki ,
> 
> Thanks for your help to refactor our code, I think it can ready to go.
> 
> About your question `I notice that you are counting genesis pool towards tvl but all the tokens there are from your team right?` The genesis pool doesn't come from the team, it comes from users who stake to earn emissions. Its 100% community owned.

meant MMO token  is part of the same group :)

**Pull request merged**
