### PR TITLE
Add Pools v2 to DeFiLlama TVL

### PR DESCRIPTION
**Pull request by CalabashSquash**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
**This is an edit of the already-existing Tracer DAO TVL calculation on DeFiLlama**
---

### Justification/Reasons/Details

A couple of months ago, Tracer launched Perpetual Pools V2
- Details: https://www.tracer.finance/radar/v2-mechanism/
This update comes with the addition of a new factory. The current DeFiLlama TVL calculations only use the V1 factory.

This PR adds the calculation of the TVL (using the exact same methodology) for the V2 factory as well as the V1 factory.

- [x] Run `node test.js projects/tracerdao/index.js` successfully, with correct output.

Please let me know if there are any questions :)

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/tracerdao exports TVL: 
        
 
 
    arbitrum                  3.72 M
    
    total                    3.72 M

**Comment by waynebruce0x** [comment]
Can you wrap the V2 section in an if block, with a block height condition? So we can backfill until the block height where the new factory was deployed?

**Comment by CalabashSquash** [comment]
Yep, will do this tomorrow

**Comment by llamatester** [comment]
The adapter at projects/tracerdao exports TVL: 
        
 
 
    arbitrum                  3.93 M
    
    total                    3.93 M

**Pull request merged**
