### PR TITLE
Added waxdao project

### PR DESCRIPTION
**Pull request by mdcryptonfts**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

WaxDAO

##### Twitter Link:

https://twitter.com/waxdao_io

##### Website Link:

https://waxdao.io

##### Logo (High resolution, will be shown with rounded borders):

https://logos.waxdao.io/waxdao_token.waxdao.png

##### Current TVL:

$30k

##### Chain:

WAX

##### Short Description (to be shown on DefiLlama):

WaxDAO is a no-code platform on WAX Blockchain that allows project owners to create their own tokens, staking farms, DAOs, and more - without needing to learn how to code.

##### Token address and ticker if any:

Address: token.waxdao
Ticker: WAXDAO

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Services

##### methodology (what is being counted as tvl, how is tvl being calculated):

TVL includes funds deposited to NFT market contracts, DAO treasuries, staking-as-a-service contracts, escrow/vesting contracts, and synthetic token contracts.

##### Github org/user (Optional, if your code is open source, we can track activity):

https://github.com/mdcryptonfts

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/waxdao exports TVL: 
        
 
 
    wax                       30.35 k
    
    total                    30.35 k

**Comment by mdcryptonfts** [comment]
Note: There are a couple of staking contracts in the adapter, however the staking farms are not created by us. They are contracts that allow other projects to create their own staking systems for NFTs and for tokens.

The majority of funds in those contracts are rewards that have been deposited by project creators, to reward people who stake their NFTs and their tokens.

I wasn't sure if this TVL should be hidden by default or not, since it is unrelated to our native token. If you think it needs to be changed, just let me know. Thanks.

**Comment by llamatester** [comment]
The adapter at projects/waxdao exports TVL: 
        
 
 
    wax-staking               27.72 k
    staking                   27.72 k
    wax                       2.63 k
    
    total                    2.63 k

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
for a locker protocol, we can count only the locked LP as tvl, and some contracts are for dao funds? we can count these under treasury but not as tvl since they are meant only for user funds

**Comment by g1nt0ki** [comment]
> Note: There are a couple of staking contracts in the adapter, however the staking farms are not created by us. They are contracts that allow other projects to create their own staking systems for NFTs and for tokens.
> 
> The majority of funds in those contracts are rewards that have been deposited by project creators, to reward people who stake their NFTs and their tokens.
> 
> I wasn't sure if this TVL should be hidden by default or not, since it is unrelated to our native token. If you think it needs to be changed, just let me know. Thanks.

missed this comment, in cases like this, we count the token value under staking

**Comment by mdcryptonfts** [comment]
> > Note: There are a couple of staking contracts in the adapter, however the staking farms are not created by us. They are contracts that allow other projects to create their own staking systems for NFTs and for tokens.
> > The majority of funds in those contracts are rewards that have been deposited by project creators, to reward people who stake their NFTs and their tokens.
> > I wasn't sure if this TVL should be hidden by default or not, since it is unrelated to our native token. If you think it needs to be changed, just let me know. Thanks.
> 
> missed this comment, in cases like this, we count the token value under staking

I moved the farming contracts under staking. The locker (waxdaolocker) is still under TVL, which sounds like what you want.

The only one I'm unsure about is `dao.waxdao`, which is a contract that allows project owners to create their own DAO/treasury. I can't find exactly how I am supposed to modify the adapter to specify that it's a treasury. I can just remove that contract if it makes it easier.

**Comment by g1nt0ki** [comment]
" I can just remove that contract if it makes it easier." yeah, can you remove that? 

we track treasury adapters here: https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/projects/treasury

it is no longer part of tvl adapter file

**Comment by llamatester** [comment]
The adapter at projects/waxdao exports TVL: 
        
 
 
    wax-staking               24.42 k
    staking                   24.42 k
    wax                       1.53 k
    
    total                    1.53 k

**Comment by mdcryptonfts** [comment]
> " I can just remove that contract if it makes it easier." yeah, can you remove that?
> 
> we track treasury adapters here: https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/projects/treasury
> 
> it is no longer part of tvl adapter file

Treasury contract has been removed.

**Pull request merged**
