### PR TITLE
Update adapter for IPOR Protocol V2

### PR DESCRIPTION
**Pull request by amydlarz**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
IPOR Protocol

##### Twitter Link:
https://twitter.com/ipor_io

##### List of audit links if any:
https://docs.ipor.io/audits

##### Website Link:
https://ipor.io/

##### Current TVL:
image

##### Treasury Addresses (if the protocol has treasury)
  "AmmTreasuryDai": "0xEd7d74AA7eB1f12F83dA36DFaC1de2257b4e7523",
  "AmmTreasuryEth": "0x63395EDAF74a80aa1155dB7Cd9BBA976a88DeE4E",
  "AmmTreasuryUsdc": "0x137000352B4ed784e8fa8815d225c713AB2e7Dc9",
  "AmmTreasuryUsdt": "0x28BC58e600eF718B9E97d294098abecb8c96b687",

##### Chain:
ethereum mainnet

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/ipor exports TVL: 
        
 
 
    ethereum                  13.04 M
    
    total                    13.04 M

**Comment by llamatester** [comment]
The adapter at projects/ipor exports TVL: 
        
 
 
    ethereum                  13.04 M
    
    total                    13.04 M

**Comment by g1nt0ki** [comment]
hi @amydlarz can you leave the existing code as it is and add a new listing/folder for ipor V2? and we will create sub listing like what we have for aave: https://defillama.com/protocol/aave

**Comment by amydlarz** [comment]
> hi @amydlarz can you leave the existing code as it is and add a new listing/folder for ipor V2? and we will create sub listing like what we have for aave: https://defillama.com/protocol/aave

Hi @g1nt0ki, it's not a new version like Aave. The Treasury contracts remain the same. We've only added StEthTreasury and modified how we access balances through the router.

**Comment by g1nt0ki** [comment]
thanks, I have merged your changes with refactor here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/7696

**Pull request closed without merging**
