### PR TITLE
feat: Ajira Pay Finance V2

### PR DESCRIPTION
**Pull request by dickensodera**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/ajira-pay-finance-v2: 
        
 
  
    
    
    Error: Llama RPC error! methos: undefined 
    - host: https://rpc-mainnet.maticvigil.com error: execution reverted
    - host: https://polygon-rpc.com error: execution reverted
    - host: https://gateway.tenderly.co/public/polygon error: execution reverted
    - host: https://polygon-pokt.nodies.app error: execution reverted
    - host: https://1rpc.io/matic error: execution reverted
    - host: https://polygon.blockpi.network/v1/rpc/public error: execution reverted
    - host: https://polygon-mainnet.public.blastapi.io error: execution reverted

**Comment by dickensodera** [comment]
Hello @0xngmi , greetings. how do we solve the rpc related issues?

**Comment by llamatester** [comment]
Error while running adapter at projects/ajira-pay-finance-v2: 
        
 
  
    
    
    Error: Llama RPC error! methos: undefined 
    - host: https://polygon-pokt.nodies.app error: execution reverted
    - host: https://polygon-rpc.com error: execution reverted
    - host: https://polygon.gateway.tenderly.co error: execution reverted
    - host: https://gateway.tenderly.co/public/polygon error: execution reverted
    - host: https://rpc.tornadoeth.cash/polygon error: execution reverted
    - host: https://polygon-mainnet.rpcfast.com?api_key=xbhWBI1Wkguk8SNMu1bvvLurPGLXmgwYeC4S6g2H7WdwFigZSmPWVZRxrskEQwIf error: execution reverted
    - host: https://polygon.rpc.blxrbdn.com error: execution reverted

**Comment by g1nt0ki** [comment]
@dickensodera maybe the smart contract address is wrong? 
image

**Comment by dickensodera** [comment]
> @dickensodera maybe the smart contract address is wrong? image

Hi let @g1nt0ki , let me check

**Comment by dickensodera** [comment]
> > @dickensodera maybe the smart contract address is wrong? image
> 
> Hi let @g1nt0ki , let me check

I've just counterchecked that it's the correct contract address @g1nt0ki

**Comment by g1nt0ki** [comment]
@dickensodera it is failing every rpc, so I doubt that it is an rpc issue

**Comment by dickensodera** [comment]
> @dickensodera it is failing every rpc, so I doubt that it is an rpc issue

Hello @g1nt0ki , made it a draft, I'll reactivate it once we have some data. It is a preparation for the v2 launch that's upcoming.

**Comment by llamatester** [comment]
The adapter at projects/ajira-pay-finance-v2 exports TVL: 
        
 
 
    linea-vesting             0
    linea                     275.97515998940173
    vesting                   0
    
    total                    275.97515998940173

**Comment by dickensodera** [comment]
> > @dickensodera it is failing every rpc, so I doubt that it is an rpc issue
> 
> Hello @g1nt0ki , made it a draft, I'll reactivate it once we have some data. It is a preparation for the v2 launch that's upcoming.

Hello @g1nt0ki , I've activated this, kindly assist where possible. Thank you.

**Comment by g1nt0ki** [comment]
thanks, I have refactored and merged it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/8971

next time you put up a PR, can you let the maintainers edit it?

**Comment by dickensodera** [comment]
> thanks, I have refactored and merged it here: #8971
> 
> next time you put up a PR, can you let the maintainers edit it?

Okay cool @g1nt0ki , thank you.

**Pull request closed without merging**
