### PR TITLE
Add Reef Chain data

### PR DESCRIPTION
**Pull request by dereksilva**
**Name (to be shown on DefiLlama):** 

Reef

**Twitter Link:** 

https://x.com/reef_chain

**List of audit links if any:** 

https://github.com/HalbornSecurity/PublicReports/blob/master/Substrate%20Audits/Reef_Chain_Substrate_Security_Audit_Report_Halborn_v1_1.pdf

**Website Link:** 

https://reef.io

**Logo (High resolution, will be shown with rounded borders):** 

https://github.com/sponsian/Reef-Branding/blob/main/ReefLogo.zip

**Current TVL:** 

N/A - will submit with DEX and DeFi protocol submissions

**Treasury Addresses (if the protocol has treasury):** 

N/A

**Chain:** 

Reef

**Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed):** 

reef

**Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed):** 

6951

**Short Description (to be shown on DefiLlama):** 

Reef Chain is a layer 1, Substrate-based chain with EVM that aims to be the easiest entry point for new blockchain users.

**Token address and ticker if any:** 

https://reefscan.com/contract/0x0000000000000000000000000000000001000000 || REEF

**Category:** 

Layer 1 blockchain

**Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):** 

Witnet

**Implementation Details:** Briefly describe how the oracle is integrated into your project: 

Witnet allows their oracles to be used on Reef Chain

**Documentation/Proof:** Provide links to documentation or any other resources that verify the oracle's usage:** 

https://docs.witnet.io/smart-contracts/witnet-data-feeds/addresses/reef-price-feeds

**forkedFrom (Does your project originate from another project):** 

N/A

**methodology (what is being counted as tvl, how is tvl being calculated):** 

N/A

**Github org/user (Optional, if your code is open source, we can track activity):** 

https://github.com/reef-chain

### CODE REVIEW

**Comment by dereksilva** [comment]
Hey @g1nt0ki, using GraphQL to pull data would be preferred, and it supports http. 

https://v2.archive.subsquid.io/network/reef

Could you try that instead?

**Comment by dereksilva** [comment]
I updated the pull request too.

**Comment by g1nt0ki** [comment]
sorry, no. we accept graph for fees/volume but prefer  on chain data for tvl

**Comment by dereksilva** [comment]
Okay. Unfortunately we're going to have to do some work to figure this out then. Thanks for letting me know!

**Comment by g1nt0ki** [comment]
> Okay. Unfortunately we're going to have to do some work to figure this out then. Thanks for letting me know!

@dereksilva we have helper functions, but you dont expose http rpcs ?

**Pull request closed without merging**
