### PR TITLE
Add Peaky Finance

### PR DESCRIPTION
**Pull request by blindersdev**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Peaky Finance

##### Twitter Link:
https://twitter.com/peakyfinance

##### List of audit links if any:
NA

##### Website Link:
https://peaky.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
peaky

##### Current TVL:
$99.98K

##### Chain:
BSC

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
NA

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
NA

##### Short Description (to be shown on DefiLlama):
Peaky Finance is a DAO that powers a suite of protocols to solve some of the common pain points of Decentralised Finance. 

##### Token address and ticker if any:
PLP: "0xa4BB3bD27fAf0461661316f1812C28410b1F4788"
fPLP: "0x8Ba044efdC04528138CbDC4176fe559a9960394A"
pBTC: "0xd2d99e9e2a26475d1b100f7a1fbd9da9fe1667ba"
pETH: "0xac7bdca1418f4e1a5716e2634f3894a5178072ef"
pBNB: "0x42a39376a058c743c4a9f2869fc4fcd3faea38f4"
pEUR: "0xdf957fe55417e94306711aef4dd1d2a51da4472c"
pJPY: "0x3f729351aa9e8f3925ae78026d527d8db65ec217"
pGBP: "0x8fbe6a9ddfacecb32a41746a9f7873497a749736"
pSGD: "0x05cf1377ec17dbeb6f61d62dd0af5ddf67bad00b"
pAUD: "0x5043dbdd3342f3cbefe594ac7fb30bad22a1dcfa"

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Derivatives

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### forkedFrom (Does your project originate from another project):
GMX

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is derived from:
1. The amount of BUSD deposited in the PLP and fPLP Vaults
2. The circulating supply of synthetic tokens using the following formula:
`Synthetic Tokens Circulating Supply = totalSupply - amountInVault - amountInDevWallet - ibTokenInDevWallet + ibTokenBorrowedByDevWallet - amountInMultisig - ibTokenInMultisig + ibTokenBorrowedByMultisig`

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/peaky-finance exports TVL: 
        
 
 
    bsc                       99.85 k
    
    total                    99.85 k

**Comment by Define101** [comment]
Hi guys notice that the website link is not working
Also, did you guys launch already?

**Comment by blindersdev** [comment]
> Hi guys notice that the website link is not working Also, did you guys launch already?

Apologies for the late reply, the website is up. We are currently doing our publicity and will be launching it in the next few days!

**Comment by Define101** [comment]
Hello blindersdev
Is this the governance token? 0xa4BB3bD27fAf0461661316f1812C28410b1F4788

**Pull request merged**
