### PR TITLE
Add MAMA to Defillama

### PR DESCRIPTION
**Pull request by ARYZEofficial**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
MAMA

##### Twitter Link:
https://twitter.com/ARYZEofficial

##### List of audit links if any:
https://3838260506-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FTmzl9GX7emUArB9s00Rz%2Fuploads%2FvK1ML7oM7IwFeeR3bHaF%2FARYZE%20-%20eEUR%2C%20eGBP%2C%20eUSD%20and%20RYZE%20Code%20Audit.pdf?alt=media&token=0e1f74c0-0278-42bb-a7cd-c22ea0bf7b5d

##### Website Link:
https://mama.io/

##### Logo (High resolution, will be shown with rounded borders):
https://raw.githubusercontent.com/ARYZEofficial/Token-Logos/904034ab82ee9d3cc4b8f66858287161bc3bcadb/MAMA_logo.svg

##### Current TVL:
$529.18k

##### Chain:
Polygon Chianid: 137

##### Short Description (to be shown on DefiLlama):
Digital Cash in MAMA are full-reserve stablecoins issued as eEUR, eGBP and eUSD, eSGD and more to come. All variants of Digital Cash are backed one-to-one with government-issued assets.

##### Token address and ticker if any:

eEUR:
https://polygonscan.com/token/0x735fa792e731a2e8f83f32eb539841b7b72e6d8f

eGBP:
https://polygonscan.com/token/0xd711d7d893de57dc13ff465763218770bd42db1d

eUSD:
https://polygonscan.com/token/0xa4335da338ec4c07c391fc1a9bf75f306adadc08

eSGD:
https://polygonscan.com/token/0x58a849e1f3c7044bb317db4611269c352c53d399

##### Category (full list at https://defillama.com/categories) *Please choose only one:
3. Dexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### methodology (what is being counted as tvl, how is tvl being calculated):
We Calculate TVL with sum of all Pools using subgraph

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/mama exports TVL: 
        
 
 
    polygon                   529.05 k
    
    total                    529.05 k

**Comment by ARYZEofficial** [comment]
Hi and thanks for the Swift response!

Could you please elaborate on why? We are s film reserve stablecoin issuer and we have respekted 3rd party auditer checking if this is correct monthly.

Please let check here:
https://www.aryze.io/backing-and-solvency

Here is our latest 2 audits:

October:
https://www.aryze.io/_files/ugd/d9f879_86b8be4faa4e46c8b402b4d7f079979e.pdf

September:
https://www.aryze.io/_files/ugd/d9f879_76b47430418243e08f8bef7a80c17b96.pdf

Please let me know if you have any questions !

All the best

Jodi
________________________________

**Comment by g1nt0ki** [comment]
hi @ARYZEofficial the issue is, you are issuer of stablecoin and it is your own dex. the dex has like 5k /529k of non aryze tokens. 

Note: we are not questioning the backing of these tokens

**Comment by g1nt0ki** [comment]
Uniswap's tvl is 3.5B of which uni token accounts for 17M = 0.4%
your case, it is 98.4% so bad comparison

**Comment by ARYZEofficial** [comment]
Hey g1nt0ki,

Super fair, I am sorry for my bad comparison, I am just merely trying to understand why our Digital Cash stablecoin cannot be part of TVL, as they are auditted stablecoins.

Our dex is a Stablecoin oriented Ex, meaning there wont be so many “otherCrypto” tokens other than USDC, DAI, Native tokens maybe BTC soon.

Would appreciate if you could include them as they are the native Stablecoins for the DEX.

If not, then feel free to proceed with the tokens you accepted earlier, just know that it would undermine the listing of the dex. 😊

Let me know what I can do to allow the other tokens, I am all ears for suggestions!

We just deployed the tokens on Curve and Uniswap aswell and they should be visible within an hour! 😊

All the best

Jodi

From: g1nt0ki ***@***.***>
Date: Friday, 17 November 2023 at 11.52
To: DefiLlama/DefiLlama-Adapters ***@***.***>
Cc: Jodi Usama Husain ***@***.***>, Mention ***@***.***>
Subject: Re: [DefiLlama/DefiLlama-Adapters] Add MAMA to Defillama (PR #8080)

Uniswap's tvl is 3.5B of which uni token accounts for 17M = 0.4%
your case, it is 98.4% so bad comparison

**Comment by llamatester** [comment]
The adapter at projects/mama exports TVL: 
        
 
 
    polygon                   1.47 k
    
    total                    1.47 k

**Pull request merged**
