### PR TITLE
Add 10kdex

### PR DESCRIPTION
**Pull request by breeze98**
##### Name (to be shown on DefiLlama):
10KDex

##### Twitter Link:
https://twitter.com/10KSwap

##### Website Link:
https://dex.10kx.com

##### Logo (High resolution, will be shown with rounded borders):
10k logo

##### Current TVL:
100,000 USD

##### Treasury Addresses (if the protocol has treasury)
0x2C145157e59CfB69a4607643D178B015E6A3004a

##### Chain:
Scroll

##### Short Description (to be shown on DefiLlama):
Empowering more DeFi users to relish a centralized exchange-like on-chain trading encounter.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Derivatives

##### forkedFrom (Does your project originate from another project):
GMX V1

##### methodology (what is being counted as tvl, how is tvl being calculated):
Total Value locked in Smart Contracts

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/10kdex exports TVL: 
        
 
 
    scroll                    36.34 k
    
    total                    36.34 k

**Comment by g1nt0ki** [comment]
@breeze98 thanks for the PR

**Comment by yuyunhong** [comment]
@g1nt0ki hi,I have a question, how should we calculate the dollar value of our own issued WETH?

**Comment by g1nt0ki** [comment]
@yuyunhong  added support here: https://github.com/DefiLlama/defillama-server/blob/master/coins/src/adapters/tokenMapping.json#L236 should reflect in the UI soon

**Comment by Armanbeyg** [comment]
(h)...w.
///___///

**Pull request merged**
