### PR TITLE
Add MemeJob 

### PR DESCRIPTION
**Pull request by baditu**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
MemeJob

##### Twitter Link:
https://x.com/MemeJobFun

##### List of audit links if any: 
N/A

##### Website Link: 
https://memejob.fun/

##### Logo (High resolution, will be shown with rounded borders):
https://drive.google.com/file/d/1PKO2UZ22KtRqp1OIeF6I6MZpT6PJO53H/view

##### Current TVL:
$155,375.60833

##### Short Description (to be shown on DefiLlama):
Launch instantly tradeable coins for 1$ | A pump fun of a different breed 🦖 | Built on $HBAR

##### Category (full list at https://defillama.com/categories) *Please choose only one:
DeFi / Launchpad

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is represented by all HBAR held in active bonding curves within MemeJob.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/buidler-labs

### CODE REVIEW

**Comment by llamabutler** [comment]
The adapter at projects/memejob exports TVL: 
        
 
 
    hedera                    0
    
    total                    0

**Comment by g1nt0ki** [comment]
@baditu thanks, I have added this with a fix

**Comment by baditu** [comment]
Thank you for the quick response and for adding the fix! I appreciate the promptness. Could you please let me know approximately how long it will take for the project to be visible on the site?

**Comment by g1nt0ki** [comment]
usually under 24 hours

**Pull request closed without merging**
