### PR TITLE
⚡️ exactly: limit and optimize fixed pool fetching

### PR DESCRIPTION
**Pull request by cruzdanilo**
# changes

- limit total number of fetched fixed pools to `2 * maxFuturePools` per market
- fetch all fixed pools in a single multicall
- set protocol start block for historical data

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/exactly exports TVL: 
        
 
 
    ethereum-borrowed         263.72 k
    ethereum                  858.95 k
    borrowed                  263.72 k
    
    total                    858.95 k

**Comment by llamatester** [comment]
The adapter at projects/exactly exports TVL: 
        
 
 
    ethereum                  858.46 k
    ethereum-borrowed         263.57 k
    borrowed                  263.57 k
    
    total                    858.46 k

**Comment by g1nt0ki** [comment]
@cruzdanilo it's Chrismas Eve, ideally neither of us should be working now, I am not sure how the PR helps me. I really want to avoid discussion our opinionated code. 

Curious how one can limit the number of pool calls, maybe slice last (max pool length + 7 ) ? i.e we ignore pools older than 7 months? 

Another question: Other protocols will use your tokens eUSDC and such, how do I price them, for example 1 eUSDC = (totalAssets/totalSupply) USDC ? 


I did not refactor code for fun, I noticed that you used human readable abi, I liked it (prefer it over the JSON ones), added support for it earlier today (https://github.com/DefiLlama/defillama-sdk/commit/f2d35e6503ce9e55a86ad1a9fe7f88eb0d455d30) and refactored your code to test the sdk as well, I sincerely apologize again.

**Comment by llamatester** [comment]
The adapter at projects/exactly exports TVL: 
        
 
 
    ethereum                  859.58 k
    ethereum-borrowed         264.39 k
    borrowed                  264.39 k
    
    total                    859.58 k

**Comment by cruzdanilo** [comment]
@g1nt0ki i now limited the number of fixed pools to 2 * maxFuturePools per market. i also used a single multicall for all fixed pools and exported the initial protocol block on ethereum, so we can have all historical data.

for the tokens (currently `eASSET`, but it will change soon to `exaASSET`), they are standard [ERC-4626](https://ethereum.org/en/developers/docs/standards/tokens/erc-4626/), and the token price is `totalAssets / totalSupply`, denominated in underlying assets.

**Pull request merged**
