### PR TITLE
add phar-v1 pools

### PR DESCRIPTION
**Pull request by 0xShad0w**
Hi again! Another one! Ty

Also would it be possible to change Ramses logo as well?

image_2024-03-12_09-33-35

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/pharaoh-exchange-v1 exports TVL: 
        
 
 
    avax-staking              414.65 k
    avax                      87.57689311004012
    staking                   414.65 k
    
    total                    87.57689311004012

**Comment by Define101** [comment]
@0xShad0w template information ....

**Comment by 0xShad0w** [comment]
Hey @Define101! My bad, I thought since they were all existing protocols that it would be easy for you to identify and I didn't have to fill in the template, but seems like it isn't the case and I should have at least provided some basic information. Will do it the right way next time, thank you. 

Would it be possible to rename them instead of V3 -> V2 and V2 -> V1 for all 3 projects? (NILE, PHAR and CLEO)

Thanks again!

**Comment by Define101** [comment]
@0xShad0w Hello hello. Just informing us that we already track them is more than enought. If you also could provide the display name and twitter/website links that would be perfect 
Regarding ramses logo. Should be good within 2 hours

**Pull request merged**
