### PR TITLE
add NAOS

### PR DESCRIPTION
**Pull request by jack77121**
##### Twitter Link:
https://twitter.com/naos_finance

##### List of audit links if any:
https://certificate.quantstamp.com/full/naos-formation

##### Website Link:
https://naos.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://ipfs.io/ipfs/QmPKkp44ZJSXfRpRWExdUnct2dohcE3x1XUxgh4ryKEMq7

##### Current TVL:
4.49 M

##### Chain:
Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
naos-finance

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
9504

##### Description/bio (to be shown on DefiLlama):
A DeFi lending protocol allowing lenders and SME borrowers to facilitate permissionless and borderless loaning/borrowing transactions

##### Token address and ticker if any:
NAOS
ETH: 0x4a615bb7166210cce20e6642a6f8fb5d4d044496

##### Category (Yield/Dexes/Lending/Minting):
Lending

##### [Optional] ETH addresss (to receive a LlamaPunk):
0x38502343cD16FE739ca18bDeC7857aEb775F0411

### CODE REVIEW

**Comment by 0xngmi** [comment]
Thanks! I'll push a commit on top to separate both pool2 TVL (staked NAOS-ETH LP tokens) and staked NAOS from the other TVL

**Comment by realdealshaman** [comment]
Thank you for your contribution! Your LlamaPunk has been sent: https://opensea.io/0x38502343cd16fe739ca18bdec7857aeb775f0411

**Comment by jack77121** [comment]
Thank you @0xngmi  and @realdealshaman  !

We found out that the $NAOS is separated as `staking` function which is cool, but not been called inside the `tvl` function.
But $NAOS is staking in our own `StakingPool` address, perhaps it could also been counted with tvl ?

If it is fine, we'd love to have another update PR 😃

**Comment by 0xngmi** [comment]
You are right, let me explain the reasoning behind it.
## Staking
When the drama around Sovryn happened we got a strong reponse from our community saying that they preferred staking TVL to be excluded from TVL and there was some debate around that. Our response was that it may be better to allow each user to choose for themselves whether staking should be part of the TVL or not, so what we are doing is separate staking from normal TVL and we plan to push an update to our frontend that will add a toggle that lets users choose whether it should be included.

Until that has been developed we just display the TVL without staking, so that's why you are seeing the current numbers

## Pool2
Since the beginning we've been excluding pool2 LP tokens from the TVL (except in some cases where the protocol is based on them, such as fei). Eventually we also plan to add a toggle for it

These are the reasons why staking and pool2 have been moved to different functions and for now are excluded.

If you feel like we are currently misclassifying these and that there's a strong argument for why we should include either staking or pool2 funds into your TVL we can discuss about it, we are pretty flexible with that.

**Pull request merged**
