### PR TITLE
add echelon

### PR DESCRIPTION
**Pull request by 0xJ3**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

Echelon Market

##### Twitter Link:

https://twitter.com/EchelonMarket

##### List of audit links if any:

https://docs.echelon.market/echelon-v1/audit-reports

##### Website Link:

https://app.echelon.market/

##### Logo (High resolution, will be shown with rounded borders):

Echelon Logo

##### Current TVL:

$184k

##### Treasury Addresses (if the protocol has treasury)

0xfa98d6ea4473eaf438676f4a74802082a3dba6221ac4d5a96c69dcbe142c2ec8

##### Chain:

Aptos

##### Short Description (to be shown on DefiLlama):

Composable, Efficient & Secure Move Money Market

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Lending

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):

Pyth and Switchboard

##### Implementation Details: Briefly describe how the oracle is integrated into your project:

Call Pyth whenever applicable, fallback to Switchboard otherwise

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:

https://docs.echelon.market/echelon-v1/risks#oracle-risk

##### forkedFrom (Does your project originate from another project):

Inspired by ideas of Compound V2 and Aave V3 but implement from scratch using Move

##### methodology (what is being counted as tvl, how is tvl being calculated):

tvl = sum(market cash) over all markets

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/echelon exports TVL: 
        
 
 
    aptos                     294955621.14 B
    
    total                    294955621.14 B

**Comment by llamatester** [comment]
The adapter at projects/echelon exports TVL: 
        
 
 
    aptos-borrowed            30.92 k
    aptos                     184.38 k
    borrowed                  30.92 k
    
    total                    184.38 k

**Comment by llamatester** [comment]
The adapter at projects/echelon exports TVL: 
        
 
 
    aptos                     184.47 k
    
    total                    184.47 k

**Comment by g1nt0ki** [comment]
hi @0xJ3 the code looks good, any reason for exlcluding borrowed, I think it is a nice metric to show

**Comment by llamatester** [comment]
The adapter at projects/echelon exports TVL: 
        
 
 
    aptos-borrowed            64.26 k
    aptos                     305.12 k
    borrowed                  64.26 k
    
    total                    305.12 k

**Comment by 0xJ3** [comment]
@g1nt0ki updated

**Comment by g1nt0ki** [comment]
@0xJ3 thanks

**Pull request merged**
