### PR TITLE
Merge between GenesisLRT and Inception

### PR DESCRIPTION
**Pull request by Sk1mer12**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/inception-lrt: 
        
 
  
    
    
    Error: Multicall failed! 
     [chain: ethereum] [fail count: 1] [abi: address:strategy]  
        target: 0xf073bAC22DAb7FaF4a3Dd6c6189a70D54110525C

**Comment by Sk1mer12** [comment]
GenesisLRT and Inception Merged. I opened the pull request to combine the TVL from both protocols on Inception. Also please delete genesisLRT repo. Thanks
Announcement link: https://x.com/Genesis_LRT/status/1787498799335665992

**Comment by llamatester** [comment]
The adapter at projects/inception-lrt exports TVL: 
        
 
 
    ethereum                  2.24 M
    
    total                    2.24 M

**Comment by Sk1mer12** [comment]
And please don't forget to delete genesisLRT (https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/projects/genesis-lrt)
I'm note being able to do it!

**Comment by g1nt0ki** [comment]
hi @Sk1mer12 we added a parent protocol instead: https://defillama.com/protocol/inception#information

**Comment by Sk1mer12** [comment]
@g1nt0ki Is it possible to make it only InceptionLRT? This is misleading to users since GenesisLRT no longer exists sir

**Pull request closed without merging**
