### PR TITLE
Energiswap Listing

### PR DESCRIPTION
**Pull request by TobyKreiselmaier**
#### Why are you creating this pull request?
We successfully launched our new DEX Energiswap on Feb 26, 2021.

##### Twitter Link:
https://twitter.com/Energicrypto

##### List of audit if any:
N/A

##### Website Link:
https://www.energiswap.org

##### Contact Email:
evan@energi.team

##### Expected TVL:
$120m (12 month target)

##### Chain:
Energi

##### Coingecko ID (so your TVL can appear on Coingecko):
https://www.coingecko.com/en/coins/energi

##### Description/bio (to be shown on DefiLlama):
A fully decentralized protocol for automated liquidity provision on Energi.

##### Token address and ticker if any:
https://etherscan.io/token/0x1416946162b1c2c871a73b07e932d2fb6c932069

### CODE REVIEW

**Comment by 0xngmi** [comment]
Thanks for submitting! I've noticed that you modified multiple unrelated files with this PR, so I've written a version that requires fewer changes on #66. Could you review that one and let me know if you agree to it?

**Comment by 0xngmi** [comment]
Merged in #66

**Comment by TobyKreiselmaier** [comment]
@0xngmi Thank you, that works for me! However, even though #66 is merged, I don't see it on the production site. When do you expect it to be listed?

**Comment by 0xngmi** [comment]
@TobyKreiselmaier it seems like the graph is broken, would it be possible to get a fix for it?

**Comment by TobyKreiselmaier** [comment]
@0xngmi I just checked. I don't see any issues. What exactly is not working?

**Pull request closed without merging**
