### PR TITLE
add BITU

### PR DESCRIPTION
**Pull request by 0xbitu**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
BitU Protocol

##### Twitter Link:
https://x.com/BitU_Protocol

##### List of audit links if any:
https://docs.bitu.io/bitu/resources/audits

##### Website Link:
https://bitu.io

##### Logo (High resolution, will be shown with rounded borders):
image

##### Current TVL:
$21M

##### Chain:
bsc

##### Short Description (to be shown on DefiLlama):
BitU Protocol offers a USD-pegged stablecoin primitive that provides stability and embedded yield. Through our Active Liquidity Management Module, we leverage on-chain transparency and off-chain capital efficiency to deliver resilient yield to support accessible ecosystem growth. 

##### Token address and ticker if any:
0x654A32542A84bEA7D2c2C1A1Ed1AAAf26888E6bD

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Decentralized Stablecoin

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Chainlink

##### methodology (what is being counted as tvl, how is tvl being calculated):
The total value of collateral locked in the BitU Protocol.
The quantity of collateral in the contract is multiplied by its price, which is updated in real-time.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/bitu exports TVL: 
        
 
 
    bsc                       21.72 M
    
    total                    21.72 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
thanks for the PR, but please compute the tvl using onchain data, like counting the token balance in your contracts

**Comment by 0xbitu** [comment]
> thanks for the PR, but please compute the tvl using onchain data, like counting the token balance in your contracts

sorry, tvl data is not stored in the contract and can only be calculated through events using subgraph.

**Comment by waynebruce0x** [comment]
how does collateralAssets() work? tracks deposit and withdrawals from ceffu? is the source code open source?

**Comment by 0xbitu** [comment]
> how does collateralAssets() work? tracks deposit and withdrawals from ceffu? is the source code open source?

Track events in the BitUMinting contract and calculate the corresponding collateral assets.
eventHandlers:
        - event: Mint(address,indexed address,indexed uint256,indexed
            uint256,uint256,uint256,uint256)
          handler: handleMint
        - event: Redeem(address,indexed address,indexed uint256,indexed
            uint256,uint256,uint256,uint256)
          handler: handleRedeem
        - event: Liqiudation(address,indexed address,indexed uint256,indexed
            uint256,uint256,uint256)
          handler: handleLiqiudation

https://github.com/BitU-Protocol/BitU-Subgraph

You can see the source code here.

**Pull request merged**
