### PR TITLE
[Range Protocol] Add Scroll Factories

### PR DESCRIPTION
**Pull request by kappayield-range**
Adding scroll factories for Izumi

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/range exports TVL: 
        
 
 
    base                      4.10 k
    bsc                       687.16 k
    manta                     673.38 k
    polygon                   3.58 k
    scroll                    8.94 k
    arbitrum                  1.49 M
    zeta                      324.35 k
    mantle                    17.18 M
    ethereum                  8.19 M
    
    total                    28.56 M

**Comment by llamatester** [comment]
The adapter at projects/range exports TVL: 
        
 
 
    base                      4.09 k
    scroll                    8.90 k
    bsc                       686.21 k
    zeta                      318.40 k
    arbitrum                  1.49 M
    manta                     669.71 k
    polygon                   3.56 k
    mantle                    17.14 M
    ethereum                  8.19 M
    
    total                    28.51 M

**Comment by g1nt0ki** [comment]
@kappayield-range thanks for the PR, I have simplified it a bit

**Comment by kappayield-range** [comment]
@g1nt0ki awesome, thanks for the code refactor 👍 . Hadn't gotten down to refactoring the code 😅

**Pull request merged**
