### PR TITLE
add multiple pools so move to config rather than token list

### PR DESCRIPTION
**Pull request by swimkirito**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/swim: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'value')
    Truncated error stack:
    
        at getTokenBalance (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:41:35)
        at async Promise.all (index 0)
        at async sumTokensUnknown (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:113:25)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:58:25)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:160:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:3

**Comment by llamatester** [comment]
The adapter at projects/swim exports TVL: 
        
 
 
    solana                    49.44 M
    
    total                    49.44 M

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
sorry, but you cannot count the swimUSD in the metapools, that would be double counting

**Comment by llamatester** [comment]
The adapter at projects/swim exports TVL: 
        
 
 
    solana                    40.44 M
    
    total                    40.44 M

**Comment by swimkirito** [comment]
> sorry, but you cannot count the swimUSD in the metapools, that would be double counting

Understood, I updated the PR to remove swimUSD.

**Pull request merged**
