### PR TITLE
feat: lombard vault

### PR DESCRIPTION
**Pull request by jameswstevens**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

Lombard Vaults

**  This should be added to the Lombard page similar to ether.fi **

##### Twitter Link:

https://x.com/Lombard_Finance

##### List of audit links if any:

https://github.com/Se7en-Seas/boring-vault/tree/main/audit

##### Website Link:

https://www.lombard.finance/app/vault/

##### Current TVL:

42.9M

##### Chain:

Ethereum

##### Short Description (to be shown on DefiLlama):

Automated yield management solution designed to maximize BTC-denominated returns

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Liquid Staking

##### methodology (what is being counted as tvl, how is tvl being calculated):

All LBTC deposited into our vaults. ** NOTE: It overlaps with out broader TVL calculation***

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/lombard-vault exports TVL: 
        
 
 
    ethereum                  43.90 M
    
    total                    43.90 M

**Comment by g1nt0ki** [comment]
hi @jameswstevens thanks for the PR, but I have already included this as part of ether-fi vault: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/etherfi-lrt/index.js#L8

**Comment by jameswstevens** [comment]
@g1nt0ki, apologies. This is not an Etherfi vault. This is the Lombard Vault. See https://www.lombard.finance/app/vault/

**Comment by g1nt0ki** [comment]
but deployed by ether fi team?

**Comment by jameswstevens** [comment]
no, it is a Veda vault.

**Comment by g1nt0ki** [comment]
yes, but whitelabeled to ether fi? https://github.com/DefiLlama/DefiLlama-Adapters/issues/10566

**Comment by jameswstevens** [comment]
@g1nt0ki, no. Actually in a few days, none of the Veda vault will have any TVL in Etherfi. See here the vault: https://debank.com/profile/0x5401b8620e5fb570064ca9114fd1e135fd77d57c.

**Comment by g1nt0ki** [comment]
*what is the relation with ether fi? I meant this is listed in the ether fi webpage and veda is managing it on their behalf

**Comment by jameswstevens** [comment]
We are depositing into Etherfi in the short term (from the vault). The user can individually stake into Etherfi as well. We asked Veda to place some vault TVL into etherfi to bootstrap liquidity. The vault and etherfi are two separate offerings.

**Comment by g1nt0ki** [comment]
to be clear, you are telling me that this is not the vault that you are trying to list but part of your vault is being deposited here? 
image

**Comment by jameswstevens** [comment]
Apologies for back and forth.

Correct - Veda provides a Vault service. Etherfi Vault and Lombard Vault are two separate services using Veda Vault Infrastructure but not the same vault.

1) Lombard has a "Lombard Vault" (Veda Vault 1). 

2) Etherfi has an "Etherfi vault" (Veda Vault 2). The confusion here is that Etherfi allows the user to stake LBTC on their platform and use this in their own vault (Veda Vault 2).

**Lombard Platform:**
BTC --> LBTC --> "Lombard Vault" (Veda Vault 1)

**Etherfi Platform**
BTC --> LBTC ---> Etherfi --> "Etherfi Vault" (Veda Vault 2)


The request I am bringing to this PR is Veda Vault 1.

**Comment by g1nt0ki** [comment]
so, "0x5401b8620E5FB570064CA9114fd1e135fd77D57c" is the address of veda vault 1? what is the address of vault 2? because I am fairly certain that '0x5401b8620E5FB570064CA9114fd1e135fd77D57c' is the vault ether fi have on their page (the tvl matches)

**Comment by jameswstevens** [comment]
This is vault 1 (Lombard Vault): 0x5401b8620E5FB570064CA9114fd1e135fd77D57c
This is vault 2 (Etherfi Vault): 0x657e8C867D8B37dCC18fA4Caead9C45EB088C642

**Comment by g1nt0ki** [comment]
my bad, I was blind and confused the two, really sorry about that. We will list this soon: https://github.com/DefiLlama/DefiLlama-Adapters/commit/9d66454bd096dbd630503645a85f364ef7502b9d

I see that some morpho tokens are not priced, will fix that.

**Pull request closed without merging**
