### PR TITLE
adding EXFI loans to TVL

### PR DESCRIPTION
**Pull request by TJakubek**
Adding a second loans contract to be counted in the loans TVL. 

On a separate note: is it possible for me to somehow handle pricing of our governance token or if this is something the team does internally?

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/flare-loans exports TVL: 
        
 
 
    songbird                  1.55 M
    
    total                    1.55 M

**Comment by g1nt0ki** [comment]
hi @TJakubek , can you share a LP address with highest liquidity for your gov token?

**Comment by TJakubek** [comment]
> hi @TJakubek , can you share a LP address with highest liquidity for your gov token?

hi @g1nt0ki , of course.
The most liquidity is in [0xcD15C231b8A0Bae40bD7938AE5eA8e43f1e9a15F](https://songbird-explorer.flare.network/address/0xcD15C231b8A0Bae40bD7938AE5eA8e43f1e9a15F/tokens#address-tabs), followed by [0x5D4e155CA27e8DAd4E4aceE48F83B6E0E4AFEec0](https://songbird-explorer.flare.network/address/0x5D4e155CA27e8DAd4E4aceE48F83B6E0E4AFEec0/tokens#address-tabs)

**Comment by TJakubek** [comment]
hey @g1nt0ki is there anything else you need?

**Comment by g1nt0ki** [comment]
fixed flare farm here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/51904bf5332e81f0c0ee5f5a82c45540a2513cb2

**Comment by TJakubek** [comment]
awesome @g1nt0ki ! thanks for going the extra mile <3

**Pull request merged**
