### PR TITLE
0x nodes adapter

### PR DESCRIPTION
**Pull request by tomxnodes**
##### Twitter Link:
https://twitter.com/0x_nodes

##### List of audit links if any:
https://github.com/0xNODES/_audits/tree/main/Halborn

##### Website Link:
https://0xnodes.io/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://github.com/0xNODES/DefiLlama-Adapters/blob/0x_nodes-adapter/projects/0x_nodes/0x_nodes_v.png

##### Current TVL:
total 4.50 M + staking 1.69 M

##### Chain:
Ethereum, BSC, Polygon, Fantom, Andromeda, Avalanche

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
10139

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
bios

##### Short Description (to be shown on DefiLlama):
0xNODES is a modularized cross chain yield aggregation protocol utilizing collateralized assets through synthetic swaps.

##### Token address and ticker if any:
0xAACa86B876ca011844b5798ECA7a67591A9743C8 (BIOS) https://etherscan.io/token/0xAACa86B876ca011844b5798ECA7a67591A9743C8

##### Category (full list at https://defillama.com/categories) *Please choose only one:
7 Yield Aggregator

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Coingecko

##### forkedFrom (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated):
'Counts the number of wrapped native tokens in all yield strategies across all the chains the protocol is deployed on + staking counts the number of BIOS tokens staked in the kernels across all the chains (PFA: Protocol Fee Accruals by staking assets)'

### CODE REVIEW

**Comment by waynebruce0x** [comment]
Can this be done using onchain calls?

**Comment by AugustG98** [comment]
> Can this be done using onchain calls? 

Hey, we really wanted to make use of onchain calls work here but our best bet is probably using our subgraphs because the protocol's assets are deployed to various LP farms across different chains would make it quite complex to fetch it all together (14 remote yield strategies and probably close to 30 LP farms) , and not sure how we'd make the adapter know what deployed assets is actually ours. The platform code uses its own accounting to keep track of onchain assets deployed deployed to the various farms. The subgraphs deployed by the 0xnodes team should be the sufficient and it's possible to check that their returned values are based on real onchain values.

**Comment by AugustG98** [comment]
> Can this be done using onchain calls? 

Give us this week, we'll try to swap out the gql for an rpc.

**Comment by tomxnodes** [comment]
@waynebruce0x and @AugustG98 migrating to on-chain is possible and can be completed later this year. Can we proceed with this PR as currently implemented, please.

**Comment by waynebruce0x** [comment]
If you can give us instructions on how to calculate TVL using onchain calls we can help you out - I'd rather not merge the gql we currently have

**Comment by llamatester** [comment]
The adapter at projects/0x_nodes exports TVL: 
        
 
 
    fantom                    57.08 k
    ethereum                  1.85 M
    avalanche                 117.00 k
    bsc                       60.42 k
    ethereum-staking          709.04 k
    polygon                   259.64 k
    avalanche-staking         19.36 k
    bsc-staking               10.86 k
    fantom-staking            16.98 k
    polygon-staking           61.15 k
    metis-staking             228.31 k
    metis                     330.01 k
    staking                   1.05 M
    
    total                    2.67 M

**Comment by 0xViva** [comment]
Confirming that we want this project removed from the defillama platform. Protocol out of operation

**Pull request merged**
