### PR TITLE
add stip&flip in the project list

### PR DESCRIPTION
**Pull request by sotach1**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Stip&Flip

##### Twitter Link:
https://x.com/StipFlip

##### List of audit links if any:
-

##### Website Link:
https://sf.exchange

##### Logo (High resolution, will be shown with rounded borders):
Screenshot 2024-06-17 at 16 27 10

##### Current TVL:
1.18k$

##### Chain:
ethereum classic 61

##### Short Description (to be shown on DefiLlama):
Open and decentralized synthetic trading protocol. Trade anything, short and long, on leverage, with no liquidation risk.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Synthetics (38)

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.): 
The protocol define it's own Oracle. It is a slow paced Oracle with a proof of stake that allow anyone to submit price as long as they have submitted a minimum stake. That stake is also used to compute the TVL
Oracle Address: 0x4AC635E92801e657F44BDEfcc7660Ea1431DF846
##### Implementation Details: Briefly describe how the oracle is integrated into your project:
The Oracle will gather the protocol swap fees, for each mint/burn of a synthetics, that will be distributed to the Oracle Operator that have provided a price and have deposited the minimal stake.
Oracle Operator have 1 hour to submit the price of an asset at midnight UTC every 24 hours.

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
https://docs.sf.exchange/docs/protocol-rules/data-provider

##### methodology (what is being counted as tvl, how is tvl being calculated):
The project mint/burn Synthetics every 24 hours in the Synths contracts. Those contract hold ETC representing the total deposit of trader and liquidity provider needed to back the synthetics.
Those synthetics are in turn traded in UniV3 pool 24/7, to provide trader with instant synthetic trading. The Synth value is already accounted in the Synth contract, the only token we are interested in the UniV3 pools are the WETC token.
The Oracle is a part of the protocol, it holds the Oracle Operator staking and contribute to the TVL as well.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/stip-flip

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/stipflip exports TVL: 
        
 
 
    ethereumclassic           971
    
    total                    971.4584361355702

**Comment by llamatester** [comment]
The adapter at projects/stipflip exports TVL: 
        
 
 
    ethereumclassic           1.23 k
    
    total                    1.23 k

**Comment by llamatester** [comment]
The adapter at projects/stipflip exports TVL: 
        
 
 
    ethereumclassic           1.36 k
    
    total                    1.36 k

**Comment by g1nt0ki** [comment]
@sotach1 thanks for the PR, sorry we cant count the value in the oracle as tvl, other than that, updated code to use event logs instead of graph.

**Comment by sotach1** [comment]
Oracle are an integral part of the protocol though. 
The staking in the Oracle gather the protocol fees, it is an integral part of the TVL

**Pull request merged**
