### PR TITLE
Update comptroller contract

### PR DESCRIPTION
**Pull request by dacarva**
The comptroller contract in line 6 was updated to the new address: 0x962308fef8edfadd705384840e7701f8f39ed0c0

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/tropykus exports TVL: 
        
 
 
    
    total                    0

**Comment by dacarva** [comment]
@llamatester I updated the contract address. It seemed a lower case issue in the address. I tested it on my machine and it is working now

**Comment by 0xngmi** [comment]
hm could be nice to move on chain, could use CompoundUsdExports if pricing is an issue

**Comment by g1nt0ki** [comment]
@dacarva thanks for the PR, but I am closing this one in favor of computing tvl using our api: https://github.com/DefiLlama/DefiLlama-Adapters/pull/3052/files#diff-0ebbceba39475cf82e2a4a1a5717e36b0f44c7d773b8016c900ba9604ac79538R5

**Pull request closed without merging**
