### PR TITLE
feat: add adapter for origami

### PR DESCRIPTION
**Pull request by 0xtjoe**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama): 
Origami Finance

##### Twitter Link: 
https://twitter.com/origami_fi

##### List of audit links if any: 
https://github.com/TempleDAO/origami-public/blob/main/audits/origami-v2/Origami%20Finance%20-%20Zellic%20Audit%20Report.pdf

##### Website Link: 
https://origami.finance

##### Logo (High resolution, will be shown with rounded borders):
https://docs.origami.finance/~gitbook/image?url=https%3A%2F%2F1838495634-files.gitbook.io%2F%7E%2Ffiles%2Fv0%2Fb%2Fgitbook-x-prod.appspot.com%2Fo%2Fspaces%252FuQqfnSZUSHvj0FdEt8I8%252Fuploads%252FJbmiK2JcjhakBDMDkEFD%252FOrigami%2520Logo.png%3Falt%3Dmedia%26token%3D4e0dfd03-1879-4a57-a5d8-156e074abf32&width=768&dpr=4&quality=100&sign=fb51723b3f82c93e84f268ccfc58faceb84074e0ad199c663719ec99483b812b

##### Current TVL: 
8.3M

##### Chain: 
Ethereum, Arbitrum, Berachain

##### Short Description (to be shown on DefiLlama): 
Origami is a first-in-class automated leverage protocol launching on Ethereum and 🐻⛓️

##### Category (full list at https://defillama.com/categories) *Please choose only one:
[Leveraged Farming](https://defillama.com/protocols/Leveraged%20Farming)

##### forkedFrom (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated):
Subgraph

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/TempleDAO

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/origami exports TVL: 
        
 
 
    ethereum                  8.17 M
    arbitrum                  97.00 k
    
    total                    8.27 M

**Comment by llamatester** [comment]
The adapter at projects/origami exports TVL: 
        
 
 
    ethereum                  7.92 M
    arbitrum                  96.65 k
    
    total                    8.02 M

**Comment by g1nt0ki** [comment]
@0xtjoe thanks for the PR, I have refactored it a bit, can you verify if the logic is fine?

I have updated code to pull only vault list from graph (and it is cached), this way, even if the vault becomes unreachable, we can still compute tvl

**Comment by frontier159** [comment]
Appreciate the review and refactor @g1nt0ki Nice work picking the correct functions to use to get the balances.

Out of interest, where do the USD values get pulled from? For example, if Origami launches a new vault which doesn't yet have that USD oracle hooked up where do we go?

**Comment by 0xtjoe** [comment]
> @0xtjoe thanks for the PR, I have refactored it a bit, can you verify if the logic is fine?
> 
> I have updated code to pull only vault list from graph (and it is cached), this way, even if the vault becomes unreachable, we can still compute tvl

All good, working correctly.
Thanks for your awesome code.

**Comment by 0xtjoe** [comment]
> Appreciate the review and refactor @g1nt0ki Nice work picking the correct functions to use to get the balances.
> 
> The logic looks sound to me.
> 
> Out of interest, where do the USD values get pulled from? For example, if Origami launches a new vault which doesn't yet have that USD oracle hooked up where do we go?

@g1nt0ki 
Could you please confirm this?

**Comment by g1nt0ki** [comment]
> > Appreciate the review and refactor @g1nt0ki Nice work picking the correct functions to use to get the balances.
> > The logic looks sound to me.
> > Out of interest, where do the USD values get pulled from? For example, if Origami launches a new vault which doesn't yet have that USD oracle hooked up where do we go?
> 
> @g1nt0ki Could you please confirm this?

hi @0xtjoe we pull the token prices from various sources and cache in our server: https://github.com/DefiLlama/defillama-server/tree/master/coins/src/adapters

**Comment by g1nt0ki** [comment]
in case we miss some tokens, we can manual add code to track their price

**Comment by 0xl2** [comment]
> in case we miss some tokens, we can manual add code to track their price

That's why you used `api.add` in the refactored code?

**Comment by 0xtjoe** [comment]
> in case we miss some tokens, we can manual add code to track their price

That's why you used `api.add` in the refactored code?

**Comment by g1nt0ki** [comment]
yeah, it adds token balance, and later we pull token prices and compute tvl in usd

**Pull request merged**
