### PR TITLE
feat: Add Syncus

### PR DESCRIPTION
**Pull request by zilayo**
##### Name (to be shown on DefiLlama):
Syncus

##### Twitter Link:
https://twitter.com/Syncus_Fi

##### List of audit links if any:
n/a

##### Website Link:
https://app.syncus.fi/#/

##### Logo (High resolution, will be shown with rounded borders):
image

##### Current TVL:
$3.17m staked + $2.1m treasury

##### Treasury Addresses (if the protocol has treasury)
https://etherscan.io/address/0xC00EC94e7746C6b695869580d6D2DB50cda86094

##### Chain:
Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): 
syncus

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed):
n/a

##### Short Description (to be shown on DefiLlama):
 A treasury-backed DeFi protocol designed to be the cornerstone of a new cross-chain economic system.

##### Token address and ticker if any:
SYNC - 0xa41d2f8Ee4F47D3B860A149765A7dF8c3287b7F0

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Reserve Currency

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
n/a

##### forkedFrom (Does your project originate from another project):
Olympus

##### methodology (what is being counted as tvl, how is tvl being calculated):
Tracks the amount of SYNC staked in the Staking contract & reserve tokens (currently only SYNC/ETH LP) held in the Treasury contract.

##### Github org/user (Optional, if your code is open source, we can track activity):
n/a

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/syncus exports TVL: 
        
 
 
    ethereum-staking          3.16 M
    ethereum                  2.17 M
    staking                   3.16 M
    
    total                    2.17 M

**Comment by llamatester** [comment]
The adapter at projects/syncus exports TVL: 
        
 
 
    ethereum                  0
    ethereum-staking          2.65 M
    staking                   2.65 M
    
    total                    0

**Comment by llamatester** [comment]
The adapter at projects/treasury/syncus.js exports TVL: 
        
 
 
    ethereum-ownTokens        827.75 k
    ethereum                  2.01 M
    ownTokens                 827.75 k
    
    total                    2.01 M

**Comment by g1nt0ki** [comment]
@zilayo thanks for the PR, we track treasury as separate metric so I split the adapter

**Pull request merged**
