### PR TITLE
Update Impermax app for TVL and borrowed amounts

### PR DESCRIPTION
**Pull request by pingu1**
The Impermax adapter is out of date and needed a little update to properly fetch TVL and borrowed amounts.

**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/impermax: 
        
 
  
    
    
    Error: Multicall is missing a target
    Truncated error stack:
        at Object.<anonymous> (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/abi/index.js:256:35)
        at new Promise (<anonymous>)

**Comment by pingu1** [comment]
> Error while running adapter at projects/impermax: 
>         
>  
>   
>     
>     
>     Error: Multicall is missing a target
>     Truncated error stack:
>         at Object.<anonymous> (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/abi/index.js:256:35)
>         at new Promise (<anonymous>)
>     

yep, I need to figure out why eth and fantom fail

**Comment by llamatester** [comment]
The adapter at projects/impermax exports TVL: 
        
 
 
    moonriver-borrowed        239.71801463184892
    era-borrowed              13.14 k
    arbitrum-borrowed         318.29 k
    polygon-borrowed          304.29 k
    avax-borrowed             41.80 k
    fantom-borrowed           186.40287598808987
    ethereum-borrowed         5.01 k
    moonriver                 9.32 k
    era                       115.57 k
    polygon                   1.28 M
    canto-borrowed            464.1398305126623
    arbitrum                  1.16 M
    avax                      240.53 k
    ethereum                  195.10 k
    fantom                    8.79 k
    canto                     2.01 k
    borrowed                  683.42 k
    
    total                    3.02 M

**Comment by g1nt0ki** [comment]
looks good, thanks for the PR

**Pull request merged**
