### PR TITLE
add filecoin chain to tvl

### PR DESCRIPTION
**Pull request by as472**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/SecuredFinance exports TVL: 
        
 
 
    ethereum                  24.83 k
    arbitrum                  4.09 k
    avax                      1.77 k
    polygon_zkevm             1.57 k
    filecoin                  672
    
    total                    32.94 k

**Comment by as472** [comment]
@g1nt0ki we are looking to add TVL for filecoin in this PR. (FIL, iFIL)
However, the iFIL amount is not being captured correctly.

**Comment by g1nt0ki** [comment]
hi @as472 I cant find iFIL on coingecko, do you know how to fetch it's price on chain?

**Comment by g1nt0ki** [comment]
hmm, we are pricing it now, so merging this.

**Pull request merged**
