### PR TITLE
feat: Adapter, Kelp - breakdown chains

### PR DESCRIPTION
**Pull request by 0xpeluche**
breakdown chains

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/kelp-dao exports TVL: 
        
 
 
    ethereum                  506.29 M
    arbitrum                  41.21 M
    scroll                    38.55 M
    linea                     29.37 M
    blast                     8.44 M
    mode                      3.20 M
    optimism                  1.71 M
    base                      1.13 M
    era                       788.61 k
    manta                     50.36 k
    xlayer                    5.05 k
    
    total                    630.75 M

**Comment by llamatester** [comment]
Error while running adapter at projects/kelp-dao: 
        
 
  
    
    
    Error: Failed to call: uint256:totalSupply target: 0x5a71f5888ee05b36ded9149e6d32ee93812ee5e9 on chain: [xlayer] rpc: https://endpoints.omniatech.io/v1/xlayer/mainnet/public, https://wallet.okex.org/fullnode/xlayer/discover/rpc/ro, https://rpc.xlayer.tech, https://xlayerrpc.okx.com  call reverted, reason: fragment.format is not a function

**Comment by llamatester** [comment]
The adapter at projects/kelp-dao exports TVL: 
        
 
 
    ethereum                  501.74 M
    arbitrum                  43.51 M
    scroll                    36.51 M
    linea                     28.33 M
    blast                     8.25 M
    mode                      2.99 M
    optimism                  1.52 M
    base                      1.15 M
    era                       779.16 k
    manta                     49.76 k
    xlayer                    4.99 k
    
    total                    624.83 M

**Comment by g1nt0ki** [comment]
@0xpeluche PR is good except of the api mutation part, it is a bad idea because api object abstracts both chain and corresponding block information. 

In this PR, you changed the chain object, but not the block, so api.call would return incorrect result/fail because we will be querying arb rpc with ethereum block.

**Pull request merged**
