### PR TITLE
This PR adds the ETCMC adapter to the DeFi Llama project, showcasing …

### PR DESCRIPTION
**Pull request by Nowalski**
…a DEX on the Ethereum Classic chain. The adapter includes TVL calculation logic using the `getUniTVL` helper function. The methodology section in the adapter configuration explains how TVL is calculated based on liquidity in the AMM.

Changes:
- Added ETCMC adapter configuration to `projects/etcmc/index.js`.
- Updated the configuration to include the staking contract address and the main ETCPOW contract address.
- Tested the integration to ensure accurate TVL calculation

**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Current TVL:
327.18 k

##### Chain:
61 ( ETC Classic )

##### Short Description (to be shown on DefiLlama):
ETCPOW is an ERC20 token on the Ethereum Classic network. It is designed to become the lifeblood of the ETCMC ecosystem, a community-driven initiative aimed at promoting decentralization and rewarding network participation. With a fixed supply of 1 billion tokens, ETCPOW is poised to become a cornerstone of the Ethereum Classic landscape.

##### Token address and ticker if any:
0x6c3B413C461c42a88160Ed1B1B31d6f7b02a1C83

##### Category (full list at https://defillama.com/categories) *Please choose only one:
[Dexes](https://defillama.com/protocols/Dexes)

##### methodology (what is being counted as TVL, how is TVL being calculated):
- TVL Calculation: TVL for ETCPOW is calculated based on the total value of tokens locked in the protocol's staking pools and liquidity pools. The TVL is determined by summing the USD value of all tokens locked in staking and liquidity pools, as provided by the Chainlink oracle.
- TVL Formula: TVL = Σ(USD value of staked tokens + USD value of liquidity tokens)
- TVL Update Frequency: The TVL is updated periodically, typically every few minutes, to reflect changes in token prices and pool balances.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/etcmc exports TVL: 
        
 
 
    ethereumclassic           330.25 k
    
    total                    330.25 k

**Comment by llamatester** [comment]
The adapter at projects/etcmc exports TVL: 
        
 
 
    ethereumclassic           327.07 k
    ethereumclassic-staking   0
    staking                   0
    
    total                    327.07 k

**Comment by g1nt0ki** [comment]
@Nowalski thanks for the PR

**Comment by llamatester** [comment]
The adapter at projects/etcmc exports TVL: 
        
 
 
    ethereumclassic           326.19 k
    ethereumclassic-staking   245.53 k
    staking                   245.53 k
    
    total                    326.19 k

**Pull request merged**
