### PR TITLE
update Bridge Mutual

### PR DESCRIPTION
**Pull request by solenemep**
##### methodology (what is being counted as tvl, how is tvl being calculated):

TVL is now calculated based on virtual USDT in Capital Pool, which is more representative

### CODE REVIEW

**Comment by waynebruce0x** [comment]
How is virtualUsdtAccumulatedBalance calculated?

**Comment by solenemep** [comment]
It represents the usdt locked in protocol. So each time liquidity is added or withrawn, virtualUsdtAccumulatedBalance is updated accordingly. You can check CapitalPool.sol

**Comment by waynebruce0x** [comment]
is this different to reading the USDT balance of the contract?

**Comment by solenemep** [comment]
Yes because the protocol has a system of Leverage and Liquidity Cushion that disperse liquidity. Thanks to this function in CapitalPool, we got all USDT in protocol.

**Pull request merged**
