### PR TITLE
Update Fluidtokens fetch

### PR DESCRIPTION
**Pull request by elRaulito**
Added liquidity locked in the smart contract

**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below if the PR is for listing a new protocol
3. If you want to update the protocol info you entered in the form below, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI

---

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/fluidtokens: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:219:11

**Comment by llamatester** [comment]
Error while running adapter at projects/fluidtokens: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:219:11

**Comment by g1nt0ki** [comment]
I think it is failing because we dont have this package: @blockfrost/blockfrost-js

**Comment by g1nt0ki** [comment]
@elRaulito think I can fix it from here, kinda touchy in adding more npm dependencies, adding a blockfrost rest api wrapper instead

**Comment by elRaulito** [comment]
@g1nt0ki oh, let me know then, and thanks a lot!

**Comment by g1nt0ki** [comment]
@elRaulito it is changed here, https://github.com/DefiLlama/DefiLlama-Adapters/pull/3109/commits/c0f9b76b2963c7de279ba9353fc822f0a82ee4be

does it look right to you?

**Pull request closed without merging**
