### PR TITLE
Added KDex for Kava

### PR DESCRIPTION
**Pull request by kdex-dev**
##### Name (to be shown on DefiLlama):
KDex

##### Twitter Link:
https://twitter.com/kdex_app

##### List of audit links if any:
None
##### Website Link:
https://kdex.app

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://pbs.twimg.com/profile_images/1572236943924117506/eIOU-vAA_400x400.jpg

##### Current TVL:
--- kava ---
Total: 0 

--- tvl ---
Total: 0 

------ TVL ------
kava                      0

total                    0 

##### Chain:
Kava

##### Short Description (to be shown on DefiLlama):
The KDex is a Uniswap V2 fork deployed on Kava, a Cosmos EVM-based bockchain

##### Token address and ticker if any:
0x836a8f50dEe12B6acca966e9861749eCf269D9d2 KDEX

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
No

##### forkedFrom (Does your project originate from another project):
Uniswap

##### methodology (what is being counted as tvl, how is tvl being calculated):
Factory addresses (0x9a6d197e85e61c23146F5b7FA55fc8a6EDDD2D57 for kava) is used to find the LP pairs. TVL is equal to the liquidity on the AMM

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/kdex exports TVL: 
        
 
 
    kava                      0
    
    total                    0

**Comment by realdealshaman** [comment]
@kdex-dev hey, thanks for the pr, when will the kdex have a tvl? we'd prefer not to add it with a $0 tvl

**Comment by g1nt0ki** [comment]
@kdex-dev I see that there is no pairs so far, let us know once you add some liquidity, we will list it.

**Comment by kdex-dev** [comment]
Hi @g1nt0ki We have started bootstrapping LP now.

--- kava ---
usd-coin                  701.4
dai                       700.6999999999999
Total: 1.40 k 

--- tvl ---
usd-coin                  701
dai                       701
Total: 1.40 k 

------ TVL ------
kava                      1.40 k

total                    1.40 k 

Let me know if anything else required or any minimum criteria

**Pull request merged**
