### PR TITLE
add BankofCronos

### PR DESCRIPTION
**Pull request by bankofcronos**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Treasury Addresses (if the protocol has treasury):  adding team treasury (not protocol backing treasury): 

0x1087234fe877721F30016ebeD5BEd061397C8851

##### Category (full list at https://defillama.com/categories) *Please choose only one: 

BankofCronos : Reserve currency
BankofCronos-Loans : CDP

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/BankOfCronos exports TVL: 
        
 
 
    cronos                    23.07 k
    
    total                    23.07 k

**Comment by realdealshaman** [comment]
@bankofcronos Hi, thank you for the PR, there are a couple of changes needed before we can merge please. We don't count stability pool tvl for Liquity or any of it's forks also , treasury tvl should be listed separately and added as a file here: https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/projects/treasury

**Comment by llamatester** [comment]
The adapter at projects/BankOfCronos exports TVL: 
        
 
 
    cronos                    361.148
    
    total                    361.148

**Comment by llamatester** [comment]
The adapter at projects/BankOfCronos exports TVL: 
        
 
 
    cronos                    361.509148
    
    total                    361.509148

**Comment by llamatester** [comment]
Error while running adapter at projects/treasury: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:203:11

**Comment by bankofcronos** [comment]
- removed stability pool from tvl
- removed treasury mv from tvl 
- added treasury implentation (copied olympus-dao)

treasury is fork of olympusdao for protocol's BOC token, I see treasury mv included in olympus tvl adapter below, can this also be included in our case?

https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/olympus/index.js
https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/treasury/olympus-dao.js

**Comment by llamatester** [comment]
The adapter at projects/BankOfCronos exports TVL: 
        
 
 
    cronos                    362.1585
    
    total                    362.1585

**Comment by llamatester** [comment]
Error while running adapter at projects/treasury: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:203:11

**Comment by 0xngmi** [comment]
wdym by 'treasury mv'?

**Comment by llamatester** [comment]
The adapter at projects/BankOfCronos exports TVL: 
        
 
 
    cronos                    362.37951749999996
    
    total                    362.37951749999996

**Comment by llamatester** [comment]
Error while running adapter at projects/treasury: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:203:11

**Comment by realdealshaman** [comment]
Thanks for explaining what you meant by "treasury mv" However, we won't be able to count it as TVL because we are already counting the value of CUSD. Counting it again within the same protocol would be double-counting. Hope you understand

**Comment by realdealshaman** [comment]
treasury adapter looks good, I think our bot llamatester just doesn't read its exports yet, but we can merge once the tvl adapter is updated

**Comment by bankofcronos** [comment]
can we submit two separate protocol tvls? one as reserve currency category for olympus fork treasury and token. And another as CDP category for yeti finance fork? 

its just that the olympus fork treasury tvl is more important for the protocol token metrics (Mcap/TVL etc.)

**Comment by llamatester** [comment]
The adapter at projects/BankOfCronos exports TVL: 
        
 
 
    cronos                    22.95 k
    
    total                    22.95 k

**Comment by llamatester** [comment]
Error while running adapter at projects/treasury: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:203:11

**Comment by bankofcronos** [comment]
-updated projects/treasury/bankofcronos.js to include team multisig and team tokens
-readded olympus fork treasury to tvl as protocol tvl shouldn't only be CDP value collateral. If prices went to 0 all CDP's would be liquidated but tvl shouldnt be zero as protocol tokens are backed by treasury mv

**Comment by llamatester** [comment]
The adapter at projects/BankOfCronos exports TVL: 
        
 
 
    cronos                    22.97 k
    
    total                    22.97 k

**Comment by llamatester** [comment]
Error while running adapter at projects/treasury: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:203:11

**Comment by realdealshaman** [comment]
@bankofcronos we can add as two products under a parentProtocol, we have the availability to add this here: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/parentProtocols.ts

**Comment by llamatester** [comment]
The adapter at projects/BankOfCronos exports TVL: 
        
 
 
    cronos                    22.95 k
    
    total                    22.95 k

**Comment by llamatester** [comment]
The adapter at projects/BankofCronos-Loans exports TVL: 
        
 
 
    cronos                    363.827
    
    total                    363.827

**Comment by llamatester** [comment]
Error while running adapter at projects/treasury: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:203:11

**Comment by llamatester** [comment]
The adapter at projects/BankOfCronos exports TVL: 
        
 
 
    cronos                    22.59 k
    
    total                    22.59 k

**Comment by llamatester** [comment]
The adapter at projects/BankofCronos-Loans exports TVL: 
        
 
 
    cronos                    363.827
    
    total                    363.827

**Comment by llamatester** [comment]
Error while running adapter at projects/treasury: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:203:11

**Comment by bankofcronos** [comment]
ok thanks, separated into projects/BankofCronos and projects/BankofCronos-Loans

can we have the parent protocol as below (added logo BOC_logo_light.png from (https://github.com/bankofcronos/icons/pull/1):

 

 {
    id: "Bank of Cronos",
    name: "Bank of Cronos",
    url: "https://app.bankofcronos.com",
    description:
    "DeFi made simple, on Cronos.",
    logo: `${baseIconsUrl}/BOC_logo_light.png`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "bankofcronos",
  },

**Comment by Define101** [comment]
Hello @bankofcronos , notice that the lend protocol is not live yet correct?

**Comment by bankofcronos** [comment]
Hi @Define101 it is live, we are rolling out frontend this weekend. Can we have that listed as well? 

I see Bank of Cronos  listed but as "Bank of Cronos OHM", can we remove the OHM from the name?  For the description under Protocol Information where can we update that? I made a mistake with the methodology for this adapter I will create another pull request to fix.


image

**Pull request merged**
