### PR TITLE
ft: add brahma.fi

### PR DESCRIPTION
**Pull request by Pradeep-selva**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/brahmafi: 
        
 
  
    
    
    Error: 
        Please move the following keys into the chain: tvl
    
        We have a new adapter export specification now where tvl and other chain specific information are moved inside chain export.
        For example if your protocol is on ethereum and has tvl and pool2, the export file would look like:
        
            module.exports = {
              methodlogy: '...',
              ethereum: {
                tvl: 
                pool2:
              }
            }

**Comment by llamatester** [comment]
Error while running adapter at projects/brahmafi: 
        
 
  
    
    
    Error: 
        Please move the following keys into the chain: tvl
    
        We have a new adapter export specification now where tvl and other chain specific information are moved inside chain export.
        For example if your protocol is on ethereum and has tvl and pool2, the export file would look like:
        
            module.exports = {
              methodlogy: '...',
              ethereum: {
                tvl: 
                pool2:
              }
            }

**Comment by llamatester** [comment]
The adapter at projects/brahmafi exports TVL: 
        
 
 
    ethereum                  0.8904835723206516
    
    total                    0.8904835723206516

**Comment by llamatester** [comment]
Error while running adapter at projects/brahmafi: 
        
 
  
    
    
    Error: Request failed with status code 404
    Truncated error stack:
        at createError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/axios/lib/core/createError.js:16:15)
        at IncomingMessage.emit (node:events:539:35)

**Comment by llamatester** [comment]
The adapter at projects/brahmafi exports TVL: 
        
 
 
    ethereum                  1.54 M
    
    total                    1.54 M

**Comment by waynebruce0x** [comment]
Can this be calculated using onchain calls instead?

**Comment by Pradeep-selva** [comment]
> Can this be calculated using onchain calls instead?

Hey, We are planning to push new vaults fairly frequently right now. So this was done, so we wouldn't have to create new PRs every time a new vault is deployed, to update TVL.
Is this an issue?

**Comment by waynebruce0x** [comment]
We prefer to use onchain calls for transparency - is the API open source?

**Comment by Pradeep-selva** [comment]
> We prefer to use onchain calls for transparency - is the API open source?

Yes, the API is open sourced. You can find the code for TVL calculation here -> https://github.com/Brahma-fi/degen-vaults-restapi/blob/master/src/utils/on_chain.py

**Pull request merged**
