### PR TITLE
Fixed Adamant Finance Polygon addresses

### PR DESCRIPTION
**Pull request by eepdev**
* Added the ADDY/WETH pool (where the majority of 2pool liquidity actually is) and removed the ADDY/USDC Sushiswap vault
* Changed the function used to get 2pool liquidity from `IVault.balance` to `IStakingRewards.totalSupply` on Polygon, since the ADDY/WETH pool isn't a vault
* Fixed an error where DefiLlama was showing an incorrectly low staking TVL because it was looking at the ADDY balances of the Lock Plus/Basic contracts instead of the ADDY balance of the `MultiFeeDistribution` contract that those contracts actually stake in
### May 18:
* Merged most recent [commit](https://github.com/DefiLlama/DefiLlama-Adapters/commit/7f5961d73b82053616ec4c5f35c7b2a3102d3582)
* Added the old `calcPool2` function back as `calcPool2_staking_rewards`, which is only called by `pool2Polygon`

Contract links can be found at https://adamantfinance.gitbook.io/adamant-finance/contract-links

### CODE REVIEW

**Comment by waynebruce0x** [comment]
is the addy/weth pool staked in a contract?

**Comment by eepdev** [comment]
> are the addy/weth tokens staked in a contract?

Yes, they're staked in [0xF7661EE874Ec599c2B450e0Df5c40CE823FEf9d3](https://polygonscan.com/address/0xF7661EE874Ec599c2B450e0Df5c40CE823FEf9d3#readContract) (the `AddyStakingRewards` contract)

**Comment by llamatester** [comment]
Error while running adapter at projects/adamantfinance: 
        
 
  
    
    
    TypeError: Cannot read properties of null (reading 'toLowerCase')
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/unwrapLPs.js:161:33
        at async Promise.all (index 2)
        at async unwrapUniswapLPs (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/unwrapLPs.js:153:3)
        at async uniTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/adamantfinance/index.js:478:3)
        at async tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/adamantfinance/index.js:520:14)
        at async cronosTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/adamantfinance/index.js:146:10)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:58:25)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:160:9
        at async Promise.all (index 2)
        at async Promise.all (index 2)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:205:3

**Comment by eepdev** [comment]
I'm unable to get even the [previous commit](https://github.com/DefiLlama/DefiLlama-Adapters/commit/1b122afa13b819f8e434504f8676a84061b4c92d) to work.
I keep getting these errors:
* `TypeError: Cannot read properties of null (reading 'toLowerCase')` 
*  `Error: Couldn't find block height for chain cronos, RPC node rugged` 
*  `Error: invalid BigNumber string (argument="value", value="NaN", code=INVALID_ARGUMENT, version=bignumber/5.6.0)`

**Comment by eepdev** [comment]
The issue was resolved in the most recent commit.

**Comment by llamatester** [comment]
The adapter at projects/adamantfinance exports TVL: 
        
 
 
    arbitrum-staking          121.23 k
    cronos-staking            44.93 M
    cronos-pool2              0
    polygon-staking           1.03 M
    polygon-pool2             543.08 k
    arbitrum                  74.97 k
    polygon                   3.20 M
    cronos                    93.04 k
    staking                   46.08 M
    pool2                     543.08 k
    
    total                    3.36 M

**Pull request merged**
