### PR TITLE
exactly: initial integration

### PR DESCRIPTION
**Pull request by cruzdanilo**
##### Name (to be shown on DefiLlama):
Exactly

##### Twitter Link:
https://twitter.com/exactlyprotocol

##### List of audit links if any:
https://github.com/exactly/audits

##### Website Link:
https://exact.ly/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
[1](https://1099550196-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2Fn6wwJ0pvrhjXGxxDpmNa%2Fuploads%2FXPQGSf3uXGcVjjsp1W7q%2FIsologo%20-%20White.svg?alt=media&token=bb1dc6c8-2c71-4d94-b7c6-146dc0df0b86) [2](https://1099550196-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2Fn6wwJ0pvrhjXGxxDpmNa%2Fuploads%2FywSTBZFhpiQcdheLN0J6%2FIsologo%20-%20Black.svg?alt=media&token=726cba89-0072-4c9b-a0db-48b73d0e1c3f) [3](https://1099550196-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2Fn6wwJ0pvrhjXGxxDpmNa%2Fuploads%2Fg1eKVv04Uc4sq9Mxhadn%2FTwitter%20Logo.png?alt=media&token=e61339b9-dffc-45c2-b607-e43058e40e27) [4](https://1099550196-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2Fn6wwJ0pvrhjXGxxDpmNa%2Fuploads%2FbLt8A2S2yyrS4ihEZstG%2FTwitter%20Logo%20-%20White.png?alt=media&token=b7d5e340-482b-4bdf-9cc4-113220f2ba6f)

##### Current TVL:
856.02 k

##### Chain:
Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N/A

##### Short Description (to be shown on DefiLlama):
Exactly is a decentralized, non-custodial, open-source protocol that provides an autonomous fixed and variable interest rate market, enabling users to frictionlessly exchange their assets' time value and complete the DeFi credit market.

##### Token address and ticker if any:
N/A

##### Category (full list at https://defillama.com/categories) *Please choose only one:
1 - Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
Counts the tokens locked in the contracts to be used as collateral to borrow or to earn yield. Borrowed coins are not counted towards the TVL, so only the coins actually locked in the contracts are counted. There are multiple reasons behind this but one of the main ones is to avoid inflating the TVL through cycled lending.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/exactly exports TVL: 
        
 
 
    ethereum                  854.30 k
    ethereum-borrowed         264.54 k
    borrowed                  264.54 k
    
    total                    854.30 k

**Comment by g1nt0ki** [comment]
@cruzdanilo thanks for the PR, I made a minor code refactor here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/ee2850e577612c932df1f695df6317efbb7db562

**Comment by cruzdanilo** [comment]
@g1nt0ki the refactor was not minor. any reason for that?

**Comment by cruzdanilo** [comment]
we spend time and effort on this. can you please explain the changes?

**Comment by g1nt0ki** [comment]
@cruzdanilo I had made a bug in the refactor, fixed it: https://github.com/DefiLlama/DefiLlama-Adapters/commit/0fc0b99d71355b0918aee95e2a9c7454f54c6066

Reason for refactor: relying on sdk methods instead of using rpc provider/interacting with multicall directly, this way, we have better control, change things in one place/cache calls, etc. Called it minor because I have retained the logic , changed only the function used.

Thanks again for the code, appreciate it, just one issue I noticed while fixing the bug that I introduced, this is #markets extra calls each passing day right? is there a different way to go about this? maybe by fetching this information via logs? or start time not being older than 30 days?

**Comment by cruzdanilo** [comment]
that was disrespectful. it was not just a refactor, features were disabled (ex: `timetravel`, type validation) without any previous review or comment in this pr.

**Comment by g1nt0ki** [comment]
hi @cruzdanilo , sorry, it was not intentional, I changed the code, so it is easy for me to understand/modify in the future.

  *  timetravel flag defaults to true, need to be set false only if it is not possible, hence removed it.
  * Removed type validation because I am not using it
  
  Try looking at it from my pov.

**Pull request merged**
