### PR TITLE
update tvl calculations. add whitelabel moonriver calculation

### PR DESCRIPTION
**Pull request by adamxyzxyz**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/fractal-protocol exports TVL: 
        
 
 
    moonriver                 2.01 M
    ethereum                  9.44 M
    
    total                    11.44 M

**Comment by g1nt0ki** [comment]
I am rewriting the adapter for more transparency: so moonriver has tvl of 2.4M ? I was breaking my head since grafana said only 1.12M

here is my WIP: https://github.com/DefiLlama/DefiLlama-Adapters/pull/4370 maybe we can collaborate there?

**Comment by g1nt0ki** [comment]
https://stats.fractalprotocol.org/d/-bD2j_g4z/stats?orgId=1

**Comment by g1nt0ki** [comment]
closed in favor of https://github.com/DefiLlama/DefiLlama-Adapters/pull/4370

**Pull request closed without merging**
