### PR TITLE
Adding adapter for Amnis Finance

### PR DESCRIPTION
**Pull request by john2798**
***NOTE***

> - If you would like to add a volume adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a liquidations adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  only if the PR is for listing a new protocol else it can be ignored/replaced with reason/details about the PR
5. For updating listing info It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push package-lock.json file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Token address and ticker if any:
amApt: 0x1::coin::CoinStore<0x111ae3e5bc816a5e63c2da97d0aa3886519e0cd5e4b046659fa35796bd11542a::amapt_token::AmnisApt>
stApt: 0x1::coin::CoinStore<0x111ae3e5bc816a5e63c2da97d0aa3886519e0cd5e4b046659fa35796bd11542a::stapt_token::StakedApt>

##### Github org/user (Optional, if your code is open source, we can track activity)

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/amnis-finance exports TVL: 
        
 
 
    aptos                     10.03 M
    
    total                    10.03 M

**Comment by g1nt0ki** [comment]
@john2798 thanks for the PR but is your project in production? from the UI I am seeing only testnet

**Comment by tony001242** [comment]
Hi @g1nt0ki, we have successfully completed the soft launch and everything is working well on the Aptos mainnet. All data is reported on the mainnet, and the official mainnet version will be launched today. The UI will be updated at the announced time with the community. Please help me to merge this PR to make everything ready at launch time. Thank you

**Comment by john2798** [comment]
@g1nt0ki Mainnet is readly. Please help me to merge this PR. Thank you

**Pull request merged**
