### PR TITLE
kriya clmm tvl

### PR DESCRIPTION
**Pull request by Knight-101**
Hi team,
We want to make a few changes to Kriya's space on Defillama

1) add a new sub-category under Kriya - 'Kriya CLMM'
2) Rename existing sub-category 'Kriya Swap' to - 'Kriya AMM'
3) Rename existing sub-category 'Kriya Earn' to - 'Kriya Strats'
4) Update Kriya Logo on Defillama - This is the updated logo link: https://www.figma.com/design/9WrJBUiYZlcKPqxT23WheJ/Brand-Style-Guide?node-id=530-1065&t=LuEaLDonKxcq1rSj-4
5) Kriya CLMM tvl function integrate

Have updated names, descriptions and app URLs in the below form accordingly

Name:
Kriya

Twitter Link: https://twitter.com/KriyaDEX
List of audit links if any: https://docs.kriya.finance/sdk-smart-contracts-and-security/audit-reports
Website Link: https://kriya.finance/
Kriya : https://app.kriya.finance/
Kriya AMM : https://app.kriya.finance/spot/liquidity
Kriya CLMM : https://app.kriya.finance/spot/liquidity
Kriya Strats : https://app.kriya.finance/strategies

Logo (High resolution, will be shown with rounded borders): Project already added
Current TVL:
Kriya AMM : $30.12M
Kriya CLMM : $6.01M
Kriya Strats : $590.90K

Treasury Addresses (if the protocol has treasury):
Chain: Sui
Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
Short Description (to be shown on DefiLlama):

Here are descriptions we want added / updated
Kriya : 1–stop DeFi protocol on Sui. Offering Swaps, Limit Orders, 1-click leverage lending strategies, Yield Optimiser Vaults and 20x perpetuals
Kriya AMM : Kriya’s native AMM. Supports both stable and constant product curves. One of deepest liquidity source in Kriya’s cross-protocol router
Kriya CLMM : Concentrated Liquidity pools for spot trading and launching new tokens efficiently
Kriya Strats : Vaults that provide retail investors tokenized access to sophisticated DeFi strategies such as leverage lending, reward auto-compounding and CLMM LP management

Token address and ticker if any:
Category (full list at https://defillama.com/categories) *Please choose only one: Yields
Kriya Strats : Yields
Kriya AMM : Dexes
Kriya CLMM : Dexes

Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Implementation Details: Briefly describe how the oracle is integrated into your project:
Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
forkedFrom (Does your project originate from another project):

methodology (what is being counted as tvl, how is tvl being calculated):
Kriya Strats : Calculated by aggregating current token wise asset and liabilities balances of all Kriya Earn vaults
Kriya AMM : Sum of token balances across Kriya’s v2 Liquidity pools
Kriya CLMM : Sum of token balances across Kriya’s v3 Liquidity pools
Kriya : Sum of TVL / Volume across different Kriya products

Github org/user (Optional, if your code is open source, we can track activity): https://github.com/efficacy-finance

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/kriya-clmm exports TVL: 
        
 
 
    sui                       6.03 M
    
    total                    6.03 M

**Comment by g1nt0ki** [comment]
@Knight-101 looks good, thanks for the PR, we will make the changes.

**Comment by adityadw1998** [comment]
Thanks for the quick merge @g1nt0ki , changes reflecting now. Minor error : Logos of sub-categories are updated, but logo of the parent 'Kriya' is still the old one

Screenshot 2024-07-17 at 10 30 25 PM

**Comment by adityadw1998** [comment]
gm @g1nt0ki bumping this up in case you missed^ thanks

**Comment by adityadw1998** [comment]
Seems its done now, reflecting on production, thanks

**Pull request merged**
