### PR TITLE
Add DonaSwap V3

### PR DESCRIPTION
**Pull request by 0xfirechain**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
DONASWAP V3

##### Twitter Link:
https://twitter.com/0xdonaswap

##### Website Link:
https://donaswap.com/

##### Logo (High resolution, will be shown with rounded borders):
https://www.donaswap.com/logo.png

##### Current TVL:
0

##### Chain:
All EVM supported running mainnet & testnet networks

##### Short Description (to be shown on DefiLlama):
DONASWAP is the primary multichain dex for the Firechain Ecosystem which sprouted by the Donaswap Token.

##### Token address and ticker if any:
FLAME (Coming Soon)

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### methodology (what is being counted as tvl, how is tvl being calculated):
V3 Factory address (0x9C3AFDDEa87a726891A44C037242393D524CAcFE) is used to find the LP pairs. TVL is equal to the liquidity on the AMM.

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/donaswap-v3: 
        
 
  
    
    
    Error: Can't get block of chain dogechain
    Truncated error stack:
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/blocks.js:227:31

**Comment by llamatester** [comment]
Error while running adapter at projects/donaswap-v3: 
        
 
  
    
    
    Error: could not coalesce error (error={ "code": -32047, "message": "Invalid eth_getLogs request. 'fromBlock'-'toBlock' range too large. Max range: 800" }, payload={ "id": 12, "jsonrpc": "2.0", "method": "eth_getLogs", "params": [ { "address": "0x9c3afddea87a726891a44c037242393d524cacfe", "fromBlock": "0x11663b5", "toBlock": "0x1166960", "topics": [ "0x783cca1c0412dd0d695e784568c96da2e9c22ff989357a2e8b1d9b2b4e6b7118" ] } ] }, code=UNKNOWN_ERROR, version=6.9.2)
    Truncated error stack:
        at makeError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/ethers/lib.commonjs/utils/errors.js:129:21)

**Comment by g1nt0ki** [comment]
hi @0xfirechain thanks for the PR

it is failing now because we are trying to fetch 3 months worth of logs. I checked a few chains, none of them had any pairs, in these cases, you can set the fromBlock to current, is there any chain with tvl right now?

**Comment by g1nt0ki** [comment]
closing this for now as there was no answer

**Pull request closed without merging**
