### PR TITLE
update the tvl calculation for Joltify rwa adapter

### PR DESCRIPTION
**Pull request by briangarden**
We involve this borrowed amount in the TVL calculation due to the difference between traditional digital lending and RWA lending.

I understand the concept of RWA lending can be quite confusing. To help clarify, I've compared it to digital lending. Hopefully, this side-by-side comparison brings more clarity.
For digital lending, the process typically involves User A depositing 100 worth of tokens and User B depositing 100 worth of tokens into the protocol. Subsequently, User A borrows 80 tokens from User B's deposit. In this scenario, User A can withdraw the borrowed 80 tokens, taking them out of the protocol. Despite this withdrawal, the protocol still retains a Total Value Locked (TVL) of 120, calculated as the sum of User A's remaining 20 tokens and User B's 100 tokens**.

It's important to note that the TVL is not double-counted; it is calculated as 100 (User A's deposit) + 100 (User B's deposit) - 80 (User A's withdrawal) = 120, reflecting the accurate value locked within the protocol after User A's token withdrawal.

In the case of Real-World Asset (RWA) lending, a Special Purpose Vehicle (SPV) entity, let's call it 'C,' utilizes contracts collateralized by assets like bonds or other securities to borrow 100 dollars from User D. In this scenario, the SPV mints a 100 dollar Non-Fungible Token (NFT) backed by real-world assets, and User D deposits 100 worth of USDT/USDC into the protocol. Consequently, User D receives the 100 dollar NFT as proof of ownership, which remains within the protocol, while the SPV takes out the 100 USDT/USDC.

In this scenario, the protocol maintains a TVL of 100, calculated as the sum of the 100 dollar NFT and the 100 USDT/USDC initially deposited by User D, minus the 100 USDT/USDC withdrawn by the SPV. The TVL is not double-counted, as it accurately reflects the stablecoins taken out of the protocol, while the NFT representing the RWA remains locked within.

It's crucial to acknowledge that the collateral's value may fluctuate or even collapse over time, potentially decreasing the corresponding NFT's value. To address this, we will continuously assess and update the NFT's value based on the underlying collateral's performance. For example, in the event of a default, the NFT's value will be adjusted accordingly, reflecting the outcome of legal proceedings and the realization of the underlying RWA's value. Our protocol will dynamically update these valuations to ensure transparency and accurate representation of the locked assets.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/joltify-rwa exports TVL: 
        
 
 
    joltify                   25.39 k
    joltify-borrowed          25.00 k
    borrowed                  25.00 k
    
    total                    25.38 k

**Comment by g1nt0ki** [comment]
I understand what you are say but other rwa lending protocols we have listed do the same thing and we still dont include the borrowed amount as tvl for them.

**Comment by llamatester** [comment]
The adapter at projects/joltify-rwa exports TVL: 
        
 
 
    joltify-borrowed          25.00 k
    borrowed                  25.00 k
    joltify                   294
    
    total                    293.794935

**Comment by briangarden** [comment]
> I understand what you are say but other rwa lending protocols we have listed do the same thing and we still dont include the borrowed amount as tvl for them.

Hey @g1nt0ki , based on your comment, we removed the borrowed assets from the TVL calculation. Instead, we added the TransferOwnership assets to the TVL calculation.

Transfer Ownership is a distinctive feature of the Joltify RWA protocol. This functionality allows any invested user to fully or partially transfer (or trade) their ownership of invested assets based on the underlying asset. This feature effectively creates a secondary market for invested RWA assets.

For example, if a user invests 200 USDC in the pool, they receive an NFT worth 200 USDC. During the interest accrual period, the user can transfer or trade their entire NFT for 200 USDC, or partially transfer/trade it, such as half the NFT for 100 USDC.

In our calculations, we only consider the liquidated/traded portion of the NFT as assets. For instance, if a client trades half of their NFT, we calculate the asset value as 100 USDC. We believe this approach is fair, as it not only reflects market value but also accounts for actual market trading to realize that value.

We kindly request that you incorporate this update into the project. Thank you for your consideration.

**Comment by g1nt0ki** [comment]
hi @briangarden 
what you are saying sounds similar to receipt tokens for lending protocols, like user gets cUSDC when they deposit USDC and they can borrow against/trade that, but since we are already counting underlying USDC as tvl, we dont count cUSDC as part of compound tvl

**Pull request closed without merging**
