### PR TITLE
World Mobile Token

### PR DESCRIPTION
**Pull request by mxdbld**
##### Name (to be shown on DefiLlama): 
World Mobile Token

##### Twitter Link: 
https://twitter.com/wmtoken

##### Website Link: 
https://worldmobiletoken.com

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): 
https://svgshare.com/i/sBA.svg

##### Current TVL: 
15.9M$

##### Chain: 
Cardano

##### Coingecko ID (so your TVL can appear on Coingecko): 
world-mobile-token

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): 
13769

##### Short Description (to be shown on DefiLlama): 
World Mobile Token (WMT) is a cryptocurrency used to power the World Mobile Network, a decentralized mobile network that provides affordable and reliable internet access to remote areas.

##### Token address and ticker if any: 
WMT  https://cexplorer.io/asset/asset1h7jsujzt4s8pup6nrzthr9nhajl0gmwhlzcqw7

##### Category (full list at https://defillama.com/categories) *Please choose only one: 
Services

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Blockfrost

##### methodology (what is being counted as tvl, how is tvl being calculated):
WMT tokens locked in the smart contract script, converted to its ADA price from the order book of Minswap

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/worldmobiletoken exports TVL: 
        
 
 
    cardano                   15.90 M
    
    total                    15.90 M

**Comment by llamatester** [comment]
The adapter at projects/worldmobiletoken exports TVL: 
        
 
 
    cardano                   0
    cardano-staking           16.02 M
    staking                   16.02 M
    
    total                    0

**Comment by g1nt0ki** [comment]
@mxdbld thanks for the PR, this considered staking, so I made a fix

**Comment by mxdbld** [comment]
@g1nt0ki, node operators for the World Mobile blockchain lock their WMT tokens (100k WMT) in exchange of a license to operate. 
I assume this is more in the category of TVL

**Comment by g1nt0ki** [comment]
SOrry, no. It is your own tokens and we count it only under staking: https://docs.llama.fi/list-your-project/what-to-include-as-tvl

**Comment by mxdbld** [comment]
Read the doc but misunderstood it. Noted

**Pull request merged**
