### PR TITLE
Updated MAHA token address, staking contract, ARTH trove manager and added treasury

### PR DESCRIPTION
**Pull request by senamakel**
We recently updated our token address for MAHA, the ARTH trove manager and setup a new contract to represent our treasury.

This PR updates those addresses for the ETH chain.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/mahadao exports TVL: 
        
 
 
    polygon                   0
    ethereum-staking          110.59 k
    ethereum-pool2            120.57 k
    bsc-pool2                 14.41 k
    ethereum                  168.98 k
    staking                   110.59 k
    pool2                     134.97 k
    
    total                    168.98 k

**Comment by llamatester** [comment]
The adapter at projects/mahadao exports TVL: 
        
 
 
    polygon                   0
    ethereum-staking          110.59 k
    ethereum-pool2            120.57 k
    bsc-pool2                 14.41 k
    ethereum                  168.98 k
    staking                   110.59 k
    pool2                     134.97 k
    
    total                    168.98 k

**Comment by llamatester** [comment]
The adapter at projects/raydium.js exports TVL: 
        
 
 
    
    total                    38.39 M

**Comment by llamatester** [comment]
The adapter at projects/mahadao exports TVL: 
        
 
 
    polygon                   0
    ethereum-pool2            123.04 k
    ethereum-staking          114.32 k
    bsc-pool2                 14.39 k
    ethereum                  172.15 k
    pool2                     137.43 k
    staking                   114.32 k
    
    total                    172.15 k

**Comment by llamatester** [comment]
The adapter at projects/raydium.js exports TVL: 
        
 
 
    
    total                    38.43 M

**Comment by llamatester** [comment]
The adapter at projects/mahadao exports TVL: 
        
 
 
    polygon                   0
    ethereum-pool2            123.04 k
    ethereum-staking          114.32 k
    bsc-pool2                 14.39 k
    ethereum                  172.16 k
    pool2                     137.43 k
    staking                   114.32 k
    
    total                    172.16 k

**Comment by g1nt0ki** [comment]
@senamakel I have made some changes here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/5113

we are already tracking the lending component here: https://defillama.com/protocol/mahalend, we will merge that under single listing like sushiswap/uniswap

I have removed uni tvl from pool2 as we can count only the staked tokens/nfts in uni v3 case

**Pull request merged**
