### PR TITLE
Configure external chain deposits for cross-chain Balanced DEX

### PR DESCRIPTION
**Pull request by usr-icon-foundation**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/balanced exports TVL: 
        
 
 
    binance                   0
    avax                      0
    archway                   0
    icon                      0
    
    total                    0

**Comment by usr-icon-foundation** [comment]
It is unclear to me why llamatester is displaying 0 TVL for all chains. Some help and/or guidance would be greatly appreciated here :) Regards

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
please revert formatting changes, makes it harder to see what is changed.

Please move balanced related code to balanced/index.js or balanced/helper.js file, unless other apps on icx rely on this code, feel like it is wrong to put in chain/icx.js

**Comment by usr-icon-foundation** [comment]
Will do! Thanks for chiming in

**Comment by usr-icon-foundation** [comment]
I will redo the formatting and place the code in the right places. Then I will redo the pull request

**Comment by g1nt0ki** [comment]
@usr-icon-foundation thanks :pray:

**Pull request closed without merging**
