### PR TITLE
Add Poison Finance

### PR DESCRIPTION
**Pull request by AidedReda**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/poison-finance exports TVL: 
        
 
 
    arbitrum                  746.89 k
    
    total                    746.89 k

**Comment by realdealshaman** [comment]
@AidedReda Hi there, thank you for submitting the PR. POISON tokens that are locked in your protocol should be exported as Staking TVL, rather than together with regular TVL. Can you please make this update to your code? Once you've made the change, please let us know so we can merge the PR.  

Also, can you add the listing info above: 
Name (to be shown on DefiLlama):
Twitter Link:
List of audit links if any:
Website Link:
etc...
Thanks again

**Comment by llamatester** [comment]
The adapter at projects/poison-finance exports TVL: 
        
 
 
    arbitrum-staking          809.88 k
    arbitrum                  136.15 k
    staking                   809.88 k
    
    total                    136.15 k

**Comment by AidedReda** [comment]
##### Name (to be shown on DefiLlama):
POISON FINANCE 

##### Twitter Link:
https://twitter.com/PoisonFinance

##### List of audit links if any:
https://solidity.finance/audits/PotionVault/

##### Website Link:
https://poison.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://ibb.co/kH2RnkZ

##### Current TVL:
$804,023.16

##### Treasury Addresses (if the protocol has treasury)
None

##### Chain:
Arbitrum ETH

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
https://www.coingecko.com/en/coins/poison-finance

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
https://coinmarketcap.com/currencies/poison/

##### Short Description (to be shown on DefiLlama):

Poison Protocol is a Magic Wand that lets you create Multi Chain Synthetic Potions that track the price of real-world assets. Synthetic Potions are intended to be used as fundamental building blocks in smart contracts, be it a dex or a game, and to bring the world's assets to the blockchain. Serving Stocks, Commodities, and ETFs on Arbitrum, BSC, and ETH 24/7. 

##### Token address and ticker if any:
https://arbiscan.io/token/0x31C91D8Fb96BfF40955DD2dbc909B36E8b104Dde

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Synthetics

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink, Pyth

##### forkedFrom (Does your project originate from another project):
No

##### methodology (what is being counted as tvl, how is tvl being calculated):
Balances of the stablecoins locked in the vault as collateral plus the balance of poison in the ipoison contract.

**Comment by AidedReda** [comment]
@realdealshaman Thanks. Commented all the info above. Broke down the TVL & Staking TVL.

**Pull request merged**
