### PR TITLE
Add SKALE IMA Bridge (Native) to SKALE TVL

### PR DESCRIPTION
**Pull request by TheGreatAxios**
Allow edits by maintainers: Yes

Goal:
- Ensure that SKALE has 100% of TVL being tracked since this is the canonical bridge
- List SKALE IMA Bridge under bridges section (will make a separate PR in bridges-server)

##### Name (to be shown on DefiLlama):
SKALE Network

##### Twitter Link:
https://x.com/SkaleNetwork

##### List of audit links if any:
https://github.com/skalenetwork/IMA/blob/develop/audits/SKALE_Audit_Bramah.pdf
https://github.com/solidified-platform/audits/blob/master/Audit%20Report%20-%20SKALE%20Self-Recharging%20Wallets.pdf
https://github.com/skalenetwork/ima-c4-audit

##### Website Link:

https://skale.space

##### Logo (High resolution, will be shown with rounded borders):

skale_token_b
skale_token_b

Have attached both SVG & PNG since there was no explicit ask. They are the same logo.

##### Current TVL:

~2.27M as per running the script locally 

##### Chain:

This is for the entire SKALE Network Protocol. It is made up of multiple SKALE Chains. It can be linked to the SKALE Europa Hub since the majority of this liquidity is for the SKALE Europa Hub which is listed on DL already.

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

Chain: https://www.coingecko.com/en/chains/skale -- note I went through the API above and did not see an explicit id for the chain. SKALE Tokens are tagged there.

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

skale-network

##### Short Description (to be shown on DefiLlama):

SKALE is a network of Layer-1 blockchains that boast zero gas fees.
SKALE Europa is the home to DeFi and so has the highest TVL, but the bridge link should be for all SKALE Chains (not just Europa).

##### Token address and ticker if any:

N/A

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Bridge

##### forkedFrom (Does your project originate from another project):

N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):

TVL is being calculated by looking up locked liquidity in the DepositBoxERC20 on the Ethereum Mainnet. This is because the TVL for this is explicit to the Native IMA Bridge which is going to be lower than the aggregate TVL for the network as a whole which can include 3rd party bridges.

The contracts used are SKALE Networks DepositBoxETH and DepositBoxERC20 which track native ETH deposits and ERC-20 deposits respectivley.

##### Github org/user (Optional, if your code is open source, we can track activity):

Organization -> [skalenetwork](https://github.com/skalenetwork)
User -> [TheGreatAxios](https://github.com/TheGreatAxios)

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/skale exports TVL: 
        
 
 
    skale                     2.17 M
    
    total                    2.17 M

**Comment by TheGreatAxios** [comment]
> The adapter at projects/skale exports TVL:
> 
> ```
> skale                     2.17 M
> 
> total                    2.17 M 
> ```

https://app.warp.dev/block/zSr7bpFk7vZa6agV72q87r

**Comment by g1nt0ki** [comment]
thanks for the PR, for bridge, we count tokens at the source chain

**Comment by llamatester** [comment]
The adapter at projects/skale exports TVL: 
        
 
 
    ethereum                  2.28 M
    
    total                    2.28 M

**Pull request merged**
