### PR TITLE
update(saddle): Additional Chains and Pools and include $veSDL

### PR DESCRIPTION
**Pull request by westonnelson**
Updating Saddle Finance integration with DeFi Llama:

Twitter Link: https://twitter.com/saddlefinance
List of audit links:
Certik: https://github.com/saddle-finance/saddle-audits/blob/master/10-29-2020_Certik.pdf
OpenZeppelin: https://blog.openzeppelin.com/saddle-contracts-audit/
Quantstamp: https://github.com/saddle-finance/saddle-audits/blob/master/12-09-2020_Quantstamp.pdf

Website Link: https://saddle.finance/

Chains: Ethereum, Arbitrum, Evmos, Optimism, Fantom
Coingecko ID: saddle-finance
Short Description: Saddle is a decentralized automated market maker on multiple blockchains, optimized for pegged value crypto assets such as stablecoins and wBTC.
Token address and ticker if any:
Ethereum: 0xf1Dc500FdE233A4055e25e5BbF516372BC4F6871 - Ticker $SDL
Etherscan: https://etherscan.io/token/0xf1dc500fde233a4055e25e5bbf516372bc4f6871
Category: DEXs

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/saddle: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:219:11

**Comment by westonnelson** [comment]
> Error while running adapter at projects/saddle:
> 
> ```
> Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
> Truncated error stack:
> 
>     at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:219:11
> ```

Do you know if it is something I removed somehow? I don't recall changing this...

**Comment by westonnelson** [comment]
> > Error while running adapter at projects/saddle:
> > ```
> > Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
> > Truncated error stack:
> > 
> >     at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:219:11
> > ```
> 
> Do you know if it is something I removed somehow? I don't recall changing this...

>>>Have added TVL Exports for both files. I believe this is what you are referring to; but not sure how it would have been removed, thanks for your help!

**Comment by llamatester** [comment]
Error while running adapter at projects/saddle: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:219:11

**Pull request closed without merging**
