### PR TITLE
Add Atlendis Adapter

### PR DESCRIPTION
**Pull request by smol-ninja**
Twitter Link: 
https://twitter.com/AtlendisLabs

List of audit links if any: 
https://github.com/runtimeverification/publications/blob/main/reports/smart-contracts/atlendis-audit-report.pdf

Website Link: 
https://app.atlendis.io/

Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): 
jellyfiemoji2

Current TVL: 
$1.348 M

Chain: 
Polygon

Coingecko ID (so your TVL can appear on Coingecko): NA

Coinmarketcap ID (so your TVL can appear on Coinmarketcap): NA

Short Description (to be shown on DefiLlama): 
Atlendis is a capital-efficient DeFi lending protocol that enables crypto loans without collateral

Token address and ticker if any: NA

Category (full list at https://defillama.com/categories) *Please choose only one: 
Lending

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

forkedFrom (Does your project originate from another project):

methodology (what is being counted as tvl, how is tvl being calculated): I fetched pools from subgraphs and then calculated TVL from the response

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/atlendis exports TVL: 
        
 
 
    polygon                   1.34 M
    
    total                    1.34 M

**Comment by 0xngmi** [comment]
borrowed money should be under the `borrowed` function

**Comment by smol-ninja** [comment]
☑️ Added borrowed value under `borrowed` function. Also note that the TVL is calculated by summing up the following values:
1. normalizedAvailableAmount: available amount to borrow (total lent - borrowed amount)
2. normalizedBorrowedAmount: borrowed amount
3. adjustedPendingAmount: pending loan amount to be considered in the next cycle

**Comment by g1nt0ki** [comment]
@smol-ninja we dont include borrowed amount in tvl since it is aready included as a separate export

**Comment by smol-ninja** [comment]
Of course. I am not including borrowed amount into TVL. 

Let me explain with an example, if a user lends $100 through Atlendis (TVL = $100), and $70 is the borrowed money, then the subgraph will result $30 as the `normalizedAvailableAmount` value; and `normalizedBorrowedAmount` value would be $70. So you get the original TVL by summing up the above two values.. 

That's why I am adding `normalizedAvailableAmount` & `normalizedAvailableAmount` in the TVL but it does mean that I am including borrowed amount as well otherwise it will be double counted.

**Comment by g1nt0ki** [comment]
hi @smol-ninja, but in in your example, only $30 should be shown as TVL, and borrowed would show $70. This is how we do for lending protocols, TVL includes the tokens locked in the protocol that is not lent out and also the amount of collateral from the borrowers if any. Example Maple: https://defillama.com/protocol/maple

**Comment by llamatester** [comment]
The adapter at projects/atlendis exports TVL: 
        
 
 
    polygon-borrowed          1.10 M
    polygon                   241.35 k
    borrowed                  1.10 M
    
    total                    241.35 k

**Comment by smol-ninja** [comment]
@g1nt0ki thanks for clarification. I was under the assumption that TVL (for lending protocols) includes how much is lent out to the protocol. Fixed it.

**Pull request merged**
