### PR TITLE
add NerveNetwork Bridge

### PR DESCRIPTION
**Pull request by MIMIEYES**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/nervenetworkbridge exports TVL: 
        
 
 
    ethpow                    0
    polygon                   47.42 k
    tron                      14.41 k
    metis                     0
    okexchain                 111.99 k
    iotex                     36.866993784
    avax                      83.96 k
    fantom                    7.00 k
    arbitrum                  407.79407269074
    harmony                   4.40 k
    heco                      9.82 k
    kava                      0.010490039999999999
    bsc                       714.75 k
    kcc                       5.18 k
    smartbch                  3.95 k
    ethereum                  376.97 k
    cronos                    10.1471256052815
    klaytn                    0.179300709
    optimism                  0.00169074
    
    total                    1.38 M

**Comment by Nemusonaneko** [comment]
pls revert ur changes in pull_request_template.md

**Comment by llamatester** [comment]
The adapter at projects/nervenetworkbridge exports TVL: 
        
 
 
    metis                     0
    ethpow                    0
    tron                      14.45 k
    harmony                   4.48 k
    kava                      0.010933713999999999
    fantom                    7.12 k
    arbitrum                  407.675805302405
    avax                      84.21 k
    bsc                       716.06 k
    optimism                  0.0017098499999999997
    iotex                     38.431431634400006
    cronos                    10.141544507282637
    polygon                   47.45 k
    okexchain                 112.00 k
    heco                      10.59 k
    smartbch                  4.16 k
    ethereum                  378.39 k
    klaytn                    0.163128903
    kcc                       5.25 k
    
    total                    1.38 M

**Comment by llamatester** [comment]
Error while running adapter at projects/nervenetworkbridge: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'getBalance')
    Truncated error stack:
        at Object.<anonymous> (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/eth/index.js:76:98)
        at new Promise (<anonymous>)
        at Array.map (<anonymous>)

**Pull request merged**
