### PR TITLE
Y2k: update adapter to fetch only available vaults at the timestamp

### PR DESCRIPTION
**Pull request by icyage**
##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/y2k-v2 exports TVL: 
        
 
 
    arbitrum                  374.89 k
    
    total                    374.89 k

**Comment by g1nt0ki** [comment]
@icyage unsure why this PR is made, correct block info is automatically injected through api object

**Comment by g1nt0ki** [comment]
okay, so I found the issue, it was pool2, the token was created on dec 20, so refill before that date failed, I have disabled pool2 and am refilling now: https://arbiscan.io/address/0x569061e2d807881f4a33e1cbe1063bc614cb75a4

like we use cache and filter out logs beyond given to block: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/helper/cache/getLogs.js#L36

**Comment by g1nt0ki** [comment]
*I have refilled till Oct 30, 2022. it should reflect in the UI in about 1-2 hours

**Pull request closed without merging**
