### PR TITLE
Added ZERO staking and ZERO/ETH LP staking tvl for zerolend

### PR DESCRIPTION
**Pull request by deadshotryker**
PFA. the contracts for zerolend lp and zero single token staking

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at : 
        
 
  > Please revert changes to package.json / package-lock.json

**Comment by llamatester** [comment]
The adapter at projects/zerolend exports TVL: 
        
 
 
    borrowed                  347.67 M
    linea-borrowed            289.59 M
    linea                     228.41 M
    blast-borrowed            22.97 M
    era-borrowed              17.23 M
    blast                     14.31 M
    era                       12.03 M
    ethereum-borrowed         9.62 M
    ethereum                  8.27 M
    manta-borrowed            8.19 M
    manta                     5.24 M
    linea-staking             2.93 M
    staking                   2.93 M
    linea-pool2               153.57 k
    pool2                     153.57 k
    xlayer-borrowed           66.58 k
    xlayer                    52.39 k
    
    total                    268.32 M

**Comment by llamatester** [comment]
The adapter at projects/treasury/zerolend.js exports TVL: 
        
 
 
    linea-ownTokens           8.45 M
    ownTokens                 8.45 M
    linea                     0
    
    total                    0

**Comment by g1nt0ki** [comment]
thanks for the update

**Pull request merged**
