### PR TITLE
Add Areon Apps TVL

### PR DESCRIPTION
**Pull request by emrahsky**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Areon Apps

##### Twitter Link:
https://twitter.com/areonnetwork

##### Website Link:
https://apps.areon.network

##### Logo (High resolution, will be shown with rounded borders):
https://cdn.areon.network/uploads/areon-black.png

##### Current TVL:
39604056

##### Chain:
Areon Network

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
https://www.coingecko.com/en/coins/areon-network

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
23262

##### Short Description (to be shown on DefiLlama):
"Areon Apps" is a platform that allows you to perform operations such as staking, validation and delegation on the Areon Network Mainnet. Using Areon's decentralized data storage protocol, you can contribute to the network and increase the security of the network through Areon Apps.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
[Liquid Staking](https://defillama.com/protocols/Liquid%20Staking)

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
https://docs.areon.network/

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/areon-network

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/areon-apps: 
        
 
  
    
    
    Error: 
        Unknown chain(s): areon
        Note: if you think that the chain is correct but missing from our list, please add it to 'projects/helper/chains.json' file
        
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:138:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

**Comment by llamatester** [comment]
The adapter at projects/areon-apps exports TVL: 
        
 
 
    area                      0
    
    total                    0

**Comment by g1nt0ki** [comment]
hi, this sounds like native chain staking, atm we are not listing these projects

**Comment by g1nt0ki** [comment]
more info: https://github.com/DefiLlama/DefiLlama-Adapters/discussions/435

**Comment by emrahsky** [comment]
> hi, this sounds like native chain staking, atm we are not listing these projects

Hi, In fact, both local chain and offchain are available, is the offchain, that is, the centralized staking structure suitable for you?

**Comment by g1nt0ki** [comment]
what do you mean by off chain? as a rule, we dont count chain staking as tvl for any chains, like neither for ethereum/solana nor for cosmos like

**Comment by emrahsky** [comment]
> what do you mean by off chain? as a rule, we dont count chain staking as tvl for any chains, like neither for ethereum/solana nor for cosmos like

actually when I say offchain I mean that this staking is done centrally, so it's not chain staking

**Comment by g1nt0ki** [comment]
if areon team is maintaining it, isnt it the same as chain staking?

**Comment by emrahsky** [comment]
actually both are available, we have our own created staking system and it is under the management of this team, the other staking method is the familiar delegated staking system. as far as I understand you cannot add the delegated staking system, can you add the staking system whose management is in the team?

**Comment by g1nt0ki** [comment]
so, if it had been done by an independent team, we could have listed it under "staking pool" (still wont show up as chain tvl) but dont think that applies here.

**Comment by emrahsky** [comment]
> so, if it had been done by an independent team, we could have listed it under "staking pool" (still wont show up as chain tvl) but dont think that applies here.

Then can't we add the part that the team manages? Can you guide me on this? We can characterize it as a staking pool.

**Comment by g1nt0ki** [comment]
but the team here is not independent of areon

**Comment by llamatester** [comment]
Error while running adapter at projects/areon-swap: 
        
 
  
    
    
    Error: Failed to call: uint256:allPairsLength target: 0x4df039804873717bff7d03694fb941cf0469b79e on chain: [astar] rpc: https://evm.astar.network, https://astar.api.onfinality.io/public, https://astar.public.blastapi.io, https://1rpc.io/astr, https://astar-rpc.dwellir.com  call reverted, reason: fragment.format is not a function

**Comment by llamatester** [comment]
The adapter at projects/areon-swap exports TVL: 
        
 
 
    area                      17
    
    total                    17.3084272538556

**Comment by llamatester** [comment]
The adapter at projects/areon-apps exports TVL: 
        
 
 
    area                      0
    
    total                    0

**Comment by emrahsky** [comment]
> The adapter at projects/areon-apps exports TVL:
> 
> ```
> area                      0
> 
> total                    0 
> ```

Ekran Resmi 2024-04-15 17 00 05


Why is the liquidity in the pool not visible? Or is it just the volume of trades?

**Comment by llamatester** [comment]
The adapter at projects/areon-swap exports TVL: 
        
 
 
    area                      16
    
    total                    16.044324786596565

**Comment by g1nt0ki** [comment]
@emrahsky I have removed the stake tvl andfixed the issue with pricing area token

**Comment by emrahsky** [comment]
> @emrahsky I have removed the stake tvl andfixed the issue with pricing area token

thanks but why are liquidities not included in tvl?

**Comment by g1nt0ki** [comment]
> > @emrahsky I have removed the stake tvl andfixed the issue with pricing area token
> 
> thanks but why are liquidities not included in tvl?

we are not tracking staking as tvl for any other chain

**Comment by emrahsky** [comment]
> > > @emrahsky I have removed the stake tvl andfixed the issue with pricing area token
> > 
> > 
> > thanks but why are liquidities not included in tvl?
> 
> we are not tracking staking as tvl for any other chain

yes we agree on that, I'm talking about the pool liquidities in hyperswap. doesn't defilama take these into account? does it only take volume into account?

**Comment by g1nt0ki** [comment]
it is listed with tvl here: https://defillama.com/protocol/hyperswap#information

**Pull request merged**
