### PR TITLE
theo adapter

### PR DESCRIPTION
**Pull request by rohancherukuri14**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Theo Network

##### Twitter Link:

https://x.com/TheoNetwork_

##### List of audit links if any:

https://github.com/theo-network/theo/blob/main/contracts/Vault/audit.md
https://github.com/theo-network/theo/blob/main/contracts/Vault/audit_2.md

##### Website Link:
theo.xyz

##### Logo (High resolution, will be shown with rounded borders):

image

##### Current TVL:
27.88M

##### Chain:

Ethereum
Arbitrum
Base

##### Short Description (to be shown on DefiLlama):

Theo Network is a set of onchain contracts and off-chain systems built to capture onchain funding rates at scale.
##### Token address and ticker if any:

No network token as of yet

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Basis Trading

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
N/A
##### Implementation Details: Briefly describe how the oracle is integrated into your project:
N/A
##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
N/A

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):

Our tvl is split across AAVE, hyperliquid, and multisigs on all chains, so we calculate TVL each round by looking at our total amount supplied to aave, our margin on hyperliquid, and the balances of our multisigs. Our automated system than rolls the round on each contract with these new values, and the defillama adapter is checking the balances on these contracts (which come from the round roll values)

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/theo-network exports TVL: 
        
 
 
    ethereum                  19.47 M
    arbitrum                  1.31 M
    base                      0
    
    total                    20.78 M

**Comment by llamabutler** [comment]
Error while running adapter at projects/theo-network: 
        
 
  
    
    
    Error: Failed to fetch vault info
    Truncated error stack:
    
        at fetchVaultInfo (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/theo-network/index.js:10:15)
        at async tvlForChain (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/theo-network/index.js:15:21)
        at async arb_tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/theo-network/index.js:33:3)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:173:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:216:3

**Comment by llamabutler** [comment]
The adapter at projects/theo-network exports TVL: 
        
 
 
    ethereum                  19.82 M
    arbitrum                  1.31 M
    base                      0
    
    total                    21.13 M

**Comment by llamabutler** [comment]
The adapter at projects/theo-network exports TVL: 
        
 
 
    ethereum                  19.85 M
    arbitrum                  1.31 M
    base                      0
    
    total                    21.16 M

**Comment by llamabutler** [comment]
The adapter at projects/theo-network exports TVL: 
        
 
 
    ethereum                  26.54 M
    arbitrum                  1.34 M
    base                      0
    
    total                    27.88 M

**Comment by g1nt0ki** [comment]
thanks for the PR, I have refactored and merged it

**Comment by g1nt0ki** [comment]
here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/4f44606a0fa1f10c5bfdc0ce92d073828d30cc38

**Comment by rohancherukuri14** [comment]
Thank you!

**Pull request closed without merging**
