### PR TITLE
add ASAGold

### PR DESCRIPTION
**Pull request by scholtz**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
ASA.Gold

##### Twitter Link:
https://twitter.com/biatecgroup

##### List of audit links if any:
https://www.asa.gold/proof-of-reserve

##### Website Link:
https://www.asa.gold

##### Logo (High resolution, will be shown with rounded borders):
https://www.asa.gold/images/logo.png

##### Current TVL:
$18000

##### Treasury Addresses (if the protocol has treasury)
AC5MB73BJFJKCVDOVJWG6QSUVTGMPL2UUYHGXEG6CQWI5XQ4OAHVZQ4Z6U

##### Chain:
Algorand

##### Short Description (to be shown on DefiLlama):
Tokenized gold token with publicly auditable gold reserves. We publish the full composition of our reserves and provide you with the onchain eshop.

##### Token address and ticker if any:
https://allo.info/asset/1241944285/token

##### Category (full list at https://defillama.com/categories) *Please choose only one:
RWA

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
MiCA whitepaper: https://www.asa.gold/gold.pdf

##### forkedFrom (Does your project originate from another project):
This is original project.

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is all tokens outside the reserves account.
One token represents one gram of gold.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/scholtz/gold-asa-frontend
https://github.com/scholtz/AsaGoldBff
https://github.com/scholtz/AsaGoldRepository

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/asa-gold exports TVL: 
        
 
 
    algorand                  11.52 k
    
    total                    11.52 k

**Comment by scholtz** [comment]
https://github.com/DefiLlama/defillama-server/pull/7201/files

**Comment by scholtz** [comment]
@llamatester exact current calculation is:

155,484 gold grams in reserves, 155,000 grams minted (out of the reserves account) - https://www.asa.gold/proof-of-reserve

current gold price is 74,24 USD/Gram = $ 11507,2 

TVL at https://vestige.fi/asset/1241944285 (18k) is double counted with the other assets which are locked at the AMMs

**Comment by g1nt0ki** [comment]
thanks for the PR

**Pull request merged**
