### PR TITLE
add jbtc

### PR DESCRIPTION
**Pull request by nexeranet**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
jBTC

##### Website Link:
https://jettonbtc.com
https://jettonbitcoin.com

##### Logo (High resolution, will be shown with rounded borders):
https://cdn.jettonbtc.com/jBTC.png

##### Chain:
TON Blockchain (The Open Network)

##### Short Description (to be shown on DefiLlama):
BTC stored on the Bitcoin network and mirrored on the TON network.

##### Token address and ticker if any:
BTC address: bc1qmukuv7j57umsd5tgg9fw88eqap57rzphkfckyp
TON address: EQCbkRdpnrWZfm07dP5n_wjGx6llNkHNIdmZ-gpIQcDP-J-5
ticker - jBTC

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Bridge

##### methodology (what is being counted as tvl, how is tvl being calculated):
Total value of BTC locked on BTC network considered as TVL.

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/jbtc exports TVL: 
        
 
 
    ton                       0
    
    total                    0.29525975351999995

**Comment by llamatester** [comment]
The adapter at projects/jbtc exports TVL: 
        
 
 
    ton                       0
    
    total                    0.29525975351999995

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
I am guessing that this is the same team as this? please merge the adapter and make a single listing/PR https://github.com/DefiLlama/DefiLlama-Adapters/pull/12597

Also, please count tvl on the source chain, this way, our users can easily verify it

**Comment by nexeranet** [comment]
Hi, How can I  add this bridge from the Bitcoin network? How can I show tvl of the specific addresses in the Bitcoin network?

**Comment by g1nt0ki** [comment]
you can do something like this: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/nexusbtc/index.js#L9

**Comment by nexeranet** [comment]
hi I fix the jbtc adapter with your example

**Comment by g1nt0ki** [comment]
@nexeranet looks good, can you include jETH part as well here, we will make a single listing

**Pull request merged**
