### PR TITLE
[Fantom] - FDoge Finance Adapter Request

### PR DESCRIPTION
**Pull request by FdogeFinance**
##### Token address and ticker if any: 
FDOGE: 0xEb0a2D1b1a33D95204af5d00f65FD9e349419878
SDOGE: 0xBda29437C8e5dC8BF6a2305D442A3742da7FB033
BDOGE: 0xD5A64D724cfE2B1D83313aC6768a589609c19379

### CODE REVIEW

**Comment by Nemusonaneko** [comment]
If this was a Tomb Fork you could use the our Tomb fork helper here:
https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/helper/tomb.js

**Comment by FdogeFinance** [comment]
> If this was a Tomb Fork you could use the our Tomb fork helper here: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/helper/tomb.js

We have submitted the SDK file above with the Tomb fork helper code inside

**Comment by Nemusonaneko** [comment]
Simplified adapter:
https://github.com/DefiLlama/DefiLlama-Adapters/commit/684f6966e2f6ab8f2af8d50315d65a05e04258fd

**Comment by FdogeFinance** [comment]
Twitter Link: https://twitter.com/FDogefinance
List of audit links if any:
Website Link: https://fdoge.finance/
Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): https://drive.google.com/file/d/1QhIdgpk07eA7jg-LU6vIJudT0W8v1jtM/view?usp=sharing
Current TVL: $944,890
Chain: Fantom Opera Chain
Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
Short Description (to be shown on DefiLlama): FDoge Finance is a combination of algorithmics stablecoin on Fantom Opera network and meme token favored by Shiba Inus worldwide. FDoge’s token, FDOGE, aims to be the backbone, main medium of exchange and main source of liquidity for the Fantom network and be frequent owned by Fantom users and Doge lovers
Token address and ticker if any:
FDOGE: 0xEb0a2D1b1a33D95204af5d00f65FD9e349419878


Category (Yield/Dexes/Lending/Minting/Assets/Insurance/Options/Indexes/Staking) *Please choose only one: Yield
Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
forkedFrom (Does your project originate from another project): forkedFrom Tomb Finance
methodology (what is being counted as tvl, how is tvl being calculated): Total value in USD of all tokens deposited across all pools/farms with price data collected from Spookyswap.finance

**Pull request closed without merging**
