### PR TITLE
feat: Add new supported chains/pools for xy-finance

### PR DESCRIPTION
**Pull request by cy-phiz**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/xy-finance exports TVL: 
        
 
 
    moonriver                 845.711296322754
    thundercore               33.18 k
    kcc                       43.06 k
    polygon                   447.57 k
    klaytn                    87.55 k
    era                       550.22 k
    arbitrum                  186.67 k
    base                      337.2871749386172
    fantom                    0
    polygon_zkevm             204.60 k
    avax                      115.31 k
    bsc                       158.42 k
    optimism                  384.70 k
    linea                     503.56 k
    ethereum                  315.16 k
    wemix                     0
    astar                     21.43 k
    cronos                    185.32 k
    
    total                    3.24 M

**Comment by llamatester** [comment]
Error while running adapter at projects/xy-finance: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    Truncated error stack:
    
        at normalizeAddress (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/tokenMapping.js:104:18)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/unwrapLPs.js:728:54
        at Array.map (<anonymous>)
        at sumTokens2 (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/unwrapLPs.js:728:37)
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/xy-finance/index.js:357:14)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:29)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:136:29
        at Array.map (<anonymous>)

**Comment by llamatester** [comment]
The adapter at projects/xy-finance exports TVL: 
        
 
 
    avax                      117.68 k
    bsc                       134.79 k
    moonriver                 845.977931619969
    optimism                  369.03 k
    klaytn                    86.94 k
    kcc                       43.07 k
    base                      326.5138307668806
    thundercore               33.18 k
    era                       654.55 k
    linea                     525.08 k
    ethereum                  325.49 k
    polygon                   444.96 k
    wemix                     0
    arbitrum                  94.92 k
    astar                     21.41 k
    polygon_zkevm             195.89 k
    fantom                    0
    cronos                    197.23 k
    
    total                    3.25 M

**Comment by g1nt0ki** [comment]
thanks for the PR, I have merged it here without duplicate code: https://github.com/DefiLlama/DefiLlama-Adapters/pull/7315

**Comment by cy-phiz** [comment]
> thanks for the PR, I have merged it here without duplicate code: #7315

thanks, mate!

**Pull request closed without merging**
