### PR TITLE
Added NPM token address

### PR DESCRIPTION
**Pull request by flashburst**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
Neptune Mutual

##### Twitter Link:
https://twitter.com/neptunemutual

##### List of audit links if any:
https://neptunemutual.com/security/

##### Website Link:
https://neptunemutual.com/

##### Logo (High resolution, will be shown with rounded borders):
https://neptunemutual.com/brand-assets/Neptune%20Mutual%20Icon.svg

##### Current TVL:
1.25 M

##### Treasury Addresses (if the protocol has treasury)
Arbitrum - 0x808ca06eec8d8645386be4293a7f4428d4994f5b

##### Chain:
Ethereum
Arbitrum One
BNB Smart Chain

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
neptune-mutual

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
22625

##### Short Description (to be shown on DefiLlama):
Neptune Mutual follows a parametric insurance model, meaning it provides payout on the basis of parameters instead of individual claim assessments. Upon the resolution of an incident, all the policyholders of the affected protocol will receive the payouts. Neptune Mutual eliminates individual claim assessments which makes policy easy to claim, faster, and much more reliable.

##### Token address and ticker if any:
Arbitrum / BSC / Ethereum - 0x57f12fe6a4e5fe819eec699fadf9db2d06606bb4
NPM

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Insurance

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/neptune-mutual-blue

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/neptune-mutual exports TVL: 
        
 
 
    bsc                       50.08 k
    arbitrum                  968.14 k
    ethereum                  229.31 k
    
    total                    1.25 M

**Comment by g1nt0ki** [comment]
@flashburst thanks for the PR, but we cant count project treasury as tvl, we can count it under treasury metric though: can you create a file for your project here: https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/projects/treasury ?

**Comment by llamatester** [comment]
The adapter at projects/neptune-mutual exports TVL: 
        
 
 
    arbitrum                  361.77 k
    bsc                       50.07 k
    ethereum                  229.27 k
    
    total                    641.11 k

**Comment by llamatester** [comment]
The adapter at projects/treasury/neptune-mutual.js exports TVL: 
        
 
 
    arbitrum-ownTokens        579.80 k
    arbitrum                  7.13 k
    ownTokens                 579.80 k
    
    total                    7.13 k

**Comment by llamatester** [comment]
The adapter at projects/treasury/neptune-mutual.js exports TVL: 
        
 
 
    arbitrum-ownTokens        583.58 k
    arbitrum                  7.14 k
    ownTokens                 583.58 k
    
    total                    7.14 k

**Pull request merged**
